apache/datafusion

Cargo.toml, datafusion-cli/Cargo.lock, datafusion/sql/src/expr/mod.rs, datafusion/sql/src/planner.rs, datafusion/sql/src/relation/mod.rs, datafusion/sql/src/statement.rs, datafusion/sql/src/unparser/ast.rs, datafusion/sql/src/unparser/dialect.rs, datafusion/sql/src/unparser/expr.rs, datafusion/sql/src/unparser/plan.rs, datafusion/sql/src/utils.rs, datafusion/sqllogictest/test_files/expr.slt, datafusion/sqllogictest/test_files/information_schema.slt
NA
Support latest features of `sqlparser-rs`.
Uprev `sqlparser-rs` to v0.50.0
No new tests needed AFAIK.
Some new SQL syntax supported.
=> Update to `sqlparser-rs` v0.50.0

datafusion/expr/src/logical_plan/builder.rs, datafusion/physical-plan/src/aggregates/mod.rs, datafusion/physical-plan/src/aggregates/order/full.rs, datafusion/physical-plan/src/aggregates/order/mod.rs, datafusion/physical-plan/src/aggregates/order/partial.rs, datafusion/physical-plan/src/filter.rs
=> Minor: make some physical-plan properties public

datafusion-examples/examples/catalog.rs
catlist rename to cataloglist, listdir  rename to direntries
=> chore: improve variable naming conventions

datafusion/physical-expr/src/expressions/binary.rs, datafusion/sqllogictest/test_files/regexp.slt
Closes #11623
For regex match operations, handle NULL input, such as
select v1 ~ null from t; --- described in #11623
=> Fix: handle NULL input for regex match operations

datafusion/core/src/dataframe/mod.rs, datafusion/functions-window/src/row_number.rs, datafusion/proto/tests/cases/roundtrip_logical_plan.rs
N/A
Fix logical conflict between https://github.com/apache/datafusion/pull/12030 and https://github.com/apache/datafusion/pull/12000
1. Update include
2. fix signature of row_number expr_fn to not take arguments
Yes
=> Fix compilation, change row_number() expr_fn to 0 args

datafusion-cli/Dockerfile
Closes #.
Remove the WARNING log when build `datafusion-cli`
> 1 warning found (use docker --debug to expand):
> - FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 18)
Fix syntax in `datafusion-cli/Dockerfile`
Yes.
No.
=> Minor: Remove warning when building `datafusion-cli` from `Dockerfile`

datafusion/expr/src/logical_plan/builder.rs
Closes #12020
A getter method seems to be the preferred way over making the internal struct public
=> Minor: add getter method for LogicalPlanBuilder.plan

datafusion/expr/src/expr_schema.rs, datafusion/expr/src/type_coercion/functions.rs, datafusion/expr/src/udwf.rs, datafusion/sqllogictest/test_files/window.slt
Closes #.
We haven't add signature check for window udf, so we didn't get the expected error if the arguments failed to match the signature
=> Window UDF signature check

datafusion/expr/src/type_coercion/functions.rs, datafusion/functions-nested/src/range.rs, datafusion/sqllogictest/test_files/array.slt
Closes #11922.
`generate_series` function does not accept string arguments. 
However, the as-is test provide string  arguments.
I think it would be better if the type signature of `generate_series` was changed.
https://github.com/apache/datafusion/blob/main/datafusion/functions-nested/src/range.rs#L129
Only sqllogictest
Yes.
No.
=> Fix: generate_series function support string type

datafusion/expr/src/utils.rs, datafusion/sqllogictest/test_files/joins.slt
Closes #12054.
Our downstream tests started failing after #11681. In` calc_func_dependencies_for_project()`, the projection length is no longer taken from the expression length. Instead, wildcard expressions are now counted based on the number of fields in the wildcard schema. The problem occurs when the wildcard expression has a table reference, but the wildcard schema is built on multiple tables.
This PR filters the wildcard schema according to the table reference of the wildcard expression.
Yes, a minimal example of our failing test has been added to `joins.slt`.
=> Fix: Remove Unrelated Fields When Expanding Wildcards in Functional Dependency Projections

datafusion-cli/Cargo.toml, datafusion/catalog/Cargo.toml
Update async-trait version in CLI and catalog crates and pin to the version defined in the root Cargo file where possible.
=> Update async-trait in CLI and catalog crates

datafusion/expr-common/src/accumulator.rs
=> Minor: polish `Accumulator::state` docs

datafusion/expr/src/expr_rewriter/mod.rs, datafusion/expr/src/logical_plan/builder.rs, datafusion/optimizer/src/analyzer/type_coercion.rs, datafusion/optimizer/src/eliminate_nested_union.rs, datafusion/optimizer/src/eliminate_one_union.rs
N/A
In `coerce_plan_expr_for_schema`, we have clones of expressions and the logical plan, which should be avoided.
Yes. `coerce_plan_expr_for_schema` is a public API whose parameter type has changed, but it is likely only used internally for Unions.
=> Minor: remove clones in `coerce_plan_expr_for_schema`

datafusion-cli/Cargo.lock, datafusion/functions-aggregate/Cargo.toml, datafusion/functions-aggregate/src/min_max.rs, datafusion/sqllogictest/test_files/aggregate.slt, datafusion/sqllogictest/test_files/arrow_typeof.slt
Closes #11764.
Float16 type support is missing in min/max groups and regular accumulators.
Float16 type added to min/max accumulators.
minor: uncommented `arrow_cast`s sqllogictests for float16
Added sqllogictests
=> fix: support min/max for Float16 type

datafusion/sqllogictest/src/engines/datafusion_engine/normalize.rs, datafusion/sqllogictest/test_files/arrow_typeof.slt
Part of https://github.com/apache/datafusion/issues/11752
Utf8View is a text column type and we should treat it as such in sqlogictests
Update sqllogictest to treat Utf8View like text
This is a small piece of https://github.com/apache/datafusion/pull/11862 from @XiangpengHao that can be merged separately
Yes, only test in the harness
No, this is a developer tool
=> Minor: update sqllogictest to treat Utf8View as text

datafusion/sql/src/planner.rs, datafusion/sql/src/relation/join.rs, datafusion/sql/src/relation/mod.rs, datafusion/sql/src/select.rs, datafusion/sql/tests/sql_integration.rs, datafusion/sqllogictest/test_files/joins.slt
Closes the planning part of #10048. The query from the issue will now fail in the optimization phase similar to #6140.
Adds an unsupported fragment of the SQL syntax.
Extends the planner with support for `LATERAL` subqueries. See the tests added in `sql_integration.rs` for details.
Yes, I added tests in `sql_integration.rs`.
If there are user-facing changes then we may require documentation to be updated before approving the PR.
If we document the supported SQL fragment in the user-facing docs as BNF-style diagrams we might want to adapt those.
I don't think so.
=> Plan `LATERAL` subqueries

datafusion/common/src/hash_utils.rs
N/A
Removing a loop that seems to be redundant.
Removing a loop that seems to be redundant.
No
=> minor: Remove unused create_row_hashes

datafusion/core/src/physical_planner.rs, datafusion/expr/src/expr.rs, datafusion/physical-expr-functions-aggregate/src/aggregate.rs, datafusion/physical-plan/src/aggregates/mod.rs
More consistency and less opportunity for column name mismatch.
Part of #11782.
It's not manageable to have these two slightly different ways of obtaining a name from an expression.
Also, minor differences in the implementation can cause schema mismatch errors.
`physical_name` delegates to `schema_name` for all cases except top-level columns which are unqualified.
This was previously the purpose of the `is_first_expr` flag in `create_physical_name`.
Relying on existing tests.
`Expr::canonical_name` is deprecated because it's just an alias for `format!`
=> Use `schema_name` to create the `physical_name`

datafusion/functions/benches/pad.rs, datafusion/functions/src/unicode/rpad.rs
=> Improve rpad udf by using a GenericStringBuilder

datafusion/sqllogictest/test_files/aggregate.slt
=> Add test to verify count aggregate function should not be nullable

datafusion/functions/src/unicode/strpos.rs, datafusion/sqllogictest/test_files/string_view.slt
=> Add Utf8View support to STRPOS function

datafusion/proto/proto/datafusion.proto, datafusion/proto/src/generated/pbjson.rs, datafusion/proto/src/generated/prost.rs, datafusion/proto/src/physical_plan/mod.rs, datafusion/proto/tests/cases/roundtrip_physical_plan.rs
Closes #.
we add fetch to CoalesceBatchExec in #11652, but don't support ser/de, so this pr add ser/de support for fetch in CoalesceBatchesExec.
yes, add one test
=> fix: ser/de fetch in CoalesceBatchesExec

datafusion/expr-common/src/type_coercion/binary.rs
Closes #.
`dictionary_coercion` implies (to me) that this function applies to all dictionary coercions rather than just comparison coercion.
Changes
1. rename `dictionary_coercion` to `dictionary_comparison_coercion`
2. Add some more comments to clarify the purpose of the coercion
=> Minor: rename `dictionary_coercion` to `dictionary_comparison_coercion`, add comments

datafusion/substrait/Cargo.toml, datafusion/substrait/src/logical_plan/consumer.rs, datafusion/substrait/src/logical_plan/producer.rs, datafusion/substrait/src/variation_const.rs
N/A
closes https://github.com/apache/datafusion/pull/12074
DF was using the Substrait type_variations on a Substrait Timestamp to indicate whether a timestamp is seconds/millis/micros/nanos, while that works within DF that's not interoperable with other systems. Substrait has since introduced a PrecisionTimestamp type which includes the precision as a first class option, so we should use that instead.
- Bump substrait to latest and fix breaks
- Support consuming PrecisionTimestamp and PrecisionTimestampTz types in addition to the deprecate Timestamp type
- Produce PrecisionTimestamp and PrecisionTimestampTz types
Yes, with unit tests
=> feat: use Substrait's PrecisionTimestamp and PrecisionTimestampTz instead of deprecated Timestamp

datafusion/functions/src/string/split_part.rs
=> Improve split_part udf by using a GenericStringBuilder

datafusion/expr/src/logical_plan/builder.rs
Closes #.
Compilaton on main is broken due to a  logical merge conflict between https://github.com/apache/datafusion/pull/12040 and https://github.com/apache/datafusion/pull/12046
```
error[E0308]: mismatched types
--> datafusion/expr/src/logical_plan/builder.rs:402:52
|
402 |         Filter::try_new_with_having(expr, Arc::new(self.plan))
|                                           -------- ^^^^^^^^^ expected `LogicalPlan`, found `Arc<LogicalPlan>`
|                                           |
|                                           arguments to this function are incorrect
|
```
Fix compilation by updating API call
=> Fix compilation on main

datafusion/physical-plan/src/sorts/sort_preserving_merge.rs
Closes #.
When SortPreservingMergeExec has only one partition, it directly calls its input to get the result. Therefore, the fetch parameter in SortPreservingMergeExec will have no effect.
so this pr, I reuse the LimitStream in Limit to limit the fetch result in SortPreservingMergeExec.
yes, add test for this case
=> fix: single partition in SortPreservingMergeExec don't take fetch

datafusion-examples/examples/custom_file_format.rs, datafusion/core/src/datasource/file_format/arrow.rs, datafusion/core/src/datasource/file_format/csv.rs, datafusion/core/src/datasource/file_format/json.rs, datafusion/core/src/datasource/file_format/mod.rs, datafusion/core/src/datasource/file_format/parquet.rs, datafusion/core/src/physical_optimizer/enforce_distribution.rs, datafusion/core/src/physical_optimizer/sort_pushdown.rs, datafusion/core/src/physical_optimizer/test_utils.rs, datafusion/physical-expr-common/src/sort_expr.rs, datafusion/physical-expr/src/equivalence/mod.rs, datafusion/physical-optimizer/src/output_requirements.rs, datafusion/physical-plan/src/execution_plan.rs, datafusion/physical-plan/src/insert.rs, datafusion/physical-plan/src/joins/sort_merge_join.rs, datafusion/physical-plan/src/joins/symmetric_hash_join.rs, datafusion/physical-plan/src/sorts/sort_preserving_merge.rs, datafusion/physical-plan/src/windows/bounded_window_agg_exec.rs, datafusion/physical-plan/src/windows/mod.rs, datafusion/physical-plan/src/windows/window_agg_exec.rs
Closes #.
Make type name shorter.
=> Use `LexRequirement` alias as much as possible

datafusion/functions-aggregate/src/approx_percentile_cont.rs, datafusion/sqllogictest/test_files/aggregate.slt
Closes #12012 .
If the `percentile` or `t-digest` is invalid for `approx_percentile_cont`, throw `no_impl_err` with a readable message instead of `internal_error`.
yes
no
=> Throw `not_impl_error` for `approx_percentile_cont` parameters validation 

datafusion/functions-aggregate/src/approx_percentile_cont.rs, datafusion/sqllogictest/test_files/aggregate.slt
Closes #12058.
[`ApproxPercentileAccumulator`](https://github.com/apache/datafusion/blob/3de50c833b0e4bbb688b02240d11a1d5092c0d36/datafusion/functions-aggregate/src/approx_percentile_cont.rs#L395) does not implement the `retract_batch` method, but `supports_retract_batch` returns true.
Yes
No
=> fix: set `supports_retract_batch` to false for `ApproxPercentileAccumulator`

datafusion/functions/src/string/common.rs, datafusion/functions/src/string/lower.rs, datafusion/functions/src/string/upper.rs, datafusion/sqllogictest/test_files/string_view.slt
Closes #11855
The Utf8View type are currently cast into Utf8 types. This PR updates the `lower` (and `upper`) functions(s) to support the type natively.
Added a specific path for Utf8Views to upper and lower.
Yes, updated the `EXPLAIN` tests to show no cast is performed. Also basic tests to show the actual transformation is done on the utf8view type.
No
=> feat: support upper and lower for stringview

datafusion/expr-common/src/type_coercion/binary.rs, datafusion/sqllogictest/test_files/type_coercion.slt
Closes #12101 .
Before this change, query to concat 2 dictionary columns will return error. This PR is to add support for concat dictionary columns in `string_concat_coercion` function.
=> fix concat dictionary(int32, utf8) bug

datafusion/functions/src/unicode/substr.rs
Fixes https://github.com/apache/datafusion/issues/12129
=> Check for overflow in substring with negative start

datafusion/common-runtime/src/common.rs
Follow on to https://github.com/apache/datafusion/pull/12086
@crepererum  suggested a  test for an existing panic propagation features here https://github.com/apache/datafusion/pull/12086#discussion_r1728587048
Add test
Only tests
Only tests
=> Minor: add test for panic propagation

datafusion/core/src/execution/context/mod.rs, datafusion/core/src/execution/mod.rs
N/A
While working on the reprpoducer for https://github.com/apache/datafusion/issues/12136 I knew there was a nice builder API added by @Omega359 in #11403 but I couldn't find it quickly in the docs
1. Add new doc example
1. There is a new `pub use` for `SessionStateBuilder`
2. There is a `From` impl for SessionState to make the example nicer
yes, by doc CI
Yes, the changes are user facing
here is what the new docs look like
=> Minor: Add example for configuring SessionContext

benchmarks/queries/clickbench/README.md, benchmarks/queries/clickbench/extended.sql
Part of https://github.com/apache/datafusion/issues/12094
@ejbyfeldt's great PR to improve STDDEV and VAR https://github.com/apache/datafusion/pull/12095 did not  had not improve any existing benchmarks. I think it would be good to add one. 
Add a query to the "extended" clickbench queries (that we use to benchmark datafusion) that has stddev and var
I tested it manually like this:
```shell
./bench.sh run clickbench_extended
```
```
Q0: SELECT COUNT(DISTINCT "SearchPhrase"), COUNT(DISTINCT "MobilePhone"), COUNT(DISTINCT "MobilePhoneModel") FROM hits;
Query 0 iteration 0 took 788.3 ms and returned 1 rows
Query 0 iteration 1 took 723.0 ms and returned 1 rows
Query 0 iteration 2 took 722.1 ms and returned 1 rows
Query 0 iteration 3 took 741.7 ms and returned 1 rows
Query 0 iteration 4 took …
```
=> Add benchmark for  STDDEV and VAR to Clickbench extended

datafusion/expr/src/logical_plan/builder.rs, datafusion/optimizer/src/analyzer/type_coercion.rs
Closes #12105 
We construct our own logical plans for a SQL-derivative languages (e.g. InfluxQL). The construction of logic plans using UNION requires that upon construction of the union plan node, we type-coerce the expressions prior to building the rest of the plan. If we don't perform this expression rewrite, then our consuming LIMIT, GROUP BY, ORDER BY, and aggregates will not be built properly.
We do not think our use case is unique, and therefore we are (a) exposing the APIs need to perform this coercion and (b) providing docs.
* Expose the expression rewriter. 
* There is precedence for other rewriters being exposed, such as [PullUpCorrelatedExpr](https://docs.rs/datafusion-optimizer/41.0.0/datafusion_optimizer/decorrelate/struct.PullUpCorrelatedExpr.html) and …
=> Provide documentation of expose APIs to enable handling of type coercion at UNION plan construction.

datafusion/catalog/src/table.rs, datafusion/core/src/dataframe/mod.rs, datafusion/core/src/datasource/cte_worktable.rs, datafusion/core/src/datasource/default_table_source.rs, datafusion/core/src/datasource/view.rs, datafusion/expr/src/table_source.rs, datafusion/optimizer/src/analyzer/inline_table_scan.rs
This patch adds an ability to return a `LogicalPlan` by value from a `TableProvider`. 
Closes https://github.com/apache/datafusion/issues/12120
Let's assume that we have `TableProvider` that supports concurrent modifications of the inner logical plan (for example, mutable VIEW), and it cannot afford to provide a reference. 
`get_logical_plan(...)` method signature was changed. Now it returns a `Cow<LogicalPlan>`.
Need to update the `get_logical_plan(...)` implementations to return `Cow::Borrowed` instead of the reference.
=> Add ability to return `LogicalPlan` by value from `TableProvider::get_logical_plan`

datafusion/functions-aggregate-common/src/aggregate/groups_accumulator/accumulate.rs, datafusion/functions-aggregate/src/stddev.rs, datafusion/functions-aggregate/src/variance.rs, datafusion/sqllogictest/test_files/aggregate.slt
Closes #12094.
Hopefully improve performance of queries using stddev and variance aggregates.
I did not find any of the current benchmarks containing stddev and/or variance. So I modified clickbench query 31 and 32 to use STDDEV instead of AVG. And these were the results:
Before
```
Running benchmarks with the following options: RunOpt { query: None, common: CommonOpt { iterations: 5, partitions: None, batch_size: 8192, debug: false, string_view: false }, path: "/home/eejbyfeldt/dev/apache/datafusion/benchmarks/data/hits.parquet", queries_path: "/home/eejbyfeldt/dev/apache/datafusion/benchmarks/queries/clickbench/queries.sql", output_path: Some("/home/eejbyfeldt/dev/apache/datafusion/benchmarks/results/implement-groups-accumulator-for-stddev/clickbench_1.json") }
Q0: SELECT …
```
=> Implement groups accumulator for stddev and variance

datafusion/expr/src/logical_plan/plan.rs, datafusion/physical-expr/src/partitioning.rs
Closes #.
I was looking for the page on [`Partitioning`](https://docs.rs/datafusion/latest/datafusion/physical_expr/enum.Partitioning.html) but the first
thing that comes up is the partitioning description for Logical plans
Thus I would like to link the description in the result that also appears first
Add a link from logical `Partitioning` to the more detailed documentation
Here is what the doc looks like now:
By doc CI  and I also looked at it manually
=> Minor: refine Partitioning documentation

datafusion/core/tests/fuzz_cases/sort_fuzz.rs, datafusion/execution/src/runtime_env.rs
Closes #12137
Allow to create `RuntimeEnv` directly from the config instance.
- New method
- Changed test to cover this change
To test this change, I've changed one existing test sort_fuzz to use a new API.
No
=> Minor: allow to build RuntimeEnv from RuntimeConfig

datafusion/functions/benches/lower.rs
Follow up for https://github.com/apache/datafusion/issues/11855.
I updated the impl of upper and lower to support stringview, but didn't update the benchmarks to include stringview cases. This may be useful in the future if certain optimizations can be added.
It does add a number of new cases, so I can trim them if there's general concern about overall benchmark runtime.
Just update the lower benches. I could also update the upper if it's good for completeness, but the lower and upper share 95% of their implementation.
Yes, ran the benchmarks.
=> benches: add lower benches for stringview

datafusion/core/src/execution/context/mod.rs, datafusion/expr/src/expr_fn.rs, datafusion/expr/src/logical_plan/plan.rs, datafusion/sql/src/unparser/rewrite.rs
Extracted from https://github.com/apache/datafusion/pull/12166 + some more new places updated.
Relates to https://github.com/apache/datafusion/pull/12172
=> Replace Arc::try_unwrap with Arc::unwrap_or_clone where cloning anyway

datafusion/expr/src/logical_plan/builder.rs, datafusion/expr/src/logical_plan/plan.rs, datafusion/expr/src/logical_plan/tree_node.rs, datafusion/optimizer/src/analyzer/type_coercion.rs, datafusion/optimizer/src/common_subexpr_eliminate.rs, datafusion/optimizer/src/decorrelate_predicate_subquery.rs, datafusion/optimizer/src/eliminate_cross_join.rs, datafusion/optimizer/src/eliminate_filter.rs, datafusion/optimizer/src/eliminate_limit.rs, datafusion/optimizer/src/eliminate_nested_union.rs, datafusion/optimizer/src/eliminate_one_union.rs, datafusion/optimizer/src/eliminate_outer_join.rs, datafusion/optimizer/src/optimize_projections/mod.rs, datafusion/optimizer/src/propagate_empty_relation.rs, datafusion/optimizer/src/push_down_filter.rs, datafusion/optimizer/src/push_down_limit.rs, datafusion/sql/src/select.rs
It can now be replaced with single call `Arc::unwrap_or_clone`, with added bonus of slightly better name.
=> Remove unwrap_arc helper

datafusion/sql/src/unparser/plan.rs
Reconstruction of `ast::OrderByExpr` was implemented twice, in `plan.rs` and `expr.rs` submodules of the unparser.
Extracted from https://github.com/apache/datafusion/pull/12177
=> Deduplicate sort unparsing logic

datafusion/expr/src/utils.rs, datafusion/sql/src/expr/function.rs, datafusion/sql/src/unparser/rewrite.rs
Relates to https://github.com/apache/datafusion/issues/1468#issuecomment-2308275476
Prep for https://github.com/apache/datafusion/pull/12177
=> Require sort expressions to be of type Sort

datafusion/proto/src/logical_plan/from_proto.rs
Behavior of `parse_vec_expr` and `parse_exprs` is almost similar -- both take a collection of expressions to parse. The only difference is that `parse_vec_expr` returns `Option::None` when collections is empty, but this difference in behavior does not correspond to difference in function names. Since the function is used once only, remove it instead of coming up with a fancy name.
Prep for https://github.com/apache/datafusion/pull/12177
=> Remove `parse_vec_expr` helper

datafusion/core/src/datasource/file_format/csv.rs, datafusion/core/src/execution/context/mod.rs, datafusion/core/tests/fuzz_cases/sort_fuzz.rs, datafusion/core/tests/memory_limit/mod.rs, datafusion/core/tests/parquet/file_statistics.rs, datafusion/execution/src/runtime_env.rs, datafusion/execution/src/task.rs, datafusion/physical-plan/src/aggregates/mod.rs, datafusion/physical-plan/src/joins/cross_join.rs, datafusion/physical-plan/src/joins/hash_join.rs, datafusion/physical-plan/src/joins/nested_loop_join.rs, datafusion/physical-plan/src/joins/sort_merge_join.rs, datafusion/physical-plan/src/repartition/mod.rs, datafusion/physical-plan/src/sorts/sort.rs, datafusion/wasmtest/src/lib.rs
Signed-off-by: Devan <devandbenz@gmail.com>## Which issue does this PR close?
Closes #12156 
Please see the issue #12156  for rationale.
Renames `RuntimeConfig` struct to `RuntimeEnvBuilder` to state more clearly its usage. Includes a type alias for backwards compatibility to ensure non-breaking changes.
=> Make RuntimeEnvBuilder rather than RuntimeConfig

datafusion/common/src/column.rs, datafusion/expr/src/expr_rewriter/mod.rs
It was deprecated since 20.0.0.
=> Remove normalize_with_schemas function

datafusion/proto/src/physical_plan/mod.rs, datafusion/proto/src/physical_plan/to_proto.rs, datafusion/proto/tests/cases/roundtrip_physical_plan.rs
`Arc::clone` is indispensable when passing shared references between threads. For synchronous code`&` and `&Arc` can be (and often are) used, with the latter being future-compatible, should the code start to need `Arc::clone` (e.g. due to parallelization).
=> Avoid Arc::clone when serializing physical expressions

datafusion/proto/tests/cases/mod.rs
I had created https://github.com/apache/datafusion/issues/11595 which I had created when working on  https://github.com/apache/datafusion/pull/11013 
When I was using `create_aggregate_expr`, aliases for max_udaf wouldn't be serialized, as indicated in #11595 . However, using the `AggregateExprBuilder` solved the problem, so the issue was probably in `create_aggregate_expr` , which by the way has been removed from the codebase, so we need to update the contributors how-to
https://github.com/apache/datafusion/blob/main/docs/source/contributor-guide/howtos.md?plain=1#L62
=> Confirming UDF aliases are serialized correctly 

datafusion/expr/src/table_source.rs, datafusion/optimizer/src/analyzer/inline_table_scan.rs, datafusion/optimizer/src/push_down_filter.rs
It was deprecated since 20.0.0.
=> Remove TableSource::supports_filter_pushdown function

datafusion/core/src/datasource/mod.rs, datafusion/core/tests/dataframe/mod.rs, datafusion/core/tests/user_defined/user_defined_plan.rs, datafusion/expr/src/expr.rs, datafusion/expr/src/expr_rewriter/mod.rs, datafusion/expr/src/expr_rewriter/order_by.rs, datafusion/expr/src/logical_plan/builder.rs, datafusion/expr/src/logical_plan/plan.rs, datafusion/expr/src/logical_plan/tree_node.rs, datafusion/expr/src/tree_node.rs, datafusion/expr/src/utils.rs, datafusion/optimizer/src/analyzer/count_wildcard_rule.rs, datafusion/optimizer/src/common_subexpr_eliminate.rs, datafusion/proto/src/logical_plan/from_proto.rs, datafusion/proto/src/logical_plan/to_proto.rs, datafusion/sql/src/expr/function.rs, datafusion/sql/src/expr/order_by.rs, datafusion/sql/src/unparser/expr.rs, datafusion/sql/src/unparser/rewrite.rs, datafusion/substrait/src/logical_plan/consumer.rs, datafusion/substrait/src/logical_plan/producer.rs
`expr::Sort` had `Box<Expr>` because Sort was also an expression (via
`expr::Expr::Sort`). This has been removed, obsoleting need to use a
`Box`.
Extracted from ~and based on~ https://github.com/apache/datafusion/pull/12177 to reduce PR scope
=> Remove Box from Sort 

datafusion/expr/src/expr_rewriter/mod.rs, datafusion/optimizer/src/simplify_expressions/simplify_exprs.rs
N/A
The code for preserving expr names here is the same as  `NamePreserver` so `NamePreserver` can be reused directly.
No
=> Minor: Reuse `NamePreserver` in `SimplifyExpressions`

datafusion/functions/src/string/common.rs
None
Simplify the code
Remove redundant argument and improve error message
No
No
=> Remove redundant argument and improve error message

datafusion/expr/src/utils.rs
=> Remove deprecated from_plan function

datafusion/physical-expr/src/aggregate.rs, datafusion/physical-expr/src/window/aggregate.rs, datafusion/physical-expr/src/window/sliding_aggregate.rs, datafusion/physical-optimizer/src/aggregate_statistics.rs, datafusion/physical-plan/src/aggregates/mod.rs, datafusion/proto/src/physical_plan/mod.rs
=> Remove redundant result of `AggregateFunctionExpr::field`

datafusion/sqllogictest/test_files/arrow_typeof.slt
Follow up to [observation made on this PR](https://github.com/apache/datafusion/pull/12199#discussion_r1733416035).
Test coverage for current behavior of `arrow_cast` with Utf8View and BinaryView types.
The change needed is already in upstream arrow-cast, but not in the current release used in datafusion.
Only test changes. No code changes.
Yes.
No.
=> Define current arrow_cast behavior for BinaryView

datafusion/common/src/config.rs, datafusion/core/src/dataframe/mod.rs, datafusion/core/src/dataframe/parquet.rs, datafusion/core/src/datasource/listing/table.rs, datafusion/core/src/execution/context/parquet.rs, datafusion/execution/src/config.rs, datafusion/physical-plan/src/aggregates/mod.rs
Extracted from https://github.com/apache/datafusion/pull/12243 per @crepererum 's https://github.com/apache/datafusion/pull/12243#issuecomment-2320721659
=> Avoid unnecessary move when setting SessionConfig

datafusion/physical-plan/src/aggregates/mod.rs
Closes #.
`GROUPING SETS ((a, b), (a))`, the `a` expr will always be treated as nullable in old code, which is not accurate.
=> Make group expressions nullable more accurate

datafusion/core/src/execution/session_state.rs, datafusion/expr/src/utils.rs, datafusion/optimizer/src/analyzer/expand_wildcard_rule.rs, datafusion/optimizer/src/analyzer/function_rewrite.rs, datafusion/optimizer/src/analyzer/subquery.rs, datafusion/optimizer/src/analyzer/type_coercion.rs, datafusion/optimizer/src/common_subexpr_eliminate.rs, datafusion/optimizer/src/decorrelate.rs, datafusion/optimizer/src/decorrelate_predicate_subquery.rs, datafusion/optimizer/src/eliminate_cross_join.rs, datafusion/optimizer/src/join_key_set.rs, datafusion/optimizer/src/optimize_projections/mod.rs, datafusion/optimizer/src/optimizer.rs, datafusion/optimizer/src/scalar_subquery_to_join.rs, datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs, datafusion/optimizer/src/simplify_expressions/simplify_exprs.rs, datafusion/optimizer/src/simplify_expressions/utils.rs, datafusion/optimizer/src/unwrap_cast_in_comparison.rs, datafusion/optimizer/src/utils.rs
Extracted from https://github.com/apache/datafusion/pull/12243 per @crepererum 's https://github.com/apache/datafusion/pull/12243#issuecomment-2320721659
=> Avoid redundant pass-by-value in optimizer

datafusion/expr/src/logical_plan/plan.rs
=> Remove deprecated LogicalPlan::with_new_inputs function

datafusion/sql/src/unparser/dialect.rs, datafusion/sql/src/unparser/expr.rs
PR improves unparser to produce valid CAST SQL for SQLite and Date32
SQLite does not have dedicated DATE type and prefers a text string that is an [ISO 8601 date/time](https://www.sqlite.org/lang_datefunc.html) value:
You can see below that casting to DATE produces invalid value whether casting to TEXT produces a valid one similar to using DATE function.
```sql
SELECT CAST('1995-03-15' AS DATE), DATE('1995-03-15'), CAST('1995-03-15' AS TEXT)
```
Test query (native)
```sql
SELECT count(o_orderdate) FROM orders 
WHERE `orders`.`o_orderdate`< '1995-03-15'
7286 rows
```
Existing  unparser behavior, producing `'1995-03-15' AS DATE` SQL for SQLite
```sql
SELECT count(o_orderdate) FROM orders 
WHERE `orders`.`o_orderdate`< CAST('1995-03-15' AS DATE)
0 rows
```
Fixed unparser behavior, producing …
=> Support alternate format for Date32 unparsing (TEXT/SQLite)

datafusion/common/src/hash_utils.rs, datafusion/core/src/datasource/listing/helpers.rs, datafusion/core/src/datasource/listing/table.rs, datafusion/core/src/datasource/physical_plan/parquet/mod.rs, datafusion/core/src/datasource/physical_plan/parquet/row_filter.rs, datafusion/core/src/datasource/statistics.rs, datafusion/core/src/execution/session_state_defaults.rs, datafusion/core/src/physical_optimizer/pruning.rs, datafusion/physical-expr/src/expressions/binary.rs, datafusion/physical-plan/src/execution_plan.rs
Helps with reviewing of #12135 
These are just a few changes that make the code cleaner/easier to understand/etc that I added when filing #12135. It was pointed out to me, though, that these make the PR harder to review as there's a lot of changes not directly related to the PR. So I'm pulling those changes into this PR so that they are hidden from the diff once this is merged, thus making the PR easier to review.
A few clean-ups that shouldn't change behavior at all.
All tests pass just like they do on main.
Shouldn't be
=> Extract drive-by fixes from PR 12135 for easier reviewing

datafusion/functions-aggregate/src/lib.rs, datafusion/functions-aggregate/src/nth_value.rs, datafusion/proto/tests/cases/roundtrip_logical_plan.rs
Closes #12278.
Same as #12278.
The API in v40 is:
```rust
pub fn nth_value(args: Vec<Expr>) -> Expr
``` 
A better API would be this:
```rust
pub fn nth_value(
expr: Expr,
n: i64,
order_by: Option<Vec<SortExpr>>
) -> Expr
```
Yes. Logical roundtrip tests, both with and without order by expression.
Yes, this is a breaking change of user-facing API.
=> Fixes missing `nth_value` UDAF expr function 

datafusion/physical-plan/src/coalesce/mod.rs, datafusion/physical-plan/src/repartition/mod.rs, datafusion/sqllogictest/test_files/repartition.slt
Closes #12057 .
In #12057, the root cause of the panic is because Hash Repartition Execution receives an empty column `RecordBatch` according to the `optimized physical_query_plan` and `RecordBatch::try_new(batch.schema(), columns)` will panic because `RecordBatchOptions:row_count` is zero and `columns` is empty. 
I fix this issue by changing the function `RecordBatch::try_new` to `RecordBatch::try_new_with_options` to handle the empty columns input by setting the `RecordBatchOptions::row_count`.
While running the unit test, I found that the `gc_string_view_batch` function will panic with empty `RecordBatch`. I tried to update the `gc_string_view_batch` to use `RecordBatch::try_new_with_options` also.
No
=> fix hash-repartition panic

datafusion/physical-plan/src/aggregates/topk/hash_table.rs, datafusion/physical-plan/src/aggregates/topk/heap.rs, datafusion/physical-plan/src/aggregates/topk/priority_map.rs
It's not necessary to use unsafe Send impl. It's enough to require the referenced trait objects as Send.
=> Remove unsafe Send impl from PriorityMap

datafusion/sqllogictest/test_files/parquet.slt
Closes #12185 .
The test output is not deterministic due to absence of sorting and bunch of duplicates in input data, and according to the commit [history](https://github.com/apache/datafusion/pull/8560/files#diff-302c60bdcb660ff15df18c07385f977c64cfa6aee4c50ea8d1cbd15700ae51b4L167) it was not intended to check the output data, but was introduced in order to check that timestamp with timezones are not losing timezones while passing through query pipeline ([original PR link](https://github.com/apache/datafusion/pull/5481)).
The test behavior is rolled back to the one before porting to sqllogictests -- it now is checking output timestamp type (must contain tz), minimum output timestamp value (suppose it may be important) and total count of output records (not necessary, but may be helpful …
=> test: check record count and types in parquet window test

datafusion/functions/src/string/common.rs, datafusion/functions/src/string/concat.rs, datafusion/sqllogictest/test_files/string_view.slt
Closes #11836 
Explained within ticket #11836
=> Update the CONCAT scalar function to support Utf8View

benchmarks/bench.sh
N/A
Many of the warnings produced by shellcheck are indications of bugs in the script that would break under certain circumstances.
The following warnings was previously produced:
[SC2006](https://www.shellcheck.net/wiki/SC2006)
[SC2035](https://www.shellcheck.net/wiki/SC2035)
[SC2045](https://www.shellcheck.net/wiki/SC2045)
[SC2086](https://www.shellcheck.net/wiki/SC2086)
[SC2140](https://www.shellcheck.net/wiki/SC2140)
[SC2221](https://www.shellcheck.net/wiki/SC2221) ([SC2222](https://www.shellcheck.net/wiki/SC2222))
Manually running the script.
No.
=> chore: Fix warnings produced by shellcheck on bench.sh

datafusion/expr-common/src/groups_accumulator.rs, datafusion/physical-plan/src/aggregates/mod.rs, datafusion/physical-plan/src/aggregates/order/full.rs, datafusion/physical-plan/src/aggregates/order/partial.rs, datafusion/physical-plan/src/aggregates/row_hash.rs
=> Fix various typos in aggregation doc

datafusion/expr/src/logical_plan/plan.rs
Closes #12304
see #12304; the reason for the performance degradation is that we format the same expr in a loop.
=> perf: avoid repeat format in calc_func_dependencies_for_project

dev/release/README.md, docs/source/download.md
N/A
I found that the download link was incorrect while skimming the DataFusion docs.
Changes the download link to point to the correct location and release.
Also updates the release process with a note to update the download page.
Not a code change.
No
=> Update download page to reflect latest version (v41)

datafusion/common/src/scalar/mod.rs
N/A
Follow on to https://github.com/apache/datafusion/pull/12192 from @lewiszlw
I noticed some improvements that could be made to avoid some allocations
Reduce some string copies, add some more test coverage
=> Minor: Reduce string allocations in ScalarValue::binary display

datafusion/expr/src/logical_plan/plan.rs
When adding new plan node type, `LogicalPlan::with_new_exprs` needs to
be updated. Different code branches apply different inputs validation
style (no validation, just assert, or assert with messages), so it's
unclear which code pattern to follow.  This commit unifies the
validation and adds it to the branches where there was none.
=> Improve & unify validation in LogicalPlan::with_new_exprs

datafusion/common/src/scalar/mod.rs
Part of #2326
Extending support for union types to primitive operations.
Added support for `DataType::Union` to `ScalarValue::try_from_array` and `ScalarValue::eq_array`.
Added unit tests (we don't have slt tests yet, see #10161)
Not directly, but more functions will work on union types.
=> Support try_from_array and eq_array for ScalarValue::Union

datafusion/optimizer/src/filter_null_join_keys.rs, datafusion/optimizer/src/push_down_filter.rs, datafusion/optimizer/tests/optimizer_integration.rs
Closes #12349
Possible performance improvements when input plans contain nullable fields.
=> Push down null filters for more join types

datafusion/expr/src/expr.rs, datafusion/expr/src/expr_rewriter/mod.rs, datafusion/expr/src/expr_schema.rs, datafusion/sqllogictest/test_files/select.slt
A more general fix for #12183
The two expressions in the following code have the same `schema_name`s, so the `NamePreserver` will not take effect when `expr1` is rewritten to `expr2`. But they will produce different fields, which will result in schema changes.
Therefore, the `NamePreserver` needs to preserve both the qualifier and the schema name to ensure that the rewritten expression has the same `to_field()` result as before.
```rust
#[test]
fn test_expr_schema_name() {
let schema = Schema::new(vec![
Field::new("a", DataType::Int32, true),
Field::new("test.a", DataType::Utf8, true),
]);
let dfschema = DFSchema::try_from_qualified_schema("test", &schema).unwrap();
let expr1 = Expr::Column(Column::new_unqualified("test.a"));
let expr2 = Expr::Column(Column::new(Some("test"), "a")); …
```
=> fix: preserve qualifiers when rewriting expressions

datafusion-cli/Cargo.lock, datafusion-cli/Cargo.toml, datafusion/core/src/physical_optimizer/mod.rs, datafusion/physical-optimizer/Cargo.toml, datafusion/physical-optimizer/src/lib.rs, datafusion/physical-optimizer/src/topk_aggregation.rs
part of https://github.com/apache/datafusion/issues/11502.
=> Move `TopKAggregation` rule into `physical-optimizer` crate

datafusion/core/tests/fuzz_cases/merge_fuzz.rs, datafusion/physical-plan/src/sorts/merge.rs, datafusion/physical-plan/src/sorts/sort_preserving_merge.rs
Closes #12300.
Please see the issue.
=> Fix Possible Congestion Scenario in `SortPreservingMergeExec`

datafusion/physical-plan/src/unnest.rs, datafusion/proto/proto/datafusion.proto, datafusion/proto/src/generated/pbjson.rs, datafusion/proto/src/generated/prost.rs, datafusion/proto/src/physical_plan/mod.rs, datafusion/proto/tests/cases/roundtrip_physical_plan.rs
Closes #12343
Completeness of `UnnestExec`
* Add a new physical plan node `UnnestExecNode` to protos
* Support encoding `UnnestExec` to `UnnestExecNode`
* Support decoding `UnnestExec` from `UnnestExecNode`
* Add some public getters to `UnnestExec` to enable the encoding
Yes, added a roundtrip test.
* A new physical plan node Protobuf message
* Public getters in `UnnestExec`
=> Support protobuf encoding and decoding of `UnnestExec`

datafusion/sql/src/unparser/dialect.rs, datafusion/sql/src/unparser/plan.rs, datafusion/sql/src/unparser/rewrite.rs, datafusion/sql/tests/cases/plan_to_sql.rs
SQLite does not support defining column aliases as part of alias table definition, for example
```sql
SELECT "customers2"."c_name2" FROM
(
SELECT "customer"."c_name", "customer"."c_address"  FROM "customer"
) AS "customers2"("c_name2", "c_address2")
```
Must be rewritten as shown below so it can be executed on SQLite.
```sql
SELECT "customers2"."c_name2" FROM
(
SELECT "customer"."c_name" as "c_name2", "customer"."c_address" as "c_address2"  FROM "customer"
) AS "customers2"
```
PRs address this issue by adding an option for unparser to specify column aliases as part of internal query projection instead of outer table alias definition.
TPC-H Q13 is an example of where such aliasing is used. 
```sql
select
c_count,
count(*) as custdist
from
(
select
c_custkey,
count(o_orderkey)
from …
```
=> Fix subquery alias table definition unparsing for SQLite

datafusion/common/src/scalar/mod.rs
=> Remove deprecated ScalarValue::get_datatype

datafusion/common/src/scalar/mod.rs
This is similar to https://github.com/apache/datafusion/pull/12322
(Another) Follow on to https://github.com/apache/datafusion/pull/12192 from @lewiszlw
1. Add tests for binary debug
2. Fix a bug that the tests found
3. improve performance with fewer allocations
Yes
=> Minor: improve performance of `ScalarValue::Binary*` debug

datafusion/functions-nested/src/array_has.rs, datafusion/physical-expr-common/src/datum.rs, datafusion/physical-expr/src/expressions/in_list.rs
Closes #.
I realize I didn't call non-nested kernel (vectorized) for non-nested type. So did the one in `in-list`
I didn't run the benchmark. If anyone has concern about the actual performance, I could run the benchmark
=> Apply non-nested kernel for non-nested in `array_has` and `inlist`

datafusion/expr/src/expr_rewriter/mod.rs, datafusion/expr/src/logical_plan/plan.rs, datafusion/optimizer/src/analyzer/count_wildcard_rule.rs, datafusion/optimizer/src/analyzer/function_rewrite.rs, datafusion/optimizer/src/analyzer/type_coercion.rs, datafusion/optimizer/src/common_subexpr_eliminate.rs, datafusion/optimizer/src/optimize_projections/mod.rs, datafusion/optimizer/src/simplify_expressions/simplify_exprs.rs, datafusion/optimizer/src/unwrap_cast_in_comparison.rs
Follow up of #12341
The `save` and `restore` functions always return `OK`, so the `Result` return type becomes redundant.
Yes
No
=> Remove unnecessary `Result` from return type in `NamePreserver`

datafusion/functions/Cargo.toml, datafusion/functions/benches/character_length.rs, datafusion/functions/src/string/common.rs, datafusion/functions/src/unicode/character_length.rs
Part of https://github.com/apache/datafusion/issues/12306
See the issue.
This PR wants to show how the change will look like and decide if we should continue with other string functions like `lower()`
Though speed up for `char_length()` is not big, I guess it's because counting character's implementation is also relatively more CPU friendly, but according to Velox's benchmarks we can expect more speed up for string functions like `lower()/upper()`
1. Inside `character_length()` first check whether the current string array is ASCII-only, if so directly count bytes instead of decode characters one by one
2. Micro benchmark (first commit is bench only)
Result
```
group                                                  after                                  before
----- …
```
=> Faster `character_length()` string function for ASCII-only case

datafusion/sqllogictest/test_files/parquet_filter_pushdown.slt
Part of https://github.com/apache/datafusion/issues/4028
While reviewing https://github.com/apache/datafusion/pull/12135 from @itsjunetime I wanted to make sure everything was hooked up end to end and that the appropriate plan changes were done. 
I figured I would write such tests as part of my review, though for some reason the PR doesn't actually improve these plans (I will comment on that separately). 
This adds "end to end" tests that show what should happen when parquet filter pushdown is enabled (specifically the FilterExec should be gone)
yes, only tests
No, only tests
=> Minor: Add tests for using FilterExec when parquet was pushed down

datafusion/core/src/execution/session_state.rs
N/A
My team and I have been exploring Datafusion's potential to federate our custom sources performantly. Part of that is tuning optimizers depending on our needs. Noticed that there isn't a convenience method in `SessionState` yet that returns logical optimizer rules compared to its physical counterpart. Would be great for our POC work to quickly inspect them outside (and/or alongside) debugger or observer.
Adds a getter method `optimizers()` in `SessionState` in parity to the `physical_optimizers()` counterpart.
Yes, ran new and existing tests. Also manually tested from our existing POC code.
Examples:
```rust
let state = SessionStateBuilder::new()
.with_optimizer_rules(vec![
Arc::new(UnwrapCastInComparison::new()),
Arc::new(SimplifyExpressions::new()), …
```
=> Minor: Add getter for logical optimizer rules

datafusion/core/src/physical_optimizer/update_aggr_exprs.rs, datafusion/core/src/physical_planner.rs, datafusion/core/src/test_util/mod.rs, datafusion/core/tests/physical_optimizer/combine_partial_final_agg.rs, datafusion/physical-expr/src/aggregate.rs, datafusion/physical-expr/src/window/aggregate.rs, datafusion/physical-expr/src/window/sliding_aggregate.rs, datafusion/physical-optimizer/src/combine_partial_final_agg.rs, datafusion/physical-plan/src/aggregates/mod.rs, datafusion/physical-plan/src/aggregates/row_hash.rs, datafusion/physical-plan/src/windows/mod.rs, datafusion/proto/src/physical_plan/mod.rs, datafusion/proto/src/physical_plan/to_proto.rs, datafusion/proto/tests/cases/roundtrip_physical_plan.rs
Closes #12257.
The trait `AggregateFunctionExpr` was removed previously in #12096 . This is a follow-up PR that removes the usage of Arc wrapping for`AggregateFunctionExpr`.
=> Removed Arc wrapping for AggregateFunctionExpr

datafusion/expr-common/src/type_coercion/binary.rs, datafusion/functions/benches/repeat.rs, datafusion/functions/benches/substr.rs, datafusion/functions/src/regex/regexpmatch.rs, datafusion/optimizer/src/unwrap_cast_in_comparison.rs, datafusion/physical-expr/src/expressions/binary.rs, datafusion/sqllogictest/test_files/string_view.slt
Part of #12180.
Support StringView for binary operators like `~`, `!~`, etc.
If Utf8View is in any side of binary operators, we COERCE to Utf8. This behaviour will remain until native StringView support is implemented.
Yes.
No.
=> Support StringView for binary operators

datafusion/physical-expr/src/expressions/binary.rs, datafusion/physical-expr/src/expressions/mod.rs, datafusion/physical-expr/src/planner.rs, datafusion/sqllogictest/test_files/strings.slt
Add support for SIMILAR TO and NOT SIMILAR TO to the physical plan.
Closes #12155.
Currently, a simple query `select * from t1 where c1 similar to 'x*'` is not supported.
- Support for "SIMILAR TO" family operator in physical plan
- Additional sqllogic tests
The functionality is based on creating a binary expression for `Operator::RegexMatch` and family.
There is an existing `like` module for the LIKE operator. Probably, this functionality can be extracted to a similar `similar_to` module.
- unit test (for binary operator only)
- sqllogictest integration test
- manual test using `datafusion-cli`
- tested with additional operators for expression and pattern
No
=> Support for SIMILAR TO for physical plan

datafusion/core/src/datasource/physical_plan/parquet/opener.rs
None
There is an unnecessary clone method call in FileOpener::open
Remove one redundant usage of clone
no
=> Minor: Remove redundant usage of clone

datafusion/core/tests/fuzz_cases/join_fuzz.rs
Closes #11537.
It turned out to be not a NLJoin issue, but fuzz tests -- during NLjoin construction, join filter was completely ignored, and all NLjoin tests were running with only equijoin conditions in filter.
In the same time filtered inner/left/right/full join fuzz tests were passing even without the filter -- the reason is that they've been using `less_than_100_join_filter`, which always returns True, as generation of input data for column, used in this filter, always returns values less than 100 -- `make_staggered_batches` comment:
```
/// two sorted int32 columns 'a', 'b' ranged from 0..99 as join columns
```
so it seems to be more useful to place `col_lt_col_filter` in all tests, since it has non 100% selectivity.
Finally, after replacing filter in all test cases, some of HjSmj …
=> tests: enable fuzz for filtered anti-semi NLJoin

datafusion/sql/src/expr/mod.rs, datafusion/sqllogictest/bin/sqllogictests.rs
Closes #11499
Cause for stack overflow was familiar to #9962, so after some LLDB debugging was able to identify that `SqlToRel::sql_expr_to_logical_expr_internal` was being recursively called with a chunky frame size (appox 70000 bytes), and seemed to be the most frequent frame in the backtrace with the largest size. Applied fix similar to #9962 where large arms are split into functions to reduce the size of the main function.
Refactor `SqlToRel::sql_expr_to_logical_expr_internal` to split larger arms into separate functions.
Yes, existing sqllogictest (with stack size modifier removed so back to default 2MB)
No
=> Refactor `SqlToRel::sql_expr_to_logical_expr_internal` to reduce stack size

docs/source/contributor-guide/index.md
Related to https://github.com/apache/datafusion/issues/12357
I think there is some "common knowledge" that is not explicitly written down anywhere
Specifically, that performance improvements should be accompanied by benchmark results (most recently this came up in  https://github.com/apache/datafusion/pull/12270)
1. Document need for benchmarks for performance PRs 
2. Add a section (without content) for the outcome of https://github.com/apache/datafusion/issues/12357
3. Some other "drive by" documentation improvements
Note I am not trying to change anything, only document the current reality.
by doc CI
Docs
=> Add documentation about performance PRs, add (TBD) section on feature criteria

datafusion/expr/src/logical_plan/extension.rs
Closes https://github.com/apache/datafusion/issues/12280
One of the links in `datafusion::logical_expr::UserDefinedLogicalNodeCore`  [doc](https://docs.rs/datafusion/latest/datafusion/logical_expr/trait.UserDefinedLogicalNodeCore.html) throws an invalid resource 
Referring to the file in a different module is abit tricky to I chose to refer to a remote Github file instead
Its a doc change so no test is needed (I think)
Yes. It will change the API doc
=> Fix invalid ref in UserDefinedLogicalNodeCore doc

datafusion/optimizer/src/filter_null_join_keys.rs, datafusion/optimizer/tests/optimizer_integration.rs
Closes (https://github.com/apache/datafusion/issues/12403)
Bug fix
=> Don't push down IsNotNull for `null_equals_null` case

datafusion/functions-nested/src/distance.rs, datafusion/sqllogictest/test_files/array.slt
=> feat: Support `FixedSizedList`  in `array_distance` function

datafusion/functions/src/unicode/substr.rs, datafusion/sqllogictest/test_files/functions.slt
N.A.
Recently native `StringView` type support is implemented on `substr()` string function, but its behaviour is not consistent with the older implementation on `StringArray` string physical column type
The function semantics on the original `StringArray` type is consistent with postgres https://www.postgresql.org/docs/9.1/functions-string.html
The postgres version of `substr(s, start, count)`'s behavior is: `start` is 1-indexed, then we have a maybe out of bounds , and 0-indexed character range `[start-1, start-1+count)` , the valid char range is `[0, s.chars().count())`, and this function will take the intersection of two.
They handle negative start index differently and also handle invalid range differently
```
DataFusion CLI v41.0.0
> select substr('foo', -2,4), …
```
=> Fix: `substr()` on StringView column's behavior is inconsistent with the old version

datafusion/substrait/src/logical_plan/consumer.rs, datafusion/substrait/src/logical_plan/producer.rs, datafusion/substrait/tests/cases/consumer_integration.rs, datafusion/substrait/tests/cases/function_test.rs, datafusion/substrait/tests/cases/logical_plans.rs, datafusion/substrait/tests/cases/mod.rs, datafusion/substrait/tests/cases/substrait_validations.rs, datafusion/substrait/tests/substrait_integration.rs, datafusion/substrait/tests/testdata/test_plans/simple_select.substrait.json, datafusion/substrait/tests/testdata/test_plans/simple_select_with_mask.substrait.json, datafusion/substrait/tests/testdata/tpch/nation.csv, datafusion/substrait/tests/testdata/tpch/region.csv, datafusion/substrait/tests/utils.rs
Closes https://github.com/apache/datafusion/issues/12223
When DataFusion consumes a Substrait plan, if the schema it has a for a table is incompatible with what is given/expected by the Substrait plan it should reject the plan. A Substrait schema is compatible with a DataFusion schema if the Substrait schema is a subset of the DataFusion schema.
Attempting to execute a plan when DataFusion and Substrait disagree on the schema is unlikely to lead to meaningful results, so in cases where the schemas are not compatible DataFusion should reject the plan.
This PR:
* Adds a validation to the the Substrait plan consumer for NamedScans that rejects Substrait plans when the schema in Substrait is incompatible with that in DataFusion.
* Updates existing tests that fail because of the above …
=> validate and adjust Substrait NamedTable schemas (#12223)

benchmarks/src/tpch/run.rs
Closes #.
Current tpc-h benchmark parquet format setting uses a default value, which ignores global parquet settings, which lead to inconsistent runtime behaviors.
This pr fixes this by inherting the global settings.
Sutble bug, easy to fix but difficult to diagnose. Maybe we should consider change the api to avoid misuse as well.
=> fix tpc-h parquet setting to respect global options

README.md
N/A
While working on https://github.com/apache/datafusion/pull/12418 I noticed that the top most links on https://github.com/apache/datafusion currently were wonky
1. The project website just linked to the github url
2. the "guides" link linked to the doc source which doesn't seem all that useful
1. Fix project website link to point at https://datafusion.apache.org/
2. Remove guide link (they are on the main project website link)
I tested manually. You can see the rendered version here: https://github.com/alamb/datafusion/tree/alamb/self_referential_site?tab=readme-ov-file
Only docs
=> Minor: Fix project website links

datafusion/core/src/dataframe/mod.rs
Closes #12425 
The current implementation regresses when you have multiple columns without a qualifier and the new with_column is a window function. This is because the loop is checking for any field to not have a qualifier.
Check the display name of the expr in the schema matches that of the window function that was added.
Updated unit test
None
=> Check window functions by str for with_column

datafusion/sql/src/expr/mod.rs, datafusion/sql/src/select.rs, datafusion/sqllogictest/test_files/wildcard.slt
Closes https://github.com/apache/datafusion/issues/12427
In order for the following query to work properly:
```sql
SELECT PUBLIC.t1.* FROM PUBLIC.t1
```
Modify some `SqlToRel` functions: 
- `sql_select_to_rex`
- `sql_expr_to_logical_expr_internal`
Using the `object_name_to_table_reference` function, to be consistent with `create_relation`.
Yes.
=> Fix: upper case qualifier wildcard bug

datafusion/functions/src/core/mod.rs, datafusion/functions/src/core/version.rs, docs/source/user-guide/sql/scalar_functions.md
Closes #12424
Pretty self explanatory — it's use to know what version of a database you're using. 
Adds a `version()` UDF.
Usage:
```bash
cargo run --manifest-path datafusion-cli/Cargo.toml
```
```sql
select version();
+--------------------------------------------+
| version()                                  |
+--------------------------------------------+
| Apache DataFusion 41.0.0, aarch64 on macos |
+--------------------------------------------+
1 row(s) fetched. 
Elapsed 0.018 seconds.
```
I'd like to add:
* Rustc version, but that would require a build script or another dependency
* Arrow-rs version, but would require a new export from arrow-rs, equivalent to `datafusion::DATAFUSION_VERSION`
yes
Just one new UDF.
=> Add a `version()` UDF

README.md, datafusion/core/src/lib.rs, docs/source/index.rst
Related to https://github.com/apache/datafusion/issues/12357
Inspired by @phillipleblanc's comment on https://github.com/apache/datafusion/issues/12357#issuecomment-2335401127 let's make it clearer that  DataFusion is targeted at people building other systems
While I was working on this, it also became clear the DataFusion summary / intro had diverged so I unified it again
Changes:
1. Clarify that DataFusion is targeted at people building other systems
2. Ensure that the readme, user guide and library .rs are all in sync
By CI
No functional change, only doc changes
=> Improve comments on target user and unify intro summaries

docs/source/contributor-guide/architecture.md, docs/source/index.rst, docs/source/library-user-guide/extensions.md
Related to https://github.com/apache/datafusion/issues/12357
Inspired by @phillipleblanc and @jonahgao comments on https://github.com/apache/datafusion/issues/12357 let's try and make it easier to find other features such as table providers rather than necessarily trying to add them to the core of DataFusion itself.
1. Add "Extensions List" page with a table of projects
2. Move datafusion-contrib content to the new page
CI doc tests. I also rendered it locally:
=> Add 'Extensions List' page to the documentation

datafusion/functions/benches/regx.rs, datafusion/functions/src/regex/regexpreplace.rs, datafusion/sqllogictest/test_files/string_view.slt
Closes #12150 & closes #11912 
Currently the StringView data type cannot be cast to`as_generic_string_array`. The changes here resolve that: https://github.com/apache/datafusion/pull/12203/files#diff-0007996e12eb1b2e63363974424f13330f85a7fc48e0c55381f8a30a0f372931R206
Another point of issue was in the `return_type` match statement when using a function within the query on `Utf8View` that appears to be returning a ScalarArray of `StringArray` 
For example:
```
SELECT
REGEXP_REPLACE(column1_utf8view, lower(column1_utf8view), 'bar') AS k
FROM test;
```
`lower(column1_utf8view)` would return a `StringArray` instead of a `StringViewArray` which would cause the result of  the query to return a `StringArray`. For now I am implementing a conversion step …
=> Fix: Internal error in regexp_replace() for some StringView input

datafusion/sql/src/parser.rs, datafusion/sqllogictest/test_files/create_external_table.slt
Closes #12363 
Returns an explicit error when attempting to `create` a `temporary` table which is unsupported.
yes.
yes, returns an explicit error.
=> Minor: add err on `create` `temporary` table

datafusion/core/tests/sql/select.rs
Part of https://github.com/apache/datafusion/issues/12424
Follow on to https://github.com/apache/datafusion/pull/12429
Testing the `version()` function is a bit tricky as the output is platform and version dependent so we didn't put one in https://github.com/apache/datafusion/pull/12429
Add a test for `version()`
All tests
No, this is test only
=> Minor: Add a test for version() function

datafusion/optimizer/src/decorrelate_predicate_subquery.rs, datafusion/optimizer/src/utils.rs, datafusion/optimizer/tests/optimizer_integration.rs, datafusion/sqllogictest/test_files/join.slt
=> Handle case-sensitive identifier when decorrelating predicate subquery

datafusion/core/src/datasource/avro_to_arrow/mod.rs
Closes #12451
We need schema::to_arrow_schema to be able to use avro_to_arrow module in situations where we are deserializing avro from in memory buffers and not an avro file.
=> Making avro_to_arrow::schema::to_arrow_schema public

datafusion/core/src/datasource/listing/table.rs
Related to https://github.com/apache/datafusion/issues/12378
While working with @waruto210  on https://github.com/apache/datafusion/pull/12417, we noticed this API would make the code easier to work with. 
Add `ListingOptions::with_file_extension_opt`
Yes, by doc test example that is run in CI
New API, no breaking changes
=> Minor: add `ListingOptions::with_file_extension_opt`

datafusion/physical-expr-common/src/physical_expr.rs, datafusion/physical-expr/src/expressions/column.rs
Part of https://github.com/apache/datafusion/issues/4028
While working with @itsjunetime on https://github.com/apache/datafusion/pull/12135
I noticed that the description / documentation of `PhysicalExpr` was not as clear as it could be:
1. It didn't really talk about the use of column indexes vs names
2. The trait itself was not well documented
3. The `Column` epr was also not as well documented as it could be
Improve the documentation so this is clearer
By docs CI
No functional changes, only documentation
=> Improve PhysicalExpr and Column documentation

datafusion/core/src/datasource/physical_plan/parquet/opener.rs, datafusion/core/src/datasource/schema_adapter.rs
Part of https://github.com/apache/datafusion/issues/4028
While working with @itsjunetime on https://github.com/apache/datafusion/pull/12135 we spent a while reviewing the code in `ParquetOpener` and I realized that the documentation could be improved
Improve the documentation
By CI
No functional changes, just docs
=> Minor: improve ParquetOpener docs

datafusion/sql/src/parser.rs, datafusion/sql/src/statement.rs, datafusion/sqllogictest/test_files/create_external_table.slt
Closes https://github.com/apache/datafusion/issues/12449
@hailelagi fixed the bug for `TEMPORARY` in https://github.com/apache/datafusion/pull/12439 :pray:
While reviewing https://github.com/apache/datafusion/pull/12439 I noticed there are some other clauses that are ignored too
For example the `CLUSTER BY ` clause is totally ignored:
```sql
> create table  foo(x int) cluster by x;
0 row(s) fetched.
Elapsed 0.009 seconds.
```
We should reject this with an explicit error rather than silently ignoring it
Changes:
1. Change sqlparser to error on fields which are currently ignored
=> Do not silently ignore unsupported `CREATE TABLE` and `CREATE VIEW` syntax

datafusion/core/src/datasource/listing/table.rs
Closes #12378.
Using `FileFormat::get_ext` as the default file extension filter better meets user expectations.
Use `FileFormat::get_ext` as the default file extension filter
Yes
User do not need to specify the file extension if they choose the default value.
=> use FileFormat::get_ext as the default file extension filter

datafusion/sql/src/unparser/plan.rs, datafusion/sql/src/unparser/rewrite.rs, datafusion/sql/tests/cases/plan_to_sql.rs
=> feat(unparser): adding alias for table scan filter in sql unparser

datafusion/functions-nested/src/array_has.rs
While working on #12459 I noticed a few things that could do with being cleaned up.
* Rewrite `ArrayHas::invoke` to be cleaner and easier to understand — logic hasn't changed
* ~~Rewrite `array_has_dispatch_for_scalar` to use `BooleanArray` builder, not a `Vec`~~ Small tweak to `array_has_dispatch_for_scalar`
Tests for `array_has` already exist.
no.
=> cleanup `array_has`

Cargo.toml
Closes #.
I met some problem when build datafusion.
It seems that  chronov0.4.34 don't contain MappedLocalTime?
https://docs.rs/chrono/0.4.34/chrono/?search=MappedLocalTime
https://docs.rs/chrono/latest/chrono/offset/type.MappedLocalTime.html
=> chore: bump chrono to 0.4.38

datafusion/expr/src/udf.rs
It was deprecated since v 34.
This also removes associated `ScalarUdfLegacyWrapper` supporting the removed function. Note that similar `SimpleScalarUDF` is retained, thus the functionality that was used to be provided by
`ScalarUdfLegacyWrapper` remains available.
🧹
=> Remove deprecated ScalarUDF::new

datafusion/core/src/execution/context/mod.rs, datafusion/core/src/execution/session_state.rs
These were deprecated since v 32.
🧹
=> Remove deprecated config setup functions

datafusion/functions/src/math/gcd.rs
The `a` and `b` are shifted as a next instruction.
=> Remove unnecessary shifts in gcd()

datafusion/expr-common/src/groups_accumulator.rs
Related to https://github.com/apache/datafusion/issues/6906
While working on https://github.com/apache/datafusion/issues/6906 with [rationale](https://github.com/apache/datafusion/issues/6906#issuecomment-2355356541) and a [potential design](https://github.com/apache/datafusion/issues/6906#issuecomment-2355629355) to improve the performance I made some diagrams to explain the context which I think would improve DataFusion
1. improve `GroupsAccumulator` docs (with diagram!)
=> Minor: improve `GroupsAccumulator` docs

datafusion/functions-aggregate-common/src/aggregate/groups_accumulator.rs
Related to https://github.com/apache/datafusion/issues/6906
While working on https://github.com/apache/datafusion/issues/6906 with [rationale](https://github.com/apache/datafusion/issues/6906#issuecomment-2355356541) and a [potential design](https://github.com/apache/datafusion/issues/6906#issuecomment-2355629355) to improve the performance I made some diagrams to explain the context which I think would improve DataFusion
1. improve `GroupsAccumulatorAdapter` docs (with diagram!)
=> Minor: improve `GroupsAccumulatorAdapter` docs

datafusion-examples/examples/simple_udf.rs, datafusion/core/src/dataframe/mod.rs, datafusion/core/tests/expr_api/simplification.rs, datafusion/core/tests/user_defined/user_defined_scalar_functions.rs, datafusion/expr/src/expr_fn.rs, datafusion/proto/src/bytes/mod.rs, datafusion/proto/tests/cases/roundtrip_logical_plan.rs, datafusion/proto/tests/cases/roundtrip_physical_plan.rs, datafusion/proto/tests/cases/serialize.rs, datafusion/sqllogictest/src/test_context.rs
The argument types are moved into `create_udf` so moving also `return_type` would increase API consistency.
Internally, the `create_udf` unwrapped or cloned (so moves) the passed in return type Arc, so there was no non-API benefit from using a shared pointer.
=> Remove Arc wrapping from create_udf's return_type

datafusion/functions-nested/src/utils.rs, datafusion/functions/src/utils.rs
`make_scalar_function` serves as a template to implement functions, abstracting away processing of scalar values. While it's recommended to implement `ScalarUDFImpl` directly, a few functions still use the `make_scalar_function` helper, perhaps because it reduces code verbosity.
While `make_scalar_function` is a template function, it's not eligible for effective inlining because of the `Arc<Fn>` return type.
This commit removes `Arc` and unlocks inlining. The change impact was
verified manually using `cargo rustc -p datafusion-functions-nested   --
--emit asm -C opt-level=2` and comparing the generated for
`ArrayDistance::invoke` exemplary function that uses
`make_scalar_function`. Only after the changes can
`ArrayDistance::invoke` call the `array_distance_inner` directly.
The change …
=> Make make_scalar_function() result candidate for inlining, by removing the `Arc`

datafusion/functions/Cargo.toml, datafusion/functions/benches/strpos.rs, datafusion/functions/src/unicode/strpos.rs
Closes #12366.
For ASCII-only cases, I tried to use the slice window to find the position instead of the string pattern matching.
We can find that the ASCII-only `StringViewArray`  case performs 50% faster than before. ~~However, I'm not really sure why the normal string array can't be improved. 🤔~~
If both arguments are ASCII-only, we can perform this faster method.
The benchmark result:
```
group                                        after                                   before
-----                                        -----                                   ------
strpos_StringArray_ascii_str_len_128         1.00  1585.2±49.78µs        ? ?/sec     1.74      2.8±0.07ms        ? ?/sec
strpos_StringArray_ascii_str_len_32          1.00   558.2±24.13µs        ? ?/sec     2.22 …
```
=> Faster strpos() string function for ASCII-only case

datafusion/functions/src/unicode/substr.rs
Part of #12306 
See the issue for the background.
Function arguments `start` and `count` in `substr(s, start, count)` are character-based, if string is utf-8 encoded, it would decode `start + count` characters. However if given strings are all ASCII encoded, function can calculate byte indices in constant time.
One tricky condition for this function is: taking a small prefix of a long string (`e.g. substr(long_str_with_1k_chars, 1, 20)`).In this case the ASCII validation overhead can be greater than decoding a small number of characters. As a result, in some micro benchmarks (taking the first 6 bytes from 128 bytes string), this PR introduced ~5% slowdown.
To avoid big regression for similar patterns, the implementation will check the approximate string length, and skip ASCII validation …
=> Specialize ASCII case for substr()

datafusion/sql/src/unparser/plan.rs, datafusion/sql/src/unparser/rewrite.rs, datafusion/sql/tests/cases/plan_to_sql.rs
Follow up PR for https://github.com/apache/datafusion/pull/12331 that improves SQLite subquery tables aliasing unparsing to support more complex cases, for example
```sql
SELECT * FROM (SELECT o_orderkey + 1 FROM orders) AS c(key) LIMIT 10
SELECT * FROM (SELECT o_orderkey FROM orders LIMIT 10) AS c(key) LIMIT 10
```
PRs modifies `LogicalPlan::SubqueryAlias(plan_alias)` unparser to support more complex table aliasing scenarios for  SQLite:
1 - calculated columns
2- cases where subquery projection is wrapped by other operators (e.g., LIMIT, SORT)
Tested manually and added unit tests
No
=> Improve SQLite subquery tables aliasing unparsing

datafusion/sql/src/expr/function.rs
Related to https://github.com/apache/datafusion/issues/12464
follow on ot https://github.com/apache/datafusion/pull/12469
Implement @comphead 's suggestion https://github.com/apache/datafusion/pull/12469#discussion_r1760316418
> Wondering may be it can be an Option<String>?
> Usually find methods, on collections as well returns the Option
yes, covered by existing unit tests
Technically it is an API change, but the API has not yet been released
=> Minor: use Option rather than Result for not found suggestion

datafusion/expr/src/udaf.rs
Deprecated since v 34. Remove it along with associated `AggregateUDFLegacyWrapper`.
=> Remove deprecated AggregateUDF::new

datafusion/core/src/datasource/physical_plan/parquet/mod.rs, datafusion/physical-expr/src/utils/guarantee.rs
Closes #12473.
Well explained in the issue.
This PR resolves the issue in display output string level instead of the real `literals: HashSet<ScalarValue>` data level.
1. Add `sorted_literals` when displaying `LiteralGuarantee` to ensure literals part of each guarantee element is deterministic. (Enough for fixing Andy's case)
2. Add sorted `guarantees` to make sure the whole guarantees vector is deterministic. (In case we have more than one `required_guarantees`)
Yes. By adding `parquet_exec_display_deterministic`.
1. Ensure EXPLAIN to be deterministic every time (loops 100 times) for the same expr.
2. Ensure EXPLAIN for two different expr with equivalent filter condition to be deterministic.
No, only if you EXPLAIN and display a physical plan, the results will be deterministic now.
=> Make `required_guarantees` output to be deterministic

datafusion/substrait/src/logical_plan/producer.rs, datafusion/substrait/tests/cases/serialize.rs
Continues #12347 
This PR sets the [output_mapping](https://github.com/substrait-io/substrait/blob/bc4d6fb9bc0435c3db24172566c343e119fc50a9/proto/substrait/algebra.proto#L30-L33) field on ProjectRels for plans _produced_ by DataFusion. 
Given a plan
```
Projection: data.b, data.a + data.a, data.a
TableScan: data projection=[a, b]",
```
When creating the Substrait ProjectRel, DataFusion will now set the output mapping to [2,3,4] so that the Substrait ProjectRel will match the DataFusion behaviour of _only_ outputting expressions.
By default, if the `emit_kind` field is not set with an `output_mapping`, [a Substrait ProjectRel emits all input columns followed by all expressions](https://substrait.io/relations/logical_relations/#project-operation). This does not match the DataFusion …
=> feat(substrait): set ProjectRel output_mapping in producer

datafusion/core/src/datasource/physical_plan/parquet/row_group_filter.rs
=> feat:Support applying parquet bloom filters to StringView columns

datafusion/physical-plan/src/joins/nested_loop_join.rs, datafusion/sqllogictest/test_files/join.slt, datafusion/sqllogictest/test_files/joins.slt
Closes #11332.
See the linked issue.
`NestedLoopJoinExec` now preserves the order of the right table for `Inner`, `Right`, `RightAnti` and `RightSemi` join types.
Tested with `join_maintains_right_order` and relevant SQL logic tests
This PR changes the output ordering of some queries with `JOIN`, as reflected in SQL logic tests. The output values and the API remain unchanged.
=> Preserve the order of right table in NestedLoopJoinExec

datafusion/functions/benches/ltrim.rs
Part of #12387 
We need a benchmark to see the improvements of the new string view trim introduced in #12395 .
Improve the ltrim benchmark, so that we can use it to see the improvements of the new string view trim.
Test manually.
No.
=> Improve benchmark for ltrim

datafusion/common/src/dfschema.rs, datafusion/sql/src/expr/identifier.rs, datafusion/sqllogictest/test_files/join.slt
Closes #12337 
check ambiguous column reference in query
=> Fix: check ambiguous column reference

datafusion/core/src/dataframe/mod.rs
Closes #12519.
Explained in #12519
yes
yes, there is additional public method in `DataFrame`
No braking changes
=> Expose DataFrame select_exprs method

datafusion/expr/src/expr_rewriter/order_by.rs, datafusion/optimizer/src/common_subexpr_eliminate.rs
N/A
These usages only require the expression's qualifier and field name. The `to_field` function constructs a `Field` that includes unnecessary information like data type, metadata, etc., which incurs higher overhead.
https://github.com/apache/datafusion/blob/f514e12ec4b73a4e6a417c5756152dd1ddceac10/datafusion/expr/src/expr_schema.rs#L461-L471
No
=> Replace some usages of `Expr::to_field` with `Expr::qualified_name`

datafusion/physical-plan/src/joins/nested_loop_join.rs, datafusion/sqllogictest/test_files/joins.slt
Closes #12528.
Iterating over the right rows instead of the left while calling `build_join_indices` increased the number of calls to `apply_join_filter_to_indices` in cases where the right table has more rows (which applies to most common use cases). Building the indices inside `build_join_indices` helps reduce the number of calls to `apply_join_filter_to_indices`
The same indices are created inside `build_join_indices` every time with an expensive operation so it makes sense to cache them.
This PR builds the indices in one go inside `build_join_indices`, removing the outer iteration, and reduces the number of calls to `apply_join_filter_to_indices` to 1 per `join_left_and_right_batch` call.
Also adds caching for join indices.
Tested with the following query using TPCH data (SF=1)
``` …
```
=> Fix NestedLoopJoin performance regression

datafusion/sql/src/unparser/plan.rs, datafusion/sql/tests/cases/plan_to_sql.rs
no corresponding issue.
The projection indices of a TableScan are the index number of its source schema. I used the `projected_schema` that is the output schema of the table scan in the previous PR. Some cases like the following one will fail because the index is out of the bound.
```rust
let schema = Schema::new(vec![
Field::new("id", DataType::Utf8, false),
Field::new("age", DataType::Utf8, false),
]);
let scan_with_projection = table_scan(Some("t1"), &schema, Some(vec![1]))?.build()?;
let scan_with_projection = plan_to_sql(&scan_with_projection)?;
assert_eq!(format!("{}", scan_with_projection), "SELECT t1.age FROM t1");
```
- Use the source schema instead of `projected_schema`.
yes
no
=> Fix unparse table scan with the projection pushdown

datafusion/sql/src/unparser/plan.rs, datafusion/sql/tests/cases/plan_to_sql.rs
Closes #12538.
I have added a missing block for unparsing OFFSET.
Yes. Unit-Tests are provided.
No.
=> Fix unparsing offset

datafusion/functions/src/datetime/date_part.rs, datafusion/sqllogictest/test_files/expr.slt
Closes #6327.
Closes https://github.com/apache/datafusion/issues/7097
Support `extract`/`date_part` by passing through requests to Arrow (where functionality was added in https://github.com/apache/arrow-rs/pull/6071 and https://github.com/apache/arrow-rs/pull/6246). There were also two changes required to the `seconds` helper function:
* If the number of nanoseconds overflows a 32 bit integer, (e.g., a DayTime interval of 5 seconds), then querying the nanoseconds returns null. However, it is reasonable to return a number of seconds in this case. However, if there is a non-round number of seconds, this will give an inaccurate answer, e.g., 5.1 seconds will get returned as 5, but I'm not sure how to solve this - returning null for round numbers of seconds seems bad. We could fall back to …
=> support EXTRACT on intervals and durations

datafusion/core/src/datasource/listing_table_factory.rs, datafusion/sql/src/statement.rs, datafusion/sql/tests/sql_integration.rs, datafusion/sqllogictest/test_files/create_external_table.slt, datafusion/sqllogictest/test_files/order.slt
Closes #7317 
This allows for setting the order upon creation of tables using parquet files without having to specify the schema. Since parquet already has the schema readily available in the metadata this is a relatively quick fix that will enable downstream usage to be less cumbersome, specifically, when setting up reproduction of issues.
=> feat(planner): Allowing setting sort order of parquet files without specifying the schema

datafusion/expr-common/src/type_coercion/binary.rs, datafusion/optimizer/src/analyzer/type_coercion.rs, datafusion/physical-expr/src/expressions/case.rs, datafusion/sqllogictest/test_files/case.slt
Closes #12370.
The rule for the List type is to choose the wider type (LargeList > List > FixedSizeList) as the target type.
- The type coercion rule for List type comparison.
- Support to coerce the list type for `then` expressions
- Support to compare nested type for `case-when` expression
yes
no
=> Support List type coercion for CASE-WHEN-THEN expression

datafusion/physical-plan/src/metrics/mod.rs
Closes #12567.
From `ParquetExec` metrics, with predicate pushdown enabled:
> metrics=[output_rows=0, elapsed_compute=96ns, row_groups_matched_bloom_filter=0, row_groups_matched_statistics=21050, file_scan_errors=0, **pushdown_rows_matched=0**, row_groups_pruned_statistics=173576, row_groups_pruned_bloom_filter=21050, file_open_errors=0, num_predicate_creation_errors=0, bytes_scanned=25023432248, **pushdown_rows_pruned=0**, page_index_rows_pruned=0, predicate_evaluation_errors=0, page_index_rows_matched=0, time_elapsed_scanning_until_data=16.622753ms, time_elapsed_processing=72.280463608s, pushdown_eval_time=382ns, page_index_eval_time=3.177676ms, time_elapsed_scanning_total=16.661811ms, time_elapsed_opening=102.989073638s]
For example, `pushdown_rows_matched` and `pushdown_rows_pruned` …
=> Sort metrics alphabetically in EXPLAIN ANALYZE output

datafusion/core/src/datasource/physical_plan/parquet/metrics.rs, datafusion/core/src/datasource/physical_plan/parquet/mod.rs, datafusion/core/src/datasource/physical_plan/parquet/page_filter.rs, datafusion/core/src/datasource/physical_plan/parquet/row_filter.rs, datafusion/core/tests/parquet/filter_pushdown.rs, datafusion/core/tests/parquet/mod.rs, docs/source/user-guide/explain-usage.md
Closes #12543.
Closes #12544.
1. Rename `{pushdown,page_index}_filtered` to `{pushdown,page_index}_pruned`
2. Add `{pushdown,page_index}_matched`
3. Added documentation for existing pushdown-related metrics
The latter makes it clearer in EXPLAIN ANALYZE when the Page Index is not checked because their row groups were already eliminated (with a Bloom Filter or row group statistics).
yes
New metrics in `EXPLAIN ANALYZE`, documented in docs/source/user-guide/explain-usage.md
=> parquet: Make page_index/pushdown metrics consistent with row_group metrics

datafusion-cli/src/main.rs, datafusion/execution/src/runtime_env.rs
Closes #12554
- Move existing functionality of `RuntimeEnv::new` to `RuntimeEnv::try_new`
- Replace all calls to `RuntimeEnv::new` in code and documentation to use `RuntimeEnv::try_new`
No extra tests required. Ensured that compilation, existing tests, and doc tests pass.
None.
=> Add `RuntimeEnv::try_new` and deprecate `RuntimeEnv::new`

datafusion-examples/examples/external_dependency/query-aws-s3.rs, datafusion/core/src/execution/context/mod.rs
Fixes https://github.com/apache/datafusion/issues/12551
As described on https://github.com/apache/datafusion/issues/12551 the current non consuming API was confusing and caused silently ignored bugs
1. Make SessionContext::enable_url_table consume self
2. Fix bug in example use
3. Add an "into_builder" API to SessionContext to make it easier to work with the builder pattern
4. Update documentation
=> Make SessionContext::enable_url_table consume self

datafusion/core/src/datasource/file_format/mod.rs
Closes #.
Currently if the file/stats format is in `BinaryArray` and we attempt to coerce it into `BinaryViewArray`, the stats will be NULL because type mismatch.
This PR fix it.
Related to #12092 and #6906
In particular, consider this query (simplified Q21 from clickbench):
```sql
SELECT MIN("URL") FROM hits;
```
Datafusion is able to [compeletely remove](https://github.com/apache/datafusion/blob/main/datafusion/physical-optimizer/src/aggregate_statistics.rs#L64) `ParquetExec` based on the statistics, as shown in the physical plan below:
```
Q21: SELECT MIN("URL") FROM hits;
=== Optimized logical plan ===
Aggregate: groupBy=[[]], aggr=[[min(hits.URL)]]
TableScan: hits projection=[URL]
=== Physical plan with metrics ===
ProjectionExec: expr=[ as min(hits.URL)], metrics=[output_rows=1, …
```
=> fix parquet infer statistics for BinaryView types

datafusion/common/src/test_util.rs
N/A
While reviewing https://github.com/datafusion-contrib/datafusion-functions-extra/pull/2 from @dmitrybugakov  I realized there is no doc example of how to use this macro
Add doc example
Yes by doc ci
Only docs, no functional changes
=> Minor: add example to of assert_batches_eq

datafusion/common/src/dfschema.rs, datafusion/optimizer/src/single_distinct_to_groupby.rs, datafusion/sqllogictest/test_files/select.slt
N/A.
The following logic was introduced for `single_distinct_to_groupby` in #4050.  
The reason was the lack of alias-with-qualifier, which caused the qualifier to be lost after alias. See [comment](https://github.com/apache/datafusion/pull/4050#discussion_r1011990524)
When searching for a qualified name in DFSchema, we must also check unqualified fields because they may have been aliased and previously had a qualifier. We can now use qualified aliases to avoid this.
https://github.com/apache/datafusion/blob/0243ebd585264852be55822e3504be54e1e0e406/datafusion/common/src/dfschema.rs#L358-L369
By existing tests.
No
=> Use qualified aliases to simplify searching DFSchema

datafusion/core/src/datasource/listing/table.rs, datafusion/core/src/datasource/physical_plan/parquet/mod.rs, datafusion/core/tests/parquet/file_statistics.rs, datafusion/core/tests/sql/path_partition.rs, datafusion/physical-plan/src/execution_plan.rs
Closes #12416.
Fix the bug mentioned in #12416.
Unlike what was mentioned in #12416, I chose to return absent stats because it's hard to know the selectivity of the filters, and also, for filters that can be resolved using only partition cols, there's no need to pushdown them to the TableScanExec, which would otherwise produce useless `unhandled` pruning predicate.
Yes
=> return absent stats when filters are pushed down

datafusion/physical-plan/src/memory.rs
While working with `MemoryExec`, I noticed it's output is pretty ugly, especially with `dbg!` where I'd expect output across multiple lines.
I don't necessarily agree with the subset of fields included, but I didn't change it.
Make `MemoryExec` easy to understand.
Change the impl of `fmt::Debug` for `MemoryExec` to use the standard `debug_struct` approach
No, `Debug` implementations generally aren't. I ran it locally.
no
=> make `Debug` for `MemoryExec` prettier

datafusion/core/src/execution/session_state.rs
Closes #12553
This PR provides an API for adding `ObjectStore`s to a `SessionStateBuilder`'s `RuntimeEnv` by introducing the new method: `SessionStateBuilder::with_object_store`.
I add a doctest to document and validate the new method.
None
=> Add  `SessionStateBuilder::with_object_store` method

datafusion/core/src/datasource/listing/table.rs, datafusion/physical-expr-common/src/sort_expr.rs, datafusion/physical-plan/src/sorts/sort.rs, datafusion/physical-plan/src/sorts/sort_preserving_merge.rs
Part of https://github.com/apache/datafusion/issues/12446
Closes #.
Basically while working on https://github.com/apache/datafusion/pull/12562 I got annoyed at the lack of documentation and display implementations as well as how award it was to create `PhysicalSortExprs`.
1. Added a bunch of docs and display impls and examples
Yes, by CI and doc tests
Better docs, easier to use APIs.
No API changes
=> Add Docs and Examples and helper methods to `PhysicalSortExpr` 

Cargo.toml, pre-commit.sh
It's very frustrating when working on datafusion that unused imports cause scripts and tests to fail at build time, and not run.
Also, while looking in to this, it seems the `pre-commit.sh` script wasn't failing when clippy failed.
This doesn't affect CI where unused imports will still cause failure I believe.
* remove `unused_imports = "deny"` from the root `Cargo.toml`, so the default behaviour of warning occurs
* make `pre-commit.sh` fail if clippy fails
Manually, yes.
No.
=> Warn instead of error for unused imports

datafusion/core/tests/fuzz_cases/sort_preserving_repartition_fuzz.rs, datafusion/physical-expr-common/src/physical_expr.rs, datafusion/physical-expr/src/equivalence/class.rs, datafusion/physical-expr/src/equivalence/mod.rs, datafusion/physical-expr/src/equivalence/ordering.rs, datafusion/physical-expr/src/equivalence/properties.rs, datafusion/physical-plan/src/filter.rs, datafusion/physical-plan/src/windows/mod.rs
Part of https://github.com/apache/datafusion/issues/12446
Closes #.
Basically while working on https://github.com/apache/datafusion/pull/12562 I found printing out and understanding `EquivalenceProperties` to be hard and I really liked the way @berkaysynnada  formatted them in the comments here https://github.com/apache/datafusion/issues/12446#issuecomment-2363159349
For example:
```
order: [a@0 ASC,c@2 DESC], const: [b@1]
```
1. Implement code to format `EquivalenceProperties` in an easier to use way
2. Improve documentation 
3. Add example
4. Rename `EquivalenceProperties::add_constants`  to `EquivalenceProperties::with_constants` so it conforms to an API that consumes `self` (leaving a deprecated `EquivalenceProperties::add_constants`  to assist migration)
Yes, by CI and doc tests …
=> Improve documentation and add `Display` impl to `EquivalenceProperties`

datafusion/physical-plan/src/aggregates/group_values/row.rs, datafusion/physical-plan/src/aggregates/mod.rs
Closes https://github.com/apache/datafusion/issues/12542
Non-nested arrays were already being dictionary encoded again if the input was dictionary encoded, so this just replicates that behavior for structs and lists.
1) Check whether there are any nested dictionaries to encode.
2) Encode arrays that have nested dictionaries appropriately.
Note this may not be conclusive, I've only included lists and structs since those are the cases/types that I need and that I'm most familiar with. I think it'd be nice to get these changes in though and handle any further cases in separate PRs.
Yes, added a unit test that tests precisely the scenario that led me to opening the issue.
No, only a bug fix. If the queries didn't panic before it could have been a change in behavior, but since all queries of …
=> physical-plan: Cast nested group values back to dictionary if necessary

datafusion/core/src/datasource/physical_plan/parquet/metrics.rs, datafusion/core/src/datasource/physical_plan/parquet/mod.rs, datafusion/core/src/datasource/physical_plan/parquet/opener.rs, datafusion/core/src/datasource/physical_plan/parquet/row_filter.rs, datafusion/core/src/datasource/physical_plan/parquet/row_group_filter.rs, docs/source/user-guide/explain-usage.md
Closes #12584.
This allows both Datafusion developers and users to better measure the impact of their optimizations. For example, I am working on #12547 (caching the page index), and my patch makes these metrics go from:
> statistics_eval_time=775.283531ms, row_pushdown_eval_time=191ns, time_elapsed_scanning_until_data=16.463873ms, time_elapsed_processing=401.16043928s, **time_elapsed_opening=473.912060225s**, page_index_eval_time=24.19564ms, **metadata_load_time=410.282903954s**, bloom_filter_eval_time=62.038167937s, time_elapsed_scanning_total=16.516948ms
to 
> row_pushdown_eval_time=191ns, time_elapsed_scanning_until_data=1.143893882s, time_elapsed_processing=34.501308377s, **time_elapsed_opening=67.214927741s**, page_index_eval_time=32.002383ms, **metadata_load_time=3.411246ms**, …
=> parquet: Add finer metrics on operations covered by `time_elapsed_opening`

datafusion/functions-aggregate/src/variance.rs, datafusion/sqllogictest/test_files/aggregate.slt
Closes #12616.
The bug was in the orginal implementation in #12095. This fixes the
issue and modify a test case such that it would have caught it.
Current code panics in debug builds and produces incorrect results in release.
Use `staturating_sub` instead to correct the behavior.
Modified test case.
No,
=> fix: Panic/correctness issue in variance GroupsAccumulator

datafusion/sql/src/unparser/expr.rs
No relevant issue
Datafusion enforces an eager cast of value to dictionary value in the logical plan where a comparison with dictionary value is presented. For example, in the following plan
```SQL
Filter: person_mood.mood_status = CAST(Utf8("happy") AS Dictionary(Int8, Utf8)) 
```
However, when using unparser to convert the plan back to sql, where the sql will be sent to various query engine (PostgreSQL, MySQL, etc.) the cast is not needed for the value, in the example above the value `happy`, since the raw value can be directly used in SQL engines without casting to an engine specific dictionary type. Therefore, the plan can simply be rewritten into
```SQL
where person_mood.mood_status = 'happy' 
```
* Directly pass `inner_expr` instead of `cast inner_expr as dictionary` in the …
=> Use original value when comparing with dictionary column in unparser

datafusion/sql/src/unparser/plan.rs, datafusion/sql/tests/cases/plan_to_sql.rs
No corrsponding issue.
Consider the following SQL:
```SQL
WITH 
w1 AS (SELECT 'a' as col),
w2 AS (SELECT 'b' as col),
w3 as (SELECT 'c' as col)
SELECT * FROM w1 UNION ALL SELECT * FROM w2 UNION ALL SELECT * FROM w3
```
If a plan contains more than two UNION statements, it cannot be properly unparsed back into an SQL string.
Fix the unparsing behavior for UNION.
yes
no
=> Fix to unparse the plan with multiple UNION statements into an SQL string

datafusion/sql/src/unparser/expr.rs
No correlated issue
The unparser omits the float scalar value information, causing incorrect sql from unparser.
When sending a query like 
```
select * from inventory where inv_warehouse_sk between 3.0/2.0 AND 4.0/2.0
```
to Datafusion, the query plan related to the scalar value is 
```
Filter: CAST(inventory.inv_warehouse_sk AS Float64) BETWEEN Float64(3) / Float64(2) AND Float64(4) / Float64(2)`. 
```
However, the unparser omits the `Float64()` information, causing wrong query from unparser
```SQL
SELECT "inventory"."inv_date_sk", "inventory"."inv_item_sk", "inventory"."inv_warehouse_sk", "inventory"."inv_quantity_on_hand" FROM "inventory" WHERE (CAST("inventory"."inv_warehouse_sk" AS DOUBLE PRECISION) BETWEEN (3 / 2) AND (4 / 2))
```
This will cause incorrect data in some engine, for …
=> Keep the float information in scalar_to_sql

datafusion/sqllogictest/src/engines/datafusion_engine/normalize.rs, datafusion/sqllogictest/test_files/aggregate.slt, datafusion/sqllogictest/test_files/coalesce.slt, datafusion/sqllogictest/test_files/copy.slt, datafusion/sqllogictest/test_files/dictionary.slt, datafusion/sqllogictest/test_files/group_by.slt, datafusion/sqllogictest/test_files/joins.slt, datafusion/sqllogictest/test_files/regexp.slt, datafusion/sqllogictest/test_files/select.slt, datafusion/sqllogictest/test_files/string/dictionary_utf8.slt, datafusion/sqllogictest/test_files/string/large_string.slt, datafusion/sqllogictest/test_files/string/string.slt, datafusion/sqllogictest/test_files/string/string_query.slt.part, datafusion/sqllogictest/test_files/string/string_view.slt, datafusion/sqllogictest/test_files/topk.slt
Part of #12415 .
Add the test for dictionary Utf8
no
=> Add Dictionary String (UTF8) type to String sqllogictests

datafusion/core/src/physical_optimizer/coalesce_batches.rs, datafusion/core/src/physical_optimizer/enforce_distribution.rs, datafusion/core/src/physical_optimizer/enforce_sorting.rs, datafusion/core/src/physical_optimizer/join_selection.rs, datafusion/core/src/physical_optimizer/optimizer.rs, datafusion/core/src/physical_optimizer/projection_pushdown.rs, datafusion/core/src/physical_optimizer/sanity_checker.rs, datafusion/core/src/physical_optimizer/update_aggr_exprs.rs, datafusion/physical-optimizer/src/aggregate_statistics.rs, datafusion/physical-optimizer/src/combine_partial_final_agg.rs, datafusion/physical-optimizer/src/limit_pushdown.rs, datafusion/physical-optimizer/src/limited_distinct_aggregation.rs, datafusion/physical-optimizer/src/optimizer.rs, datafusion/physical-optimizer/src/topk_aggregation.rs
Part of #12555 
Supporting [SessionStateBuilder](https://docs.rs/datafusion/latest/datafusion/execution/session_state/struct.SessionStateBuilder.html) to implement Debug
1. Require `Debug` for PhysicalOptimizerRule
2. `#derive` Debug where necessary
~~3. Add a `&` to take a `&JoinType` in `EnforceDistribution` (not sure why this wasn't a `cargo check` error but rust-analyzer showed it and types seem to require it)~~
By CI and the compiler
API change for `PhysicalOptimizerRule` which now requires Debug
=> Require `Debug` for `PhysicalOptimizerRule`

datafusion/core/src/physical_optimizer/sanity_checker.rs, datafusion/physical-expr-common/src/sort_expr.rs, datafusion/physical-expr/src/partitioning.rs
Part of https://github.com/apache/datafusion/issues/12446
Today when the SanityChecker fails it is not always clear why and dumps out a message like thisL
> Error during planning: Plan: ["SortPreservingMergeExec: [d@4 ASC NULLS LAST,c@1 ASC NULLS LAST,a@2 ASC NULLS LAST,a0@3 ASC NULLS LAST,b@0 ASC NULLS LAST], fetch=2", "  UnionExec", "    SortExec: TopK(fetch=2), expr=[d@4 ASC NULLS LAST,c@1 ASC NULLS LAST,a@2 ASC NULLS LAST,b@0 ASC NULLS LAST], preserve_partitioning=[false]", "      ProjectionExec: expr=[b@1 as b, c@2 as c, a@0 as a, NULL as a0, d@3 as d]", "        CsvExec: file_groups={1 group: [[Users/andrewlamb/Software/datafusion2/datafusion/core/tests/data/window_2.csv]]}, projection=[a, b, c, d], output_ordering=[c@2 ASC NULLS LAST], has_header=true", "    SortExec: …
=> Improve SanityChecker error message

datafusion/physical-plan/src/aggregates/group_values/column.rs, datafusion/physical-plan/src/aggregates/group_values/group_column.rs, datafusion/physical-plan/src/aggregates/group_values/mod.rs
Follow on to https://github.com/apache/datafusion/pull/12269 from @jayzhan211
As I was reviewing the code, the names of the modules don't quite match their contents and aren't consistent with `row.rs`, so I would like to fix that as we begin to work on this code more
Changes:
1. rename modules to match contents and reflect structure.
2. rename `ArrowRowEq` to `GroupColumn` as I think that better reflects what the trait does
CI tests
=> Rename aggregation modules, GroupColumn

datafusion/core/src/dataframe/mod.rs, datafusion/expr/src/expr_schema.rs, datafusion/expr/src/logical_plan/builder.rs, datafusion/functions/src/core/coalesce.rs, datafusion/functions/src/datetime/to_local_time.rs, datafusion/functions/src/encoding/inner.rs, datafusion/functions/src/unicode/strpos.rs, datafusion/functions/src/unicode/substr.rs, datafusion/sqllogictest/test_files/encoding.slt, datafusion/sqllogictest/test_files/functions.slt, datafusion/sqllogictest/test_files/scalar.slt, datafusion/sqllogictest/test_files/select.slt, datafusion/sqllogictest/test_files/string/string_literal.slt, datafusion/sqllogictest/test_files/timestamps.slt
=> fix: coalesce schema issues

datafusion/functions/src/string/common.rs
Follow on to https://github.com/apache/datafusion/pull/12395 from @Rachelint 
Part of reviewing https://github.com/apache/datafusion/pull/12395I spent some non trivial time reading this code, and I wanted to encodde my learnings as comments
1. Add comments to various functions
2. Update parameter names
No code, just docs and name changes
No, this is all internal code
=> Minor: improve documentation to StringView trim

datafusion/physical-plan/src/sorts/sort.rs
Closes #.
Minor changes in the Sort code to improve readability.
=> [MINOR]: Simplifications Sort Operator

datafusion/physical-plan/src/repartition/mod.rs
Closes #.
`Partitioning` information is already present in the `cache` member of the `RepartitionExec`. Hence, storing it separately is redundant. This Pr removes it.
=> [Minor] Remove redundant member from RepartitionExec

datafusion/core/src/execution/context/avro.rs, datafusion/core/src/execution/context/csv.rs, datafusion/core/src/execution/context/json.rs, datafusion/core/src/execution/context/mod.rs, datafusion/core/src/execution/context/parquet.rs
Closes #.
Changing `&str` into `impl Into<TableReference>` to be consistent with the `register_table` function.
Before:
```rust
pub async fn register_listing_table(
&self,
name: &str,
table_path: impl AsRef<str>,
options: ListingOptions,
provided_schema: Option<SchemaRef>,
sql_definition: Option<String>,
) -> Result<()> {
```
After:
```rust
pub async fn register_listing_table(
&self,
table_ref: impl Into<TableReference>,
table_path: impl AsRef<str>,
options: ListingOptions,
provided_schema: Option<SchemaRef>,
sql_definition: Option<String>,
) -> Result<()> {
```
The modified functions include:
- register_listing_table
- register_avro
- register_csv
- register_json
- register_parquet
=> Update `register_table` functions args to take `Into<TableReference>`

datafusion/common/src/utils/mod.rs, datafusion/functions-aggregate-common/src/aggregate/groups_accumulator.rs, datafusion/functions-aggregate/src/first_last.rs, datafusion/physical-plan/src/sorts/partial_sort.rs, datafusion/physical-plan/src/sorts/sort.rs, datafusion/physical-plan/src/windows/bounded_window_agg_exec.rs
Closes #.
As in the [suggestion](https://github.com/apache/datafusion/pull/12639#discussion_r1778531190), this PR renames the util function `get_arrayref_at_indices` to `take_arrays`. 
Also, type of the `indices` parameter is changed from `&PrimitiveArray<UInt32Type>` to `&dyn Array` to make it similar to `compute::take`'s API.
=> [MINOR]: Rename get_arrayref_at_indices to take_arrays

datafusion/common/src/utils/mod.rs, datafusion/physical-plan/src/repartition/mod.rs
Follow #12654 
gently ping @comphead @akurmustafa 
`get_arrayref_at_indices` is no longer exist.
No
I encountered a compile error on the current main branch. After renaming `get_arrayref_at_indices`, Cargo was able to compile the code for me.
No
=> [MINOR]:  Use take_arrays in repartition 

datafusion/expr-common/src/type_coercion/binary.rs, datafusion/sqllogictest/test_files/binary_view.slt
Closes #12500
a step forward to enable reading StringViewArray by default from Parquet 
add binary_view to  string_view coercion
yes , add a slt test case 
I also test manually 
change `benchmarks/src/clickbench.rs` , make **force_view_types = true**
```rust
config
.options_mut()
.execution
.parquet
.schema_force_view_types = true
```
```sh 
cargo build 
cargo run --bin dfbench -- clickbench --iterations 1  \
--path data/hits_partitioned \
--queries-path queries/clickbench/queries.sql  \
-o ./clickbench_partitioned.json
``` 
all 43 query completed.
No, since force_view_type default is still false.
=> Add binary_view to string_view coercion

datafusion/physical-expr/src/expressions/binary/kernels.rs
=> [Minor] Improve error message when bitwise_* operator takes wrong unsupported type

datafusion/common/src/utils/mod.rs
Follow on to https://github.com/apache/datafusion/pull/12654
@mustafasrepo  ported `take_arrays` upstream to arrow-rs in https://github.com/apache/arrow-rs/pull/6475
Let's leave a link to that so our future selves know we can remove the copy in DataFusion
Add a doc link
=> Minor: Add github link to code that was upstreamed

datafusion/execution/src/stream.rs, datafusion/physical-plan/src/execution_plan.rs, datafusion/physical-plan/src/repartition/mod.rs, datafusion/physical-plan/src/sorts/merge.rs, datafusion/physical-plan/src/sorts/sort_preserving_merge.rs
Related to https://github.com/apache/datafusion/issues/12641 and https://github.com/apache/datafusion/pull/12642
https://github.com/apache/datafusion/pull/12642 proposes changing the current behavior on error. While reviewing that code I realized the current behavior is not well documented. 
Document the error handling behavior better
N/A
Just documentation, no functional changes
=> Minor: Improve documentation on execution error handling

datafusion/expr/src/lib.rs, datafusion/expr/src/udwf.rs, datafusion/physical-plan/src/windows/mod.rs
Part of #8709.
Closes #12661.
1. So that a user-defined window function can customize the implementation for evaluating results in reverse order, allowing the optimizer to avoid sorting the data.
2. Check if `IGNORE NULLS` is set.
3. Easier to review a smaller diff compared to a PR converting an existing built-in window function.
1. Extends `WindowUDFExpr` with two new state fields for tracking if a window expression is reversed, and if `IGNORE NULLS` is used in the query.
```rust
/// Implements [`BuiltInWindowFunctionExpr`] for [`WindowUDF`]
#[derive(Clone, Debug)]
struct WindowUDFExpr {
...,
/// This is set to `true` only if the user-defined window function
/// expression supports evaluation in reverse order, and the
/// evaluation order is reversed.
is_reversed: bool,
/// Set to `true` …
```
=> Adds `WindowUDFImpl::reverse_expr`trait method + Support for `IGNORE NULLS`

datafusion/physical-plan/src/aggregates/row_hash.rs
Closes #.
I found an partial assertion check may be needed in skip aggregation probe, this pr added it.
https://github.com/apache/datafusion/pull/12332#discussion_r1776203466
Add an assertion to ensure and emphasize that skip aggregation probe will only be called in partial aggregation.
Test by exist tests.
No.
=> Minor: add partial assertion for skip aggregation probe

datafusion/physical-expr/src/utils/guarantee.rs
Minor change so no associated issue - hopefully that's okay, I see comparable "minor" PRs get merged.
With https://github.com/apache/datafusion/pull/8654/files, this (non-public) function is no longer fallible, so could read a little more clearly if the name and return type reflects that.
Rename `LiteralGuarantee::try_new` to new and have it return `Self` rather than `Option<Self>`.
Yes, existing tests pass.
None.
=> Minor: Change LiteralGuarantee try_new to new

datafusion/expr/src/lib.rs, datafusion/expr/src/udaf.rs, datafusion/functions-aggregate/src/count.rs, datafusion/functions-aggregate/src/min_max.rs, datafusion/physical-optimizer/src/aggregate_statistics.rs, datafusion/physical-plan/src/lib.rs
=> Add `value_from_statisics` to AggregateUDFImpl, remove special case for min/max/count aggregate statistics

datafusion/physical-plan/src/windows/bounded_window_agg_exec.rs
Closes #.
Simplify `required_input_ordering` method of the `BoundedWindowAggExec`.
=> [MINOR]: Simplify required_input_ordering of BoundedWindowAggExec

datafusion/physical-expr/src/window/nth_value.rs, datafusion/physical-plan/src/windows/mod.rs, datafusion/sqllogictest/test_files/window.slt
Closes #12320.
The root cause in #12320 is because `get_signed_integer_value` will return an error on `NULL` or `Int64(NULL)` value. To process the `nth_value` function, it requires the `n` value should be an integer. Therefore, I decided to convert `NULL` value to 0 in `get_signed_integer_value` and implement handler for the `0` case. This will evaluate to NULL value for the `nth_value(v1, NULL)` expression.
Furthermore, it also evaluate the `nth_value(v1, 0)` to NULL instead of generating panic, which match the expected behaviour in duckdb.
[x] Return 0 for NULL value in `get_signed_integer`
[x] Handle nth_value execution when n is 0
[x] Test file updated to test `nth_value(v2, 0)`, `nth_value(v2, NULL)` and `nth_value(v2, v2 * NULL)`.
Yes
=> handle 0 and NULL value of NTH_VALUE function

datafusion/expr/src/udaf.rs
Follow on to https://github.com/apache/datafusion/pull/12296
Related to https://github.com/apache/datafusion/issues/11151
@edmondop  added`AggregateUDFImpl::value_from_stats` in https://github.com/apache/datafusion/pull/12296 (❤️ ) and I had some suggestions to improve the documentation
1. Add documentation 
2. 
Docs CI
Just Docs, no functional changes
=> Improve documentation for AggregateUDFImpl::value_from_stats

datafusion/core/src/catalog_common/mod.rs, datafusion/sql/src/parser.rs, datafusion/sql/src/statement.rs, datafusion/sql/tests/sql_integration.rs, datafusion/sqllogictest/test_files/create_external_table.slt
Closes #12607
This PR adds the ability to create external tables with qualified names.
I add a unit  test to verify the expected behaviour in the issue. Namely, a call to `create external table staging.foo` should be a `TableReference::Partial {schema: "staging", table: "foo"}` qualified reference.
I also add two sqllogic tests to check happy path and error case where there is no schma that the qualified name maps to.
Yes there are user-facing changes. Previously, external tables with qualified names was unsupported.
=> Add support for external tables with qualified names

datafusion/functions/src/regex/regexplike.rs, datafusion/functions/src/regex/regexpmatch.rs, datafusion/sqllogictest/test_files/regexp.slt, datafusion/sqllogictest/test_files/string/dictionary_utf8.slt, datafusion/sqllogictest/test_files/string/string.slt, datafusion/sqllogictest/test_files/string/string_query.slt.part, datafusion/sqllogictest/test_files/string/string_view.slt
Closes #12664.
As pointed out in the original issue, `REGEX_MATCH` and `REGEX_LIKE` fail if the first argument is `LargeUtf8` but the second (or third) argument is `Utf8`. We were performing `as_generic_string_array::<i64>` on `&GenericStringArray<i32>`, which caused the issue.
Regex Match implementation in Apache Arrow requires the input and patterns [to have the same type](https://github.com/apache/arrow-rs/blob/3293a8c2f9062fca93bee2210d540a1d25155bf5/arrow-string/src/regexp.rs#L409), and the flags [to have the same type as well](https://github.com/apache/arrow-rs/blob/3293a8c2f9062fca93bee2210d540a1d25155bf5/arrow-string/src/regexp.rs#L430). I have reflected this change in the function signatures. 
Yes, by `string_query.slt.part`
No, only a bugfix.
=> Fix Regex signature types

datafusion/physical-plan/src/aggregates/group_values/group_column.rs
Follow on to #12269 from @jayzhan211 and https://github.com/apache/datafusion/pull/12623
Part of #12680
https://github.com/apache/datafusion/pull/12623 added a more performant way to track nulls in the `PrimitiveGroupValueBuilder`. Let's use the same thing for Strings/Binary views to reduce replication 
1. Refactor `ByteGroupValueBuilder` to use `MaybeNullBufferBuilder` to track nulls
Yes, by existing CI
No, this is an internal refactor
Performance (basically all changes within measurement threshold in my opinion)
```
Benchmark clickbench_partitioned.json
┏━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━┓
┃ Query        ┃  main_base ┃ alamb_boolean_string_groups ┃       Change ┃ …
```
=> Refactor `ByteGroupValueBuilder` to use `MaybeNullBufferBuilder`

docs/source/user-guide/sql/data_types.md
None
[Data Types](https://datafusion.apache.org/user-guide/sql/data_types.html) shows `X'1234` as an example of a hex string literal, but it's not syntactically valid.
Adds a closing quotation mark to make it valid.
```
$ datafusion-cli
❯ select X'1234;  🤔 Invalid statement: sql parser error: Unterminated string literal at Line: 1, Column 9
❯ select X'1234';
+-----------------+
| Binary("18,52") |
+-----------------+
| 1234            |
+-----------------+
1 row in set. Query took 0.000 seconds.
```
=> doc: Fix malformed hex string literal in user guide

datafusion/expr/src/type_coercion/functions.rs
Remove conditions where unnecessary.
Refactor to improve readability.
=> Simplify match patterns in coercion rules

datafusion-cli/Cargo.lock, datafusion/functions-aggregate/Cargo.toml, datafusion/functions-aggregate/src/macros.rs
DataFusion is a SQL query engine and also a reusable library for
building query engines. The core functionality should not depend on
frontend related functionalities like `sqlparser` or `datafusion-sql`.
=> Remove aggregate functions dependency on frontend

datafusion/physical-plan/src/aggregates/row_hash.rs
While working on #12697, I discovered the change. Since this change is not negligible, I’ve separated it to ensure more accurate benchmarking results for #12697.
```
Benchmark clickbench_1.json
┏━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Query        ┃       main ┃ rm-clone-v4 ┃        Change ┃
┡━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ QQuery 0     │     0.53ms │      0.42ms │ +1.25x faster │
│ QQuery 1     │    45.57ms │     44.49ms │     no change │
│ QQuery 2     │    88.79ms │     80.65ms │ +1.10x faster │
│ QQuery 3     │    74.46ms │     67.41ms │ +1.10x faster │
│ QQuery 4     │   423.98ms │    391.22ms │ +1.08x faster │
│ QQuery 5     │   678.29ms │    673.73ms │     no change │
│ QQuery 6     │ …
```
=> Minor: Remove clone in `transform_to_states`

datafusion/physical-expr/src/equivalence/ordering.rs, datafusion/physical-expr/src/equivalence/properties.rs
Part of https://github.com/apache/datafusion/issues/12446, broken out of https://github.com/apache/datafusion/pull/12562 for easy review
In order to write tests for https://github.com/apache/datafusion/issues/12446 I found I needed to be able to set SortOptions and constants more easily.
1. Refactor the tests for union property calculation into a structure.
2. Add `#[ignored]` tests for https://github.com/apache/datafusion/issues/12446
Only tests
No functional changes
=> Refactor tests for union sorting properties, add tests for unions and constants

datafusion/optimizer/src/analyzer/count_wildcard_rule.rs, datafusion/sql/src/expr/function.rs, datafusion/sqllogictest/test_files/aggregate.slt
=> Fix: support Qualified Wildcard in count aggregate function

datafusion/physical-plan/src/aggregates/group_values/column.rs, datafusion/physical-plan/src/aggregates/group_values/group_column.rs
Part of https://github.com/apache/datafusion/issues/12680
As suggested by @Dandandan in https://github.com/apache/datafusion/pull/12623#discussion_r1781444375
We can avoid some duplication using const generics
Use const generics rather than manually copied implementation to avoid duplication
Existing tests
Benchmark results (realistically no change)
```
Benchmark clickbench_partitioned.json
┏━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Query        ┃  main_base ┃ alamb_const_generics ┃        Change ┃
┡━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ QQuery 0     │     2.33ms │               2.35ms │     no change │
│ QQuery 1     │    39.78ms │              39.59ms │     no change │
│ QQuery 2     │ …
```
=> Reduce code duplication in `PrimitiveGroupValueBuilder` with const generics

datafusion-cli/Cargo.lock, datafusion/common/src/dfschema.rs, datafusion/core/src/dataframe/mod.rs, datafusion/expr/Cargo.toml, datafusion/expr/src/logical_plan/plan.rs, datafusion/expr/src/utils.rs, datafusion/optimizer/tests/optimizer_integration.rs, datafusion/sql/src/planner.rs, datafusion/sql/src/relation/join.rs, datafusion/sqllogictest/test_files/join.slt
Closes #11464
Closes #11408
In https://github.com/apache/datafusion/pull/6091 we relaxed and allowed duplicated qualified fields in order to support duplicated group bys. This leads to some confusion and bugs as we do not allow for unqualified duplicated names. This makes the necessary changes to still support duplicated group by while still disallowing duplicated qualified names.
Revert allowing duplicated qualified names from #6091
Deduplicate group by exprs when creating output schema for LogicalPlan::Aggregate.
Remove test case `with_column_self_join` as this test no fails already at the join, I don't think it possible to modify to fulfill it old purpose.
The old logic in `plan_table_with_joins` would create schemas with duplicated fields as it would end up with multiple copies for …
=> Disallow duplicated qualified field names

datafusion/functions/Cargo.toml, datafusion/functions/benches/encoding.rs, datafusion/functions/src/encoding/inner.rs
Closes #.
It is generally faster to make a big allocation up front, rather than making many small allocations.
- Add a benchmark
- Refactor to reduce code duplication
- Change decoding methods to write into pre-allocated buffer
Relying on existing SQL tests.
Yes, base64 and hex decoding is ~2x faster:
```
base64_decode/1024      time:   [26.362 µs 26.459 µs 26.597 µs]
change: [-48.501% -47.320% -45.897%] (p = 0.00 < 0.05)
3 (3.00%) high severe
hex_decode/1024         time:   [92.789 µs 92.904 µs 93.035 µs]
change: [-58.973% -58.895% -58.816%] (p = 0.00 < 0.05)
Found 5 outliers among 100 measurements (5.00%)
base64_decode/4096 …
```
=> Optimize base64/hex decoding by pre-allocating output buffers (~2x faster)

datafusion/core/src/physical_planner.rs, datafusion/core/tests/user_defined/user_defined_plan.rs, datafusion/expr/src/logical_plan/extension.rs, datafusion/optimizer/src/analyzer/subquery.rs, datafusion/optimizer/src/optimize_projections/mod.rs, datafusion/optimizer/src/push_down_filter.rs, datafusion/optimizer/src/push_down_limit.rs, datafusion/optimizer/src/test/user_defined.rs, datafusion/proto/tests/cases/roundtrip_logical_plan.rs, datafusion/substrait/tests/cases/roundtrip_logical_plan.rs
Closes #12679.
As per issue depicted.
Modify `UserDefinedLogicalNodeCore`/`UserDefinedLogicalNode` traits to check if its safe to push the limit to the children or not, via `allows_limit_to_inputs`, and also update the related interfaces.
Yes, I've add several tests in `datafusion/optimizer/src/push_down_limit.rs`. Please correct me if it's wrong cases or needs more tests.
No user-facing changes.
But, interface changed in `UserDefinedLogicalNodeCore`/`UserDefinedLogicalNode` traits.
=> Support `LIMIT` Push-down logical plan optimization for `Extension` nodes

datafusion/core/src/datasource/avro_to_arrow/arrow_array_reader.rs
Resolves #12682
Nullable values are passed as unions and this requires a resolving of the union to have the correct null_buffer size.
Added a new test for this issue
=> Fix AvroReader: Add union resolving for nested struct arrays

datafusion-cli/Cargo.lock, datafusion/functions-window/Cargo.toml, datafusion/functions-window/src/lib.rs, datafusion/functions-window/src/macros.rs, datafusion/functions-window/src/row_number.rs
Closes #12688.
Part of https://github.com/apache/datafusion/issues/8709.
Follow-on to PR https://github.com/apache/datafusion/pull/12030.
A set of [convenience macros similar to user-defined aggregate functions](https://github.com/apache/datafusion/blob/main/datafusion/functions-aggregate/src/macros.rs) for defining user-defined window functions.
Writing this code for every user-defined window function is tedious. https://github.com/apache/datafusion/blob/e1b992a7878e78e8a63b7e24425c665727bda493/datafusion/functions-window/src/row_number.rs#L35-L54
The above code gets replaced by this macro:
```rust
define_udwf_and_expr!(
RowNumber,
row_number,
"Returns a unique row number for each row in window partition beginning at 1."
);
```
Defines the following new macros:
1. `get_or_init_udwf!` - …
=> Adds macros for creating `WindowUDF` and `WindowFunction` expression

datafusion/sql/src/unparser/plan.rs, datafusion/sql/src/unparser/utils.rs, datafusion/sql/tests/cases/plan_to_sql.rs
Follow up PR for [feat: support unparsing LogicalPlan::Window nodes](https://github.com/apache/datafusion/pull/10767/) and making Aggreagation unparsing more robust.
1. Adds support for unparsing plans containing simultaneously Aggregation and [Window functions](https://www.postgresql.org/docs/current/tutorial-window.html). Existing version fails with error `Tried to unproject agg expr not found in provided Aggregate!` This makes unparsing to correctly handle [TPC-DS](https://github.com/apache/datafusion-benchmarks/tree/main/tpcds/queries) Q47, Q53, Q57, Q63, Q89
2. Improves unparsing of Aggregations containing GroupingSet (for example when using `ROLLUP`).   Existing version panics with `called `Option::unwrap()` on a `None` value`. This makes unparsing to correctly handle …
=> Support unparsing plans with both Aggregation and Window functions

datafusion/functions/src/unicode/strpos.rs, datafusion/sqllogictest/test_files/functions.slt, datafusion/sqllogictest/test_files/scalar.slt
In 1b3608da7ca59d8d987804834d004e8b3e349d18 `strpos` signature was modified to indicate it supports dictionary as input argument, but the invoke method doesn't support them.
- fixes https://github.com/apache/datafusion/issues/12670
=> Fix strpos invocation with dictionary and null

datafusion/core/tests/fuzz_cases/sort_preserving_repartition_fuzz.rs, datafusion/core/tests/memory_limit/mod.rs, datafusion/physical-plan/src/aggregates/row_hash.rs, datafusion/physical-plan/src/repartition/mod.rs, datafusion/physical-plan/src/sorts/mod.rs, datafusion/physical-plan/src/sorts/sort.rs, datafusion/physical-plan/src/sorts/sort_preserving_merge.rs, datafusion/physical-plan/src/sorts/streaming_merge.rs
Closes #.
Simplification of streaming_merge function parameters, since they're too many (7 currently).
No
=> Simplify streaming_merge function parameters

docs/source/index.rst
Closes #12749.
See #12749.
Just changes to the docs.
Yes. Built and viewed locally.
No.
=> Fix misformatted links on project index page

datafusion/core/src/datasource/file_format/mod.rs, datafusion/physical-plan/src/joins/cross_join.rs, datafusion/physical-plan/src/union.rs, datafusion/sqllogictest/src/test_context.rs, datafusion/sqllogictest/test_files/metadata.slt
Related to #12687 
Closes #12734
Closes https://github.com/apache/datafusion/issues/12735
A https://github.com/apache/datafusion/pull/11989 (and released in 42.0.0) has [added a check](https://github.com/apache/datafusion/blob/322d83526909ab44cfbe34b982d1a1c36a4dbe8f/datafusion/core/src/physical_planner.rs#L676) that the logical and physical plan input schemas (to an aggregate node) are the same.
Once released into the wild, it began being triggered. We [previously fixed a use case with distinct aggregations](https://github.com/apache/datafusion/pull/12691). In this PR we fix two additional use cases for cross joins, and union on null fields.
commit 1 = reproducer for cross join bug, where schema metadata is dropped
commit 2 = fix
commit 3 = cleanup PR, since I noticed field metadata is …
=> Provide field and schema metadata missing on cross joins, and union with null fields.

datafusion/sqllogictest/test_files/string/large_string.slt, datafusion/sqllogictest/test_files/string/string.slt, datafusion/sqllogictest/test_files/string/string_query.slt.part, datafusion/sqllogictest/test_files/string/string_view.slt
Follow on to https://github.com/apache/datafusion/pull/12712
Now that  https://github.com/apache/datafusion/issues/12670  is fixed (thanks @findepi !), we should update the tests to reflect this and keep the string implementations in sync as @goldmedal  suggests: https://github.com/apache/datafusion/pull/12712#issuecomment-2388357130
Remove the workaround in string tests to make sure all implementations are consistent
Only tests
=> Minor: Update string tests for strpos

datafusion/expr-common/src/type_coercion/binary.rs, datafusion/expr/src/logical_plan/builder.rs, datafusion/expr/src/type_coercion/functions.rs, datafusion/functions-nested/src/make_array.rs, datafusion/optimizer/src/analyzer/type_coercion.rs, datafusion/sqllogictest/test_files/array.slt, datafusion/sqllogictest/test_files/errors.slt, datafusion/sqllogictest/test_files/map.slt, datafusion/sqllogictest/test_files/select.slt
Closes #.
* Main: Follow on https://github.com/apache/datafusion/pull/10268. Apply `type_union_resolution ` to Array and Values coercion
* Cleanup: Remove `coerce_arguments_for_fun` and move the coercion logic to `coerce_types`. So does the null to i64 conversion.
=> Apply `type_union_resolution` to array and values

datafusion/physical-plan/src/aggregates/group_values/group_column.rs
Closes #.
I found New added fuzz tests in #12667 failed after #12703 
And after debugging, I found it is due to the change of `equal_to` function in `PrimitiveGroupValueBuilder`. 
I think we should only check row's `value` when this row is not null in both `exist array` and `input array`.Because the actual `value` of row may be meaningless when it is `null`.
Don't check the equality of actual values in `exist row` and `input row`, when both them are nulls.
Test by new uts.
No
=> fix `equal_to` in `PrimitiveGroupValueBuilder`

datafusion/expr/src/udwf.rs
Closes #12756.
Show how to set the name for the result field of a `WindowUDF` using `WindowUDFFieldArgs` argument. 
No, only doc change.
No.
=> Minor: doc how field name is to be set for `WindowUDF`

datafusion/physical-plan/src/aggregates/group_values/group_column.rs
Part of https://github.com/apache/datafusion/issues/12680
While reviewing https://github.com/apache/datafusion/pull/12758 from @Rachelint I wondered if the same issue applied to the String version. It turns out the answer is yes. 
1. Apply the same logic fix in https://github.com/apache/datafusion/pull/12758 to `ByteGroupValueBuilder`
2. I also tried to simplify the logic slightly
Yes, new unit test
=> Fix `equal_to` in `ByteGroupValueBuilder`

datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs, datafusion/sqllogictest/test_files/cse.slt
Closes #12769.
The nullable requirement seem to have been added in #1401 but as far as
I can tell they are not needed for these 2 cases.
I think this can be shown using this truth table: (generated using
datafusion-cli without this patch)
```
> CREATE TABLE t (v BOOLEAN) as values (true), (false), (NULL);
> select t.v, t2.v, t.v AND (t.v OR t2.v), t.v OR (t.v AND t2.v) from t cross join t as t2;
+-------+-------+---------------------+---------------------+
| v     | v     | t.v AND t.v OR t2.v | t.v OR t.v AND t2.v |
+-------+-------+---------------------+---------------------+
| true  | true  | true                | true                |
| true  | false | true                | true                |
| true  |       | true                | true                |
| false | true  | false …
```
=> Allow boolean Expr simplification even when nullable

datafusion/sql/src/unparser/dialect.rs, datafusion/sql/src/unparser/expr.rs, datafusion/sql/src/unparser/utils.rs
PR improves unparsing to generate valid sql for Postgres and `round` scalar function by enforcing `NUMERIC` data type for it.
Postgres requires `NUMERIC` data type for `round` as it does not support `Float` arguments that are produced by default. Right now unparsed sql fails with the error "Query Error function round(double precision, integer) does not exist" if `round` is used.
https://www.postgresql.org/docs/17/functions-math.html 
```
round ( v numeric, s integer ) → numeric
Rounds v to s decimal places. Ties are broken by rounding away from zero.
round(42.4382, 2) → 42.44
round(1234.56, -1) → 1230
```
```
-- SQL Error [42883]: ERROR: function round(double precision, integer) does not exist
select round(CAST(1.23456 AS float), 2)
-- 1.23
select round(CAST(1.23456 AS numeric), 2)
```
1. …
=> Improve `round` scalar function unparsing for Postgres

datafusion/physical-expr/src/equivalence/properties.rs
Closes https://github.com/apache/datafusion/issues/12700
Fixes a bug
1. Remember what dependencies have been processed to avoid an infinite recursion
Note, this is the minimal change I could make to solve the overflow.
While this change I think is reasonable on its own, there may be more to do as well. The comments from @mustafasrepo and @berkaysynnada in https://github.com/apache/datafusion/issues/12700#issuecomment-2389022925 suggest to me that there may be a deeper problem and this PR simply treats the symptom rather than the root cause
Yes, a new unit test is added 
I also verified that this change fixes the end to end .slt tests in https://github.com/apache/datafusion/pull/12721
=> Fix stack overflow calculating projected orderings

datafusion/substrait/src/logical_plan/consumer.rs, datafusion/substrait/src/logical_plan/producer.rs
This partially addresses #7687 (though the issue talks about a python component which is not yet included here)
Adds serialization to and from Substrait's top-level ExtendedExpression message
Yes, new unit tests are added.
New methods.  No changes to existing behavior.
=> feat: add support for Substrait ExtendedExpression

datafusion/functions-aggregate/src/min_max.rs
N/A
While working on https://github.com/apache/datafusion/issues/6906 I found some comments that weren't properly "rust doc" commants and thus don't show up in documentation
Change `//` to `///` in a few places
=> Minor: improve docs on MovingMin/MovingMax

datafusion/sqllogictest/test_files/order.slt
Closes https://github.com/apache/datafusion/issues/12446
This adds end to end tests for https://github.com/apache/datafusion/issues/12446 showing the issue is resolved. 
The fix for the equivalence computation is included in https://github.com/apache/datafusion/pull/12562, but the end to end tests then hit https://github.com/apache/datafusion/issues/12700
Add end to end `.slt` tests
Only tests
=> Add union sorting equivalence end to end tests

datafusion/physical-optimizer/src/topk_aggregation.rs, datafusion/physical-plan/src/aggregates/mod.rs, datafusion/physical-plan/src/coalesce_batches.rs, datafusion/physical-plan/src/coalesce_partitions.rs, datafusion/physical-plan/src/execution_plan.rs, datafusion/physical-plan/src/filter.rs, datafusion/physical-plan/src/limit.rs, datafusion/physical-plan/src/projection.rs, datafusion/physical-plan/src/repartition/mod.rs, datafusion/physical-plan/src/sorts/sort.rs, datafusion/sqllogictest/test_files/aggregates_topk.slt
Closes #12748.
We don't want bugs.
1. Push down agg limits past projections so we can observe the bug
2. Fix the bug
Yes
1. queries that weren't optimized should now be optimized
2. queries that are optimized should return correct results
=> Fix bug in TopK aggregates

datafusion/sqllogictest/test_files/unnest.slt
Closes #.
Remove some legacy TODO comments and refine the tests for unnest.
the original CI
no
=> Minor: clean up TODO comments in unnest.slt

datafusion/common/src/dfschema.rs, datafusion/sql/src/expr/identifier.rs
N/A
`check_ambiguous_name` was introduced for issue #12337 .
After PR #12608, there are no longer duplicate field names in `DFSchema`, so this function is no longer necessary.
By existing tests.
No, `check_ambiguous_name` should only be used internally.
=> Remove unnecessary `DFSchema::check_ambiguous_name`

datafusion/core/src/datasource/physical_plan/parquet/mod.rs
Closes https://github.com/apache/datafusion/issues/12737
Closes https://github.com/apache/datafusion/pull/12726
See https://github.com/apache/datafusion/issues/12737 for rationale (basically many times we manipulate a `ParquetExec` downstream we end up needing to create a builder from an existing `ParquetExec`
Changes:
1. Add `ParquetExec::into_builder()` method
2. Add docs with examples of usage
3. Update some existing code to use it
Yes
New API and Docs
=> API  from `ParquetExec` to `ParquetExecBuilder`

datafusion/expr-common/src/groups_accumulator.rs, datafusion/functions-aggregate/src/min_max.rs
Closes #.
While working on https://github.com/apache/datafusion/issues/6906 with @devanbenz  it was not always clear that much of the complexity related to null handling in `GroupsAccumulator` can be handled by `NullState`
1. Add a note with reference to NullState in the `GroupsAccumulator` comments
2. Drive by remove a partial copy of the apache license
Yes, by CI
Just documentation
=> Minor: add documentation note about `NullState`

.github/actions/setup-builder/action.yaml, ci/scripts/retry
`Setup rust toolchain` build step was observed to be flaky. Retries may help.
- Fixes https://github.com/apache/datafusion/issues/12713
=> Retry apt-get and rustup on CI

datafusion/sql/src/planner.rs, datafusion/sqllogictest/test_files/array.slt
Closes #10303.
See #10303. 
To make it possible to create a table with a fixed size list column without resorting to casting.
Enable SQL query planner to convert the SQL data type Array(ArrayElemTypeDef::SquareBracket) to a FixedSizeList.
Yes.
No.
=> Support creating tables via SQL with `FixedSizeList` column (e.g. `a int[3]`)

datafusion/physical-plan/src/joins/hash_join.rs
Closes #12806.
It is needed by physical optimizers that want to replace the HashJoin with a different type of join, as they need to replace it with an equivalent projection, but HashJoinExec::projection could not be used to build it because it refers to indices in HashJoinExec::join_schema.
Makes HashJoinExec::join_schema public
no (should they?)
new field in the API, already documented
=> Make HashJoinExec::join_schema public

datafusion/core/tests/fuzz_cases/aggregate_fuzz.rs, datafusion/functions-aggregate-common/src/aggregate/groups_accumulator.rs
Closes https://github.com/apache/datafusion/issues/12833
Fix a bug (found by fuzz testing) in https://github.com/apache/datafusion/issues/12114
Handle the no values case
=> Fix convert_to_state bug in `GroupsAccumulatorAdapter`

datafusion/functions-aggregate-common/src/tdigest.rs, datafusion/sqllogictest/test_files/aggregate.slt
Closes #12716.
Handles case where min/max are infinite or not a number (NaN)
Checks if min/max values are infinite or NaN + tests
Yes
=> Fix: approx_percentile_cont_with_weight Panic

datafusion/wasmtest/Cargo.toml, datafusion/wasmtest/src/lib.rs
Closes #12842.
The new release of wasm-bindgen-test causes clippy to throw errors.
PR fixed these errors and also verified locally that these tests can still run on Chrome.
```sh
running 2 tests
test datafusion_wasmtest::test::basic_execute ... ok
test datafusion_wasmtest::test::datafusion_test ... ok
test result: ok. 2 passed; 0 failed; 0 ignored; 0 filtered out
```
Yes
No
=> Fix clippy error on wasmtest

datafusion/functions/src/unicode/substr.rs, datafusion/sqllogictest/test_files/errors.slt
Closes #12699.
Fixes a panic.
Adds guard that checks that we are passed a correct number of arguments to substr.
Existing and a new test.
No.
=> Fix panic on wrong number of arguments to substr

datafusion/substrait/src/logical_plan/consumer.rs, datafusion/substrait/tests/cases/roundtrip_logical_plan.rs, datafusion/substrait/tests/testdata/test_plans/intersect.substrait.json
Adds support for intersect (primary) set operation to substrait consumer. 
Intersect can't be round-tripped (at least not easily) because DF has no explicit logical plan node for the op, rather splits it into lower level operations. That's why the test is comparing DF plans produced by an externally written substrait plan and equivalent datafusion sql query.
yes, a new feature
=> feat(substrait): add intersect support to consumer

datafusion/sql/src/cte.rs, datafusion/sql/src/expr/function.rs, datafusion/sql/src/expr/identifier.rs, datafusion/sql/src/expr/order_by.rs, datafusion/sql/src/expr/unary_op.rs, datafusion/sql/src/expr/value.rs, datafusion/sql/src/parser.rs, datafusion/sql/src/planner.rs, datafusion/sql/src/query.rs, datafusion/sql/src/relation/mod.rs, datafusion/sql/src/select.rs, datafusion/sql/src/statement.rs, datafusion/sql/src/unparser/dialect.rs, datafusion/sql/src/unparser/expr.rs, datafusion/sql/src/unparser/rewrite.rs, datafusion/sql/src/unparser/utils.rs, datafusion/sql/src/utils.rs, datafusion/sql/src/values.rs
Closes #.
I was learning the codebase (sql folder) and thought, "might as well do some light clean up"
Changed comments (grammar, typos, consistent capitalization )
=> Minor: Small comment changes in sql folder

datafusion/functions/src/core/mod.rs, datafusion/functions/src/core/struct.rs, datafusion/sqllogictest/test_files/struct.slt
Closes #.
Add support for DuckDB-like syntax and functions to facilitate testing
=> Add DuckDB struct test and row as alias

datafusion/execution/src/memory_pool/mod.rs
Closes #.
I think the comments for MemoryPool are already great, but some more concrete examples can further help
=> Minor: more doc to `MemoryPool` module

datafusion/sql/src/select.rs, datafusion/sqllogictest/test_files/aggregate.slt
Closes #12814 .
The query is invalid due to aggregation functions in where clause.
Added check for aggregation functions.
=> Added check for aggregate functions in optimizer rules

datafusion/core/src/datasource/memory.rs, datafusion/core/tests/fuzz_cases/aggregate_fuzz.rs, datafusion/core/tests/fuzz_cases/sort_preserving_repartition_fuzz.rs, datafusion/core/tests/fuzz_cases/window_fuzz.rs, datafusion/core/tests/memory_limit/mod.rs, datafusion/physical-plan/src/joins/nested_loop_join.rs, datafusion/physical-plan/src/joins/test_utils.rs, datafusion/physical-plan/src/memory.rs, datafusion/physical-plan/src/repartition/mod.rs, datafusion/physical-plan/src/union.rs
Closes #.
The `MemTable` contains a field `sort_order: Arc<Mutex<Vec<Vec<SortExpr>>>>`, and its columns refer to the original schema of the source. In the `scan()` method, we introduce an optional projection that is injected into `MemoryExec`. However, currently, the `sort_order` is not projected, which results in it referring to an invalid schema during planning.
I am surprised that existing tests do not catch this problem. I identified this bug in our downstream tests, where newly added aggregate fuzzer tests exposed the problem. For instance, the test `test_basic_prim_aggr_group_by_mixed_string_int64()` have queries that do not use column "d," but `sort_keys_set` contains an ordering involving "d". If we had supported ordered `MemoryExec` via sql (e.g., CREATE TABLE ... WITH ORDER …
=> Bug-fix: MemoryExec sort expressions do NOT refer to the projected schema

datafusion/functions/Cargo.toml, datafusion/functions/benches/iszero.rs, datafusion/functions/src/math/iszero.rs
Didn't create an issue beforehand.
`iszero` runs faster using `BooleanArray::from_unary`.
I think this is because we don't need to branch on each value to check if it's null, which the `.iter` inside `make_function_scalar_inputs_return_type` is doing.
- Add benchmark
- Replace `make_function_scalar_inputs_return_type` use with `BooleanArray::from_unary`
Yes, with existing tests.
Faster `iszero`. I don't expect this function to be a bottleneck anywhere, but at least it's a bit faster now.
```
iszero f32 array: 1024  time:   [771.48 ns 773.07 ns 774.97 ns]
change: [-69.960% -69.618% -69.232%] (p = 0.00 < 0.05)
Found 16 outliers among 100 measurements (16.00%)
6 (6.00%) high mild
10 (10.00%) high severe
iszero f64 array: 1024  time:   [683.35 ns 683.91 ns 684.49 ns] …
```
=> Optimize `iszero` function (3-5x faster)

datafusion/common/src/test_util.rs
Closes #12574
This macro allows for easy creation of a record batch, useful for prototype and unit testing. A user requested this feature.
Adds a macro to create a record batch. For example, the following creates a record batch with three arrays, a non nullable Int32, a nullable Float64, and a non nullable String.
```
let batch = create_batch!(
("a", Int32, vec![1, 2, 3]),
("b", Float64, vec![Some(4.0), None, Some(5.0)]),
("c", Utf8, vec!["alpha", "beta", "gamma"])
)?;
let ctx = SessionContext::new();
ctx.read_batch(batch)?.show().await
```
Yields:
```
+---+-----+-------+
| a | b   | c     |
+---+-----+-------+
| 1 | 4.0 | alpha |
| 2 |     | beta  |
| 3 | 5.0 | gamma |
+---+-----+-------+
```
Tested both in the provided unit test and locally.
No
=> Macro for creating record batch from literal slice

datafusion/core/src/physical_optimizer/pruning.rs
Replaces https://github.com/apache/datafusion/pull/12606, https://github.com/apache/datafusion/pull/12835
As per https://github.com/apache/datafusion/pull/12606#issuecomment-2392303014 the plan was to split the rewrite logic from the rest of PruningPredicate. It turns out that was as easy as making a function public, kudos to whoever wrote this originally for organizing it nicely 🥳.
=> Make PruningPredicate's rewrite public

datafusion/sqllogictest/test_files/string/string_view.slt
Closes #12149
Verifying a fix applied in arrow-rs.
Additional slt test added 
yes
No
=> octet_length + string view == ❤️ 

datafusion/expr/src/utils.rs, datafusion/sql/src/select.rs
N/A
In the call to `find_aggregate_exprs`, we copied the select list expressions and the having expression.
Yes
No
The public API `find_aggregate_exprs` becomes generalized and will not break existing calls.
=> Remove Expr clones in `select_to_plan`

datafusion/core/src/bin/print_functions_docs.rs
Part of https://github.com/apache/datafusion/issues/12740
First part of https://github.com/apache/datafusion/issues/12872
Eventually I would like to ensure that all functions have documentation. Now that we have the automated documentation builder in place, it is possible to see what is missing.
As first step, update the print docs script to print out the list of functions that are not documented. As a follow on PR I will make this an error once we have all functions documented
I tested them manually. Here is what it looks like:
```shell
INFO: The following functions do not have documentation:
- regr_avgy
- regr_sxx
- regr_slope
- regr_r2
- regr_count
- regr_avgx
- regr_syy
- regr_intercept
- regr_sxy
...
```
Here is what it looked like before
```shell
(venv) …
```
=> Print undocumented functions to console while generating docs

datafusion/functions/Cargo.toml, datafusion/functions/benches/signum.rs, datafusion/functions/src/math/signum.rs
Didn't create an issue beforehand.
Same idea as https://github.com/apache/datafusion/pull/12881. Using the `unary` functions allow faster processing (most likely auto-vectorized code) by avoiding branching on nulls.
- Add bench
- Apply `unary`
Yes, with existing tests.
Yes, faster `signum`:
```
signum f32 array: 1024  time:   [419.68 ns 420.68 ns 421.84 ns]
change: [-93.679% -93.655% -93.628%] (p = 0.00 < 0.05)
signum f64 array: 1024  time:   [1.1809 µs 1.1822 µs 1.1835 µs]
change: [-81.672% -81.630% -81.593%] (p = 0.00 < 0.05)
Found 5 outliers among 100 measurements (5.00%)
signum f32 array: 4096  time: …
```
=> Optimize `signum` function (3-25x faster)

datafusion/expr/src/function.rs
This is needed to implement the WindowUDF trait.
Closes #12877.
`PartitionEvaluatorArgs` is needed to implement `WindowUDF`, but is not currently re-exported.
`PartitionEvaluatorArgs` is re-exported in `datafusion_expr::function`.
I placed it here because that is where`WindowUDFFieldArgs` is re-exported.
N/A
Not from any released version.
=> re-export PartitionEvaluatorArgs from datafusion_expr::function

datafusion/physical-plan/src/aggregates/mod.rs, datafusion/physical-plan/src/aggregates/row_hash.rs
Closes #.
Spilling-related metrics (number of files spilled, peak memory usage) are used in spilling operators sort and SMJ, but not available in aggregation, this PR adds the same metrics in Sort/SMJ to aggregate
Run datafusion-cli:
```shell
cargo run -- --mem-pool-type fair -m 65M -c "
explain analyze select t1.v1, sum(t2.v1)
from
unnest(generate_series(1,1000)) as t1(v1)
, unnest(generate_series(1,1000)) as t2(v1)
group by t1.v1, t2.v1"
```
Result (spilling only happen in final aggregation)
```
......
|                   |   AggregateExec: mode=FinalPartitioned, gby=[v1@0 as v1, v1@1 as v1], aggr=[sum(t2.v1)], metrics=[output_rows=1332842, elapsed_compute=2.510508892s, spill_count=4, spilled_bytes=6914304, spilled_rows=288048, peak_mem_used=59607832] 
.......
|                   | …
```
=> Add spilling related metrics for aggregation

datafusion-examples/examples/custom_file_format.rs, datafusion/functions/src/regex/mod.rs, datafusion/optimizer/src/replace_distinct_aggregate.rs, datafusion/physical-plan/src/metrics/value.rs, datafusion/proto/src/logical_plan/file_formats.rs, datafusion/substrait/tests/cases/roundtrip_logical_plan.rs
Just a code cleanup
In many places the qualified name is redundant since `Arc` is already imported. In some `use` was added. In all cases `Arc` is unambiguous.
None
More code consistency, fewer warnings in an IDE.
imports
no
no
=> Import Arc consistently

datafusion/substrait/src/lib.rs, datafusion/substrait/src/logical_plan/consumer.rs, datafusion/substrait/tests/cases/consumer_integration.rs, datafusion/substrait/tests/cases/function_test.rs, datafusion/substrait/tests/cases/logical_plans.rs, datafusion/substrait/tests/cases/roundtrip_logical_plan.rs, datafusion/substrait/tests/cases/substrait_validations.rs
This is a necessary prerequisite for #12798
substrait consumer should make the best effort for one-to-one traslation w/o invoking optimizer. Doing otherwise makes round-trip tests too complicated. 
When translating substrait ReadRel nodes, consumer constructs a dataframe first, applies projections with `select` and hopes that subsequent `into_optimized_plan` calls with push projections down to `TableScan`. In practice, this sometimes adds unnecessary projection nodes to the plan and also unnecessary "pushed down" projections to TableScan even when substrait doesn't specify any such thing.
This PR:
- removes `into_optimized_plan` calls from consumer.
- removes unnecessary projection nodes introduced in `ensure_schema_compatability`, instead opting to handcraft projections that are put into …
=> fix(substrait): remove optimize calls from substrait consumer

datafusion/expr-common/src/columnar_value.rs, datafusion/functions/src/macros.rs
If all UDF arguments are scalars, so should be the result. In most cases, such function calls will be contant-folded, however, if for whatever reason the are not optimized, we want to avoid an error due to array length mismatch.
No particular issue, as I couldn't find a case that is not constant-folded with pure DataFusion, however we have some custom optimizer rules that might result in expressions that are not constant-folded.
The rationale is that the UDF implementations shouldn't rely on optimizer rules to work correctly.
* Added a new helper function `ColumnarValue::from_args_and_result` to perform the check and conversion.
* Updated the math UDF macros to return a scalar value when all their arguments are scalar.
Relying on existing tests to ensure nothing breaks.
I made …
=> Ensure that math functions fulfil the ColumnarValue contract

datafusion/optimizer/src/push_down_limit.rs, datafusion/sqllogictest/test_files/joins.slt
Closes #.
When JoinType is Full, push the limit down to the left and right sides.
modify optimizer `push_down_limit`
yes
=> Optimization: support push down limit when full join

datafusion/functions/benches/regx.rs, datafusion/functions/src/regex/regexplike.rs, datafusion/sqllogictest/test_files/string/string_view.slt
=> Implement native support StringView for `REGEXP_LIKE`

datafusion/functions-aggregate/src/grouping.rs, datafusion/optimizer/src/analyzer/mod.rs, datafusion/optimizer/src/analyzer/resolve_grouping_function.rs, datafusion/sqllogictest/test_files/explain.slt, datafusion/sqllogictest/test_files/grouping.slt
Closes #5647 .
Closes https://github.com/apache/datafusion/pull/10208
Grouping function is supported by postgres and needed inorder to be able to run TPC-DS (#4763).
This PR adds an analyzer rule that will transform the grouping aggregation function into a projection on top of grouping id (added in #12571). Since the grouping aggregation function is so specific and special (and not really a aggregation), I don't think it make sense to generalize the UDAF api to support it.
This PR currently leaves the non-functional grouping UDAF. But since it non functional and will remain so, we might want to replace it with some built in `Expr::Grouping` instead. Would love some more feedback if that should be done in this PR or some other alternative.
New slt, mostly copied from #10208 with some …
=> feat: Implement grouping function using grouping id

benchmarks/src/bin/h2o.rs, benchmarks/src/clickbench.rs, benchmarks/src/imdb/run.rs, benchmarks/src/lib.rs, benchmarks/src/parquet_filter.rs, benchmarks/src/sort.rs, benchmarks/src/tpch/run.rs
This pull request focuses on refactoring the import statements across multiple files in the `benchmarks` module to improve code organization by consolidating utility imports into a single module.
Closes #.
yes
=> Minor: Refactor benchmark imports to use `util` module

datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs
Follow up to #12814
This address a bug that previously always replace % 1 expression with a 0 of type i32. This lead to panics/crashes in a lot of places since we expect the type to not change as part of this simplification rule.
This patch fixes it by replacing it with a 0 of correct type.
Yes.
No.
=> Fix zero data type in `expr % 1` simplification

datafusion/functions/Cargo.toml, datafusion/functions/benches/cot.rs, datafusion/functions/src/math/cot.rs
Using the `unary` functions allows faster processing by avoiding branching on nulls.
- Apply `unary`
- Add benchmark
Existing testcases.
No.
**BENCHMARK RESULT
=> Optimize performance of `math::cot` (~2x faster)

datafusion/optimizer/src/analyzer/expand_wildcard_rule.rs
=> Expand wildcard expressions in distinct on

datafusion-cli/src/exec.rs, datafusion-cli/src/object_storage.rs
Closes #.
`default_table_options` function contains the clone logic, so there is no need to clone the returned `TableOptions`.
https://github.com/apache/datafusion/blob/747001a41481e0cf39dc758a85d1bdb64fdeb7c0/datafusion/core/src/execution/session_state.rs#L797-L801
https://github.com/apache/datafusion/blob/747001a41481e0cf39dc758a85d1bdb64fdeb7c0/datafusion/common/src/config.rs#L1274-L1278
=> chores: remove redundant clone

datafusion/physical-plan/src/windows/mod.rs, datafusion/sqllogictest/test_files/window.slt
=> Fix: handle NULL input in lead/lag window function

Cargo.toml, datafusion-cli/Cargo.lock, datafusion-cli/Cargo.toml, datafusion/core/src/datasource/file_format/csv.rs, datafusion/core/src/datasource/file_format/parquet.rs, datafusion/functions/src/regex/regexplike.rs, datafusion/physical-expr/src/expressions/binary.rs, datafusion/sqllogictest/test_files/repartition_scan.slt, datafusion/wasmtest/Cargo.toml, datafusion/wasmtest/src/lib.rs
Part of https://github.com/apache/datafusion/issues/12813
Clippy is failing on branch-42 after the arrow 53.1.0 upgrade. This was fixed in https://github.com/apache/datafusion/pull/12724 on main, but that also includes several other fixes
1. Update to arrow 53.1.0
2. port just enough of https://github.com/apache/datafusion/pull/12724 to get CI passing
3. port https://github.com/apache/datafusion/pull/12844 from @jonahgao  to fix another clippy error
=> Backport update to arrow 53.1.0 on branch-42

datafusion/core/src/datasource/file_format/mod.rs, datafusion/physical-plan/src/joins/cross_join.rs, datafusion/physical-plan/src/union.rs, datafusion/sqllogictest/src/test_context.rs, datafusion/sqllogictest/test_files/metadata.slt
Part of #12813 . Applies fixes from https://github.com/apache/datafusion/pull/12729 to DataFusion version 42
=> Backport "Provide field and schema metadata missing on cross joins, and union with null fields" (#12729)

datafusion/physical-plan/src/aggregates/group_values/row.rs, datafusion/physical-plan/src/aggregates/mod.rs
Part of #12813 applies fix from https://github.com/apache/datafusion/pull/12586
=> Backport "physical-plan: Cast nested group values back to dictionary if necessary" (#12586)

docs/source/contributor-guide/index.md
N/A
We generate changelogs based on PR titles where PRs following the conventional commits specification, and also based on labels associated with PRs, but we did not documentation for this process.
This PR adds documentation.
=> docs: Add documentation about conventional commits

datafusion/physical-plan/src/aggregates/mod.rs, datafusion/physical-plan/src/projection.rs, datafusion/sqllogictest/test_files/metadata.slt
Part of https://github.com/apache/datafusion/issues/12813
This PR is used to backport #12691 to DF 42.
PR #12691
Yes, on main branch.
=> backport-to-DF-42: Provide field and schema metadata missing on distinct aggregations

datafusion/sql/src/unparser/dialect.rs, datafusion/sql/src/unparser/expr.rs
Closes #12915.
* To fix a bug with casting integers in MySQL
* Adds an option to the `Dialect` to specify the cast type for Int32 integers, replicating the existing behavior for Int64 integers.
Yes.
No.
=> fix: Add Int32 type override for Dialects

datafusion/functions/src/string/contains.rs
=> fix: using simple string match replace regex match for contains udf

.github/workflows/rust.yml, Cargo.toml, datafusion-cli/Cargo.toml, datafusion-cli/Dockerfile, datafusion/core/Cargo.toml, datafusion/proto-common/Cargo.toml, datafusion/proto-common/gen/Cargo.toml, datafusion/proto/Cargo.toml, datafusion/proto/gen/Cargo.toml, datafusion/substrait/Cargo.toml
Current goal is to support four last stable versions or versions for 4 months whichever is lower.  Given 1.78.0 was released on: 2 May, 2024, it does not need to be supported.
=> Increase minimum supported Rust version (MSRV) to 1.79

datafusion/substrait/Cargo.toml, datafusion/substrait/src/logical_plan/consumer.rs, datafusion/substrait/src/logical_plan/producer.rs, datafusion/substrait/tests/cases/roundtrip_logical_plan.rs, datafusion/substrait/tests/testdata/test_plans/intersect_multiset.substrait.json, datafusion/substrait/tests/testdata/test_plans/intersect_multiset_all.substrait.json, datafusion/substrait/tests/testdata/test_plans/intersect_primary.substrait.json, datafusion/substrait/tests/testdata/test_plans/minus_primary.substrait.json, datafusion/substrait/tests/testdata/test_plans/minus_primary_all.substrait.json, datafusion/substrait/tests/testdata/test_plans/union_distinct.substrait.json, datafusion/substrait/tests/utils.rs
Adds support for set operations to substrait consumer except for Multiset Minus (still unsure what that one does exactly...) 
- updates substrait crate to latest and makes some necessary changes accordingly to handle recent changes in AggregateRel.
- adds set op rules to consumer with tests.
Yes
Yes
=> feat(substrait): add set operations to consumer, update substrait to `0.45.0`

datafusion/sql/src/unparser/plan.rs, datafusion/sql/src/unparser/rewrite.rs, datafusion/sql/tests/cases/plan_to_sql.rs
Closes #.
Consider the following SQL
```SQL
SELECT 
c.custkey, 
c.name 
FROM 
(
SELECT 
c_custkey as custkey, 
c_name as name 
FROM 
customer
) c
```
The unoptimized plan is
```
Projection: c.custkey, c.name
SubqueryAlias: c
Projection: customer.c_custkey AS custkey, customer.c_name AS name
TableScan: customer
```
However, after the `optimize_projections` rule, the top-level projection will be removed like
```
SubqueryAlias: c
Projection: customer.c_custkey AS custkey, customer.c_name AS name
TableScan: customer projection=[c_custkey, c_name]
```
The unparsing result would like
```SQL
SELECT 
customer.c_custkey AS custkey, 
customer.c_name AS "name" 
FROM 
(
SELECT 
customer.c_custkey, 
customer.c_name 
FROM 
customer
) AS c
```
It's an invalid SQL because the column qualifier is the …
=> Unparse `SubqueryAlias` without projections to SQL

datafusion/core/src/dataframe/mod.rs, datafusion/core/src/datasource/listing/helpers.rs, datafusion/core/src/datasource/listing/table.rs, datafusion/sqllogictest/test_files/arrow_files.slt, datafusion/sqllogictest/test_files/errors.slt
Closes #12901.
This patch fixes 2 bugs. Errors in partition filters are ignored and
that we allow partition filters to be pushed down for unpartitioned tables,
but we never evaluate such filters. This leads to correctness issues 
in both cases.
The first bug is fixed by reporting errors for partition filters and only evaluating the filters we allowed as partition filters in `supports_filters_pushdown`. 
The second bug is fixed by only allowing partition filters to be pushed down when we have partition columns. Because we currently just ignore the filters in that case.
Yes, using new and existing tests.
No.
=> Fix 2 bugs related to push down partition filters

datafusion/common/src/functional_dependencies.rs, datafusion/sql/src/statement.rs
Reduce datafusion-common dependency on sqlparser
=> Move TableConstraint to Constraints conversion

datafusion/sql/src/unparser/expr.rs, datafusion/sql/src/unparser/plan.rs, datafusion/sql/src/unparser/utils.rs, datafusion/sql/tests/cases/plan_to_sql.rs
Improves unparsing to produce valid sql for TPC-DS benchmark queries:
Fix UNION unparsing for queries where UNION is a subquery
Original query
```sql
select
channel,
col_name
from
(
select
'store' as channel,
'ss_customer_sk' as col_name
from
store_sales
union all
select
'web' as channel,
'ws_ship_hdemo_sk' as col_name
from
web_sales
) as foo
group by
channel,
col_name
order by
channel,
col_name
```
Before (invalid):
```sql
select
'store' as "channel",
'ss_customer_sk' as "col_name"
from
"store_sales"
union all
select
'web' as "channel",
'ws_ship_hdemo_sk' as "col_name"
from
"web_sales"
order by
"foo"."channel" asc nulls last,
"foo"."col_name" asc nulls last
```
After (correct)
```sql
select
"foo"."channel",
"foo"."col_name"
from
(
select
'store' as "channel",
'ss_customer_sk' as …
```
=> Improve unparsing for `ORDER BY`, `UNION`, Windows functions with Aggregation

datafusion/expr-common/src/columnar_value.rs, datafusion/functions/src/macros.rs, datafusion/physical-expr/src/scalar_function.rs
This was done in #12922 only for math functions.
We now generalize this fallback to all scalar UDFs.
Closes #12959
See #12922
* We move the fallback for one-element array return value from the math function macros to `ScalarFunctionExpr`
* We remove the helper method added in #12959
Relying on existing tests.
`ColumnarValue::from_args_and_result` is removed again, it's not released yet.
=> Handle one-element array return value in ScalarFunctionExpr

docs/source/user-guide/sql/scalar_functions_new.md
CI is failing on main https://github.com/apache/datafusion/actions/runs/11389933675/job/31690903265
```
Running prettier
docs/source/user-guide/sql/window_functions_new.md 54ms
'docs/source/user-guide/sql/window_functions_new.md' successfully updated!
diff --git a/docs/source/user-guide/sql/scalar_functions_new.md b/docs/source/user-guide/sql/scalar_functions_new.md
index 8f1e30f..ffc2b68 100644
--- a/docs/source/user-guide/sql/scalar_functions_new.md
+++ b/docs/source/user-guide/sql/scalar_functions_new.md
@@ -1802,6 +1802,7 @@ Additional examples can be found [here](https://github.com/apache/datafusion/blo
- [current_date](#current_date)
- [current_time](#current_time)
+- [current_timestamp](#current_timestamp)
- [date_bin](#date_bin)
- [date_format](#date_format)
- …
```
=> Fix CI on main ( regenerate function docs)

datafusion/core/src/physical_optimizer/join_selection.rs
ref #12491, #10978
If there is embeded projection in HashJoinExec, no need to add projection above hashjoin after swapping join order.
Thanks @onursatici for catching it.
=> Fix：fix HashJoin projection swap

datafusion/substrait/src/logical_plan/consumer.rs
some minor refactoring after #12800 as promised.
existing tests
no
=> refactor(substrait): refactor ReadRel consumer

datafusion/substrait/src/logical_plan/producer.rs, datafusion/substrait/tests/cases/roundtrip_logical_plan.rs
Current roundtrip tests for wildcard expression pass only because tests themselves optimize the plan beforehand and "optimize" the wildcard away before actually doing a roundtrip. Producer should be able to convert the plan to substrait even if the plan isn't optimized beforehand.
- Changes the wildcard test not to optimize the query beforehand
- Injects `ExpandWildcardRule` at the top of the producer. Substrait doesn't have anything analogous to the wildcard, so the easiest solution I found was to run ExpandWildcardRule to work around that. The main thing is that it's run as part of the producer so the producer no longer assumes that full optimizer has been run before.
yes
yes, producer can convert wildcard expression independently of the optimizer.
=> feat(substrait): add wildcard handling to producer

datafusion/core/tests/fuzz_cases/join_fuzz.rs, datafusion/physical-plan/src/joins/sort_merge_join.rs, datafusion/sqllogictest/test_files/sort_merge_join.slt
Related to #11555 
Related to #12359  
Closes #.
Move filtered logic out of join_output stage.
The problem is for filtered joins there is extra step need, e.g to calculate final filtered mask for the specific row the algorithm, it needs the knowledge for  every right row processed for the given left row. 
For example for LeftOuter join :
`select * from t1 join t2 on (t1.a = t2.a and t1.b > t2.b)`
t1:
|a|b|
|---|---|
|1| 10|
t2:
|a|b|
|---|---|
|1| 9|
|1|11|
Currently the Join will output
|a|b|a|b
|---|---|---|---|
|1| 10|||
|1| 10|1|11|
which is incorrect, the first null matched row shouldn't be out as for given row there is a match exists.
The problem is records calculated depending on batch size and the output can be called anytime once the output size hit the batch size. So with `batch …
=> Move SMJ join filtered part out of join_output stage. LeftOuter, LeftSemi

datafusion/functions/src/regex/regexpmatch.rs, docs/source/user-guide/sql/scalar_functions_new.md
=> Minor: Fixed regexpr_match docs

datafusion/core/benches/sql_planner.rs, datafusion/core/src/physical_optimizer/update_aggr_exprs.rs, datafusion/core/src/physical_planner.rs, datafusion/core/tests/fuzz_cases/aggregate_fuzz.rs, datafusion/core/tests/physical_optimizer/combine_partial_final_agg.rs, datafusion/core/tests/physical_optimizer/limited_distinct_aggregation.rs, datafusion/physical-expr/src/aggregate.rs, datafusion/physical-expr/src/utils/mod.rs, datafusion/physical-expr/src/window/aggregate.rs, datafusion/physical-expr/src/window/sliding_aggregate.rs, datafusion/physical-optimizer/src/aggregate_statistics.rs, datafusion/physical-optimizer/src/combine_partial_final_agg.rs, datafusion/physical-plan/src/aggregates/mod.rs, datafusion/physical-plan/src/aggregates/row_hash.rs, datafusion/physical-plan/src/windows/mod.rs, datafusion/proto/src/physical_plan/mod.rs, datafusion/proto/src/physical_plan/to_proto.rs, datafusion/proto/tests/cases/roundtrip_physical_plan.rs
Closes #12738.
I investigated the performance degradation in creating physical plans for queries with a large number of columns compared to version 40 and discovered the following:
1. The main time loss occurs during the cloning of plan nodes during optimizations. We can compare two flame graphs (for version 40 and version 42, attached) and see that in version 42, `enforce_distribution` spends additional time destroying the vector of AggregateFunExpr. It turns out that in patch f5c47fa274d53c1d524a1fb788d9a063bf5240ef, the Arc for storing aggregate expressions was removed. As a result, during calls to `with_new_children`, fairly heavy structures are being cloned and destroyed.
2. Some time was also spent on a new optimization: limit pushdown. This is optional and left up to the user to …
=> Improve performance for physical plan creation with many columns

datafusion/core/src/dataframe/mod.rs, datafusion/expr/src/logical_plan/builder.rs
Closes #12980 
When the datafusion logical planner build the AGGREGATE plan, it adds additional columns in the group_expr based on the functional dependencies. However, for queries that are aggregating upon table obatined through UNION operation, the functional dependency is still preserved in the schema of UNION plan, while the functional dependency no longer retains after the UNION. This causes wrong column being added as group_by column in aggregation plan
- Changes to eliminate functional dependency when building `UNION` logical plan
- Unit test to verify the changes
Yes, unit test `test_aggregate_with_union` is added to verify the change
Aggregation based upon UNION results will not produce wrong results with duplicated groups
=> Don't preserve functional dependency when generating UNION logical plan

datafusion/core/tests/tpcds_planning.rs, datafusion/optimizer/src/decorrelate_predicate_subquery.rs, datafusion/sqllogictest/test_files/subquery.slt, datafusion/sqllogictest/test_files/tpch/q20.slt.part, datafusion/substrait/tests/cases/roundtrip_logical_plan.rs
Closes #5368.
Support subqueries in more cases and needed for TPC-DS (#4763) 
Extends the `DecorrelatePredicateSubquery` optimizer rule to not only handle predicate subquries in the "top" of a conjunctive filter, but also in other expressions like OR. This is done by replacing the subquery by an existence join and replacing the subquery expression with the exists column. Since datafusion does not natively support existence join/mark join (yet) we emulate it by adding a boolean column and checking for null after the join.
More tests in subquery.slt (also move some of the existing spec that needed updating with these changes).
Yes, support for predicate subqueries in more cases.
=> feat: Decorrelate more predicate subqueries

datafusion/core/src/physical_optimizer/join_selection.rs
Closes #10978.
On join swap embedded projection for anti/semi joins is getting modified just like for any other join types. This leads to resulting embedded projection, containing column indices out of bounds of join output schema.
The fix is not to modify output projection for semi/anti joins -- they already have one-side schema as an output, and trying to add/subtract the number of fields from the other input side to column indices will break the projection. 
Existing test for swapping join with embedded projection is extended to test all join types.
Swapping inputs for semi/anti joins with embedded projection should start working.
=> fix: join swap for projected semi/anti joins

datafusion/sql/src/unparser/plan.rs, datafusion/sql/src/unparser/rewrite.rs, datafusion/sql/tests/cases/plan_to_sql.rs
It's a follow-up PR of #12896 
from https://github.com/apache/datafusion/pull/12896#issuecomment-2408609989
Enhance the original tests
=> Enhance table scan unparsing to avoid unnamed subqueries.

datafusion/core/tests/core_integration.rs, datafusion/core/tests/execution/logical_plan.rs, datafusion/core/tests/execution/mod.rs, datafusion/functions-aggregate/src/count.rs, datafusion/physical-plan/src/common.rs, datafusion/physical-plan/src/values.rs
Before the change, the `ValuesExec` containing `NullArray` would
incorrectly report column statistics as being non-null, which would
misinform `AggregateStatistics` optimizer and fold `count(always_null)`
into row count instead of 0.
This commit fixes the column statistics derivation for values with
`NullArray` and therefore fixes execution of logical plans with count
over such values.
Note that the bug was not reproducible using DataFusion SQL frontend,
because in DataFusion SQL the `VALUES (NULL)` doesn't have type
`DataType:Null` (it has some apparently arbitrarily picked type
instead).
As a follow-up, all usages of `Array:null_count` should be inspected.
The function can easily be misused (it returns "physical nulls", which
do not exist for null type).
- Relates to: …
=> Fix count on all null `VALUES` clause

datafusion/optimizer/src/eliminate_cross_join.rs, datafusion/sqllogictest/test_files/join.slt
Closes #7549, #4877
Simplifying optimization rule and supporting an extra case, adding more opportunity for optimization.
=> Support filter in cross join elimination

datafusion/core/tests/expr_api/simplification.rs, datafusion/expr/src/expr_rewriter/mod.rs, datafusion/optimizer/src/simplify_expressions/simplify_exprs.rs, datafusion/sqllogictest/test_files/tpch/q22.slt.part
Closes #.
The main reason I wanted to do this change is to make some test more robust to change. E.g it should not matter if something was simplified in filter and then pushed into the scan vs pushed into the scan and then simplified.
Looking at the test changes it looks like this is actually a bug fix and because we previsouly did ended up duplicating a filter in TPC-H q22 during push down. But with this change we correctly deduplicate that filter.
Also exclude `LogicalPlan::TableScan` from aliases in `NamePreserver`
Using existing tests.
Might lead to less alias in explain strings.
=> fix: Do NOT preserve names (aliases) of Exprs for simplification in TableScan filters

datafusion/core/tests/user_defined/user_defined_scalar_functions.rs, datafusion/expr/src/udf.rs, datafusion/physical-expr/src/scalar_function.rs
Closes #13000.
These changes will allow functions to be implemented that produce a unique result for each call given the same input.
=> Fix functions with Volatility::Volatile and parameters

datafusion/substrait/src/logical_plan/consumer.rs
Closes #12862
union with a single input no longer works (technically a breaking change)
=> fix(substrait): disallow union with a single input

datafusion/core/tests/fuzz_cases/join_fuzz.rs, datafusion/physical-plan/src/joins/sort_merge_join.rs, datafusion/sqllogictest/test_files/sort_merge_join.slt
Related #12359 .
Follow up on #12764 
Same as #12764 but for Right Outer join
=> Move filtered SMJ right join out of `join_partial` phase

datafusion/physical-plan/src/analyze.rs, datafusion/physical-plan/src/coalesce_batches.rs, datafusion/physical-plan/src/coalesce_partitions.rs, datafusion/physical-plan/src/common.rs, datafusion/physical-plan/src/display.rs, datafusion/physical-plan/src/empty.rs, datafusion/physical-plan/src/execution_plan.rs, datafusion/physical-plan/src/explain.rs, datafusion/physical-plan/src/filter.rs, datafusion/physical-plan/src/insert.rs, datafusion/physical-plan/src/limit.rs, datafusion/physical-plan/src/memory.rs, datafusion/physical-plan/src/placeholder_row.rs, datafusion/physical-plan/src/projection.rs, datafusion/physical-plan/src/stream.rs, datafusion/physical-plan/src/streaming.rs, datafusion/physical-plan/src/test.rs, datafusion/physical-plan/src/unnest.rs, datafusion/physical-plan/src/values.rs, datafusion/physical-plan/src/work_table.rs
Closes #.
Going through learning codebase, cleaned some comments/code
=> Minor: Cleaned physical-plan Comments

datafusion/sql/src/unparser/plan.rs
It's a follow-up of #13006 
We missed the good suggestions from @phillipleblanc https://github.com/apache/datafusion/pull/13006#issuecomment-2427901276
They make sense to me 👍 
the original tests.
no
=> improve the condition checking for unparsing table_scan

datafusion/common/src/hash_utils.rs
N/A
`where T: Trait, <T as Trait>::Assoc: Bound` can be simplified to `where T: Trait<Assoc: Bound>`
The syntax has been stablized since Rust 1.79.0, which is the current Rust version used by DataFusion.
Ref: https://blog.rust-lang.org/2024/06/13/Rust-1.79.0.html#bounds-in-associated-type-position
Yes
No
=> minor: simplify associated item bound of `hash_array_primitive`

datafusion/optimizer/src/optimizer.rs, datafusion/sqllogictest/test_files/explain.slt, datafusion/sqllogictest/test_files/subquery.slt
Closes #3770 and maybe #2480
This is a step towards being able to run TPC-DS q41 (#4763) which has an
expressions that needs simplification before our rules can decorrelate the
subquery.
This patch makes it so that rules the configure an `apply_order` will
also include subqueries in their traversel.
Yes, subqueries will now also be optimized.
=> feat: Run (logical) optimizers on subqueries

datafusion/functions/src/math/log.rs, datafusion/sqllogictest/test_files/scalar.slt
Closes #13020.
Unit tests in log.rs do not cover unary case and failure case. Also added explicit casting to slt tests for f32 and f64 with log(x) and log(x,y) to cover all cases
-added tests
changes are only tests and all tests pass 
no
=> extended log.rs tests for unary/binary and f32/f64 casting

datafusion/core/benches/sql_planner.rs, datafusion/core/tests/tpcds_planning.rs
Keep failing queries up to date, refer to new issue.
=> [Minor] Update info/list of TPC-DS queries

datafusion/physical-plan/src/union.rs, datafusion/sqllogictest/src/test_context.rs, datafusion/sqllogictest/test_files/metadata.slt
Part of #12733 
closes https://github.com/apache/datafusion/issues/13010
We found another bug for when the logical vs physical schema does not match. In this specific case, the UNION schema will [select which side has the nullable field -- and default to taking the left side](https://github.com/apache/datafusion/blob/5a0ea0bbad3de73ded192bf32080094cee5db9f3/datafusion/physical-plan/src/union.rs#L491).
In the example case, we have the nullable field as the right side. With this setup, it became evident that we are not adding the field metadata from the left side => to the right side.
[First commit](https://github.com/apache/datafusion/commit/a9b6bd56ed10ac23585d1010c923e5c457525274) is the reproducer.
Second commit is the fix.
Third commit updates the test/reproducer now that the fix is …
=> Fix logical vs physical schema mismatch for UNION where some inputs are constants

datafusion/common/src/cse.rs
Part of https://github.com/apache/datafusion/issues/11194.
We don't need to store the exact number of sure and conditional evaluations in `NodeStats` during CSE.
This PR adds a new `NodeEvaluation` enum to track evaluation.
No.
=> Improve CSE stats

datafusion/functions/src/math/cot.rs, docs/source/user-guide/sql/scalar_functions_new.md
Part of #12740
I noticed that the `cot` function does not have documentation by running the script in https://github.com/apache/datafusion/issues/12872
```shell
(venv) andrewlamb@Andrews-MacBook-Pro-2:~/Software/datafusion$ ./dev/update_function_docs.sh
...
Running CLI and inserting scalar function docs table
Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.25s
Running `target/debug/print_functions_docs scalar`
INFO: The following functions do not have documentation:
- map_extract
- map
- cot
- map_keys
- map_values
```
Note that @ jonathanc-n  is working on the map functions in https://github.com/apache/datafusion/pull/13047
In fact it appears to be completely undocumented in the old docs too: https://datafusion.apache.org/user-guide/sql/scalar_functions.html so this is a …
=> Minor: Add documentation for `cot`

README.md, docs/source/library-user-guide/api-health.md
Closes #13077 .
DataFusion need to state the clear policy when the deprecated methods can be removed from the codebase to let the users enough time to migrate and keep the API hygiene
=> Documentation: Add API deprecation policy

datafusion/core/benches/sql_planner.rs
Based on discussion in #94 but unsure if it would close it.
Lack of join benchmarks for physical planning.
Added a number of physical planning benchmarks mostly focused on JOIN queries.
- Query plan should consider sort merge join
- Theta join (a < b) where query plan should consider sort merge join
- Query plan consisting of many self joins
- Nested query which may be unnested to become a regular join query
- Query plan using intersection which is equivalent to a join (and another for the same equivalent query plan but written using explicit join)
n/a
No
=> chore: Added a number of physical planning join benchmarks

datafusion/functions-window/src/lead_lag.rs, docs/source/user-guide/sql/window_functions.md, docs/source/user-guide/sql/window_functions_new.md
Partially #12936
Part of #12740
- migrate to new doc
- delete lead/lag from static docs
- documentation change
only documentation change
=> [docs]: migrate lead/lag window function docs to new docs

datafusion/expr/src/window_frame.rs, datafusion/optimizer/src/analyzer/type_coercion.rs, datafusion/sql/tests/cases/plan_to_sql.rs, datafusion/sqllogictest/test_files/window.slt, datafusion/substrait/src/logical_plan/producer.rs
Closes #11432
Closes #12982
This tried to fix the liked issue by improving the type inference when creating window frame from sqlparser.
- WindowFrameBound's try_from method is replaced by a try_parse that also takes the WindowFrame's units in order to make some conclusions about the type.
Yes
No API changes but potentially a new behaviour introduced that could break some existing code.
=> feat: improve type inference for WindowFrame

datafusion/core/src/datasource/file_format/parquet.rs, datafusion/core/src/datasource/listing/table.rs, datafusion/core/src/datasource/physical_plan/file_scan_config.rs, datafusion/core/src/datasource/schema_adapter.rs, datafusion/core/src/physical_planner.rs, datafusion/expr/src/logical_plan/builder.rs, datafusion/expr/src/utils.rs, datafusion/physical-plan/src/joins/utils.rs, datafusion/physical-plan/src/windows/utils.rs
This will not close, but rather just helps with the situation in, #12733.
As I was trying to fix other issues, I ran into more instances where Schema metadata could theoretically be dropped. These specific issues don't have reproducers (since I just found them while working on other stuff), but I think they are clearly issues nonetheless.
Mostly changing `Schema::new` to `Schema::new_with_metadata` and `schema_builder.finish()` to `schema_builder.finish().with_metadata(...)`
Yes, all tests still pass.
No
=> Fix more instances of schema missing metadata

datafusion/core/benches/sql_planner.rs, datafusion/core/tests/tpcds_planning.rs, datafusion/optimizer/src/analyzer/subquery.rs, datafusion/optimizer/src/decorrelate.rs, datafusion/optimizer/src/scalar_subquery_to_join.rs, datafusion/sqllogictest/test_files/subquery.slt
Closes #13074.
The goal here is to support TPC-DS q41 which has an expression that can
not be pull up until it has been simplified by SimplifyExpressions. This
means that currently we reject the query already in the analyzer. But
after this change we are able to plan that query.
This patch moves subquery check `can_pull_over_aggregation` from
analyzer into the PullUpCorrelatedExpr. Instead of failing the query we
will now instead do not decorrelate such queries and then fail during
physical plan creation.
Yes, existing tests.
Yes, errors for certains subqueries might change from failed analyzer to failed to create physical plan.
=> feat: Move subquery check from analyzer to PullUpCorrelatedExpr (Fix TPC-DS q41)

benchmarks/bench.sh
Closes #13105.
Removed `--prefer_hash_join` option from `parquet_filter` commands.
Yes. The changes are tested.
+ No use-facing changes.
+ No need to change `README.md` also.
=> removed --prefer_hash_join option from parquet_filter command.

datafusion/core/src/bin/print_functions_docs.rs
Draft until we have completely migrated all function documentation. The CI will fail until all currently existing functions are documented
Closes https://github.com/apache/datafusion/issues/12872
The idea here is to ensure that all functions are documented, and ensure this is the case via a CI test.
Changes:
make the ./dev/update_function_docs.sh script error if there are undocumented functions
Here is an example failure:
```
(venv) andrewlamb@Andrews-MacBook-Pro-2:~/Software/datafusion$ ./dev/update_function_docs.sh
/Users/andrewlamb/Software/datafusion
Inserting header
Running CLI and inserting aggregate function docs table
Compiling datafusion v42.0.0 (/Users/andrewlamb/Software/datafusion/datafusion/core)
Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.77s
Running …
```
=> Make CI error if a function has no documentation

datafusion/core/tests/fuzz_cases/aggregate_fuzz.rs, datafusion/core/tests/fuzz_cases/aggregation_fuzzer/data_generator.rs, test-utils/src/array_gen/primitive.rs
Part of #12114 .
Supporting more types for dataset generator in fuzzer framework is needed according to [this comment](https://github.com/apache/datafusion/issues/12114#issuecomment-2402755758).
1. Refactor the `PrimitiveArrayGenerator` to make it easier to introduce new primitive types.
2. Add coverage of Date32/Date64 types.
No.
=> feat: Add `Date32`/`Date64`  in aggregate fuzz testing

datafusion/sql/src/query.rs, datafusion/sql/tests/sql_integration.rs
Closes #12294.
This PR enables creating logical plan for a prepare statement with a limit clause.
Creating  physical plan for prepare is not yet supported and is being tracked in #4539.
Yes
No
=> fix: planning of prepare statement with limit clause

benchmarks/README.md, benchmarks/bench.sh, benchmarks/src/bin/external_aggr.rs, datafusion/execution/src/memory_pool/mod.rs
Closes https://github.com/apache/datafusion/issues/7571
Adding benchmark for external aggregation.
The benchmark queries are simple aggregation on the TPCH `lineitem` table. For instance, `SELECT DISTINCT l_orderkey FROM lineitem`.
I think using `lineitem` table is suitable to benchmark memory-limited aggregation due to
1. It's easy to choose different aggregation cardinality (figure is from [DuckDB external aggregation paper](https://hannes.muehleisen.org/publications/icde2024-out-of-core-kuiper-boncz-muehleisen.pdf))
Also we already have TPCH data generator and we can change scaling factor later
2. Memory stress can be changed by adding more aggregates to `SELECT` clause (e.g. query `select max(c1), max(c2)... max(c100)` has larger memory pressure because it have to store large …
=> Add benchmark for memory-limited aggregation

datafusion/core/tests/fuzz_cases/join_fuzz.rs, datafusion/physical-plan/src/joins/sort_merge_join.rs, datafusion/sqllogictest/test_files/sort_merge_join.slt
Related https://github.com/apache/datafusion/issues/12359 
Follow up on https://github.com/apache/datafusion/pull/12764
Same as https://github.com/apache/datafusion/pull/12764 but for Left Anti join
=> Move filtered SMJ Left Anti filtered join out of `join_partial` phase

datafusion/sql/src/unparser/ast.rs, datafusion/sql/tests/cases/plan_to_sql.rs
With filters pushdown optimization, the LogicalPlan can have filters defined as part of `TableScan` and `Filter` nodes.
To avoid overwriting one of the filters, we combine the existing filter with the additional filter.
Example query
```sql
select
c_phone as cntrycode,
c_acctbal
from
customer
where c_mktsegment = 'BUILDING' and c_acctbal > (
select
avg(c_acctbal)
from
customer);
```
Logical Plan
``` …
```
=> Improve TableScan with filters pushdown unparsing (multiple filters)

datafusion/expr/src/logical_plan/builder.rs, datafusion/sqllogictest/test_files/type_coercion.slt
Closes #13092
Raise the error earlier, restore the behaviour of previous versions of DF
code, slt test.
yes
no
=> Raise a plan error on union if column count is not the same between plans

datafusion/sql/Cargo.toml, datafusion/sql/src/unparser/expr.rs, datafusion/sql/src/unparser/plan.rs, datafusion/sql/src/unparser/utils.rs, datafusion/sql/tests/cases/plan_to_sql.rs
PR adds basic support for `UNNEST` unparsing: Lists/Arrays only (structs support needs some extra work and could be added as incremental improvement).
1. PR adds handler for `LogicalPlan::Unnest` and updates `reconstruct_select_statement` to check if there is `Unnest` child so that corresponding columns are correctly unprojected via `unproject_unnest_expr`.  For example `column("unnest_placeholder([Int64(1),Int64(2),Int64(2),Int64(5),NULL],depth=1)")` is transformed into `UNNEST([1, 2, 2, 5, NULL])`.
1. Adds `unnest_to_sql` to convert an UNNEST expression to an AST. Since there is no dedicated representation for UNNEST in the AST, the implementation converts the expression to a function call.
Added unit tests, tested as part of internal https://github.com/spiceai/spiceai functionality. …
=> Add basic support for `unnest` unparsing

datafusion/sql/src/unparser/plan.rs, datafusion/sql/src/unparser/utils.rs, datafusion/sql/tests/cases/plan_to_sql.rs
With filter pushdown optimization enabled, `TableScan` filters and `LogicalPlan::Filter` without a dedicated `Projection` are incorrectly applied after the join statement, leading to incorrect results. For example
Original query (TPC-H Q13)
```sql
select
c_custkey,
count(o_orderkey)
from
customer left join orders on
c_custkey = o_custkey
and o_comment not like '%special%requests%'
group by
c_custkey
```
is unparsed as below. You can see that original filter from Join is unparsed after join as `where`. The difference is that original query will contain customer records where there is no matching order and the second version does not (filter is applied after join).
```sql
select
    "customer"."c_custkey",
    count("orders"."o_orderkey")
  from
    "customer"
  left join "orders" on …
```
=> Improve TableScan with filters pushdown unparsing (joins)

datafusion/optimizer/src/test/mod.rs
Plan textual representation is rich. Testing it's not a particular string is difficult to make robust, that's probably why the helper is unused.
=> Remove unused assert_analyzed_plan_ne test helper

datafusion/functions/src/datetime/date_part.rs, datafusion/functions/src/string/btrim.rs, datafusion/functions/src/string/ltrim.rs, datafusion/functions/src/string/rtrim.rs, datafusion/functions/src/unicode/substr.rs, docs/source/user-guide/sql/scalar_functions_new.md
Related to #13139, discussed in #13036
Complete documentation for functions with alternative syntax 
doc updates only
Yes.
Documentation
=> docs: Add alternative syntax for extract, trim and substring.

datafusion/substrait/src/logical_plan/consumer.rs, datafusion/substrait/src/logical_plan/producer.rs, datafusion/substrait/tests/cases/roundtrip_logical_plan.rs
This PR replaces adds the operation name `modulus` which is the standard [Substrait operation name](https://substrait.io/extensions/functions_arithmetic/#modulus) for `mod`
=> Add Support for `modulus` operation in substrait

datafusion/common/src/scalar/mod.rs, datafusion/expr-common/src/columnar_value.rs
Closes #.
Both `ColumnarValue` and `ScalarValue` contain the `cast_to` function, but they are inconsistent:
https://github.com/apache/datafusion/blob/7b2284c8a0b49234e9607bfef10d73ef788d9458/datafusion/expr-common/src/columnar_value.rs#L196-L216
https://github.com/apache/datafusion/blob/7b2284c8a0b49234e9607bfef10d73ef788d9458/datafusion/common/src/scalar/mod.rs#L2822-L2829
unify `cast_to` of `ColumnarValue` and `ScalarValue`.
=> unify cast_to function of ScalarValue

datafusion/optimizer/src/push_down_filter.rs, datafusion/optimizer/src/utils.rs
Closes #.
Currently, infer join predicates is supported only when `JoinType` is `Inner`.
https://github.com/apache/datafusion/blob/18b2aaa04d956475ddc74fbbde3725370e2d7bde/datafusion/optimizer/src/push_down_filter.rs#L560-L567
Support for inferring join predicate in other cases except JoinType which is Inner. e.g.
```sql
SELECT * FROM t1 LEFT JOIN t2 ON t1.c0 = t2.c0 WHERE t2.c0 > 8;
```
| JoinType  | Infer Direction | Restrict Null |
| :-------: | :-------------: | :-----------: |
|   Inner   |     L <-> R     |       N       |
|   Left    |     L <-> R     |       Y       |
|   Right   |     L <-> R     |       Y       |
| LeftSemi  |     L <-> R     |       Y       |
| RightSemi |     L <-> R     |       Y       |
| LeftAnti  |     L <-> R     |       Y       |
| RightAnti |     L <-> …
=> [Optimization] Infer predicate under all JoinTypes

datafusion/substrait/src/logical_plan/consumer.rs, datafusion/substrait/tests/cases/roundtrip_logical_plan.rs, datafusion/substrait/tests/testdata/test_plans/aggregate_sorted_no_project.substrait.json
Closes #13113.
Adding support to a new sort of expression (ORDER BY within aggregation functions) in the Substrait consumer.
For example:
> SELECT ARRAY_AGG(genre **ORDER BY genre**) FROM book
The wiring to go from Substrait's SortField to DataFusion's SortExpr in the context of aggregation measurements.
The actual conversion already existed at `from_substrait_sorts` because of window functions - I just hooked up in the context of aggragations as well.
I added a roundtrip test and also added a logical plan to check if everything was decoded correctly. Open to more ideas on how to better unit test this.
n/a
=> feat(substrait): support order_by in aggregate functions

datafusion/substrait/src/logical_plan/consumer.rs, datafusion/substrait/src/logical_plan/producer.rs
Similar to #13108.
This PR adds support for `negate` arithmetic expression, which is the [official substrait expression for negative](https://substrait.io/extensions/functions_arithmetic/#negate). 
The test case was already implemented [here](https://github.com/apache/datafusion/blob/651e8af4c5a87a7f90cdeaeab7367f43399dff52/datafusion/substrait/tests/cases/roundtrip_logical_plan.rs#L577).
=> Support `negate` arithmetic expression in substrait

datafusion/expr/src/function.rs
Closes #13148.
`ExpressionArgs` is needed to implement `WindowUDFImpl` as of https://github.com/apache/datafusion/pull/12857, but it is not currently re-exported.
`ExpressionArgs` is re-exported in datafusion_expr::function.
I placed it here because that is where `WindowUDFFieldArgs` and `PartitionEvaluatorArgs` are re-exported.
N/A
Not from any released version
=> chore: re-export functions_window_common::ExpressionArgs

datafusion/sql/src/unparser/expr.rs
N/A
Build on main is currently broken.
Remove  unneeded prefix, which is an error after #13086
Builds on CI.
Nope.
=> minor: Fix build on main

datafusion/core/tests/dataframe/mod.rs
Closes #5771
Keeping issues and code comments up to date.
Removing old outdate comment.
No.
=> minor: Update test case for issue #5771 showing it is resolved

docs/source/contributor-guide/testing.md
Follow up to https://github.com/apache/datafusion/pull/13045
Suggested by @Omega359  and @find on https://github.com/apache/datafusion/pull/13045#issuecomment-2439695514 let's make it more likely someone finds / uses the improvements in https://github.com/apache/datafusion/pull/13045
1. Add a mention of `cargo nextest` 
2. Improve the basic outline a bit too while I was in there
=> Minor: improve testing docs, mention `cargo nextest`

datafusion/expr/src/logical_plan/builder.rs, datafusion/sqllogictest/test_files/order.slt
Closes #13157
Previously we crashed on queries where the order by mentioned a missing
columns multiple times.
Only add each missing column once.
Yes, new sqllogictest.
Bugfix.
=> fix: Order by mentioning missing column multiple times

datafusion/core/tests/fuzz_cases/join_fuzz.rs
Closes #13162
Same as in #13162
Remove #[allow(unused_qualifications)] and the unused qualifiers used in importing JoinTestType from datafusion/core/tests/fuzz_cases/join_fuzz.rs
tested via `cargo clippy`
No
=> fix: import JoinTestType without triggering unused_qualifications lint

datafusion/sqllogictest/src/engines/datafusion_engine/normalize.rs, datafusion/sqllogictest/test_files/string/dictionary_utf8.slt
In SLT tests string rendering, including empty string rendering, needs to be consistent.
This fixes the rendering of `''` dictionary-encoded values.
The consistency guarantee could be made through string_query.slt.part, but this triggers other problems in the SLT framework that need to be solved first. See https://github.com/apache/datafusion/pull/13197
=> Fix rendering of dictionary empty string values in SLT tests

datafusion/core/tests/user_defined/user_defined_window_functions.rs, datafusion/expr/src/udwf.rs
Closes #13168.
Same as in  #13168.
`WindowUDFImpl::expressions` is changed to return all the input expressions by default instead of only the 1st one.
Not from a released version.
=> fix: default UDWFImpl::expressions returns all expressions

CHANGELOG.md, datafusion/CHANGELOG.md
Closes #.
Right now, if you look at the datafusion changelog
https://github.com/apache/datafusion/blob/main/CHANGELOG.md
It directs you to
https://github.com/apache/datafusion/blob/main/datafusion/CHANGELOG.md
Which then directs you to
https://github.com/apache/datafusion/tree/main/dev/changelog
This both requires 3 clicks as well as ends up directing you to the `main` version of the tree rather than a previous branch. 
1. Update the main changelog page to point directly to the changelog directory
See rendered versions here: 
https://github.com/alamb/datafusion/blob/alamb/improve_changelog/CHANGELOG.md
=> Minor: Reduce indirection for finding changlog

datafusion/optimizer/src/analyzer/type_coercion.rs, datafusion/sqllogictest/test_files/dictionary.slt
=> Support `DictionaryArray` in `OVER` clause 

datafusion/sqllogictest/bin/sqllogictests.rs, datafusion/sqllogictest/test_files/avro.slt, datafusion/sqllogictest/test_files/map.slt, datafusion/sqllogictest/test_files/pg_compat/pg_compat_types.slt, datafusion/sqllogictest/test_files/select.slt, datafusion/sqllogictest/test_files/string/dictionary_utf8.slt, datafusion/sqllogictest/test_files/string/init_data.slt.part, datafusion/sqllogictest/test_files/string/large_string.slt, datafusion/sqllogictest/test_files/string/string.slt, datafusion/sqllogictest/test_files/string/string_literal.slt, datafusion/sqllogictest/test_files/string/string_query.slt.part, datafusion/sqllogictest/test_files/string/string_view.slt, datafusion/sqllogictest/test_files/window.slt
- motivation: https://github.com/apache/datafusion/pull/13061#discussion_r1824014515
- relates to https://github.com/apache/datafusion/issues/12637
=> Allow testing records with sibling whitespace in SLT tests and add more string tests

datafusion/core/src/datasource/file_format/parquet.rs, datafusion/core/src/datasource/file_format/write/demux.rs, datafusion/core/src/datasource/listing/url.rs
Closes #9684.
Dataframe's `write_parquet()` was identified as incorrectly identifying paths without an extension as a single file output.
This change updates `start_demuxer_task` to respect the suggested behaviour:
```
tmp/dataset/ -> is a folder since it ends in /
tmp/dataset -> is still a folder since it does not end in / but has no valid file extension
tmp/file.parquet -> is a file since it does not end in / and has a valid file extension .parquet
tmp/file.parquet/ -> is a folder since it ends in /
```
* Add `file_extension()` to `ListingTableUrl` to return an Optional extension
* Update `start_demuxer_task()` to require the presence of an extension from the `ListingTableUrl` to set `single_file_output` to true
* Rename `file_extension` to `default_extension` to indicate usage will be …
=> Use single file write when an extension is present in the path.

datafusion/expr/src/expr.rs, datafusion/optimizer/src/push_down_filter.rs
Related to 
- https://github.com/apache/datafusion/issues/13060
- https://github.com/apache/datafusion/pull/13128
While reviewing https://github.com/apache/datafusion/pull/13128  I noticed that the code got a bit more complicated because `Expr::volatile` returns `Result<bool>` and thus the calling code needs now to pass up `Results`
However, `Expr::volatile` is actually infallible (never returns an error) so let's mark it as such to keep the code simpler
This is also consistent with other `Expr` methods such as `Expr::any_column_refs`
1. Minor: `Expr::volatile` infallible
By existing CI
* The signature of `Expr::volatile` has changed
=> Minor: make `Expr::volatile` infallible

datafusion/substrait/src/logical_plan/consumer.rs, datafusion/substrait/tests/cases/emit_kind_tests.rs, datafusion/substrait/tests/cases/mod.rs, datafusion/substrait/tests/testdata/test_plans/emit_kind/direct_on_project.substrait.json, datafusion/substrait/tests/testdata/test_plans/emit_kind/emit_on_filter.substrait.json
Follows up from https://github.com/apache/datafusion/pull/12495
Closes https://github.com/apache/datafusion/issues/12347
Substrait relations have an [emit_kind](https://github.com/substrait-io/substrait/blob/683f4179a058c2c99c04501b920a48ff372356ff/proto/substrait/algebra.proto#L15-L22) which is either Direct, in which case the default fields of the relation are output, or Emit, which enables precise control of the order and inclusion of fields.
For example, given a relation with the following emit
```json
"emit": {
"outputMapping": [2, 0, 1]
}
```
The output mapping indicates that from the default columns output from the relation, only the 2nd, 0th and 1st column should be output (in that order).
DataFusion currently ignores the emit_kind field entirely when reading Substrait plans.
This …
=> feat(substrait): handle emit_kind when consuming Substrait plans

datafusion/functions/src/datetime/date_bin.rs, datafusion/sqllogictest/test_files/timestamps.slt
Closes #13145
The date_bin() function was not working correctly for timestamps before 1970. Specifically if the input timestamp was the exact time of the start of a bin then it would be placed in the previous bin.
The % operator has a negative result when the dividend is negative. This causes the date_bin calculation to round up to the next bin. To compensate the size of 1 interval is subtracted from the result if the input is negative. This subtraction is no longer performed if the input is already the exact time of the start of a bin.
Yes I've added unit tests and an SQL logic test.
None, other than the bug fix itself.
=> fix: date_bin() on timstamps before 1970

datafusion/expr/src/udf.rs, datafusion/functions-nested/benches/map.rs, datafusion/functions/benches/character_length.rs, datafusion/functions/benches/concat.rs, datafusion/functions/benches/cot.rs, datafusion/functions/benches/date_bin.rs, datafusion/functions/benches/encoding.rs, datafusion/functions/benches/isnan.rs, datafusion/functions/benches/iszero.rs, datafusion/functions/benches/lower.rs, datafusion/functions/benches/ltrim.rs, datafusion/functions/benches/make_date.rs, datafusion/functions/benches/nullif.rs, datafusion/functions/benches/pad.rs, datafusion/functions/benches/repeat.rs, datafusion/functions/benches/signum.rs, datafusion/functions/benches/strpos.rs, datafusion/functions/benches/substr.rs, datafusion/functions/benches/substr_index.rs, datafusion/functions/benches/to_char.rs, datafusion/functions/benches/to_timestamp.rs, datafusion/functions/benches/trunc.rs, datafusion/functions/benches/upper.rs, datafusion/functions/src/core/version.rs
`invoke_batch` is the one used now. The others are no longer in use and we should deprecate and remove them.
Extracted from https://github.com/apache/datafusion/pull/13174
=> Deprecate ScalarUDF::invoke and invoke_no_args for invoke_batch

datafusion/substrait/src/logical_plan/consumer.rs
Closes https://github.com/apache/datafusion/issues/13218
There was a logical conflict between these two PRs:
- https://github.com/apache/datafusion/pull/13127
- https://github.com/apache/datafusion/pull/13206
Fix Build
=> Fix CI compile failure due to merge conflict

datafusion/expr/src/udf.rs, datafusion/functions/benches/random.rs, datafusion/functions/src/datetime/date_bin.rs, datafusion/functions/src/datetime/date_trunc.rs, datafusion/functions/src/datetime/from_unixtime.rs, datafusion/functions/src/datetime/make_date.rs, datafusion/functions/src/datetime/to_char.rs, datafusion/functions/src/datetime/to_date.rs, datafusion/functions/src/datetime/to_local_time.rs, datafusion/functions/src/datetime/to_timestamp.rs, datafusion/functions/src/datetime/to_unixtime.rs, datafusion/functions/src/math/log.rs, datafusion/functions/src/math/power.rs, datafusion/functions/src/math/signum.rs, datafusion/functions/src/regex/regexpcount.rs, datafusion/functions/src/string/concat.rs, datafusion/functions/src/string/concat_ws.rs, datafusion/functions/src/string/contains.rs, datafusion/functions/src/string/lower.rs, datafusion/functions/src/string/upper.rs, datafusion/functions/src/utils.rs
`invoke_batch` covers all needs, so let's deprecate and eventually remove the redundant variants.
- https://github.com/apache/datafusion/pull/13179 deprecated functions in ScalarUDF, this PR deprecates equivalent functions in ScalarUDFImpl trait.
- follows https://github.com/apache/datafusion/pull/13001
- follows https://github.com/apache/datafusion/pull/13179
=> Deprecate invoke and invoke_no_args in favor of invoke_batch

datafusion/sql/src/planner.rs, datafusion/sqllogictest/test_files/timestamps.slt
Relates to https://github.com/apache/datafusion/discussions/13230
=> Support timestamp(n) SQL type

datafusion/common/src/tree_node.rs, datafusion/physical-plan/src/insert.rs
They were deprecated since 38.0.0, which was released 6 months ago.
=> Remove elements deprecated since v 38.

datafusion/core/src/datasource/file_format/csv.rs
Closes #13087.
CsvFormat's infer_schema can now properly parse CSV data with escape characters.
Minor changes to CSV parser's infer_schema_from_stream function & a new test for these changes
yes
no
=> fix: CSV Infer Schema now properly supports escaped characters.

datafusion/core/tests/user_defined/user_defined_plan.rs, datafusion/expr/src/expr.rs, datafusion/expr/src/logical_plan/plan.rs, datafusion/expr/src/tree_node.rs, datafusion/optimizer/src/common_subexpr_eliminate.rs
Follow-up of https://github.com/apache/datafusion/pull/12177, part of https://github.com/apache/datafusion/issues/12193.
`Expr` clones can be costly, so let's avoid them if we can.
This is a minor follow-up of https://github.com/apache/datafusion/pull/12177 to remove some `Expr` clones. 
Yes, with exiting UTs.
No.
=> Remove `Expr` clones from `SortExpr`s

datafusion/common/src/stats.rs
Fixes a todo (removes a clone) in https://github.com/apache/datafusion/pull/13187 
Add code and tests to avoid cloning ColumnStatistics when possible
yes, new unit tests are added
Probably not
=> Optimize `Statistics::projection` to avoid a clone

datafusion/core/tests/user_defined/user_defined_scalar_functions.rs, datafusion/expr/src/udf.rs, datafusion/functions-nested/src/make_array.rs, datafusion/functions/src/core/version.rs, datafusion/functions/src/math/pi.rs, datafusion/functions/src/math/random.rs, datafusion/functions/src/string/uuid.rs
Migrate scalar UDFs from deprecated invoke_no_args to invoke_batch.
- follows https://github.com/apache/datafusion/pull/13174
- for https://github.com/apache/datafusion/issues/13238
=> Migrate invoke_no_args to invoke_batch

datafusion/core/tests/fuzz_cases/aggregate_fuzz.rs, datafusion/core/tests/fuzz_cases/aggregation_fuzzer/data_generator.rs, datafusion/functions-aggregate/src/min_max/min_max_bytes.rs, test-utils/src/array_gen/decimal.rs, test-utils/src/array_gen/mod.rs, test-utils/src/array_gen/primitive.rs, test-utils/src/array_gen/random_data.rs, test-utils/src/array_gen/string.rs
Part of #12114 .
Supporting more types for dataset generator in fuzzer framework is needed to improve aggregation fuzzer coverage.
- Support `Interval` and `Time` types for `PrimitiveArrayGenerator`.
- Introduce `DecimalArrayGenerator` to support `Decimal` type.
- Support `Utf8View` type.
=> feat: Add `Time`/`Interval`/`Decimal`/`Utf8View` in aggregate fuzz testing

Cargo.toml, datafusion-examples/examples/ffi/README.md, datafusion-examples/examples/ffi/ffi_example_table_provider/Cargo.toml, datafusion-examples/examples/ffi/ffi_example_table_provider/src/lib.rs, datafusion-examples/examples/ffi/ffi_module_interface/Cargo.toml, datafusion-examples/examples/ffi/ffi_module_interface/src/lib.rs, datafusion-examples/examples/ffi/ffi_module_loader/Cargo.toml, datafusion-examples/examples/ffi/ffi_module_loader/src/main.rs, datafusion/ffi/README.md, datafusion/ffi/src/table_provider.rs
Closes #13175
PR #12920 introduces FFI bindings for TableProvider but did not show an end to end example of using these. This PR improves the documentation for how to use the `datafusion-ffi` crate and a complete example of building one library that exposes a table provider and loading it from a different binary.
Adds three crates to show interface, implementation, and using a library table provider.
These are an example, not any change to core functionality.
None.
=> Example: FFI Table Provider as dynamic module loading

datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs, datafusion/sqllogictest/test_files/string/string.slt, datafusion/sqllogictest/test_files/string/string_literal.slt, datafusion/sqllogictest/test_files/string/string_query.slt.part
`expr LIKE '%'` was previously simplified to `true`, but the expression returns `NULL` when `expr` is null.
The conversion was conditional on `!is_null(expr)` which means "is not always true, i.e. is not a null literal".
This commit adds correct simplification logic. It additionally expands the rule coverage to include string view (Utf8View) and large string (LargeUtf8). This allows writing shared test cases even despite `utf8_view LIKE '%'` returning incorrect results at execution time (tracked by https://github.com/apache/datafusion/issues/12637). I.e. the simplification masks the bug for cases where pattern is statically known.
- relates to https://github.com/apache/datafusion/issues/12637 but doesn't fix it fully 
- fixes the bug for cases when pattern is static
fix correctness …
=> Fix incorrect `... LIKE '%'` simplification with NULLs

datafusion/common/src/config.rs, datafusion/core/src/datasource/file_format/csv.rs, datafusion/core/src/datasource/file_format/file_compression_type.rs, datafusion/core/src/datasource/file_format/json.rs, datafusion/core/src/datasource/listing_table_factory.rs, datafusion/proto-common/proto/datafusion_common.proto, datafusion/proto-common/src/from_proto/mod.rs, datafusion/proto-common/src/generated/pbjson.rs, datafusion/proto-common/src/generated/prost.rs, datafusion/proto-common/src/to_proto/mod.rs, datafusion/proto/src/generated/datafusion_proto_common.rs, datafusion/proto/src/logical_plan/file_formats.rs, datafusion/proto/tests/cases/roundtrip_logical_plan.rs
No related issue
I came across the following obstacles trying to write some custom schema inference code:
1. There are cases where we need to know if the user explicitly set the `schema_infer_max_rec` config.
2. The stream passed into `read_to_delimited_chunks_from_stream` does not necessarily have to be `BoxStream<'static>`
1. Make `CsvOptions::schema_infer_max_rec` and `JsonOptions::schema_infer_max_rec` `Option`s
2. Add lifetime parameter to functions in CSV and compression that makes the compiler complain
Tested with existing code and tests.
1. `CsvOptions::schema_infer_max_rec` and `JsonOptions::schema_infer_max_rec` are now `Option<usize>`s as opposed to `usize` (`with_schema_infer_max_rec` signature is unchanged)
2. `read_to_delimited_chunks`, …
=> Change `schema_infer_max_rec ` config to use `Option<usize>` rather than `usize`

datafusion/core/src/datasource/file_format/mod.rs, datafusion/core/src/datasource/listing/helpers.rs, datafusion/core/src/datasource/listing/mod.rs, datafusion/core/src/datasource/physical_plan/file_scan_config.rs, datafusion/core/src/datasource/physical_plan/file_stream.rs, datafusion/core/src/datasource/physical_plan/mod.rs, datafusion/core/src/datasource/physical_plan/parquet/mod.rs, datafusion/core/src/datasource/physical_plan/parquet/opener.rs, datafusion/core/src/datasource/schema_adapter.rs, datafusion/core/src/test_util/parquet.rs, datafusion/core/tests/parquet/custom_reader.rs, datafusion/core/tests/parquet/page_pruning.rs, datafusion/proto/src/generated/pbjson.rs, datafusion/proto/src/physical_plan/from_proto.rs, datafusion/substrait/src/physical_plan/consumer.rs
Currently you can only pass it to `ParquetExecBuilder` but that applies to entire groups of files. This adds an API to set it on a per-file basis in cases where you know the size of the metadata in each file. In our case we have a metadata store that stores information about each file, including the size of the metadata, so we know the _exact_ size in bytes and can ensure that we never have to double-request to read the entire metadata.
=> allow passing in metadata_size_hint on a per-file basis

datafusion/expr/src/logical_plan/builder.rs, datafusion/sqllogictest/test_files/errors.slt
Closes #.
Got a panic when forgot to put braces:
We have number of column validation, we just don't compare it with with the schema size.
Yes, added a new test
No
=> Ensure schema and data have the same size

datafusion/core/src/physical_optimizer/mod.rs, datafusion/physical-optimizer/src/lib.rs, datafusion/physical-optimizer/src/update_aggr_exprs.rs
=> chore: Move `OptimizeAggregateOrder` from core to optimizer crate

datafusion/expr/src/logical_plan/builder.rs
Follow on to https://github.com/apache/datafusion/pull/13182
While reviewing https://github.com/apache/datafusion/pull/13182 from @onursatici it was not immediatley clear to @gruuya https://github.com/apache/datafusion/pull/13182#discussion_r1825227285 and myself that the expressions were constrained to the left and right input
1. Improve the documentation on `LogicalPlanBuilder::join_with_expr_keys` to make this clearer
CI
Docs only
=> Minor: improve `LogicalPlanBuilder::join_with_expr_keys` docs

datafusion/sqllogictest/test_files/string/dictionary_utf8.slt, datafusion/sqllogictest/test_files/string/init_data.slt.part, datafusion/sqllogictest/test_files/string/large_string.slt, datafusion/sqllogictest/test_files/string/string.slt, datafusion/sqllogictest/test_files/string/string_literal.slt, datafusion/sqllogictest/test_files/string/string_query.slt.part
More tests before https://github.com/apache/datafusion/pull/13260 lands.
Would prevent regression https://github.com/apache/datafusion/pull/13260#discussion_r1832239184
=> Test LIKE with implicit `\` escape

datafusion/physical-expr-common/src/binary_map.rs, datafusion/physical-expr-common/src/binary_view_map.rs, datafusion/physical-expr-common/src/lib.rs, datafusion/physical-expr-common/src/tree_node.rs, datafusion/physical-expr-common/src/utils.rs
Part of https://github.com/apache/datafusion/issues/11143.
=> Enable `clone_on_ref_ptr` clippy lint on physical-expr-common crate

datafusion/core/src/physical_optimizer/mod.rs, datafusion/physical-optimizer/src/coalesce_batches.rs, datafusion/physical-optimizer/src/lib.rs
=> chore: Move `CoalesceBatches` from core to optimizer crate 

datafusion/expr/src/logical_plan/builder.rs, datafusion/optimizer/src/filter_null_join_keys.rs
`LogicalPlanBuilder::join_with_expr_keys` rejects join conditions when the join expression has one unqualified and one qualified column with the same name. This is not consistent with `LogicalPlanBuilder::join` where such cases are handled well.
This becomes a problem in `datafusion::proto` where joins are deserialised with using `join_with_expr_keys`.
Specifically, a join condition like `... from t1 join t2 where id = t2.id` where `t1.id` is written unqualified is successfully parsed and the logical plan is created. However, when it comes to deserialising such plan from proto, we hit get ambiguous reference error, and fail to deserialise.
Normalising left and right keys only get the schema for their respective tables
A new unit test is added
`join_with_expr_keys` already has a constraint …
=> join_with_expr_keys to support expressions with both unqualified and qualified column names

datafusion/core/src/execution/context/mod.rs, datafusion/core/src/physical_planner.rs, datafusion/core/tests/sql/sql_api.rs, datafusion/expr/src/expr_rewriter/mod.rs, datafusion/expr/src/logical_plan/builder.rs, datafusion/expr/src/logical_plan/display.rs, datafusion/expr/src/logical_plan/mod.rs, datafusion/expr/src/logical_plan/plan.rs, datafusion/expr/src/logical_plan/statement.rs, datafusion/expr/src/logical_plan/tree_node.rs, datafusion/optimizer/src/common_subexpr_eliminate.rs, datafusion/optimizer/src/optimize_projections/mod.rs, datafusion/proto/src/logical_plan/mod.rs, datafusion/sql/src/statement.rs, datafusion/sql/src/unparser/plan.rs, datafusion/sql/tests/sql_integration.rs, datafusion/sqllogictest/test_files/prepare.slt
See https://github.com/apache/datafusion/pull/13242#discussion_r1829802124
Move `LogicalPlan::Prepare` and `LogicalPlan::Execute` into `LogicalPlan::Statement`.
They are more suitable for being implemented as statements. This can also reduce the variants of `LogicalPlan`.
- Move PREPARE/EXECUTE into `LogicalPlan::Statement`
- Statements share a global empty schema instead of each holding a dummy schema, which eliminates the need for manual implementations of `PartialOrd`
Yes
=> refactor: move PREPARE/EXECUTE into `LogicalPlan::Statement`

datafusion/expr-common/Cargo.toml, datafusion/functions-aggregate-common/Cargo.toml, dev/release/README.md
N/A
I had to manually update two Cargo.toml files when releasing 43.0.0 because they refered to README files that do not exist.
=> chore: Post 43.0.0 release fixes

datafusion/expr-common/src/signature.rs, datafusion/expr-common/src/type_coercion/aggregates.rs
Closes #13271
As mentioned on the issue, the implementations for `information_schema.routines` and `information_schema.parameters` will need to be able to list all possible combinations of argument types.
* Implement get_possible_types for `Uniform`, `Coercible`, `Variadic`, `Numeric` and `String`.
Yes
No
=> Implement get_possible_types for Uniform, Coercible, Variadic, Numeric and String

datafusion/functions/src/string/bit_length.rs, datafusion/sqllogictest/test_files/string/string_literal.slt, datafusion/sqllogictest/test_files/string/string_query.slt.part, datafusion/sqllogictest/test_files/string/string_view.slt
Closes https://github.com/apache/datafusion/issues/13195
Thanks to @jayzhan211 , he noticed following issue which string scalar function `bit_length()` doesn't support `Utf8View` type:
```rust
select bit_length(arrow_cast('a', 'Utf8View'));
```
Update `bit_length()` scalar function to support `Utf8View`
Yes for scalar function. No for array function as it's still PR in https://github.com/apache/arrow-rs/pull/6671
=> Support `Utf8View` for string function `bit_length()`

datafusion/core/tests/fuzz_cases/aggregate_fuzz.rs, datafusion/core/tests/fuzz_cases/aggregation_fuzzer/data_generator.rs, test-utils/src/array_gen/binary.rs, test-utils/src/array_gen/mod.rs, test-utils/src/array_gen/primitive.rs, test-utils/src/array_gen/random_data.rs
Closes #13279.
Added timestamp, binary, and float for the fuzz testing
=> feat: Added Timestamp/Binary/Float to fuzz

datafusion/core/benches/sql_planner.rs, datafusion/expr/src/expr.rs, datafusion/expr/src/logical_plan/plan.rs, datafusion/sql/src/expr/mod.rs
Closes #13307.
Comparing to the release 40.0.0 there is a performance issue in function replace_params_with_values.
There was a patch, that adds name preserving to the expression during placeholders substitution:
https://github.com/apache/datafusion/commit/945902dd5d440bdc360cab60ef31cd0c3bceec41
For now replace_params_with_values works as follows:
- preserve original name
- first pass: infer placeholders types
- second pass: substitute placeholders
It unconditionally copies the original name of the expression even it has not placeholders to substitute. It can affect performance and by my measures it works 2x slower on some plans, which contain few placeholders or does not have it at all.
This pach adds the following optimization:
preserve original name and substitute placeholders only if …
=> Optimize `replace_params_with_values`

docs/source/conf.py, docs/source/contributor-guide/howtos.md, docs/source/library-user-guide/profiling.md, docs/source/library-user-guide/query-optimizer.md, docs/source/user-guide/sql/scalar_functions.md
Closes #13320.
Make the build log cleaner.
Yes. Tested on my local machine.
No.
=> Remove warning logs during the document build process

dev/release/README.md
Closes #.
I noticed we had a new ffi crate as part of 
-  #12470 
Let's document how to publish it as well
=> minor: include datafusion-ffi in publishing instructions

dev/update_datafusion_versions.py
None
In the last update to 43.0.0 we have a new crate that needs to be published but it was not included in the script.
Adds `datafusion-ffi` to publish list
No, I do not have the ability to test it.
None
=> Update dev script to publish FFI crate

datafusion/core/src/execution/context/mod.rs, datafusion/core/src/execution/session_state.rs, datafusion/expr/src/logical_plan/mod.rs, datafusion/expr/src/logical_plan/statement.rs, datafusion/sql/src/statement.rs, datafusion/sqllogictest/test_files/prepare.slt
Follow-up of #13242
Support the `DEALLOCATE` sql statement to remove prepared plans.
A typical usage is
```sh
> prepare p(int) as select $1;
0 row(s) fetched.
Elapsed 0.003 seconds.
> deallocate p;
0 row(s) fetched.
Elapsed 0.002 seconds.
```
Yes
No
=> feat: support `DEALLOCATE` to remove prepared statements

datafusion/functions-nested/src/map.rs, docs/source/user-guide/sql/scalar_functions.md
Closes #.
I'm not sure why https://github.com/apache/datafusion/pull/13324 changed the format of the code scope in `scalar_functions.md` but it causes the CI for checking the `md` file to fail.
```
Rust / check configs.md and ***_functions.md is up-to-date (pull_request) 
```
I found 2 PRs have been impacted:
- https://github.com/apache/datafusion/pull/13336
- https://github.com/apache/datafusion/pull/13338
Reformat `scalar_functions.md`
Checked by CI
no
=> Fix `scalar_functions.md` for CI

datafusion/expr/src/expr_schema.rs, datafusion/sqllogictest/test_files/metadata.slt
Part of https://github.com/apache/datafusion/issues/12733
The field metadata was not being extracted from the ExprSchema for cast expressions. When cast was used as a projection on an aggregate, it would be missing the field metadata and fail the [schema-misalignment check](https://github.com/apache/datafusion/blob/322d83526909ab44cfbe34b982d1a1c36a4dbe8f/datafusion/core/src/physical_planner.rs#L676) (see [background epic](https://github.com/apache/datafusion/issues/12733#issue-2563622229)).
The result was that the logical plan schema did not have the field metadata, whereas the physical plan schema did:
```
Schema { 
fields: [
Field { 
name: "dist", 
data_type: Date32, 
nullable: false, 
dict_id: 0, 
dict_is_ordered: false, 
metadata: {"metadata_key": "ts non-nullable field"} 
}
], …
```
=> Fix ExprSchema extraction of metadata for Cast expressions.

datafusion/functions-nested/src/concat.rs, docs/source/user-guide/sql/scalar_functions.md
Closes #.
Added changes to array_prepend to fix the tests that are failing due to the changes in #13362
=> fix: Fix failures caused by `array_prepend`

datafusion/expr-common/src/signature.rs, datafusion/expr/src/type_coercion/functions.rs, datafusion/functions-aggregate/src/count.rs, datafusion/functions-nested/src/make_array.rs, datafusion/functions-window/src/cume_dist.rs, datafusion/functions-window/src/rank.rs, datafusion/functions-window/src/row_number.rs, datafusion/functions/src/datetime/current_date.rs, datafusion/functions/src/datetime/current_time.rs, datafusion/functions/src/datetime/now.rs, datafusion/functions/src/math/pi.rs, datafusion/functions/src/math/random.rs
Closes #.
Currently there are uniform(0), any(0), exact(0) 3 ways to describe zero argument signature. To avoid confusion, add `TypeSignature::ZeroArg` and disable 0 argument for those 3 signatures, they now require at least one argument.
=> Support TypeSignature::Nullary

datafusion/expr/src/expr_schema.rs
Follow-up to https://github.com/apache/datafusion/pull/13310, closes https://github.com/apache/datafusion/issues/9375.
This is a small follow-up change to the previous PR to fix the stack overflow issue in https://github.com/apache/datafusion/issues/9375.
Please note that during the investigation 2 different issues were discovered:
- There was a stack overflow with `debug` build due to `sqlparser`, and this didn't come up with `release` build: https://github.com/apache/datafusion/issues/9375#issuecomment-2469909998.
- And there was a different stack overflow with `release` build: https://github.com/apache/datafusion/issues/9375#issuecomment-2470000115.
This PR fixes only the 2nd issue.
Most likely the 1st issue can also be fixed with stacker/recursive, but the change would be required in …
=> Annotate `Expr::get_type()` with recursive

datafusion/functions/src/core/nullif.rs, datafusion/sqllogictest/test_files/nullif.slt, datafusion/sqllogictest/test_files/string/string_view.slt
Closes  #13379
Completing support for StringView in udfs
Code, tests.
yes
No
=> Add utf8view support in nullif

datafusion/core/tests/fuzz_cases/join_fuzz.rs, datafusion/physical-plan/src/joins/sort_merge_join.rs, datafusion/sqllogictest/test_files/sort_merge_join.slt
Closes #12359 
Closes #10659
Move the Full Outer filtered SMJ join out of `join_partial` phase to evaluate filter expressions properly and keep track of previous related expressions already evaluated for the same row
=> Move filtered SMJ Full filtered join out of `join_partial` phase

datafusion-examples/examples/advanced_parquet_index.rs, datafusion/core/tests/parquet/external_access_plan.rs, datafusion/core/tests/parquet/mod.rs, datafusion/execution/src/disk_manager.rs, datafusion/physical-plan/src/joins/cross_join.rs, datafusion/physical-plan/src/joins/hash_join.rs, datafusion/physical-plan/src/joins/nested_loop_join.rs, datafusion/physical-plan/src/repartition/mod.rs, datafusion/physical-plan/src/sorts/cursor.rs
Closes #13278.
This PR refactors instances where `#[allow(dead_code)]` was used on struct fields that exist solely to ensure their `Drop` (destructor) is called. In such cases, the field name has been updated to use an underscore prefix (e.g., `_name`) instead of relying on `#[allow(dead_code)]`. This change aligns with idiomatic Rust practices, where _ prefixes indicate that fields or variables are intentionally unused but still necessary (e.g., memory reservation, tmp file cleanup in the source code).
Yes, in local environment.
=> Remove uses of #[allow(dead_code)] in favor of _identifier

Cargo.toml, datafusion/core/tests/fuzz_cases/aggregate_fuzz.rs, test-utils/Cargo.toml, test-utils/src/array_gen/primitive.rs
Closes #13302 .
Added random timezones to fuzz test for timestamps
=> feat: Add random timezone to aggregate fuzz test

datafusion/sql/src/unparser/plan.rs, datafusion/sql/tests/cases/plan_to_sql.rs
Closes #12773
When parsing a query into a logical plan, aggregation precedes projection. But optimiser can eliminate projection, leaving aggregation as a top node. This is not expected by `select_to_sql_recursively` because it always handles projection and aggregation together. 
Added a separate branch if aggregation is the top node. 
Yes, added a new test
No
=> Allow aggregation without projection in `Unparser`

datafusion/core/src/execution/context/mod.rs, datafusion/core/src/execution/session_state.rs, datafusion/expr/src/planner.rs, datafusion/sql/src/planner.rs, datafusion/sql/tests/common/mod.rs, datafusion/sql/tests/sql_integration.rs
Closes #13292 .
yes
A new trait for ExprPlanner
=> Introduce `TypePlanner` for customizing type planning

datafusion/functions/src/datetime/date_bin.rs, docs/source/user-guide/sql/scalar_functions.md
Part of #7013 
I was making an example for something and referring to `date_bin` docs and noticed it had no SQL example (and thus I also accidnetally mixed up the argument order)
https://datafusion.apache.org/user-guide/sql/scalar_functions.html#date-bin
Let's add one (mostly to save myself work in the future)
Add an SQL example for date_bin:
=> Minor: Add SQL example for `date_bin`

datafusion/expr-common/src/type_coercion/binary.rs, datafusion/sqllogictest/test_files/coalesce.slt
=> Add Utf8View to `TypeCategory::Unknown`

datafusion/functions-nested/src/string.rs, docs/source/user-guide/sql/scalar_functions.md
Closes #13384.
Added and fixed docs for array_to_string and string_to_array
=> fix: Fix documentation for `null_string` to `array_to_string` + `string_to_array`

datafusion-examples/README.md, datafusion-examples/examples/expr_api.rs, datafusion/optimizer/src/analyzer/type_coercion.rs, datafusion/sql/README.md
Closes #13375.
- Expose `TypeCoercionRewriter::new`.
- Add examples for applying type coercion to expressions.
- Update out-of-date README for the datafusion-sql module
The `TypeCoercionRewriter::new` is now made public.
=> chore: expose TypeCoercionRewriter::new and add examples for type coerce expressions

datafusion/core/src/datasource/physical_plan/json.rs, datafusion/physical-plan/src/joins/sort_merge_join.rs, datafusion/physical-plan/src/memory.rs, datafusion/physical-plan/src/recursive_query.rs, datafusion/physical-plan/src/sorts/partial_sort.rs, datafusion/physical-plan/src/work_table.rs
N/A
These were all of the `ExecutionPlan` implementations that I found that didn't expose all of their properties needed for instantiation. Exposing the properties now makes the API consistent across all `ExecutionPlan` implementations.
We exposed the properties of `NdJsonExec`, `SortMergeJoinExec`, `MemoryExec`, `RecursiveQueryExec`, `PartialSortExec`, and `WorkTableExec`.
These are simple getters. No tests are needed.
These are backwards compatible changes to user-facing APIs.
=> Add getters to  `ExecutionPlan` Properties

datafusion/core/src/datasource/default_table_source.rs
Fixes a tiny bug where `DefaultTableSource::table_type` would always return `TableType::Base` regardless of the actual table type of the provider.
Yes there is a unit test.
=> Have DefaultTableSource return the correct TableType

datafusion/functions/src/regex/regexpcount.rs
Closes #13413
Fixes bug, also code refactoring to have less allocations and calculate hash less often.
Yes, the new unit test has been added to cover a bug fix. Also, bench results.. so regexp_count has similar perf as other regexp functions now:
```rs
regexp_count_1000 string
time:   [2.4421 ms 2.4491 ms 2.4562 ms]
change: [-2.4790% -2.1304% -1.7839%] (p = 0.00 < 0.05)
regexp_count_1000 utf8view
time:   [2.4608 ms 2.4686 ms 2.4766 ms]
change: [-2.4392% -1.9838% -1.5766%] (p = 0.00 < 0.05)
regexp_like_1000        time:   [2.4550 ms 2.4806 ms 2.5182 ms]
change: [-2.9338% -1.1353% +0.4878%] (p = 0.23 > 0.05)
No change in performance detected.
Found 2 outliers among 100 measurements (2.00%)
regexp_match_1000 …
```
=> Fix `regex` cache on pattern, less alloc, hash less often

datafusion/common/src/dfschema.rs
N/A
I’m trying to implement a schema comparison functionality in my project based on the semantic equality of `DFSchema`. However the helper function `datatype_is_semantically_equal ` is currently private. It would be really helpful if this could be made public, similar to `datatype_is_logically_equal`.
Make `DFSchema::datatype_is_semantically_equal` public
N/A
Yes, Documentation needs to be updated to reflect the new public function
=> Make DFSchema::datatype_is_semantically_equal public

datafusion/functions/src/crypto/basic.rs, datafusion/functions/src/crypto/digest.rs, datafusion/functions/src/crypto/md5.rs, datafusion/functions/src/crypto/sha224.rs, datafusion/functions/src/crypto/sha256.rs, datafusion/functions/src/crypto/sha384.rs, datafusion/functions/src/crypto/sha512.rs, datafusion/sqllogictest/test_files/expr.slt, datafusion/sqllogictest/test_files/string/string_view.slt
Closes  #13406
Completing  support for utf8view in functions.
Code, tests.
Yes
No
=>  Add support for Utf8View to crypto functions

datafusion/core/tests/expr_api/simplification.rs, datafusion/functions/src/string/concat.rs
This addresses one item of https://github.com/apache/datafusion/issues/13330
Concat simplifier was not correctly combining the return types, so Utf8View was instead getting returned as Utf8, causing a schema failure.
When combining schema in simplifier, follows the same rules to set the return type.
Tested in unit tests and with tests in `datafusion-python` that identified the problem.
Added additional checks in current unit test.
None
=> Fix `concat` simplifier for Utf8View types

benchmarks/README.md, benchmarks/bench.sh, benchmarks/src/bin/dfbench.rs, benchmarks/src/bin/sort_integration.rs, benchmarks/src/lib.rs, benchmarks/src/sort_tpch.rs
Closes #.
I noticed there is no benchmark to test sorting the whole relational table: existing sort benchmark is only for a single `SortExec`, and this can't test how would end-to-end large sort query scale to multiple CPU cores. With integration test, it is possible to see the combined performance of local sort on small batches and final step multi way sort-preserving merge.
The benchmark includes 10 queries to sort the entire `lineitem` table in TPCH dataset, with different characteristics. For example: with different number of sort key/ payload columns, different sort key types and cardinality, etc. Also it is easy to add more benchmark queries.
More details see `sort_integration.rs`
Added a single benchmark binary for benchmark. It can be executed with:
```sh
./bench.sh run …
```
=> Add sort integration benchmark

datafusion/core/src/execution/context/mod.rs
I'm not sure that changing the implementation is possible at this point. We could call deregister_table but I fear that's not atomic. So we'd have to change the implementation of SchemaProvider, a breaking change.
=> fix docs of register_table to match implementation

datafusion/core/src/datasource/file_format/csv.rs, datafusion/core/src/datasource/file_format/json.rs, datafusion/core/src/datasource/file_format/mod.rs, datafusion/core/src/datasource/physical_plan/csv.rs, datafusion/core/src/datasource/physical_plan/json.rs
None
Part of #13411
This PR implements a common `Decoder` trait, the `BatchDeserializer` trait and the `DecoderDeserializer` struct as described in the issue, along with `CsvDecoder` and `JsonDecoder` as `arrow-csv` and `arrow-json` `Decoder`s are readily available.
Note: There are about 290 lines of new tests, so it is about 250 lines of actual code.
- Add `BatchDeserializer` as a common interface.
- `digest` consumes the input in chunks
- `next` attempts to deserialize the digested data and returns a `DeserializerOutput` which is either a `RecordBatch`, `RequiresMoreData` and `InputExhausted`
- `finish` signals the end of the input stream
- Add `Decoder` trait
- Mimics arrow-json and arrow-csv's `Decoder`s
- Implement `Decoder` for `CsvDecoder` and `JsonDecoder` by forwarding methods
- …
=> Deduplicate and standardize deserialization logic for streams

datafusion/physical-plan/src/sorts/sort.rs
Closes #.
`ExternalSorter` is a big and important struct for sorting execution, this PR only organizes its fields for readability: fields are put into different categories, and closely related ones are put next to each other.
=> Minor: Doc and organize fields in `struct ExternalSorter`

datafusion/functions-nested/src/planner.rs, datafusion/sql/src/unparser/expr.rs, datafusion/sql/tests/cases/plan_to_sql.rs
Closes #11144.
DataFusion will plan the array construction and the elements' access to the corresponding scalar functions. If we don't handle those cases, they will be unparsed to `ast::Expr::ScalarFunction` which isn't a common SQL syntax.
```
SELECT [1, 2, 3] -> make_array(1, 2, 3)
```
```
SELECT [1, 2, 3][1] -> array_element(make_array(1,2,3), 1)
```
This PR tries to allow the array SQL to do SQL-Plan-SQL roundtrip.
- Unparse `make_array` to `ast::Expr::Array`
- Unparse `array_element` to `ast::Expr::Subscript`
expr unit tests and SQL roundtrip tests.
no
=> Support unparsing Array plan to SQL string

datafusion/core/src/physical_optimizer/join_selection.rs, datafusion/core/src/physical_planner.rs
none
Do not compute expensive condition before checking inexpensive condition first
no
no
=> Evaluate cheaper condition first in join selection and physical planner 

datafusion/sql/src/unparser/dialect.rs, datafusion/sql/src/unparser/expr.rs, datafusion/sql/src/unparser/utils.rs
N/A
When unparsing `CharacterLengthFunc` scalar function to DuckDB & SQLite syntax SQL query, the `CharacterLengthFunc` scalar function need to be unparsed to `length`, since `length` is the equivalence of `CharacterLengthFunc` in DuckDB & SQLite.
DuckDB [length()](https://duckdb.org/docs/sql/functions/char.html#lengthstring)
SQLite [length()](https://www.sqlite.org/lang_corefunc.html#length)
- Add struct `DuckDBDialect`, which implements the `Dialect` trait
- Add new method `character_length_style` for `Dialect` trait for determining the `CharacterLengthStyle` to use for a dialect
- Add helper function `character_length_to_sql`, which unparses the `CharacterLengthFunc` to `length` or `character_length` based on  `CharacterLengthStyle` 
Yes
No
=> Fix duckdb & sqlite character_length scalar unparsing

datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs
per https://github.com/apache/datafusion/pull/13260#discussion_r1830873028
=> chore: remove unnecessary test helpers

datafusion/core/src/physical_planner.rs
For https://github.com/apache/datafusion/issues/12733
Better error message to help downstream projects and make it easier to provide reproducers
Example error message
```
Datafusion error: Internal error: Physical input schema should be the same as the one converted from logical input schema. Differences:
- field nullability at index 3 [return_rank]: (physical) false vs (logical) true
- field nullability at index 4 [currency_rank]: (physical) false vs (logical) true.
This was likely caused by a bug in DataFusion's code and we would welcome that you file an bug report in our issue tracker
```
Enhanced error message when physical schema and schema-from-logical (aka logical schema) do not match as expected
No
Yes
=> Produce informative error on physical schema mismatch

datafusion/core/src/physical_optimizer/join_selection.rs, datafusion/sqllogictest/test_files/join.slt
Fixes https://github.com/apache/datafusion/issues/13425
Fix query regression in DF 43
Proper guard for swapping potentially unswappabe join
yes
yes
=> Fix invalid swap for LeftMark nested loops join

datafusion/physical-plan/src/unnest.rs, datafusion/sqllogictest/test_files/unnest.slt
Closes #13237.
In the current implementation, during the process where we align all columns to match the length of the longest unnest operation, it can result in excessive data copying and lead to unexpected errors for queries such as:
`select * from (select unnest(range(0, 100000)) id) t inner join (select unnest(range(0, 100000)) id) t1 on t.id = t1.id;`
This can trigger errors like `attempt to add with overflow`
Introduced repeat_mask to determine which columns need to be repeated or replaced with nulls based on:
1. Whether the column is required in future unnesting levels.
2. Whether the column is involved in unnesting at all.
Ensures only necessary columns are repeated, reducing unnecessary data copying.
Yes
No
=> Fix redundant data copying in unnest

datafusion/catalog/src/table.rs
Closes #13439
We don't want to lose this method in a refactor, and it has no tests.
Docs indicating that it is being used.
No, its just docs.
They will see the docs.
=> Add docs on TableProvider::statistics()

datafusion/sql/src/unparser/expr.rs
Closes #13461
Now that Utf8View is being returned by DataFusion, we need to ensure that when we encounter it as part of unparsing an expression, we support it properly.
Correctly maps the Utf8View Arrow data type to the existing Utf8 type for unparsing.
Yes
No API changes.
=> Support Utf8View in Unparser `expr_to_sql`

datafusion/sql/src/unparser/plan.rs, datafusion/sql/tests/cases/plan_to_sql.rs
Closes #13459
This fixes the unparser to explicitly treat inner `JOIN` with no conditions as a `CROSS JOIN`, which works for all database systems. DataFusion treats inner joins with no conditions as a `CROSS JOIN` - but not all database systems the unparser targets support that.
When generating the SQL AST for an Inner join with no conditions, return a CROSS JOIN operator instead.
Yes
No API changes.
=> Unparse inner join with no conditions as a cross join

datafusion/physical-plan/src/sorts/sort.rs, datafusion/physical-plan/src/topk/mod.rs
Closes #.
I came across this when writing https://github.com/GreptimeTeam/greptimedb/pull/5018. `partition` and `partition_id` are the same things.
A minor refactor to remove the unnecessary inparam.
No need
API change for those who use `TopK` directly like me in https://github.com/GreptimeTeam/greptimedb/pull/5018
=> MINOR: remove one duplicated inparam in TopK

datafusion/common/src/hash_utils.rs, datafusion/expr/src/utils.rs, datafusion/sqllogictest/src/test_context.rs, datafusion/sqllogictest/test_files/information_schema_columns.slt, datafusion/sqllogictest/test_files/joins.slt
None
fix potential query failure due to incorrect `can_hash` result
- update `can_hash` 
- cleanup `compute_hashes`
Yes, unit tests.
query-based tests are hard to write -- it is unclear how to construct Union or RunEndEncoded types in SQL
yes
=> Fix join on arrays of unhashable types and allow hash join on all types supported at run-time

datafusion/core/src/datasource/physical_plan/arrow_file.rs, datafusion/core/src/datasource/physical_plan/avro.rs
Remove `#[allow(dead_code)]` suppressions that look redundant.
- Relates to https://github.com/apache/datafusion/issues/13278
=> Remove redundant dead_code check suppressions

.github/actions/setup-builder/action.yaml, ci/scripts/retry
hopefully fixes  https://github.com/apache/datafusion/issues/13494
Try to fix CI stability issue.
Try add a timeout to the apt-get invocation so that retry can kick in.
CI script hange
no
no
=> chore: try make Setup Rust CI step immune to network hang

datafusion-cli/Cargo.lock, datafusion/core/src/physical_optimizer/mod.rs, datafusion/physical-optimizer/Cargo.toml, datafusion/physical-optimizer/src/lib.rs, datafusion/physical-optimizer/src/pruning.rs
part of https://github.com/apache/datafusion/issues/11502.
=> Move `Pruning` into `physical-optimizer` crate

datafusion/common/src/tree_node.rs, datafusion/expr/src/expr.rs, datafusion/expr/src/logical_plan/ddl.rs, datafusion/expr/src/logical_plan/plan.rs, datafusion/expr/src/logical_plan/statement.rs, datafusion/expr/src/logical_plan/tree_node.rs, datafusion/expr/src/tree_node.rs, datafusion/optimizer/src/optimize_projections/mod.rs, datafusion/sql/src/unparser/rewrite.rs
Part of https://github.com/apache/datafusion/issues/8913.
The current implementation of `LogicalPlan:apply_children()`, `LogicalPlan::map_children()`, `LogicalPlan::apply_expressions()`, `LogicalPlan::map_expressions()`, `Expr::apply_children()` and `Expr::map_children()` are confusing due the `map_until_stop_and_collect` macro. I think we can introduce a trait that can contain arbitrary sibling elements that functions can be applied on and mapped:
```rust
/// [`TreeNodeContainer`] contains elements that a function can be applied on or mapped. The
/// elements of the container are siblings so the continuation rules are similar to
/// [`TreeNodeRecursion::visit_sibling`] / [`Transformed::transform_sibling`].
pub trait TreeNodeContainer<'a, T: 'a>: Sized {
fn apply_elements<F: FnMut(&'a T) …
```
=> Add `Container` trait and to simplify `Expr` and `LogicalPlan` apply and map methods

datafusion/physical-plan/src/aggregates/group_values/mod.rs, datafusion/physical-plan/src/aggregates/group_values/multi_group_by/mod.rs, datafusion/sqllogictest/test_files/group_by.slt
Closes #13263.
Add group column for Date/Time/Timestamp
=> feat: Support faster multi-column grouping ( `GroupColumn`) for `Date/Time/Timestamp` types

datafusion/expr-common/src/type_coercion/binary.rs, datafusion/functions-nested/src/make_array.rs, datafusion/sqllogictest/test_files/array.slt, datafusion/sqllogictest/test_files/union.slt
Closes #12291
Currently, we don't attempt to coerce inner list types, and so this works (although it shouldn't)
```sql
SELECT make_array(2) x UNION ALL SELECT make_array(now()) x;
```
Now we’ll try to coerce inner types instead of just using the type of the first array.
Yes, added a test
No
=> Coerce Array inner types

datafusion/physical-plan/src/aggregates/group_values/row.rs
related to
- https://github.com/apache/datafusion/issues/13505
I want to know when the aggregation path is using the slower (but general) `GroupValuesRows` so we can verify that work like https://github.com/apache/datafusion/issues/13505 has been completed
Add a `debug` log message with some comments
N/A
No
=> Minor: Add debug log message for creating GroupValuesRows

datafusion/sql/src/unparser/expr.rs, datafusion/sql/tests/cases/plan_to_sql.rs
Closes #13477 
Support roundtrip for statements containing `named_struct` and `get_field`
Implement expr_to_sql for `named_struct` and `get_field`
Yes
No
=> Unparse struct to sql

datafusion/expr/src/lib.rs, datafusion/expr/src/udf.rs, datafusion/functions/benches/random.rs, datafusion/functions/src/core/version.rs, datafusion/functions/src/datetime/to_local_time.rs, datafusion/functions/src/datetime/to_timestamp.rs, datafusion/functions/src/datetime/to_unixtime.rs, datafusion/functions/src/math/log.rs, datafusion/functions/src/math/power.rs, datafusion/functions/src/math/signum.rs, datafusion/functions/src/regex/regexpcount.rs, datafusion/functions/src/utils.rs, datafusion/physical-expr/src/scalar_function.rs
Closes https://github.com/apache/datafusion/issues/12819.
There is currently no way to determine the schema-defined nullability of the arrays from `args: &[ColumnarValue],`from the `invoke_batch` function. The array nullability `Array::is_nullable()` (which is available) only checks the array null count.
If the return type (from `ScalarUDFImpl::return_type`) is passed to the newly defined invoke method then this datatype can be inspected and any nullability information can be inferred. 
Define a new trait function `invoke_batch_with_return_type` which defaults to calling to `invoke_batch`.
Example usage can be seen [here](https://github.com/apache/datafusion/pull/13289).
There are no breaking changes, but a new optional method is added.
=> Add `ScalarUDFImpl::invoke_with_args` to support passing the return type created for the udf instance

datafusion/core/src/dataframe/mod.rs, datafusion/core/src/datasource/file_format/arrow.rs, datafusion/core/src/datasource/file_format/mod.rs, datafusion/core/src/datasource/physical_plan/avro.rs, datafusion/core/src/datasource/physical_plan/json.rs, datafusion/core/src/datasource/physical_plan/parquet/mod.rs, datafusion/core/tests/parquet/page_pruning.rs, datafusion/physical-plan/src/aggregates/topk_stream.rs, datafusion/sql/src/expr/mod.rs, datafusion/sql/src/select.rs
N/A
Replace `&[T.clone()]` with `std::slice::from_ref(&T)` to avoid cloning of T.
No
=> refactor: use `std::slice::from_ref` to remove some clones

datafusion/common/src/utils/proxy.rs, datafusion/execution/src/memory_pool/mod.rs, datafusion/physical-expr-common/src/binary_map.rs, datafusion/physical-expr-common/src/binary_view_map.rs
For #13256, but only parts of it.
Prepare `hashbrown` 0.15 upgrade.
- `HashTableAllocExt`
- a few migrations
Existing tests pass.
No.
=> refactor: change some `hashbrown` `RawTable` uses to `HashTable`

datafusion/expr/src/table_source.rs, datafusion/optimizer/src/push_down_filter.rs
When using pushdown filters, the planner pushes the volatile `random()` filter to the table source, so it executes in scan (for example, in parquet) and in the query engine, which leads to weird results.
Closes #13268.
It's impossible to evaluate volatile filters in different layers.
- Improvement for rule optimiser to avoid passing volatile filters to scan
- Unit test
- Unit tests
- Regression tests
- Manual test
As proposed in the original issue, I tried `alltypes_tiny_pages_plain.parquet` sample file containing 7300 lines:
```sql
set datafusion.execution.parquet.pushdown_filters=true;
create external table data stored as parquet location 'alltypes_tiny_pages_plain.parquet';
```
Running a query 
```sql
select COUNT(*) from data WHERE RANDOM() < 0.1;
```
with `datafusion-cli` gives an …
=> Avoid pushdown of volatile functions to tablescan

datafusion/functions-nested/src/map.rs, datafusion/sql/src/unparser/expr.rs, datafusion/sql/tests/cases/plan_to_sql.rs, datafusion/sqllogictest/test_files/map.slt
Implements `map` for #13478. For `get_field` it doesn't look like there is a way to distinguish if it is a map access from the expression.
Support roundtrip for statements containing `map`
Implement `expr_to_sql` for `map`. 
Yes
No
=> Unparse map to sql

datafusion/execution/src/runtime_env.rs
Closes #.
Having a version in the message lets us know when we can remove it in the future
=> Minor: add version to RuntimeEnv::new deprecation message

datafusion/common/src/hash_utils.rs
Previously it would panic due to division by zero.
=> Fix panic when hashing empty FixedSizeList Array

datafusion/sqllogictest/test_files/union.slt
Closes #.
I encountered a CI failure in https://github.com/apache/datafusion/actions/runs/11995648362/job/33439273622?pr=13540
```
External error: query result mismatch:
[SQL] select make_array(make_array(1)) x UNION ALL SELECT make_array(arrow_cast(make_array(-1), 'LargeList(Int8)')) x;
[Diff] (-expected|+actual)
-   [[-1]]
-   [[1]]
+   [[1]]
+   [[-1]]
at test_files/union.slt:775
```
I think for `UNION ALL` statements, output order is not deterministic
So this PR specified the output order in failed test cases.
=> Minor: Fix two test cases causing CI failures by adding `rowsort`

datafusion/physical-plan/src/aggregates/group_values/mod.rs, datafusion/physical-plan/src/aggregates/group_values/multi_group_by/mod.rs, datafusion/physical-plan/src/aggregates/group_values/multi_group_by/primitive.rs, datafusion/sqllogictest/test_files/group_by.slt
=> Set timezone for group column timestamp type

datafusion/optimizer/src/analyzer/subquery.rs, datafusion/sqllogictest/test_files/unnest.slt
Closes #13498.
Subquery's check_inner_plan support LogicalPlan::Unnest
Add handling for LogicalPlan::Unnest
Add new test
Yes
No
=> Support Unnest in Subqueries

datafusion/physical-expr/src/planner.rs, datafusion/sqllogictest/test_files/string/string_literal.slt
Other escape characters are currently not supported.
=> Support LIKE with ESCAPE `\`

datafusion/physical-plan/src/execution_plan.rs
Replace with usage of `DataFusionError::strip_backtrace`.
=> chore: Remove redundant assert_starts_with test helper

.gitignore, datafusion/core/tests/parquet/external_access_plan.rs, datafusion/core/tests/parquet/mod.rs
Closes #13530.
I always receive this warning when running `cargo clippy`, and I would like to get rid of it.
=> test: allow external_access_plan run on windows

datafusion/sqllogictest/test_files/string/dictionary_utf8.slt, datafusion/sqllogictest/test_files/string/init_data.slt.part, datafusion/sqllogictest/test_files/string/large_string.slt, datafusion/sqllogictest/test_files/string/string.slt, datafusion/sqllogictest/test_files/string/string_query.slt.part, datafusion/sqllogictest/test_files/string/string_view.slt
- arrow upgrade https://github.com/apache/datafusion/pull/13508
- fixed https://github.com/apache/datafusion/issues/12637
- apparently fixed https://github.com/apache/datafusion/issues/13329 (resolving associated todos)
- this PR resolves remaining todos, thus
- closes https://github.com/apache/datafusion/issues/12637
- closes https://github.com/apache/datafusion/issues/13329
cc @goldmedal @austin362667 @jayzhan211
=> Update tests and resolve TODOs after arrow update

datafusion-examples/examples/custom_datasource.rs
Made imports explicit so the "custom datasource" example can be copied/pasted outside the repo.
This example was referenced in the wiki, but some imports were not friendly for copying/paste. I see no reason to keep them the old way, especially because the file is meant to be a template.
I have just renamed the imports to make them work outside this repo.
Now the example could be compiled without issue :)
=> Fixed imports in custom_datasource.rs example

datafusion/sqllogictest/test_files/decimal.slt
closes https://github.com/apache/datafusion/issues/12870
Bug for fixed in https://github.com/apache/arrow-rs/pull/6547, this pr just adds a test for it
No
=> Add zero-`decimal`-cast test

Cargo.toml, datafusion/sqllogictest/src/engines/conversion.rs
Closes #10001.
We use the bigdecimal crate to format decimal values to strings and display them in sqllogical tests(SLTs).
The new version of bigdecimal formats certain decimals in scientific notation, which will break many SLT tests.
There are two possible solutions:
1. Set the compile-time environment variables for bigdecimal, such as `RUST_BIGDECIMAL_FMT_EXPONENTIAL_LOWER_THRESHOLD`. However, I'm a bit concerned about whether it's appropriate to operate environment variables in a library like DataFusion. Additionally, we might need to introduce a separate Cargo config.toml into the project root directory so that `cargo test --test sqllogictests` can work.
2. Implement our own method for formatting decimals.
This PR takes the latter approach.
Yes. By new UTs and existing SLT tests.
No. …
=> chore(deps): update bigdecimal from 0.4.1 to 0.4.6

datafusion/functions-aggregate-common/src/utils.rs, datafusion/physical-expr/src/aggregate.rs, datafusion/physical-plan/src/aggregates/topk/heap.rs
- Related to https://github.com/apache/datafusion/issues/13505
- Related to https://github.com/apache/datafusion/pull/13564
While reviewing https://github.com/apache/datafusion/pull/13564#pullrequestreview-2465814062 @jayzhan211  pointed out this function wasn't necessary as there is now equivalent functionality in arrow-rs
It is confusing there are two patterns to do the same thing, so let's remove the DataFusion specific pattern
1. Change code to use `PrimitiveArray::with_data_type` instead
2. Deprecate adjust_output_array
By CI
=> Deprecate `adjust_output_array` in favor of `PrimitiveArray::with_data_type`

datafusion/common/src/cast.rs
These functions are useful when implementing UDFs. It would be helpful for downstream projects to provide graceful cast functions for all data types.
=> Supplement as_*_array functions

Cargo.toml, benchmarks/Cargo.toml, benchmarks/src/bin/external_aggr.rs, benchmarks/src/bin/h2o.rs, benchmarks/src/imdb/run.rs, benchmarks/src/sort.rs, benchmarks/src/sort_tpch.rs, benchmarks/src/tpch/run.rs, benchmarks/src/util/options.rs, benchmarks/src/util/run.rs, datafusion-cli/Cargo.lock, datafusion/common/Cargo.toml, datafusion/common/src/config.rs, datafusion/core/Cargo.toml, datafusion/core/tests/fuzz_cases/aggregation_fuzzer/context_generator.rs, datafusion/core/tests/sql/mod.rs, datafusion/sqllogictest/Cargo.toml, datafusion/sqllogictest/bin/sqllogictests.rs
Removes `num_cpus` to reduce number of dependencies.
=> [Minor] Use std::thread::available_parallelism instead of `num_cpus`

rust-toolchain.toml
Temporarily pin toolchain version until problems reported by newer clippy release are solved.
- Workaround for https://github.com/apache/datafusion/issues/13597
=> Temporarily pin toolchain version to avoid clippy

dev/release/README.md
Related to 
- https://github.com/apache/datafusion/issues/13499
If we are going to do backports more frequently, let's add an example of doing so
add an example of how to `cherry-pick` / backport to release instructions
=> Minor: Add example of backporting / `cherry-pick`ing to release branch

datafusion/core/src/physical_optimizer/join_selection.rs, datafusion/physical-plan/src/joins/test_utils.rs
N/A.
Using succinct test utility functions instead of verbose constructions, making some downstream-useful test utils crate-public.
Verbose usages in unit tests of `join_selection.rs` is cleaned up, three useful test utils are made crate-public for facilitating DRY in forks.
No, only three useful test utils are now crate-accessible by devs.
=> Tidy up join test code

datafusion/expr/src/expr_fn.rs
This is helpful for simple function implementations or function stubs, when `Signature::exact` is not desired.
=> Add SimpleScalarUDF::new_with_signature

datafusion/expr/src/logical_plan/plan.rs, datafusion/expr/src/logical_plan/tree_node.rs
Part of https://github.com/apache/datafusion/issues/8913.
`LogicalPlan::..._with_subqueries()` methods don't handle correctly if an `f_down` closure/method returns `TreeNodeRecursion::Jump`. Currently if `TreeNodeRecursion::Jump` is returned then the node's subquery expression plans are not visited but the node's children are.
This PR fixes `LogicalPlan::_with_subqueries()` behaviour and when `TreeNodeRecursion::Jump` is returned then neither the node's subquery expression plans nor the node's children are visited.
Yes, added new tests.
No.
=> Fix `LogicalPlan::..._with_subqueries` methods

datafusion/sql/src/planner.rs, datafusion/sqllogictest/test_files/errors.slt
- Part of https://github.com/apache/datafusion/pull/13546
While working on the upgrade of sqlparser, the structure has changed and thus the debug formatting has changed (so I needed to change this error message anyways)
The error message was hard to understand anyways, so I spent a few moments improving it to show the actual indentifers rather than a debug version
1. Improve error message and test
Yes
=> Improve unsupported compound identifier message

datafusion/sql/src/planner.rs, datafusion/sql/src/utils.rs
Follow on to https://github.com/apache/datafusion/pull/13605
As suggested by @jonahgao on https://github.com/apache/datafusion/pull/13605/files#r1863695929
> Not related to the current PR, maybe we can move IdentNormalizer into IdentTaker to simplify take() and avoid creating normalizer every time.
1. Move IdentNormalizer into IdentTaker
Yes, by CI
No, these are all internal apis
=> Minor: Simplify `IdentTaker`

.github/workflows/rust.yml, Cargo.toml, datafusion-cli/Cargo.toml, datafusion-cli/Dockerfile, datafusion/core/Cargo.toml, datafusion/ffi/Cargo.toml, datafusion/proto-common/Cargo.toml, datafusion/proto-common/gen/Cargo.toml, datafusion/proto/Cargo.toml, datafusion/proto/gen/Cargo.toml, datafusion/substrait/Cargo.toml
Current goal is to support four last stable versions or versions for 4 months whichever is lower.  Given 1.80.0 was released on: 25 July, 2024 it's over 4 months old and 1.79 does not need to be supported.
=> Increase minimum supported Rust version (MSRV) to 1.80

datafusion/core/tests/fuzz_cases/aggregation_fuzzer/data_generator.rs, datafusion/physical-plan/src/aggregates/group_values/mod.rs, datafusion/physical-plan/src/aggregates/group_values/multi_group_by/mod.rs, datafusion/physical-plan/src/aggregates/group_values/multi_group_by/primitive.rs, datafusion/physical-plan/src/aggregates/group_values/single_group_by/primitive.rs, datafusion/sqllogictest/test_files/group_by.slt
Closes #13505.
Added group column for `Decimal128Array`
Yes, slt tests.
=> feat: Add GroupColumn `Decimal128Array`

datafusion/common/src/scalar/mod.rs, datafusion/common/src/utils/mod.rs, datafusion/functions-aggregate-common/src/aggregate/count_distinct/bytes.rs, datafusion/functions-aggregate-common/src/aggregate/count_distinct/native.rs, datafusion/functions-aggregate/src/array_agg.rs, datafusion/functions-aggregate/src/nth_value.rs, datafusion/functions-nested/src/make_array.rs, datafusion/functions-nested/src/utils.rs
- Follow on to  https://github.com/apache/datafusion/pull/13468
- Related to https://github.com/apache/datafusion/issues/13481
There are a bewildering number of small free functions for performing the same basic thing: converting an array into a single row list array / scalar
This has also lead to subtle bugs such as https://github.com/apache/datafusion/issues/13481
Let's encapsulate that operation into a well documented structure
1. Add `ArrayScalarBuilder`
2. Tests
3. Documentation
=> Create `ArrayScalarBuilder` for creating single element List arrays

.github/workflows/rust.yml, datafusion/substrait/Cargo.toml, datafusion/substrait/src/lib.rs, datafusion/substrait/tests/cases/mod.rs
Closes #13593 
- `physical` feature, which enables production and consumption of physical substrait plans.
Yes, running `cargo tree -p datafusion-substrait` with and without the `--no-default-features` shows that `parquet` and many other dependencies are not included.
No, the new feature is enabled by default. Users who might want to benefit from this change will have to use `default-features = false` when including the `datafusion-substrait` crate.
=> feat(substrait): remove dependency on datafusion default features

datafusion/sql/src/unparser/plan.rs, datafusion/sql/tests/cases/plan_to_sql.rs
Follow-up item for [Support unparsing plans after applying the `optimize_projections` rule PR](https://github.com/apache/datafusion/pull/13267), focusing on the unparsing enhancement to support the described scenario.
With the `optimize_projections` optimization, columns are pushed down to the `TableScan`, resulting in both `Projection` and `TableScan` nodes containing projection information. As a result, the generated SQL contains a duplicate subquery, e.g., `SELECT a, b FROM (SELECT a, b FROM my_table).`
PR updates `unparse_table_scan_pushdown` to prevent the creation of an additional projection if the unparser already includes a projection (`SELECT`) part.
Yes, TPC-H, TPC-DS benchmark tests, unit tests.
Improved Plan-to-SQL conversion when a TableScan with projection information is …
=> Improve unparsing after optimize_projections optimization

datafusion-cli/src/object_storage.rs
Unlike S3 or other object stores you have to explicitly give `http` or `https` as the protocol. It makes sense to me that if you're specifying `http` explicitly it's okay to make the insecure connection. This would be quite useful for local testing.
=> allow http in datafusion-cli http object store

datafusion/expr/src/type_coercion/functions.rs, datafusion/optimizer/src/analyzer/type_coercion.rs, datafusion/sqllogictest/test_files/aggregate.slt, datafusion/sqllogictest/test_files/errors.slt, datafusion/sqllogictest/test_files/expr.slt
This makes for a more actionable error message.
=> Report current operation when coercion fails

datafusion/physical-plan/src/aggregates/group_values/multi_group_by/mod.rs, datafusion/physical-plan/src/aggregates/group_values/row.rs, datafusion/physical-plan/src/aggregates/group_values/single_group_by/primitive.rs
For #13433, but only parts of it.
Prepare `hashbrown` 0.15 upgrade.
- `HashTableAllocExt`
- a few migrations
Existing tests pass.
No.
=> refactor: change some `hashbrown` `RawTable` uses to `HashTable` (round 2)

datafusion/common/src/types/builtin.rs, datafusion/expr/src/logical_plan/statement.rs
Part of https://github.com/apache/datafusion/issues/11687
Clear the TODOs after updating MSRV to 1.80.
`LazyLock` has been [stable](https://blog.rust-lang.org/2024/07/25/Rust-1.80.0.html#lazycell-and-lazylock) since Rust version 1.80.0, and it provides a simpler and more suitable way to define static variables.
No
=> refactor: replace `OnceLock` with `LazyLock`

datafusion/expr-common/src/columnar_value.rs, datafusion/functions-nested/src/array_has.rs, datafusion/functions/src/regex/regexpcount.rs, datafusion/functions/src/regex/regexplike.rs, datafusion/functions/src/regex/regexpmatch.rs, datafusion/functions/src/regex/regexpreplace.rs, datafusion/functions/src/utils.rs
`ColumnarValue::into_array` takes ownership of the columnar value and so requires copying data if the call site doesn't own the value.  This does not matter in many cases, since the `into_array` internally will copy data even more. It does matter however for the cases when to-array is called with desired array length of 1, which may happen when UDF implementation attempts to normalize arguments into arrays without expanding them. This pattern can be seen in regexp functions, but can be useful in downstream projects too.
=> Allow ColumnarValue to array conversion with less copying

datafusion/core/tests/user_defined/user_defined_scalar_functions.rs, datafusion/physical-expr/src/scalar_function.rs
This makes for a more actionable error message.
=> Report current function name when invoke result length wrong

datafusion/physical-plan/src/display.rs, datafusion/physical-plan/src/execution_plan.rs
Part of #7013 
While working on something internally, I found it would be quite helpful to have an examplefor `displayable`
`displayable` is mentioned on
https://docs.rs/datafusion/latest/datafusion/physical_plan/trait.ExecutionPlan.html
> ExecutionPlan can be displayed in a simplified form using the return value from displayable in addition to the (normally quite verbose) Debug output.
But there is no example
Add doc examples for this function
Yes, by CI
=> Minor: add examples for using `displayable` to show `ExecutionPlans`

datafusion/core/src/test_util/parquet.rs, datafusion/core/tests/parquet/filter_pushdown.rs, datafusion/core/tests/parquet/mod.rs
Closes #.
support run filter_pushdown on windows machine
1、avoid escape char (i.g. '\\') in path.
filter_pushdown
No
=> test: support run filter_pushdown on windows machine

.gitignore, datafusion/core/Cargo.toml, datafusion/core/benches/csv_load.rs, datafusion/core/src/test_util/csv.rs, datafusion/core/src/test_util/mod.rs, test-utils/src/data_gen.rs
Related to #12904
Requested in comments for `https://github.com/apache/datafusion/pull/13228`
A direct testing on loading csv files was identified as a gap in the benchmarking suite.
Basic benchmarks related to loading csv files.
Tested via `./bench.sh run csv`
Logged output:
```
Running csv load benchmarks.
Generated test dataset with 10240283 rows
Executing 'CSV Load Speed Test.'
Iteration 0 finished in 7.079167 ms.
Iteration 1 finished in 3.3643750000000003 ms.
Iteration 2 finished in 3.2645 ms.
Iteration 3 finished in 3.311208 ms.
Iteration 4 finished in 3.319 ms.
Done
```
results file:
[csv.json](https://github.com/user-attachments/files/17891638/csv.json)
Curious result is the first iteration is consistently 6-7 ms vs ~3ms on future iterations.  Is a new `SessionContext` not …
=> Add csv loading benchmarks.

datafusion/substrait/Cargo.toml
Closes #13653.
substrait@0.49.5 uses a higher MSRV 1.80.1.
[Changelog
](https://github.com/substrait-io/substrait-rs/blob/main/CHANGELOG.md)
> 0.49.5 (2024-12-04)
replace once_cell with std::sync::LazyLock, bumping msrv to 1.80.1
This PR restricts substrait‘s version to 0.49.4 to ensure compatibility with the current DataFusion MSRV.
Yes. By CI.
No
=> fix: cargo msrv check failed

datafusion-cli/Cargo.lock, datafusion/core/src/bin/print_functions_docs.rs, datafusion/doc/src/lib.rs, datafusion/functions-aggregate/Cargo.toml, datafusion/functions-aggregate/src/approx_distinct.rs, datafusion/functions-aggregate/src/approx_median.rs, datafusion/functions-aggregate/src/approx_percentile_cont.rs, datafusion/functions-aggregate/src/approx_percentile_cont_with_weight.rs, datafusion/functions-aggregate/src/array_agg.rs, datafusion/functions-aggregate/src/average.rs, datafusion/functions-aggregate/src/bool_and_or.rs, datafusion/functions-aggregate/src/correlation.rs, datafusion/functions-aggregate/src/count.rs, datafusion/functions-aggregate/src/covariance.rs, datafusion/functions-aggregate/src/first_last.rs, datafusion/functions-aggregate/src/grouping.rs, datafusion/functions-aggregate/src/median.rs, datafusion/functions-aggregate/src/min_max.rs, datafusion/functions-aggregate/src/nth_value.rs, datafusion/functions-aggregate/src/stddev.rs, datafusion/functions-aggregate/src/string_agg.rs, datafusion/functions-aggregate/src/sum.rs, datafusion/functions-aggregate/src/variance.rs, datafusion/functions/src/datetime/to_date.rs, datafusion/functions/src/math/abs.rs, datafusion/functions/src/string/ltrim.rs, datafusion/macros/src/lib.rs, docs/source/user-guide/sql/aggregate_functions.md
Closes #.
-  Migrate aggregate functions doc to attribute based
- With migration some documentation bugs fixed
=> Doc gen: Migrate aggregate functions doc to attribute based.

datafusion/core/src/datasource/listing/url.rs, datafusion/core/src/physical_optimizer/enforce_distribution.rs, datafusion/core/src/physical_optimizer/replace_with_order_preserving_variants.rs, datafusion/core/src/physical_optimizer/sanity_checker.rs, datafusion/functions/src/string/common.rs, datafusion/functions/src/unicode/strpos.rs, datafusion/physical-expr/src/equivalence/class.rs, datafusion/physical-plan/src/common.rs
Minor code improvements. These gonna be suggested edits in future Rust version.
relates to https://github.com/apache/datafusion/issues/13631
=> chore: Minor code improvements suggested by newer clippy

.github/workflows/rust.yml, Cargo.toml, datafusion-cli/Cargo.toml, datafusion/core/Cargo.toml, datafusion/ffi/Cargo.toml, datafusion/proto-common/Cargo.toml, datafusion/proto-common/gen/Cargo.toml, datafusion/proto/Cargo.toml, datafusion/proto/gen/Cargo.toml, datafusion/substrait/Cargo.toml
We currently require 1.80, but we also say that
> If a hotfix is released for the minimum supported Rust version (MSRV),
> the MSRV will be the minor version with all hotfixes
therefore we should requite 1.80.1 and thus allow dependencies that
require 1.80.1 (such as substrait)
- require 1.80.1 msrv
existing tests
1.80.0 is no longer supported
relates to
- https://github.com/apache/datafusion/pull/13657
- https://github.com/apache/datafusion/pull/13654
- https://github.com/apache/datafusion/pull/13622
=> Increase minimum supported Rust version (MSRV) to 1.80.1 

benchmarks/src/bin/external_aggr.rs, datafusion-cli/src/main.rs, datafusion/core/src/datasource/physical_plan/parquet/access_plan.rs, datafusion/core/tests/expr_api/mod.rs, datafusion/core/tests/memory_limit/mod.rs, datafusion/expr/src/logical_plan/plan.rs, datafusion/expr/src/test/function_stub.rs, datafusion/functions-aggregate/src/macros.rs, datafusion/functions-nested/src/macros.rs, datafusion/functions-table/src/lib.rs, datafusion/functions-window/src/macros.rs, datafusion/functions/src/macros.rs, datafusion/functions/src/regex/regexpreplace.rs, datafusion/physical-expr-common/src/sort_expr.rs, datafusion/physical-expr/src/expressions/not.rs, datafusion/physical-expr/src/utils/guarantee.rs, datafusion/sqllogictest/src/engines/datafusion_engine/normalize.rs
Part of #11687
Replaced the remaining `OnceLock`s except for function [Documentation](https://github.com/apache/datafusion/blob/2464703c84c400a09cc59277018813f0e797bb4e/datafusion/functions/src/math/pi.rs#L89) instances.
LazyLock provides a simpler way to define static variables.
Yes
No
=> refactor: replace `OnceLock` with `LazyLock` (round 2)

datafusion/physical-plan/src/windows/bounded_window_agg_exec.rs
For #13433, but only parts of it.
Note this that PR is rather small because it's -- in contrast to the other outstanding migrations -- rather self-contained.
Prepare `hashbrown` 0.15 upgrade.
- a few migrations
Existing tests pass.
No.
=> refactor: change some `hashbrown` `RawTable` uses to `HashTable` (round 3)

README.md
Looks like the MSRV policy on hotfixes can be slightly reworded and improved
Closes #.
=> Minor: Rephrase MSRV policy to be more explanatory

datafusion/core/src/datasource/physical_plan/csv.rs, datafusion/core/src/datasource/physical_plan/json.rs, datafusion/core/src/datasource/physical_plan/mod.rs, datafusion/sqllogictest/test_files/csv_files.slt
Closes #12328.
At this moment DF is unable to properly identify ranges after file repartitioning for CSV files with custom line terminator (bound calculation function considers only `\n` as a line separating character).
Test failures are caused by `target_partitions = 4` (default for Datafusion sqllogictests engine/runner) and `set repartition_file_min_size = 1` in `csv_files.slt` executed before failing test -- these two settings trigger scan repartitioning, which is not supported. 
File scan repartitioning functions used for plain-text files (CSV and NDJson -- though json reader don't have line separator option in its API) now aware of line terminator character.
Sqllogictests for single-thread reading and repartitioned reading of CSV with custom line separator.
No.
=> fix: repartitioned reads of CSV with custom line terminator

datafusion-examples/examples/regexp.rs, datafusion/functions/src/regex/regexplike.rs, datafusion/sqllogictest/test_files/regexp.slt, datafusion/sqllogictest/test_files/string/string_view.slt
Close some tasks in #13301.
Simplify function signature.
Added more tests for implicit casting.
No
=> Refactor regexplike signature

datafusion/core/Cargo.toml
Temporary fix for #13686
Tests panicked in arrow's `pretty_format_batches_with_options`, caused by the new release of lexical-write-integer.
This PR pins the version of lexical-write-integer and makes cargo choose the common version among DataFusion and arrow-rs to v1.0.2.
No. Only modify dev-dependencies.
=> Temporary fix for CI

datafusion/core/Cargo.toml
Issue was patched as of lexical release 1.0.5.
Reverts #13689
Closes #13686
=> Unlock lexical-write-integer version.

datafusion/functions/src/unicode/substr.rs
Closes #13687 .
tested with: cargo bench --bench substr
the result shows that `substr_string` and `substr_large_string` are running much faster in all cases.
```rust
Compiling datafusion-functions v43.0.0 (/Volumes/Workspace/blaze-init/arrow-datafusion/datafusion/functions)
Finished `bench` profile [optimized] target(s) in 2m 15s
Running benches/substr.rs (target/release/deps/substr-a86cfe081ca878bf)
SHORTER THAN 12/substr_string_view [size=1024, strlen=12]
time:   [17.906 µs 18.033 µs 18.166 µs]
change: [-5.6189% -4.0418% -2.4317%] (p = 0.00 < 0.05)
SHORTER THAN 12/substr_string [size=1024, strlen=12]
time:   [16.450 µs 16.554 µs 16.670 µs]
change: [-71.933% -71.626% -71.291%] (p = 0.00 < 0.05) …
```
=> Improve substr() performance by avoiding using owned string

datafusion/physical-expr-common/src/physical_expr.rs
Related to https://github.com/apache/datafusion/issues/13702
The public function `down_cast_any_ref` was removed in https://github.com/apache/datafusion/pull/13005, causing compilation errors in downstream projects.
It would be better to deprecate this function and remove it in a future release to give downstream projects time to make changes.
Add the function back and mark it as deprecated.
=> chore: reinstate down_cast_any_ref

datafusion/functions/src/unicode/character_length.rs
Closes #.
Optimize performance of `character_length` function.
1. Using `PrimitiveBuilder` to build the `PrimitiveArray` instead of collecting via `iter().map(...).collect::<PrimitiveArray<T>>()`.
2. Pre-check one-time `is_array_ascii_only` instead of calling array.is_ascii() for every element while loop.
Yes, existing unit tests.
No.
*BENCHMARK RESULT
```rust
Compiling datafusion-functions v43.0.0 (/home/tailm/repos/github/datafusion/datafusion/functions)
Finished `bench` profile [optimized] target(s) in 1m 02s
Running benches/character_length.rs (target/release/deps/character_length-a803a7794d6fcb71)
character_length_StringArray_ascii_str_len_8
time:   [35.772 µs 35.949 µs 36.158 µs]
change: [-28.386% -28.101% -27.755%] (p = 0.00 < 0.05) …
```
=> Optimize performance of `character_length` function

datafusion/sqllogictest/bin/sqllogictests.rs
Closes #.
Found when was working on https://github.com/apache/datafusion/pull/13710
The test running time is different depending on OS so it would be useful to know the exact SLT execution time.
=> Minor: Output elapsed time for sql logic test

datafusion/catalog/src/table.rs
- Part of #7013 
- While working on https://github.com/apache/datafusion/pull/13722
- It took me a while to find the Catalog documentation, so let's make it easier to find
- Also the documentation for `TableProvider`, one of the key DataFusion traits, was quite sparse
Add docs and links to `TableProvider`
Docs only, no functional change
=> Improve documentation for TableProvider

datafusion/expr/src/expr_fn.rs
Debug trait is useful for understanding what something is and how it's configured, especially if the implementation is behind dyn trait.
=> Reveal implementing type and return type in simple UDF implementations

datafusion/physical-plan/src/stream.rs
Part of #7013 
While working on https://github.com/apache/datafusion/issues/13714 I got hung up (again) on creating a `SendableRecordBatchStream` from some batches (I forgot to `Box::pin` the `RecordBatchStreamAdapter`  a while)
Let's put this in a documentation example on `RecordBatchStreamAdapter`
1. Add a doc example of using `RecordBatchStreamAdapter`
Only docs, no functional changes
=> Minor: Add doc example to RecordBatchStreamAdapter

datafusion/functions-aggregate-common/src/aggregate/groups_accumulator/accumulate.rs, datafusion/functions-aggregate/src/correlation.rs
Closes https://github.com/apache/datafusion/issues/13549
Implement `GroupsAccumulator` for `corr` aggregation function, for better performance when group cardinality is high
I rerun the H2o benchmark:
`falsa groupby --path-prefix=/Users/yongting/data/ --size MEDIUM --data-format PARQUET`
https://github.com/mrpowers-io/falsa
```
CREATE EXTERNAL TABLE IF NOT EXISTS h2o_100m (
id1 VARCHAR NOT NULL,
id2 VARCHAR NOT NULL,
id3 VARCHAR NOT NULL,
id4 INTEGER NOT NULL,
id5 INTEGER NOT NULL,
id6 INTEGER NOT NULL,
v1 INTEGER NOT NULL,
v2 INTEGER NOT NULL,
v3 DOUBLE PRECISION NOT NULL
)
STORED AS parquet
LOCATION '/Users/yongting/data/G1_1e8_1e8_100_0.parquet';
select id2, id4, power(corr(v1, v2), 2) as r2 from h2o_100m group by id2, id4;
```
Main: 12s
This PR: 4s
(On my MacBook with m4 pro)
---- …
=> Implement GroupsAccumulator for corr(x,y) aggregate function

datafusion/proto/src/logical_plan/mod.rs, datafusion/proto/tests/cases/roundtrip_logical_plan.rs
Closes #.
Unions with multiple tables result in an optimised plan with an Aggregate Node on top, example:
```sql
SELECT a FROM t1 UNION (SELECT a from t1 UNION SELECT a from t2)
```
```
Aggregate: groupBy=[[t1.a]], aggr=[[]] [a:Int64;N]
Union [a:Int64;N]
TableScan: t1 projection=[a] [a:Int64;N]
TableScan: t1 projection=[a] [a:Int64;N]
TableScan: t2 projection=[a] [a:Int64;N]
```
This Aggregate node uses the first tables name as references in its `groupBy`. Currently on `main` deserialisation from proto gets the last child of the Union node.
I added a test in this PR that previously failed to deserialise the optimised plan above with:
```
SchemaError(FieldNotFound { field: Column { relation: Some(Bare { table: "t1" }), name: "a" }, valid_fields: [Column { relation: Some(Bare { table: "t2" …
```
=> fix union serialisation order in proto

datafusion/functions/Cargo.toml, datafusion/functions/benches/initcap.rs, datafusion/functions/src/string/initcap.rs
Closes #.
Eliminate the intermediate `Vec<char>` and directly push into a `String`.
Update the `initcap` function, benchmark included.
Yes, existing unit tests.
No.
*BENCHMARK RESULT
```rust
Compiling datafusion-functions v43.0.0 (/home/tailm/repos/github/datafusion/datafusion/functions)
Finished `bench` profile [optimized] target(s) in 1m 02s
Running benches/initcap.rs (target/release/deps/initcap-408d405a24fbbea1)
initcap string view shorter than 12 [size=1024]
time:   [34.326 µs 34.353 µs 34.383 µs]
change: [-48.954% -48.796% -48.631%] (p = 0.00 < 0.05)
Found 26 outliers among 100 measurements (26.00%)
4 (4.00%) low severe
9 (9.00%) low mild
5 (5.00%) high mild
8 (8.00%) high severe
initcap string view longer than 12 …
```
=> Optimize performance of `initcap` function (~2x faster)

datafusion/functions/src/string/initcap.rs, docs/source/user-guide/sql/scalar_functions.md
- Related to https://github.com/apache/datafusion/pull/13691
- Related to https://github.com/apache/datafusion/issues/13711
@tlm365  says: https://github.com/apache/datafusion/pull/13691#discussion_r1877208207
> @Dandandan you're right. I tested it with some unit tests for special characters (unicode), this PR's implementation doesn't work and the old implementation doesn't work either. But I think it makes sense at the moment since the initcap function is in datafusion::function::string not datafusion::function::unicode.
> 
> Perhaps, it would be better if we update the documentation that initcap is not supported for unicode characters yet and try to handle it if necessary in another PR.
Update docs to reflect the caveat that init cap only works on ASCII strings
by CI
Just docs, no …
=> Minor: Add documentation explaining that initcap oly works for ASCII

datafusion/sqllogictest/bin/sqllogictests.rs
Before the change, the request to use PostgreSQL was simply ignored when `--complete` flag was present.
- Extracted from https://github.com/apache/datafusion/pull/13743
=> Support sqllogictest --complete with postgres

datafusion/physical-plan/src/joins/hash_join.rs
Closes #.
memory reservation is not used outside of `collect_left_input`, I don't think there is any good reason to add it in JoinLeftData. Remove this so we don't need to create dummy value for reservation when we create JoinLeftData
Also, Debug and Clone for `HashJoinStreamState`
=> Minor: Remove memory reservation in `JoinLeftData` used in HashJoin

Cargo.toml, datafusion/sqllogictest/src/engines/conversion.rs, datafusion/sqllogictest/src/engines/datafusion_engine/normalize.rs
Utilize new `to_plain_string` function (added in https://github.com/akubera/bigdecimal-rs/issues/135)
- Extracted from https://github.com/apache/datafusion/pull/13743
=> Update to bigdecimal 0.4.7

.github/actions/setup-rust-runtime/action.yaml, datafusion-cli/Cargo.lock, datafusion/common/Cargo.toml, datafusion/core/Cargo.toml, datafusion/execution/Cargo.toml, datafusion/expr-common/Cargo.toml, datafusion/expr/Cargo.toml, datafusion/ffi/Cargo.toml, datafusion/functions-aggregate-common/Cargo.toml, datafusion/functions-nested/Cargo.toml, datafusion/functions-table/Cargo.toml, datafusion/macros/Cargo.toml, datafusion/optimizer/Cargo.toml, datafusion/physical-plan/Cargo.toml, datafusion/proto-common/Cargo.toml, datafusion/sqllogictest/Cargo.toml, datafusion/wasmtest/Cargo.toml, test-utils/Cargo.toml
Related to https://github.com/apache/datafusion/issues/13726
Closes #.
Clean up dependencies
Going forward Im planning to add crate level hint `#![warn(unused_extern_crates)]` to specific crates, cannot do that globally as we got a lot of false positives on crates having test/bench sub crates.
=> chore: clean up dependencies

datafusion/substrait/src/logical_plan/producer.rs
Closes #13645 
Should match the Substrait spec - None isn't valid for this protobuf
-->
Using the existing Substrait Tests; though I do note that some aren't passing any way
=> fix: specify roottype in substrait fieldreference

README.md, docs/source/library-user-guide/api-health.md
Follow on to https://github.com/apache/datafusion/pull/13701
I missed one of @findepi 's suggestions on https://github.com/apache/datafusion/pull/13701#discussion_r1877921868, so let's fix that here. 
Also there was another good idea:
- https://github.com/apache/datafusion/pull/13701#discussion_r1884581982
Improve the guidelines to be clearer and more concise
CI
=> Improve Deprecation Guidelines more

datafusion/functions/src/strings.rs
Add a safety check to ensure that the null buffer and offsets buffers are the same length. This introduces a panic if they are not aligned through a
runtime assertion.
~I couldn't find an issue for this, it was raised internally for InfluxData's use of `datafusion`. I can create one if necessary :smile:~
Fixes https://github.com/apache/datafusion/issues/13759
See description.
I believe the existing test suite should cover this, although I'm happy to add a forced `#[should_panic]`, I'm not quite sure how much value this provides though.
Users of the `LargeStringArrayBuilder` must be aware that method can now panic when the invariants are not upheld.
=> fix: add `null_buffer` length check to `StringArrayBuilder`/`LargeStringArrayBuilder`

datafusion/sqllogictest/test_files/aggregate.slt
-
I saw TODO's in the codebase that these did not have any slt tests
Several slt test cases for count(partitioned,aggregated, aggregated cube)
They are only slt tests
No
=> [minor] add missing slt tests for count(partitioned,aggregated, aggregated cube)

docs/source/contributor-guide/index.md
- Closes https://github.com/apache/datafusion/issues/12357
- related to https://github.com/apache/datafusion/issues/13648
Given recent discussions on improving DataFusion stability (see https://github.com/apache/datafusion/issues/13648) I think it is time to document the criteria to add new features to DataFusion to help ensure everyone's expectations are aligned
1. Add summary of conclusion of https://github.com/apache/datafusion/issues/12357 to the docs
CI
=> Update documentation guidelines for contribution content

datafusion/common/src/scalar/mod.rs
- Part of https://github.com/apache/datafusion/issues/13762
When trying to write a unit test for https://github.com/apache/datafusion/issues/13762 I found there was no good place to test the round tripping of Array --> ScalarValue --> Array (which is what is done for constant values)
So I wrote some
Add tests for this path, with ones that fail due to bugs commented out
Yes, by CI
No - this are just tests
=> Add Round trip tests for Array <--> ScalarValue

datafusion/optimizer/src/analyzer/mod.rs
- I was looking at the `Analyzer` documentation as part of reviewing https://github.com/apache/datafusion/pull/13651 with @wiedld  and noticed some things that could be better
Improve the documentation for the Analyzer
Yes, by CI
Docs only, no functional changes
=> Minor: improve `Analyzer` docs

datafusion-cli/Cargo.lock, datafusion-cli/Cargo.toml
Part of 
- https://github.com/apache/datafusion/pull/13663
I needed to update Cargo.lock in `datafusion-cli` as part of https://github.com/apache/datafusion/pull/13663 and I hit some MSRV problem related to home
I wanted to fix it in a separate PR rather than try and include it as part of the arrow upgrade.
When I did `cargo update` in the datafusion-cli directory, the MSRV check fails:
Specifically, home 0.5.11 has a MSRV of `1.81` which is too new to pass our CI check
--     Updating home v0.5.9 -> v0.5.11
```
andrewlamb@Andrews-MacBook-Pro-2:~/Software/datafusion2/datafusion-cli$ cargo msrv verify
[Meta]   cargo-msrv 0.17.1
Compatibility Check #1: Rust 1.80.1
[FAIL]   Is incompatible
╭────────────────────────────────────────────────────────────────────────╮
│ error: rustc 1.80.1 is not …
```
=> Minor: cargo update in datafusion-cli

datafusion/common/src/scalar/mod.rs
Closes https://github.com/apache/datafusion/issues/13762
Fix support for dense union.
Fix `ScalarValue::to_array_of_size` for DenseUnion
Yes. The test from https://github.com/apache/datafusion/pull/13777 is uncommented.
=> Fix `ScalarValue::to_array_of_size` for DenseUnion

datafusion/core/src/datasource/physical_plan/parquet/row_group_filter.rs, datafusion/core/tests/parquet/mod.rs, datafusion/core/tests/parquet/row_group_pruning.rs
Closes #13574 .
Currently row group pruning by Bloom filters is unaware of Dictionary typed scalar values (the literal part of predicate) while checking for values being contained in filter. This PR adds limited support for them  -- now Bloom filter pruning is able to handle majority of Dictionary scalars (with the exception of Decimal type).
Part of `BloomFilterStatistics` responsible for checking scalar value against Sbbf is moved into helper function with additional support of Dictionary() and LargeUtf8/LargeBinary type.
There are tests for supported datatypes checking pruning and matching (to ensure that there won't be any excessive pruning) cases.
No
=> fix: pruning by bloom filters for dictionary columns

datafusion/functions-nested/src/set_ops.rs, datafusion/sqllogictest/test_files/array.slt
=> Handle empty rows for `array_distinct`

datafusion/expr-common/src/signature.rs, datafusion/expr/src/type_coercion/functions.rs, datafusion/functions-nested/src/extract.rs, datafusion/functions-nested/src/flatten.rs
Fixes https://github.com/apache/datafusion/issues/13755
Fix a bug, see issue https://github.com/apache/datafusion/issues/13755
TL;DR: fix incorrect result of `ExprSchemable::get_type` for an array function invoked on array of list
Just the fix
unit test
yes
=> Fix get_type for higher-order array functions

datafusion/functions/src/strings.rs
Closes https://github.com/apache/datafusion/issues/13796
We identified a potential code vulnerability during a security audit at InfluxData.
Make overflow a panic.
yes
no
=> Handle possible overflows in StringArrayBuilder / LargeStringArrayBuilder

datafusion/core/src/datasource/file_format/csv.rs, datafusion/core/src/datasource/file_format/json.rs, datafusion/core/src/datasource/file_format/parquet.rs, datafusion/core/src/datasource/listing/helpers.rs, datafusion/core/src/datasource/listing/table.rs
Ignore empty files in ListingTable. Sometimes input datasets can contain empty files (as in 0 bytes), and trying to treat them like normal files fails when e.g. reading parquet metadata. 
Closes https://github.com/apache/datafusion/issues/13737.
Empty files cannot contribute anything to the table, other than to break things, so ignoring them is pretty much strictly better. Also aligns with e.g. [Spark](https://github.com/apache/spark/blob/b2c8b3069ef4f5288a5964af0da6f6b23a769e6b/sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/PartitioningAwareFileIndex.scala#L82C9-L82C23).
Ignore empty files in ListingTable when listing files with or without partition filters, as well as when inferring schema
One thing I'm not sure about is that it seems `pruned_partition_list` is also …
=> fix: Ignore empty files in ListingTable when listing files with or without partition filters, as well as when inferring schema

datafusion/common/src/scalar/mod.rs
Closes #.
Just a minor change. Decimal, Time and Date datatypes can be created just like other numeric and temporal types with 0.
ScalarValue::new_zero() includes Decimal128, Decimal256, Time32(Second/Millisecond), Time64(Microsecond, Nanosecond), Date32, Date64.
=> Minor: Extend ScalarValue::new_zero()

.github/workflows/rust.yml
Related to #13726 .
Presumably there is an issue in Github runners starting from last year and causing the Window Rust flow to run for 1.5h without any particular reason. Commenting out the flow for now and waiting for a new GH Windows runner
=> chore: temporarily disable Windows Rust flow

datafusion/physical-plan/src/joins/sort_merge_join.rs
Closes https://github.com/apache/datafusion/issues/13144.
More concise and potentially more performant API
=> Minor: Replace `BooleanArray::extend` with `append_n`

datafusion/execution/src/runtime_env.rs
N/A
Improve documentation.
typo: remove extraneous "`" in doc comment
N/A
No
=> typo: remove extraneous "`" in doc comment, fix header

datafusion/physical-expr/src/equivalence/properties.rs
N/A
Minor fix: typo -- remove extra "`" interfering with doc formatting.
N/A
No
=> MINOR: typo -- remove extra "`" interfering with doc formatting

datafusion-cli/Cargo.lock, datafusion/expr-common/src/sort_properties.rs, datafusion/expr/src/udf.rs, datafusion/functions/src/string/concat.rs, datafusion/physical-expr/Cargo.toml, datafusion/physical-expr/src/equivalence/properties.rs, datafusion/physical-expr/src/expressions/binary.rs, datafusion/physical-expr/src/expressions/literal.rs, datafusion/physical-expr/src/expressions/negative.rs, datafusion/physical-expr/src/scalar_function.rs
Closes #13839.
DataFusion's ordering equivalence system currently only handles single-parameter monotonic functions. This PR extends support to N-ary functions that preserve lexicographical ordering, like concat(). This enables more optimization opportunities when working with ordered data.
- Added `preserves_lex_ordering` field to `ExprProperties`
- Implemented `output_preserves_lex_ordering` for concat function
- Updated `discover_new_orderings()` to handle multiple parameters
- Added tests for concat and non-monotonic multiply cases
Yes, added three new test cases:
- test_ordering_equivalence_with_monotonic_concat
- test_ordering_equivalence_with_non_monotonic_multiply
- test_ordering_equivalence_with_concat_equality
No user-facing changes. This is an internal optimization improvement.
=> Support n-ary monotonic functions in ordering equivalence

datafusion/substrait/Cargo.toml
Closes #13854
https://github.com/apache/datafusion/pull/13594/files#diff-d195b6dfaaed44b9828e145dc50c075c77b7faf8f44783ca5e6eda2c617af928L39 removed DF default features from the substrait crate. That broke some tests that depended on stuff coming from nested_expressions feature. 
Interestingly, the tests still passed in CI but failed when run locally - maybe due to CI running a whole bunch of tests at once and thus compiling DF with different set of features, or something?
No - but in the original PR that caused the issue, that _might_ be a breaking change to some consumer if someone has disabled default_features for DF but things have been working still because datafusion-substrait has been pulling those features in anyways. Not sure if that can happen - I checked our internal stuff and …
=> fix: enable DF's nested_expressions feature by in datafusion-substrait tests to make them pass

datafusion/expr-common/src/signature.rs, datafusion/expr-common/src/type_coercion/binary.rs
- Follow on to https://github.com/apache/datafusion/pull/13817
While improving the docs in https://github.com/apache/datafusion/pull/13817, @findepi  identified additional areas that were not super clear
Try to improve the documentation about coercion more. 
By doc CI tests
Better docs, no functional change
=> Improve`Signature` and `comparison_coercion` documentation

Cargo.toml, datafusion-cli/Cargo.lock, datafusion/common/src/utils/mod.rs, datafusion/core/tests/user_defined/user_defined_scalar_functions.rs, datafusion/expr/src/expr.rs, datafusion/expr/src/expr_fn.rs, datafusion/optimizer/src/analyzer/inline_table_scan.rs, datafusion/proto/src/logical_plan/from_proto.rs, datafusion/proto/tests/cases/roundtrip_logical_plan.rs, datafusion/sql/src/expr/function.rs, datafusion/sql/src/expr/mod.rs, datafusion/sql/src/parser.rs, datafusion/sql/src/planner.rs, datafusion/sql/src/select.rs, datafusion/sql/src/statement.rs, datafusion/sql/src/unparser/ast.rs, datafusion/sql/src/unparser/dialect.rs, datafusion/sql/src/unparser/expr.rs, datafusion/sql/src/unparser/plan.rs, datafusion/sql/src/unparser/utils.rs, datafusion/sqllogictest/test_files/information_schema.slt
- Closes https://github.com/apache/datafusion/pull/13546
Keep up with dependencies (in this case get access to source spans)
1. Upgrade to sqlparser 0.53.0
2. Update APIs
=> Upgrade to sqlparser `0.53.0`

datafusion/physical-plan/src/joins/sort_merge_join.rs
Minor improvement when dealing with internal arrays for SMJ potentially removing extra allocation for filtered SortMergeJoin
Closes #.
=> Minor: Use `resize` instead of `extend` for static values in SMJ logic

datafusion/core/src/catalog_common/information_schema.rs, datafusion/sql/src/statement.rs, datafusion/sqllogictest/test_files/information_schema.slt
Closes #12144.
This PR implements `SHOW FUNCTIONS` to list the available functions during runtime. Instead of listing the function name only ([like Apache Spark](https://spark.apache.org/docs/3.5.3/sql-ref-syntax-aux-show-functions.html)), I think it's better to provide more information like [what Snowflake did](https://docs.snowflake.com/en/sql-reference/sql/show-functions#output). 
To provide the required information, I also added some columns to `information_schema.routines` and `information_schema.parameters`.
```
SHOW FUNCTIONS [ LIKE <pattern> ];
```
```
> show functions like '%datetrunc';
+---------------+-------------------------------------+-------------------------+-------------------------------------------------+---------------+-------------------------------------------------- …
```
=> Implement `SHOW FUNCTIONS`

datafusion/sql/src/statement.rs
Closes #.
Build on main is broken due to a logical conflict between
- https://github.com/apache/datafusion/pull/13799
- https://github.com/apache/datafusion/pull/13767
Example failure:
https://github.com/apache/datafusion/actions/runs/12441590178/job/34738687199
```
error[E0433]: failed to resolve: use of undeclared type `ShowStatementFilter`
--> datafusion/sql/src/statement.rs:2003:17
|
2003 |                 ShowStatementFilter::Like(like) => {
|                 ^^^^^^^^^^^^^^^^^^^ use of undeclared type `ShowStatementFilter`
|
help: a struct with a similar name exists
|
2003 |                 ShowStatementIn::Like(like) => {
|                 ~~~~~~~~~~~~~~~
help: consider importing one of these enums
|
18   + use crate::statement::ast::ShowStatementFilter;
|
18   + use …
```
=> Fix build `use of undeclared type ShowStatementFilter`

datafusion/substrait/src/logical_plan/producer.rs, datafusion/substrait/tests/cases/roundtrip_logical_plan.rs
Closes #13860
Explained in #13860 
Included a test that fails before this change
`to_substrait_plan` will include a `FetchRel` when serializing a `Sort` that contains a `fetch`.   It had previously missed this.
=> Minor: fix: Include FetchRel when producing LogicalPlan from Sort

datafusion/sql/src/expr/value.rs
- Part of https://github.com/apache/datafusion/issues/13854
There was a problem running substrait tests as they didn't activate the right features in DataFusion:
```
Error: Internal("Expected a simplified result, but none was found")
```
This error was confusing as it sounded like a bug and didn't hint at how to fix the problem
Improve the error message to be more specific about what is wrong and change from internal to not implemented
=> Minor: improve error message when ARRAY literals can not be planned

docs/source/user-guide/sql/information_schema.md
- part of https://github.com/apache/datafusion/issues/12144
- Follow on to https://github.com/apache/datafusion/pull/13799
We should document features  so users can more easily find them
Also, @comphead  says https://github.com/apache/datafusion/pull/13799#issuecomment-2555969968
> Thanks @goldmedal it would be really nice to update the user documentation
1. Add documentation (copy / paste from the description on https://github.com/apache/datafusion/pull/13799 from @goldmedal )
2. Add section headings for the `SHOW` / `information_schema` tables
Here is the new content rendered: 
CI
=> Add documentation for `SHOW FUNCTIONS`

datafusion/functions/Cargo.toml, datafusion/functions/benches/initcap.rs, datafusion/functions/src/string/mod.rs, datafusion/functions/src/unicode/initcap.rs, datafusion/functions/src/unicode/mod.rs, datafusion/sqllogictest/test_files/string/string_query.slt.part, docs/source/user-guide/sql/scalar_functions.md
Closes #13711.
- Support UTF-8 for `initcap` function.
- Moved `initcap` from `string` module to `unicode` module.
- Update docs.
Yes, unit tests are included.
Yes. `api change`.
=> Support unicode character for `initcap` function

datafusion-cli/Cargo.lock, datafusion/core/Cargo.toml
N/A
async-compression provides two [IO implementations](https://docs.rs/async-compression/0.4.18/async_compression/#io-implementation): `tokio` and `futures-io`. We are only using `tokio` and not using `futures-io`. Remove it to avoid compiling code related to `futures-io` in `async-compression`.
No
=> Minor: remove unused async-compression `futures-io` feature

datafusion/doc/src/lib.rs, datafusion/sql/src/statement.rs
- Closes https://github.com/apache/datafusion/issues/13764
I would like to help people upgrade DataFusion versions with as much help as possible. This means following the [deprecation guidelines](https://github.com/apache/datafusion/blob/main/README.md) 
Changes to `DocBuilder` introduced a breaking API change that could be confusing to some during upgrade
- https://github.com/apache/datafusion/pull/13575
1. Restore `DocumentationBuilder::new`, and mark it  `#[deprecated]``, following the [deprecation guidelines](https://github.com/apache/datafusion/blob/main/README.md) 
2. Make `DocumentationBuilder::new_with_defaults`  new to help users find the new API
3. Add `Default` for `DocSection` to make it easier for users to bash out their own docs
4. Improve some other docs
=> Restore `DocBuilder::new()` to avoid breaking API change

datafusion/functions-table/src/generate_series.rs, datafusion/sqllogictest/test_files/table_functions.slt
Closes #13615.
+ Added some args validation to `GenerateSeriesTable`
+ Added `step` field to `GenerateSeriesState`, and added support for generating series with custom step
sqllogictests for generate_series() UDTF
No
=> Support 1 or 3 arg in generate_series() UDTF

datafusion/physical-plan/src/joins/sort_merge_join.rs
Closes #.
Since SortMergeJoin appears only when the inputs are sorted, marking its emission type as incremental would reflect its behavior better.
=> Minor: change the sort merge join emission as incremental

datafusion/core/src/physical_optimizer/join_selection.rs
Closes #.
These functions can be used in other modules across the crate, so I'm relaxing their accessibility.
=> Minor: change visibility of hash join utils

README.md, datafusion-cli/Cargo.lock, datafusion-cli/Cargo.toml, datafusion/common/Cargo.toml, datafusion/common/src/tree_node.rs, datafusion/core/Cargo.toml, datafusion/expr/Cargo.toml, datafusion/expr/src/expr_schema.rs, datafusion/expr/src/logical_plan/tree_node.rs, datafusion/optimizer/Cargo.toml, datafusion/optimizer/src/analyzer/subquery.rs, datafusion/optimizer/src/common_subexpr_eliminate.rs, datafusion/optimizer/src/eliminate_cross_join.rs, datafusion/optimizer/src/optimize_projections/mod.rs, datafusion/physical-optimizer/Cargo.toml, datafusion/physical-optimizer/src/aggregate_statistics.rs, datafusion/sql/Cargo.toml, datafusion/sql/src/expr/mod.rs, datafusion/sql/src/lib.rs, datafusion/sql/src/query.rs, datafusion/sql/src/set_expr.rs, datafusion/sql/src/stack.rs
- Closes https://github.com/apache/datafusion/issues/13766
The recursive-protect flag was added in https://github.com/apache/datafusion/pull/13778, but when @andygrove  tried to disable it in comet, recursive was still enabled. 
I am not an expert in the crate feature mechanism, but the feature appears to get activated if a downstream crate like comet uses a crate like `datafusion` (the core crate) that passes the feature through
1. Change feature flag to enable recursive protection at the main crate level
2. rename `recursive-protection` to `recursive_protection` to be consistent with other flags
1. Make feature not enabled by default in sub crates
3. Add feature to the datafusion core crate
4. move another stack protection mechanism into a guarded section
Here is an example showing how …
=> Fix `recursive-protection` feature flag

datafusion/core/src/physical_optimizer/join_selection.rs
- Closes https://github.com/apache/datafusion/issues/13898
- Fix a regression in visibility introduced in https://github.com/apache/datafusion/pull/13893
`swap_hash_join` used to be pub and now it is pub(crate) which means other downstream crates can't use it
Restore `swap_hash_join` to be `pub`
=> Fix visibility of `swap_hash_join` to be `pub` 

datafusion/physical-plan/src/sorts/partial_sort.rs
Closes #.
PartialSort could still generate empty batches after the exhaustion of its input. That is avoided, and debug_assert!() is moved to the actual return point.
=> Minor: Avoid emitting empty batches in partial sort

datafusion/physical-expr/src/expressions/case.rs, datafusion/sqllogictest/test_files/case.slt
=> fix case_column_or_null with nullable when conditions

benchmarks/bench.sh
The URL to the external website was returning a 404. Presuming recent changes in the external website's structure, the required data has been moved to a different URL. The commit ensures the new URL is used.
Closes #13896 
The bug was occuring due to referencing a file hosted on an external website whose URL had been changed. The PR updates the code to point at the correct URL.
The [bench.sh#463](https://github.com/apache/datafusion/blob/7b4e5598a5d3e95a6c0dfcb9375f50778a2b2f64/benchmarks/bench.sh#L463) has been changed to use the correct URL for the file.
Yes. After the change, the expected command worked correctly, initiating a download as intended:
No.
=> Changed the url for downloading IMDB dataset from benchmark - Fixed Issue #13896

datafusion/sqllogictest/Cargo.toml, datafusion/sqllogictest/bin/sqllogictests.rs
Closes #https://github.com/apache/datafusion/pull/13884
Resolve the breaking change ("The Validator type used in various function in Runner implementation has a new required field Normalizer that is used to normalize result values.")
=> chore(deps): update sqllogictest requirement from 0.23.0 to 0.24.0

datafusion/physical-plan/src/topk/mod.rs
Part of #13430.
In Top K, the RecordBatch size is overestimated. Fix it by using `get_record_batch_memory_size`.
Unit tested for a narrow range.
No
=> fix : use `get_record_batch_memory_size` for calculating RecordBatch memory size in topK

datafusion/functions/src/unicode/initcap.rs, datafusion/functions/src/utils.rs
Closes #13907
Described in the issue, when the input type is utf8view for initcap, so should the return type. The actual return type *is* utf8view, so we just need to set it in the `return_type` function to match.
One change to return_type function
Tested in datafusion-python unit tests. I also updated the unit test macro to validate that data types returned from scalar functions matches those that are expected, which is why this problem was not identified previously.
None
=> Correct return type for initcap scalar function with utf8view

datafusion/common/src/join_type.rs, datafusion/core/src/physical_optimizer/join_selection.rs, datafusion/physical-plan/src/joins/cross_join.rs, datafusion/physical-plan/src/joins/hash_join.rs, datafusion/physical-plan/src/joins/join_filter.rs, datafusion/physical-plan/src/joins/mod.rs, datafusion/physical-plan/src/joins/nested_loop_join.rs, datafusion/physical-plan/src/joins/utils.rs
Closes #.
I want to make it as easy as possible for people to implement (join order) optimizers on top of DataFusion (for example, https://github.com/cmu-db/optd, though I fully admit I have failed so far to get them to engage with us)
However, some of the key building blocks of such optimizations like swapping join inputs, are crate internal APIs of the very basic join ordering optimizer included with DataFusion. Thus it will be hard for others to find and use this cdoe
Some additional evidence there is demand for these functions is 
- this PR (that makes them more visible for use in forks) https://github.com/apache/datafusion/pull/13893 from @berkaysynnada 
- `swap_hash_join` is used in comet: https://github.com/apache/datafusion/pull/13899
Making the functions public and on the `Exec`s …
=> Make it easier to make optimizers: Move join input swapping and related methods into PhysicalOperators

datafusion/functions/src/string/repeat.rs, datafusion/functions/src/string/replace.rs, datafusion/functions/src/string/split_part.rs, datafusion/functions/src/string/starts_with.rs, datafusion/functions/src/string/to_hex.rs, datafusion/functions/src/string/uuid.rs, datafusion/functions/src/unicode/find_in_set.rs, datafusion/functions/src/unicode/reverse.rs
Closes #13671 .
As discussed in #13671  , this PR will migrate the parts of builtin string functions documentation that currently support migration.
=> doc-gen: migrate scalar functions (string) documentation 3/4

datafusion/functions/src/unicode/initcap.rs, datafusion/functions/src/utils.rs
- Part of https://github.com/apache/datafusion/issues/13334
- Backport https://github.com/apache/datafusion/pull/13909 to `branch-44`
Note this targets https://github.com/apache/datafusion/tree/branch-44 (not main)
=> BACKPORT: Correct return type for initcap scalar function with utf8view (#13909)

datafusion/functions/src/crypto/digest.rs, datafusion/functions/src/crypto/md5.rs, datafusion/functions/src/crypto/sha224.rs, datafusion/functions/src/crypto/sha256.rs, datafusion/functions/src/crypto/sha384.rs, datafusion/functions/src/crypto/sha512.rs, docs/source/user-guide/sql/scalar_functions.md
part of #13671.
As discussed in #13671, this PR will migrate the builtin hashing functions documentation that currently support migration.
=> doc-gen: migrate scalar functions (crypto) documentation

datafusion/functions/src/datetime/current_date.rs, datafusion/functions/src/datetime/current_time.rs, datafusion/functions/src/datetime/date_bin.rs, datafusion/functions/src/datetime/date_part.rs, datafusion/functions/src/datetime/date_trunc.rs, datafusion/functions/src/datetime/from_unixtime.rs, docs/source/user-guide/sql/scalar_functions.md
Closes #13671 .
As discussed in #13671 , this PR will migrate the parts of builtin datetime functions documentation that currently support migration.
=> doc-gen: migrate scalar functions (datetime) documentation 1/2

datafusion/physical-plan/src/joins/hash_join.rs
Part of #13430
In Hash Join build side, the RecordBatch size is overestimated. 
I think that accurate memory accounting on the build side of hash join is important.
Fix it by using `get_record_batch_memory_size`.
Unit tested for a narrow range.
no
=> Minor : Improve hash join build side recordbatch size accuracy

datafusion/functions/src/math/cot.rs, datafusion/functions/src/math/factorial.rs, datafusion/functions/src/math/gcd.rs, datafusion/functions/src/math/iszero.rs, datafusion/functions/src/math/lcm.rs, datafusion/functions/src/math/log.rs, datafusion/functions/src/math/nans.rs
Closes #13671 .
As discussed in #13671  , this PR will migrate the parts of builtin math functions documentation that currently support migration.
=> doc-gen: migrate scalar functions (math) documentation 1/2

datafusion/functions/src/unicode/left.rs, datafusion/functions/src/unicode/lpad.rs, datafusion/functions/src/unicode/right.rs, datafusion/functions/src/unicode/rpad.rs, datafusion/functions/src/unicode/strpos.rs, datafusion/functions/src/unicode/substr.rs, datafusion/functions/src/unicode/substrindex.rs, datafusion/functions/src/unicode/translate.rs, docs/source/user-guide/sql/scalar_functions.md
As discussed in #13671  , this PR will migrate the parts of builtin string functions documentation that currently support migration.
=> doc-gen: migrate scalar functions (string) documentation 4/4

benchmarks/src/clickbench.rs
Closes [#13941 ](https://github.com/apache/datafusion/issues/13941)
Add the debug option for clickbench
yes:
```rust
cargo run --release --bin dfbench clickbench  --query 35 --debug
Compiling datafusion-benchmarks v44.0.0 (/Users/zhuqi/arrow-datafusion/benchmarks)
Building [=======================> ] 352/353: dfbench(bin)
Finished `release` profile [optimized] target(s) in 4m 51s
Running `target/release/dfbench clickbench --query 35 --debug`
Running benchmarks with the following options: RunOpt { query: Some(35), common: CommonOpt { iterations: 3, partitions: None, batch_size: 8192, debug: true }, path: "benchmarks/data/hits.parquet", queries_path: "benchmarks/queries/clickbench/queries.sql", output_path: None }
Q35: SELECT "ClientIP", "ClientIP" - 1, "ClientIP" - 2, "ClientIP" - 3, …
```
=> Support explain query when running dfbench with clickbench

datafusion/sqllogictest/Cargo.toml, datafusion/sqllogictest/test_files/group_by.slt
- Reverts https://github.com/apache/datafusion/pull/13917
- @Omega359 is adding the sqlite sqllogictests in https://github.com/apache/datafusion/pull/13936
- Those tests include labels in the sqlogictest files, but there is an issue with sqllogictest 0.25.0 https://github.com/risinglightdb/sqllogictest-rs/issues/242 that prevents them from working
pin to sqllogictest `0.24.0` and add a note about why
By CI
No this is development tooling
=>  Revert "Update sqllogictest requirement from 0.24.0 to 0.25.0 (#13917)"

datafusion/functions/src/string/ascii.rs, datafusion/functions/src/string/bit_length.rs, datafusion/functions/src/string/chr.rs, datafusion/functions/src/string/contains.rs, datafusion/functions/src/string/octet_length.rs, datafusion/functions/src/string/rtrim.rs, datafusion/functions/src/unicode/character_length.rs
As discussed in #13671  , this PR will migrate the parts of builtin string functions documentation that currently support migration.
=> doc-gen: migrate scalar functions (string) documentation 1/4

datafusion/functions/src/string/btrim.rs, datafusion/macros/src/user_doc.rs
Closes #13944
As explained in #13944, the `user_doc` macro doesn't support multiple alternative syntaxes which has prevented `trim` from using it. 
Build a list of alternative syntax examples in the macro
Use `user_doc` for `trim`
I have run `./dev/update_function_docs.sh` and there are no changes
No
=> Support multiple alternative syntaxes in the `user_doc` macro, port `trim` to use new macro

.devcontainer/Dockerfile, .devcontainer/devcontainer.json
None
Easier contribution
Added devcontainer file
yes
No
=> chore: Create devcontainer.json

datafusion/core/src/physical_optimizer/join_selection.rs, datafusion/physical-plan/src/joins/sort_merge_join.rs
None.
The function `swap_inputs` was missing for the SMJ operator. This is a continuation of #13910 that fills this gap.
This PR implements the `swap_inputs` method for the SMJ operator, which basically is the same with its sisters for other operators (e.g. Hash Join). It also makes the `swap_join_according_to_unboundedness` utility function in `join_selection.rs` crate public to enable implementation of (and experimentation with) custom join rules by downstream projects.
There are no explicit unit tests, but the sisters methods don't have such tests either. These methods are tested indirectly via optimization rules. We can consider whether to add such tests for all such methods in a future PR.
None.
=> Add swap_inputs to SMJ

datafusion/functions-nested/src/set_ops.rs, datafusion/sqllogictest/test_files/array.slt
Closes #13961
Just add the last offset in case of null, and migrated the input list nulls to the output
Yes, and of course created a failing test first, fixed and made sure the test now pass
not requiring any docs update
=> fix(datafusion-functions-nested): `arrow-distinct` now work with null rows

datafusion/sqllogictest/Cargo.toml, datafusion/sqllogictest/bin/postgres_container.rs, datafusion/sqllogictest/bin/sqllogictests.rs, datafusion/sqllogictest/src/engines/datafusion_engine/normalize.rs, datafusion/sqllogictest/src/engines/postgres_engine/mod.rs
Closes #13948 
Code cleanup.
Code.
Yes.
No.
=> Extract postgres container from sqllogictest, update datafusion-testing pin

.github/workflows/hash_collisions.yml, .github/workflows/rust.yml
part of #13845 
The hash collisions job is expensive (just as expensive as the cargo docs tests which are being worked on elsewhere) and rarely fail. It would be better to just run the hash collision job on merge to main instead of on every PR checkin.
github actions updates.
Well, kinda. I don't have a merge to main to actually test that portion however from reading the github documentation it should work.
No.
=> Move hash collision test to run only when merging to main

datafusion/functions/src/string/concat.rs, datafusion/functions/src/string/concat_ws.rs, datafusion/functions/src/string/ends_with.rs, datafusion/functions/src/string/levenshtein.rs, datafusion/functions/src/string/lower.rs, datafusion/functions/src/string/overlay.rs, datafusion/functions/src/string/upper.rs, datafusion/functions/src/unicode/initcap.rs, docs/source/user-guide/sql/scalar_functions.md
As discussed in #13671  , this PR will migrate the parts of builtin string functions documentation that currently support migration.
=> doc-gen: migrate scalar functions (string) documentation 2/4

dev/release/README.md
- related to #13334 
It turns out we no longer need to run `--no-verify` to publish `datafusion-cli` which I discovered while releasing DataFusion 44
https://github.com/apache/datafusion/issues/13334#issuecomment-2567705051
Update release instructions
=> Update release README for datafusion-cli publishing

datafusion/functions-aggregate/src/first_last.rs, datafusion/sqllogictest/test_files/aggregate.slt
Closes #.
We also check `requirement_satisfied` for `update_batch`, add it for `merge_batch`.
=> Minor: sort requirement check for `Last` function's `merge_batch`

datafusion-examples/README.md, datafusion-examples/examples/deserialize_to_struct.rs
- Related to https://github.com/apache/datafusion/issues/11172
While trying to find more examples to consolidate, I ran into this example which wasn't well documented and its description was mislableed
1. Fix description
2. Update comments to explain what it was doing
By CI
=> Improve deserialize_to_struct example

datafusion/physical-expr/src/expressions/case.rs, datafusion/sqllogictest/test_files/case.slt
Closes #11638.
The objective of this PR is to optimize the `case_when: expr or expr` benchmark. I measured a small but consistent improvement of around 10% on this benchmark.
I implemented an additional evaluation method to improve `CASE WHEN condition THEN expr ELSE expr` performance.
The implementation is supposed to be very close to the existing implementation of more general cases.
I added a basic test case for the new evaluation method.
No, the changes should not affect the semantics of the CASE expression.
=> Optimize CASE expression for "expr or expr" usage.

datafusion/substrait/src/logical_plan/consumer.rs
Additional work for https://github.com/apache/datafusion/issues/13318
Improve the ergonomics of the consumer and fixed a gap in null literal handling.
Adds two handlers to the SubstraitConsumer
* `consume_rel`
* `consume_expression`
and routes all calls to `from_substrait_rel` and `from_substrait_rex` through them to allow users to customize behaviour at the Rel and Expression level.
The existing code in `from_substrait_null` would fail to handle nulls of user-defined types. The null handling code has been simplified to first convert the type of the null into a DataFusion DataType, which already allows for conversion of user-defined Substrait types using `consume_user_defined_type` and then converting that DataType into a ScalarValue.
As an added benefit, this also allows us to remove a …
=> feat(substrait): introduce consume_rel and consume_expression

datafusion/expr/src/expr_schema.rs, datafusion/optimizer/src/analyzer/type_coercion.rs, datafusion/sql/tests/sql_integration.rs, datafusion/sqllogictest/test_files/aggregate.slt, datafusion/sqllogictest/test_files/array.slt, datafusion/sqllogictest/test_files/errors.slt, datafusion/sqllogictest/test_files/scalar.slt
Closes #13979.
I added several new unit tests in `sql_integrations`, despite the fact that some cases are already covered in sqllogictest. It was also manually tested (removed the duplicated 'Error during planning'; no changes made to 'Error during planning: Execution error:' in the third case):
<table>
<tr>
<td><b>Before</b></td><td><b>After</b></td>
</tr>
<tr>
<td>
```sql
> select version(1);
Error during planning: Error during planning:
Failed to coerce arguments to satisfy a call
to version function: coercion from [Int64] to
the signature Exact([]) failed. No function
matches the given name and argument
types 'version(Int64)'. You might need to
add explicit type casts.
```
</td>
<td>
```sql
> select version(1);
Error during planning: Failed to coerce
arguments to satisfy a call to …
```
=> fix: Avoid re-wrapping planning errors  Err(DataFusionError::Plan) for use in plan_datafusion_err

datafusion/core/tests/fuzz_cases/join_fuzz.rs, datafusion/physical-plan/src/joins/sort_merge_join.rs, datafusion/physical-plan/src/test.rs, datafusion/sqllogictest/test_files/sort_merge_join.slt
=> feat: support `RightAnti` for `SortMergeJoin`

datafusion/core/src/execution/context/mod.rs
=> fix: Preserve session id when using `ctx.enable_url_table()`

datafusion/core/src/datasource/memory.rs
Closes #14010
Implements Option 1. from said issue.
If anybody thinks other options are more reasonable I can also change the implementation.
Test during planning whether the `MemTable` has zero partitions and raise a planning error if this is the case.
The error message is asserted in `test_insert_into_zero_partition`
Inserting into a `MemTable` with zero partitions fails during planning instead of during execution.
Should this be mentioned in the doc to `insert_into`?
=> FIX: Out of bounds error when inserting into MemTable with zero partitions

datafusion/wasmtest/Cargo.toml, datafusion/wasmtest/README.md, datafusion/wasmtest/src/lib.rs
=> Chore: update wasm-supported crates, add tests

datafusion-cli/Cargo.toml, datafusion/core/Cargo.toml, datafusion/ffi/Cargo.toml, datafusion/proto-common/Cargo.toml, datafusion/proto-common/gen/Cargo.toml, datafusion/proto/Cargo.toml, datafusion/proto/gen/Cargo.toml, datafusion/substrait/Cargo.toml
Closes #9214
`cargo-msrv` version `0.16.0` includes the upstream fix we needed (though current version is now `0.17.1` anyway)
- https://github.com/foresterre/cargo-msrv/releases/tag/v0.16.0
So we can apply the fix to the TOMLs to ensure we have a single source of truth for rust-version field.
Change all rust-version to use workspace value (other than cli which isn't part of the workspace)
CI checks
No
=> Use workspace rust-version for all workspace crates

Cargo.toml, datafusion-cli/Cargo.toml
Closes #14018
DataFusion uses an old version of `url` crate which has known vulnerability https://rustsec.org/advisories/RUSTSEC-2024-0421 fixed in latest release.
`url` crate update
Tests not included as it is just a dependancy update which should be covered by existing tests.
No user-facing changes.
=> `url` dependancy update

datafusion/functions-nested/src/cardinality.rs, datafusion/functions-nested/src/dimension.rs, datafusion/functions-nested/src/distance.rs, datafusion/functions-nested/src/empty.rs, datafusion/functions-nested/src/except.rs, datafusion/functions-nested/src/extract.rs, datafusion/functions-nested/src/map_extract.rs, datafusion/functions-nested/src/map_keys.rs, datafusion/functions-nested/src/map_values.rs, datafusion/functions-nested/src/position.rs, datafusion/functions-nested/src/range.rs, datafusion/functions-nested/src/remove.rs, datafusion/functions-nested/src/repeat.rs, datafusion/functions-nested/src/replace.rs, datafusion/functions-nested/src/resize.rs, datafusion/functions-nested/src/reverse.rs, datafusion/functions-nested/src/set_ops.rs, datafusion/functions-nested/src/string.rs
Changes the visibility of the ArraySort struct from super to public to allows broader access to the struct, enabling its use in other modules
Once again While working on adding support for ArrayPosition, I discovered it was not publicly accessible. To prevent others from encountering this issue, I updated the visibility of all nested function structs.
Related to #14006
=> Minor: make nested functions  public and implement Default trait

datafusion/functions-nested/src/string.rs, datafusion/functions/src/datetime/common.rs, datafusion/functions/src/regex/regexpcount.rs, datafusion/functions/src/string/repeat.rs, datafusion/functions/src/string/split_part.rs, datafusion/functions/src/strings.rs, datafusion/functions/src/unicode/character_length.rs, datafusion/functions/src/unicode/lpad.rs, datafusion/functions/src/unicode/rpad.rs, datafusion/functions/src/unicode/strpos.rs, datafusion/functions/src/unicode/substr.rs
Closes #.
Remove redundant implementation of `StringArrayType`
By CI.
No.
=> Minor: Remove redundant implementation of `StringArrayType`

datafusion/core/src/physical_optimizer/sanity_checker.rs, datafusion/core/tests/fuzz_cases/equivalence/ordering.rs, datafusion/core/tests/fuzz_cases/equivalence/projection.rs, datafusion/core/tests/fuzz_cases/equivalence/properties.rs, datafusion/core/tests/fuzz_cases/equivalence/utils.rs, datafusion/physical-expr/src/equivalence/ordering.rs, datafusion/physical-expr/src/equivalence/properties.rs, datafusion/physical-plan/src/memory.rs, datafusion/physical-plan/src/union.rs
As a first part of optimizing equivalence / ordering calculations I need to ensure the internal invariants are clear do I don't break them during optimization
This changes the various fields to be non `pub` 
Existing CI
As in https://github.com/apache/datafusion/pull/14037, While this is a breaking API change (the fields are no longer pub) I think disruptions will be minimal
=> Encapsulate fields of `EquivalenceProperties`

datafusion/core/tests/fuzz_cases/equivalence/utils.rs, datafusion/physical-expr/src/equivalence/class.rs, datafusion/physical-expr/src/equivalence/mod.rs, datafusion/physical-expr/src/equivalence/properties.rs
As a first part of optimizing equivalence / ordering calculations I need to ensure the internal invariants are clear do I don't break them during optimization
This changes the `classes` to be non pub and adds some conversion methods
Existing CI
As in https://github.com/apache/datafusion/pull/14037, While this is a breaking API change (the field is no longer pub) I think disruptions will be minimal
=> Encapsulate fields of `EquivalenceGroup`

datafusion/functions-nested/src/set_ops.rs, datafusion/sqllogictest/test_files/array.slt
Closes/FLUP #13809 
FLUP for https://github.com/apache/datafusion/pull/13810, this fix will handle nulls as well
=> Fix error on `array_distinct` when input is empty #13810

datafusion/physical-expr/src/equivalence/ordering.rs, datafusion/physical-expr/src/equivalence/projection.rs, datafusion/physical-expr/src/equivalence/properties.rs, datafusion/physical-plan/src/memory.rs, datafusion/physical-plan/src/union.rs
As a first part of optimizing equivalence / ordering calculations I need to ensure the internal invariants are clear do I don't break them during optimization
This changes the members of the equivalent classes to be non pub and documents what they do better.
While this is a breaking API change (the field is no longer pub) I hope the additional documentation makes migration as painless as possible
=> Encapsulate fields of `OrderingEquivalenceClass` (make field non pub)

datafusion/core/src/datasource/listing/table.rs
- Closes #14016 .
- closes https://github.com/timvw/datafusion/pull/1
Relatively simple changes to ensure that eventual compression information is considered
Yes. Added test to verify behavior is as expected.
No
=> Fix: ensure that compression type is also taken into consideration during ListingTableConfig infer_options

datafusion-cli/Cargo.lock, datafusion/optimizer/Cargo.toml, datafusion/optimizer/src/push_down_filter.rs, datafusion/sqllogictest/test_files/window.slt
Ensures selections can be pushed past window functions, similarly to what is already done with aggregations, when possible.
Unlike aggregations, however, extra care must be taken when handling multiple functions in the same Window operator.
N/A.
Pushing filters past window functions allows for a more efficient execution, as data are filtered closer to the root. Optimizers such as the one used by Postgres already support this optimization. Example:
```sql
CREATE TABLE t (k int, v int);
-- filter is pushed past the window function
EXPLAIN 
SELECT * 
FROM (
SELECT *, rank() OVER(PARTITION BY k) 
FROM t
) 
WHERE k = 1; -- filter column is used by the partition key
QUERY PLAN
---------------------------------------------------------
WindowAgg
->  Seq Scan on t
Filter: (k = 1)
-- filter is not …
```
=> feat(optimizer): Enable filter pushdown on window functions

datafusion/sql/Cargo.toml, datafusion/sql/src/unparser/plan.rs, datafusion/sql/tests/cases/plan_to_sql.rs
Closes #13621.
Unparsing unions with more than 2 inputs (produced by the logical optimizer)
Tests and required changes to unparser
Yes
Should be able to unparse most unions
=> Unparsing optimized (> 2 inputs) unions

datafusion/physical-expr/src/expressions/case.rs
=> Simplify error handling in case.rs (#13990)

datafusion-examples/examples/remote_catalog.rs, datafusion/catalog/Cargo.toml, datafusion/catalog/src/async.rs, datafusion/catalog/src/lib.rs
Closes #10339 .
As discussed in #13582 we do not actually want to make the schema providers asynchronous (the downstream changes are significant).  Instead a cache-then-plan approach was outlined in #13714.  This PR adds helpers which make it easier for users to follow the cache-then-plan approach.
This is hopefully just a first step.  Eventually I would like to integrate these into `SessionContext` itself so that we can have methods like `register_async_catalog_list` and `SessionContext` will keep track of a list of asynchronous providers and take care of calling the `resolve` method for the user.  The entire process can then be entirely hidden from the user.
Adds helpers, which are exposed in `datafusion_catalog` but not yet integrated into `SessionContext`.  Users can use them …
=> feat: add `AsyncCatalogProvider` helpers for asynchronous catalogs

datafusion/sql/src/unparser/dialect.rs, datafusion/sql/src/unparser/expr.rs
Unparser does not currently support extending dialect with custom handlers for internal UDFs or new engine extensions. Possible workarounds here are creating a custom dialect wrapper around original dialect with overrided `scalar_function_to_sql_overrides` or using `CustomDialect`. This is not very convenient and robust as requires tracking changes to the main dialect and reflecting the same improvements in the custom dialect.
Propose introducing  a pattern and approach for extending `scalar_function_to_sql_overrides` for dialects with additional handlers, example usage.
```rust
/// Create a new instance of the `DuckDB` dialect with support of custom internal UDFs
let dialect = DuckDBDialect::new().with_custom_scalar_overrides(vec![(
"cosine_distance", …
```
=> Custom scalar to sql overrides support for DuckDB Unparser dialect

datafusion/functions/Cargo.toml, datafusion/functions/benches/reverse.rs, datafusion/functions/src/unicode/reverse.rs
Closes #.
Improve performance of `reverse` function.
By CI.
No.
*Benchmark result
```rust
Compiling datafusion-functions v44.0.0 (/home/tailm/repos/github/datafusion/datafusion/functions)
Finished `bench` profile [optimized] target(s) in 1m 02s
Running benches/reverse.rs (target/release/deps/reverse-ee84c92e095fbd3f)
reverse_string_view [size=1024, str_len=8]
time:   [24.668 µs 24.701 µs 24.739 µs]
change: [-38.667% -38.454% -38.190%] (p = 0.00 < 0.05)
Found 13 outliers among 100 measurements (13.00%)
9 (9.00%) high mild
reverse_string_view [size=1024, str_len=32]
time:   [72.822 µs 72.914 µs 73.004 µs]
change: [-39.081% -38.568% -38.119%] (p = 0.00 < 0.05)
reverse_string …
```
=> Improve perfomance of `reverse` function

datafusion/substrait/Cargo.toml
Closes #13853.
This uses the same basic solution as in `substrait-rs`:
https://github.com/substrait-io/substrait-rs/blob/bbcc9f6d0b084a13706f39a43bbba9d37bf2a959/Cargo.toml#L62-L63
- `substrait-rs` has an optional `protoc` [feature](https://github.com/substrait-io/substrait-rs/blob/d0945cd0123e2cb39667e196b410a610242bcd54/Cargo.toml#L31)
0 The `protoc` feature [adds a dependency](https://github.com/substrait-io/substrait-rs/blob/d0945cd0123e2cb39667e196b410a610242bcd54/Cargo.toml#L54) on [`protobuf-src`](
https://docs.rs/protobuf-src/2.1.0/protobuf_src/), which ensures a fixed version of the protobuf compiler by compiling/vendoring it
- In the `build.rs` file, the [vendored protoc](https://github.com/substrait-io/substrait-rs/blob/d0945cd0123e2cb39667e196b410a610242bcd54/build.rs#L284-L285 …
=> docs(ci): use up-to-date protoc with docs.rs

datafusion/functions-window/src/nth_value.rs, datafusion/sqllogictest/test_files/window.slt
=> Fix bug in `nth_value` when `ignoreNulls` is true and no nulls in values

datafusion/expr/src/lib.rs
No
Since almost all items of the `signature` module are already re-exported from the `datafusion-expr` package, it makes sense to also re-export the newly-added `TypeSignatureClass` to simplify usage.
Re-export TypeSignatureClass from the datafusion-expr package.
No need to test.
Yes, users now can import `TypeSignatureClass` from the `datafusion-expr` package.
=> minor: re-export TypeSignatureClass from the datafusion-expr package

datafusion/common/src/pyarrow.rs, datafusion/core/src/datasource/listing/table.rs, datafusion/core/src/execution/context/mod.rs, datafusion/physical-expr-common/src/physical_expr.rs, datafusion/physical-expr-common/src/sort_expr.rs
=> Fix clippy for Rust 1.84

datafusion/expr/src/type_coercion/functions.rs
No
The error message of the `function_length_check` is incorrect.
Place the `expected_length` and `length` at where they should be.
Yes, added a simple unit test.
Yes, users will see correct error message when given unexpected number of args.
=> fix: incorrect error message of function_length_check

datafusion/core/src/physical_optimizer/replace_with_order_preserving_variants.rs
Closes #8230.
Added plan execution for `replace_with_order_preserving_variants.rs` only. In the original task, `enforce_distribution.rs` and `enforce_sorting.rs` are also suggested, which can be fixed later.
This change can be tested, for example, by modifying [this line](https://github.com/apache/datafusion/blob/42dce6e5d101cb3e414b832cbb16a2b87cf9f372/datafusion/core/src/physical_optimizer/replace_with_order_preserving_variants.rs#L1424) to `expressions::lit("3"),`. Such a change doesn't affect the execution plan representation, so it can only be detected by executing the plan.
No
=> test: Add plan execution during tests for bounded source

Cargo.toml
Fixes https://github.com/apache/datafusion/pull/14065#issuecomment-2582438534.
Maybe we should just add a `Cargo.lock` file to have checks in CI to prevent this in the future, following suggestions from https://doc.rust-lang.org/cargo/faq.html#why-have-cargolock-in-version-control and https://doc.rust-lang.org/cargo/guide/continuous-integration.html#verifying-latest-dependencies.
=> Bump `ctor` to `0.2.9`

datafusion/expr/src/type_coercion/functions.rs, datafusion/sqllogictest/test_files/math.slt
Closes #14059.
Make `get_valid_types` handle TypeSignature::Numeric(n) correctly, for various n.
Yes, added a unit test.
No.
=> fix: make get_valid_types handle TypeSignature::Numeric correctly

datafusion/core/tests/physical_optimizer/combine_partial_final_agg.rs, datafusion/core/tests/physical_optimizer/limited_distinct_aggregation.rs
- Related to https://github.com/apache/datafusion/issues/11502
I tried to move some of these tests to be with the code they are testing, but found out the reason is the dependency on ParquetExec
Add comments explaining this rationale so it is clearer to the next reader
No
=> Add comments to physical optimizer tests

datafusion-cli/src/print_format.rs, datafusion/common/src/format.rs, datafusion/functions-nested/src/map.rs, datafusion/sqllogictest/src/engines/datafusion_engine/normalize.rs, datafusion/sqllogictest/test_files/aggregate.slt, datafusion/sqllogictest/test_files/array.slt, datafusion/sqllogictest/test_files/avro.slt, datafusion/sqllogictest/test_files/expr.slt, datafusion/sqllogictest/test_files/map.slt, datafusion/sqllogictest/test_files/parquet.slt, datafusion/sqllogictest/test_files/scalar.slt, datafusion/sqllogictest/test_files/struct.slt, datafusion/sqllogictest/test_files/unnest.slt, docs/source/user-guide/sql/scalar_functions.md
Closes https://github.com/apache/datafusion/issues/13872.
Discussions on PR: https://github.com/apache/datafusion/pull/14046
The null values are printed blank, now they will be printed as "NULL".
Before: 
```
> select make_array(null);
+------------------+
| make_array(NULL) |
+------------------+
| []               |
+------------------+
> select array_repeat(null,0);
+-----------------------------+
| array_repeat(NULL,Int64(0)) |
+-----------------------------+
| []                          |
+-----------------------------+
> select array_repeat(null,1);
+-----------------------------+
| array_repeat(NULL,Int64(1)) |
+-----------------------------+
| []                          |
+-----------------------------+
```
Now: 
```
> select make_array(null);
+------------------+
| …
```
=> added "DEFAULT_CLI_FORMAT_OPTIONS"  for cli and sqllogic test

docs/source/user-guide/introduction.md
Datafusion is the central SQL query processing engine behind https://telemetry.sh and transitively powers many large analytics products including https://beamanalytics.io.
=> Add telemetry.sh to list of use cases

datafusion/functions/Cargo.toml, datafusion/functions/benches/find_in_set.rs, datafusion/functions/src/unicode/find_in_set.rs, datafusion/functions/src/unicode/mod.rs
Closes #.
Improve performance of `find_in_set` function
Yes. Added unit tests and benchmarks.
No.
*BENCHMARK RESULT
```rust
Compiling datafusion-functions v44.0.0 (/home/tailm/repos/github/datafusion/datafusion/functions)
Finished `bench` profile [optimized] target(s) in 1m 02s
Running benches/find_in_set.rs (target/release/deps/find_in_set-c80fb04778cbe610)
find_in_set/string_len_8
time:   [414.89 µs 415.67 µs 416.41 µs]
change: [-64.610% -64.526% -64.440%] (p = 0.00 < 0.05)
Found 2 outliers among 50 measurements (4.00%)
2 (4.00%) low mild
find_in_set/string_view_len_8
time:   [440.65 µs 441.02 µs 441.50 µs]
change: [-63.746% -63.607% -63.494%] (p = 0.00 < 0.05)
Found 2 outliers among 50 …
```
=> Improve performance of `find_in_set` function

datafusion/catalog/src/async.rs
- Follow on to https://github.com/apache/datafusion/pull/13800
Add a link to the relevant example to the documentation of the newly added `AsyncSchemaProvider`
Add link to docs
By CI
Docs only, no functional change
=> minor: Add link to example for `AsyncSchemaProvider`

datafusion/physical-expr-common/src/physical_expr.rs, datafusion/physical-expr/src/physical_expr.rs
=> Minor: use hashmap for `physical_exprs_contains` and move `PhysicalExprRef` to `physical-expr-common`

datafusion/execution/src/stream.rs
- Part of #7013 
Streams are hard enough to work with, let's document them the best we can
I often forget what the name of the class that can make a `Stream` into a `RecordBatchStream` so let's add that to the docs
1. Add a link to RecordBatchStreamAdapter to `SendableRecordBatchStream`
CI
more docs, no functional changes
=> Minor: Add a link to RecordBatchStreamAdapter to `SendableRecordBatchStream`

datafusion/substrait/Cargo.toml, datafusion/substrait/tests/utils.rs
Handle breaking change in substrait bump. Closes #14103.
=> Update substrait requirement from 0.51 to 0.52

datafusion/proto/proto/datafusion.proto, datafusion/proto/src/generated/pbjson.rs, datafusion/proto/src/generated/prost.rs, datafusion/proto/src/logical_plan/from_proto.rs, datafusion/proto/src/logical_plan/mod.rs, datafusion/proto/src/logical_plan/to_proto.rs, datafusion/proto/tests/cases/roundtrip_logical_plan.rs
=> feat: add support for `LogicalPlan::DML(...)` serde

datafusion/optimizer/src/push_down_filter.rs, datafusion/sqllogictest/test_files/subquery.slt
Closes #14108.
Please see the issue.
Aliased window expr is handled as if it is a normal window expr
Yes, with an .slt test, which was failing before
=> Avoid Aliased Window Expr Enter Unreachable Code

datafusion/functions-window/src/nth_value.rs
Closes #14063.
This PR simplifies some of the logic of the nth_value window function, making the code path clearer and more understandable.
Yes.
None.
=> clarify logic in nth_value window function

datafusion/sql/src/unparser/plan.rs, datafusion/sql/tests/cases/plan_to_sql.rs
Related to https://github.com/apache/datafusion/issues/11743, cc @LatrecheYasser 
This is a small improvement to the sql unparser. 
Basically, the projection of a table can be `None` or `Some(vec![])`. 
`None` means we want to select everything, or the table doesn't support projection pushdown. 
`Some(vec![])` means the table has empty projection, potentially because all the computation is been pushed down.
For example, with filter push down, this query has empty projection (i.e., `Some(vec![])`): `SELECT COUNT(*) FROM hits WHERE "URL" <> '';`, in that case the unpraser should return `SELECT 1 FROM ...` rather than `SELECT * FROM ...`
Please let me know if this makes sense!
Yes
No
=> Distinguish None and empty projection in unparser

.github/workflows/extended.yml
Closes #13967
Run sqlite test suite on push to main.
**##** What changes are included in this PR?
Just the github action. 
No, I do not know of a great way to test this.
No.
NOTE: This PR should **NOT** be merged until https://github.com/apache/datafusion-testing/pull/4 is merged into datafusion-testing and datafusion repo has been updated with a reference to that commit. As well a manual run of the sqlite test suite should likely be done prior to merging this just in case a change crept in between the generation of the sqlite test files and the merging of this PR.
=> Add sqlite sqllogictest run to extended.yml

datafusion-cli/Cargo.lock, datafusion/expr/src/udf.rs, datafusion/macros/Cargo.toml, datafusion/macros/src/user_doc.rs
Closes #14001 .
This pr modifies `user_doc` to find `label` only for given `doc_section` attribute and try correspondent const from predefined `DocSections`. If there is no match but label exists, (ex. `General Functions`) it will automatically fill `include` and `description` with default value as before.
will test with github CI.
=> doc-gen: make user_doc to work with predefined consts

README.md, datafusion-cli/README.md
The question of why `Cargo.lock` is not checked in comes up from time to time, most recently in
- https://github.com/apache/datafusion/pull/14069#pullrequestreview-2542239568
from @mbrobbel 
I think documenting the rationale as I understand it will help:
1. To answer questions about why it is this way
2. Help us decide if we want to change the process
Document my recollection of why Cargo.lock is not checked in
By CI
Update the readme
=> Minor: Document the rationale for the lack of Cargo.lock

datafusion/optimizer/src/analyzer/type_coercion.rs, datafusion/optimizer/tests/optimizer_integration.rs
If users use the whole analyzer, they won't encounter the issue. But if only use the [TypeCoercionRewriter](https://docs.rs/datafusion/latest/datafusion/optimizer/analyzer/type_coercion/struct.TypeCoercionRewriter.html)(Yes, it's me), such as 
```rust
if let LogicalPlan::Union(union) = logical_plan  {
logical_plan = TypeCoercionRewriter::coerce_union(union)?;
}
``` 
and if there is the wildcard in the union, such as the test in the PR, I'll get the error `https://github.com/apache/datafusion/blob/main/datafusion/expr/src/logical_plan/plan.rs#L2138`.
Make the error report early and clear, the current change will directly tell the user what they are missing.
Yes
No
=> Return err if wildcard is not expanded before type coercion

datafusion/physical-expr/src/equivalence/ordering.rs
I am testing out a change to the internal representation of `OrderingEquivalenceClass` in https://github.com/apache/datafusion/pull/14136 and this method turns out to basically be an implementation detail.
To make the job easier, let's make it a method on `OrderingEquivalenceClass`
1. move resolve_overlap a method on `OrderingEquivalenceClass`
By CI
No, this is entirely code movement
=> Minor: move resolve_overlap a method on `OrderingEquivalenceClass`

datafusion/functions/src/encoding/inner.rs, datafusion/functions/src/regex/regexpcount.rs, datafusion/functions/src/regex/regexplike.rs, datafusion/functions/src/regex/regexpmatch.rs, datafusion/functions/src/regex/regexpreplace.rs
As discussed in #13671, this PR will migrate the builtin binary string and regular expression  functions documentation that currently support migration.
=> doc-gen: migrate scalar functions (encoding & regex) documentation

datafusion/physical-plan/src/joins/hash_join.rs, datafusion/physical-plan/src/joins/nested_loop_join.rs, datafusion/physical-plan/src/joins/utils.rs
Closes #.
We have two same functions  `get_final_indices_from_shared_bitmap` in `hash_join.rs` and `nested_loop_join.rs` , remove one.
=> Deduplicate function `get_final_indices_from_shared_bitmap`

datafusion/physical-plan/src/joins/hash_join.rs
Closes #.
Improve performance.
Don't eval on experssions everytime when receiving new batch from probe side.
ci.
=> Reuse `on` expressions values in HashJoinExec

datafusion/core/src/physical_optimizer/join_selection.rs, datafusion/core/src/physical_optimizer/projection_pushdown.rs, datafusion/core/src/physical_planner.rs, datafusion/core/tests/fuzz_cases/join_fuzz.rs, datafusion/physical-plan/src/joins/hash_join.rs, datafusion/physical-plan/src/joins/nested_loop_join.rs, datafusion/physical-plan/src/joins/utils.rs, datafusion/proto/proto/datafusion.proto, datafusion/proto/src/generated/pbjson.rs, datafusion/proto/src/generated/prost.rs, datafusion/proto/src/physical_plan/mod.rs, datafusion/proto/tests/cases/roundtrip_physical_plan.rs, datafusion/sqllogictest/test_files/group_by.slt, datafusion/sqllogictest/test_files/tpch/plans/q11.slt.part
Closes #.
Similar to HashJoin, we also need projection pushdown for nested loop join
=> NestedLoopJoin Projection Pushdown

datafusion/substrait/src/logical_plan/consumer.rs
No issue added, let me know if one is needed
Fixing an issue with the current substrait consumer
Using built-in method for regularizing order by statements based on window frames in the substrait consumer
Yes
Anyone that is passing substrait plans directly to DataFusion should be able to pass window function nodes with no order bys and with a "RANGE" window frame unit.
=> Fix: regularize order bys when consuming from substrait

datafusion/functions/src/core/arrow_cast.rs, datafusion/functions/src/core/arrowtypeof.rs, datafusion/functions/src/core/coalesce.rs, datafusion/functions/src/core/getfield.rs, datafusion/functions/src/core/greatest.rs, datafusion/functions/src/core/least.rs, datafusion/functions/src/core/named_struct.rs, datafusion/functions/src/core/nullif.rs, datafusion/functions/src/core/nvl.rs, datafusion/functions/src/core/nvl2.rs, datafusion/functions/src/core/struct.rs, datafusion/functions/src/core/version.rs
Closes #13671 .
As discussed in #13671, this PR will migrate the builtin functions ( other, conditional, and struct) documentation that currently support migration.
=> doc-gen: migrate scalar functions (other, conditional, and struct) documentation

Cargo.toml, datafusion-cli/Cargo.lock, datafusion-cli/Cargo.toml, datafusion/common/Cargo.toml, datafusion/common/src/file_options/parquet_writer.rs, datafusion/common/src/pyarrow.rs, datafusion/core/src/datasource/file_format/parquet.rs, datafusion/core/src/datasource/physical_plan/parquet/row_group_filter.rs, datafusion/core/tests/fuzz_cases/pruning.rs, datafusion/physical-plan/src/aggregates/mod.rs, datafusion/proto-common/src/from_proto/mod.rs, datafusion/proto-common/src/to_proto/mod.rs, datafusion/proto/tests/cases/roundtrip_logical_plan.rs
- Closes #14114 
- Closes https://github.com/apache/datafusion/pull/13663
Further to the effort in #13663, this PR upgrades PyO3 to `0.23.3`, arrow-rs to `54.0.0` and parquet to `54.0.0`, and mark several deprecated functions as `allow[deprecated]` for further process.
=> Upgrade arrow-rs, parquet to `54.0.0` and pyo3 to `0.23.3`

datafusion/core/src/datasource/listing/table.rs, datafusion/core/src/datasource/physical_plan/file_scan_config.rs, datafusion/core/src/datasource/physical_plan/statistics.rs, datafusion/core/src/physical_optimizer/replace_with_order_preserving_variants.rs, datafusion/core/src/physical_optimizer/utils.rs, datafusion/core/tests/fuzz_cases/equivalence/utils.rs, datafusion/core/tests/fuzz_cases/window_fuzz.rs, datafusion/physical-expr-common/src/sort_expr.rs, datafusion/physical-expr/src/equivalence/ordering.rs, datafusion/physical-expr/src/equivalence/properties.rs, datafusion/physical-plan/src/joins/utils.rs, datafusion/physical-plan/src/memory.rs, datafusion/physical-plan/src/sorts/sort.rs, datafusion/physical-plan/src/topk/mod.rs, datafusion/proto/tests/cases/roundtrip_physical_plan.rs
In order to optimize the ordering calculations, we may need to change how the structures are represented internally.
Since all the inner fields are `pub` making such changes requires too many changes over the codebase
1. Make `LexOrdering::inner` non pub, 
2. add comments, 
3. update usages 
Yes, by existing CI
This is a deliberate API change  that forces all `LexOrdering` object to be created via constructor rather than directly
=> Make `LexOrdering::inner` non pub, add comments, update usages

datafusion/common/src/scalar/mod.rs, datafusion/core/tests/sql/path_partition.rs, datafusion/functions-aggregate/src/string_agg.rs, datafusion/functions/src/crypto/basic.rs, datafusion/functions/src/datetime/common.rs, datafusion/functions/src/encoding/inner.rs, datafusion/functions/src/string/concat.rs, datafusion/functions/src/string/concat_ws.rs, datafusion/optimizer/src/unwrap_cast_in_comparison.rs, datafusion/physical-expr/src/expressions/binary.rs, datafusion/physical-optimizer/src/pruning.rs
- Closes https://github.com/apache/datafusion/issues/14166
See https://github.com/apache/datafusion/issues/14166
TLDR is I don't want to have to remember to check all the variants of ScalarValue that can contain a string
1. Add `ScalarValue::try_as_str` to get str value from logical strings
2. Add docs/examples
3. Update some of the code in DataFusion to use this new API
yes, by doc tests and examples
there is a new API but all existing APIs still work
=> Add `ScalarValue::try_as_str` to get str value from logical strings

datafusion/functions-nested/src/sort.rs
…nction
As mentioned in #14115 , several examples in DataFusion codebase still using `BooleanBufferBuilder` rather than `NullBufferBuilder`, they should be replaced with `NullBufferBuilder` for optimization.
=> refactor: switch BooleanBufferBuilder to NullBufferBuilder in sort function
