- datafusion-cli/Cargo.lock
- datafusion/functions-aggregate/Cargo.toml
- datafusion/functions-aggregate/src/correlation.rs
…tion function
As mentioned in  #14115, several examples in DataFusion codebase still using `BooleanBufferBuilder` rather than `NullBufferBuilder`, they should be replaced with `NullBufferBuilder`  for optimization.
> refactor: switch BooleanBufferBuilder to NullBufferBuilder in correlation function

- .github/workflows/extended.yml
- Follow on to https://github.com/apache/datafusion/pull/14142 from @2010YOUY01 
WHen checking if the job ran I went to github: https://github.com/apache/datafusion/actions/runs/12850882520/job/35830990299
It was not immediately clear the right job had run because the name is somewhat generic:
Update the name to mention it runs with `extended_tests`
> Minor: Rename extended test job name

- docs/source/contributor-guide/communication.md
Following up suggestion from @alamb in our Discord community
> Added job board as a separate header in the documentation

- datafusion/sql/src/expr/binary_op.rs
- datafusion/sqllogictest/test_files/expr.slt
Closes #14098.
This change adds support for the Spaceship operator (<=>) by mapping it to the IsNotDistinctFrom operator and adds tests for the operator as well.
1. Mapping of Spaceship operator (<=>) with IsNotDistinctFrom
2. Adds tests for the Spaceship operator
3. Sanity test for the Spaceship operator
Yes. Tests have been added in the sqllogictest/test_files/expr.slt as well.
The users can now use the Spaceship operator (<=>) in their queries.
> Support spaceship operator (`<=>`) support (alias for `IS NOT DISTINCT FROM`

- datafusion/core/benches/sql_planner.rs
https://github.com/apache/datafusion/issues/13748 is a planning speed problem, so as I increase the performance I want a benchmark that shows the improvements
Add bechmark to the `sql_planner` suite
```shell
cargo bench  --bench sql_planner -- sorted
...
Warning: Unable to complete 100 samples in 5.0s. You may wish to increase target time to 6.0s, or reduce sample count to 80.
physical_sorted_union_orderby
time:   [60.126 ms 60.213 ms 60.320 ms]
6 (6.00%) high mild
3 (3.00%) high severe
```
Clippy / compilation is tested via CI
A new benchmark
Check out the flamegraph: 
Whole flamegraph:
> Add benchmark for planning sorted unions

- datafusion/core/src/physical_optimizer/projection_pushdown.rs
- datafusion/core/src/physical_planner.rs
- datafusion/core/tests/fuzz_cases/join_fuzz.rs
- datafusion/physical-optimizer/src/join_selection.rs
- datafusion/physical-plan/src/joins/hash_join.rs
- datafusion/physical-plan/src/joins/join_filter.rs
- datafusion/physical-plan/src/joins/nested_loop_join.rs
- datafusion/physical-plan/src/joins/sort_merge_join.rs
- datafusion/physical-plan/src/joins/stream_join_utils.rs
- datafusion/physical-plan/src/joins/symmetric_hash_join.rs
- datafusion/proto/src/physical_plan/mod.rs
> feat: Use `SchemaRef` in `JoinFilter`

- datafusion/functions-nested/src/concat.rs
- datafusion/functions-nested/src/range.rs
- datafusion/functions-nested/src/replace.rs
- datafusion/functions-nested/src/resize.rs
…ns-nested functions
As mentioned in #14115  , several examples in DataFusion codebase still using BooleanBufferBuilder rather than NullBufferBuilder, they should be replaced with NullBufferBuilder for optimization.
Functions replaced with `NullBufferBuilder`:
* `concat`
* `range`
* `resize`
* `replace`
> refactor: switch BooleanBufferBuilder to NullBufferBuilder in functions-nested functions

- datafusion/physical-expr/src/expressions/case.rs
- datafusion/sqllogictest/test_files/case.slt
~Draft as it builds on https://github.com/apache/datafusion/pull/14156~
- Follow on to https://github.com/apache/datafusion/pull/14156
While reviewing https://github.com/apache/datafusion/pull/14156 I noticed that the code unecessairly expanded a constant to an array, and that I could update it avoid having any internal errors
1. New .slt tests
2. Update case handling code to make it clear the errors are unreachable
yes, with new slt tests
> Improve `case` expr constant handling for when `<scalar>`

- datafusion/proto-common/src/from_proto/mod.rs
- datafusion/proto-common/src/to_proto/mod.rs
- datafusion/proto/tests/cases/roundtrip_logical_plan.rs
Follow on to
- https://github.com/apache/datafusion/pull/14153
I filed a ticket to track the removal of some deprecated features  and wanted to leave the information in the code as comments for my future self
- https://github.com/apache/datafusion/issues/14173
Add some references to the relevant ticket in the relevant code
> Minor add ticket references to deprecated code

- datafusion/core/src/physical_optimizer/enforce_sorting.rs
- datafusion/core/src/physical_optimizer/replace_with_order_preserving_variants.rs
- datafusion/core/src/physical_optimizer/sort_pushdown.rs
- datafusion/sqllogictest/test_files/topk.slt
`select * from (select * from topk limit 8) order by x limit 3;` will return 8 rows which isn't expected.
After debug: I found the fetch(limit 3) in topk will lost during `EnforceSorting`
fix offset missed during EnforceSorting
yes
> fix: fetch is missed in the EnsureSorting

- datafusion/physical-expr/src/analysis.rs
Added unit tests to interval analysis method which converts Expr tree to a set of Intervals for columns in a given schema.
I did not have an issue for this, but I was experimenting with the [`analyze`](https://docs.rs/datafusion/latest/datafusion/physical_expr/fn.analyze.html) method for converting `Expr` trees into sets of `Interval`s and pushed the resulting tests up, since I did not see any that directly tested the `analyze` method.
I did not see any unit tests for the `analyze` method. In addition to [this example](https://github.com/apache/datafusion/blob/5d1864866374b1a27068473b34aac1c8c88fad55/datafusion-examples/examples/expr_api.rs#L226), these provide a bit more of a sense of how the method works for different boundary expressions in queries.
Two new unit tests in the …
> test: interval analysis unit tests

- datafusion/physical-plan/src/joins/sort_merge_join.rs
Closes #14050.
Filtered SortMergeJoin outputs the data after left row shift which is not performant, merging batches into bigger chunks close to `batch_size`
> Merge SortMergeJoin filtered batches into larger batches

- datafusion/functions-nested/src/array_has.rs
- datafusion/sqllogictest/test_files/array.slt
Closes #13682 
Makes null handling for `array_has` consistent across scalars and arrays, following the DuckDB behavior of returning false instead of null if a list contains null values.
Updates both scalar and array handling for `array_has` to return false regardless of if the left hand side has any null values in it. This matches DuckDB, but differs from systems like Postgres, Spark, and Trino.
Tests are added and updated to accommodate the changes.
Fix handling of array_has for scalars to match the array behavior.
> Make scalar and array handling for array_has consistent

- datafusion/functions/benches/character_length.rs
- datafusion/functions/benches/helper.rs
- datafusion/functions/benches/reverse.rs
- datafusion/functions/src/unicode/reverse.rs
Closes #12445.
See the issue.
+ If all characters in this string are within the ASCII range, reverse bytes directly
+ Move `gen_string_array` in `benches/character_length.rs` to helper.rs
Yes. Using existing unit test
bench result
```
reverse_StringArray_ascii_str_len_8
time:   [93.762 µs 94.463 µs 95.301 µs]
change: [-38.347% -37.726% -37.143%] (p = 0.00 < 0.05)
7 (7.00%) high mild
reverse_StringArray_utf8_density_0.8_str_len_8
time:   [491.88 µs 496.57 µs 501.74 µs]
change: [-1.0373% +0.1648% +1.4032%] (p = 0.79 > 0.05)
No change in performance detected.
Found 6 outliers among 100 measurements (6.00%)
3 (3.00%) high severe
reverse_StringViewArray_ascii_str_len_8
time: …
```
> Faster reverse() string function for ASCII-only case

- datafusion/sqllogictest/Cargo.toml
- dev/release/README.md
- Related to https://github.com/apache/datafusion/discussions/14229
Other projects such as rust-iceberg would like to use the datafusion sqllogictest driver to write tests
The code is structured to be published as a crate, and is part of the official release tarballs. We just haven't previously published it to crates. io. 
1. Add instructions to release for publishing the datafusion-sqllogictest crates as part of releasing
I tested it manually to publish previously approved releases
- https://dist.apache.org/repos/dist/release/datafusion/datafusion-42.2.0/
- https://dist.apache.org/repos/dist/release/datafusion/datafusion-43.0.0/
- https://dist.apache.org/repos/dist/release/datafusion/datafusion-44.0.0/
(I had to add the new description field to Cargo.toml)
They are now available on …
> Add publishing datafusion-sqllogictest to release README.md

- datafusion/physical-optimizer/src/enforce_sorting/sort_pushdown.rs
Closes https://github.com/apache/datafusion/pull/14192#discussion_r1922215734
> Minor: use the minimum fetch

- datafusion/sqllogictest/src/engines/datafusion_engine/mod.rs
- datafusion/sqllogictest/src/engines/datafusion_engine/normalize.rs
- datafusion/sqllogictest/src/engines/mod.rs
- datafusion/sqllogictest/src/engines/output.rs
- datafusion/sqllogictest/src/lib.rs
Follow up https://github.com/apache/datafusion/pull/14233
For datafusion users, if they want to build their own sqllogictest frameworks, `normalize` and `output` components will be useful.
> Expose more components from sqllogictest

- datafusion/physical-expr/src/equivalence/properties.rs
N/A
Fix typo in public  API function
- Rename function to fix typo
- Add deprecated function with original name
> chore: deprecate function with typo in name (is_expr_constant_accross_partitions)

- datafusion/expr-common/src/type_coercion/binary.rs
- datafusion/sqllogictest/test_files/coalesce.slt
- datafusion/sqllogictest/test_files/insert.slt
- datafusion/sqllogictest/test_files/joins.slt
- datafusion/sqllogictest/test_files/union.slt
Previously, when combining `UInt64` with any signed integer, the resulting type would be `Int64`, which would result in lost information. Now, combining `UInt64` with a signed integer results in a `Decimal(20, 0)`, which is able to encode all (64-bit) integer types. Thanks @jonahgao for the pointers.
The function `bitwise_coercion` remains the same, since it's probably not a good idea to introduce decimals when performing bitwise operations. In this case, it converts `(UInt64 | _)` to `UInt64`.
Closes #14208.
- Updated `binary_numeric_coercion` in `expr-common/type_coercion/binary.rs`.
- Added new tests to `expr-common/type_coercion/binary.rs`.
- Updated existing sqllogic tests to use the new coercion.
Yes.
No.
> fix(expr-common): Coerce to Decimal(20, 0) when combining UInt64 with signed integers

- datafusion/sqllogictest/test_files/operator.slt
- Related to https://github.com/apache/datafusion/pull/14223
While reviewing https://github.com/apache/datafusion/pull/14223 I misinterpreted the impact of a change.
@jonahgao straightened me out in https://github.com/apache/datafusion/pull/14223/files#r1926245243 and had a good suggestion of how to test the behavior (don't overly extend the output types)
So let's add some tests to automatically ensure the coercion is working correctly
Add tests that show the output type of arithmetic operations with different input types
It is only tests, no behavior change
> Minor: Add tests for types of arithmetic operator output types

- datafusion/functions-nested/src/repeat.rs
- datafusion/sqllogictest/test_files/array.slt
Closes https://github.com/apache/datafusion/issues/14228.
The count in `array_repeat` function only works with `Int64` data type. Now, we have upcasted the count variable if the dataype is `Int8`, `Int16` and `Int32`. 
Updated the implementation of `array_repeat` to upcast  datatype of `count` argument.
Yes, Added test in `array.slt` file.
No
> Add casting of `count` to `Int64` in `array_repeat` function to ensure consistent integer type handling

- datafusion/execution/src/memory_pool/mod.rs
Closes #.
While using `MemoryPool` downstream, I noticed some typos and outdated documentation, so I am improving it here.
Updated some typos and minor documentations for memory pool
No, because they are just doc changes
No
> Minor: Update documentations for memory pool

- datafusion/sqllogictest/bin/sqllogictests.rs
- datafusion/sqllogictest/src/lib.rs
- datafusion/sqllogictest/src/util.rs
Follow up https://github.com/apache/datafusion/pull/14233
During building the custom sqllogictest, I found these methods are also useful.
> Extract useful methods from sqllogictest bin

- datafusion/sqllogictest/test_files/operator.slt
- Follow on to https://github.com/apache/datafusion/pull/14223
- Follow on to https://github.com/apache/datafusion/pull/14250
I was *still* confused about what happens with coercion in https://github.com/apache/datafusion/pull/14223#issuecomment-2611941609 and somewhat panic'ing that the change would impact performance. I want tests in place to show the output types of operations
Add more sqllogictests showing the output types when adding literals to various column types
> Add more tests showing coercing behavior with literals

- datafusion/functions-aggregate/Cargo.toml
- datafusion/functions-aggregate/benches/array_agg.rs
N/A
So we can see the improvement in #14299
added benchmark for array_agg `merge_batch` function
N/A
Nope
> bench: add array_agg benchmark

- datafusion/core/src/lib.rs
- Part of #7013 
- related to https://github.com/apache/datafusion/pull/14300
Recently while working with @berkaysynnada and @logan-keede  got me reviewing the documentation about the crate organization and I found it a but out of date
Let's update it
Update the "crate organization" documentation section, improving wording about use of the `datafusion` crate as well as add some new major subcrates
By CI
Update docs, no functional change
> Minor: Update documentation about crate organization

- datafusion/physical-plan/src/aggregates/group_values/multi_group_by/bytes.rs
- datafusion/physical-plan/src/aggregates/group_values/multi_group_by/bytes_view.rs
- datafusion/physical-plan/src/aggregates/group_values/multi_group_by/primitive.rs
As mentioned in #14115 , several examples in DataFusion codebase still using BooleanBufferBuilder rather than NullBufferBuilder, they should be replaced with NullBufferBuilder for optimization.
> refactor: switch `BooleanBufferBuilder` to `NullBufferBuilder` in unit tests  of multi_group_by

- datafusion/functions/src/math/monotonicity.rs
Closes #10595
These methods are pretty straight forward but they did not have any unit tests. Thus, this PR adds required tests.
- unit tests
- only change is addition of tests
No
> minor: add unit tests for monotonicity.rs

- datafusion-examples/examples/expr_api.rs
- datafusion/physical-expr/src/analysis.rs
- datafusion/physical-plan/src/filter.rs
Closes #14226
Details from #14226:
The [`AnalysisContext`](https://github.com/apache/datafusion/blob/2aff98e002ce6d48008b8bbe2b38ee644a6d5c20/datafusion/physical-expr/src/analysis.rs#L38) which is the result of the [`analyze`](https://github.com/apache/datafusion/blob/2aff98e002ce6d48008b8bbe2b38ee644a6d5c20/datafusion/physical-expr/src/analysis.rs#L159) method for refining column boundaries from a physical expression represents an empty set the same as an unbounded set.
For example, in the case where the bounds can not be shrunk, e.g., a < 0 OR a >= 0, this results an interval of [None, None], but means [-∞, ∞], i.e., [CERTAINLY_TRUE](https://github.com/apache/datafusion/blob/2aff98e002ce6d48008b8bbe2b38ee644a6d5c20/datafusion/expr-common/src/interval_arithmetic.rs#L419-L422). In the …
> make AnalysisContext aware of empty sets to represent certainly false bounds

- datafusion/physical-plan/src/values.rs
- Follow on to #14032
@shehabgamin notes on https://github.com/apache/datafusion/issues/14008#issuecomment-2609034408:
> **DataFusion**
> `ValuesExec` is now deprecated. The deprecation message is a bit confusing though. It currently states: "Use `MemoryExec::try_new_as_values` instead", but I think should say: "Use `MemoryExec::try_new_as_values` or `MemoryExec::try_new_from_batches` instead". Or, just simply: "Use `MemoryExec` instead".
Improve documentation about deprecation and the suitable alternatives
By CI
Only documentation, no functional change
> Improve deprecation message for MemoryExec

- datafusion/expr/src/logical_plan/plan.rs
Closes #13678.
Placeholders should be returned when calling `LogicalPlan::get_parameter_types()`
Remove filtering on None type parameters in `LogicalPlan::get_parameter_types()`
Added unit test with placeholder value.
> fix: LogicalPlan::get_parameter_types fails to return all placeholders

- datafusion/optimizer/src/push_down_limit.rs
- datafusion/sqllogictest/test_files/joins.slt
- Closes https://github.com/apache/datafusion/issues/14335
- Closes https://github.com/apache/datafusion/pull/14336
LIMITs are incorrectly pushed through FULL OUTER Joins
disable full outer join limit push down
Added unit test, also the original unit test show right behaviour now.
Yes, FULL OUTER JOIN and LIMIT produces right results now.
> fix: FULL OUTER JOIN and LIMIT produces wrong results

- datafusion/sql/src/unparser/dialect.rs
- datafusion/sql/src/unparser/expr.rs
NA
Some dialect doesn't support window frames in window function, for example, in dremio, window frame doesn't work with RANK, DENSE_RANK or ROW_NUMBER functions, and would cause error like will cause error like `ROW/RANGE not allowed with RANK, DENSE_RANK or ROW_NUMBER functions`.
Include a method for Dialect determining whether the Dialect support window frame based on the window function name, start_bound, end_bound. When the window frame start_bound and end_bound indicates that no frame is specified in the original query, and the window function requires no window frame to function in the expected way, the window function will be unparsed as None in ast.
Yes
No
> Customize window frame support for dialect

- datafusion/common/src/scalar/mod.rs
As mentioned in #14115  , several examples in DataFusion codebase still using BooleanBufferBuilder rather than NullBufferBuilder, they should be replaced with NullBufferBuilder for optimization.
> refactor: switch `BooleanBufferBuilder` to `NullBufferBuilder` in an unit test of common_scalar

- Cargo.toml
- datafusion-cli/Cargo.toml
Per the policy: https://github.com/apache/datafusion?tab=readme-ov-file#rust-version-compatibility-policy
> DataFusion's supports the last 4 stable Rust minor versions released and any such versions released within the last 4 months.
The most recent versions are `1.81`, `1.82`, `1.83`, `1.84`
https://github.com/rust-lang/rust/blob/master/RELEASES.md
- Related to https://github.com/apache/datafusion/pull/14257
Several of our dependencies now have a MSRV of 1.81
Update MSRV to 1.81
> Increase MSRV to 1.81.0

- datafusion/physical-plan/src/filter.rs
Closes #14347
CI is failing after I merged
- https://github.com/apache/datafusion/pull/14074
https://github.com/apache/datafusion/actions/runs/13018845357/job/36314586166
```
error[E0063]: missing field `sum_value` in initializer of `ColumnStatistics`
--> datafusion/physical-plan/src/filter.rs:462:28
|
462 |                     return ColumnStatistics {
|                            ^^^^^^^^^^^^^^^^ missing `sum_value`
```
Fix compilation
> Fix build "missing field `sum_value` in initializer of `ColumnStatistics`"

- datafusion-cli/Cargo.lock
- datafusion/physical-expr-common/Cargo.toml
- datafusion/physical-expr-common/src/binary_map.rs
As mentioned in #14115  , several examples in DataFusion codebase still using BooleanBufferBuilder rather than NullBufferBuilder, they should be replaced with NullBufferBuilder for optimization.
> refactor: switch `BooleanBufferBuilder` to `NullBufferBuilder` in binary_map

- datafusion/sqllogictest/bin/sqllogictests.rs
Make it possible again to run single SLT file, even if it's name is a substring of other file(s).
For example, after the change, this command:
cargo test --test sqllogictests -- test_files/union.slt
runs `union.slt` file, but does not run `pg_compat_union.slt`.
The functionality was probably accidentally lost probably in https://github.com/apache/datafusion/pull/13936
cc @Omega359
> Restore ability to run single SLT file

- datafusion/physical-plan/src/aggregates/group_values/single_group_by/primitive.rs
As mentioned in #14115  , several examples in DataFusion codebase still using BooleanBufferBuilder rather than NullBufferBuilder, they should be replaced with NullBufferBuilder for optimization.
> refactor: switch `BooleanBufferBuilder` to `NullBufferBuilder` in single_group_by

- datafusion/functions-nested/src/array_has.rs
- datafusion/sqllogictest/test_files/array.slt
- docs/source/user-guide/sql/scalar_functions.md
Closes #14216.
`arrays_overlap` function is supported by following query engines:
`arrays_overlap`: `select arrays_overlap(array('hello', world'), array('hello'))` => `true`
References:
Spark: https://docs.databricks.com/en/sql/language-manual/functions/arrays_overlap.html
Snowflake: https://docs.snowflake.com/en/sql-reference/functions/arrays_overlap
Presto: https://prestodb.io/docs/current/functions/array.html#arrays_overlap-x-y-boolean
DataFusion' s `array_has_any` function aims to have same behavior with `arrays_overlap` function and it can also be exposed as alias of legacy `array_has_any` function.
Also, related DataFusion Comet PR: https://github.com/apache/datafusion-comet/pull/1312
Added new UT to verify `arrays_overlap` function in terms of different source arrays.
Yes, new …
> Support arrays_overlap function (alias of `array_has_any`)

- datafusion/sqllogictest/bin/sqllogictests.rs
- Follow on to https://github.com/apache/datafusion/pull/14355
- Follow on to https://github.com/apache/datafusion/pull/13936
While testing https://github.com/apache/datafusion/pull/14355 from @findepi  I found it hard to see how many files were run
Before this PR:
```shell
andrewlamb@Andrews-MacBook-Pro-2:~/Software/datafusion$ cargo test --test sqllogictests  -- union
Finished `test` profile [unoptimized + debuginfo] target(s) in 0.16s
Running bin/sqllogictests.rs (target/debug/deps/sqllogictests-3d953efd822e1e41)
Completed in 0 seconds
```
After this PR, it reports `Completed 2 tests`:
```shell
andrewlamb@Andrews-MacBook-Pro-2:~/Software/datafusion$ cargo test --test sqllogictests  -- union
Finished `test` profile [unoptimized + debuginfo] target(s) in 0.16s
Running …
```
> Minor: include the number of files run in sqllogictest display

- datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs
- datafusion/sqllogictest/test_files/case.slt
There is an optimization for searched CASE where values are of boolean type. It was converting the expression like
CASE
WHEN X THEN A
WHEN Y THEN B
..
[ ELSE D ]
END
into
(X AND A)
OR (Y AND NOT X AND B)
[ OR (NOT (X OR Y) AND D) ]
This had the following problems
- does not work for nullable conditions. If X is nullable, we cannot use NOT (X) to compliment it. We need to use `X IS DISTINCT FROM true`
- it does not work correctly when some conditions are nullable and other values are false. E.g. X=NULL, A=true, Y=NULL, B=true, D=false, the CASE should return false, but the boolean expression will simplify to `(NULL AND ..) OR (NULL AND ..) OR (false)` which is NULL, not false
- thus we use `X` for truthness check of `X`, we need to test `X IS NOT DISTINCT FROM true`
- it did not work …
> Fix incorrect searched CASE optimization

- datafusion/core/tests/fuzz_cases/aggregate_fuzz.rs
- datafusion/functions-aggregate/src/median.rs
- datafusion/sqllogictest/test_files/aggregate.slt
Closes #13550 
Support specific GroupsAccumulator for median for better performance.
- Impl `MedianGroupsAccumulator`
- add related tests.
Yes, by exist tests and new e2e and fuzzy tests.
No.
> Improve speed of  `median` by implementing special `GroupsAccumulator` 

- datafusion/expr/src/logical_plan/builder.rs
- datafusion/expr/src/logical_plan/plan.rs
- datafusion/sqllogictest/test_files/union.slt
This commit fixes two bugs related to UNION handling
- when constructing union plan nullability of the other union branch was
ignored, thus resulting field could easily have incorrect nullability
- when pruning/simplifying projects, in `recompute_schema` function
there was similar logic, thus loosing nullability information even for
correctly constructed Union plan node
As a result, other optimizer logic (e.g. `expr_simplifier.rs`) could
draw incorrect conclusions and thus lead to incorrect query results, as
demonstrated with the attached SLT test.
- fixes https://github.com/apache/datafusion/issues/14352
> Fix UNION field nullability tracking

- datafusion/common/src/utils/mod.rs
- related to https://github.com/apache/datafusion/pull/14370
- Part of #14008 
As @andygrove  mentioned https://github.com/apache/datafusion/pull/14370/files#r1937564039 we should deprecate public APIs rather than remove them immediately
- Revert the changes in https://github.com/apache/datafusion/pull/14370
- Deprecate `is_sorted` instead
By the compiler
> Revert `is_sorted` removal, deprecate instead

- datafusion/expr-common/src/type_coercion/binary.rs
- datafusion/sqllogictest/test_files/case.slt
- Fixes https://github.com/apache/datafusion/issues/14383
When coercing fields for a struct, we shouldn't rename the fields to `c0`, `c1`, etc. See https://github.com/apache/datafusion/issues/14383
Preserve the Struct field names
Yes, sqllogictests are added
coerced struct field names do not revever to `c0`, `c1, etc
> Do not rename struct fields when coercing types in `CASE`

- datafusion/ffi/src/execution_plan.rs
- datafusion/ffi/src/insert_op.rs
- datafusion/ffi/src/lib.rs
- datafusion/ffi/src/record_batch_stream.rs
- datafusion/ffi/src/table_provider.rs
- datafusion/ffi/src/tests/async_provider.rs
This method was missing from the FFI bindings for use in datafusion-python extensions.
Closes #14390.
Add missing method wrapper for `TableProvider::insert_into` in the FFI bindings.
A wrapper for `TableProvider::insert_into` is added.
Its tested as thoroughly as `TableProvider::scan`.
Previously wrapped `TableProvider` instances will now support `insert_into` which I guess would be user-facing?
> Add `TableProvider::insert_into` into FFI Bindings

- datafusion/core/tests/dataframe/mod.rs
- datafusion/optimizer/src/analyzer/type_coercion.rs
- Closes https://github.com/apache/datafusion/issues/13510
Fix a bug
Resolve join predicates using the correct schema
Yes, a new unit test is added
Bug fix
> Fix join type coercion when joining 2 relations with the same name via `DataFrame` API

- datafusion/core/tests/dataframe/mod.rs
- Follow on to https://github.com/apache/datafusion/pull/14387
@jonahgao  found a typo 🤦 https://github.com/apache/datafusion/pull/14387#discussion_r1938293922
Fix typo
> Minor: fix typo in test name

- datafusion/core/tests/dataframe/mod.rs
- Issues https://github.com/apache/datafusion/issues/6057 was fixed long ago, this PR is only to add regression test
- Closes https://github.com/apache/datafusion/issues/6057
> test: add regression test for unnesting dictionary encoded columns

- datafusion/functions-aggregate/src/median.rs
This is a small (one 20-lines change) follow-on to https://github.com/apache/datafusion/pull/13681
@Rachelint (in https://github.com/apache/datafusion/pull/13681) makes `median()` aggregate function significantly faster by implementing `GroupsAccumulator`
However, regular `Accumulator` is still used in no-grouping aggregates and window expressions, this PR took some code from https://github.com/apache/datafusion/pull/13681 to also improve `median()`'s regular `Accumulator` implementation
Benchmarks:
```
DataFusion CLI v44.0.0
> CREATE EXTERNAL TABLE IF NOT EXISTS lineitem (
l_orderkey BIGINT,
l_partkey BIGINT,
l_suppkey BIGINT,
l_linenumber INTEGER,
l_quantity DECIMAL(15, 2),
l_extendedprice DECIMAL(15, 2),
l_discount DECIMAL(15, 2),
l_tax DECIMAL(15, 2),
l_returnflag VARCHAR, …
```
> perf: Improve `median` with no grouping by 2X 

- datafusion/expr-common/src/signature.rs
- datafusion/expr/src/lib.rs
- datafusion/expr/src/type_coercion/functions.rs
- datafusion/expr/src/udaf.rs
- datafusion/expr/src/udf.rs
- datafusion/functions-nested/src/extract.rs
- datafusion/functions-nested/src/flatten.rs
- datafusion/physical-expr/src/scalar_function.rs
- datafusion/sqllogictest/test_files/array.slt
This commit fixes the array_slice function so that if any arguments are NULL, the result is NULL. Previously, array_slice would return an internal error if any of the arguments were NULL. This behavior matches the behavior of DuckDB for array_slice.
Fixes #10548
Closes #10548.
Yes
Yes, previously a user would be returned an error, now they are returned a NULL value for `array_slice` with NULL input.
> bug: Fix NULL handling in array_slice, introduce `NullHandling` enum to `Signature`

- datafusion/functions-nested/src/map_keys.rs
- datafusion/functions-nested/src/map_values.rs
- datafusion/sqllogictest/test_files/map.slt
> Fix `null` input  in `map_keys/values`

- datafusion/expr-common/src/type_coercion/binary.rs
- datafusion/sqllogictest/test_files/case.slt
- datafusion/sqllogictest/test_files/struct.slt
- Fixes https://github.com/apache/datafusion/issues/14154
See issue -- nested structs in Lists are not coerced correctly
1. Fix bug (basically the same fix in https://github.com/apache/datafusion/pull/14384 to the type_union resolution)
2. Add tests
Yes, new sqllogictests
Bug fix
> Fix regression list Type Coercion List with inner type struct which has large/view types

- datafusion/functions/benches/regx.rs
- datafusion/functions/src/regex/regexpmatch.rs
- datafusion/sqllogictest/test_files/regexp.slt
- datafusion/sqllogictest/test_files/string/string_view.slt
Closes #11911
Add support for utf8view to regexp_match function
Code, tests, benchmarks.
Yes
signature for regexp_match rust function (not the udf) changed to not include <T: OffsetSizeTrait>
I am unsure if that is an breaking api change or not. I suppose it should be.
> Update REGEXP_MATCH scalar function to support Utf8View

- datafusion/expr-common/src/type_coercion/binary.rs
- datafusion/sqllogictest/test_files/case.slt
- datafusion/sqllogictest/test_files/struct.slt
- Backport https://github.com/apache/datafusion/pull/14385 to the 45 release branch
> [branch-45] Fix regression list Type Coercion List with inner type struct which has large/view types (#14385)

- datafusion/physical-plan/Cargo.toml
- datafusion/physical-plan/src/joins/symmetric_hash_join.rs
None.
With the MSRV > 1.80 we can use `std::sync::LazyLock` instead of `once_cell::Lazy`.
Remove `once_cell` dependency from `datafusion-physical-plan` and replace use of `once_cell::Lazy` with `std::sync::LazyLock`.
CI.
Datafusion crates no longer depend directly on `once_cell`.
> Replace `once_cell::Lazy` with `std::sync::LazyLock`

- datafusion/expr/src/logical_plan/builder.rs
- datafusion/optimizer/src/decorrelate.rs
Fix link to issue. Instead of linking to https://github.com/apache/datafusion/pull/10500, link to https://github.com/apache/datafusion/issues/10553
> chore: Fix link to issue and expand comment 

- datafusion/sql/src/parser.rs
Closes apache/datafusion#14372
This PR allows to skip **[COPY INTO](https://docs.snowflake.com/en/sql-reference/sql/copy-into-table)** statement which is not supported by DFParser.
**COPY INTO** already supported by native parser as a **Statement::CopyIntoSnowflake**
Added some tests with snowflake dialect
No
> DFParser should skip unsupported COPY INTO

- datafusion/core/benches/aggregate_query_sql.rs
- datafusion/functions-aggregate/src/first_last.rs
- datafusion/sqllogictest/test_files/group_by.slt
Closes https://github.com/apache/datafusion/issues/14215
- ## Rationale for this change
Right now, merging / updating batches in `first_value` / `last_value` we sometimes sort input to find just one max / min row. In some cases, we request to sort only top-1 value but even that produces extra index buffers...
Instead of sorting arrays, just finding min / max directly. 
Yes, by `aggregate.slt`. Also added new benches to illustrate the speed improvement 
No
> Improve performance 10%-100% in `FIRST_VALUE` / `LAST_VALUE` by not sort rows in `FirstValueAccumulator`

- docs/source/user-guide/cli/datasources.md
This PR updates `datasources.md` doc by removing `AWS_PROFILE` from the supported S3 configuration as its experimental support was removed from `object_store` crate in the version `0.6.0`: https://github.com/apache/arrow-rs/pull/4238
> fix(doc): remove AWS_PROFILE from supported S3 configuration

- datafusion/sqllogictest/test_files/string/string_literal.slt
Add test cases for the bug recently fixed in Arrow.
- closes https://github.com/apache/datafusion/issues/13304
> chore: Add more LIKE with escape tests

- datafusion/sql/src/unparser/expr.rs
Adds more support for `ScalarValue` variants in `scalar_to_sql`
Includes support for lists and dictionary type scalars.
Tests have been added for the `ScalarValue::Dictionary` and `ScalarValue::List` variants
There are no breaking/user-facing changes
> Support `Dictionary` and `List` types in  `scalar_to_sql`

- datafusion/proto/proto/datafusion.proto
- datafusion/proto/src/generated/pbjson.rs
- datafusion/proto/src/generated/prost.rs
- datafusion/proto/src/physical_plan/mod.rs
- datafusion/proto/tests/cases/roundtrip_physical_plan.rs
- Closes https://github.com/apache/datafusion/issues/14253
We don't currently serialize `parquet_options` in `ParquetExec`
Write and optionally parse the value in protobuf
Yes, extended a round trip test
No
> Serialize `parquet_options` in `datafusion-proto`

- datafusion/functions-nested/src/make_array.rs
- datafusion/sqllogictest/test_files/array.slt
- Closes #13819.  
Currently, `FixedSizeList` values inside a `make_array` call are eagerly coerced into `List`, resulting in non-intuitive behavior.  
To improve consistency, this PR aligns the behavior with DuckDB: coercion should only occur when the `FixedSizeList` is modified. This approach makes coercion more predictable and avoids unnecessary type transformations.  
This PR removes the coercion logic in `make_array` when the type union resolves to `FixedSizeList`, ensuring that `make_array` no longer performs eager coercion.  
Previously, `make_array` would automatically coerce `FixedSizeList` into `List`, even when no operations were performed. With this fix, the expected behavior is preserved:  
```sql
> SELECT arrow_typeof([arrow_cast([1, 2, 3], 'FixedSizeList(3, Int64)')]); …
```
> fix: `List` of `FixedSizeList` coercion issue in SQL

- datafusion/expr/src/logical_plan/builder.rs
- datafusion/expr/src/logical_plan/invariants.rs
- datafusion/optimizer/src/decorrelate_predicate_subquery.rs
- datafusion/sqllogictest/test_files/explain.slt
- datafusion/sqllogictest/test_files/subquery.slt
- datafusion/sqllogictest/test_files/unnest.slt
Support uncorrelated EXISTS
- based on https://github.com/apache/datafusion/pull/14463 so 
- also fixes https://github.com/apache/datafusion/issues/14461
> core: Support uncorrelated EXISTS

- datafusion/functions/src/core/arrow_cast.rs
- datafusion/functions/src/core/arrowtypeof.rs
- datafusion/functions/src/core/getfield.rs
- datafusion/functions/src/core/nullif.rs
- datafusion/functions/src/core/nvl.rs
- datafusion/functions/src/core/nvl2.rs
- datafusion/functions/src/core/version.rs
- datafusion/functions/src/crypto/basic.rs
- datafusion/functions/src/datetime/date_part.rs
- datafusion/functions/src/datetime/make_date.rs
- datafusion/functions/src/datetime/to_char.rs
- datafusion/functions/src/lib.rs
- datafusion/functions/src/math/abs.rs
- datafusion/functions/src/utils.rs
Add a `take_function_args` helper that provides convenient unpacking of function arguments along with validation that the provided argument count matches the expected.  A few functions are updated to leverage the new pattern to demonstrate its usefulness.
> Validate and unpack function arguments tersely

- datafusion/functions-nested/src/extract.rs
- datafusion/sqllogictest/test_files/array.slt
This commit fixes the following edge cases in the array_slice function so that it's semantics match DuckDB:
- When begin < 0 and -begin > length, begin is clamped to the beginning of the list.
- When step < 0 and begin = end, then the result should be a list with the single element found at index begin/end.
- Fixes #10548
- Closes #10548.
Yes
Yes, the behavior of `array_slice` has changed.
> bug: Fix edge cases in array_slice

- datafusion/core/tests/custom_sources_cases/statistics.rs
- datafusion/core/tests/physical_optimizer/limit_pushdown.rs
- datafusion/core/tests/sql/explain_analyze.rs
- datafusion/physical-optimizer/src/limit_pushdown.rs
- datafusion/physical-plan/src/coalesce_partitions.rs
- datafusion/physical-plan/src/stream.rs
- datafusion/physical-plan/src/union.rs
- datafusion/sqllogictest/test_files/aggregate.slt
- datafusion/sqllogictest/test_files/limit.slt
- datafusion/sqllogictest/test_files/repartition.slt
- datafusion/sqllogictest/test_files/union.slt
> Feat: Add fetch to CoalescePartitionsExec

- datafusion/expr/src/type_coercion/functions.rs
- datafusion/optimizer/src/analyzer/type_coercion.rs
- datafusion/sql/tests/sql_integration.rs
- datafusion/sqllogictest/test_files/aggregate.slt
- datafusion/sqllogictest/test_files/array.slt
- datafusion/sqllogictest/test_files/errors.slt
- datafusion/sqllogictest/test_files/expr.slt
- datafusion/sqllogictest/test_files/functions.slt
- datafusion/sqllogictest/test_files/math.slt
- datafusion/sqllogictest/test_files/scalar.slt
- Closes #.
Function signature error messages do not include the function name making for debugging issues very difficult in a system with dataframes with hundreds of function calls.
Updated error messages and tests.
Yes
Unless you count updated error messages, no.
> Improve error messages to include the function name.

- datafusion/expr/src/expr_rewriter/order_by.rs
- datafusion/sql/tests/sql_integration.rs
- datafusion/sqllogictest/test_files/order.slt
Closes #14459.
Added the search for a columnized expressions in the children projection nodes.
Yes.
No.
> fix: order by expr rewrite fix

- datafusion/expr/src/logical_plan/plan.rs
Closes #.
We found a bug related to `with_new_exprs()` for the `Limit` plan in https://github.com/GreptimeTeam/greptimedb/issues/5469
The `Limit` plan returns expressions in the order: `[skip, fetch]`
https://github.com/apache/datafusion/blob/e8d9b62f7f7c7a8bfccbff020360c87ed79b59f8/datafusion/expr/src/logical_plan/tree_node.rs#L457-L459
When applying the expressions, it uses `pop()` which rewrites fields in the wrong order. It will swap `skip` and `fetch`.
https://github.com/apache/datafusion/blob/e8d9b62f7f7c7a8bfccbff020360c87ed79b59f8/datafusion/expr/src/logical_plan/plan.rs#L962-L963
This PR rewrites skip and fetch in the reverse order to get the correct `Limit` plan.
This PR adds more cases for all possible `fetch` and `limit` combinations.
> fix: rewrite fetch, skip of the Limit node in correct order

- datafusion/functions-nested/src/extract.rs
- datafusion/sqllogictest/test_files/array.slt
In 3dfce7d33c19d6e7941b58cb7e83194c066347ca I misunderstood an existing test and accidentally added a variant of `array_slice` that accepts two arguments. This variant is not valid and only works if one of the arguments are null. This commit fixes the problem by removing the two argument variant.
Related to #10548
Fixes a mistake in my previous RP.
Yes
No
> bug: Remove array_slice two arg variant

- datafusion/physical-plan/src/sorts/index.rs
- datafusion/physical-plan/src/sorts/mod.rs
This is a minor change for remove unused index file and mod.
no
> Minor: deprecate unused index mod

- datafusion/common/src/config.rs
- datafusion/core/tests/macro_hygiene/mod.rs
The `config_namespace` macro was relying on a few symbols being properly imported before its used. This removes that need by referring to the symbols directly with the `$crate` prefix.
- Closes #14518.
The `config_namespace!` macro relied on symbols being properly imported. This fixes that issue.
1. Fix `config_namespace!` to not require imported symbols being available.
2. Re-add the inadvertently removed `#[macro_export]` attribute.
Yes. There's an isolated test to show that the macro now works without any `use` statements.
Some folks might get "unused import" diagnostics/warnings after this change, maybe?
> Fix config_namespace macro symbol usage

- datafusion/expr/src/lib.rs
- datafusion/expr/src/udf.rs
- datafusion/functions-nested/src/extract.rs
- datafusion/physical-expr/src/scalar_function.rs
3dfce7d33c19d6e7941b58cb7e83194c066347ca added an enum to all scalar functions called `NullHandling`, with two variants: `PassThrough` and `Propagate`. `PassThrough` would pass through null inputs to the function implementation. `Propagate` would cause the function to return null if any of the inputs were scalar and null, it would not do anything if an input was an array and null. Function implementors were responsible for handling null array inputs and making sure the behavior was consistent with the scalar null behavior caused by `NullHandling`.
If the function signature correctly described the accepted types, then the null array input handling would also work for null scalar inputs. However, if the function signature was `VariadicAny`, then the null array input handling would not work …
> functions: Remove NullHandling from scalar funcs

- datafusion/core/src/lib.rs
- datafusion/core/src/physical_planner.rs
- datafusion/core/src/schema_equivalence.rs
- datafusion/sqllogictest/test_files/union.slt
Physical plan can be further optimized. In particular, an expression can be determined as never null even if it wasn't known at the time of logical planning. Thus, the final schema check needs to be relax, allowing now-non-null data where nullable data was expected. This replaces schema equality check, with asymmetric "is satisfied by" relation.
- implements https://github.com/apache/datafusion/issues/13190#issuecomment-2455689662
- fixes https://github.com/apache/datafusion/issues/13190
> Relax physical schema validation

- datafusion/expr/src/udaf.rs
- datafusion/expr/src/udf.rs
- datafusion/expr/src/udwf.rs
When composing or decorating functions, it's useful to operate on Impl trait objects (dyn ScalarUDFImpl) instead of the Expr-level adapter (ScalarUDF). However, before the change, it was impossible to construct `ScalarUDF` from `Arc<dyn ScalarUDFImpl>`, even though the use of `Arc` is already part of the type API. This commit allows constructing the scalar from a shared impl object.
> Allow constructing ScalarUDF from shared implementation

- datafusion/core/src/physical_planner.rs
- datafusion/core/tests/fuzz_cases/window_fuzz.rs
- datafusion/core/tests/physical_optimizer/test_utils.rs
- datafusion/physical-optimizer/src/enforce_distribution.rs
- datafusion/physical-optimizer/src/enforce_sorting/mod.rs
- datafusion/physical-plan/src/windows/bounded_window_agg_exec.rs
- datafusion/physical-plan/src/windows/mod.rs
- datafusion/physical-plan/src/windows/window_agg_exec.rs
- datafusion/proto/src/physical_plan/mod.rs
- datafusion/proto/tests/cases/roundtrip_physical_plan.rs
> chore: remove partition_keys from (Bounded)WindowAggExec

- datafusion/core/src/datasource/physical_plan/parquet/mod.rs
- datafusion/physical-optimizer/src/pruning.rs
- datafusion/sqllogictest/test_files/parquet.slt
- datafusion/sqllogictest/test_files/parquet_filter_pushdown.slt
- datafusion/sqllogictest/test_files/repartition_scan.slt
> use a single row_count column during predicate pruning instead of one per column

- datafusion/proto/src/bytes/mod.rs
- Closes #14560
json parity with bytes impl
Code.
Existing tests
No
> Update proto to support to/from json with an extension codec

- datafusion/core/tests/physical_optimizer/enforce_sorting.rs
- datafusion/core/tests/physical_optimizer/test_utils.rs
- datafusion/physical-optimizer/src/enforce_sorting/mod.rs
It's clear that fetch will miss after removing SPM
If SPM is with fetch, we won't remove it.
Yes, ut
No
> Fix: limit is missing after removing SPM

- .github/workflows/extended.yml
- Closes #14576
Get CI working again.
added cargo clean at the end of each step in extended.yml
Nope
No
> Adding cargo clean at the end of every step 

- .github/actions/setup-builder/action.yaml
- Closes [#14435](https://github.com/apache/datafusion/issues/14435)
Remove unused build dependency `cmake`
```
.github/actions/setup-builder/action.yaml
```
Yes
No
> Revert modification of build dependency

- datafusion-cli/Cargo.toml
This commit adds nested expressions to the CLI by default so users can run functions like `array_slice` and other nested expressions.
None
It can be confusing for users that nested expressions don't work in the CLI by default. The error message is not that helpful either, for example:
```
DataFusion CLI v45.0.0
> select array_slice([1,2,3], 1, 2);
Error during planning: Invalid function 'array_slice'.
Did you mean 'array_agg'?
```
This PR enables them by default to avoid this confusion.
No
No
> cli: Add nested expressions

- .github/workflows/extended.yml
- Part of https://github.com/apache/datafusion/issues/14576
These tests are failing on main due to out of disk space (see https://github.com/apache/datafusion/issues/14576)
Here is an example: https://github.com/apache/datafusion/actions/runs/13261520752/job/37019301867
1. Disable failing tests
No
Hopefully we'll get the tests passing again on main
> Disable extended tests (`extended_tests`) that are failing on runner

- datafusion/functions/benches/repeat.rs
- datafusion/functions/src/string/repeat.rs
minor fix
Check string size overflow before string repeat build to fail fast and save memory.
check max size in string repeat function
added unit test
More friendly error message
> minor: check size overflow before string repeat build

- datafusion/functions/Cargo.toml
- datafusion/functions/benches/date_trunc.rs
- datafusion/functions/src/datetime/date_trunc.rs
N/A
I haven't looked at the generated code, but i presume that using `try_unary` can lead to better vectorization.
- Add benchmark for `date_trunc`
- Prefer using `try_unary` over `iter`-`map` combo.
```
date_trunc_minute_1000  time:   [12.745 µs 12.794 µs 12.849 µs]
change: [-19.871% -19.544% -19.210%] (p = 0.00 < 0.05)
```
Using existing tests.
Faster `date_trunc`
> Speedup `date_trunc`  (~20% time reduction)

- datafusion/physical-expr/src/equivalence/class.rs
- datafusion/sqllogictest/test_files/join.slt.part
Closes #14326.
See the issue above.
Now projection mapping source expression is normalized before we lookup in the map.
Yes, there is a unit test.
No
> equivalence classes: use normalized mapping for projection

- datafusion/sql/src/statement.rs
- datafusion/sql/tests/sql_integration.rs
- Closes #14583.
When executing DELETE statements with case-sensitive quoted table names, the table name was incorrectly being normalized to lowercase during table scan creation.
The issue was introduced in commit 8b716d3 where the table name was being converted to a string before being passed to `LogicalPlanBuilder::scan()`. This caused it to be treated as a new SQL identifier and normalized again, losing case sensitivity.
- Fixed DELETE statement handling to preserve case-sensitivity of table names by passing the already available and normalized `TableReference` directly to `LogicalPlanBuilder::scan()` instead of converting to string first
Yes, added a new test in `datafusion/sql/tests/sql_integration.rs`:
- `plan_delete_quoted_identifier_case_sensitive()`: verifies case-sensitive …
> fix: case-sensitive quoted identifiers in DELETE statements

- .github/dependabot.yml
None.
Groups PRs like the ones listed into one:
- https://github.com/apache/datafusion/pull/14621
- https://github.com/apache/datafusion/pull/14622
- https://github.com/apache/datafusion/pull/14623
Dependabot config update to group `prost*` and `pbjson*` updates.
No.
No.
> chore(deps): group `prost` and `pbjson` dependabot updates

- datafusion/core/src/test/mod.rs
N/A
Follow-up of [chore(deps): bump bzip2 from 0.5.0 to 0.5.1 #14620](https://github.com/apache/datafusion/pull/14620)
The auto-finish on drop feature has been added back in bzip2 0.5.1, so there's no need to keep our implementation.
> [3f3bb54](https://github.com/trifectatechfoundation/bzip2-rs/commit/3f3bb54746ff1afee6a6039018dc9c6c2d832b7b) Add finisher drop implementation to BzEncoder
Yes
No
> Minor: remove unused `AutoFinishBzEncoder`

- datafusion/expr-common/src/type_coercion/binary.rs
- datafusion/sqllogictest/test_files/coalesce.slt
- Closes #14581.
utf8view is good enough, there is no reason we need `dict(_, utf8view)`.
> Fallback to Utf8View for `Dict(_, Utf8View)` in `type_union_resolution_coercion`

- datafusion/core/src/lib.rs
- docs/source/index.rst
- docs/source/user-guide/features.md
- docs/source/user-guide/sql/index.rst
- closes https://github.com/apache/datafusion/issues/825
- closes https://github.com/apache/datafusion/issues/1222
I ran across the status page when looking at the docs. The status page was both out of date and hard to find
1. Move the page from SQL status --> Features
1. Update for current support
I built the pages manually and they look quite good if I do say so myself
> Update features / status documentation page

- benchmarks/src/bin/external_aggr.rs
- benchmarks/src/clickbench.rs
- benchmarks/src/h2o.rs
- benchmarks/src/imdb/run.rs
- benchmarks/src/sort_tpch.rs
- benchmarks/src/tpch/run.rs
- benchmarks/src/util/options.rs
- Closes #14641.
I had to run sort-tpch queries with memory limit when testing fixes for memory related issues, so I decide to add `--memory-limit` option for most of the benchmarking cli tools. I wish other developers could find it handy.
This PR adds 2 cli options `--memory-limit`, `--mem-pool-type` and `--sort-spill-reservation-bytes` to the following benchmarking tools:
* `dfbench` subcommands: `sort`, `sort-tpch`, `clickbench`, `h2o`, `imdb`, `parquet-filter`
* `tpch`
* `imdb`
`external_aggr` already supports `--memory-limit`, it now accepts `--mem-pool-type`. The default value of `--mem-pool-type` is `fair` so the behavior remains unchanged.
The changes were tested manually.
No. The benchmarking guide has not covered every option so hopefully the developers could find these options …
> feat: Add support for --mem-pool-type and --memory-limit options to multiple benchmarks

- docs/source/user-guide/sql/scalar_functions.md
A small logical conflict came in from
- https://github.com/apache/datafusion/pull/12116
CI is broken on main after merge of above
Example: https://github.com/apache/datafusion/actions/runs/13331376256/job/37236061495
I reran `./dev/update_function_docs.sh` and checked in the result
> Fix CI doctests on main

- datafusion/core/src/dataframe/mod.rs
- datafusion/core/src/datasource/listing/table.rs
- datafusion/core/src/datasource/memory.rs
- datafusion/core/src/physical_planner.rs
- datafusion/expr/src/logical_plan/builder.rs
- datafusion/expr/src/logical_plan/dml.rs
- datafusion/expr/src/logical_plan/plan.rs
- datafusion/expr/src/logical_plan/tree_node.rs
- datafusion/proto/proto/datafusion.proto
- datafusion/proto/src/generated/pbjson.rs
- datafusion/proto/src/generated/prost.rs
- datafusion/proto/src/logical_plan/mod.rs
- datafusion/sql/src/statement.rs
- Closes #14654.
As discussed in https://github.com/apache/datafusion-ballista/issues/1164 DML statement has table reference instead of table source, which as implication impacts usability in case of ser/de logical plan.  After deserialisation another table lookup need to be performed which impacts usability in case of ballista (where we keep two separate session context and only one of them has table definition)
This PR add table source as well to LogicalPlan:DML to improve usability. 
this PR changes: 
- LogicalPlan:DML
- proto LogicalPlanNode::DML
using existent tests 
proto definition changed
> feat: add resolved `target` to `DmlStatement`  (to eliminate need for table lookup after deserialization)

- datafusion/core/tests/fuzz_cases/pruning.rs
- datafusion/physical-optimizer/src/pruning.rs
- Closes #14053 .
For predicate `col NOT LIKE 'const_prefix%'`, we rewrite it as `(col_min NOT LIKE 'const_prefix%' OR col_max NOT LIKE 'const_prefix%')`. If both `col_min` and `col_max` have the prefix `foo`, we skip the entire row group (as we can be certain that all data in this row group has the prefix `foo`).
Yes
No
> Implement predicate pruning for not like expressions

- datafusion/functions-nested/src/concat.rs
- datafusion/sqllogictest/test_files/array.slt
- Closes #14613 
`array_prepend` would error when attempting to concatenate certain `List` data types due to an incorrect offset type assumption. The error occurs because the implementation eagerly matches by the inner `List` type and hardcodes the corresponding offset type when calling `concat_internal`, potentially mismatching the outer list's offset type.
This commit keeps the offset type used for `concat_internal` consistent with the dynamically provided offset type. 
Yes, see the uncommented SQL statement.
No.
> bug: fix offset type mismatch when prepending lists

- datafusion/physical-optimizer/src/enforce_sorting/mod.rs
- datafusion/physical-optimizer/src/enforce_sorting/replace_with_order_preserving_variants.rs
- datafusion/physical-plan/src/tree_node.rs
- Closes #.
`update_sort_ctx_children` only updates the data field of the context nodes, which tracks whether nodes are connected to a `SortExec`. `update_plan_from_children()` is about updating the actual execution plan structure.
The data field updates in `update_sort_ctx_children` don't actually require any changes to the underlying execution plan.
Therefore, the call to `update_plan_from_children()` in `update_sort_ctx_children` appears unnecessary.
So remove it to avoid confusion.
remove unnecessary `update_plan_from_children` call
> Minor: remove confusing `update_plan_from_children` call from `EnforceSorting`

- datafusion-examples/examples/advanced_parquet_index.rs
- datafusion-examples/examples/parquet_index.rs
- datafusion/core/src/datasource/file_format/arrow.rs
- datafusion/core/src/datasource/file_format/avro.rs
- datafusion/core/src/datasource/file_format/csv.rs
- datafusion/core/src/datasource/file_format/json.rs
- datafusion/core/src/datasource/file_format/parquet.rs
- datafusion/core/src/datasource/physical_plan/avro.rs
- datafusion/core/src/datasource/physical_plan/csv.rs
- datafusion/core/src/datasource/physical_plan/file_scan_config.rs
- datafusion/core/src/datasource/physical_plan/json.rs
- datafusion/core/src/datasource/physical_plan/parquet/mod.rs
- datafusion/core/src/datasource/physical_plan/parquet/source.rs
- datafusion/core/src/datasource/schema_adapter.rs
- datafusion/core/src/test/mod.rs
- datafusion/core/src/test_util/parquet.rs
- datafusion/core/tests/fuzz_cases/pruning.rs
- datafusion/core/tests/parquet/custom_reader.rs
- datafusion/core/tests/parquet/external_access_plan.rs
- datafusion/core/tests/parquet/schema_coercion.rs
- datafusion/core/tests/physical_optimizer/enforce_distribution.rs
- datafusion/core/tests/physical_optimizer/enforce_sorting.rs
- datafusion/core/tests/physical_optimizer/projection_pushdown.rs
- datafusion/core/tests/physical_optimizer/test_utils.rs
- datafusion/proto/src/physical_plan/mod.rs
- datafusion/proto/tests/cases/roundtrip_physical_plan.rs
- datafusion/substrait/src/physical_plan/consumer.rs
- datafusion/substrait/tests/cases/roundtrip_physical_plan.rs
- Follow on to https://github.com/apache/datafusion/pull/14224 from @mertak-synnada  ❤️ 
This was something I noticed while trying to upgrade InfluxDB IOx to use the new APIs introduced in https://github.com/apache/datafusion/pull/14224
I would like to make it easier when someone using these APIs upgrades
1. Rename   new_exec` -> `build`
2. Change it to take `self` rather than force a clone
There are some changes to APIs that are not yet released
> Improve UX Rename `FileScanConfig::new_exec` to `FileScanConfig::build`

- .github/workflows/rust.yml
GitHub runs include this warning
The Ubuntu-20.04 brownout takes place from 2025-02-01.
For more details, see https://github.com/actions/runner-images/issues/11101
`test-datafusion-pyarrow` doesn't work on the latest image, needs to be
fixed separately.
> Update GitHub CI run image for license check job

- datafusion/functions/Cargo.toml
- datafusion/functions/benches/uuid.rs
- datafusion/functions/src/string/uuid.rs
- datafusion/sqllogictest/test_files/functions.slt
N/A
It seems to be faster to generate random u128's in bulk, and then converting them to Uuids.
However, we are not exactly using the same random number generator. `Uuid::new_v4()` is using `getrandom`. In this PR, we are using `rand`.
```
$ cargo bench -p datafusion-functions --bench uuid
uuid                    time:   [19.516 µs 19.541 µs 19.565 µs]
change: [-97.652% -97.648% -97.643%] (p = 0.00 < 0.05)
```
Yes, existing tests. And added a new test for UUIDv4 format.
Yes, faster uuid() UDF.
> Speed up `uuid` UDF (40x faster)

- datafusion/common/src/config.rs
- datafusion/execution/src/task.rs
no related issue.
We allow users to define the custom config by `extensions_options` like
```rust
extensions_options! {
struct TestExtension {
value: usize, default = 42
}
}
```
However, the `Option` type isn't allowed. It's hard to handle the null value case.
This PR allows user to define the field like
```rust
extensions_options! {
struct TestExtension {
value: usize, default = 42
option_value: Option<usize>, default = None
}
}
```
- Implement `ConfigField,` which has been implemented for many data types, within the macro.
add unit test.
New behavior for `extensions_options` macro
> Allow extensions_options to accept Option field

- Cargo.lock
- datafusion/core/Cargo.toml
- datafusion/core/src/lib.rs
> Minor: Re-export `datafusion_expr_common` crate

- datafusion/physical-optimizer/src/enforce_sorting/mod.rs
- datafusion/physical-plan/src/tree_node.rs
- Helps with the docs effort https://github.com/apache/datafusion/issues/7013.
- Noticed while reviewing https://github.com/apache/datafusion/pull/14650, that some of the EnforceSorting docs could be improved.
Only docs. No code.
N/A
N/A
> Improve EnforceSorting docs.

- benchmarks/lineformat.py
- benchmarks/lineprotocol.py
- Closes #6107
a step towards https://github.com/apache/datafusion/issues/5504
addition of python script that converts some `**benchmark**.json` to lineformat
on some files in [`result.zip`](https://github.com/apache/arrow-datafusion/files/12619837/results.zip)
```sh
[nix-shell:~/dev/datafusion/benchmarks]$ python3 lineformat.py ~/Downloads/results/alamb_sort-merge-accounting/sort.json 
benchmark,name=sort,version=28.0.0,datafusion_version=28.0.0,num_cpus=8 query="sort utf8",iteration=0,row_count=10838832,elapsed_ms=85626006 1691105678000000000
benchmark,name=sort,version=28.0.0,datafusion_version=28.0.0,num_cpus=8 query="sort utf8",iteration=1,row_count=10838832,elapsed_ms=68694468 1691105678000000000
benchmark,name=sort,version=28.0.0,datafusion_version=28.0.0,num_cpus=8 query="sort …
```
> script to export benchmark information as Line Protocol format

- datafusion-examples/examples/optimizer_rule.rs
- datafusion/core/tests/fuzz_cases/equivalence/utils.rs
- datafusion/core/tests/physical_optimizer/projection_pushdown.rs
- datafusion/core/tests/user_defined/user_defined_scalar_functions.rs
- datafusion/expr/src/expr_fn.rs
- datafusion/expr/src/udf.rs
- datafusion/optimizer/src/analyzer/type_coercion.rs
- datafusion/optimizer/src/common_subexpr_eliminate.rs
- datafusion/optimizer/src/push_down_filter.rs
- datafusion/physical-expr/src/utils/mod.rs
- datafusion/proto/tests/cases/mod.rs
- datafusion/sql/src/unparser/expr.rs
- datafusion/sql/tests/sql_integration.rs
> Migrate the internal and testing functions to invoke_with_args

- datafusion/catalog/src/table.rs
- datafusion/core/src/datasource/default_table_source.rs
- datafusion/expr/src/table_source.rs
- Part of #7013 
While reviewing https://github.com/apache/datafusion/pull/14631 from @milenkovicm  I noticed / was reminded
that the `TableSource` vs `TableProvider` split is a bit confusing. It would be nice to have some better docs
1. Update docs for `TableSource` and `DefaultTableSource`
By CI and I also reviewed the resulting docs manually
Docs only
> Improve docs `TableSource` and `DefaultTableSource`

- datafusion/expr/src/logical_plan/builder.rs
- datafusion/expr/src/logical_plan/plan.rs
- datafusion/sql/src/set_expr.rs
- datafusion/sql/tests/sql_integration.rs
- datafusion/sqllogictest/test_files/union_by_name.slt
- Closes #14508
UNION [ALL | DISTINCT] BY NAME implementation and associated tests
Yes
Yes, no breaking changes, but new functionality.
> feat: Implement UNION ALL BY NAME

- datafusion/common/src/cast.rs
- datafusion/common/src/lib.rs
- datafusion/functions-aggregate/src/approx_percentile_cont.rs
- datafusion/functions-aggregate/src/bool_and_or.rs
- datafusion/functions-aggregate/src/count.rs
- datafusion/functions-aggregate/src/variance.rs
- When `downcast_value!` errors out, include actual type in the error message, beside the expected.
-  Also improve macro hygiene of that macro by not requiring callers to import `DataFusionError` themselves 
- add (optional) backtraces by using proper constructor macro for the `DataFusionError`
> Improve  `downcast_value!` macro

- datafusion/physical-plan/Cargo.toml
- datafusion/physical-plan/benches/partial_ordering.rs
- datafusion/physical-plan/src/aggregates/order/partial.rs
- Closes #14565.
Faster is better?
Yes, added a new test.
No.
(The input_schema argument of GroupOrderingPartial::try_new is no longer used and can be removed, this is not included in this PR)
> perf: Drop RowConverter from GroupOrderingPartial

- datafusion/functions/Cargo.toml
- datafusion/functions/benches/to_hex.rs
- datafusion/functions/src/string/to_hex.rs
N/A
We can speedup `to_hex` by writing string values directly to the string array, instead of making temporary allocations.
```
to_hex i32 array: 1024  time:   [14.239 µs 14.295 µs 14.354 µs]
change: [-48.522% -48.285% -48.031%] (p = 0.00 < 0.05)
Found 4 outliers among 100 measurements (4.00%)
to_hex i64 array: 1024  time:   [15.471 µs 15.546 µs 15.624 µs]
change: [-46.390% -46.208% -46.007%] (p = 0.00 < 0.05)
Found 2 outliers among 100 measurements (2.00%)
```
- Add a benchmark
- Avoid string allocations
Relying on existing tests.
Faster execution.
> Speedup `to_hex` (~2x faster)

- datafusion/common/src/dfschema.rs
- datafusion/core/src/datasource/listing/table.rs
- datafusion/core/src/datasource/memory.rs
- datafusion/core/tests/dataframe/mod.rs
- datafusion/sqllogictest/test_files/aggregate_skip_partial.slt
- datafusion/sqllogictest/test_files/insert.slt
- datafusion/sqllogictest/test_files/insert_to_external.slt
Describe the bug
In, https://github.com/apache/datafusion/issues/14394, it was reported that while attempting to implement a DataSink different schemas for the record batches were being given than per the RecordBatchStream.
A fix for the given example, an INSERT INTO ... VALUES query, was merged (https://github.com/apache/datafusion/pull/14472). However, this issue likely arises when the schema of the source of an INSERT statement contain fields that differ from the table schema in terms of nullability. That is, the problem is not just limited to INSERT INTO ... VALUES statements.
- Closes [#14550](https://github.com/apache/datafusion/issues/14550)
Add a separate nullable checking besides the original checking which only include the name and datatype.
Improve the error message to …
> bug: improve schema checking for `insert into` cases

- datafusion/core/src/dataframe/mod.rs
- datafusion/core/tests/dataframe/mod.rs
- datafusion/expr/src/logical_plan/builder.rs
Related to https://github.com/apache/datafusion/issues/14563 (probably more prs to come)
Now, when normalizing the column, we always generate `plan.using_columns()` which is recursive and very expensive - and [may not be needed](https://github.com/apache/datafusion/blob/980931c5a70b8b08c918195803145f64f1ec901f/datafusion/common/src/column.rs#L224) if column is already normalized 
Exit early if column already has a relation set. Also, set the relation when `with_column_renamed` is called
Extended a test to assert references
No
> Early exit on column normalisation to improve DataFrame performance

- datafusion/functions/src/string/repeat.rs
- Closes #14610.
By calculating the length in advance and allocating memory accordingly, the repeat function achieves improved performance to a certain degree.
The following are the local test results:
```txt
repeat 3 times/repeat_string_view [size=1024, repeat_times=3]
time:   [40.286 µs 40.438 µs 40.607 µs]
change: [-0.1541% +0.4780% +1.0910%] (p = 0.17 > 0.05)
No change in performance detected.
repeat 3 times/repeat_string [size=1024, repeat_times=3]
time:   [38.556 µs 38.744 µs 38.944 µs]
change: [-10.201% -8.3456% -6.4266%] (p = 0.00 < 0.05)
repeat 3 times/repeat_large_string [size=1024, repeat_times=3]
time:   [30.212 µs 30.365 µs 30.523 µs]
change: [-3.3156% -2.5561% -1.7929%] (p = 0.00 < 0.05)
repeat 30 times/repeat_string_view …
```
> optimize performance of the repeat function (up to 50% faster)

- datafusion-examples/examples/expr_api.rs
- Part of #3929 (see the recent followup discussion).
The goal of this change is to add an example to explain data flow during boundary analysis this is mostly to help us get a better intuition for how we should proceed next for #4158 and #4159.
In `datafusion-examples/examples/expr_api.rs` there is now a new function that explains data flow during boundary analysis and selectivity calculation. To allow contributors to better understand the implementation as it exists, documented in the design doc of #3929, I used the same demonstrating example.
The change re-uses parts of the API that is already covered by existing tests.
Yes, this introduces a new example.
> Add an example of boundary analysis simple expressions.

- datafusion/substrait/src/logical_plan/producer.rs
None
the DefaultSubstraitProducer should be available for datafusion_substrait users
make DefaultSubstraitProducer public
no behavior changes, it just makes a struct `pub`
---
Not sure why this was not public on the first place, if I'm missing some context please let me know
> make DefaultSubstraitProducer public

- datafusion/functions/src/encoding/inner.rs
> chore: Migrate Encoding functions to invoke_with_args

- Cargo.lock
- Cargo.toml
- datafusion/sqllogictest/test_files/decimal.slt
Upgrade to arrow-rs bug fix release.
- fixes https://github.com/apache/datafusion/issues/14450
- replaces closes https://github.com/apache/datafusion/pull/14716
> Fix off by 1 in decimal cast to lower precision

- datafusion/functions/benches/concat.rs
- datafusion/functions/benches/lower.rs
- datafusion/functions/benches/ltrim.rs
- datafusion/functions/benches/repeat.rs
- datafusion/functions/benches/to_hex.rs
- datafusion/functions/benches/upper.rs
- datafusion/functions/benches/uuid.rs
- datafusion/functions/src/string/ascii.rs
- datafusion/functions/src/string/bit_length.rs
- datafusion/functions/src/string/btrim.rs
- datafusion/functions/src/string/chr.rs
- datafusion/functions/src/string/concat.rs
- datafusion/functions/src/string/concat_ws.rs
- datafusion/functions/src/string/contains.rs
- datafusion/functions/src/string/ends_with.rs
- datafusion/functions/src/string/levenshtein.rs
- datafusion/functions/src/string/lower.rs
- datafusion/functions/src/string/ltrim.rs
- datafusion/functions/src/string/octet_length.rs
- datafusion/functions/src/string/overlay.rs
- datafusion/functions/src/string/repeat.rs
- datafusion/functions/src/string/replace.rs
- datafusion/functions/src/string/rtrim.rs
- datafusion/functions/src/string/split_part.rs
- datafusion/functions/src/string/starts_with.rs
- datafusion/functions/src/string/to_hex.rs
- datafusion/functions/src/string/upper.rs
- datafusion/functions/src/string/uuid.rs
- Closes #14708.
Deprecate and remove `invoke_batch` in string functions and migrate to providing `invoke_with_args`.
Yes.
None.
> migrate string functions to `inovke_with_args`

- datafusion/functions-nested/src/array_has.rs
- datafusion/functions-nested/src/cardinality.rs
- datafusion/functions-nested/src/concat.rs
- datafusion/functions-nested/src/dimension.rs
- datafusion/functions-nested/src/distance.rs
- datafusion/functions-nested/src/empty.rs
- datafusion/functions-nested/src/except.rs
- datafusion/functions-nested/src/extract.rs
- datafusion/functions-nested/src/flatten.rs
- datafusion/functions-nested/src/length.rs
- datafusion/functions-nested/src/make_array.rs
- datafusion/functions-nested/src/map.rs
- datafusion/functions-nested/src/map_extract.rs
- datafusion/functions-nested/src/map_keys.rs
- datafusion/functions-nested/src/map_values.rs
- datafusion/functions-nested/src/position.rs
- datafusion/functions-nested/src/range.rs
- datafusion/functions-nested/src/remove.rs
- datafusion/functions-nested/src/repeat.rs
- datafusion/functions-nested/src/replace.rs
- datafusion/functions-nested/src/resize.rs
- datafusion/functions-nested/src/reverse.rs
- datafusion/functions-nested/src/set_ops.rs
- datafusion/functions-nested/src/sort.rs
- datafusion/functions-nested/src/string.rs
> chore: Migrate Array Functions to invoke_with_args

- datafusion/functions/src/regex/regexpcount.rs
- datafusion/functions/src/regex/regexplike.rs
- datafusion/functions/src/regex/regexpmatch.rs
- datafusion/functions/src/regex/regexpreplace.rs
> chore: Migrate Regex function to invoke_with_args

- datafusion/core/tests/fuzz_cases/sort_fuzz.rs
- datafusion/core/tests/memory_limit/mod.rs
- datafusion/physical-plan/src/sorts/cursor.rs
- datafusion/physical-plan/src/sorts/sort.rs
- datafusion/physical-plan/src/sorts/stream.rs
- datafusion/physical-plan/src/sorts/streaming_merge.rs
- datafusion/physical-plan/src/spill.rs
- datafusion/physical-plan/src/test.rs
- Hopefully it closes #10073, but it is still an incomplete solution.
I had a hard time making DataFusion Comet work on cloud instances with 4GB memory per CPU core, partially because DataFusion is very likely to allocates more memory than reserved and run into OOM, or run into various kinds of memory reservation failures. In cases when the partition to process is larger than available memory, we expect spilling to happen to run the query to completion, but got tons of failures instead. We found operators involving SortExec such as sort-merge join triggers the aforementioned problems frequently.
#10073 reports that SortExec may allocate 2X memory than it reserves (see "the second problem" in the issue), and we found that it contributed to most of the OOM cases we encountered when using …
> bug: Fix memory reservation and allocation problems for SortExec

- datafusion/functions/Cargo.toml
- datafusion/functions/benches/chr.rs
- datafusion/functions/src/string/chr.rs
N/A
It is wasteful to allocate temporary memory with intermediate `to_string` calls.
```
chr                     time:   [3.7600 µs 3.7730 µs 3.7892 µs]
change: [-74.908% -74.553% -74.265%] (p = 0.00 < 0.05)
Found 12 outliers among 100 measurements (12.00%)
2 (2.00%) low mild
8 (8.00%) high severe
```
- Add a bench for `chr`
- Avoid intermediate String allocations by encoding directly to the string array
Relying on existing tests
Faster execution
> Speed up `chr` UDF (~4x faster)

- datafusion/core/tests/expr_api/simplification.rs
- datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs
- datafusion/sqllogictest/test_files/subquery.slt
Not sure why they are not supported. It seems that if we're not careful, some transformations can introduce aliases nested inside other expressions.
Didn't create an issue, because it's more of an internal change and mostly relevant when using DataFusion as a library.
Having `Expr::Alias` as part of the expression AST is a trade-off. It makes the AST uniform and simpler but it allows representing trees that are not really valid SQL such as having aliases nested in function arguments and generally makes them legal in any position of the AST. Therefore I think it would be a desirable property if all transformations can handle aliases wherever they appear.
Simply changing the `can_evaluate` predicate is enough, alias expressions can already be evaluated.
Yes, added a unit test and a couple …
> Support aliases in ConstEvaluator

- datafusion/functions/src/crypto/digest.rs
- datafusion/functions/src/crypto/md5.rs
- datafusion/functions/src/crypto/sha224.rs
- datafusion/functions/src/crypto/sha256.rs
- datafusion/functions/src/crypto/sha384.rs
- datafusion/functions/src/crypto/sha512.rs
> chore: migrate crypto functions to invoke_with_args

- datafusion/physical-optimizer/src/enforce_sorting/mod.rs
- Closes #.
This is a follow-up on #14650. @xudong963 had shown that rather than a change in the plan structure, the only change is possible in node payloads. So, `update_sort_ctx_children()` is no longer updating plans. Considering these, the new calls at update_plan_from_children() seem also redundant to me.
Remove redundant update_plan_from_children() calls in enforce sorting where we know that the plan in the node is consistent with PlanContext children.
> Minor: Further Clean-up in Enforce Sorting

- .github/dependabot.yml
None.
It would be nice if minor/patch bumps of `arrow*` and `parquet` are grouped. In addition major parquet bumps should be ignored too, because they are grouped in the manual major bump of arrow crates.
I removed the limit because sometimes dependabot PRs can't be merged directly, and these open PRs shouldn't block other updates to the `Cargo.lock` file (to make sure we're testing with updated dependencies in CI).
Updates to the dependabot config.
No.
> dependabot: group arrow/parquet minor/patch bumps, remove limit

- datafusion/substrait/Cargo.toml
- datafusion/substrait/src/serializer.rs
- datafusion/substrait/tests/cases/serialize.rs
- Closes #9727 
It's reasonable to always truncate an existing file before serializing a plan. 
On the other hand, the following `deserialize` method always read the file to end which does not consider the case that the file is not truncated before serialization.
Applied a clippy suggestion by adding a `truncate(true)`.
Tested by clippy
No
> fix: Substrait serializer clippy error: not calling truncate

- datafusion/functions-nested/src/planner.rs
- datafusion/functions/src/core/getfield.rs
- datafusion/sqllogictest/test_files/map.slt
- Closes #11785 
- relates to https://github.com/apache/datafusion/issues/14552
> Map access supports constant-resolvable expressions

- .github/workflows/rust.yml
Solves #14776 
CI job `test-datafusion-pyarrow` pins to ubuntu-20.04. This MR changes it back to ubuntu-latest and fix the failing CI
> Fix CI job test-datafusion-pyarrow

- datafusion/execution/src/memory_pool/mod.rs
This is not related to an issue. It is requested by this comment: https://github.com/apache/datafusion/pull/14644#issuecomment-2665613858
There's a convention that ExecutionPlans do not reserve memory for the batches it produces, but it is not explicitly stated in the doc. We should explicitly point out those conventions in the doc to make it clear.
This change clarifies the general conventions that ExecutionPlans need to follow when using MemoryPool: memory for output batches are reserved by their consumers rather than their producers.
N/A for doc changes.
No
> docs: Add additional info about memory reservation to the doc of MemoryPool

- .github/workflows/extended.yml
- datafusion/core/tests/memory_limit/memory_limit_validation/sort_mem_validation.rs
- Closes https://github.com/apache/datafusion/issues/14680
CI for extended tests are failing because there is not enough disk space for CI runners, test binaries take lots of disk space.
This PR frees up more disk space on CI runner (12GB -> 45GB). 
Before, after setting up Rust dependencies, there is only 12GB disk space left to run the tests, I think this can run into trouble if we want extended tests to do more stuff in the future.
1. CI change
- Directly running test on Github CI runner, instead of Docker container, and manually setup Rust dependencies.
- Applied Github Action https://github.com/jlumbroso/free-disk-space to delete unnecessary files on CI runner.
2. Test change
Memory validation test causes recompilations (I didn't find a direct fix 🤦🏼 ), and it caused large disk space …
> Fix CI fail for extended test (by freeing up more disk space in CI runner)

- datafusion/execution/src/disk_manager.rs
Before the change, executing the test would create (and leave behind) the `datafusion/execution/DOESNT_EXIST` folder inside source repository.
> chore: Fix test not to litter in repository

- datafusion/core/tests/execution/logical_plan.rs
- datafusion/execution/src/runtime_env.rs
- datafusion/physical-expr-common/src/binary_map.rs
- datafusion/sql/src/expr/value.rs
- test-utils/src/array_gen/string.rs
- related to #1557 
Rust 1.85 was released.
Clippy 1.85 warning fixes.
In CI.
No.
> Fix Clippy 1.85 warnings

- datafusion/core/src/datasource/data_source.rs
- datafusion/core/src/datasource/physical_plan/arrow_file.rs
- datafusion/core/src/datasource/physical_plan/avro.rs
- datafusion/core/src/datasource/physical_plan/csv.rs
- datafusion/core/src/datasource/physical_plan/file_scan_config.rs
- datafusion/core/src/datasource/physical_plan/json.rs
- datafusion/core/src/datasource/physical_plan/parquet/source.rs
- Closes #14607. 
I also want to suggest some changes around `FileGroupPartitioner`/`PartitionedFile` but I need to do some more thinking there and this change is useful without them IMO.
Allows specific file formats to define their own file repartitioning.
Move the logic in `FileScanConfig::repartitioned` down to the `FileSource` trait as the default interface, allowing external `FileSource` implementation to control their repartitioning logic.
Introduces a new function with a default implementation to a trait.
> Allow `FileSource`-specific repartitioning

- Cargo.toml
- datafusion/common/src/table_reference.rs
- datafusion/expr/src/utils.rs
- datafusion/physical-expr-common/src/sort_expr.rs
- datafusion/physical-expr/src/equivalence/properties.rs
- rust-toolchain.toml
- Closes #14808.
Rust `1.85.0` is now the latest stable release.
- Bumps the MSRV to `1.82.0`
- Bumps the version in `rust-toolchain.toml` to `1.85.0`
CI.
Yes, MSRV bump.
> Bump MSRV to 1.82, toolchain to 1.85

- datafusion/ffi/src/execution_plan.rs
- datafusion/ffi/src/insert_op.rs
- datafusion/ffi/src/table_source.rs
- datafusion/ffi/src/volatility.rs
None
Improve code coverage
Adds unit tests, no functional code changes.
The two images below were generated before and after these unit tests were included.  Generated using:
```shell
cargo tarpaulin --package datafusion-ffi --tests --features integration-tests --out Html
```
None
> Chore/Add additional FFI unit tests

- .github/workflows/extended.yml
- Cargo.lock
- Cargo.toml
- datafusion/physical-optimizer/Cargo.toml
- datafusion/wasmtest/Cargo.toml
Found by `cargo udeps`. Unfortunately there were false positives too (https://github.com/apache/datafusion/issues/9881#issuecomment-2676375161).
> Remove unused crate dependencies

- docs/source/contributor-guide/development_environment.md
- docs/source/contributor-guide/index.md
- Closes https://github.com/apache/datafusion/issues/14681
Add better instruction for new-comers to build the project.
I manually verified the build steps work on my end.
> docs: Add instruction to build

- datafusion/sql/src/unparser/expr.rs
No issue raised, just something we've seen in production
Ensures we can convert dictionary & interval types to ast datatypes
Adds a small change to support dictionaries
I am actually not too sure how best to test this, might need a bit of guidance here if we wanna add a test
No
> Add support for `Dictionary` to AST datatype in unparser

- benchmarks/README.md
- Closes #14819.
I added a new benchmark in #14818. There wasn't documentation on how to add a new benchmark (and some of the existing docs were wrong) so I wrote up what I did as I figured it out. I guessed a lot, so please correct me!
New and improved docs!
No, but I'd love to have someone try following the new docs to test if they're clear and helpful!
Nope!
> Improve benchmark docs

- datafusion/functions-table/src/generate_series.rs
- datafusion/functions-table/src/lib.rs
- datafusion/sqllogictest/test_files/table_functions.slt
Part of https://github.com/apache/datafusion/issues/10177. It does not close it, as there is no support for timestamp arguments.
`generate_series` currently exists as a table function, so it would be natural to also support `range`.
- Parametize enough of the existing implementation of `generate_series` such that it can be used to implement `range`.
Yes, copied the existing slt tests for `generate_series` (modulo where/join/order by variations). 
Support for queries like
```sql
SELECT * FROM range(1,10);
```
> Add `range` table function

- datafusion/functions/src/unicode/character_length.rs
- datafusion/functions/src/unicode/initcap.rs
- datafusion/functions/src/unicode/left.rs
- datafusion/functions/src/unicode/lpad.rs
- datafusion/functions/src/unicode/reverse.rs
- datafusion/functions/src/unicode/right.rs
- datafusion/functions/src/unicode/rpad.rs
- datafusion/functions/src/unicode/strpos.rs
- datafusion/functions/src/unicode/substr.rs
- datafusion/functions/src/unicode/substrindex.rs
- datafusion/functions/src/unicode/translate.rs
- Closes #14709 
Yes, I've run all the test cases under the `/functions/src/unicode`
> chore: migrate invoke_batch to invoke_with_args for unicode function

- datafusion/functions/src/utils.rs
N/A
Needed for so I can return `internal_err` in:
- #14841
https://github.com/apache/datafusion/pull/14841#discussion_r1966963244
Changed `test_function` macro to use `return_type_from_args` and not `return_type`
existing tests
Nope
> test: change test_function macro to use `return_type_from_args` instead of `return_type`

- datafusion/physical-plan/src/windows/bounded_window_agg_exec.rs
- Closes #.
Now window operator did not calculate `elapsed_compute` metric, this change includes counting compute time during execution.
Add `elapsed_compute` counting within `BoundedWindowAggExec`
I tested manually in datafusion-cli:
Before `elapsed_compute` metric in `BoundedWIndowAggExec` is several nanoseconds, after the change, the result is:
```
DataFusion CLI v45.0.0
> explain analyze SELECT
t1.v1 AS series,
ROW_NUMBER() OVER (ORDER BY t1.v1) AS row_num,
SUM(t1.v1) OVER (ORDER BY t1.v1 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS cumulative_sum
FROM generate_series(1, 10000000) AS t1(v1);
+-------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------ …
```
> Minor: Counting elapsed_compute in BoundedWindowAggExec

- datafusion/functions/Cargo.toml
- datafusion/functions/benches/gcd.rs
- datafusion/functions/src/math/gcd.rs
- datafusion/sqllogictest/test_files/math.slt
- Closes #.
`make_scalar_function` convert scalar to array and call function kernel. However, we don't need to convert to array and can directly compute on it. This improve the gcd performance in array vs scalar case
> Optimize `gcd` for array and scalar case by avoiding `make_scalar_function` where has unnecessary conversion between scalar and array

- datafusion/functions/src/math/monotonicity.rs
- Closes #11687 .
LazyLock is more ergonomic than OnceLock.
Replaces all OnceLock in monoticity.rs in `datafusion-functions` with their LazyLock equivalents.
No
> refactor: replace OnceLock with LazyLock

- datafusion/core/src/dataframe/mod.rs
- datafusion/expr/src/logical_plan/builder.rs
- datafusion/expr/src/logical_plan/mod.rs
- datafusion/sql/src/select.rs
- datafusion/substrait/tests/cases/logical_plans.rs
- datafusion/substrait/tests/cases/roundtrip_logical_plan.rs
- datafusion/substrait/tests/testdata/test_plans/multilayer_aggregate.substrait.json
Closes #14348 
Substrait plans are intended to be interpreted literally. When you see plan nodes like:
```
"project": {
"common": {
"emit": {
"outputMapping": [0, 3]
}
},
...
}
```
The output mapping (e.g. `[0, 3]`) contains ordinals representing the offset of the target expression(s) within the [input, output] list. If the DataFusion LogicalPlanBuilder is introducing additional input expressions, this violates the plan's intent and will produce the incorrect output mappings. Please see the issue for a concrete example.
* Introduce new `add_implicit_group_by_exprs` option to the logical plan builder. It is disabled by default.
* The option is enabled _only_ in the DataFrame and SQL paths.
Added a multilayer aggregation Substrait example. The first aggregation produces a unique column with …
> fix(substrait): Do not add implicit groupBy expressions in `LogicalPlanBuilder` or when building logical plans from Substrait

- datafusion/sqllogictest/README.md
- datafusion/sqllogictest/regenerate/sqllogictests.rs
- datafusion/sqllogictest/regenerate/src/engines/datafusion_engine/runner.rs
- datafusion/sqllogictest/regenerate/src/engines/postgres_engine/mod.rs
- datafusion/sqllogictest/regenerate_sqlite_files.sh
- Part of https://github.com/apache/datafusion/pull/14824
The regeneration logic uses a fork of the sqllogictest runner. However, the runner has been updated on `main` and the fork hasn't been updated. 
This means we can't update the sqllogictest tests anymore , and we hit this when working with @jayzhan211 on https://github.com/apache/datafusion/pull/14824#issuecomment-2682233579
1. Add two other files that need the old version
2. Update the updates for changes on main
3. Also add a note in the docs about the `regenerate_sqlite_files.sh` script
I tested them manually
No, this is a development only change
However, I think we need to come up with a more maintainable solution for maintaining these files
I'll file a ticket describing that need later
> Fix `regenerate_sqlite_files.sh` due to changes in sqllogictests

- datafusion/expr/src/lib.rs
- datafusion/functions/src/string/btrim.rs
- datafusion/functions/src/string/ltrim.rs
- datafusion/functions/src/string/rtrim.rs
- datafusion/sqllogictest/test_files/string/string_view.slt
> replace TypeSignature::String with TypeSignature::Coercible for trim functions

- datafusion/sql/src/expr/function.rs
- datafusion/sql/tests/cases/diagnostic.rs
- Closes  #14430 
well explained in the issue.
This PR attaches `Diagnostic` with the "function x does not exist" error.
Get the span of function from sql-parser, then attach to Diagnostic after transformation.
yes, unit test was added.
> chore: Attach Diagnostic to "function x does not exist" error

- datafusion/sql/src/planner.rs
- Closes #13700.
Previously, the `SqlToRel::new` method uses a default `ParserOptions`.
Now, its parser options derive the `SqlParserOptions` from the context provider.
Yes, covered by existing test cases.
Previously, users need to set the parser options once when creating a session config, and again when creating a `SqlToRel`.
Now, users can set the parser options only once when creating a session config, and expect each `SqlToRel`'s created by `SqlToRel::new` derives the parser options in the session config.
> refactor: make SqlToRel::new derive the parser options from the context provider

- docs/source/index.rst
I found the that the setting up development environment page wasn't linked in the table of contents
running `cd docs && ./build.sh` also shows an error
```
reading sources... [100%] user-guide/sql/write_options
/Users/andrewlamb/Software/datafusion/docs/temp/index.rst:138: WARNING: toctree contains reference to nonexisting document 'contributor-guide/getting_started'
looking for now-outdated files... none found
pickling environment... done
checking consistency... /Users/andrewlamb/Software/datafusion/docs/temp/contributor-guide/development_environment.md: WARNING: document isn't included in any toctree
```
I think this may have been introduced in https://github.com/apache/datafusion/pull/14694
Fix the index:
I tested them lcal
> Minor: Add Development Environment to Documentation Index

- Cargo.toml
- Closes #13816.
Minimizing the DF binary size from 60M to 50M by stripping debuginfo.
Removing unwind panic saves 10 more MB
The stripped binary has the biggest methods for std panic
> chore: Strip debuginfo symbols for release

- Cargo.lock
- benchmarks/Cargo.toml
- benchmarks/bench.sh
- benchmarks/src/bin/dfbench.rs
- benchmarks/src/cancellation.rs
- benchmarks/src/lib.rs
- Connects to #14036 (does not close it).
The behavior observed in #14036 was hard to reproduce and quantify; having a benchmark makes that easier!
This benchmark loads multiple files into an in-memory object store, starts a datafusion query in a new tokio runtime, lets the query run for an amount of time, cancels the query, and measures how long it takes to drop the tokio runtime.
This demonstrates datafusion is likely not yielding often enough to allow for timely query cancellation and freeing up of all resources.
This PR is only tests :)
Nope!
> Cancellation benchmark

- datafusion/datasource/src/file_scan_config.rs
Part of
- Related to https://github.com/delta-io/delta-rs/pull/3261
- Related to https://github.com/apache/datafusion/issues/14123
- Follow on to https://github.com/apache/datafusion/pull/14224
- Related to https://github.com/apache/datafusion/pull/14882
When working on upgrading delta-rs to use the new DataSourceExec I was super confused that the source printed out like this
```
object_store_url=...
```
Without the struct name 🤯 
Add the struct name
> Include struct name on FileScanConfig debug impl

- datafusion/optimizer/src/simplify_expressions/simplify_exprs.rs
Whenever we use `recompute_schema` or `with_exprs_and_inputs`, this ensures that we obtain the same schema.
Followup to #14734
In #14734 we introduced more aggressive constant folding which applies also to aliases. That lead to the discovery that `SimplifyExpressions` doesn't preserve the name of grouping sets which are relevant for the computed schema. Note that this could be an issue also before #14734 because the grouping set might have no alias and then if the expression were changed by constant folding, it would still affect the result schema.
In `SimplifyExpressions` we check for grouping sets and then map over their children with the `NamePreserver`.
Otherwise, same as before.
Added a unit test.
No user facing changes, the schema of grouping sets should be more stable after …
> Preserve the name of grouping sets in SimplifyExpressions

- datafusion/expr-common/src/type_coercion/binary.rs
- datafusion/functions/src/string/starts_with.rs
- datafusion/sqllogictest/test_files/string/string_view.slt
> replace TypeSignature::String with TypeSignature::Coercible for starts_with

- datafusion/physical-plan/src/joins/hash_join.rs
- datafusion/physical-plan/src/joins/stream_join_utils.rs
- datafusion/physical-plan/src/joins/utils.rs
- Continues https://github.com/apache/datafusion/issues/13433 the quest of @crepererum
Use some more HashTable, so we can upgrade (and benefit from further improvements).
I tested the benchmarks, I get no regressions (makes sense, as it is using similar APIs).
> Move HashJoin from `RawTable` to `HashTable`

- datafusion-examples/examples/parquet_exec_visitor.rs
- datafusion/core/src/datasource/physical_plan/arrow_file.rs
- datafusion/core/src/datasource/physical_plan/csv.rs
- datafusion/core/src/datasource/physical_plan/json.rs
- datafusion/core/src/datasource/physical_plan/parquet/mod.rs
- datafusion/core/src/datasource/physical_plan/parquet/source.rs
- datafusion/core/src/test/mod.rs
- datafusion/core/src/test_util/parquet.rs
- datafusion/core/tests/parquet/file_statistics.rs
- datafusion/core/tests/parquet/utils.rs
- datafusion/core/tests/physical_optimizer/projection_pushdown.rs
- datafusion/core/tests/sql/path_partition.rs
- datafusion/datasource/src/file_scan_config.rs
- datafusion/datasource/src/memory.rs
- datafusion/datasource/src/source.rs
- datafusion/proto/src/physical_plan/from_proto.rs
- datafusion/proto/src/physical_plan/mod.rs
- datafusion/proto/tests/cases/roundtrip_physical_plan.rs
- datafusion/substrait/src/physical_plan/producer.rs
- Related to https://github.com/delta-io/delta-rs/pull/3261
- Related to https://github.com/apache/datafusion/issues/14123
- Follow on to https://github.com/apache/datafusion/pull/14224
While working on upgrading DataFusion 46 in several projects, I found the name `source` super confusing as there are two similarly named traits,  `FileSource` and `DataSource` but several functions / fields are named just `source` so it is not clear which they refer to 
This was especially confusing as `DataSourceExec` has a `DataSource` which is a `FileScanConfig` not the `FileSOurce` (which is a``ParquetSource` 🤯 
1. rename the fields and accessors to be explicitly `data_source` or `file_source` to avoid the confusion
The documentation on how all these traits are related to each other is somewhat sparse. …
> Rename `DataSource` and `FileSource` fields for consistency

- datafusion/functions/src/datetime/to_char.rs
- datafusion/sqllogictest/test_files/timestamps.slt
- Closes #14884.
Currently, when passing a NULL value to to_char, it returns an empty string instead of NULL. [This behavior differs from PostgreSQL, Spark, DuckDb](https://github.com/apache/datafusion/issues/14884#issuecomment-2686313231), which returns NULL when given a NULL input. Aligning with common practise ensures consistency and expected behavior for users relying on SQL standards.
Modify to_char function implementation to return NULL when the input is NULL.
Update relevant test cases to validate the correct behavior.
Ensure consistent behavior across different data types.
Yes, test cases have been added to check the NULL behavior of to_char.
Existing test cases have been updated where necessary.
Verified that the changes do not introduce regressions.
Users who previously received …
> Fix the null handling for to_char function

- datafusion/core/tests/physical_optimizer/enforce_distribution.rs
- datafusion/core/tests/physical_optimizer/enforce_sorting.rs
- datafusion/core/tests/physical_optimizer/sanity_checker.rs
- datafusion/core/tests/physical_optimizer/test_utils.rs
- Demonstrates bug found for https://github.com/apache/datafusion/issues/14691
Demonstrate the bug.
Afterwards we can continue the process of figuring out the proper fix.
Adds a single test case, and associated methods.
Yes
No
> Add tests for Demonstrate EnforceSorting can remove a needed coalesce

- datafusion-cli/src/print_options.rs
- datafusion-cli/tests/cli_integration.rs
- closes #14920
When we only have one batch and size < max_rows, also size < preview limit, we should collect it at the end.
When we only have one batch and size < max_rows, also size < preview limit, we should collect it at the end.
Add the collect logic at the end.
Yes
Testing result
```rust
> select * from a;
Error during planning: table 'datafusion.public.a' not found
> CREATE EXTERNAL TABLE IF NOT EXISTS lineitem (
l_orderkey BIGINT,
l_partkey BIGINT,
l_suppkey BIGINT,
l_linenumber INTEGER,
l_quantity DECIMAL(15, 2),
l_extendedprice DECIMAL(15, 2),
l_discount DECIMAL(15, 2),
l_tax DECIMAL(15, 2),
l_returnflag VARCHAR,
l_linestatus VARCHAR,
l_shipdate DATE,
l_commitdate DATE,
l_receiptdate DATE,
l_shipinstruct VARCHAR,
l_shipmode VARCHAR,
l_comment VARCHAR
) STORED AS parquet
LOCATION …
```
> Fix: New Datafusion-cli streaming printing way should handle corner case for only one small batch which lines are less than max_rows

- datafusion/physical-optimizer/src/enforce_sorting/mod.rs
- related to https://github.com/apache/datafusion/issues/14691
The [initial PR](https://github.com/apache/datafusion/pull/14637) to fix the above issue, also did a refactor and added docs. 
I'm breaking up the initial PR, and this is only ~the refactor~ the docs portion.
~Refactor and add docs to more tightly define `update_coalesce_ctx_children`. Afterwards, I could remove a few of the conditionals in the other helper methods, since it's now handled with the proper and full labeling of the coalesce context (of which coalesce to remove).~
Only docs.
N/A
No
> Add docs to `update_coalesce_ctx_children`.

- benchmarks/README.md
- benchmarks/bench.sh
- benchmarks/src/h2o.rs
- [Closes #14867](https://github.com/apache/datafusion/issues/14867)
We have supported group by in
https://github.com/apache/datafusion/issues/7209
PR:
https://github.com/apache/datafusion/pull/13996
This ticket we will support join for H2O.ai Database-like Ops benchmark to dfbench
The upstream just merged the join data generation:
https://github.com/mrpowers-io/falsa/pull/24
Add join support 
yes
Add new join support, we need add a follow-up to change the doc also
> Add H2O.ai Database-like Ops benchmark to dfbench (join support)

- datafusion/physical-plan/src/common.rs
- datafusion/physical-plan/src/joins/sort_merge_join.rs
- datafusion/physical-plan/src/sorts/sort.rs
- datafusion/physical-plan/src/spill.rs
- Closes #4658
The IPC Stream format allows for dictionary replacement, unlike the IPC File format. As per https://github.com/apache/datafusion/issues/4658#issuecomment-2679417596 the File format does not offer advantages for the spill use case.
Replaced the functionality in spilled sorts to write the IPC Stream format, instead of the IPC File format.
Covered by existing tests of spill, I adapted these where necessary.
The code change is internal only; if for some reason users were inspecting the contents of spilled files without using the datafusion APIs to read them, they will find the format has changed.
> Use arrow IPC Stream format for spill files

- datafusion/core/tests/physical_optimizer/enforce_distribution.rs
- datafusion/core/tests/physical_optimizer/enforce_sorting.rs
- datafusion/core/tests/physical_optimizer/sanity_checker.rs
- datafusion/core/tests/physical_optimizer/test_utils.rs
Revert "test(14691): demonstrate EnforceSorting can remove a needed coalesce (#14919)"
This reverts commit 32224b48ca5f779ed2833f480f69af51c6637408.
Justification can be seen here: https://github.com/apache/datafusion/pull/14919#discussion_r1976065383
> Remove invalid bug reproducer.

- datafusion/core/src/datasource/listing/table.rs
- datafusion/core/src/lib.rs
- datafusion/datasource/src/file.rs
- datafusion/datasource/src/source.rs
- Follow up to https://github.com/apache/datafusion/pull/14224
https://github.com/apache/datafusion/pull/14224 introduced a fairly substantial change to how datasource code was implemented. To assist the upgrade I think it would be nice to document the new design in code / doc comments
1. Update and expand doc comments
By Docs CI and I built the docs locally and looked at them
There are no functional changes
> Improve documentation for `DataSourceExec`, `FileScanConfig`, `DataSource` etc

- datafusion/core/tests/physical_optimizer/projection_pushdown.rs
- datafusion/datasource/src/file_scan_config.rs
- Related to https://github.com/delta-io/delta-rs/pull/3261#issuecomment-2691373678
- Fixes https://github.com/apache/datafusion/issues/14957
I feel like there should be a way to apply swapping even if the file is partitioned - but submitting a hotfix since it's a release blocker
Added a test
No
> Do not swap with projection when file is partitioned

- datafusion/core/tests/physical_optimizer/projection_pushdown.rs
- datafusion/datasource/src/file_scan_config.rs
- Part of https://github.com/apache/datafusion/issues/14123
- Backports https://github.com/apache/datafusion/pull/14956
Let's include https://github.com/apache/datafusion/pull/14956 in `branch-46`
> [branch-46] Do not swap with projection when file is partitioned (#14956)

- datafusion/core/src/datasource/listing/table.rs
- datafusion/core/src/lib.rs
- datafusion/datasource/src/file.rs
- datafusion/datasource/src/source.rs
- Part of https://github.com/apache/datafusion/issues/14123
- Backports https://github.com/apache/datafusion/pull/14941
I would like to try and make the transition to DataSourceExec as easy as possible, and part of that is better documentation
> [branch-46] Improve documentation for `DataSourceExec`, `FileScanConfig`, `DataSource` etc (#14941)

- docs/source/contributor-guide/index.md
I was setting up a new workstation and while checking the docs I was redirected to the user guide instead of the development environment page. This is just a minor fix for a left-over from #14694.
Documentation is pointing to the wrong page.
Yes, visitors will now be redirected to the proper page.
> MINOR fix(docs): set the proper link for dev-env setup in contrib guide

- datafusion/core/tests/physical_optimizer/projection_pushdown.rs
- datafusion/datasource/src/file_scan_config.rs
- Follow on to https://github.com/apache/datafusion/pull/14956
- Related to https://github.com/delta-io/delta-rs/pull/3261
I wondered if the fix in https://github.com/apache/datafusion/pull/14956 worked for expressions so I wrote some more tets for it
1. Add a test when the projection that is pushed down includes an expression (not just a column)
2. Add some more comments
Yes
No
> Minor: Add more projection pushdown tests, clarify comments

- datafusion/catalog-listing/src/helpers.rs
- datafusion/expr/src/expr.rs
- datafusion/expr/src/expr_fn.rs
- datafusion/expr/src/expr_rewriter/mod.rs
- datafusion/expr/src/expr_schema.rs
- datafusion/expr/src/logical_plan/builder.rs
- datafusion/expr/src/logical_plan/plan.rs
- datafusion/expr/src/tree_node.rs
- datafusion/expr/src/utils.rs
- datafusion/functions-aggregate/src/planner.rs
- datafusion/functions-window/src/planner.rs
- datafusion/optimizer/src/analyzer/expand_wildcard_rule.rs
- datafusion/optimizer/src/analyzer/type_coercion.rs
- datafusion/optimizer/src/common_subexpr_eliminate.rs
- datafusion/optimizer/src/push_down_filter.rs
- datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs
- datafusion/proto/src/logical_plan/from_proto.rs
- datafusion/proto/src/logical_plan/to_proto.rs
- datafusion/sql/src/expr/mod.rs
- datafusion/sql/src/unparser/expr.rs
- datafusion/sql/src/utils.rs
- datafusion/substrait/src/logical_plan/producer.rs
N/A
This is discussed as part of #14123.
`Expr::Wildcard` is marked as deprecated.
N/A
N/A
> Deprecate `Expr::Wildcard`

- datafusion/catalog-listing/src/helpers.rs
- datafusion/expr/src/expr.rs
- datafusion/expr/src/expr_fn.rs
- datafusion/expr/src/expr_rewriter/mod.rs
- datafusion/expr/src/expr_schema.rs
- datafusion/expr/src/logical_plan/builder.rs
- datafusion/expr/src/logical_plan/plan.rs
- datafusion/expr/src/tree_node.rs
- datafusion/expr/src/utils.rs
- datafusion/functions-aggregate/src/planner.rs
- datafusion/functions-window/src/planner.rs
- datafusion/optimizer/src/analyzer/expand_wildcard_rule.rs
- datafusion/optimizer/src/analyzer/type_coercion.rs
- datafusion/optimizer/src/common_subexpr_eliminate.rs
- datafusion/optimizer/src/push_down_filter.rs
- datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs
- datafusion/proto/src/logical_plan/from_proto.rs
- datafusion/proto/src/logical_plan/to_proto.rs
- datafusion/sql/src/expr/mod.rs
- datafusion/sql/src/unparser/expr.rs
- datafusion/sql/src/utils.rs
- datafusion/substrait/src/logical_plan/producer.rs
- Part of https://github.com/apache/datafusion/issues/14123
- Backports https://github.com/apache/datafusion/pull/14959
Let's include https://github.com/apache/datafusion/pull/14959 in `branch-46`
> [branch-46] Deprecate `Expr::Wildcard` (#14959)

- dev/changelog/46.0.0.md
- Part of https://github.com/apache/datafusion/issues/14123
FInal update of changelog prior to making an RC to include backported content
FInal update of changelog prior to making an RC
> [branch-46] Update changelog for backports to 46.0.0

- dev/changelog/46.0.0.md
Add a link to 
- https://github.com/apache/datafusion/pull/14891
- Part of https://github.com/apache/datafusion/pull/14979
See rendered: https://github.com/alamb/datafusion/blob/alamb/upgrade_guide/dev/changelog/46.0.0.md
In the release notes to help people find it easier
FYI @xudong963
> Add note about upgrade guide into the release notes

- datafusion/core/src/datasource/listing/table.rs
- datafusion/core/src/test/object_store.rs
- Closes #14916.
When scanning an exact list of remote Parquet files, the ListingTable was fetching file metadata (via head calls) sequentially. This was due to using `stream::iter(file_list).flatten()`, which processes each one-item stream in order. For remote blob stores, where each head call can take tens to hundreds of milliseconds, this sequential behavior significantly increased the time to create the physical plan.
This commit replaces the sequential flattening with concurrent merging using `stream::iter(file_list).flatten_unordered(meta_fetch_concurrency)`. With this change, the `head` requests are executed in parallel (up to the configured `meta_fetch_concurrency` limit), reducing latency when creating the physical plan.
Note that the ordering loss introduced by …
> Fix sequential metadata fetching in ListingTable causing high latency

- datafusion/core/src/execution/session_state.rs
- related to https://github.com/apache/datafusion/issues/14899
- related to https://github.com/apache/datafusion/pull/14935
The fact that SessionStateBuilder starts out empty and you need to call `with_default_features` was causing some confusion
Let's add some docs to help clarify that
> Improve `SessionStateBuilder::new` documentation

- .github/actions/setup-builder/action.yaml
- .github/workflows/extended.yml
- dev/release/verify-release-candidate.sh
- Closes https://github.com/apache/datafusion/pull/14985
- Closes https://github.com/apache/datafusion/issues/14982
`rustup` previously would automatically install the toolchain (version of rust) that
was needed if it wasn't already installed.
However, the recently released rustup version changes this behavior
https://github.com/rust-lang/rustup/blob/f00c3d1fbcbe8d3ae2411e63ca906bc9b69e43d1/CHANGELOG.md?plain=1#L9-L17
Thus to ensure we have the correct toolchain installed, we need to run `rustup toolchain install`
* Update the verification script to call `rustup toolchain install` per release notes
* Update the extended test to use the standard builder setup rather than their own special thing
* I verified manually that this change fixes the verification script run for the  46.0.0 RC
* I …
> Fix verification script and extended tests due to `rustup` changes

- docs/source/conf.py
- docs/source/index.rst
- Closes #14984
The dynamic Star and Fork buttons were replaced with static versions. The new versions don't include Star and Fork counts but otherwise look similar.
Yes, locally.
No.
> Minor: Replace Star and Fork buttons in docs with static versions

- datafusion-cli/Cargo.toml
- Closes #.
We can build `datafusion` with `backtrace` feature to display full backtrace when an error is thrown. See https://datafusion.apache.org/user-guide/crate-configuration.html#enable-backtraces.
This PR propagates this feature to `datafusion-cli`, when compiling `datafusion-cli` with `--features=backtrace` flag, the same feature will be passed to inner `datafusion` crate.
Add `backtrace` feature to `datafusion-cli` build option, and it's only pass through to build `datafusion`.
Tested manually.
Without `backtrace` feature:
```sh
yongting@Mac ~/C/d/datafusion-cli (cli-backtrace *)> RUST_BACKTRACE=1 cargo run
DataFusion CLI v46.0.0
> select to_car();
Error during planning: Invalid function 'to_car'.
Did you mean 'to_char'?
>
```
With `backtrace` feature enabled:
```sh
yongting@Mac …
```
> Minor: Add `backtrace` feature in datafusion-cli

- datafusion/core/src/execution/session_state.rs
> chore: Update `SessionStateBuilder::with_default_features` does not replace existing features

- datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs
- datafusion/optimizer/src/simplify_expressions/utils.rs
- datafusion/sqllogictest/test_files/simplify_expr.slt
> Simplify Between expression to Eq

- datafusion/core/tests/dataframe/dataframe_functions.rs
- datafusion/core/tests/dataframe/mod.rs
- datafusion/functions-aggregate/src/count.rs
- datafusion/sqllogictest/test_files/subquery.slt
> Count wildcard alias

- datafusion/core/tests/physical_optimizer/enforce_distribution.rs
- Part of #15003 
Make it easier to skim test case plans.
Only changes the plans used in the test cases; change to include indentation.
Yes
No
> Minor: Add indentation to EnforceDistribution test plans.

- datafusion/core/src/execution/session_state.rs
- Closes #14981 
added method `new_with_defaults` to `StreamStateBuilder`
> Minor: add method `SessionStateBuilder::new_with_default_features()`

- datafusion/physical-plan/src/display.rs
- datafusion/physical-plan/src/filter.rs
- datafusion/sqllogictest/test_files/explain_tree.slt
- Closes https://github.com/apache/datafusion/issues/15000
- Part of https://github.com/apache/datafusion/issues/14914
Let's have nice explain plans! 
I wanted an example of how to make a tree explain plan so that I can file a bunch of follow on tickets for https://github.com/apache/datafusion/issues/14914 to share the work
1. Update comments about `ExplainFormat`
2. Implement for `FilterExec`
3. Update tests
Yes
tree explain is better
> Implement `tree` explain for FilterExec

- datafusion/sql/src/unparser/expr.rs
No Issue, just another production error we're seeing
This seems like a pretty straight forward change to support `AtArrow` and `ArrowAt`
> Unparser add `AtArrow` and `ArrowAt` conversion to BinaryOperator

- dev/release/verify-release-candidate.sh
- Closes #.
Check all build dependencies are available before running the script.
Background: I'll use a separate docker to verify the release candidate. And I always forget to install some of the build dependencies. Then I need to install it and restart from the very beginning. I list all the things I'm aware of (or need to be installed in a fresh ubuntu image) and check them before the build starts.
A new function `check_dependencies` in `dev/release/verify-release-candidate.sh` that checks build dependencies in advance.
Yes, I use this version to verify 46.0.0 RC2 release
no
> Add dependency checks to verify-release-candidate script

- datafusion/core/tests/memory_limit/mod.rs
- datafusion/physical-plan/src/sorts/sort.rs
- Closes #.
I came across one sorting query with memory limit fail indefinitely, here is a simpler reproducer (running in `datafusion-cli` with commit 75977692c)
```sh
cargo run --profile release-nonlto -- --mem-pool-type fair -m 10M
```
2 sort queries are executed: Q1 get executed with no issue, Q2 has smaller input size than Q1, but it failed.
```
DataFusion CLI v46.0.0
> set datafusion.execution.sort_spill_reservation_bytes = 3000000;
0 row(s) fetched.
Elapsed 0.001 seconds.
> select * from generate_series(1,10000000) as t1(v1) order by v1;
...Query succeed
> select * from generate_series(1,9000000) as t1(v1) order by v1;
Resources exhausted: Failed to allocate additional 65536 bytes for ExternalSorterMerge[0] with 0 bytes already allocated for this reservation - 49152 bytes remain …
```
> fix: External sort failing on an edge case

- datafusion/functions/src/datetime/to_char.rs
- datafusion/sqllogictest/test_files/timestamps.slt
- Closes #14969.
After #14908, the `to_char` function was incorrectly returning `NULL` for valid `DATE` values due to improper handling of the `DATE` type. This fix ensures that `to_char` correctly formats non-null `DATE` values while preserving `NULL` values as expected.
This is a re-implementation of #14908
- Fixed the `to_char` function to properly process `DATE` values.
- Added slt test cases to verify correct behavior when formatting `DATE` values.
Yes, new test cases have been added to confirm that:
1. `to_char` correctly formats valid `DATE` values.
2. `NULL` values remain unaffected.
No breaking changes. Users will now see correctly formatted `DATE` values when using `to_char`, instead of unexpected `NULL` results.
> Fix: to_char Function Now Correctly Handles DATE Values in DataFusion

- datafusion/substrait/src/logical_plan/producer.rs
- Fixes #12244
https://github.com/apache/datafusion/issues/12244 reported a larger problem with plan generation which was mostly but not completely fixed by https://github.com/apache/datafusion/pull/12245. As noted in https://github.com/apache/datafusion/issues/12244, invalid plans could be still be generated.
Structs for Schemas are set to always non-nullable.
Yes. I ran the substrait-validator CLI over a plan generated from datafusion built with this patch.
No.
> Make Substrait Schema Structs always non-nullable

- datafusion/physical-expr/src/aggregate.rs
I stumbled on some missing documentation while trying to construct a AggregateFunctionExpr
1. AggregateFunctionExpr didn't link to AggregateExprBuilder, which seems to be the only way to construct it
2. AggregateExprBuilder did not specify that providing an alias is required.
This PR should fix both those issues.
> docs: Improve docs on AggregateFunctionExpr construction

- datafusion/functions-aggregate/src/min_max.rs
- datafusion/functions-nested/src/lib.rs
- datafusion/functions-nested/src/max.rs
- datafusion/sqllogictest/test_files/array.slt
- docs/source/user-guide/sql/scalar_functions.md
Closes #14469.
Currently, Spark, Snowflake and Presto support `array_max` function. This can also be useful for DataFusion.
```
array_max(make_array(3,1,4,2)) => 4
array_max(make_array('h','e','o','l','l',NULL)) => o
array_max(make_array(NULL,NULL)) => NULL
select input, array_max(input) from 
(select make_array(d - 1, d, d + 1) input from (values (10), (NULL)) t(d)) =>
----
[9, 10, 11] 11
[NULL, NULL, NULL] NULL
```
Spark: https://docs.databricks.com/en/sql/language-manual/functions/array_max.html
Snowflake: https://docs.snowflake.com/en/sql-reference/functions/array_max
Presto: https://prestodb.io/docs/current/functions/array.html#array_max-x-x
All potential use-cases have been covered like different `data_types`, `empty array`, `NULL` etc.
Added new UT cases to verify `array_max` …
> feat: Add `array_max` function support

- datafusion/core/tests/physical_optimizer/enforce_distribution.rs
Part of #15003 
Make it easier to determine the differences in test configuration, for each test case.
Also clearly defines what are the defaults used for the test suite.
Define `TestConfig`, which requires one-of `DoFirst` optimizer run configs. Most test cases uses this test config with the default settings.
Provide a set of interfaces to define which configurations get tweaked.
Yes
No
> Refactor test suite in EnforceDistribution, to use standard test config.

- datafusion/optimizer/src/lib.rs
- datafusion/optimizer/src/optimizer.rs
- datafusion/optimizer/src/simplify_expressions/simplify_exprs.rs
- datafusion/optimizer/src/utils.rs
Follow up for #15027
---
1. Cleanup deprecated function in `optimizer`
2. Inlined `optimize_plan_node`
---
I've also noticed that, all `supports_rewrite` return true and not used anywhere, should we also remove it?
> Remove deprecated function `OptimizerRule::try_optimize`

- benchmarks/README.md
- benchmarks/src/cancellation.rs
This is a follow-on to https://github.com/apache/datafusion/pull/14818.
There were some further improvements to the documentation that @alamb and I noticed after #14818 was merged in.
I noticed there was a label with the text "Arglebargle" that I put in there before I knew where that text ended up (it's a heading in the `bench.sh` output)
[@alamb had a suggestion in the previous PR](https://github.com/apache/datafusion/pull/14818#discussion_r1972019358) that I've now taken
[In my next PR, @alamb noticed I forgot to add this benchmark's description to `benchmarks/README.md`](https://github.com/apache/datafusion/pull/15030#discussion_r1982252416)
Nope, they're just docs :)
These are the docs :)
> Improve benchmark documentation

- datafusion/expr/src/logical_plan/plan.rs
- Closes #14999
Account for columns in any comparisons to the `equi_join_count`. Eg a pair of columns can be compared to one equi_join. Then check for column pairs while creating the new `on` expression.
Yes, I've added some unit tests.
`with_new_exprs` with a column will no longer return an error if the other conditions are correct.
> Handle columns in with_new_exprs with a Join

- benchmarks/README.md
-o takes a filepath not a folder
Otherwise it shows: `Error: IoError(Os { code: 21, kind: IsADirectory, message: "Is a directory" })`
https://github.com/apache/datafusion/blob/532bd14992a87f841b4b9dbafa278305fef4c964/benchmarks/src/util/run.rs#L150
> doc: Correct benchmark command

- datafusion/core/tests/user_defined/user_defined_scalar_functions.rs
- datafusion/expr/src/udf.rs
- datafusion/functions-nested/benches/map.rs
- datafusion/functions/benches/character_length.rs
- datafusion/functions/benches/chr.rs
- datafusion/functions/benches/cot.rs
- datafusion/functions/benches/date_bin.rs
- datafusion/functions/benches/date_trunc.rs
- datafusion/functions/benches/encoding.rs
- datafusion/functions/benches/isnan.rs
- datafusion/functions/benches/iszero.rs
- datafusion/functions/benches/make_date.rs
- datafusion/functions/benches/nullif.rs
- datafusion/functions/benches/pad.rs
- datafusion/functions/benches/random.rs
- datafusion/functions/benches/reverse.rs
- datafusion/functions/benches/signum.rs
- datafusion/functions/benches/strpos.rs
- datafusion/functions/benches/substr.rs
- datafusion/functions/benches/substr_index.rs
- datafusion/functions/benches/to_char.rs
- datafusion/functions/benches/to_timestamp.rs
- datafusion/functions/benches/trunc.rs
- datafusion/optimizer/src/eliminate_group_by_constant.rs
See https://github.com/apache/datafusion/issues/14123#issuecomment-2703526303
Also (main) part of https://github.com/apache/datafusion/issues/14652 and closes https://github.com/apache/datafusion/issues/13515
People should use `invoke_with_args` instead. Calling `invoke_batch` for any DF-builtin function will fail at runtime with something like `Function X does not implement invoke but called`
We should also consider just removing the old functions (invoke_batch, invoke, invoke_no_args), to clear up the trait.
Mark `invoke_batch` as deprecated. It was already called so in the docstring, but the compiler doesn't read those.
Existing tests
New deprecation
> fix: mark ScalarUDFImpl::invoke_batch as deprecated

- datafusion/physical-plan/src/streaming.rs
- datafusion/sqllogictest/test_files/explain_tree.slt
- Closes part of #14914 and #15086.
implement tree rendering for StreamingTableExec
yes
> implement tree rendering for StreamingTableExec

- datafusion/common/src/dfschema.rs
- datafusion/core/tests/dataframe/mod.rs
- Closes [#15015](https://github.com/apache/datafusion/issues/15015)
Relax the datatype check to pass when we support cast, and the final map batch schema will automatically insert the the right schema datatype field.
Relax the datatype check to pass when we support cast, and the final map batch schema will automatically insert the the right schema datatype field.
Yes
Support the consistent API which is same with sql insert into.
> fix: Support datatype cast for insert api same as insert into sql

- datafusion/core/tests/expr_api/mod.rs
- Part of https://github.com/apache/datafusion/issues/14987
We are trying to make predicates like `int_col = '1234' faster in delta.rs. Let's add a test showing what is going on
Add tests for https://github.com/apache/datafusion/issues/14987
yes
> Add tests for simplification and coercion of `SessionContext::create_physical_expr`

- datafusion/core/src/physical_planner.rs
- datafusion/physical-plan/src/display.rs
- datafusion/sqllogictest/test_files/explain_tree.slt
- Closes https://github.com/apache/datafusion/issues/15020
- Part of https://github.com/apache/datafusion/issues/14914
See https://github.com/apache/datafusion/issues/15020
I mostly want to focus our PRs for `tree` mode and keep the slt diff down
Do not print logical plans in explain `tree` mode
yes
> Do not display logical_plan win explain `tree` mode 🧹 

- datafusion/core/tests/sql/select.rs
- datafusion/sql/src/unparser/plan.rs
- datafusion/sql/tests/cases/plan_to_sql.rs
- Closes #13272.
the qualifier is incorrect for subqueryalias when unparsing.
wrap with subqueryalias if alias is passed when unparsing.
Unittest
No
> fix: unparse for subqueryalias

- .github/workflows/rust.yml
- datafusion/datasource-parquet/Cargo.toml
- datafusion/datasource-parquet/src/file_format.rs
- datafusion/wasmtest/Cargo.toml
- Closes https://github.com/apache/datafusion/issues/15150
I encountered a compile error when trying to upgrade DataFusion to V46 for [paruqet viewer](https://parquet-viewer.xiangpeng.systems).
I think the bug was accidentally introduced in https://github.com/apache/datafusion/pull/14464 cc @logan-keede 
Reverted the wasm32 gate as it should work for wasm32. I also enabled the `parquet` feature for wasm-test so that we can capture the bug in ci.
I also removed the fs feature on tokio, as I don't think parquet datasource relies on it, which breaks wasm build.
> Fix wasm32 build on version 46

- datafusion/optimizer/tests/optimizer_integration.rs
- datafusion/sql/src/select.rs
- datafusion/sql/tests/cases/plan_to_sql.rs
- datafusion/sql/tests/sql_integration.rs
- datafusion/sqllogictest/test_files/alias.slt
- datafusion/sqllogictest/test_files/copy.slt
- datafusion/sqllogictest/test_files/cte.slt
- datafusion/sqllogictest/test_files/group_by.slt
- datafusion/sqllogictest/test_files/joins.slt
- datafusion/sqllogictest/test_files/order.slt
- datafusion/sqllogictest/test_files/prepare.slt
- datafusion/sqllogictest/test_files/select.slt
- datafusion/sqllogictest/test_files/subquery.slt
- datafusion/sqllogictest/test_files/wildcard.slt
- Closes #.
- A step before #7765 and #14634
- Before #14634, other query like create view should be fixed as well
> Expand wildcard to actual expressions in `prepare_select_exprs`

- datafusion/functions/benches/date_trunc.rs
- Closes #15167
Got broken in https://github.com/apache/datafusion/pull/15049, as the call for return_type was only providing one data type instead of two.
`cargo bench --bench date_trunc` runs sucessfully after this
> fix: date_trunc bench broken by #15049

- Cargo.lock
Remove the `humantime` dependency via `env_logger` (https://rustsec.org/advisories/RUSTSEC-2025-0014.html)
To remove it fully we need https://github.com/apache/arrow-rs/pull/7261.
`humantime` is unmaintained
`cargo update -p env_logger`
CI
No
> Bump `env_logger` from `0.11.6` to `0.11.7`

- datafusion/core/src/physical_planner.rs
I recommend look at the diff while ignoring whitespace (e.g. [this link](https://github.com/apache/datafusion/pull/15188/files?w=1)) as I think the change is much clearer (and smaller)
- part of https://github.com/apache/datafusion/issues/15021
- Part of https://github.com/apache/datafusion/pull/15166
I would like to make it easier to review https://github.com/apache/datafusion/pull/15166 so I pulled out a mechanical change into a new PR
1. Break the handling of `explain` and `analyze` into two functions (with much less indent!)
> Minor: split EXPLAIN and ANALYZE planning into different functions

- .github/workflows/rust.yml
- Part of https://github.com/apache/datafusion/issues/15155
The coverage for feature flags needs to be improved, as explained on https://github.com/apache/datafusion/issues/15155
1. Move the checks for datafusion-substrait and datafusion-proto into their own jobs
2. Consolidate the 'no default features' check into the per-crate checks 
Note I will make a follow on PR to add additional coverage for flags in `datafusion-functions` and `datafusion` but I am trying to keep this PR reasonably sized
> Split out `datafusion-substrait` and `datafusion-proto` CI feature checks, increase coverage

- datafusion/expr/src/logical_plan/plan.rs
- datafusion/expr/src/utils.rs
- The follow-up of #15170 
- The pre-work of https://github.com/apache/datafusion/issues/7765
After removing wildcard expand rule, some functions added by #11681 can be removed.
CI 
no
> Remove unused wildcard expanding methods

- datafusion/physical-plan/src/memory.rs
- datafusion/sqllogictest/test_files/explain_tree.slt
- Closes #15171
- Part of #14914
- Implement LazyMemoryExec
- Update related tests
Yes
No
> Implement tree explain for LazyMemoryExec

- datafusion/datasource-csv/src/file_format.rs
- datafusion/sqllogictest/test_files/explain_tree.slt
> Implement `tree` explain for `CsvSink`

- datafusion/core/src/dataframe/mod.rs
- datafusion/core/tests/dataframe/mod.rs
- datafusion/expr/src/expr.rs
- datafusion/expr/src/expr_schema.rs
- datafusion/expr/src/tree_node.rs
- datafusion/optimizer/src/optimize_projections/mod.rs
- datafusion/proto/proto/datafusion.proto
- datafusion/proto/src/generated/pbjson.rs
- datafusion/proto/src/generated/prost.rs
- datafusion/proto/src/logical_plan/to_proto.rs
- datafusion/sql/src/unparser/rewrite.rs
when we use dataframe API,  we need to edit metadata on fields (e.g. to indicate a UTF8 columns is JSON data).
In spark, it allows user to customize metadata in alias.
https://spark.apache.org/docs/latest/api/python/reference/pyspark.sql/api/pyspark.sql.Column.alias.html
This PR adds this feature to datafusion.
add an alias function that accepts metadata.
unit test
new api is introduced.
> feat: support customize metadata in alias for dataframe api

- datafusion/functions-aggregate/src/approx_distinct.rs
- datafusion/sqllogictest/test_files/aggregate_skip_partial.slt
- Closes part of https://github.com/apache/datafusion/issues/15096
support ApproxDistinct with utf8view
support ApproxDistinct with utf8view
Yes
support ApproxDistinct with utf8view
> feat: support ApproxDistinct with utf8view

- datafusion/physical-expr/src/equivalence/properties/mod.rs
@akurmustafa  and I [wrote a blog](https://datafusion.apache.org/blog/2025/03/11/ordering-analysis/) with more details of how `EquivalenceProperties` works. Let's add a backlink to make it easier for people to find:
Add link to blog in docs
Only docs, no functional changes
> Add blog link to `EquivalenceProperties` docs

- datafusion/physical-plan/src/union.rs
- datafusion/sqllogictest/test_files/explain_tree.slt
- Closes #15196
- Part of #14914 
1. Implement InterleaveExec
2. Update related tests
Yes
No
> Implement tree explain for InterleaveExec

- Cargo.lock
- Part of https://github.com/apache/datafusion/issues/15151
- Related to https://github.com/apache/datafusion/issues/15122
We are making a 46.0.1 patchset release with some bug fixes
I would like to  get a clean CI run on 46, but the rustsec check is failing due to an older dependency we have fixed on main
Here is an example failure
https://github.com/apache/datafusion/actions/runs/13857186054/job/38776531902?pr=15227
- Backport https://github.com/apache/datafusion/pull/15063
> [branch-46] Update ring to v0.17.13 (#15063)

- .github/workflows/rust.yml
- datafusion/core/src/datasource/file_format/parquet.rs
- datafusion/wasmtest/Cargo.toml
- Part of https://github.com/apache/datafusion/issues/15151
- Related to https://github.com/apache/datafusion/issues/15150
We are making a 46.0.1 patchset release with some bug fixes
- Backport https://github.com/apache/datafusion/pull/15102
Note I had to backport the changes manually (`git cherry-pick` didn't work as the files have been moved)
> [branch-46] Fix wasm32 build on version 46

- .asf.yaml
- Closes https://github.com/apache/datafusion/issues/15235
This PR follows the fix in `arrow-rs` https://github.com/apache/arrow-rs/pull/7288/files, and try to bring back the GitHub discussion section
> Re-enable github discussion

- .github/workflows/rust.yml
- Closes [#15226](https://github.com/apache/datafusion/issues/15226)
exclude datafusion-cli testing for mac
exclude datafusion-cli testing for mac
yes
exclude datafusion-cli testing for mac
> Minor: exclude datafusion-cli testing for mac

- Cargo.toml
- datafusion/core/src/datasource/stream.rs
- datafusion/optimizer/src/eliminate_limit.rs
- datafusion/optimizer/src/push_down_filter.rs
- datafusion/optimizer/src/push_down_limit.rs
- datafusion/physical-optimizer/src/aggregate_statistics.rs
- datafusion/physical-plan/src/joins/nested_loop_join.rs
- datafusion/sql/src/unparser/dialect.rs
- Closes https://github.com/apache/datafusion/issues/14649.
To catch used underscore bindings in the codebase.
Enable clippy lint to check for used underscore bindings:
```
[workspace.lints.clippy]
large_futures = "warn"
used_underscore_binding = "warn"
```
Yes, they are
No
> Enable `used_underscore_binding` clippy lint

- datafusion-examples/examples/planner_api.rs
- datafusion/core/src/execution/session_state.rs
- datafusion/core/src/physical_planner.rs
- datafusion/expr/src/logical_plan/builder.rs
- datafusion/expr/src/logical_plan/mod.rs
- datafusion/expr/src/logical_plan/plan.rs
- datafusion/expr/src/logical_plan/tree_node.rs
- datafusion/physical-plan/src/display.rs
- datafusion/sql/src/parser.rs
- datafusion/sql/src/statement.rs
- datafusion/sqllogictest/test_files/explain.slt
- docs/source/user-guide/sql/explain.md
- Closes https://github.com/apache/datafusion/issues/15021
- Closes https://github.com/apache/datafusion/issues/219
I would like to be able to see more of the great explain plan code that DataFusion already has (see https://github.com/apache/datafusion/issues/15021 for details)
Changes:
Here is an example
```sql
> explain format text select * from values(1) t(x);
Invalid or Unsupported Configuration: Invalid explain format: text
> explain format indent select * from values(1) t(x);
+---------------+-----------------------------------------------------+
| plan_type     | plan                                                |
+---------------+-----------------------------------------------------+
| logical_plan  | SubqueryAlias: t                                    |
|               | …
```
> Support `EXPLAIN ... FORMAT <indent | tree | json | graphviz > ...`

- datafusion/datasource/src/url.rs
N/A
I spent some time looking into #7393. It seems the simple cases can be supported in a few lines of code (e.g. parsing `s3://bucket/key/*.parquet` into a base URL `s3://bucket/key/` and a glob pattern `*.parquet`. But soon I realized there is no clear idea how broader cases can be handled.
1. For `http` or `https` schemes, glob patterns in the URL may not make sense, since many HTTP servers do not support listing files under a given directory. Also, the `?` character before the query should not be treated as a glob pattern.
2. Special characters (`*`, `?`, etc.) in the authority (host name, username, or password) probably should not be treated as glob patterns. However, if we want to support glob patterns in URL paths only, we face a difficulty that the parsed URL does not provide …
> Make `ListingTableUrl::try_new` public

- datafusion/datasource-parquet/src/source.rs
- datafusion/physical-expr-common/src/sort_expr.rs
- datafusion/physical-plan/src/aggregates/mod.rs
- datafusion/physical-plan/src/filter.rs
- datafusion/physical-plan/src/joins/hash_join.rs
- datafusion/physical-plan/src/joins/sort_merge_join.rs
- datafusion/physical-plan/src/joins/symmetric_hash_join.rs
- datafusion/physical-plan/src/sorts/sort_preserving_merge.rs
- datafusion/sqllogictest/test_files/explain_tree.slt
> Simplify the printing of all plans containing `expr` in `tree` mode

- datafusion/expr/src/type_coercion/mod.rs
- datafusion/optimizer/src/analyzer/type_coercion.rs
- datafusion/sqllogictest/test_files/subquery_sort.slt
- datafusion/sqllogictest/test_files/window.slt
Support utf8view datatype for window
- Close part of  [#15096](https://github.com/apache/datafusion/issues/15096)
Support utf8view datatype for window
Support utf8view datatype for window
Yes
Support utf8view datatype for window
> Support utf8view datatype for window

- datafusion/core/src/execution/session_state.rs
Overwriting the default catalog when building the `SessionState` can be unexpected.
Add logs for the overwriting the default catalog.
> Add debug logging for default catalog overwrite in SessionState build

- datafusion/physical-plan/src/placeholder_row.rs
- datafusion/sqllogictest/test_files/explain_tree.slt
- Closes #15138
- Part of #14914 
- Implement PlaceholderRowExec
- Update related tests
Yes
No
> Implement tree explain for PlaceholderRowExec

- datafusion/expr-common/src/accumulator.rs
I think this is what the "passed to the" part is missing but I might be wrong.
> docs: update documentation for Final GroupBy in accumulator.rs

- datafusion/ffi/src/catalog_provider.rs
- datafusion/ffi/src/lib.rs
- datafusion/ffi/src/schema_provider.rs
- datafusion/ffi/src/table_provider.rs
- datafusion/ffi/src/tests/catalog.rs
- datafusion/ffi/src/tests/mod.rs
- datafusion/ffi/tests/ffi_integration.rs
- part of https://github.com/apache/datafusion/issues/15283
This PR expands the interfaces available via FFI to include Catalogs and Schemas (catalog schema, not arrow schema).
Adds FFI variants of CatalogProvider and SchemaProvider
Unit tests included. Coverage is shown here:
None
> Add CatalogProvider and SchemaProvider to FFI Crate

- datafusion/expr-common/src/type_coercion/binary.rs
- datafusion/physical-expr/src/expressions/binary.rs
- datafusion/sqllogictest/test_files/string/string_view.slt
- Closes  sub_task of 
[#15096](https://github.com/apache/datafusion/issues/15096)
feat: Native support utf8view for binary operator
Because upstream arrow-rs already support utf8view for the remaining function for ut8view such as regex_match, details:
https://github.com/apache/arrow-rs/issues/6717
feat: Native support utf8view for binary operator
Because upstream arrow-rs already support utf8view for the remaining function for ut8view such as regex_match.
Yes
feat: Native support utf8view for binary operator
> feat: Native support utf8view for regex string operators

- datafusion/sql/src/expr/unary_op.rs
- datafusion/sql/tests/cases/diagnostic.rs
- related #14433 
attach a Diagnostic when dealing with "incompatible type in unary expression" error
Yes, I've tested the PLUS operator with column and non-column operands.
> chore: Attach Diagnostic to "incompatible type in unary expression" error

- datafusion/sqllogictest/test_files/union.slt
This CI failure is caused by the conflict with https://github.com/apache/datafusion/pull/15135, so is not detected
- Closes #.
> CI Red: Fix union in view table test

- Cargo.lock
- README.md
- datafusion-examples/Cargo.toml
- datafusion-examples/examples/tracing.rs
- datafusion/common-runtime/Cargo.toml
- datafusion/common-runtime/src/common.rs
- datafusion/common-runtime/src/join_set.rs
- datafusion/common-runtime/src/lib.rs
- datafusion/common-runtime/src/trace_utils.rs
- datafusion/core/Cargo.toml
- datafusion/core/src/datasource/file_format/arrow.rs
- datafusion/core/src/datasource/memory.rs
- datafusion/core/tests/fuzz_cases/aggregate_fuzz.rs
- datafusion/core/tests/fuzz_cases/aggregation_fuzzer/fuzzer.rs
- datafusion/core/tests/fuzz_cases/distinct_count_string_fuzz.rs
- datafusion/datasource-csv/src/source.rs
- datafusion/datasource-json/src/source.rs
- datafusion/datasource-parquet/src/file_format.rs
- datafusion/datasource-parquet/src/writer.rs
- datafusion/datasource/src/write/orchestration.rs
- datafusion/physical-plan/src/execution_plan.rs
- datafusion/physical-plan/src/repartition/mod.rs
- datafusion/physical-plan/src/stream.rs
- Closes #9415, 
This PR lays the groundwork for optional instrumentation of async tasks in DataFusion.
This PR introduces a general mechanism enabling DataFusion to propagate user-defined context (such as tracing spans, logging, or metrics) across thread boundaries without depending on any specific instrumentation library.
Previously, tasks spawned on new threads—such as those performing repartitioning or Parquet file reads—would lose thread-local context, making instrumentation challenging for users. The introduced approach addresses this gap by allowing users to inject custom instrumentation via the new `JoinSetTracer` trait. This ensures context is preserved seamlessly, keeping DataFusion lightweight by not adding any direct instrumentation dependencies.
- **New `JoinSetTracer` …
> feat: introduce `JoinSetTracer` trait for tracing context propagation in spawned tasks

- Cargo.toml
- Closes #.
`release-nonlto` build produces binaries with performance close to `--release` build, but compiles faster. This compilation profile is used for easier development and benchmarking.
Now it by default strips the debug symbols, as a consequence, If a flamegraph is collected using this `release-nonlto` build, useful function names will not displayed.
`sudo cargo flamegraph --profile release-nonlto --bin dfbench -- sort-tpch -p /Users/yongting/Code/datafusion/benchmarks/data/tpch_sf10 -q 3`
The generated flamegraph will look like:
If we keep the symbol names, the flamegraph will be generated with function names in the call stack.
Changed `cargo.toml` to keep debug symbols in `release-nonlto` build.
Tested manually in the above example.
No.
> Minor: Keep debug symbols for `release-nonlto` build

- datafusion/datasource-parquet/src/file_format.rs
- Closes #.
The statistics are calculated only for columns in the table schema that actually have statistics available in the parquet metadata, avoiding unnecessary work.
> Use `any` instead of `for_each`

- datafusion/datasource/src/file_scan_config.rs
- datafusion/proto/proto/datafusion.proto
- datafusion/proto/src/generated/pbjson.rs
- datafusion/proto/src/generated/prost.rs
- datafusion/proto/src/physical_plan/from_proto.rs
- datafusion/proto/src/physical_plan/to_proto.rs
- Closes None.
- Reference [Support serde for batch_size](https://github.com/apache/datafusion/pull/15311#discussion_r2004114426)
Support serde for FileScanConfig `batch_size`
> When `FileScanConfig` call `open(..)`, will set `batch_size` for `file_source`, so this PR add `batch_size` property for struct `FileScanConfig` to support serde `batch_size` to proto.
https://github.com/apache/datafusion/blob/19dd46d3c65e3160c0fb949880bc3e960434e96d/datafusion/datasource/src/file_scan_config.rs#L172-L190
> feat: Support serde for FileScanConfig `batch_size`

- docs/source/library-user-guide/working-with-exprs.md
- Closes [#7724](https://github.com/apache/datafusion/issues/7724) .
Added some description about DFSchema and Schema for make user easy to understanding and easy to use 
Updated documentation we a new section "Arrow Schema and DataFusion DFSchema"
No need to test
Yes, documentation is user-facing changes
> added explaination for Schema and DFSchema to documentation

- datafusion/functions-aggregate/src/min_max.rs
- datafusion/sqllogictest/test_files/aggregate.slt
> Implement GroupsAccumulator for min/max Duration

- datafusion/substrait/src/logical_plan/consumer.rs
- datafusion/substrait/tests/cases/consumer_integration.rs
- datafusion/substrait/tests/testdata/test_plans/select_count_from_select_1.substrait.json
- datafusion/substrait/tests/testdata/test_plans/select_window_count.substrait.json
- Closes #15344
Fixing empty `count()` aggregation functions provided through Substrait
Adding back this check https://github.com/apache/datafusion/pull/14824/files#diff-474e53672159d74dae38992a914a74eba81b8350ebe161f11d755f06414ed7b4 and testing it
yes, by a new test and by extending previously existing tests
yes, users will be able to feed empty `count()` functions through the Substrait interface
> Fix empty aggregation function count() in Substrait

- datafusion/functions-nested/src/array_has.rs
- datafusion/sqllogictest/test_files/array.slt
- Closes #15038 
Fix array_has_any and array_has_all with empty array input
Added the unit test in array.slt
NA
> Fix array_has_all and array_has_any with empty array

- benchmarks/src/clickbench.rs
Minor: add average time for clickbench benchmark query
Minor: add average time for clickbench benchmark query
Minor: add average time for clickbench benchmark query
Yes
Minor: add average time for clickbench benchmark query
> Minor: add average time for clickbench benchmark query

- Cargo.lock
- datafusion/wasmtest/Cargo.toml
- datafusion/wasmtest/src/lib.rs
- Closes #15357.
End to end parquet reading test for WASM.
No
> Add "end to end parquet reading test" for WASM

- docs/source/library-user-guide/adding-udfs.md
- Closes [#15267](https://github.com/apache/datafusion/issues/15267) .
This PR adds documentation for using the `ExprPlanner` API to plan custom expressions, as requested in #15267. Clear documentation with an example will help users extend DataFusion to support custom operators like PostgreSQL's `->`.
- Added a new section `## Custom Expression Planning` to document
- Included an introduction explaining what `ExprPlanner` does and why it’s useful.
- Provided a step-by-step example showing how to implement and register an `ExprPlanner` to make the `->` operator concatenate strings (e.g., `'foo'->'bar'` outputs `foobar`).
- Linked to relevant API docs (`ExprPlanner` and `FunctionRegistry`) for further reading.
yes
Yes, since this is an documentation chang
> Documentation: Plan custom expressions

- datafusion/physical-plan/src/aggregates/topk/heap.rs
- datafusion/physical-plan/src/aggregates/topk/snapshots/datafusion_physical_plan__aggregates__topk__heap__tests__val=1 idx=0, bucket=1.snap
- datafusion/physical-plan/src/joins/nested_loop_join.rs
- datafusion/physical-plan/src/joins/sort_merge_join.rs
- datafusion/physical-plan/src/repartition/mod.rs
- Part of #15248.
Completely migrate physical plan tests to `insta`
Migrating from `assert_batches_sorted_eq` and `assert_batches_eq` to `assert_snapshot` in physical-plan tests
Yes, they are
No, they are not
>  Migrate physical plan tests to `insta` (Part-2)

- datafusion/datasource/src/write/demux.rs
- datafusion/sqllogictest/test_files/copy.slt
Closes #15336
Support additional types in hive partitions.
Code, slt test.
Yes, test updated to include additional types.
No
> fix: write hive partitions for any int/uint/float

- datafusion/physical-plan/src/metrics/baseline.rs
- datafusion/physical-plan/src/metrics/mod.rs
- datafusion/physical-plan/src/sorts/sort.rs
- datafusion/physical-plan/src/spill.rs
- Related to https://github.com/apache/datafusion/pull/14975
- related https://github.com/apache/datafusion/issues/15358
- related to https://github.com/apache/datafusion/issues/15323
Let's walkthrough an example, there is one external sort query with 1 partition, and sort exec has:
- 10MB memory limit
- 1MB `sort_spill_reservation_bytes` (see configuration explanation in https://datafusion.apache.org/user-guide/configs.html)
During the execution:
1. `SortExec` will read in batches, and 10MB memory limit is reached
2. It will sorted all buffered batches in-place, and merge them at once. Note only the 1MB buffer from 10MB total limit is pre-reserved for merging, so there is only 1MB available to store the merged output.
3. After we have collected 1MB of merged batch, one spill will be …
> fix: Redundant files spilled during external sort + introduce `SpillManager`

- datafusion/physical-plan/src/sorts/partial_sort.rs
- datafusion/physical-plan/src/sorts/sort.rs
- datafusion/physical-plan/src/sorts/sort_preserving_merge.rs
- datafusion/physical-plan/src/windows/bounded_window_agg_exec.rs
- Closes #15248 .
Migrate physical plan tests to insta
Migrating from `assert_batches_eq` to assert_snapshot in physical-plan tests
Yes they are
No
> Migrate physical plan tests to `insta` (Part-3 / Final)

- datafusion/physical-expr/src/expressions/case.rs
- datafusion/sqllogictest/bin/sqllogictests.rs
- datafusion/sqllogictest/test_files/case.slt
- Closes https://github.com/apache/datafusion/issues/15384
Commit https://github.com/apache/datafusion/commit/0f4b8b136ceb9132fd6b6595bd6a09a09707f5d9 (https://github.com/apache/datafusion/pull/13953) introduced a new
optimized evaluation mode for CASE expression with exactly one WHEN-THEN
clause and ELSE clause being present. Apparently, the new mode did not
take into account expensive or fallible expressions, as it
unconditionally evaluated both branches. This is definitely incorrect
for fallible expressions. For these, fallback to the original execution
mode.
fix so that CASE is lazy again
slt
yes
> Restore lazy evaluation of fallible CASE 

- benchmarks/src/sort_tpch.rs
- datafusion/core/benches/sort.rs
- datafusion/physical-plan/src/sorts/cursor.rs
- datafusion/physical-plan/src/sorts/streaming_merge.rs
- Closes partof [#15096](https://github.com/apache/datafusion/issues/15096)
Support Utf8View datatype single column comparisons for SortPreservingMergeStream
Support Utf8View datatype single column comparisons for SortPreservingMergeStream
Yes
Support Utf8View datatype single column comparisons for SortPreservingMergeStream
> Perf: Support Utf8View datatype single column comparisons for SortPreservingMergeStream

- datafusion/expr-common/src/type_coercion/binary.rs
- datafusion/optimizer/src/single_distinct_to_groupby.rs
- datafusion/optimizer/tests/optimizer_integration.rs
- datafusion/physical-expr/src/expressions/binary.rs
- datafusion/sqllogictest/test_files/math.slt
- datafusion/sqllogictest/test_files/operator.slt
- datafusion/sqllogictest/test_files/window.slt
- Closes #15340
Better handle type coercion when unsigned numerics are involved
code, extensive tests, existing test updates.
Yes
Possibly. Some previous results from dataframe/sql queries may have had the incorrect type if one of the types that were coerced was an unsigned type.
> Fix type coercion for unsigned and signed integers (`Int64` vs `UInt64`, etc)

- datafusion/functions-nested/src/array_has.rs
- datafusion/sqllogictest/test_files/array.slt
- Closes #14533 
This PR indirectly addresses #14533 not by actually changing the `array_has` evaluation but instead by simplifying it to the equivalent `InList` expression where the haystack is not varying per-row.
The `array_has` udf has to operate row-by-row because it may have a varying haystack. The `InList` expression, on the other hand, can operate in a columnar fashion by evaluating each of the N haystack items for equality against the needle and OR the results. It looks to me list `InList` also supports some kind of `Set` optimization.
Add a `simplify` implementation to `array_has` UDF which will produce an `InList` expr when the haystack is a literal list.
Yes, see test additions in the diff.
I also reran the original example from #14533 and we see that now the last two …
> simplify `array_has` UDF to `InList` expr when haystack is constant

- datafusion/physical-plan/src/sorts/sort.rs
- datafusion/physical-plan/src/spill/in_progress_spill_file.rs
- datafusion/physical-plan/src/spill/mod.rs
- datafusion/physical-plan/src/spill/spill_manager.rs
- Closes #15373
Split `spill.rs` into `spill/mod.rs`, `spill/spill_manager.rs`, and `spill/in_progress_spill_file.rs`.
> refactor: SpillManager into a separate file

- datafusion/core/src/lib.rs
The link from [the datafusion docs](https://docs.rs/datafusion/46.0.1/datafusion/index.html#execution) to the paper "Encapsulation of parallelism in the Volcano query processing system" was broken.
This PR changes the link from https://w6113.github.io/files/papers/volcanoparallelism-89.pdf (which is broken) to https://doi.org/10.1145/93605.98720 (which should "never" break).
A free PDF is available at the new link.
The Volcano paper is cited twice in the `datafusion` codebase. PR #14497 fixed one of the two citations. This new PR fixes the other citation :slightly_smiling_face:.
> Fix link to Volcano paper

- datafusion/functions-aggregate-common/src/merge_arrays.rs
- datafusion/functions-aggregate/src/array_agg.rs
- datafusion/sqllogictest/test_files/aggregate.slt
- docs/source/user-guide/sql/aggregate_functions.md
- Closes #12371.
Completing ARRAY_AGG functionality as a prerequisite for adding the full functionality of STRING_AGG in https://github.com/apache/datafusion/pull/14412
Adds a Postgres-style support for DISTINCT + ORDER_BY functionality, allowing users to issue statements like:
```sql
SELECT ARRAY_AGG(DISTINCT col ORDER BY col) FROM table;
```
Note that there's a limitation that prohibits ordering by an expression that is not the same as the ARRAY_AGG argument. For example, the following queries are invalid:
```sql
SELECT ARRAY_AGG(DISTINCT col ORDER BY other_col) FROM table; ❌
SELECT ARRAY_AGG(DISTINCT col ORDER BY concat(col, '')) FROM table; ❌
```
This is the same limitation that exists on Postgres, [example in Postgres fiddle](https://www.db-fiddle.com/f/4jyoMCicNSZpjMt4jFYoz5/16028) …
> Add support for DISTINCT + ORDER BY in `ARRAY_AGG`

- datafusion-examples/examples/parquet_exec_visitor.rs
- datafusion/core/src/test_util/parquet.rs
- datafusion/core/tests/parquet/utils.rs
- datafusion/core/tests/sql/path_partition.rs
- datafusion/datasource/src/source.rs
- datafusion/proto/src/physical_plan/mod.rs
- datafusion/substrait/src/physical_plan/producer.rs
- docs/source/library-user-guide/upgrading.md
When I upgraded the df46, It was annoying for me to do the following thing(a series of `downcast_ref`) and it's also easy to call the wrong method, such as mixing `file_source()` and `data_source()`:
```rust
if let Some(scan_config) = self.data_source().as_any().downcast_ref::<FileScanConfig>() {
if let Some(parquet_source) = scan_config
.file_source()
.as_any()
.downcast_ref::<ParquetSource>(){...}
```
Add the `downcast_to_source` method for `DataSourceExec` to make life easy
Yes, I replace the existing code with the new method.
It'll be useful for users to upgrade df46.
> Add `downcast_to_source` method for `DataSourceExec`

- datafusion/functions/src/crypto/basic.rs
- datafusion/functions/src/crypto/digest.rs
- datafusion/functions/src/crypto/md5.rs
- datafusion/functions/src/crypto/sha224.rs
- datafusion/functions/src/crypto/sha256.rs
- datafusion/functions/src/crypto/sha384.rs
- datafusion/functions/src/crypto/sha512.rs
- datafusion/sqllogictest/test_files/array.slt
- datafusion/sqllogictest/test_files/string/string_view.slt
- Closes #14762 .
1. Use `TypeSignature::Coercible` and logical type (string & binary) for crypto functions
2. Add `DataType::BinaryView` for `utf8_or_binary_to_binary_type` to support binaryView
3. Make `digest_binary_array` can digest binary and binaryView
4. Implement `digest_binary_array_impl`, which can be used by `digest_binary_array`
5. Make `digest_process` to support binaryView
> refactor: use TypeSignature::Coercible for crypto functions

- datafusion/proto/src/physical_plan/from_proto.rs
- datafusion/proto/src/physical_plan/to_proto.rs
- datafusion/proto/tests/cases/roundtrip_physical_plan.rs
- Closes #.
The following test fails, for the same reason in #14116
```rust
#[tokio::test]
async fn roundtrip_empty_projection() -> Result<()> {
let ctx = all_types_context().await?;
let sql = "select 1 from alltypes_plain";
roundtrip_test_sql_with_context(sql, &ctx).await
}
```
It is basally the same problem in projection handling: `None != Some(vec![])`, None means project all, but Some(vec![]) means project nothing.
Protobuf doesn't seem to support `Option<Vec<>>`, so if there's a None projection, the new encoder will hydrate it to use all columns.
> Fix roundtrip bug with empty projection in DataSourceExec

- datafusion/expr-common/src/type_coercion/binary.rs
- datafusion/optimizer/src/analyzer/type_coercion.rs
- Closes #15351.
In the `delta-rs` case, they use a custom field name, `key_value`, for the map type.
https://github.com/delta-io/delta-rs/blob/30dd5edf9717f6545ffbc73e65b676b8adaa0a01/crates/core/src/kernel/arrow/mod.rs#L13
Then, we use `lhs_type = rhs_type` to compare the data type for type coercion checking. However, in the document of `MpaType`:
```rust
/// In a field with Map type, the field has a child Struct field, which then
/// has two children: key type and the second the value type. The names of the
/// child fields may be respectively "entries", "key", and "value", but this is
/// not enforced.
Map(FieldRef, bool),
```
The field name doesn't matter actually. We should use `equals_datatype` to compare them instead.
```rust
/// Compares the datatype with another, ignoring nested …
```
> Use `equals_datatype` to compare type when type coercion

- datafusion/datasource-parquet/src/source.rs
- Closes #.
Currently setting metrics to parquet source has no effect, this pr fixes this.
The old `with_metrics` method was quite weird, and very easy to misuse. I changed it to consume `self` so that it's clear that we must use the returned value.
Btw, the bug was find by copilot review when I'm porting some of the code to LiquidCache, quite cool:
Here's the original link: https://github.com/XiangpengHao/liquid-cache/pull/136#discussion_r2017318959
I think it's generally helpful for code review, not sure how it can work in DataFusion though.
(cc @alamb this probably another LLM fever I caught recently :-)
> Fix no effect metrics bug in ParquetSource

- benchmarks/src/clickbench.rs
- Closes [#15471](https://github.com/apache/datafusion/issues/15471)
The average time for clickbench query compute should use new vec to make it compute for each query
The average time for clickbench query compute should use new vec to make it compute for each query
Yes
```rust
Q42: SELECT DATE_TRUNC('minute', to_timestamp_seconds("EventTime")) AS M, COUNT(*) AS PageViews FROM hits WHERE "CounterID" = 62 AND "EventDate"::INT::DATE >= '2013-07-14' AND "EventDate"::INT::DATE <= '2013-07-15' AND "IsRefresh" = 0 AND "DontCountHits" = 0 GROUP BY DATE_TRUNC('minute', to_timestamp_seconds("EventTime")) ORDER BY DATE_TRUNC('minute', M) LIMIT 10 OFFSET 1000;
Query 42 iteration 0 took 56.9 ms and returned 10 rows
Query 42 iteration 1 took 54.6 ms and returned 10 rows
Query 42 iteration 2 took 56.5 …
```
> fix: the average time for clickbench query compute should use new vec to make it compute for each query

- docs/source/contributor-guide/testing.md
- Related to https://github.com/apache/datafusion/issues/14319
- Follow on to https://github.com/apache/datafusion/pull/15101
@danila-b made a workflow action to run extended tests in https://github.com/apache/datafusion/pull/15101 and I would like to make sure it documented
Add a note in the contributor guide about how to run the tests
> Add documentation for `Run extended tests` command

- datafusion/physical-plan/src/joins/hash_join.rs
> Remove CoalescePartitions insertion from HashJoinExec

- datafusion/core/tests/memory_limit/mod.rs
- datafusion/physical-plan/src/sorts/sort.rs
related to https://github.com/apache/datafusion/issues/15372
One external sort query will panic due to an assertion failure
Compile and run `datafusion-cli` commit 46f40245
```
> set datafusion.execution.sort_spill_reservation_bytes = 0;
> select * from generate_series(1, 10000000) as t1(v1) order by v1;
thread 'tokio-runtime-worker' panicked at datafusion/physical-plan/src/sorts/sort.rs:406:9:
assertion failed: self.in_mem_batches_sorted
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
For background knowledge for external sort, check the doc in https://github.com/apache/datafusion/blob/46f4024577f4e13b79d8739849ecf51af5ddc7c2/datafusion/physical-plan/src/sorts/sort.rs#L80
Now a single field `in_mem_batches` is used to represent buffered data in different …
> fix: Assertion fail in external sort

- Cargo.lock
- datafusion/sql/Cargo.toml
- datafusion/sql/tests/sql_integration.rs
- Related #15397, this is a part of #15484 breaking down.
This is the part 1 of #15484 breakdown, as the code changes in #15484 is too large.
No
> Migrate datafusion/sql tests to insta, part1

- datafusion/expr/src/type_coercion/functions.rs
- datafusion/ffi/src/tests/mod.rs
- datafusion/ffi/src/tests/udf_udaf_udwf.rs
- datafusion/ffi/src/tests/utils.rs
- datafusion/ffi/src/udf/mod.rs
- datafusion/ffi/src/udf/return_info.rs
- datafusion/ffi/src/udf/return_type_args.rs
- datafusion/ffi/tests/ffi_integration.rs
- datafusion/ffi/tests/ffi_udf.rs
- datafusion/sql/tests/sql_integration.rs
- datafusion/sqllogictest/test_files/functions.slt
None
During testing for aggregate UDFs via FFI I discovered that if we have a UDF with a nullary type signature, it cannot use the coercion functions with arguments of zero lenght. This PR adjusts for that fact.
Additional testing showed that we need to implement `return_type_from_args` or some UDFs would fail. This PR implements it.
In addition to the two changes above, there are some moving around of the FFI integration tests now that they're getting larger. Basically I split them into a couple of files.
Unit test added.
> Allow type coersion of zero input arrays to nullary

- datafusion/common/src/scalar/mod.rs
- datafusion/functions/src/datetime/to_timestamp.rs
- datafusion/sqllogictest/test_files/timestamps.slt
- Closes #.
While working on this:
https://github.com/apache/datafusion/issues/14612
I found out that, when we enable `parse_float_as_decimal` as `true`.
`to_timestamp` and `as timestamp`  are converted into Decimal128 type.
So, creating a separate PR, which can help us support `Decimal` type for `timestamp` as well.
Adding support for Decimal128 for timestamps
```
> SELECT to_timestamp(1.1) as c1, cast(1.1 as timestamp) as c2, 1.1::timestamp as c3;
+-------------------------+-------------------------+-------------------------+
| c1                      | c2                      | c3                      |
+-------------------------+-------------------------+-------------------------+
| 1970-01-01T00:00:01.100 | 1970-01-01T00:00:01.100 | 1970-01-01T00:00:01.100 | …
```
> Decimal type support for `to_timestamp` 

- datafusion/core/benches/distinct_query_sql.rs
- datafusion/core/benches/topk_aggregate.rs
- Closes #15213 .
It is not certain, but it seems that plan creation and `collect()` should share the same runtime.. It is presumed that the issue occurred because RepartitionExec lazily polls within the runtime.
- https://github.com/apache/datafusion/blob/main/datafusion/physical-plan/src/repartition/mod.rs#L165-L177
- https://github.com/apache/datafusion/pull/10009
I will add more details if I find anything additional.
- Move the `Runtime::new()` into`bench_function`
- Ensure that plan creation (`ctx.sql()`) and `collect()` share the same runtime.
yes. below test are succeded
- `cargo bench -p datafusion --bench topk_aggregate`
- `cargo bench -p datafusion --bench distinct_query_sql`
No.
> FIX : some benchmarks are failing

- datafusion/sql/tests/sql_integration.rs
- Related #15397, #15497  this is a part of #15484 breaking down.
This is the part 2 of #15484 breakdown, as the code changes in #15484 is too large. Part1: #15497 
No
> Migrate `datafusion/sql` tests to insta, part2

- .github/actions/setup-rust-runtime/action.yaml
- Closes #15535
GH cache service is migrating and all users of the cache service (sccache for example) need to be updated.
github action update. sccache-action was disabled because neither the version nor the githash worked because of apache policies in place. A ticket with apache infra should be submitted to have the githash tests fixed.
Will be done in this PR
No.
> Disable sccache action to fix gh cache issue

- docs/source/user-guide/sql/data_types.md
- Closes #15464 .
The Decimal support in DataFusion was marked as complete in [Issue #3523](https://github.com/apache/datafusion/issues/3523) on November 21, 2024. However, the user guide documentation (`docs/source/user-guide/sql/data_types.md`) still labels it as "experimental," which is outdated and misleading. This PR updates the documentation to reflect the current status, improving user understanding and trust in the Decimal functionality.
- Updated the `Numeric Types` section in `docs/source/user-guide/sql/data_types.md` to remove the "experimental" label for `DECIMAL(precision, scale)`.
- Replaced the note with: "Decimal support has been fully implemented“
- Retained the link to #3523 for historical context.
No tests are included in this PR because it only modifies documentation …
> Update user guide to note decimal is not experimental anymore

- datafusion/physical-plan/src/sorts/sort.rs
- Closes #.
`ExternalSorter` supports `fetch` field for 'TopK' queries (e.g. `SELECT .... ORDER BY c1 LIMIT 10`), however it's not used now inside DataFusion. This might be due to `ExternalSorter` with limit is first implemented, and later a more optimized `TopK` data structure is used instead for such query pattern.
This `fetch` field then can be removed for simplicity.
Remove `fetch` field inside `ExternalSorter`
No, `ExternalSorter` is not a public interface.
> refactor: Cleanup unused `fetch` field inside `ExternalSorter`

- datafusion/core/benches/data_utils/mod.rs
- datafusion/core/benches/distinct_query_sql.rs
- datafusion/core/benches/topk_aggregate.rs
Since we have merged the utf8view support for aggregate topk, so also add the corresponding benchmark code in this PR.
https://github.com/apache/datafusion/pull/15152
Close part of  https://github.com/apache/datafusion/issues/15096
Since we have merged the utf8view support for aggregate topk, so also add the corresponding benchmark code in this PR.
Since we have merged the utf8view support for aggregate topk, so also add the corresponding benchmark code in this PR.
Yes
| Benchmark                                       | Min Time  | Median Time | Max Time  | Performance Change |
|------------------------------------------------|----------|------------|----------|-------------------|
| **Utf8 - time-series rows**                    | 987.96ms | 995.70ms   | 1.0035s  | +4.58% ~ +6.89%  |
| …
> Add utf8view benchmark for aggregate topk

- datafusion/sql/tests/sql_integration.rs
- Related #15397, #15497, #15499  this is a part of #15484 breaking down.
This is the part 3 of #15484 breakdown, as the code changes in #15484 is too large. Part1: #15497, Part2:  #15499
No
> Migrate datafusion/sql tests to insta, part3

- datafusion/datasource/src/file_scan_config.rs
- datafusion/proto/src/physical_plan/to_proto.rs
- Closes #14937.
Both `FileScanConfig` and `DataSource` has same statistics, it make that statistics may have out-of-sync bugs.
Remove redundant statistics from `FileScanConfig` and only a single statistics that held on the `DataSource`.
> Remove redundant statistics from FileScanConfig

- datafusion/core/tests/memory_limit/mod.rs
- datafusion/execution/src/disk_manager.rs
- datafusion/physical-plan/src/spill/in_progress_spill_file.rs
- datafusion/physical-plan/src/spill/spill_manager.rs
- Closes #15358 
See the rationale part of the first attempt PR https://github.com/apache/datafusion/pull/14975
The included changes and implementation are different than the above PR, it will be explained below.
1. Add `max_temp_directory_size` field inside `DiskManager` to keep track of current total disk usage for temporary files, by default it's 100GB.
2. Update `RefCountedTempFile`:
- Included a reference to `DiskManager` that created it
- Added a utility function `update_disk_usage()` to update the global disk usage. After modifying the managed tempfile, the caller also has to call this function to do the update, to make sure when disk limit is exceeded an error will be thrown. (Currently `RefCountedTempFile` is only used for spill files inside DataFusion, so I think this additional …
> feat: Add config `max_temp_directory_size` to limit max disk usage for spilling queries

- datafusion/core/tests/fuzz_cases/aggregate_fuzz.rs
- datafusion/physical-plan/src/aggregates/mod.rs
- datafusion/physical-plan/src/aggregates/row_hash.rs
- Closes #15530.
I think the PR below forgot to update the group by expressions:
- #13995
Update group by columns to be based on their index for merging phase 
Yes
No
> fix: update group by columns for merge phase after spill

- datafusion/datasource/src/file_groups.rs
- datafusion/datasource/src/statistics.rs
- Closes #.
Add Arc for statistics in FileGroup to avoid potentially deep Clone
> Minor: add Arc for statistics in FileGroup

- datafusion/optimizer/src/decorrelate.rs
- datafusion/optimizer/src/scalar_subquery_to_join.rs
- datafusion/optimizer/src/utils.rs
- datafusion/sqllogictest/test_files/subquery.slt
> fix: Queries similar to `count-bug` produce incorrect results

- datafusion/sqllogictest/test_files/joins.slt
- I added some slt tests to investigate #15549
This change adds SQL logic tests to validate support for accessing fields within compound (struct-like) columns during `JOIN` operations.
- Introduced two new tables: `compound_field_table_t` and `compound_field_table_u`, each containing a single column with a compound field (`{r: <string>, c: <number>}`).
- Added four test queries covering:
- Field access using string keys in `JOIN` conditions with aliases
- Same logic without using aliases
- Joins on numeric field values within the compound field
- Joins with combined conditions on both fields
- Added cleanup statements to drop the temporary tables after the tests
✅ Yes. This PR adds SQL logic tests directly into the `joins.slt` test suite. These queries act as both verification and …
> Add SQL logic tests for compound field access in JOIN conditions

- datafusion/ffi/src/table_provider.rs
- Closes #15569.
In ffi physical plan, if projection is empty, full schema will be returned
remove this logic. But I don't know are there any other scenarios that depend on this trikcy logic.
UT
No
> fix: ffi aggregation

- .github/workflows/audit.yml
- Part of https://github.com/apache/datafusion/issues/15571
We should be running the AUDIT check on all PRs to main so we don't see it for the first time on unrelated PRs
Add additional trigger for `audit` CI job on pushes to main
> Run audit CI check on all pushes to main

- datafusion/physical-plan/src/sorts/merge.rs
Related to:
- https://github.com/apache/datafusion/issues/15271
- Closes https://github.com/apache/datafusion/issues/15573
I saw in my code that clone and pop front and push takes some of the time from `poll_next_inner`
This is from my sampling
Before:
After:
1. Created custom `FixedSizeQueue` which avoid cloning the vector (could be avoided even without introducing this)
2. Not removing items instead just playing with indexes
Existing tests
No
> Perf: remove `clone` on `uninitiated_partitions` in SortPreservingMergeStream

- datafusion-cli/src/main.rs
- docs/source/user-guide/cli/usage.md
Closes #15553.
Allows users to specify a disk limit for spill queries.
A CLI option for users to specify a disk limit.
Yes, new CLI option in `datafusion-cli`.
> Add disk usage limit configuration to datafusion-cli

- .github/workflows/rust.yml
- datafusion/wasmtest/README.md
- datafusion/wasmtest/src/lib.rs
- datafusion/wasmtest/webdriver.json
Related to https://github.com/apache/datafusion/issues/13815 #15102 
While digging into another issue, I realized the wasm test was never actually executed in CI, and thus we don't know whether our previous tests will pass (although they build successfully)
1. This PR enables running wasm test in CI. I believe headless mode is supported as of 2025.
2. The snapshot test doesn't seem to support wasm: https://github.com/mitsuhiko/insta/issues/120, so I disabled it and has to use some ugly string match
> Actually run wasm test in ci

- datafusion/sql/tests/cases/diagnostic.rs
- datafusion/sql/tests/cases/plan_to_sql.rs
- Related #15397
- Related #15484,  #15497, #15499, #15533, #15548 , #15567
- this is a part of #15484 breaking down.
This is the part 5 of #15484 breakdown, as the code changes in #15484 is too large. Part1: #15497, Part2:  #15499, Part3: #15533, Part4: 15548, Part5: #15567
No
> Migrate datafusion/sql tests to insta, part6

- datafusion/sqllogictest/test_files/timestamps.slt
- Closes #14638 
https://github.com/apache/arrow-rs/pull/7141 enables casting from date to time zone-aware timestamps. (Included in [arrow 54.3.0](https://github.com/apache/arrow-rs/releases/tag/54.3.0)). 
This commit adds a SLT test case that tests against this feature.
> Add test case for new casting feature from date to tz-aware timestamps

- datafusion/physical-plan/src/joins/cross_join.rs
- datafusion/physical-plan/src/joins/hash_join.rs
- datafusion/physical-plan/src/joins/nested_loop_join.rs
- datafusion/physical-plan/src/joins/utils.rs
Continuing https://github.com/apache/datafusion/pull/15476 and https://github.com/apache/datafusion/pull/15418
> ## Rationale for this change + What changes are included in this PR?
> 
> The logic of HashJoin's `execute` implements differs from the other operators - The recursive call to the `execute` step of the build side are delayed until `collect_left_join` is poll'ed. This PR changes that to make it more alike to the standard implementations of `execute`.
> ## Are these changes tested?
> 
> No changes in behaviour are expected.
> ## Are there any user-facing changes?
> 
> No
Notable changes:
* Fixed the bug that caused test failures (partition 0 of the left side was executed multiple times)
* Applied the same changes the nested_loop_join and cross_join
> Remove CoalescePartitions insertion from Joins

- datafusion/common/src/functional_dependencies.rs
- datafusion/sql/src/statement.rs
- Closes #15443 
- doc is advising user to use a private function, that used to be public. 
doc fix + making `SqlToRel::new_constraint_from_table_constraints` public.
Yes, `SqlToRel::new_constraint_from_table_constraints` is public again.
> fix doc and broken api

- datafusion/sql/tests/cases/plan_to_sql.rs
- Closes #15397
- Related #15484,  #15497, #15499, #15533, #15548 , #15567, ##15578
- this is a part of #15484 breaking down.
This is the part 5 of #15484 breakdown, as the code changes in #15484 is too large. Part1: #15497, Part2:  #15499, Part3: #15533, Part4: 15548, Part5: #15567, Part6: #15578
No
> Migrate datafusion/sql tests to insta, part7

- .github/workflows/audit.yml
- Closes #15571 .
proc-macro-error are unmaintaned anymore, to fix the CI check we temporarily ignore it
ignored cargo audit proc-macro-error warning
yes, it a ci change should be test automatically
no
> ignore security_audit CI check proc-macro-error warning

- datafusion/physical-plan/src/repartition/mod.rs
- datafusion/sqllogictest/test_files/explain_tree.slt
- Closes #.
easy to understand because it means the number of `RepartitionExec` input's output partition number
Yes
explain tree displaying
> chore: improve RepartitionExec display tree 

- datafusion/physical-expr/benches/binary_op.rs
- part of https://github.com/apache/datafusion/issues/15631
- follow up to https://github.com/apache/datafusion/pull/15462
Some of these benchmarks were written for the wonderful analysis by @acking-you  in https://github.com/apache/datafusion/pull/15462 of bool_or vs count_ones. While they were helpful for that  analysis, they really are micro benchmarks for arrow kernels, not DataFusion so I think they don't belong in this repo.
Since most of the binary.rs operations call into arrow kernels, I didn't think adding more was useful at this time.
1. Remove arrow kernel benchmarks
2. rename the short circuit benchmarks
> Remove uneeded binary_op benchmarks 

- datafusion/core/tests/physical_optimizer/enforce_sorting.rs
- datafusion/physical-expr/src/equivalence/properties/mod.rs
- datafusion/physical-plan/src/sorts/sort.rs
- datafusion/physical-plan/src/topk/mod.rs
- datafusion/sqllogictest/test_files/topk.slt
- datafusion/sqllogictest/test_files/window.slt
- Closes #15529.
DataFusion currently implements an early termination optimization (TopK) for fully sorted data. However, many real-world datasets are only partially sorted (for example, a time-series dataset sorted by day but not within each day). This PR extends the TopK early termination optimization to recognize and leverage a common prefix between the input ordering and the query’s requested ordering. With this enhancement, once the top‑K buffer is full and subsequent rows are guaranteed to be worse based on the shared sort prefix, DataFusion can safely terminate scanning early. This change is expected to reduce unnecessary data scans and sorts, thereby significantly improving query performance and reducing resource consumption.
- **Sort Prefix Computation:**  
- Enhanced the …
> perf: Introduce sort prefix computation for early TopK exit optimization on partially sorted input (10x speedup on top10 bench)

- datafusion/common/src/config.rs
- Closes #15565.
warning is erroneous and confusing to the user.
only log warning if value != default
UT
No
> chore: avoid erroneuous warning for FFI table operation (only not default value)

- datafusion/physical-optimizer/src/aggregate_statistics.rs
Ignores a Clippy warning identified in https://github.com/apache/datafusion/pull/15625. Note, that this warning seems to be a false positive. I've submitted an issue with the Clippy project https://github.com/rust-lang/rust-clippy/issues/14566. Ideally we'd get this fixed upstream instead of having to add this ignore directive.
As mentioned in https://github.com/apache/datafusion/pull/15625#pullrequestreview-2748351074, we get a Clippy warning 
```
warning: parameter is only used in recursion
--> datafusion/physical-optimizer/src/aggregate_statistics.rs:48:9
|
48 |         config: &ConfigOptions,
|         ^^^^^^ help: if this is intentional, prefix it with an underscore: `_config`
|
note: parameter used here
--> datafusion/physical-optimizer/src/aggregate_statistics.rs:86:42
|
86 | …
```
> Ignore false positive only_used_in_recursion Clippy warning

- datafusion/datasource/src/write/demux.rs
- datafusion/sqllogictest/test_files/dictionary.slt
- Closes #15649 .
I added some sqllogictests.
> fix: dictionary encoded column to partition column casting bug

- datafusion/core/src/datasource/listing/table.rs
- datafusion/datasource/src/mod.rs
- datafusion/datasource/src/statistics.rs
- Closes https://github.com/apache/datafusion/issues/15615
- Part of #8229 
We are trying to improve statistics handling (so we can use it more). It turns out that the code to aggregate statistics in ListingTable was repliated with code already present in Precision
1. Remove redundant code
2. Deprecate one public method 
By existing CI
> Remove redundant `Precision` combination code in favor of `Precision::min/max/add`

- datafusion/core/tests/fuzz_cases/aggregate_fuzz.rs
- datafusion/core/tests/fuzz_cases/aggregation_fuzzer/fuzzer.rs
- datafusion/functions-aggregate/src/first_last.rs
- datafusion/sqllogictest/test_files/group_by.slt
- Closes #13998.
Achieved significant performance improvement when cardinality is high.
| benchmark sql                                                                                                                                                            | main    | thisPR |
| ------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | ------- | ------ |
| `select id2, id4, last_value(v1 order by id2, id4) as r2 from '~/h2o_100m.parquet' group by id2, id4;`                                                                   | 36.546s | 7.276s |
| `select l_shipmode, last_value(l_partkey order by l_orderkey, l_linenumber, l_comment, l_suppkey, l_tax) from …
> Improve performance of `last_value` by implementing special `GroupsAccumulator`

- Cargo.lock
- datafusion/physical-expr-common/src/physical_expr.rs
- datafusion/physical-expr/Cargo.toml
- datafusion/physical-expr/src/expressions/dynamic_filters.rs
- datafusion/physical-expr/src/expressions/mod.rs
- datafusion/physical-expr/src/lib.rs
- datafusion/physical-expr/src/utils/mod.rs
- datafusion/physical-optimizer/src/pruning.rs
- datafusion/proto/src/physical_plan/to_proto.rs
- Work towards #15512
This PR introduces:
- `PhysicalExpr::snapshot` to capture the current state of dynamic PhyscalExpr's for feeding into systems that match on concrete trait impls (namely PruningPredicate and protobuf serialization)
- Internal (private) helpers DynamicFilterSource and DynamicPhysicalExpr to make it easier to build dynamic PhysicalExpr, and to test and justify the snapshotting.
> Introduce DynamicFilterSource and DynamicPhysicalExpr

- datafusion/sql/src/unparser/dialect.rs
- datafusion/sql/src/unparser/expr.rs
- datafusion/sql/src/unparser/utils.rs
- Closes #15629
SQLite does not support timestamp/date scalars like `to_timestamp`, `from_unixtime`, `date_trunc`, etc.
For the `SqliteDialect`:
* Updates `from_unixtime` to `datetime(expr, 'unixepoch')`, expecting the input to be in seconds.
* Updates `date_trunc` to use the `strftime` function to format the timestamp as a string depending on the truncation unit.
* This is about as good as we can get with SQLite, given that dates and timestamps are all represented as strings in SQLite.
Yes. I've added new units tests in the unparser.
No.
> fix: Rewrite `date_trunc` and `from_unixtime` for the SQLite unparser

- datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs
- datafusion/sqllogictest/test_files/simplify_expr.slt
> fix decimal precision issue in simplify expression optimize rule

- datafusion/common-runtime/src/common.rs
Allows polling a `SpawnedTask`, instead of just joining it.
Required for #15654
An `impl Future` was added to `SpawnedTask`.
In addition, the underlying implementation is changed from `JoinSet` to a `JoinHandle` to simplify
the code, as `JoinSet` doesn't provide any additional benefits.
Documentation was also updated to make clearer what happens when `spawn_blocking` is called.
Added two tests that verify the behaviour on `spawn`.
No, although `SpawnedTask` is public so it does add to the API.
> Implement Future for SpawnedTask.

- datafusion/execution/src/memory_pool/mod.rs
- datafusion/execution/src/memory_pool/pool.rs
- Closes #15126 .
This makes an important change to the MemoryConsumer API, letting any memory pool identify which consumer is requesting the memory, and therefor separate consumers that might have the same name (for example, two AggregateExec operators in the same Partition)
This also modifies the TrackConsumer pool to adhere to these changes.
Nothing except the addition of  a unique identifier in the consumer, and an id() function to retrieve it.
All of the TrackedConsumer pool tests now verify this, as they have all been updated to accomodate the fact that the pool uses the IDs to track (the inner pool is unchanged in its behaviour atm)
This ensures the validity of the logic
Yes, MemoryConsumer is no longer clone-able, it is now moved into the register() function and thats it, to avoid …
> feat: Add unique id for every memory consumer

- datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs
- datafusion/sqllogictest/test_files/array.slt
- datafusion/sqllogictest/test_files/simplify_expr.slt
- Closes #15387
This pr adds a rule in ExprSimplifier to simplify x=x as follows.
- if x is not nullable, x=x -> true
- else, x=x -> x is NOT NULL
Yes, via unit test and slt
> Enhance: simplify `x=x` --> `x IS NOT NULL OR NULL`

- datafusion/sql/src/select.rs
- datafusion/sqllogictest/test_files/window.slt
- Closes #15605.
ident normalizer is not called.
normalize ident before comparing window name.
UT
NO
> fix: normalize window ident

- datafusion/physical-plan/src/spill/mod.rs
- datafusion/physical-plan/src/spill/spill_manager.rs
- Closes https://github.com/apache/datafusion/issues/15323.
The previous design of reading spill files was a `push` design, spawning
long lived blocking tasks which repeatedly read records, send them and
wait until they are received. This design had an issue where progress
wasn't guaranteed (i.e., there was a deadlock) if there were more spill
files than the blocking thread pool in tokio which were all waited for
together.
To solve this, the design is changed to a `pull` design, where blocking
tasks are spawned for every read, removing waiting on the IO threads and
guaranteeing progress.
While there might be an added overhead for repeatedly calling
`spawn_blocking`, it's probably insignificant compared to the IO cost of
reading from the disk.
Added a test which causes a deadlock in `main` …
> Remove waits from blocking threads reading spill files.

- datafusion/core/tests/memory_limit/memory_limit_validation/utils.rs
Currently the memory limit tests hang due to lock contention and the overhead from frequently calling `sysinfo::System::refresh_all()` in the memory monitoring task. 
In fact, we don't really need to refresh all info, it's enough to just get the memory data about the current process, which significantly reduces the refresh time and the tests finish quickly.
In the memory limit utils, the memory monitoring spawned task now refreshes system info only for what's actually necessary.
It's part of the tests, and they seem to not hang anymore :)
No
> tests: only refresh the minimum sysinfo in mem limit tests.

- .github/workflows/extended.yml
- .github/workflows/pr_comment_commands.yml
Triggering extended tests failed here: https://github.com/apache/datafusion/actions/runs/14439917392
For creating a workflow with workflow_dispatch, you can't specify a branch name in another repo as the ref.
Instead you need a local branch name and to send which PR to checkout as a parameter.
It sucks a bit that in the Actions list it looks like a test on `main`, but I'm not sure there's a better alternative.
Here's the trigger working in https://github.com/ashdnazg/datafusion/pull/1 with the correct hash being used: https://github.com/ashdnazg/datafusion/actions/runs/14443854280/job/40499839662#step:2:3
Here's the test working as usual on push to main: https://github.com/ashdnazg/datafusion/actions/runs/14443836470/job/40499776589#step:2:2
No
> ci: fix workflow triggering extended tests from pr comments.

- docs/source/user-guide/sql/explain.md
- Closes #15705 
#15427 changed the default EXPLAIN format to `tree`.
This PR updates the EXPLAIN documentation to reflect that the `tree` format is now the default, instead of `indent`. This reordering ensures that users see the format that matches actual output first, improving clarity and user experience when reading or debugging EXPLAIN plans.
- Changed section heading to state that `tree` is the default format.
- Moved the `tree` format section above the `indent` format section for logical flow.
- No functional changes—documentation update only.
Not applicable. These are documentation-only changes and do not impact functionality.
Yes. The documentation now:
- Reflects the `tree` format as the default EXPLAIN output.
- Presents the `tree` format example first for easier reference.
- …
> Make tree the Default EXPLAIN Format and Reorder Documentation Sections

- datafusion/functions-aggregate/src/string_agg.rs
- datafusion/sqllogictest/test_files/aggregate.slt
- datafusion/sqllogictest/test_files/information_schema.slt
- docs/source/user-guide/sql/aggregate_functions.md
- Closes #8260.
See https://github.com/apache/datafusion/pull/14413 first.
Complete the missing functionality of the STRING_AGG function.
Adds support for DISTINCT and ORDER_BY clauses by reusing the existing ARRAY_AGG functionality and building the whole STRING_AGG aggregation function on top of it. This way, the full STRING_AGG functionality is automatically implemented [almost] for free.
The rationale for reusing the ARRAY_AGG functionality is because both functions are very similar, with just two minor diferences:
- STRING_AGG works only with strings, while ARRAY_AGG works with any type.
- The return of STRING_AGG is the same as ARRAY_AGG, but with the resulting array of strings joined by a delimiter.
In order to have the full STRING_AGG functionality, some small addition is also …
> STRING_AGG missing functionality

- datafusion/physical-plan/src/sorts/sort.rs
- Closes https://github.com/apache/datafusion/issues/15675
I noticed an internal error in the sort implementation. This PR is exposing it as a proper user-facing error instead.
If a user hits this condition, they now receive a `DataFusionError:ResourcesExhausted` instead of `DataFusionError::Internal`.
Yes.
In away, the code now exposes a different error to the user facing API. However, since the old error was internal, this was a bug and I don't expect any documentation changes are necessary.
> Fix internal error in sort when hitting memory limit

- Cargo.lock
- Closes https://github.com/apache/datafusion/issues/15724
Get a clean CI run
I suspect some sort of logical conflict or something
Checked in the local copy of Cargo.lock on my machine
> Update checked in Cargo.lock file to get clean CI

- datafusion/physical-plan/src/repartition/mod.rs
- datafusion/sqllogictest/test_files/explain_tree.slt
- Closes #.
Now output partition count is displayed inside `()` after partition scheme like `RoundRobin`
```
13)┌─────────────┴─────────────┐
14)│      RepartitionExec      │
15)│    --------------------   │
16)│   input_partition_count:  │
17)│             1             │
18)│                           │
19)│    partitioning_scheme:   │
20)│     RoundRobinBatch(4)    │
21)└─────────────┬─────────────┘
```
This number's meaning is not obvious, this PR let this output partition count to be displayed separately
```
13)┌─────────────┴─────────────┐
14)│      RepartitionExec      │
15)│    --------------------   │
16)│   input_partition_count:  │
17)│             1             │
18)│                           │
19)│  output_partition_count:  │
20)│             4             │
21)│ …
```
> Minor: include output partition count of `RepartitionExec` to tree explain

- dev/changelog/47.0.0.md
- part of https://github.com/apache/datafusion/issues/15072
Get final few PRs that were merged prior to 47 branch
Run
```shell
./dev/release/generate-changelog.py 46.0.0 HEAD 47.0.0 > dev/changelog/47.0.0.md
npx prettier@2.7.1 --write             '{datafusion,datafusion-cli,datafusion-examples,dev,docs}/**/*.md'             '!datafusion/CHANGELOG.md'             README.md             CONTRIBUTING.md
```
> [branch-47] Final release note touchups

- datafusion/physical-plan/src/sorts/sort.rs
> minor: fix doc comment

- datafusion-examples/examples/sql_dialect.rs
- datafusion/sql/src/parser.rs
- datafusion/sql/tests/cases/diagnostic.rs
- datafusion/sqllogictest/test_files/copy.slt
- datafusion/sqllogictest/test_files/create_external_table.slt
- Closes #14437.
converting ParserError into DataFusionError to attach diagnostic through `expected`.
> Attach Diagnostic to syntax errors

- datafusion/functions-nested/src/flatten.rs
- datafusion/sqllogictest/test_files/array.slt
- Closes #13757
Parity with the `flatten` implementation in duckdb.
Remove the recursion in `flatten_internal` so that only the top level elements are flattened.
Existing sqllogictests have been updated.
Yes, `flatten` no longer recursively flattens the array
> Change `flatten` so it does only a level, not recursively

- datafusion/physical-expr/benches/binary_op.rs
- datafusion/physical-expr/src/expressions/binary.rs
- Closes #15636
You can learn the reason behind this PR by reviewing the discussion in this issue: https://github.com/apache/datafusion/issues/15631#issuecomment-2798871646
Many thanks to @kosiew for doing a tremendous amount of work. Based on his PR https://github.com/apache/datafusion/pull/15648, I have made the following changes:
1. Performance test cases have been added for "all false" in AND operations and "all true" in OR operations.
2. Reduce some unnecessary function calls: for instance, `false_count` and `true_count` can be unified as `values().count_set_bits()` in non-null cases, which would eliminate two calls to `nulls_count` and one call to `true_count`.
3. Add heuristic pre-selection under the `and` operation. For more details on the principle, you can refer to: …
> Apply pre-selection and computation skipping to short-circuit optimization

- datafusion/proto/proto/datafusion.proto
- datafusion/proto/src/generated/prost.rs
- datafusion/proto/src/logical_plan/mod.rs
- datafusion/proto/tests/cases/roundtrip_logical_plan.rs
- Closes #15718.
partition columns should exclude file schema in listing table
1. update partition column type in proto
2. remove partition columns from ListingTableScanNode schema.
UT
No
> fix: serialize listing table without partition column

- datafusion/proto-common/src/common.rs
- datafusion/proto/src/logical_plan/mod.rs
- Follow on to https://github.com/apache/datafusion/pull/15737
I noticed a potential simplification while reviewing https://github.com/apache/datafusion/pull/15737 from @chenkovsky
> Minor: simplify code in datafusion-proto

- datafusion/optimizer/src/optimize_projections/mod.rs
- Closes #.
If the two projections have same exprs (my real case). We can directly remove the current projection and return the child projection. Avoid really running the `merge_consecutive_projections` method. This would improve performance if the projections have many exprs
```rust
use criterion::{criterion_group, criterion_main, Criterion};
use datafusion_common::{DFSchema, ScalarValue, Result};
use datafusion_expr::{col, lit, Expr, LogicalPlan, Projection};
use std::sync::Arc;
use datafusion_optimizer::optimize_projections::{merge_consecutive_projections, merge_consecutive_projections_v2};
/// Creates a projection with another projection as input, both with n expressions
fn create_nested_projection(n_exprs: usize) -> Result<Projection> {
// Create a simple empty relation as the base …
```
> Add a fast path for `optimize_projection`

- datafusion/optimizer/src/optimize_projections/mod.rs
- Closes #.
In our prod, we found that the `optimize_projection` is slow when the number of columns is large, and `is_projection_unnecessary` is a bottleneck. After checking the method, I found we can improve it.
Here is the benchmark:
v1 is the old and v2 is the optimized version
```
Projection Optimization/v1_one_non_trivial
time:   [92.212 µs 93.578 µs 95.428 µs]
Found 16 outliers among 100 measurements (16.00%)
14 (14.00%) high severe
Projection Optimization/v2_one_non_trivial
time:   [242.52 ns 248.62 ns 256.51 ns]
5 (5.00%) high severe
```
1000 exprs in Projection, and one of them is non-trival expr.
```rust
use arrow::datatypes::{DataType, Field, Schema};
use criterion::{criterion_group, …
```
> Speed up `optimize_projection` by improving `is_projection_unnecessary`

- datafusion/expr-common/src/type_coercion/aggregates.rs
- datafusion/functions-aggregate/src/average.rs
- datafusion/sqllogictest/test_files/aggregate.slt
- re #15458
Enable support for averaging `Duration` type
Added accumulator to compute the Avg of `Duration` types, would add support for `GroupsAccumulator` in a follow-up PR.
Yes.
Yes.
> Support `Accumulator` for avg duration

- datafusion/core/tests/expr_api/simplification.rs
- datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs
- datafusion/optimizer/src/simplify_expressions/simplify_exprs.rs
- Closes #.
Before:
```
[2025-04-16T10:30:23Z DEBUG datafusion_optimizer::utils] Optimizer input (pass 0):
Projection: t.a
Filter: CAST(t.a AS Int64) BETWEEN Int64(3) AND Int64(3)
TableScan: t
[2025-04-16T10:30:23Z DEBUG datafusion_optimizer::optimizer] Plan unchanged by optimizer rule 'eliminate_nested_union' (pass 0)
[2025-04-16T10:30:23Z DEBUG datafusion_optimizer::utils] simplify_expressions:
Projection: t.a
Filter: t.a = Int32(3)
TableScan: t
...
[2025-04-16T10:30:23Z DEBUG datafusion_optimizer::utils] push_down_filter:
Projection: t.a
Filter: t.a = Int32(3)
TableScan: t
...
[2025-04-16T10:30:23Z DEBUG datafusion_optimizer::utils] optimize_projections:
Filter: t.a = Int32(3)
TableScan: t projection=[a]
[2025-04-16T10:30:23Z DEBUG datafusion_optimizer::utils] Optimized plan (pass 0): …
```
> Improve `simplify_expressions` rule

- datafusion/datasource-parquet/src/file_format.rs
- datafusion/datasource-parquet/src/source.rs
- datafusion/sqllogictest/test_files/create_external_table.slt
- datafusion/sqllogictest/test_files/parquet.slt
- Closes #15721.
coerce_int96 is ignored when infer schema.
call coerce_int96_to_resolution when fetching schema
UT
No
> fix: describe Parquet schema with coerce_int96

- datafusion/sql/src/parser.rs
- Closes https://github.com/apache/datafusion/issues/15623.
- Added `recursion_limit` (available through SQL parser options) field to `DFParser`
struct to track the current recursion limit
- Updated error handling to include the current recursion limit value in error messages
- Ensured consistent error handling for recursion limit across different parsing scenarios:
- `COPY INTO` statements
- General statement parsing
- Native and sqlparser-rs parser paths
- Updated error message format would be:
`SQL error: RecursionLimitExceeded (current limit: {recursion_limit})`
> Show current SQL recursion limit in RecursionLimitExceeded error message

- datafusion/sqllogictest/test_files/aggregate.slt
> Minor: fix flaky test in `aggregate.slt`

- datafusion/physical-optimizer/src/limit_pushdown.rs
This PR removed the unused logic, why it's unused?
Because now we have 
Because now we have unified DataSourceExec and with fetch support, so the limit pushdown can be pushed to DataSourceExec, the corner case will not happen for this logic.
For example:
```rust
query TT
explain select * from testSubQueryLimit as t1 join (select * from testSubQueryLimit limit 10) limit 2;
----
logical_plan
01)Limit: skip=0, fetch=2
02)--Cross Join: 
03)----SubqueryAlias: t1
04)------Limit: skip=0, fetch=2
05)--------TableScan: testsubquerylimit projection=[a, b], fetch=2
06)----Limit: skip=0, fetch=2
07)------TableScan: testsubquerylimit projection=[a, b], fetch=2
physical_plan
01)GlobalLimitExec: skip=0, fetch=2
02)--CrossJoinExec
03)----DataSourceExec: partitions=1, partition_sizes=[1], fetch=2 …
```
> Minor: remove unused logic for limit pushdown

- datafusion/expr/src/logical_plan/builder.rs
- datafusion/expr/src/logical_plan/plan.rs
- Closes #14363.
This PR adds a new `Join::try_new()` constructor method that:
- Automatically computes the correct schema based on join type
- Leverages the existing `build_join_schema()` function
- Handles all join types correctly (Inner, Left, Right, Full, Semi, Anti, and LeftMark)
- Additionally, it updates the `LogicalPlanBuilder`:
- `cross_join()`
- `join_with_expr_keys()`
- `join_using()`
to use the new `try_new` method instead of manual schema computation.
> Add try_new for LogicalPlan::Join

- datafusion/core/src/execution/session_state.rs
- Closes #.
I found some unnecessary struct creation in `SessionStateBuilder::build` due to using `unwrap_or`, and switch to `unwrap_or_else` can eliminate them.
Use `unwrap_or_else` to slightly improve `SessionStateBuilder::build`.
Not need
No.
> Minor: eliminate unnecessary struct creation in session state build

- datafusion/core/tests/physical_optimizer/enforce_distribution.rs
- datafusion/physical-optimizer/src/enforce_distribution.rs
- Closes #.
If SPM contains `fetch`, then fetch will be missing in the `replace_order_preserving_variants` method during the `EnforceDistribution` optimizer.
To avoid missing `fetch`
Yes, ut
> Fix: fetch is missing in `replace_order_preserving_variants` method during `EnforceDistribution` optimizer

- Cargo.lock
- datafusion/optimizer/Cargo.toml
- datafusion/optimizer/benches/projection_unnecessary.rs
- datafusion/optimizer/src/optimize_projections/mod.rs
- Closes #.
We found the `is_projection_unnecessary` method is costly if there are many exprs in projection, and is a bottleneck in the `optimize_projection` rule
Speed up the `is_projection_necessary function`
1. Add the check for the `exprs` length with the `input.schema()`
2. Optimize the way of checking if the projection can be removed.
```
projection_unnecessary_comparison/is_projection_unnecessary_v2
time:   [3.1893 µs 3.2122 µs 3.2391 µs]
Found 6 outliers among 100 measurements (6.00%)
1 (1.00%) low mild
3 (3.00%) high severe
projection_unnecessary_comparison/is_projection_unnecessary
time:   [4.0953 ms 4.1299 ms 4.1644 ms]
Found 25 outliers among 100 measurements (25.00%)
10 (10.00%) low severe
12 (12.00%) high mild
3 (3.00%) high severe
```
Yes, by existing …
> Speed up `optimize_projection`

- datafusion/sql/src/unparser/ast.rs
- datafusion/sql/src/unparser/plan.rs
- datafusion/sql/tests/cases/plan_to_sql.rs
- Closes #15813
Adds support for correctly round-tripping SQL queries that rely on the distinct properties of the `UNION` set operator.
Keeps track of whether a Distinct node is the direct parent of a Union node in the Unparser's QueryBuilder. If so, then when the Union node is being processed the SetModified is set to `None` rather than `All`. That will cause the sqlparser AST to correctly emit the `UNION` SQL operator.
Yes, I've added a new SQL roundtrip test that would have failed previously.
No
> Support unparsing `UNION` for distinct results

- datafusion/execution/src/memory_pool/mod.rs
- datafusion/execution/src/memory_pool/pool.rs
> Add `MemoryPool::memory_limit`  to expose setting memory usage limit

- datafusion/core/tests/execution/logical_plan.rs
- datafusion/expr/src/logical_plan/builder.rs
> Preserve projection for inline scan

- datafusion/core/tests/physical_optimizer/enforce_sorting.rs
- datafusion/core/tests/physical_optimizer/replace_with_order_preserving_variants.rs
- datafusion/physical-optimizer/src/enforce_sorting/mod.rs
- datafusion/physical-optimizer/src/enforce_sorting/replace_with_order_preserving_variants.rs
- Closes #.
fetch is missing in `EnforceSorting` optimizer (two places)
Retain `fetch`
Yes, by ut and existing tests.
> Fix: fetch is missing in `EnforceSorting` optimizer (two places)

- datafusion/sql/src/unparser/expr.rs
- datafusion/sql/tests/cases/plan_to_sql.rs
SQL Unparser incorrectly handles `ILIKE` expressions, handling all as `LIKE`, ignoring `case_insensitive` flag.
Case sensitivity shouldn't be ignored in `ILIKE` expressions, as it's a part of the SQL standard.
Added correct handling for `case_insensitive` flag in `ILIKE` expressions in SQL unparser
Yes, covered by additional SQL roundtrip test in plan_to_sql, fixed and extended expressions tests for LIKE/ILIKE.
No
> Fix `ILIKE` expression support in SQL unparser

- datafusion/common/src/error.rs
- datafusion/sql/src/expr/function.rs
- datafusion/sql/src/expr/subquery.rs
- datafusion/sql/src/expr/unary_op.rs
- datafusion/sql/src/parser.rs
- datafusion/sql/src/set_expr.rs
- datafusion/sql/src/utils.rs
```
this actually gives me an idea that `err!` should support diagnostics as optional param, so we can remove extra `map_err`
```
_Originally posted by @comphead in https://github.com/apache/datafusion/pull/15680#discussion_r2047736900_
- Closes #.
> Make `Diagnostic` easy/convinient to attach by using macro and avoiding `map_err`

- datafusion/physical-optimizer/src/pruning.rs
Adds support for dictionaries and some more primitive types to pruning predicate.
I encountered this when feeding in a stats schema with dictionary encoded columns.
I see no reason we can't support this.
> predicate pruning: support cast and try_cast for more types

- datafusion/core/tests/physical_optimizer/replace_with_order_preserving_variants.rs
- datafusion/physical-optimizer/src/enforce_sorting/replace_with_order_preserving_variants.rs
- Closes #.
Another `fetch` missing
Yes
> Fix: fetch is missing in `plan_with_order_breaking_variants` method

- datafusion/physical-optimizer/src/enforce_sorting/replace_with_order_preserving_variants.rs
- Closes #.
There was a new pr (https://github.com/apache/datafusion/pull/15842) which use old `ExecutionPlan::with_fetch` method merged, it should be changed to use correct `with_fetch` method.
> Fix build failure caused by new `CoalescePartitionsExec::with_fetch` method

- datafusion/common/src/scalar/mod.rs
It does not close any specific issue but it's related to #10856
Previously, the function that compares two ScalarValue lists only worked when the two lists have the same length. Engines usually can compare lists of arbitrary length, considering the longer list greater if all the other elements are equal.
This is some preliminary work need for the following PR to work:
- https://github.com/apache/datafusion/pull/15857
Add support for comparing ScalarValue::List of arbitrary length + some tests
Yes, by current tests and some new ones
I don't think so
> Fix ScalarValue::List comparison when the compared lists have different lengths

- datafusion/core/src/execution/session_state.rs
- Closes #.
Currently when getting the error when custom UDF is not registered
```
called `Result::unwrap()` on an `Err` value: DataFusionError("There is no UDF named \"comet_array_repeat\" in the registry")
```
it is not clear if the fix is under user control or not. Adding more details to error message
> chore: More details to `No UDF registered` error

- datafusion/physical-optimizer/src/pruning.rs
N/A
Follow-up for https://github.com/apache/datafusion/pull/15764/files#r2051508562 - removes unexpected stdout logging.
Changes `dbg!` to `log::debug!`
N/A
No
> Remove usage of `dbg!`

- datafusion/functions/src/datetime/from_unixtime.rs
- docs/source/user-guide/sql/scalar_functions.md
The documentation says nanoseconds but the given example is using seconds, so I believe seconds is the correct unit?
> Fix `from_unixtime` function documentation

- datafusion/expr-common/src/interval_arithmetic.rs
- datafusion/physical-expr/src/equivalence/properties/mod.rs
- Closes #.
We don't need additional check for the same value.
> Minor: Interval singleton

- docs/source/library-user-guide/upgrading.md
- Closes #.
I noticed that https://datafusion.apache.org/library-user-guide/upgrading.html#filescanconfig-filescanconfigbuilder had "FileScanConfig –> FileScanConfigBuilder" as a top-level headline. It should probably be under the 47 release
> Upgrade-guide: Downgrade "FileScanConfig –> FileScanConfigBuilder" headline

- datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs
- datafusion/sqllogictest/test_files/strings.slt
- Closes #15835.
Bugfix
Bugfix and unit test cases for the optimization.
Yes.
This changes the behavior of ILIKE.
> fix: Avoid mistaken ILike to string equality optimization

- Cargo.lock
- datafusion/common/src/stats.rs
- datafusion/core/src/datasource/listing/table.rs
- datafusion/core/src/datasource/mod.rs
- datafusion/datasource/src/file_groups.rs
- datafusion/datasource/src/schema_adapter.rs
- datafusion/sqllogictest/test_files/listing_table_statistics.slt
- Closes https://github.com/apache/datafusion/issues/15689
As said in https://github.com/apache/datafusion/issues/15689
> Map file-level column statistics to the table-level

- datafusion/functions-aggregate/benches/array_agg.rs
- datafusion/functions-aggregate/src/array_agg.rs
- datafusion/sqllogictest/test_files/aggregate.slt
- Closes #13742
- Part of #9924
See the linked issues.
Take into account the `ignore_nulls` flag from `AccumulatorArgs`.
Yes, added SLT tests.
`ArrayAggAccumulator` constructors take an `ignore_nulls` flag.
> Respect ignore_nulls in array_agg

- datafusion/physical-plan/src/joins/hash_join.rs
- Closes #15620.
The hash join seed is hard-coded to a different value that the RepartitionExec seed.
No.
> Set HashJoin seed

- datafusion/expr-common/src/signature.rs
- datafusion/expr/src/type_coercion/functions.rs
- datafusion/functions-nested/src/cardinality.rs
- datafusion/functions-nested/src/concat.rs
- datafusion/functions-nested/src/dimension.rs
- datafusion/functions-nested/src/distance.rs
- datafusion/functions-nested/src/empty.rs
- datafusion/functions-nested/src/extract.rs
- datafusion/functions-nested/src/make_array.rs
- datafusion/functions-nested/src/max.rs
- datafusion/functions-nested/src/set_ops.rs
- datafusion/functions-nested/src/sort.rs
- datafusion/functions-nested/src/utils.rs
- datafusion/sqllogictest/test_files/array.slt
- datafusion/sqllogictest/test_files/unnest.slt
- Part of #7142
#10790 changed empty arrays to default to `Int64` but that is just a band-aid which creates other problems downstream, e.g. type errors when nesting expressions. It also introduced a bug (and possible panic) in `array_union` and `array_intersect` which are fixed here.
Apart from that, from a type-theoretical PoV empty arrays **should** indeed be typed as `Array<Null>` because `Null` is coercible to any other type and by extension (immutable arrays are covariant) `Array<Null>` is coercible to any other array type.
The crux of the problem is that Arrow is incapable of dealing with the mismatching array types that arise from this encoding. To workaround this limitation of Arrow, we unify array function argument types in advance and coerce them to the common type. In addition, …
> Saner handling of nulls inside arrays

- datafusion/functions-nested/src/flatten.rs
- Closes https://github.com/apache/datafusion/issues/15896
- Closes https://github.com/apache/datafusion/pull/15899
After #15149, `flatten` stopped working for `List(FixedSizeList)` because it expected the inner fixed size list to be casted to list, which wasn't happening anymore.
Looking back, #15160 correctly stopped using [ArrayFunctionSignature::RecursiveArray](https://docs.rs/datafusion/latest/datafusion/logical_expr/enum.ArrayFunctionSignature.html#variant.RecursiveArray), which I expected would make only the top level list be coerced, and it would break, but it didn't. It appears that recursive lists continued to be coerced
And then #15149 refactored that code path with the correct behavior, exposing the issue in `flatten`
If the inner value is a fixed size list, it get's coerced …
> Fix `flatten` scalar function when inner list is `FixedSizeList`

- datafusion/expr/src/expr.rs
- Closes #15863
Placeholders are currently limited to certain expressions.
This PR addes placeholder inference in the following additional expressions:
- `Expr::InList`
- `Expr::Like`
- `Expr::SimilarTo`
Yes
Yes, placeholders are supported in additional expressions.
> infer placeholder datatype for IN lists

- datafusion/sql/src/unparser/plan.rs
- datafusion/sql/tests/cases/plan_to_sql.rs
> Unparse `UNNEST` projection with the table column alias

- datafusion/spark/src/function/utils.rs
Fixes CI after https://github.com/apache/datafusion/pull/15168
> Fix CI in main

- datafusion/spark/src/function/utils.rs
- Follow on to https://github.com/apache/datafusion/pull/15917 from @blaginin 
I was reviewing the macro added in https://github.com/apache/datafusion/pull/15917 and thought I could make it slightly simpler
> Minor: cleanup datafusion-spark scalar functions

- benchmarks/queries/clickbench/README.md
- datafusion/sqllogictest/test_files/clickbench_extended.slt
- Closes https://github.com/apache/datafusion/issues/15927
See https://github.com/apache/datafusion/issues/15927
TLDR is that we improved the syntax for APPROX_PERCENTILE_CONT but did not update the corresponding benchmark query
Update benchmark query, add tests
I also verified the new syntax gets the same answer as the old syntax in datafusion 47:
DataFusion 47 with old query:
```sql
(venv) andrewlamb@Andrews-MacBook-Pro-2:~/Downloads$ ~/Software/datafusion-cli/datafusion-cli-47.0.0
DataFusion CLI v47.0.0
> SELECT "ClientIP", "WatchID",  COUNT(*) c, MIN("ResponseStartTiming") tmin, APPROX_PERCENTILE_CONT("ResponseStartTiming", 0.95) tp95, MAX("ResponseStartTiming") tmax
FROM 'hits.parquet'
WHERE "JavaEnable" = 0 -- filters to 32M of 100M rows
GROUP BY  "ClientIP", "WatchID"
HAVING c > 1 …
```
> Fix ClickBench extended queries after update to APPROX_PERCENTILE_CONT

- datafusion/sqllogictest/test_files/listing_table_statistics.slt
- N/A
There were some sqllogictests writing to `/tmp/...`, which on Windows works but writes to `C:/tmp/...`. This means that the physical plans will report different paths for Windows and Linux/MacOS.
- `listing_table_statistics.slt` - writes files to the standard path `test_files/scratch` instead of `/tmp`.
Yes.
No.
> fix: sqllogictest on Windows

- datafusion/datasource-parquet/src/file_format.rs
- datafusion/datasource-parquet/src/row_filter.rs
- datafusion/sqllogictest/test_files/parquet_filter_pushdown.slt
> fix query results for predicates referencing partition columns and data columns

- datafusion/substrait/src/logical_plan/producer.rs
- Closes #15855
fix a error where `SELECT NULL::DOUBLE` can't be encode to substrait
replace `cast(NULL, <data type>)` to typed null in substrait
unit tests are added, also downstream code also have test them
shouldn't be any, simply a constant folding shouldn't affect downstream system
> fix: fold cast null to substrait typed null

- datafusion/physical-plan/src/aggregates/group_values/single_group_by/primitive.rs
> Reduce rehashing cost for primitive grouping by also reusing hash value

- .github/workflows/docs_pr.yaml
- Closes #15951 
@alamb  noticed that some CI jobs are doing the same task with the different names and thus adding an extra 15 minutes in the CI jobs .thus , this two same jobs are unnecessary and need to be handle 
Updates the `docs_pr.yaml`
> [Update] : Removal of duplicate CI jobs

- datafusion/physical-plan/src/aggregates/group_values/multi_group_by/bytes.rs
- Closes #15967.
See issue description
When appending values in `ByteGroupValueBuilder` we check for overflows of the underlying `OffsetSizeTrait` type
There is a test which reproduces the segfault without this fix
No
> Segfault in ByteGroupValueBuilder

- datafusion/datasource-parquet/src/mod.rs
Followup to #15971. I forgot to re-export it 🤦🏻 and there's obviously no test to make sure the function is public...
> re-export can_expr_be_pushed_down_with_schemas to be public

- datafusion/optimizer/src/extract_equijoin_predicate.rs
- datafusion/optimizer/src/scalar_subquery_to_join.rs
- datafusion/optimizer/src/single_distinct_to_groupby.rs
- datafusion/optimizer/src/test/mod.rs
- Related #15396 , #15446, #15884, #15893, #15937
This is the part 5 of #15396  
No
> Migrate Optimizer tests to insta, part5

- datafusion/catalog/src/information_schema.rs
- datafusion/common/src/types/native.rs
- datafusion/sqllogictest/test_files/information_schema.slt
- Related to https://github.com/apache/datafusion/issues/13371
Previously, we showed the physical type name for the function parameter type. However, it produces too many similar records for a function. For example, if we try to get the parameters of `string_agg`, we will get the result:
```
datafusion public string_agg 1 IN expression LargeUtf8 NULL false 0
datafusion public string_agg 2 IN delimiter Utf8 NULL false 0
datafusion public string_agg 1 OUT NULL LargeUtf8 NULL false 0
datafusion public string_agg 1 IN expression LargeUtf8 NULL false 1
datafusion public string_agg 2 IN delimiter LargeUtf8 NULL false 1
datafusion public string_agg 1 OUT NULL LargeUtf8 NULL false 1
datafusion public string_agg 1 IN expression LargeUtf8 NULL false 2
datafusion public string_agg 2 IN delimiter …
```
> Show LogicalType name for `INFORMATION_SCHEMA`

- datafusion/core/src/datasource/physical_plan/mod.rs
- datafusion/datasource-avro/src/source.rs
Part of  #15950 .
The `AvroExec` structure was deprecated in DataFusion 46 and is scheduled for removal. Development and testing primarily focus on the `DataSourceExec`. This makes it likely that `AvroExec` is "rot rotting" – meaning it may not function correctly but we have no tests covering its functionality. This can lead to a poor user experience if users attempt to use this unsupported path.
Removed `AvroExec`
Passed unit tests
Yes, remove deprecated API
> refactor: remove deprecated `AvroExec`

- datafusion/datasource-parquet/src/mod.rs
- datafusion/datasource-parquet/src/opener.rs
- Closes #16008.
This pull request refactors the `should_enable_page_index` function by relocating it from `mod.rs` to `opener.rs` to simplify the code and improve maintainability
Moved `should_enable_page_index` from `mod.rs` to `opener.rs` within the `datafusion/datasource-parquet`
Passed unit tests
No
> refactor:  move `should_enable_page_index` from `mod.rs` to `opener.rs`

- datafusion/proto/src/logical_plan/from_proto.rs
- datafusion/proto/src/physical_plan/from_proto.rs
- datafusion/proto/src/physical_plan/mod.rs
- datafusion/proto/tests/cases/roundtrip_logical_plan.rs
- datafusion/proto/tests/cases/serialize.rs
Falls back to the codec hook when the UDF is not present in the `SessionContext`.
- Closes #15996.
We need this for more flexible logical plan decoding.
There isn't a lot of test coverage for this code, but there is one test that has a different error message now.
This conservatively avoids any breaking changes for users of `datafusion-proto`.
> feat(proto): udf decoding fallback

- docs/source/library-user-guide/upgrading.md
- part of https://github.com/apache/datafusion/issues/15950
As suggested by @comphead  on https://github.com/apache/datafusion/pull/16005#issuecomment-2873058448 we should include a note about the removal of structures prior to their expected removal
1. Add note to the upgrade guide about removal
> Add note to upgrade guide for removal of `ParquetExec`, `AvroExec`, `CsvExec`, `JsonExec`

- datafusion/common/src/scalar/mod.rs
- datafusion/functions-aggregate/src/min_max.rs
- datafusion/optimizer/src/analyzer/type_coercion.rs
- datafusion/sqllogictest/test_files/aggregate.slt
- datafusion/sqllogictest/test_files/array_query.slt
- Closes #13987.
Reuse the work done on https://github.com/apache/datafusion/pull/15667 for adding support to Min/Max aggregation functions over lists. 
This was first attempted on https://github.com/apache/datafusion/pull/15857, but decided to follow a simpler approach in this PR.
Add support for performing `MIN` and `MAX` aggregations over lists.
Yes, by new sqllogictests
Yes, users can now perform `MIN` and `MAX` operations over lists
> Support `MIN` and `MAX` for `DataType::List`

- datafusion/common/src/scalar/mod.rs
- datafusion/functions-aggregate/src/first_last.rs
- datafusion/functions-aggregate/src/min_max.rs
- Closes #15923.
When aggregating first/last list over a column of lists, the first/last
accumulators hold the necessary scalar value as is, which points to the
list in the original input buffer.
This results in two issues:
1) We prevent the deallocation of the input arrays which might be
significantly larger than the single value we want to hold.
2) During aggreagtion with groups, many accumulators receive slices of the
same input buffer, resulting in all held values pointing to this buffer.
Then, when calculating the size of all accumulators we count the buffer
multiple times, since each accumulator considers it to be part of its own
allocation.
The PR copies/compacts scalar values held by the first/last operators, such that they no longer hold the entire input buffer, thereby solving …
> fix: overcounting of memory in first/last.

- datafusion/physical-plan/src/coalesce_batches.rs
- Closes #.
I observed a relatively huge gap between the analyze result and flamegraph. It turns out that the consumption of concating batches is not included in the metrics.
More accurate metrics for CoalescBatchesExec
n/a
no
> fix: track timing for coalescer's in execution time

- datafusion/expr/src/udf.rs
- Follow on to https://github.com/apache/datafusion/pull/16039
- @kylebarron  🦅 👁️  spotted an error in  https://github.com/apache/datafusion/pull/16039
Clarify that the name is ignored, not the field
> docs: Clarify that it is only the name of the field that is ignored

- datafusion/core/tests/memory_limit/mod.rs
- datafusion/execution/src/memory_pool/pool.rs
- datafusion/physical-plan/src/joins/cross_join.rs
- datafusion/physical-plan/src/joins/hash_join.rs
- datafusion/physical-plan/src/joins/nested_loop_join.rs
- Closes #16040 .
- line break, indentation (2 blankspace) for each top memory consumers
- use human_readable_byte
```
// TrackConsumersPool with 10m limit 
// select * from generate_series(1,5000000) as t1(v1) order by v1; 
Not enough memory to continue external sort. Consider increasing the memory limit, or decreasing sort_spill_reservation_bytes
caused by
Resources exhausted: Additional allocation failed with top memory consumers (across reservations) as:
ExternalSorterMerge[0]#2(can spill: false) consumed 10.0 MB,
DataFusion-Cli#0(can spill: false) consumed 0.0 B,
ExternalSorter[0]#1(can spill: true) consumed 0.0 B.
Error: Failed to allocate additional 128.0 KB for ExternalSorter[0] with 0.0 B already allocated for this reservation - 0.0 B remain available for the total pool
```
``` …
```
> Improve error message on Out of Memory

- datafusion/sqllogictest/test_files/parquet_statistics.slt
- Related to https://github.com/apache/datafusion/issues/15455
- @adriangb  thinks there is an issue in the config flags: https://github.com/apache/datafusion/pull/16080
- I found the current behavior non obvious (see https://github.com/apache/datafusion/pull/16096)
- I think @xudong963  also finds the behavior non obvious: https://github.com/apache/datafusion/issues/15455
1. Add tests that demonstrate the current behavior of `collect_statistics`
Yes
> Add test that demonstrate behavior for `collect_statistics`

- datafusion/functions-window/src/lead_lag.rs
- datafusion/functions-window/src/nth_value.rs
- datafusion/functions-window/src/ntile.rs
- datafusion/functions-window/src/rank.rs
- datafusion/functions-window/src/row_number.rs
- docs/source/user-guide/sql/window_functions.md
-  Follow on to https://github.com/apache/datafusion/pull/16074
- https://github.com/apache/datafusion/pull/16074 from @Adez017 added examples to the window function docuementation but I forgot to check it was included in the code as well. Thus the tests for the doc regeneration failed
1. Add sql examples to source code to get CI clean again
> Fix CI on main: Add window function examples in code

- Cargo.lock
- datafusion/core/src/datasource/listing/table.rs
- datafusion/core/tests/memory_limit/mod.rs
- datafusion/core/tests/parquet/file_statistics.rs
None
Clean the litter from test
`TempDir::into_path` "leaks" the temp dir. This updates the `tempfile` crate to a version where this method is deprecated and fixes all usages.
clippy
no
> Fix temp dir leak in tests

- datafusion/core/src/physical_planner.rs
when logical optimization failed, explain format indent will return
```
+-----------+------+
| plan_type | plan |
+-----------+------+
+-----------+------+
```
error message is swallowed.
but for tree format, error will be thrown out.
throw error if optimization failed for indent format.
UT
No
> feat: make error handling in indent explain consistent with that in tree

- datafusion/physical-plan/src/sorts/sort.rs
- Closes #.
While reviewing https://github.com/apache/arrow-rs/pull/7530 from @Dandandan  I noticed some code in DataFusion that has been moved upstream in Arrow
Specifically, now `lex_sort_to_indices1 supports Lists with more than one column: https://github.com/apache/arrow-rs/issues/5454
Remove the special code in DataFusion in favor of the upstream arrow implementation
> Clean up ExternalSorter and use upstream kernel

- datafusion/core/src/datasource/physical_plan/parquet.rs
- datafusion/datasource-parquet/src/opener.rs
- datafusion/datasource-parquet/src/row_filter.rs
- datafusion/datasource-parquet/src/source.rs
- datafusion/physical-optimizer/src/pruning.rs
> Revert use file schema in parquet pruning

- datafusion/core/src/dataframe/mod.rs
- datafusion/core/tests/dataframe/mod.rs
- Closes #16017 
The dataframe `describe` method serves as a tidier way to produce standard summary statistics about a dataset via the dataframe API. The abstraction hides an implicit normalization of column names performed by calls made to `col` from within the method's definition. @johnkerl flagged that use of datasets with non-normal column names (i.e. using uppercase or periods in the name) causes unexpected failures. The method is leaking its implementation and the fix provided properly seals it by escaping identifiers passed to `col`.
@findepi asks:
> what if f.name() contains " itself?
>
> should we use some format ident function?
The question raises a nuanced edge case. The following is a diagram of the call chain from passing a string to `col` followed by an explanation of each …
> fix: describe escaped quoted identifiers

- datafusion/expr/src/udf.rs
- datafusion/functions/src/core/named_struct.rs
- datafusion/functions/src/core/struct.rs
- Closes #.
- Similarly to https://github.com/apache/datafusion/pull/16112
I think it would be helpful to have a method that mimic'd the old field rather than having to always access `return_field.data_type`
Add `ScalarFunctionArgs::return_type` method and change some callsites
A new API method. No changes to existing APIs
> Minor: Add `ScalarFunctionArgs::return_type` method

- benchmarks/README.md
- benchmarks/queries/clickbench/README.md
- datafusion/expr/src/logical_plan/dml.rs
- docs/source/library-user-guide/catalogs.md
- docs/source/library-user-guide/custom-table-providers.md
- Follow on to https://github.com/apache/datafusion/pull/16033
While reviewing https://github.com/apache/datafusion/pull/16033 from @nuno-faria the current state of support for DML operations in DataFusion was somewhat unclear. Let's try and fix that with some docs
1. Update library user guide
2. Update docstrings
By CI
Only documentation, no behavior changes
> Improve the DML / DDL Documentation

- datafusion/functions/src/string/contains.rs
- datafusion/functions/src/string/mod.rs
- Closes #15866.
Yes, I think this can be simply tested by importing the `contains` function and making sure it compiles with 2 args.
User can use `contains` function as expected
> Fix `contains` function expression

- datafusion-cli/src/main.rs
- datafusion-cli/tests/cli_integration.rs
- datafusion-cli/tests/snapshots/cli_top_memory_consumers@no_track.snap
- datafusion-cli/tests/snapshots/cli_top_memory_consumers@top2.snap
- datafusion-cli/tests/snapshots/cli_top_memory_consumers@top3_default.snap
- docs/source/user-guide/cli/usage.md
Part of #16065 
Currently, datafusion-cli does not provide an option to use `TrackConsumersPool` as memory pool. It would be useful to set `TrackConsumersPool` as default so that users can view top memory consumers when running out of memory. 
This pr adds a new option `top-memory-consumers` in datafusion-cli. Thereby, user can set `TrackConsumersPool { inner: <mem-pool-type>, top: <top-memory-consumers>}` as memory pool. If `top-memory-consumers` is set to 0, datafusion-cli will use `mem-pool-type` not wrapped with `TrackConsumersPool`. 
Yes, via locally. 
I updated the docs. (`usage.md`)
> Set `TrackConsumersPool` as default in datafusion-cli

- .github/workflows/extended.yml
- Closes #.
The extended test (job `linux-test-extended`)  in CI is failing because of changes introduced in https://github.com/apache/datafusion/pull/16081. This PR added several failing snapshot tests for CLI integration. The CLI integration tests in CI run with backtrace disabled, while the extended tests run with backtrace enabled, which is causing the discrepancies.
Since the purpose of the failing CI job is only for tests guarded by the `extended_test` feature, and we don't have any for CLI tests, we can exclude CLI tests from the extended test suite.
Failed CI run: https://github.com/apache/datafusion/actions/runs/15179660797/job/42686605128
Failed CI job script: https://github.com/apache/datafusion/blob/cb45f1f9cc4f4041b8dcf9c7f0f5d51470d5f5a3/.github/workflows/extended.yml#L77 …
> CI: Fix extended test failure

- datafusion-examples/examples/advanced_udaf.rs
- datafusion/functions-aggregate-common/src/accumulator.rs
- datafusion/functions-aggregate/src/bit_and_or_xor.rs
- datafusion/functions-aggregate/src/first_last.rs
- datafusion/functions-aggregate/src/sum.rs
- Draft as it builds on https://github.com/apache/datafusion/pull/15748
- Follow up to https://github.com/apache/datafusion/pull/15911
https://github.com/apache/datafusion/pull/15911 from @timsaucer  added `Accumulator::return_field` to make it more general, but that requires changing all call sites to refer to `return_field.data_type()`
In DataFusion 47:
```rust
args.return_type,
```
on `main`:
```
args.return_field.data_type(),
```
To help with the migration, I added a `return_type()` method to `AccumulatorArgs`
After this PR (the code looks much closer to DataFusion 47):
```rust
args.return_type(),
```
I will add similar functions to the `WindowUDFFieldArgs` and  `ScalarFunctionArgs`
1. I added a `return_type()` method to `AccumulatorArgs`
2. Update callsites to use it
By exsiting CI …
> Minor: Add `Accumulator::return_type` and `StateFieldsArgs::return_type` to help with upgrade to 48

- datafusion/core/tests/memory_limit/mod.rs
- datafusion/physical-plan/src/aggregates/row_hash.rs
- Closes https://github.com/apache/datafusion/issues/16151
See https://github.com/apache/datafusion/issues/16151
- The `GroupedHashAggregateStream::new` function now dynamically constructs the operator name to include a comma-separated list of the aggregate functions it handles (e.g., `GroupedHashAggregateStream[0] (COUNT, SUM))`.
- A new test case, `oom_grouped_hash_aggregate`, has been added. This test verifies that the enriched `GroupedHashAggregateStream` name correctly appears in out-of-memory error messages.
Unit test
A change in the error message wording but it's **not** a breaking API change.
> Enrich GroupedHashAggregateStream name to ease debugging Resources exhausted errors

- datafusion/expr/src/logical_plan/builder.rs
- datafusion/expr/src/logical_plan/plan.rs
- datafusion/expr/src/logical_plan/tree_node.rs
Both WHERE clause and HAVING clause translate to a Filter plan node. They differ in how the references and aggregates are handled. HAVING goes after aggregation and may reference aggregate expressions and therefore HAVING's filter will be placed after Aggregation plan node.
Once a plan has been built, however, there is no special additional semantics to filters created from HAVING. Remove the unnecessary field.
For reference, the field was added along with usage in a50aeefcbfc84d491495887d57fa8ebc0db57ff2 commit and the usage was later removed in eb62e2871e49c402ec7b0d25658faa6dc5219969 commit.
> Remove `Filter::having` field

- datafusion/optimizer/tests/optimizer_integration.rs
Added `tables: HashMap<String, Arc<dyn TableSource>>` and `MyContextProvider::with_schema` method for dynamically defining tables for optimizer integration tests.
--
Current mock context uses hardcoded tables, this change allows adding multiple tables without modify the mock implementation. This change will make testing #16023 easier.
--
Yes, all of the integration tests are passing.
No, this is purely for integration tests in `datafusion/optimizer`
> refactor(optimizer): Add support for dynamically adding test tables

- datafusion/functions-nested/src/length.rs
- datafusion/sqllogictest/test_files/array.slt
- Closes #16163.
FixedSizeList is not supported
support FixedSizeList
UT
No
> feat: array_length for fixed size list

- datafusion/core/tests/sql/explain_analyze.rs
- datafusion/expr/src/logical_plan/plan.rs
- datafusion/optimizer/src/optimize_projections/mod.rs
- datafusion/optimizer/tests/optimizer_integration.rs
- datafusion/sqllogictest/test_files/array.slt
- datafusion/sqllogictest/test_files/explain.slt
- datafusion/sqllogictest/test_files/joins.slt
- datafusion/sqllogictest/test_files/limit.slt
- datafusion/sqllogictest/test_files/subquery.slt
- datafusion/sqllogictest/test_files/union.slt
- datafusion/sqllogictest/test_files/window.slt
- datafusion/substrait/tests/cases/roundtrip_logical_plan.rs
Remove trailing whitespace in `Display` for `LogicalPlan::Projection`. This prevents editors and other tools  from automatically removing trailing whitespace at the end of lines.
--
Most editors automatically remove trailing whitespace at end of lines on save/paste actions. This chnage removes trailing whitespace from implementation and snapshots for better developer experience.
--
Yes, all of the tests are updated with new expected print output.
This change only effects output of `LogicalPlan::display_indent()` and is purely for DX.
> fix: Remove trailing whitespace in `Display` for `LogicalPlan::Projection`

- datafusion/physical-plan/src/aggregates/group_values/multi_group_by/mod.rs
- datafusion/physical-plan/src/aggregates/group_values/row.rs
- datafusion/physical-plan/src/aggregates/group_values/single_group_by/primitive.rs
- datafusion/physical-plan/src/aggregates/mod.rs
This PR hard-codes the seed for the hash aggregation. The main benefit compared to the previously runtime-determined seed is that after applying this PR, partial aggregation and final aggregation will share the same hash function.
I haven't measured it, but in theory, this should make the final aggregation step more efficient, because the partial aggregation will emit the group values in a way that will be clustered in the final aggregation hash table - thus causing a benefitial memory access pattern when building the final aggregation.
I expect it speeds up large-cardinality aggregations that don't trigger the skipping of the partial aggregation step a tiny bit.
> Set aggregation hash seed

- datafusion/common/src/pruning.rs
- Follow on to https://github.com/apache/datafusion/pull/16139
Implement suggestions from @xudong963: https://github.com/apache/datafusion/pull/16139#discussion_r2114104284
Tweak the docs a bit
> Minor: update documentation for PrunableStatistics

- datafusion/proto-common/proto/datafusion_common.proto
- datafusion/proto-common/src/generated/pbjson.rs
- datafusion/proto-common/src/generated/prost.rs
- datafusion/proto-common/src/to_proto/mod.rs
- datafusion/proto/src/generated/datafusion_proto_common.rs
- datafusion/sqllogictest/test_files/regexp/regexp_like.slt
> Remove use of deprecated dict_ordered in datafusion-proto (#16218)

- benchmarks/compare.py
- benchmarks/src/bin/external_aggr.rs
- benchmarks/src/clickbench.rs
- benchmarks/src/imdb/run.rs
- benchmarks/src/sort_tpch.rs
- benchmarks/src/tpch/run.rs
- benchmarks/src/util/mod.rs
- benchmarks/src/util/run.rs
- Closes #16160 .
To track whether certain queries fail on limited memory, we need to continue executing benchmark queries even when previous one fails. Also, it would be better to mark & visualize the failure with `compare.py`. 
- `tpch`, `clickbench`, `sort_tpch` executes next query when current query fails on any iteration. (It will not execute the next iteration of failed query) 
- In terminal, Error message is printed as [], and it will print the ids of failed queries. 
- New field `success` added to output json, updated `compare.py` to compare the elapsed time of successful results, not failed ones.  
Since it's benchmark suite, I tested it manually. 
```
// Sample output in terminal
Query 18 failed: Resources exhausted: Additional allocation failed with top memory consumers (across …
```
> Update tpch, clickbench, sort_tpch to mark failed queries

- datafusion/sqllogictest/test_files/aggregate.slt
- closes https://github.com/apache/datafusion/issues/16250
Let's have sqllogictest pass locally without having to set `RUST_BACKTRACE`
Note I didn't actually find / fix the actual underlying problem...
1. Update test to look for the error message rather than the entire thing
yes, by CI and I ran it locally as well
No
This is only a test change
> Adjust slttest to pass without RUST_BACKTRACE enabled

- datafusion/physical-plan/src/aggregates/group_values/multi_group_by/primitive.rs
- datafusion/sqllogictest/test_files/aggregate.slt
- Closes #16254.
NaN != NaN
Use arrow is_eq to test equality
UT
No
> fix: NaN semantics in GROUP BY

- .github/workflows/rust.yml
- Cargo.lock
- datafusion/sqllogictest/Cargo.toml
- datafusion/sqllogictest/README.md
- datafusion/sqllogictest/bin/sqllogictests.rs
- datafusion/sqllogictest/src/engines/datafusion_substrait_roundtrip_engine/mod.rs
- datafusion/sqllogictest/src/engines/datafusion_substrait_roundtrip_engine/runner.rs
- datafusion/sqllogictest/src/engines/mod.rs
- datafusion/sqllogictest/src/lib.rs
It probably does not fully closes it but it partially addresses:
- https://github.com/apache/datafusion/issues/15069
Being able to execute the full sqllogictest suite adding a Substrait roundtrip. This means:
- Parsing the test statement
- Building a logical plan out of it
- Converting the logical plan to Substrait
- Converting the Substrait plan back to logical
- Execute it
Adds a new `DataFusionSubstraitRoundTrip` sqllogictest runner implementation that will do a Substrait roundtrip where it makes sense, and a new `--substrait-round-trip` option to the sqllogictest CLI.
Example:
Runs the full aggregate.slt file doing a Substrait roundtrip on each individual statement
```shell
cargo test --test sqllogictests -- --substrait-round-trip aggregate 
```
Runs an individual failing test …
> Add `--substrait-round-trip` option in sqllogictests

- datafusion/physical-optimizer/src/pruning.rs
- Found while testing https://github.com/delta-io/delta-rs/pull/3520
- Related to #15771 
While testing the DataFuion upgrade in delta.rs I found that `PruningStatistics` is no longer exported from `datafusion::physical_optimizer::pruning` after #16069
The fix downstream is easy (use the new import location) but I think leaving a backwards compatible `pub use` would mean no changes needed
1. change `use` to `pub use` so downstream users can upgrade without change
By CI
> Minor: fix upgrade papercut `pub use PruningStatistics`

- datafusion/ffi/src/lib.rs
- datafusion/ffi/src/tests/mod.rs
- datafusion/ffi/src/tests/udf_udaf_udwf.rs
- datafusion/ffi/src/udwf/mod.rs
- datafusion/ffi/src/udwf/partition_evaluator.rs
- datafusion/ffi/src/udwf/partition_evaluator_args.rs
- datafusion/ffi/src/udwf/range.rs
- datafusion/ffi/src/volatility.rs
- datafusion/ffi/tests/ffi_integration.rs
- datafusion/ffi/tests/ffi_udwf.rs
- Closes #14562
This is the last part of the FFI UDFs that remain. It builds on top of https://github.com/apache/datafusion/pull/14775 so this PR looks larger than it really is.
- Exposes window UDFs via FFI
- Adds unit test and integration test
Yes, including an end-to-end integration test.
None.
> feat: Add Window UDFs to FFI Crate

- datafusion/catalog-listing/README.md
- datafusion/catalog/README.md
- datafusion/common-runtime/README.md
- datafusion/common/README.md
- datafusion/datasource-avro/README.md
- datafusion/datasource-json/README.md
- datafusion/datasource-parquet/README.md
- datafusion/datasource/README.md
- datafusion/doc/README.md
- datafusion/execution/README.md
- datafusion/expr-common/README.md
- datafusion/expr/README.md
- datafusion/functions-aggregate-common/README.md
- datafusion/functions-aggregate/README.md
- datafusion/functions-nested/README.md
- datafusion/functions-table/README.md
- datafusion/functions-window-common/README.md
- datafusion/functions-window/README.md
- datafusion/functions/README.md
- datafusion/macros/README.md
- datafusion/optimizer/README.md
- datafusion/physical-expr-common/README.md
- datafusion/physical-expr/README.md
- datafusion/physical-optimizer/README.md
- datafusion/physical-plan/README.md
- datafusion/proto-common/README.md
- datafusion/session/README.md
- datafusion/sql/README.md
- Related to https://github.com/delta-io/delta-rs/pull/3521
While testing a DataFusion upgrade in delta.rs I found that that project used many of the subcrates in DataFusion directly. I made a PR to clean this up (https://github.com/delta-io/delta-rs/pull/3521) but I wanted to make it easier to understand which `datafusion-*` crate is designed to be used directly and which is not
1. Add a note to subcrates README.md files that are not intended to be used directly
2. Add a few missing READMEs I found while doing this
By CI
(Hopefully) better documentation
> Improve DataFusion subcrate readme files

- datafusion/physical-expr/src/window/aggregate.rs
- datafusion/physical-expr/src/window/sliding_aggregate.rs
- datafusion/physical-expr/src/window/window_expr.rs
- dev/changelog/48.0.0.md
This reverts commit 0c3037404929fc3a3c4fbf6b9b7325d422ce10bd.
- related to https://github.com/apache/datafusion/issues/16308
There is a regression between 48.0.0-rc1 and 48.0.0-rc2 that causes some windowed aggregate tests to fail in Comet.
This PR is a test to see if reverting a recent PR solves the issue. We will run Comet tests in CI pointing to this branch to confirm.
> fix: [branch-48] Revert "Improve performance of constant aggregate window expression"

- benchmarks/bench.sh
- benchmarks/compare.py
- No issue created yet, related to PR #16196.
The current benchmark comparison script compares the fastest execution times of each query. This is already useful but only a small portion of the measure data such as maximum and average times and some metric of variability. This PR adds an extra command to the result processing Python script that calculates and shows these values.
Adds support for a `compare_detail` command to `bench.sg` and a `--detailed` flag to `compare.py`.
Not beyond manual execution of `bench.sh` with both the existing fastest mode and the new detailed mode.
No, this is a developer oriented change.
> Extend benchmark comparison script with more detailed statistics

- datafusion/datasource-parquet/src/source.rs
- datafusion/physical-plan/src/execution_plan.rs
- datafusion/physical-plan/src/filter_pushdown.rs
- datafusion/sqllogictest/test_files/parquet_filter_pushdown.slt
I was concerned that the dance we were doing with `allowed_filters` resulted in the order of filters being returned to the parent differing from the order they were passed down in.
Luckily during the design of these APIs we ended up making them agnostic to the ordering of filters (hence why we pass the actual `PhysicalExpr` back up) so there is no bug 😄 
Nonetheless I decided to add tests, documentation and helpers to avoid this being a cause for confusion or a bug in the future.
> Add test for ordering of predicate pushdown into parquet

- docs/source/user-guide/features.md
- Closes #16341.
The feature matrix in the user guide was missing an updated status for join spilling support. This PR ensures that the documentation reflects the current capabilities of the system, improving clarity for users and maintainers.
- Updates the feature matrix to mark "Spilling (to disk) Joins" as supported (`[x]`).
- No tests are required for this documentation-only change.
- The underlying functionality is assumed to be covered by existing tests related to join spilling.
- Yes, this is a documentation update that clarifies existing functionality.
- No behavioral or API changes are included.
> Fix: mark "Spilling (to disk) Joins" as supported in features

- datafusion/core/src/datasource/physical_plan/arrow_file.rs
- datafusion/core/src/datasource/physical_plan/csv.rs
- datafusion/core/tests/physical_optimizer/filter_pushdown/util.rs
- datafusion/datasource-avro/src/source.rs
- datafusion/datasource-csv/src/source.rs
- datafusion/datasource-json/src/source.rs
- datafusion/datasource-parquet/src/metrics.rs
- datafusion/datasource-parquet/src/opener.rs
- datafusion/datasource-parquet/src/source.rs
- datafusion/datasource/src/file_meta.rs
- datafusion/datasource/src/file_scan_config.rs
- datafusion/datasource/src/file_stream.rs
- datafusion/physical-optimizer/src/pruning.rs
- datafusion/proto/src/physical_plan/to_proto.rs
- docs/source/library-user-guide/upgrading.md
> Add late pruning of Parquet files based on file level statistics

- datafusion/execution/src/memory_pool/mod.rs
- Closes #.
Add more docs to the structures related to `MemoryPool`
> docs: Expand `MemoryPool` docs with related structs

- datafusion-cli/src/object_storage.rs
- Follow on to https://github.com/apache/datafusion/pull/16300
- Part of https://github.com/apache/datafusion/issues/16378
CI is failing, but when I ran the same command as is failing on CI locally, it passes for me:
```shell
cargo test  --profile ci --exclude datafusion-examples --exclude datafusion-benchmarks --exclude datafusion-sqllogictest --workspace --lib --tests --features=force_hash_collisions,avro
```
Therefore I conclude something about the environment on the github builder is causing the issue
Add context from the inner error source as well to the error message, so I can debug what is the actual problem
> Add more context to error message for datafusion-cli config failure

- datafusion/optimizer/src/eliminate_cross_join.rs
- Closes #.
I found that a join plan created using `join_detailed` method with `null_equals_null` set to `true` will be rewritten to a join plan with `null_equals_null` set to `false`. This is because optimizer rule `eliminate_cross_join` will assemble a Join plan and hardcode a `false` value. This patch fixes that rule and now it will respect the `null_equals_null` flag from input plan.
A little more background: In a normal SQL model, JOIN and many other places usually take `null != null`. But I want to leverage JOIN to "concat" two tables' columns in a PromQL scenario, where I treat `null` as just an identical vacancy, that requires `null = null`.
A bug fix to `eliminate_cross_join` plan
I wrote a new unit test case to cover this case.
No.
> fix: preserve null_equals_null flag in eliminate_cross_join rule

- datafusion/physical-plan/src/sorts/merge.rs
- datafusion/physical-plan/src/sorts/sort_preserving_merge.rs
- Closes #16321.
`SortPreservingMergeStream` works in two phases. It first waits for each input stream to be ready to emit. Once everybody's ready it proceeds to an emit phase.
During the waiting phase, it will poll each stream in a round-robin fashion. If any stream returns `Pending` the code self-wakes the current task and immediately returns `Pending`. This results in busy-waiting when waiting for, for instance, a `SortExec` that's sorting its data or any other pipeline breaker.
While this works, it wastes CPU cycles.
Rather than returning immediately when one stream is pending, poll each stream once. Only return pending when there are still streams left that have not started emitting. This assumes that the pending streams are well behaved and will wake the task when they need to be …
> bug: remove busy-wait while sort is ongoing

- benchmarks/bench.sh
- benchmarks/src/tpch/run.rs
- Closes [#16370](https://github.com/apache/datafusion/issues/16370)
1. tpch data generate for csv format
2. Support tpch and tpch10 csv format
Yes:
```rust
./benchmarks/bench.sh data tpch
***************************
DataFusion Benchmark Runner and Data Generator
COMMAND: data
BENCHMARK: tpch
DATA_DIR: /Users/zhuqi/arrow-datafusion/benchmarks/data
CARGO_COMMAND: cargo run --release
PREFER_HASH_JOIN: true
***************************
Creating tpch dataset at Scale Factor 1 in /Users/zhuqi/arrow-datafusion/benchmarks/data/tpch_sf1...
tbl files exist (/Users/zhuqi/arrow-datafusion/benchmarks/data/tpch_sf1/supplier.tbl exists).
Expected answers exist (/Users/zhuqi/arrow-datafusion/benchmarks/data/tpch_sf1/answers/q1.out exists).
parquet files exist …
```
> feat: Support tpch and tpch10 benchmark for csv format

- datafusion/functions-nested/src/concat.rs
- datafusion/sqllogictest/test_files/array.slt
Fixes issue where 'select array_concat(NULL::integer[])' would throw 'Arrow error: Compute error: concat requires input of at least one array'
- Closes #16349 
- Fix array_concat_inner to properly handle NULL list arrays by checking null_count
- Add logic to create properly typed empty arrays for all-null inputs
- Support NULL handling for List, LargeList, and FixedSizeList types
- Add comprehensive test coverage for NULL array scenarios
> Fix array_concat with NULL arrays

- datafusion/core/src/execution/session_state.rs
- datafusion/sqllogictest/test_files/table_functions.slt
- Fixes https://github.com/apache/datafusion/issues/14958
Table functions don't need to special case `Cast`s of literals or other constructs that could be simplified.
Apply expression simplification to table functions.
Yes, added a sqllogictest
Yes, more queries should be supported.
> Simplify expressions passed to table functions

- docs/source/library-user-guide/upgrading.md
- Follow on to https://github.com/apache/datafusion/pull/16170
I hit another required change while testing the delta-rs upgrade, which I wanted to document
- https://github.com/delta-io/delta-rs/pull/3520
1. Add a note to the upgrade guide about changes in `Expr::Scalar` in 48.0.0
Docs only
> Add note in upgrade guide about changes to `Expr::Scalar` in 48.0.0

- benchmarks/README.md
- docs/source/contributor-guide/inviting.md
- Closes #.
The [ASF process for inviting new PMC members](https://www.apache.org/dev/pmc.html#pmcmembers) has been updated, notably sending an email notice to the board is no longer required. 
Let's update the DataFusion specific cookbook to match the updated process
Documentation only changes
> Update PMC management instructions to follow new ASF process

- .github/workflows/rust.yml
- While working on https://github.com/apache/datafusion/pull/16401 I noticed that the license header check ran twice:
Remove the redundant CI check
CI
> Remove redundant license-header-check CI job

- datafusion/physical-plan/Cargo.toml
- datafusion/physical-plan/benches/sort_preserving_merge.rs
- Closes #16448.
#15913 introduced a feature to hid a test utilities module in `datafusion-physical-plan`. The module was later made public but the feature stayed behind making it non-trivial to compile/lint the sort_merge benchmark.
> Remove unused feature in `physical-plan` and fix compilation error in benchmark

- datafusion/physical-plan/src/joins/hash_join.rs
- datafusion/physical-plan/src/joins/symmetric_hash_join.rs
- Closes #16415.
The algorithm that is used for mark joins in `calculate_indices_by_join_type` might be confusing for newer contributors so we should add a comment to clarify.
Added comments with an example to explain how the algorithm works.
> doc: Add comments to clarify algorithm for `MarkJoin`s

- datafusion/physical-plan/src/sorts/sort.rs
Reverts unnecessary methods added in #15770
> remove unused methods in SortExec

- datafusion/core/tests/fuzz_cases/sort_query_fuzz.rs
- datafusion/physical-plan/src/topk/mod.rs
> Temporarily fix bug in dynamic top-k optimization

- docs/source/library-user-guide/upgrading.md
- Closes #.
Doc upgrade guide for the new feature https://github.com/apache/datafusion/pull/16268
> doc: upgrade guide for new compression option for spill files

- datafusion/sql/src/relation/mod.rs
- datafusion/sqllogictest/test_files/array.slt
- datafusion/sqllogictest/test_files/spark/array/array.slt
- datafusion/sqllogictest/test_files/spark/array/array_repeat.slt
- datafusion/sqllogictest/test_files/spark/array/sequence.slt
- datafusion/sqllogictest/test_files/table_functions.slt
- Closes #16467.
Use UDTF name in logical plan table scan
Yes, exist `sqllogictest` are updated.
Yes, but the table scan name for a UDTF in the logical plan was not previously documented.
> Use UDTF name in logical plan table scan

- datafusion/physical-expr/src/utils/mod.rs
No reason for it to not accept a non-arce'd ref
> refactor reassign_predicate_columns to accept an &Schema instead of &Arc<Schema>

- datafusion/common/src/config.rs
- datafusion/core/tests/macro_hygiene/mod.rs
\-
The macro -- while being public and actually helpful -- is currently broken & undocumented.
- docs
- hygiene fixes
- macro hygiene test
For devs: the macro now works.
> fix: document and fix macro hygiene for `config_field!`

- datafusion/physical-plan/src/execution_plan.rs
- datafusion/physical-plan/src/lib.rs
- datafusion/physical-plan/src/recursive_query.rs
- datafusion/physical-plan/src/work_table.rs
This PR addresses the extensibility limitation that causes recursive queries to fail when used with the `datafusion-tracing` crate, as reported in [datafusion-contrib/datafusion-tracing#5](https://github.com/datafusion-contrib/datafusion-tracing/issues/5).
While there isn't a specific DataFusion issue filed, this change enables external crates like `datafusion-tracing` to properly support recursive queries by implementing work table injection in their wrapper nodes.
Currently, recursive query execution in `RecursiveQueryExec` uses downcasting to find `WorkTableExec` nodes and inject work tables. This approach fails when execution plans are wrapped by custom execution nodes, as is done by the `datafusion-tracing` crate, causing recursive queries to fail with "Unexpected empty work table" …
> fix: make `with_new_state` a trait method for `ExecutionPlan`

- datafusion/core/src/datasource/listing_table_factory.rs
- datafusion/core/src/execution/context/mod.rs
- datafusion/core/src/execution/context/parquet.rs
- datafusion/datasource/src/url.rs
- datafusion/sqllogictest/test_files/parquet.slt
> `TableProvider` to skip files in the folder which non relevant to selected reader

- datafusion/sql/Cargo.toml
- Closes #.
- While reviewing https://github.com/apache/datafusion/pull/16161 from @chenkovsky  it seems like we have to keep remembering in code reviews not to add dependencies in datafusion-sql
let's add some comments for future developers
> Add some comments about adding new dependencies in datafusion-sql

- datafusion/core/tests/physical_optimizer/enforce_sorting.rs
- datafusion/core/tests/physical_optimizer/sanity_checker.rs
- datafusion/expr/src/window_frame.rs
- datafusion/expr/src/window_state.rs
- Closes #.
Before the change, the frame constructed with
`WindowFrame::new(Some(true))` would not be fully functional, because
of the bound being of unexpected type.
Change in `WindowFrame::new`
with unit tests
yes
> Fix WindowFrame::new with order_by 

- datafusion/sql/src/unparser/dialect.rs
- datafusion/sql/src/unparser/expr.rs
- datafusion/sql/src/unparser/plan.rs
- datafusion/sql/tests/cases/plan_to_sql.rs
No corresponding issue at DataFusion. I encountered it in the Wren AI case. 
- https://github.com/Canner/wren-engine/issues/1089
Consider the following SQL:
```
select count(*) from (select 1)
```
It will be simplified to the following SQL after we move `CountWildcardRule` to the logical planner https://github.com/apache/datafusion/pull/14689
```
SELECT count(1) AS \"count(*)\" FROM (SELECT 1)
```
However, some dialects (e.g. BigQuery) don't allow some [special characters](https://cloud.google.com/bigquery/docs/schemas#flexible-column-names)(`(`, `*`, `@`, ...) in an alias name. We should have a way to handle this case for the unparser. 
- Introduce the interface `col_alias_overrides` for the unparser dialect.
```rust
/// Allows the dialect to override column alias unparsing if the …
```
> Allow unparser to override the alias name for the specific dialect

- datafusion/execution/src/disk_manager.rs
- datafusion/physical-plan/src/metrics/baseline.rs
- datafusion/physical-plan/src/sorts/sort.rs
- datafusion/physical-plan/src/spill/in_progress_spill_file.rs
- datafusion/physical-plan/src/spill/mod.rs
- Related to #16367 
Previously, the `spilled_bytes` metric reported the estimated in-memory size of spilled `RecordBatches`, based on their array sizes. However, with the introduction of spill file compression in the `SpillManager`, the in-memory size no longer reflects the actual bytes written to disk.
This PR updates the `spilled_bytes` metric to instead report the total number of bytes physically **written to disk** during spilling.
Whenever `in_progress_file.finish()` is called, it updates the spill file metric based on `current_disk_usage` for this spill file. Since spill files are append-only, we only update this value once. 
Yes. We manually compare the spill file size and reported metric.
After this PR, running certain spilling aggregate queries may show significantly lower …
> Update `spilled_bytes` metric to reflect actual disk usage

- datafusion/core/src/lib.rs
@crepererum  mentioned to me that it was somewhat non obvious that DataFusion has two main sources of documentation. The API docs and the website. Let's try and make that a little clearer from the api docs
Update the intro paragraph of the library docs to make the link to the website clearer
by CI and I rendered them locally:
Different landing text on docs.rs page
> Minor: add clearer link to the main website from intro paragraph.

- datafusion/core/src/datasource/physical_plan/parquet.rs
- datafusion/datasource-parquet/src/opener.rs
- datafusion/datasource-parquet/src/row_filter.rs
- datafusion/physical-expr/src/lib.rs
- datafusion/physical-expr/src/schema_rewriter.rs
The idea here is to move us one step closer to https://github.com/apache/datafusion/issues/15780 although there is still work to do (e.g. https://github.com/apache/datafusion/issues/15780#issuecomment-2824716928).
My goal is that this immediately unblocks other work (in particular https://github.com/apache/datafusion/pull/15057) while being a relatively small change that we can build upon with more optimizations, etc.
> adapt filter expressions to file schema during parquet scan

- datafusion/ffi/src/udwf/mod.rs
- datafusion/ffi/src/udwf/partition_evaluator_args.rs
- Closes https://github.com/apache/datafusion-python/issues/1144
There is a bug in how we compute the indices to create a schema for. It misses the last index *and* it can erroneously create an index 0 when none exists.
Properly handle the `None` case when finding `max` index.
Unit test will be added before marking this PR ready. Tested in datafusion-python.
No
> fix: column indices in FFI partition evaluator

- datafusion/functions-table/src/generate_series.rs
- datafusion/sqllogictest/test_files/table_functions.slt
- Closes https://github.com/apache/datafusion/issues/14209
The table functions `range` and `generate_series` now matches the functionality of the scalar functions of the same name.
- Introduce `SeriesValue` which abstracts how different value-types are generated
- Implement `SeriesValue` for integers and timestamps. The timestamp logic is also used for date generation
Yes, added more slt tests.
Yes, `range` and `generate_series` table functions are now more powerful.
> Support timestamp and date arguments for `range` and `generate_series` table functions

- datafusion/common/src/join_type.rs
- datafusion/core/tests/fuzz_cases/join_fuzz.rs
- datafusion/core/tests/physical_optimizer/join_selection.rs
- datafusion/expr/src/logical_plan/builder.rs
- datafusion/physical-optimizer/src/join_selection.rs
- datafusion/physical-plan/src/joins/hash_join.rs
- datafusion/physical-plan/src/joins/nested_loop_join.rs
- datafusion/physical-plan/src/joins/sort_merge_join.rs
- datafusion/physical-plan/src/joins/symmetric_hash_join.rs
- datafusion/physical-plan/src/joins/utils.rs
- datafusion/sqllogictest/test_files/subquery.slt
…p (#16488)"
This reverts commit d73f0e87dc72de1df4bc14d1ca61493567b71d63.
- Closes #16595 .
> Revert Finalize support for `RightMark` join + `Mark` join

- datafusion/sql/src/relation/mod.rs
- datafusion/sqllogictest/test_files/table_functions.slt
Closes #16568 
Allows usage of table functions in relations
```sql
SELECT col1, f.* FROM json_tbl, LATERAL FLATTEN(INPUT => col1, PATH => 'name') f;
```
Added section for TableFactor::Function
Tested in fork with registered **flatten** table function
No
> Allow usage of table functions in relations

- docs/source/library-user-guide/functions/adding-udfs.md
N/A; minor documentation improvement.
I've been learning DataFusion and applying it to some work projects 🎉 I'm also a native English speaker, and noticed some minor issues.
See the description.
I ran the build script and it doesn't look like anything broke :)
Yes; this affects user-facing documentation.
> docs: Minor grammatical fixes for the scalar UDF docs

- datafusion/common/src/scalar/mod.rs
- datafusion/common/src/utils/mod.rs
- datafusion/core/tests/sql/aggregates.rs
- datafusion/functions-aggregate-common/src/min_max.rs
- datafusion/functions-aggregate/src/array_agg.rs
- datafusion/optimizer/src/simplify_expressions/simplify_predicates.rs
Fix calls to `ScalarValue::partial_cmp` that treat `None` return value as equivalent to equality. The `partial_cmp` returns `None` when values cannot be compared, for example they have incompatible types. Apparently, in all these places it is an error condition when values cannot be compared.
> Avoid treating incomparable scalars as equal

- datafusion/core/tests/fuzz_cases/record_batch_generator.rs
- datafusion/core/tests/fuzz_cases/sort_query_fuzz.rs
- datafusion/physical-plan/src/topk/mod.rs
- Closes https://github.com/apache/datafusion/issues/16452
- @AdamGS  removed some of the code here https://github.com/apache/datafusion/pull/16465
- However, the test kept failing
- @adriangb fixed what we think is the real issue here: https://github.com/apache/datafusion/pull/16491
- Let's restore the removed code in https://github.com/apache/datafusion/pull/16465
> restore topk pre-filtering of batches and make sort query fuzzer less sensitive to expected non determinism 

- datafusion/physical-plan/benches/spill_io.rs
- Related to #16367 
This pr adds some microbenchmarks to compare performance characteristics between different compression codecs. It generates 50 RecordBatch for each case, and run both write & read. It manually prints out **compression ratio (mem_bytes / disk_bytes)** after each run.  
To make benchmark more realistic, this pr generates `RecordBatches` that resemble the data it spills on `AggregateExec` (tpc-h) and `SortExec` (sort-tpch). It covers both thin batch consists of primitive arrays and wide batches with complex data type. 
Below are schema of RecordBatch & original query for each benchmark case.
- Q2 [Int64(partkey), Decimal128(min(ps_supplycost))]
```
select
...
p_partkey,
...
where
p_partkey = ps_partkey
...
and ps_supplycost = (
select
min(ps_supplycost)
```
- Q16 …
> Add microbenchmark for spilling with compression

- datafusion/datasource-parquet/src/source.rs
- datafusion/sqllogictest/test_files/parquet_filter_pushdown.slt
> Fix parquet filter_pushdown: respect parquet filter pushdown config in scan

- datafusion/core/src/physical_planner.rs
- datafusion/core/tests/execution/logical_plan.rs
- datafusion/expr/src/expr.rs
- datafusion/expr/src/expr_fn.rs
- datafusion/expr/src/planner.rs
- datafusion/expr/src/test/function_stub.rs
- datafusion/expr/src/udaf.rs
- datafusion/functions-aggregate/src/approx_percentile_cont.rs
- datafusion/functions-aggregate/src/count.rs
- datafusion/functions-aggregate/src/first_last.rs
- datafusion/functions-aggregate/src/macros.rs
- datafusion/functions-aggregate/src/planner.rs
- datafusion/optimizer/src/analyzer/type_coercion.rs
- datafusion/optimizer/src/common_subexpr_eliminate.rs
- datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs
- datafusion/optimizer/src/single_distinct_to_groupby.rs
- datafusion/proto/src/logical_plan/from_proto.rs
- datafusion/proto/src/logical_plan/to_proto.rs
- datafusion/proto/tests/cases/roundtrip_logical_plan.rs
- datafusion/sql/src/expr/function.rs
- datafusion/sql/src/unparser/expr.rs
- datafusion/substrait/src/logical_plan/consumer/expr/aggregate_function.rs
- datafusion/substrait/src/logical_plan/consumer/rel/aggregate_rel.rs
- datafusion/substrait/src/logical_plan/producer/expr/aggregate_function.rs
> Convert Option<Vec<sort expression>> to Vec<sort expression>

- datafusion-cli/src/exec.rs
- Closes #16559.
Encapsulate s3 region retry logic into StatementExecutor
Already covered by existing tests as this PR is to refactor logic
No
> `datafusion-cli`: Refactor statement execution logic

- datafusion/common/src/column.rs
- datafusion/common/src/dfschema.rs
- datafusion/common/src/error.rs
- datafusion/expr/src/logical_plan/builder.rs
- One step towards #16652.
- See #16652.
Box a field.
Unit test.
**Breaking:** `SchemaError::AmbiguousReference::column` is now boxed.
> refactor: shrink `SchemaError`

- rust-toolchain.toml
- Closes  #16655.
Improve build times.
Rust 1.88.0 is properly configured and active
All toolchain components (rustfmt, clippy) are working
The DataFusion workspace compiles cleanly with the new Rust version
No warnings or errors detected
> Update to Rust 1.88

- datafusion-examples/examples/parquet_embedded_index.rs
- Follow on to https://github.com/apache/datafusion/pull/16395
- Related to https://github.com/apache/datafusion/issues/16374
@JigaoLuo notes in https://github.com/apache/datafusion/issues/16374#issuecomment-3039204719 that it may not be clear this approach can be used for any type of index, so let's try and make that clearer in the comments
1. Add some more comments to `datafusion-examples/examples/parquet_embedded_index.rs` clarifying the scope of the available indexes
By CI
Just docs
> Clarify the generality of the embedded parquet index

- datafusion/substrait/src/logical_plan/consumer/types.rs
- datafusion/substrait/src/logical_plan/producer/types.rs
- datafusion/substrait/src/variation_const.rs
- Closes #16273.
This commit adds support for the Arrow Dictionary type in Substrait plans.
Yes
Add support for Arrow Dictionary type in Substrait plans
> Add support for Arrow Dictionary type in Substrait

- datafusion/physical-plan/src/sorts/cursor.rs
We fixed the inline key corner case in:
https://github.com/apache/arrow-rs/issues/7874
https://github.com/apache/arrow-rs/pull/7875
This PR port the change to datafusion CursorValue compare, which is used in merging phase for sort.
We fixed the inline key corner case in:
https://github.com/apache/arrow-rs/pull/7875
This PR port the change to datafusion CursorValue compare, which is used in merging phase for sort.
Yes
Yes
No
> fix: port arrow inline fast key fix to datafusion

- docs/source/index.rst
- docs/source/library-user-guide/upgrading.md
- Part of #16486 
We back ported the default setting for statistics `datafusion.execution.collect_statistics` to 48.0.1 so we should update the upgrade guide to reflect that
1. Move the description to 48.0.1 release heading
2. Move the upgrade guide higher in the index to make it easier to find
by CI
Upgrade guide
> Update Upgrade Guide for 48.0.1

- datafusion/common/src/scalar/mod.rs
- Closes #13754 .
Yes. Existing test already handles case for array of size 1
https://github.com/apache/datafusion/blob/ec1555871f7a4d4532d7c606745c79f18d5210d1/datafusion/common/src/scalar/mod.rs#L6161-L6174
> optimize `ScalarValue::to_array_of_size` for structural types

- datafusion/sql/src/expr/function.rs
- datafusion/sql/src/expr/mod.rs
- datafusion/sqllogictest/test_files/select.slt
Fixes #14141.
When a reserved function like `user` is called without parenthesis, it may as well be a column. This works in PostgreSQL for example:
```text
psql (17.5 (Debian 17.5-1.pgdg120+1))
Type "help" for help.
postgres=# create table t(a int, "user" text);
CREATE TABLE
postgres=# insert into t values (1, 'foo');
INSERT 0 1
postgres=# select t.user from t;
user
------
foo
(1 row)
postgres=# select user from t;
user
----------
postgres
(1 row)
```
However sqlparser tries to detect these functions, see https://github.com/apache/datafusion-sqlparser-rs/issues/1909
We now first try to use the respective function and then also consider columns.
More sqllogictests
More queries work as expected (IMHO).
> fix: try to lower plain reserved functions to columns as well

- datafusion/core/tests/physical_optimizer/filter_pushdown/mod.rs
- datafusion/datasource/src/source.rs
- datafusion/physical-plan/src/filter.rs
- datafusion/sqllogictest/test_files/parquet_filter_pushdown.slt
- Closes #16563.
Add the missing equivalence info so that optimizer can pick it up when pruning SortExec
Add the equivalence info based on the filters
Added in `parquet_filter_pushdown.slt`
Yes, fix the unexpected behavior
> Add the missing equivalence info for filter pushdown

- datafusion/sqllogictest/bin/sqllogictests.rs
Use the `test-threads` option in sqllogictests if it is passed in, instead of ignoring it.  Default to using get_available_parallelism as before otherwise.
Previously, this option was only added for compatability with the standard test runner, but was ignored.
( This change was suggested by @alamb :
https://github.com/apache/datafusion/pull/16694#discussion_r2190398395 )
Closes #16721
> Use the `test-threads` option in sqllogictests

- datafusion-examples/examples/sql_analysis.rs
- datafusion/catalog/src/memory/table.rs
- datafusion/core/src/datasource/memory_test.rs
- datafusion/core/tests/dataframe/mod.rs
- docs/source/library-user-guide/building-logical-plans.md
- Related to https://github.com/datafusion-contrib/datafusion-postgres/pull/108.
When creating a `MemTable` with no partition (`vec![]`), we will get an error later like this `does not satisfy distribution requirements: SinglePartition. Child-0 output partitioning: UnknownPartitioning(0)\"))"`. Because an execution plan should have at least one partition.
This API is kinda error-prone, so this patch adds a check to make sure `MemTable` has at least one partition. It also fixes several existing examples that use `vec![]` instead of `vec![vec![]]`
> ensure MemTable has at least one partition

- datafusion/core/src/dataframe/mod.rs
- datafusion/core/tests/dataframe/mod.rs
for 
```
SELECT col FROM tb EXCEPT DISTINCT SELECT col FROM tb;
SELECT col FROM tb INTERSECT DISTINCT SELECT col FROM tb;
```
it's already supported in sql. but it's not exposed in dataframe api.
expose intersect distinct/except distinct in dataframe api
UT
No
> feat: expose intersect distinct/except distinct in dataframe api

- datafusion/expr-common/src/type_coercion/binary.rs
- datafusion/sqllogictest/test_files/dates.slt
- Closes #16760
Currently, binary arithmetic expressions involving `NULL` (e.g., `NULL - DATE '1984-02-28'`) fail coercion because they do not account for `NULL` types explicitly. This patch adds support for type coercion when one operand is `NULL`, aligning behavior with SQL semantics where operations involving `NULL` should return `NULL`.
- Added logic in `BinaryTypeCoercer` to handle `NULL` in binary arithmetic expressions by coercing it to the non-null side's type.
- Updated signature resolution to include this new coercion case.
- Added SQL logic tests verifying expected behavior for `NULL` arithmetic with `DATE` values.
Yes. New test cases are added in `dates.slt` to validate arithmetic involving `NULL`, ensuring that:
- `NULL - DATE` returns `NULL`
- `DATE - NULL` returns `NULL` …
> Support Type Coercion for NULL in Binary Arithmetic Expressions

- datafusion/datasource/src/file_compression_type.rs
- datafusion/functions-aggregate-common/src/min_max.rs
- datafusion/functions-aggregate/src/min_max.rs
- datafusion/sqllogictest/test_files/aggregate.slt
- Closes #16513
This
```sql
CREATE TABLE binaries AS VALUES (X'000103', 1);
CREATE VIEW fixed_size_binary_views
AS SELECT arrow_cast(column1, 'FixedSizeBinary(3)') as value, column2 as id FROM binaries;
SELECT id, MIN(value) FROM fixed_size_binary_views GROUP BY id ORDER BY id;
```
led to `Min/Max accumulator not implemented for type FixedSizeBinary`
Extended function-aggregate implementation to support FixedSizeBinary using [new arrow-rs](https://github.com/apache/arrow-rs/issues/7674) `min_fixed_size_binary` function.
Also, removed a leftover `FileTypeExt` after a previous refactoring
- slt integration tests
- manual tests
No
> Support min/max aggregates for FixedSizeBinary type

- datafusion/core/tests/parquet/page_pruning.rs
This should unblock our way to enable filter pushdown by default.
When working on #16711 we keep getting the annoying test error because these two test cases are written without filter-pushdown in mind, i.e., the assertions of **row counts are before filter is applied**
This PR makes it more explicit what to expect with and without filter pushdown.
cc @alamb I think with this change we will get a green light in #16711
> fix tests in page_pruning when filter pushdown is enabled by default

- datafusion-examples/examples/default_column_values.rs
- datafusion-examples/examples/json_shredding.rs
- datafusion/core/src/datasource/listing/table.rs
- datafusion/core/tests/integration_tests/schema_adapter_integration_tests.rs
- datafusion/core/tests/parquet/mod.rs
- datafusion/core/tests/parquet/schema_adapter.rs
- datafusion/datasource-parquet/src/opener.rs
- datafusion/datasource-parquet/src/row_filter.rs
- datafusion/datasource-parquet/src/source.rs
- datafusion/datasource/src/file_scan_config.rs
- datafusion/physical-expr/src/schema_rewriter.rs
- docs/source/library-user-guide/upgrading.md
https://github.com/apache/datafusion/issues/16235#issuecomment-3067125182
This essentially partially reverts https://github.com/apache/datafusion/pull/16461 by keeping backward compatibility with the existing SchemaAdapter.
> Restore custom SchemaAdapter functionality for Parquet

- docs/source/library-user-guide/upgrading.md
- Closes [#16428](https://github.com/apache/datafusion/issues/16428)
Update upgrade md for new unified config for sql string mapping to utf8view
Update upgrade md for new unified config for sql string mapping to utf8view
> Update `upgrading.md` for new unified config for sql string mapping to utf8view

- datafusion/datasource/src/file_scan_config.rs
- datafusion/datasource/src/statistics.rs
- datafusion/sqllogictest/test_files/parquet.slt
- datafusion/sqllogictest/test_files/parquet_sorted_statistics.slt
\-
There are valid cases where files are pre-sorted on nullable columns. Arrow and DataFusion have proper semantic for that.
Removes an exception / special-handling for nullable columns. The Arrow row encoder that is used in the respective code fully supports nullable columns (or at least it will cleanly fail if it doesn't), INCLUDING nulls-first&last.
- regression test (added in 1st commit, fixed in 2nd commit)
- extended/changed unit test for `split_groups_by_statistics`
Some queries are now faster.
> fix: support nullable columns in pre-sorted data sources

- benchmarks/bench.sh
- benchmarks/src/h2o.rs
Currently, we only support for CSV format for h2o benchmark, but from the compare with other database result, it is using parquet, so this ticket try to support parquet format benchmark in datafusion.
Details:
https://github.com/apache/datafusion/issues/16710#issuecomment-3078052376
cc @alamb @Dandandan @2010YOUY01 
Currently, we only support for CSV format for h2o benchmark, but from the compare with other database result, it is using parquet, so this ticket try to support parquet format benchmark in datafusion.
Currently, we only support for CSV format for h2o benchmark, but from the compare with other database result, it is using parquet, so this ticket try to support parquet format benchmark in datafusion.
Tested group by, join, both ok now.
```rust
./bench.sh run …
```
> benchmark: Add parquet h2o support

- datafusion-examples/examples/parquet_index.rs
- Closes #16817
Minor documentation clean-up.
No
> docs: Remove reference to forthcoming example (#16817)

- datafusion-cli/src/object_storage.rs
I have aws s3 configured in my develop env. These two tests fail.
```
cargo test object_storage::tests::s3_object_store_builder_resolves_region_when_none_provided
cargo test object_storage::tests::s3_object_store_builder_default
thread 'object_storage::tests::s3_object_store_builder_resolves_region_when_none_provided' panicked at datafusion-cli/src/object_storage.rs:746:9:
assertion `left == right` failed
left: Some("xxxx")
right: Some("eu-central-1")
```
Set env to a non-existent file to avoid reading the default configuration file
UT
No
> fix: unit test for object_storage

- datafusion/sqllogictest/test_files/array.slt
- datafusion/sqllogictest/test_files/map.slt
- Closes https://github.com/apache/datafusion/issues/16187.
Add tests proving the issue is fixed after the original fix was implemented in arrow-rs 55.2.0
> chore: add tests for out of bounds for NullArray

- benchmarks/src/imdb/run.rs
- benchmarks/src/tpch/run.rs
- datafusion/datasource/src/file_stream.rs
- datafusion/datasource/src/mod.rs
- datafusion/physical-plan/src/metrics/mod.rs
- Closes #.
After reviewing https://github.com/apache/datafusion/pull/16830, I was trying to setup a CI with `cargo-deadlinks` to auto-detect broken links in the doc comments. 
However, I found it a bit tricky, so in this PR I'm fixing some known broken links. I'll also open an issue to set up such a CI check and try to address it later.
Fix broken links in CI
> docs: Fix broken links

- docs/source/library-user-guide/upgrading.md
- Part of https://github.com/apache/datafusion/issues/16235
- While working on the upgrade to delta.rs https://github.com/delta-io/delta-rs/pull/3603 I found that the MSRV has been updated but was not called out in the upgrade guide.
This PR adds a note to the upgrade guide to call out the MSRV update that happened in 
- https://github.com/apache/datafusion/pull/16728
> Add note to upgrade guide about MSRV update

- datafusion/sqllogictest/test_files/join.slt.part
- datafusion/sqllogictest/test_files/joins.slt
- Closes #.
When I was working on a join related task, I found some sqlogictests failing due to different result sort orders.
However, those queries should not assume the returned order, so this PR enforce static order for them using `rowsort` option in sqllogictest framework.
> test: Fix flaky join tests

- datafusion/sqllogictest/test_files/joins.slt
- Closes #.
My local dev branch triggers a heisenbug:
```
cargo test --features backtrace --test sqllogictests
```
The error message said the csv file (the temporary file created inside .slt) does not exist
```
1. query failed: DataFusion error: Internal error: Error encountered while finalizing writes! Partial results may have been written to ObjectStore!.
This issue was likely caused by a bug in DataFusion's code. Please help us to resolve this by filing a bug report in our issue tracker: https://github.com/apache/datafusion/issues
[SQL] COPY (values (1), (2), (3), (4), (5))  TO 'test_files/scratch/limit/t1.csv'
STORED AS CSV
at /Users/yongting/Code/datafusion/datafusion/sqllogictest/test_files/joins.slt:4259
2. query failed: DataFusion error: Object Store error: Object at location …
```
> test: fix more flaky join tests

- datafusion-examples/README.md
- datafusion-examples/examples/async_udf.rs
- datafusion/core/src/execution/context/mod.rs
- docs/source/library-user-guide/functions/adding-udfs.md
- A follow on to https://github.com/apache/datafusion/pull/14837 from @goldmedal 
I was working on writing up DataFusion 49 release notes 
- https://github.com/apache/datafusion-site/pull/91
and I wasn't able to find the async docs quite as nicely as I wanted so I got inspired and went through the example to showcase the LLM usecase a bit more.
1. Add `async_udf.rs` example to examples index page
2. Tweak the library user guide a bit
3. Upgrade the async_udf.rs example to focus on an LLM usecase to try and make it clearer how the async thing benefits
By existing CI
Better docs
> Improve async_udf example and docs

- datafusion/functions/src/string/chr.rs
- Closes #.
I wonder if `chr()` works for larger or negative input when reading https://github.com/apache/datafusion/pull/14700, as I read from [`encode_utf8`](https://doc.rust-lang.org/std/primitive.char.html#method.encode_utf8) would panic if the provided buffer is not large enough. So I added some unit test cases to verify. It turns out `chr()` can handle input like `i64::MAX` (gated by `core::char::from_u32`), but it does miss the negative case.
Add unit tests to `chr()` function. And check if the input is negative.
My local bench result shows the extra check won't slow this function by a lot
```
chr                     time:   [5.1686 µs 5.1726 µs 5.1774 µs]
change: [+0.3217% +0.4109% +0.5066%] (p = 0.00 < 0.05)
Found 3 outliers among 100 measurements …
```
> MINOR: add unit tests for chr function

- datafusion/datasource-parquet/src/source.rs
- datafusion/datasource/src/file_scan_config.rs
- datafusion/datasource/src/source.rs
I spoke with @alamb about continuing to refactor these traits with the goal of eventually getting projection pushdown.
We agreed tugging at loose ends of the knot is a good place to start, and removing deprecated methods is a good place to do so.
> remove deprecated methods from FileScanConfig / DataSourceExec

- Cargo.lock
- datafusion/core/src/physical_planner.rs
- datafusion/ffi/src/udaf/accumulator_args.rs
- datafusion/physical-plan/src/aggregates/mod.rs
- datafusion/proto/Cargo.toml
- datafusion/proto/proto/datafusion.proto
- datafusion/proto/src/generated/pbjson.rs
- datafusion/proto/src/generated/prost.rs
- datafusion/proto/src/physical_plan/from_proto.rs
- datafusion/proto/src/physical_plan/mod.rs
- datafusion/proto/src/physical_plan/to_proto.rs
- datafusion/proto/tests/cases/roundtrip_physical_plan.rs
- Closes  #16772 
Serialization and deserialization of physical plans are currently incomplete. This PR introduces the necessary fixes to ensure all TPC-H queries pass.
**Summary of Changes:**
1. Introduced pretty_assertions in the proto crate to highlight test output differences more clearly. This addition aids debugging, though I’m open to reverting it if it noticeably impacts crate size.
2. Resolved the missing aggregate in human_display by adding a corresponding field to the proto definition.
3. Corrected the date_part display function by introducing a new proto field to handle it properly.
4. Fixed the issue of extra [] in non-group-by aggregates by checking for empty group-by conditions.
5. Enabled roundtrip tests for all TPC-H queries to ensure correctness and completeness.
Yes
- …
> Fixes 3 bugs during serialization and deserialization of physical plans

- datafusion/core/tests/user_defined/user_defined_scalar_functions.rs
- datafusion/expr/src/async_udf.rs
- datafusion/expr/src/expr_fn.rs
- datafusion/expr/src/udf.rs
- datafusion/expr/src/utils.rs
- datafusion/ffi/src/udf/mod.rs
- datafusion/proto/tests/cases/mod.rs
- datafusion/sql/tests/sql_integration.rs
Reduce boilerplate in cases where implementation of `{ScalarUDFImpl,AggregateUDFImpl,WindowUDFImpl}::{equals,hash_value}` can be derived using standard `PartialEq` and `Hash` traits.
This is code complexity reduction. Follows https://github.com/apache/datafusion/pull/16781
While valuable on its own, this also prepares for more automatic derivation of UDF equals/hash and/or removal of default implementations (which currently are error-prone) -- https://github.com/apache/datafusion/issues/16677
- closes https://github.com/apache/datafusion/issues/16865
> Derive UDF equality from PartialEq, Hash

- datafusion/common-runtime/src/common.rs
- Closes #.
When implementing `Stream`s with `SpawnedTask` objects, the `poll_next` requires `&mut self `, but the existing `join_unwind` method consumes the `SpawnedTask`. The new `join_unwind_mut` method allows polling task completion status while retaining the `SpawnedTask` for subsequent polls.
Added `join_unwind_mut(&mut self)` method to `SpawnedTask` that mirrors the behavior of `join_unwind(self)`
> Mutable Join Unwind

- Cargo.lock
- datafusion/spark/Cargo.toml
- datafusion/spark/src/function/datetime/last_day.rs
- datafusion/spark/src/function/datetime/mod.rs
- datafusion/sqllogictest/test_files/spark/datetime/last_day.slt
- Closes #16774.
- Part of #15914.
Implement Spark datetime function last_day
I added tests for `last_day` function.
yes, new function.
> feat(spark): implement Spark datetime function last_day

- datafusion/common/src/scalar/mod.rs
- Closes #.
We use these utils in our fork and think they could be useful in here as well. They provide convenient ways to create default, minimum, and maximum ScalarValue instances for various data types.
* Add ScalarValue::new_default() - returns default values for data types (zero for numeric, empty for strings/collections)
* Add ScalarValue::min() - returns minimum representable values for numeric/temporal types
* Add ScalarValue::max() - returns maximum representable values for numeric/temporal types
> ScalarValue Default + Min + Max

- datafusion/expr-common/src/interval_arithmetic.rs
- Closes #.
I'm adding `is_superset` method to the `Interval` to check if one interval is a superset of another, with support for both strict and non-strict checks.
* is_superset method to Interval that checks if an interval contains another interval
* unit tests
Yes, with `test_is_superset`
> minor: add is_superset() method for Interval's

- datafusion/expr/src/window_state.rs
- datafusion/physical-expr/src/aggregate.rs
- datafusion/physical-expr/src/expressions/literal.rs
- datafusion/physical-expr/src/window/aggregate.rs
- datafusion/physical-expr/src/window/sliding_aggregate.rs
- datafusion/physical-expr/src/window/standard.rs
- datafusion/physical-expr/src/window/window_expr.rs
- datafusion/physical-plan/src/aggregates/group_values/single_group_by/bytes.rs
- datafusion/physical-plan/src/test.rs
- Closes #.
AggregateFunctionExpr::with_new_expressions()` has been implemented. This is useful when updating column indices within the expressions of an `AggregateFunctionExpr`.
Additionally, `create_window_fn()` method has been added to the `WindowExpr` trait. This provides a convenient way to directly access the underlying window function evaluator.
* AggregateFunctionExpr::with_new_expressions()
* WindowExpr::create_window_fn()
* Some derive-Clone's
> minor: implement with_new_expressions for AggregateFunctionExpr

- datafusion/physical-plan/src/metrics/value.rs
- Closes #.
Add methods to `Time` and `ScopedTimerGuard` that allow measuring elapsed time with custom start/end instants instead of relying on `Instant::now()`.
* Add `timer_with(now: Instant)` to `Time` - creates a timer starting from a specific instant
* Add `stop_with(end_time: Instant)` to `ScopedTimerGuard` - stops timer with a custom end time
* Add `done_with(end_time: Instant)` to `ScopedTimerGuard` - stops timer with custom end time and consumes self
* Add unit tests 
Yes, unit tests are added
> Implement Helpers for ScopedTimerGuard and Time Structs

- datafusion/optimizer/src/push_down_filter.rs
- datafusion/sqllogictest/test_files/push_down_filter.slt
- docs/source/user-guide/sql/special_functions.md
- Closes #16695.
Added new test case in `push_down_filter.slt`
No.
> fix: skip predicates on struct unnest in PushDownFilter

- datafusion/functions/src/unicode/initcap.rs
- A small change derived from https://github.com/apache/datafusion/pull/13691#discussion_r1882903037
I'm not sure if there is a way to write into String View Builder char by char, so I keep the skeleton, but trying to reuse the allocated intermediate `String`. 
Benchmark result (not too much)
```
initcap string view shorter than 12 [size=1024]
time:   [14.302 µs 14.317 µs 14.330 µs]
change: [-15.157% -15.023% -14.900%] (p = 0.00 < 0.05)
initcap string view longer than 12 [size=1024]
time:   [25.708 µs 25.734 µs 25.761 µs]
change: [+0.8967% +1.0978% +1.2905%] (p = 0.00 < 0.05)
initcap string [size=1024]
time:   [24.750 µs 24.787 µs 24.835 µs]
change: [-0.9080% …
```
> optimize `initcap` function by avoiding memory allocation

- datafusion/ffi/src/udaf/mod.rs
- datafusion/functions-aggregate/src/sum.rs
- datafusion/sqllogictest/test_files/window.slt
We added the new feature for support distinct operation for window, and added count support.
- Follow-up [#16925](https://github.com/apache/datafusion/pull/16925)
This PR is to add sum support.
We added the new feature for support distinct operation for window, and added count support.
- Follow-up [#16925](https://github.com/apache/datafusion/pull/16925)
This PR is to add sum support.
Also fix the typo in window.slt.
Yes, slt testing added.
New sum distinct feature supported.
> feat: Support distinct window for sum

- datafusion/core/tests/physical_optimizer/filter_pushdown/mod.rs
- datafusion/physical-plan/src/execution_plan.rs
- datafusion/physical-plan/src/filter_pushdown.rs
- datafusion/physical-plan/src/joins/hash_join.rs
Replaces a piece of https://github.com/apache/datafusion/pull/16445 to break up into smaller PRs
> Enable physical filter pushdown for hash joins

- datafusion/functions-window/src/cume_dist.rs
- datafusion/functions-window/src/lead_lag.rs
- datafusion/functions-window/src/nth_value.rs
- datafusion/functions-window/src/ntile.rs
- datafusion/functions-window/src/rank.rs
- datafusion/functions-window/src/row_number.rs
- docs/source/user-guide/sql/window_functions.md
This is a quick fix while reading the docs page at https://datafusion.apache.org/user-guide/sql/window_functions.html.
The Analytical Functions section is malformed.
A markdown format fix.
Tested via the github preview page on the PR.
This only affects documentation.
> Fix window_functions docs formatting

- datafusion-examples/examples/composed_extension_codec.rs
- datafusion/proto/src/physical_plan/mod.rs
Closes #16980 .
Tested via:
```sh
cargo run --package datafusion-examples --example composed_extension_codec
```
No.
> fix: `ComposedPhysicalExtensionCodec` does not use the same codec as encoding when decoding

- datafusion/functions-window/src/row_number.rs
#17014 changed the generated documentation file rather than the source used to generate the documentation, which has caused the "check configs.md and ***_functions.md is up-to-date" CI check to start failing.
This fixes the source example to remove the extra `#`
> docs: Fix failing documentation check in CI

- dev/update_config_docs.sh
- docs/source/user-guide/configs.md
I wrote up some guidance for running datafusion with "small" data in https://github.com/apache/datafusion/issues/17025#issuecomment-3151817573 that I felt was worth capturing in the documentation
- Add information about tuning datafusion for small data / short queries to the configuration page
By CI (and I tested them locally)
> Docs: Add Tuning Guide for small data / short queries

- docs/source/user-guide/crate-configuration.md
I was trying to add a [tuning guide for small data / short queries](https://github.com/apache/datafusion/pull/17040) but got nerd-sniped into fixing
the crate configuration guidelines while finding a place to the tuning guide
1. Make it clear there are several potential build optimizations, and update the explanations
2. Polish text
By docs CI
Better docs
> Docs: Update the crate configuration / build settings page

- datafusion/substrait/src/extensions.rs
- datafusion/substrait/src/logical_plan/consumer/expr/scalar_function.rs
- datafusion/substrait/tests/cases/roundtrip_logical_plan.rs
- Closes #16949.
We've identified Substrait functions that have implementations in DataFusion, but are not mapped to those functions because their names are slightly different. For example, DataFusion does not understand the Substrait is_nan function, because DataFusion's name for the same function is isnan, and the Substrait consumer and producer work off of direct name mappings.
- New mapping created in the consumer to map Substrait names to DataFusion names
- Added new name mappings to the existing mapping of DataFusion names to Substrait names; in the producer, the register_function() calls the implementation of register_function() in Extensions, and this registers function names with function anchors (so this is where mappings are added).
This PR adds mappings for the Substrait …
> Add missing Substrait to DataFusion function name mappings

- datafusion/physical-plan/src/sorts/cursor.rs
This is the follow-up for https://github.com/apache/datafusion/pull/16630
We can use upstream inline_key_fast now since arrow-rs new release has the ability.
Change to use upstream inline_key_fast.
Change to use upstream inline_key_fast.
Yes, the upstream including the tests already.
No
> refactor: use upstream arrow-rs inline_key_fast

- Cargo.lock
- datafusion/spark/Cargo.toml
- datafusion/spark/src/function/hash/crc32.rs
- datafusion/spark/src/function/hash/mod.rs
- datafusion/spark/src/function/hash/sha1.rs
- datafusion/sqllogictest/test_files/spark/hash/crc32.slt
- datafusion/sqllogictest/test_files/spark/hash/sha.slt
- datafusion/sqllogictest/test_files/spark/hash/sha1.slt
implement spark udf  crc32/sha1
UT
No
> feat(spark): implement spark hash function crc32/sha1

- datafusion/datasource-parquet/src/source.rs
See original PR: https://github.com/apache/datafusion/pull/16968
(cherry picked from commit 0183244a426e5e1fda28c7b6e6961f70f04c0744)
- Closes #.
See https://github.com/apache/datafusion/issues/17036#issuecomment-3161369093
Cherrypick https://github.com/apache/datafusion/commit/0183244a426e5e1fda28c7b6e6961f70f04c0744 into `branch-49`
This removes a warning when instantiating a `SchemaAdapter` related to deprecation since its replacement is not complete yet, thus users can't complete the migration yet.
> [branch-49] remove warning from every file open

- datafusion/core/tests/user_defined/user_defined_window_functions.rs
- datafusion/expr/src/async_udf.rs
- datafusion/expr/src/expr_fn.rs
- datafusion/expr/src/lib.rs
- datafusion/expr/src/ptr_eq.rs
- datafusion/expr/src/udwf.rs
- datafusion/expr/src/utils.rs
- datafusion/ffi/src/udwf/mod.rs
- datafusion/functions-window/src/lead_lag.rs
- datafusion/functions-window/src/nth_value.rs
- datafusion/functions-window/src/rank.rs
- datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs
- datafusion/proto/tests/cases/mod.rs
Reduce boilerplate in cases where implementation of `{ScalarUDFImpl,AggregateUDFImpl,WindowUDFImpl}::{equals,hash_value}` can be derived using standard `PartialEq` and `Hash` traits.
This is code complexity reduction. Follows https://github.com/apache/datafusion/pull/16842
While valuable on its own, this also prepares for more automatic derivation of UDF equals/hash and/or removal of default implementations (which currently are error-prone) -- https://github.com/apache/datafusion/issues/16677
- closes https://github.com/apache/datafusion/issues/16867
> Derive UDWF equality from PartialEq, Hash

- datafusion/physical-expr/src/expressions/is_not_null.rs
- datafusion/physical-expr/src/expressions/is_null.rs
- datafusion/sqllogictest/test_files/expr.slt
- Closes #17055.
Removes incorrect `return_field` implementation from `IsNotNull` physical expression - it was forwarding to its input which meant it was incorrectly claiming the return datatype was the same as the input.
Yes.
Bugfix.
> fix return field for `is_not_null` expression

- datafusion/functions-aggregate/src/array_agg.rs
The `ArrayAgg` struct is stateful, therefore it must implement `AggregateUDFImpl::equals` and `hash_value` functions.
> Fix equality of parametrizable ArrayAgg function

- Cargo.lock
- datafusion/spark/Cargo.toml
- datafusion/spark/src/function/url/mod.rs
- datafusion/spark/src/function/url/parse_url.rs
- datafusion/sqllogictest/test_files/spark/url/parse_url.slt
- Part of #15914.
Implement Spark `url` function `parse_url`
Yes
Yes
> Implement Spark `url` function `parse_url`

- datafusion/core/tests/user_defined/user_defined_aggregates.rs
- datafusion/core/tests/user_defined/user_defined_scalar_functions.rs
- datafusion/core/tests/user_defined/user_defined_window_functions.rs
- datafusion/doc/src/lib.rs
- datafusion/expr/src/async_udf.rs
- datafusion/expr/src/expr_fn.rs
- datafusion/expr/src/lib.rs
- datafusion/expr/src/ptr_eq.rs
- datafusion/expr/src/udaf.rs
- datafusion/expr/src/udf.rs
- datafusion/expr/src/udf_eq.rs
- datafusion/expr/src/udwf.rs
- datafusion/expr/src/utils.rs
- datafusion/ffi/src/udaf/mod.rs
- datafusion/ffi/src/udf/mod.rs
- datafusion/ffi/src/udwf/mod.rs
- datafusion/functions-aggregate/src/approx_percentile_cont.rs
- datafusion/functions-aggregate/src/approx_percentile_cont_with_weight.rs
- datafusion/functions-aggregate/src/array_agg.rs
- datafusion/functions-aggregate/src/bit_and_or_xor.rs
- datafusion/functions-aggregate/src/first_last.rs
- datafusion/functions-aggregate/src/regr.rs
- datafusion/functions-aggregate/src/stddev.rs
- datafusion/functions-aggregate/src/string_agg.rs
- datafusion/functions-window/src/lead_lag.rs
- datafusion/functions-window/src/nth_value.rs
- datafusion/functions-window/src/rank.rs
- datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs
- datafusion/proto/tests/cases/mod.rs
- datafusion/sql/tests/sql_integration.rs
Reduce boilerplate in cases where implementation of `AggregateUDFImpl::{equals,hash_value}` can be derived using standard `Eq` and `Hash` traits.
This is code complexity reduction. Follows https://github.com/apache/datafusion/pull/17057
While valuable on its own, this also prepares for more automatic derivation of UDF equals/hash and/or removal of default implementations (which currently are error-prone) -- https://github.com/apache/datafusion/issues/16677
- fixes https://github.com/apache/datafusion/issues/16866
> Derive UDAF equality from Eq, Hash

- datafusion/common/src/test_util.rs
- Closes #17101.
Make both macros slightly nicer to use, and prevent some potentially confusing error messages.
> Make macros in common::test_util hygenic and not dependent on user dependencies

- datafusion/expr/src/planner.rs
- datafusion/expr/src/simplify.rs
- datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs
Whilst looking at #16652 I saw some other uses of `#[allow(clippy::large_enum_variant)]`; tested removing some of these and looks fine now, clippy not complaining. Might as well clean these up in that case.
> minor: remove unnecessary clippy:large_enum_variant allows

- datafusion/core/tests/physical_optimizer/join_selection.rs
- datafusion/physical-expr/src/equivalence/properties/joins.rs
- datafusion/physical-plan/src/joins/test_utils.rs
- datafusion/physical-plan/src/joins/utils.rs
- datafusion/sqllogictest/test_files/joins.slt
- Closes #.
While building the equivalence properties of joins, we can identify more precise orderings when the join is a LeftJoin and the join algorithm preserves the order of the left input (and similarly for RightJoin with the right input).
In addition to the main change described above:
* Replaced `hash_join_swap_subrule` with the actual optimizer rule it represents, as this is the rule we should be testing
* Extended the columns in the `build_sides_record_batches` utility to include a new column that generates randomly ordered data. While not yet used, this column will be useful for future fuzz testing of joins.
* Increased the visibility of `reorder_output_after_swap()` and `swap_join_projection()`, as these functions are likely to be needed across optimizer rules.
> minor: Improve equivalence handling of joins

- datafusion/expr-common/src/operator.rs
- datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs
- datafusion/optimizer/src/simplify_expressions/unwrap_cast.rs
- datafusion/sqllogictest/test_files/errors.slt
- datafusion/sqllogictest/test_files/parquet.slt
- datafusion/sqllogictest/test_files/predicates.slt
- datafusion/sqllogictest/test_files/spark/predicate/ilike.slt
- datafusion/substrait/tests/cases/roundtrip_logical_plan.rs
There were optimizations simplifying some arithmetic operations (`*`, `/`, `%` and some bitwise operations) when one operand is constant `NULL`. This can be extended to almost all other binary operators.
> Simplify comparisons and binary operations involving NULL

- clippy.toml
- datafusion/sqllogictest/src/engines/datafusion_engine/error.rs
- Closes #16652
Most of the work to close this issue was done by #16653 and #16672 anyway; here we just try set a lower threshold for clippy to warn us about error variants being too large (from default of 128 to 70) so hopefully we can identify any future issues quicker.
> Set a lower threshold for clippy to flag large error variants

- datafusion/functions/src/datetime/date_part.rs
- datafusion/sqllogictest/test_files/expr/date_part.slt
- docs/source/user-guide/sql/scalar_functions.md
- Closes #17111.
Yes, SLT tests added.
`isoweek` support added to `date_part`
> feat: add `isodow` (ISO day-of-week) support to date_part (Monday = 0)

- docs/source/contributor-guide/development_environment.md
- rust-toolchain.toml
~~I'm using [helix](https://github.com/helix-editor/helix/), and the lsp integration wasn't working since it was trying to use the rust-analyzer component from the pinned toolchain, whilst I apparently only had rust-analyzer for latest toolchain.~~
~~Let me know if there's a better solution for this 🙂~~
Related: #14655
Update the documentation to reflect this edge case instead of requiring this new component for all CI runs
> Update dev env documentation to reflect pinned rust version

- datafusion/functions/src/core/getfield.rs
There is no need to create intermediate `ScalarValue::Utf8` if all we want is the inner value.
> Simplify `GetFieldFunc`'s `display_name`, `schema_name`

- datafusion/datasource-parquet/src/reader.rs
- Closes #.
When compiling `datafusion-cli` with `cargo run`, there is a compiler warning:
```sh
warning: unused variable: `options`
--> datafusion/datasource-parquet/src/reader.rs:247:9
|
247 |         options: Option<&'a ArrowReaderOptions>,
|         ^^^^^^^ help: if this is intentional, prefix it with an underscore: `_options`
|
= note: `#[warn(unused_variables)]` on by default
```
This PR uses `#[allow(unused_variables)]` to suppress the warning.
> Minor: Fix compiler warning when compiling `datafusion-cli`

- datafusion/physical-plan/src/projection.rs
- Related to https://github.com/apache/datafusion/issues/17122
- follow on to https://github.com/apache/datafusion/pull/17123
@hareshkh [tracked down](https://github.com/apache/datafusion/issues/17122#issuecomment-3178108708) a performance issue in the stats projection code where we were silently ignoring errors when evaluating the stats projection. This both 
1. Silently masked a real bug (fixed in https://github.com/apache/datafusion/pull/17123)
2. Caused a performance issue (each DataFusion error allocates a String)
Let's not ignore errors silently, but instead return them to the caller.
1. Return errors rather than ignoring them
Yes, by existing CI tests
No
> Refactor: Do not silently ignore errors in `stats_projection`

- Cargo.lock
- Closes #17208.
https://github.com/apache/datafusion/blob/0a024a2f0e64194042c2965804dce20669047113/Cargo.lock#L1816-L1818
https://github.com/apache/datafusion/blob/0a024a2f0e64194042c2965804dce20669047113/Cargo.lock#L2466-L2468
the version of `datafusion-physical-expr-adapter` does not match with `datafusion` in Cargo.lock
update `datafusion-physical-expr-adapter` version to 49.0.1 in `Cargo.lock`
ci test
no
> fix(ci): update `datafusion-physical-expr-adapter` version to 49.0.1in Cargo.lock

- datafusion/core/src/datasource/listing/table.rs
- datafusion/core/src/lib.rs
- datafusion/execution/src/cache/cache_manager.rs
- datafusion/execution/src/cache/cache_unit.rs
- closes https://github.com/apache/datafusion/issues/17048
- Closes https://github.com/apache/datafusion/issues/17000
As explained on the ticket 
> DataFusion's built in ListingTable will soon have metadata caching 🎉
>
> I think we should make sure this feature is more discoverable via the docs
Revamp and extend documentation for `LIstingTable` and the various CacheManager structures
By Docs ci
Better docs. No function changes intended
> [Parquet Metadata Cache] Document the ListingTable cache

- docs/source/library-user-guide/upgrading.md
- Closes #.
https://github.com/apache/datafusion/pull/16996 did a complete rewrite for Nested Loop Join operator, and it includes a implicit breaking change: the input sort order could no longer be preserved, comparing to the old version. I think it's important to add to the upgrade guide.
> Doc: Update upgrade guide for the rewritten NLJ operator

- datafusion/core/tests/user_defined/user_defined_plan.rs
- datafusion/expr/src/logical_plan/extension.rs
- datafusion/expr/src/logical_plan/invariants.rs
- datafusion/substrait/tests/cases/roundtrip_logical_plan.rs
In `UserDefinedLogicalNode::check_invariants`, the actual plan to check for invariants is `self`. The `plan` is always `LogicalPlan::Extension` and provides no further information.  It's confusing.
- extracted from https://github.com/apache/datafusion/pull/17189
> Remove redundant `plan` from extension's check_invariants

- datafusion/proto/proto/datafusion.proto
- datafusion/proto/src/generated/pbjson.rs
- datafusion/proto/src/generated/prost.rs
- datafusion/proto/src/physical_plan/from_proto.rs
- datafusion/proto/src/physical_plan/to_proto.rs
- datafusion/proto/tests/cases/roundtrip_physical_plan.rs
No issue, just an error we're seeing in production
Adds support for the `ignore_nulls` and `distinct` clauses of window expressions during proto serialization
Some changes to the protobuf node and accompanying support in to/from modules.
Yes tests are included
Not really, this is a pretty straight forward change to proto serialization
> Preserve `distinct` and `ignore_nulls` in window expressions during proto serde

- datafusion/proto/src/physical_plan/mod.rs
- datafusion/proto/tests/cases/roundtrip_physical_plan.rs
> fix: deserialization error for `FilterExec` (predicates with inlist)

- datafusion/physical-plan/src/sorts/sort.rs
N/A
In `ExternalSorter` there are cases where the `batch_size` config is not respected
Wrap the stream with `BatchSplitStream` when we only have a single batch to sort and when we can sort in place (the paths that did not respect the batch size)
Yes
Not an API change
> fix: sort should always output batches with `batch_size` rows

- datafusion/ffi/src/record_batch_stream.rs
- related to https://github.com/apache/datafusion/issues/17241
Back port a memory leak from main into `branch-49`. Original PR: https://github.com/apache/datafusion/pull/17190
Current users of the record batch stream FFI can experience a memory leak.
One file changed.
Tests performed on initial PR, but this is very hard to include in a unit test approach with FFI.
None
> [branch-49] FFI_RecordBatchStream was causing a memory leak (#17190)

- datafusion/physical-expr-common/src/datum.rs
- datafusion/sqllogictest/test_files/array.slt
- Closes #17263 .
- Error occurred in BooleanArray::new() when comparing nested arrays (arrays of arrays)
- Root cause: Null buffer length mismatch in scalar-to-array comparisons
- Fixed Length Mismatch: Null buffers now correctly match result array length
- Proper Null Propagation: Null scalars correctly propagate to entire result
- Combined Cases: (false, false) | (true, true) use same logic
- Clear Intent: filter(|nulls| !nulls.is_valid(0)) clearly shows null scalar check
> fix: align `array_has` null buffer for scalar

- datafusion/physical-expr-common/src/datum.rs
- datafusion/sqllogictest/test_files/array.slt
* fix: align `array_has` null buffer for scalar
- Closes #.
> fix: align `array_has` null buffer for scalar (#17272)

- datafusion/core/tests/physical_optimizer/filter_pushdown/mod.rs
- datafusion/physical-plan/src/joins/hash_join.rs
Fixes https://github.com/apache/datafusion/actions/runs/17135806873/job/48611550480#step:6:1257
> Make dynamic filter creation in HashJoinExec deterministic against partition evaluation order

- datafusion/expr-common/src/signature.rs
- datafusion/expr/src/udf.rs
- Related to https://github.com/apache/datafusion/pull/17195
While reviewing https://github.com/apache/datafusion/pull/17195 from @mbutrovich  and other recent PRs related to type signatures, I believe the current behavior and implications of TypeSignatures is not clear; I think it is especially confusing to understand what "supported" means
Thus I would like to improve the docs to help 
Improve the documentation for type signatures in general to explain what they mean and the implications better.
By CI
Some better docs and examples
> Improve documentation for Signature, Volatility, and TypeSignature

- datafusion/datasource-parquet/src/source.rs
- datafusion/sqllogictest/test_files/parquet_statistics.slt
- N/A.
The output of the `EXPLAIN ANALYZE` contained an additional line break in the `DataSourceExec`, which causes the plan to become misformatted.
Example
```sql
-- before
+-------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- …
```
> minor: Remove extra line break in explain physical plan

- datafusion/sql/src/select.rs
- datafusion/sqllogictest/test_files/from-first.slt
- docs/source/user-guide/sql/select.md
- Closes #.
I noticed in https://github.com/apache/datafusion/pull/17278 that `from` without an explicit projection did not work.
This should fix it.
The from-first syntax is also available in duckdb. See https://duckdb.org/docs/stable/sql/query_syntax/from.html#examples
Yes, added SLT test
FROM-first syntax without projection is now supported.
> Support from-first SQL syntax

- datafusion/datasource-parquet/src/opener.rs
- Follow on to https://github.com/apache/datafusion/pull/16433
While reviewing https://github.com/apache/datafusion/pull/16433 (see https://github.com/apache/datafusion/pull/16433#discussion_r2294296505) 
> I found this code somewhat 🤯 (and this function is already 100s of lines long) I spent some time refactoring it into its own stream for readability
Extract out the early termination code into its own stream structure
No, this is internal refactoring only
> Encapsulate early File pruning in parquet opener in its own stream

- datafusion/proto/proto/datafusion.proto
- datafusion/proto/src/generated/pbjson.rs
- datafusion/proto/src/generated/prost.rs
- datafusion/proto/src/physical_plan/mod.rs
- datafusion/proto/tests/cases/roundtrip_physical_plan.rs
- Closes #17292
As described in #17292
A proto definition for SortMergeExec, and test to verify them 
Note 0: there is a bit of duplication of code between all joins we have, we may want to consolidate the logic at some point 
Yes, two round trip tests added 
Note 1: test `roundtrip_logical_plan_sort_merge_join` looks more like tests used in logical_codec_round trip than physical_codec_round trip, but I find it useful. It can be removed as there is other test testing round trip
No
> feat: Support SortMergeJoin proto serde

- .github/workflows/rust.yml
- datafusion/core/tests/physical_optimizer/filter_pushdown/mod.rs
- datafusion/physical-plan/src/joins/join_filter.rs
- datafusion/physical-plan/src/joins/nested_loop_join.rs
- typos.toml
- follow up of https://github.com/apache/datafusion/pull/17135#pullrequestreview-3155345954
Add a CI job to check typo (we got four new typos in these two weeks XD)
A new ci job
> add a ci job for typo checking

- datafusion/physical-plan/src/spill/spill_manager.rs
When we spill `RecordBatch` on external sorting, we call `batch.get_sliced_size` to report `max_record_batch_size` in each spill file. Thereby we can safely read the batch back from spill file with correct memory estimation. However, it is found (in https://github.com/apache/datafusion/pull/17029) that `get_sliced_size` underestimated the memory size for `StringViewArray`. The diff was quite large i.e. when correct batch size was 1392730 bytes, it returned 163840 bytes, which means the actual memory usage may far exceed the configured memory_limit, especially when merging spill file. 
This underestimation happens because arrow api `get_slice_memory_size` counts for only `views` buffer for `StringViewArray` while ignoring the capacity for `data` (payload) buffer. 
See …
> Fix incorrect memory accounting for sliced `StringViewArray`

- datafusion/core/src/physical_planner.rs
- Closes #.
use the same level as the logical optimizer
https://github.com/apache/datafusion/blob/3f70c9a2b78a62bbb8eb4d96487318e709741b0a/datafusion/optimizer/src/optimizer.rs#L381-L389
change per-step log of physical optimizer from `trace!` to `debug!`
log content
> minor: use debug level log for physical optimizer

- docs/source/user-guide/sql/ddl.md
None since this is just a small documentation fix
SQL syntax is incorrect
Adds a single `S`
Manually tested the fixed query
No
> Fix syntax error in DDL documentation example

- datafusion/sql/src/statement.rs
- datafusion/sqllogictest/test_files/order.slt
- Closes #17392.
A blind `unwrap` call can currently trigger panics during query parsing.
Correctly handle and propagate the `Err` case.
Yes, an additional test was added to check that the panic no longer occurs
No
> Avoid panic when 'with order' expression could not be converted to a logical expression

- datafusion/expr/src/logical_plan/plan.rs
Before the changes, `PartialOrd` could return `Some(Equal)` for two `Window` nodes that are not equal in `PartialEq` sense. This is violation of `PartialOrd` contract.
The fix is to consult eq inside ord implementation. If ord thinks two instances are equal, but they are not equal in Eq sense, they are considered incomparable.
- follows https://github.com/apache/datafusion/pull/17182
- for https://github.com/apache/datafusion/issues/17064
> Fix PartialOrd for Window

- datafusion/core/tests/physical_optimizer/filter_pushdown/mod.rs
- datafusion/physical-plan/src/joins/hash_join/exec.rs
Any system that applies additional optimizer rules or otherwise manipulates plans will end up calling `with_new_children` which wipes out the bounds accumulator thus disabling the optimization.
> fix bounds accumulator reset in HashJoinExec dynamic filter pushdown

- datafusion/datasource-parquet/src/opener.rs
- Closes #17352
Allows taking advantage of page indexes to optimize queries when reading encrypted Parquet files.
Removes previous workaround disabling page index reading when a Parquet file is encrypted.
Yes, reading the page index is enabled by default so this is covered by existing encryption tests, eg. https://github.com/apache/datafusion/blob/051269e97aa08d7a631c7ab44b48ffa1ba9e822f/datafusion/core/src/dataframe/parquet.rs#L252
No
> Re-enable page index for encrypted Parquet

- datafusion/core/src/lib.rs
- datafusion/datasource-avro/src/mod.rs
- Closes https://github.com/apache/datafusion/issues/17389
When the avro feature flag is set, it would be useful for us to be able to import apache_avro from datafusion so that the versions are always aligned, similarly to how parquet currently works.
- Exporting apache_avro from datasource_avro
- Exporting datafusion_datasource_avro::apache_avro from lib.rs
This change only adds an export when a feature flag is set, I don't know if there's a good way to test this, and it's a very small change that's unlikely to cause any regressions.
> Re-export apache-avro when avro feature flag is set

- docs/source/library-user-guide/profiling.md
I noticed in the profiling docs the `--` renders as a larger dash in the text (top of the pic). I figured, I'd submit a quick fix since the "Edit this page" button is so conveniently there :).
Adds backticks to render it properly. It should now render it as two separate dash in orange similar to this text later in the page
> docs: Render `--` properly in profiling docs

- datafusion/physical-plan/src/joins/sort_merge_join/exec.rs
- datafusion/physical-plan/src/joins/sort_merge_join/stream.rs
- datafusion/sqllogictest/test_files/sort_merge_join.slt
N/A
Adds the ability for the `SortMergeJoin` physical node to join on binary types:
- `Binary`,
- `FixedSizeBinary`
- `BinaryView`
- `LargeBinary`
- An update to the comparitor functions to support the listed binary types
- Tests to verify binary types are supported via the `ON` clause
✅ 
The documentation does not list the subset of types supported by the `ON` clause of `SortMergeJoin`.
> feat: Support binary data types for `SortMergeJoin` `on` clause

- datafusion/expr/src/lib.rs
- datafusion/expr/src/udaf.rs
Extract AggregateUDFImpl method that have complex implementations. This makes it feasible to implement that trait with
`#[warn(clippy::missing_trait_methods)]` Clippy check enabled. That check is very helpful when the type implementing `AggregateUDFImpl` delegates many methods to another `AggregateUDFImpl` implementation and therefore does not want to unconsciously rely on default implementation. Sadly, Rust does not allow explicitly delegating to trait method's default implementation. Extracting the logic to standalone functions works around that limitation.
> Extract complex default impls from AggregateUDFImpl trait

- datafusion/common/src/config.rs
- datafusion/core/src/datasource/file_format/csv.rs
- datafusion/core/src/datasource/file_format/options.rs
- datafusion/datasource-csv/src/file_format.rs
- datafusion/datasource-csv/src/source.rs
- datafusion/proto-common/proto/datafusion_common.proto
- datafusion/proto-common/src/from_proto/mod.rs
- datafusion/proto-common/src/generated/pbjson.rs
- datafusion/proto-common/src/generated/prost.rs
- datafusion/proto-common/src/to_proto/mod.rs
- datafusion/proto/proto/datafusion.proto
- datafusion/proto/src/generated/datafusion_proto_common.rs
- datafusion/proto/src/generated/pbjson.rs
- datafusion/proto/src/generated/prost.rs
- datafusion/proto/src/logical_plan/file_formats.rs
- datafusion/proto/src/physical_plan/mod.rs
Support csv truncated rows in datafusion
- Closes [#17464](https://github.com/apache/datafusion/issues/17464)
Support csv truncated rows in datafusion
Support csv truncated rows in datafusion
Yes
New feature support.
> Support csv truncated rows in datafusion

- datafusion/common/src/stats.rs
- datafusion/core/tests/custom_sources_cases/statistics.rs
- datafusion/core/tests/physical_optimizer/partition_statistics.rs
- datafusion/physical-plan/src/coalesce_batches.rs
- datafusion/physical-plan/src/coalesce_partitions.rs
- datafusion/physical-plan/src/limit.rs
- datafusion/physical-plan/src/sorts/sort.rs
- datafusion/sqllogictest/test_files/parquet_statistics.slt
> better preserve statistics when applying limits

- datafusion/expr/src/expr.rs
- datafusion/expr/src/logical_plan/ddl.rs
- datafusion/expr/src/logical_plan/dml.rs
- datafusion/expr/src/logical_plan/extension.rs
- datafusion/expr/src/logical_plan/plan.rs
- datafusion/expr/src/udaf.rs
- datafusion/expr/src/udwf.rs
- datafusion/optimizer/src/optimize_projections/mod.rs
- datafusion/optimizer/src/push_down_filter.rs
- datafusion/optimizer/src/push_down_limit.rs
- datafusion/substrait/tests/cases/roundtrip_logical_plan.rs
Before the changes, `PartialOrd` could return `Some(Equal)` for two values that are not equal in `PartialEq` sense. This is violation of `PartialOrd` contract.
The fix is to consult eq inside ord implementation. If ord thinks two instances are equal, but they are not equal in Eq sense, they are considered incomparable.
- follows https://github.com/apache/datafusion/pull/17182
- follows https://github.com/apache/datafusion/pull/17393
- fixes https://github.com/apache/datafusion/issues/17064
> Fix `PartialOrd` for logical plan nodes and expressions

- datafusion/datasource-parquet/src/reader.rs
- Closes #17279.
Uses the `metadata_size_hint` when reading metadata in the `CachedParquetFileReader`, if available, so the behavior is consistent with the documentation.
- Added `metadata_size_hint` to `CachedParquetFileReader`.
N/A.
No.
> fix: Ensure the CachedParquetFileReader respects the metadata prefetch hint

- datafusion/expr-common/src/signature.rs
Just clarify numeric similar to how string is clarified
> minor: Update doc comments on type signature

- Cargo.lock
- benchmarks/Cargo.toml
- datafusion-cli/Cargo.toml
- datafusion/catalog/Cargo.toml
- datafusion/core/Cargo.toml
- datafusion/datasource-avro/Cargo.toml
- datafusion/datasource-csv/Cargo.toml
- datafusion/datasource-json/Cargo.toml
- datafusion/datasource-parquet/Cargo.toml
- datafusion/datasource/Cargo.toml
- datafusion/physical-expr-adapter/Cargo.toml
- datafusion/physical-expr/Cargo.toml
- datafusion/physical-optimizer/Cargo.toml
- datafusion/physical-plan/Cargo.toml
- datafusion/proto-common/Cargo.toml
- datafusion/pruning/Cargo.toml
- datafusion/session/Cargo.toml
- datafusion/spark/Cargo.toml
- datafusion/wasmtest/Cargo.toml
Very much a test with `cargo machete` to understand all the false positives detected by the tooling.
> Trying cargo machete to prune unused deps.

- datafusion/sql/src/expr/substring.rs
- datafusion/sql/tests/sql_integration.rs
Closes #17569 
Seems like the current message was just truncated.
Fixes a typo in an error message in `datafusion/sql/src/expr/substring.rs`, makes it more like a similar message in `datafusion/sql/src/expr/value.rs`.
yes
not meaningful ones, unless someone is matching on a very specific error message.
> Fix typo in error message in `substring.rs`

- datafusion/substrait/Cargo.toml
* Closes #17582 
* 
---
A test failure was observed when building the DataFusion Substrait integration with only the `nested_expressions` feature enabled in `datafusion/substrait/Cargo.toml`. The `UnicodeFunctionPlanner` was not registered when `unicode_expressions` was disabled, causing the `SUBSTR` / `substring` function to be unplannable during Substrait logical plan conversion. This produced the error shown in the test:
```
NotImplemented("Substring could not be planned by registered expr planner. Hint: enable the unicode_expressions")
```
This PR updates the dev-dependency for `datafusion` within `datafusion/substrait/Cargo.toml` to include the `unicode_expressions` feature so that the `simple_scalar_function_substr` test can run reliably and the Unicode function planner is available …
> datafusion/substrait: enable `unicode_expressions` in dev-dependencies to fix substring planning test

- datafusion/core/tests/physical_optimizer/filter_pushdown/mod.rs
- datafusion/physical-plan/src/joins/hash_join/exec.rs
- datafusion/physical-plan/src/joins/hash_join/shared_bounds.rs
- datafusion/physical-plan/src/joins/hash_join/stream.rs
- Closes #17541.
Refine `report_partition_bounds` Logic in `shared_bounds.rs`:
- The `partition` parameter has been renamed to left_side_partition_id to clarify that it refers to the partition from the left (build) side.
- New deduplication logic has been added: it skips reporting bounds if the current `left_side_partition_id` is identical to the previously recorded one. This directly fixes the issue in `CollectLeft` mode, where all streams report the same `left_side_partition_id` of `0`, thus preventing duplicate expressions.
Yes
No
> fix: Prevent duplicate expressions in DynamicPhysicalExpr

- datafusion/physical-plan/src/topk/mod.rs
- Closes #17597.
The original code was referencing a record batch for each line in the limit, which was causing the `arrow_select::interleave_record_batch` to allocate vectors with billions of elements. For example, if we had 32 batches and `LIMIT 50000`, those 32 batches would be referenced 50k times. The new version uses only one reference per existing batch, limiting the memory used as well as improving the execution time:
```sql
> select *
from lineitem
order by l_comment;
-- Elapsed 1.804 seconds.
-- would OOM before
> select *
from lineitem
order by l_comment
limit 50000;
-- Elapsed 0.625 seconds.
```
- Updated the way the record batches and indices are created in `topk/mod.rs`.
Yes.
No.
> fix: `SortExec` `TopK` OOM

- datafusion/core/tests/user_defined/user_defined_scalar_functions.rs
- datafusion/expr/src/expr.rs
- datafusion/expr/src/expr_fn.rs
- datafusion/expr/src/expr_schema.rs
- datafusion/sql/src/expr/identifier.rs
- datafusion/sqllogictest/test_files/joins.slt
- datafusion/sqllogictest/test_files/unnest.slt
- Closes #17422.
As reported by #17422, extension metadata was dropped in some queries involving subqueries. This happens when a column references another column in a correlated subquery, which creates an `OuterReferenceColumn` in DataFusion's logical plan.
`OuterReferenceColumn` is defined to contain a data type and a referenced column. As we know, outer reference column refers to a field in another table, so there's no way to retrieve the field metadata of referenced column given the schema of the current table. To overcome this problem, we define `OuterReferenceColumn` to contain the entire referenced field as a `FieldRef`. We also updated the implementation of `to_field` to return the referenced field, which contains the original metadata of referenced field.
Changed …
> fix: Change `OuterReferenceColumn` to contain the entire outer field to prevent metadata loss

- datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs
- Closes #17589
Improves perf
Extends the case simplification by simplifying the expr when any of the when statements are true. Previously the simplification only applied to when the first element was true.
Yes
No
> perf: Simplify CASE for any WHEN TRUE

- datafusion/sql/Cargo.toml
If trying to run tests on `datafusion-sql` alone, currently running into build errors:
```bash
datafusion$ cargo test -p datafusion-sql
Compiling datafusion-functions-nested v50.0.0 (/Users/jeffrey/Code/datafusion/datafusion/functions-nested)
error[E0308]: mismatched types
--> datafusion/functions-nested/src/planner.rs:58:18
|
58 |         if op == BinaryOperator::StringConcat {
|            --    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `BinaryOperator`, found `Operator`
|            |
|            expected because this is `BinaryOperator`
error[E0308]: mismatched types
--> datafusion/functions-nested/src/planner.rs:82:32
|
82 |         } else if matches!(op, BinaryOperator::AtArrow | BinaryOperator::ArrowAt) {
|                            --  ^^^^^^^^^^^^^^^^^^^^^^^ expected …
```
> minor: Ensure `datafusion-sql` package dependencies have `sql` flag

- datafusion/substrait/src/logical_plan/consumer/rel/join_rel.rs
- datafusion/substrait/src/logical_plan/producer/rel/join.rs
- datafusion/substrait/tests/cases/roundtrip_logical_plan.rs
- Closes #17603.
- Very small addition to the Substrait logical plan conversion, now that they have proper RIGHT_ANTI and RIGHT_SEMI join types: https://github.com/substrait-io/substrait/pull/662
- Even when not used explicitly, certain shapes of queries (WHERE `NOT EXISTS (SELECT 1 FROM ...)`) would get rewritten/optimized as left-anti joins, so this is a bit more problematic than just not supporting the conversions.
Just the necessary mapping for the consumer/producer, and the tests to validate the new join types.
(+1 for `RightSemi Join` which was also a blind spot.)
Added proper unit tests.
n/a
> feat(substrait): add support for RightAnti and RightSemi join types

- docs/source/user-guide/introduction.md
Noticed when reviewing #17668 we duplicate a lot of links in `introduction.md`; minor cleanup to remove this duplication and use the existing link definitions
> docs: deduplicate links in `introduction.md`

- Cargo.lock
- datafusion/sql/Cargo.toml
- datafusion/sql/src/unparser/dialect.rs
- datafusion/sql/src/unparser/expr.rs
Required for https://github.com/spiceai/spiceai/pull/7055
Most databases use following format for timestamps : `2025-09-15 11:00:00 +00:00`
But duckdb fails due to extra space:
* Extended `Dialect` with `timestamp_with_tz_to_string` and default implementation
* Custom `timestamp_with_tz_to_string` implementation for `DuckDBDialect`
* Tests
Manually + unit tests
No
> [unparser] Custom timestamp format for DuckDB

- datafusion/substrait/src/logical_plan/consumer/expr/literal.rs
- datafusion/substrait/src/logical_plan/producer/expr/literal.rs
- Closes #17654.
Making sure that we can have proper mapping between Substrait and Arrow types.
Adds support for `ScalarValue::Time64Microsecond` and `ScalarValue::Time64Nanosecond` to be converted to and from Substrait literals. 
This includes the `PrecisionTime` literal type and specific `TIME_64_TYPE_VARIATION_REF` for 6-digit (microseconds) and 9-digit (nanoseconds) precision.
Added unit tests
n/a
> feat(substrait): add time literal support

- datafusion/functions-nested/src/sort.rs
- datafusion/sqllogictest/test_files/array.slt
Part of #8185
Was checking through array functions and found `array_sort` doesn't handle `LargeList` arrays. Fix so it does.
Handle `LargeList` arrays in `array_sort`
Added SLT tests with LargeList as input (as well as FixedSizeList which was already supported).
No
> Support LargeList for array_sort

- datafusion/functions-nested/src/except.rs
- datafusion/sqllogictest/test_files/array.slt
Part of #8249
Was checking through array functions and found `array_except` doesn't handle `FixedSizeList` arrays. Fix so it does.
Fix signature so it allows automatic coercion from fixed size list to list
Added SLT tests
No
> Support FixedSizeList for array_except

- .github/workflows/rust.yml
- Cargo.toml
- datafusion/core/tests/macro_hygiene/mod.rs
- datafusion/expr-common/src/statistics.rs
- datafusion/ffi/src/udwf/partition_evaluator.rs
- datafusion/functions-aggregate/src/average.rs
- datafusion/functions-aggregate/src/bit_and_or_xor.rs
- datafusion/functions-aggregate/src/sum.rs
- datafusion/physical-expr/src/expressions/binary.rs
- datafusion/physical-plan/src/joins/sort_merge_join/exec.rs
- datafusion/physical-plan/src/limit.rs
- datafusion/spark/src/function/string/luhn_check.rs
- rust-toolchain.toml
- Closes https://github.com/apache/datafusion/issues/17676
- Bumps version in `rust-toolchain.toml`
- Fixes clippy errors
- Disables debug info in CI profile (`debug = false`)
N/A
N/A
> chore: Upgrade Rust version to 1.90.0

- Cargo.lock
- datafusion/wasmtest/Cargo.toml
Re-attempt of #17288
Ran `cargo update` to update dependencies and checked them in.
Pinned wasm-bindgen-test as upgrading that causes issues with wasm CI, see: #17642
> chore: update a bunch of dependencies

- datafusion/wasmtest/README.md
https://rustwasm.github.io/wasm-pack/installer/ is broken and is now available here instead: https://drager.github.io/wasm-pack/installer/
Context: [Sunsetting the rustwasm GitHub org](https://blog.rust-lang.org/inside-rust/2025/07/21/sunsetting-the-rustwasm-github-org/)
> chore: fix wasm-pack installation link in wasmtest README

- datafusion/core/src/execution/context/mod.rs
- datafusion/core/src/execution/session_state.rs
- datafusion/execution/src/task.rs
- datafusion/expr/src/registry.rs
- datafusion/proto/src/bytes/mod.rs
- datafusion/proto/src/bytes/registry.rs
- datafusion/spark/src/lib.rs
- Closes #17649.
No, this is backward compatible change
> feat: expose `udafs` and `udwfs` methods on `FunctionRegistry`

- datafusion/substrait/src/logical_plan/consumer/expr/literal.rs
- datafusion/substrait/src/logical_plan/producer/expr/literal.rs
- Closes #17685
Increasing substrait support
This adds support for substrait conversion for seconds and milliseconds. This follows a previous PR that added support for microseconds and nanoseconds.
Yes
N/A, substrait support still in development
> feat: Support Seconds and Milliseconds literals in substrait

- Cargo.toml
- datafusion/core/src/datasource/file_format/csv.rs
- datafusion/functions-nested/src/planner.rs
- datafusion/functions/src/core/named_struct.rs
- datafusion/physical-plan/src/display.rs
- datafusion/sql/src/unparser/expr.rs
- docs/source/library-user-guide/upgrading.md
Rust 1.90.0 became stable[^1], and 1.86.0 was released more than 4 months ago.
Note that for some reason https://releases.rs/docs/1.90.0/ does not list as stable, however `rustup update` definitely does pull 1.90.0
[^1]: https://blog.rust-lang.org/2025/09/18/Rust-1.90.0/
> Bump MSRV to 1.87.0

- docs/source/library-user-guide/query-optimizer.md
- Closes #17722
Clicking a link in the optimizer docs downloads the file instead of redirecting to GitHub. This seems to be only a problem for `.rs` files. `.md` files are fine. Looking at other files (example below), the approach has been to use the GitHub links instead of a relative path. I also grepped through the docs to check if there were any more relative paths to `.rs` files, and found this is the only one left.
example of how links are formatted in other files:
https://github.com/apache/datafusion/blob/a8d5016b97481d837857036ddd450574455a1b4e/docs/source/library-user-guide/functions/adding-udfs.md?plain=1#L34-L35
Use github link instead of relative link to optimizer_rule.rs. 
N/A
N/A
> docs: Fix 'Clicking a link in optimizer docs downloads the file instead of redirecting to github'

- datafusion/core/tests/dataframe/mod.rs
- datafusion/functions-aggregate/src/average.rs
- datafusion/functions-aggregate/src/lib.rs
- datafusion/functions-aggregate/src/sum.rs
- datafusion/proto/tests/cases/roundtrip_logical_plan.rs
- docs/source/user-guide/expressions.md
- Closes #2407
- Closes #2409
So we can use these distinct aggregates via DataFrames
Introduce `avg_distinct()` and `sum_distinct()` functions to be used in DataFrame API.
Added DataFrame tests, also proto roundtrip test.
New functions, updated documentation for DataFrame functions.
> Introduce `avg_distinct()` and `sum_distinct()` functions to DataFrame API

- datafusion/core/src/physical_planner.rs
- datafusion/sqllogictest/src/test_context.rs
- datafusion/sqllogictest/test_files/async_udf.slt
- Fixes https://github.com/apache/datafusion/issues/17619
Add support for using async UDFs as arguments to aggregation functions.
- Rewrite arguments to aggregation functions so that they are executed async
- Update the sqlogictest runner so it adds a `async_abs` function
- Add slt test
Yes, added slt test
Yes, async UDF can now be used in more places
> Add support for calling async UDF as aggregation expression

- datafusion/spark/src/function/map/map_from_arrays.rs
- datafusion/spark/src/function/map/mod.rs
- datafusion/spark/src/function/map/utils.rs
- datafusion/sqllogictest/test_files/spark/map/map_from_arrays.slt
part of #15914 
Migrate spark functions from https://github.com/lakehq/sail/ to datafusion engine to unify codebase
implement spark udf `map_from_arrays`
https://spark.apache.org/docs/latest/api/sql/index.html#map_from_arrays
sqllogictests added
map_from_arrays(keys_array_col, values_array_col) now can be called in queries
> feat(spark): implement Spark `map` function `map_from_arrays`

- datafusion/physical-plan/src/joins/utils.rs
The goal of this PR is to allow cardinality statistics being passed through joins even if fields don't have max and min values set, as long as a distinct value estimate is provided.
Currently we require max and min to be set, as they might be used to estimate the distinct count. This is unnecessarily conservative if distinct_count has actually been provided, in which case max and min won't be used at all and the presence of max or min has no influence over how good of an estimate it is.
> Support join cardinality estimation less conservatively

- datafusion/core/benches/sql_planner.rs
- datafusion/physical-plan/src/windows/mod.rs
- datafusion/sqllogictest/test_files/window.slt
- Closes #17401.
There is a complexity issue with window ordering calculations. Rather than computing all possibilities and eliminating the failing ones, we incrementally refine the ordering, keeping only elements that satisfy requirements.
related content: https://github.com/apache/datafusion/pull/14813, https://github.com/apache/datafusion/issues/17401, https://github.com/apache/datafusion/pull/17563
This PR implements the algorithm mentioned in the issue. There is also one minor change: the `sort_options_resolving_constant` function now generates candidates according to the intended usage. This enables a minor optimization possibility.
> Prevent exponential planning time for Window functions - v2

- Cargo.toml
- benchmarks/README.md
- benchmarks/bench.sh
- benchmarks/compile_profile.py
- Closes #.
It's common to see developers complain that DataFusion takes too long to compile or that the generated binary size is too large.
This benchmark makes it easier to experiment with ways to speed up compilation and reduce binary size.
The `compile_profile` benchmark does:
1. Compile the benchmark runner, and also compiles its `datafusion` dependency, and measures the compilation time.
2. Run the `tpch` benchmark, measure the binary execution speed
3. Measure the size of the binaries from compilation.
```
Summary
Profile             Compile         Run        Size
---------------------------------------------------
dev                  67.30s      10.17s     213.3MB
release             476.18s       0.87s      53.6MB
ci                   64.85s       6.89s     172.4MB …
```
> dev: Add benchmark for compilation profiles

- Cargo.toml
- Part of https://github.com/apache/datafusion/issues/17594
I am trying to get a clean CI run on the `branch-50` branch but some CI is failing with "out of diskspace" errors
https://github.com/apache/datafusion/actions/runs/18017424338/job/51322145417?pr=17778
> rustc-LLVM ERROR: IO failure on output stream: No space left on device
> error: could not compile `datafusion-functions-nested` (lib test)
@rkrishn7  fixed this on main as part of https://github.com/apache/datafusion/pull/17677 (thanks to @Jefffrey  for helping me find this https://github.com/apache/datafusion/pull/17778#issuecomment-3338605948) but the fix isn't in the branch-50 branch yet
Backport the part of https://github.com/apache/datafusion/pull/17677 that reduces disk usage for tests
By CI 
No this is an internal …
> [branch-50] Backport change to avoid debug symbols in ci builds to 50.0.0

- datafusion/core/benches/sql_planner.rs
- datafusion/physical-plan/src/windows/mod.rs
- datafusion/sqllogictest/test_files/window.slt
- Part of https://github.com/apache/datafusion/issues/17594
- Related to https://github.com/apache/datafusion/issues/17401
- Backport of https://github.com/apache/datafusion/pull/17684
The fix for https://github.com/apache/datafusion/issues/17594 was requested for inclusion in DataFusion 50.1.0. 
- Backport https://github.com/apache/datafusion/pull/17684 to the `branch-50` branch
Yes new tests
No
> [branch-50] Backport Prevent exponential planning time for Window functions - v2 #17684 

- benchmarks/src/imdb/run.rs
- benchmarks/src/tpch/run.rs
- datafusion-examples/examples/composed_extension_codec.rs
- datafusion/ffi/src/plan_properties.rs
- datafusion/ffi/src/udaf/accumulator_args.rs
- datafusion/ffi/src/udwf/partition_evaluator_args.rs
- datafusion/proto/src/bytes/mod.rs
- datafusion/proto/src/lib.rs
- datafusion/proto/src/physical_plan/from_proto.rs
- datafusion/proto/src/physical_plan/mod.rs
- datafusion/proto/tests/cases/roundtrip_physical_plan.rs
- docs/source/library-user-guide/upgrading.md
- Closes #17596 .
As described in #17596  replacing `SessionContext` with `TaskContext` and aligning `PhysicalExtensionCodec::try_decode` with other interface changes. 
more details at ballista pr https://github.com/apache/datafusion-ballista/pull/1320/
- changed public good few interfaces in `datafusion_proto::physical_plan` replacing `SessionContext` with `TaskContext`
- removed `runtime: &RuntimeEnv,` from arguments as `RuntimeEnv` can be retrieved from `TaskContext` 
current tests
yes, interface in good few public methods changed
Note: if we agree that change make sense I'll refactor methods which have TaskContext and RuntimeEnv such as:
```rust
fn try_into_projection_physical_plan(
&self,
projection: &protobuf::ProjectionExecNode,
ctx: &TaskContext,
runtime: &RuntimeEnv, …
```
> feat: change `datafusion-proto` to use `TaskContext` rather than`SessionContext` for physical plan serialization

- datafusion/wasmtest/README.md
Whilst debugging #17642 I realized how much of a pain it is to try get it running locally on my Mac; including some instructions and a reference link to hopefully save anyone else the same pain later.
(I didn't research too much into this so if there's more details that could be added I'll be happy to add, I just tried to get the bare minimum down)
> docs: update wasmtest README with instructions for Apple silicon

- datafusion/core/src/physical_planner.rs
Backport: Fix potential overflow when we print verbose physical plan 
https://github.com/apache/datafusion/pull/17798
Backport: Fix potential overflow when we print verbose physical plan 
https://github.com/apache/datafusion/pull/17798
> [Backport] Fix potential overflow when we print verbose physical plan 

- datafusion/functions-aggregate/src/approx_percentile_cont.rs
- datafusion/functions-aggregate/src/approx_percentile_cont_with_weight.rs
- datafusion/sqllogictest/test_files/aggregate.slt
- Closes #4259
#4259 was actually resolved by #11721, however I noticed this same fix wasn't applied on `approx_percentile_cont_with_weight`. Fixing it for this function too.
When updating batches in the `ApproxPercentileWithWeightAccumulator`, filter out null values in both arrays (taking care to filter out corresponding value in other array if partner value is null). Also add a debug assert in `ApproxPercentileAccumulator::convert_to_float` to ensure we don't accidentally pass in arrays with nulls again.
Also fix some visibility modifiers on `ApproxPercentileAccumulator` methods.
Added SLT tests.
API change technically as changing some methods in `ApproxPercentileAccumulator` from `pub` to `pub(crate)`; I don't think these were meant to be `pub` in the first place based on the comments. …
> fix: Filter out nulls properly in approx_percentile_cont_with_weight

- datafusion/core/benches/sql_planner.rs
- part of https://github.com/apache/datafusion/issues/17801
I am trying to run some benchmarks with @pepijnve  on
https://github.com/apache/datafusion/pull/17419 but the benchmark queries are
now failing.
In order to unblock testing, I would like to disable the panic'ing query in the benchmark code until we fix the underlying issue.
Skip the failing test
I tested this manually that the previously failing code
```shell
cargo bench --profile dev --bench sql_planner -- physical_plan_tpcds_all
```
Now runs to completion
No, this is a benchmarking change only
> Temporarily disable failing `sql_planner` benchmark query

- .github/dependabot.yml
- docs/.gitignore
- docs/Makefile
- docs/README.md
- docs/build.sh
- docs/make.bat
- docs/requirements.txt
- docs/rustdoc_trim.py
- docs/source/conf.py
- Pin pip packages and introduce dependabot config to auto-bump them for us - I believe there's been an overall strategy to try pin our dependencies to specific versions to mitigate supply chain risks, so this is following suit
- Update docs README a bit, add `uv` instruction to make it easier to build
- Remove need for `temp` dir as we now run the `rustdocs_trim` as part of the Sphinx process as an extension itself, and also remove the `sed` for relative links as there are no relative links anymore
- Reference extensions documentation for Sphinx: https://www.sphinx-doc.org/en/master/extdev/index.html#dev-extensions
> minor: simplify docs build process & pin pip package versions

- docs/source/user-guide/introduction.md
Noticed https://github.com/apache/datafusion/pull/17825 and also added vortex! Also, deleted some project that I believe are not currently actively maintained
> Cleanup user guide known users section

- docs/source/user-guide/explain-usage.md
> Fix the doc about row_groups pruning metrics in explain_usage.md

- .github/actions/setup-macos-aarch64-builder/action.yaml
- .github/workflows/audit.yml
- .github/workflows/rust.yml
- datafusion/common/src/scalar/mod.rs
- datafusion/core/src/datasource/listing/table.rs
- datafusion/core/tests/physical_optimizer/filter_pushdown/mod.rs
- datafusion/physical-expr/src/expressions/case.rs
- docs/source/user-guide/introduction.md
- typos.toml
Fix typos causing failures on CI on main, also go through our actions and make sure we pin to hash instead of version (and add comments for versions where missing)
> chore: fix typos & pin action hashes

- datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs
- Closes https://github.com/apache/datafusion/issues/17590
- Closes https://github.com/apache/datafusion/issues/1693
- Closes https://github.com/apache/datafusion/pull/17628
Extends the case simplification by simplifying the expr when any of the when statements are false. 
Implements the following simplifications:
```sql
CASE WHEN false THEN A END --> NULL
CASE WHEN false THEN A ELSE B END --> B
CASE WHEN X THEN A WHEN false THEN B END --> CASE WHEN X THEN A ELSE B END
```
Yes
No
> perf: Optimize CASE for any WHEN false

- datafusion/physical-expr/src/expressions/cast_column.rs
- datafusion/physical-expr/src/expressions/mod.rs
* Closes #17760 
The planner sometimes needs to rewrite the physical representation of a resolved column to a new schema/field while preserving nested-structure semantics. The existing `CastExpr` doesn't carry the input/target field metadata required to perform struct-aware casts (correct nested field ordering, nullability, and null-padding for missing children). Adding a dedicated `CastColumnExpr` lets the execution layer call into `datafusion_common::nested_struct::cast_column` and guarantees casts behave correctly for both array and scalar values.
This change is focused on execution-time casting semantics (schema-aware casts) and does not attempt to modify planner/optimizer behaviour.
* Add new physical expression implementation: …
> Add `CastColumnExpr` for struct-aware column casting

- datafusion/core/src/execution/context/mod.rs
- datafusion/expr-common/src/signature.rs
- datafusion/expr/src/logical_plan/ddl.rs
- Closes #.
Internlly at InfluxData, we are evaluating using `CREATE FUNCTION` but when I was providing links to the docs, it was a little sparse and unclear what was supported. 
I think some documentation would make this functionality a little easier to find and use.
Add some documentation and links
By CI and I rendered them locally:
I also added `Debug` and `Clone` to `RegisterFunction` for consistency
> docs: Improve documentation for FunctionFactory / CREATE FUNCTION

- datafusion/physical-optimizer/src/limit_pushdown_past_window.rs
- datafusion/sqllogictest/test_files/window.slt
- Closes https://github.com/apache/datafusion/issues/17894
As SPM after Sort is almost always occurring (for larger / multiple files/partitions), it currently limits the usefulness of the rule.
As an aside, it would be worth looking at if this rule could be implemented in logical plan. (e.g. in `PushDownLimit`).
> Make limit pushdown work for SortPreservingMergeExec

- .github/actions/setup-macos-aarch64-builder/action.yaml
- .github/workflows/audit.yml
- .github/workflows/rust.yml
- datafusion/common/src/scalar/mod.rs
- datafusion/core/src/datasource/listing/table.rs
- datafusion/core/tests/physical_optimizer/filter_pushdown/mod.rs
- datafusion/physical-expr/src/expressions/case.rs
- docs/source/user-guide/introduction.md
- typos.toml
- Related to https://github.com/apache/datafusion/issues/17849
- Backports https://github.com/apache/datafusion/pull/17855
Make CI happy on branch-50
Fixing typos and pinning GH action dependencies to commit hashes.
CI itself.
No
> [branch-50] Backport: fix typos & pin action hashes (#17855)

- datafusion/datasource-parquet/src/source.rs
- Closes #.
`with_predicate()` is a builder pattern API to overwrite `predicate` field for `ParquetSource`. Now it's also resetting the metrics, this step should be unnecessary.
This change was introduced by a giant refactor https://github.com/apache/datafusion/pull/14224, so likely this is done by mistake, instead of some certain reasons.
Existing test has covered metrics.
Since now this `with_predicate()` is called before constructing metrics set, so it's not introducing any bug, and no test case needs to be changed.
> fix: `ParquetSource` - `with_predicate()` don't have to reset metrics

- datafusion/common/src/dfschema.rs
- Closes #.
Related https://github.com/apache/datafusion/issues/17466
Rename `print_schema_tree` to `tree_string` to better reflect the method purpose. The method returns a tree string, and doesn't print anything
Yes
> chore: rename Schema `print_schema_tree` to `tree_string`

- datafusion/expr/src/async_udf.rs
Clearing a TODO item I noticed, since we're now MSRV of 1.87.0:
https://github.com/apache/datafusion/blob/3ee52f85fdb94544da04f6a67f0c7fc03c714843/Cargo.toml#L78-L79
Utilize `dyn_eq` and `dyn_hash` via trait upcasting. There is a slight change in behaviour given the pointers inside the Arcs aren't being compared anymore, see comment.
> chore: utilize trait upcasting for AsyncScalarUDF PartialEq & Hash

- datafusion/optimizer/src/scalar_subquery_to_join.rs
- datafusion/sqllogictest/test_files/window.slt
- Closes #17770 
The optimizer fails on this query:
```
WITH suppliers AS (
SELECT *
FROM (VALUES (1, 10.0), (1, 20.0)) AS t(nation, acctbal)
)
SELECT
ROW_NUMBER() OVER (PARTITION BY nation ORDER BY acctbal DESC) AS rn
FROM suppliers AS s
WHERE acctbal > (
SELECT AVG(acctbal) FROM suppliers
);
```
https://github.com/apache/datafusion/issues/17770#issuecomment-3358276321:
`scalar_subquery_to_join` rewrites the input schema fed to the window function, creating an invalid plan.
In `ScalarSubqueryToJoin`, add a projection on top of the filter after converting the subquery to a join, similar to `EliminateGroupByConstant`: 
https://github.com/apache/datafusion/blob/10a437b826568c27b81d7d16a02b938a13d1a4ad/datafusion/optimizer/src/eliminate_group_by_constant.rs#L26-L30
Yes, using the existing …
> fix: optimizer `common_sub_expression_eliminate` fails in a window function

- datafusion/common/src/dfschema.rs
- datafusion/core/src/physical_planner.rs
- datafusion/core/tests/sql/select.rs
- datafusion/expr-common/src/type_coercion/binary/tests/arithmetic.rs
- datafusion/expr/src/conditional_expressions.rs
- datafusion/physical-expr/src/expressions/cast.rs
- datafusion/physical-expr/src/expressions/in_list.rs
- datafusion/physical-plan/src/windows/bounded_window_agg_exec.rs
- part of https://github.com/apache/datafusion/pull/17888
I am working on the arrow 57 upgrade and I found I had to update the output of many tests. I broke some of the changes out into their own PR so they are easier to review
1. Update `assert_eq` to `assert_snapshot` in a few places 
2. Misc other updates I will call out inline
Yes by CI
No these are test only changes
> Update tests to use insta / make them easier to update

- datafusion/core/tests/physical_optimizer/test_utils.rs
N/A
While working on an upgrade, I noticed the same schema was created by many distinct tests (and I am about to do it again). 
- https://github.com/apache/datafusion/pull/17888
Since the schema is always the same and is wrapped in an `Arc` we can just clone the Arc
Use a `static LazyLock` to create the schema once and just pass out a reference to it
Yes by CI
No this is a test change only
> Minor Test refactor: avoid creating the same SchemaRef

- datafusion/expr/src/logical_plan/plan.rs
- Closes #17912.
`Window::try_new_with_schema` is missing doc string with unclear error message.
- Add docs `Window::try_new_with_schema`.
- Descriptive error message for invalid output schema.
No. I think this is a just a small docs change.
No.
> docs: `Window::try_new_with_schema` with a descriptive error message

- datafusion/common/src/stats.rs
Use saturating operations, if the operation saturates, `Exact` is changed to `Inexact`
Note this is not consistent with `Precision::<ScalarValue>` that wraps, happy to change behavior to wrapping here too if considered more relevant (but for cardinality estimations, saturation seems to make more sense to me).
- Close #17928.
Avoid panics on large number of joins in debug mode that explode estimated cardinalities.
> Precision::<usize>::{add, sub, multiply}: avoid overflows
