apache/datafusion

ballista/ui/scheduler/README.md

I've add guide for running dashboard UI in ballista project.
Please review 🙏 
Add guide in README

Add install guide in README

---

datafusion/src/sql/planner.rs
datafusion/tests/sql.rs
docs/user-guide/src/sql/select.md

Closes #250
Fix behavior and a simple implementation of select distinct.
An implementation of select distinct.
A working select distinct

Implement select distinct

---

README.md

docs - fix the ballista link

---

datafusion/src/sql/planner.rs

Closes #300
Currently we ignore OVER clauses, giving incorrect results (using normal aggregates).
```
select 1, SUM(x) OVER (PARTITION by x) from (select 1 as x union all select 2 as x) t;
+----------+--------+
| Int64(1) | SUM(x) |
+----------+--------+
| 1        | 3      |
+----------+--------+
```
Return an error.
Return error on not supported over clause.

Return error on OVER clause

---

README.md

Closes #105, #84
Add project links (Squirtle and Tensorbase) to list in `README.md`
Add project links (Squirtle and Tensorbase) to list in `README.md`
No

Add projects (Squirtle and Tensorbase) to list in readme

---

datafusion/src/optimizer/filter_push_down.rs

Closes #408
This PR ensures that filter expressions already present on the table scan part of a logical plan are not re-added if the plan is run through the optimiser again.

fix: don't duplicate existing filters

---

README.md

update readme to reflect work on window functions

---

.github/workflows/dev_pr.yml

Port https://github.com/apache/arrow-rs/pull/468 by @Dandandan  to DataFusion repo
(I will be testing this on my own fork)

Fix PR labeler

---

README.md
ballista/rust/core/src/serde/logical_plan/from_proto.rs
ballista/rust/core/src/serde/logical_plan/to_proto.rs
datafusion/src/logical_plan/builder.rs
datafusion/src/logical_plan/plan.rs
datafusion/src/physical_plan/windows.rs

Related https://github.com/apache/arrow-rs/pull/489
Closes #.
update stale documentations related to window functions so that we don't have wrong messages
cleaned up some of the legacy comments

update stale documentations related to window functions

---

ballista/rust/core/src/execution_plans/query_stage.rs

Addressing https://github.com/apache/arrow-datafusion/pull/543#discussion_r659184184
cc @andygrove

Remove unnecessary mutex

---

benchmarks/queries/q15.sql

Add query 15 to TPC-H queries

---

datafusion/src/sql/planner.rs
datafusion/tests/sql.rs

Add support for leading field in interval

---

python/.gitignore
python/Cargo.toml
python/src/dataframe.rs
python/tests/generic.py
python/tests/test_sql.py
python/tests/test_udaf.py

fix python crate with the changes to logical plan builder
follow up on #593 
Closes #.

fix python crate with the changes to logical plan builder

---

datafusion/tests/sql.rs

Fixes test due to logical merge conflict between https://github.com/apache/arrow-datafusion/pull/605 and https://github.com/apache/arrow-datafusion/pull/660

Fix test output due to logical merge conflict

---

DEVELOPERS.md

The directory in testing setup chapter is out of date. This pull request fix these typos.
N/A
Document change.
N/A

Fix typo in DEVELOPERS.md

---

integration-tests/sqls/self_join_with_alias.sql
integration-tests/sqls/simple_union_all.sql
integration-tests/test_psql_parity.py

add more integration tests

---

ballista/rust/core/src/execution_plans/shuffle_writer.rs
ballista/rust/executor/src/main.rs

Closes #713 .
Simple bug fix. Wrong variable was being used for partition number.
No

Ballista: Shuffle write bug fix

---

datafusion/src/physical_plan/parquet.rs

provide more details on required .parquet file extension
Closes #.
provide more details on required .parquet file extension

provide more details on required .parquet file extension error message

---

datafusion/src/logical_plan/plan.rs
datafusion/src/physical_plan/explain.rs

impl `fmt::Display` for PlanType
Closes #.
fmt::Display is more idiomatic

impl fmt::Display for PlanType

---

python/pyproject.toml

fix maturin version in pyproject.toml
Closes #.
otherwise in future versions it'll be an error

fix maturin version in pyproject.toml

---

.github/workflows/dev_pr/labeler.yml

We need good PR labels to help with changelog automation.
Automatically add python label to PRs. Also adjust label detection logic for datafusion and ballista.
no

automatically add python label to PRs

---

.github/workflows/dev_pr/labeler.yml

Automatically add sql, development-process and documentation labels to PR for changelog automation.
Automatically add sql, development-process and documentation labels to PR.
no

automatically add sql, development-process and documentation labels to PRs

---

dev/docker/ballista.dockerfile

Closes #828.
- Fixes docker build and the integration tests.\
- Minor re-ordering of lines in Docker file for consistency (put crates in alphabetical order)
Adds ballista-examples crate to docker image.
No

Add ballista-examples to docker build

---

ballista/rust/core/src/serde/physical_plan/to_proto.rs

Closes #832.
Implement serde for min/max

Implement serde for MIN and MAX

---

ballista/rust/client/src/lib.rs
ballista/rust/core/src/lib.rs
ballista/rust/executor/src/lib.rs
ballista/rust/scheduler/src/lib.rs

Closes #830.
Adds crate documentation that will appear in crates.io when the crates are published.
Documentation.
No.

Add minimal crate documentation for Ballista crates

---

ballista/rust/client/Cargo.toml
ballista/rust/core/Cargo.toml
ballista/rust/executor/Cargo.toml
ballista/rust/scheduler/Cargo.toml

Closes #851.
We need this so we can release.
Add version number to dependencies.
No

Add version to ballista dependencies

---

benchmarks/src/bin/tpch.rs

Closes #854 .
Make parquet files compatible with Apache Spark and other JVM-based systems so we can run the same benchmarks.

Change tpch keys from UInt64 to Int64

---

datafusion/src/physical_plan/expressions/binary.rs
datafusion/src/physical_plan/expressions/coercion.rs
datafusion/tests/sql.rs

Closes #815
support like operation on DictionaryArray

support like on DictionaryArray

---

datafusion/src/lib.rs

This a simple typo fix :)
Nope !
I was taking a look at the lib and reading through the docs. The project looks awesome ! And the detailed docs on the internal behavior are really good, thank you so much for this.

Typo fix in DataFusion crate documentation

---

dev/docker/ballista-base.dockerfile
dev/docker/ballista.dockerfile
docs/user-guide/src/distributed/docker-compose.md

Closes https://github.com/apache/arrow-datafusion/issues/918
We want the tests to work
- Change some versions from 0.5.0-SNAPSHOT to 0.6.0
- Upgrade Rust from 1.53 to 1.54
- Pin cargo chef version
No

Fix integration tests

---

python/README.md

Closes #.
The link to DataFusion in [python/readme](https://github.com/apache/arrow-datafusion/blob/master/python/README.md) is outdated after we migrating the repo.
Document update.
No.

fix deadlink in python/readme

---

README.md

Closes #1021
Just a quick fix for a broken link
README.md only.
No.

Fix broken README.md link to cli.md

---

docs/source/cli/index.rst

update docs to newest version to include ballista options
Closes #.

nit: update docs to newest version

---

datafusion/src/execution/context.rs
datafusion/src/sql/planner.rs
datafusion/tests/user_defined_plan.rs

Support querying CSV files without providing the schema

---

datafusion-cli/Dockerfile

see [related](https://github.com/rust-lang/docker-rust/issues/77). need to upgrade base image 
Closes #.

fix docker for cli because of base image upgrade

---

datafusion-cli/src/context.rs
datafusion-cli/src/exec.rs
datafusion-cli/src/lib.rs
datafusion-cli/src/main.rs
datafusion-cli/src/print_options.rs

refactor datafusion cli to be more modular

---

datafusion/src/physical_plan/repartition.rs

Closes #614.
Tests were failing on nightly
Avoid comparision to exact batch as hashes might change
No

Failing test in RepartitionExec on nightly

---

datafusion-cli/src/command.rs
datafusion-cli/src/exec.rs

Closes #1230
add list table command
```
> \d
+---------------+--------------------+------------+------------+
| table_catalog | table_schema       | table_name | table_type |
+---------------+--------------------+------------+------------+
| datafusion    | information_schema | tables     | VIEW       |
| datafusion    | information_schema | columns    | VIEW       |
+---------------+--------------------+------------+------------+
```

datafusion-cli to add list table command

---

datafusion-cli/src/exec.rs

datafusion cli to handle EoF and interrupt signal

---

datafusion/src/avro_to_arrow/arrow_array_reader.rs

Closes #1205
Avro reader performance is quite bad.
Avoids cloning avro data values.
No

Improve avro reader performance by avoiding some cloning on avro_rs::Value

---

datafusion/src/physical_plan/expressions/coercion.rs

Closes #.
numerical_coercion pattern match optimize so that we have less boilerplate

numerical_coercion pattern match optimize

---

dev/docker/ballista-base.dockerfile

Closes https://github.com/apache/arrow-datafusion/issues/1272.
Fix integration tests.
Update Rust version to 1.56
No

Update Rust version in Ballista integration test

---

datafusion/src/execution/context.rs

Closes https://github.com/apache/arrow-datafusion/issues/1262
```
expected:
[
"+---------------------+--------------+",
"| week                | SUM(test.c2) |",
"+---------------------+--------------+",
"| 2020-12-07 00:00:00 | 24           |",
"| 2020-12-14 00:00:00 | 156          |",
"+---------------------+--------------+",
]
actual:
[
"+---------------------+--------------+",
"| week                | SUM(test.c2) |",
"+---------------------+--------------+",
"| 2020-12-07 00:00:00 | 40           |",
"| 2020-12-14 00:00:00 | 140          |",
"+---------------------+--------------+",
]
```

Fix test group_by_date_trunc failed locally

---

datafusion/tests/sql.rs

Continued work on #743 task 2.

WIP: Fourth batch of updating sql tests to use assert_batches_eq

---

datafusion/src/catalog/information_schema.rs
datafusion/src/catalog/schema.rs
datafusion/src/execution/context.rs

[datafusion-1269]: forbid creating the table with the same name

---

.asf.yaml

fixes #591
Closes #591.
To add Github topics the the repo.
See also 
https://cwiki.apache.org/confluence/display/INFRA/Git+-+.asf.yaml+features#Git.asf.yamlfeatures-Repositorymetadata

Add topics to Github repo

---

README.md

Closes #.
update https://github.com/datafusion-contrib/datafusion-java link

Update README.md to refresh datafusion-java link

---

ballista-examples/Cargo.toml
ballista/rust/core/Cargo.toml
ballista/rust/executor/Cargo.toml
datafusion-cli/Cargo.toml
datafusion-examples/Cargo.toml
datafusion/Cargo.toml

The arrow-rs 6.2.0 has released, upgrade the arrow-rs version to `6.2.0`

upgrade arrow-rs to 6.2.0

---

datafusion/src/datasource/file_format/json.rs
datafusion/src/optimizer/common_subexpr_eliminate.rs
datafusion/src/physical_plan/crypto_expressions.rs
datafusion/src/physical_plan/planner.rs
datafusion/src/physical_plan/string_expressions.rs
datafusion/src/scalar.rs
datafusion/src/sql/planner.rs
datafusion/src/test_util.rs

Closes #.
fix some clippy warnings from nightly channel

fix some clippy warnings from nightly channel

---

datafusion-cli/src/command.rs

Closes #.
Datafusion cli quiet mode command to contain option bool, to allow printing current value
- allow printing current value
- allow different switch flags

Datafusion cli quiet mode command to contain option bool

---

docs/source/user-guide/cli.md
docs/source/user-guide/sql/ddl.md

Add the document for `DDL` sql and CLI command.

add documentation to Datafusion cli's new commands

---

datafusion/src/physical_plan/hash_aggregate.rs

remove unused code in hash_aggregate

---

datafusion/src/datasource/file_format/parquet.rs

n/a
Small cleanup. Also avoids a bit of work within `infer_schema`.

Split fetch_metadata into fetch_statistics and fetch_schema

---

datafusion/src/physical_plan/aggregates.rs
datafusion/src/physical_plan/functions.rs
datafusion/src/physical_plan/type_coercion.rs
datafusion/src/physical_plan/udaf.rs
datafusion/src/physical_plan/udf.rs
datafusion/src/physical_plan/window_functions.rs

Before refactor the coercion framework, I take a look some  cal `result_type` or `create_xx_phy_expr`, and find some parameters has no meaningful. It's very easy to make mistakes.
related #1356
related #1358

Change the arg names and make parameters more meaningful

---

datafusion/src/physical_plan/expressions/array_agg.rs

The array agg doesn't implement the trait function `name`.

add array agg name

---

ballista/rust/core/Cargo.toml
ballista/rust/executor/Cargo.toml
datafusion-cli/Cargo.toml
datafusion-examples/Cargo.toml
datafusion/Cargo.toml

upgrade the arrow-rs version

---

datafusion/src/sql/planner.rs

Closes #1380 .
Be consistent with pg
Change real datatype to map to f32 instead of f64

Be consistent with pg on real datatype

---

datafusion/src/sql/planner.rs
datafusion/tests/sql.rs

fix: Select * returns an unexpected result

---

datafusion/src/logical_plan/builder.rs

This PR contains some minor style cleanups that I noticed while reviewing https://github.com/apache/arrow-datafusion/pull/1415 from @viirya.
As that PR had already had a lot of discussion, I figured I would just propose the cleanups directly as a follow on PR rather than hold up merging #1415

Minor Code cleanups

---

ballista/rust/core/Cargo.toml
datafusion/Cargo.toml

use 0.13 sql parser

---

ballista/rust/core/Cargo.toml
ballista/rust/executor/Cargo.toml
datafusion-cli/Cargo.toml
datafusion-examples/Cargo.toml
datafusion/Cargo.toml
datafusion/src/physical_plan/expressions/binary.rs

Update arrow-rs to 6.4.0 and replace boolean comparison in datafusion with arrow compute kernel

---

docs/source/specification/roadmap.md

Thanks to the work of @rdettai @xudong963  and others, we are making great progress here
Also added https://github.com/apache/arrow-datafusion/issues/122 as @liukun4515  is actively working on it
cc @hntd187

Update roadmap with features completed

---

ballista/rust/core/src/serde/mod.rs
datafusion/src/logical_plan/operators.rs

enhancement mod/rem operation for expr

---

.github/dependabot.yml

Closes #1472 
ref: https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/

add dependbot

---

README.md

Add note about support for VAR / STDDEV added by @realno  in https://github.com/apache/arrow-datafusion/pull/1525 ❤️

Update docs to note support for VARIANCE and STDDEV

---

Cargo.toml
README.md

update reference to python and update readme

---

benchmarks/README.md

minor: improve the benchmark readme

---

datafusion/Cargo.toml
datafusion/src/physical_plan/crypto_expressions.rs

Closes #1630 #1629 #1628 
https://docs.rs/blake2/latest/blake2/index.html

update md-5, sha2, blake2

---

datafusion/src/logical_plan/expr.rs
datafusion/src/optimizer/simplify_expressions.rs
datafusion/src/optimizer/utils.rs

refine match pattern related code

---

ballista/rust/core/Cargo.toml
ballista/rust/executor/Cargo.toml
datafusion-cli/Cargo.toml
datafusion-examples/Cargo.toml
datafusion/Cargo.toml

N/A
Update to latest arrow, getting among other things, improvements for decimal type, and parquet utf8 validation and performance improvements
Update to arrow 8.0.0
Changelog here https://github.com/apache/arrow-rs/blob/8.0.0/CHANGELOG.md for full details
New arrow dependency

Update to arrow 8.0.0

---

datafusion/Cargo.toml
datafusion/fuzz-utils/Cargo.toml
datafusion/fuzz-utils/src/lib.rs
datafusion/src/execution/memory_manager.rs
datafusion/src/execution/mod.rs
datafusion/src/physical_plan/sorts/sort.rs
datafusion/tests/merge_fuzz.rs
datafusion/tests/order_spill_fuzz.rs

Closes #1573.
Fuzz Test for various corner cases sorting RecordBatches exceeds available memory and should spill.
1. new `order_spill_fuzz` test
2. extract common methods from `merge_fuzz` into dev crate `fuzz-utils` to DRY.
No.
cc @alamb

Fuzz test for spillable sort

---

datafusion/src/physical_plan/aggregates.rs

Add upper bound for public function `signature`

---

datafusion/src/physical_plan/tdigest/mod.rs

minor: fix `cargo run --release` error

---

.github/workflows/rust.yml

add `cargo check --release` to ci

---

datafusion-common/Cargo.toml
datafusion-common/README.md
datafusion-common/src/error.rs
datafusion-common/src/lib.rs
datafusion/Cargo.toml
datafusion/src/pyarrow.rs

- Closes #1752
- Part of #1750

[split/1] split datafusion-common module

---

ballista/rust/client/Cargo.toml
ballista/rust/client/README.md
ballista/rust/core/Cargo.toml
ballista/rust/executor/Cargo.toml
ballista/rust/scheduler/Cargo.toml
datafusion-cli/Cargo.toml
datafusion/Cargo.toml

Re https://github.com/apache/arrow-datafusion/issues/1587

Update datafusion versions

---

datafusion-common/Cargo.toml
datafusion-expr/Cargo.toml
datafusion/Cargo.toml

Update versions for split crates

---

ballista/rust/core/README.md

Just a minor fix for README for the ballista.

update README for ballista

---

datafusion/CHANGELOG.md

re #1587 get the last few updates prior to creating a release candidate

Final CHANGELOG touchups for 7.0.0

---

datafusion-cli/README.md
docs/source/user-guide/cli.md

follow up of https://github.com/apache/arrow-datafusion/pull/1816
After this https://github.com/apache/arrow-datafusion/pull/1816, we should build/compile the datafusion-cli with features of ballista.

Add doc for building `datafusion-cli` when connect the ballista

---

datafusion-cli/Cargo.toml
datafusion-cli/src/main.rs

Update datafusion-cli allocator

---

datafusion-cli/Cargo.toml
datafusion-common/Cargo.toml
datafusion-expr/Cargo.toml
datafusion-jit/Cargo.toml
datafusion-physical-expr/Cargo.toml

re #1750 
The description of sub crates is copy/pasted from DataFusion and not very specific
Change crate descriptions to be more specific
just descriptions

Update crate descriptions

---

DEVELOPERS.md

Hey @HaoYang670 I have added rustup update stable in in the Bootstrap environment part, because we always use the latest stable version of Rust to test this project.
Please review this. If any changes needed inform me i will do that.
Thanks!
#1894 
closes #1894

Fixed : Rust version requirement is not mentioned in the developer's guide.

---

datafusion/src/catalog/schema.rs

Enhance MemorySchemaProvider to support `register_listing_table`

---

datafusion-common/Cargo.toml
datafusion-jit/Cargo.toml
datafusion-jit/src/jit.rs

Closes #1950 #1949 #1948 #1947

update jit-related dependencies

---

README.md

NA
Add new https://github.com/datafusion-contrib/datafusion-bigtable repo to README

Update README: link to datafusion-bigtable repo

---

datafusion/src/logical_plan/expr_visitor.rs

N/A very small change and CONTRIBUTING.md lead me to believe it was not needed. If indeed an issue is required I'm happen to open one.
Simple typo in documentation that presents itself in the docs
single line change of docs
No

Address typo in ExprVisitable trait documentation

---

datafusion-proto/src/from_proto.rs

~Draft until https://github.com/apache/arrow-datafusion/pull/1914 is merged~
Add reference to https://github.com/apache/arrow-datafusion/issues/1977 to code introduced in https://github.com/apache/arrow-datafusion/pull/1914

Add ticket reference to clippy allow

---

datafusion-expr/src/window_function.rs

Fixing a typo in documentation of window_function.
Closes #.

Fixing a typo in documentation

---

datafusion/src/lib.rs

Closes #. https://github.com/apache/arrow-datafusion/issues/1813
To make sure the examples in `https://arrow.apache.org/datafusion/user-guide/example-usage.html` always work irrespective of API updates. 
- Including a doc test for files in `arrow-datafusion/docs/source/user-guide/example-usage.md`
No
No

Automatically test examples in user guide

---

datafusion-cli/src/helper.rs
datafusion/src/execution/context.rs
datafusion/src/sql/parser.rs
datafusion/src/sql/planner.rs

This is a follow-up pr.
Closes #1986.
@Jimexist

return VecDeque for DFParser::parse_sql

---

docs/source/user-guide/sql/datafusion-functions.md
docs/source/user-guide/sql/sql_status.md

After implement the #1974 , add the doc for user😊
Closes #.

Add doc for EXTRACT, date_part

---

README.md

Substitute HDFS objectstore plugin

---

CONTRIBUTING.md
ballista-examples/README.md
ballista-examples/src/bin/ballista-dataframe.rs
ballista-examples/src/bin/ballista-sql.rs
datafusion-examples/examples/avro_sql.rs
datafusion-examples/examples/dataframe.rs
datafusion-examples/examples/flight_client.rs
datafusion-examples/examples/flight_server.rs
datafusion-examples/examples/parquet_sql.rs
datafusion-examples/examples/parquet_sql_multiple_files.rs
docs/source/user-guide/distributed/clients/rust.md

Simplify prerequisites for running examples

---

ballista/rust/client/README.md
docs/source/user-guide/distributed/deployment/cargo-install.md

Closes #1809.
To make sure the ballista install examples in `docs/source/user-guide/distributed/deployment/cargo-install.md` and `ballista/rust/client/README.md` always work irrespective of crate updates
No.
No.

Revise document of installing ballista pinned to specified version

---

datafusion/src/sql/planner.rs

Closes #2036.
Change the code location and add annotation
None

Change the code location and add annotation

---

datafusion/src/optimizer/simplify_expressions.rs

minor: remove repeated test

---

dev/docker/ballista-base.dockerfile

update zlib version to 1.2.12

---

datafusion/physical-expr/src/expressions/case.rs

N/A
Some features have been added to arrow-rs that mean we no longer have to have this code in datafusion. I noticed this while working on https://github.com/apache/arrow-datafusion/pull/2118
use `eq_dyn` rather than re-creating part of it in DataFusion
No

minor: replace array_equals in case evaluation with eq_dyn from arrow-rs

---

dev/release/README.md

part of https://github.com/apache/arrow-datafusion/issues/2095

doc: update release schedule

---

datafusion-cli/src/context.rs
datafusion-cli/src/main.rs

closes https://github.com/apache/arrow-datafusion/issues/1984

[CLI] Add show tables for datafusion-cli

---

datafusion/core/src/sql/planner.rs

Closes #.
I found it during add namedExpr.
I think match twice is unnecessary for `prepare_select_exprs` and make complexity.
simplify `prepare_select_exprs`

refactor: simplify `prepare_select_exprs`

---

datafusion/core/src/physical_plan/windows/window_agg_exec.rs

Part of https://github.com/apache/arrow-datafusion/issues/2201.
See ticket
This removes the tokio::spawn from WindowAggExec. I opted to just remove the spawn, instead of making it conditional on being run in a tokio runtime, as I'm not actually sure why it does this? I guess it might allow for parallelism with respect to parent operators, but it seems a little unusual for an operator to make this distinction?
WindowAggExec can be used outside a tokio runtime

Remove tokio::spawn from WindowAggExec (#2201)

---

datafusion/core/src/physical_plan/empty.rs
datafusion/core/src/physical_plan/explain.rs
datafusion/core/src/physical_plan/filter.rs
datafusion/core/src/physical_plan/limit.rs
datafusion/core/src/physical_plan/projection.rs
datafusion/core/src/physical_plan/repartition.rs
datafusion/core/src/physical_plan/sorts/sort.rs
datafusion/core/src/physical_plan/sorts/sort_preserving_merge.rs
datafusion/core/src/physical_plan/union.rs

chore: add `debug!` log in some execution operators

---

.editorconfig

Closes #.
It's inspired in https://github.com/apache/arrow-datafusion/pull/2200#discussion_r849651184
add editor config file
None

minor: add editor config file

---

datafusion/common/Cargo.toml
datafusion/jit/Cargo.toml

Closes #2303.
Closes #2302.
Closes #2301.
Closes #2300.

chore: update cranelift to 0.83.0

---

datafusion/common/src/scalar.rs

Closes #.
Careless idents exist in Some macro code of `scalar.rs`
Beautify this code with neat idents.
No.

MINOR: beautify code with neat idents

---

README.md

Closes #.
Recently  [`datafusion-objectstore-azure`](https://github.com/datafusion-contrib/datafusion-objectstore-azure) has been added to the datafusion-contrib org. It would be nice to create awareness in the community by adding it to the README here.

Reference `datafusion-objectstore-azure` in README

---

datafusion/core/src/sql/planner.rs

N/A
This is a follow-up to the recently merged subquery expression support and fixes a bug where a schema was being extended rather than merged (which handles duplicate columns correctly). Without this fix, the test added in this PR will fail with a "Schema contains duplicate qualified field name" error due to both the subquery input and the outer query containing fields from the table "person".
Merge schemas.
No

minor: fix duplicate column bug in subquery support

---

datafusion/core/src/physical_plan/planner.rs

Closes #.
I find some unused code, they are redundant.

minor: remove redundant code

---

datafusion/core/src/sql/planner.rs
datafusion/core/src/sql/utils.rs

N/A
Before this change, we get error messages like `Projection references non-aggregate values` without any context, which are not super helpful.
With this change, we get:
```
Projection references non-aggregate values: Expression #person.first_name could not be resolved from available columns: #MAX(person.age)
```
Improve error messages and update tests.
Yes, better error messages.

MINOR: Improve error messages for GROUP BY / HAVING queries

---

datafusion/core/src/execution/context.rs
datafusion/core/src/sql/planner.rs
datafusion/core/tests/sql/errors.rs
datafusion/core/tests/sql/information_schema.rs

Table provider error propagation

---

.github/workflows/rust.yml
CONTRIBUTING.md
ci/scripts/rust_clippy.sh
ci/scripts/rust_fmt.sh
ci/scripts/rust_toml_fmt.sh
dev/format-code.sh
dev/rust_lint.sh

Closes #https://github.com/apache/arrow-datafusion/issues/2321
No.

Issue 2321: Add code formatting instructions to CONTRIBUTING

---

data-access/src/object_store/mod.rs
datafusion/core/src/execution/context.rs

Fix `read_from_registered_table_with_glob_path` fails if path contains // #2465

---

dev/release/README.md
dev/release/update_change_log-all.sh
dev/release/update_change_log-ballista.sh
dev/release/update_change_log-datafusion.sh

could help #2392 
`dev/release/update_change_log-all.sh` is updated to respect release branch, else it always compare difference from latest master
was used in https://github.com/apache/arrow-datafusion/pull/2187

MINOR: Parameterize changelog script

---

benchmarks/src/bin/tpch.rs
datafusion/physical-expr/src/expressions/datetime.rs

N/A
Make it easier for contributors to run the queries that currently fail, with a link to the issue.
Add ignored tests with links to issues, which have also been updated with the latest failures (mostly subquery related).
Also improved one error message.
No

MINOR: Add ignored tests for all remaining benchmark queries

---

dev/release/README.md
dev/release/verify-release-candidate.sh

N/A
Verification script needs updating because crate locations have changed
Change a path in the verification script
Add more docs to the release process
No

MINOR: Update verification script and add notes on signing keys

---

datafusion-cli/README.md

None
v7.0.0 -> v8.0.0, because we already have released v8.0.0
None

Update datafusion-cli readme cli version

---

dev/build-arrow-ballista.sh

https://github.com/apache/arrow-ballista/pull/40 has been merged

Unpin Ballista following FileFormat Breaking Change

---

.github/workflows/dev_pr/labeler.yml

Closes #2617 .
Update GitHub label workflow.
None
None

minor: Update GitHub label workflow.

---

.github/workflows/rust.yml
datafusion/core/tests/order_spill_fuzz.rs
datafusion/core/tests/sql/explain_analyze.rs
datafusion/core/tests/sql/json.rs

chore: try fix CI coverage

---

.github/workflows/dev_pr/labeler.yml

N/A
The `datafusion` label is redundant now that the repo only contains DataFusion
Remove some labeler rules
No

MINOR: remove `datafusion` and `python` labeler rules

---

docs/README.md
docs/requirements.txt

N/A
Running `make html` was failing with:
```
ImportError: cannot import name 'environmentfilter' from 'jinja2' (/home/andy/miniconda3/lib/python3.9/site-packages/jinja2/__init__.py)
```
Specify to use Jinja < 3.1
No

MINOR: Fix docs build

---

benchmarks/tpch-gen.sh
dev/build-set-env.sh

fix(script): fix tpch data script

---

datafusion/core/src/physical_plan/hash_join.rs

N/A
If I get an error telling me a data type is not supported then I would like to know which data type it was
Improve error message to include data type name
Nice errors

MINOR: Improve unsupported data type error message

---

datafusion-cli/Cargo.lock
datafusion/core/src/physical_plan/hash_join.rs

Closes https://github.com/apache/arrow-datafusion/issues/2744
I want to perform a join on date32/64 types
Support date32/64 in hash join
No

Support dates in hash join

---

datafusion/common/Cargo.toml
datafusion/jit/Cargo.toml

Closes #2760 #2761 #2762 #2763
-- Clean the redundant tickets :(

minor: update cranelift related dependencies

---

datafusion/optimizer/src/filter_null_join_keys.rs

Closes https://github.com/apache/arrow-datafusion/issues/2780
Simplify optimization rule and have it apply in more cases
Filter out null join keys where the join key is nullable
No

Simplify FilterNullJoinKeys rule

---

docs/source/python/index.rst

add csv registration and sql query to examples

---

datafusion/optimizer/src/simplify_expressions.rs

MINOR: make name meaningful and clean up code

---

datafusion/core/src/dataframe.rs

Closes #2844.
Add with_column method to allow end user to add columns to dataframe dynamically
Yes, new dataframe with_column function added

Adding dataframe with_column function

---

CONTRIBUTING.md

Closes #2880
updated the error link in CONTRIBUTING.md

fix(doc): update test directory link in CONTRIBUTING.md

---

datafusion/core/tests/sql/functions.rs
datafusion/expr/src/built_in_function.rs

Closes https://github.com/apache/arrow-datafusion/issues/2926
Support h2o benchmark
Add `pow` as synonym for `power`
No

Add pow as synonym for power

---

datafusion/common/src/scalar.rs

I accidentally added this statement in https://github.com/apache/arrow-datafusion/pull/2891 🤦

Minor: Remove left over debugging statement

---

datafusion/common/Cargo.toml
datafusion/jit/Cargo.toml

Closes #2951  #2952  #2953 #2954

chore: update jit-related dependencies

---

datafusion/core/tests/sql/projection.rs

I made a typo in #3003 . this is to fix it

fix typo for PR3003

---

README.md

Great talk, thanks @alamb @Dandandan

doc: add a new video link about datafusion

---

datafusion/core/src/physical_optimizer/pruning.rs
datafusion/core/tests/parquet_pruning.rs

I noticed a few possible documentation improvements while working on a pruning bug

Minor: improve some docstrings about pruning

---

README.md

Add CeresDB to list of products using DataFusion

MINOR: Add CeresDB to list of products using DataFusion

---

datafusion/core/src/dataframe.rs
datafusion/core/src/logical_plan/mod.rs
datafusion/core/src/prelude.rs
datafusion/core/tests/dataframe_functions.rs
datafusion/expr/src/expr_fn.rs

Closes #2870 
This is my first contribution :) picked an issue looked simple but hopefully there isn't more to it and I am not missing something. Tried to write unit tests where I saw appropriate. Most of the logic is already tested under `Expr::cast` and this change exposes a dataframe function for it. Should I also add an integration test?

Add cast function for creating cast expression

---

datafusion-cli/Cargo.lock

update cargo lock

---

datafusion/core/tests/sql/timestamp.rs

Closes #3082 
this is solved while arrow-rs is upgraded to v20. this pr is to add test cases

add test case for cast_timestamp_before_1970

---

datafusion/physical-expr/src/expressions/datetime.rs

Closes https://github.com/apache/arrow-datafusion/issues/3172#issue-1339706487

Rename do_data_time_math() to do_date_time_math()

---

datafusion/core/tests/sql/aggregates.rs
datafusion/expr/src/aggregate_function.rs
datafusion/physical-expr/src/aggregate/min_max.rs

Closes #3166 .
add min and max for time

add min/max for time

---

datafusion/optimizer/src/eliminate_filter.rs

re https://github.com/apache/arrow-datafusion/pull/3175 
I accidentally merged https://github.com/apache/arrow-datafusion/pull/3175 ever though there was a clippy error 🤦 
Fix clippy errors
No

Fix clippy

---

datafusion/core/src/physical_plan/planner.rs
datafusion/expr/src/logical_plan/plan.rs
datafusion/expr/src/utils.rs
datafusion/proto/src/logical_plan.rs
datafusion/sql/src/planner.rs

Closes https://github.com/apache/arrow-datafusion/issues/3207
Support Dask SQL queries that use this syntax
No

Add SQL query planner support for `DISTRIBUTE BY`

---

README.md

[minor] add Coverage Status in readme

---

docs/source/user-guide/library.md
docs/source/user-guide/sql/data_types.md
docs/source/user-guide/sql/information_schema.md
docs/source/user-guide/sql/sql_status.md

Closes #.
Just a few small changes, trying to keep them small for easy review.
* updated the SQL data types docs to match what's in the code
* moved Rust Version and extensibility sections from SQL status to Library Usage page
* minor updates to other pages

MINOR: documentation updates

---

datafusion/common/Cargo.toml
datafusion/jit/Cargo.toml

Closes #3230 #3231 #3232 #3233 .

chore: update cranelifts to 0.87.0

---

dev/release/README.md

N/A
We need to remove old releases when publishing a new release
Docs
No

MINOR: Add notes on deleting old releases and release candidates from svn

---

datafusion/core/tests/sql/timestamp.rs

Related to https://github.com/apache/arrow-datafusion/issues/3321 but this just ignores the test for now
Fix the build
Ignore test

Fix build: Ignore failing test

---

datafusion/core/tests/sql/explain_analyze.rs

add SQL level test for the https://github.com/apache/arrow-datafusion/pull/3270

add explain sql test for optimizer rule PreCastLitInComparisonExpressions

---

datafusion/physical-expr/src/expressions/in_list.rs

None. This is a follow-up work of #3324. (Thank you @alamb  https://github.com/apache/arrow-datafusion/pull/3324#discussion_r962143914)
Instead of collecting to vector and then converting to `HashSet`, we can collect to `HashSet` directly.

Collect to `HashSet` directly in `in_list`

---

datafusion-examples/examples/README.md

Closes #.
None
add tips in README of example
None

Minor: add hint in README of example

---

datafusion/core/src/prelude.rs

Let prelude import all expression functions

---

datafusion/optimizer/src/eliminate_limit.rs

Closes #.
review in [#3374 ](https://github.com/apache/arrow-datafusion/pull/3374#issuecomment-1239508562)
remove redundant code
None

minor: remove redundant code.

---

datafusion/optimizer/src/filter_null_join_keys.rs
datafusion/optimizer/src/single_distinct_to_groupby.rs
datafusion/optimizer/src/type_coercion.rs

Closes #.
Consistency in naming. Noticed most rules are snake case style in the output, but these were pascal case. Changed to snake case as well.

MINOR: update optimizer rule names to be consistent style as the rest

---

datafusion/core/src/physical_plan/planner.rs
datafusion/optimizer/src/type_coercion.rs
datafusion/physical-expr/src/expressions/in_list.rs
datafusion/physical-expr/src/planner.rs

inlist: move type coercion to logical phase

---

datafusion/physical-expr/src/expressions/in_list.rs

[minor] Remove unused arg in macro in Inlist

---

datafusion/core/src/physical_plan/file_format/row_filter.rs

Use the column data type as the NULL data type in the row filter

---

datafusion/proto/src/from_proto.rs
datafusion/proto/src/lib.rs

Add BitwiseXor in function from_proto_binary_op

---

dev/release/README.md

N/A
Update based on releasing 12.0.0

MINIOR: Update release instructions

---

datafusion/core/src/physical_plan/file_format/file_stream.rs
datafusion/core/src/physical_plan/file_format/mod.rs

Make FileStream and FileOpener public

---

datafusion/sql/src/table_reference.rs

N/A
This would have made some debugging much easier in Dask SQL
Impl `Debug` for some structs
No

MINOR: Impl `Debug` for TableReference and ResolvedTableReference

---

benchmarks/src/bin/tpch.rs

Closes #.
With @DhamoPS's fix for q19 performance now in main, enable it in the benchmark and fix the schema for result validation (it passes).

MINOR: enable q19 in TPCH

---

README.md

N/A
Add Dask SQL to list of projects powered by DataFusion
No

MINOR: Add Dask SQL to list of projects powered by DataFusion

---

datafusion-cli/Cargo.lock
datafusion-cli/Cargo.toml
datafusion-cli/Dockerfile
datafusion-cli/README.md
datafusion-cli/src/exec.rs
datafusion-cli/src/main.rs

Closes #.
update datafusion cli deps

update datafusion cli deps

---

datafusion/core/src/physical_plan/file_format/delimited_stream.rs
datafusion/core/src/physical_plan/hash_join.rs

[CI] Fix the newly added linting errors to make clippy happy

---

benchmarks/src/bin/tpch.rs
datafusion-examples/examples/dataframe_in_memory.rs
datafusion-examples/examples/simple_udf.rs
datafusion/core/src/dataframe.rs
datafusion/core/src/execution/context.rs
datafusion/core/tests/dataframe.rs
datafusion/core/tests/dataframe_functions.rs
datafusion/core/tests/sql/aggregates.rs
datafusion/core/tests/sql/expr.rs
datafusion/core/tests/sql/functions.rs
datafusion/core/tests/sql/group_by.rs
datafusion/core/tests/sql/idenfifers.rs
datafusion/core/tests/sql/joins.rs
datafusion/core/tests/sql/math.rs
datafusion/core/tests/sql/mod.rs
datafusion/core/tests/sql/predicates.rs
datafusion/core/tests/sql/references.rs
datafusion/core/tests/sql/select.rs
datafusion/core/tests/sql/timestamp.rs
datafusion/core/tests/sql/udf.rs
datafusion/core/tests/sql/unicode.rs
datafusion/core/tests/user_defined_aggregates.rs

Closes #3426
1. add `SessionContext::register_batch` to register a single `RecordBatch` as a table
2. add `SessionContext::read_batch` to read a `DataFrame` from a single `RecordBatch`
3. replace some code with `register_batch` in test/example

add `register_batch` and `read_batch` to `SessionContext` to register a single RecordBatch as a table

---

datafusion/core/src/execution/context.rs
datafusion/core/src/physical_plan/aggregates/mod.rs

N/A
I started making some minor changes I noticed while reviewing https://github.com/apache/arrow-datafusion/pull/3600 (see  https://github.com/apache/arrow-datafusion/pull/3600#discussion_r979231669) 
Improve docstrings, fix some links
Better API docs

MINOR: improve docstrings on SessionContext

---

datafusion/core/src/datasource/object_store.rs

Closes #.
Adds some documentation, r.e. https://github.com/apache/arrow-datafusion/pull/3595

Document ObjectStoreProvider

---

datafusion/expr/src/logical_plan/builder.rs

Check each query has same number of columns when building the UNION plan

---

datafusion/optimizer/src/simplify_expressions.rs

Closes #3626.
Please look at the issue.
Add 2 simplification rules and tests

Simplify multiplication by `0` and by `null` 

---

datafusion/expr/src/expr.rs

Closes N/A
Some of the optimizer rules are using `Expr::name` inappropriately.
- Improve docs for `Expr::name`
- Add new `Expr::canonical_name`
No

MINOR: Add `Expr::canonical_name` and improve docs on `Expr::name`

---

datafusion/sql/src/planner.rs

Closes #3716.
Adds support for processing the column aliases already parsed by sqlparser-rs during SQL planning stage.
Normally we already had some relevant logic processing these entries for relations, now it is in a separate function where both the CTE planner and the relation planner can use.
This is a fix/feture.

Support column aliases specified by `WITH` statements

---

datafusion/core/src/dataframe.rs

Closes #3733 
Changes: do not use col(), which tries to parse strings as identifiers (e.g. splits on .)
One fewer bug

Fix DataFrame::select_columns to handle column names with a period

---

docs/source/user-guide/sql/explain.md
docs/source/user-guide/sql/index.rst

Closes #3755 
`EXPLAIN` is supported in datafusion. But it's not described in user guide.
Add explain section to SQL reference.
No

User Guide: Add `EXPLAIN` to SQL reference

---

datafusion/core/src/physical_plan/planner.rs
datafusion/expr/src/expr.rs
datafusion/expr/src/expr_rewriter.rs
datafusion/expr/src/expr_schema.rs
datafusion/expr/src/expr_visitor.rs
datafusion/expr/src/lib.rs
datafusion/optimizer/src/type_coercion.rs
datafusion/physical-expr/src/planner.rs
datafusion/proto/src/from_proto.rs
datafusion/proto/src/lib.rs
datafusion/proto/src/to_proto.rs
datafusion/row/src/writer.rs
datafusion/sql/src/planner.rs
datafusion/sql/src/utils.rs

Part of #2175
Refactor `Expr::Like`, `Expr::ILike`, `Expr::SimilarTo` to use a struct

Refactor `Expr::Like`, `Expr::ILike`, `Expr::SimilarTo` to use a struct

---

benchmarks/src/bin/tpch.rs
datafusion-examples/examples/expr_api.rs
datafusion/core/src/physical_optimizer/pruning.rs
datafusion/core/src/physical_plan/planner.rs
datafusion/core/tests/provider_filter_pushdown.rs
datafusion/expr/src/expr.rs
datafusion/expr/src/expr_fn.rs
datafusion/expr/src/expr_rewriter.rs
datafusion/expr/src/expr_schema.rs
datafusion/expr/src/expr_visitor.rs
datafusion/expr/src/logical_plan/plan.rs
datafusion/jit/src/ast.rs
datafusion/optimizer/src/filter_push_down.rs
datafusion/optimizer/src/reduce_cross_join.rs
datafusion/optimizer/src/reduce_outer_join.rs
datafusion/optimizer/src/rewrite_disjunctive_predicate.rs
datafusion/optimizer/src/scalar_subquery_to_join.rs
datafusion/optimizer/src/simplify_expressions.rs
datafusion/optimizer/src/type_coercion.rs
datafusion/optimizer/src/unwrap_cast_in_comparison.rs
datafusion/optimizer/src/utils.rs
datafusion/physical-expr/src/planner.rs
datafusion/proto/src/from_proto.rs
datafusion/proto/src/lib.rs
datafusion/proto/src/to_proto.rs
datafusion/sql/src/planner.rs
datafusion/sql/src/utils.rs

Part of #2175 and #3807
This PR applies this for Expr::BinaryExpr.

Refactor Expr::BinaryExpr to use a struct

---

.github/workflows/rust.yml

N/A
When this test fails, it may not be obvious how to fix it (for example https://github.com/apache/arrow-datafusion/pull/3855#issuecomment-1280675236)
Add a comment to help anyone who hits the error in the future
No
cc @isidentical

[MINOR] Add a hint about how to resolve the `Cargo.lock` CI check

---

dev/release/README.md

Closes https://github.com/apache/arrow-datafusion/issues/3812
Help automate board reports
Docs

MINOR: Add notes on Apache Reporter

---

docs/source/user-guide/sql/ddl.md

Closes #3211.
Better documentation means better user experience
`CREATE VIEW` ddl explanation
Documents

add create view explanation

---

datafusion/common/Cargo.toml
datafusion/jit/Cargo.toml

Closes #3917 #3918 #3919 #3920

chore: update cranelift-related dependencies

---

datafusion/core/src/physical_plan/hash_join.rs
datafusion/expr/src/expr_rewriter.rs

Closes #.
find typo when read code.
typo fix
None

minor: fix some typo.

---

docs/source/user-guide/sql/ddl.md

Closes #3904.
fix doc about `CREATE TABLE IF NOT EXISTS`

doc: fix doc about `CREATE TABLE IF NOT EXISTS`

---

datafusion/core/tests/sql/predicates.rs

Add (ignored) test for https://github.com/apache/arrow-datafusion/issues/3936

Add test for querying predicate on dictionary

---

benchmarks/README.md

Closes #.
Fix benchmarks README formatting

Fix benchmarks README formatting

---

.github/pull_request_template.md
datafusion/expr/src/logical_plan/display.rs
datafusion/expr/src/logical_plan/plan.rs

Closes #.
minor: remove redundant prefix.

minor: remove redundant prefix.

---

datafusion/proto/Cargo.toml

Closes #.
Should avoid confusing issues where people get different generated output

Pin datafusion-proto build dependencies

---

datafusion/core/src/dataframe.rs
datafusion/core/src/physical_plan/joins/hash_join.rs
datafusion/core/src/test/exec.rs

Closes #.
Something I noticed while trolling the code

minor: remove redundant code/TODO

---

docs/source/contributor-guide/communication.md
docs/source/contributor-guide/index.md

Closes https://github.com/apache/arrow-datafusion/issues/3957
Document how we should handle PRs
Add Pull Request guidelines to contributor guide
docs

Add Pull Request guidelines to contributor guide

---

datafusion/physical-expr/src/expressions/cast.rs

Follow on to https://github.com/apache/arrow-datafusion/pull/3969, leave a note to help us remember to clean up when upstream change is merged

Minor: Add TODO and tracking ticket reference

---

datafusion/core/tests/sql/aggregates.rs
datafusion/core/tests/sql/predicates.rs
datafusion/optimizer/tests/integration-test.rs
datafusion/sql/src/planner.rs

Closes #3891.
``` sql
❯ select count(*);
+-----------------+
| COUNT(UInt8(1)) |
+-----------------+
| 1               |
+-----------------+
❯ select count(1);
+-----------------+
| COUNT(UInt8(1)) |
+-----------------+
| 1               |
+-----------------+
❯ select count(2);
+-----------------+
| COUNT(UInt8(1)) |
+-----------------+
| 1               |
+-----------------+
❯ select count(2.2);
+-----------------+
| COUNT(UInt8(1)) |
+-----------------+
| 1               |
+-----------------+
```
```sql
❯ select count(*), count(1), count(2), count(2.2);
+-----------------+-----------------+-----------------+---------------------+
| COUNT(UInt8(1)) | COUNT(Int64(1)) | COUNT(Int64(2)) | COUNT(Float64(2.2)) | …
```

Reserve the literal expression of `Count` function

---

docs/source/user-guide/cli.md

[MINOR] Update `SET` in cli.md 

---

.github/pull_request_template.md

Closes #4113.
Make it explicit that all PRs should have tests, and force developers to at least ponder why they don't have one.
A change to the PR template.
They will be reminded that testing is required.

Template change

---

datafusion/core/tests/sql/cast.rs
datafusion/expr/src/utils.rs
datafusion/sql/src/planner.rs

Preserve the `Cast` expression in `columnize_expr`

---

datafusion/core/src/physical_plan/file_format/parquet.rs

Closes #.
Was a temporary workaround that is no longer necessary

Remove BoxedAsyncFileReader

---

datafusion/core/src/physical_plan/file_format/parquet/row_groups.rs

Remove an outdated comment noticed by @Ted-Jiang https://github.com/apache/arrow-datafusion/pull/4160#discussion_r1018604494

Minor: Remove completed comment on parquet row group pruning

---

datafusion/optimizer/src/inline_table_scan.rs
datafusion/optimizer/src/optimizer.rs
datafusion/optimizer/src/projection_push_down.rs
datafusion/optimizer/src/reduce_outer_join.rs
datafusion/optimizer/src/simplify_expressions/simplify_exprs.rs
datafusion/optimizer/src/single_distinct_to_groupby.rs
datafusion/proto/src/lib.rs

Closes #.
remove redundant println

minor: remove redundant println and cleanup

---

datafusion/core/tests/dataframe_functions.rs
datafusion/physical-expr/src/regex_expressions.rs

Closes #1429.
Improve error messaging as per what PostgreSQL does
Added unit test

Improve error message for regexp_match 'g' flag

---

datafusion-cli/Cargo.lock
datafusion/core/Cargo.toml
datafusion/optimizer/Cargo.toml
datafusion/physical-expr/Cargo.toml

upgrade required chrono version to 0.4.23

---

datafusion/optimizer/src/eliminate_filter.rs
datafusion/optimizer/src/filter_push_down.rs
datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs
datafusion/optimizer/src/simplify_expressions/simplify_exprs.rs
datafusion/optimizer/src/simplify_expressions/utils.rs

remove duplicate or redundant code

---

benchmarks/src/bin/tpch.rs
datafusion-examples/examples/parquet_sql_multiple_files.rs
datafusion/core/src/datasource/listing/table.rs
datafusion/core/src/datasource/listing_table_factory.rs
datafusion/core/src/execution/options.rs
datafusion/core/tests/path_partition.rs
datafusion/core/tests/sql/parquet.rs

Follow up PR for https://github.com/apache/arrow-datafusion/issues/4178

Use defaults for ListingOptions builder

---

datafusion/optimizer/src/optimizer.rs

Closes #.
In the previous code, we did not verify whether the schema is equal, which may cause some problems.
We can add a checkrt to confirm optimizer can keep plan schema immutable. 
It's found when I try wo add a new rule.
add a checker to confirm optimizer can keep plan schema immutable.

add a checker to confirm optimizer can keep plan schema immutable.

---

datafusion/expr/src/columnar_value.rs
datafusion/expr/src/lib.rs
datafusion/physical-expr/src/scalar_function.rs

Remove the type alias `NullColumnarValue`

---

datafusion/sql/src/planner.rs

Closes #.
* avoid a clone into string when checking ambiguous
* improve the test case.

minor: avoid a clone into string when checking ambiguous

---

datafusion/optimizer/tests/integration-test.rs
datafusion/sql/src/planner.rs

Closes #4210 
add ambiguous check for projection

 add ambiguous check for projection

---

datafusion/core/src/physical_optimizer/coalesce_batches.rs
datafusion/core/src/physical_optimizer/enforcement.rs
datafusion/core/src/physical_plan/joins/sort_merge_join.rs
datafusion/core/src/physical_plan/joins/utils.rs
datafusion/core/src/physical_plan/rewrite.rs
datafusion/physical-expr/src/expressions/case.rs
datafusion/physical-expr/src/rewrite.rs
datafusion/physical-expr/src/utils.rs

re https://github.com/apache/arrow-datafusion/issues/4139
Allow error propagation in physical optimizers

Refine Err propagation and avoid unwrap in transform closures

---

datafusion/sql/src/planner.rs

re https://github.com/apache/arrow-datafusion/pull/4305#discussion_r1028973434
Suggested by @mingmwang  in https://github.com/apache/arrow-datafusion/pull/4305#discussion_r1028973434
Fix typos in test names
yes
no

minor: fix typos in test names

---

datafusion/sql/src/planner.rs

re #4260 
refine the code of build schema for ambiguous check, factor this out into a function

refine the code of build schema for ambiguous check, factor this out into a function

---

datafusion/optimizer/src/limit_push_down.rs

enhancement: when fetch == 0, pushdown limit 0 instead skip+fetch.

---

datafusion/optimizer/src/eliminate_cross_join.rs
datafusion/optimizer/src/limit_push_down.rs
datafusion/optimizer/src/optimizer.rs
datafusion/optimizer/src/rewrite_disjunctive_predicate.rs
datafusion/row/src/lib.rs

1. forgot to modify the name in #4185 🥹
2. other typo
Closes #.

minor: correct name and typo

---

datafusion/core/src/physical_plan/filter.rs

Closes #4374.
Just like `num_rows`, we now estimate the byte size for the output of a `FilterExec` operation.
Estimation of total byte size through filter predictivity.
Tests are included
No

Include byte size estimates in the filter statistics

---

datafusion/core/src/physical_plan/common.rs
datafusion/core/src/physical_plan/joins/sort_merge_join.rs
datafusion/core/src/physical_plan/windows/window_agg_exec.rs

[minor] use arrow kernel concat_batches instead combine_batches

---

datafusion-examples/examples/dataframe.rs

Not related to pr but to improve document
Closes #.
Did not proposed any change just added example
change in the dataframe example file
Current implementation does not have any test to run
No
No Breaking change in public API.

Adding more dataframe example to read csv files

---

datafusion/physical-expr/src/expressions/binary.rs
datafusion/physical-expr/src/expressions/binary/kernels_arrow.rs

replace the comparator for `decimal array op scalar` using arrow  kernel

---

.github/workflows/dev_pr/labeler.yml

Add sqllogictest auto labeler

---

datafusion/proto/src/from_proto.rs
datafusion/proto/src/lib.rs

Closes #4480.
Help support window function in ballista.

Add window func related logic plan to proto ability.

---

datafusion/physical-expr/src/expressions/mod.rs
datafusion/physical-expr/src/window/aggregate.rs
datafusion/physical-expr/src/window/built_in.rs
datafusion/physical-expr/src/window/lead_lag.rs
datafusion/physical-expr/src/window/nth_value.rs
datafusion/physical-expr/src/window/rank.rs

Closes #4479 .
Enable window func in ballista.

Make window function related struct public for ballista.

---

datafusion/core/src/physical_plan/aggregates/hash.rs
datafusion/expr/src/accumulator.rs

N/A
While working on https://github.com/apache/arrow-datafusion/pull/4488 I had to remind myself of this information several times, so I added comments (largely selfishly for my future self)
Update docstrings
N/A
Docs only

Minor: Update docstrings and comments to aggregate code

---

datafusion-examples/examples/custom_datasource.rs
datafusion/core/src/dataframe.rs
datafusion/optimizer/src/simplify_expressions/simplify_exprs.rs

minor: remove redundant `unwrap()`

---

datafusion/optimizer/src/eliminate_cross_join.rs

When i review #4443, I find it's redundant.

refactor: remove redundant `build_join_schema()`

---

datafusion/core/tests/sqllogictests/test_files/dates.slt
datafusion/core/tests/sqllogictests/test_files/timestamps.slt

~Draft as it builds on https://github.com/apache/arrow-datafusion/pull/4568~
Closes https://github.com/apache/arrow-datafusion/issues/3944
Closes https://github.com/apache/arrow-datafusion/issues/3408
Add teset coverage  https://github.com/apache/arrow-datafusion/issues/3944
New tests
Yes!
No

Minor: Add tests for date interval predicate handling

---

datafusion/core/tests/sql/select.rs
datafusion/core/tests/sqllogictests/src/main.rs
datafusion/core/tests/sqllogictests/test_files/select.slt

re https://github.com/apache/arrow-datafusion/issues/4495

Move subset of select tests to sqllogic

---

datafusion/core/src/physical_plan/windows/mod.rs
datafusion/expr/src/window_function.rs
datafusion/proto/src/to_proto.rs
datafusion/sql/Cargo.toml
datafusion/sql/src/planner.rs

Closes #4552 .
Please refer to the issue.
1. Adds a new variants in `WindowFunction` enum to represent UDAF as window function;
2. Finds the UDAF by its name from context provider;
3. Executes it just like other aggregate functions (see test `window_function_with_udaf()`)
Yes
No

feat: user-defined aggregate function(UDAF) as window function

---

Cargo.toml
benchmarks/Cargo.toml
datafusion-cli/Cargo.lock
datafusion-cli/Cargo.toml
datafusion-examples/Cargo.toml
datafusion/common/Cargo.toml
datafusion/core/Cargo.toml
datafusion/core/src/physical_plan/limit.rs
datafusion/expr/Cargo.toml
datafusion/jit/Cargo.toml
datafusion/optimizer/Cargo.toml
datafusion/physical-expr/Cargo.toml
datafusion/physical-expr/src/expressions/nullif.rs
datafusion/proto/Cargo.toml
datafusion/row/Cargo.toml
datafusion/sql/Cargo.toml
parquet-test-utils/Cargo.toml
test-utils/Cargo.toml

Update to arrow v29

---

datafusion/sql/src/planner.rs

N/A
just when correlated subquery need outer_query_schema.
correlated subquery can't exist FROM clause.
So, we can remove redundant `outer_query_schema `

refactor: remove redundant `outer_query_schema`

---

datafusion/sql/src/parser.rs

Fix the bugs in parsing `COMPRESSION TYPE`

---

datafusion/optimizer/src/type_coercion.rs

Closes #.
when I do #4599, I find all UT in this file use `optimize()`, so I refactor them.

refactor: extract `assert_optimized_plan_eq` from UT.

---

datafusion/core/src/dataframe.rs
datafusion/core/src/physical_plan/mod.rs

Closes #.
Following #2434 there is no reason for these to be async

Make execute_stream functions sync

---

datafusion/core/src/physical_optimizer/pruning.rs
datafusion/core/src/physical_plan/planner.rs
datafusion/expr/src/expr.rs
datafusion/expr/src/expr_fn.rs
datafusion/expr/src/expr_rewriter.rs
datafusion/expr/src/expr_schema.rs
datafusion/expr/src/expr_visitor.rs
datafusion/expr/src/lib.rs
datafusion/expr/src/logical_plan/builder.rs
datafusion/expr/src/utils.rs
datafusion/optimizer/src/eliminate_outer_join.rs
datafusion/optimizer/src/unwrap_cast_in_comparison.rs
datafusion/physical-expr/src/planner.rs
datafusion/proto/src/from_proto.rs
datafusion/sql/src/planner.rs
datafusion/sql/src/utils.rs

Part of https://github.com/apache/arrow-datafusion/issues/2175 and https://github.com/apache/arrow-datafusion/issues/3807
Refactor Expr::TryCast to use a struct.

Refactor Expr::TryCast to use a struct

---

datafusion/core/src/dataframe.rs
datafusion/expr/src/logical_plan/builder.rs
datafusion/expr/src/utils.rs
datafusion/optimizer/src/common_subexpr_eliminate.rs
datafusion/optimizer/src/decorrelate_where_exists.rs
datafusion/optimizer/src/decorrelate_where_in.rs
datafusion/optimizer/src/eliminate_cross_join.rs
datafusion/optimizer/src/eliminate_limit.rs
datafusion/optimizer/src/eliminate_outer_join.rs
datafusion/optimizer/src/filter_null_join_keys.rs
datafusion/optimizer/src/propagate_empty_relation.rs
datafusion/optimizer/src/push_down_filter.rs
datafusion/optimizer/src/push_down_limit.rs
datafusion/optimizer/src/push_down_projection.rs
datafusion/optimizer/src/scalar_subquery_to_join.rs
datafusion/proto/src/logical_plan.rs
datafusion/sql/src/planner.rs

 Make LogicalPlanBuilder consuming (#4622) 

---

datafusion/core/Cargo.toml
datafusion/core/tests/sqllogictests/src/error.rs

Use thiserror in sqllogictest erorr

---

datafusion/core/src/datasource/listing/table.rs
datafusion/core/src/physical_plan/planner.rs
datafusion/core/tests/dataframe.rs
datafusion/expr/src/expr.rs
datafusion/expr/src/expr_rewriter.rs
datafusion/expr/src/expr_schema.rs
datafusion/expr/src/expr_visitor.rs
datafusion/expr/src/logical_plan/builder.rs
datafusion/expr/src/utils.rs
datafusion/optimizer/src/utils.rs
datafusion/proto/src/from_proto.rs
datafusion/proto/src/lib.rs
datafusion/proto/src/to_proto.rs
datafusion/sql/src/planner.rs
datafusion/sql/src/utils.rs

Refactor Expr::Sort to use struct

---

datafusion/expr/src/type_coercion/binary.rs

More descriptive error for plus/minus between timestamps/dates

---

.github/workflows/rust.yml

N/A
`Lint` is a little confusing.

minor: rename the github actions

---

datafusion/core/src/lib.rs

MINOR: Remove where_clause_object_safety clippy ignore (#3081)

---

benchmarks/src/bin/tpch.rs
datafusion/core/src/execution/context.rs
datafusion/core/tests/user_defined_aggregates.rs
datafusion/proto/src/logical_plan/mod.rs

Closes #.
Exposing public members of non-trivial types leaks internal implementation details and complicates making changes in a non-breaking fashion. IMO unless a datatype is literally just a container for data, with no implied relationship between those fields, its members should be private. This is similar to best-practice in C++ for using [struct vs class](https://google.github.io/styleguide/cppguide.html#Structs_vs._Classes).

Make SessionContext members private

---

datafusion/core/src/physical_plan/file_format/parquet.rs
datafusion/core/src/physical_plan/file_format/parquet/page_filter.rs

Part of #4693 
Eagerly constructing the `PagePruningPredicate` not only saves cycles, but allows it to occur when `ExecutionProps` is in scope. A future PR will update `PruningPredicate` to require this to resolve #4693

Eagerly construct PagePruningPredicate

---

datafusion/core/src/physical_plan/file_format/parquet.rs

Improve debug log message per https://github.com/apache/arrow-datafusion/pull/4713#discussion_r1056316886

minor: improve debug logging for pruning predicates

---

datafusion/core/src/physical_plan/file_format/parquet/page_filter.rs

minor: Support more data type for `null_counts` in the `PruningStatistics`

---

datafusion/expr/src/logical_plan/builder.rs
datafusion/expr/src/utils.rs
datafusion/optimizer/src/eliminate_cross_join.rs
datafusion/optimizer/src/extract_equijoin_predicate.rs

Closes #.
1. Use the `find_valid_equijoin_key_pair` to check the validate of  equijoin predicate.
2. Modify the method signature of `check_all_column_from_schema`, return `bool` now.

Minor: use a common method to check the validate of  equijoin predicate

---

datafusion/common/src/error.rs
datafusion/common/src/scalar.rs
datafusion/common/src/table_reference.rs
datafusion/common/src/test_util.rs
datafusion/expr/src/accumulator.rs
datafusion/expr/src/expr.rs
datafusion/expr/src/expr_fn.rs
datafusion/expr/src/logical_plan/plan.rs
datafusion/expr/src/type_coercion/binary.rs
datafusion/expr/src/type_coercion/functions.rs
datafusion/expr/src/utils.rs
datafusion/expr/src/window_frame.rs
datafusion/sql/src/parser.rs

N/A
We plan to use this interface more directly (see  using https://github.com/influxdata/influxdb_iox/pull/6469) so having more documentation will be good.
Improve docstrings
Not really
better docstrings

minor: Improve docstrings

---

README.md

[Greptime DB](https://github.com/GreptimeTeam/greptimedb) is an open source & cloud native distributed time-series database. GreptimeDB's query engine is powered by Apache Arrow DataFusion.

Add a new open source project that is use DataFusion as query engine

---

datafusion/sql/src/planner.rs

refactor: extract `parse_value`

---

datafusion/core/tests/sql/explain_analyze.rs

remove duplicated test

---

datafusion/core/src/physical_plan/file_format/parquet/row_groups.rs

None
While reviewing https://github.com/apache/arrow-datafusion/pull/4810 from @liukun4515  I had to double check what this function was doing, so I wanted to document it to save future self (and maybe other readers)
doc comments on a test functon
No (nor are they needed)
No

minor: add some comments to row group pruning tests

---

docs/source/contributor-guide/roadmap.md

A few links were fixed in https://github.com/romanz/arrow-datafusion/blob/fix-docs/docs/source/contributor-guide/roadmap.md.

Fix a few links in `roadmap.md`

---

README.md

N/A
Enriching the known uses list.
Added Synnada to known uses in the README file.
N/A.
No.

Add Synnada to known uses

---

.gitignore
datafusion/CHANGELOG.md
dev/release/update_change_log.sh

Update changelog for 16.0.0-rc2

---

datafusion/core/src/physical_plan/union.rs

re https://github.com/apache/arrow-datafusion/issues/4883
I was working on https://github.com/apache/arrow-datafusion/issues/4883 and had to remind myself of how UnionExec worked by reading the code. I figured I would add some docs to help my future self as well as others
docstrings and ascii art about union
N/A
Docs

Minor: Add docstrings to UnionExec

---

README.md

[Kamu](https://kamu.dev) is a decentralized collaborative stream processing data pipeline with complete reproducibility and provenance (think "smart contracts" for data streams).
We've been using DataFusion:
- For most of batch-oriented features of our CLI
- Expanding its use to replace Apache Spark
- in our data ingestion flow
- as the default "SQL console" for EDA
Hoping to support the DataFusion project more as we progress!

Docs: Add known user - Kamu

---

.github/workflows/dev_pr/labeler.yml

NA
I find myself trying to find PRs in need of review -- having label categorization helps me do so
label any PR that modifies a file in `datafusion/subtrait` with the `substrait` label. Example
https://github.com/apache/arrow-datafusion/pulls?q=is%3Apr+is%3Aopen+label%3Asubstrait
No (I don't know how to test them other than "live")
No, dev process only

Add substrait label to PRs

---

datafusion/core/src/physical_plan/projection.rs

Executing ProjectionExec with no column should not return an Err

---

datafusion/core/src/physical_plan/file_format/csv.rs

na
Keep context in code in case someone else runs into this and wonders
add comment 
no
no

Minor add ticket link to broken test

---

datafusion/core/tests/sql/joins.rs
datafusion/sql/src/relation/join.rs

Closes #4931.
This PR add the syntax support to DataFusion.

SUPPORT SEMI/ANTI JOIN SQL syntax in DataFusion

---

README.md

MINOR: Add Substrait to feature list in README

---

benchmarks/Cargo.toml
datafusion-cli/Cargo.lock
datafusion-cli/Cargo.toml
datafusion-examples/Cargo.toml
datafusion/common/Cargo.toml
datafusion/core/Cargo.toml
datafusion/expr/Cargo.toml
datafusion/jit/Cargo.toml
datafusion/optimizer/Cargo.toml
datafusion/physical-expr/Cargo.toml
datafusion/proto/Cargo.toml
datafusion/row/Cargo.toml
datafusion/sql/Cargo.toml

Part of https://github.com/apache/arrow-datafusion/issues/4948
Patch release to fix regressions
Bump version numbers

[maint-16.x] Prep for release

---

datafusion/substrait/src/lib.rs

re-export substrait crate

---

datafusion/core/Cargo.toml
datafusion/core/tests/sqllogictests/src/main.rs

Bump sqllogictest to v0.11.1

---

datafusion/core/src/execution/context.rs
datafusion/core/tests/sql/create_drop.rs

Currently, when creating an external table, we won't check whether it exist or not, always create a new table. To create a new table, we need to read data from csv/json/parquet and infer the type, this will bring a lot of extra overhead.
In this pr, before creating an external table, we can check whether table exist or not, if it exist, directly return.
Signed-off-by: xyz <a997647204@gmail.com>
Closes #4997

[Enhancement] early check table exist before create

---

dev/release/README.md
dev/release/release-crates.sh

Closes #5042.
Add the `release-crates.sh` script to simplify publishing of crates to crates.io.

Add `release-crates.sh` script

---

datafusion-examples/examples/avro_sql.rs
datafusion/common/src/config.rs
datafusion/common/src/error.rs
datafusion/common/src/pyarrow.rs
datafusion/core/src/avro_to_arrow/arrow_array_reader.rs
datafusion/core/src/avro_to_arrow/reader.rs
datafusion/core/src/avro_to_arrow/schema.rs
datafusion/core/src/datasource/file_format/avro.rs
datafusion/core/src/physical_plan/aggregates/row_hash.rs
datafusion/core/src/physical_plan/file_format/avro.rs
datafusion/core/src/physical_plan/windows/bounded_window_agg_exec.rs
datafusion/core/tests/sql/avro.rs
datafusion/core/tests/sql/window.rs
datafusion/core/tests/sqllogictests/src/engines/postgres/mod.rs
datafusion/core/tests/window_fuzz.rs
datafusion/optimizer/src/alias.rs
datafusion/row/src/jit/reader.rs
datafusion/row/src/jit/writer.rs
datafusion/sql/src/expr/value.rs
datafusion/substrait/src/consumer.rs
datafusion/substrait/src/producer.rs
datafusion/substrait/src/serializer.rs
datafusion/substrait/tests/roundtrip.rs
datafusion/substrait/tests/serialize.rs

Closes https://github.com/apache/arrow-datafusion/issues/5080
New Rust nightly has new Clippy rules
`cargo clippy --fix`

fix clippy failures

---

datafusion/core/tests/sqllogictests/src/main.rs

Closes https://github.com/apache/arrow-datafusion/issues/5082
Keeping the test using the same number of cores will make for deterministic tests and avoid variance from system to system when running tests
The fact that there is an error when the target partitions are set to 32 is a separate bug tracked via https://github.com/apache/arrow-datafusion/issues/5090
Hardcode target partitions to 4 for sqllogictest runner
yes by existing tests
No -- this is a test harness only issue

Hard code target_partitions=4 in sqllogictests

---

datafusion/CHANGELOG.md

Changelog updates for 17.0.0-rc2

---

README.md

chore: change `DataBend` to `Databend`

---

datafusion/core/tests/sqllogictests/test_files/union.slt

N/A
#5075
fix unstable slt case.

sqllogicaltest: fix unstable slt case.

---

datafusion/core/src/physical_plan/file_format/file_stream.rs

Closes #5019
currently, file stream time scanning will be 'start()' only once, and may be 'stop()' many times. After the first calling to 'stop()', the self.start value of time scanning will be replaced to default value by 'take()'. The subsequent calling to 'stop()' make no sense.
In this pr, we will 'start()' time scanning again, if the scan of current batch is success.

[BugFix] fix file stream time scanning metrics bug

---

datafusion/proto/src/physical_plan/from_proto.rs

Closes #5107 .
See #5107 
Make `parse_physical_expr` public
No need to test
`parse_physical_expr` method goes public

Make `parse_physical_expr` public

---

datafusion/sql/Cargo.toml
datafusion/substrait/Cargo.toml
dev/release/README.md

N/A
Fixing a couple small issues that came up during the release

Fix release issues

---

datafusion/core/src/physical_optimizer/pruning.rs
datafusion/expr/src/logical_plan/plan.rs
datafusion/optimizer/src/push_down_filter.rs
datafusion/sql/src/expr/mod.rs

~Draft as it builds on https://github.com/apache/arrow-datafusion/pull/5092~
Follow on to https://github.com/apache/arrow-datafusion/pull/5092
if it is easier to rewrite expressions in DataFusion, this will lower the barrier to entry to new contributors
Reduces code for the common case of rewriting an expression by letting the Rust compiler capture parameters via a closure. Some rewrites (like constant folding) still need the full generality of the `ExprRewriter` and I did not 
No

Minor: reduce code duplication using `rewrite_expr`

---

datafusion/core/src/execution/memory_pool/pool.rs

Closes #.
Spotted by @xiaoyong-z on https://github.com/apache/arrow-datafusion/pull/4522#discussion_r1094187143

Fix FairSpillPool try_grow for non-spillable consumers

---

datafusion/substrait/README.md

update"DataFusion protobuf definition" link to right place

Update substrait  README.md

---

.github/actions/setup-builder/action.yaml

Closes #.
Recently ran into this in https://github.com/apache/arrow-rs/pull/3661 so thought I would add the fix here also, as this repo will likely run into the same issue.

Patch git Safe Paths in CI

---

README.md

Update README.md link blaze-rs to https://github.com/blaze-init/blaze

Update README.md update blaze-rs link to https://github.com/blaze-init/blaze

---

datafusion/core/src/physical_plan/joins/sort_merge_join.rs

Signed-off-by: xyz <a997647204@gmail.com>
Closes #.

minor: remove unnecessary `continue`

---

datafusion/expr/src/type_coercion/binary.rs
datafusion/physical-expr/src/expressions/binary.rs
datafusion/physical-expr/src/expressions/binary/kernels_arrow.rs

Support arithmetic operation on DictionaryArray

---

datafusion/physical-expr/src/expressions/binary.rs

Closes #.
extract clone outsite.

minor: remove unnecessary clone

---

datafusion/optimizer/src/propagate_empty_relation.rs
datafusion/optimizer/src/test/mod.rs

bugfix: fix propagating empty_relation generates an illegal plan

---

README.md

Update README.md fix [welcoming community] links

---

benchmarks/src/bin/tpch.rs
datafusion/common/src/dfschema.rs
datafusion/common/src/scalar.rs
datafusion/common/src/table_reference.rs
datafusion/core/src/physical_plan/empty.rs
datafusion/core/src/physical_plan/sorts/sort.rs
datafusion/core/src/physical_plan/sorts/sort_preserving_merge.rs
datafusion/core/src/physical_plan/unnest.rs
datafusion/core/src/physical_plan/windows/bounded_window_agg_exec.rs
datafusion/physical-expr/src/aggregate/average.rs
datafusion/physical-expr/src/aggregate/count_distinct.rs
datafusion/physical-expr/src/aggregate/min_max.rs
datafusion/physical-expr/src/aggregate/sum.rs
datafusion/physical-expr/src/expressions/binary.rs
datafusion/physical-expr/src/expressions/binary/kernels_arrow.rs
datafusion/physical-expr/src/expressions/in_list.rs
datafusion/physical-expr/src/window/nth_value.rs
datafusion/substrait/src/logical_plan/consumer.rs

N/A
N/A
fix clippy when use rust-nightly

fix clippy in nightly

---

datafusion/core/src/physical_plan/file_format/json.rs

Closes #4832 .
The bug itself has already been fixed in current master, adding test case for this feature could help to avoid future regressions.
The only change - is the new test.

Test case for NDJsonExec with randomly ordered projection

---

datafusion/core/tests/sqllogictests/src/engines/datafusion/normalize.rs

Closes #5231 .
Remove IMHO unnecessary schema check for SLT, this check prevents to run test cases having mixed nulls and non null values
Its tested, since all SLT tests running fine

[SQLLogicTest] Make schema validation ignore nullable and metadata attributes

---

datafusion/core/tests/dataframe.rs

Closes #.
replace `unwrap()` with `?`

minor: replace `unwrap()` with `?`

---

datafusion/core/src/datasource/file_format/parquet.rs

N/A
I accidentally merged https://github.com/apache/arrow-datafusion/pull/5260 when it had a fmt breakage
`cargo fmt` and check in the result
existing CI

minor: Fix cargo fmt

---

datafusion/core/Cargo.toml
datafusion/core/benches/sort.rs

For benchmarking changes in issue #5230 .
Provide a benchmark to see if changes made for #5230 improve performance.
A benchmark adopted from the `merge` benchmark.

Add benchmark for SortExec

---

.github/dependabot.yml
datafusion/core/src/lib.rs
datafusion/row/README.md
datafusion/substrait/README.md
dev/release/README.md
dev/release/create-tarball.sh
dev/release/update_change_log-datafusion.sh
docs/build.sh
docs/source/conf.py
docs/source/contributor-guide/roadmap.md
docs/source/index.rst

Part of https://github.com/apache/arrow-datafusion/issues/4994
I will submit a request to INFRA to rename `master` to `main` and will then merge this PR once that has happened.
See issue
Replace `master` with `main` where appropriate.

Rename master to main

---

datafusion/core/tests/tpcds_planning.rs

Closes #.
tpcds-64 already was fixed.
enable tpcds-64 test

enable tpcds-64 test

---

datafusion/optimizer/src/scalar_subquery_to_join.rs

Closes #.
This test build a wrong plan (problem in projection)l
build right plan and enable this test.

fix: correct plan builder when test `scalar_subquery_project_expr`

---

docs/source/user-guide/expressions.md

Closes #5312.
Document datafusion math expression usage for corner cases
Not needed
No

[DOC] Update math expression documentation 

---

datafusion-examples/README.md

chore: small typo in the example README

---

.github/dependabot.yml

Closes #5340.
We manually update Arrow so it is pointless to have dependabot filing PRs that nobody will merge.

Ignore Arrow in dependabot

---

benchmarks/expected-plans/q15.txt
benchmarks/expected-plans/q16.txt
benchmarks/expected-plans/q2.txt
benchmarks/expected-plans/q8.txt
benchmarks/expected-plans/q9.txt
datafusion/optimizer/src/lib.rs
datafusion/optimizer/src/merge_projection.rs
datafusion/optimizer/src/optimizer.rs
datafusion/optimizer/tests/integration-test.rs

feat: add rule to merge projection.

---

datafusion/core/tests/tpcds_planning.rs

related #4794 
After disable skip_failed. I find a problem exist in tpcds_logical_q10/q35. It's same with #4794.
So we should disable them until we fix them

minor: disable tpcds_logical_q10/q35

---

datafusion/optimizer/src/merge_projection.rs

N/A
N/A
- fix rule name and comment
- use `unalias()` make code simple

minor: fix rule name and comment.

---

datafusion/optimizer/src/type_coercion.rs

There are some additional tests for "like_for_type_coercion" and "test_type_coercion_rewrite" tests.
Yes
No

Minor: added some tests for coercion type

---

README.md

I think Apache Spark is better than just "spark."
Closes #.

docs: clarify spark

---

docs/source/user-guide/dataframe.md

fix(docs): fix typos

---

datafusion/expr/src/expr_fn.rs

Closes #4974.
Add `datafusion_expr::stddev` to continue  work with https://github.com/apache/arrow-datafusion/pull/5226

Add `expr_fn::stddev` 

---

datafusion/expr/src/expr_fn.rs

Closes #4974.
Add `datafusion_expr::median` to continue  work with https://github.com/apache/arrow-datafusion/pull/5226

add expr_fn::median

---

datafusion/core/Cargo.toml

Upgrade bytes to 1.4

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

Closes #.
Mirror https://github.com/apache/arrow-rs/pull/2196
Comment out description text in issue templates

Comment out description text in issue templates

---

datafusion/core/src/physical_plan/joins/hash_join.rs

--
Fixing tests after #5487 and #5490 were merged
Join creation in one of test cases fixed

fix: hash_join tests with passing boolean by value

---

datafusion/core/Cargo.toml
datafusion/optimizer/Cargo.toml

Add necessary features to optimizer

---

datafusion/core/tests/sqllogictests/README.md

N/A
I keep pointing / suggesting people use these tests so I want to make it as easy as possible to use
Make a cookbook section to put all the most commonly used commands at the beginning
N/A
Docs

minor: improve sqllogictest docs

---

benchmarks/Cargo.toml
datafusion-cli/Cargo.lock
datafusion/core/Cargo.toml
datafusion/expr/Cargo.toml
datafusion/physical-expr/Cargo.toml
datafusion/proto/Cargo.toml
datafusion/substrait/Cargo.toml

Closes #.
Used [cargo-machete](https://github.com/bnjbvr/cargo-machete) to detect unused dependencies & remove them

Remove unused dependencies found by cargo-machete

---

datafusion/execution/src/object_store.rs

re https://github.com/apache/arrow-datafusion/pull/5543
Inspired by @thinkharderdev 's comment on https://github.com/apache/arrow-datafusion/pull/5543#discussion_r1133860499 I didn't fully appreciate the difference between these two traits
Improve doc strings and add some more examples
N/A
Docs

Minor: improve docstrings for `ObjectStoreRegistry` and `ObjectStoreProvider`

---

datafusion/core/tests/sqllogictests/test_files/aggregate.slt
datafusion/physical-expr/src/aggregate/approx_median.rs
datafusion/physical-expr/src/aggregate/approx_percentile_cont.rs
datafusion/physical-expr/src/aggregate/median.rs

refactor: add more error info when array is empty

---

README.md

Closes https://github.com/apache/arrow-datafusion/issues/5498
Make it easier for potential users to evaluate if DataFusion is right for them 
Add some extra information to the main README
N/A
Docs

Clarify differences of DataFusion with other systems in README.md

---

datafusion/core/src/dataframe.rs
datafusion/core/tests/dataframe.rs

Closes #5558
- handle input dataframe has only boolean/binary column got error
- add more test

fix dataframe only boolean/binary column got error on describe

---

datafusion/physical-expr/src/expressions/binary.rs
datafusion/physical-expr/src/expressions/binary/kernels_arrow.rs

Closes #5642.
We should use dyn kernels for modulus too.

Use modulus dyn kernels for arithmetic expressions

---

datafusion/core/tests/sqllogictests/test_files/aggregate.slt
datafusion/physical-expr/src/aggregate/median.rs

Median returns null on empty input instead of error

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

community: polish issue template

---

datafusion/expr/src/logical_plan/plan.rs
datafusion/optimizer/src/decorrelate_where_exists.rs
datafusion/optimizer/src/decorrelate_where_in.rs
datafusion/optimizer/src/scalar_subquery_to_join.rs

Closes #.
add with_plan for Subquery

minor: add with_plan for Subquery

---

datafusion/proto/src/logical_plan/mod.rs
datafusion/proto/src/logical_plan/to_proto.rs

Closes #5691
Handle serialization of `Expr::TryCast`

Handle serialization of TryCast

---

datafusion/optimizer/src/analyzer/count_wildcard_rule.rs
datafusion/optimizer/src/analyzer/inline_table_scan.rs
datafusion/optimizer/src/analyzer/mod.rs
datafusion/optimizer/src/lib.rs
datafusion/optimizer/src/optimizer.rs
datafusion/optimizer/src/test/mod.rs

Closes #5682
move InlineTableScan into Analyzer.
Add Unit test for Analyzer

analyzer: move InlineTableScan into Analyzer.

---

dev/release/rat_exclude_files.txt

Closes https://github.com/apache/arrow-datafusion/issues/5719
Fix rat check failures during release process
Exclude some files from rat check

Exclude some .github files from rat license check

---

Cargo.toml
datafusion-cli/Cargo.lock
datafusion-examples/Cargo.toml
datafusion/common/Cargo.toml
datafusion/core/tests/sql/set_variable.rs
datafusion/expr/Cargo.toml
datafusion/jit/Cargo.toml

Closes #5667
This is the quick fix for https://github.com/apache/arrow-datafusion/pull/5603/files#r1147905129

Use consistent arrow version

---

datafusion/core/tests/sqllogictests/test_files/select.slt
datafusion/sql/src/query.rs

Closes #5711.
See #5711
Fixes for LIMIT edge cases
Yes
No

LIMIT edge cases

---

datafusion/expr/src/type_coercion/mod.rs

Put the file "type_coercion" in the same named fold and rename the file "mod.rs"

---

datafusion/substrait/Cargo.toml
datafusion/substrait/src/logical_plan/producer.rs

Upgrade to substrait 0.5.1 and set the version field of produced plans

---

datafusion/core/tests/sqllogictests/test_files/timestamps.slt

Closes #5164.
The fix was implemented in arrow Rust 36.0.0 adding a test 
Added test to prove change works correctly
yes
no

minor: add timestampstz utf8 conversion test

---

datafusion/core/tests/sqllogictests/src/engines/datafusion/normalize.rs

Closes #.
Replacing a method comparing schemas by name and type with already existing method from arrow-rs
Yes
No

MINOR: simplify sqllogic test schema check

---

datafusion/substrait/Cargo.toml

Bump substrait version to 0.6.0

---

datafusion/optimizer/src/type_coercion.rs

Related #5848.
In original code, type_coercion just consider ( timestamp, interval ) but ignore ( interval, timestamp )
add UT

fix: type_coercion support BinaryExpr ( interval , timestamp ).

---

datafusion/core/src/physical_plan/sorts/cursor.rs
datafusion/core/src/physical_plan/sorts/sort_preserving_merge.rs
datafusion/core/tests/sort_key_cursor.rs

Closes #.
This doesn't appear to be being used anywhere

Remove batch_idx from SortKeyCursor

---

datafusion/core/tests/sqllogictests/test_files/timestamps.slt

Closes #5454.
Prove timestamptz <=> toimestamp conversion bug reported in #5454 fixed with Arrow 36.0.0
Yes
No

Prove timestamptz <=> timestamp now works

---

benchmarks/src/bin/parquet.rs
datafusion/expr/src/operator.rs
datafusion/expr/src/type_coercion/binary.rs
datafusion/expr/src/utils.rs
datafusion/optimizer/src/type_coercion.rs

Closes #5849.
Closes #5847.
Add UT.

fix: coerce type for InSubquery and fix timestamp minus timestamp.

---

datafusion/core/Cargo.toml

Closes #.
https://github.com/apache/arrow-datafusion/pull/5831#discussion_r1158188354
update sqllogictest version 0.13.2.

chore: update sqllogictest version 0.13.2.

---

datafusion/core/src/catalog/information_schema.rs
datafusion/core/src/catalog/mod.rs

Closes #.
pub the information schema providers so that we can reuse it from outside

minor: made `information_schema` pub

---

docs/source/contributor-guide/architecture.md

Closes https://github.com/apache/arrow-datafusion/issues/5499
Add @alamb April architecture tech talks to documentation

[Minor]: Update `architecture.md` to include April tech talks

---

datafusion/optimizer/src/analyzer/type_coercion.rs

test: add Between UT for type_coercion

---

datafusion/core/tests/sqllogictests/test_files/scalar.slt
datafusion/expr/src/built_in_function.rs
datafusion/expr/src/expr_fn.rs
datafusion/expr/src/function.rs
datafusion/physical-expr/src/functions.rs
datafusion/physical-expr/src/math_expressions.rs
datafusion/proto/proto/datafusion.proto
datafusion/proto/src/generated/pbjson.rs
datafusion/proto/src/generated/prost.rs
datafusion/proto/src/logical_plan/from_proto.rs
datafusion/proto/src/logical_plan/to_proto.rs
docs/source/user-guide/expressions.md
docs/source/user-guide/sql/scalar_functions.md

Part of https://github.com/apache/arrow-datafusion/issues/5838
Implementation of the constant "Pi" (3.14159...)
Yes
Yes

feat: implementation of the constant "Pi"

---

docs/source/_static/theme_overrides.css
docs/source/_templates/docs-sidebar.html

Closes #5935
Fix site sidebar logo position to respect the scrolling sidebar and always remain below it (and not overlap)
Example:

doc: fix site sidebar logo position

---

datafusion-examples/examples/dataframe_subquery.rs

Keeping code and comment logic consistent.

minor:update subquery example

---

datafusion/expr/src/logical_plan/plan.rs

fix: Do not panic on invalid placeholders

---

datafusion/optimizer/src/analyzer/mod.rs
datafusion/optimizer/src/optimizer.rs
datafusion/optimizer/src/utils.rs

Remove duplicated code in analyzer and optimizer.
move log_plan to utils.

minor:move log_plan to utils

---

datafusion/core/tests/user_defined_aggregates.rs

refactor: make `FirstSelector` not to have `update` and `merge`

---

README.md

minor: add developer's guide link in README.md

---

datafusion/core/src/physical_plan/udaf.rs
datafusion/proto/proto/datafusion.proto
datafusion/proto/src/generated/pbjson.rs
datafusion/proto/src/generated/prost.rs
datafusion/proto/src/physical_plan/mod.rs
datafusion/proto/src/physical_plan/to_proto.rs

Add support for UDAF in physical plan serialization

---

datafusion/core/tests/sqllogictests/test_files/join.slt
datafusion/expr/src/logical_plan/builder.rs

Closes https://github.com/apache/arrow-datafusion/issues/5994 .
Fixes partially https://github.com/apache/arrow-datafusion/issues/5747
Fix bugs reported in https://github.com/apache/arrow-datafusion/issues/5994
Yes
No

infer column nullability on joins

---

datafusion/core/src/datasource/empty.rs
datafusion/core/src/datasource/memory.rs
datafusion/core/src/lib.rs
datafusion/row/src/jit/writer.rs
docs/source/contributor-guide/architecture.md

Closes  https://github.com/apache/arrow-datafusion/issues/5501
I am trying to make it easier to work on and use the DataFusion project
1. Update the architecture guide 
No (though  the links are verified by the changes in https://github.com/apache/arrow-datafusion/pull/6044) 
Better docs
Here is an example:

Update DataFusion architecture documentation

---

datafusion/common/src/dfschema.rs
datafusion/core/tests/sqllogictests/test_files/groupby.slt
datafusion/expr/src/utils.rs

Closes #.
slt: groupby same colomn

fix: allow group by same expr in Aggregate

---

datafusion/core/tests/sqllogictests/test_files/groupby.slt

Closes #.
#6099
Add sqllogicaltest about GROUPBY.
A small part in https://github.com/gregrahn/sqllogictest
Add test

test: more sqllogicaltest for GROUPBY.

---

datafusion/common/src/scalar.rs
datafusion/core/src/execution/context.rs
datafusion/core/src/physical_optimizer/sort_enforcement.rs
datafusion/expr/src/type_coercion/binary.rs
datafusion/optimizer/src/analyzer/count_wildcard_rule.rs
datafusion/optimizer/src/common_subexpr_eliminate.rs
datafusion/physical-expr/src/expressions/datetime.rs
datafusion/physical-expr/src/expressions/not.rs
datafusion/physical-expr/src/intervals/interval_aritmetic.rs
datafusion/proto/src/physical_plan/mod.rs

minor: replace unwrap() with Err

---

datafusion/physical-expr/src/expressions/datetime.rs
datafusion/physical-expr/src/expressions/in_list.rs
datafusion/physical-expr/src/expressions/mod.rs
datafusion/physical-expr/src/intervals/test_utils.rs
datafusion/physical-expr/src/planner.rs
datafusion/physical-expr/src/utils.rs
datafusion/proto/src/physical_plan/from_proto.rs
datafusion/proto/src/physical_plan/mod.rs

Closes #6117.
FollowUp after https://github.com/apache/arrow-datafusion/pull/6114

Remove input schema from PhysicalExpr, move the validation logic to physical expression planner

---

datafusion/expr/src/logical_plan/plan.rs

When I merged https://github.com/apache/arrow-datafusion/pull/6121 I introduced a logical merge conflict
Fix build

Fix broken build due to merge conflict

---

datafusion/row/src/lib.rs

Closes -.
https://github.com/apache/arrow-datafusion/pull/5973#pullrequestreview-1383407703
Add two tests.

minor: add decimal roundtrip tests for the row format

---

datafusion/physical-expr/src/aggregate/sum.rs

Handle ScalarValue::Dictionary in add_to_row and update_avg_to_row

---

datafusion/core/src/physical_plan/joins/hash_join.rs
datafusion/core/tests/memory_limit.rs

Closes #.
The use of shared memory reservations was not only confusing, but also unnecessary. This reworks the memory accounting to not need this complexity. If we like this approach I will do something similar for the other joins

Simplify HashJoin memory accounting

---

datafusion/core/tests/sqllogictests/test_files/timestamps.slt
datafusion/core/tests/sqllogictests/test_files/type_coercion.slt
datafusion/expr/src/type_coercion/binary.rs
datafusion/expr/src/type_coercion/mod.rs
datafusion/optimizer/src/analyzer/type_coercion.rs

Closes #6176.
add type coercion for Date - Interval
add sqllogicaltest.

fix: type coercion ignore prevent  `Interval - Date`

---

datafusion/physical-expr/src/expressions/binary.rs

I noticed this while trying to figure out how to clean up binary.rs
I think this code is old, outdate and unecessary
Remove dead code
no

minor: remove unused code in binary.rs

---

datafusion/core/src/datasource/listing/table.rs

N/A
Just fix typo.
N/A
N/A
N/A

minor: fix tiny typo in table.rs

---

datafusion/core/src/physical_plan/joins/nested_loop_join.rs

NA
As suggested by @comphead  `batch` is pretty generic: https://github.com/apache/arrow-datafusion/pull/6188/files#r1182689135
rename `batch` to `right_batch` in `NestedLoopsJoinExec`

Minor: rename variable for clarity

---

datafusion/optimizer/src/analyzer/type_coercion.rs

Closes #.
There are same code in type coercion, unify them by using one function

minor: refactor code to avoid same code.

---

datafusion/core/src/physical_optimizer/sort_enforcement.rs
datafusion/core/src/physical_plan/aggregates/mod.rs
datafusion/core/src/physical_plan/file_format/mod.rs
datafusion/core/tests/sqllogictests/test_files/interval.slt
datafusion/optimizer/src/analyzer/subquery.rs
datafusion/physical-expr/src/expressions/binary/kernels_arrow.rs
datafusion/physical-expr/src/utils.rs

fix: slt fail due to bors problem

---

docs/source/user-guide/sql/ddl.md

Closes #.
add more sql example in ddl.md

doc: add more sql example in ddl.md

---

datafusion/expr/src/type_coercion/binary.rs
datafusion/optimizer/src/analyzer/type_coercion.rs
datafusion/physical-expr/src/expressions/binary.rs

Closes #.
remove prefix in type_coercion to make code clear

minor: remove prefix in type_coercion

---

datafusion/expr/src/type_coercion/binary.rs

N/A 
I noticed this while reviewing https://github.com/apache/arrow-datafusion/pull/6269 from @viirya 
https://github.com/apache/arrow-datafusion/issues/3387 has been closed so there is no need for this workaround any longer
remove workaround 

minor: Remove dead code for casting dictionaries

---

datafusion/core/src/datasource/listing/helpers.rs
datafusion/core/src/physical_plan/planner.rs
datafusion/expr/src/expr.rs
datafusion/expr/src/expr_schema.rs
datafusion/expr/src/tree_node/expr.rs
datafusion/expr/src/udf.rs
datafusion/expr/src/utils.rs
datafusion/optimizer/src/analyzer/type_coercion.rs
datafusion/optimizer/src/push_down_filter.rs
datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs
datafusion/physical-expr/src/planner.rs
datafusion/proto/src/logical_plan/from_proto.rs
datafusion/proto/src/logical_plan/mod.rs
datafusion/proto/src/logical_plan/to_proto.rs
datafusion/sql/src/expr/function.rs
datafusion/sql/src/utils.rs

Related to https://github.com/apache/arrow-datafusion/issues/2175 and https://github.com/apache/arrow-datafusion/issues/3807.
following #6281

refactor: Expr::ScalarUDF to use a struct

---

datafusion/core/src/physical_optimizer/pruning.rs
datafusion/core/src/physical_plan/planner.rs
datafusion/expr/src/expr.rs
datafusion/expr/src/expr_fn.rs
datafusion/expr/src/expr_schema.rs
datafusion/expr/src/tree_node/expr.rs
datafusion/optimizer/src/analyzer/type_coercion.rs
datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs
datafusion/optimizer/src/simplify_expressions/utils.rs
datafusion/optimizer/src/unwrap_cast_in_comparison.rs
datafusion/physical-expr/src/planner.rs
datafusion/proto/src/logical_plan/from_proto.rs
datafusion/proto/src/logical_plan/mod.rs
datafusion/proto/src/logical_plan/to_proto.rs
datafusion/sql/src/expr/mod.rs
datafusion/sql/src/utils.rs

Related to https://github.com/apache/arrow-datafusion/issues/2175 and https://github.com/apache/arrow-datafusion/issues/3807.

refactor: Expr::InList to use a struct

---

docs/source/user-guide/cli.md

git checkout 12.0.0 was erroring due to .git file could not be found
Closes #.

corrected order of cd command to git checkout

---

docs/source/user-guide/example-usage.md

Follow snmalloc upgrade in 9.0.0
None
Align dependency version in the docs with the code
Documentation doesn't require specific tests

Bump snmalloc version in the example usage doc

---

datafusion/execution/src/disk_manager.rs

Due to variable shadowing, the test code always pass. Changing 'file_path' to 'dir_path'.

Fix variable shadowing in test code

---

Cargo.toml
benchmarks/Cargo.toml
datafusion-cli/Cargo.lock
datafusion-cli/Cargo.toml
datafusion/CHANGELOG.md
datafusion/core/Cargo.toml
datafusion/execution/Cargo.toml
datafusion/expr/Cargo.toml
datafusion/optimizer/Cargo.toml
datafusion/physical-expr/Cargo.toml
datafusion/proto/Cargo.toml
datafusion/row/Cargo.toml
datafusion/sql/Cargo.toml
datafusion/substrait/Cargo.toml
dev/changelog/25.0.0.md

N/A
Scheduled release
- Bump version
- Update changelog ([rendered version](https://github.com/andygrove/arrow-datafusion/blob/release-25.0.0/dev/changelog/25.0.0.md))

Prepare for 25.0.0 Release

---

datafusion/core/src/physical_plan/file_format/mod.rs

Minor fix for the Debug of FileScanConfig

---

datafusion/common/src/utils.rs

Closes #.
Replace parse_identifiers code with upstreamed version from sqlparser: https://github.com/sqlparser-rs/sqlparser-rs/issues/805

minor: Use parse_multipart_identifier from sqlparser

---

datafusion/optimizer/src/simplify_expressions/or_in_list_simplifier.rs

https://github.com/apache/arrow-datafusion/pull/6414
It's my fault to not let it be known that the above PR was still being worked on. This is an additional optimization to the code in the above PR based on the review.
Remove unnecessary clone in OrInListSimplifier
No

Minimize clone in OrInListSimplifier

---

datafusion/core/tests/sqllogictests/test_files/window.slt
datafusion/expr/src/window_frame.rs

Closes #.
Small refactoring for window frame error messages, making them more consistent and readable
Yes
Window frame error message will slightly change

minor: make window frame error messages more consistent

---

datafusion/core/src/physical_plan/aggregates/bounded_aggregate_stream.rs
datafusion/core/src/physical_plan/aggregates/row_hash.rs
datafusion/expr/src/conditional_expressions.rs
datafusion/expr/src/logical_plan/plan.rs
datafusion/expr/src/table_source.rs

Closes https://github.com/apache/arrow-datafusion/issues/6529
Rust 1.70 was released and it has some new clippy lints
Change some `///!` style comments to `//!`  (note that it lost the extra `/`)
Yes by CI

Fix new clippy lint

---

docs/source/user-guide/sql/select.md

Related to https://github.com/apache/arrow-datafusion/issues/6439 
It would be nice to document the new feature @mustafasrepo  added in https://github.com/apache/arrow-datafusion/pull/6481
Add entry in user guide

Minor: Add EXCEPT/EXCLUDE to SQL guide

---

README.md

N/A
DataFusion is both a Rust library and a Python library. There is currently no mention of the Python bindings in the top-level README.
Update top-level README to state that Python bindings are available, with a link to the repo.
N/A
No

Add link to Python Bindings in top-level README

---

datafusion/core/src/catalog/information_schema.rs
datafusion/core/src/catalog/listing_schema.rs

feat: fix docs

---

datafusion/core/src/catalog/information_schema.rs

fix: ignore panics if racing against catalog/schema changes

---

datafusion/core/tests/sqllogictests/test_files/scalar.slt
datafusion/sql/src/expr/function.rs
datafusion/sql/tests/integration_test.rs

Closes #6436 
Yes
add some tests in scala.slt

fix Incorrect function-name matching with disabled enable_ident_normalization

---

datafusion/physical-expr/src/datetime_expressions.rs
datafusion/physical-expr/src/window/aggregate.rs
datafusion/physical-expr/src/window/built_in.rs

minor: remove useless mut and borrow()

---

datafusion/core/tests/sql/timestamp.rs

Closes #.
fix and enable a test

fix: correct test timestamp_add_interval_months

---

datafusion/expr/src/literal.rs

Closes #.
Although we can use the `NonZero*::get()` method to obtain the inner integer value, it still deserves impl the `Literal` trait to bring more convenience.

Impl `Literal` trait for `NonZero*` types
