apache/datafusion

datafusion/core/src/execution/memory_manager/mod.rs

Part of #4328 
Included a check to avoid underflow when available memory is calculated when consumers request additional memory. 
The trackers acquire memory independent of `MemoryManager` and communicates the memory acquired using the function `grow_tracker_usage`. The tracker can end up allocating more memory than what is defined in `MemoryManager.pool_size` This PR does not prevent trackers from allocating more memory than what is defined in `MemoryManager.pool_size`. Might be a candidate for future refactoring.
Added a test to avoid underflow.

Add check to avoid underflow in memory manager

---

datafusion/core/src/datasource/listing/table.rs

Throw error (not `panic`) if a listing table specifies an missing partition column

---

datafusion/common/src/dfschema.rs
datafusion/optimizer/src/optimizer.rs

Closes https://github.com/apache/arrow-datafusion/issues/4346
Note this PR is almost all tests
Optimizer passes do not necessarily keep nullability and metadata the same between passes
See https://github.com/apache/arrow-datafusion/issues/4346 for more detail
1. Make the check added in https://github.com/apache/arrow-datafusion/pull/4233  less stringent by only checking field name and data type. 
Yes
No

Do not error in optimizer if resulting schema has different metadata

---

datafusion/core/src/physical_plan/file_format/parquet/page_filter.rs

Closes https://github.com/apache/arrow-datafusion/issues/4236 (cc @HaoYang670 )
errors are ignored when creating page indexes but were being logged as error (to the output)
reduce logging level to debug from error
No (for logging)
Not really. cc @Ted-Jiang

Do not log error if page index can not be evaluated

---

datafusion/core/src/physical_plan/joins/hash_join.rs
datafusion/core/tests/sql/joins.rs
datafusion/core/tests/sql/mod.rs
datafusion/sql/src/planner.rs

Closes #4362.
The PR also added some join UTs to cover different join types(Semi/Anti/Cross). It discloses several bugs and need to be addressed further.

HashJoin should return Err when the right side input stream produce Err, add more join UTs to cover different join types

---

datafusion/optimizer/src/optimizer.rs

N/A
I am debugging something wrong in one of the optimizer passes it wasn't immediately obvious to me from the logging that some passes didn't change the plan at all. 
Do not log the plan for optimizer passes that didn't make changes
Not really
no

minor: improve optimizer logging and do not repeat rule name

---

docs/source/user-guide/example-usage.md

Closes #.
This change makes the SQL and DataFrame (DF) examples at https://arrow.apache.org/datafusion/user-guide/example-usage.html more similar.
Currently the SQL example uses `LIMIT 100`  while the DF one collects all results and then just prints the first 100 via `show_limit(100)`.
The sample DF code now uses `limit()` instead of `show_limit()`. 
No.
No

Use limit() function instead of show_limit() in the first example

---

datafusion/common/src/cast.rs
datafusion/common/src/scalar.rs
datafusion/core/src/physical_plan/joins/hash_join.rs
datafusion/core/src/physical_plan/sorts/sort.rs
datafusion/core/src/physical_plan/windows/mod.rs
datafusion/core/tests/custom_sources.rs
datafusion/core/tests/provider_filter_pushdown.rs
datafusion/core/tests/sql/parquet.rs
datafusion/core/tests/user_defined_aggregates.rs
datafusion/physical-expr/src/aggregate/median.rs
datafusion/physical-expr/src/crypto_expressions.rs
datafusion/physical-expr/src/expressions/in_list.rs
datafusion/physical-expr/src/hash_utils.rs
datafusion/physical-expr/src/string_expressions.rs

This is discussed in #3152. 
This is the new PR of improving error handling for downcasting. In #4261 we found out that there is a `downcast_value!` macro which also covers our casting functions. Implementing `as_xxx_array` function with `downcast_value!` is nearly decided for now for future PRs. 
- Refactor previous casting functions.
- Add some more types for downcasting.
- I remove some macros and use my downcasting functions in [string_expression.rs](https://github.com/apache/arrow-datafusion/blob/master/datafusion/physical-expr/src/string_expressions.rs). Please review it carefully. I don't want to break crucial parts.

Improve error handling and add some more types for proper downcasting

---

datafusion/common/src/scalar.rs
datafusion/core/src/physical_plan/aggregates/hash.rs
datafusion/core/src/physical_plan/aggregates/mod.rs

For #3940.
**Update: This does NOT close the issue. I forgot the no-group version (`AggregateStream`). Will do that in a follow-up PR. It's a rather simple change though.**
Ensure that users don't run out of memory while performing group-by operations. This is esp. important for servers or multi-tenant systems.
This is similar to #4202. It includes an additional type `StreamType` so we can double-check our test setup (namely: is the stream that we request actually the stream version we want).
Extended `test_oom`. Also here are the perf results:
```console
❯ cargo bench -p datafusion --bench aggregate_query_sql -- --baseline issue3940d-pre …
```

feat: `ResourceExhausted` for memory limit in `GroupedHashAggregateStream`

---

datafusion/expr/src/expr_fn.rs

Closes #4298.
Update docs for the scalar functions
Remove the macro `unary_scalar_expr`

Clean the `expr_fn` - use `scalar_expr` to create unary scalar expr functions,  remove macro `unary_scalar_functions`

---

datafusion/core/src/physical_plan/file_format/parquet/page_filter.rs
datafusion/core/tests/parquet/page_pruning.rs

Closes #4317.
After fix all the ignore issue, I think now page pruning has the same amount test case like row group pruning✌️.

Fix page index pruning fail on complex_expr

---

datafusion/core/src/physical_plan/limit.rs

None.
1. Remove the `current_skip` and `current_fetch` from `LimitStream` because they are redundant.
2. Remove the public function `truncate_batch` and merge its functionality into `stream_limit`. Because `truncate_batch` is    not performant when `row_num == 0` and it's only used in `stream_limit`
Current tests cover the changes.
No.

Clean the code in `limit.rs`.

---

datafusion/core/src/physical_plan/sorts/cursor.rs
datafusion/core/src/physical_plan/sorts/sort_preserving_merge.rs

Closes #4300.
running benchmarks with `cargo bench --bench merge`:
```
merge i64               time:   [8.0959 ms 8.2001 ms 8.3260 ms]
change: [-58.629% -57.906% -57.138%] (p = 0.00 < 0.05)
Found 11 outliers among 100 measurements (11.00%)
7 (7.00%) high severe
merge f64               time:   [8.2829 ms 8.3378 ms 8.4028 ms]
change: [-56.127% -55.475% -54.829%] (p = 0.00 < 0.05)
Found 10 outliers among 100 measurements (10.00%)
5 (5.00%) high mild
5 (5.00%) high severe
merge utf8 low cardinality
time:   [7.5418 ms 7.6425 ms 7.7538 ms]
change: [-65.897% -65.335% -64.703%] (p = 0.00 < 0.05)
Found 13 outliers among 100 measurements (13.00%)
7 (7.00%) high mild
6 (6.00%) high severe
merge utf8 …
```

Use tournament loser tree for k-way sort-merging, increase merge speed by 50%

---

datafusion/core/src/physical_plan/aggregates/mod.rs
datafusion/core/src/physical_plan/aggregates/no_grouping.rs

Closes #3940.
Ensure that users don't run out of memory while performing group-by operations. This is esp. important for servers or multi-tenant systems.
Same as #4371 and #4202 but for `AggregateStream` (used when there are no group keys).
`test_oom` extended. Perf results:
```text
❯ cargo bench -p datafusion --bench aggregate_query_sql -- --baseline issue3940e-pre
Finished bench [optimized] target(s) in 0.09s
Running benches/aggregate_query_sql.rs (target/release/deps/aggregate_query_sql-6efc67fad0362d05)
aggregate_query_no_group_by 15 12
time:   [690.60 µs 691.61 µs 692.75 µs]
change: [+0.2423% +0.7005% +1.1322%] (p = 0.00 < 0.05)
Found 11 outliers among 100 measurements (11.00%)
2 (2.00%) low severe
1 (1.00%) low mild
4 (4.00%) high …
```

feat: `ResourceExhausted` for memory limit in `AggregateStream`

---

datafusion/optimizer/src/eliminate_limit.rs

reimplment `eliminate_limit` to remove `global-state`.

---

datafusion/core/src/physical_plan/joins/hash_join.rs

Closes #4009 
improve hashjoin execution metrics, include hashmap build time.

improve hashjoin execution metrics

---

datafusion/core/src/execution/memory_manager/proxy.rs
datafusion/core/src/physical_plan/aggregates/hash.rs
datafusion/core/src/physical_plan/aggregates/no_grouping.rs
datafusion/core/src/physical_plan/aggregates/row_hash.rs
datafusion/core/src/physical_plan/sorts/sort.rs
datafusion/core/tests/join_fuzz.rs
datafusion/core/tests/memory_limit.rs
datafusion/core/tests/merge_fuzz.rs
datafusion/core/tests/order_spill_fuzz.rs
test-utils/src/lib.rs

~Draft as it is waiting on:~
Resolves https://github.com/apache/arrow-datafusion/issues/4404
I would like end to end coverage that when run with a memory limit, queries will error (rather than exceed the memory limit)
1. Add new `memory_limit` test
2. Improve error messages to make it clearer what is out of memory
2. Refactor `stagger_batch` into a function

Add integration test for erroring when memory limits are hit

---

datafusion/core/src/physical_plan/filter.rs

No
If **Selection operator** doesn't produce any rows, we can just pull next `RecordBatch`es from it.
Add loop for filter executor.
No

Optimize filter executor in pull-based executor

---

datafusion/physical-expr/src/string_expressions.rs

Closes #4339.
Better control for `to_hex` function
Now it returns error if it can't cast. There was a `unwrap` usage before this change

fix panic on to_hex function for negative numbers

---

datafusion/optimizer/src/limit_push_down.rs

add more join case which can be optimized for the `limit push down` rule.
Closes #.

optimize limit push for join case

---

datafusion-cli/src/command.rs
datafusion-cli/src/main.rs
datafusion-cli/src/object_storage.rs
datafusion-cli/src/print_format.rs
datafusion/core/src/datasource/listing_table_factory.rs
datafusion/core/src/physical_plan/repartition.rs
datafusion/physical-expr/src/regex_expressions.rs

Closes #4434.
Now that DF emits `ResourceExhausted` errors for out-of-memory situations, it would be nice if the API user could somehow detect this situation (e.g. to convert this to a suitable HTTP status code).
Convert a bunch of `Execution` errors into typed errors.
**:warning: Consensus required prior to merging :warning:**
None. I'm not really sure how we want to prevent regressions here. It's just too many errors. I somewhat check-able rule (via some regex script?!) would be: "no `Execution\(.+\.to_string`". Shall I add this to the `lint` CI workflow?
Errors types slightly changed. This also changes error texts a bit.

fix: do NOT convert errors to strings but keep the type

---

datafusion/common/src/error.rs

Closes #4435.
It would be nice to get the typed "original" error, even when it is wrapped into a chain of `ExternalError`, `ArrowError`, `Arc` etc. The original error could be used to generate HTTP status codes in certain situations, e.g. "resource exhausted".
```rust
impl DataFusionError {
/// Get underlying error.
///
/// This may be the same as `self`.
pub fn find_root(&self) -> &Self {...}
}
```
- `test_find_root_error`
New method for `DataFusionError`.

feat: `DataFusionError::find_root`

---

datafusion/core/tests/sql/explain_analyze.rs
datafusion/expr/src/utils.rs

Closes #4378 .
Replace panics in favor if Error

The CLI panics when passing an invalid explain query

---

datafusion/common/src/cast.rs
datafusion/core/src/avro_to_arrow/arrow_array_reader.rs
datafusion/core/src/datasource/file_format/avro.rs
datafusion/core/src/datasource/file_format/parquet.rs
datafusion/physical-expr/src/crypto_expressions.rs
datafusion/physical-expr/src/datetime_expressions.rs
datafusion/physical-expr/src/expressions/datetime.rs
datafusion/row/src/writer.rs

Discussed in #3152 .
This is the new PR in series to improve error handling for downcasting.
- Add `as_xxx_array` functions for following types to downcast:
- `MapArray`
- `NullArray`
- `UnionArray`
- `TimestampNanosecondArray`
- `TimestampMillisecondArray`
- `TimestampMicrosecondArray`
- `TimestampSecondArray`
- `BinaryArray`

Improve error handling for array downcasting

---

datafusion-examples/examples/custom_datasource.rs
datafusion/common/src/scalar.rs
datafusion/core/src/dataframe.rs
datafusion/core/src/datasource/datasource.rs
datafusion/core/src/datasource/empty.rs
datafusion/core/src/datasource/listing/table.rs
datafusion/core/src/datasource/memory.rs
datafusion/core/src/datasource/view.rs
datafusion/core/src/physical_optimizer/join_selection.rs
datafusion/core/src/physical_plan/joins/hash_join.rs
datafusion/core/src/physical_plan/planner.rs
datafusion/core/src/test_util.rs
datafusion/core/tests/custom_sources.rs
datafusion/core/tests/provider_filter_pushdown.rs
datafusion/core/tests/row.rs
datafusion/core/tests/sql/information_schema.rs
datafusion/core/tests/statistics.rs
datafusion/expr/src/type_coercion/other.rs
datafusion/optimizer/src/type_coercion.rs
datafusion/physical-expr/src/window/lead_lag.rs
datafusion/proto/src/logical_plan.rs
datafusion/sql/src/planner.rs

Part of #4424 
Changed some occurrences of `&Option<T>` with `Option<&T>`
There might be user facing changes as public functions are modified. Would leave it up to reviewers to add `api-change` tag.

Replace `&Option<T>` with `Option<&T>`

---

datafusion/common/src/dfschema.rs

re https://github.com/apache/arrow-datafusion/pull/4347/files
per @mingmwang 's suggestion, handle field equivalence checks for nested types: https://github.com/apache/arrow-datafusion/pull/4347/files#r1031012003
1. Check equivalences for nested types
2. Tests
Yes
No (fewer potential false positives in optimizer checks)

Add check for nested types in equivalent names and types

---

datafusion/physical-expr/src/window/aggregate.rs
datafusion/physical-expr/src/window/built_in.rs
datafusion/physical-expr/src/window/built_in_window_function_expr.rs
datafusion/physical-expr/src/window/cume_dist.rs
datafusion/physical-expr/src/window/lead_lag.rs
datafusion/physical-expr/src/window/nth_value.rs
datafusion/physical-expr/src/window/partition_evaluator.rs
datafusion/physical-expr/src/window/rank.rs
datafusion/physical-expr/src/window/row_number.rs
datafusion/physical-expr/src/window/window_expr.rs

Closes #4440.
Handling of the Builtin Window Functions (such as `ROW_NUMBER`, `FIRST_VALUE`, etc.) are quite different than accumulators (such as `SUM`, `AVG`, etc.) even though they have significant commonalities. We can increase readability if we make their implementation similar in spirit; and we can increase code reuse in this way too. This PR changes the `PartitionEvaluator` trait such that it resembles the `Accumulator` trait.
The `create_evaluator` method of `BuiltInWindowFunctionExpr` no longer takes a record batch during creation. Instead; when we are doing evaluation, we pass the relevant batch section to the `evaluate` method of the `PartitionEvaluator` trait.
N.A (Existing tests should work after refactor)

Refactor Builtin Window Function Implementation

---

datafusion/core/src/datasource/view.rs
datafusion/optimizer/src/limit_push_down.rs

part of https://github.com/apache/arrow-datafusion/issues/4381 .

Fix `push down limit` regression when meet SubqueryAlias

---

docs/source/contributor-guide/index.md

re https://github.com/apache/arrow-datafusion/issues/4460
make the harness added in https://github.com/apache/arrow-datafusion/pull/4395 by @mvanschellebeeck  easier to find
Add a pointer to these tests in the contributor guide
N/A

MINOR: Add note about sqllogictest to contributor guide

---

datafusion/core/src/physical_plan/windows/window_agg_exec.rs
datafusion/core/tests/sql/window.rs

Fix output_partitioning(), output_ordering(), equivalence_properties() in WindowAggExec, shift the Column indexes

---

datafusion/jit/src/jit.rs
datafusion/physical-expr/src/crypto_expressions.rs
datafusion/proto/src/from_proto.rs
datafusion/proto/src/physical_plan/from_proto.rs
datafusion/proto/src/to_proto.rs

Part of #4424 
No user-facing changes.

Replace `&Option<T>` with `Option<&T>` part 2

---

datafusion/optimizer/src/push_down_filter.rs
datafusion/optimizer/tests/integration-test.rs

fix `push_down_filter` for pushing filters on grouping columns rather than aggregate columns

---

datafusion-examples/examples/memtable.rs
datafusion/core/tests/sqllogictests/test_files/cte.slt
datafusion/sql/src/planner.rs

No. I found the bug in databend. Then I tested DF and found the same bug 🤣 
`From` clause may exist CTEs, we should separate them from global CTEs.
CTEs in from clause are allowed to be duplicated.
Yes, use sqllogictest!
No

Fix `Cte` in `from` clause with duplicated cte name

---

.github/workflows/rust.yml

There's no need for a separate CI run as sqllogictests already run as part of cargo test here: https://github.com/apache/arrow-datafusion/blob/master/.github/workflows/rust.yml#L71

Remove sqllogictests CI run

---

datafusion/core/src/datasource/memory.rs
datafusion/core/tests/sqllogictests/src/error.rs
datafusion/core/tests/sqllogictests/src/insert/mod.rs

Follow up https://github.com/apache/arrow-datafusion/pull/4496

Remove interior mutability of `MemTable`

---

benchmarks/src/bin/tpch.rs
benchmarks/src/tpch.rs
datafusion/core/src/dataframe.rs
datafusion/expr/src/expr_rewriter.rs
datafusion/expr/src/logical_plan/builder.rs
datafusion/expr/src/utils.rs
datafusion/optimizer/src/decorrelate_where_in.rs
datafusion/optimizer/src/inline_table_scan.rs
datafusion/optimizer/src/push_down_filter.rs
datafusion/optimizer/src/scalar_subquery_to_join.rs
datafusion/optimizer/src/simplify_expressions/simplify_exprs.rs
datafusion/optimizer/src/subquery_filter_to_join.rs
datafusion/proto/src/logical_plan.rs
datafusion/sql/src/planner.rs

re https://github.com/apache/arrow-datafusion/issues/4483
When I was in the process of investigating the reasons for duplicate Projects and duplicate aliases, I find the code of create subquery_alias or expr-alias use multiple method.
After refactor it, we can easily find all code of create `alias`  
refactor code about subquery_alias and expr-alias.

refactor code about `subquery_alias` and `expr-alias`.

---

datafusion/core/tests/sqllogictests/src/insert/mod.rs
datafusion/sql/src/planner.rs

While working on PR #4490 that implements `PREPARE stmt`, I found that I need to pass the provided data types of the parameters/binding down to the plan's expressions  to map data types to $1, $2, ...
@alamb has suggested me to pass datatypes of the parameters  along with the CTEs. This PR is just a refactor to convert `ctes` from a hash map to a struct that store both ctes (hahhmap) and the params' data types.

refactor: make Ctes a struct to also store data types provided by prepare stmt

---

datafusion/core/src/physical_plan/windows/window_agg_exec.rs
datafusion/core/tests/sql/window.rs
datafusion/physical-expr/src/window/aggregate.rs
datafusion/physical-expr/src/window/built_in.rs
datafusion/physical-expr/src/window/window_expr.rs

Closes #4509 .
Need show window frame info in window_agg_exec
Before
```
explain SELECT s_suppkey, s_nationkey, s_acctbal, (sum(s_acctbal) over (
ORDER BY s_acctbal DESC ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING)) wr
FROM supplier
limit 10;
+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| plan_type     | plan                                                                                                                                                                                                                             | …
```

Add get_window_frame in window_expr, show frame info in window_agg_exec

---

datafusion/expr/src/logical_plan/builder.rs
datafusion/sql/src/planner.rs

Closes #4526
remove `outer_query_schema` in `sql_select_to_rex`.
selection-expr is independent, we shouldn't add outer_schema in its schema.
Selection-subquery is different from where-subquery/from-subquery.

shouldn't add `outer_query_schema` in `sql_select_to_rex`

---

datafusion/core/src/physical_plan/file_format/chunked_store.rs

N/A
There appeared to be confusion (maybe meta confusion) about the usecase for `ChunkedStream` on https://github.com/apache/arrow-datafusion/pull/4525
Add some docstrings (adapted from @tustvold  and @metesynnada 's comments on https://github.com/apache/arrow-datafusion/pull/4525) to `ChunkedStore`
Docstring only tests
No

MINOR: add some comments about intended use of ChunkedStore

---

datafusion/common/src/dfschema.rs
datafusion/common/src/lib.rs
datafusion/common/src/table_reference.rs
datafusion/core/src/catalog/listing_schema.rs
datafusion/core/src/datasource/view.rs
datafusion/core/src/execution/context.rs
datafusion/core/tests/sql/errors.rs
datafusion/core/tests/sqllogictests/src/insert/mod.rs
datafusion/core/tests/sqllogictests/src/main.rs
datafusion/core/tests/sqllogictests/test_files/ddl.slt
datafusion/expr/src/logical_plan/plan.rs
datafusion/proto/proto/datafusion.proto
datafusion/proto/src/from_proto.rs
datafusion/proto/src/generated/pbjson.rs
datafusion/proto/src/generated/prost.rs
datafusion/proto/src/logical_plan.rs
datafusion/proto/src/to_proto.rs
datafusion/sql/src/planner.rs
datafusion/sql/src/utils.rs

Closes https://github.com/apache/arrow-datafusion/issues/4513
Closes https://github.com/apache/arrow-datafusion/issues/4531
This looks like a massive change but a substantial amount of it is generated protobuf code
See more details on https://github.com/apache/arrow-datafusion/issues/4513
TLDR is that this SQL:
```sql
❯ select * from "foo.bar";
Plan("failed to resolve schema: foo")
```
Should not be treating "foo" as a schema name
The issue is that the SQL planner was flattening multi part identifiers like `['"foo"', 'bar']` into Strings like `'"foo".bar'` and then the strings were being parsed by https://github.com/apache/arrow-datafusion/blob/740a4fa2c6ba4b85875a433bb86e5b00435a5969/datafusion/common/src/table_reference.rs#L97 which does not parse them properly (instead it simply splits …

Fix querying and defining  table / view names with period

---

datafusion/common/src/scalar.rs
datafusion/physical-expr/src/aggregate/approx_percentile_cont.rs
datafusion/physical-expr/src/aggregate/array_agg.rs
datafusion/physical-expr/src/aggregate/array_agg_distinct.rs
datafusion/physical-expr/src/aggregate/count_distinct.rs
datafusion/physical-expr/src/aggregate/median.rs
datafusion/physical-expr/src/aggregate/sum_distinct.rs

Arrow now offers `size` methods for `DataType` and `Field`, so these TODOs can be fixed.
\-
Improve `size`/memory usage calculations within DF.
Include `Field` and `DataType` into size calcuations.
\-
Size calculations are more accurate.

fix: remove TODOs linked to arrow#3147

---

datafusion-cli/Cargo.lock
datafusion/core/Cargo.toml

re #4460 
When updating DataFusion in IOx I noticed a new `sqllogictest` dependency. Since this is only used for the `sqllogictest` test it can be under a `dev-dependency`
1. move sqllogictest to dev-dependencies
2. update datafusion-cli Cargo.lock
Yes, by CI 
There are fewer dependencies in DataFusion

MINOR: move sqllogictest to dev-dependencies

---

datafusion/core/tests/sql/expr.rs
datafusion/expr/src/function.rs
datafusion/physical-expr/src/datetime_expressions.rs

Closes #3096.
See #3096 
Bugfix for extract/date_part to work with functions

Fix date_part/extract functions to support now()

---

datafusion/sql/src/planner.rs

fix: remove wrong comment about `having`

---

datafusion/sql/src/planner.rs

Closes #.
After #4484 #4141 , we remove the alias in `query_to_plan()`, so we can remove it.
What's more, we can find just `subquery_to_plan` need to pass `outer_schema`.

refactor code about `query -> plan` for subqueries

---

datafusion/core/src/physical_optimizer/join_selection.rs
datafusion/core/src/physical_plan/joins/cross_join.rs
datafusion/core/src/physical_plan/planner.rs

Closes #4431 .
Yes, rename `CrossJoinExec::try_new` to `CrossJoinExec::new` and update the return type to `Self`.

Remove the schema checking when creating `CrossJoinExec`

---

datafusion/proto/src/physical_plan/mod.rs

N/a
https://github.com/apache/arrow-datafusion/pull/4432 had a logical conflict (and I didn't recheck it)
First master CI faillure: https://github.com/apache/arrow-datafusion/actions/runs/3657087583/jobs/6180276339
```
Checking datafusion-benchmarks v15.0.0 (/__w/arrow-datafusion/arrow-datafusion/benchmarks)
error[E0599]: no function or associated item named `try_new` found for struct `CrossJoinExec` in the current scope
--> datafusion/proto/src/physical_plan/mod.rs:560:44
|
560 |                 Ok(Arc::new(CrossJoinExec::try_new(left, right)?))
|                                            ^^^^^^^ function or associated item not found in `CrossJoinExec`
```
Fix compilation of datafusion-proto
yes

Minor: Fix logical conflict

---

datafusion/common/src/table_reference.rs
datafusion/core/src/execution/context.rs
datafusion/core/tests/sqllogictests/test_files/ddl.slt
datafusion/sql/src/planner.rs

Closes https://github.com/apache/arrow-datafusion/issues/4571
I think #4530 made error messages look much crappier. For example:
```
Table Bare \{ table: "user" \} doesn't exist.
```
I noticed this while adding errors in https://github.com/apache/arrow-datafusion/pull/4535
I would like the messages to only have the table name (not the Debug version of OwnedTableReference).
1. Improve error messages to not have Bare
2. Update tests
2. Drive by improvement to change an InternalError to an execution error
Yes
Better error messages

Remove Confusing "Bare" in does not exist messages

---

datafusion/core/tests/sql/joins.rs

Closes #.
This pr is to fix https://github.com/apache/arrow-datafusion/pull/4443#pullrequestreview-1209435138
cc @liukun4515

Minor: Add test case for reduce cross join

---

datafusion/core/src/physical_plan/joins/sort_merge_join.rs

None.
Remove the local variable `left_expr` and `right_expr` to reduce memory usage and avoid iterating twice.

Avoid materializing local varaibles when creating `sortMergeJoinExec`

---

datafusion/core/src/physical_plan/filter.rs
datafusion/physical-expr/src/expressions/binary.rs
datafusion/physical-expr/src/expressions/column.rs
datafusion/physical-expr/src/expressions/literal.rs
datafusion/physical-expr/src/physical_expr.rs

Closes #4518.
Allowing the propagation of column statistics in filter estimations theoretically unlocks all the parent estimations which in turn should benefit us greatly when dealing with nested joins.
The major change here is the new analysis context API which allows it to be attached with an expression boundaries alongside the information it already holds (column boundaries). With this in our hand, we can derive the column statistics for filter's result and all other use cases where the expression analysis used. 
The initial design was around sharing a single `&mut Context` around and returning `ExprBoundaries` as we do now, but thanks to @alamb's suggestion on [my fork](https://github.com/isidentical/arrow-datafusion/pull/5#discussion_r1023180238) we can achieve a similar thing …

Enrich filter statistics with known column boundaries

---

datafusion-cli/Cargo.lock
datafusion/common/Cargo.toml
datafusion/core/Cargo.toml
datafusion/core/tests/sqllogictests/src/insert/mod.rs
datafusion/expr/Cargo.toml
datafusion/sql/Cargo.toml
datafusion/sql/src/planner.rs

Closes https://github.com/apache/arrow-datafusion/pull/4523
re https://github.com/apache/arrow-datafusion/issues/3944
Get latest sqlparser to keep up with dependencies and get fix for https://github.com/apache/arrow-datafusion/issues/3944
1. Update dependency (thanks @dependabot!) 
2. Update code for API changes
maybe https://github.com/apache/arrow-datafusion/issues/3944 is fixed. I will make a subsequent PR with some tests to cover that case

Update sqlparser requirement from 0.27 to 0.28

---

datafusion/core/tests/sql/group_by.rs
datafusion/sql/src/planner.rs

Part of #4556 .
having just use expr in groupby/aggr
```sql
pg
-- create
CREATE TABLE EMPLOYEE (
empId INTEGER PRIMARY KEY,
name TEXT NOT NULL,
dept TEXT NOT NULL
);
-- insert
INSERT INTO EMPLOYEE VALUES (0001, 'Clark', 'Sales');
-- fetch 
SELECT empid FROM EMPLOYEE having empid = 0;
psql:commands.sql:15: ERROR:  column "employee.empid" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: SELECT empid FROM EMPLOYEE having empid = 0;
^
```

bugfix: just allow having use expr in `groupby` or `aggr`

---

datafusion/core/tests/sql/select.rs
datafusion/expr/src/logical_plan/plan.rs
datafusion/sql/src/planner.rs

Closes #4550
Convert a Prepare Logical Plan into a Logical Plan with all params replaced with values
. Recursively walk the logical plan and its expressions to find and replace Placeholders with corresponding values\
. Add corresponding tests
Yes
Not yet until this is integrated into physical plan

feat: prepare logical plan to logical plan without params/placeholders

---

datafusion/expr/src/utils.rs
datafusion/sql/src/planner.rs

None
Related to pr #4137
Generate a  logical plan for query :
`SELECT TRY_CAST(SUM(age) AS FLOAT) FROM person`
**Expected plan:**
```
Projection: TRY_CAST(SUM(person.age) AS Float32)
Aggregate: groupBy=[[]], aggr=[[SUM(person.age)]]
TableScan: person
```
**Actual plan:**
```
Projection: SUM(person.age)
Aggregate: groupBy=[[]], aggr=[[SUM(person.age)]]
TableScan: person
```
The try_cast expression is dropped.
Yes.
No.

Preserve the TryCast expression in columnize_expr

---

datafusion/core/tests/sql/udf.rs
datafusion/sql/Cargo.toml
datafusion/sql/src/planner.rs

Draft as it builds on https://github.com/apache/arrow-datafusion/pull/4553
re https://github.com/apache/arrow-datafusion/pull/4553
https://github.com/apache/arrow-datafusion/pull/4553 adds a dependency that will slow down `cargo test -p datafusion-sql` as now the rest of datafusion must be compiled to run the tests
1. Move the `udaf_as_window_func` from `datafusion-sql` to sql_integration (which already depends on sql core)
Yes
No

Minor: Remove datafusion-core dev dependency from datafusion-sql

---

datafusion/common/src/column.rs
datafusion/expr/src/expr_fn.rs
datafusion/expr/src/logical_plan/builder.rs
datafusion/sql/src/planner.rs

~Draft as it builds on https://github.com/apache/arrow-datafusion/pull/4534~
N/A
Less cloning is better
Allow `subquery_alias` and `subquery_alias_owned` to take an existing `String` rather than always copying  it
No

minor: Remove more clones from the planner 

---

datafusion/core/src/catalog/information_schema.rs
datafusion/core/src/datasource/mod.rs
datafusion/core/src/datasource/streaming.rs
datafusion/core/src/physical_plan/mod.rs
datafusion/core/src/physical_plan/streaming.rs

Relates to #3777
Whilst working on #3777 I discovered somewhat to my surprise that the work of computing system tables is actually done eagerly in `SchemaProvider::table`. This is at best surprising
Adds a `StreamingTable` that is akin to `MemTable` but streaming, and then uses this to implement the system tables.

Lazy system tables

---

datafusion/core/src/physical_plan/file_format/avro.rs
datafusion/core/src/physical_plan/file_format/csv.rs
datafusion/core/src/physical_plan/file_format/file_stream.rs
datafusion/core/src/physical_plan/file_format/json.rs
datafusion/core/src/physical_plan/file_format/parquet.rs

Closes #4533
Reduces the coupling between ParquetExec and ObjectStore

Remove ObjectStore from FileStream (#4533)

---

datafusion/sql/src/parser.rs

None. This is a follow-up of #4262.
I found there were some cases in the `parser.rs` where we made the `Keyword`s which have been provided by the `sqlparser`. So I remove them and use the `Keyword` in `sqlparser` instead.

Remove the function `consume_token` from the parser

---

datafusion/optimizer/src/common_subexpr_eliminate.rs
datafusion/optimizer/src/decorrelate_where_exists.rs
datafusion/optimizer/src/decorrelate_where_in.rs
datafusion/optimizer/src/eliminate_cross_join.rs
datafusion/optimizer/src/eliminate_filter.rs
datafusion/optimizer/src/eliminate_limit.rs
datafusion/optimizer/src/eliminate_outer_join.rs
datafusion/optimizer/src/filter_null_join_keys.rs
datafusion/optimizer/src/inline_table_scan.rs
datafusion/optimizer/src/propagate_empty_relation.rs
datafusion/optimizer/src/push_down_filter.rs
datafusion/optimizer/src/push_down_limit.rs
datafusion/optimizer/src/push_down_projection.rs
datafusion/optimizer/src/rewrite_disjunctive_predicate.rs
datafusion/optimizer/src/scalar_subquery_to_join.rs
datafusion/optimizer/src/single_distinct_to_groupby.rs
datafusion/optimizer/src/subquery_filter_to_join.rs
datafusion/optimizer/src/type_coercion.rs
datafusion/optimizer/src/unwrap_cast_in_comparison.rs

add `try_optimize()` for all rules.

---

datafusion/core/tests/sql/subqueries.rs
datafusion/expr/src/logical_plan/plan.rs
datafusion/expr/src/utils.rs
datafusion/optimizer/src/type_coercion.rs

Doesn't close any, but is related to #4370.
While working on #4370 I've discovered that we don't optimize expressions within `TableScan` nodes.
Include `TableScan` expressions within the logical optimization.
See plan change in `tpch_q22_correlated`.
Better optimized plans.

fix: run logical optimizer rules for `TableScan` expressions

---

datafusion-examples/examples/simple_udf.rs
datafusion/core/src/execution/context.rs
datafusion/core/src/physical_plan/file_format/json.rs
datafusion/core/tests/sql/mod.rs
datafusion/core/tests/sql/udf.rs
datafusion/proto/src/bytes/mod.rs
datafusion/proto/src/lib.rs
datafusion/proto/src/physical_plan/mod.rs

Signed-off-by: Ruihang Xia <waynestxia@gmail.com>
NAN
Change the API for `register_*` (like `register_udf`) in `SessionContext`. Relax the share requirement from `&mut self` to `&self`. Because the actual state is wrapped in a `RwLock` (`state: Arc<RwLock<SessionState>>`), it's unnecessary to require `&mut self` for `SessionContext` itself.
Relax the share requirement from `&mut self` to `&self`.
No need I suppose. 
Yes, this is API change.

refactor: relax the signature of register_* in SessionContext

---

datafusion-examples/examples/custom_datasource.rs
datafusion-examples/examples/dataframe.rs
datafusion-examples/examples/deserialize_to_struct.rs
datafusion-examples/examples/flight_server.rs
datafusion/core/src/dataframe.rs
datafusion/core/src/datasource/view.rs
datafusion/core/src/execution/context.rs
datafusion/core/src/scheduler/mod.rs
datafusion/core/tests/dataframe.rs
datafusion/core/tests/dataframe_functions.rs
datafusion/core/tests/sql/select.rs

Closes #4621
Part of #4349 
Relates to #4617 
* Avoids unnecessary clones and memory allocations
* More idiomatic
* Fits into a broader story to rely less on interior mutability (#4617)

Make DataFrame API consuming (#4621)

---

datafusion-examples/examples/rewrite_expr.rs
datafusion/core/tests/user_defined_plan.rs
datafusion/optimizer/src/common_subexpr_eliminate.rs
datafusion/optimizer/src/decorrelate_where_exists.rs
datafusion/optimizer/src/decorrelate_where_in.rs
datafusion/optimizer/src/eliminate_cross_join.rs
datafusion/optimizer/src/eliminate_filter.rs
datafusion/optimizer/src/eliminate_limit.rs
datafusion/optimizer/src/eliminate_outer_join.rs
datafusion/optimizer/src/filter_null_join_keys.rs
datafusion/optimizer/src/inline_table_scan.rs
datafusion/optimizer/src/optimizer.rs
datafusion/optimizer/src/propagate_empty_relation.rs
datafusion/optimizer/src/push_down_filter.rs
datafusion/optimizer/src/push_down_limit.rs
datafusion/optimizer/src/push_down_projection.rs
datafusion/optimizer/src/rewrite_disjunctive_predicate.rs
datafusion/optimizer/src/scalar_subquery_to_join.rs
datafusion/optimizer/src/simplify_expressions/simplify_exprs.rs
datafusion/optimizer/src/single_distinct_to_groupby.rs
datafusion/optimizer/src/subquery_filter_to_join.rs
datafusion/optimizer/src/test/mod.rs
datafusion/optimizer/src/type_coercion.rs
datafusion/optimizer/src/unwrap_cast_in_comparison.rs

Related to https://github.com/apache/arrow-datafusion/pull/4619

FOLLOWUP: remove `optimize()`

---

datafusion/optimizer/src/unwrap_cast_in_comparison.rs

part of https://github.com/apache/arrow-datafusion/issues/3031
Closes https://github.com/apache/arrow-datafusion/issues/3031

unwrap_cast_in_comparison.rs: support unint <-> decimal

---

datafusion/core/src/physical_plan/aggregates/hash.rs

\-
Just found a bunch of CPU-cycles spent in `clone` for large aggregations that involve strings. Seems that we don't need to clone that much data.
A bit more data moving instead of cloning.
```console
❯ cargo bench -p datafusion --bench aggregate_query_sql -- --baseline avoid_hash_group_scalarvalue_copy
aggregate_query_no_group_by 15 12
time:   [681.31 µs 682.55 µs 683.93 µs]
change: [-1.3475% -0.9347% -0.4997%] (p = 0.00 < 0.05)
aggregate_query_no_group_by_min_max_f64
time:   [623.32 µs 624.53 µs 625.77 µs]
change: [-1.5852% -1.1752% -0.7877%] (p = 0.00 < 0.05)
Found 5 outliers among 100 measurements (5.00%)
1 (1.00%) low severe
1 …
```

Improve group by hash performance: avoid group-key/-state clones for hash-groupby

---

datafusion/core/benches/sql_planner.rs
datafusion/core/src/avro_to_arrow/schema.rs
datafusion/core/src/physical_plan/file_format/mod.rs
datafusion/core/src/physical_plan/udaf.rs
datafusion/expr/src/field_util.rs
datafusion/optimizer/src/push_down_filter.rs
datafusion/optimizer/src/single_distinct_to_groupby.rs
datafusion/physical-expr/src/aggregate/approx_distinct.rs
datafusion/physical-expr/src/aggregate/approx_percentile_cont.rs
datafusion/physical-expr/src/aggregate/array_agg.rs
datafusion/physical-expr/src/aggregate/array_agg_distinct.rs
datafusion/physical-expr/src/aggregate/average.rs
datafusion/physical-expr/src/aggregate/correlation.rs
datafusion/physical-expr/src/aggregate/count.rs
datafusion/physical-expr/src/aggregate/count_distinct.rs
datafusion/physical-expr/src/aggregate/covariance.rs
datafusion/physical-expr/src/aggregate/grouping.rs
datafusion/physical-expr/src/aggregate/median.rs
datafusion/physical-expr/src/aggregate/min_max.rs
datafusion/physical-expr/src/aggregate/stddev.rs
datafusion/physical-expr/src/aggregate/sum.rs
datafusion/physical-expr/src/aggregate/sum_distinct.rs
datafusion/physical-expr/src/aggregate/tdigest.rs
datafusion/physical-expr/src/aggregate/variance.rs
datafusion/physical-expr/src/type_coercion.rs
datafusion/sql/src/planner.rs

fix `cargo clippy` warning

---

datafusion-examples/examples/rewrite_expr.rs
datafusion/core/src/execution/context.rs
datafusion/core/tests/user_defined_plan.rs
datafusion/optimizer/README.md
datafusion/optimizer/src/common_subexpr_eliminate.rs
datafusion/optimizer/src/decorrelate_where_exists.rs
datafusion/optimizer/src/decorrelate_where_in.rs
datafusion/optimizer/src/eliminate_cross_join.rs
datafusion/optimizer/src/eliminate_filter.rs
datafusion/optimizer/src/eliminate_limit.rs
datafusion/optimizer/src/eliminate_outer_join.rs
datafusion/optimizer/src/filter_null_join_keys.rs
datafusion/optimizer/src/inline_table_scan.rs
datafusion/optimizer/src/lib.rs
datafusion/optimizer/src/optimizer.rs
datafusion/optimizer/src/propagate_empty_relation.rs
datafusion/optimizer/src/push_down_filter.rs
datafusion/optimizer/src/push_down_limit.rs
datafusion/optimizer/src/push_down_projection.rs
datafusion/optimizer/src/rewrite_disjunctive_predicate.rs
datafusion/optimizer/src/scalar_subquery_to_join.rs
datafusion/optimizer/src/simplify_expressions/simplify_exprs.rs
datafusion/optimizer/src/single_distinct_to_groupby.rs
datafusion/optimizer/src/subquery_filter_to_join.rs
datafusion/optimizer/src/test/mod.rs
datafusion/optimizer/src/type_coercion.rs
datafusion/optimizer/src/unwrap_cast_in_comparison.rs
datafusion/optimizer/src/utils.rs
datafusion/optimizer/tests/integration-test.rs

Make OptimizerConfig a trait (#4631) (#4638)

---

datafusion/optimizer/src/eliminate_limit.rs
datafusion/optimizer/src/optimizer.rs

Closes #4613 .
Currently, we must do optimize recursively in each rules, which is troubled.
It make it's a little hard for putting some rule into optimizer.
avoid every rule must recursive children in optimizer
And I modify the `eliminate_limit` as an example.
When `apply_order` is None, it's completely compatible with original behavior.

Optimizer: avoid every rule must recursive children in optimizer

---

datafusion-examples/examples/custom_datasource.rs
datafusion/core/src/dataframe.rs
datafusion/core/src/execution/context.rs

DataFrame owned SessionState

---

datafusion/core/src/datasource/listing/table.rs
datafusion/core/src/datasource/mod.rs
datafusion/proto/src/physical_plan/from_proto.rs

Closes #4323.
Even in the cases where none of the files included stats/byte size information,  `get_statistics_with_limit` was generating statistics with the claims of zero rows / zero bytes. This PR fixes it to only include the number of rows when it is known.
For preserving the old relaxed behavior, this PR changes the collection to include row/byte count information when any of them are present in any of the files. If it is only present in even one file, that is enough for the listing (all the others are counted towards zero rows, which is the existing behavior). 
Yes.
No.

Fix limited statistic collection accross files with no stats

---

datafusion/core/src/physical_plan/coalesce_batches.rs

Closes #3894 (and addresses part of #3494)
Moving start of timer for elasped_compute to after input_batch has been polled for more accurate time

Fix CoalesceBatches elasped_compute metric

---

benchmarks/expected-plans/q20.txt
datafusion/core/tests/sql/subqueries.rs
datafusion/expr/src/logical_plan/plan.rs
datafusion/optimizer/src/decorrelate_where_exists.rs
datafusion/optimizer/src/decorrelate_where_in.rs
datafusion/optimizer/src/eliminate_filter.rs
datafusion/optimizer/src/eliminate_limit.rs
datafusion/optimizer/src/eliminate_outer_join.rs
datafusion/optimizer/src/filter_null_join_keys.rs
datafusion/optimizer/src/inline_table_scan.rs
datafusion/optimizer/src/propagate_empty_relation.rs
datafusion/optimizer/src/scalar_subquery_to_join.rs
datafusion/optimizer/src/test/mod.rs

Closes #.
Remove recursion in optimizer rules. and utilize the optimizer traverse the plan tree.

remove recursion in optimizer rules

---

datafusion/expr/src/expr.rs
datafusion/optimizer/src/utils.rs

Closes #4681.
As detailed in the issue, there was a problem with `create_name()` being called on `Expr::Wildcard` in the `type_coercion` and `unwrap_cast_in_comparison` optimization rules, which eventually led to these optimization rules not being applied.
In the issue description, two different solutions were suggested. Here, I chose the first one, i.e. to add one line to the `name_for_alias` function, ensuring that we individualize the `Expr::Wildcard` case, and naming the expression in a reasonable way (e.g. "*") instead of calling `display_name()`.
No tests were added in this PR, but we tested the code with the suggested change on our own and the bug is solved, since the warnings are gone and the optimization rules are applied as intended.
We still want to hear what you think about …

Add line that prevents display_name from being called on Wildcard

---

datafusion/core/src/dataframe.rs
datafusion/core/src/datasource/datasource.rs
datafusion/core/src/datasource/empty.rs
datafusion/core/src/datasource/file_format/avro.rs
datafusion/core/src/datasource/file_format/csv.rs
datafusion/core/src/datasource/file_format/json.rs
datafusion/core/src/datasource/file_format/mod.rs
datafusion/core/src/datasource/file_format/parquet.rs
datafusion/core/src/datasource/listing/table.rs
datafusion/core/src/datasource/memory.rs
datafusion/core/src/datasource/streaming.rs
datafusion/core/src/execution/context.rs
datafusion/core/src/physical_plan/file_format/avro.rs
datafusion/core/src/physical_plan/file_format/json.rs
datafusion/core/src/physical_plan/file_format/parquet.rs
datafusion/core/src/test_util.rs
datafusion/core/tests/parquet/page_pruning.rs
datafusion/core/tests/row.rs
datafusion/core/tests/sql/information_schema.rs
datafusion/core/tests/statistics.rs

Part of #4349
Relates to #4617 
Relates to #3909 #3886
#4427 pushed `ConfigOptions` into `ParquetFormat`, however, the resulting `Arc<Mutex<ConfigOptions>>` is tricky to work with (#3886) and has unclear mutation semantics (#4617). 
Pushes `SessionState` into `FileFormat` which in turn will allow removing `ConfigOptions` from `ParquetFormat` and instead just fetching the configuration from the passed in `SessionState`

Push SessionState into FileFormat (#4349)

---

datafusion/optimizer/src/eliminate_filter.rs
datafusion/optimizer/src/eliminate_outer_join.rs
datafusion/optimizer/src/filter_null_join_keys.rs
datafusion/optimizer/src/push_down_filter.rs
datafusion/optimizer/src/push_down_limit.rs
datafusion/optimizer/src/rewrite_disjunctive_predicate.rs
datafusion/optimizer/src/single_distinct_to_groupby.rs
datafusion/optimizer/src/subquery_filter_to_join.rs
datafusion/optimizer/src/test/mod.rs
datafusion/optimizer/src/unwrap_cast_in_comparison.rs

FOLLOWUP: remove more recursion in optimizer rules.

---

datafusion-examples/examples/rewrite_expr.rs
datafusion/core/src/physical_plan/planner.rs
datafusion/expr/src/logical_plan/plan.rs
datafusion/optimizer/src/common_subexpr_eliminate.rs
datafusion/optimizer/src/decorrelate_where_exists.rs
datafusion/optimizer/src/decorrelate_where_in.rs
datafusion/optimizer/src/eliminate_cross_join.rs
datafusion/optimizer/src/eliminate_outer_join.rs
datafusion/optimizer/src/optimizer.rs
datafusion/optimizer/src/push_down_filter.rs
datafusion/optimizer/src/push_down_projection.rs
datafusion/optimizer/src/rewrite_disjunctive_predicate.rs
datafusion/optimizer/src/scalar_subquery_to_join.rs
datafusion/optimizer/src/single_distinct_to_groupby.rs
datafusion/optimizer/src/subquery_filter_to_join.rs
datafusion/proto/src/logical_plan/mod.rs

Closes #.
- add `#[non_exhaustive]` for LogicalPlan to avoid to bypass `try_new/new()` to build plan directly and 
- cleanup filter `predicate() input()`

Avoid to bypass `try_new/new()` to build plan directly and cleanup filter

---

datafusion/core/src/datasource/file_format/csv.rs

re https://github.com/apache/arrow-datafusion/issues/3658
I spent some time messing with this code as part of review https://github.com/apache/arrow-datafusion/pull/4661#issuecomment-1363824177 trying to make it easier to read, so I figured I would put it up for review
Move some code around into functions with comments to avoid double nested loops
no
cc @Jefffrey

Minor: refactor streaming CSV inference code

---

datafusion/core/tests/sqllogictests/test_files/nullif.slt
datafusion/expr/src/nullif.rs
datafusion/physical-expr/src/expressions/nullif.rs

Closes #4205 .
Adding more options to call `NULLIF` in terms of signatures and inputs.
1) Calling arrow `compute::nullif` without intermediate type checking
2) String typed inputs now allowed as `NULLIF` arguments
3) Added support for literal as first argument for both Scalar-Array and Scalar-Scalar cases
Unit tests for nullif_func added

Extended datatypes & signatures support for `NULLIF` function

---

datafusion/core/tests/sql/timestamp.rs
datafusion/expr/src/type_coercion/binary.rs
datafusion/expr/src/type_coercion/functions.rs
datafusion/physical-expr/src/planner.rs

Closes #4644 
Closes #4672.
Add cast between Date and Timestamp

Implement cast between Date and Timestamp

---

datafusion/core/src/physical_plan/common.rs

Create writer with `arrow::ipc::IPCWriteOptions`

---

datafusion/optimizer/src/extract_equijoin_expr.rs
datafusion/optimizer/src/extract_equijoin_predicate.rs
datafusion/optimizer/src/lib.rs
datafusion/optimizer/src/optimizer.rs
datafusion/sql/src/planner.rs

Closes #4710.
See #4710
* Remove the usage of `extract join keys` in sql planner.
* Add `ExtractEquijoinPredicate` to optimizer.
Yes.

Move the extract_join_keys to optimizer

---

datafusion/core/tests/parquet/filter_pushdown.rs

Signed-off-by: Ruihang Xia <waynestxia@gmail.com>
Closes #.
I found this test is very slow (the last one `datafusion::parquet_exec parquet::filter_pushdown::single_file`):
```
PASS [   0.061s]        datafusion-benchmarks::bin/tpch tests::run_q5
PASS [   0.091s]        datafusion-benchmarks::bin/tpch tests::run_q21
PASS [   0.082s]        datafusion-benchmarks::bin/tpch tests::run_q9
PASS [   0.056s]          datafusion::user_defined_plan normal_query_without_schemas
PASS [   0.047s]          datafusion::user_defined_plan topk_plan
PASS [   0.081s]          datafusion::user_defined_plan normal_query
PASS [   0.015s]          datafusion::user_defined_plan topk_query
PASS [   0.120s]        datafusion-benchmarks::bin/tpch tests::run_q7
PASS [   0.112s]    datafusion::user_defined_aggregates …
```

refactor: parallelize `parquet_exec` test case `single_file`

---

datafusion/core/src/dataframe.rs
datafusion/core/src/datasource/view.rs
datafusion/core/src/execution/context.rs
datafusion/physical-expr/src/execution_props.rs

Closes #4747
Closes #4626 
This works around #4747 by ensuring that the execution time is already set by the time a user has obtained a `SessionState`.

Set query_execution_start_time on snapshot from SessionContext (#4747)

---

datafusion/expr/src/type_coercion/binary.rs
datafusion/expr/src/type_coercion/functions.rs
datafusion/physical-expr/src/planner.rs

from the https://github.com/apache/arrow-datafusion/pull/4726#issuecomment-1365869414
If we want to compare the timestamp with date, we just need to add logic in `type_coercion`, and don't need to do type coercion in the physical phase.

revert some code for #4726 / remove unnecessary coercion in physical plans

---

datafusion/physical-expr/src/planner.rs

As pointed out by @liukun4515  on https://github.com/apache/arrow-datafusion/pull/4726 https://github.com/apache/arrow-datafusion/pull/4726#issuecomment-1365869414 type coercion is not needed during physical planning
cc @comphead 
~Code is uneeded~
Avoid confusion about design in the future
~Remove uneeded code~
Add comments about coercion in the physical planner
Yes, all existing tests pass
No

Minor: comments about coercion in physical planner

---

benchmarks/src/bin/tpch.rs
datafusion/core/src/dataframe.rs
datafusion/core/src/execution/context.rs
datafusion/core/tests/custom_sources.rs
datafusion/core/tests/parquet/mod.rs
datafusion/core/tests/sql/aggregates.rs
datafusion/core/tests/sql/explain.rs
datafusion/core/tests/sql/explain_analyze.rs
datafusion/core/tests/sql/mod.rs
datafusion/core/tests/sql/projection.rs
datafusion/core/tests/sql/udf.rs
datafusion/core/tests/tpcds_planning.rs

Part of #4617
Follow on to #4679 
These methods are very easy to accidentally misuse, and end up planning or optimizing against a different state than used for previous phases. Deprecating them will hopefully encourage correct usage of these APIs

Deprecate SessionContext physical plan methods (#4617)

---

benchmarks/src/bin/tpch.rs
datafusion/core/src/datasource/listing/table.rs
datafusion/core/src/datasource/listing_table_factory.rs
datafusion/core/src/execution/context.rs
datafusion/core/src/physical_plan/file_format/avro.rs
datafusion/core/src/physical_plan/file_format/json.rs
datafusion/core/src/physical_plan/file_format/parquet.rs
datafusion/core/src/physical_plan/planner.rs
datafusion/core/tests/parquet/page_pruning.rs

Closes #.
Exposing members publicly is a very strong and broad API commitment, which makes it very difficult to make non-breaking changes, as it is very hard to reason about how the type is being used.
Makes the members of `SessionState` private

Make SessionState members private

---

datafusion/core/tests/sql/joins.rs
datafusion/expr/src/utils.rs
datafusion/optimizer/src/simplify_expressions/simplify_exprs.rs

Closes #4754.
The `SimplifyExpressions` will give an alias to the result if the new name and old name is not same. For the rebuild of equijoin in from_plan, we assume the simplified result of a binary equality expression is still a binary equality expression, this is not correct and may result in the failure of `SimplifyExpressions` rule.
Add alias check for equijoin in from_plan.
Yes.

Add alias check for equijoin in from_plan

---

benchmarks/expected-plans/q11.txt
benchmarks/expected-plans/q15.txt
benchmarks/expected-plans/q16.txt
benchmarks/expected-plans/q17.txt
benchmarks/expected-plans/q18.txt
benchmarks/expected-plans/q2.txt
benchmarks/expected-plans/q20.txt
benchmarks/expected-plans/q22.txt
benchmarks/src/bin/tpch.rs
datafusion/core/tests/sql/subqueries.rs
datafusion/optimizer/src/alias.rs
datafusion/optimizer/src/decorrelate_where_in.rs
datafusion/optimizer/src/optimizer.rs
datafusion/optimizer/src/scalar_subquery_to_join.rs
datafusion/optimizer/tests/integration-test.rs

Closes #3437
Closes #3791
(although these were actually fixed by https://github.com/apache/arrow-datafusion/pull/4038)
Having mutable state associated with `OptimizerConfig` complicates implementing it for `SessionState`. I originally hoped to implement `OptimizerConfig` for `DataFrame`, but this would have required churning all the planning machinery and so I decided against this.  
There is one implication potentially worth highlighting with this change, as the state is now associated with the `OptimizerRule` and not an `OptimizerContext` created for the call to `SessionState::optimize`, state will now bleed across calls whereas it previously wouldn't. In some ways this is better, as previously calling `optimize` twice could theoretically result in an alias collision, but I thought it …

Move subquery alias assignment onto rules

---

datafusion/core/src/physical_plan/planner.rs
datafusion/core/src/physical_plan/union.rs
datafusion/core/tests/sql/union.rs

Closes #4677.
When creating `UnionExec` from `LogicalPlan::Union`, the schema of the top plan is ignored. This could cause errors when the top level schema doesn't match the child schema. (see the example in #4677)
```sql
❯ create table t as select 1 as a;
0 rows in set. Query took 0.014 seconds.
❯ select count(*) from (select a from t union all select a from t);
Internal("create_physical_expr expected same number of fields, got got Arrow schema with 1  and DataFusion schema with 0")
```
```sql
❯ create table t as select 1 as a;
0 rows in set. Query took 0.014 seconds.
❯ select count(*) from (select a from t union all select a from t);
+-----------------+
| COUNT(UInt8(1)) |
+-----------------+
| 2               |
+-----------------+
1 row in …
```

Take the top level `schema` into account when creating `UnionExec`

---

datafusion/core/tests/tpcds_planning.rs
datafusion/sql/src/planner.rs

Closes https://github.com/apache/arrow-datafusion/issues/4065 from @andygrove 
Closes https://github.com/apache/arrow-datafusion/issues/4728 from @Jefffrey 
Also reported by @maxburke  in slack
Debug builds are overflowing the stack causing pain and suffering for users. 
1. Extract several parts of the body of `SqlToRel::sql_expr_to_logical_expr` into separate functions
The reason this reduces stack size in debug builds is explained in the "Technical Backstory" heading of https://github.com/apache/arrow-datafusion/pull/1047
Covered by existing coverage
None intended (other than avoiding stack overflows)

Fix Stack overflow in sql planning in debug builds

---

datafusion/core/tests/sql/expr.rs

Closes #4528.
Nanoseconds tests were disabled because of sqlparser didn't support nanoseconds. Current 29 sql parser allows tests to run
Tests for nanosecond for date_part/extract
Yes
No

Uncomment nanoseconds tests after sql parser upgrade

---

datafusion/core/src/physical_plan/file_format/parquet.rs
datafusion/core/src/physical_plan/file_format/parquet/page_filter.rs
datafusion/core/src/physical_plan/file_format/parquet/row_groups.rs

support byte array for decimal in parquet page and row group filters

---

datafusion/core/tests/tpcds_planning.rs
datafusion/sql/src/planner.rs

Re https://github.com/apache/arrow-datafusion/issues/4065 from @andygrove 
This is a follow on to https://github.com/apache/arrow-datafusion/pull/4779 which reduced the stack space needed to plan in debug builds. This PR minimizes the stack required as much as I know how. 
Special case BinaryOp (see comments for explination)
Yes (existing + new tests)
No

Minimize stack space required to plan deeply nested binary expressions

---

datafusion/physical-expr/src/crypto_expressions.rs

Closes #4781.
Makes `datafusion-physical-expr` compatible with `blake3/traits-preview` feature.
No

 Make datafusion-physical-expr compatible with blake3/traits-preview feature.

---

datafusion/sql/src/planner.rs

~Draft as it builds on https://github.com/apache/arrow-datafusion/pull/4779~
re https://github.com/apache/arrow-datafusion/issues/4065
I am trying to make the code in `sql_expr_to_logical_expr` as uniform as possible to avoid reintroducing issues like https://github.com/apache/arrow-datafusion/issues/4065
Extract a few more functions
Existing tests 
No

Minor: Refactor some sql planning code into functions

---

datafusion/core/src/catalog/listing_schema.rs

- Append trailing slash to table paths  if they are directories
Is similar to #4204 - inability to use an object store listing for a table schema.
However this PR addresses tables generated from `ListingSchemaProvider`.
I would like to set up an object store (s3) where each directory maps to a single table/schema, with the contents being made up of all files (parquet) inside the directory. By registering the schema provider like:
```rust
Arc::new(ListingSchemaProvider::new(
String::from(format!("s3://{bucket_name}")),
"".into(),
Arc::new(ListingTableFactory::default()),
s3.clone(),
String::from("PARQUET"),
false,
));
```
Then if there is a folder in the bucket, such as `userdata`, attempting to query against `userdata` table causes the s3 client to 404, as the provider creates …

fix: ListingSchemaProvider directory paths (related: #4204)

---

datafusion/core/src/execution/context.rs
datafusion/core/src/physical_optimizer/coalesce_batches.rs
datafusion/core/src/physical_optimizer/repartition.rs

Closes #4806
This moves interpretation of the config options into the rules themselves, which avoids issues where the option is altered after creation of the `SessionState` by the `SessionContext`

Enable PhysicalOptimizerRule lazily (#4806)

---

benchmarks/src/bin/tpch.rs
benchmarks/src/tpch.rs

Closes #.
The tbl format is of the form
```
a|b|c|
```
Note the trailing `|`. Interpreting this as CSV therefore adds an additional trailing column, currently the CSV reader just ignores this. However, with arrow 30 the reader now complains if you give it a schema that doesn't match the file. The changes in this PR work around this
Adds an additional `__placeholder` column to the schema when reading from a tbl file, this can then be projected out. This was a quick way to workaround this issue without polluting the general codebase with support for what appears to be a TPCH specific data format?

Handle trailing tbl column in TPCH benchmarks

---

datafusion/sql/src/planner.rs

None.
As the columns referenced in `expr` are always fewer than the columns in `schemas`, we don't need to include all the columns in our hash map.
Pass current tests.
No.

rewrite the function `ensure_any_column_reference_is_unambiguous`

---

datafusion/core/src/physical_plan/aggregates/mod.rs
datafusion/core/src/physical_plan/aggregates/row_hash.rs
datafusion/physical-expr/src/hash_utils.rs

For #2723.
This has two effects:
- **wider feature support:** We now use the V2 aggregator for all group-column types. The arrow row format support is sufficient for that. V1 will only be used if the aggregator itself doesn't support V2 (and these are quite a few at the moment). We'll improve on that front in follow-up PRs.
- **more speed:** Turns out the arrow row format is also faster (see below).
Use arrow row format for group keys instead of DF row format.
Perf results (mind the noise in the benchmarks that are actually not even touched by this code change):
```text
❯ cargo bench -p datafusion --bench aggregate_query_sql -- --baseline issue2723a-pre
...
Running benches/aggregate_query_sql.rs (target/release/deps/aggregate_query_sql-fdbe5671f9c3019b)
aggregate_query_no_group_by 15 12 …
```

feat: use arrow row format for hash-group-by

---

datafusion/core/src/physical_plan/aggregates/mod.rs
datafusion/core/src/physical_plan/repartition.rs
datafusion/core/tests/memory_limit.rs

Closes #4816.
Unbounded channels in `RepartitionExec` may easily lead to OOMs, even when the user has a memory manager limit configured.
Memory accounting. Some drive-by clean-ups.
New test called `oom`.
Better memory accounting.

fix: account for memory in `RepartitionExec`

---

datafusion/core/tests/sqllogictests/test_files/aggregate.slt
datafusion/physical-expr/src/aggregate/stddev.rs
datafusion/physical-expr/src/aggregate/variance.rs

Closes #4843.
Rather than crash when performing a variance-based aggregation on a single value, follow Postgres' semantics:
- `var`/`stddev` of single element is `NULL`
- `var_pop`/`stddev_pop` of single element is 0
There's documentation of this behavior in Snowflake (https://docs.snowflake.com/en/sql-reference/functions/stddev.html), and it's what Postgres does, but in searching briefly I haven't found this behavior described in the Postgres docs.
I added a pair of sqllogictest tests for the one and two element cases.
Queries that used to crash when aggregating single values with variance-based aggregations will no longer crash.

Update variance/stddev to work with single values

---

datafusion-cli/Cargo.lock
datafusion-cli/Cargo.toml
datafusion-cli/src/catalog.rs
datafusion-cli/src/lib.rs
datafusion-cli/src/main.rs
datafusion/core/src/execution/context.rs

Closes #4580 .
See #4580
Follow up #4581 
- Add `DynamicFileCatalog`, `DynamicFileCatalogProvider`, `DynamicFileCatalogProvider`, which can try to create a `ListingTable` when table is not found.
- Register `DynamicFileCatalog` in `SessionContext`
Manually tested.
```
$ cargo run
Finished dev [unoptimized + debuginfo] target(s) in 0.19s
Running `target/debug/datafusion-cli`
DataFusion CLI v15.0.0
❯ select * from '../parquet-testing/data/alltypes_tiny_pages.parquet' limit 10;
+-----+----------+-------------+--------------+---------+------------+-----------+--------------------+-----------------+------------+-------------------------+------+-------+
| id  | bool_col | tinyint_col | smallint_col | int_col | bigint_col | float_col | double_col         | date_string_col | string_col | …
```

support `select .. FROM 'parquet.file'` in datafusion-cli

---

docs/source/user-guide/cli.md

re https://github.com/apache/arrow-datafusion/issues/4580
The feature added in https://github.com/apache/arrow-datafusion/pull/4838 is so cool -- we need to let our users know!
Update `datafusion-cli` documentation
N/A
Just docs

Document ability to select directly from files in datafusion-cli

---

datafusion/optimizer/src/push_down_projection.rs

Closes #4667
During PushDownProjection optimization, it does not properly account for distinct, as it will attempt to push directly through the distinct, from input plan:
```sql
Projection: data.id
Distinct:
Projection: data.id, data.data
TableScan: data
```
Will generate output plan:
```sql
Projection: data.id
Distinct:
TableScan: data projection=[id]
```
Where it has inadvertently removed the `data.data` projection during the push down and hence leading to incorrect distinct behaviour.
Properly handle distincts during recursion in PushDownProjection, to 'restart' the traversal with all required columns (derived from schema of the distinct) rather than using the input required columns.
After fix, the above plan output will instead be:
```sql
Projection: data.id
Distinct:
TableScan: data …
```

Fix push_down_projection through a distinct

---

datafusion/core/tests/sql/window.rs
datafusion/physical-expr/src/aggregate/average.rs

Closes #4845.
Adds an implementation of `retract_batch` to `AvgAccumulator` that is identical to the implementation for `SumAccumulator`.
I added `AVG` to a couple of existing tests that previously failed with `"Retractable Accumulator hasn't been implemented..."` error.
`AVG` can now be used in window expressions with custom frames.

Implement retract_batch for AvgAccumulator

---

datafusion/core/tests/sql/window.rs
datafusion/physical-expr/src/aggregate/stddev.rs
datafusion/physical-expr/src/aggregate/variance.rs

Follow on to https://github.com/apache/arrow-datafusion/pull/4846 for `var`, `var_pop`, `stddev`, and `stddev_pop`. 
The actual `retract_batch` function was already implemented, but it looks like the `create_sliding_accumulator` implementations weren't added previously so it wasn't possible to use these aggregate functions in window expressions that use custom frames.
The test added in effc4728912684f63b2e4ce837ae1b1816796480 will fail until https://github.com/apache/arrow-datafusion/pull/4847 is merged and this branch is updated.
I'll mark this is draft until then.
`var`, `var_pop`, `stddev`, and `stddev_pop` will now work in window expressions that use custom frames rather than raising an error.

Support using var/var_pop/stddev/stddev_pop in window expressions with custom frames

---

datafusion/core/tests/sqllogictests/test_files/aggregate.slt
datafusion/physical-expr/src/aggregate/correlation.rs
datafusion/physical-expr/src/aggregate/covariance.rs

Follow up on #4843 (or #4314)
Covariance function also has an issue with single row inputs processing and cases when inputs contain NULL values
Covariance function now able to process single row and pairs of (NULL, NOT NULL) arguments. As a consequence of proper handling NULLs in Variance, Correlation function now requires additional input filtering - in case one input field is NULL, we should filter out whole record (second field actually) to keep Sttdev (as part of correlation) calculation relevant.
Fixed/added tests for corresponding accumulators and sqllogictests
covar_samp/covar_pop/corr functions don't return Errors in case of single row input or (null, not null) argument values

Covariance single row input & null skipping

---

datafusion/sql/src/relation/join.rs
datafusion/sql/tests/integration_test.rs

Closes #117
Support for planning sql natural join, which simply gets turned into a USING join based on the common columns (checked via name only), and if no common columns found then becomes a cross join.
Added to sql integration_test.rs

Support for SQL Natural Join

---

datafusion/core/src/physical_optimizer/repartition.rs
datafusion/core/src/physical_plan/limit.rs
datafusion/core/src/physical_plan/mod.rs
datafusion/core/src/scheduler/pipeline/execution.rs

Related to #4686 
https://github.com/apache/arrow-datafusion/pull/4691 from @mustafasrepo  made the `relies_on_input` redundant in favor of the more general required_input_ordering
Remove `relies_on_input`
No, though it is an API change

Remove unused ExecutionPlan::relies_input_order (has been replaced with `required_input_ordering`)

---

datafusion/common/src/column.rs

None.
While debugging #4854 I got a bit confused because the docs of `normalize_col_with_schemas` and `normalize_col` just state "uses `Column::normalize_with_schemas` but the latter just says "internal implementation" and I had to read throw the code to understand what "normalize" actually means.
Docs for `Column::normalize_with_schemas`.
\-
Better docs.

docs: improve `Column::normalize_with_schemas` docs

---

Cargo.toml
datafusion/substrait/Cargo.toml
datafusion/substrait/src/consumer.rs
datafusion/substrait/src/producer.rs
datafusion/substrait/src/serializer.rs
datafusion/substrait/tests/roundtrip.rs
datafusion/substrait/tests/serialize.rs

Follows on from https://github.com/apache/arrow-datafusion/pull/4543
Updates the crate to build against the version of DataFusion in the repo.
I could not add it to the workspace due to https://github.com/apache/arrow-datafusion/issues/4880 so there will be a follow-on PR to complete the integration at some point
Yes, existing tests

Update datafusion-substrait crate to build against repo version of DataFusion

---

datafusion/core/src/physical_plan/repartition/distributor_channels.rs
datafusion/core/src/physical_plan/repartition/mod.rs

Closes #4865.
The repartition operation had an unbounded buffer. This is not required in all cases and is even counterproductive since it will drive the input nodes to completion while potentially starving the output nodes and while filling up the buffers up to the memory limit (at which point it will just bail out).
A somewhat more sophisticated channel construct (distribution channels) that are only unbounded as long as at least one channel is empty. In practice (= for any reasonable repartition config) this will NOT lead to unbounded memory usage since virtually all partitions should eventually receive some data.
- all existing tests pass
- extensive tests for the distribution construct
Improved scheduling for the repartition operation.

refactor: improve repartition buffering

---

datafusion/core/src/physical_optimizer/dist_enforcement.rs
datafusion/core/tests/sql/joins.rs

Closes #4873.
See #4873 for a failing example and some preliminary investigation.
The issue is in the EnforceDistribution physical optimizer (the query from the issue works without it).  After looking at this for a while, I think I see what's going on.  Normally, the column expressions for a group by have indices that correspond to the schema of the input operation. But for the case of a partial aggregation, these indices need to be updated to correspond to the schema of the partial aggregation instead of the input.
This make sense to me, and it fixes the query, but this is the first time I've looked at the Physical optimizer so someone who's more familiar with that side of things should definitely take a look before merging this.
I added a test case based on the query reported in the …

Fix column indices in EnforceDistribution optimizer in Partial AggregateMode

---

datafusion/expr/src/logical_plan/plan.rs

Closes #4898 
See issue description.
Yes. A new test is included to test the changes.
The users who enable tracing of LogicalPlan might see additional subqueries in the logs.

fix: Visit subqueries in `Expr::Alias`

---

datafusion-examples/examples/rewrite_expr.rs
datafusion/core/tests/user_defined_plan.rs
datafusion/optimizer/src/common_subexpr_eliminate.rs
datafusion/optimizer/src/eliminate_cross_join.rs
datafusion/optimizer/src/push_down_filter.rs
datafusion/optimizer/src/utils.rs

Update  `optimize_children` to return `Result<Option<LogicalPlan>>`

---

datafusion/expr/src/expr_visitor.rs
datafusion/expr/src/logical_plan/plan.rs
datafusion/optimizer/src/push_down_filter.rs

Inspired by the bug in https://github.com/apache/arrow-datafusion/pull/4900 and  discussion with @avantgardnerio  on https://github.com/apache/arrow-datafusion/pull/4701#discussion_r1069131341
I realized while reading https://github.com/apache/arrow-datafusion/pull/4900 there were likely other places in Expr that could have subqueries so there may be other bugs lurking similar to https://github.com/apache/arrow-datafusion/issues/4898
However, there was no good way to walk all expressions in a LogicalPlan other than to call `LogicalPlan::expressions()` which clones them all
1. Add LogicalPlan::inspect_expressions that calls a function on each expression
2. Rewrite subquery traversal to use this this function

Refactor: `Add LogicalPlan::observe_expressions` to walk expressions

---

datafusion/substrait/src/consumer.rs
datafusion/substrait/tests/roundtrip.rs
datafusion/substrait/tests/serialize.rs

Part of https://github.com/apache/arrow-datafusion/issues/4897
As suggested by @nseekhao, given that to_substrait_rel() takes LogicalPlan and returns Substrait Rel, it would be better if from_subtrait_rel() takes Substrait Rel and returns LogicalPlan rather than DataFrame.
Note that this was originally https://github.com/datafusion-contrib/datafusion-substrait/pull/35

[Substrait] Change API to return LogicalPlan instead of DataFrame

---

datafusion/core/src/physical_plan/aggregates/mod.rs
datafusion/core/src/physical_plan/limit.rs
datafusion/optimizer/src/push_down_filter.rs

Closes #4715.
With these introduced row count info, for a SQL similar to the following pattern, the `JoinSelection` optimizer rule will successfully be able to choose the `CollectLeft` partition mode rather than the `Partitioned`, which reduces the query duration running on Ballista from 7.5s to 4.5s for a data set of 1.3 billion rows.
```
select column_of_high_cardinality,
sum(measure_1)
from table_0
where column_of_high_cardinality in
(select column_of_high_cardinality
from table_0
group by column_of_high_cardinality
order by sum(measure_0) desc
limit 1000)
group by column_of_high_cardinality
```

Refine the statistics estimation for the limit and aggregate operator

---

datafusion/core/src/physical_optimizer/repartition.rs
datafusion/core/src/physical_plan/mod.rs
datafusion/core/tests/sql/explain_analyze.rs

Fixes https://github.com/apache/arrow-datafusion/issues/4883
the fix is small logic fix to a condition. The rest of this PR is documentation and tests 
The repartition optimizer pass is destroying a pre-existing sort order by repartitioning the data. The plan is actually producing correct answers (which is good) because the sort is added back afterwards, but it was doing so by resorting the data :(
There is much more backstory on https://github.com/apache/arrow-datafusion/issues/4883
yes, new tests
Without this change the tests fail like (added a repartition above the parquet exec)
```
---- physical_optimizer::repartition::tests::repartition_does_not_destroy_sort_more_complex stdout ----
thread 'physical_optimizer::repartition::tests::repartition_does_not_destroy_sort_more_complex' …
```

Do not repartition inputs whose sort order is required

---

datafusion/core/src/execution/context.rs

Closes #4920.
When using the Datafusion in the distributed engine, Ballista, a session will be created at the server side. While for the client, it will get a session id as the response. Then the client and the server will communicate with each other with specifying the session id as the key for the session state. Therefore, it's necessary to create a session state with specifying a session id at the Ballista client side.

Make it able to specify a session id for SessionState

---

datafusion/core/src/physical_optimizer/sort_enforcement.rs

re https://github.com/apache/arrow-datafusion/issues/4943
Rationale: I am working on a bug related to sort enforcement and wanted to add a new test and the current structure was very hard to do without a lot of copy / paste.
refactor repetition in sort_enforcement.rs tests into a macro
Only tests
No -- there is no intended change in behavior

Reduce redundancy in sort_enforcement tests

---

datafusion/core/Cargo.toml

NA
object_store 0.5.3 adds support of environment variable alias for similar meaning. e.g. either `aws_endpoint` or `aws_endpoint_url`
https://github.com/apache/arrow-rs/pull/3436
It is a nice improvement to simplify downstream application config. e.g. https://github.com/roapi/roapi/pull/241/files#r1070219697
No

Upgrade object_store from 0.5.0 to 0.5.3

---

datafusion-cli/src/object_storage.rs

NA
It is a minor improvement. From Google Cloud Console, the schema for GCS is `gs://`
https://cloud.google.com/storage/docs/gsutil#syntax
support `gs://` same as `gcs://`
yes, unit test
No

Support gs:// as GCS schema

---

datafusion/core/src/execution/context.rs

Co-authored-by: yangzhong <yangzhong@ebay.com>
Part of https://github.com/apache/arrow-datafusion/issues/4948
This PR is against the `maint-16.x` branch. We want to release a patch release to allow Ballista to upgrade to DataFusion 16.x
Make it possible to set session id.
Not really, no.
No

[maint-16.x] Make it able to specify a session id for SessionState (#4933)

---

datafusion/core/src/physical_optimizer/sort_enforcement.rs
datafusion/core/src/physical_plan/union.rs

Closes https://github.com/apache/arrow-datafusion/issues/4943
See https://github.com/apache/arrow-datafusion/issues/4943 -- basically the issue is that `EnforceSorting` pass is adding an unecessary sort to `UnionExec` at some times
1. Implement `UnionExec::maintains_input_order` as suggested by @mustafasrepo https://github.com/apache/arrow-datafusion/issues/4943#issuecomment-1385360298
2. Add test
Yes
Bug fix (though I don't know if any SQL queries would be affected by this)

Do not resort inputs to `UnionExec` if they are already sorted

---

datafusion/core/src/physical_plan/planner.rs
datafusion/expr/src/lib.rs
datafusion/expr/src/logical_plan/mod.rs
datafusion/expr/src/logical_plan/plan.rs
datafusion/expr/src/utils.rs
datafusion/optimizer/src/common_subexpr_eliminate.rs
datafusion/optimizer/src/push_down_projection.rs
datafusion/proto/src/logical_plan/mod.rs
datafusion/sql/src/select.rs
datafusion/sql/src/statement.rs
datafusion/sql/tests/integration_test.rs

Closes #4901.
- A new `LogicalPlan` enum variant called `WriteRel` and modeled after Substrait
- Changes to the planner to allow it to generate the new plans
- Integration tests for insert/update/delete
Yes
Only if the user is a programmer using DataFusion as a library, in which case more ASTs will convert to LogicalPlans.

Add insert/update/delete to LogicalPlan and add SQL planner support

---

README.md

Closes #.
Fix typos I introduced in https://github.com/apache/arrow-datafusion/pull/4903

Minor: comma engineering in Readme

---

datafusion/core/src/physical_optimizer/dist_enforcement.rs
datafusion/core/tests/sql/joins.rs

Backport https://github.com/apache/arrow-datafusion/pull/4878 onto `maint-16.x` branch.
cc @andygrove

Maint-16.x Backport: #4878

---

datafusion/core/src/physical_plan/planner.rs
datafusion/expr/src/logical_plan/plan.rs
datafusion/proto/src/logical_plan/mod.rs
datafusion/sql/tests/integration_test.rs

Follow on to https://github.com/apache/arrow-datafusion/pull/4902 from @avantgardnerio 
There are some messages / display strings that appear to still reference an older version of the code
Update the display name to `Dml` everywhere
existing coverage

Minor: Make messages consistent for LogicalPlan::Dml

---

datafusion/substrait/Cargo.toml
datafusion/substrait/src/consumer.rs
datafusion/substrait/src/producer.rs
datafusion/substrait/src/serializer.rs
datafusion/substrait/tests/roundtrip.rs

Closes #4950.
Bump to latest `substrait` crate release.
Dependabot's bump commit (#4961) and a commit that handles the rename of the `protobuf` module to `proto`.
Yes.
No.

Upgrade to Substrait 0.4.0

---

datafusion/core/src/execution/context.rs

Closes #4957.
Splitting planning and parsing.
Transitively, yes.
New API methods, no breaking changes.

Expose `sql_to_statement` and `statement_to_plan` on `SessionState`

---

datafusion/core/src/physical_plan/planner.rs

NA
Propagation error from the extension planner back to the user
Code change + tests
Yes

Propagate planning error back to user

---

datafusion/common/src/error.rs

Closes #4970
More clear error handling by providing a more specific DataFusionError enum for Substrait
Modifications to DataFusionError enum

Add DataFusionError::Substrait variant to DataFusionError enum

---

datafusion/expr/src/expr.rs
datafusion/expr/src/expr_schema.rs
datafusion/expr/src/logical_plan/plan.rs
datafusion/proto/src/logical_plan/from_proto.rs
datafusion/proto/src/logical_plan/to_proto.rs
datafusion/sql/src/expr/mod.rs
datafusion/sql/src/expr/value.rs
datafusion/sql/src/statement.rs
datafusion/sql/tests/integration_test.rs

Closes #4683.
1. Code in sql_to_rel to infer parameter type
2. A test for a particular type of statement with parameters
3. A method to get the inferred types
[x]
FlightSQL implementers can respond with types.
I'm opening this as a draft PR to discuss general approach. If folks are on board with it, I'll add support for a bunch more statement types and more tests.

Infer prepared statement parameter types

---

datafusion/common/src/error.rs
datafusion/common/src/lib.rs
datafusion/core/src/error.rs
datafusion/core/src/physical_plan/joins/utils.rs

Closes #4981
I used approach with errors wrapped to `Arc` (I see it's common pattern in arrow & datafusion), because it should be shareable. 
I also created separate type alias for that
I've added test which failed before these changes.

fix(4981): incorrect error wrapping in `OnceFut`

---

datafusion/core/src/datasource/listing/table.rs
datafusion/core/src/execution/context.rs

N/A
The discussion on https://github.com/apache/arrow-datafusion/pull/4908 with @saikrishna1-bidgely made it clear to me that having more documentation about ListingTable and what it can do would help people;
1. Add a doc example for creating ListingTables
2.  Add some hints in the docs for `SessionContext::read_parquet`, etc pointing there
Yes they are doc tests
better docs

Minor: Document how to create `ListingTables`

---

datafusion-cli/src/command.rs
datafusion-cli/src/functions.rs
datafusion-cli/src/main.rs
datafusion-cli/src/print_format.rs
datafusion/common/src/column.rs
datafusion/common/src/dfschema.rs
datafusion/common/src/error.rs
datafusion/common/src/scalar.rs
datafusion/core/src/avro_to_arrow/arrow_array_reader.rs
datafusion/core/src/physical_plan/common.rs
datafusion/core/src/physical_plan/display.rs
datafusion/core/src/physical_plan/joins/utils.rs
datafusion/core/src/physical_plan/mod.rs
datafusion/core/tests/sql/explain_analyze.rs
datafusion/core/tests/sqllogictests/src/error.rs
datafusion/core/tests/sqllogictests/src/insert/mod.rs
datafusion/core/tests/user_defined_plan.rs
datafusion/expr/src/expr_visitor.rs
datafusion/expr/src/logical_plan/plan.rs
datafusion/optimizer/src/decorrelate_where_in.rs

Closes #.
This is technically a breaking change, as there are some rare cases where this will now result in a compile error as it cannot infer the return type.

Allow overriding error type in DataFusion Result

---

.github/workflows/dev.yml
docs/source/user-guide/sql/data_types.md
docs/source/user-guide/sql/scalar_functions.md

N/A
https://arrow.apache.org/datafusion/user-guide/sql/data_types.html is out of date, as we discovered while working on docs for IOx: https://github.com/influxdata/docs-v2/pull/4700
1. Update supported type
2. Add note about `arrow_typeof` function
N/A (they are docs)
Yes, docs

minor: Update data type support documentation

---

datafusion/common/src/bisect.rs
datafusion/common/src/lib.rs
datafusion/common/src/utils.rs
datafusion/physical-expr/src/window/aggregate.rs
datafusion/physical-expr/src/window/built_in.rs
datafusion/physical-expr/src/window/nth_value.rs
datafusion/physical-expr/src/window/partition_evaluator.rs
datafusion/physical-expr/src/window/sliding_aggregate.rs
datafusion/physical-expr/src/window/window_frame_state.rs

Closes #4979. Makes progress on #4904.
During range calculation for window frames, we can use linear search instead of bisect. Since we know that table is already sorted and we would progress only in one direction. Linear search is amortized constant (When window frame boundaries are static). Hence this version is more optimal than current bisect implementation (where search complexity is log(n)). This change decreases overall window range calculation complexity from `O(n*log(n))` to `O(n)`.
Existing tests verify window range calculation correctness. Unit tests for `linear_search` is also added. We also compared time elapsed during Window result calculation for the query
```sql
SELECT SUM(a) OVER(ORDER BY a RANGE BETWEEN 10 PRECEDING AND 10 FOLLOWING) FROM t1;
```
. Time comparison …

Add support for linear range calculation in WINDOW functions

---

datafusion/physical-expr/src/expressions/binary.rs

N/A
We saw this message in our logs:
```
Error while planning query: Internal error: The type of Dictionary(Int32, Utf8) = Utf8 of binary physical should be same. This was likely caused by a bug in DataFusion's code and we would welcome that you file an bug report in our issue tracker
```
It was not clear what operator is being used. 
Print out the debug version of Operator rather than display for a better message
No
No

Minor: improve internal error message

---

datafusion/sql/src/select.rs

When I was browsing the code, I realized that the comment I wrote before is no longer useful.
Because the cross join -> inner join optimization has been moved to the optimizer.

Minor: Remove invalid comments

---

datafusion/core/tests/sqllogictests/test_files/aggregate.slt
datafusion/physical-expr/src/aggregate/average.rs

Closes https://github.com/apache/arrow-datafusion/issues/5007
Answer is incorrect
I started seeing this error when I upgraded IOx to https://github.com/influxdata/influxdb_iox/pull/6639 -- though I could reproduce the issue via datafusion cli even before that. 
AVG nulls is null
yes
yes

AVG(null) is NULL (not zero)

---

datafusion/core/src/physical_plan/aggregates/row_hash.rs

~Draft as it builds on https://github.com/apache/arrow-datafusion/pull/4924~
re https://github.com/apache/arrow-datafusion/issues/4973
Follow on to https://github.com/apache/arrow-datafusion/pull/4924 work from @mustafasrepo and @ozankabak 
As we prepare to improve group by performance even more, we will be working on this code going forward.
There are several TODOs in the group by hash code as well as some out of date comments that make it harder to work with. Given the thinking / plans to improve this code it is important it remains relatively easy to work with
Since I had all the code paged in anyways as I was reviewing https://github.com/apache/arrow-datafusion/pull/4924 I figured I would add my comments here
1. Remove extra level of unwrapping in `GroupedHashAggregateStreamInner`
2. …

Simplify GroupByHash implementation (to prepare for more work)

---

datafusion/common/src/error.rs

Closes https://github.com/apache/arrow-datafusion/issues/4991
In IOx (and in DataFusion) we often want to know what the root cause of an error is (e.g was it a bug or was it a resources exhausted). ArrowError can wrap other errors with Arrow::External (and DataFusion has something similar) but there is no easy way to get at the source of the error to walk the chain without knowing all the possible types that may be present
I want a generic way to walk up the error stack
1. Implement `std::error::Error::source()` for `DataFusionError`
2. Make `DataFusionError::find_root` less specific (uses source() rather than so much checking for arrow)
Yes, covered by (some quite gnarly) existing tests
Better standard support

Implement `std::error::Error::source()` for `DataFusionError`, make `DataFusionError::find_root` more generic

---

datafusion/sql/src/expr/value.rs
datafusion/sql/tests/integration_test.rs

Closes #5005 .
As suggested by  @alamb in #5005, we are catching the parameter `$__timeTo` and returning `DatafusionError::Plan` error
* check the param to match `__timeTo` 
* created a test in 
yes
Specific error message when this parameter is used.
----
P.S.: This is my first commit to Datafusion. I hope this is ok. Tell me, if I misunderstood the issue. Thanks for the great project!

Check placeholder  __timeTo and return Datafusion::Plan error

---

datafusion/sql/src/statement.rs
datafusion/sql/tests/integration_test.rs

Closes #4976.
Type inference for `insert into values ($1)` style queries.
Yes, with an integration test.
Type inference should work on more parameterized queries.

Infer values for inserts

---

.github/workflows/rust.yml
datafusion/core/Cargo.toml
datafusion/core/tests/path_partition.rs
datafusion/core/tests/sql/select.rs
datafusion/physical-expr/Cargo.toml
datafusion/physical-expr/src/expressions/binary.rs

Closes #4386
Release build of datafusion-cli on master
```
________________________________________________________
Executed in   65.44 secs    fish           external
usr time   17.23 mins  521.00 micros   17.23 mins
sys time    0.48 mins    0.00 micros    0.48 mins
```
With this feature
```
________________________________________________________
Executed in   48.18 secs    fish           external
usr time   16.46 mins  567.00 micros   16.46 mins
sys time    0.48 mins    0.00 micros    0.48 mins
```
Adds a `dictionary_expressions` feature that gates `arrow/dyn_cmp_dict` and `arrow/dyn_arith_dict`. I vacillated a bit on the naming and whether this should enable `arrow/dyn_arith_dict` but figured as this is just plumbing features through, and does not alter the actual DataFusion code, …

Add dictionary_expresions feature (#4386)

---

datafusion/core/src/physical_plan/file_format/avro.rs
datafusion/core/src/physical_plan/file_format/csv.rs
datafusion/core/src/physical_plan/file_format/file_stream.rs
datafusion/core/src/physical_plan/file_format/json.rs
datafusion/core/src/physical_plan/file_format/parquet.rs

When we executing explain analyze select * from tablexxx, csv/json/avro exev metrics is empty.
This bug is introduced by not implementing metrics traits in csv/json/avro.
Signed-off-by: xyz <a997647204@gmail.com>
Closes #5014
Before 
After
implementing metrics traits in csv/json/avro, add csv metrics unit test
yes
User can see metrics in csv exec

[BugFix] fix explain csv/json/avro exec can not see metrics bug

---

datafusion/sql/src/statement.rs
datafusion/sql/tests/integration_test.rs

Works-around #5046.
Described in issue 
Casts from `values` clause types to `insert` table types.
Yes, with an integration test.
No - I don't think anyone is using the `insert/update/delete` plans yet, and if they are this is probably an improvement.

Ensure insert projections are of correct type

---

datafusion/core/src/lib.rs

Closes #5036 .
While browsing the docs I have noticed some links don't work.
This PR fixes some docs links to logical plan.
I have generated the docs locally and the links now work. 
No

Update docs links to logical plans module.

---

datafusion/substrait/src/producer.rs

Part of https://github.com/apache/arrow-datafusion/issues/4897
Original PR in datafusion-substrait repo: https://github.com/datafusion-contrib/datafusion-substrait/pull/37
Quick fix to list ALL columns from source table in ReadRel base_schema.
According to Substrait [documentation](https://substrait.io/relations/logical_relations/#read-properties), the base_schema (Direct Schema) property should contain all columns BEFORE projection or emit/hiding is applied.
No .. this is applying a PR that was already merged in the original repo prior to us accepting the code donation here, so I am just trying to get those changes re-applied

[Substrait] ReadRel. Get column names from TableScan source

---

datafusion/substrait/src/consumer.rs
datafusion/substrait/src/producer.rs
datafusion/substrait/tests/roundtrip.rs

Part of https://github.com/apache/arrow-datafusion/issues/4897
Original PR: https://github.com/datafusion-contrib/datafusion-substrait/pull/38/files
Re-applying PR from datafusion-substrait repo

Improve join type support in substrait

---

datafusion/sql/src/statement.rs
datafusion/sql/tests/integration_test.rs

Closes #5052.
Removal of `BTreeMap`
Yes, they were covered by a previous test.
Fields will be returned in a new order. This should be okay because no one is using update yet, and if they were they must have been tolerating random orders.

Retain schema order in projection

---

dev/release/README.md
dev/release/publish_homebrew.sh

Closes #5043.
Fix the homebrew publish script:
1. Change the script so that git parallel fetch works on both Linux and macOS and doesn't error out if the OS is neither.
2. Fix a typo.
3. Add documentation so that everyone can run the script.

Fix homebrew publish script

---

datafusion/core/src/physical_plan/limit.rs

Closes #5064
Bug fix. I found this when working with the Coralogix which pushes down limits to fully to the scan (so the batch size almost always equals the limit).
Change `<=` to `<` 🥳

Fix limit when size of batch to poll == skip/fetch value

---

datafusion/sql/Cargo.toml
datafusion/sql/src/statement.rs
datafusion/sql/tests/integration_test.rs

Closes #5068.
Ensure that all assignment targets are actual columns of the target table, to prevent typos being silently swallowed up.
During logical planning of the `UPDATE` statement try to fetch each of the referenced assignment columns.
Yes, there is a new 3-case test now.
Not really; Datafusion is read-only, so the only difference is what error is shown (`SchemaError(FieldNotFound` from the logical planning as opposed to `Internal("Unsupported logical plan: Dml")` from the physical planning phase). The real user-facing changes will be in the projects that use Datafusion as a framework and also [support writes](https://www.splitgraph.com/blog/seafowl-time-travel).

Validate assignment target column existence for UPDATE statements

---

datafusion/sql/src/statement.rs
datafusion/sql/tests/integration_test.rs

Closes #5058
The changes fix a bug resulting in double-quoted identifiers in SQL query plans.
The changes affect logical plan creation in `datafusion/sql/src/statement.rs`
The PR includes an integration test for the `CREATE SCHEMA` SQL statement.
User queries with quoted identifiers will work as expected due to this change.

Fix CREATE SCHEMA schema name double quoting issue.

---

datafusion/core/src/datasource/listing/table.rs
datafusion/core/src/execution/context.rs
datafusion/core/src/execution/options.rs
datafusion/core/tests/sql/parquet.rs
datafusion/core/tests/sql/window.rs

The `read_csv`, `read_parquet`, `read_json` and `read_avro` methods can not use a single method to read the locations.
Closes #5024.
This will make for a simpler code in #4908.
Implemented a new trait `ReadOptions`. The code for method `to_listing_options` has been moved from the respective structs into this trait. Also the code from `read_csv/json/avro/parquet` to get the resolved schema has been moved here in `get_resolved_schema`.
Once this trait is implemented, the remaining code in the methods `read_csv/json/avro/parquet` is the same and has been moved to a private method.
This is only a refactor and the existing tests should cover the refactored code.
No

Implemented a ReadOptions trait for cleaner code.

---

datafusion/substrait/tests/roundtrip.rs

Closes https://github.com/apache/arrow-datafusion/issues/4897
The test that failed used a function that compared an **optimized** plan to an **unoptimized** plan.
While at it, also changed from using the deprecated `SessionContext::optimize` to the recommended `SessionState::optimize`.
Modified the `roundtrip_fill_na()` function used by the failed test to compare optimized plan to optimized plan. Test now passes.
Yes
No

Optimize returned plan in roundtrip_fill_na function

---

datafusion/substrait/src/consumer.rs
datafusion/substrait/src/producer.rs
datafusion/substrait/tests/roundtrip.rs

Modified test
Part of https://github.com/apache/arrow-datafusion/issues/4897
Original PR: https://github.com/datafusion-contrib/datafusion-substrait/pull/40
Applying PRs that were already merged in the original repo
- Add Substrait producer and consumer support for NULL literals of types:
- `INT8`, `INT16`, `INT32`
- `DECIMAL128`
- Add tests
Yes
No

Add NULL literal support for decimal and integers

---

datafusion/substrait/Cargo.toml
datafusion/substrait/src/consumer.rs
datafusion/substrait/src/producer.rs
datafusion/substrait/tests/roundtrip.rs

Closes https://github.com/apache/arrow-datafusion/issues/5084
Support for `null-equals-null` joins as described in https://github.com/apache/arrow-datafusion/issues/5084.
- Support `null-equals-null` joins in both producer and consumer
- Support for accepting `ScalarValue::UInt8` in the producer. (Encoded as `i32` since Substrait does not support unsigned integers)
Yes
No

Add null-equals-null join support

---

datafusion/expr/src/expr_rewriter.rs
datafusion/expr/src/expr_rewriter/order_by.rs
datafusion/expr/src/lib.rs

Related to https://github.com/apache/arrow-datafusion/issues/4854
I want to make the code easier to work with as part of the fix and breaking the PR into smaller parts will help with review
1.  Move the code into its own module
2. Add unit tests
No functional change is intended 
Yes
No

Minor: extract sort col rewrite into its own module, add unit tests

---

datafusion/common/Cargo.toml
datafusion/jit/src/jit.rs

N/A
N/A
- update cranelift-module
- convert `ModuleError` to `DatafusionError`

chore: update cranelift-module

---

datafusion/optimizer/src/utils.rs

Closes #.
In #4826, I forgot to remove some unused methods. Remove them now.

Minor: remove unused methods in datafusion/optimizer/src/utils.rs

---

README.md

Thanks a ton to @francis-du  for adding the info about [GreptimeDB](https://github.com/GreptimeTeam/greptimedb) in #4768 . We noticed that the name was written as Greptime DB, but the correct name is actually GreptimeDB.

Typo of greptimedb

---

.github/workflows/rust.yml
docs/source/user-guide/expressions.md

ci: don't trigger rust ci for doc changes

---

datafusion/common/src/config.rs
datafusion/sql/src/statement.rs
datafusion/sql/tests/integration_test.rs

Closes #5078.
Enable logical planning of `INSERT` statements without the optional target column list.
If there are no parsed target fields in the `INSERT` statement default to using all the fields from the table's schema.
Yes.
Only to users that use Datafusion as a framework where write statements are supported.

Insert target columns empty fix

---

datafusion/proto/src/logical_plan/from_proto.rs
datafusion/proto/src/physical_plan/from_proto.rs

Closes https://github.com/apache/arrow-datafusion/issues/4424.
This pr is following: https://github.com/apache/arrow-datafusion/pull/4446, https://github.com/apache/arrow-datafusion/pull/4458 and https://github.com/apache/arrow-datafusion/pull/5102. And I think this is the last pr for closing the issue https://github.com/apache/arrow-datafusion/issues/4424, because it clears all remaining `&Option<T>` type.
Replace `&Option<T>` with `Option<&T>`.
Pass the original test.
May change the api.

Replace &Option<T> with Option<&T>

---

datafusion/core/src/physical_plan/windows/window_agg_exec.rs
datafusion/core/tests/sql/window.rs

Closes [#5090](https://github.com/apache/arrow-datafusion/issues/5090).
When cardinality of column is low, and target partition is high, we may get empty record batches in `WindowAggExec`. In these cases we receive an error as described in the [#5090](https://github.com/apache/arrow-datafusion/issues/5090). This PR adds handling for empty batches to fix the bug.
A simple change to fix the bug.
Yes, new tests are added.
No.

Bug fix: Empty Record Batch handling

---

datafusion/substrait/tests/roundtrip.rs

Closes https://github.com/apache/arrow-datafusion/issues/5134
DataFusion already turns `Expr::InList` into a series of `Eq` joined by `Or` (in an optimized plan). So explicit implementation is NOT needed to support `Expr::InList` (as of DataFusion version 17.0). Thus, only a test is added to confirm the validity of the support.
Simple `SELECT ... FROM ... WHERE c1 IN (<list>);` test.
Yes
No

Add in-list test

---

datafusion/common/src/config.rs
datafusion/core/src/execution/context.rs
datafusion/core/tests/sqllogictests/src/engines/datafusion/create_table.rs
datafusion/core/tests/sqllogictests/src/engines/datafusion/insert.rs
datafusion/core/tests/sqllogictests/test_files/ddl.slt
datafusion/sql/src/expr/identifier.rs
datafusion/sql/src/planner.rs
datafusion/sql/src/relation/mod.rs
datafusion/sql/src/statement.rs
datafusion/sql/tests/integration_test.rs

Closes #4551.
See issue above.
- Add new field `enable_ident_normalization` in ParserOptions
- Add SqlParserOptions in ConfigOptions
Add new UT: parse_ident_normalization
Yes, users can configure this new option when parse SQL

Add option to control whether to normalize ident

---

datafusion/core/Cargo.toml
datafusion/core/tests/sqllogictests/src/engines/postgres/mod.rs
datafusion/core/tests/sqllogictests/src/engines/postgres/types.rs
datafusion/core/tests/sqllogictests/test_files/pg_compat/pg_compat_type_coercion.slt

Closes #5147.
In sqllogictest tests I could write a query for Datafusion like this one
```
select arrow_typeof(null and null), arrow_typeof(null or null);
```
I would like to write the same query for Postgres, so that not only values are checked for compatibility but also types
```
select pg_typeof(null and null), pg_typeof(null or null);
```
This pr includes handling of `regtype` results in Postgres sqllogictest client.
Github actions
Sqllogictest only

[sqllogictest] Support `pg_typeof`

---

datafusion/core/tests/sqllogictests/test_files/pg_compat/pg_compat_type_coercion.slt
datafusion/expr/src/type_coercion/binary.rs

Closes #4335.
These queries should produce a value instead of an error
```
❯ select null and null;
❯ select null or null;
```
Null comparison coercion and tests.
I made the null logical comparison produce booleans. This is the Postgres does it, and DataFusion seems to be compatible with Postgres.
Sqllogictests and unit tests
`null and null` and `null or null` would produce Boolean null value instead of an error.

Compare NULL types

---

datafusion/expr/src/type_coercion/binary.rs
datafusion/physical-expr/src/expressions/binary.rs
datafusion/physical-expr/src/expressions/binary/kernels_arrow.rs

Support arithmetic scalar operation with DictionaryArray

---

datafusion/physical-expr/src/aggregate/sum.rs

Closes #.
Fixes a TODO item in the codebase.
Fixes a TODO item in `sum` aggregation: replace the sum logic for `Decimal128` with the usage of `sum` kernel provided by `arrow-rs`, which also uses SIMD and potentially can give better performance.
Yes, with existing tests.
No

Switch to use sum kernel from arrow-rs for Decimal128

---

datafusion/core/src/physical_plan/planner.rs
datafusion/core/tests/sql/errors.rs

\--
Use the correct error type because API users may rely on that (e.g. to generate appropriate HTTP error codes).
Change some errors from `Internal` to `NotImplemented`.
SQL test, see changed test.
Improved error types.

fix: treat unsupported SQL plans as "not implemented"

---

datafusion/expr/src/type_coercion/binary.rs

Closes #5154
This change teaches DataFusion how to coerce Dictionary(_, string-like-type) to a string-like type for regex conditional expressions, so the comparison may succeed.
Updated the type coercion rules when encountering one of the regular expression operators.
Yes, new tests were added to validate the changes.
Queries that previously would fail with an error that the Dictionary type is incompatible with a regular expression condition will now succeed. IOx uses `Dictionary(Int32, Utf8)` columns for tags.
In some cases, regular expression queries succeed, such as:
```sql
SELECT usage_idle FROM cpu WHERE cpu ~ '9'
```
As the optimiser changes the filter plan from a regex conditional to a `LIKE '%9%'`, and the `LIKE` operator has additional code to coerce dictionary types: …

feat: Type coercion for Dictionary(_, _) to Utf8 for regex conditions

---

datafusion-examples/Cargo.toml
datafusion-examples/README.md
datafusion-examples/examples/flight_sql_server.rs

Closes #5139 .
Adds an example for a standalone DataFusion server that can execute queries from tools like DBeaver or DataGrid via the JDBC Driver for Arrow Flight SQL.
Just an example, and more dependencies in the datafusion-example module.
No.

add example for Flight SQL server that supports JDBC driver

---

datafusion/core/tests/sqllogictests/test_files/pg_compat/pg_compat_union.slt
datafusion/core/tests/sqllogictests/test_files/union.slt

sqllogicaltest: add cleanup and use rowsort.

---

datafusion/core/src/execution/disk_manager.rs

Closes #5186 .
DiskManager fails if the spill folder doesn't exist, that is bit annoying.
Create disk manager spill folder if doesn't exist
Test attached
No

Create disk manager spill folder if doesn't exist

---

datafusion/expr/src/logical_plan/plan.rs
datafusion/optimizer/src/type_coercion.rs
datafusion/optimizer/src/unwrap_cast_in_comparison.rs
datafusion/optimizer/src/utils.rs

minor: extract `merge_schema()` function.

---

datafusion/core/src/physical_plan/file_format/file_stream.rs

Closes #5129 
File opening is mostly IO (and may involve a bunch of sequential IO) so it can probably be parallelized well with decoding. So we should open the next file in parallel while decoding the current file in `FileStream`
I think this should be covered by existing tests
`FileStreamMetrics.time_opening` is a slightly different metric now as it won't capture time spent opening but rather time spent opening while also not concurrently decoding.

FileStream: Open next file in parallel while decoding

---

datafusion/core/src/datasource/memory.rs

The issue is close to #5178, but for `MemTable`.
1. It should be cancel-safe
2. There was an issue with join - `await` was sequential
3. There was possible to get a panic instead of Error
Existed tests are passing

fix(MemTable): make it cancel-safe and fix parallelism

---

datafusion/core/src/physical_plan/file_format/csv.rs
datafusion/core/src/physical_plan/file_format/json.rs
datafusion/core/src/physical_plan/file_format/parquet.rs

Closes #5178
Currently interruption from outside of datafusion don't stop spawned tasks and it continue to execute query.
It's very helpful to be able to restrict these methods by `timeout` or `select` for example.
It's quite hard to cover with union-tests and such test could be too flaky (any ideas are welcome). 
However all existed tests are passing successfully.

fix: make `write_csv/json/parquet` cancel-safe

---

datafusion/optimizer/src/simplify_expressions/simplify_exprs.rs

Closes #5191.
Remove use `all_schemas()`  but use the plan schema + children_merge_schema().
set `pub skip_failed_rules: bool, default = false`
Before this PR, `right_anti_filter_push_down` and `right_semi_with_alias_filter` will fail.
After this PR, they will success.
Current test can cover it (we just need to disable skip_fail)

bugfix: fix eval `nullalbe()` in `simplify_exprs`

---

datafusion/expr/src/logical_plan/plan.rs
datafusion/sql/tests/integration_test.rs

Closes #5215.
Replace parameters in scalar subqueries.
With an integration test, yes.
Scalar subqueries with parameters should work.

Replace placeholders in ScalarSubqueries

---

datafusion/common/src/table_reference.rs
datafusion/core/src/dataframe.rs
datafusion/expr/src/logical_plan/builder.rs
datafusion/expr/src/utils.rs
datafusion/sql/src/relation/join.rs
docs/source/user-guide/dataframe.md

Closes #1254
New method for DataFrame `join_on` allowing user to pass in arbitrary `Expr`'s which are AND'ed together to form the `ON` condition.
Also fix to DataFrame join to enforce ambiguity check, like how was done by SQL planner
New unit test
New method in DataFrame, doc updated

Dataframe join_on method

---

datafusion/core/src/physical_plan/planner.rs
datafusion/core/tests/sql/timestamp.rs

Closes #5217.
Part of #4685
No need, current tests can cover this problem, but it was hidden by skip_failed_rules.
set `pub skip_failed_rules: bool, default = false`
Before this PR, `cast_string_to_time` and `in_list_types_struct_literal` will fail.
After this PR, they will success.

fix: correct expected error in test

---

datafusion/expr/src/type_coercion.rs
datafusion/optimizer/src/type_coercion.rs

Closes  #5233.
Part of #4685
No need, current tests can cover this problem, but it was hidden by skip_failed_rules.
set `pub skip_failed_rules: bool, default = false`
Before this PR, `sort_on_window_null_string` will fail.
After this PR, they will success.

bugfix: fix error when `get_coerced_window_frame` meet `utf8`

---

datafusion/sql/src/select.rs

Closes #5247
No tests added. Adding tests for invalid SQL might not be desirable (considering potential surface area of invalid SQL)

Disallow SORT BY in SQL

---

datafusion/core/tests/dataframe.rs
datafusion/core/tests/sqllogictests/test_files/select.slt
datafusion/expr/src/logical_plan/builder.rs
datafusion/sql/tests/integration_test.rs

Closes #5065
Currently, if the order by column is not in select list, we will add_missing_columns to the select list.  This will lead to the bug in issue #5065.
In this pr, we modify the behaviour, for select distinct, we will throw error msg if order by expressions are not int select list.
yes 
no

[BugFix] abort plan if order by column not in select list

---

datafusion/core/tests/sqllogictests/test_files/order.slt

related to https://github.com/apache/arrow-datafusion/issues/5247
Add a small test for https://github.com/apache/arrow-datafusion/pull/5249
More tests more better
Yes

Minor: Add negative test for SORT BY

---

datafusion/expr/src/logical_plan/plan.rs

Closes #5192.
Currently, all_schema() can return schema of child of child. (due to recursively call `all_schema()`)
But, plan shouldn't get schema of child of child (or child of child of child of child ......).
It should just get info of itself and children.
For example
```sql
A join (Project (B.id = 3) -- B)
```
join shouldn't get schema of `B`.
So, I refactor this implementation, remove recursion.
Just return children schema and itself schema

refactor: correct the implementation of `all_schemas()`

---

datafusion/core/tests/sql/explain_analyze.rs
datafusion/core/tests/sqllogictests/README.md
datafusion/core/tests/sqllogictests/src/engines/conversion.rs
datafusion/core/tests/sqllogictests/src/engines/datafusion/normalize.rs
datafusion/core/tests/sqllogictests/test_files/explain.slt

Part of https://github.com/apache/arrow-datafusion/issues/4495
As part of porting window functions tests in https://github.com/apache/arrow-datafusion/pull/5199 I found there was additional work to do for normalizing explain plans. 
1. This PR ports an explain test to sqllogictest and updates the display normalization to handle it
Yes
No

Minor: port some explain test to sqllogictest, add filename normalization

---

datafusion/core/src/datasource/file_format/parquet.rs
datafusion/core/src/physical_plan/file_format/parquet.rs

Part of https://github.com/apache/arrow-datafusion/issues/5104
I am trying to write a test for https://github.com/apache/arrow-datafusion/issues/5104 and getting lost in the maze of parameters passed to `round_trip` and `round_trip_to_parquet`
It is also hard for me to evaluate which combinations of tests are covered
Move the parameters to run the roundtrip test into a structure, with better documentation
Yes
no

Minor: refactor ParquetExec roundtrip tests

---

datafusion/core/src/physical_plan/file_format/csv.rs
datafusion/optimizer/src/push_down_projection.rs

Closes #5146.
Fixing `push_down_projection` behaviour for "TableScan-only" queries -- recreation `TableScan.projection` changes column order in output plan schema, which is unacceptable for the optimizer.
Now push down projection preserves original order of projection indices, filtering out not required fields.
Added tests for optimizing scan with randomly ordered projection and optimizing projection over it.
Also added test for randomly ordered projection in CsvExec, as, at first, this issue looked suspiciously similar to #4832 (not that case -- CsvExec was working in 16-17 versions)

Preserve `TableScan.projection` order in `push_down_projection` optimizer rule

---

datafusion/core/src/datasource/object_store.rs

\-
Improves integration of `ObjectStoreUrl` w/ other code bases.
Derive the following traits for `ObjectStoreUrl`:
- `Ord`/`PartialOrd`
- `Eq`/`PartialEq`
- `Hash`
Auto-derive, no testing needed.
`ObjectStoreUrl` is better usable.

minor: derive Ord/PartialOrd/Eq/PartialEq traits for `ObjectStoreUrl`

---

datafusion/core/src/execution/context.rs

Closes #.
`catalog_list` in `SessionState` was made private in #4764. That makes `catalog_list` fixed to `MemoryCatalogList` inside: 
https://github.com/apache/arrow-datafusion/blob/c0defeb7a074d286976240a3965600a77038459a/datafusion/core/src/execution/context.rs#L1475-L1480
If we are to provide another implementation for `catalog_list`, we can't.
Adds a new constructor for `SessionState` for injecting custom implementor for `catalog_list`.

Set `catalog_list` from outside for `SessionState`.

---

datafusion/core/src/datasource/file_format/parquet.rs
datafusion/core/src/physical_optimizer/pruning.rs
datafusion/core/src/physical_plan/file_format/parquet.rs
datafusion/core/src/physical_plan/file_format/parquet/page_filter.rs

Closes https://github.com/apache/arrow-datafusion/issues/5104
See https://github.com/apache/arrow-datafusion/issues/5104
I want to turn on page index pushdown for all queries. I can't do that if it causes errors for queries across parquet files where the schema is not the same
Fix a bug (I will describe inline)
Yes
IN PROGRESS -- testing against https://github.com/apache/arrow-datafusion/pull/5099
Less bugs

Support page skipping / page_index pushdown for evolved schemas

---

datafusion/core/src/dataframe.rs
datafusion/core/tests/dataframe.rs
datafusion/expr/src/logical_plan/builder.rs
datafusion/sql/src/query.rs

Closes #5255
In pr #5132, we added a check that order by expr list must exist in distinct expr list, this restriction may be over eager for dataframe user, sometimes they may want to do this for some particular reasons.
In this pr, we relax the check for distinct, order by for dataframe, this check will only be triggered for sql planner.
yes
no

[fix][plan] relax the check for distinct, order by for dataframe

---

datafusion/proto/proto/datafusion.proto
datafusion/proto/src/generated/pbjson.rs
datafusion/proto/src/generated/prost.rs
datafusion/proto/src/physical_plan/mod.rs

Serialize preserve_partitioning in SortExec

---

datafusion/core/src/lib.rs
docs/source/user-guide/example-usage.md

This is a minor document fix, does not introduce new features or fix bugs.
Examples are provides for both SQL query and DataFrame API respectively, and they should be semantically consistent.
The DataFrame API example on this page calls `filter` methods on `df`, but the DataFrame API one does not contains relevant part of `WHERE` expression, this could be confusing for newcomers.
This PR adds `WHERE` express to SQL query examples to match API syntax expression.
Code blocks should covered by doctest.
No.

Make SQL query consistent with API syntax expression in code examples

---

datafusion/common/src/dfschema.rs
datafusion/expr/src/utils.rs
datafusion/optimizer/src/decorrelate_where_in.rs

Closes #.
The `check_all_column_from_schema` is used to check if columns are all in the schema.
It is based on `index_of_column`. Giving the column, `index_of_column` has three result:
1. No such field, return FieldNotFound error.
2. Find only one field, return this field.
3. Find one more field, return Ambiguous reference error.
`1` and `3` will return Error. In `check_all_column_from_schema`, we need distinguish these two, but currently we don't do it. This pr will fix it.
* Refactor `index_of_column_by_name` to return `Result<Option<usize>>`.
* Add `is_column_from_schema`, and `check_all_column_from_schema` calls it.
Yes

Fix the potential bug of check_all_column_from_schema

---

datafusion/proto/proto/datafusion.proto
datafusion/proto/src/generated/pbjson.rs
datafusion/proto/src/generated/prost.rs
datafusion/proto/src/physical_plan/from_proto.rs
datafusion/proto/src/physical_plan/mod.rs
datafusion/proto/src/physical_plan/to_proto.rs

This is required in order for `ballista` to serialise the indexing expressions for nested lists. Otherwise, `ballista` cannot execute any SQL that contains indexing expressions.
Closes https://github.com/apache/arrow-datafusion/issues/5323
Add missing protobuf serialisation for `GetIndexedFieldExpr` that is required when running queries that index nested structures.
Add protobuf serialisation for `GetIndexedFieldExpr` and a unit test.
Yes
No

Add missing protobuf serialisation functionality GetIndexedFieldExpr.

---

datafusion/core/src/execution/context.rs

Closes #5317 
As described in #5317 , accessors are need in new `SessionContext` api.
Changes are dead simple 
N/A

feat: add accessor to SessionContext fields for ContextProvider impl

---

datafusion-cli/src/exec.rs

Closes #.
Better user experience
Instead of:
```
❯ select not_a_column;
SchemaError(FieldNotFound { field: Column { relation: None, name: "not_a_column" }, valid_fields: [] })
```
it's
```
❯ select not_a_column;
Schema error: No field named 'not_a_column'.
```
datafusion-cli uses the nicely formatted error messages already available rather than debug format for errors

MINOR: nicer error messages for cli, use display format rather than debug

---

datafusion/optimizer/src/propagate_empty_relation.rs
datafusion/optimizer/src/push_down_filter.rs
datafusion/optimizer/src/push_down_limit.rs

minor: remove useless `.get()`

---

datafusion/common/src/dfschema.rs
datafusion/optimizer/src/utils.rs
datafusion/optimizer/tests/integration-test.rs

Closes #5334.
Part of #4685.
This PR fix tpcds_logical_q8.

bugfix: fix tpcds_logical_q8 ambiguous name.

---

datafusion/optimizer/src/inline_table_scan.rs

Closes #.
In origin rule, we will discard all `projection` in `table_scan`.
This isn't a best choice. we can remain it.
generate new `projection` plan accord by original `projection` in `table_scan`.

generate new projection plan in inline_table_scan instead of discarding

---

datafusion/core/tests/tpcds_planning.rs

related #5368 .
disable tpcds-q41
N/A
N/A

minor: disable tpcds-q41 due to not support decorrelate disjunction subquery

---

datafusion/expr/src/expr.rs
datafusion/expr/src/operator.rs
datafusion/physical-expr/src/expressions/binary.rs
datafusion/physical-expr/src/expressions/try_cast.rs

Found while working on #4695.
Broken display code makes debugging and testing hard.
- `TryCast` should display as `TRY_CAST`, not as `CAST`
- `BinaryExpr` should use parenthesis
- fix the two display bugs mentioned above
- move `precedence` from logical binary expression to `Operator`, so I can reuse this in the phys. expr. display code
Slight changes in debug outputs.
**Breaking:** `BinaryExpr::precedence` is gone

fix: misc phys. expression display bugs

---

datafusion/optimizer/src/eliminate_cross_join.rs
datafusion/optimizer/src/eliminate_outer_join.rs
datafusion/optimizer/src/optimizer.rs
datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs
datafusion/optimizer/src/unwrap_cast_in_comparison.rs
datafusion/optimizer/src/utils.rs

Just fixing typos in some optimizer's files.
No
No

Fixed small typos in files of the optimizer

---

datafusion/core/tests/sql/udf.rs
datafusion/physical-expr/src/planner.rs

Closes #5378.
UDFs with zero arguments were not working before.
- Change UDF planning to receive null as input if it takes no args
- This is following the existing docs specification: 
- > ...with the exception of zero param function, where a singular element vec
will be passed. In that case the single element is a null array to indicate
the batch's row count (so that the generative zero-argument function can know
the result array size).
- Add test for zero param UDF to sql integration test suite
Yes.
Fixing user-facing bug.

UDF zero params #5378

---

datafusion/optimizer/src/eliminate_cross_join.rs

Optimization of the function "intersect".
During the execution of the function "extract_possible_join_keys", if the operator of an expression equals OR, then the algorithm goes recursively in depth of the tree and joins keys in the array "accum". As bottom nodes are majority and they may not have right and left descendants, then the join does not happen. However, "intersect" in any cases iterates over all left join keys, which is costly.
This minor patch fixed the problem.
No new tests added
No

Minor: intersect expressions optimization

---

datafusion/core/src/physical_optimizer/pruning.rs
datafusion/core/src/physical_plan/file_format/parquet/page_filter.rs

Prep work for #4695.
Makes the actual change in #4695 easier.
Internal improvements.
Existing tests pass, no function changes.
\-

refactor: parquet pruning simplifications

---

datafusion/optimizer/tests/integration-test.rs

bugfix: fix master `bors` problem.

---

datafusion/core/tests/sql/subqueries.rs
datafusion/optimizer/src/decorrelate_where_exists.rs
datafusion/optimizer/src/decorrelate_where_in.rs

Closes #.
Add some special test cases that outer and subquery table are same table.

Minor: add tests for subquery to join

---

datafusion/expr/src/type_coercion.rs
datafusion/optimizer/src/type_coercion.rs

N/A
https://github.com/apache/arrow-datafusion/pull/5384#discussion_r1116851452 from @waynexia 
we also should support DataType::LargeUtf8 in https://github.com/apache/arrow-datafusion/pull/5234.
add forgotten large_utf8

minor: add forgotten large_utf8

---

datafusion/optimizer/src/push_down_filter.rs

Closes #.
When I do #4465, I find `push_down_filter` exist dead-loop.
So I fix this problem, and refactor it.

refactor `push_down_filter` to fix dead-loop and use optimizer_recurse.

---

datafusion-cli/Cargo.lock
datafusion/expr/src/logical_plan/builder.rs
datafusion/expr/src/logical_plan/plan.rs
datafusion/expr/src/table_source.rs
datafusion/optimizer/Cargo.toml
datafusion/optimizer/src/push_down_filter.rs

Closes #5357.
Allow TableProviders with multi-column indexes to fully filter results. Presently, if a TableProvider is ordered by `[col_a, col_b]`, and it gets a query `where col_a=1 and col_b=2`, then it receives two calls to `supports_filter_pushdown()`: one for `col_a` and one for `col_b` and it would have to return `exact` for `col_a` and `Unsupported` for `col_b` because it can filter them together, and it can filter `col_a` because it's first in the sort order, but it cannot filter `col_b` on it's own.
This change would allow the TableProvider to say "Yes, I can filter expressions like `col_a = x and col_b  = y`.
Change the TableProvider API to have a single method that accepts the entire Vec of Exprs and returns a Vec of results so the TableProvider can assess them all …

Try to push down full filter before break-up

---

datafusion-examples/examples/catalog.rs

#5291 (does not close)
A simple example can help users figure out how to use DataFusion's catalog API.
Just the example.
n/a
n/a

Add example of catalog API usage (#5291)

---

datafusion/core/src/datasource/file_format/mod.rs
datafusion/core/src/datasource/file_format/options.rs
datafusion/core/src/execution/mod.rs

Part of https://github.com/apache/arrow-datafusion/issues/5405 (splitting out execution)
I am trying to split out the physical plan into its own crate. While extracting the execution code, I found that config.rs which contains file format configuration
Move config.rs which contains file format configuration to live with the rest of the datasource code
None intended (I left a backwards compatible `pub use` )

Move file format config.rs to live with the rest of the datasource code

---

datafusion/core/src/physical_plan/file_format/parquet.rs

Relates to #5404
https://github.com/apache/arrow-rs/pull/3633 added the ability to push down limits to the parquet reader. This is particularly important when filter pushdown is enabled on `ParquetOptions` (soon to be default), as it allows the limit to be applied before late materialization, which has significant performance benefits

Parquet limit pushdown (#5404)

---

datafusion/core/src/datasource/datasource.rs
datafusion/core/src/datasource/default_table_source.rs
datafusion/optimizer/src/type_coercion.rs

Closes #5418.
Update to TableProvider
Yes, existing tests should cover this case.
They will have to update their TableProviders once we do away with the Deprecation and switch for real.

Also push down all filters in TableProvider

---

datafusion/optimizer/src/push_down_filter.rs

Closes #5424 
Yes
Predicates will be pushed down through extension plan nodes
No

Fix filter pushdown for extension plans

---

datafusion/physical-expr/src/aggregate/count_distinct.rs

Closes #5325 .
Fixing performance drop for `.size` function. Drop was found during performance benchmarks
During regression the query with `count(distinct )` took 100s in optimized build, now it takes 5s.
Yes
No

Optimize count_distinct.size

---

datafusion/core/src/physical_plan/joins/hash_join.rs
datafusion/core/src/physical_plan/joins/nested_loop_join.rs
datafusion/core/src/physical_plan/joins/utils.rs
datafusion/core/tests/sqllogictests/test_files/join.slt

Closes #5382.
In `build_batch_from_indices`, we should manually specify the row count (using RecordBatch::try_new_with_options) to create a RecordBatch when the input schema and columns are empty.
Yes.

fix nested loop join with literal join filter

---

datafusion/core/src/datasource/file_format/avro.rs
datafusion/core/src/datasource/file_format/csv.rs
datafusion/core/src/datasource/file_format/json.rs
datafusion/core/src/datasource/file_format/mod.rs
datafusion/core/src/datasource/file_format/parquet.rs
datafusion/core/src/datasource/listing/table.rs
datafusion/core/src/physical_optimizer/pruning.rs
datafusion/core/src/physical_plan/file_format/parquet.rs
datafusion/core/src/physical_plan/file_format/parquet/page_filter.rs
datafusion/core/src/physical_plan/file_format/parquet/row_filter.rs
datafusion/core/src/physical_plan/file_format/parquet/row_groups.rs
datafusion/core/tests/parquet/page_pruning.rs
datafusion/core/tests/row.rs
datafusion/physical-expr/src/lib.rs
datafusion/physical-expr/src/physical_expr.rs
datafusion/physical-expr/src/utils.rs
datafusion/proto/proto/datafusion.proto
datafusion/proto/src/generated/pbjson.rs
datafusion/proto/src/generated/prost.rs
datafusion/proto/src/physical_plan/mod.rs
parquet-test-utils/src/lib.rs

Closes #4695.
Use `Arc<dyn PhysicalExpr>` instead of `Expr` within `ParquetExec` and move lowering from logical to physical expression into plan lowering (e.g. `ListingTable`).
This is in line w/ all other physical plan nodes (e.g. `FilterExpr`) and simplifies reasoning within physical optimizer but also allows correct passing of `ExecutionProps` into the conversion.
Basically a bunch of type changes. The tests still use logical expressions because they are easier to construct and its a simple conversion from logical to phys. (at least in the test cases).
All existing tests pass. Removed tests that no longer apply. Added one to demonstrate `PruningPredicate` behavior when no columns are referenced (see https://github.com/apache/arrow-datafusion/pull/5386#discussion_r1117641476 ).
- Phys. …

refactor: ParquetExec logical expr. => phys. expr.

---

datafusion-cli/src/exec.rs
datafusion-cli/src/object_storage.rs
datafusion/common/src/scalar.rs
datafusion/core/src/physical_plan/file_format/parquet.rs
datafusion/core/src/physical_plan/file_format/parquet/page_filter.rs
datafusion/core/src/physical_plan/file_format/parquet/row_groups.rs
datafusion/physical-expr/src/expressions/get_indexed_field.rs
datafusion/proto/src/bytes/mod.rs
datafusion/row/src/writer.rs

minor: fix clippy in nightly.

---

datafusion/physical-expr/src/expressions/cast.rs

related #5396 
This test is minimum reproduce case of a bug in tpcds-q58.
"CAST(Int64(100) AS Decimal128(38, 38))"
It will fail in 
```rust
let col_val = phys_expr.evaluate(&self.input_batch)?;
```
and throw "ArrowError(ComputeError("Overflow happened on: 100 * 100000000000000000000000000000000000000"))"
Add a unit test reproduce a bug.

add a unit test that cover cast bug.

---

datafusion-cli/Cargo.lock
datafusion/core/Cargo.toml

closes https://github.com/apache/arrow-datafusion/pull/5428
Update dependencies
dependency upgrade from https://github.com/apache/arrow-datafusion/pull/5428 and run `cargo update` in datafusion-cli directory
Existing tests

build(deps): update zstd requirement from 0.11 to 0.12

---

datafusion/physical-expr/src/aggregate/build_in.rs
datafusion/physical-expr/src/aggregate/count_distinct.rs
datafusion/proto/src/physical_plan/mod.rs

refactor count_distinct to not to have update and merge

---

datafusion/core/tests/sqllogictests/test_files/pg_compat/pg_compat_simple.slt
datafusion/core/tests/sqllogictests/test_files/select.slt
datafusion/physical-expr/src/expressions/binary.rs
datafusion/physical-expr/src/expressions/binary/kernels_arrow.rs

Closes #5392.
To fix wrong behavior when comparing NaN. Details in #5392 
Yes
No

Fix is_distinct from for float NaN values

---

datafusion/core/src/physical_plan/joins/hash_join.rs
datafusion/expr/src/utils.rs

This helps ameliorate the performance issues in #5456 though the correctness issues identified in that issue still exist.
Before:
```
358946 rows in set. Query took 356.370 seconds.
```
After:
```
358946 rows in set. Query took 2.073 seconds.
```

Enable hash joins on FixedSizeBinary columns

---

datafusion/physical-expr/src/expressions/binary.rs

`compute_decimal_op_dyn_scalar` should not cast lhs array to decimal array

---

datafusion/physical-expr/src/aggregate/sum_distinct.rs

refactor: make sum_distinct not to have update and merge

---

datafusion-examples/examples/simple_udaf.rs

refactor: make GeometricMean not to have update and merge

---

datafusion/core/tests/sqllogictests/test_files/order.slt
datafusion/optimizer/src/eliminate_duplicated_expr.rs
datafusion/optimizer/src/lib.rs
datafusion/optimizer/src/optimizer.rs

Closes #5296.
a new rule to eliminate the duplicated sort keys in Order By clause
add unit test

feat: eliminate the duplicated sort keys in Order By clause

---

datafusion/core/tests/sqllogictests/test_files/scalar.slt
datafusion/expr/src/type_coercion/binary.rs
datafusion/physical-expr/src/expressions/binary.rs
datafusion/physical-expr/src/expressions/binary/kernels.rs

feat: Support bitwise operations for unsigned integer types

---

datafusion/core/src/test/variable.rs
datafusion/physical-expr/src/execution_props.rs
datafusion/physical-expr/src/var_provider.rs

Closes https://github.com/apache/arrow-datafusion/issues/5488
See https://github.com/apache/arrow-datafusion/issues/5488
1. `#[derive(Debug)]` for `ExecutionProps`
2. Add `Debug` to the `VarProvider` trait -- this is technically a breaking change, but I think it is an improvement in usability
Yes, unit test
Anyone who has implemented `VarProvider` will also have to now ensure they implement the `Debug` for that struct

Implement `Debug` for `ExecutionProps` and `VarProvider`

---

datafusion/core/src/dataframe.rs
datafusion/core/src/execution/context.rs
datafusion/core/src/physical_plan/file_format/csv.rs
datafusion/core/src/physical_plan/file_format/json.rs
datafusion/core/src/physical_plan/file_format/parquet.rs

I am trying to extract the physical_plan code into its own crate; SessionState is in `datafusion-core` which means physical_plan can't have references back there.
See more details in https://github.com/apache/arrow-datafusion/issues/1754#issuecomment-1452438453
Change some code to use `TaskContext` rather than `SessionState` (that is simply used to make a `TaskContext`)
I don't think anyone uses these APIs (they are helpers from SessionContext) but I think they are technically public

chore: Remove references from SessionState from physical_plan

---

datafusion/core/src/execution/context.rs
datafusion/core/src/execution/runtime_env.rs
datafusion/core/tests/sql/create_drop.rs
datafusion/proto/src/logical_plan/mod.rs

I am trying to extract the physical_plan code into its own crate; and to do so I need to remove the circular dependencies between core --> datasource --> execution --> datasource
Table factories are used for planning, not for execution, but RuntimeEnv is used for execution (and I am trying to move it into the `datafusion_execution` crate)
See more details in https://github.com/apache/arrow-datafusion/issues/1754#issuecomment-1452438453
1. Move table_factories off of RuntimeEnv and directly to SessionState
Covered by existing tests (and the test changes illustrate what happened to the API). I believe this will affect Ballista (@avantgardnerio ) and delta-rs (cc @roeap )
Users who are specifying custom TableFactoryProviders have …

Minor: Move TableProviderFactories up out of `RuntimeEnv` and into `SessionState`

---

datafusion/common/src/scalar.rs
datafusion/core/tests/sqllogictests/test_files/timestamps.slt
datafusion/expr/src/type_coercion.rs
datafusion/expr/src/type_coercion/binary.rs
datafusion/physical-expr/src/planner.rs

Closes #5413 
As the `timestamp` + feature has already been implemented, you can further enhance the `imp_op` function by adding additional matching conditions to support `interval` operations.

feat: interval add timestamp

---

datafusion/common/src/config.rs
datafusion/expr/src/logical_plan/extension.rs

Related to https://github.com/apache/arrow-datafusion/issues/5400
These new required methods were aded https://github.com/apache/arrow-datafusion/pull/5421  (thanks @mslapek ) and I felt a little more documentation could help people during upgrade.
We found this when working on upgrading  DataFusion in IOx:  https://github.com/influxdata/influxdb_iox/pull/7158
Add doc comments and examples
Yes, they are doc tests and thus tested via `cargo test --doc` and `cargo test --all`
More docs

Minor: Improve docs for UserDefinedLogicalNode `dyn_eq` and `dyn_hash`

---

datafusion/common/src/config.rs
datafusion/core/src/execution/context.rs

Closes #5496.
- Adds `ConfigOptions::with_extensions` constructor to create new config with some default extensions.
- Chages `TaskContext::new` to accept config extensions to create new config using that.
- Additionaly I renamed `TaskContext::new` to `try_new` and added return type so that any error is not ignored when setting config option
One test added.
`TaskContext::new` changed to `TaskContext::try_new` with new argument added and which now returns result

Allow setting config extensions for TaskContext

---

datafusion-cli/Cargo.lock
datafusion/common/Cargo.toml
datafusion/core/Cargo.toml
datafusion/expr/Cargo.toml
datafusion/sql/Cargo.toml
datafusion/sql/src/planner.rs
datafusion/sql/src/select.rs
datafusion/sql/src/statement.rs

Closes https://github.com/apache/arrow-datafusion/pull/5451
New version of sqlparser was released and we need a few changes to DataFusion to acknowledge we don't support newly added syntax
Changes from @dependabot in https://github.com/apache/arrow-datafusion/pull/5451 and updates to make ti compile
Existing tests cover it
No

build(deps): update sqlparser requirement from 0.30 to 0.32 w/ API update

---

datafusion/core/src/physical_plan/common.rs
datafusion/core/src/physical_plan/joins/cross_join.rs
datafusion/core/src/physical_plan/joins/hash_join.rs
datafusion/core/tests/memory_limit.rs

Part of #5339
Part of #5220 
Control over memory allocations made by `HashJoinExec`
Major change is `MemoryReservation.try_grow` calls added to 3 places where allocations for build-side data and related structures are performed:
1. build-side record batches collection -- similar to `CrossJoinExec` memory reserved for each `RecordBatch` fetched from build-side, reservation size calculated using already fetched batch, which could lead to insignificant (no more then single batch size) overallocations
2. build-side hashtable -- there is only one allocation happens during `RawTable::with_capacity()` and it could be massive, so it seems reasonable to preemptively estimate the size required for `RawTable` and reserve it in pool -- the calculations of the size are described in comment
3. …

Memory limited hash join

---

benchmarks/db-benchmark/README.md

Related to https://github.com/apache/arrow-datafusion/issues/5502
I was researching benchmarks as part of https://github.com/apache/arrow-datafusion/issues/5502 and I had to do some digging to figure out what db-benchmark was
See subj
no

Minor: Add db-benchmark URL to db-benchmark readme

---

datafusion/expr/src/logical_plan/plan.rs

Related to #5513, but not close it as there is another unfinished discussion.
#5236 returns chindren's schema rather than `ExtensionPlan`'s in `all_schema`, which will break other places that make use of `ExtensionPlan`.
Correct `all_schema`'s behavior

fix: return schema of ExtensionPlan instead of its children's

---

datafusion/core/src/physical_plan/joins/hash_join.rs
datafusion/physical-expr/src/aggregate/count_distinct.rs

Closes #5534.
The `.size` was accidently corrupted during #5408
Put the size logic back

revert accidently deleted size code in count_distinct

---

datafusion/core/src/physical_plan/planner.rs
datafusion/core/tests/user_defined_plan.rs
datafusion/expr/src/lib.rs
datafusion/expr/src/logical_plan/extension.rs
datafusion/expr/src/logical_plan/mod.rs
datafusion/optimizer/src/push_down_filter.rs
datafusion/optimizer/src/test/user_defined.rs
datafusion/proto/src/logical_plan/mod.rs

Related to #5400 
Follow-up of the discussion from PR #5515 where @alamb added new docs to `UserDefinedLogicalNode`.
Will make boilerplate from `dyn_eq` and `dyn_hash` unnecessary.
Added the trait `UserDefinedLogicalNodeCore` and a blanket implementation `UserDefinedLogicalNodeCore -> UserDefinedLogicalNode`.
Refactored existing `UserDefinedLogicalNode` to use `UserDefinedLogicalNodeCore` - which showcases the value of this PR.
It's a refactor. The expected behaviour is in already existing tests.
Added new trait `UserDefinedLogicalNodeCore`.
No changes to the existing API (including `UserDefinedLogicalNode`).

Add UserDefinedLogicalNodeCore

---

datafusion/expr/src/type_coercion/aggregates.rs

The array "NUMERICS", that are defined in the file "datafusion/expr/src/type_coercion/aggregates.rs" (see https://github.com/apache/arrow-datafusion/blob/main/datafusion/expr/src/type_coercion/aggregates.rs#L30-L41) contains all types, which found in many "match" and "matches!" cases.
I think this PR suggests more concise way for these cases.
Rewritten "match" statements and "matches!" macros.
Yes
No

Minor: add the concise way for matching numerics

---

datafusion/expr/src/operator.rs
datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs

Follow on to https://github.com/apache/arrow-datafusion/pull/5423
as @izveigor pointed out on https://github.com/apache/arrow-datafusion/pull/5423/files#r1125686357, the tests in expr simplifier used a more verbose style that he followed, which makes sense.
However, I would like to keep the codebase easier to maintain and thus use less ceremony for creating Exprs. 
1. Support `^`, `&`, `|`, `<<` and `>>` opertors for building exprs
2. Simplify expression simply test cases
You can now create exprs like
```rust
let expr = lit(0) & lit(45)
```

Simplify simplify test cases, support `^`, `&`, `|`, `<<` and `>>` operators for building exprs

---

datafusion/common/src/column.rs
datafusion/core/src/dataframe.rs
datafusion/core/tests/dataframe.rs
datafusion/expr/src/expr_rewriter.rs
datafusion/expr/src/logical_plan/builder.rs
datafusion/expr/src/logical_plan/plan.rs
datafusion/expr/src/utils.rs
datafusion/optimizer/src/push_down_filter.rs
datafusion/sql/src/select.rs
datafusion/sql/src/statement.rs
datafusion/sql/tests/integration_test.rs
datafusion/substrait/src/logical_plan/consumer.rs

Closes #5211, Closes #5248, Closes #5251
Rather than having separate steps for doing ambiguity checks on unqualified columns and then normalizing them, will enforce ambiguity check during normalization (turning into qualified column). This way will not have to keep adding ambiguity checks for different paths (see issues listing which paths were missing these checks)
Introduce new unqualified column normalization methods to enforce ambiguity checks. Change old usages of the normalization method to use this new method.
Added extra ambiguity tests
Deprecated some methods (though unsure if they were intended to be user facing in the first place, vs being intended for use in other datafusion crates)

Enforce ambiguity check whilst normalizing columns

---

datafusion/core/tests/sqllogictests/test_files/subquery.slt
datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs

Closes #5529 .
fix: failed to run "where x in ((select ...))"
rewrite `Expr::InList` with only one subquery to `Expr::InSubquery` during logical plan optimization
yes
no

fix: failed to execute sql with subquery

---

datafusion/optimizer/src/unwrap_cast_in_comparison.rs

Closes #5507
When converting between different timestamps, reduce the precision by truncating excess digits.

fix: cast literal to timestamp

---

datafusion/core/tests/sql/expr.rs
datafusion/physical-expr/src/datetime_expressions.rs

Closes #2785
Explain #2785
Add `EXTRACT( EPOCH FROM COL)`

feat: extract (epoch from col)

---

datafusion/core/src/execution/mod.rs
datafusion/execution/src/lib.rs
datafusion/execution/src/runtime_env.rs

I am trying to extract the physical_plan code into its own crate; and to do so I need to remove the circular dependencies between core --> datasource --> execution --> datasource
The `RuntimeEnv` is used at runtime, so it belongs in the `datafusion_execution` crate
See more details in https://github.com/apache/arrow-datafusion/issues/1754#issuecomment-1452438453
1. Move RuntimeEnv to `datafusion_execution`
No, I added a `pub use` so this code movement should not affect users

Minor: Move RuntimeEnv to `datafusion_execution`

---

datafusion/expr/src/utils.rs

re https://github.com/apache/arrow-datafusion/pull/5509
@mingmwang suggested this in https://github.com/apache/arrow-datafusion/pull/5509/files#r1133495404 but I had already merged the PR. Thus apply the suggestion as a follow on PR
Add explicit match rather than implicit `_` to help avoid subtle bugs in the future when new `Expr` variants are added
Existing tests
No
cc @mingmwang  and @Jefffrey

Minor: restore explicit match to help avoid subtle bugs in the future when new `Expr` variants are added

---

datafusion/core/tests/sqllogictests/test_files/aggregate.slt

Related to #4495 
There are some out of date errors I noticed while working on https://github.com/apache/arrow-datafusion/pull/5574
uncomment some tests in aggregates.slt and remove TODOs that have been done
Yes they are tests
No

Minor: clean up aggregates.slt tests

---

README.md
datafusion/common/src/dfschema.rs
datafusion/common/src/table_reference.rs
datafusion/core/src/execution/context.rs
datafusion/core/src/physical_plan/planner.rs
datafusion/core/src/test_util/mod.rs
datafusion/expr/src/logical_plan/builder.rs
datafusion/expr/src/logical_plan/plan.rs
datafusion/expr/src/utils.rs
datafusion/optimizer/src/inline_table_scan.rs
datafusion/optimizer/src/push_down_filter.rs
datafusion/optimizer/src/push_down_projection.rs
datafusion/proto/proto/datafusion.proto
datafusion/proto/src/generated/pbjson.rs
datafusion/proto/src/generated/prost.rs
datafusion/proto/src/logical_plan/mod.rs
datafusion/sql/src/relation/mod.rs
datafusion/substrait/src/logical_plan/producer.rs

Closes https://github.com/apache/arrow-datafusion/issues/5522
After https://github.com/apache/arrow-datafusion/pull/5343 some APIs take a String and parse it like a table reference (aka apply sql normalization rules to it)
TBD
Yes, both existing tests as well as new unit tests
Theoretically yes, but he existing `LogicalPlanBuilder::scan("tablename", ...)` will continue to work so no major API work will be needed

Use TableReference for TableScan

---

datafusion/expr/src/expr_rewriter/order_by.rs
datafusion/sql/tests/integration_test.rs

Closes #5610.
I changed `rewrite_in_terms_of_projection` to add casts back, but I honestly have no idea if this is proper way to fix this but it does the trick and would appreciate some direction.
Added two new tests.
Bugfix.

Preserve casts in rewrite_sort_cols_by_aggs

---

datafusion/common/src/table_reference.rs

Related to https://github.com/apache/arrow-datafusion/pull/5615
While working on https://github.com/apache/arrow-datafusion/pull/5615 I realized how complicated the TableReference has become so I felt more documentataion was in order
Add Documentation and Examples to `TableReference`
Yes, doc tests are tested
More docs

Minor: Add Documentation and Examples to `TableReference`

---

datafusion/core/tests/sql/order.rs
datafusion/optimizer/src/eliminate_duplicated_expr.rs

Closes #.
Follow up mentioned in the PR
https://github.com/apache/arrow-datafusion/pull/5462
Dedup sort keys should ignoring sort options:
For example `select * from t1 order by id desc, id, name, id asc`;
The real sort key should be: `Sort Key: id DESC, name`

[FOLLOWUP] eliminate the duplicated sort keys in Order By clause

---

datafusion/core/src/datasource/file_format/file_type.rs

Closes #5628.
Support larger compressed files with multi-members.
Changing `convert_read`
Yes
No

Update default behaviour of compression algorithms (support multistreams)

---

datafusion/common/src/error.rs
datafusion/sql/src/expr/mod.rs

related to faster planning: https://github.com/apache/arrow-datafusion/issues/5637
related to like inference: https://github.com/apache/arrow-datafusion/issues/5617
This function has a bunch of unecessary `clone()` which likely means running parameter type inference would be bad to do for all queries
Avoids a bunch of expr copies when inferring placeholder types
Existing tests cover this functionality
No

Minor: reduce cloning in `infer_placeholder_types`

---

datafusion/expr/src/logical_plan/plan.rs

Update the type of `param_values` to `&[ScalarValue]` in function `replace_params_with_values`

---

datafusion/core/src/physical_plan/joins/sort_merge_join.rs
datafusion/core/src/physical_plan/metrics/value.rs
datafusion/core/tests/memory_limit.rs

Closes #5220.
Control over memory allocation in `SortMergeJoinExec`
- `SMJStream.reservation` -- memory reservation to control buffered data size -- it may require significant amount of memory, for example, in case of multiple batches with the same join key values
- `peak_memory_used` -- during join execution, normally, both `try_grow` and `shrink` methods are called  -- on adding new buffered batches and on flushing them if join key has changed, respectively. In this case it seems reasonable to track only peak memory for each partition -- after that it's summed up across all partitions which is not really precise, but still valuable in terms of showing "worst case" (in fact peak memory used, probably, can be lower)
- memory limit tests now are able to run with configurable …

feat: Memory limited merge join

---

datafusion/common/src/cast.rs
datafusion/core/src/physical_plan/aggregates/row_hash.rs
datafusion/core/src/test_util/mod.rs
datafusion/core/tests/parquet/custom_reader.rs
datafusion/expr/src/logical_plan/plan.rs
datafusion/expr/src/utils.rs
datafusion/optimizer/src/simplify_expressions/regex.rs
datafusion/optimizer/src/utils.rs
datafusion/physical-expr/src/aggregate/variance.rs
datafusion/physical-expr/src/utils.rs
datafusion/proto/src/common.rs
datafusion/proto/src/logical_plan/from_proto.rs
datafusion/proto/src/logical_plan/mod.rs
datafusion/proto/src/physical_plan/from_proto.rs
datafusion/proto/src/physical_plan/mod.rs
datafusion/proto/src/physical_plan/to_proto.rs

Closes #5660 .
Simplify Result type, make it less wordy.
There are many places where `Result<T, DatafusionError>` used, we can replace it by already created type and get just `Result<T>` 
Replace `Result<T, DatafusionError>` entries with `Result<T>`
Yes
No

Minor: Simplify `Result<T, DataFusionError>`

---

datafusion/substrait/src/logical_plan/consumer.rs
datafusion/substrait/src/logical_plan/producer.rs
datafusion/substrait/tests/roundtrip_logical_plan.rs

Closes https://github.com/apache/arrow-datafusion/issues/5136
To add (partial) support for `Expr::Cast` in Substrait producer/consumer.
- Support for casting to:
- `Boolean`
- `Int8`, `Int16`, `Int32`, `Int64`
- `Decimal128`
- Tests
- Casting decimal literal to integer
- Casting decimal column to integer
Yes. (decimal -> integer)
No

Substrait: Add cast expression with bool, integers and decimal128 support

---

datafusion/core/tests/sqllogictests/test_files/timestamps.slt
datafusion/expr/src/function.rs
datafusion/physical-expr/src/datetime_expressions.rs

Support `date_bin` with 2 arguments

---

datafusion/optimizer/src/lib.rs
datafusion/optimizer/src/optimizer.rs
datafusion/optimizer/src/plan_signature.rs

Closes #3892
Removes a blocker for #4628 (allows to have only one `LogicalPlan` in RAM)
Attractive alternative for returning `Option<LogicalPlan>` in the optimizer loop (see the comment https://github.com/apache/arrow-datafusion/issues/4628#issuecomment-1470106106)
Explained in the issue.
Added a new structure `LogicalPlanSignature` with `compute` method.
Used `LogicalPlanSignature` in the main optimization loop to detect cycles with hash-set.
*(Maybe we should raise default `max_passes` in optimizer? We can detect cycles.)*
Added unit-test for computation in `LogicalPlanSignature` (for `get_node_number` function).
Added unit-tests to `optimizer.rs` testing cycle-detection ability.
Existing tests to detect regression.
NO API changes. The new module with `LogicalPlanSignature` is …

Add LogicalPlanSignature and use in the optimizer loop

---

datafusion/core/tests/dataframe.rs
datafusion/optimizer/src/analyzer/count_wildcard_rule.rs
datafusion/optimizer/src/analyzer/mod.rs
datafusion/optimizer/src/eliminate_filter.rs
datafusion/optimizer/src/lib.rs

Closes #.
related PR: #5627
- move analyzer to new dir 
- fix CountWildcardRule.

fix: correct CountWildcardRule and move analyzer into a new directory.

---

datafusion/common/src/config.rs
datafusion/core/src/execution/context.rs

N/A
@andygrove  reported on [ASF Slack](https://the-asf.slack.com/archives/C01QUFS30TD/p1679408811522469
> I am trying to upgrade Ray SQL to DataFusion 20, and running into problems trying to create the new Extensions param to TaskContext::try_new
> The struct is defined as:
> #[derive(Debug, Default, Clone)]
> pub struct Extensions(BTreeMap<&'static str, ExtensionBox>);
> I am hitting this error:
> error[E0423]: cannot initialize a tuple struct which contains private fields
>   --> src/context.rs:177:13
>     |
> 177 |             Extensions(BTreeMap::new())
>     |             ^^^^^^^^^^
>     |
> note: constructor is not visible here due to private fields
> Am I missing something obvious here, or is it no longer possible to create TaskContext outside of the core project?
Turns out the …

Minor: Add `Extensions::new()`

---

datafusion/physical-expr/src/datetime_expressions.rs

re https://github.com/apache/arrow-datafusion/pull/5643 and https://github.com/apache/arrow-datafusion/issues/5641
I saw a way to reduce some code duplication introduced in https://github.com/apache/arrow-datafusion/pull/5643 but felt it would not be fair to @Weijun-H  to go back and forth more on that PR because https://github.com/apache/arrow-datafusion/pull/5643  implemented the desired behavior, and this is just a code cleanup
refactor the `date_bin` implementation to have a single implementation for 2 and 3 argument forms
No

minor: reduce replication in `date_bin` implementation

---

docs/source/_templates/docs-sidebar.html

re #5500 
While working https://github.com/apache/arrow-datafusion/pull/5670 we lost the sidebar logo
Add the logo back in
Tested locally
docs

Docs: Add logo back to sidebar

---

datafusion/substrait/src/logical_plan/consumer.rs
datafusion/substrait/src/logical_plan/producer.rs
datafusion/substrait/tests/roundtrip_logical_plan.rs

Closes # [5390](https://github.com/apache/arrow-datafusion/issues/5390).
Added the ability to producer/consume Substrait plans with WindowFunction
- Producer
- Added `LogicalPlan::Window` case
- If the input to this relation is a `ProjectRel`, append `WindowFunction` expressions before returning the parsed `ProjectRel`
- If the input is NOT a projection, create a `ProjectRel`, add column reference expressions to represent ALL of the fields of the input relation's output. Then append `WindowFunction` expressions.
- Consumer
- Added case to parse `WindowFunction`
- Note that the output `WindowFrameUnits` are currently set to either `Rows` or `Range` depending on whether `ORDER BY` is present in the `WindowFunction`. May need to revisit the cases when frame is explicitly defined.
- Moved all …

Substrait: Add support for WindowFunction

---

docs/README.md

Related to #5500 
https://github.com/apache/arrow-datafusion/pull/5670 from @martin-g  automates the build and publish of the datafusion documentation to https://arrow.apache.org/datafusion/ 🎉 
Update the documentation on the release process
N/A
No

Minor: Document docs build process

---

docs/source/user-guide/introduction.md

Related to #5500 
The  https://arrow.apache.org/datafusion/ site is currently broken
Somehow related to https://github.com/apache/arrow-site/pull/336#issuecomment-1480389066
Change formatting of markdown (no content) to get the datafusion site to rebuild and republish
No (I am testing live)
Docs

Minor: change doc formatting to force a republish

---

datafusion/common/src/parsers.rs
datafusion/core/tests/sqllogictests/test_files/timestamps.slt
datafusion/expr/src/function.rs
datafusion/physical-expr/src/datetime_expressions.rs

Closes #5697
Teach `date_bin` to support for microsecond and nanosecond precision of intervals via the `MonthDayNano` type. Note that months are complicated to support and will require additional work. In doing so, we can also address #5689.
`date_bin` is now capable of parsing fractional intervals with a precision of microseconds and greater. The interval parser is also capable of interpreting the additional units `microsecond`, `microseconds`, `nanosecond` and `nanoseconds`, which should be additive.
Yes, unit tests for parsing intervals, validating arguments to `date_bin` and new SQL tests in the `timestamps.slt` file.
Yes, users can now use additional units for intervals, such as:
```sql
select date_bin('500 microseconds', ...)
```
and the `date_bin` function is capable of binning …

feat: `date_bin` supports MonthDayNano, microsecond and nanosecond units

---

datafusion/core/tests/sqllogictests/test_files/dates.slt
datafusion/physical-expr/src/expressions/binary.rs

Closes #5650
Return plan error when performing binary operations between timestamp and utf8

Return plan error when adding utf8 and timestamp

---

datafusion/optimizer/src/analyzer/mod.rs
datafusion/optimizer/src/optimizer.rs

Related to the discussion on https://github.com/apache/arrow-datafusion/pull/5683 with @jackwener  and @mingmwang  
I was not clear exactly what should be an `OptimizerRule` and what should be an `AnalyzerRule`
Add doc strings explaining the difference per @jackwener 's comment https://github.com/apache/arrow-datafusion/pull/5683#issuecomment-1480536552
N/A
Better doc strings

minor: Add doc comments to clarify what Analyzer is for

---

datafusion/core/src/physical_optimizer/pruning.rs
datafusion/core/tests/parquet/mod.rs
datafusion/core/tests/parquet/row_group_pruning.rs

Closes https://github.com/apache/arrow-datafusion/issues/5708
We were seeing wrong results with parquet file that had columns with `.` in their names
Bug fix + test
yes
I also verified that this fixes the issue we saw upstream in IOx https://github.com/influxdata/influxdb_iox/issues/7225#issuecomment-1481809300
bug fix
cc @crepererum

Fix parquet pruning when column names have periods

---

datafusion/core/src/physical_plan/limit.rs
datafusion/core/src/test/mod.rs

Closes https://github.com/apache/arrow-datafusion/issues/5701
Bug fix
Use `options` to explicitly set `row_count`, closely related / similar solution to https://github.com/apache/arrow-datafusion/pull/4912
Yes
No

Executing LocalLimitExec with no column should not return an Err

---

.asf.yaml

Related to #5500 
Now that we have the automated publishing working, I want to document how the process works. #5687 was aprt. 
cc @martin-g @kou 
Add some comments to `.asf.yaml` so my future self remembers what the parts are for
N/a

Minor: Comments to .asf.yaml

---

.github/workflows/docs.yaml
datafusion/core/tests/parquet/row_group_pruning.rs

Related to #5500 
Publishing the docs is configured  by `asf.yaml` and thus if that files changes we should also retrigger the docs workflow
As suggested by @kou  on  https://github.com/apache/arrow-datafusion/pull/5703#pullrequestreview-1355709963
1. Trigger docs CI build on changes to asf.yaml
No
No

Minor: Trigger docs CI build on changes to asf.yaml

---

datafusion/optimizer/src/analyzer/count_wildcard_rule.rs
datafusion/optimizer/src/analyzer/inline_table_scan.rs
datafusion/optimizer/src/analyzer/mod.rs

re https://github.com/apache/arrow-datafusion/pull/5705
The current signature of `AnalyzerRule` requires the `LogicalPlan` to be `clone()`ed. 
@mingmwang  says that was an oversight
https://github.com/apache/arrow-datafusion/pull/5705#discussion_r1147073711
Change signature to take owned LogicalPlan
Existing tests
No

Minor: Reduce clones in AnalyzerRule

---

benchmarks/src/bin/tpch.rs
datafusion/proto/README.md

fix test of benchmarks warning:
```shell
warning: use of deprecated associated function `datafusion::dataframe::DataFrame::to_logical_plan`: Use DataFrame::into_optimized_plan
--> benchmarks/src/bin/tpch.rs:751:29
|
751 |             let plan = plan.to_logical_plan()?;
|                             ^^^^^^^^^^^^^^^
|
= note: `#[warn(deprecated)]` on by default
warning: `datafusion-benchmarks` (bin "tpch" test) generated 1 warning
```
use `into_optimized_plan` instead of deprecated `to_logical_plan`

fix test of benchmarks warning

---

datafusion/expr/src/tree_node/plan.rs

Related to https://github.com/apache/arrow-datafusion/pull/5630
As suggested by @mingmwang https://github.com/apache/arrow-datafusion/pull/5630#issuecomment-1486169300 we can save a copy here

Minor: Avoid an unecessary contruction in `map_children` some extra plan construction

---

Cargo.toml
datafusion-cli/Cargo.lock
datafusion-examples/Cargo.toml
datafusion/common/Cargo.toml
datafusion/core/tests/sql/set_variable.rs
datafusion/expr/Cargo.toml
datafusion/jit/Cargo.toml

re https://github.com/apache/arrow-datafusion/issues/5744
See https://github.com/apache/arrow-datafusion/issues/5744 (we want to release a point fix)
Backport changes from https://github.com/apache/arrow-datafusion/pull/5724 to `branch-21` in preparation of a DataFusion minor release
Yes
Fewer dependencies

Backport: Use consistent arrow version (do not use both `arrow` `34.0.0` and `arrow-array` `35.0.0`) (#5724)

---

Cargo.toml
benchmarks/Cargo.toml
datafusion-cli/Cargo.toml
datafusion/CHANGELOG.md
datafusion/core/Cargo.toml
datafusion/execution/Cargo.toml
datafusion/expr/Cargo.toml
datafusion/jit/Cargo.toml
datafusion/optimizer/Cargo.toml
datafusion/physical-expr/Cargo.toml
datafusion/proto/Cargo.toml
datafusion/row/Cargo.toml
datafusion/sql/Cargo.toml
datafusion/substrait/Cargo.toml
dev/update_datafusion_versions.py

re https://github.com/apache/arrow-datafusion/issues/5744
Prepare for `22.1.0` release as described on https://github.com/apache/arrow-datafusion/issues/5744
Update version to `22.1.0` and add (manual) Changelog entry on `branch-21`
No
Eventually they will be

Backport: Update version and Changelog for `21.1.0`

---

docs/build.sh

NA
https://github.com/apache/arrow-datafusion/pull/5780 unfortunately broke the docs build (see https://github.com/apache/arrow-datafusion/actions/runs/4566861530/jobs/8059935571)
I think this is because @sanderson fixed the script to work on mac (it previously was broken) but that sadly broke it on linux. 
Mess with `sed` command line
No -- will test 'live'
Not really

Minor: fix docs build

---

datafusion-cli/Cargo.lock
datafusion/physical-expr/Cargo.toml

re https://github.com/apache/arrow-datafusion/pull/5764
Without it datafusion compiles both arrow 36 and arrow 34
See  https://github.com/apache/arrow-datafusion/pull/5764#discussion_r1153371981
Use workspace version
Covered by existing tests 
No

Minor: use workspace arrow-array rather than hard coded 34

---

datafusion/common/src/scalar.rs
datafusion/core/tests/sqllogictests/test_files/arrow_typeof.slt
datafusion/core/tests/sqllogictests/test_files/interval.slt
datafusion/sql/src/planner.rs
docs/source/user-guide/sql/data_types.md

Closes https://github.com/apache/arrow-datafusion/issues/5651
See https://github.com/apache/arrow-datafusion/issues/5651 (basically I want to be able to interact with intervals like normal). Also related to https://github.com/apache/arrow-datafusion/pull/5764 from @berkaysynnada
1. Add basic support for `INTERVAL` SQL --> `DataType::Interval(MonthDayNano)` arrow type
2. Add code to go to/from ScalarValue and Interval Arrays
3. Basic tests
Yes
Yes (you can now do `SELECT '1 day'::interval`) and it works!

Support `INTERVAL` SQL Type

---

datafusion/core/tests/sqllogictests/test_files/interval.slt

re https://github.com/apache/arrow-datafusion/pull/5792
One of the tests added in https://github.com/apache/arrow-datafusion/pull/5792 intermittently fails due to ordering mismatch -- for example 
https://github.com/apache/arrow-datafusion/actions/runs/4568420322/jobs/8063658835?pr=5803
```
[Diff] (-expected|+actual)
-   0 years 0 mons 5 days 0 hours 0 mins 0.000000003 secs Interval(MonthDayNano)
-   0 years 0 mons 6 days 0 hours 0 mins 0.000000007 secs Interval(MonthDayNano)
+   0 years 0 mons 6 days 0 hours 0 mins 0.000000007 secs Interval(MonthDayNano)
+   0 years 0 mons 5 days 0 hours 0 mins 0.000000003 secs Interval(MonthDayNano)
at tests/sqllogictests/test_files/interval.slt:59
```
Add sorting to test script to make test deterministic
yes 
no

Minor: fix flaking test

---

benchmarks/src/bin/tpch.rs

Incorrect row comparison for tpch queries in benchmarks

---

datafusion/physical-expr/src/aggregate/min_max.rs

Follow on to https://github.com/apache/arrow-rs/issues/1010
This function is not necessary now.
Remove the function "remove typed_min_max_batch_decimal128".
Yes
No

Minor: remove typed_min_max_batch_decimal128

---

.github/workflows/rust.yml

N/a
While reviewing https://github.com/apache/arrow-datafusion/pull/5730 I noticed that the CI checks did not run even though we were changing the definition of what to run in `.github`
Change CI trigger to only ignore documentation related changes (not everything in .github which also includes workflow definitions)
I will test them manually in https://github.com/apache/arrow-datafusion/pull/5730
No

Minor: Run rust workflow on changes to .github

---

datafusion/core/tests/sqllogictests/test_files/math.slt
datafusion/expr/src/expr_fn.rs
datafusion/expr/src/function.rs
datafusion/physical-expr/src/functions.rs
datafusion/physical-expr/src/math_expressions.rs
datafusion/proto/src/logical_plan/from_proto.rs
datafusion/sql/tests/integration_test.rs

Support `round()` function with two parameters

---

datafusion/core/tests/sqllogictests/test_files/pg_compat/pg_compat_null.slt
datafusion/expr/src/expr_schema.rs

Fixes #5733
Fixes the issue.
Make `Expr::schema` return coerced `DataType` for `Expr::Case`.
Added `pg_compat_null.slt` reproducing the issue.
No, except the bug fix.

Fix datatype of case expression

---

datafusion/expr/src/expr_schema.rs

re https://github.com/apache/arrow-datafusion/pull/5734
Add reference to ticket filed as result of discussion https://github.com/apache/arrow-datafusion/pull/5734/files#r1148464084
Add ticket reference as comment
no
no

Minor: Add ticket reference as comment

---

datafusion/core/src/physical_plan/planner.rs
datafusion/expr/src/logical_plan/mod.rs
datafusion/expr/src/logical_plan/plan.rs
datafusion/expr/src/utils.rs
datafusion/optimizer/src/common_subexpr_eliminate.rs
datafusion/proto/src/logical_plan/mod.rs
datafusion/sql/src/statement.rs
datafusion/sql/tests/integration_test.rs

Closes #5826.
To make it easier for folks to build execution engines on top of DataFusion's planner (see issue for more detail).
Two LogicalPlan nodes for starting and ending transactions.
Additional tests were added to the planner.
When users try to run begin and end transaction statements, they will now fail in physical instead of logical planning.

Implement LogicalPlan support for transactions

---

datafusion/core/src/execution/context.rs
datafusion/expr/src/logical_plan/plan.rs
datafusion/expr/src/utils.rs
datafusion/sql/src/statement.rs
datafusion/sql/tests/integration_test.rs

Closes #5834.
As a developer building a database atop DataFusion, it would be useful to have knowledge of primary keys retained in the LogicalPlan.
A new `primary_key` field on `LogicalPlan::CreateMemoryTable`
Sort of - there's a test that broke before, but I couldn't figure out what prints this LogicalPlan node, so I wasn't able to add the pk info to the `Debug` trait and assert that.
`create table` statements that used to fail (e.g. with `primary key` clauses) will now not fail. I'm not sure if that's an issue for anyone.

Add primary key information to CreateMemoryTable LogicalPlan node

---

datafusion/sql/src/expr/identifier.rs
datafusion/sql/src/expr/mod.rs
datafusion/sql/src/expr/subquery.rs
datafusion/sql/src/planner.rs
datafusion/sql/src/query.rs
datafusion/sql/src/relation/mod.rs
datafusion/sql/src/select.rs
datafusion/sql/src/set_expr.rs
datafusion/sql/src/statement.rs

related to #5637 , but really a Friday afternoon project that has bothered me for a whle
The PlannerContext in the SQL planner has a map of `LogicalPlans` and it is cloned during planning (which deep clones the values 😱 ). Also, the LogicalPlan is cloned on use anyways.
1. Make the fields of `PlannerContext` non pub
2. 
No

minor(sqlparser): encapsulate PlanerContext, reduce some clones

---

datafusion/core/src/physical_plan/file_format/file_stream.rs

Closes #5799.
Next file opening future will now be polled while the current file is being scanned.
I did not add any new tests as I believe this change should be covered by existing tests, but I am happy to add additional tests that I didn't think of.
I believe not.

Poll next open file future while scanning current file

---

datafusion/core/src/physical_plan/joins/symmetric_hash_join.rs
datafusion/core/src/test_util/mod.rs
datafusion/core/tests/fifo.rs

Closes https://github.com/apache/arrow-datafusion/issues/5714.
To optimize the asynchronous performance of the `SymmetricHashJoin` operator, we propose merging the two child streams using `futures::select`. This will enable simultaneous polling of both streams and execute the branch corresponding to the future that completes first.
- Single stream SHJ implementation on `poll_next()`
- Refactor on fifo tests and reduce code duplication.
Yes
No

Enhance Asynchronous Performance of SHJ Implementation 

---

docs/source/index.rst

Related to #3058 
I am trying to make sure people can find the information they are looking for when the come to the DataFusion webpage
1. Add crates.io and docs.rs links to the website
2. Move the links to the top
(the links are at the top!)
No
doc

Minor: Add crates.io / API links to website

---

datafusion/common/src/column.rs
datafusion/common/src/dfschema.rs
datafusion/common/src/table_reference.rs
datafusion/common/src/utils.rs
datafusion/core/src/dataframe.rs
datafusion/core/tests/dataframe.rs
datafusion/core/tests/sql/idenfifers.rs
datafusion/core/tests/sql/references.rs
datafusion/core/tests/sqllogictests/test_files/join.slt
datafusion/expr/src/expr_rewriter/mod.rs
datafusion/sql/tests/integration_test.rs

Closes https://github.com/apache/arrow-datafusion/issues/5523
Closes https://github.com/apache/arrow-datafusion/pull/5625
Error messages are hard to read with so many unecessary `"`
This work is based off of @Weijun-H 's great start in https://github.com/apache/arrow-datafusion/pull/5625 (🙏 )
1. Improve error messages by only quoting column names if necessary
2. Add test for quote_identifier
Yes -- both existing tests and new tets

feat: Quote column names if required in error messages

---

datafusion/physical-expr/src/math_expressions.rs

Use ScalarValue for single input on math expression

---

datafusion/core/tests/sqllogictests/test_files/arrow_typeof.slt
datafusion/sql/src/expr/arrow_cast.rs

Closes #5913
cc @alamb 
allow arrow_cast to cast to timestamptz
```bash
❯ select arrow_cast(timestamp '2000-01-01T00:00:00', 'Timestamp(Nanosecond, Some( "+08:00" ))');
+-----------------------------+
| Utf8("2000-01-01T00:00:00") |
+-----------------------------+
| 2000-01-01T08:00:00+08:00   |
+-----------------------------+
1 row in set. Query took 0.010 seconds.
```
```bash
❯ select arrow_cast(timestamptz '2000-01-01T00:00:00Z', 'Timestamp(Nanosecond, Some( "+08:00" ))');
+------------------------------+
| Utf8("2000-01-01T00:00:00Z") |
+------------------------------+
| 2000-01-01T08:00:00+08:00    |
+------------------------------+
1 row in set. Query took 0.002 seconds.
```
```bash
❯ select arrow_cast(0, 'Timestamp(Nanosecond, Some( "+08:00" ))');
+---------------------------+
| …
```

arrow_cast to cast to timestamptz

---

datafusion/expr/src/expr_schema.rs
datafusion/optimizer/src/analyzer/type_coercion.rs

Closes #.
type coercion should do for expr and subquery in InSubquery
Add UT test for expr/subquery in Insubquery

fix: type coercion for expr/subquery in InSubquery

---

docs/source/contributor-guide/architecture.md

The order of the slide url is not corresponding to the recording.

Minor:  fix the architecture slide url

---

datafusion/core/tests/sql/aggregates.rs
datafusion/core/tests/sql/errors.rs
datafusion/expr/src/aggregate_function.rs
datafusion/expr/src/signature.rs
datafusion/expr/src/type_coercion/aggregates.rs
datafusion/expr/src/type_coercion/functions.rs
datafusion/physical-expr/src/aggregate/build_in.rs
datafusion/physical-expr/src/aggregate/count.rs

Closes #5619
Most of other sql engines like pg, mysql, spark support count for multiple expressions like: select count(col1, col2) from table1;
Support count for multiple expressions, when any expression return null for each row, the row will not be counted. 
Yes, add new ut and e2e test
No
No

Count agg support multiple expressions

---

datafusion/substrait/src/lib.rs
datafusion/substrait/src/logical_plan/consumer.rs
datafusion/substrait/src/logical_plan/producer.rs
datafusion/substrait/src/variation_const.rs
datafusion/substrait/tests/roundtrip_logical_plan.rs

Closes https://github.com/apache/arrow-datafusion/issues/5717.
Extend the type and literal support in substrait. Most of simple type/literal are supported (exception: `Date64` literal), and compound types except `FixedSizeUtf8`, `FixedSizeList`, `Dictionary` etc.
Some of, see comment below
Not breaking

feat: extend substrait type support, including type variations

---

datafusion/core/tests/sqllogictests/test_files/select.slt
datafusion/physical-expr/src/expressions/binary.rs
datafusion/physical-expr/src/expressions/like.rs

fix: binaryExpr not supported for LargeUtf8

---

datafusion/core/src/physical_plan/file_format/file_stream.rs

Closes https://github.com/apache/arrow-datafusion/issues/5899
See https://github.com/apache/arrow-datafusion/pull/5790#discussion_r1155734134 -- I was messing around in this code anyways so I figured I would also make the proposed change
1. Include the time to call `start_file_opening` in the `time_opening` FileStream metrics
No -- I don't have any good idea of how to test it
(Slighly) better metrics

Improve file scan time opening metric to include start_next_file

---

datafusion/substrait/src/logical_plan/consumer.rs
datafusion/substrait/src/logical_plan/producer.rs
datafusion/substrait/tests/roundtrip_logical_plan.rs

Related to https://github.com/apache/arrow-datafusion/issues/5717
During the review of https://github.com/apache/arrow-datafusion/pull/5775 I noticed there was unsafe code in `datafusion-proto` for seemingly unecessary reasons. See https://github.com/apache/arrow-datafusion/pull/5775#discussion_r1161492804 with @waynexia 
1. Remove `unsafe` code. 
2. Add boundary tests to ensure substrait roundtrip casting works
Yes new tests are added
No

Remove `unsafe` code (`transmute`) in datafusion-proto

---

datafusion/core/tests/sql/timestamp.rs
datafusion/expr/src/function.rs
datafusion/physical-expr/src/datetime_expressions.rs

Closes #5750
`date_trunc` will return `TimestampSecond` when truncing minute.

support `date_trunc` with `millisecond` and `microsecond` and keep the same type as the input

---

datafusion-examples/README.md
datafusion/common/src/tree_node.rs
datafusion/core/src/lib.rs
datafusion/expr/src/operator.rs
datafusion/physical-expr/src/sort_expr.rs
datafusion/sql/src/planner.rs
docs/source/contributor-guide/architecture.md
docs/source/contributor-guide/index.md

Move some content into the code organization section
Part of https://github.com/apache/arrow-datafusion/issues/5501
I would like to make it easier for people to find, use, and contribute to DataFusion
1. Cleaning up the "landing" page in docs.rs https://docs.rs/datafusion/latest/datafusion/index.html (aka the main API documentation)
2. Remove some duplicated content
I reviewed the built docs locally
(Hopefully) Better docs

Improve contributor guide and main API landing page

---

datafusion-cli/Cargo.lock
datafusion/core/Cargo.toml
datafusion/core/src/physical_plan/sorts/cursor.rs
datafusion/core/src/physical_plan/sorts/merge.rs
datafusion/core/src/physical_plan/sorts/stream.rs

Part of #5882
```
merge sorted i64        time:   [5.3681 ms 5.3730 ms 5.3784 ms]
change: [-43.762% -43.690% -43.621%] (p = 0.00 < 0.05)
Found 4 outliers among 100 measurements (4.00%)
sort merge i64          time:   [5.6187 ms 5.6264 ms 5.6344 ms]
change: [-42.354% -42.259% -42.162%] (p = 0.00 < 0.05)
merge sorted f64        time:   [5.6240 ms 5.6307 ms 5.6386 ms]
change: [-40.730% -40.639% -40.548%] (p = 0.00 < 0.05)
Found 5 outliers among 100 measurements (5.00%)
sort merge f64          time:   [5.9045 ms 5.9124 ms 5.9207 ms]
change: [-39.173% -39.065% …
```

Specialize Primitive Cursor -- make sorts / merges on a single primitive column faster

---

datafusion/core/tests/sqllogictests/test_files/timestamps.slt
datafusion/expr/src/type_coercion/binary.rs
datafusion/optimizer/src/analyzer/type_coercion.rs

Closes #.
- remove result in temporal_add_sub_coercion()
- just match for BinaryExpr Date/Time +/- Interval

just match for BinaryExpr Date/Time +/- Interval

---

datafusion/sql/src/select.rs
datafusion/sql/tests/integration_test.rs

Related issue #5943 
See #5943 
Temporarily disable `SELECT INTO` support. But, this does not close #5943 , it does prevent confusion from users.
I will spend additional time implementing support for `SELECT INTO`.

fix: return `NotImplemented` when execute `SELECT INTO` syntax

---

datafusion/common/src/scalar.rs

Closes #5810.
Repro in the bug itself. ScalarValue returns an error for many arithmetic errors, but not overflows. 
Use `checked_*` and check results.
Tests added.
No.

Scalar arithmetic should return error when overflows.

---

datafusion/common/src/dfschema.rs
datafusion/expr/src/logical_plan/builder.rs

Closes #5850 .
Simplify modification for `DFField` nullable flag  
Yes
No

Minor: Add `DFField.with_nullable(bool)`

---

datafusion/core/src/physical_optimizer/pipeline_checker.rs
datafusion/core/src/physical_optimizer/pipeline_fixer.rs
datafusion/core/src/test_util/mod.rs
datafusion/core/tests/sql/window.rs

Closes #.
Sometimes `PipelineFixer` will receive executors that cannot run on unbounded data. In these cases currently, we generate error. However, during optimization stages these pipeline breaking executors may be removed, may be changed, etc. Hence, `PipelineFixer` shouldn't give pre-mature decisions. 
For instance, If window expression is in the form 
`SUM(inc_col) OVER(ORDER BY ts DESC ROWS BETWEEN 1 PRECEDING AND UNBOUNDED FOLLOWING) as sum1` it would be calculated with `WindowAggExec`. However, it can be converted to the equivalent form 
`SUM(inc_col) OVER(ORDER BY ts ASC ROWS BETWEEN UNBOUNDED PRECEDING AND 1 FOLLOWING) as sum1`
Second form can be calculated with `BoundedWindowAggExec` without breaking the pipeline (given that its input is already ordered with `ts ASC`).  
If …

Move error check from pipeline fixer to pipeline checker

---

datafusion/core/tests/sqllogictests/test_files/dates.slt
datafusion/core/tests/sqllogictests/test_files/timestamps.slt
datafusion/expr/src/type_coercion/aggregates.rs
datafusion/expr/src/type_coercion/binary.rs
datafusion/physical-expr/src/type_coercion.rs

Closes #5931 .
support data/timestamp minus in type coercion.
Add test in slt.

fix: support `date - timestamp` and `timestamp - date`

---

datafusion/expr/src/expr.rs
datafusion/optimizer/src/analyzer/type_coercion.rs
datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs
datafusion/optimizer/src/simplify_expressions/simplify_exprs.rs

related to https://github.com/apache/arrow-datafusion/pull/5929
While reviewing https://github.com/apache/arrow-datafusion/pull/5929 I noticed there was no way to create `Expr::Between` simply
Add `Expr::between` and `Expr::not_between`
Yes

minor: Add `Expr::between` to clean up boilerplate

---

datafusion/core/src/physical_plan/sorts/cursor.rs
datafusion/core/src/physical_plan/sorts/merge.rs
datafusion/core/src/physical_plan/sorts/stream.rs

Part of #5882 
```
merge sorted utf8 low cardinality
time:   [5.0056 ms 5.0200 ms 5.0368 ms]
change: [-24.330% -24.082% -23.834%] (p = 0.00 < 0.05)
Found 11 outliers among 100 measurements (11.00%)
5 (5.00%) high mild
6 (6.00%) high severe
sort merge utf8 low cardinality
time:   [5.7681 ms 5.7938 ms 5.8190 ms]
change: [-21.867% -21.399% -20.931%] (p = 0.00 < 0.05)
merge sorted utf8 high cardinality
time:   [7.8982 ms 7.9206 ms 7.9468 ms]
change: [-14.207% -13.879% -13.546%] (p = 0.00 < 0.05)
5 (5.00%) high severe
sort merge utf8 high cardinality
time:   [9.1147 ms 9.1690 ms 9.2234 ms]
change: [-13.848% -13.085% -12.344%] (p = 0.00 < 0.05) …
```

Specialized Cursor for StringArray and BinaryArray

---

datafusion/substrait/Cargo.toml

\-
Limit chrono features so we don't pull in time 0.1 which suffers from <https://rustsec.org/advisories/RUSTSEC-2020-0071>.
Dependency adjustment.
Existing tests pass.
\-

fix: do not depend on time 0.1

---

datafusion/core/tests/memory_limit.rs

Closes #.
While working on other stuffs, came across by change to this piece of code, the comment looks wrong now.

Minor: fix wrong code comment

---

.github/workflows/docs.yaml
.github/workflows/docs_pr.yaml
docs/source/user-guide/example-usage.md

Closes #.
Fixes failing CI https://github.com/apache/arrow-datafusion/actions/runs/4685079004/jobs/8301949150
Probably broken by https://github.com/apache/arrow-datafusion/pull/5962

minor: fix doctest that runs accidentally

---

datafusion/core/src/physical_plan/file_format/parquet.rs
datafusion/core/src/physical_plan/file_format/parquet/row_groups.rs

Closes #5995
file_offset is not the offset into the file where the column is located, but rather is the location of non-inlined metadata - https://github.com/apache/parquet-format/blob/master/src/main/thrift/parquet.thrift#L781. Some writers such as DuckDB will set it to 0, causing all row groups to be scheduled into the same partition

Don't use parquet file offset for file range pruning

---

datafusion/core/tests/sqllogictests/test_files/select.slt
datafusion/core/tests/sqllogictests/test_files/type_coercion.slt
datafusion/physical-expr/src/expressions/binary.rs

Closes #5991.
After I fix `type coercion` for `largeUtf8/utf8`, I find `largeutf8 is distinct from largeutf8` still fail.
add slt

fix: largeUtf8 don't support `is distinct from`

---

datafusion/core/src/dataframe.rs

Closes #4428
When calling `with_column_renamed("old", "new")` in DataFrame API, it should be able to look up `"old"` column name even if it is not qualified, for ease of use. 
If in plan there is column named `t1.c1` (where `t1` is the table name and `c1` is the column name) then allow "c1" for old_name to be able to refer to this column without needing to explicitly state the full qualified name
Also ensure do an ambiguity check when looking up the old column name
New unit tests added

Proper resolution for old name in with_column_renamed

---

datafusion/core/tests/sqllogictests/test_files/subquery.slt
datafusion/optimizer/src/analyzer/mod.rs

Closes #6017
Allows `values` to be used in subqueries. This previously worked in DataFusion 20.0.0
Added sqllogictest

fix: Allow values in subqueries

---

datafusion-examples/Cargo.toml
datafusion-examples/examples/csv_opener.rs
datafusion-examples/examples/json_opener.rs
datafusion/core/src/physical_plan/file_format/csv.rs
datafusion/core/src/physical_plan/file_format/json.rs
datafusion/core/src/physical_plan/file_format/mod.rs

make `JsonOpener` and `CsvOpener` public

chore: make JsonOpener and CsvOpener public

---

datafusion/core/tests/dataframe.rs
datafusion/optimizer/src/analyzer/count_wildcard_rule.rs
datafusion/optimizer/src/test/mod.rs

Closes #5473.
add more scenario
- test_count_wildcard_on_sort
- test_count_wildcard_on_where_in
- test_count_wildcard_on_where_exist
- test_count_wildcard_on_where_scalar_subquery

update count_wildcard_rule for more scenario

---

datafusion-examples/examples/rewrite_expr.rs
datafusion/core/src/execution/context.rs
datafusion/core/tests/sql/subqueries.rs
datafusion/core/tests/sqllogictests/test_files/dates.slt
datafusion/expr/src/logical_plan/plan.rs
datafusion/optimizer/src/analyzer/mod.rs
datafusion/optimizer/src/analyzer/type_coercion.rs
datafusion/optimizer/src/test/mod.rs
datafusion/optimizer/tests/integration-test.rs
datafusion/proto/proto/datafusion.proto
datafusion/proto/src/generated/pbjson.rs
datafusion/proto/src/generated/prost.rs
datafusion/proto/src/logical_plan/from_proto.rs
datafusion/proto/src/logical_plan/to_proto.rs

Closes #5598
With new separate analyzer stage, split off from logical optimizer stage, should have output of these rules in verbose explain for debugging
Example output now:
```
❯ explain verbose select * from part;
+------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| plan_type                                                  | plan …
```

Add analyzer output to verbose explain

---

datafusion/optimizer/src/test/mod.rs

Closes #.
Current CI reports the error as follow:
```
error[E0061]: this method takes 3 arguments but 2 arguments were supplied
--> datafusion/optimizer/src/test/mod.rs:131:42
|
131 |         Analyzer::with_rules(vec![rule]).execute_and_check(plan, &options)?;
|                                          ^^^^^^^^^^^^^^^^^---------------- an argument is missing
|
note: associated function defined here
--> datafusion/optimizer/src/analyzer/mod.rs:83:12
|
83  |     pub fn execute_and_check<F>(
|            ^^^^^^^^^^^^^^^^^
84  |         &self,
85  |         plan: &LogicalPlan,
|         ------------------
86  |         config: &ConfigOptions,
|         ----------------------
87  |         mut observer: F,
|         ---------------
help: provide the argument
|
131 | …
```

Minor: Fix compilation error

---

datafusion/core/tests/sqllogictests/test_files/ddl.slt
datafusion/expr/src/logical_plan/builder.rs
datafusion/expr/src/logical_plan/plan.rs
datafusion/optimizer/src/analyzer/inline_table_scan.rs
datafusion/optimizer/src/decorrelate_where_in.rs
datafusion/optimizer/src/scalar_subquery_to_join.rs
datafusion/proto/proto/datafusion.proto
datafusion/proto/src/generated/pbjson.rs
datafusion/proto/src/generated/prost.rs
datafusion/proto/src/logical_plan/mod.rs

Closes #6016.
(Opening this to get early feedback)
Simplest way I found for fixing the above issue. I didn't want to try to add an analyzer rule for swapping out references in parent nodes.
Changes `SubqueryAlias` to hold a `OwnedTableReference` instead of just a string.
Adds sqllogictests.
Yes, this changes the public interface for `SubqueryAlias`.

Use OwnedTableReference for subquery aliases

---

datafusion/expr/src/aggregate_function.rs
datafusion/expr/src/built_in_function.rs
docs/source/user-guide/sql/aggregate_functions.md
docs/source/user-guide/sql/data_types.md
docs/source/user-guide/sql/ddl.md
docs/source/user-guide/sql/explain.md
docs/source/user-guide/sql/scalar_functions.md
docs/source/user-guide/sql/select.md

Related to https://github.com/apache/arrow-datafusion/issues/3058
Update sql doc and do some touching up

Update sql doc

---

datafusion/core/benches/jit.rs
datafusion/core/src/physical_plan/aggregates/row_hash.rs
datafusion/core/tests/row.rs
datafusion/row/src/accessor.rs
datafusion/row/src/jit/mod.rs
datafusion/row/src/jit/reader.rs
datafusion/row/src/jit/writer.rs
datafusion/row/src/layout.rs
datafusion/row/src/lib.rs
datafusion/row/src/reader.rs
datafusion/row/src/writer.rs

Closes https://github.com/apache/arrow-datafusion/issues/6024.
While reviewing the latest code changes over aggregation, I found the original `RowType::Compact` row is no longer used as grouping key representation in AggregateExec; therefore remove it and re-document the row format in DataFusion a little bit.
Remove the deprecated compact row layout as well as the related implementations.
Yes, the `RowType` enum is removed, with its usages removed from related row APIs. After this change, the only layout for `RowLayout` in DataFusion is the word-aligned layout.

feat: Remove compact row since it's no longer used

---

datafusion/core/tests/sqllogictests/test_files/decimal.slt

Closes #5825.
This issue was fixed at the upstream. Now adding a test for verification.

Add test for handling precision overflow when casting from integer to decimal

---

datafusion/substrait/src/logical_plan/producer.rs
datafusion/substrait/tests/serialize.rs

Related to https://github.com/GreptimeTeam/greptimedb/issues/1396
Allow table scan without projection. It should be a constrain as the projection field in `TableScan` plan is optional:
https://github.com/apache/arrow-datafusion/blob/3ad7734a7e5b1844b02f1374d0dc1c441bef216d/datafusion/expr/src/logical_plan/plan.rs#L1396-L1403
Don't throw error when there is no projection in `TableScan`.
Yes
Yes but not breaking

feat: allow TableScan without projection

---

datafusion/common/src/scalar.rs
datafusion/core/src/physical_plan/aggregates/row_hash.rs
datafusion/core/tests/sql/aggregates.rs
datafusion/physical-expr/src/aggregate/average.rs
datafusion/physical-expr/src/aggregate/count.rs
datafusion/physical-expr/src/aggregate/min_max.rs
datafusion/physical-expr/src/aggregate/row_accumulator.rs
datafusion/physical-expr/src/aggregate/sum.rs
datafusion/row/src/accessor.rs

Closes #6002 .
improve the Aggregator performance when group by high cardinality columns.
1) add `update_scalar()` method to `RowAccumulator`  trait
2) Adaptively decide the accumulators update mode
I had test this on my local Mac.
For TPCH-q17, there is at about 40% improvement.
Before this PR:
Running benchmarks with the following options: DataFusionBenchmarkOpt { query: Some(17), debug: false, iterations: 3, partitions: 1, batch_size: 8192, path: "./parquet_data", file_format: "parquet", mem_table: false, output_path: None, disable_statistics: false, enable_scheduler: false }
Query 17 iteration 0 took 1888.9 ms and returned 1 rows
Query 17 iteration 1 took 1851.8 ms and returned 1 rows
Query 17 iteration 2 took 1853.1 ms and returned 1 rows
Query 17 avg time: 1864.61 ms
After this PR: …

Row accumulator support update Scalar values

---

datafusion/core/src/physical_optimizer/sort_enforcement.rs

Closes #.
Some struct referenced in sort_enforcement optimizer rule are not linked
Some minor style changes that
- add a new line under mod comment
- add link to referenced struct

Minor: tweak docuement of sort enforcement optimizer rule

---

ci/scripts/rust_docs.sh

Related to https://github.com/apache/arrow-datafusion/issues/6042. Follow on to https://github.com/apache/arrow-datafusion/pull/6044 
I often use `rust_lint.sh` to ensure my PR will pass CI. 
Add a `rust_docs.sh` script so that `./dev/rust_lint.sh` also runs the newly added check in https://github.com/apache/arrow-datafusion/pull/6044 
I tested them manually
No

Update rust_lint.sh to include newly added `cargo doc` check

---

datafusion/common/src/dfschema.rs
datafusion/expr/src/expr_schema.rs
datafusion/expr/src/field_util.rs

\-
Helps debugging.
Require `Debug` where it is sensible and improve error message.
\-
\-

Minor: assorted schema handling debug improvements

---

datafusion/physical-expr/src/expressions/binary/kernels.rs

Closes #6066 .
- Use arrow::compute::binary as the bitwise_op kernel for array bitwise_op
- Use arrow::compute::unary as the bitwise_op_scalar kernel.
- Currying the $METHOD in bitwise_op_scalar function.
Covered by unit tests in binary.rs.
No

fix: Use arrow bitwise_op as binary_kernels

---

datafusion/common/src/dfschema.rs
datafusion/core/tests/sqllogictests/test_files/aggregate.slt
datafusion/core/tests/sqllogictests/test_files/groupby.slt
datafusion/expr/src/logical_plan/plan.rs
datafusion/optimizer/src/eliminate_duplicated_expr.rs

fix: allow group by same expr in Aggregate

---

datafusion/common/src/scalar.rs

Fixes #6083.
I should be possible to create a truly NULL struct, not only a struct w/ all-NULL members.
Fix NULL handling for `ScalarValue::Struct(None, ...)`.
1. existing tests pass
2. new test that checks `ScalarValue::to_array` and `ScalarValue::iter_to_array`
`ScalarValue::Struct(None, ...)` now produces true NULL values that also pass the arrow `is_null` kernel.

fix: null handling of `ScalarValue::Struct`

---

datafusion/expr/src/logical_plan/builder.rs
datafusion/optimizer/src/simplify_expressions/context.rs
datafusion/optimizer/src/simplify_expressions/simplify_exprs.rs

Closes #5996.
Fixing this will allow lots of expression simplification to succeed where it failed before.
In IOx we would like to be able to run the logical optimizer with `skip_failed_rules` set to `false`, since some of our custom rules are required to run and produce user-facing errors.
When I ran IOx tests with `skip_failed_rules` set to `false`, I found issue #5996.
The issue is with the `SimplifyExpressions` logical rule. As it traverses the logical plan, it includes both the output schema for the current node and the merged input schema from the node's inputs.
The inclusion of two schemas causes an issue when various expression simplifiers inquire about attributes of expressions, e.g., here, which was the case for #5996:
https://github.com/apache/arrow-datafusion/blob/011adc203e4a02 …

fix: make simplify_expressions use a single schema for resolution

---

datafusion/substrait/src/logical_plan/consumer.rs
datafusion/substrait/src/logical_plan/producer.rs
datafusion/substrait/tests/roundtrip_logical_plan.rs

Closes #6058.
Please refer to related [issue](https://github.com/apache/arrow-datafusion/issues/6058).
- Producer: handle duplicate qualified fields by returning the join's output schema
- Consumer: handle duplicate qualified fields by returning the join's output schema
- Test: add test with `INTERSECT` with table/column reuse
Yes
No

Substrait: Handle multiple select with the same table/columns in INTERSECT

---

datafusion-cli/Cargo.lock
datafusion/optimizer/Cargo.toml
datafusion/optimizer/src/simplify_expressions/regex.rs
datafusion/physical-expr/Cargo.toml

Closes https://github.com/apache/arrow-datafusion/pull/6092
Keep up with dependencies
See title
Existing tests
No

chore(deps): update regex and regex-syntax requirement from 0.6.28 to 0.7.1

---

datafusion/core/src/execution/context.rs

feat: add version field to ExecutionContext

---

datafusion/physical-expr/src/expressions/binary.rs
datafusion/physical-expr/src/expressions/binary/kernels.rs

Related to https://github.com/apache/arrow-datafusion/issues/6066
While reviewing https://github.com/apache/arrow-datafusion/pull/6093 from @RTEnzyme I noticed there were kernels in arrow-rs for some of the bitwise operations: https://docs.rs/arrow/latest/arrow/compute/kernels/bitwise/index.html
Use the kernels from arrow-rs rather than redefining them in datafusion
No

Use arrow kernels for bitwise operations

---

datafusion/common/src/config.rs
datafusion/execution/src/config.rs

Closes #6110.
When Ballista wants to customize the Datafusion configurations, with provided string map, currently it has to list all of the configurations and customize the related configurations. It's better for the SessionConfig to provide a method to construct a 
SessionConfig with string map.

Add from_string_hash_map() method for SessionConfig

---

datafusion/core/src/datasource/memory.rs
datafusion/core/src/physical_plan/mod.rs

Closes #.
This makes it consistent with RepartitionExec and CoalescePartitionsExec

Parallelise collect_partitioned

---

datafusion/core/src/physical_plan/aggregates/mod.rs
datafusion/core/src/physical_plan/projection.rs
datafusion/core/tests/sqllogictests/test_files/groupby.slt
datafusion/physical-expr/src/lib.rs
datafusion/physical-expr/src/utils.rs

Fix column mapping in output_ordering() and output_partitioning() for ProjectionExec and AggregateExec

---

datafusion/physical-expr/src/utils.rs

Related to upstream ticket https://github.com/influxdata/influxdb_iox/issues/7644
We need to also re-assign the schema stored within `InListExpr` at the same time when we replace the children.
This bug affects both the public API `reassign_predicate_columns` as well as potential internal use of it.
Bugfix.
New test.
\-

fix: `reassign_predicate_columns` w/ in-list expr

---

Cargo.toml
datafusion-cli/Cargo.lock
datafusion-cli/Cargo.toml
datafusion-examples/examples/flight_sql_server.rs
datafusion/common/src/scalar.rs
datafusion/core/src/physical_plan/file_format/json.rs
datafusion/core/src/physical_plan/sorts/sort.rs
datafusion/core/tests/sqllogictests/test_files/arrow_typeof.slt
datafusion/physical-expr/src/expressions/binary.rs

Update to arrow 38

---

datafusion/expr/src/logical_plan/dml.rs
datafusion/expr/src/logical_plan/mod.rs
datafusion/expr/src/logical_plan/plan.rs
datafusion/expr/src/logical_plan/statement.rs

Related to https://github.com/apache/arrow-datafusion/issues/1281
I am trying to improve the organization of `LogicalPlan` and would like the code to mirror the structure
extract DML related plan structures into a new module
Covered by existing tests 
No, the imports are updated so there should be no API changes

Minor: Split `DmlStatement` into its own module

---

datafusion/core/src/dataframe.rs
datafusion/core/src/execution/context.rs

While working on https://github.com/apache/arrow-datafusion/pull/6106 I noticed a method that doesn't make sense and isn't used in the codebase, so it should be marked deprecated
I also noticed that several other deprecated methods didn't have a `since` marking so I added a conservative one
A method is marked as deprecated -- I don't think anyone actually uses this

Minor: Mark default_session_builder deprecated, add since markings

---

datafusion/core/tests/sqllogictests/test_files/tpch.slt
datafusion/physical-expr/src/expressions/binary/kernels_arrow.rs

Make decimal multiplication allow precision-loss in DataFusion

---

datafusion/core/src/execution/context.rs
datafusion/core/src/physical_plan/planner.rs
datafusion/expr/src/logical_plan/ddl.rs
datafusion/expr/src/logical_plan/mod.rs
datafusion/expr/src/logical_plan/plan.rs
datafusion/expr/src/utils.rs
datafusion/optimizer/src/common_subexpr_eliminate.rs
datafusion/proto/src/logical_plan/mod.rs
datafusion/sql/src/statement.rs

Extract `LogicalPlan::Drop*` DDL related plan structures into `LogicalPlan::Ddl`
Closes https://github.com/apache/arrow-datafusion/issues/1281
While reviewing https://github.com/apache/arrow-datafusion/pull/6096 from @jaylmiller  I noticed that the LogicalPlan was getting quite large for the various Catalog manipulation statements
Move `LogicalPlan::Drop*` variants into `LogicalPlan::Ddl`  to keep them more isolated
Yes, this is an API change -- some LogicalPlan variants are now wrapped up another layer of struct

Complete Extracting LogicalPlan::Drop* DDL related plan structures into LogicalPlan::Ddl

---

datafusion/optimizer/src/common_subexpr_eliminate.rs

Fixes #6116.
`common_subexpr_eliminate` MUST NOT push aggregate functions into the `LogicalPlan::Aggregate` child.
Fixed and improved logic for aggregates.
- existing tests pass (modulo `aggregate`)
- fixed and extended `aggregate` test
Probably no changes for SQL users. This mostly affects Rust API users that manually construct logical plans (e.g. for other query languages).

fix: `common_subexpr_eliminate` and aggregates

---

datafusion/core/tests/sqllogictests/test_files/scalar.slt
datafusion/sql/src/expr/value.rs

This issue reply https://github.com/apache/arrow-datafusion/issues/3448#issuecomment-1368607406 mentioned after a fix in sqlparser-rs, now datafusion should support scientific notations.
1. Remove old `unimplemented()` code for scientific notations
2. Add tests for scientific notations
Yes, now values in scientific notations should be supported

Add support for scientific notation (remove old unimplemented() for scientific notation)

---

datafusion/common/src/lib.rs
datafusion/common/src/schema_reference.rs
datafusion/core/src/catalog/catalog.rs
datafusion/core/src/execution/context.rs
datafusion/core/tests/sqllogictests/test_files/ddl.slt
datafusion/core/tests/sqllogictests/test_files/information_schema.slt
datafusion/expr/src/logical_plan/ddl.rs
datafusion/expr/src/logical_plan/mod.rs
datafusion/proto/src/logical_plan/mod.rs
datafusion/sql/src/statement.rs

Closes #6027
Being able to drop schemas is generally just a good feature to have: exists in most databases.
- Add optional method `deregister_schema` to `CatalogProvider` trait (and an impl for it in `MemoryCatalogProvider`)
- Add a new LogicalPlan node `DropCatalogSchema`
- Modify parser to be able to parse `LogicalPlan::DropCatalogSchema`
- Implement dropping schema in the datafusion context
Unit tests and sql integration tests
this is a user-facing feature but everything is backwards compatible.

Support DROP SCHEMA statements

---

benchmarks/compare.py

Part of https://github.com/apache/arrow-datafusion/issues/6127
I want to be able to easily understand what is being compared and reported. Currently the reporting from `compare.py` is somewhat opaque: 
1. It averages benchmark run timings (which increases the variance)
2. The header columns are non sensical
1. Use `min` of the iteration times to report the benchmark results -- I think this minimizes run to run variance and is the fairest way to asses performance
2. Use the filename as the column header
No, it is a tool only change
Not really
(note the bad headers)
```shell
python3 compare.py results/alamb_bench/tpch.json results/alamb_bench/tpch_mem.json
┏━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Query        ┃ /Users/alam… ┃           -o ┃        Change ┃ …
```

Improve `compare.py` output to use `min` times and better column titles

---

datafusion/core/src/physical_plan/aggregates/mod.rs

N/A
I was confused when reading `AggregateExec` `GroupByOrderMode` documentation due to invalid example.
Documentation update.
Yes
No

Fix GroupByOrderMode documentation

---

datafusion/core/tests/sqllogictests/test_files/timestamps.slt
datafusion/optimizer/src/optimizer.rs

This does not close an issue but is related to https://github.com/apache/arrow-datafusion/issues/6108
In IOx we use a logical planner rule to transform plans to support time series gap filling. Sometimes, a user has submitted invalid SQL that we cannot handle. In this case we want to generate a user-facing error message from the optimizer rule. It makes sense to use something besides `DataFusion::Internal` for this case.
Downstream IOx issue: https://github.com/influxdata/influxdb_iox/issues/7330
This just makes it so that when a rule invocation returns an error, it is not wrapped in `DataFusionError::Internal`.
I ran the existing suite of tests, and updated a SQL logic test. This is just a change to how errors are returned from  the logical planner when `skip_failed_rules` is `false`, …

refactor: optimizer shouldn't assume failed rules are internal error

---

datafusion/expr/src/function.rs
datafusion/expr/src/signature.rs

Related to https://github.com/apache/arrow-datafusion/pull/6149
When adding a new function, it is important to update the metadata appropriately. However, when @izveigor missed one place in https://github.com/apache/arrow-datafusion/pull/6149 the resulting runtime error was quite confusing - https://github.com/apache/arrow-datafusion/pull/6149#issuecomment-1530038460. It would be much better if the compiler told us the problem.
Replace a default match arm with all explicit patterns for clarity
no

minor: remove default match for function signature

---

datafusion/optimizer/src/common_subexpr_eliminate.rs

\-
An oversight in #6129 which would let the newly added test `aggregate_with_releations_and_dots` fail w/:
```text
SchemaError(FieldNotFound { field: Column { relation: None, name: "table.test.col.a" }, valid_fields: [Column { relation: Some(Partial { schema: "table", table: "test" }), name: "col.a" }, Column { relation: None, name: "AVG(UInt32(1) + table.test.col.atable.test.col.aUInt32(1) AS UInt32(1) + table.test.col.a)UInt32(1) + table.test.col.atable.test.col.aUInt32(1) AS UInt32(1) + table.test.col.a" }] })
```
Fix.
New test `aggregate_with_releations_and_dots`
Bugfix.

fix: `common_subexpr_eliminate` w/ aggregates and relations

---

benchmarks/bench.sh

Follow on to https://github.com/apache/arrow-datafusion/pull/6131
Add support for running parquet filter and sort benchmarks to sort
You can now run
```shell
bench.sh run sort
```
and 
```shell
bench.sh run parquet
```
to run benchmarks

Add parquet filter and sort to bench.sh

---

datafusion/common/src/delta.rs
datafusion/physical-expr/src/expressions/datetime.rs

Noticed while reviewing https://github.com/apache/arrow-datafusion/pull/6196
These tests are for a function in another file
Move the tests to be with the code they are testing
only tests
no

minor: Move shift_date tests to be with code

---

datafusion/core/src/physical_plan/planner.rs
datafusion/core/tests/sqllogictests/test_files/window.slt
datafusion/expr/src/window_frame.rs

Closes #6207 .
Change not user friendly `Datafusion::Internal` error messages to `Datafusion::Plan`
Yes
Error format will change

minor: change error type for window expressions

---

datafusion/core/src/physical_plan/planner.rs
datafusion/core/tests/sqllogictests/test_files/dates.slt
datafusion/core/tests/sqllogictests/test_files/timestamps.slt
datafusion/expr/src/type_coercion/binary.rs
datafusion/physical-expr/src/expressions/datetime.rs
datafusion/physical-expr/src/intervals/cp_solver.rs
datafusion/physical-expr/src/intervals/interval_aritmetic.rs

Closes #.
`coerce_type` current mix many motivation in it. 
- get_result_type
- get_common_type
- check type convert
I prepare to split it into `get_result_type` and `get_common_type `
about check type convertion #6223
separate get_result_type from coerce_type.

refactor: separate get_result_type from `coerce_type`

---

datafusion/core/src/datasource/listing_table_factory.rs
datafusion/core/src/physical_plan/file_format/mod.rs
datafusion/core/tests/sqllogictests/test_files/ddl.slt

Part of porting tests to sqllogic test https://github.com/apache/arrow-datafusion/pull/6234
Some tests in `window.rs` programmatically create "infinite" external tables. I want to port them to SQL and thus I need to be able to do the same thing programatically
Add support for `('infinite_source', 'true1')` in `CREATE EXTERNAL TABLE`:
```sql
CREATE external table t ...
OPTIONS('infinite_source' 'true')
LOCATION 'tests/data/empty.csv';
```
Add a `infinite_source=true` in the explain plan (which is super easy after https://github.com/apache/arrow-datafusion/pull/6202 from @tz70s ❤️ )
```
logical_plan TableScan: t projection=[c1]
physical_plan CsvExec: file_groups={1 group: [[WORKSPACE_ROOT/datafusion/core/tests/data/empty.csv]]}, projection=[c1], infinite_source=true, has_header=true
```
yes …

Minor: allow creating infinite external tables via SQL (for testing)

---

datafusion/core/tests/sqllogictests/test_files/dates.slt
datafusion/core/tests/sqllogictests/test_files/interval.slt
datafusion/core/tests/sqllogictests/test_files/timestamps.slt
datafusion/expr/src/type_coercion/binary.rs

Closes #.
related to https://github.com/apache/arrow-datafusion/issues/5927
following https://github.com/apache/arrow-datafusion/pull/6221
- separate result type into new file
- separate  get common type / get result type for temporal type
- refactor code of handling type for temporal type

refactor: separate get_common_type / get_result_type for temporal type

---

datafusion/core/tests/dataframe.rs
datafusion/expr/src/utils.rs

Closes #6237.
`projection_push_down` don't consider VarProvider in columns.

fix: `projection_push_down` don't consider VarProvider in columns.

---

datafusion/sql/src/parser.rs
docs/source/user-guide/sql/ddl.md

When writing tests yesterday it was quite challenging to remember the exact CREATE EXTERNAL table syntax so I want to document it for next time
add doc comments and update DDL user guide
N/A
Docs

Minor: document syntax of CREATE EXTERNAL TABLE

---

datafusion/core/tests/sqllogictests/test_files/create_external_table.slt
datafusion/sql/src/parser.rs

Closes #6248
N/A
- Modify create external table parser
- Add some tests
Yes
No

Enable parser to parse create external clauses in arbitrary order

---

datafusion/core/src/physical_plan/planner.rs
datafusion/expr/src/expr.rs
datafusion/expr/src/expr_schema.rs
datafusion/expr/src/tree_node/expr.rs
datafusion/expr/src/udaf.rs
datafusion/optimizer/src/analyzer/type_coercion.rs
datafusion/optimizer/src/common_subexpr_eliminate.rs
datafusion/proto/src/logical_plan/from_proto.rs
datafusion/proto/src/logical_plan/mod.rs
datafusion/proto/src/logical_plan/to_proto.rs
datafusion/sql/src/expr/function.rs
datafusion/sql/src/utils.rs

Related to https://github.com/apache/arrow-datafusion/issues/2175 and https://github.com/apache/arrow-datafusion/issues/3807.
refactor: Expr::AggregateUDF  to use a struct

refactor: Expr::AggregateUDF  to use a struct

---

datafusion/expr/src/expr.rs
datafusion/expr/src/expr_fn.rs
datafusion/expr/src/logical_plan/plan.rs
datafusion/optimizer/src/analyzer/count_wildcard_rule.rs
datafusion/optimizer/src/analyzer/inline_table_scan.rs
datafusion/optimizer/src/analyzer/mod.rs
datafusion/optimizer/src/analyzer/type_coercion.rs
datafusion/optimizer/src/decorrelate_where_exists.rs
datafusion/sql/src/expr/subquery.rs

Related to https://github.com/apache/arrow-datafusion/issues/2175 and https://github.com/apache/arrow-datafusion/issues/3807.
Refactor Expr::Exists to a struct.
Yes.

refactor: Expr::Exists to use a struct.

---

datafusion/core/tests/sqllogictests/test_files/interval.slt
datafusion/core/tests/sqllogictests/test_files/type_coercion.slt
datafusion/sql/src/expr/mod.rs
datafusion/sql/src/expr/value.rs

Closes #6205.
Due to sqlparser lack of semantic, we need to rewrite the AST in datafusion.
For example, this is valid in sqlparser:
```
SELECT INTERVAL `1 month` + `1 month`
```
This is also valid:
```
SELECT INTERVAL '1 month' + '2012-01-01'::date;
```
Both generates structurally similar interval expression with BinaryOp +.
The first statement generates the following AST (SELECT omitted):
```
Interval
BinaryOp
Value(StringLiteral)
Value(StringLiteral)
```
The second statement generates the following AST (SELECT omitted):
```
Interval
BinaryOp
Value(StringLiteral)
Cast
Value(StringLiteral)
```
I don't think this can be handled in sqlparser because sqlparser doesn't have the semantic to understand which BinaryOp + cast is and isn't allowed.
This PR transforms the 2nd AST (or any AST with …

Support `interval '1 month' + date/timestamp`: Handle binary op interval in logical AST builder  

---

datafusion/core/src/datasource/listing/helpers.rs
datafusion/core/src/physical_plan/planner.rs
datafusion/expr/src/expr.rs
datafusion/expr/src/expr_fn.rs
datafusion/expr/src/expr_schema.rs
datafusion/expr/src/logical_plan/plan.rs
datafusion/expr/src/tree_node/expr.rs
datafusion/expr/src/utils.rs
datafusion/optimizer/README.md
datafusion/optimizer/src/analyzer/count_wildcard_rule.rs
datafusion/optimizer/src/analyzer/inline_table_scan.rs
datafusion/optimizer/src/analyzer/mod.rs
datafusion/optimizer/src/analyzer/type_coercion.rs
datafusion/optimizer/src/decorrelate_where_in.rs
datafusion/optimizer/src/push_down_filter.rs
datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs
datafusion/proto/src/logical_plan/to_proto.rs
datafusion/sql/src/expr/subquery.rs
datafusion/sql/src/utils.rs

Related to #2175 and #3807.
Refactor Expr::InSubquery to use a struct.

Refactor: Expr::InSubquery to use a struct

---

datafusion/core/src/datasource/listing/helpers.rs
datafusion/core/src/datasource/listing_table_factory.rs
datafusion/core/src/physical_plan/planner.rs
datafusion/expr/src/expr.rs
datafusion/expr/src/expr_schema.rs
datafusion/expr/src/logical_plan/plan.rs
datafusion/expr/src/tree_node/expr.rs
datafusion/expr/src/utils.rs
datafusion/optimizer/src/push_down_filter.rs
datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs
datafusion/proto/src/logical_plan/from_proto.rs
datafusion/proto/src/logical_plan/to_proto.rs
datafusion/sql/src/expr/mod.rs
datafusion/sql/src/expr/value.rs
datafusion/sql/src/statement.rs
datafusion/sql/src/utils.rs

related https://github.com/apache/arrow-datafusion/issues/2175 
close https://github.com/apache/arrow-datafusion/issues/3807.

refactor: Expr::PlaceHolder to use a struct

---

datafusion/core/tests/sqllogictests/test_files/aggregate.slt
datafusion/physical-expr/src/expressions/binary.rs

Fix inconsistent array type for binary numerical operators result between array and scalar

---

datafusion/core/src/physical_plan/common.rs
datafusion/core/src/physical_plan/explain.rs
datafusion/core/tests/provider_filter_pushdown.rs

Closes #.
SizedRecordBatchStream doesn't actually perform memory tracking despite its name, and whilst it does call record_poll, none of the consumers are hooked up in such a way to actually surface this. It seemed simpler and less confusing to just remove this construct

Remove SizedRecordBatchStream

---

datafusion/core/tests/sqllogictests/test_files/create_external_table.slt
datafusion/sql/src/parser.rs

Closes #6288 
- Modify create external table parser
- Add some tests

Improve error message for CREATE EXTERNAL TABLE

---

datafusion/common/src/scalar.rs
datafusion/core/tests/sqllogictests/test_files/interval.slt
datafusion/expr/src/type_coercion/mod.rs
datafusion/physical-expr/src/expressions/negative.rs

feat: negation of `Intervals`

---

datafusion/physical-expr/src/expressions/case.rs

Closes #6333 
The update to `remainder` is incorrect when `when_match` contains NULLs.
Treat NULLs as false.
YES
No
<!--
If there are any breaking changes to public APIs, please add the `api change` label.
No

Fix case evaluation with NULL

---

datafusion/expr/src/type_coercion/binary.rs
datafusion/physical-expr/src/expressions/binary/kernels_arrow.rs

Closes #6278, bring the performance back.
For decimal multiply,  avoid casting to the wider type, decimals can multiply decimals directly.
Main branch:
Running benchmarks with the following options: DataFusionBenchmarkOpt { query: Some(1), debug: false, iterations: 3, partitions: 1, batch_size: 8192, path: "./parquet_data", file_format: "parquet", mem_table: false, output_path: None, disable_statistics: true }
Query 1 iteration 0 took 1716.3 ms and returned 4 rows
Query 1 iteration 1 took 1697.0 ms and returned 4 rows
Query 1 iteration 2 took 1694.3 ms and returned 4 rows
Query 1 avg time: 1702.52 ms
Branch 23 (Tag 23.0.0):
Running benchmarks with the following options: DataFusionBenchmarkOpt { query: Some(1), debug: false, iterations: 3, partitions: 1, batch_size: 8192, path: …

refine decimal multiply, avoid cast to wider type

---

datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs
datafusion/optimizer/src/simplify_expressions/simplify_exprs.rs

None
`expr_non_null IS NOT NULL`  is always true
`expr_non_null IS NULL`  is always false
They are a type of predicate that is either unnecessary or impossible.
By simplifying them, we can gain more opportunities for optimization.  
For example：
1. `SELECT * FROM t WHERE col_non_null IS NOT NULL` --(Simplify)--> `SELECT * FROM t WHERE TRUE` --(EliminateFilter)--> `SELECT * FROM t`
2.  `SELECT * FROM t WHERE col_non_null IS NULL` --(Simplify)--> `SELECT * FROM t WHERE FALSE` --(EliminateFilter)--> `<EmptyRelation>`
Yes
No

Simplify IsNotNull and IsNull expression

---

docs/source/contributor-guide/index.md

N/A 
@mustafasrepo  and I had a good conversation on https://github.com/apache/arrow-datafusion/pull/6234 (https://github.com/apache/arrow-datafusion/pull/6234#issuecomment-1542157223) about the rationale for sqllogictests and I wanted to include a summary of that discussion in the docs
Update the contribution guide to be clearer about tests and the *why* of DataFusion using sqllogictests
N/A
Docs

Minor: Update the testing section of contributor guide

---

datafusion/core/tests/sqllogictests/test_files/aggregate.slt
datafusion/physical-expr/src/aggregate/min_max.rs
datafusion/physical-expr/src/expressions/mod.rs
datafusion/row/src/accessor.rs

\-
Min/max for bools is supported by Rust stdlib, arrow and by `ScalarValue` but wasn't exposed by the min/max aggregator.
Min/max aggregator support for bool.
Two new tests.
Min/max aggregation w/ bool should work now.

feat: min/max agg for bool

---

datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs
datafusion/optimizer/src/simplify_expressions/regex.rs

Closes #6367.
This should be a performance improvement for queries that contain this pattern, and it may also be easier to push down predicates that use `=` or `!=` rather than regexes.
It will also make it easier to find predicates that are looking for the empty string (an important case for [IOx's InfluxQL support](https://github.com/influxdata/influxdb_iox/issues/6902)).
This adds a pattern to `ExprSimplifier` to find regexes of the form `^foo$` and uses them to compare with a string literal instead of doing regex matching.
I included unit tests with the other regex simplifications that are performed. I also tested manually with `datafusion-cli`.
No.

feat: add pattern for simplifying exprs like `str ~ '^foo$'`

---

datafusion/optimizer/src/simplify_expressions/regex.rs

N/A
I noticed this while reviewing https://github.com/apache/arrow-datafusion/pull/6369 from @wolffcm 
Remove `println!`
N/A
Less random console spew

Minor: remove left over println

---

datafusion/core/src/physical_plan/file_format/mod.rs
datafusion/core/src/physical_plan/planner.rs

Closes #6358.
When a sql needs to hit thousands of files, the content of thousands of partition files shown by the FileGroupsDisplay is too much.
Only at most 5 of them will be shown. Others will be replaced by `...`

Limit the number of partition files to be displayed for FileGroupsDisplay

---

datafusion/sql/Cargo.toml
datafusion/sql/src/expr/binary_op.rs
datafusion/sql/src/expr/mod.rs

Closes #6040
Closes #1444 
Closes #1434 
Not sure why anyone would want more than 256 expressions but I thought I would write the iterative version just for fun. Now users can write all the expressions they want (or at least until the generated `Expr` can no longer fit in the stack).
Kudos to @alamb and @houqp for suggesting this iterative version.
- Iterative version of expr logical plan builder
- Add tests verifying the number of expressions that can be handled is now larger
Yes. Tested by existing tests. Also added a few stack overflow tests.
No

Switch to non-recursive on heap virtual stack when building logical plan from SQL expression

---

datafusion/core/tests/sqllogictests/test_files/union.slt
datafusion/expr/src/logical_plan/builder.rs

Closes #6139 .
Fixes bunch of UNION ALL alias related bugs like
- wrong output alias. Should be A
```
❯  select 1 a group by a union all select 2 b;
+---+
| b |
+---+
| 2 |
| 1 |
+---+
```
- Wrong internal input aliasing
```
❯ create table t as select 1 a union all select 1 b;
Error during planning: Mismatch between schema and batches
❯ create table t as select 1 a group by a union all select 2 b;
Error during planning: Mismatch between schema and batches
```

Fix UNION ALL aliasing

---

datafusion/core/src/datasource/file_format/parquet.rs

Closes #.
Inferring parquet metadata is largely IO bound, especially when interacting with remote stores or when there is no parquet size hint. As such it makes sense to attempt to run in parallel.

Concurrent Parquet Schema Inference

---

datafusion/core/src/datasource/file_format/parquet.rs

Follow up to https://github.com/apache/arrow-datafusion/pull/6366 as suggested here https://github.com/apache/arrow-datafusion/pull/6366#r1196984754

Minor: used named constant for the schema inference concurrency limit

---

datafusion/core/tests/sqllogictests/test_files/select.slt
datafusion/physical-expr/src/expressions/binary.rs
datafusion/physical-expr/src/expressions/binary/kernels_arrow.rs

Support is [not] distinct from for binaryarray types

---

datafusion/execution/src/memory_pool/mod.rs
datafusion/execution/src/memory_pool/pool.rs

Related to #3058 
While reviewing https://github.com/apache/arrow-datafusion/pull/6382 I realized that the `MemoryPool` abstraction could be better documented / explained. 
Extended Docstrings for `MemoryPool`, etc.
N/A
Docs

Minor: Improve documentation of `MemoryPool`

---

datafusion/core/src/physical_plan/file_format/mod.rs

Closes #6381
introduces a `map_schema` method that maps the file schema to the table schema, and a `SchemaMapping` structure to hold the mapping and necessary type conversions. 
Yes

feat: support type cast in SchemaAdapter

---

datafusion/core/src/execution/context.rs
datafusion/execution/src/registry.rs
datafusion/expr/src/logical_plan/extension.rs
datafusion/substrait/Cargo.toml
datafusion/substrait/src/logical_plan/consumer.rs
datafusion/substrait/src/logical_plan/producer.rs
datafusion/substrait/src/serializer.rs
datafusion/substrait/tests/roundtrip_logical_plan.rs
datafusion/substrait/tests/serialize.rs

Closes https://github.com/apache/arrow-datafusion/issues/6335.
Accomplish the serialize/deserialize part for logical plan extension.
- A new field in `SessionState`: `ExtensionDeserializer`
This is the registry (or dispatcher) of all extension's deserializer methods. In this PR only `UserDefinedLogicalPlan` is included.
- Two new methods on `UserDefinedLogicalPlan`: `serialize` and `deserialize`
Yes
Yes as described above. But both of them are non-breaking

feat: implement serialize/deserialize for extension logical plan

---

datafusion/core/tests/sqllogictests/src/main.rs
datafusion/core/tests/sqllogictests/src/setup.rs

Closes https://github.com/apache/arrow-datafusion/issues/6399
If a feature is not enabled, we should not fail tests . This test was newly added in https://github.com/apache/arrow-datafusion/pull/6362 by @e1ijah1 👋 ❤️  but has the unfortunate property that running `cargo test -p datafusion` now fails because `avro.slt` will only pass if the `avro` feature is enabled
Change sqllogictest so that it does not run avro.sql if the `avro` feature is not available
Yes
You can now do:
```shell
RUST_LOG=debug cargo test -p datafusion --test sqllogictests -- avro
```
And it will pass
```
Finished test [unoptimized + debuginfo] target(s) in 0.28s
Running tests/sqllogictests/src/main.rs (/Users/alamb/Software/target-df/debug/deps/sqllogictests-ef50afea7db0aec6)
[2023-05-23T10:59:09Z INFO …
```

Do not run avro sqllogictests tests unless the avro feature is enabled

---

datafusion-cli/Cargo.lock
datafusion/common/Cargo.toml

re https://github.com/apache/arrow-datafusion/pull/6164
@yjshen  removed the other cranelift dependencies in  https://github.com/apache/arrow-datafusion/pull/6164
This one appears to have been left over
Remove another unnecessary dependency

Minor: remove unecessary cranelift dependency

---

datafusion/core/tests/sqllogictests/test_files/errors.slt
datafusion/core/tests/sqllogictests/test_files/scalar.slt
datafusion/expr/src/function.rs
datafusion/expr/src/function_err.rs
datafusion/expr/src/lib.rs
datafusion/physical-expr/src/functions.rs

https://github.com/apache/arrow-datafusion/issues/6396
Currently, the error message for the built-in scalar function signature mismatch is not straightforward.
The error message before and after this change is shown below:
(There are 5 different function signature types(variadic, exact...) from internal implementation, 1 function is chosen from each type)
```
[BEFORE]DataFusion CLI v25.0.0
❯ select concat();
Internal error: Builtin scalar function concat does not support empty arguments. This was likely caused by a bug in DataFusion's code and we would welcome that you file an bug report in our issue tracker
❯ SELECT nullif(1);
Error during planning: Coercion from [Int64] to the signature Uniform(2, [Boolean, UInt8, UInt16, UInt32, UInt64, Int8, Int16, Int32, Int64, Float32, Float64, …
```

Improve error message for wrong built-in scalar function signatures.

---

datafusion/optimizer/src/common_subexpr_eliminate.rs

Fixes #6277.
Having a single method w/ all optimization algorithms lets rustc+LLVM pick the largest possible stack size over all branches when compiled under the `dev` profile (e.g. for tests). So even if there's a deeply nested projection (e.g. for `tpcds_logical_q64`), we pay for the more complex aggregation optimization with every recursion.
Splitting the method into sub-methods seems to fix this.
Just moving code around, no functional change.
Manually w/:
```bash
#!/usr/bin/env bash
pushd datafusion/core
export RUST_MIN_STACK=1800000
exec "$@"
```
and
```console
$ cargo with './exec.sh {bin} {args}' -- test -p datafusion --test tpcds_planning -- tpcds_logical_q64 --nocapture
```
Less stack usage.

refactor: split `CommonSubexprEliminate::try_optimize`

---

datafusion/physical-expr/src/expressions/binary.rs

Closes #.
This is a follow up to #6269.
As we try on upgrading to latest DataFusion 25.0.0 internally, just found this issue. In DataFusion, for numerical operators between Dictionary array (lhs) and literal (rhs), the type of rhs literal will be coerced to Scalar::Dictionary. Although the operation is still between array and literal, the result datatype can be aligned with the operation between array and array.
That's why #6269 is proposed to convert the result between array and literal to match the one between array and array.
But in our case, we don't rely on query analysis and optimization of DataFusion but directly go for physical execution, our query doesn't go through the coercion phase. So the operation is between Dictionary array and original literal (without coerced to …

Skip casting result array for binary numerical operators result between array and scalar if possible

---

datafusion/physical-expr/src/lib.rs
datafusion/physical-expr/src/utils.rs

I found this while reviewing https://github.com/apache/arrow-datafusion/pull/6452 so figured I would propose to remove it entirely

Minor: remove dead code `sort_expr_list_eq_strict_order`

---

datafusion/core/tests/simplification.rs
datafusion/core/tests/sqllogictests/test_files/explain.slt
datafusion/core/tests/sqllogictests/test_files/join.slt
datafusion/expr/src/field_util.rs
datafusion/expr/src/logical_plan/display.rs
datafusion/expr/src/type_coercion/binary.rs
datafusion/optimizer/src/eliminate_join.rs
datafusion/optimizer/src/lib.rs
datafusion/optimizer/src/optimizer.rs

Closes #.
- eliminate useless join 
- convert inner to outer when condition is true
- simplify code
- UT
- sqllogicaltest

feat: eliminate useless join | convert inner to outer when condition is true

---

datafusion/physical-expr/src/equivalence.rs

While studying the code I wanted to encapsulate some of what I learned as comments to make it easier next time.

Minor add more docs to equivalence class code

---

docs/source/contributor-guide/index.md

Closes #6418.
The current command `dnf install -y protobuf-compiler` does install a real package, but it is not sufficient to be able to build DataFusion on Fedora systems.
The proposed command `dnf install -y protobuf-devel` correctly installs the protobuf compiler as well as some development resources that are required.
The proposed change improves the docs in the sense that it installs the correct dependencies for Fedora
A small code snippet in the docs.
No tests required for such a documentation change, at least not as far as I'm aware.
Yes, in the sense that it changes the documentation, but the current command simply doesn't work, and ultimately this change doesn't break anything for anyone.

Fix protobuf install command for Fedora Linux.

---

datafusion/execution/src/config.rs
docs/source/user-guide/cli.md
docs/source/user-guide/sql/information_schema.md

Continue PR 4757

---

docs/source/user-guide/sql/index.rst
docs/source/user-guide/sql/window_functions.md

Closes #6338.
List window functions in the user guide

User guide lists window functions

---

datafusion/core/src/execution/context.rs
datafusion/execution/src/object_store.rs

minor: fix comment docs

---

datafusion/common/src/dfschema.rs
datafusion/common/src/error.rs
datafusion/common/src/utils.rs
datafusion/core/src/avro_to_arrow/arrow_array_reader.rs
datafusion/core/src/avro_to_arrow/reader.rs
datafusion/core/src/catalog/information_schema.rs
datafusion/core/src/catalog/mod.rs
datafusion/core/src/datasource/mod.rs
datafusion/core/src/physical_optimizer/dist_enforcement.rs
datafusion/core/src/physical_optimizer/pipeline_fixer.rs
datafusion/core/src/physical_plan/aggregates/bounded_aggregate_stream.rs
datafusion/core/src/physical_plan/aggregates/mod.rs
datafusion/core/src/physical_plan/aggregates/no_grouping.rs
datafusion/core/src/physical_plan/aggregates/row_hash.rs
datafusion/core/src/physical_plan/file_format/parquet/row_groups.rs
datafusion/core/src/physical_plan/filter.rs
datafusion/core/src/physical_plan/joins/symmetric_hash_join.rs
datafusion/core/src/physical_plan/mod.rs
datafusion/expr/src/expr.rs
datafusion/expr/src/expr_fn.rs
datafusion/expr/src/logical_plan/ddl.rs
datafusion/expr/src/logical_plan/extension.rs
datafusion/expr/src/logical_plan/plan.rs
datafusion/expr/src/tree_node/expr.rs
datafusion/physical-expr/src/expressions/cast.rs
datafusion/physical-expr/src/expressions/try_cast.rs
datafusion/physical-expr/src/physical_expr.rs
datafusion/physical-expr/src/string_expressions.rs
datafusion/proto/src/physical_plan/mod.rs
datafusion/substrait/src/logical_plan/consumer.rs

Closes #207.
This PR fixes most of the remaining clippy `allow`s remaining in the code base.
Clippy `allow`s sometimes silence actually useful lints. Even if the lint was not useful at some point, it's easy to forget about them even after the code has been fixed.
For these reasons it's good practice to clean them up once in a while.
The bulk of the changes is simply removing `allows` the were not needed at all.
Some changes are slightly more involved, but should still be pretty localized and self-explanatory.
This PR does not (and should not) introduce new features or modify existing features. Thus, existing test coverage should be sufficient.
I added one test to for the code I added for data pointer equality (related to the removal of [vtable address …

Clippy lints

---

datafusion/core/src/datasource/listing/helpers.rs
datafusion/core/src/physical_optimizer/pruning.rs
datafusion/core/src/physical_plan/file_format/parquet/row_groups.rs
datafusion/core/src/physical_plan/planner.rs
datafusion/expr/src/expr.rs
datafusion/expr/src/operator.rs
datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs
datafusion/optimizer/src/simplify_expressions/simplify_exprs.rs

Closes #6437.
Some operators on `Expr` are duplicated between type methods and trait impls. This PR removes the duplicated operators in favor of the trait impls.
See #6437 for a more in-depth explanation of why this should be fixed.
Moved the `Not` trait impl to the `operator` module.
Removed the duplicate type methods.
Fixed calls to the removed methods to use the corresponding trait method in instances where the two method names were not the same.
No features were added or removed, so the existing tests should be OK.
I removed a now useless test case for the `Not` trait impl, and added a new one in the `operator` module's unit tests. The new test was made in the same style as the other existing operator unit tests.
Yes, some operator methods have now changed names (when the type methods …

Use `std::ops` traits for `Exprs` rather than custom function names

---

datafusion/substrait/src/logical_plan/consumer.rs
datafusion/substrait/src/logical_plan/producer.rs
datafusion/substrait/tests/roundtrip_logical_plan.rs

Closes #6411.
Currently, we had supported Subtrait::ScalarFunction to DF::BinaryExpr when args len is 2. Now, we support Subtrait::ScalarFunction to DF::ScalarFunction for arbitrary args len. Use name to determine Operator or ScalarFunction to transform for two args cases.
Test roundtrip_logical_plan

Substrait: Support Expr::ScalarFunction

---

datafusion/core/tests/sqllogictests/README.md

N/A
I saw a few potential improvements while reviewing https://github.com/apache/arrow-datafusion/pull/6435 from @liurenjie1024 and figured I would propose them as a follow on PR rather than do back and forth on https://github.com/apache/arrow-datafusion/pull/6435
Improve the docs about running TPCH tests via sqllogictests

Minor: Improve the tpch sqllogictest docs

---

datafusion-cli/Cargo.lock
datafusion/expr/Cargo.toml
datafusion/expr/src/built_in_function.rs
datafusion/sql/src/utils.rs

Related #6448.
Closes https://github.com/apache/arrow-datafusion/pull/6462
Reduce search complexity when mapping BuiltinScalarFunction and its alias. Currently it is linear search and the place becoming a hotspot. The change is to make the search O(1) using static maps
Yes
No

reduce search complexity for BuiltinScalarFunction

---

datafusion/optimizer/src/decorrelate_predicate_subquery.rs
datafusion/optimizer/src/lib.rs
datafusion/optimizer/src/scalar_subquery_to_join.rs

Closes https://github.com/apache/arrow-datafusion/issues/6495
CI / builds are failing after the update of the ctor library
Ensure we only use `#[ctor]` once in the datafusion-optimizer library
yes by CI

Fix builds fail with error: symbol `init___rust_ctor___ctor` is already defined #6495

---

datafusion/core/src/physical_optimizer/pipeline_checker.rs
datafusion/core/src/physical_plan/analyze.rs
datafusion/core/src/physical_plan/planner.rs
datafusion/core/tests/sql/explain_analyze.rs
datafusion/optimizer/src/decorrelate_predicate_subquery.rs
datafusion/optimizer/src/lib.rs
datafusion/optimizer/src/scalar_subquery_to_join.rs

Closes https://github.com/apache/arrow-datafusion/pull/6380
Closes https://github.com/apache/arrow-datafusion/issues/6379
See https://github.com/apache/arrow-datafusion/issues/6379
This is based off https://github.com/apache/arrow-datafusion/pull/6380 from @tustvold but it was getting a little big to just push to his branch so I decided to make a new PR
1. Don't optimize the input to `AnalyzeExec`
2. Update `AnalyzeExec` to handle multiple input streams using `futures`-fu 
3. Add a new test
Yes
Less confusing `EXPLAIN ANALYZE` results

Don't optimize AnalyzeExec (#6379) (try 2)

---

datafusion/core/src/physical_plan/file_format/file_stream.rs
datafusion/core/src/physical_plan/file_format/mod.rs

Closes #6476 
In some cases it useful to skip files during scan if they are not readable (because they have been deleted or corrupted, etc) without failing the entire query
`FileStream` can now have an `OnError` config set. When `OnError::Fail` (default) the behavior is unchanged from what exists now and any error opening or scanning a fail will terminate the stream. If `OnError::Skip`, then the stream will skip the error'd file and continue scanning any other files in the queue. 
Yes
No
No

Make `FileStream` error handling configurable

---

datafusion/proto/proto/datafusion.proto
datafusion/proto/src/generated/pbjson.rs
datafusion/proto/src/generated/prost.rs
datafusion/proto/src/logical_plan/mod.rs

Add serde for `DROP VIEW`

---

datafusion-cli/Cargo.lock
datafusion-cli/Cargo.toml
datafusion-cli/src/exec.rs
datafusion-cli/src/helper.rs

Closes #6397 
See #6397 
* add `unescape_input` function to unescape the input of datafusion-cli
* unescape the sql before executing and verifying it 
Add unit tests in `src/helper.rs`
None

feat: datafusion-cli support executes sql with escaped characters

---

datafusion/core/tests/sqllogictests/test_files/timestamps.slt
datafusion/physical-expr/src/datetime_expressions.rs

Closes #https://github.com/apache/arrow-datafusion/issues/6517
Instead of panic when the stride of date_bin is 0, let us just make it an error message
Check if the stride is 0 and error out
Yes
User will see a proper error message `Execution error: DATE_BIN stride must be non-zero and positive` instead of 
`thread 'main' panicked at 'attempt to calculate the remainder with a divisor of zero',  /arrow-datafusion/datafusion/physical-expr/src/datetime_expressions.rs:354:34
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`

fix: error instead of panic when date_bin interval is 0

---

datafusion/core/src/avro_to_arrow/arrow_array_reader.rs
datafusion/core/src/avro_to_arrow/reader.rs

Closes #6537.
Explained in the linked issue
Reworked `AvroArrowArrayReader::next_batch`, removed `avro_to_arrow::reader::Reader::next`, and reworked `avro_to_arrow::reader::Reader`'s `Iterator` implementation.
No change in behavior, so existing tests should be sufficient.
I think so? I'm not sure because `avro_to_arrow::reader::Reader` doesn't appear in the documentation, but it's public AFAICT?
Anyways, if `Reader` is indeed public, then users will have to import the `Iterator` trait to use the `next` method.

Remove `avro_to_arrow::reader::Reader::next` in favor of `Iterator` implementation.

---

docs/source/contributor-guide/index.md

N/A
I have had PR size discussions with various people over time and I wanted to write down suggestions so that 
1. We could agree as a community on the guidance (so it was consistent)
2. It can be clearly documented and we don't have to repeat it on a case by case basis
Most recently this came up with @izveigor on https://github.com/apache/arrow-datafusion/pull/6384 but I have had similar exchanges with @ozankabak  and likely others
Add a suggestion in the contributor section of the docs
N/A
Docs

Docs: add more PR guidance in contributing guide (smaller PRs)

---

datafusion-cli/Cargo.lock
datafusion/core/Cargo.toml
datafusion/core/src/physical_plan/sorts/sort_preserving_merge.rs
datafusion/core/src/physical_plan/stream.rs
datafusion/core/tests/parquet/page_pruning.rs

~Draft as it Builds on https://github.com/apache/arrow-datafusion/pull/6507~
N/A
We don't really use this crate, so we can reduce the dependnecy load of DataFusion
Now that I know enough `futures` fu to do so, `RecordBatchReceiverStream` be easily be replaced with `futures::stream::unfold`
No

Minor: remove `tokio_stream` dependency

---

datafusion/core/tests/sqllogictests/test_files/dates.slt
datafusion/expr/src/type_coercion/binary.rs

Closes #.
type coercion support date - date
need arrow-rs support it, and then we add slt to test it.

fix: type coercion support date - date

---

datafusion/core/tests/sqllogictests/test_files/aggregate.slt
datafusion/physical-expr/src/aggregate/bit_and_or_xor.rs
datafusion/physical-expr/src/aggregate/build_in.rs
datafusion/physical-expr/src/expressions/mod.rs

Follow on to https://github.com/apache/arrow-datafusion/pull/6276
We can use `BIT_AND(DISTINCT)`, `BIT_OR(DISTINCT)`, `BOOL_AND(DISTINCT)` and `BOOL_OR(DISTINCT)` but it won't have any effect, so the mechanism of action remains the same. Another case is `BIT_XOR(DISTINCT)`, for this function the results with the default version will be different.
For example (where `a` = `[4, 7, 4, 7, 15]`):
```
select bit_xor(a);
----
15
select bit_xor(distinct a);
----
12
```
All bitwise and boolean aggregate functions start to support `DISTINCT` cases.
Yes
Yes

feat: `DISTINCT` bitwise and boolean aggregate functions

---

datafusion/core/tests/sqllogictests/test_files/functions.slt
datafusion/expr/src/function.rs

```
use datafusion::prelude::*;
use datafusion_expr::BuiltinScalarFunction;
​
#[tokio::main]
async fn main() -> datafusion::error::Result<()> {
let ctx = SessionContext::new();
ctx.register_csv("example", "tests/data/example.csv", CsvReadOptions::new()).await?;
​
let df = ctx.table("example").await?;
​
let f = Expr::ScalarFunction(datafusion_expr::expr::ScalarFunction {
fun: BuiltinScalarFunction::Struct,
args: vec![col("a"), col("b")],
});
​
let df2 = df.select(vec![f])?;
df2.show().await?;
Ok(())
}
```
Error: ArrowError(InvalidArgumentError("column types must match schema types, expected Struct([]) but found Struct([Field { name: \"c0\", data_type: Int64, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }, Field { name: \"c1\", data_type: Int64, nullable: true, dict_id: …

Make the struct function return the correct data type.

---

datafusion/core/src/datasource/listing/table.rs

Closes #.
A surprise panic would raise in `list_files_for_scan` if the `table_paths` is empty, I think this can be avoided.
No

fix: avoid panic in `list_files_for_scan`

---

datafusion/core/src/execution/context.rs
datafusion/core/tests/sqllogictests/test_files/groupby.slt

Closes #.
related #5821. 
we need analyze plan to make plan valid.

fix: analyze/optimize plan in `CREATE TABLE AS SELECT`

---

datafusion/core/src/physical_optimizer/sort_enforcement.rs
datafusion/core/tests/sqllogictests/test_files/scalar.slt
datafusion/physical-expr/src/expressions/mod.rs
datafusion/physical-expr/src/expressions/not.rs

This reverts commit 87e5adc9
Closes #6589

Revert "feat: Implement the bitwise_not in NotExpr (#5902)"

---

datafusion/core/tests/sql/mod.rs
datafusion/core/tests/sqllogictests/test_files/scalar.slt
datafusion/core/tests/sqllogictests/test_files/union.slt
datafusion/expr/src/expr_schema.rs
datafusion/optimizer/src/analyzer/type_coercion.rs

Closes #5821.
relate with #6613 
- fix create project with new schema during analysis
- remove type coercion of case expression in Expr::Schema

fix: remove type coercion of case expression in Expr::Schema

---

datafusion/core/src/execution/context.rs

N/A
This was upstreamed in https://github.com/sqlparser-rs/sqlparser-rs/pull/848, let's use the upstream version
use upstream version of a function
existing tests

Minor: use upstream `dialect_from_str`

---

datafusion-cli/src/exec.rs
datafusion-cli/src/object_storage.rs
datafusion/core/src/datasource/file_format/options.rs
datafusion/core/src/datasource/listing/table.rs
datafusion/core/src/datasource/listing_table_factory.rs
datafusion/core/src/physical_plan/analyze.rs
datafusion/expr/src/expr.rs
datafusion/expr/src/function.rs
datafusion/expr/src/function_err.rs
datafusion/optimizer/src/rewrite_disjunctive_predicate.rs
datafusion/physical-expr/src/expressions/binary.rs
datafusion/proto/src/logical_plan/mod.rs
datafusion/sql/src/parser.rs

style: make clippy happy and remove redundant prefix

---

datafusion/substrait/src/logical_plan/consumer.rs
datafusion/substrait/src/logical_plan/producer.rs
datafusion/substrait/tests/roundtrip_logical_plan.rs

Closes #.
This is a patch on top of PR#[6059](https://github.com/apache/arrow-datafusion/pull/6059).
The PR#[6059](https://github.com/apache/arrow-datafusion/pull/6059) fixed duplicate schema error. However, after inspecting the generated plans, it turned out that since we use table/col name from DF to translate to Substrait's field index, the producer has no way of distinguishing between the same column name from `left` and `right` if the table name is also the same.
To fix the problem described, instead of constructing the join condition as one big expression then parse it, each side gets parsed separately so the producer can keep track of field index offset (based on number of columns from `left`) when it tries to parse the `right` part of the join condition.
Yes.
No

Substrait: Fix incorrect join key fields (indices) when same table is being used more than once

---

.github/workflows/rust.yml
ci/scripts/rust_clippy.sh
ci/scripts/rust_docs.sh
ci/scripts/rust_fmt.sh
datafusion-cli/src/exec.rs
datafusion-cli/src/object_storage.rs
datafusion-cli/src/print_format.rs

Closes #6577 
See #6577 
Add `cargo test`, `cargo doc` of datafusion-cli to the CI Job
Yes
None

Add datafusion-cli tests to the CI Job

---

datafusion/core/src/datasource/physical_plan/mod.rs

This fixes inconsistency between rustdocs for Display of files and file groups by applying the same function formatting up to 5 elements. Also adds corresponding unit tests.
Also this is useful for the upcoming fix of https://github.com/apache/arrow-datafusion/issues/6383
No concrete issue but [a minor comment from the already merged PR](https://github.com/apache/arrow-datafusion/pull/6526#discussion_r1224460068)
This seems to address minor issue in the previous PR
As described above
New tests are included in the PR
This changes file group formatting - now it's limited up to 5 files

Unify formatting of both groups and files up to 5 elements

---

datafusion/physical-expr/src/window/built_in.rs
datafusion/physical-expr/src/window/built_in_window_function_expr.rs
datafusion/physical-expr/src/window/cume_dist.rs
datafusion/physical-expr/src/window/partition_evaluator.rs
datafusion/physical-expr/src/window/rank.rs

Related to #5781 
`BuiltInWindowFunctionExpr` already contains several methods that describe how to call the corresponding `PartitionEvaluator` such as `supports_bounded_execution`. 
The `include_rank` function similarly controls how the `PartitionEvaluator`  is called, and therefore I think makes more sense to include on `BuiltInWindowFunctionExpr` as well
As we contemplate exposing `BuiltInWindowFunctionExpr` and `PartitionEvaluator` to implement window functions, making sure the interface is consistent I think is valuable
1. Move `include_rank` into `BuiltInWindowFunctionExpr`

Minor: Move `include_rank` into `BuiltInWindowFunctionExpr`

---

datafusion/core/src/execution/context.rs
datafusion/core/src/physical_optimizer/optimizer.rs

Closes #.
Make a new struct `PhysicalOptimizer` to hold all physical optimizer rules. Like `Optimizer` for logical rules and `Analyzer` for analyzer rules. I found it's not very convenient when I want to customize physical optimize rules.
New struct `PhysicalOptimizer` and several related methods on it.
yes
It's a public struct

feat: encapsulate physical optimizer rules into a struct

---

datafusion/core/tests/sql/timestamp.rs
datafusion/physical-expr/src/datetime_expressions.rs

None
This is inspired when I review #6632 and read the date_trunc implementation. Based on its signature, date_trunc always returns nanosecond timestamp, but for scalar case, it actually returns second/millisecond/microsecond scalar values. This patch fixes the mismatched scalar types.

Return correct scalar types for date_trunc

---

datafusion/core/tests/sqllogictests/test_files/insert.slt
datafusion/sql/src/statement.rs

Closes #.
Currently, the order of the specified column names for INSERT must match the order of the column names in the table.
For example, the following statement cannot be executed successfully
```shell
DataFusion CLI v26.0.0
❯ create table t(a int, b int);
0 rows in set. Query took 0.028 seconds.
❯ insert into t(b,a) values(2,1);
Error during planning: Inserting query must have the same schema with the table.
```
To address this issue, we can rearrange the order of the INSERT fields so that they align with the table fields.
Yes
No

Insert supports specifying column names in any order

---

datafusion/core/tests/sqllogictests/test_files/timestamps.slt

Related to https://github.com/apache/arrow-datafusion/issues/6653
I was surprised that the change in https://github.com/apache/arrow-datafusion/pull/6654 did not cause a test failure so I reviewed our coverage and found there wasn't coverage for the schema of the scalar version of `date_trunc`
Add a test
yes

Minor: Add test for date_trunc schema on scalars

---

datafusion/core/src/physical_plan/planner.rs
datafusion/expr/src/expr_rewriter/mod.rs
datafusion/optimizer/src/analyzer/mod.rs
datafusion/optimizer/src/analyzer/type_coercion.rs
datafusion/optimizer/src/unwrap_cast_in_comparison.rs
datafusion/optimizer/src/utils.rs

Closes #6643 
See #6643 
move `unalias`, `rewrite_preserving_name` rewrite functions into the `datafusion_expr::expr_rewriter` mod.

refactor: unify generic expr rewrite functions into the `datafusion_expr::expr_rewriter`

---

datafusion/core/tests/sqllogictests/test_files/functions.slt
datafusion/optimizer/src/analyzer/count_wildcard_rule.rs
datafusion/sql/src/expr/function.rs
datafusion/sql/tests/integration_test.rs

Closes #.
- replace count(*) analyzer by removing it in sql crate, sql/dataframe all use rule to replace count(*)
- fix: CountWildcardRule ignore Expr::Alias

refactor: unify replace count(*) analyzer by removing it in sql crate

---

datafusion/physical-expr/src/window/built_in.rs
datafusion/physical-expr/src/window/built_in_window_function_expr.rs
datafusion/physical-expr/src/window/cume_dist.rs
datafusion/physical-expr/src/window/lead_lag.rs
datafusion/physical-expr/src/window/nth_value.rs
datafusion/physical-expr/src/window/ntile.rs
datafusion/physical-expr/src/window/partition_evaluator.rs
datafusion/physical-expr/src/window/rank.rs
datafusion/physical-expr/src/window/row_number.rs

Related to #5781 
This PR implements the proposal in the [#PR12](https://github.com/alamb/arrow-datafusion/pull/12)
- `evaluate_stateful` and `evaluate_inside_range` are combined under single `evaluate` methods
- `uses_window_frame` and `supports_bounded_execution` methods are moved from `BoundedWindowFunctionExpr` to `PartitionEvaluator`.
With the changes in this PR new Evaluators can be implemented according to table below.
|uses_window_frame|supports_bounded_execution|function_to_implement|
|---|---|----|
|false|false|`evaluate_all` (if we were to implement `PERCENT_RANK` it would end up in this quadrant, we cannot produce any result without seeing whole data)|
|false|true|`evaluate` (optionally can also implement `evaluate_all` for more optimized implementation. However, there will be …

Combine evaluate_stateful and evaluate_inside_range

---

datafusion/core/tests/user_defined_aggregates.rs
datafusion/expr/src/signature.rs

This is part of https://github.com/apache/arrow-datafusion/issues/6611
I am adding support for sliding windows in user defined aggregates and I need some way to test it.  
The actual code change is relatively small but it takes non trivial effort to test, so I wanted to add the tests first so the actual code change is clearer. 
Add more tests to `user_defined_aggregates.rs` for a user defined aggregates. 
it is only tests
No

Minor: Add tests for User Defined Aggregate functions

---

datafusion/core/tests/dataframe.rs

~~related #6447~~
related PR #6010
This test use wrong `select()`, so bug is hidden.
correct this test and ignore this PR temporarily
error log
```
Error: SchemaError(FieldNotFound { field: Column { relation: None, name: "COUNT(*)" }, valid_fields: [Column { relation: None, name: "COUNT(UInt8(1))" }, Column { relation: Some(Bare { table: "t2" }), name: "a" }, Column { relation: Some(Bare { table: "t2" }), name: "b" }, Column { relation: Some(Bare { table: "t2" }), name: "c" }] })
```
update:
use `count(Wildcard).to_string()` to resolve problem.

fix: correct wrong test

---

datafusion/common/src/dfschema.rs
datafusion/core/tests/sql/expr.rs
datafusion/core/tests/sqllogictests/test_files/array.slt
datafusion/expr/src/utils.rs

part of #6596.
Closes #6613 
In original code, `project` call `from_plan`, it will keep original schema even if expression are different.
It's wrong! Because different expression will have different schema. So I correct it.

fix: from_plan shouldn't use original schema

---

datafusion/physical-expr/src/window/built_in_window_function_expr.rs
datafusion/physical-expr/src/window/partition_evaluator.rs

More work towards https://github.com/apache/arrow-datafusion/issues/5781 by incrementally adding docstrings to the relevant `WindowFunction` expressions
This code needs to be well documented if we expose it and even if we don't, documenting it better will make the code easier to understand
More Docstrings that describe the differences of functions on `PartitionEvaluator` more
N/A

Minor: Add more doc strings to WindowExpr

---

.github/actions/setup-builder/action.yaml

Closes https://github.com/apache/arrow-datafusion/issues/6676
As shown on https://github.com/apache/arrow-datafusion/issues/6676#issuecomment-1593485461, disabling incremental complication saves 2GB of builder space
With incremental compilation enabled (the default):
https://github.com/apache/arrow-datafusion/actions/runs/5281745040/jobs/9555736433?pr=6678
```
Run du -s -h $GITHUB_WORKSPACE/target/debug/* || true
429M	/__w/arrow-datafusion/arrow-datafusion/target/debug/build
21G	/__w/arrow-datafusion/arrow-datafusion/target/debug/deps
4.0K	/__w/arrow-datafusion/arrow-datafusion/target/debug/examples
2.3G	/__w/arrow-datafusion/arrow-datafusion/target/debug/incremental
```
Without incremental compilation: https://github.com/apache/arrow-datafusion/actions/runs/5281960476/jobs/9556242542
``` …
```

Disable incremental compilation on CI

---

datafusion/core/src/physical_plan/udaf.rs
datafusion/core/src/physical_plan/windows/mod.rs
datafusion/core/tests/user_defined_aggregates.rs
datafusion/expr/src/accumulator.rs
datafusion/expr/src/udaf.rs
datafusion/proto/src/physical_plan/mod.rs

Closes https://github.com/apache/arrow-datafusion/issues/6611
When used as window functions, `AggregateUDF` can not use the `retract_batch` API for sliding window calculations
1. Add a new `supports_retract_batch` in `Accumulator` trait (to mirror the API added by @mustafasrepo  for Window Functions)
2. If the Accumulator reports it supports `retract_batch`, use the sliding accumulator code
Yes
New API, though they should all be backwards compatible

Allow `AggregateUDF` to define retractable batch , implement sliding window functions

---

datafusion/physical-expr/src/aggregate/median.rs

Closes #6674 .
See #6674 
Removed self.all_values.len() from inside reserve().
I have also looked at the two other places where reserve() is used, and they don't use the same calculation.
https://github.com/apache/arrow-datafusion/blob/9dfaf4249e31e9a08953955fe4837eb287b089bf/datafusion/execution/src/memory_pool/proxy.rs#L41
https://github.com/apache/arrow-datafusion/blob/9dfaf4249e31e9a08953955fe4837eb287b089bf/datafusion/execution/src/memory_pool/proxy.rs#L83
No
No

removed self.all_values.len() from inside reserve

---

datafusion/sql/src/expr/mod.rs
datafusion/sql/src/expr/value.rs

Clean up following PR for issue #6205
N/A
- Fix clippy allow too many arguments
No

refactor: fix clippy allow too many arguments

---

datafusion/expr/src/expr.rs
datafusion/expr/src/expr_rewriter/mod.rs
datafusion/optimizer/src/merge_projection.rs
datafusion/optimizer/src/push_down_projection.rs
datafusion/optimizer/src/scalar_subquery_to_join.rs
datafusion/optimizer/src/simplify_expressions/simplify_exprs.rs

Closes #.
alias() should skip add alias for `Expr::Sort`
otherwise, it will failed `"Create name does not support sort expression"`.
Currently, we just skip in `add_alias_if_changed`, I refactor they and move into `Expr::alias()` function

refactor: alias() should skip add alias for `Expr::Sort`

---

datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs
datafusion/physical-expr/src/execution_props.rs

N/A
While reviewing https://github.com/apache/arrow-datafusion/pull/6706 I noticed this could be improved and figured I would make a PR
1. Add `ExecutionProps::with_query_execution_start_time`
2. Update code to use it
Maybe an easier to use `ExecutionProps` -- no API changes

Minor: Improve UX for setting `ExecutionProps::query_execution_start_time`

---

datafusion/core/src/datasource/listing/url.rs

N/A
It would be nice to make it comparable, as right now it can't be used in structs that implement `Eq`, `Hash` and `PartialEq`
Additional traits added to `ListingTableUrl`
Yes
Yes

add Eq and PartialEq to ListingTableUrl

---

datafusion/core/src/physical_optimizer/sort_enforcement.rs
datafusion/core/src/physical_plan/coalesce_batches.rs

Closes #.
`CoalesceBatchesExec` preserves its input ordering. However, `maintains_input_order` flag is not implemented.
This PR fixes this problem. 
`test_remove_unnecessary_sort_window_multilayer` is updated such that, it includes `CoalesceBatchesExec` in its plan. Updated test shows that ordering is propagated through `CoalesceBatchesExec`.

MINOR: Add maintains input order flag to CoalesceBatches

---

docs/source/conf.py

The https://arrow.apache.org/datafusion/ website has the wrong year, so let's correct that and make sure it looks like we are keeping up to date

Minor: Update copyight date on website

---

Cargo.toml
datafusion-cli/Cargo.lock
datafusion-cli/Cargo.toml
datafusion/core/tests/sql/expr.rs
datafusion/sql/tests/sql_integration.rs

N/A
Keep up to date with dependencies
Update `arrow`, `arrow-flight` and `parquet` to `42.0.0` -- https://github.com/apache/arrow-rs/issues/4422
Existing tests
A slight regression in parsing intervals (`0.5 month` works, but `.5 month`, without the leading `0`, does not). Due to https://github.com/apache/arrow-rs/issues/4424

Update `arrow`, `arrow-flight` and `parquet` to `42.0.0`

---

datafusion/physical-expr/src/datetime_expressions.rs

Minor follow on to https://github.com/apache/arrow-datafusion/pull/6723 
While reviewing https://github.com/apache/arrow-datafusion/pull/6723 (thanks @BryanEmond !) I noticed it would be possible to do so with a little less code using `Option::map` so I coded it up
Refactor some code to avoid `unwrap`
Covered by existing tests added in https://github.com/apache/arrow-datafusion/pull/6723

Minor: remove some uses of unwrap

---

datafusion/physical-expr/src/expressions/in_list.rs

Closes #.
As `Decimal128` and `Decimal256` data types became primitive types they are automatically converted by `downcast_primitive_array` macros.
I think the dead code should be removed.

Minor: remove dead code with decimal datatypes from `in_list`

---

datafusion/core/src/lib.rs
datafusion/core/tests/user_defined_aggregates.rs
datafusion/expr/src/accumulator.rs
datafusion/expr/src/expr_fn.rs
datafusion/expr/src/function.rs
datafusion/expr/src/lib.rs
datafusion/expr/src/udaf.rs
datafusion/optimizer/src/analyzer/type_coercion.rs
datafusion/optimizer/src/common_subexpr_eliminate.rs
datafusion/proto/src/physical_plan/mod.rs

related to https://github.com/apache/arrow-datafusion/issues/6611
@stuartcarnie  had some questions about how this API should work, and so I wanted to encode the answers into documentation for others as well
1. Update docs for `AggregateUDF`
2. Update docs for `Accumulator`
3. Rename `AccumulatorFunctionImplementation` to `AccumulatorFactoryFunction` to better describe what it does
Yes (existing tests + doc tests)
1. Better docs
2. Different type alias name (`AccumulatorFunctionImplementation` to `AccumulatorFactoryFunction`)

Update documentation for creating User Defined Aggregates (AggregateUDF)

---

datafusion/core/src/catalog/information_schema.rs
datafusion/core/src/datasource/streaming.rs
datafusion/core/src/physical_plan/streaming.rs
datafusion/core/tests/memory_limit.rs

To split out `physical_plan` it can't depend on `datasource` (which is in the datafusion core crate now)
Move `PartitionStream` to physical_plan
N/A
In theory, yes, if anyone uses this API, which I think will not be many people as it is fairly new

Minor: Move `PartitionStream` to physical_plan

---

docs/source/user-guide/sql/scalar_functions.md

Related to https://github.com/apache/arrow-datafusion/pull/6736 and https://github.com/apache/arrow-datafusion/pull/6594
I had a hard time finding the `struct` function documentation even when I knew it existed.  As I work on updating the DataFusion SQL support page in https://github.com/apache/arrow-datafusion/pull/6594 , I wanted to reference the struct functions
1. Add a new heading called `Struct Functions` and move `struct` there
2. Add a SQL example
Here is what it looks like rendered:
N/A
User docs only

Docs: Improve documentation for `struct` function`

---

datafusion/core/src/lib.rs

Closes https://github.com/apache/arrow-datafusion/issues/6648
When I am trying to use rustdocs to find certain classes it often fails to do so (see https://github.com/apache/arrow-datafusion/issues/6648 for more details)
1. Directly `pub use` the content of submodules rather than just the modules themselves
This means that rustdoc can now find all the classes directly:
Existing tests
Better rust docs

Re-export modules individually to fix rustdocs

---

datafusion/core/tests/sqllogictests/test_files/interval.slt
datafusion/physical-expr/src/expressions/binary.rs
datafusion/physical-expr/src/expressions/binary/kernels_arrow.rs

Closes #6774.
`Eq` and `NotEq` work fine on intervals. This PR extends support to `IsDistinctFrom` and `IsNotDistinctFrom`.
- Changed the kernels to work on `ArrowPrimitiveType` instead of `ArrowNumericType`.
- Added interval types to the `binary_array_op` macro.
Tested in `interval.slt`
Yes, `IsDistinctFrom` and `IsNotDistinctFrom` work on interval types.

Support IsDistinctFrom and IsNotDistinctFrom on interval types

---

datafusion/sql/src/expr/value.rs

Closes #6764 .
Datafusion supports the binary data type, but there is no way to insert binary data or query with binary data in a predicate through a sql. And this is caused by missing conversion from `sqlparser::ast::Value::HexStringLiteral` to `datafusion_expr::Expr::Literal(ScalarValue::Binary)`.
Support the conversion from `sqlparser::ast::Value::HexStringLiteral` to `datafusion_expr::Expr::Literal(ScalarValue::Binary)`.
Add a unit test for hex string literal decoding.
Now, the sql including hex string literal, e.g. `X'FF01'`, can be processed and treated as a binary data by datafusion.

Support hex string literal

---

datafusion/common/src/dfschema.rs
datafusion/common/src/lib.rs
datafusion/core/src/datasource/file_format/csv.rs
datafusion/core/src/datasource/listing/table.rs
datafusion/core/src/datasource/memory.rs
datafusion/core/src/datasource/mod.rs
datafusion/core/src/physical_plan/insert.rs
datafusion/core/tests/sqllogictests/test_files/insert.slt

Fix the following issue:
```shell
DataFusion CLI v26.0.0
❯ create table t1(a int not null);
0 rows in set. Query took 0.028 seconds.
❯ insert into t1 values(1);
Error during planning: Inserting query must have the same schema with the table.
```
This issue is because the nullable information of the two schemas is different.
input schema: Schema { fields: [Field { name: "a", data_type: Int32, **nullable: true**, dict_id: 0, dict_is_ordered: false, metadata: {} }], metadata: {} }
table schema: Schema { fields: [Field { name: "a", data_type: Int32, **nullable: false**, dict_id: 0, dict_is_ordered: false, metadata: {} }], metadata: {} }
Declaring the schema as nullable doesn't necessarily mean that the actual data is always NULL.
When data is NOT NULL, it should be allowed to be inserted into …

Fix inserting into a table with non-nullable columns

---

datafusion/core/src/physical_planner.rs
datafusion/core/tests/sqllogictests/test_files/dates.slt
datafusion/core/tests/sqllogictests/test_files/interval.slt
datafusion/core/tests/sqllogictests/test_files/timestamps.slt
datafusion/core/tests/sqllogictests/test_files/type_coercion.slt
datafusion/expr/src/type_coercion/binary.rs
datafusion/optimizer/src/analyzer/type_coercion.rs
datafusion/physical-expr/src/expressions/binary.rs

Part of #3419
This is the first of what will be a series of PRs to consolidate the type coercion logic and make it easier to follow. In particular this PR adds the ability to express type coercion of heterogeneous types, as occurs in arithmetic. This in turn feeds into the effort to move more of this logic upstream https://github.com/apache/arrow-rs/issues/3999
Replaces `coerce_types` with  `get_input_types` that returns separate types for the left and right expressions. It also consolidates the coercion logic in a single private `signature` function to avoid inconsistency and reduce repetition.

Cleanup type coercion (#3419)

---

datafusion/physical-expr/src/datetime_expressions.rs

Follow on to https://github.com/apache/arrow-datafusion/pull/6654 from @Weijun-H  (❤️ )
While reviewing https://github.com/apache/arrow-datafusion/pull/6654 and trying to answer @viirya 's question here https://github.com/apache/arrow-datafusion/pull/6654#discussion_r1244324968
1. Rename `date_trunc_single` to `date_trunc_coarse` to better explain what it does
2. Add comments to explain how it works
3. Remove the use of indirection and call the function directly
Covered by the (very) nice existing tests added in https://github.com/apache/arrow-datafusion/pull/6654
No

Minor: Simplify `date_trunc` code and add comments

---

datafusion/core/tests/sqllogictests/test_files/array.slt

Related to https://github.com/apache/arrow-datafusion/issues/6709
While reviewing  https://github.com/apache/arrow-datafusion/pull/6618 I felt there was a gap in coverage:
tests for array functions on array functions

Minor: Add array / array sqllogic tests for `array_contains`

---

datafusion/physical-expr/src/datetime_expressions.rs

Related  to to https://github.com/apache/arrow-datafusion/issues/6653 and  https://github.com/apache/arrow-datafusion/pull/6654
Both @viirya  and I were confused about a seeming special case handling of `microsecond` and `millisecond` truncation in the `date_trunc` code -- see  https://github.com/apache/arrow-datafusion/pull/6654#discussion_r1244324968
Update the code so  `microsecond` and `millisecond` are handled the same way as the other granularities

Minor: Make `date_trunc` code easier to understand

---

datafusion/expr/src/expr_schema.rs

None
The nullability of  the `between` expression not only depends on the subexpression but may also depend on the `low` or `high` expression.
For example
```shell
DataFusion CLI v27.0.0
❯ select 1 between null and 2;
+------------------------------------+
| Int64(1) BETWEEN NULL AND Int64(2) |
+------------------------------------+
|                                    |
+------------------------------------+
❯ select 1 between 1 and null;
+------------------------------------+
| Int64(1) BETWEEN Int64(1) AND NULL |
+------------------------------------+
|                                    |
+------------------------------------+
```
fix  incorrect nullability of `between` expr
Yes
No

fix: incorrect nullability of `between` expr

---

datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs
datafusion/physical-expr/src/expressions/binary.rs
datafusion/physical-expr/src/expressions/binary/kernels_arrow.rs

Closes #6791
The current behaviour is inconsistent, can lead to nulls in non-nullable columns, and is pretty surprising.
A future iteration of the upstream arithmetic kernels is also likely to make this the only option - https://github.com/apache/arrow-rs/issues/2647#issuecomment-1612146560

Use checked division kernel

---

datafusion/core/tests/sqllogictests/test_files/binary.slt
docs/source/user-guide/sql/data_types.md

Related to https://github.com/apache/arrow-datafusion/issues/6764
Some tests for https://github.com/apache/arrow-datafusion/pull/6767
1. Add `binary.slt` tests for `Binary` data type to add some end to end coverage 
2. Add note about using `X'` style strings to docs
Yes, all tests
No

Minor: add sqllogictests for binary data type

---

datafusion/expr/src/type_coercion/binary.rs
datafusion/physical-expr/Cargo.toml
datafusion/physical-expr/src/expressions/binary.rs
datafusion/physical-expr/src/expressions/binary/kernels_arrow.rs

Closes #.
The support for arithmetic on dictionaries is inconsistent, results in a huge amount of code gen, and doesn't yield significant performance savings. There is an upstream PR proposing removing this functionality - https://github.com/apache/arrow-rs/pull/4407
In particular as far as I can tell the current logic has the following behaviour:
* Dictionary + Dictionary => Non-Dictionary (or error if feature not enabled)
* Dictionary + Scalar Dictionary => Dictionary
* Dictionary + Non-Dictionary => Dictionary
* Non-Dictionary + Dictionary => Non-Dictionary
By coercing the dictionaries we can avoid all this complexity, and provide a more consistent user experience
As an aside it is unclear why you would ever use a primitive dictionary, they will almost always be slower to process and …

Consistently coerce dictionaries for arithmetic

---

datafusion/proto/proto/datafusion.proto
datafusion/proto/src/generated/pbjson.rs
datafusion/proto/src/generated/prost.rs
datafusion/proto/src/logical_plan/from_proto.rs
datafusion/proto/src/logical_plan/mod.rs
datafusion/proto/src/logical_plan/to_proto.rs

Implement serialization for UDWF and UDAF in plan protobuf

---

datafusion/core/src/physical_plan/insert.rs
datafusion/expr/src/expr_schema.rs

None
Similar to #6786 .
We can safely assume that the `InList` expr is non-nullalbe only if all of its subexpressions are non-nullable.
An example of a nullable expression is:
```
DataFusion CLI v27.0.0
❯ select 1 in(2, null);
+----------------------------------------------------------------------+
| Int64(1) IN (Map { iter: Iter([Literal(Int64(2)), Literal(NULL)]) }) |
+----------------------------------------------------------------------+
|                                                                      |
+----------------------------------------------------------------------+
```
- fix incorrect nullability of `InList` expr
- cleaner code for insert.rs
Yes
No

fix: incorrect nullability of `InList` expr

---

datafusion/core/tests/sql/timestamp.rs

Fix timestamp_add_interval_months to pass any date

---

benchmarks/Cargo.toml
benchmarks/src/bin/tpch.rs

N/A
I wanted to validate y POC grouping code that it got the right answer when running benchmarks
the `tpch` benchmark driver now shows the output if `RUST_LOG` is enabled
```shell
cargo run --profile dev --bin tpch -- benchmark datafusion --iterations 5 --format parquet -q 17 --path <data> 
...
Running benchmarks with the following options: DataFusionBenchmarkOpt { query: Some(17), debug: false, iterations: 5, partitions: 2, batch_size: 8192, path: "/Users/alamb/Software/arrow-datafusion/benchmarks/data/", file_format: "parquet", mem_table: false, output_path: None, disable_statistics: false }
Query 17 iteration 0 took 6383.7 ms and returned 1 rows
Query 17 iteration 1 took 6341.2 ms and returned 1 rows
Query 17 iteration 2 took 6337.4 ms and returned 1 rows
Query 17 iteration 3 took …
```

Minor: Log TPCH benchmark results

---

datafusion/physical-expr/src/aggregate/utils.rs

Related to https://github.com/apache/arrow-datafusion/issues/4973
While working on a POC for new grouping code, I found I needed to call the decimal averaging code, but could not do so in a performant (vectorized) way because it created a `ScalarValue` 
1. Pull out the decimal average code into its own structure
2. Add comments that explain what is happening
3. Refactor `calculate_result_decimal_for_avg`

Refactor Decimal128 averaging code to be vectorizable (and easier to read)

---

datafusion/core/src/physical_plan/aggregates/row_hash.rs
datafusion/physical-expr/src/hash_utils.rs

`create_hashes` is not super critical to performance but shows up in profiles.
There are some tweaks we can do:
* Don't rehash the first array if we need to hash multiple columns
* Directly iterate over values for primitive / non null arrays 
* Use `value_unchecked`
Overall this is a little bit faster:
```
┃ Query        ┃     main ┃ create_hashes_primitive ┃        Change ┃
┡━━━━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ QQuery 1     │ 189.57ms │                186.99ms │     no change │
│ QQuery 2     │  58.37ms │                 56.41ms │     no change │
│ QQuery 3     │  50.00ms │                 47.19ms │ +1.06x faster │
│ QQuery 4     │  39.27ms │                 37.18ms │ +1.06x faster │
│ QQuery 5     │  95.93ms │                 91.49ms │     no change │
│ …
```

[MINOR] Improve performance of `create_hashes`

---

Cargo.toml

Closes #.
Fix the following warning when building the project.
```
warning: some crates are on edition 2021 which defaults to `resolver = "2"`, but virtual workspaces default to `resolver = "1"`
note: to keep the current resolver, specify `workspace.resolver = "1"` in the workspace root's manifest            
note: to use the edition 2021 resolver, specify `workspace.resolver = "2"` in the workspace root's manifest        
```

Fix cargo build warning

---

datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs

Related to #6345
Quoted from the [PostgreSQL documentation](https://www.postgresql.org/docs/current/functions-comparison.html):
> Notice that IS UNKNOWN and IS NOT UNKNOWN are effectively the same as IS NULL and IS NOT NULL, respectively, except that the input expression must be of Boolean type.
So they can apply the same simplification rules.
Simplify `IsUnkown` and `IsNotUnkown` expression
Yes
No

Simplify `IsUnkown` and `IsNotUnkown` expression

---

datafusion/common/src/scalar.rs
datafusion/expr/src/expr_schema.rs

None
The nullability of the `Like` expressions can also depend on the pattern expression.
```shell
DataFusion CLI v27.0.0
❯ select 'foo' like null is null;
+--------------------------------+
| Utf8("foo") LIKE NULL  IS NULL |
+--------------------------------+
| true                           |
+--------------------------------+
```
- fix nullability of `Like` expressions
- improve the documentation for `ScalarType`
Yes
No

fix: incorrect nullability of `Like` expressions

---

datafusion/physical-expr/src/hash_utils.rs

Follow on to https://github.com/apache/arrow-datafusion/pull/6816 from @Dandandan 
There are some `unsafe` blocks in this function, so I would like to make it more obvious that they are ok
Add the same assert to `hash_array_primitive` as are in `hash_array`
existing tests

Minor: Add one more assert to `hash_array_primitive`

---

datafusion/common/src/dfschema.rs
datafusion/expr/src/utils.rs
datafusion/optimizer/src/analyzer/type_coercion.rs

revert #6595 #6820

---

datafusion/common/src/scalar.rs
datafusion/proto/proto/datafusion.proto
datafusion/proto/src/generated/pbjson.rs
datafusion/proto/src/generated/prost.rs
datafusion/proto/src/logical_plan/from_proto.rs
datafusion/proto/src/logical_plan/to_proto.rs

Closes #.
The upstream arithmetic kernels, such as those in https://github.com/apache/arrow-rs/pull/4465 return Duration for timestamp arithmetic. See https://github.com/apache/arrow-rs/issues/3964 for further discussion on why duration is preferable to interval (TLDR: they're faster and less ambiguous). In order to incorporate these kernels #6832 we need scalar support for durations
Not explicitly, but the exhaustive matches combined with the copy-pasted macros makes me unsure if this would add much value

Add Duration to ScalarValue

---

datafusion/physical-expr/src/aggregate/median.rs

Related to discussion in #4973.
This PR improves the median aggregator by reducing the number of allocations. 
For this example I am using one year of data from the [nyctaxi](https://www.nyc.gov/site/tlc/about/tlc-trip-record-data.page) dataset, running  a group by `payment_type` and computing the `total_amount` median, with the current version it takes ~22secs:
```
$ time ./target/release/datafusion-median
+--------------+--------------+----------+
| payment_type | total_amount | n        |
+--------------+--------------+----------+
| 5            | 5.275        | 6        |
| 3            | 7.7          | 194323   |
| 4            | -6.8         | 244364   |
| 0            | 23.0         | 1368303  |
| 2            | 13.3         | 7763339  |
| 1            | 16.56        | 30085763 | …
```

Improve median performance.

---

datafusion/core/tests/sqllogictests/test_files/decimal.slt
datafusion/physical-expr/src/expressions/binary/kernels_arrow.rs

Related #6794.
Before we figure a proper way to address the issue, we should return error for the overflowing case instead of returning incorrect result.

Return error when internal multiplication overflowing in decimal division kernel

---

datafusion/proto/proto/datafusion.proto
datafusion/proto/src/generated/pbjson.rs
datafusion/proto/src/generated/prost.rs
datafusion/proto/src/logical_plan/from_proto.rs
datafusion/proto/src/logical_plan/mod.rs
datafusion/proto/src/logical_plan/to_proto.rs

None
In our system, we store metadata in both the `Field` and the `Schema`, such as the default values for columns and the primary keys for tables.
But once those metadata are serialized, they are lost.
I wonder if we can preserve those metadata in the proto.
Preserve metadata for `Field` and `Schema` in proto
Yes
New message fields in proto

feat: preserve metadata for `Field` and `Schema` in proto

---

datafusion/core/src/datasource/memory.rs
datafusion/core/src/physical_plan/memory.rs

Closes #.
Refactor MemTable for unnecessary code.
Removing `try_new_owned_data`
Existing tests are enough.
No

[MINOR] Remove unnecessary api from MemTable

---

datafusion/core/src/physical_optimizer/sort_enforcement.rs
datafusion/core/src/physical_optimizer/sort_pushdown.rs
datafusion/core/src/physical_plan/joins/hash_join.rs
datafusion/core/src/physical_plan/joins/utils.rs
datafusion/core/tests/sqllogictests/test_files/join_disable_repartition_joins.slt

Closes https://github.com/apache/arrow-datafusion/issues/6857
In theory, we can maintain the order of records on the probe side of the hash join. This ordering preservation can be applied to Inner, RightSemi, and RightAnti joins.
The implementation changes in this pull request are designed to leverage this aspect of hash join operations, thereby eliminating unnecessary sort operations. Consequently, this enhancement is expected to result in improved performance, particularly in scenarios where the probe side of the hash join operation is already sorted.
1. **Adjustment of HashJoinExec APIS**: We have modified the HashJoinExec operation to preserve the order of its probe side in Inner, RightSemi, and RightAnti joins, thereby eliminating unnecessary sort operations.
2. **Bug Fix on Sort …

Adjustment of HashJoinExec APIs to Preserve Probe Side Order

---

datafusion/core/src/physical_plan/streaming.rs

N/A
https://github.com/apache/arrow-datafusion/pull/6860 and https://github.com/apache/arrow-datafusion/pull/6835 conflicted logically and cause compilation to fail on `main`:
https://github.com/apache/arrow-datafusion/actions/runs/5483558927/jobs/9990031096
```
Compiling datafusion v27.0.0 (D:\a\arrow-datafusion\arrow-datafusion\datafusion\core)
error[E0252]: the name `DisplayFormatType` is defined multiple times
--> datafusion\core\src\physical_plan\streaming.rs:38:24
|
34 |     DisplayFormatType, ExecutionPlan, Partitioning, SendableRecordBatchStream,
|     ----------------- previous import of the type `DisplayFormatType` here
...
38 | use super::{DisplayAs, DisplayFormatType};
|                        ^^^^^^^^^^^^^^^^^ `DisplayFormatType` reimported here
|
= note: `DisplayFormatType` …
```

Fix build on main due to logical conflict

---

datafusion/core/src/datasource/physical_plan/mod.rs
datafusion/core/src/physical_plan/display.rs
datafusion/core/src/physical_plan/streaming.rs

Related to #1754 
I would like to move all physical plan into its own crate eventually, thus there can't be back dependencies to core
Move `ProjectSchemaDisplay` and `OutputOrderingDisplay` TO the display module with the other ExecutionPlan display code, most recently modified by @liurenjie1024 in https://github.com/apache/arrow-datafusion/pull/6726
existing CI

Minor: Consolidate display related traits

---

datafusion/core/src/datasource/file_format/parquet.rs

Related to https://github.com/apache/arrow-datafusion/pull/2960
Add one more test.
Add a test for parquet use the byte array as the physical type to store decimal.
No.

test: parquet use the byte array as the physical type to store decimal

---

datafusion/core/src/physical_plan/sorts/merge.rs
datafusion/core/src/physical_plan/sorts/mod.rs

Closes https://github.com/apache/arrow-datafusion/issues/6871
We would like to use `streaming_merge` on its own.
Changing `physical_plan::merge::streaming_merge` to public
Yes, existing tests
No

Make streaming_merge public

---

datafusion/physical-expr/src/aggregate/sum.rs

Closes https://github.com/apache/arrow-datafusion/issues/6878
I noticed this while working on #4973 
The `SUM` accumulator is general (it can handle sliding windows) but to be general it carries through an extra count for each group in the "state" -- this count is ignored. For low cardinality groups this likely isn't a problem but for large cardinality groups creating and carrying through the counts takes a measurable amount of time (I saw it in #6800)
Use a specialized sum accumulator for retractable windows and only track the counts there. For non 
Performance (the bigger changes like `q15 have a `sum` in them, so the change is plausible). The smaller changes don't have any sums which makes me suspicious
```
┏━━━━━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━ …
```

Performance: Use a specialized sum accumulator for retractable aggregregates

---

datafusion/core/tests/sqllogictests/test_files/array.slt
datafusion/physical-expr/src/array_expressions.rs

Ref #6849
Calculate dims for each array in concat(), find the max one, and wrap each array to the same dims.
Note that this change does not restrict that each array dimension should be diff by 1 as mentioned in the issue, but I think it is fine not to restrict that, If we need to ensure that, we just need additional error handling.

Support array concatenation for arrays with different dimensions

---

datafusion/substrait/src/logical_plan/consumer.rs
datafusion/substrait/src/logical_plan/producer.rs
datafusion/substrait/tests/cases/roundtrip_logical_plan.rs
datafusion/substrait/tests/roundtrip_logical_plan.rs

Closes #6866 .
Explained in issue.
* Parse DF join filter into Substrait's `post_join_filter` in producer
* Parse `post_join_filter` into join filter in consumer
* Test cases:
* non-empty join expression, non-empty filter
* empty join expression, non-empty filter
* query with `exists` clause
Yes.
Please note that if a test case includes subquery aliases, the results will not be correct due to issue #6867 .
No

feat: implement substrait join filter support

---

datafusion/physical-expr/src/expressions/binary.rs

Add FixedSizeBinary support to binary_op_dyn_scalar

---

datafusion/core/src/physical_plan/joins/nested_loop_join.rs

Closes #.
Just reduce some redundant code.
Using `partitioned_join_output_partitioning` to instead some code
No need.
No.

Minor: reduce redundant code

---

datafusion/core/src/physical_plan/joins/nested_loop_join.rs
datafusion/proto/proto/datafusion.proto
datafusion/proto/src/generated/pbjson.rs
datafusion/proto/src/generated/prost.rs
datafusion/proto/src/physical_plan/mod.rs

Closes #6898 
See #6898 
* add `NestedLoopJoinExecNode` in datafusion.proto, then regen proto files
* support encode/decode `NestedLoopJoinExec` in `try_into_physical_plan` and `try_from_physical_plan` function
* add `roundtrip_nested_loop_join` unit test
Yes
None

feat: support for `NestedLoopJoinExec` in datafusion-proto

---

datafusion/core/tests/sqllogictests/test_files/array.slt
datafusion/physical-expr/src/array_expressions.rs

Closes https://github.com/apache/arrow-datafusion/issues/6887
Fix a bug (see https://github.com/apache/arrow-datafusion/issues/6887)
NOTE this PR looks large, but has only 4 lines of code changes. The rest of it is doc comments and tests
1. Check for `null` when creating new arrays
2. Add tests
3. Add docstrings / ASCII art 
yes
fix regression

Fix `make_array` null handling, update tests

---

datafusion/core/tests/fuzz_cases/aggregate_fuzz.rs

I added this in #6800  while debugging a failure and thought it would help others
Add println to aggregate_fuzz that will be displayed when the test fails
CI

Minor: Add output to aggregrate_fuzz.rs on failure

---

datafusion/core/src/physical_plan/windows/mod.rs
datafusion/core/tests/user_defined/user_defined_window_functions.rs

Closes #6914.
The schema produced by the `WindowUDF` physical expression is now marked as being nullable.
Yes, in the `user_defined_integration` tests.
No

allow window UDF to return null

---

datafusion/core/src/datasource/listing/mod.rs

Closes #6919 .
Adding more cozy method to create file scans for Partitioned files.
The method calculates actual file size for existing constructor. Now its challenging to create manually links to existing multiple input parquet files, as its needed to calculate their sizes first
Existing tests
No

Minor: Add factory method to PartitionedFile to create File Scan

---

datafusion/core/src/datasource/physical_plan/mod.rs

We (Coralogix) need this to implement a custom TableProvider returning the correct schema in presence of partitioning. 
Allow to use the method outside of this module.

[Minor] Make FileScanConfig::project pub

---

benchmarks/src/bin/tpch.rs

Closes #6917 
See #6917 
* add round trip test of physical plan in tpch unit tests
Yes
None

feat: add round trip test of physical plan in tpch unit tests

---

datafusion/core/tests/sqllogictests/src/engines/datafusion/error.rs

Minor: Use thiserror to implement the `From` trait for `DFSqlLogicTestError`

---

datafusion/core/tests/sqllogictests/test_files/aggregate.slt

Related to https://github.com/apache/arrow-datafusion/issues/6889
I was doing some testing and found out that the new GroupsAccumulator in https://github.com/apache/arrow-datafusion/pull/6904 aren't implemented for date/time/timestamps -- so here are some tests to cover that
Add some tests
These are only tests

Add additional test coverage for aggregaes using dates/times/timestamps/decimals

---

datafusion/core/tests/sqllogictests/test_files/aggregate.slt
datafusion/physical-expr/src/aggregate/bit_and_or_xor.rs
datafusion/physical-expr/src/aggregate/groups_accumulator/prim_op.rs

Resolves https://github.com/apache/arrow-datafusion/issues/6955, a bug introduced in https://github.com/apache/arrow-datafusion/pull/6904
The answer is incorrect because the starting value is always 0 and thus `0 & ` anything else will also be zero which is not right
1. Allow the starting value of the accumulator t be specified
2. set the default value of the accumulator correctly for `bit_and`
3. Add new tests (subset of what is in https://github.com/apache/arrow-datafusion/pull/6952)
Yes

Fix incorrect results in `BitAnd` GroupsAccumulator

---

datafusion/common/src/dfschema.rs
datafusion/expr/src/expr_schema.rs

Closes #6886.
This change improves support for extension types by allowing access to field metadata at the logical planning stage.
- Added `ExprSchemable::metadata` method.
- Forwards metadata for column and alias expressions
- All other expressions return empty metadata
- Updated `ExprSchemable::to_field` to populate field metadata.
- Added metadata utility methods `metadata` and `with_metadata` to `DFField` to match `Field` methods in `arrow-rs`.
Yes
No

Preserve field metadata across expressions in logical plans

---

datafusion/core/tests/sqllogictests/test_files/interval.slt
datafusion/physical-expr/src/expressions/binary.rs

Closes #6947.
More complete support for operations between interval types.
Add missing cases for interval types to `binary_array_op_dyn_scalar`.
Added `.slt` tests. Also added tests for the array-array and scalar-scalar cases that already work today but seem untested.
Yes, comparing an interval array with an interval scalar now works.

Support equality and comparison between interval arrays and scalars

---

datafusion/physical-expr/src/aggregate/bit_and_or_xor.rs

Follow on to https://github.com/apache/arrow-datafusion/pull/6957
I didn't see a comment from @viirya  https://github.com/apache/arrow-datafusion/pull/6957#discussion_r1262797697 that had the good suggestion to explain the default value
Add doc comments to explain the code
N/A

Minor: Add comments about initial value for `BitAnd` accumulator

---

datafusion/physical-expr/src/aggregate/min_max.rs

related to 
While working on https://github.com/apache/arrow-datafusion/pull/6957 to provide a default starting value, I realized this could be used to consolidate the Min/Max accumulator implementation as well to avoid duplication
Change min/max to use the standard `PrimitiveGroupsAccumulator` rather than implementing itself
No, this is just less code

Minor: remove duplication in Min/Max accumulator

---

datafusion/core/tests/sqllogictests/test_files/array.slt
datafusion/physical-expr/src/array_expressions.rs

Ref #6804
Array concat with columns! Behavior is similar to Postgres.
Concat Operator `a || b` is not included in this PR!

Column support for array concat

---

datafusion/physical-expr/src/array_expressions.rs

chore: break earlier in macro `contains!`

---

datafusion/core/tests/sqllogictests/test_files/scalar.slt
datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs

Closes #7004.
This rule should only be applied if the base subexpression is not present.
Yes
No

fix: incorrect simplification of case expr

---

datafusion/core/tests/sqllogictests/test_files/aggregate.slt

Related to https://github.com/apache/arrow-datafusion/issues/6889
Adds coverage for Min/Max/Count for strings, which I intend to improve shortly and I want to ensure there is reasonable coverage
Add basic min/max/count tests for strings / Binary
All tests
No

Minor: Add String/Binary aggregate tests

---

datafusion/core/src/physical_optimizer/pipeline_fixer.rs
datafusion/core/src/physical_plan/joins/mod.rs
datafusion/core/src/physical_plan/joins/symmetric_hash_join.rs

Closes #.
The support for repartition joins configuration was missing in SHJ, so we added a simple struct to control it.
`StreamJoinPartitionMode` is added.
Yes
No

[MINOR] Supporting repartition joins conf in SHJ

---

datafusion/core/tests/sqllogictests/test_files/array.slt
datafusion/physical-expr/src/array_expressions.rs

Closes https://github.com/apache/arrow-datafusion/issues/6985
Follow on to https://github.com/apache/arrow-datafusion/pull/6879
Follow on to https://github.com/apache/arrow-datafusion/pull/6805
Yes
Yes

feat: array functions treat an array as an element

---

datafusion/core/src/physical_optimizer/sort_enforcement.rs
datafusion/core/src/physical_optimizer/test_utils.rs

Closes #.
Making the test utils common.
Only test utils are moved.
Yes
No

[MINOR] Moving some test utils from EnsureSorting to test_utils

---

datafusion/core/src/lib.rs
datafusion/core/src/physical_plan/mod.rs
datafusion/core/src/physical_plan/repartition/mod.rs
datafusion/expr/src/logical_plan/plan.rs

N/A
While writing up https://github.com/apache/arrow-datafusion/issues/7001 I made some diagrams and descriptions about `Repartition` that I felt would add value as doc comments
Add docs to `RepartitionExec` and architecture guide
CI tests the doc comments
Docs

Docs: Add docs to `RepartitionExec` and architecture guide

---

datafusion/core/src/physical_plan/aggregates/order/full.rs
datafusion/core/src/physical_plan/aggregates/order/mod.rs
datafusion/core/src/physical_plan/aggregates/order/partial.rs
datafusion/core/src/physical_plan/aggregates/row_hash.rs

Closes #.
The approach of storing hashes in GroupOrdering was causing merge conflicts for #7016 and is not actually necessary

Don't store hashes in GroupOrdering

---

datafusion-cli/Dockerfile

Closes #7030
Make the build success.
To fix this issue, we need to use Rust 1.70+ and the workspace inheritance feature. So this change proposes to do so in the Dockerfile.
Confirmed `docker build` and `docker run` works successfully.
```
$ docker build -f datafusion-cli/Dockerfile . --tag datafusion-cli
$ docker run -v /path/to/data/:/data -it --rm datafusion-cli:latest
```
No.

Fix `datafusion-cli/Dockerfile` to build successfully

---

datafusion/core/tests/sqllogictests/test_files/subquery.slt
datafusion/core/tests/sqllogictests/test_files/tpch/q13.slt.part
datafusion/core/tests/sqllogictests/test_files/tpch/q15.slt.part
datafusion/sql/src/planner.rs
datafusion/sql/tests/sql_integration.rs

Closes #7027.
Reposition the projection from the top of the `SubqueryAlias` to below,  so that the columns referenced from the `SubqueryAlias` can have their qualifiers.
Yes
No

Move the column aliases below the SubqueryAlias

---

benchmarks/bench.sh

Part of https://github.com/apache/arrow-datafusion/issues/6994
See https://github.com/apache/arrow-datafusion/issues/6994
> The ClickBench benchmarks are both widely used in the industry and focus on grouping / aggregation / filtering: https://github.com/ClickHouse/ClickBench/tree/main/datafusion
Add support in bench.sh for downloading the ClickBench dataset (both single file as well as partitioned)
You can download it now via:
```shell
./bench.sh data clickbench_1 # single parquet file
./bench.sh data clickbench_partitioned # 100 parquet file partitioned dataset
```
Example
```shell
./bench.sh data clickbench_partitioned
***************************
DataFusion Benchmark Runner and Data Generator
COMMAND: data
BENCHMARK: clickbench_partitioned
DATA_DIR: …
```

Add support for ClickBench in bench.sh

---

datafusion-cli/Cargo.lock
datafusion/core/Cargo.toml
datafusion/core/src/physical_plan/aggregates/group_values/mod.rs
datafusion/core/src/physical_plan/aggregates/group_values/primitive.rs
datafusion/core/src/physical_plan/aggregates/group_values/row.rs
datafusion/core/src/physical_plan/aggregates/mod.rs
datafusion/core/src/physical_plan/aggregates/row_hash.rs

Part of #6969
```
Benchmark tpch_mem.json
┏━━━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Query        ┃     main ┃ specialize-primitive-group-values ┃        Change ┃
┡━━━━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ QQuery 1     │ 385.21ms │                          384.94ms │     no change │
│ QQuery 2     │ 102.04ms │                           91.22ms │ +1.12x faster │
│ QQuery 3     │ 104.50ms │                          108.36ms │     no change │
│ QQuery 4     │  69.37ms │                           72.72ms │     no change │
│ QQuery 5     │ 234.38ms │                          248.42ms │  1.06x slower │
│ QQuery 6     │  28.62ms │                           28.20ms │     no …
```

Specialize single column primitive group values

---

datafusion/common/src/scalar.rs

This came up in some profiles (mainly query 1, 16).
Benchmark results:
```
Benchmark tpch_mem.json
┏━━━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Query        ┃     main ┃ speedup_scalar_to_array_decimal ┃        Change ┃
┡━━━━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ QQuery 1     │ 199.40ms │                        182.91ms │ +1.09x faster │
│ QQuery 2     │  34.24ms │                         33.64ms │     no change │
│ QQuery 3     │  46.25ms │                         45.73ms │     no change │
│ QQuery 4     │  36.88ms │                         37.35ms │     no change │
│ QQuery 5     │  94.34ms │                         94.33ms │     no change │
│ QQuery 6     │  10.33ms │ …
```

[Minor] Speedup to_array_of_size for Decimal128

---

Cargo.toml
datafusion-cli/Cargo.lock
datafusion/core/src/execution/context.rs
datafusion/sql/src/set_expr.rs

Closes https://github.com/apache/arrow-datafusion/pull/7037
Keep up with dependencies
See title
Yes, existing CI

chore(deps): update sqlparser requirement from 0.35 to 0.36.1

---

datafusion-examples/examples/dataframe-to-s3.rs
datafusion/core/src/datasource/physical_plan/csv.rs
datafusion/core/src/datasource/physical_plan/json.rs
datafusion/core/src/datasource/physical_plan/mod.rs
datafusion/core/src/datasource/physical_plan/parquet.rs

Related to #1777
Many ETL and other workflows need to persist data to an ObjectStore. Currently, DataFrame write_parquet, write_json, and write_csv only support writing to a local file system. 
DataFrame write methods (write_parquet, write_json, and write_csv) now expect a ObjectStore URL registered in the current context. Unit tests are updated to accommodate this change, and an example for writing to S3 is added.
Existing unit tests are updated to cover this change.
Yes, users will now need to pass an ObjectStore url to write methods rather than a local path.

use ObjectStore for dataframe writes

---

datafusion/core/src/physical_planner.rs
datafusion/expr/src/logical_plan/builder.rs
datafusion/expr/src/logical_plan/plan.rs

refactor: with_inputs() can use original schema to avoid recompute schema.

---

datafusion/common/src/cast.rs
datafusion/common/src/scalar.rs
datafusion/core/tests/sqllogictests/test_files/arrow_typeof.slt
datafusion/core/tests/sqllogictests/test_files/decimal.slt
datafusion/expr/src/type_coercion/aggregates.rs
datafusion/physical-expr/src/aggregate/average.rs
datafusion/physical-expr/src/aggregate/sum.rs
datafusion/proto/proto/datafusion.proto
datafusion/proto/src/generated/pbjson.rs
datafusion/proto/src/generated/prost.rs
datafusion/proto/src/logical_plan/from_proto.rs
datafusion/proto/src/logical_plan/to_proto.rs

Add Decimal256 to `ScalarValue`

---

datafusion/core/tests/sqllogictests/test_files/binary.slt
datafusion/expr/src/type_coercion/binary.rs

Partial fix for #7039.
Closes https://github.com/apache/arrow-datafusion/issues/7039#
The following casts should be safe:
- Utf8 -> Binary | LargeBinary
- Utf8 | LargetUtf8 | Binary -> LargeBinary
Yes
No

Add Utf8->Binary type coercion for comparison

---

datafusion-examples/examples/simple_udaf.rs
datafusion/core/src/execution/context.rs
datafusion/core/src/physical_plan/windows/mod.rs
datafusion/core/tests/sql/udf.rs
datafusion/expr/src/expr_fn.rs
datafusion/optimizer/src/analyzer/type_coercion.rs
datafusion/proto/src/bytes/mod.rs
datafusion/proto/src/logical_plan/mod.rs

Closes #7094 .
For someone who is new to DataFusion and is trying to write a custom UDAF, it may be a little confusing to understand why create_udaf only takes one DataType for the input_type. Additionally, I did not find any examples demonstrating how to create a UDAF with multiple input arguments.
change `input_type: DataType` to `input_type: Vec<DataType>`
```
pub fn create_udaf(
name: &str,
return_type: Arc<DataType>,
volatility: Volatility,
accumulator: AccumulatorFactoryFunction,
state_type: Arc<Vec<DataType>>,
) -> AggregateUDF {
```
Yes
yes

change the input_type parameter of the create_udaf function from DataType to Vec<DataType>

---

datafusion/core/src/physical_plan/projection.rs
datafusion/core/tests/sqllogictests/test_files/groupby.slt

Closes #.
ProjectionExec has `columns_map: HashMap<Column, Vec<Column>>`. This map stores the mapping between columns in the input schema, and columns in the projection schema. During mapping it does matching according to name search. However, this is prone to error, since we may have columns with same name in the schema (such as after join).
This Pr removes name search during association. 
Yes new tests are added.

fix: Projection columns_map remove name search

---

datafusion/expr/src/built_in_function.rs

Related to https://github.com/apache/arrow-datafusion/pull/7008
I only just now realized what "dimension" meant in the context of ListArray / Arrays so I tried to document it
Doc comments

Minor: Refine doc comments for BuiltinScalarFunction::return_dimension

---

datafusion/proto/src/common.rs
datafusion/proto/src/logical_plan/mod.rs
datafusion/proto/src/physical_plan/mod.rs

refactor byte_to_string and string_to_byte

---

docs/source/user-guide/introduction.md

related to https://github.com/apache/arrow-datafusion/pull/7102
Closes https://github.com/apache/arrow-datafusion/pull/7103
inpsired by @MrPowers in https://github.com/apache/arrow-datafusion/pull/7102 I would like to make it easier for people to evaluate and decide to try DataFusion
Part of that decision is what other projects are using DataFusion and how well the project aligns with the prospective user's goals.
Thus, I think it would help to make a distinction between the "Active" users of DataFusion and "Dormant" to help people find the best comparison projects.
Move projects that haven't had at least one commit in the last 6 months to a separate section

Move inactive projects to a different section

---

benchmarks/src/tpch/convert.rs

Working on a wsl2 setup, bench.sh wasn't able to convert .tbl files to parquet files since the table folders under data/tpch{1,10} don't exist and so writing fails.
Proactively create these folders in `convert.rs`
Yeah, now it works locally
No
No
No

create all needed folders in advance for benchmarks

---

datafusion/sql/src/select.rs

Closes #.
As discussed in the [link](https://github.com/apache/arrow-datafusion/pull/7040#discussion_r1276232108), current documentation for group by rewrite is missing. And rationale for it was not clear. This PR updates the docstring of the `get_updated_group_by_exprs` function such that adds its usage, and its motivation is more clear.

[doc], [minor]. Update docstring of group by rewrite.

---

datafusion/core/tests/sqllogictests/test_files/groupby.slt
datafusion/physical-expr/src/aggregate/first_last.rs

Closes [#7118](https://github.com/apache/arrow-datafusion/issues/7118).
Thanks @alamb and @crepererum for filing the issue.

fix: fix index bug and add test to check it

---

datafusion/core/src/physical_plan/filter.rs
datafusion/core/tests/sqllogictests/test_files/predicates.slt

Closes https://github.com/apache/arrow-datafusion/issues/7125
Panic in query isn't good
Fix the check if a predicate is supported for range analysis 
yes
I also verified this PR passes the IOx tests  in https://github.com/influxdata/influxdb_iox/pull/8355

fix: Fix panic in filter predicate

---

.github/workflows/rust.yml
datafusion/core/Cargo.toml
datafusion/proto/Cargo.toml
datafusion/substrait/Cargo.toml

Closes #7122 
Sometimes, `rust-version` in Cargo.toml tends to be out of sync with the actual MSRV.
So, it's nice to have a MSRV check as a CI process.
Added a MSRV check job to GA for some packages `datafusion`, `datafusion-substrait`, `datafusion-proto` and `datafusion-cli` which are intended to be published.
The following packages are also intended to be published but `datafusion` depends on them. So, this PR doesn't include MSRV check for them.
* datafusion-expr
* datafusion-optimizer
* datafusion-physical-expr
* datafusion-sql
* datafusion-execution
GA.
No

Add MSRV check as a GA job

---

datafusion/core/src/physical_optimizer/sort_enforcement.rs
datafusion/core/src/physical_optimizer/test_utils.rs

Closes #.
In some tests, we use memory_exec for dummy source. However, in current version partition number size at the source is 0, which is weird a bit. In this PR, I changed the util so that it makes partition size 1.

[MINOR]: Make memory exec partition number =1, in test utils

---

datafusion/substrait/src/logical_plan/consumer.rs
datafusion/substrait/src/logical_plan/producer.rs
datafusion/substrait/tests/cases/roundtrip_logical_plan.rs

Closes #7116 .
Add support for `union` and `union all`
- Producer: support for `LogicalPlan::Union`
- Consumer: support for `set_rel::SetOp::UnionAll`
- DataFusion (v[28.0.0](https://github.com/apache/arrow-datafusion/tree/28.0.0)) represents `union` as `agg+union all` in optimized plan (`distinct+union all` in unoptimized plan). Thus, only `union all` needs support in the consumer
- Other set operations are not yet supported
- Unit tests: `union`, `union all`, `union`s of more than 2 tables
Yes
No

Substrait union/union all

---

datafusion/common/src/scalar.rs

Closes [#7089](https://github.com/apache/arrow-datafusion/issues/7089).
`size_of_scalar` test seems to be failing in M1 machines. This PR removes this test when target architecture is arm64.

minor: Remove mac m1 compilation for size_of_scalar test

---

datafusion/core/tests/memory_limit.rs
datafusion/execution/src/config.rs

Part of https://github.com/apache/arrow-datafusion/issues/5885
Broken out of https://github.com/apache/arrow-datafusion/pull/7130 for easier / quicker review
I want to write a test for sort preserving merge memory limiting. The tests are awkward to extend at the moment and have some duplicated logic
Refactor the `memory_limit` tests so they can be easily extended (see https://github.com/apache/arrow-datafusion/pull/7130 for an example of doing so) 
all tests
no

Refactor memory_limit tests to make them easier to extend

---

datafusion/core/src/physical_plan/memory.rs

Related to https://github.com/apache/arrow-datafusion/pull/6382
I set the ordering on MemExec but it didn't show up on the explain plan
Show the output ordering, if present

Minor: show output ordering in MemoryExec

---

datafusion/core/tests/sqllogictests/test_files/aggregate.slt
datafusion/expr/src/aggregate_function.rs
datafusion/expr/src/type_coercion/aggregates.rs
datafusion/physical-expr/src/aggregate/build_in.rs
datafusion/physical-expr/src/aggregate/mod.rs
datafusion/physical-expr/src/aggregate/regr_slope.rs
datafusion/physical-expr/src/expressions/mod.rs
datafusion/proto/proto/datafusion.proto
datafusion/proto/src/generated/pbjson.rs
datafusion/proto/src/generated/prost.rs
datafusion/proto/src/logical_plan/from_proto.rs
datafusion/proto/src/logical_plan/to_proto.rs
docs/source/user-guide/sql/aggregate_functions.md

NA
I'm planning to add PostgreSQL linear regression aggregate functions. Their implementations are similar, so I'd like to implement `regr_slope(y, x)` first, and the remaining functions should be easy to extend.
Adding `regr_slope(y, x)` aggregate function, mainly implementing `Accumulator` for `RegrSlopeAccumulator`
The linear regression is calculated using `COVAR_POP(x,y) / VAR_POP(x)`
One-pass and parallel algorithm for `covar/var` reference: https://en.wikipedia.org/wiki/Algorithms_for_calculating_variance#Welford's_online_algorithm
All end-to-end tests produced the same result compared to Postgres
No

Add regr_slope() aggregate function

---

datafusion/core/tests/dataframe/mod.rs
datafusion/expr/src/expr_fn.rs

Closes [#7157 ](https://github.com/apache/arrow-datafusion/issues/7157).
Make it possible to perform `array_agg` with the DataFrame API.
The appropriate export for the `array_agg` expression.
Yes
[array_agg](https://docs.rs/datafusion-expr/28.0.0/datafusion_expr/expr_fn/fn.array_agg.html) added.

Add expression for array_agg

---

datafusion/core/src/datasource/file_format/csv.rs
datafusion/core/src/datasource/physical_plan/csv.rs
datafusion/core/src/datasource/physical_plan/json.rs

Previously `cargo test -p datafusion --no-default-features --lib` failed with 77 tests panicking with the message:
> Compression is not supported in this build
This commit fixes this test failure under --no-default-features by excluding the tests via `#[cfg(feature = "compression")]`.

fix: skip compression tests on --no-default-features

---

datafusion/core/src/physical_plan/joins/hash_join.rs
datafusion/core/tests/sqllogictests/test_files/join_disable_repartition_joins.slt

Closes https://github.com/apache/arrow-datafusion/issues/7113.
Fixing the HashJoin order.
Reversing indices.
Yes, with existing tests.
No

HashJoin order fixing

---

.github/pull_request_template.md

The PR title is an `<h1>`, so headings in
the PR description should start at `<h2>`.

tweak: demote heading levels in PR template

---

datafusion/core/src/physical_plan/mod.rs

Skip the PR template as there is no code changes.
1. Fix a broken link in the doc of `datafusion::physical_plan::SendableRecordBatchStream`

docs: fix broken link

---

datafusion/core/src/dataframe.rs

Closes #7182.
The main motivation for this change is to provide ability to extend DataFrame with additional write methods. Problem is if this method is not public we'd need to provide external ctx to write method
`dataframe.task_ctx(&self)` exposed as public
it is backward compatible, but there is still question if maintainers want to make this method public

make dataframe.task_ctx public

---

datafusion-cli/src/exec.rs
datafusion-cli/src/helper.rs
datafusion-cli/src/print_options.rs
datafusion-cli/tests/cli_integration.rs

Closes #6793.
This PR allows `datafusion-cli` to accept multiple statements.

feat: allow `datafusion-cli` to accept multiple statements

---

datafusion/core/src/datasource/physical_plan/avro.rs
datafusion/core/src/datasource/physical_plan/csv.rs
datafusion/core/src/datasource/physical_plan/json.rs
datafusion/core/src/datasource/physical_plan/mod.rs
datafusion/core/src/datasource/physical_plan/parquet.rs
datafusion/core/src/physical_plan/mod.rs

I want to feature-gate AvroExec in a followup commit, so that you cannot get bitten by AvroExec::execute returning an NotImplemented error if the "avro" feature isn't enabled. (Since idiomatic Rust code should work if it compiles.)
As a preparation for that this commit gets rid of a `plan_any.downcast_ref::<AvroExec>()` call that couldn't be easily put behind a `cfg(feature = "avro")` without complicating the control flow.
Yes this PR adds the `file_scan_config` method to the `ExecutionPlan` trait.

refactor: add ExecutionPlan::file_scan_config to avoid downcasting

---

datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs
datafusion/optimizer/src/simplify_expressions/regex.rs

Closes #7185
Strings with underline are very common, e.g. id_1,id_2. But the current regrex expression optimization ignores underline. For regrex expressions of the form `~ ^(id_1|id_2)$`, we are required to support the string with underline.
Add test case in expr_simplifier.rs

Support simplifying expressions such as `~ ^(ba_r|foo)$` , where the string includes underline

---

datafusion/execution/src/memory_pool/mod.rs
datafusion/execution/src/memory_pool/pool.rs

Part of https://github.com/apache/arrow-datafusion/issues/5885
This PR contains new MemoryReservation APIs used in https://github.com/apache/arrow-datafusion/pull/7130. They were originally written by @tustvold  and I polished them up, fixed a bug, and added tests
I broke it into its own PR for ease in reviewing. You can see the usecase in https://github.com/apache/arrow-datafusion/pull/7130.
1. Add new APIs and tests
Yes

Add MemoryReservation::{split_off, take, new_empty}

---

benchmarks/bench.sh

related to https://github.com/apache/arrow-datafusion/pull/6893
I changed `bench.sh` in  https://github.com/apache/arrow-datafusion/pull/6893 to run 10 iterations of each benchmark in the hopes this would make my runs more predictable / less noisy
I do not think the numbers are any more predictable and now my benchmark runs (like for #7180 ) are taking 2x as long
Change iterations from 10 to 5

Update bench.sh to only run 5 iterations

---

datafusion/core/src/dataframe.rs
datafusion/core/src/datasource/file_format/csv.rs
datafusion/core/src/datasource/file_format/options.rs
datafusion/core/src/datasource/listing/mod.rs
datafusion/core/src/datasource/listing/table.rs
datafusion/core/src/datasource/memory.rs
datafusion/core/src/datasource/physical_plan/json.rs
datafusion/core/src/datasource/physical_plan/mod.rs
datafusion/core/src/datasource/provider.rs
datafusion/core/src/execution/context.rs
datafusion/core/src/physical_plan/insert.rs
datafusion/core/src/physical_planner.rs
datafusion/core/tests/sqllogictests/test_files/explain.slt
datafusion/core/tests/sqllogictests/test_files/insert.slt
datafusion/expr/src/logical_plan/builder.rs
datafusion/expr/src/logical_plan/dml.rs
datafusion/sql/src/statement.rs
datafusion/sql/tests/sql_integration.rs

None, but progresses towards the goals of #5076 and #7079
The goal of this PR is to enable DataFrame write methods to leverage a common implementation with SQL `Insert Into` statements, so that common logic related to writing via `ObjectStore` and parallelization or other optimizations can be made in one place (such as those discussed in #7079).
The following changes are completed/planned:
The following work is planned for follow up PRs
Yes, a test case is added for using `insert into` to append new files to a listing table.
The `write_table` method is a new public method to expose the functionality of the `insert_into` logical plan for DataFrames.

Unify DataFrame and SQL (Insert Into) Write Methods

---

datafusion/proto/src/bytes/mod.rs

On my local dev machine, `cargo test roundtrip_deeply_nested` aborts with a stack overflow error. Increasing the `stack_size` value in the test fixes the problem. It is unclear to me why this is required for me locally, but does not affect the CI pipeline (or presumably other devs).
Increase stack_size to 20_000_000 from previous value of 10_000_000.
N/A
No.

Minor: Further Increase stack_size to prevent roundtrip_deeply_nested test stack overflow

---

datafusion/core/src/physical_plan/common.rs

Closes #7206.
`spawn_buffered` function will use tokio context to spawn the execution of stream if tokio runtime is started. However, if the started runtime is current-thread and it is blocked on, spawned tasks could be possibly dead-locked.
Manually tested in internal code if using current-thread tokio runtime.

Use tokio only if running from a multi-thread tokio context

---

datafusion/core/src/physical_planner.rs
datafusion/expr/src/expr.rs
datafusion/expr/src/expr_schema.rs
datafusion/expr/src/field_util.rs
datafusion/expr/src/lib.rs
datafusion/expr/src/tree_node/expr.rs
datafusion/physical-expr/src/expressions/get_indexed_field.rs
datafusion/physical-expr/src/expressions/mod.rs
datafusion/physical-expr/src/planner.rs
datafusion/proto/proto/datafusion.proto
datafusion/proto/src/generated/pbjson.rs
datafusion/proto/src/generated/prost.rs
datafusion/proto/src/logical_plan/from_proto.rs
datafusion/proto/src/logical_plan/to_proto.rs
datafusion/proto/src/physical_plan/from_proto.rs
datafusion/proto/src/physical_plan/mod.rs
datafusion/proto/src/physical_plan/to_proto.rs
datafusion/sql/src/expr/identifier.rs
datafusion/sql/src/expr/mod.rs
datafusion/sql/src/utils.rs

Closes https://github.com/apache/arrow-datafusion/issues/7193
Closes https://github.com/apache/arrow-datafusion/issues/7146
Yes
Yes

improve the ergonomics of creating field and list array accesses

---

docs/source/user-guide/introduction.md

Add https://github.com/GlareDB/glaredb as noticed by @andygrove  to the list of systems powered by DataFusion
cc @scsmithr

Docs: Add GlareDB to list of DataFusion users

---

datafusion/substrait/src/logical_plan/producer.rs
datafusion/substrait/tests/cases/roundtrip_logical_plan.rs

Closes #.
Try to encode `-` in substrait will report an error that "substract" is not supported
```
170   │ 2023-08-08T03:52:46.109050Z  WARN servers::mysql::server: Internal error occurred during query exec, server actively close the channel to let client try next time: Failed to collect recordbatch, source: Failed to poll stream, source: External error: External er
│ ror, source: Failed to request remote peer, source: Failed to do Flight get, code: Internal error, source: This feature is not implemented: Unsupported function name: "substract".
```
Correct typo "substract" to "subtract" 
Yes
No

fix: typo in substrait

---

datafusion/physical-expr/src/expressions/get_indexed_field.rs

Related to https://github.com/apache/arrow-datafusion/issues/7193
Minor follow on to https://github.com/apache/arrow-datafusion/pull/7215/files
I figured this code could have some more comments and make it easier to construct tests
Minor: Add constructors to GetFieldAccessExpr and add docs
Yes

Minor: Add constructors to GetFieldAccessExpr and add docs

---

.asf.yaml

Closes #.
It is required that PR is approve to make Merge

chore: required at least 1 approve before merge

---

datafusion/core/tests/sqllogictests/test_files/aggregate.slt
datafusion/expr/src/aggregate_function.rs
datafusion/expr/src/type_coercion/aggregates.rs
datafusion/physical-expr/src/aggregate/build_in.rs
datafusion/physical-expr/src/aggregate/mod.rs
datafusion/physical-expr/src/aggregate/regr.rs
datafusion/physical-expr/src/expressions/mod.rs
datafusion/proto/proto/datafusion.proto
datafusion/proto/src/generated/pbjson.rs
datafusion/proto/src/generated/prost.rs
datafusion/proto/src/logical_plan/from_proto.rs
datafusion/proto/src/logical_plan/to_proto.rs
docs/source/user-guide/sql/aggregate_functions.md

NA
A previous PR first implemented `regr_slope(y, x)` linear regression aggregate function https://github.com/apache/arrow-datafusion/pull/7135
This PR wants to extend the previous one to implement all PostgreSQL's linear regression aggregate functions like `regr_intercept(y, x)`
https://www.postgresql.org/docs/9.4/functions-aggregate.html
Extend `RegrAccumulator` to support other `regr_*(y, x)` aggregate functions
All end-to-end tests have the same result compared to PostgreSQL
No

Add linear regression aggregate functions

---

datafusion/expr/src/expr.rs
datafusion/sql/src/expr/identifier.rs

Related to https://github.com/apache/arrow-datafusion/issues/7193
Follows https://github.com/apache/arrow-datafusion/pull/7215 from @izveigor 
In order to have a good experience accessing fields, it should be easy to create field / lists accesses
See subject
Yes -- with doc tests 
New methods on `Expr`

Add `Expr::field`, `Expr::index`, and `Expr::slice`, add docs

---

datafusion/core/src/datasource/file_format/csv.rs
datafusion/core/src/datasource/file_format/json.rs
datafusion/core/src/datasource/file_format/mod.rs
datafusion/core/src/datasource/file_format/options.rs
datafusion/core/src/datasource/listing/table.rs

None, but progresses towards the goals of #5076 and #7079. Follow on to #7141. 
Adds support for `insert into <table>` for tables which are backed by Json files. 
- Implements `JsonSink `in similar fashion to `CsvSink`
- Minor refactor of `CsvSink` to support code reuse with `JsonSink`
- Generalized existing tests of `insert into` to be easily extensible for additional `FileFormats` and `options`
- Added test coverage for appending to existing Json files and appending new Json files to a `ListingTable`
- Added checks and throw error if attempting insert to sorted or compressed table since not implemented yet
Yes
Insert into Json table will work now.

Extend insert into support to include Json backed tables

---

datafusion/sql/src/utils.rs

N/A
While maintaining a copy of the `clone_with_replacement` function in IOx I realized it simply duplicates the more general ["TreeNode" API](https://docs.rs/datafusion/latest/datafusion/common/tree_node/index.html)
I think this will make adding/modifing `Expr` variants will be easier as there are fewer things that need to be changed
1. Remove `clone_with_replacement`
2. Rewrite the uses of `clone_with_replacement` terms of treenode API
no -- `clone_with_replacement` is not a publicly exposed function

Minor: Remove unecessary `clone_with_replacement`

---

datafusion/core/tests/sqllogictests/test_files/array.slt
datafusion/physical-expr/src/array_expressions.rs
datafusion/physical-expr/src/scalar_function.rs

Support `make_array` null handling in nested version

---

datafusion/core/src/datasource/physical_plan/mod.rs
datafusion/core/tests/sqllogictests/test_files/groupby.slt

Closes #.
At the projection of the source, we keep track of ordering as long as they are used in the query.
Consider table below
```sql
CREATE EXTERNAL TABLE multiple_ordered_table (
a0 INTEGER,
a INTEGER,
b INTEGER,
c INTEGER,
d INTEGER
)
STORED AS CSV
WITH HEADER ROW
WITH ORDER (a ASC, b ASC)
WITH ORDER (c ASC)
LOCATION 'tests/data/window_2.csv';
```
which satisfies ordering `a ASC, b ASC` and `c ASC`.
If we run the query below on this table.
```sql
SELECT c
FROM multiple_ordered_table
ORDER BY c ASC;
```
since, only column `c` is used. We will not keep track of ordering `a ASC, b ASC`. However, during projection of orderings
empty vectors are still added to output ordering. Since, first entry in among alternative orderings is output_ordering. Output ordering of the `CsvExec` is empty. …

[Minor], Bug Fix: Add empty ordering check at the source.

---

datafusion/core/src/physical_optimizer/replace_with_order_preserving_variants.rs
datafusion/core/src/physical_plan/repartition/mod.rs
datafusion/core/tests/fuzz_cases/sort_preserving_repartition_fuzz.rs

Closes #.
`with_preserve_order` was setting `preserve_order` flag of the `RepartitionExec` to `true`. Other executors generally take argument to set the flag. With this PR, `with_preserve_order` member also receives flag argument.

Minor: with preserve order now receives argument

---

datafusion-examples/Cargo.toml

Closes #.
In `datafusion-examples/Cargo.toml`, `[[example]]` tables are defined like as follows.
```
[[example]]
name = "avro_sql"
path = "examples/avro_sql.rs"
required-features = ["datafusion/avro"]
```
But `avro_sql.rs` is in `examples`, we don't need to have `[[example]]` table for `avro_sql`.
Remove the `[[example]]` table from the `Cargo.toml`.
I confirmed `avro_sql` still work even after this change with `cargo run --example avro_sql --features datafusion/avro`
No.

Minor: Remove [[example]] table from datafusion-examples/Cargo.toml

---

benchmarks/queries/q8.sql

Remove additional cast from TPCH q8

---

datafusion/common/src/lib.rs
datafusion/common/src/utils.rs
datafusion/core/src/datasource/empty.rs
datafusion/core/src/datasource/listing/table.rs
datafusion/core/src/physical_plan/memory.rs
datafusion/core/src/physical_plan/mod.rs
datafusion/core/tests/custom_sources.rs
datafusion/core/tests/custom_sources_cases/statistics.rs

As part of preparing (finally) to move the physical_plan into its own crate so datafusion builds faster and is more modular, I am trying to clean up cross module dependencies where I find them
1. Move `project_schema` into datafusion_common
2. Update `use` for `project_schema` in `datasource`
tested by existing tests
No -- I left a `pub use` for backwards compatibility

Minor: Move `project_schema` to `datafusion_common`

---

datafusion/core/src/physical_plan/mod.rs
datafusion/core/src/physical_plan/visitor.rs

I am trying to improve the code structure of DataFusion -- I tried to remove this function and replace it with the TreeNode API but I was not successful. At least I can pull this code into its own module to make it easier to find
Move ExecutionPlanVisitor and some related functions into their own `visitor.rs` module
No -- I left `pub use` so no changes should be needed

Minor: Extract ExecutionPlanVisitor to its own module

---

datafusion-cli/Cargo.lock
datafusion/core/src/physical_plan/mod.rs
datafusion/core/src/physical_plan/stream.rs
datafusion/execution/Cargo.toml
datafusion/execution/src/stream.rs

As part of preparing (finally) to move the physical_plan into its own crate so datafusion builds faster and is more modular, I am doing some code rearranging to slim down the contents of `physical_plan/mod.rs`
1. Move `RecordBatchStream` and `SendableRecordBatchStream` to `datafusion_execution` crate
2. Move `EmptyStream` into `stream.rs` with other stream wrappers (so hopefully it will be more discoverable)
No: I left `pub use` so there should be no backwards incompatible changes

Minor: Move streams out of `physical_plan` module

---

datafusion/core/src/physical_plan/common.rs
datafusion/core/src/physical_plan/sorts/sort.rs

Related to https://github.com/apache/arrow-datafusion/issues/5885
Suggested by @yjshen in https://github.com/apache/arrow-datafusion/pull/7130#discussion_r1287837220
`batch_byte_size` has been ported upstream and is now available as [`RecordBatch::get_array_memory_size`](https://docs.rs/arrow/latest/arrow/record_batch/struct.RecordBatch.html#method.get_array_memory_size)
Changes
1. deprecate batch_byte_size
2. Update to use `RecordBatch::get_array_memory_size` instead
Yes, by clippy CI check
A deprecated function telling them what to change

Deprecate `batch_byte_size`

---

datafusion/core/tests/memory_limit.rs

Closes #.
Fix clippy for the main branch.
Avoid using the deprecated function.
Existing tests
No.

Minor: fix clippy for memory_limit test

---

datafusion/core/src/physical_plan/projection.rs
datafusion/core/src/physical_plan/repartition/mod.rs
datafusion/core/tests/sqllogictests/test_files/select.slt

Closes #.
This PR adds 
-Now projection doesn't benefit from parallelism when all of the expressions are either `Column` or `Literal`
- `benefits_from_input_partitioning` flag is implemented for `RepartitionExec` (increasing partition is only beneficial for hash partition.)
- unrelated minor change: `preserve_order` method is added to the `RepartitionExec` to inspect `preserve_order` flag of the, `RepartitionExec`.

[MINOR]: update benefits_from_input_partitioning implementation for projection and repartition

---

datafusion/core/src/physical_plan/joins/symmetric_hash_join.rs
datafusion/core/src/physical_plan/joins/test_utils.rs
datafusion/core/src/physical_plan/memory.rs
datafusion/core/tests/fuzz_cases/aggregate_fuzz.rs
datafusion/core/tests/fuzz_cases/sort_preserving_repartition_fuzz.rs
datafusion/core/tests/fuzz_cases/window_fuzz.rs
datafusion/core/tests/memory_limit.rs

Closes #.
Currently, MemoryExec does not accept multi-globally ordered expressions, unlike the external tables with multiple WITH ORDER. This PR adds it, just like the external tables. 
MemoryExec API is changed.
Yes
Not currently.

Adding order equivalence support on MemoryExec

---

datafusion/core/tests/sqllogictests/test_files/functions.slt
datafusion/expr/src/built_in_function.rs

Closes #5471.
Running `upper(col)` where `col` is a dictionary results in an internal error:
```
Internal error: The "upper" function can only accept strings.. This was likely caused by a bug in DataFusion's code and we would welcome that you file an bug report in our issue tracker
```
Other functions like `length` and `character_length` also have the same issue. Here is a list of all the functions with the same issue:
```
$ grep utf8_to_str_type
datafusion/expr/src/built_in_function.rs
600:                utf8_to_str_type(&input_expr_types[0], "btrim")
628:                utf8_to_str_type(&input_expr_types[0], "initcap")
630:            BuiltinScalarFunction::Left => utf8_to_str_type(&input_expr_types[0], "left"),
632:                utf8_to_str_type(&input_expr_types[0], "lower")
634: …
```

fix(functions): support `Dictionary` for string and int functions
