datafusion/core/src/datasource/memory.rs
datafusion/core/src/datasource/streaming.rs
datafusion/core/src/physical_plan/streaming.rs

Related to https://github.com/apache/arrow-datafusion/pull/6566
While helping with  https://github.com/apache/arrow-datafusion/pull/6566 I really wanted to know what the actual schemas involved were, not just that they were mismatched
Add some `debug!` logging prior to raising an error
no
no, debugging logs only

Minor: Add debug logging for schema mismatch errors

---

datafusion/core/src/datasource/listing/table.rs

Closes #.
Similar to https://github.com/apache/arrow-datafusion/pull/6605.
No

fix: fix more panics in `ListingTable`

---

datafusion/core/tests/sqllogictests/test_files/decimal.slt
datafusion/physical-expr/src/aggregate/median.rs

Closes https://github.com/apache/arrow-datafusion/issues/6633
Yes
Yes

fix: median with even number of `Decimal128` not working

---

datafusion/core/tests/sqllogictests/test_files/aggregate.slt

already created table at `sqllogictests/src/main.rs`
https://github.com/apache/arrow-datafusion/blob/d3ef6c88d886fe1d3662c316d614b9c9c5c2e4f1/datafusion/core/tests/sqllogictests/src/setup.rs#L67-L72

Minor: cleanup the unnecessary CREATE TABLE aggregate_test_100 statement at aggregate.slt

---

datafusion/physical-expr/src/expressions/binary.rs

Like `test_coercion` for `BitwiseAnd`, `BitwiseOr`, `BitwiseXor`.

Minor: add test cases for coercion bitwise shifts

---

datafusion/expr/src/logical_plan/builder.rs
datafusion/optimizer/src/analyzer/type_coercion.rs
datafusion/optimizer/src/eliminate_outer_join.rs
datafusion/optimizer/src/optimizer.rs
datafusion/optimizer/src/push_down_filter.rs
datafusion/optimizer/src/utils.rs

Closes #.
use `with_new_inputs` replace `from_plan`, make code clear

minor: `with_new_inputs` replace `from_plan`

---

docs/source/user-guide/cli.md
docs/source/user-guide/example-usage.md

Closes #.
Refreshing user guide

Minor: Update user guide

---

datafusion/core/src/datasource/listing/mod.rs
datafusion/core/src/datasource/physical_plan/mod.rs

N/A
Just fixing some typo (and duplicates) in documentation
- Doc updates
N/A
N/A

Fix documentation typo

---

datafusion/core/src/execution/context.rs
datafusion/sql/src/expr/arrow_cast.rs
datafusion/sql/src/expr/grouping_set.rs
datafusion/sql/src/expr/identifier.rs
datafusion/sql/src/expr/mod.rs
datafusion/sql/src/expr/unary_op.rs

Closes #.
Some Error type is wrong

fix: correct the error type

---

datafusion-cli/Cargo.lock
datafusion/expr/Cargo.toml

chore(deps): update strum/strum_macros requirement from 0.24 to 0.25

---

datafusion/optimizer/src/merge_projection.rs
datafusion/optimizer/src/push_down_projection.rs

Closes #.
extract common function from `push down project` and `merge_project`

refactor: extract merge_projection common function.

---

datafusion/substrait/src/logical_plan/producer.rs

Closes #.
Now we pass ordering requirement of the aggregate function to the `sorts` field of the `substrait::proto::AggregateFunction`.

MINOR: Aggregate ordering substrait support

---

datafusion-cli/Cargo.lock
datafusion/core/Cargo.toml
datafusion/optimizer/Cargo.toml
datafusion/physical-expr/Cargo.toml
datafusion/substrait/Cargo.toml

chore(deps): update itertools requirement from 0.10 to 0.11

---

datafusion/core/src/physical_plan/common.rs

N/A
Just moving some definition before tests module.
N/A
N/A
N/A

refactor: move some code in physical_plan/common.rs before tests module

---

datafusion/core/tests/sqllogictests/test_files/subquery.slt

Closes #6606.
Add UT to verify the issue was fixed.

add UT to verify the fix on "issues/6606"

---

.asf.yaml

Closes #.
Following the renaming of master to main, I ended up getting my local checkout into a confused state because main didn't exist in my fork. This all culminated in me accidentally force pushing the main branch on this repo instead of my fork. Fortunately I was able to recover this situation, but we should prevent this from happening in future

Protect main branch

---

datafusion/core/src/datasource/listing/helpers.rs
datafusion/core/src/physical_planner.rs
datafusion/expr/src/expr.rs
datafusion/expr/src/expr_rewriter/mod.rs
datafusion/expr/src/expr_rewriter/order_by.rs
datafusion/expr/src/expr_schema.rs
datafusion/expr/src/logical_plan/builder.rs
datafusion/expr/src/logical_plan/plan.rs
datafusion/expr/src/tree_node/expr.rs
datafusion/expr/src/utils.rs
datafusion/optimizer/src/analyzer/count_wildcard_rule.rs
datafusion/optimizer/src/common_subexpr_eliminate.rs
datafusion/optimizer/src/decorrelate.rs
datafusion/optimizer/src/push_down_filter.rs
datafusion/optimizer/src/push_down_projection.rs
datafusion/optimizer/src/utils.rs
datafusion/physical-expr/src/planner.rs
datafusion/proto/src/logical_plan/from_proto.rs
datafusion/proto/src/logical_plan/to_proto.rs
datafusion/sql/src/select.rs
datafusion/sql/src/utils.rs
datafusion/substrait/src/logical_plan/producer.rs

Closes #.
it's first step of #6681
encapsulate Alias as a struct

refactor: encapsulate Alias as a struct

---

Cargo.toml
datafusion-cli/Cargo.lock
datafusion-cli/Cargo.toml

Upgrade arrow 43

---

datafusion/core/src/datasource/physical_plan/mod.rs
datafusion/core/src/datasource/streaming.rs
datafusion/core/src/physical_plan/streaming.rs

Closes https://github.com/apache/arrow-datafusion/issues/6859.
A mini PR for refactoring StreamingTableExec
Order information is added into `StreamingTableExec`
NA
NA

[MINOR] Adding order into StreamingTableExec

---

docs/source/user-guide/sql/scalar_functions.md

Closes #.
Documents code added in https://github.com/apache/arrow-datafusion/pull/6821 by @ozgrakkurt 
Add new section to the user guide (based off https://www.postgresql.org/docs/9.4/functions-binarystring.html)
existing tests
docs

docs: Add `encode` and `decode` to the user guide

---

datafusion-cli/Cargo.lock
datafusion/common/src/display/graphviz.rs
datafusion/common/src/display/mod.rs
datafusion/core/src/physical_plan/display.rs
datafusion/core/src/physical_plan/streaming.rs
datafusion/core/src/physical_planner.rs
datafusion/core/tests/sql/explain_analyze.rs
datafusion/expr/src/logical_plan/display.rs
datafusion/expr/src/logical_plan/plan.rs

Display execution plan in graphviz format.
Part of #3606 .

feat: Add graphviz display format for execution plan.

---

docs/source/user-guide/sql/data_types.md

[minor]fix doc to remove duplicate content

---

datafusion/expr/src/expr_fn.rs

chore: fix format

---

datafusion/execution/src/memory_pool/proxy.rs

Closes #.
Tripling the allocation is a little unusual and I suspect is a mistake.
This does not appear to have a discernible impact on benchmarks, the variation appears to just be noise, but I think we should probably fix this unless it was intentional

Double RawTable on grow instead of triple

---

datafusion/expr/src/type_coercion/binary.rs

Add more Decimal256 type coercion

---

datafusion/core/src/physical_plan/aggregates/order/partial.rs
datafusion/core/tests/sqllogictests/test_files/groupby.slt

Closes #7100 .
See the #7100  for rationale, and reproducer.
Yes new test is added.

Relax check during aggregate partial mode.

---

README.md

Closes https://github.com/apache/arrow-datafusion/pull/7061
Inspired by @MrPowers's proposal in https://github.com/apache/arrow-datafusion/pull/7061, I think we can make it easier for people who land at the DataFusion README to find what they are looking for quickly. 
See rendered change here: https://github.com/alamb/arrow-datafusion/tree/alamb/readme#readme
Basically:
1. Add links in bullet list for efficient location
2. Remove outdated codecov badge that is visually distracting
3. Add direct link to known users

 Add additional links to main README

---

datafusion/core/tests/sqllogictests/test_files/array.slt
datafusion/physical-expr/src/array_expressions.rs
datafusion/physical-expr/src/functions.rs

`make_array` with column of list

---

datafusion/core/src/physical_plan/joins/nested_loop_join.rs

Closes #.
There appears to be an error with the full join in the table.
Only comment change.
NA
NA

[MINOR] Document refactor on NestedLoopJoin

---

datafusion/common/src/scalar.rs

fix: build_timestamp_list data type mismatch

---

datafusion/core/src/datasource/file_format/parquet.rs

Follow on to https://github.com/apache/arrow-datafusion/pull/7244 from @devinjdangelo 
Add a comment with  upstream ticket reference to https://github.com/apache/arrow-rs/issues/4693
No code changes

Minor: Add upstream ticket reference in comments

---

datafusion/expr/src/expr_fn.rs

Minor: Fix documentation typos for array expressions

---

datafusion/expr/src/logical_plan/plan.rs

n/a
While working on https://github.com/influxdata/influxdb_iox/pull/8515 I had some questions about the various `LogicalPlan` that I had to look up in the code. I wanted to encode this information as doc comments so I didn't have to do it a second time
1. Update docstrings for `LogicalPlan`
N/A
better (hopefully) docs

Minor: Improve docstrings for `LogicalPlan`

---

datafusion/sql/src/parser.rs

minor: fix doc/typo

---

datafusion/physical-expr/src/aggregate/average.rs

Closes #.
Removed redundant type check in `Avg`. When I did a post-merging review of #7369, the old type check looks redundant as its type coercion is now explicit.

Remove redundant type check in Avg

---

Cargo.toml
datafusion-cli/Cargo.lock
datafusion/sql/src/expr/mod.rs
datafusion/sql/src/expr/substring.rs
datafusion/sql/src/planner.rs
datafusion/sql/src/statement.rs

Closes #7386.
[dependabot](https://github.com/apps/dependabot) failed to update sqlparser due to some upstream changes.
Update sqlparser requirement from 0.36.1 to 0.37.0

Update sqlparser requirement from 0.36.1 to 0.37.0

---

.github/workflows/rust.yml

Closes https://github.com/apache/arrow-datafusion/pull/7407
Based on suggestion in https://github.com/actions/setup-python/issues/709

Fix python CI

---

docs/source/user-guide/sql/ddl.md

Related to https://github.com/apache/arrow-datafusion/pull/7477
Suggested by @jackwener  on https://github.com/apache/arrow-datafusion/pull/7477/files#r1316669263
Update docs

minor: Add ARROW to `CREATE EXTERNAL TABLE` docs and add example of `COMPRESSION TYPE`

---

datafusion/sql/src/parser.rs

N/A
Improve error message as suggested by @yjshen on https://github.com/apache/arrow-datafusion/pull/7489#issuecomment-1708912465
Include `ARROW` in parser error message

Minor: improve error message

---

datafusion/common/src/scalar.rs
datafusion/core/src/datasource/physical_plan/file_scan_config.rs
datafusion/core/src/physical_plan/filter.rs
datafusion/core/src/physical_plan/joins/hash_join_utils.rs
datafusion/core/tests/path_partition.rs
datafusion/expr/src/columnar_value.rs
datafusion/expr/src/expr_schema.rs
datafusion/physical-expr/src/aggregate/array_agg_ordered.rs
datafusion/physical-expr/src/datetime_expressions.rs
datafusion/physical-expr/src/expressions/literal.rs
datafusion/physical-expr/src/expressions/mod.rs
datafusion/physical-expr/src/expressions/not.rs
datafusion/physical-expr/src/expressions/nullif.rs
datafusion/physical-expr/src/intervals/interval_aritmetic.rs
datafusion/proto/src/logical_plan/from_proto.rs
datafusion/proto/src/logical_plan/to_proto.rs

Minor: deprecate ScalarValue::get_datatype()

---

datafusion/core/Cargo.toml

Closes https://github.com/apache/arrow-datafusion/issues/7540.
Cargo update.
With existing tests.
No.

Update the async-trait crate to resolve clippy bug

---

datafusion/core/Cargo.toml
datafusion/core/src/physical_plan/aggregates/topk/heap.rs

Closes #7550.
Replace `ptree` with `termtree`
Existing tests have been modified for new assertions (which have been manually verified to match)
No.

replace ptree with termtree

---

datafusion/core/src/physical_plan/aggregates/mod.rs

Closes #.
In codebase, we have some checks to understand whether group by expression is single group or grouping set. In this PR, I add a new method for this check.

[MINOR]: Add is single method

---

datafusion/core/src/physical_optimizer/topk_aggregation.rs
datafusion/physical-plan/src/aggregates/mod.rs
datafusion/sqllogictest/test_files/aggregate.slt

Closes #7608.
Resolve a panic for specific types of TopK queries.
- a fix
- a test
2/4... still trying to figure out how to test the last case. Maybe 3/4 is the best I can do.
More queries should work

Fix panic in TopK

---

docs/source/user-guide/sql/scalar_functions.md

N/A
While working on https://github.com/apache/arrow-datafusion/issues/7604 it took me some time to figure out the syntax for creating specific `Timestamp` types, so I wanted to tell my future self (and others) how to do it

Minor: add examples for `arrow_cast` and `arrow_typeof` to user guide

---

datafusion/physical-expr/src/aggregate/regr.rs
datafusion/physical-expr/src/expressions/mod.rs
datafusion/physical-expr/src/window/lead_lag.rs
datafusion/physical-expr/src/window/mod.rs
datafusion/physical-expr/src/window/ntile.rs
datafusion/proto/proto/datafusion.proto
datafusion/proto/src/generated/pbjson.rs
datafusion/proto/src/generated/prost.rs
datafusion/proto/src/physical_plan/from_proto.rs
datafusion/proto/src/physical_plan/mod.rs
datafusion/proto/src/physical_plan/to_proto.rs

Implement protobuf serialization for `(Bounded)WindowAggExec`.

---

datafusion/physical-expr/src/datetime_expressions.rs

Follow on to https://github.com/apache/arrow-datafusion/pull/7614
I noticed this cleanup while reviewing https://github.com/apache/arrow-datafusion/pull/7614
Remove an Arc which is not necessary: https://github.com/apache/arrow-datafusion/pull/7614#discussion_r1334959880
existing tests

Minor: remove unecessary `Arc`s in datetime_expressions 

---

datafusion/core/src/datasource/file_format/parquet.rs

Follow on to https://github.com/apache/arrow-datafusion/pull/7562
I filed several TODO items as part of reviewing https://github.com/apache/arrow-datafusion/pull/7562 and I want to put references in the code to make it easier to find
Add some comments with ticket references

Minor: add ticket references to parallel parquet writing code

---

datafusion-cli/Cargo.lock

Closes #.
Run `cargo update` in `datafusion-cli` dir.
Cargo.lock changes for cli

Minor: fix CI failure due to Cargo.lock in datafusioncli

---

docs/source/library-user-guide/adding-udfs.md
docs/source/library-user-guide/catalogs.md
docs/source/library-user-guide/working-with-exprs.md
docs/source/user-guide/example-usage.md

Closes #.
Folder links does not work in the document.
e.g
https://arrow.apache.org/datafusion/user-guide/example-usage.html#example-usage
`more code examples` link in Example Usage section does not works at all.
Change all file links to GitHub in document, which would be easier to browse.

Minor: Change all file links to GitHub in document

---

datafusion/physical-expr/src/array_expressions.rs

Closes #.
Again, use ListArray instead of ArrayData.

Minor: Build array_array() with ListArray construction instead of ArrayData

---

datafusion/expr/src/expr.rs

Related to https://github.com/apache/arrow-datafusion/issues/7765.
See https://github.com/apache/arrow-datafusion/issues/7765 for details
Tweak document of `Expe::Wildcard` and `Expr::QualifiedWildcard`.

minor: add more document to Wildcard expr

---

datafusion/core/src/datasource/physical_plan/file_stream.rs
datafusion/physical-plan/src/repartition/mod.rs

Minor: fix typo in comments

---

datafusion/sqllogictest/test_files/window.slt

Closes #6691
Add test to ensure regression doesn't occur

Add simple window query to sqllogictest

---

README.md

Related to https://github.com/apache/arrow-datafusion/pull/7745
We should document crate features
Document the `parquet` crate feature added in https://github.com/apache/arrow-datafusion/pull/7745

Minor: Document `parquet` crate feature

---

datafusion-examples/Cargo.toml

Closes #.
make `cargo run --example avro_sql` success run
add `avro` feature to `datafusion` in datafusion-examples

Minor：add `avro` feature in datafusion-examples to make `avro_sql` run

---

datafusion/physical-expr/src/array_expressions.rs

Closes #.
I think we don't need to deal with ColumnarValue but ArrayRef directly, so removing this may simply be the `make_array` function here.

Minor: Remove array() in array_expression

---

datafusion/core/src/catalog/mod.rs

Improve MemoryCatalogProvider default impl block placement

Improve MemoryCatalogProvider default impl block placement

---

datafusion/core/Cargo.toml
datafusion/execution/Cargo.toml
datafusion/physical-plan/Cargo.toml

Closes #.
Apply https://github.com/apache/arrow-datafusion/pull/7964 for new READMEs in https://github.com/apache/arrow-datafusion/pull/7970

Fix crate READMEs for core, execution, physical-plan

---

Cargo.toml
datafusion-cli/Cargo.lock
datafusion/sql/src/expr/function.rs
datafusion/sql/src/expr/mod.rs
datafusion/sql/src/planner.rs
datafusion/sql/src/set_expr.rs
datafusion/sql/src/statement.rs

Closes #7980.
Update sqlparser requirement from 0.38.0 to 0.39.0

Update sqlparser requirement from 0.38.0 to 0.39.0

---

Cargo.toml
benchmarks/Cargo.toml
datafusion-cli/Cargo.toml
datafusion-examples/Cargo.toml
datafusion/common/Cargo.toml
datafusion/core/Cargo.toml
datafusion/execution/Cargo.toml
datafusion/expr/Cargo.toml
datafusion/optimizer/Cargo.toml
datafusion/physical-expr/Cargo.toml
datafusion/physical-plan/Cargo.toml
datafusion/proto/Cargo.toml
datafusion/sql/Cargo.toml
datafusion/sqllogictest/Cargo.toml
datafusion/substrait/Cargo.toml
datafusion/wasmtest/Cargo.toml
test-utils/Cargo.toml

Extract common deps into workspace

Minor: Extract common deps into workspace

---

datafusion/execution/src/memory_pool/mod.rs

Minor: remove a strange char

---

docs/source/user-guide/expressions.md

Closes #.
This is a doc fix of #7732.

Minor: Remove the irrelevant note from the Expression API doc

---

datafusion/physical-plan/src/aggregates/mod.rs

Use FairSpillPool for TaskContext with spillable config

---

datafusion/core/src/physical_optimizer/limited_distinct_aggregation.rs
datafusion/physical-plan/src/limit.rs
datafusion/sql/src/statement.rs

Minor: clean up the code regarding clippy

---

datafusion/proto/src/logical_plan/from_proto.rs

Closes #.
fix ci break after #8081 merge

Minor: fix ci break

---

Cargo.toml
datafusion-cli/Cargo.lock
datafusion-cli/Cargo.toml
dev/changelog/33.0.0.md
dev/release/generate-changelog.py

N/A
RC1 vote failed, and we are waiting on Arrow-rs 48.0.1 which will likely be released in the next couple days.

Prepare 33.0.0-rc2

---

Cargo.toml

Closes https://github.com/apache/arrow-datafusion/issues/8236
Necessary for releasing to crates.io

Add versions to datafusion dependencies

---

datafusion/physical-expr/src/array_expressions.rs
datafusion/physical-plan/src/filter.rs

Minor: clean up the code based on Clippy

---

datafusion/expr/src/interval_arithmetic.rs

Minor: remove useless clone based on Clippy

---

datafusion/physical-expr/src/datetime_expressions.rs

Minor: fix function name typo

---

datafusion/physical-expr/src/array_expressions.rs

Minor: remove useless clone in `array_expression`

---

datafusion-examples/Cargo.toml

Let's keep up with dependencies -- I am not sure why this was lagging behind. Maybe it was an oversight since we last updated

Minor: Update prost-derive dependency

---

docs/source/user-guide/introduction.md

NA
[LakeSoul](https://github.com/lakesoul-io/LakeSoul) is an open source LakeHouse framework incubated under Linux Foundation. LakeSoul implements IO in Rust for cloud storage with Arrow-rs, and uses DataFusion for columnar sorting and projection/filter pushdown.
Add LakeSoul to the list of Known Users.
NA
NA

Minor: Add LakeSoul to the list of Known Users

---

datafusion/physical-plan/src/joins/stream_join_utils.rs
datafusion/physical-plan/src/joins/symmetric_hash_join.rs

Closes #.
`StreamJoinMetrics` can be replaced under the stream_join_utils.rs. 
Code replacement for utils. Also, I added an empty `RecordBatch` guard for the edge cases in SHJ.
With existing tests.
No

[MINOR]: Some code changes and a new empty batch guard for SHJ

---

datafusion/common/src/file_options/file_type.rs
datafusion/common/src/file_options/mod.rs

Closes #.
Run: `cargo test --package datafusion-common --lib -- scalar::tests --nocapture`

Minor: Cleanup warning in scalar.rs test

---

datafusion/proto/src/logical_plan/mod.rs

Minor: clean up code

---

datafusion/proto/src/logical_plan/mod.rs

Closes #.
Remove useless conversion

minor: remove useless conversion

---

datafusion/common/src/utils.rs
datafusion/physical-expr/src/array_expressions.rs
datafusion/sqllogictest/test_files/array.slt

feat: support `LargeList` in `array_ndims`

---

datafusion/physical-expr/src/array_expressions.rs
datafusion/sqllogictest/test_files/array.slt

feat: support LargeList in array_repeat

---

datafusion/common/src/dfschema.rs

Minor: Use caster check for column name in schema merge

---

docs/source/contributor-guide/index.md

docs: add sudo for install commands
For linux, add sudo is necessary

docs: add sudo for install commands

---

datafusion/sqllogictest/test_files/array.slt

Minor: typo in `arrays.slt`

---

datafusion/core/tests/parquet/mod.rs
datafusion/execution/src/config.rs

Add options of parquet bloom filter and page index in Session config

---

docs/source/contributor-guide/index.md

docs: Update contributor guide with installation instructions 

---

datafusion/common/src/scalar.rs
datafusion/physical-expr/src/array_expressions.rs
datafusion/sqllogictest/test_files/array.slt

Support `LargeListArray` scalar values and `align_array_dimensions`

---

datafusion/core/README.md
datafusion/execution/README.md
datafusion/physical-plan/README.md

They seem to be some copy-paste errors made in #7970

docs: fix wrong name in sub-crates' README

---

datafusion/optimizer/src/optimizer.rs

better code style
use .zip to avoid an unwrap
No

Use .zip to avoid unwrap

---

.github/workflows/rust.yml

N/A
Not everyone may be familiar with what `MSRV` means and what to do to fix this CI check (e.g. https://github.com/apache/arrow-datafusion/issues/8961#) so it would be good to document it for anyone else that hits it
1. Add comments / documentation to the MSRV CI check explaining what it is and how to fix it
By CI

Minor: Add comments to MSRV CI check to help if it fails

---

datafusion-cli/src/catalog.rs
datafusion-examples/examples/external_dependency/catalog.rs
datafusion/core/src/catalog/information_schema.rs
datafusion/core/src/catalog/mod.rs
datafusion/core/src/execution/context/mod.rs
docs/source/library-user-guide/catalogs.md

Closes #.
A follow up on https://github.com/apache/arrow-datafusion/pull/8968/files#r1464114449
Rename `CatalogList` to `CatalogProviderList` as it better reflects the trait meaning which in fact is a collection of catalog providers.
Yes
Downstream users should be using a new name `CatalogProviderList` instead of `CatalogList`

Rename `CatalogList` to `CatalogProviderList`

---

datafusion/physical-expr/src/aggregate/count_distinct/mod.rs

Closes #.
This macro is meaningless, so we can remove it
remove useless macro
N/A

minor: remove useless macro

---

docs/source/user-guide/introduction.md

This is a nitpick, but hey -- we want to highlight all that DataFusion can do :D 
Thank you for DataFusion and for featuring us. @alamb beat me to adding us to the list of users!

chore: Clarify ParadeDB branding

---

docs/source/user-guide/example-usage.md

Closes #.
Adding examples how to include latest datafusion from Github without waiting the features to be released as a crate

doc: Add example how to include latest datafusion

---

datafusion/physical-plan/src/filter.rs

Fix a typo in an error message in `FilterExec::with_default_selectivity`.

Fix typo in an error message

---

datafusion/substrait/src/logical_plan/consumer.rs

Fix incorrect comment in substrait consumer

chore: Fix incorrect comment in substrait consumer

---

datafusion/expr/src/built_in_function.rs
datafusion/sqllogictest/test_files/functions.slt
datafusion/sqllogictest/test_files/scalar.slt

Closes #.
The PR slightly improves error messaging format for some of builtin functions like INSTR, SUBSTR, POSITION to increase readability for the end user.

minor: fix error message function naming

---

docs/source/library-user-guide/catalogs.md

Examples link in catalogs.rs leads to a 404 

---

datafusion/core/Cargo.toml

Closes #.
When I run some unit tests, I got the
```
use tokio::fs::File;
^^ could not find `fs` in `tokio`
```
error. However, running `cargo test` works. This PR fixes this problem.

MINOR: Add "fs" feature to "tokio", fix "features" typo.

---

datafusion/core/src/physical_optimizer/projection_pushdown.rs

Closes #9211.
It is a minor PR fixing the bug in the mentioned issue. 
`is_projection_removable()` has some condition checks based on fields of projection and its input. Field comparison is not safe. Instead, we should check the input indices of expressions to ensure projection does not change the input table.
A test is added covering the fix.

Bugfix - Projection Removal Conditions

---

datafusion-cli/Dockerfile

Closes https://github.com/apache/arrow-datafusion/issues/9209.
Previously, we got the following error:
```
❯ docker run -it -v /tmp:/data datafusion-cli
datafusion-cli: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by datafusion-cli)
datafusion-cli: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by datafusion-cli)
datafusion-cli: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by datafusion-cli)
datafusion-cli: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by datafusion-cli)
```
Update the versions in CI, It ensures that the Rust image is based on a specific release.
Yes, I tested the change in my local machine. Here is the screenshot:
No

fix: fix `GLIBC_2.35' not found error in ci

---

datafusion/core/src/execution/context/mod.rs
datafusion/execution/src/registry.rs
datafusion/execution/src/task.rs
datafusion/proto/src/bytes/mod.rs
datafusion/proto/src/bytes/registry.rs

Related to https://github.com/apache/arrow-datafusion/issues/9203

feat: Implement `FunctionRegistry::register_udwf` and `FunctionRegistry::register_udaf` for SessionContext, MemoryFunctionRegistry and TaskContext

---

datafusion/core/src/dataframe/mod.rs
datafusion/core/src/dataframe/parquet.rs

Closes #9247
Cleanup after doctest run
Doctest updates.
yes.
No.

Fix untracked files after rustdoc run

---

datafusion/sqllogictest/test_files/copy.slt

Add a reference to https://github.com/apache/arrow-datafusion/issues/9269
This was a test added by @devinjdangelo in https://github.com/apache/arrow-datafusion/pull/9240 and I wanted to cross link it

Minor: Add ticket reference to test

---

ci/scripts/rust_toml_fmt.sh

Closes #9308 
Bug fix.
script fix.
yes.
No.

Fix toml format script

---

datafusion/sql/src/expr/mod.rs
datafusion/sqllogictest/test_files/agg_func_substitute.slt

fix: issue #9213 substitute ArrayAgg to NthValue to optimize query plan

---

datafusion/physical-expr/src/scalar_function.rs

Closes #.
Refreshing struct fields debug impl for `ScalarFunctionExpr`

Minor: Adding missing fields to debug for `ScalarFunctionExpr`

---

datafusion/core/src/dataframe/mod.rs

fix:  throw error when incursion happen in dataframe api

---

datafusion/functions/src/math/mod.rs
datafusion/substrait/src/logical_plan/consumer.rs
datafusion/substrait/tests/cases/roundtrip_logical_plan.rs

Substrait: Support ScalarUDF

---

datafusion/sqllogictest/test_files/agg_func_substitute.slt

Closes https://github.com/apache/arrow-datafusion/issues/9339
Make test deterministic to prevent test failures

Make agg_func_substitute test deterministic

---

datafusion/functions/src/core/nvl2.rs
datafusion/physical-expr/src/datetime_expressions.rs

Closes https://github.com/apache/arrow-datafusion/issues/9387
delete some tail space
Also fixes a CI failure: https://github.com/apache/arrow-datafusion/actions/runs/8083720466/job/22087560300

delete tail space, fix `error: unused import: DataFusionError`

---

datafusion-cli/src/catalog.rs

Closes #9224 
issue #9224 substitute tlide in table path

feat: issue #9224 substitute tlide in table path

---

datafusion/expr/src/field_util.rs
datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs
datafusion/physical-expr/src/expressions/get_indexed_field.rs
datafusion/sqllogictest/test_files/array.slt

Closes #.
There is a bug in ConstEvaluator for large list handling, to add a test for it, I need to support LargeList for list range indexing.

Minor: Support LargeList List Range indexing and fix large list handling in ConstEvaluator 

---

datafusion/core/src/lib.rs

Closes https://github.com/apache/arrow-datafusion/issues/9432
The wrong module was re-exported.

Re-export datafusion-functions-array

---

datafusion/expr/src/field_util.rs
datafusion/physical-expr/src/expressions/get_indexed_field.rs
datafusion/sqllogictest/test_files/array.slt

Closes #9423.
A follow-up solution for https://github.com/apache/arrow-datafusion/pull/9393
```
select arrow_cast([1, 2, 3], 'LargeList(Int64)')[1];
---
1
```
Yes, I added a simple SQL logic test.
No.

Minor: Support LargeList for ListIndex

---

datafusion/functions/src/datetime/to_timestamp.rs
datafusion/sqllogictest/test_files/timestamps.slt

Closes #8452 .
A test case in `timestamps.slt`, and a test case in `datetime/to_timestamp.rs`.
Yes
No

Add test case for invalid tz in timestamp literal

---

datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs

Related to https://github.com/apache/arrow-datafusion/pull/9304 
While working on https://github.com/apache/arrow-datafusion/pull/9304 I noticed some code that was overly complicated to call a function. This was confusing and I would like to remove the rough edge
Just call function with a reference without explicitly naming the clone method

Minor: simplify call

---

datafusion/sqllogictest/test_files/group_by.slt
datafusion/sqllogictest/test_files/limit.slt

Closes #.
CI failed in #9442 #9439 
Current CI related with`sqllogicaltest` is failed

fix sqllogicaltest result

---

datafusion-examples/examples/advanced_udwf.rs
datafusion-examples/examples/simple_udwf.rs
datafusion/common/src/scalar/mod.rs
datafusion/core/src/datasource/physical_plan/parquet/page_filter.rs
datafusion/core/src/physical_optimizer/join_selection.rs
datafusion/core/tests/fuzz_cases/merge_fuzz.rs
datafusion/core/tests/memory_limit.rs
datafusion/physical-expr/src/utils/guarantee.rs
datafusion/physical-plan/src/lib.rs
datafusion/physical-plan/src/metrics/builder.rs
datafusion/physical-plan/src/test/exec.rs

Minor: docs: rm duplicate words.

---

datafusion/sqllogictest/test_files/window.slt

Closes #.
When reviewing https://github.com/apache/arrow-datafusion/pull/9445 there was a minor review miss on the LEAD test description

Minor: fix LEAD test description

---

docs/source/user-guide/sql/scalar_functions.md

Minor: change doc for range

---

datafusion/physical-plan/src/windows/bounded_window_agg_exec.rs
datafusion/sqllogictest/test_files/window.slt

Closes [#9320](https://github.com/apache/arrow-datafusion/issues/9320).

Fix undeterministic behaviour of schema nullability of lag window query

---

datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs

Follow on to https://github.com/apache/arrow-datafusion/pull/9304
@Omega359  pointed out this issue on https://github.com/apache/arrow-datafusion/pull/9304#discussion_r1513764598
Fix logic inversion bug. 
No test changes due to rationale explained on https://github.com/apache/arrow-datafusion/pull/9304#discussion_r1515004035
No

Minor: fixed transformed state in UDF Simplify

---

datafusion/core/src/datasource/listing/table.rs

Closes #.
make the code more readable.

[minor] extract collect file statistics method and add doc

---

datafusion/physical-expr/src/window/lead_lag.rs
datafusion/sqllogictest/test_files/window.slt

Add support for ignore nulls for LEAD, LAG in WindowAggExec

---

datafusion/sql/src/expr/mod.rs

re https://github.com/apache/arrow-datafusion/issues/9487
As shown by bug fixes like https://github.com/apache/arrow-datafusion/pull/9521, using `..` makes it easy for new fields to be added to the struct without being handled resulting in bigs
By explicitly matching all fields it is easier to ensure newly added fields don't get silently ignored
Remove some `..` pattern matching in the sql planner
`CAST .. FORMAT` will now error rather than silently ignoring the FORMAT

Minor: remove `..` pattern matching in sql planner

---

datafusion/sqllogictest/test_files/window.slt

Closes #.
I recognized that sometimes CI fails because of the test
```sql
query T
select lag(a) over () as x1
from
(select 2 id, 'b' a union all select 1 id, null a union all select 3 id, null);
```
. This test is not deterministic as above (even with `rowsort` argument) because sometime result would be 
```
NULL
NULL
NULL
```
or 
```
NULL
NULL
b
```
according to data order at the input of the window executor. This PR fixes this problem.

[MINOR]: Fix undeterministic test

---

datafusion/optimizer/src/common_subexpr_eliminate.rs

Closes #.
unify some plan optimization in CommonSubexprEliminate (projection/sort/filter)

refactor: unify some plan optimization in CommonSubexprEliminate

---

docs/source/user-guide/sql/scalar_functions.md

doc: Add missing doc link

---

datafusion/physical-expr/src/array_expressions.rs
docs/source/user-guide/sql/scalar_functions.md

chore: improve array expression doc and clean up array_expression.rs

---

datafusion/common/src/stats.rs
datafusion/core/src/datasource/file_format/mod.rs
datafusion/core/src/physical_optimizer/enforce_distribution.rs
datafusion/core/src/physical_optimizer/output_requirements.rs
datafusion/core/src/physical_optimizer/projection_pushdown.rs
datafusion/physical-expr/src/binary_map.rs
datafusion/physical-plan/src/aggregates/order/mod.rs
datafusion/sql/src/expr/arrow_cast.rs
datafusion/sqllogictest/test_files/create_function.slt
datafusion/sqllogictest/test_files/limit.slt
dev/changelog/13.0.0.md
dev/changelog/7.0.0.md
docs/source/contributor-guide/communication.md
docs/source/library-user-guide/adding-udfs.md

chore: remove repetitive word `the the` --> `the` in docs / comments

---

datafusion/sqllogictest/test_files/copy.slt

Add a reference to https://github.com/apache/arrow-datafusion/issues/9714 to the commented out test so future readers can find the context

Minor: add ticket reference to commented out test

---

datafusion-cli/src/exec.rs
datafusion/common/src/file_options/file_type.rs

Closes #9707 .
Please see the issue description for #9707 .
We're getting the `format` from `format_options` & passing it to `register_object_store_and_config_extensions` so that `TableOptions` are set correctly.
There are very less tests for the `datafusion-cli` crate. Testing this change would require setting up some sort of auto-cleanup like SQL Logic Tests for the COPY TO command. Let me know if we should do this now or open an issue separately for increasing the CLI test coverage.
No. This PR just fixes what's expected to be working. No new changes.

Fix COPY TO failing on passing format options through CLI

---

datafusion/common/src/error.rs
datafusion/common/src/param_value.rs
datafusion/sql/tests/sql_integration.rs

fix: change placeholder errors from Internal to Plan

---

datafusion/proto/src/logical_plan/from_proto.rs
datafusion/proto/src/logical_plan/to_proto.rs
datafusion/proto/src/physical_plan/from_proto.rs
datafusion/proto/src/physical_plan/mod.rs
datafusion/proto/src/physical_plan/to_proto.rs

Closes #.
Similar to the [PR9810](https://github.com/apache/arrow-datafusion/pull/9810). This PR eliminates repetitive codes in the codebase for cleanup.

[Minor]: Move some repetitive codes to functions(proto) 

---

datafusion/core/src/datasource/memory.rs
datafusion/core/src/physical_planner.rs
datafusion/physical-expr/src/lib.rs
datafusion/physical-expr/src/planner.rs

Closes #.
Decreases repetitive code scatterred in the code base.

[MINOR]: Move some repetitive codes to functions

---

datafusion/functions/src/datetime/common.rs

Eliminate duplicate parsing of the input and format strings in some cases
Relates to #9090.
The implementation of `to_timestamp(timestamp, format)` contains fallback logic to resort to `NaiveDateTime` if parsing into a `DateTime` fails. In such cases, the `timestamp` and `format` strings would be parsed twice. This PR uses `chrono::format::parse` directly (in the same way `DateTime::parse_from_str` and `NaiveDateTime::parse_from_str` do) to perform the parsing only once.
This results in about 25% speed improvement in the `to_timestamp_with_formats` benchmark.
Yes, existing tests.

Optimize to_timestamp (with format) (#9090)

---

docs/source/contributor-guide/index.md

Closes #.
Documenting how to use baselines with benchmarks

doc: Adding baseline  benchmark example

---

datafusion/core/src/lib.rs

Related to https://github.com/apache/arrow-datafusion/issues/6782
Now that there is a more formal description of DataFusion available (aka the SIGMOD paper) we should make it easier to find on our website / architecture documents
Add a link to the final draft of the paper to the crate's docs

Minor: Add SIGMOD paper reference to architecture guide

---

datafusion/sql/src/unparser/expr.rs

Add Expr->String for SimilarTo, IsNotTrue, IsNotUnknown,Negative

---

dev/release/README.md

Part of https://github.com/apache/arrow-datafusion/issues/9682
There are some new crates in datafusion 37.0.0 so the documentation needs to be updated
Update the documentation with the list of crates required
N/A

Minor: Update release README

---

Cargo.toml
datafusion-cli/Cargo.toml
datafusion-cli/Dockerfile
datafusion/core/Cargo.toml
datafusion/proto/Cargo.toml
datafusion/proto/gen/Cargo.toml
datafusion/substrait/Cargo.toml

Closes #.
As per https://github.com/apache/arrow-datafusion?tab=readme-ov-file#rust-version-compatibility-policy its time to bump MSRV to 1.73
Latest stable rustc is 1.77

minor: update MSRV 1.73

---

datafusion/core/src/physical_optimizer/pruning.rs

N/A
@Ted-Jiang  found a bug in the docs on https://github.com/apache/arrow-datafusion/pull/9223 https://github.com/apache/arrow-datafusion/pull/9223/files#r1554837787
Fix doc example
N/A
better docs

Minor: fix bug in pruning predicate doc

---

datafusion/sqllogictest/test_files/joins.slt

Part of #10119.
Follow up on #10120 -- there is another one test like the fixed one
rowsort added

fix: another non-deterministic test in `joins.slt`

---

datafusion/optimizer/src/eliminate_limit.rs

Stop copying plans in `EliminateLimit`

---

datafusion/optimizer/src/analyzer/type_coercion.rs
datafusion/sqllogictest/test_files/unnest.slt

chore: Update Error for Unnest Rewritter

---

docs/source/download.md
docs/source/index.rst
docs/source/user-guide/example-usage.md

docs: add download page

---

datafusion/core/tests/fuzz_cases/join_fuzz.rs

Closes #.
This PR changes 2 tests from running with 10000 data 1000. This reduces test time. I think, additional coverage from increasing data size from 1000 to 10000 is not wort to additional time overhead.

[MINOR]: Reduce test run time

---

dev/release/create-tarball.sh

N/A
This information is not relevant now that DataFusion is a TLP.
Change email subject line.
No.

minor: Remove [RUST][DataFusion] from release vote email subject line

---

datafusion/core/tests/expr_api/mod.rs
datafusion/functions/src/core/mod.rs

Closes https://github.com/apache/datafusion/issues/10566.

Improve signature of `get_field` function

---

datafusion-examples/examples/rewrite_expr.rs
datafusion/core/src/execution/context/mod.rs
datafusion/core/tests/optimizer_integration.rs
datafusion/optimizer/tests/optimizer_integration.rs
datafusion/sql/examples/sql.rs
datafusion/sql/src/expr/function.rs
datafusion/sql/src/expr/mod.rs
datafusion/sql/src/planner.rs
datafusion/sql/tests/sql_integration.rs

Renaming like `SchemaProvider::table_names`, add docs and remove deprecated code.

Improve ContextProvider

---

docs/source/user-guide/sql/scalar_functions.md

Closes #10462
Documenting to_unixtime udf function
doc update.
Yes.
Documentation only.

Add to_unixtime function to scalar functions doc

---

datafusion/common/src/file_options/csv_writer.rs
datafusion/sqllogictest/test_files/csv_files.slt

Closes #10670
`sqllogictest` has been added which fails without these changes

fix: pass `quote` parameter to CSV writer

---

datafusion/core/src/datasource/listing/helpers.rs

Closes #10722.
Remove the unnecessary double parentheses as suggested.
Yes
No

ci: fix clippy error on main

---

datafusion/functions-array/src/sort.rs
datafusion/sqllogictest/test_files/array.slt

Closes #10772.
If the row fail to match the filter condition, it has empty rows (row count is 0), so we should handle this edge case

Handle empty rows for `array_sort`

---

datafusion/execution/src/task.rs
datafusion/expr/src/expr_schema.rs
datafusion/expr/src/udf.rs

Improve docs and fix a typo

---

datafusion-cli/src/main.rs
datafusion/physical-plan/src/joins/sort_merge_join.rs

Closes #.
Remove duplicated code to create Greedy memory pool if no pool set

Minor: Remove code duplication in `memory_limit` derivation for datafusion-cli

---

datafusion/core/src/execution/session_state.rs

Debug print as many fields as possible for `SessionState`

---

dev/release/README.md

N/A
When releasing 39.0.0, I discovered that we have a new crate.
Add crate to release instructions.

minor: add proto-common crate to release instructions

---

datafusion/expr/src/utils.rs
datafusion/physical-expr/src/window/nth_value.rs
datafusion/physical-expr/src/window/window_expr.rs
datafusion/physical-plan/src/joins/hash_join.rs
datafusion/physical-plan/src/joins/stream_join_utils.rs
datafusion/physical-plan/src/joins/symmetric_hash_join.rs
datafusion/physical-plan/src/joins/test_utils.rs
datafusion/physical-plan/src/joins/utils.rs

ci: fix clippy failures on main

---

datafusion/core/src/dataframe/mod.rs
datafusion/physical-plan/src/joins/hash_join.rs
datafusion/physical-plan/src/joins/nested_loop_join.rs
datafusion/physical-plan/src/joins/sort_merge_join.rs
datafusion/physical-plan/src/joins/symmetric_hash_join.rs
datafusion/physical-plan/src/joins/utils.rs

Closes #.
Current join output partition rules are confusing, and the `partitioned_join_output_partitioning()` method is open to misuse (not all kinds of partitioned joins apply the same logic). With this PR, we will have simplified rules.
Join partition requirements and output partitions are as follows. By looking at the table, we can have two types of join partitioning rules: **symmetric** and **asymmetric**. For the cases where two possible options can be selected, I have chosen the ones that reduce duplication.
**Output Partitioning According to Join Types:**
  | Left Semi | Left Anti | Left | Inner | Full | Right | Right Semi | Right Anti
-- | -- | -- | -- | -- | -- | -- | -- | --
Cross Join | NA | NA | NA | right+offset | NA | NA | NA | NA
Sort Merge Join** | left | left | left | …

Simplify Join Partition Rules

---

datafusion/core/src/physical_optimizer/optimizer.rs

chore: Update documentation link in `PhysicalOptimizerRule` comment

---

datafusion/expr/src/expr_fn.rs
datafusion/sql/src/unparser/expr.rs

It's a follow up of #10795 and a part of #9494
yes
no

Support to unparse IntervalYearMonth and IntervalDayTime to String

---

datafusion-examples/README.md
datafusion-examples/examples/pruning.rs

Part of https://github.com/apache/datafusion/issues/10855
While working on  https://github.com/apache/datafusion/issues/10855 I noticed some minor things to improve
1. Fix example listing
2. Update some comments in the pruning example

Minor: Examples cleanup + more docs in pruning example 

---

datafusion/functions/src/datetime/to_timestamp.rs

to_timestamp functions should preserve timezone

---

datafusion-examples/Cargo.toml
datafusion-examples/README.md
datafusion-examples/examples/composed_extension_codec.rs

Closes #.
Execution plan tree might have different node from different crates, for example `ShuffleWriterExec` from `datafusion-ballista` and `DeltaScan` from `deltalake`, these crates both provide `PhysicalExtensionCodec`.
```
ShuffleWriterExec
ProjectionExec
...
DeltaScan
```
As @alamb said, we could make a composeable codec for this case.

Add composed extension codec example

---

datafusion/core/src/lib.rs

Part of #7013 
As I give various presentations like https://github.com/apache/datafusion/issues/10969 I have been describing the emergent design principles of DataFusion. But I could not find them documented anywhere
Let's document the emergent principles -- I don't intend that this changes anything about DataFusion, I am simply trying to describe the current reality
1. Add Design Principles section
2. Move `Custominzing` section  `Architecture` overview

Minor: Add Architectural Goals to the docs

---

datafusion/functions/src/math/gcd.rs
datafusion/sqllogictest/test_files/math.slt

Closes #11098.
Comes from the [binary gcd algorithm](https://en.wikipedia.org/wiki/Binary_GCD_algorithm) for signed numbers.
Yes
No

fix: gcd returns negative results

---

datafusion/common/src/scalar/mod.rs

Minor: Add more support for ScalarValue::Float16

---

datafusion/common/src/display/mod.rs

No issues are linked, just edit the comment.
The current comment on the FinalPhysicalPlan contains some typos.
Fixed the typo.
No need.
No.

fix: typo in comment about FinalPhysicalPlan

---

datafusion/core/src/datasource/physical_plan/parquet/statistics.rs
datafusion/core/tests/parquet/arrow_statistics.rs

Adds support for Dictionary data type statistics from parquet data pages.

---

datafusion-examples/examples/advanced_udaf.rs
datafusion/functions-aggregate/src/approx_distinct.rs
datafusion/functions-aggregate/src/approx_percentile_cont.rs
datafusion/functions-aggregate/src/average.rs
datafusion/functions-aggregate/src/bit_and_or_xor.rs
datafusion/functions-aggregate/src/count.rs
datafusion/physical-expr-common/src/binary_map.rs
datafusion/physical-expr-common/src/expressions/cast.rs
datafusion/physical-expr/src/expressions/case.rs

Remove unnecessary qualified names

---

datafusion/expr/src/planner.rs
datafusion/functions/src/planner.rs
datafusion/sql/src/expr/mod.rs
datafusion/sql/src/expr/substring.rs

Implement user defined planner for sql_substring_to_expr

---

docs/source/contributor-guide/testing.md

Part of #7013 
@2010YOUY01  had done some great work for SQLLancer -- see https://github.com/apache/datafusion/issues/11030. It has found all sorts of corner case bugs (also kudos to @jonahgao for fixing many of them). This is a big step forward for a maturing engine.
(also it is getting added to https://github.com/sqlancer/sqlancer/pull/954)
Document the use of sql lancer based fuzzing to help make it more discoverable
Doc CI

Minor: Add note about SQLLancer fuzz testing to docs

---

datafusion/substrait/tests/cases/consumer_integration.rs
datafusion/substrait/tests/testdata/tpch_substrait_plans/query_13.json
datafusion/substrait/tests/testdata/tpch_substrait_plans/query_14.json
datafusion/substrait/tests/testdata/tpch_substrait_plans/query_16.json

Implement TPCH substrait integration test, support tpch_13, tpch_14,16

---

datafusion/proto/proto/datafusion.proto
datafusion/proto/src/generated/pbjson.rs
datafusion/proto/src/generated/prost.rs
datafusion/proto/src/physical_plan/from_proto.rs
datafusion/proto/src/physical_plan/mod.rs
datafusion/proto/src/physical_plan/to_proto.rs
datafusion/proto/tests/cases/roundtrip_physical_plan.rs

Closes https://github.com/apache/datafusion/issues/11350.

Support serialization/deserialization for custom physical exprs in proto

---

datafusion/physical-plan/src/insert.rs
datafusion/physical-plan/src/lib.rs

Closes #.
Currently, DF does not utilize `execute_input_stream()` outside of the `DataSinkExec` implementation. However, many downstream users might benefit from such a utility when writing their own sink operators. Therefore, moving it to a broader scope could be helpful.
The `execute_input_stream()` function has been moved from the `DataSinkExec` implementation to `lib.rs` in the `physical_plan` module.

Minor: Make execute_input_stream Accessible for Any Sinking Operators

---

datafusion/physical-plan/src/aggregates/row_hash.rs
datafusion/physical-plan/src/lib.rs
datafusion/physical-plan/src/sorts/sort.rs
datafusion/physical-plan/src/spill.rs

Fixes https://github.com/apache/datafusion/issues/11496

Move spill related functions to spill.rs

---

datafusion/sql/src/expr/function.rs
datafusion/sql/src/parser.rs
datafusion/sql/src/relation/mod.rs
datafusion/sql/src/select.rs
datafusion/sql/src/unparser/ast.rs
datafusion/sql/src/unparser/plan.rs
datafusion/sql/src/unparser/utils.rs
datafusion/sql/src/utils.rs
datafusion/sql/tests/common/mod.rs
datafusion/sql/tests/sql_integration.rs
datafusion/sqllogictest/README.md
datafusion/sqllogictest/test_files/aggregate.slt
datafusion/sqllogictest/test_files/array.slt
datafusion/sqllogictest/test_files/binary.slt
datafusion/sqllogictest/test_files/copy.slt
datafusion/sqllogictest/test_files/explain.slt
datafusion/sqllogictest/test_files/interval.slt
datafusion/sqllogictest/test_files/math.slt
datafusion/sqllogictest/test_files/options.slt
datafusion/sqllogictest/test_files/scalar.slt
datafusion/sqllogictest/test_files/timestamps.slt
datafusion/sqllogictest/test_files/unnest.slt
datafusion/sqllogictest/test_files/update.slt
datafusion/sqllogictest/test_files/window.slt
datafusion/substrait/src/logical_plan/producer.rs

Closes https://github.com/apache/datafusion/issues/11521

chore: fix typos of sql, sqllogictest and substrait packages

---

datafusion-examples/examples/expr_api.rs

Closes NA
fix comment in the `simplify_demo()` example to sync with code
Not needed. Jut fixes the comments.
No

chore: Minor cleanup `simplify_demo()` example

---

datafusion/core/tests/fuzz_cases/join_fuzz.rs

Closes #.
Related to #11555 
Disable flaky SMJ antijoin filtered test until the perm solution

Minor:Disable flaky SMJ antijoin filtered test until the fix

---

datafusion/physical-expr/src/partitioning.rs

Fix typo in doc of Partitioning
Closes #11593 .

Fix typo in doc of Partitioning

---

docs/source/user-guide/sql/scalar_functions.md

Doc: A tiny typo in scalar function's doc

---

datafusion/common/src/dfschema.rs

N/A
The only difference between `qualified_field_with_unqualified_name` and `field_with_unqualified_name` is that the former returns an additional qualifier.
```sh
$ diff <(sed -n '492,520p' dfschema.rs) <(sed -n '524,552p' dfschema.rs)
4c4
<             1 => Ok((matches[0].0, (matches[0].1))),
---
>             1 => Ok(matches[0].1),
18c18
<                     Ok((fields_without_qualifier[0].0, fields_without_qualifier[0].1))
---
>                     Ok(fields_without_qualifier[0].1)
```
So `field_with_unqualified_name` can be implemented by directly invoke `qualified_field_with_unqualified_name` and simply ignore the returned qualifier.
No

refactor: simplify `DFSchema::field_with_unqualified_name`

---

datafusion/core/src/datasource/file_format/json.rs
datafusion/proto-common/proto/datafusion_common.proto
datafusion/proto-common/src/generated/pbjson.rs
datafusion/proto-common/src/generated/prost.rs
datafusion/proto/proto/datafusion.proto
datafusion/proto/src/generated/datafusion_proto_common.rs
datafusion/proto/src/generated/pbjson.rs
datafusion/proto/src/generated/prost.rs
datafusion/proto/src/lib.rs
datafusion/proto/src/logical_plan/file_formats.rs
datafusion/proto/src/logical_plan/mod.rs
datafusion/proto/tests/cases/roundtrip_logical_plan.rs

Implement physical plan serialization for json Copy plans

---

.github/workflows/rust.yml

Cleanup of the GitHub workflow definition.

Update cache key used in rust CI script

---

datafusion/core/src/datasource/file_format/parquet.rs
datafusion/proto-common/proto/datafusion_common.proto
datafusion/proto-common/src/from_proto/mod.rs
datafusion/proto-common/src/generated/pbjson.rs
datafusion/proto-common/src/generated/prost.rs
datafusion/proto-common/src/to_proto/mod.rs
datafusion/proto/src/generated/datafusion_proto_common.rs
datafusion/proto/src/logical_plan/file_formats.rs
datafusion/proto/tests/cases/roundtrip_logical_plan.rs

Implement physical plan serialization for parquet Copy plans

---

datafusion/expr/src/udaf.rs

Minor: Improve documentation for AggregateUDFImpl::state_fields

---

datafusion/sqllogictest/test_files/aggregate.slt

This was failing in an earlier version we are using currently (39) but is fixed more recently.
Adding test to make sure this doesn't break in the future.

[Minor] Add test for only nulls (empty) as input in APPROX_PERCENTILE_CONT

---

datafusion/functions-aggregate/src/approx_median.rs
datafusion/functions-aggregate/src/approx_percentile_cont.rs
datafusion/physical-expr-common/src/aggregate/tdigest.rs

Some minor refactoring
* Change count to be of type `u64`
* Some small other misc type improvements

[Minor] Refactor approx_percentile

---

datafusion/expr/src/signature.rs

I was creating a UDF and noticed that `Signature::numeric` was missing docs and also the param name confused me at first, so I aligned it to be consistent with param name of other methods on `Signature`.

Add docs and rename param for `Signature::numeric`

---

docs/source/user-guide/introduction.md

Closes #.
Keeping the docs up to date.
Adding Sail by LakeSail to the list of known users.
N/A
No.

Doc: Add Sail to known users list

---

datafusion/proto/src/physical_plan/mod.rs

Related to https://github.com/apache/datafusion/issues/11804
When comments have ticket references it is easier to find the context
Add a comment with reference to the code. Also do some manual `fmt`ing as the line was pretty long
CI

Minor: add ticket reference and fmt

---

datafusion/functions/src/math/log.rs

Closes #.
Log func tests failed to run on my server (centos 8.5).
The difference values are from doc example of [f32::log](https://doc.rust-lang.org/std/primitive.f32.html#method.log) and [f64::log](https://doc.rust-lang.org/std/primitive.f64.html#method.log).

Improve log func tests stability

---

datafusion/expr/src/test/function_stub.rs
datafusion/functions-aggregate/src/average.rs
datafusion/functions-aggregate/src/bool_and_or.rs
datafusion/functions-aggregate/src/regr.rs

Don't implement `create_sliding_accumulator` repeatedly

---

docs/source/user-guide/sql/scalar_functions.md

doc: Add support for `map` and `make_map` functions

---

datafusion/core/Cargo.toml

Improve readme page in crates.io

---

datafusion/physical-plan/src/joins/nested_loop_join.rs

Closes #.
We could use `?` to make code cleaner.

Improve nested loop join code

---

docs/source/contributor-guide/inviting.md

N/A
Per https://apache.org/foundation/glossary.html#PMC
Make it clear this the person will not become *the* PMC, rather they will join the PMC
Adjust email template wording
N/A

Minor: change wording for PMC membership notice

---

datafusion/functions/src/core/mod.rs
datafusion/functions/src/crypto/mod.rs
datafusion/functions/src/datetime/mod.rs
datafusion/functions/src/encoding/mod.rs
datafusion/functions/src/math/mod.rs
datafusion/functions/src/regex/mod.rs
datafusion/functions/src/string/mod.rs
datafusion/functions/src/unicode/mod.rs

Follow on to https://github.com/apache/datafusion/pull/11959
I think the context for https://github.com/apache/datafusion/pull/11959 may not be obvious, so we should add a comment explaining that: https://github.com/apache/datafusion/pull/11959#event-13875462487
1. Add a comment with the rationale of including `get_field`
2. Some drive by doc cleanuos
Only doc changes, no functional changes

Minor: Improve function documentation

---

datafusion/catalog/src/catalog.rs

no
replace [`TableProvider]` with [`TableProvider`] in `catalog.rs`
no, just document changes.
no

[MINOR] correct document mistakes

---

datafusion/functions/Cargo.toml
datafusion/functions/benches/random.rs
datafusion/functions/src/math/random.rs

NA
(The change has 2 lines)
Before `random()` scalar function's implementation use `rand` crate to generate random values one by one
And `rand` crate suggests using another method for efficiency, if it's intended to generate an array of random values.
https://docs.rs/rand/latest/rand/trait.Rng.html#arrays-and-tuples
I tried and get 20% speedup in micro bench (evaluate 1M rows with 8k batch size)
```
Finished `bench` profile [optimized] target(s) in 1m 41s
Running benches/random.rs (/Users/yongting/Desktop/code/my_datafusion/arrow-datafusion/target/release/deps/random-b9fac37452f14654)
random_1M_rows_batch_8192
time:   [3.4447 ms 3.4721 ms 3.5062 ms]
change: [-25.835% -24.272% -22.846%] (p = 0.00 < 0.05)
Found 6 outliers among 100 measurements (6.00%)
2 (2.00%) …
```

Faster random() scalar function

---

datafusion/functions/src/unicode/strpos.rs
datafusion/functions/src/utils.rs

Closes #12071.
A test for `strpos` (I couldn't find any existing tests) which covers the currently working and currently broken cases, and a fix for mixed type case (by casting arg 0 and arg 1 to their own types rather than both to the type of arg 0).
(There's also a minor change to a testing helper macro to give more info when an error occurs).
New unit test
One less error :-)

functions: support strpos with mixed string types

---

datafusion/functions-window/src/row_number.rs

Closes #.
We need the access of RowNumber struct from `core` crate.

Minor: make RowNumber public

---

datafusion/core/src/physical_optimizer/combine_partial_final_agg.rs

Closes #.
Use `let else` syntax to improve `CombinePartialFinalAggregate` code readability.

Improve `CombinePartialFinalAggregate` code readability

---

datafusion/physical-plan/src/aggregates/row_hash.rs

NA
`GroupedHashAggregateStream` now has tens of fields due to the complexity of aggregation logic
This PR intends to categorize those fields into different groups and add comments for each group, to improve readability
reordering struct fields and adding comments

minor: Add comments for `GroupedHashAggregateStream` struct

---

datafusion/sqllogictest/test_files/map.slt

The syntax issue has been fixed in https://github.com/sqlparser-rs/sqlparser-rs/pull/1361, and we have also upgraded sqlparser-rs.

Enable the test for creating empty map

---

Cargo.toml

relates to slack thread https://the-asf.slack.com/archives/C04RJ0C85UZ/p1724705568390599?thread_ts=1724441957.775059&cid=C04RJ0C85UZ

Make it easier to understand datafusion-cli exclusion

---

docs/source/user-guide/sql/scalar_functions.md

Closes #.
Fix corresponding `array_distinct` alias link title.
`array_dims` -> `array_distinct`
No, just docs.

Minor: fix `list_distinct` alias link title

---

Cargo.toml
datafusion-examples/Cargo.toml
datafusion/proto-common/Cargo.toml
datafusion/proto/Cargo.toml
datafusion/substrait/Cargo.toml

Update prost dependency and use same version consistently.

Update prost dependency

---

datafusion/physical-plan/src/execution_plan.rs

N/A
While working with @ozankabak  and @berkaysynnada on https://github.com/apache/datafusion/pull/12174.  I found myself referring several times to the `ExecutionMode` documentation and had to re-read it a few times 
Try to improve the docs

Minor: Improve ExecutionMode documentation

---

datafusion/sqllogictest/test_files/sort_merge_join.slt

Closes #11659.
Failure is not reproducing neither locally nor in CI -- seems like the test can be uncommented.
The ignored test enabled again.

test: re-enable merge join test with forced collisions

---

datafusion/common/src/scalar/mod.rs

Closes #.
Binary scalars might be large, which makes plan printing so long.
Display binary scalars as hex string.

Improve binary scalars display

---

datafusion/functions-aggregate-common/src/stats.rs

N/A
DataFusion Comet currently has a copy of this enum with `PartialEq` and `Eq` added. I would like use the DataFusion version instead.

minor: Add PartialEq, Eq traits to StatsType

---

datafusion/core/src/physical_optimizer/sanity_checker.rs

Closes #.
There are minor changes on the variable names and error messages to improve understandability.

Minor: Update Sanity Checker Error Messages

---

datafusion/core/src/execution/session_state.rs

Closes #.
Reuse SessionStateBuilder builder methods for default builder to unify API calls

minor: reuse SessionStateBuilder methods for default builder

---

datafusion/physical-plan/src/aggregates/mod.rs
datafusion/physical-plan/src/aggregates/row_hash.rs
datafusion/physical-plan/src/spill.rs

Reuse `spill_record_batch_by_size` function

---

datafusion/core/tests/fuzz_cases/join_fuzz.rs

Adding more debug output. Fixing bugs when saving debug data. Fixing debug examples
Closes #.

minor: improve join fuzz tests debug kit

---

datafusion/physical-plan/src/joins/nested_loop_join.rs

fix: nested loop join requires outer table to be a FusedStream

---

datafusion/sql/src/expr/function.rs
datafusion/sql/tests/sql_integration.rs

fix: DataFusion panics with "No candidates provided"

---

datafusion/expr/src/udf.rs

Deprecate unused ScalarUDF::fun

---

datafusion/expr/src/udwf.rs

Deprecated since v 34. Remove it along with associated `WindowUDFLegacyWrapper`.

Remove deprecated WindowUDF::new

---

datafusion/physical-plan/src/aggregates/row_hash.rs

Closes #.
Found some imports are not on top of the file.
See title.

Minor: move imports to top in `row_hash.rs`

---

datafusion/core/src/execution/session_state.rs

feat: Support adding a single new table factory to SessionStateBuilder

---

datafusion/core/src/datasource/file_format/options.rs

Minor: add new() function for ParquetReadOptions

---

docs/source/user-guide/introduction.md

Add the Blaze project to known users.
Closes #.

Update introduction.md for `blaze` project

---

datafusion/expr/src/utils.rs
datafusion/sql/src/utils.rs
datafusion/sqllogictest/test_files/unnest.slt

Closes #12684 
Fix the wildcard expansion for the unnest case.
yes
no

Fix unnest conjunction with selecting wildcard expression

---

datafusion/functions-aggregate/src/variance.rs
docs/source/user-guide/sql/aggregate_functions.md
docs/source/user-guide/sql/aggregate_functions_new.md

~Draft as it builds on https://github.com/apache/datafusion/pull/12747~
Part of https://github.com/apache/datafusion/issues/12740
Automatically generating documentation has several benefits as listed on https://github.com/apache/datafusion/issues/12740
1. Port documentation

Port / Add Documentation for `VarianceSample` and `VariancePopulation`

---

datafusion/catalog/README.md

Closes #12796.
I noticed that the catalog submodule doesn't have a README which is inconsistent with the other notable submodules.
Added a README 
Yes
No

Minor: add README to Catalog Folder

---

datafusion/functions/benches/encoding.rs
datafusion/functions/src/string/btrim.rs
datafusion/functions/src/string/ltrim.rs
datafusion/functions/src/string/rtrim.rs

Fixes for a bunch of conflicts introduced in #12812. cc @alamb @jayzhan211 .

[logical-types] fix conflicts

---

datafusion/common/src/scalar/mod.rs

Closes #12855.
Fix the bug
A broken test
(TODO) bug fix 
Yes

Fix Bug in Display for ScalarValue::Struct

---

datafusion/expr/src/built_in_window_function.rs
datafusion/expr/src/conditional_expressions.rs
datafusion/expr/src/expr.rs
datafusion/expr/src/expr_schema.rs
datafusion/expr/src/function.rs
datafusion/expr/src/simplify.rs
datafusion/expr/src/tree_node.rs
datafusion/expr/src/udaf.rs
datafusion/expr/src/udf_docs.rs
datafusion/expr/src/utils.rs
datafusion/expr/src/window_state.rs

Closes #.
Was learning codebase again, and fixed + added some docs on the way.

Minor: added to docs in expr folder

---

datafusion/expr-common/src/accumulator.rs
datafusion/expr-common/src/columnar_value.rs
datafusion/expr-common/src/groups_accumulator.rs
datafusion/expr-common/src/interval_arithmetic.rs
datafusion/expr-common/src/signature.rs
datafusion/expr-common/src/type_coercion/aggregates.rs
datafusion/expr-common/src/type_coercion/binary.rs

Closes #.
Went through the codebase to learn again, fixed up some comments

Minor: expr-doc small fixes

---

datafusion/functions/src/regex/regexpmatch.rs
docs/source/user-guide/sql/scalar_functions_new.md

Closes #.
Fix spelling mentioned in #13008

Minor: Fix spelling in regexpr_count docs

---

datafusion/common/src/lib.rs
datafusion/common/src/types/builtin.rs
datafusion/common/src/types/logical.rs
datafusion/common/src/types/mod.rs
datafusion/common/src/types/native.rs
datafusion/wasmtest/Cargo.toml
datafusion/wasmtest/src/lib.rs

While #12853 is still in review I was wandering if I could make some additional progress on the logical-types branch.

[logical-types branch] Backport native and logical types

---

datafusion/functions-nested/src/range.rs
docs/source/user-guide/sql/scalar_functions_new.md

Closes #13093 .
Added new instance of the documentation, due to a clash with the 'range' function

docs: Fixed generate_series docs

---

README.md
docs/source/index.rst

Followup on #13083 
Closes #.
Add deprecated policy to the contributor guide contents and fix the policy link from main README

minor: Add deprecated policy to the contributor guide contents

---

benchmarks/README.md

Closes #.
Recently @doupache and @austin362667 added a great IMDB benchmark, this PR wants to include it in `benchmarks/README.md`

Minor: doc IMDB in benchmark README

---

datafusion/core/src/bin/print_functions_docs.rs
datafusion/expr/src/udf_docs.rs
datafusion/functions/src/unicode/strpos.rs
docs/source/user-guide/sql/scalar_functions_new.md

Closes #13139 .
Added alternative syntax argument for doc functions

[docs]: added `alternative_syntax` function for docs

---

docs/source/user-guide/sql/window_functions.md

Closes #.
Deleted cume_dist and percent_rank docs.

Minor: Delete old cume_dist and percent_rank docs

---

docs/source/contributor-guide/howtos.md

Closes #.
New docs, need to mention somewhere on how to update the docs for future implementations of UDFs

minor: Update HOWTO to help with updating new docs

---

datafusion/core/tests/fuzz_cases/aggregation_fuzzer/data_generator.rs

Closes #.
Was working on the fuzz testing and noticed some of the comments were incorrect.
Small changes to fix up the file

minor: doc fixes in fuzz testing

---

docs/source/library-user-guide/profiling.md

Closes #.
Was running some flamegraphs however some things such as running it in the data directory which corresponded to the sql query weren't clear.
Cleaned up + made the documentation a bit more specific

feat: Updating flamegraph docs

---

datafusion/common/src/table_reference.rs
datafusion/core/src/execution/session_state.rs

Closes #13300.
See #13300.
See #13300.
The only user-facing changes are derives for `ResolvedTableReference`. I think it is ok to not assert generated code.
Also, I changed internal code to utilize new derives, so it should be covered by existing tests if ever. 
Yes. Rustdoc will cover implemented derives.

Derive Eq, Hash, Ord for ResolvedTableReference to be capable of map key

---

datafusion-cli/Cargo.lock
datafusion/common/Cargo.toml
datafusion/common/src/instant.rs

\-
See https://rustsec.org/advisories/RUSTSEC-2024-0384.html .
Just replaces a dependency.
Existing tests/CI.
\-

refactor: replace `instant` with `web-time`

---

datafusion/physical-plan/src/joins/sort_merge_join.rs

Closes #.
Rename structures to more meaningful names, adding more comments, remove unnecessary clones

Minor: SortMergeJoin small refactoring

---

docs/source/user-guide/concepts-readings-events.md

🤦  -- fix bug I introduced in https://github.com/apache/datafusion/pull/13335 that @djanderson  caught

Fix typo in concepts-readings-events.md

---

datafusion/sqllogictest/test_files/insert_to_external.slt

Fixes https://github.com/apache/datafusion/issues/13396

Fix test query results even for quick test execution

---

datafusion/functions-aggregate/src/min_max.rs
datafusion/sqllogictest/test_files/group_by.slt

Closes [#13415 ](https://github.com/apache/datafusion/issues/13415)

[MINOR]: fix min max accumulator nan bug

---

datafusion/functions-aggregate/src/count.rs
datafusion/functions-aggregate/src/variance.rs
datafusion/physical-plan/src/aggregates/row_hash.rs

Closes #.
Aggregate Filter could be applied in partial stage, at the point we reach final stage we don't need to handle filter. Therefore, to simplify the code logic, I remove related unreachable code

Remove unreachable filter logic in final grouping stage

---

datafusion/functions/src/crypto/md5.rs
datafusion/sqllogictest/test_files/string/string_query.slt.part

- Closes #13444
- Closes https://github.com/apache/datafusion/pull/13443
Bug fix for md5 not working as expected with largeutf8 input
Code, tests.
Yes
No

Fixed issue with md5 not support LargeUtf8 correctly

---

datafusion/core/src/dataframe/mod.rs
datafusion/core/src/dataframe/parquet.rs
datafusion/core/src/datasource/file_format/avro.rs
datafusion/core/src/datasource/file_format/parquet.rs
datafusion/core/src/datasource/file_format/write/demux.rs
datafusion/core/src/datasource/physical_plan/file_scan_config.rs
datafusion/core/src/datasource/physical_plan/statistics.rs
datafusion/sql/src/select.rs
docs/source/library-user-guide/catalogs.md

Closes #.
Remove some panics and wrap error calls into backtraceable API

Minor: clean up error entries

---

datafusion/expr/src/expr.rs
datafusion/sql/src/unparser/dialect.rs

Added in 1c7209b280ba0d8a7faa6a4a63ff5bc52a6fd9bc and 55b792a608be881439fd20dafdd803478346186a respectively.

chore: add version to deprecation messages

---

datafusion/optimizer/src/optimize_projections/required_indices.rs

There is a mistake in the doc，missed a number
Minor fix, no issue #
only doc update
no

[minor] Update Doc of required_indices.rs

---

datafusion/optimizer/src/analyzer/type_coercion.rs
datafusion/sqllogictest/test_files/window.slt

Closes #13566 .
Allowed for boolean data type on column
Yes, slt tests for all window functions. All tested behaviour matches with duckdb

feat: Add `Boolean` Column Support for Window Functions

---

datafusion/expr/src/udf.rs

ScalarUDFImpl has to be Sync and Send.

Remove redundant type constraints from ScalarUDF from

---

datafusion/substrait/src/logical_plan/consumer.rs
datafusion/substrait/src/logical_plan/producer.rs
datafusion/substrait/tests/cases/roundtrip_logical_plan.rs

Closes #13419 .
See issue.
See added tests.

feat(substrait): support-try-cast

---

datafusion/physical-expr/src/equivalence/class.rs

Closes #13639.
There is a logical conflict between #13611 and main.
`indexmap::IndexSet` was replaced to `common::IndexSet` in #13611, but there's still code using it on the main.
Yes
No

fix: CI build failed on main

---

docs/source/contributor-guide/inviting.md

Increase the time for voting in the template to 1 week, per https://community.apache.org/pmc/adding-committers.html#vote
Closes #.
https://community.apache.org/pmc/adding-committers.html#vote suggests 7 days for votes
Increase the time for voting in the template to 1 week, per https://community.apache.org/pmc/adding-committers.html#vote
Just documentation

Update governance page for 7 days of voting

---

datafusion/physical-plan/src/joins/cross_join.rs
datafusion/physical-plan/src/joins/nested_loop_join.rs

Closes #.
Some small changes to improve readability in cross join and nested loop join

[minor]: Simplifications

---

datafusion/physical-plan/src/joins/hash_join.rs

Based on the [comment](https://github.com/apache/datafusion/pull/13751/files#r1885543455), I decide to revert this reservation back
Closes #.

Revert the removal of reservation in HashJoin

---

datafusion/functions-nested/src/distance.rs
datafusion/functions-nested/src/length.rs
datafusion/functions-nested/src/string.rs
datafusion/functions-nested/src/utils.rs
datafusion/functions/src/macros.rs
datafusion/functions/src/math/abs.rs
datafusion/functions/src/math/factorial.rs
datafusion/functions/src/math/gcd.rs
datafusion/functions/src/math/lcm.rs
datafusion/functions/src/math/power.rs

Closes #.
Small refactoring for `downcast_arg` macro.

Minor: Unify `downcast_arg` method

---

datafusion/functions/src/math/nanvl.rs
datafusion/functions/src/math/pi.rs
datafusion/functions/src/math/power.rs
datafusion/functions/src/math/random.rs
datafusion/functions/src/math/round.rs
datafusion/functions/src/math/signum.rs
datafusion/functions/src/math/trunc.rs

As discussed in #13671  , this PR will migrate the parts of builtin math functions documentation that currently support migration.

doc-gen: migrate scalar functions (math) documentation 2/2

---

datafusion/core/tests/fuzz_cases/pruning.rs

- Closes https://github.com/apache/datafusion/issues/13946
1. After https://github.com/apache/datafusion/pull/12978 from @adriangb  (❤️ ) the test_fuzz_utf8 test takes over a minute to run on my machine
2. It is also not especially clear what it is doing or what is taking the time
1. Break the test into multiple individual test cases that each test a particular predicate
2. The logic is still the same (no changes are intended)
New output: longest test now takes 12 seconds
Example:
```
andrewlamb@Mac:~/Software/datafusion$ cargo nextest run --test fuzz -- pruning
Compiling datafusion v44.0.0 (/Users/andrewlamb/Software/datafusion/datafusion/core)
Finished `test` profile [unoptimized + debuginfo] target(s) in 2.08s
------------
Nextest run ID d214dd1d-952c-4280-a2b6-14f2d0109b79 with …
```

Parallelize pruning utf8 fuzz test

---

docs/source/user-guide/sql/write_options.md

Closes #.
Fix outdated doc example
Update doc example to use new `OPTIONS` API for setting delimiter

Update doc example to remove deprecated DELIMITER option for external tables

---

datafusion/expr/src/logical_plan/plan.rs

Closes #.
I didn't understand the calculation method the first time, I tried to rewrite it more clearly

Minor: Rewrite LogicalPlan::max_rows for Join and Union, made it easier to understand

---

docs/source/contributor-guide/getting_started.md

Closes #13969 
Add a small bit of docs and links to IDE docs for the newly added dev container support.
getting started doc update.
doc update.

Added references to IDE documentation for dev containers

---

Cargo.toml
datafusion-cli/Cargo.toml

Closes #.
I have faced with
```
Checking datafusion-expr v44.0.0 (/Users/berkaysahin/Desktop/datafusion/datafusion/expr)
error: unexpected `cfg` condition value: `used_linker`
--> datafusion/expr/src/lib.rs:101:1
|
101 | #[ctor::ctor]
| ^^^^^^^^^^^^^
|
= note: expected values for `feature` are: `recursive_protection`
= help: consider adding `used_linker` as a feature in `Cargo.toml`
= note: see <https://doc.rust-lang.org/nightly/rustc/check-cfg/cargo-specifics.html> for more information about checking conditional configuration
= note: `-D unexpected-cfgs` implied by `-D warnings`
= help: to override `-D warnings` add `#[allow(unexpected_cfgs)]`
= note: this error originates in the attribute macro `ctor::ctor` (in Nightly builds, run with -Z macro-backtrace for more info);
```
and the …

Update ctor dep to latest

---

datafusion/physical-plan/src/aggregates/mod.rs
datafusion/physical-plan/src/aggregates/row_hash.rs

Closes #.
Whenever we have `PhysicalGroupBy`, we can call this function instead of the util like one.

Minor: Make `group_schema` as `PhysicalGroupBy` method

---

datafusion/physical-plan/src/joins/hash_join.rs
datafusion/physical-plan/src/joins/mod.rs
datafusion/physical-plan/src/joins/nested_loop_join.rs

Minor: fix duplicated SharedBitmapBuilder definitions

---

datafusion/common/src/config.rs

Closes #.
Current `default_from_session_config` take no effect, this pr fix it. It also added a `#[must_use]` hopefully it will be less likely to misuse.

Fix combine with session config

---

datafusion/core/src/datasource/view.rs

- Closes https://github.com/apache/datafusion/issues/14132
yes
No

bugfix: create view with multi union may get wrong schema

---

datafusion/core/src/datasource/view.rs
datafusion/sqllogictest/test_files/ddl.slt

Add tests for PR #14133 (view with multi unions) 

---

datafusion/core/src/datasource/physical_plan/parquet/row_group_filter.rs

Closes #.
I ran into this code while doing something else.  There is duplication in the set of types supported by Bloom filtering checks that must be kept in sync. It would be better to have a single list
Simplify the bloom filter check
By existing CI

Minor: Simplify Bloom Filter Check

---

datafusion/common/src/scalar/mod.rs

Fix doctests in ScalarValue (#14164)

---

docs/source/contributor-guide/howtos.md

Closes #13368 .
Added `How to add/edit documentation for UDFs` section to howto doc.
This PR only updates documentation. Thus no tests are included.
Yes.

Chore: Add  UDF documentation guide

---

datafusion/functions/src/string/concat_ws.rs
datafusion/sqllogictest/test_files/case.slt
datafusion/sqllogictest/test_files/expr.slt

fix concat ws simplify

---

docs/source/user-guide/introduction.md

* doc: Add funnel.io to known users list
* update: docs/source/user-guide/introduction.md

doc: Add funnel.io to known users list

---

datafusion/expr/src/expr.rs

- Closes #14310.
Adding the relation (`TableReference`) from the alias expression to the output of schema display. This allows validation logic to take the relation into account and not falsely fail.
Yes
No

Add relation to alias expr in schema display

---

datafusion/physical-plan/src/unnest.rs

As mentioned in #14115 , several examples in DataFusion codebase still using BooleanBufferBuilder rather than NullBufferBuilder, they should be replaced with NullBufferBuilder for optimization.

refactor: switch `BooleanBufferBuilder` to `NullBufferBuilder` in unit tests for unnest

---

datafusion-cli/Dockerfile

- Follow on to https://github.com/apache/datafusion/pull/14330
Let's keep the Dockerfile up to date with the MSRV
Per @comphead  update the MSRV in dockergile: https://github.com/apache/datafusion/pull/14330#pullrequestreview-2576710800
I tested it manually via `docker build . -f datafusion-cli/Dockerfile`

Update version in `datafusion-cli/Dockerfile` to 1.81

---

README.md

Adding neat thing that likely shows off the project activity and might help with commit report activity
Closes #.

chore: Adding commit activity badge

---

datafusion/core/src/dataframe/mod.rs

- Related to  #14387
Clarify behavior in documentation
Documentation update
N/A
N/A

docs: Clarify join behavior in `DataFrame::join`

---

docs/source/library-user-guide/adding-udfs.md

Closes #14404.
Provide examples using the most up-to-date API.
- Updated the code examples in `library-user-guide/adding-udfs.md`.
N/A.
No.

docs: Fix create_udf examples

---

Cargo.toml
datafusion-cli/Cargo.lock
datafusion-cli/Cargo.toml
datafusion/core/src/datasource/physical_plan/arrow_file.rs
datafusion/optimizer/src/unwrap_cast_in_comparison.rs
datafusion/physical-expr/src/window/standard.rs

bump arrow version to 54.1.0 and fix clippy error

---

datafusion/sqllogictest/bin/postgres_container.rs

None
Noticed two Clippy warnings with suggestions to fix.
Suggestion by Clippy.
CI.
No.

Fix a clippy warning

---

datafusion/core/tests/dataframe/mod.rs
datafusion/optimizer/src/analyzer/type_coercion.rs

- Backport https://github.com/apache/datafusion/pull/14387 to the 45 release branch

[release-45] Fix join type coercion (#14387)

---

datafusion/expr-common/src/type_coercion/binary.rs
datafusion/sqllogictest/test_files/string/dictionary_utf8.slt
datafusion/sqllogictest/test_files/string/init_data.slt.part
datafusion/sqllogictest/test_files/string/large_string.slt
datafusion/sqllogictest/test_files/string/string.slt
datafusion/sqllogictest/test_files/string/string_query.slt.part
datafusion/sqllogictest/test_files/string/string_view.slt

- Backport https://github.com/apache/datafusion/pull/14377 to the 45 release branch

[branch-45] Support `Utf8View` to `numeric` coercion (#14377)

---

datafusion/functions/benches/regx.rs
datafusion/functions/src/regex/regexpmatch.rs
datafusion/sqllogictest/test_files/regexp.slt
datafusion/sqllogictest/test_files/string/string_view.slt

- Backport https://github.com/apache/datafusion/pull/14449 to the 45 release branch

[branch-45] Update REGEXP_MATCH scalar function to support Utf8View (#14449)

---

dev/changelog/45.0.0.md

FInal update of changelog prior to making an RC to include backported content
FInal update of changelog prior to making an RC

[branch-45] Update changelog for backports to 45.0.0

---

datafusion/expr/src/logical_plan/builder.rs

- Follow on to https://github.com/apache/datafusion/pull/14473
I accidentally merged a PR that didn't pass CI tests  🤦  
Fix ci by running `cargo fmt` and checking in the result
Yes

Minor: `cargo fmt` to fix CI

---

Cargo.toml
datafusion-cli/Cargo.lock
datafusion-cli/Cargo.toml

chore: clean up dependencies for datafusion cli

---

datafusion/sql/src/unparser/expr.rs

Unparser dialects specify timestamp data type overrides via `timestamp_cast_dtype` which is NOT currently used when converting timestamp literals resulting in `syntax error near TIMESTAMP` error for MySQL
```sql
SELECT CAST('2025-01-31 01:05:49.123' AS TIMESTAMP)
SQL Error [1064] [42000]: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'TIMESTAMP))
```
PR updates `handle_timestamp` used by `scalar_to_sql` to respect dialect timestamp type overrides.
Yes, manually and added unit test.
Unparser will generated valid sql for timestamp literals conversion for dialects specifying custom data type for timestamp conversion (`timestamp_cast_dtype`)

Improve Unparser (scalar_to_sql) to respect dialect timestamp type overrides

---

datafusion-cli/Cargo.lock
datafusion/core/Cargo.toml

like this https://github.com/apache/datafusion/actions/runs/13151403418/job/36699387339?pr=14493
Closes #.

fix(ci): build error with wasm

---

datafusion/functions/src/datetime/to_unixtime.rs
datafusion/sqllogictest/test_files/timestamps.slt

Closes #14488
Fix functionality gap.
Code, slt test.
Yes
No

to_unixtime does not support timestamps with a timezone

---

datafusion/core/tests/physical_optimizer/replace_with_order_preserving_variants.rs

Remove useless test util

---

datafusion/core/Cargo.toml
datafusion/core/benches/dataframe.rs

... or lack thereof
- Part of #14563
Benchmark showcasing the issue.
Benchmark only
Yes
No

Benchmark showcasing with_column and with_column_renamed function performance 

---

datafusion/optimizer/src/analyzer/count_wildcard_rule.rs

Fix typo in comments

---

datafusion/physical-expr/src/equivalence/class.rs
datafusion/sqllogictest/test_files/join.slt.part

- Closes https://github.com/apache/datafusion/pull/14327/files

Fix ci test

---

datafusion/functions/src/math/abs.rs
datafusion/functions/src/math/cot.rs
datafusion/functions/src/math/factorial.rs
datafusion/functions/src/math/gcd.rs
datafusion/functions/src/math/iszero.rs
datafusion/functions/src/math/lcm.rs
datafusion/functions/src/math/log.rs
datafusion/functions/src/math/nans.rs
datafusion/functions/src/math/nanvl.rs
datafusion/functions/src/math/pi.rs
datafusion/functions/src/math/power.rs
datafusion/functions/src/math/random.rs
datafusion/functions/src/math/round.rs
datafusion/functions/src/math/signum.rs
datafusion/functions/src/math/trunc.rs

- Part of https://github.com/apache/datafusion/issues/13515
- Part of https://github.com/apache/datafusion/issues/14652.

Migrate math functions to implement invoke_with_args

---

README.md

- Related to #14389 
- Closes #.

chore: adding Linkedin follow page

---

datafusion/functions/src/macros.rs

- Part of #14652 
Most of the math functions have been migrated by #14658 but the functions defined through macro are missed.

MIgrate math function macro to implement invoke_with_args

---

datafusion/core/tests/parquet/row_group_pruning.rs

Closes #13821.
The issue with reading / writing decimal dictionaries has been fixed in `parquet` crate, and now when it's updated and contains the fix, the test which relies on this logic can be enabled.
Enabling previously ignored test
Yes
No

minor: enable decimal dictionary sbbf pruning test

---

datafusion/functions/src/core/arrow_cast.rs
datafusion/functions/src/core/arrowtypeof.rs
datafusion/functions/src/core/coalesce.rs
datafusion/functions/src/core/getfield.rs
datafusion/functions/src/core/greatest.rs
datafusion/functions/src/core/least.rs
datafusion/functions/src/core/nullif.rs
datafusion/functions/src/core/nvl.rs
datafusion/functions/src/core/nvl2.rs
datafusion/functions/src/core/version.rs

- Closes #14703.
Remove usages of the deprecated invoke_batch and invoke.
Yes.
No

chore: Migrate Core Functions to invoke_with_args

---

datafusion/functions/src/core/getfield.rs

- Follow on to https://github.com/apache/datafusion/pull/14712
It appears https://github.com/apache/datafusion/pull/14712 had a logical conflict somehow and thus no longer builds
Fix compilation error
By CI and I tested them locally

Fix build after logical conflict

---

docs/source/contributor-guide/gsoc_application_guidelines.md
docs/source/contributor-guide/gsoc_project_ideas.md

Updating expired Discord links with a new, valid link.

Update website links

---

docs/source/user-guide/introduction.md

Add polygon.io to user list

---

docs/source/user-guide/introduction.md

- Closes #.
`datafusion-tui` was renamed `datafuion-dft` and I actively maintain the project now.

Update dft in intro "Known Users"

---

datafusion/core/src/datasource/physical_plan/parquet/mod.rs

- Closes #.
The method is useful for user to build their own `ParquetExec`.
Expose `build_row_filter` method

Expose `build_row_filter` method

---

.github/workflows/dev_pr/labeler.yml

- Closes #.
The number of subcrates has expanded, so should our automation for labeling PRs
Update labeler with some newly added components
No, this is entirely development process

Update labeler components

---

datafusion/core/src/datasource/listing/table.rs
datafusion/core/src/datasource/mod.rs

- Closes #.
Converting logical sort expressions to physical sort expressions is a useful mothod, make it pub and add doc for it.
Yes

Make `create_ordering` pub and add doc for it

---

datafusion/core/tests/fuzz_cases/aggregation_fuzzer/data_generator.rs
datafusion/core/tests/fuzz_cases/aggregation_fuzzer/mod.rs

- Closes #.
I'm thinking about enhancing the sort fuzzer, so I checked our nice aggregate fuzzer to find reusable parts. While doing so, I also took the opportunity to add more comments to it.
More comment to the aggregation fuzzer.
NA
NO

Minor: More comment to aggregation fuzzer

---

Cargo.lock

- Closes https://github.com/apache/datafusion/issues/15062
there is a vulnerability in old versions of ring that is triggering a CI failure

Update ring to v0.17.13

---

.github/workflows/rust.yml
datafusion/sqllogictest/Cargo.toml

- Closes #15058
Make the sqllogictest consistent for the testing result 
Make the sqllogictest consistent for the testing result 
Yes
No

Minor: fix CI to make the sqllogic testing result consistent

---

datafusion/optimizer/src/decorrelate.rs

- Closes #10553.
Improve documentation for `need_handle_count_bug`

Minor: Improve documentation of `need_handle_count_bug`

---

dev/changelog/46.0.0.md
dev/release/README.md

- Closes https://github.com/apache/datafusion/issues/14123
We made some small changes to the release notes on the `release-46` branch and added 2 new crates which should be reflected in the release instructions
1. Cherry pick release note changes to main
- https://github.com/apache/datafusion/pull/14977
- https://github.com/apache/datafusion/pull/14979
3. Add 2 new crates to release instructions

Minor: final `46.0.0` release tweaks: changelog + instructions

---

datafusion/proto-common/gen/src/main.rs
datafusion/proto/gen/src/main.rs

Minor: Cleanup useless/duplicated code in gen tools

---

.github/workflows/extended.yml

fix extend sqllogical consistent with main test
Similar to:
- https://github.com/apache/datafusion/issues/15058
We need to fix the extend consistence also.
Yes
No

Minor: fix extend sqllogical consistent with main test

---

.github/workflows/rust.yml
Cargo.lock
datafusion/core/Cargo.toml
datafusion/core/tests/core_integration.rs
datafusion/core/tests/serde/mod.rs

- Part of https://github.com/apache/datafusion/issues/15151
- Related to https://github.com/apache/datafusion/issues/15122
We are making a 46.0.1 patchset release with some bug fixes
- Backport https://github.com/apache/datafusion/pull/15124

[branch-46] Fix broken `serde` feature (#15124)

---

benchmarks/src/imdb/convert.rs
benchmarks/src/tpch/convert.rs
datafusion/core/src/dataframe/mod.rs
datafusion/core/tests/dataframe/mod.rs
datafusion/expr/src/expr_fn.rs
datafusion/expr/src/lib.rs
datafusion/expr/src/logical_plan/builder.rs
datafusion/expr/src/select_expr.rs
datafusion/proto/tests/cases/roundtrip_logical_plan.rs
datafusion/sql/src/expr/function.rs
datafusion/sql/src/select.rs
datafusion/sql/src/statement.rs
datafusion/sql/src/unparser/expr.rs
datafusion/sql/tests/cases/plan_to_sql.rs
datafusion/sqllogictest/test_files/select.slt

Fix wildcard dataframe case

---

datafusion/datasource-parquet/src/file_format.rs
datafusion/datasource-parquet/src/opener.rs

I found this code snippet can be improved while I read the code in the file.
Reduced Schema Traversals: The refactored code traverses the schema fields only once instead of twice, cutting computational complexity by half for large schemas.
Early-Exit Optimization: By detecting transformation requirements early, unnecessary processing is avoided when no transformations are needed.
Improved Documentation: The function has clear documentation explaining its purpose and operation.
Leverage previous tests
None

Refactor file schema type coercions

---

datafusion/sqllogictest/README.md

minor: fix `data/sqlite` link

---

datafusion/optimizer/src/optimizer.rs
datafusion/optimizer/tests/optimizer_integration.rs
datafusion/sqllogictest/test_files/explain.slt
datafusion/sqllogictest/test_files/group_by.slt

[Minor] Remove/reorder logical plan rules

---

docs/source/user-guide/concepts-readings-events.md

NIL.
This PR improves the overall quality and accessibility of the documentation by:
- Enhancing readability through improved formatting.
- Providing additional learning resources for users.
- Fixing and updating the resources with proper links for slides and recordings.
- Fixing mislabeled resources and adding tags in the "Good Reads" section to maintain uniformity.
Apart from adding supplemental resources and reference links to external materials shared in discord but I noticed there were a few resources not updated yet and some resources were mislabeled / missing. So I scraped around the internet and updated as much as I could.
The changes improve documentation formatting for better reading, adds new content and included links to relevant presentation slides / recordings for existing …

Docs: Formatting and Added Extra resources

---

benchmarks/README.md
benchmarks/bench.sh

- Closes #.
Currently it is possible to run a specific query for the benchmark using a cumbersome command 
```
cargo run --release --bin dfbench -- tpch --iterations 3 --path ./data --format tbl --query 1 --batch-size 4096
```
which requires much more information, this PR is to provide an optional query filter from `bench.sh` command line

minor: Allow to run TPCH bench for a specific query

---

datafusion/physical-plan/src/joins/hash_join.rs

- Closes #15493.
I'm not sure why #15476 caused the CI and other case failures https://github.com/apache/datafusion/issues/15493#issuecomment-2764449044. However, after reverting it, all the tests pass.
I prefer to revert this commit before we fix this issue.
- Revert #15476

Revert #15476 to fix the datafusion-examples CI fail

---

datafusion/functions-nested/src/sort.rs
datafusion/sqllogictest/test_files/array.slt

ArraySort: support structs

---

datafusion/physical-plan/src/joins/sort_merge_join.rs

minor: Organize fields inside SortMergeJoinStream

---

datafusion/physical-plan/src/joins/hash_join.rs
datafusion/physical-plan/src/joins/mod.rs
datafusion/physical-plan/src/joins/utils.rs
datafusion/physical-plan/src/projection.rs

chore: rm duplicated `JoinOn` type

---

datafusion/datasource-parquet/src/page_filter.rs

Chore: Call arrow's methods `row_count` and `skipped_row_count`

---

datafusion/core/src/datasource/listing/table.rs
datafusion/datasource/src/statistics.rs

- Closes #.
While reviewing the PR https://github.com/xudong963/arrow-datafusion/pull/5 from @alamb , I noticed that there are some confusion in comments
Enhance and fix comments

Minor: refine comments for statistics compution

---

datafusion/proto/proto/datafusion.proto

N/A
The Java package name needs updating now that DataFusion is a top-level project.
Rename package.
No. This package name is actually not referenced anywhere in this repo. It would only affect people who generate Java bindings.

chore: Rename protobuf Java package

---

datafusion/physical-plan/src/topk/mod.rs

[Minor] Use interleave_record_batch in TopK implementation

---

datafusion/functions-aggregate/src/first_last.rs

Minor: add order by arg for last value

---

docs/source/user-guide/sql/explain.md

#15606 changed repartitionExec display tree

doc : update RepartitionExec display tree

---

datafusion/datasource/src/file_scan_config.rs
datafusion/datasource/src/file_stream.rs

- Follow up https://github.com/apache/datafusion/pull/15671

Avoid computing unnecessary statstics

---

docs/source/user-guide/introduction.md

doc: Adding Feldera as known user

---

datafusion/physical-plan/src/aggregates/group_values/row.rs

Minor: cleanup hash table after emit all

---

datafusion/sqllogictest/test_files/aggregate.slt

- Closes #15789.
Tests improvement
Fix potential flaky test in aggregate.slt
Yes
No

Minor: fix potential flaky test in aggregate.slt

---

.asf.yaml

- Closes https://github.com/apache/datafusion/issues/15877
See the PR: https://github.com/apache/infrastructure-asfyaml/pull/66 & the doc: https://github.com/apache/infrastructure-asfyaml?tab=readme-ov-file#pull-request-settings

Keeping pull request in sync with the base branch

---

docs/source/user-guide/introduction.md

- Closes #.
Update users description where missing and some punctuation

doc: Update known users docs

---

.asf.yaml

- Follow up: https://github.com/apache/datafusion/pull/15894
After https://github.com/apache/datafusion/pull/15894, I found the update branch still doesn't work, after checking the doc carefully, I found I missed the **s**

Fix allow_update_branch

---

docs/source/user-guide/introduction.md

- Fix typo in introduction.md
- Remove period from end of bullet point to maintain consistency with other bullet points
- No issue: simply noticed a typo when reading documentation
Maintain good spelling and consistency in formatting
No tests - just a change to .md file
Changes are user-facing but in a .md file

Fix typo in introduction.md

---

datafusion/sqllogictest/test_files/parquet_filter_pushdown.slt

- Closes #.
https://github.com/apache/datafusion/actions/runs/14833815909/job/41640667985

Fix main CI by adding `rowsort` to slt test

---

Cargo.lock
datafusion/core/benches/push_down_filter.rs
datafusion/physical-optimizer/src/filter_pushdown.rs
datafusion/physical-plan/src/filter.rs

Brings benchmark from ~30us to ~3us.

Improve filter pushdown optimizer rule performance

---

datafusion/core/tests/fuzz_cases/join_fuzz.rs
datafusion/physical-plan/src/joins/sort_merge_join.rs
datafusion/sqllogictest/test_files/sort_merge_join.slt

Implement RightSemi join for SortMergeJoin

---

datafusion/optimizer/src/common_subexpr_eliminate.rs
datafusion/optimizer/src/eliminate_cross_join.rs
datafusion/optimizer/src/eliminate_duplicated_expr.rs
datafusion/optimizer/src/eliminate_filter.rs
datafusion/optimizer/src/eliminate_group_by_constant.rs
datafusion/optimizer/src/eliminate_join.rs
datafusion/optimizer/src/eliminate_nested_union.rs
datafusion/optimizer/src/eliminate_outer_join.rs
datafusion/optimizer/src/filter_null_join_keys.rs
datafusion/optimizer/src/optimize_projections/mod.rs
datafusion/optimizer/src/propagate_empty_relation.rs
datafusion/optimizer/src/push_down_filter.rs
datafusion/optimizer/src/push_down_limit.rs
datafusion/optimizer/src/replace_distinct_aggregate.rs
datafusion/optimizer/src/test/mod.rs

- Closes #15396
- Related #15446, #15884, #15893, #15937, #15945, #15984
This is the part 7 of #15396  
No

Migrate Optimizer tests to insta, part7

---

datafusion/sqllogictest/test_files/imdb.slt

Added SLT tests for IMDB benchmark queries

---

datafusion/expr-common/src/type_coercion/binary.rs
datafusion/sqllogictest/test_files/binary.slt

- Closes #15755.
cannot convert FixedSizeBinary to BinaryView
support coercing FixedSizeBinary to BinaryView
UT
No

feat: coerce to/from fixed size binary to binary view

---

datafusion/physical-plan/src/common.rs

DataFusion now uses the [SpillManager](https://github.com/apache/datafusion/blob/b6a51740f1c3cd92e416fea4d2f3b1600f10c97a/datafusion/physical-plan/src/spill/spill_manager.rs#L41) code for writing spill files and `IpcWriter` is unused
This is also duplicative with code upstream
Remove unused code
By CI
This is technically a pub struct so this is an API change. If we wanted to lower the potential impact we could mark the struct as deprecated instsead but given it is old and unused I thought it would be ok to just delete it

Minor: remove unused IPCWriter

---

docs/source/user-guide/introduction.md

Add iceberg-rust to user list

---

dev/changelog/48.0.0.md

- Part of https://github.com/apache/datafusion/issues/15771
We added some more commits to the 48 release, so let's make sure they are included in the changelog.
I ran this command and checked in the results:
```shell
./dev/release/generate-changelog.py 47.0.0 branch-48 48.0.0 > dev/changelog/48.0.0.md
```

[branch-48] Update CHANGELOG for latest 48.0.0 release

---

datafusion/functions/src/string/to_hex.rs
datafusion/sqllogictest/test_files/expr.slt

Add support `UInt64` and other integer  data types for `to_hex`

---

benchmarks/bench.sh

- Closes #.
There are a large number of benchmarks now in `bench.sh`'s help message. This PR groups them into categories to improve readability.

Minor: Clean-up `bench.sh` usage message

---

datafusion/expr/src/udf.rs

\-
Better DX.
Auto-derives.
\-
For devs: the things that you expect to work now work.

feat: derive `Debug` and `Clone` for `ScalarFunctionArgs`

---

docs/source/user-guide/sql/ddl.md

CI was broken in #16524 this PR to fix `ddl.md` formatting
- Closes #.

chore: fix CI failures on `ddl.md`

---

datafusion/sql/src/expr/function.rs
datafusion/sqllogictest/test_files/aggregate.slt

Improve err message grammar

---

datafusion/sql/src/expr/function.rs
datafusion/sqllogictest/test_files/aggregate.slt

- Closes #16596.
raise exception when order_by and within_group are specified
UT
No

fix: disallow specify both order_by and within_group

---

datafusion/sql/src/expr/function.rs
datafusion/sqllogictest/test_files/aggregate.slt

- Closes #16596.
- Follow up https://github.com/apache/datafusion/pull/16606/files#r2173688327
change error message
UT
No

fix: format within_group error message

---

datafusion/ffi/src/udwf/mod.rs
datafusion/ffi/src/udwf/partition_evaluator_args.rs

(note this targets branch-48, NOT `main`)
- Part of https://github.com/apache/datafusion/issues/16486
- Fixes https://github.com/apache/datafusion-python/issues/1144 on 48.0.1
- Backport of https://github.com/apache/datafusion/pull/16480

[branch-48] fix: column indices in FFI partition evaluator (#16480)

---

datafusion/core/tests/physical_optimizer/partition_statistics.rs
datafusion/physical-plan/src/placeholder_row.rs

\-
The current stats are very vague and can actually be better.
Use proper stats.
Regression test.
\-

fix: `PlaceholderRowExec::partition_statistics`

---

datafusion/physical-optimizer/src/enforce_distribution.rs

- Closes #.
`add_spm_on_top()` in `enforce_distribution.rs` either adds SortPreservingMergeExec or CoalescePartitionsExec, depending on the order requirement. So, using a more generic name is less surprising.

minor: Rename add_spm_on_top as add_merge_on_top

---

datafusion/physical-plan/src/aggregates/topk/hash_table.rs

- Closes #16837.
Solve issue 16837
Pass full datatype though to output in `PrimitiveHashTable`
A unit test was added. It failed, then it didn't.
More queries should work.

Fix [Bug] Aggregate + TopK fails when asc = false

---

datafusion-cli/src/print_format.rs

Closes #15795 .
```sh
cargo test --package datafusion-cli
```
No.

test(datafusion-cli): migrate tests to `insta` in `print_format.rs`

---

docs/source/user-guide/sql/window_functions.md

- Fix failing CI introduced in #16930

docs: Fix failing CI

---

datafusion/physical-expr/src/scalar_function.rs

implements:
- https://github.com/apache/datafusion/pull/17078#discussion_r2263312644

Improve Hash speed for ScalarFunctionExpr

---

datafusion/spark/src/function/datetime/date_add.rs
datafusion/spark/src/function/datetime/date_sub.rs
datafusion/spark/src/function/datetime/mod.rs
datafusion/sqllogictest/test_files/spark/datetime/date_add.slt
datafusion/sqllogictest/test_files/spark/datetime/date_sub.slt
datafusion/sqllogictest/test_files/spark/datetime/dateadd.slt

- Closes #.
implement spark function date_add/date_sub
UT
No

feat(spark): implement spark datetime function  date_add/date_sub

---

datafusion/proto/src/physical_plan/mod.rs
datafusion/proto/tests/cases/roundtrip_physical_plan.rs

- part of https://github.com/apache/datafusion/issues/17229
Note: targets the `branch-49` not `main`
- Backport https://github.com/apache/datafusion/pull/17224
cc @alamb

[branch-49] Backport fix: deserialization error for FilterExec (predicates with inlist) 

---

datafusion/core/tests/catalog/memory.rs

chore: check the error message log

---

datafusion/core/benches/sql_planner.rs

Part of #17261
Adding/updating benchmarks to allow for making it easier for others to investigate planning performance concerns.
sql_planner benchmark update.
Yes.
No

Expand sql_planner benchmark for benchmarking physical and logical optimization.

---

README.md

fix(doc): update the link of deprecation guidelines (#17328)

---

datafusion-examples/README.md

- Closes #.
Come across that example is not listed in readme
add `custom_file_casts` and `default_column_values` examples to the list

MINOR: add missing examples to example list

---

datafusion/functions-nested/src/map_keys.rs

fix: align `map_keys` nullability flag

---

datafusion/datasource-parquet/src/reader.rs

- Backports https://github.com/apache/datafusion/pull/17302.

[branch-50]  fix: Ensure the CachedParquetFileReader respects the metadata prefetch hint (#17302)

---

typos.toml

fix: Ignore governance doc from typos

---

datafusion/sqllogictest/test_files/join.slt.part

- Closes #14015
Actual cause for the above issue has already been fixed, so just adding the test case to our suite to prevent regressions.
Add SLT case generated by SQLancer.
Adding a test.
No.

minor: add SQLancer fuzzed SLT case for natural joins

---

.github/dependabot.yml

Currently `dependabot` runs daily and becomes noisy. 
- Closes #.

chore: dependabot to run weekly

---

datafusion/expr/src/conditional_expressions.rs

This is a one line PR to make it easier for downstream projects to use `CaseBuilder`.

minor: impl Clone and Debug on  CaseBuilder
