datafusion-cli/src/exec.rs, datafusion-cli/src/helper.rs
Partially #7255
datafusion-cli currently only supports the generic dialect.
For example: 
```
DataFusion CLI v28.0.0
❯ set datafusion.sql_parser.dialect = postgresql;
0 rows in set. Query took 0.003 seconds.
❯ select 17 # 5;  🤔 Invalid statement: sql parser error: No infix parser for token Sharp
```
`select 17 # 5` is valid in the PostgreSQL dialect, but got an ‘Invalid statement’ error.
This is because the rustyline validator only supports the generic dialect, not the one specified by the current user.
https://github.com/apache/arrow-datafusion/blob/bb185a64d1ec14eb3f6c638147d382a2a0fcf4dd/datafusion-cli/src/helper.rs#L53
- rustyline validator takes into consideration the current user’s dialect setting. 
- After SQL statement execution is completed, attempt to synchronize the validator’s …
=> fix: CLI should support different sql dialects

datafusion/core/tests/sqllogictests/test_files/scalar.slt, datafusion/expr/src/operator.rs, datafusion/sql/src/expr/binary_op.rs
Closes #7255.
`'#'` is PostgreSQL-specific bitwise XOR  operator,  which is not supported in Datafusion.
```sh
DataFusion CLI v28.0.0
❯  set datafusion.sql_parser.dialect = postgresql;
0 rows in set. Query took 0.002 seconds.
❯ select 17#5;
This feature is not implemented: Unsupported SQL binary operator PGBitwiseXor
```
-  Add support for PostgreSQL bitwise XOR operator.
- Unify the display name of bitwise XOR operator.
Yes
No
=> feat: Add support for PostgreSQL bitwise XOR operator

datafusion/core/tests/sqllogictests/test_files/aggregate.slt, datafusion/core/tests/sqllogictests/test_files/errors.slt, datafusion/expr/src/aggregate_function.rs, datafusion/expr/src/built_in_function.rs, datafusion/expr/src/utils.rs, datafusion/expr/src/window_function.rs, datafusion/optimizer/src/analyzer/type_coercion.rs
Closes #6396 .
When wrong function signature is given, it's more clear to provide error message with "what's the right function signature" instead of "what's wrong"
Previous PRs in #6396  have implemented such error messages for built-in scalar functions, this PR would like to also implement it for aggregate/window functions.
Before:
```sql
DataFusion CLI v28.0.0
❯ select corr();
Error during planning: The function Correlation expects 2 arguments, but 0 were provided
❯ select regr_slope(1, '2');
Error during planning: The function RegrSlope does not support inputs of type Int64.
❯ select row_number(column1)
over (order by column1 rows between 2 preceding and current row)
from (values (1,2), (2,4), (3,6), (4,12), (5,15), (6, 18));
Error during planning: The function expected 0 arguments …
```
=> Improve error message for aggregate/window functions

datafusion/optimizer/src/optimizer.rs
In connection to #7241.
If we allow buggy logical plans to be skipped then plans that don't fail but produce different schemas should also be skippable. 
Moved checking schema equality before handling logical plan errors so that the same option `skip_failed_rules` can be applied to these rules as well
Added a new test for this case. 
The error message changed slightly. 
Don't think so
Nope
=> Allow `skip_failed_rules` to skip  buggy logical plan rules that have a schema mismatch

datafusion/core/src/datasource/file_format/csv.rs, datafusion/core/src/datasource/listing/table.rs, datafusion/core/src/datasource/listing_table_factory.rs, datafusion/sql/src/statement.rs, datafusion/sql/tests/sql_integration.rs
Follow on to #7244 
Related to #7228 and #7036
Note: does not close #7228 since it does not provide a mechanism to create external table target if it does not exist. It does offer a partial workaround since you can now specify `OPTIONS (insert_mode append_new_files)` when creating external tables so `insert into` will add new files to the table.
Previous PRs adding support for inserting to `ListingTables` have not adequately tested an end to end process of creating an empty external table from SQL and subsequently inserting data into it. This PR adds test cases for this and adds a few enhancements / solves a few bugs to make the test cases pass.
- New test cases which create empty external table and insert data into it
- Remove logic throwing error when parquet schema is specified via SQL …
=> Enable creating and inserting to empty external tables via SQL

datafusion-examples/examples/catalog.rs, docs/source/index.rst, docs/source/library-user-guide/adding-udfs.md, docs/source/library-user-guide/building-logical-plans.md, docs/source/library-user-guide/catalogs.md, docs/source/library-user-guide/custom-data-sources.md, docs/source/library-user-guide/custom-table-providers.md, docs/source/library-user-guide/execution-plans.md, docs/source/library-user-guide/extending-operators.md, docs/source/library-user-guide/index.md, docs/source/library-user-guide/using-the-dataframe-api.md, docs/source/library-user-guide/using-the-sql-api.md, docs/source/library-user-guide/working-with-exprs.md
~Closes #~ Related to #7014
This won't finish #7014, but adds the skeleton described in that issue as well as content for the custom table provider and catalog. I can also add some info on Scalar UDFs, but am not sure I know enough about the others to write something w/o a summary to expand on.
Hope this is what you'all are looking for, certainly open to feedback.
Finally, I'm getting some unrelated (I think) warnings, are these known?
```
/Users/thauck/personal/code/github.com/tshauck/arrow-datafusion/docs/temp/user-guide/example-usage.md:24: WARNING: 'myst' cross-reference target not found: '../../../datafusion-examples' [myst.xref_missing]
/Users/thauck/personal/code/github.com/tshauck/arrow-datafusion/docs/temp/user-guide/example-usage.md:211: WARNING: Pygments lexer name …
```
=> Add library guide for table provider and catalog providers

.gitignore, datafusion/core/src/dataframe.rs, datafusion/core/src/datasource/file_format/csv.rs, datafusion/core/src/datasource/file_format/json.rs, datafusion/core/src/datasource/file_format/parquet.rs, datafusion/core/src/datasource/file_format/write.rs, datafusion/core/src/datasource/listing/table.rs, datafusion/core/src/datasource/listing/url.rs, datafusion/core/src/datasource/memory.rs, datafusion/core/src/datasource/physical_plan/csv.rs, datafusion/core/src/datasource/physical_plan/json.rs, datafusion/core/src/datasource/physical_plan/mod.rs, datafusion/core/src/datasource/physical_plan/parquet.rs, datafusion/core/src/datasource/provider.rs, datafusion/core/src/physical_plan/insert.rs, datafusion/core/src/physical_planner.rs, datafusion/expr/src/logical_plan/builder.rs, datafusion/expr/src/logical_plan/dml.rs, datafusion/expr/src/logical_plan/mod.rs, datafusion/expr/src/logical_plan/plan.rs, datafusion/expr/src/utils.rs, datafusion/optimizer/src/common_subexpr_eliminate.rs, datafusion/proto/src/logical_plan/mod.rs, datafusion/sql/src/statement.rs, datafusion/sql/tests/sql_integration.rs, datafusion/sqllogictest/bin/sqllogictests.rs, datafusion/sqllogictest/test_files/copy.slt
closes #5076 
closes https://github.com/apache/arrow-datafusion/pull/6539
Part of #5654 
In many cases, we want to be able to export data to file(s) in an ObjectStore without first registering an external table. This is possible with `COPY ... TO ...` statements. We can leverage the FileSinks created to support inserting to ListingTables for part of the implementation for this.
- Implement a logical plan for Copy To statements
- Generalize name of `InsertExec` to `FileSinkExec`
- Implement a physical plan for Copy To statements relying on `FileSinkExec`
- Expand sqllogictests in copy.slt, add support for automatically cleared directory in sqllogictests for writing files fresh
- Reimplement `DataFrame::write_* `methods to use `Copy To`
- Add support for [per_thread_output …
=> Implement Support for Copy To Logical and Physical plans

datafusion/physical-expr/src/math_expressions.rs, docs/source/user-guide/expressions.md
Closes #7310 
`nanvl` was added in #7171 but some additional change needed.
One is adding an entry to the function list table in `user-guide/expressions.md` for `nanvl`.
Another is modifying the error message in tests newly added to `math_expressions.rs`.
This PR added an entry to the function list table for `nanvl` and fix the error message in `math_expressions.rs`.
Existing tests pass with `cargo test --workspace`.
No.
=> Minor: Followup tasks for `nanvl`

datafusion/core/src/datasource/listing/url.rs, datafusion/core/src/datasource/listing_table_factory.rs, datafusion/core/src/physical_planner.rs, datafusion/expr/src/logical_plan/plan.rs, datafusion/sqllogictest/test_files/insert_to_external.slt
Closes #7228
(^ this issue was closed prematurely with #7276 by accident, but this one should close it for real)
Existing Sqllogic tests for insert into only cover memory tables. Expanding this to cover external tables will improve our test coverage and validation of changes to FileSinks.
- Adds `insert_to_external.slt` which replicates many of the tests in `insert.slt` but for external ListingTables
- Refactor the logic for creating local file paths if not existing in `Copy To` physical plan to a new method `ListingTableUrl::parse_create_local_if_not_exists`
- Add new option for external table creation to allow creating local path
```sql
statement ok
CREATE EXTERNAL TABLE
single_file_test(a bigint, b bigint)
STORED AS csv
LOCATION 'test_files/scratch/single_csv_table.csv'
OPTIONS( …
```
=> Add Sqllogictests for INSERT INTO external table

datafusion/sql/src/statement.rs, datafusion/sql/tests/sql_integration.rs
Closes #7315.
Add qualifiers to the filter fields of the `UPDATE` statement plan.
See above
Existing tests altered to accordingly.
The `EXPLAIN` will now show qualified fields for the filter node of the `UPDATE` plan.
=> Qualify filter fields in the update plan

datafusion/core/Cargo.toml
Discussed in https://github.com/apache/arrow-datafusion/discussions/7253
We are using a new API `JoinSet::spawn_blocking` introduced in tokio 1.28.
https://github.com/apache/arrow-datafusion/blob/f2c0100a5a10bf3ea166a1a590d94b8c9b6cf673/datafusion/core/src/physical_plan/stream.rs#L97
tokio v1.28 [changelog](https://github.com/tokio-rs/tokio/blob/master/tokio/CHANGELOG.md#1280-april-25th-2023):
> 1.28.0 (April 25th, 2023)
Added
task: add JoinSet::spawn_blocking and JoinSet::spawn_blocking_on (https://github.com/tokio-rs/tokio/pull/5612)
So it’s better for us to raise the minimum required tokio version to 1.28.
This can help avoid compilation failures for users.
Bump tokio version
N/A
No
=> chore(deps): update tokio requirement to 1.28

datafusion/common/src/test_util.rs, datafusion/core/src/datasource/physical_plan/csv.rs, datafusion/core/src/test_util/mod.rs
Final prep for #1754 
physical plan can't depend on code in core when I pull it out
move some functions from `datafusion/core/src/test_util.rs` to `datafusion/common/src/test_util.rs`
No -- I left backward compatible `pub use`
=> Minor: Move shared testing code into datafusion_common

datafusion/expr/src/built_in_function.rs, datafusion/sqllogictest/test_files/functions.slt
=> refine: `substr` error

datafusion/sql/src/statement.rs
Closes #.
This patch makes `sql_statement_to_plan_with_context()` public. Compared to `sql_statement_to_plan`, it accepts an external `PlannerContext`, which allows pre-registering some external context for planning
Like above
n/a
A new public API `sql_statement_to_plan_with_context`
=> chore: public sql_statement_to_plan_with_context()

datafusion/common/src/scalar.rs, datafusion/physical-expr/src/aggregate/bit_and_or_xor.rs
=> Deprecate ScalarValue bitor, bitand, and bitxor (#6842)

datafusion/core/src/execution/context.rs, datafusion/core/src/prelude.rs, datafusion/core/tests/sql/mod.rs, datafusion/core/tests/sql/sql_api.rs
Closes https://github.com/apache/arrow-datafusion/issues/7328
Closes https://github.com/apache/arrow-datafusion/issues/7272
See https://github.com/apache/arrow-datafusion/issues/7328
Basically it is hard to understand how to control what SQL statements DataFusion will allow
1. New `SQLOptions` and `SessionContext::sql_with_options` apis
2. Update docs
New `SQLOptions` and `SessionContext::sql_with_options` apis
Everything should be backwards compatible
=> Add `SQLOptions` for controlling allowed SQL statements, update docs

datafusion/expr/src/built_in_function.rs, datafusion/expr/src/expr_fn.rs, datafusion/physical-expr/src/array_expressions.rs, datafusion/physical-expr/src/functions.rs, datafusion/proto/proto/datafusion.proto, datafusion/proto/src/generated/pbjson.rs, datafusion/proto/src/generated/prost.rs, datafusion/proto/src/logical_plan/from_proto.rs, datafusion/proto/src/logical_plan/to_proto.rs, datafusion/sqllogictest/test_files/array.slt, docs/source/user-guide/sql/scalar_functions.md
=> feat: `array-empty`

datafusion/expr/src/logical_plan/dml.rs
N/A
While working on https://github.com/influxdata/influxdb_iox/pull/8515  I found that DdlStatement had a `name()` but `DmlStatement` did not.  This was annoying and slowed me down (very slightly)
https://docs.rs/datafusion/latest/datafusion/logical_expr/enum.DdlStatement.html#method.name
1. Add  `WriteOp::name` and `DmlStatement::name`
New method
=> Minor: add `WriteOp::name` and `DmlStatement::name`

datafusion/core/tests/memory_limit.rs, datafusion/physical-expr/src/aggregate/median.rs
=> Specialize Median Accumulator

datafusion/core/src/execution/context.rs, datafusion/core/tests/sql/udf.rs, datafusion/optimizer/src/analyzer/type_coercion.rs, datafusion/physical-expr/src/aggregate/average.rs, datafusion/physical-expr/src/aggregate/sum.rs, datafusion/physical-expr/src/aggregate/sum_distinct.rs, datafusion/physical-expr/src/aggregate/utils.rs, datafusion/physical-expr/src/expressions/mod.rs, datafusion/sqllogictest/test_files/decimal.slt
Part of #6842
This makes it easier to see what is going on, and avoids using ScalarValue arithmetic
=> Specialize Avg and Sum accumulators (#6842)

datafusion/physical-expr/src/intervals/interval_aritmetic.rs, datafusion/physical-expr/src/intervals/rounding.rs
Closes #.
In the interval arithmetic library, there is a function converting open bounds to closed bounds for convenience. This function increments or decrements a bound's value (according to the side of the bound) one step-size of the corresponding datatype. However, some buggy cases have been realized:
1. When a floating point value is 0 and it is tried to be decremented
2. When a value is tried to be incremented when it is at its maximum
3. When a value is tried to be decremented when it is at its minimum
After the fix, when an integer is at its maximum/minimu, it remains the same. When a floating value is at its maximum/minimum, it becomes infinity/negative infinity.
There are minor changes in the implementation of next_value() function. The existing next_up()/next_down() functions …
=> Bug-fix/next_value() of Min/Max Scalar Values

datafusion/expr/src/logical_plan/builder.rs
Closes #.
original code will remove distinct when they are children of union.
But we should't remove them, because
1. distinct can decrease cardinaty/rowcount of union input
2. sometime distinct can pushdown, such as distinct can pushdown through join.
3. even if we want to remove distinct, we should create rule instead of eliminate distinct in plan builder
union_distinct shouldn't remove child distinct
=> fix: union_distinct shouldn't remove child distinct

datafusion/physical-expr/src/array_expressions.rs
This appears to have crept in as part of #7313
when I run sqllogictest it looks like
```
Running "nullif.slt"
Running "array.slt"
Running "type_coercion.slt"
Running "clickbench.slt"
Running "information_schema_columns.slt"
Running "information_schema_multiple_catalogs.slt"
args[0]: ListArray
[
PrimitiveArray<Int64>
[
1,
],
]
args[0]: ListArray
[
NullArray(0),
]
...
PrimitiveArray<Int64>
[
null,
18,
],
],
]
Compilation finished at Wed Aug 23 14:32:11
```
delete `println!`
existing tests
=> Minor: remove stray `println!` from `array_expressions.rs`

datafusion/core/src/datasource/mod.rs, datafusion/core/src/datasource/statistics.rs
N/A
I am just trying to clean up the code, and I ran into this code that was in need of a home while doing so
Move statistics code for datasource into its own module
checked by compiler
=> Minor: move datasource statistics code into its own module

datafusion/physical-expr/src/expressions/in_list.rs, datafusion/sqllogictest/test_files/predicates.slt
Closes #7377 
This PR fixes an issue that `'NaN'::double in ('NaN'::double)` is evaluated as `false`, which is inconsistent with the result of `'NaN'::double = 'NaN'::double`.
The root cause is that equality is evaluated using `PartialEq::eq`. So the fix is using `to_bits` for equality check for float values like as `ScalarValue::Float64` does.
NOTE: This issue doesn't happen when `Simplifier` simplifies `IN` expr like
```
a IN (x, y, z) -> a = x OR a = y OR a = z
```
Modified an existing test.
Yes, but this change is for correctness.
=> Fix IN expr for NaN

datafusion/core/src/datasource/listing/helpers.rs
Closes #.
No need to iterate through all files when query contains partition criteria.
=> Unnecessary to list all files during partition pruning

docs/source/user-guide/sql/ddl.md, docs/source/user-guide/sql/dml.md
Part of https://github.com/apache/arrow-datafusion/issues/7319
One thing I noticed while reviewing https://github.com/apache/arrow-datafusion/pull/7362 (thank you @spaydar !!) was that it didn't mention the `COPY (SELECT ...)` syntax, which is quite helpful for reordering input, for example. 
Add note and example of using  `COPY (SELECT ...)` and define what DDL/DML are
better docs
=> Docs: Add query syntax to `COPY` docs

datafusion/physical-expr/src/aggregate/array_agg_distinct.rs, datafusion/sqllogictest/test_files/aggregate.slt
Closes #6743.
Currently `DistinctArrayAggAccumulator` stores its state as a set of scalar values and returns it as a single scalar list. The problem is that while merging state, accumulator, instead of adding list elements, simply adds the whole list to the state as a single value, which causes errors while executing `evaluate` on accumulator with merged state.
`merge_state` now unpacks scalar list input and updates state with its elements.
- tests for merging `DistinctArrayAggAccumulator`s have been added, 
- check for successful execution of `array_agg(distinct col)` has been added to sqllogictests
`array_agg(distinct)` should not fail in case query execution requires merging accumulator states (e. g. aggregation over multiple partitions)
=> fix: inconsistent scalar types in `DistinctArrayAggAccumulator` state

docs/source/library-user-guide/adding-udfs.md, docs/source/library-user-guide/working-with-exprs.md
Closes #7304
This fills out the expr and UDF pages a bit. I tried to cover enough of the UDFs so that I could link to it from the expr page. For the expr page, it doesn't match the outline exactly -- I probably have some blindspots, so certainly open to feedback.
- Scalar part of UDF library user page
- Expr library user page
Manually built the docs to review output.
Yes
=> docs: Add `Expr` library developer page

datafusion/sqllogictest/src/engines/conversion.rs, datafusion/sqllogictest/src/engines/datafusion_engine/normalize.rs, datafusion/sqllogictest/test_files/arrow_typeof.slt
A followup to #7048.
In #7048, one question is the display string of Decimal256 scalar is different to Decimal128 in sqllogictest. This patch fixes it.
=> Fix Decimal256 scalar display string in sqllogictest

datafusion/expr/src/aggregate_function.rs, datafusion/expr/src/type_coercion/aggregates.rs, datafusion/physical-expr/src/aggregate/min_max.rs, datafusion/sqllogictest/test_files/aggregate.slt
=> feat: support Binary for `min/max`

datafusion/sqllogictest/src/engines/conversion.rs, datafusion/sqllogictest/test_files/math.slt, datafusion/sqllogictest/test_files/predicates.slt, datafusion/sqllogictest/test_files/scalar.slt, datafusion/sqllogictest/test_files/select.slt
Closes #7402 
DataFusion distinguishes `NaN` and `-NaN` so sqllogictest should distinguish them for precise test.
Changed `conversion.rs` so that it returns `"-NaN"` if a value is a kind of `NaN` and its sign is negative.
Modified existing test and added a simple test to `select.rs`.
No.
=> Make sqllogictest distinguish NaN from -NaN

datafusion-cli/src/main.rs, docs/source/user-guide/cli.md
=> feat: Add memory pool configuration to `datafusion-cli`

datafusion/execution/src/memory_pool/pool.rs
Follow up to https://github.com/apache/arrow-datafusion/pull/7424
I noticed that there was a log entry when a Greedy pool was created, but not entry when a Fair pool was created.
Add debug log entry when `FairSpillPool` is created
This is the same basic message as for the existing greedy pool: 
https://github.com/apache/arrow-datafusion/blob/2503bda50ced1bc983280e0b7783a482bc1d5714/datafusion/execution/src/memory_pool/pool.rs#L63
=> Minor: Debug log when FairPool is created

datafusion/core/tests/fuzz_cases/mod.rs, datafusion/core/tests/fuzz_cases/sort_fuzz.rs
related to #7432 
While working on https://github.com/apache/arrow-datafusion/pull/7432 I wasn't 100% clear what sort cases were covered, which lead me to `sort_fuzz`. 
I took some time to make that clearer. 
Rework `sort_fuzz` to be a builder style
only tests
=> Refactor sort_fuzz test to clarify what is covered

datafusion-cli/Cargo.lock, datafusion/common/Cargo.toml, datafusion/core/Cargo.toml, datafusion/optimizer/Cargo.toml, datafusion/optimizer/tests/optimizer_integration.rs, datafusion/physical-expr/Cargo.toml, datafusion/physical-expr/src/datetime_expressions.rs, datafusion/proto/Cargo.toml, datafusion/sqllogictest/Cargo.toml, datafusion/substrait/Cargo.toml
Closes #7450 
This PR is to make CI happy.
Replace `DateTime::from_utc` with `DateTime::from_naive_utc_and_offset`.
No.
=> Use DateTime::from_naive_utc_and_offset instead of DateTime::from_utc

datafusion/core/src/physical_plan/projection.rs, datafusion/sqllogictest/test_files/joins.slt, datafusion/sqllogictest/test_files/subquery.slt
Closes #.
- support `total_byte_size` use the primitive_size of the `datatype`
- if column of projection can't get the primitive_size, use the child statistic as statistics of the projection
=> [minior fix]: adjust the projection statistics

docs/source/user-guide/introduction.md
NA
Find two new frameworks using Datafusion. I think it is great to share
=> Add new known users: Arroyo and Restate

datafusion/physical-expr/src/utils.rs
Closes #7418 .
IOx tests failed. This error has not been encountered in Datafusion because in the absence of output ordering, `input.output_ordering()` returns None, not Some([]). This issue is fixed now.
=> Bug-fix/find_orderings_of_exprs

datafusion/core/src/physical_plan/sorts/sort.rs
Closes #.
We've seen such error but the sorter still continues to merge batches:
```
Failure while reading spill file: NamedTempFile("/var/folders/zq/2tdnn5955wvdcw7qfy6qhvk00000gn/T/.tmpkgzYB9/.tmp2bAVMU"). Error: IO error: No such file or directory (os error 2) 
```
If any spill file doesn't exist anymore, it seems more reasonable to stop merging final sort output and return an error.
=> Return error if spill file does not exist in ExternalSorter

datafusion-cli/Cargo.lock, datafusion-cli/Cargo.toml, datafusion-cli/src/main.rs
re #7424.
Find the memory pool size setting string in datafusion-cli during performance testing, and we could make the byte string more flexible.
Parse the pool byte string as the number of bytes.
Add unit test and tested locally.
No.
=> Minor: more flexible pool size setting for datafusion-cli

datafusion/core/src/physical_plan/values.rs
N/A
Allows reconstructing a `ValuesExec` from a schema and vector of record batches.
The use case here is being able to completely serialize a physical plan that would get produced from a statement like `insert into my_table values (...)`.
Serialization of `ValuesExec` is not included in this PR. My plan for serialization was to just IPC encode the batches. If that sounds reasonable, I can follow up with a PR adding that to the `proto` crate.
Adds a couple small tests.
Adds additional functions for `ValuesExec`, but no change in behavior.
=> feat: Allow creating a ValuesExec from record batches

datafusion/sql/src/statement.rs, datafusion/sql/tests/sql_integration.rs, docs/source/user-guide/sql/ddl.md
Closes #7445
The goal of this PR is to make it possible to create external tables using compression that are not in the built-in table factory, but are still valid. I.e. the logic now throws are error if you pass it a file type that's not CSV or JSON with a file compression type that's not uncompressed. Put another way, I have a `TableProviderFactory` with a custom file type that can be gzipped, and I'd like to create a table using the SQL syntax.
Another possible change is that this `plan_err` could just be removed, and the logic could be moved into the `ListingTableFactory`'s `create` method. I haven't tested this approach however.
* Update the if logic to check the exact types that aren't allowed for a more generic "not"
* Update the tests to check that the new case passes
* Update the …
=> refactor: change file type logic for create table

datafusion/optimizer/src/analyzer/subquery.rs
Closes #.
If some analyze rule inserts extension plan, the post-analyze check will fail.
It looks acceptable for an analyzer rule to do so and can simply "ignore" extension plan node, e.g., the outermost node can either be `[Projection, Filter, Window, Aggregate, Join]`, or an extension node
n/a
n/a
=> minor: do not fail analyzer if subquery plan contains extension

datafusion/physical-expr/src/expressions/in_list.rs, datafusion/sqllogictest/test_files/predicates.slt
Closes #7448 
The failure cases shown in #7448 are apparently valid. So this PR is for bug fix.
The cause of the issue is that `in_expr` doesn't consider the case where the evaluated value of each expr in a list varies per row.
So the issue happens in such a case except for the case `IN` expr is simplified by the optimizer.
The fix is to care such a case and search the target value from the list sequentially per the given RecordBatch.
Yes. But it's a bug fix.
=> Make IN expr work with multiple items

datafusion/common/src/scalar.rs
N/A
While working on upgrading IOx to arrow `46.0.0` (https://github.com/influxdata/influxdb_iox/pull/8577) I struggled to find `ScalarValue::to_scalar`
I think adding some documentation would help my future self (as well as others)
See also related discussion is https://github.com/apache/arrow-rs/issues/4781
Add doc comments and example for `ScalarVaue::to_scalar`
Yes, by doc tests
=> Minor: Add doc comments and example for `ScalarVaue::to_scalar`

datafusion/core/src/datasource/file_format/parquet.rs
Closes #7079 
When writing out multiple partitions to multiple parquet files, we can speed up the operation by writing all parquet files in parallel on multiple cpu cores.
Parallelizing the serialization of a single parquet file (similar to as done for csv/json in #7452) is more complex and will need upstream changes in arrow-rs. There is already an issue open for this here https://github.com/apache/arrow-rs/issues/1718. 
Spawn a tokio task for each parquet file being written. 
Yes by existing tests.
No other than better write performance when writing multiple parquet files on a system with multiple cpu cores.
=> Write Multiple Parquet Files in Parallel

datafusion/physical-expr/src/aggregate/average.rs, datafusion/physical-expr/src/aggregate/groups_accumulator/prim_op.rs, datafusion/physical-expr/src/aggregate/min_max.rs, datafusion/physical-expr/src/aggregate/utils.rs, datafusion/physical-expr/src/expressions/mod.rs
Closes #7493.
Currently `PrimitiveGroupsAccumulator#evaluate` method initialize the result Arrow array using its generic type parameter `T` which is a `ArrowPrimitiveType`, converted from enum `DataType`. This, however, doesn't have complete information comparing to the original `DataType` it converted from. For instance, `TimestampMicrosecondType` always have `None` as timezone while in the `DataType` it could be set to some specific timezone.
I noticed that we already have `adjust_output_array` that handles a similar case for decimal type. One straightforward solution is to add another case for `Timestamp` in the method. However, I feel the logic would become simpler if we just call `with_data_type` after creating the Arrow array. This would also allow us to prevent more potential …
=> `PrimitiveGroupsAccumulator` should propagate timestamp timezone information properly

datafusion/common/src/scalar.rs, datafusion/expr/src/logical_plan/plan.rs, datafusion/optimizer/src/unwrap_cast_in_comparison.rs, datafusion/physical-expr/src/aggregate/approx_percentile_cont.rs, datafusion/sql/src/expr/value.rs
N/A
The fact that most of the DataFusion codebase uses `fn data_type()` to retrieve the datatype but `ScalarValue` uses `get_datatype` is frustrating to me. It is a very small rough edge, but one that is easy to fix
Here is the example showing exsiting APIs that use `data_type()`:  https://github.com/search?q=repo%3Aapache%2Farrow-datafusion%20data_type&type=code
1. Add `ScalarValue::data_type()`
2. Add docs to `ScalarValue::get_datatype`
Note I did not actually `#deprecate` get_datatype as I thought that would be too large a change. I can do so if people would like however.
I changed a few locations to call `ScalarValue::data_type`
=> Minor: Add `ScalarValue::data_type()` for consistency with other APIs

datafusion/physical-expr/src/expressions/in_list.rs, datafusion/sqllogictest/test_files/scalar.slt
Closes #7495
Both the base expression and the list expressions should be considered in the nullability calculation.
Yes
No
=> fix: incorrect nullability calculation of `InListExpr`

datafusion/proto/src/logical_plan/mod.rs, datafusion/proto/src/logical_plan/to_proto.rs
N/A
Currently, we have only implemented `TryFrom<&DFSchemaRef>` for `protobuf::DfSchema`.
In the example below, when encoding a `DFSchema`, we have to create an `Arc`, which can be considered wasteful.
```rust
let dfschema = datafusion::common::DFSchema::empty();
let arc_dfschema = Arc::new(dfschema);
let proto_dfschema: datafusion_proto::DfSchema =(&arc_dfschema).try_into().unwrap();
```
Implementing `TryFrom<&DFSchema>` for `protobuf::DfSchema` helps to avoid this issue, 
and then the code is simplified as follows.
```rust
let dfschema = datafusion::common::DFSchema::empty();
let proto_dfschema: datafusion_proto::DfSchema =(&dfschema).try_into().unwrap();
```
Yes
New API, without breaking changes
=> Minor(proto): Implement `TryFrom<&DFSchema>` for `protobuf::DfSchema`

datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs, datafusion/sqllogictest/test_files/math.slt
Closes #7502.
- Disable the DivideZero simplification rule for floating types.  
- And we don’t have enough information to determine the sign of `inf`, so let’s skip optimizing for them.
Yes
No
=> fix: inconsistent behaviors when dividing floating numbers by zero

datafusion/common/src/file_options/parse_utils.rs
None
I noticed some stray comment markings (///) in an error message, probably because the message was copied from a comment in the code.
Remove the /// markings from the error message.
Yes by existing tests
Will no longer see unneeded /// markings in error message.
=> Minor: Remove stray comment markings from encoding error message

datafusion/common/src/scalar.rs
Part of #7353 
We have explicit type coercion machinery during plan construction that handles this, doing this implicitly within ScalarValue introduces inconsistency and is unnecessary. I am also not sure the type coercion logic is correct, it is certainly not consistent with the arrow-cast kernel.
Potentially more critically this definition of PartialEq is inconsistent with the definition of Hash, which could cause some very strange behaviour
=> Remove implicit interval type coercion from ScalarValue comparison

datafusion/core/src/physical_plan/common.rs, datafusion/core/src/physical_plan/sorts/sort.rs, datafusion/core/src/physical_plan/sorts/sort_preserving_merge.rs, datafusion/core/src/physical_plan/stream.rs, datafusion/core/src/test/exec.rs
Closes #7509.
Any error happened in the spawned task reading spills cannot propagate out currently. So these errors will be ignored and it doesn't look correct as the sorted result will be incorrect.
Propagating errors from spawned task reading spills.
=> Propagate error from spawned task reading spills

datafusion/core/src/datasource/file_format/parquet.rs, datafusion/core/src/datasource/physical_plan/avro.rs, datafusion/core/src/datasource/physical_plan/csv.rs, datafusion/core/src/datasource/physical_plan/file_scan_config.rs, datafusion/core/src/datasource/physical_plan/json.rs, datafusion/core/src/datasource/physical_plan/mod.rs, datafusion/core/src/datasource/physical_plan/parquet.rs, datafusion/core/src/physical_plan/mod.rs
Closes #7357
This was added by @yahoNanJing in https://github.com/apache/arrow-datafusion/pull/5572. It was then evolved in https://github.com/apache/arrow-datafusion/pull/7175 to try to avoid strongly coupling to AvroExec. However, this is causing issues trying to split apart the crates (#7357) and it is unclear how best to adapt the design https://github.com/apache/arrow-datafusion/pull/7425#discussion_r1316290949.
Given this API does not appear to be being used, I wonder if we can do the simplest possible thing, and just remove it
Removes the API
=> Remove get_scan_files and ExecutionPlan::file_scan_config (#7357)

datafusion/common/src/scalar.rs
=> Simplify ScalarValue::distance (#7517)

datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs, datafusion/sqllogictest/test_files/math.slt
N/A
Similar to #7503. 
Because of the presence of `NaN`, some simplification rules will no longer be applicable to floating-point types.
Yes
No
=> Fix some simplification rules for floating-point arithmetic operations

datafusion/core/src/physical_plan/sorts/sort.rs
Closes https://github.com/apache/arrow-datafusion/issues/7537,
Closes https://github.com/apache/arrow-datafusion/issues/7523
=> Fix flaky `test_sort_fetch_memory_calculation` test

datafusion/core/src/physical_optimizer/enforce_distribution.rs, datafusion/core/src/physical_optimizer/enforce_sorting.rs, datafusion/core/src/physical_optimizer/replace_with_order_preserving_variants.rs, datafusion/core/src/physical_optimizer/utils.rs
Closes #.
In the [discussion](https://github.com/apache/arrow-datafusion/pull/7488#discussion_r1318975676) we aggreed that moving common code used in different rules to a common location 
- will increase reusability
- will improve (make clear) dependency relation between files
This PR moves common code to under utils.rs file.
Also in this PR I revisited `visibilities` of functions and structs in the optimizer rules. Visibilities of the local structs decreased. 
=> Move common code to utils

datafusion/physical-expr/src/analysis.rs, datafusion/physical-expr/src/intervals/cp_solver.rs, datafusion/physical-expr/src/intervals/interval_aritmetic.rs
related to https://github.com/apache/arrow-datafusion/pull/7467
While reviewing https://github.com/apache/arrow-datafusion/pull/7467 I found I had to remind myself several times what open/closed meant in the context of intervals. 
1. Clarify comments on `Interval` (they were already nice, just could be somewhat clearer)
2. Add `Interval::new_open` and `Interval::new_closed` as a way to make the code more self documenting
3. Change some uses of `Interval::new` to `Interval::new_open` and `Interval::new_closed`  
I am happy to change more uses but I wanted to see what people thought of the idea first
Existing tests
No functional change intended, just easier to understand code
=> Minor: Add comments and clearer constructors to `Interval`

datafusion/optimizer/src/eliminate_cross_join.rs
Closes #7530
Explained in issue
EliminateCrossJoin optimization rule should be skipped for InnerJoin with filter, this PR fixes a bug were nested InnerJoins with filter do not cause the rule to be skipped.
yes see `eliminate_cross_not_possible_nested_inner_join_with_filter`
There are no API changes but query results might differ.
=> fix: skip EliminateCrossJoin rule if inner join with filter is found

datafusion/core/src/physical_plan/aggregates/mod.rs, datafusion/physical-expr/src/lib.rs, datafusion/physical-expr/src/physical_expr.rs, datafusion/sqllogictest/test_files/groupby.slt
Closes #.
In the [discussion](https://github.com/apache/arrow-datafusion/pull/7488#discussion_r1319438550) @Dandandan observed that we produce unnecessary `Aggregate::Partial/Aggregate::Final` stack where `Aggregate::Single` would work.
This PR fixes this problem.
This case arises only when ordering requirement of aggregator is among group by expressions. In these cases we now ignore ordering requirement (since each group will satisfy this requirement definitively.)
=> [Minor]: Produce better plan when group by contains all of the ordering requirements

datafusion/physical-expr/src/intervals/interval_aritmetic.rs
=> Minor: beautify interval display

datafusion/core/src/datasource/avro_to_arrow/arrow_array_reader.rs, datafusion/sqllogictest/Cargo.toml, datafusion/sqllogictest/test_files/avro.slt
Closes #7524 
This PR fixes an issue that I explained #7524.
The causes are:
1. `schema_lookup` considers the `lookup` table only for root record. Child records have their own `lookup` table so they should be considered too.
2. The logic for reading arrays of records are wrong.
So, this change includes fixes for them.
I prepared [this Avro format file](https://github.com/sarutak/arrow-testing/blob/nested-records/data/avro/nested_records.avro) for test.
The schema of this file is as follows.
```
{
"name": "record1",
"namespace": "ns1",
"type": "record",
"fields": [
{
"name": "f1",
"type": {
"name": "record2",
"namespace": "ns2",
"type": "record",
"fields": [
{
"name": "f1_1",
"type": "string"
},  {
"name": "f1_2",
"type": "int"
},  {
"name": "f1_3",
"type": {
"name": "record3", …
```
=> Make AvroArrowArrayReader possible to scan Avro backed table which contains nested records

datafusion/core/src/physical_plan/sorts/sort.rs, datafusion/execution/src/disk_manager.rs
Closes #7537, 
Closes #7523
Closes https://github.com/apache/arrow-datafusion/issues/7546
This issue seems a potential race condition issue.
To improve the stability, this issue need to be fixed.
This issue happens when the parent directory of spilled files are deleted before being read.
The root cause is `TempDir` of the parent directory can be dropped if [this async block](https://github.com/apache/arrow-datafusion/blob/561e0d7e87825aba224bf2eb9c3b8b5e1b725597/datafusion/core/src/physical_plan/sorts/sort.rs#L870) exits before [the reading task](https://github.com/apache/arrow-datafusion/blob/561e0d7e87825aba224bf2eb9c3b8b5e1b725597/datafusion/core/src/physical_plan/sorts/sort.rs#L618) starts like as follows.
1. Exit the [async block](https://github.com/apache/arrow-datafusion/blob/561e0d …
=> Fix a race condition issue on reading spilled file

.github/workflows/rust.yml, datafusion/common/Cargo.toml, datafusion/common/src/error.rs, datafusion/core/Cargo.toml
Closes #7522.
In #7434 the backtrace was introduced, however its expensive to build and should be optional. Introducing a cargo feature for backtrace
yes
=> Make backtrace as a cargo feature

datafusion-cli/Cargo.lock, datafusion/common/src/scalar.rs, datafusion/core/src/physical_plan/metrics/value.rs, datafusion/core/src/physical_plan/sorts/sort_preserving_merge.rs, datafusion/core/tests/parquet/mod.rs, datafusion/core/tests/sql/explain_analyze.rs, datafusion/optimizer/src/simplify_expressions/simplify_exprs.rs, datafusion/physical-expr/src/datetime_expressions.rs, datafusion/proto/src/physical_plan/to_proto.rs
Closes #.
https://crates.io/crates/chrono/0.4.31 was released recently and it appears to deprecated `timestamp_nanos`. This results in local clippy failures for me
```
error: use of deprecated method `chrono::DateTime::<Tz>::timestamp_nanos`: use `timestamp_nanos_opt()` instead
--> datafusion/physical-expr/src/datetime_expressions.rs:171:30
|
171 |     let now_ts = Some(now_ts.timestamp_nanos());
|                              ^^^^^^^^^^^^^^^
|
= note: `-D deprecated` implied by `-D warnings`
```
Use the non-deprecated API
by existing tests
=> Minor: Fix `clippy` by switching to `timestamp_nanos_opt` instead of (deprecated) `timestamp_nanos`

datafusion/physical-expr/src/aggregate/first_last.rs
Closes #7567.
Closes https://github.com/apache/arrow-datafusion/pull/7559
First and Last Accumulators would update itself from first/last row during merging state batches (e.g., `merge_batch`). However, currently it takes the whole state row (which includes `is_set` flag) into `update_with_new_row` which in turn takes all columns except for first one into `orderings` (so existing `is_set` is put there) and adds `is_set` flag. This ends with double `is_set` flags if `state` is called on the accumulators which have merged state batches.
Normally this is not an issue because `state` is not called once aggregation enters the stage of merging state batches. But in #7400, where spilling happens to call `state` on such accumulators to get its states and spill into disk. This leads to a hacky fix …
=> First and Last Accumulators should update with state row excluding is_set flag

datafusion/expr/src/utils.rs, datafusion/optimizer/src/eliminate_cross_join.rs
N/A
simplify code of eliminate_cross_join.rs
N/A
=> refactor: simplify code of eliminate_cross_join.rs

Cargo.toml, datafusion/common/Cargo.toml, datafusion/core/Cargo.toml, datafusion/optimizer/Cargo.toml, datafusion/physical-expr/Cargo.toml, datafusion/proto/Cargo.toml, datafusion/sqllogictest/Cargo.toml, datafusion/substrait/Cargo.toml
Closes #.
https://github.com/apache/arrow-datafusion/pull/7572 makes changes to fix clippy with the newest version of chrono, `0.4.31` but to do so it uses new features from that version of chrono (`timestamp_nanos_opt()`). 
Thus we need to make sure DataFusion declares that it requires at least `0.4.31` 
1. Change chrono dependency to a `workspace` dependency and specify at lest `0.4.31`
=> Minor: Update chrono pin to `0.4.31`

datafusion-cli/Cargo.lock, datafusion/core/src/datasource/listing/table.rs, datafusion/core/src/datasource/listing_table_factory.rs, datafusion/core/tests/parquet/file_statistics.rs, datafusion/core/tests/parquet/mod.rs, datafusion/execution/Cargo.toml, datafusion/execution/src/cache/cache_manager.rs, datafusion/execution/src/cache/cache_unit.rs, datafusion/execution/src/cache/mod.rs, datafusion/execution/src/lib.rs, datafusion/execution/src/runtime_env.rs, datafusion/proto/src/logical_plan/mod.rs
=> [feat] Introduce cacheManager in session ctx and make StatisticsCache share in session

datafusion/sqllogictest/test_files/encoding.slt, datafusion/sqllogictest/test_files/errors.slt, datafusion/sqllogictest/test_files/set_variable.slt
N/A
In the following example, sqllogictest will parse 'caused by' as an SQL statement, execute it, and then encounter a `ParserError`.  This is because`caused by` is the first new line after `statement error`.
The statement we really wanted to test `SET datafusion.execution.coalesce_batches to 1
` was ignored and not executed.
https://github.com/apache/arrow-datafusion/blob/678d27af3c2e800153c20da5c737a255e1450cc1/datafusion/sqllogictest/test_files/set_variable.slt#L96-L99
This could be a bug in the complete mode of sqllogictest where it generates incorrect statements for multi-line errors.
Quickly fix the misplaced statements manually.
N/A
No
=> fix misplaced statements in sqllogictest

datafusion-examples/examples/simple_udwf.rs
Both `create_udf` and `create_udaf` are used in `simple_udf.rs` and `simple_udaf.rs` respectively, and for consistency, `simple_udwf.rs` should also use the corresponding functions.
chore: use the `create_udwf` function in `simple_udwf`
=> chore: use the `create_udwf` function in `simple_udwf`, consistent with `simple_udf` and `simple_udaf`

docs/source/library-user-guide/catalogs.md
Closes #.
The documentation misuses `MemoryCatalogList` and missings the introduction of `CatalogList`. There are also some markdown structure issues.
Fix docs's errors and add the `CatalogList` trait content.
=> chore: fix catalog's usage docs error and add docs about `CatalogList` trait

datafusion/core/tests/sql/mod.rs, datafusion/expr/src/built_in_function.rs, datafusion/optimizer/src/analyzer/type_coercion.rs, datafusion/physical-expr/src/functions.rs, datafusion/physical-expr/src/math_expressions.rs, datafusion/proto/src/physical_plan/mod.rs, datafusion/sqllogictest/test_files/decimal.slt, datafusion/sqllogictest/test_files/math.slt, datafusion/sqllogictest/test_files/scalar.slt
N/A
Currently, the `abs` function only supports float types as input.
https://github.com/apache/arrow-datafusion/blob/93e14a70793ebf091ee39e2fb3ac72918ada2e13/datafusion/expr/src/built_in_function.rs#L818-L821
Other types will be converted to `Float64` when calling the `abs` function.
This type conversion is undesirable and may result in loss of precision.
```
DataFusion CLI v30.0.0
❯ create table t(c bigint) as values('922337203685477580');
0 rows in set. Query took 0.014 seconds.
❯ select arrow_typeof(abs(c)), abs(c), cast(abs(c) as bigint) c2, c from t;
+------------------------+----------------------+--------------------+--------------------+
| arrow_typeof(abs(t.c)) | abs(t.c)             | c2                 | c                  | …
```
=> feat:  natively support more data types for the `abs` function.

docs/source/contributor-guide/quarterly_roadmap.md
Closes #7535.
I've added a placeholder for the 2023 Q4 roadmap, with three issues [suggested by @alamb](https://github.com/apache/arrow-datafusion/issues/7535#issuecomment-1717983843) that are currently in progress / top priorities.
I wasn't entirely sure whether the old 2022 Q2 roadmap should be kept or removed, I've left it in for now.
=> Create 2023 Q4 roadmap

datafusion-cli/Cargo.lock, datafusion/physical-plan/Cargo.toml
\-
Too many unnecessary deps.
Remove a few that are not used at all and remove dev dependencies to their appropriate section.
CI still passes.
Less deps.
=> chore: reduce `physical-plan` dependencies

docs/source/conf.py, docs/source/index.rst
N/a
In the race to get the internets attention, github stars seem to matter. 
It serves both as a marker of use (and thus encourages new users). Thus collecting stars helps a project grow. 
Thus, let's make it easier to catch some wind from people visiting the DataFusion docs site 
Add `star` and `fork` buttons to the main doc site https://arrow.apache.org/datafusion/
Rendered preview
I tested it manually locally
New badges on the docs page
=> Minor: add githubs start/fork buttons to documentation page

docs/source/user-guide/cli.md
Closes #.
Adding more example for `CREATE EXTERNAL TABLE` doc. Specifically how to register datasource on folder level, or with wildcards
=> Minor: add more examples for `CREATE EXTERNAL TABLE` doc

datafusion/common/src/functional_dependencies.rs
Closes #7511
Make the whole LogicalPlan introspectable again.
Simple unit test included.
Publishes `Constraint`.
Implements `Deref` for `Constraints` to get `&[Constraint]`. This allows iterating `Constraints` (Without having to implement a whole iterator, or using `impl Iterator`; code is easy to switch to either of those approaches is someone has a very strong opinion. KISS sounds right to me.).
=> Expose contents of Constraints

datafusion/physical-plan/src/insert.rs, datafusion/physical-plan/src/lib.rs, datafusion/physical-plan/src/limit.rs
Closes #.
When dealing with unbounded data sources, the default implementation of `Ok(false)` can lead to silent errors.
If a plan does not implement `unbounded_output`, it cannot support unbounded outputs as default.
With existing tests.
No
=> Change the unbounded_output API default

datafusion-cli/src/exec.rs, datafusion-cli/src/main.rs, datafusion-cli/src/print_format.rs, datafusion-cli/src/print_options.rs, docs/source/user-guide/cli.md
NA
If a query outputs a large number of lines, currently datafusion-cli will display them all and flood the terminal.
This PR added a `--maxrows` option to limit max number of rows for output display.
```bash
--maxrows <MAXROWS>
The max number of rows to display for 'Table' format
[default: 40] [possible values: numbers(0/10/...), inf(no limit)]
```
```
arrow-datafusion/datafusion-cli|cli-large-output🌝| >>> cargo run --release -- --maxrows 5
Finished release [optimized] target(s) in 0.30s
Running `target/release/datafusion-cli --maxrows 5`
DataFusion CLI v31.0.0
❯ CREATE EXTERNAL TABLE lineitem STORED AS PARQUET LOCATION '/Users/yongting/Desktop/code/my_datafusion/arrow-datafusion/benchmarks/data/tpch_sf10/lineitem/part-0.parquet';
0 rows in set. Query took 0.041 seconds.
❯ select …
```
=> feat: Better large output display in datafusion-cli with --maxrows option

docs/source/user-guide/example-usage.md
Closes #.
In the PR #7434 the optional backtrace has been added for most Datafusion errors. This PR is for updating the user doc how to enable and use backtraces
Not needed
=> Minor: Adding backtrace documentation

.github/workflows/rust.yml, Cargo.toml, datafusion/wasmtest/Cargo.toml, datafusion/wasmtest/README.md, datafusion/wasmtest/datafusion-wasm-app/.gitignore, datafusion/wasmtest/datafusion-wasm-app/README.md, datafusion/wasmtest/datafusion-wasm-app/bootstrap.js, datafusion/wasmtest/datafusion-wasm-app/index.html, datafusion/wasmtest/datafusion-wasm-app/index.js, datafusion/wasmtest/datafusion-wasm-app/package-lock.json, datafusion/wasmtest/datafusion-wasm-app/package.json, datafusion/wasmtest/datafusion-wasm-app/webpack.config.js, datafusion/wasmtest/src/lib.rs, dev/release/rat_exclude_files.txt
Closes https://github.com/apache/arrow-datafusion/issues/177
As a follow on to https://github.com/apache/arrow-datafusion/pull/7625 and inspired by @alamb comment in https://github.com/apache/arrow-datafusion/issues/7624#issuecomment-1732272727, this PR adds a `wasmtest` crate that depends on the DataFusion crates that are current WASM-compatible and uses `wasm-pack` to compile it. This wasm-pack build is added as a GitHub action to make sure that we don't inadvertently break the WASM compatibility of crates that are currently compatible.
I also added a `datafusion/wasmtest/datafusion-wasm-app` directory containing a small standalone app that loads and runs the `wasmtest` crate.  This isn't used in CI, but makes it easy to play with WASM support during development.
I also added some notes …
=> Add test crate to compile DataFusion with wasm-pack

datafusion/core/src/execution/context.rs
Related to a discussion with @Ted-Jiang  on https://github.com/apache/arrow-datafusion/pull/7620/files#r1334962930
There is a reason there is no `Default` impl for `SessionState` but that reason is not explicitly documented anywhere. Let's document it.
Add docstrings to `SessionState`
=> Minor: improve docstrings on `SessionState`

docs/source/user-guide/dataframe.md
In the [documentation for DataFrame](https://arrow.apache.org/datafusion/user-guide/dataframe.html), a copy/paste of the example has a couple of compile errors.
`.show` returns a `Future`, and the `Future` returns a `Result`.
Closes #7649.
Make it easier to use the example.
=> Update example in the DataFrame documentation.

datafusion/optimizer/src/extract_equijoin_predicate.rs
N/A
While reviewing https://github.com/apache/arrow-datafusion/pull/7612 it took me a while to find this optimziation and when I did so it was lacking in docs. 
Add docstrings
N/A
Docs
=> Minor: add doc comments to `ExtractEquijoinPredicate`

datafusion/core/src/physical_optimizer/enforce_distribution.rs
Closes #.
Sometimes in the physical plan I see `RepartitionHash(input_partition=1, output_partition=1)`. In these cases, hash repartitioning is unnecessary. This PR adds a check for this case.
Yes, a new test is added to show that unnecessary hash repartition is not added to the physical plan. Even if operator requires hash repartitioning.
=> [MINOR]: Do not add unnecessary hash repartition to the physical plan

datafusion/core/src/datasource/avro_to_arrow/arrow_array_reader.rs, datafusion/core/src/datasource/avro_to_arrow/schema.rs, datafusion/sqllogictest/test_files/avro.slt
Closes #7634
Avro defines three kinds of named types - `Record`, `Enum` and `Fixed`.
https://avro.apache.org/docs/1.11.1/specification/#names
But DataFusion currently supports only Record.
So this PR aims to add support for the rest of the named types.
It's not trivial that which Arrow type Avro's `Enum` or `Fixed` should be converted to.
So I referred to how Apache Spark converts such types.
Spark converts `Enum` type to String, and `Fixed` to Binary.
Similarly, this PR introduces the conversion rule that converts `Enum` to `Utf8` and `Fixed` to `FixedSizeBinary`.
For `Enum`, given we have the following schema and corresponding data (represented as JSON here for readability).
```
{
"name": "record1",
"namespace": "ns1",
"type": "record",
"fields": [
{
"name": "f1",
"type": {
"name": …
```
=> Support Avro's Enum type and Fixed type

datafusion/common/src/utils.rs, datafusion/core/src/physical_optimizer/enforce_distribution.rs, datafusion/core/src/physical_optimizer/enforce_sorting.rs, datafusion/core/src/physical_optimizer/replace_with_order_preserving_variants.rs, datafusion/core/src/physical_optimizer/utils.rs, datafusion/physical-plan/src/lib.rs, datafusion/physical-plan/src/windows/bounded_window_agg_exec.rs, datafusion/physical-plan/src/windows/mod.rs, datafusion/physical-plan/src/windows/window_agg_exec.rs
Closes #.
This PR is mostly a restructure PR. All of the changes comes from code movement or comment updates.
Currently window construction analysis for the given input is done using a helper function inside `enforce_sorting`. However, doing this in enforce_sorting clutters code a bit there. Also this functionality may be useful in other places also. 
This PR moves this analysis to the methods of the `WindowAggExec` and `BoundedWindowAggExec`.
=> Move window analysis to the window method

datafusion/core/src/dataframe.rs, datafusion/core/src/datasource/view.rs, datafusion/expr/src/logical_plan/builder.rs, datafusion/optimizer/src/push_down_filter.rs, datafusion/optimizer/src/push_down_projection.rs, datafusion/optimizer/src/simplify_expressions/simplify_exprs.rs, datafusion/optimizer/src/unwrap_cast_in_comparison.rs
Closes #7683
We don't want to scan columns not needed by the rest of the plan.
We change the scan implementations to apply the filters before the projection.
This way we don't need to add the filters to the projection in to make the plan correct.
Existing tests + new test.
=> Don't add filters to projection in TableScan

datafusion/expr/src/table_source.rs
Related to https://github.com/apache/arrow-datafusion/pull/7680 
While reviewing https://github.com/apache/arrow-datafusion/pull/7680 from @tshauck  (👋 ) I realized the documentation for `TableProviderFilterPushDown` could be clearer
Improve the docstrings 
N/A
=> Minor: Improve  `TableProviderFilterPushDown` docs

datafusion/core/tests/sql/timestamp.rs
=> FIX:  Test timestamp with table

datafusion/optimizer/src/simplify_expressions/simplify_exprs.rs
Closes #7700
Fix issue in `SimplifyExpressions` optimizer which fails to simplify the TableScan filter expressions.
This became visible in our testing after #7670 was merged.
=> Fix bug in `SimplifyExpressions`

docs/source/library-user-guide/custom-table-providers.md
Closes #7676 
See issue re: question
Adds section to expand on the `TableProvider` trait functionality and specifically one on supports_filters_pushdown.
=> docs: add section on supports_filters_pushdown

.github/workflows/rust.yml
Closes #7677
Making the CI faster accelerate development.
This PR includes improvement of cache usage in CI.
In the current workflow, the critical path seems `cargo check` to `verify benchmark results (amd64)`. So `actions/cache` is used only for the jobs.
Cached contents are also revised.
Done by CI.
With my experiment, the total duration of workflow defined by `rust.yml` was about 30 mins.
https://github.com/sarutak/arrow-datafusion/actions/runs/6329626199
No.
=> Improve cache usage in CI

datafusion/core/tests/user_defined/user_defined_aggregates.rs, datafusion/sql/src/expr/function.rs
Closes #.
Just came across these lines that UDF is parsed before scalar function:
https://github.com/apache/arrow-datafusion/blob/bcc2acd8d10204b32b64fa3b77372655eaee8f06/datafusion/sql/src/expr/function.rs#L49-L61 
And then find this rule doesn't hold for Aggr/UDAF
After this patch, UDAF can shadow builtin AggrFn if they have the same name. 
n/a
It is... I think
=> minor: revert parsing precedence between Aggr and UDAF

.github/workflows/rust.yml
Closes #7705 
To recover CI.
#7678 introduces `actions/cache` for two GA jobs but a cache for the benchmark job seems large, and this can take up the space.
So, this PR proposes to stop using the cache for the benchmark job.
Done by GA.
No.
=> Stop using cache for the benchmark job

.github/workflows/rust.yml
Closes #7707 
Run benchmarks  as intended.
This PR changes `rust.yml` to run benchmark.
This PR also changes the cargo command running benchmark to narrow the package to be built, which can reduce the build time.
Done by CI.
No.
=> Change rust.yml to run benchmark

datafusion/sql/src/expr/mod.rs, datafusion/sql/tests/sql_integration.rs
Closes #7702.
Add extra inference code for BETWEEN predicate.
Unit test in code.
Parameter type inference now works with statements like `SELECT ... WHERE col BETWEEN $1 AND $2`.
=> Extend infer_placeholder_types to support BETWEEN predicates

.github/workflows/rust.yml
Related to  https://github.com/apache/arrow-datafusion/issues/7709
While looking into https://github.com/apache/arrow-datafusion/issues/7709 I discovered why this test is run in release mode, and I wanted to leave a note for my future self
Add a comment
=> Minor: Add comment explaining why verify benchmark results uses release mode

datafusion/common/Cargo.toml, datafusion/sqllogictest/test_files/avro.slt
Closes #7717
Avro supports deflate, snappy, bzip2, xz and zstandard but currently Datafusion only enables snappy.
Change `common/Cargo.toml` to enable the codecs supported by Avro.
Added new tests.
Yes. But this change doesn't break compatibility.
=> Support all the codecs supported by Avro

datafusion/expr/src/built_in_function.rs, datafusion/expr/src/type_coercion/functions.rs, datafusion/sqllogictest/test_files/timestamps.slt
Closes #7697.
The specific use case for this change is to allow the third (offset) parameter of the date_bin function to be specified as a constant string when the input array for the second parameter has a specified time zone.
Extend the type coercion logic used with function calls to enable text respresentaions of timestamps to be coerced to a timestamp type with a timezone. If there is no other suitable choice the timezone will be "+00" (UTC).
Yes
Strictly speaking this changes the behaviour in a way a user might notice, not in a way that requires changes to the documentation though.
=> fix: coerce text to timestamps with timezones

docs/source/user-guide/introduction.md
I was reading about LanceDB and then realized it used DataFusion -- https://github.com/search?q=repo%3Alancedb%2Flance%20datafusion&type=code
cc @wjones127  
(btw I would love to know why you chose DataFusion and how you are using it -- among other things, it might make an excellent example usecase for https://github.com/apache/arrow-datafusion/issues/6782)
=> Add LanceDB to the list of Known Users

datafusion/expr/src/type_coercion/binary.rs, datafusion/expr/src/type_coercion/mod.rs, datafusion/optimizer/src/analyzer/type_coercion.rs
The method `is_numeric` is available in `arrow-rs` since version 3.0.0
Closes #1613 .
Remove redundant code
is_numeric removed, replaced with DataType::is_numeric
Tested with `cargo test`
No user-facing changes
=> Remove redundant is_numeric for DataType

datafusion/core/Cargo.toml, datafusion/core/src/datasource/avro_to_arrow/arrow_array_reader.rs, datafusion/core/src/datasource/avro_to_arrow/schema.rs, datafusion/sqllogictest/test_files/avro.slt
Corrects handling of a nullable struct union.
Closes #7662.
Bug fix
=> fix: avro_to_arrow: Handle avro nested nullable struct (union)

datafusion/core/src/lib.rs
N/A
I am trying to make sure I spend some time each day improving DataFusion's documentation. I stumbled on to some stuff today that could be clearer. 
Update landing page
=> Minor: Improve crate docs

datafusion/core/benches/topk_aggregate.rs, datafusion/core/src/catalog/mod.rs, datafusion/core/src/datasource/default_table_source.rs, datafusion/core/src/datasource/file_format/parquet.rs, datafusion/core/src/physical_optimizer/enforce_distribution.rs, datafusion/core/src/physical_optimizer/enforce_sorting.rs, datafusion/core/src/physical_optimizer/pipeline_checker.rs, datafusion/core/src/physical_optimizer/replace_with_order_preserving_variants.rs, datafusion/core/src/physical_optimizer/test_utils.rs, datafusion/core/tests/custom_sources.rs, datafusion/execution/src/memory_pool/mod.rs, datafusion/execution/src/stream.rs, datafusion/expr/src/expr.rs, datafusion/optimizer/src/push_down_filter.rs, datafusion/physical-expr/src/aggregate/mod.rs, datafusion/physical-expr/src/aggregate/utils.rs, datafusion/physical-expr/src/expressions/binary.rs, datafusion/physical-expr/src/physical_expr.rs, datafusion/physical-expr/src/sort_properties.rs, datafusion/physical-expr/src/window/built_in_window_function_expr.rs, datafusion/physical-expr/src/window/window_expr.rs, datafusion/physical-plan/src/aggregates/mod.rs, datafusion/physical-plan/src/lib.rs, datafusion/physical-plan/src/memory.rs, datafusion/physical-plan/src/projection.rs, datafusion/physical-plan/src/visitor.rs, datafusion/sql/src/expr/mod.rs, datafusion/sql/src/parser.rs
Closes #.
With new version of `RUST 1.73.0`, some of the existing code doesn't pass from clippy. This PR resolves these linter errors.
=> [MINOR]: Resolve linter errors in the main

datafusion/physical-expr/src/array_expressions.rs
Closes #.
Prefer ListArray::new() and array::compute::concat to build Array instead of ArrayData, which I think adds more complexity and difficult for understanding the code. In previous implementation I fails to build it without ArrayData, but now I know how to do :) https://github.com/apache/arrow-datafusion/pull/6879/files#r1261847204
=> Minor: Build concat_internal() with ListArray construction instead of ArrayData

datafusion/core/src/physical_optimizer/aggregate_statistics.rs, datafusion/core/tests/custom_sources.rs, datafusion/core/tests/sql/explain_analyze.rs, datafusion/sqllogictest/test_files/explain.slt
This fixes the issue of column name `COUNT(UInt8)` appearing instead of `COUNT(*)`
Closes #104.
This should make produced column name consistent with the input SQL
Tested with `cargo test`
Changes column name for this particular case
=> Fix column name for COUNT(*) set by AggregateStatistics

datafusion/expr/src/built_in_function.rs, datafusion/expr/src/lib.rs, datafusion/expr/src/signature.rs, datafusion/expr/src/type_coercion/functions.rs
Follow on to https://github.com/apache/arrow-datafusion/pull/7720
While reviewing https://github.com/apache/arrow-datafusion/pull/7720 from @mhilton 
I realized that the type coercion / signatures were not as well documented as well as they could be (e.g. the fact that DataFuson would coerce arguments for example, was somewhat implied). 
1. Improve the `Signature` and `TypeSignature` documentation
2. Rename `TIMEZONE_PLACEHOLDER` to `TIMEZONE_WILDCARD` (added in https://github.com/apache/arrow-datafusion/pull/7720) to better represent what it means
Yes, with a new doc example as well as existing tests
better docs and `TIMEZONE_WILDCARD` is better documented
=> Add documentation about type signatures, and export `TIMEZONE_WILDCARD`

datafusion/core/src/datasource/provider.rs
N/A
@comphead  liked the ASCII art (https://github.com/apache/arrow-datafusion/pull/7747#issuecomment-1749116468) :) -- but seriously I would like to make it easier for DataFusion to be used -- both the specifics of how DataFusion works as well as more general database principles. 
1. Updated docs for `TableProvider::scan`, including details about filter, projection and limit pushdown (with a diagram!)
doc tests
Docs only
=> Minor: Improve TableProvider document, and add ascii art

datafusion/core/src/physical_optimizer/pruning.rs
N/A
We make use of the PruningPredicate a lot in IOx and I think it is a powerful feature. However, it is hard to explain to people / refer them to docs about it. 
I would like to make it easier to understand by reading the docs
Improve the docs for PruningPredicate, clarifying the rationale as well as adding some examples
By doc tests
Better docs. No code changes
=> Minor: Improve `PruningPredicate` documentation

datafusion/core/src/datasource/file_format/csv.rs, datafusion/core/src/datasource/file_format/json.rs, datafusion/core/src/datasource/file_format/mod.rs, datafusion/core/src/datasource/file_format/parquet.rs, datafusion/core/src/datasource/listing/table.rs, datafusion/core/src/datasource/memory.rs, datafusion/core/src/physical_planner.rs, datafusion/physical-plan/src/insert.rs, datafusion/sqllogictest/test_files/insert_to_external.slt
Closes #7354 
See issue
Allows specifying a `required_input_ordering` on a `FileSinkExec` which forces the output to be sorted in a particular way. The setting is optional, so `Copy To` can keep its existing behavior while `ListingTable` can optionally inject its required sort order.
Yes, via a new sqllogic test
Inserting to a table with required order works and maintains required file ordering
=> Support InsertInto Sorted ListingTable

test-utils/src/lib.rs
Related to #7749 when I mentioned the wrong function (sorry @Tangruilin) 
Hopefully this will make finding this function easier
=> Minor: improve documentation to `stagger_batch`

datafusion/core/tests/sql/mod.rs
In `datafusion/core/tests/sql/mod.rs`, `#[cfg(feature = "avro")]` is applied to `pub mod create_drop`, but it is not related to Avro.
I guess this is a leftover of d01002c33228a305fdb69d3e6a51465
Removed unnecessary `#[cfg(feature = "avro")]`.
Done by CI.
No.
=> Minor: Remove unnecessary `#[cfg(feature = "avro")]`

datafusion/sqllogictest/test_files/aggregate.slt
=> Minor: make tests deterministic

datafusion/physical-expr/src/intervals/interval_aritmetic.rs
N/A
While reviewing https://github.com/apache/arrow-datafusion/pull/7758 I had to remind myself again what `[` and `(` meant and figured I would improve the docstrings to help future readers
Update the docstrings for `Intervals` to help understand the terminology more
=> Minor: Improve `Interval` Docs

datafusion/expr/src/logical_plan/builder.rs, datafusion/optimizer/src/eliminate_nested_union.rs, datafusion/optimizer/src/eliminate_one_union.rs, datafusion/optimizer/src/lib.rs, datafusion/optimizer/src/optimizer.rs, datafusion/optimizer/src/propagate_empty_relation.rs, datafusion/optimizer/src/test/mod.rs, datafusion/sql/tests/sql_integration.rs, datafusion/sqllogictest/test_files/explain.slt
=> Move nested union optimization from plan builder to logical optimizer

datafusion/core/src/dataframe.rs
Closes #7790.
The join operation produced two columns with identical names, but they belong to different relations.
We should preserve the relation names to distinguish between them.
Yes
No
=> fix: preserve column qualifier for `DataFrame::with_column`

datafusion/common/src/scalar.rs, datafusion/core/src/physical_optimizer/join_selection.rs, datafusion/core/src/physical_optimizer/pipeline_checker.rs, datafusion/physical-expr/src/expressions/negative.rs, datafusion/physical-expr/src/intervals/interval_aritmetic.rs, datafusion/physical-expr/src/intervals/utils.rs, datafusion/physical-plan/src/filter.rs
Closes #.
If there is a NegativeExpr in a PhysicalExpr, during the pruning operations of joins, we encounter a "not implemented" error. This PR enables us to use NegativeExpr's in join predicates if there is a pruning operation.
NegativeExpr's evaluate_bounds() and propagate_constraints() functions are implemented.
Yes, unit tests of propagation over NegativeExpr's are added.
=> Interval Arithmetic NegativeExpr Support

datafusion/common/src/stats.rs
Closes #.
Some parameters need to be carried along with their exactness information. That exactness information can be provided by the source, or it can be set during the execution. This implementation which will initially be useful in statistics can also be used in different areas in the future.
If this approach makes sense and is approved by the community, I will subsequently open a new [PR](https://github.com/apache/arrow-datafusion/pull/7793) where its importance on statistics will be seen and some optimizations will be possible.
An enumeration, named Precision, is implemented to define 3 types of exactness variants: Exact, Inexact, and Absent. The enum can be used in a generic way, and some utilities on usize and ScalarValue have also been added.
Yes, unit tests are added.
=> Exactness Indicator of Parameters: Precision

datafusion/core/src/dataframe.rs, datafusion/expr/src/logical_plan/builder.rs
=> add `LogicalPlanBuilder::join_on`

datafusion/core/src/physical_optimizer/enforce_sorting.rs, datafusion/core/src/physical_optimizer/test_utils.rs
Closes [#7794](https://github.com/apache/arrow-datafusion/issues/7794).
In the issue, `EnforceSorting` moves up the sort that satisfies the window. In this case, operators that are below the `SortExec` do not have ordering at their inputs. However, some of them (`SortPreservingRepartitionExec`) expects its input to be ordered. While removing `SortExec` down the plan, we also replace operators with their corresponding variants that do not preserve order. With this change I believe `SortPreservingRepartitionExec` will be replaced with `RepartitionExec` in the issue.
Yes, a new test is added to replicate problem in the issue.
=> Fix SortPreservingRepartition with no existing ordering.

datafusion/core/src/physical_optimizer/enforce_sorting.rs, datafusion/core/src/physical_optimizer/test_utils.rs, datafusion/core/src/physical_planner.rs, datafusion/core/tests/fuzz_cases/window_fuzz.rs, datafusion/physical-plan/src/windows/bounded_window_agg_exec.rs, datafusion/physical-plan/src/windows/mod.rs, datafusion/physical-plan/src/windows/window_agg_exec.rs, datafusion/proto/proto/datafusion.proto, datafusion/proto/src/generated/pbjson.rs, datafusion/proto/src/generated/prost.rs, datafusion/proto/src/physical_plan/mod.rs, datafusion/proto/tests/cases/roundtrip_physical_plan.rs
Closes #.
As far as I am aware we do not need to keep `input_schema` in the state for `WindowAggExec` and `BoundedWindowAggExec`. We can reach this schema with `self.input.schema` when needed. 
This PR removes `input_schema` from `WindowAggExec` and `BoundedWindowAggExec`.
=> [Minor]: Remove input_schema field from window executor

datafusion/physical-plan/src/sorts/merge.rs, datafusion/physical-plan/src/sorts/mod.rs, datafusion/physical-plan/src/sorts/sort.rs, datafusion/physical-plan/src/sorts/streaming_merge.rs
Prerequisite for the cascading merge.
Part of #7181 .
Create a new merge submodule which has the SortPreservingMergeStream (a.k.a. the loser tree). The SortPreservingMergeStream will be [used repeatedly](https://github.com/apache/arrow-datafusion/blob/9b1019853fb3d71f6355ab1d850089332592b3d8/datafusion/physical-plan/src/sorts/cascade.rs#L43-L75) as part of the cascading merge tree.
By comparison, the streaming_merge() method will only be called once -- by the cascading struct (in the cascade submodule).
See above.
Only moving code. Nothing change.
No.
=> refactor(7181): move streaming_merge() into separate mod from the merge node

datafusion/core/src/physical_planner.rs, datafusion/expr/src/logical_plan/dml.rs, datafusion/expr/src/logical_plan/plan.rs
=> Improve update error

datafusion/expr/src/logical_plan/builder.rs, datafusion/optimizer/src/decorrelate_predicate_subquery.rs, datafusion/optimizer/src/eliminate_join.rs, datafusion/optimizer/src/extract_equijoin_predicate.rs, datafusion/optimizer/src/scalar_subquery_to_join.rs, datafusion/sql/src/relation/join.rs, datafusion/substrait/src/logical_plan/consumer.rs
Related to https://github.com/apache/arrow-datafusion/issues/7766, follow on to https://github.com/apache/arrow-datafusion/pull/7805
@jackwener suggested in https://github.com/apache/arrow-datafusion/pull/7805/files#r1356685435 that the newly added `LogicalPlan::join_on` API could be used more widely:
> There are more code can be like this.
> 
> like `join_on_false()` .....
1. Use `join_on` more widely. 
2. Chang the API of LogicalPlan::join_on to match `DataFrame::join_on` and take an iterator of Exprs rather than just an Expr. 
Since the API change in https://github.com/apache/arrow-datafusion/pull/7805 has not been released, this is not a end-user visible API change
=> Minor: Update LogicalPlan::join_on API, use it more

datafusion/optimizer/src/eliminate_nested_union.rs, datafusion/sqllogictest/test_files/union.slt
Closes #7786.
Related to #7695.
=> Add distinct union optimization

.github/workflows/rust.yml, ci/scripts/rust_toml_fmt.sh, datafusion/sqllogictest/Cargo.toml
Closes #.
`ci/scripts/rust_toml_fmt.sh` does not return an error when any occurrence of failed.
- Update `cargo-tomlfmt` check script and CI.
- Fix the format of `datafusion/sqllogictest/Cargo.toml`
=> Make CI fail on any occurrence of rust-tomlfmt failed

datafusion/expr/src/built_in_function.rs, datafusion/expr/src/lib.rs, datafusion/expr/src/signature.rs, datafusion/physical-expr/src/functions.rs, datafusion/physical-expr/src/scalar_function.rs
NA
I'm working on something related to functions and would like to use `Monotonicity` inside `expr` crate.
But now `Monotonicity` is defined in `physical-expr` crate, which depends on `expr`
Since it should be part of the function definition, it's better to move it into `expr` crate.
=> Minor: Move `Monotonicity` to `expr` crate

datafusion/physical-plan/src/aggregates/mod.rs
No particular issue, minor fixup
Code block looks bad in the crate rustdocs right now. Also `text` code block is used as advised by the rustdocs documentation (I see `ignore` blocks being used in `unnest.rs`)
Improves rustdoc for PhysicalGroupBy
with `cargo test --doc`
None
=> Use code block for better formatting of rustdoc for PhysicalGroupBy

datafusion-cli/src/exec.rs, datafusion/common/src/dfschema.rs, datafusion/common/src/error.rs, datafusion/common/src/functional_dependencies.rs, datafusion/core/src/datasource/listing/table.rs, datafusion/core/src/execution/context.rs, datafusion/core/src/physical_optimizer/pruning.rs, datafusion/core/src/physical_optimizer/sort_pushdown.rs, datafusion/execution/src/task.rs, datafusion/expr/src/aggregate_function.rs, datafusion/expr/src/built_in_function.rs, datafusion/expr/src/expr_schema.rs, datafusion/expr/src/field_util.rs, datafusion/expr/src/logical_plan/builder.rs, datafusion/expr/src/type_coercion/binary.rs, datafusion/expr/src/utils.rs, datafusion/expr/src/window_function.rs, datafusion/optimizer/src/analyzer/type_coercion.rs, datafusion/optimizer/src/push_down_filter.rs, datafusion/physical-plan/src/joins/utils.rs, datafusion/proto/src/bytes/mod.rs, datafusion/proto/src/logical_plan/from_proto.rs, datafusion/proto/src/logical_plan/mod.rs, datafusion/sql/src/expr/arrow_cast.rs, datafusion/sql/src/expr/function.rs, datafusion/sql/src/expr/identifier.rs, datafusion/sql/src/expr/order_by.rs, datafusion/sql/src/statement.rs, datafusion/sql/tests/sql_integration.rs
Closes #7818 
The PR improves backtrace coverage for `DatafusionError::Plan` errors, specifically for errors called in 
`ok_or_else` or `map_err` constructions
Currently constructions  `ok_or_else` or `map_err` using direct reference to `DatafusionError::Plan` which makes impossible to backtrace them in case of tracing error for the `Result<T, E>`. To improve the coverage one more error macros introduced `plan_err_raw` (name discussible)
=> Extend backtrace coverage for `DatafusionError::Plan` errors errors

datafusion/physical-expr/src/physical_expr.rs
N/A
While reviewing https://github.com/apache/arrow-datafusion/pull/7804#pullrequestreview-1674090033 I spent time figuring out in more detail what these functions did. I figured I would save myself (and hopefully other future readers) some time in the future
Add doc comments and examples for `PhysicalExpr::{propagate_constraints, evaluate_bounds}`
Docs
=> Minor: Upgrade docs for `PhysicalExpr::{propagate_constraints, evaluate_bounds}`

datafusion/sqllogictest/test_files/binary.slt
Related to 
* https://github.com/apache/arrow-datafusion/issues/7345
* https://github.com/apache/arrow-datafusion/issues/7344
* https://github.com/apache/arrow-datafusion/issues/7343
* https://github.com/apache/arrow-datafusion/issues/7342
While working on Clickbench results as part of the #6782 I hit https://github.com/apache/arrow-datafusion/issues/7342 and I didn't know how many other issues @JayjeetAtGithub  hit that are still an issue. 
Add tests for the above issues (and it turns out that https://github.com/apache/arrow-datafusion/issues/7343 is no longer an issue)
This is only tests
=> Minor: Add tests for binary / utf8 coercion

datafusion/proto/src/logical_plan/from_proto.rs, datafusion/proto/src/logical_plan/to_proto.rs
Follow on to https://github.com/apache/arrow-datafusion/pull/7629
I noticed some panics while reviewing https://github.com/apache/arrow-datafusion/pull/7629 from @jayzhan211  but I didn't want to delay merging that PR any longer.
This commit avoids panics in the error handling in the ScalarValue::List protobuf encoding by using the `?` operator
instead unwrap. It also removes some unused variants that are no longer used after
https://github.com/apache/arrow-datafusion/pull/7629
By existing tests and the rust compiler
Less panics on bad data
=> Avoid panics on error while encoding/decoding ListValue::Array as protobuf

datafusion/common/src/scalar.rs, datafusion/physical-expr/src/aggregate/bit_and_or_xor.rs, datafusion/physical-expr/src/aggregate/median.rs, datafusion/physical-expr/src/aggregate/sum.rs, datafusion/physical-expr/src/aggregate/sum_distinct.rs
=> Remove redundant unwrap in `ScalarValue::new_primitive`, return a `Result` 

datafusion/core/tests/sql/expr.rs, datafusion/expr/src/built_in_function.rs
Closes #7847
Reordering the function signature to prioritize coercing to higher precision types. 
Yes, extra tests added.
=> Fix precision loss when coercing date_part utf8 argument

datafusion/core/src/prelude.rs, datafusion/expr/src/expr.rs, datafusion/expr/src/expr_fn.rs, datafusion/expr/src/operator.rs, docs/source/conf.py, docs/source/user-guide/expressions.md
=> Add operator section to user guide, Add `std::ops` operations to `prelude`, and add `not()` expr_fn

README.md, datafusion/core/Cargo.toml
=> Expose arrow-schema `serde` crate feature flag

datafusion-examples/examples/rewrite_expr.rs, datafusion/core/src/execution/context.rs, datafusion/optimizer/tests/optimizer_integration.rs, datafusion/sql/examples/sql.rs, datafusion/sql/src/expr/function.rs, datafusion/sql/src/expr/identifier.rs, datafusion/sql/src/expr/mod.rs, datafusion/sql/src/planner.rs, datafusion/sql/src/relation/mod.rs, datafusion/sql/src/statement.rs, datafusion/sql/tests/sql_integration.rs
Some field/method names are confused.
=> Improve `ContextProvider` naming:  rename` get_table_provider` --> `get_table_source`, deprecate `get_table_provider`

datafusion/expr/src/built_in_function.rs, datafusion/expr/src/type_coercion/binary.rs, datafusion/expr/src/type_coercion/functions.rs, datafusion/sqllogictest/test_files/binary.slt
Closes https://github.com/apache/arrow-datafusion/issues/7342
Closes https://github.com/apache/arrow-datafusion/issues/7345
Closes https://github.com/apache/arrow-datafusion/issues/7344
It also closes several draft / PRs:
Closes https://github.com/apache/arrow-datafusion/pull/7349
Closes https://github.com/apache/arrow-datafusion/pull/7350
Closes https://github.com/apache/arrow-datafusion/pull/7365
Some of the clickbench queries have this pattern
1. Add a bunch of comments
1. Add automatic coercion rules from `Binary` and `LargeBinary` to the appropriate `Utf8` (string) variants for `LIKE` and `ILIKE`
2. Add appropriate binary --> string logic in return type calculation for functions
Yes, new tests
Yes now some queries will not error
=> Support `Binary`/`LargeBinary` --> `Utf8`/`LargeUtf8` in ilike and string functions

datafusion/physical-expr/src/aggregate/average.rs, datafusion/physical-expr/src/aggregate/utils.rs, datafusion/sqllogictest/test_files/decimal.slt
=> Support Decimal256 on AVG aggregate expression

datafusion/execution/src/memory_pool/pool.rs
N/A
It seems clear from the documentation for `FairSpillPool` that this is what was intended here.
N/A: documentation change only
No: Documentation change only
=> Minor: fix typo in GreedyMemoryPool documentation

datafusion/physical-plan/src/sorts/cursor.rs, datafusion/physical-plan/src/sorts/merge.rs, datafusion/physical-plan/src/sorts/stream.rs
Closes #.
https://github.com/apache/arrow-datafusion/pull/7798 proposed making the cursors themselves sliceable, this resulted in a potentially surprising interface where slicing a cursor would reset its position. This is necessary because a cascading merge sort needs to re-visit rows from previous passes.
Instead of introducing a notion of cursor slicing, this PR instead separates the cursor out from the cursor's values. This in turn will allow constructing cursors multiple times on the same set of values, and potentially adding the ability to slice said values. I think this will be easier to follow.
No, all of these details are crate private
=> Add CursorValues Decoupling Cursor Data from Cursor Position

datafusion/sql/src/utils.rs, datafusion/sql/tests/sql_integration.rs, datafusion/sqllogictest/test_files/decimal.slt
=> Support Decimal256 column in create external table

datafusion/physical-expr/src/aggregate/min_max.rs, datafusion/sqllogictest/test_files/decimal.slt
=> Support Decimal256 in Min/Max aggregate expressions

datafusion/sqllogictest/test_files/decimal.slt
=> Add Decimal256 sqllogictests for SUM, MEDIAN and COUNT aggregate expressions

datafusion/common/src/file_options/parquet_writer.rs
Closes #7867
Previous warnings could be confusing and it was decided to drop single quotes to fix this.
Warnings were fixed
Tested with `cargo test` locally.
Minor change in warnings
=> Drop single quotes to make warnings for parquet options not confusing

datafusion/core/tests/fuzz_cases/limit_fuzz.rs, datafusion/core/tests/fuzz_cases/mod.rs, datafusion/core/tests/fuzz_cases/sort_fuzz.rs, test-utils/src/lib.rs
This is a follow on to https://github.com/apache/arrow-datafusion/pull/7772  (❤️ ) by @Tangruilin
I would like coverage for multi-column sorts as well as coverage for different limit values as well
1. Move tests into `limit_fuzz.rs` as they are independent of the Sort fuzz tests
2. Make the tests it run faster (in parallel)
2. Add coverage for multi-column sorts
3. Add coverage for different limit values too
Only tests
no
=> Add multi-column topk fuzz tests

datafusion/core/src/datasource/listing/table.rs, datafusion/core/src/datasource/physical_plan/avro.rs, datafusion/core/src/datasource/physical_plan/csv.rs, datafusion/core/src/datasource/physical_plan/file_scan_config.rs, datafusion/core/src/datasource/physical_plan/file_stream.rs, datafusion/core/src/datasource/physical_plan/parquet.rs, datafusion/proto/src/physical_plan/from_proto.rs, datafusion/proto/src/physical_plan/to_proto.rs
Closes https://github.com/apache/arrow-datafusion/issues/7875
Currently, `FileScanConfig.table_partition_cols` has data type `Vec<(String, DataType)>` to store only columns name and its data type. A column can include many more information such as `nullable` and extra meta data. Thus, when we convert table_partition_cols to Fields [here](https://github.com/apache/arrow-datafusion/blob/1dd887cdff518ede1d1de457f4b20c22a9c7228f/datafusion/core/src/datasource/physical_plan/file_scan_config.rs#L138), all other information of a field will either empty or default.
We want the data type of table_partition_cols a vector of Fields in the first place so when we need to store a Field, we won't lose any information.
FYI: IOx needs this requirement.
Replace data type of …
=> Change `FileScanConfig.table_partition_cols` from `(String, DataType)` to `Field`s

datafusion/common/src/scalar.rs
Closes #7900
This causes some bugs in Coralogix for `count distinct` (I couldn't reproduce with sql e2e tests in DataFusion)
=> Maintain time zone in `ScalarValue::new_list`

docs/source/library-user-guide/custom-table-providers.md
Closes #.
Seems ExecutionContext have been replace by SessionContext, this PR fix the inconsistent in doc. 
replace ExecutionContext to SessionContext
no
no
=> doc: fix ExecutionContext to SessionContext in custom-table-providers.md

Cargo.toml, datafusion-cli/Cargo.lock, datafusion-cli/Cargo.toml, datafusion-cli/src/print_format.rs, datafusion/common/Cargo.toml, datafusion/common/src/file_options/csv_writer.rs, datafusion/common/src/file_options/mod.rs, datafusion/common/src/pyarrow.rs, datafusion/core/src/datasource/file_format/csv.rs, datafusion/core/src/datasource/listing_table_factory.rs, datafusion/core/src/datasource/physical_plan/csv.rs, datafusion/core/tests/fifo.rs, datafusion/sqllogictest/test_files/json.slt, datafusion/wasmtest/Cargo.toml
=> Update arrow 48.0.0

datafusion/physical-plan/src/aggregates/mod.rs, datafusion/physical-plan/src/projection.rs
Closes #.
This is simplification Pr, to improve readability.
=> [MINOR] Simplify Aggregate, and Projection output_partitioning implementation

datafusion/physical-expr/src/aggregate/first_last.rs, datafusion/physical-expr/src/aggregate/utils.rs, datafusion/sqllogictest/test_files/groupby.slt
Closes #.
While reversing first, last aggregate function. Previously we were not reversing their ordering requirements. This results in bug during merging of the results from different batches. 
To encounter this issue. Aggregate (final) should receive its data in different batches. Hence for this reason, we should choose a batch size lower than row number in the source table.
This PR fixes mentioned problem.
=> [Bug Fix]: Fix bug, first last reverse

datafusion-examples/examples/custom_datasource.rs, datafusion/core/src/physical_planner.rs, datafusion/core/src/test_util/mod.rs, datafusion/physical-plan/src/analyze.rs, datafusion/physical-plan/src/explain.rs, datafusion/physical-plan/src/insert.rs, datafusion/physical-plan/src/lib.rs, datafusion/physical-plan/src/streaming.rs, datafusion/physical-plan/src/test/exec.rs, datafusion/physical-plan/src/unnest.rs
Follow on to https://github.com/apache/arrow-datafusion/pull/7793
While integrating https://github.com/apache/arrow-datafusion/pull/7793 into IOx, I found I had to change many of our `ExecutionPlan` implementations with the boilerplate (but non trivial) `ExecutionPlan::statistics` implementation
```rust
fn statistics(&self) -> Result<datafusion::physical_plan::Statistics, DataFusionError> {
Ok(datafusion::physical_plan::Statistics::new_unknown(&self.schema()))
}
```
In order the ease the upgrade pain for others, we should provide this as a default.
1. Provide a default impl for `ExecutionPlan::statistics`
2. Improve documentation
Hopefully a slightly less painful upgrade for https://github.com/apache/arrow-datafusion/pull/7793
=> Minor: provide default implementation for ExecutionPlan::statistics

datafusion/proto/src/logical_plan/mod.rs, datafusion/proto/src/physical_plan/mod.rs
Closes #.
Remove unnecessary clone in `LogicalPlanNode::try_into_logical_plan` and `PhysicalPlanNode::try_into_physical_plan`.
=> Minor: Remove unnecessary clone in datafusion_proto

datafusion/core/src/physical_optimizer/enforce_distribution.rs, datafusion/core/src/physical_optimizer/enforce_sorting.rs, datafusion/core/src/physical_optimizer/replace_with_order_preserving_variants.rs, datafusion/core/src/physical_optimizer/sort_pushdown.rs, datafusion/core/src/physical_optimizer/utils.rs
Closes #.
This is a cleanup PR. It removes couple of clones in the codebase, where they are not necessary. Also changes `add_sort_above` utils co that it takes `&[PhysicalSortRequirement]` instead of `&[PhysicalSortExpr]` as argument.
=> [MINOR]: Simplify code, change requirement from PhysicalSortExpr to PhysicalSortRequirement

datafusion/core/src/datasource/physical_plan/file_scan_config.rs, datafusion/core/tests/custom_sources_cases/provider_filter_pushdown.rs, datafusion/core/tests/sql/explain_analyze.rs, datafusion/optimizer/src/push_down_projection.rs, datafusion/physical-plan/src/joins/cross_join.rs, datafusion/sqllogictest/test_files/avro.slt, datafusion/sqllogictest/test_files/json.slt, datafusion/sqllogictest/test_files/subquery.slt
related to #3214 
When I want to do the query like
```
select random() from test;
```
I encounter `Arrow error: External error: Arrow error: Invalid argument error: must either specify a row count or at least one column`.  I found that the error was occurring because, after reading a `RecordBatch`, we will to reproject the `RecordBatch` use the partition column, and it did not support an empty projection. see below.
https://github.com/apache/arrow-datafusion/blob/ba50a8b178eece7e79b100d0b73bdc9d6d3ec6d5/datafusion/core/src/datasource/physical_plan/file_scan_config.rs#L342
- change `file_scan_config.rs` and `cross_join.rs` to support empty `RecordBatch`
- change `push_down_projection` to support scan table with no projection
=> support scan empty projection 

datafusion/core/src/datasource/physical_plan/parquet.rs, datafusion/core/src/datasource/physical_plan/parquet/row_groups.rs, datafusion/sqllogictest/test_files/json.slt, datafusion/sqllogictest/test_files/predicates.slt
Impl #4512  
Implement `bloom filter` support when pruning `row group`.
no
=> feat: Use bloom filter when reading parquet to skip row groups 

datafusion/optimizer/src/push_down_filter.rs
related to #7876 
As @jonahgao said, 
> Pushing `random` through the projection can also cause problems.
> If it can be fixed, then `random` will not be pushed further through the aggregatation in this case.
Previously, projection pushed down all predicates. Now, projection pushes down predicates that do not contain volatile functions or contain volatile functions but are not included in projection.
For example,
```sql
SELECT t.c1, t.r FROM (SELECT c1, random() AS r FROM test GROUP BY c1) as t WHERE t.r > 0.5 AND random() > 0.8 AND t.c1 > 5;
```
initial logical plan
```
+------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+
| initial_logical_plan …
```
=> fix: don't push down volatile predicates in projection

datafusion/core/src/physical_optimizer/enforce_distribution.rs, datafusion/core/src/physical_optimizer/enforce_sorting.rs, datafusion/core/src/physical_optimizer/test_utils.rs, datafusion/core/tests/fuzz_cases/window_fuzz.rs, datafusion/physical-expr/src/aggregate/first_last.rs, datafusion/physical-expr/src/lib.rs, datafusion/physical-expr/src/physical_expr.rs, datafusion/physical-expr/src/scalar_function.rs, datafusion/physical-plan/src/aggregates/mod.rs, datafusion/physical-plan/src/windows/bounded_window_agg_exec.rs, datafusion/physical-plan/src/windows/mod.rs
Closes #.
This PR simplifies codebase in enforce_distribution and other places a bit to improve readability. Also couples of unnecessary clones are removed.
=> [MINOR]: Simplify enforce_distribution, minor changes

.github/workflows/dev.yml, .github/workflows/rust.yml
\-
Mostly to keep the CI up-to-date, triggered by #7915.
Upgrade node version to 20.
CI passes.
\-
=> ci: upgrade node to version 20

datafusion/core/src/datasource/file_format/parquet.rs, datafusion/core/src/datasource/mod.rs, datafusion/core/src/datasource/physical_plan/mod.rs, datafusion/core/src/execution/context/parquet.rs
Follow on to https://github.com/apache/arrow-datafusion/pull/7745
I noticed a few simplifications on https://github.com/apache/arrow-datafusion/pull/7745
1. Remove some `pub use (crate)` that were enabled with `#cfg(feature = "parquet")`
Existing tests
No
=> Minor: reduce some `#cfg(feature = "parquet")`

datafusion/core/src/physical_optimizer/enforce_distribution.rs
Follow on to https://github.com/apache/arrow-datafusion/pull/7745
I noticed a few simplifications on https://github.com/apache/arrow-datafusion/pull/7745 -- namely since almost all the tests in enforce_distribution use the parquet exec, `#cfg`ing each one is overly verbose and hard to maintain.
1. Replace a bunch of`#cfg(feature = "parquet")` with a test on the entire module
Existing tests
No
=> Minor: reduce use of `#cfg(feature = "parquet")` in tests

datafusion/sql/src/statement.rs, datafusion/sqllogictest/test_files/update.slt
N/A
Similar to insert:
https://github.com/apache/arrow-datafusion/blob/08c1b69a4ec9e5ddeaefd2810c0624ce9d9a3b9b/datafusion/sql/src/statement.rs#L1149
Add a casting for the updated value to match the data type of the table’s column.
**Current**:
```sh
❯ create table t1(a int, b varchar, c double);
0 rows in set. Query took 0.025 seconds.
❯ explain update t1 set a=1, b=2, c=3.0;
+--------------+-------------------------------------------------------------+
| plan_type    | plan                                                        |
+--------------+-------------------------------------------------------------+
| logical_plan | Dml: op=[Update] table=[t1]                                 |
|              |   Projection: Int64(1) AS a, Int64(2) AS b, Float64(3) AS c |
|              | …
```
=> minor: add a datatype casting for the updated value

datafusion/sqllogictest/test_files/select.slt
Closes #6510
Add test for issue to ensure no regression
New sqllogictest case
=> Add simple exclude all columns test to sqllogictest

datafusion/common/src/dfschema.rs, datafusion/core/src/datasource/file_format/write/demux.rs, datafusion/core/src/datasource/listing/table.rs, datafusion/core/src/datasource/memory.rs, datafusion/sqllogictest/test_files/insert_to_external.slt
Closes #7891 
The initial implementation of hive style partition demux code only supported plain UTF8 arrays. This PR adds support for dictionary encoded `UTF8` arrays. 
- Extracts string values from dictionary encoded `UTF8` arrays to determine hive partitions
- Adds additional cases to schema semantic equivalence checking: `Dictionary(_, dtype)` is now considered semantically equivalent to `dtype`. 
Yes using dictionary encoded values from parquet-testing submodule
No, just (hopefully) more robust support for inserting inferred schema string data as a partition column.
=> Support Partitioning Data by Dictionary Encoded String Array Types

datafusion/sql/src/statement.rs
Follow on to https://github.com/apache/arrow-datafusion/pull/7922
I saw a way to simplify some code while reviewing https://github.com/apache/arrow-datafusion/pull/7922 so I figured I would put up a PR
Simplify some code. No functional changes intended
no
=> Minor: simplify update code

datafusion/substrait/src/logical_plan/consumer.rs, datafusion/substrait/src/physical_plan/consumer.rs, datafusion/substrait/tests/cases/roundtrip_logical_plan.rs, datafusion/substrait/tests/cases/roundtrip_physical_plan.rs, datafusion/substrait/tests/cases/serialize.rs
=> Minor: Change from `&mut SessionContext` to `&SessionContext` in substrait

datafusion/physical-plan/src/joins/hash_join.rs
Related to https://github.com/apache/arrow-datafusion/issues/7949
To explain https://github.com/apache/arrow-datafusion/issues/7949 I needed to explain the background of how HashJoinExec works, and so I wanted to encode that information into the documentation
Improved documentation. For example:
N/A
Better `HashJoinExec` documentation.
=> Minor: Improve `HashJoinExec` documentation

datafusion/core/src/physical_optimizer/combine_partial_final_agg.rs, datafusion/core/src/physical_optimizer/enforce_distribution.rs, datafusion/core/src/physical_optimizer/topk_aggregation.rs, datafusion/physical-expr/src/array_expressions.rs, datafusion/substrait/src/logical_plan/producer.rs
=> chore: clean useless clone baesd on clippy

datafusion/core/src/datasource/physical_plan/csv.rs, datafusion/core/src/datasource/physical_plan/mod.rs, datafusion/core/src/datasource/physical_plan/parquet.rs, datafusion/core/src/physical_optimizer/enforce_distribution.rs, datafusion/physical-plan/src/lib.rs
Closes https://github.com/apache/arrow-datafusion/issues/7935
Inspired by PR https://github.com/apache/arrow-datafusion/pull/7745, the repartition input code as it is now is both a bit messy (needs a `#cfg`) but also only works for `ParquetExec` and `CsvExec`, where the code is general for any ExecutionPlan.
1. Extract the `repartition` code to a trait on ExecutionPlan, which also allows other (user defined) table sources to benefit from this optimization
2. Document what is happening in more detail
3. Move implementation code for Parquet and CSV
=> Move source repartitioning into `ExecutionPlan::repartition`

datafusion/common/README.md, datafusion/core/README.md, datafusion/execution/README.md, datafusion/expr/README.md, datafusion/optimizer/README.md, datafusion/physical-expr/README.md, datafusion/physical-plan/README.md, datafusion/proto/README.md, datafusion/sql/README.md, datafusion/wasmtest/README.md
Found while reviewing #7971
Fix wrong Markdown reference-style links.
The correct format should be:
```
[DataFusion][df]
[df]: https://crates.io/crates/datafusion
```
N/A
No
=> minor: fix broken links in README.md

datafusion/sqllogictest/README.md
Related to https://github.com/apache/arrow-datafusion/issues/7966
Related to https://github.com/apache/arrow-datafusion/pull/7964
While working on https://github.com/apache/arrow-datafusion/pull/7970 I noticed that the sqllogictest crate's README was slightly differently formatted than the others. It would be nice to be consistent
1. Update the introduction of the README to follow the same pattern as the other crate readmes
2. Use standard headings
=> Minor: Upate the `sqllogictest` crate README

datafusion/common/src/scalar.rs, datafusion/sqllogictest/test_files/array.slt
=> Fix `ScalarValue` handling of NULL values for ListArray

datafusion/physical-expr/src/sort_properties.rs, datafusion/physical-expr/src/utils.rs
Closes #.
`ExprOrdering` implementation has some minor refactors where the code is hard to understand and could be simplified. Comments were added and the algorithm became more clear. A unit test for `find_orderings_of_exprs()` was added.
`ExprOrdering` struct used for finding the orders of `PhysicalExpr`'s is simplified by eliminating unnecessary `Option<>`'s. The comments are added to clarify how order information is assigned to children nodes and propagated to the main node during the transformation.
Yes.
=> Refactor of Ordering and Prunability Traversals and States

datafusion/physical-expr/src/functions.rs, datafusion/physical-expr/src/planner.rs, datafusion/sqllogictest/test_files/scalar.slt
=> Keep output as scalar for scalar function if all inputs are scalar

Cargo.toml, datafusion/common/src/scalar.rs, datafusion/sqllogictest/test_files/aggregate.slt
Closes https://github.com/apache/arrow-datafusion/issues/7938
There was a regression in query execution where multiple distinct aggregates caused a panic (because new code for `ScalarValue::new_list` was failing)
Remove special case code in `ScalarValue::new_list` and build from existing functions
New unit tests are added
Fix regression
=> Fix panic in multiple distinct aggregates by fixing `ScalarValue::new_list`

datafusion/sql/src/statement.rs, datafusion/sqllogictest/test_files/update.slt
Example Query：`update t1 set name=t2.name from t2 where t1.id=t2.id`
It modifies a table using information from other tables.
There is support for this syntax in the code, but it doesn’t actually work.
```sh
DataFusion CLI v32.0.0
❯ create table t1(id int, name text);
0 rows in set. Query took 0.032 seconds.
❯ create table t2(id int, name text);
0 rows in set. Query took 0.003 seconds.
❯ update t1 set name=t2.name from t2 where t1.id=t2.id;
Schema error: No field named t2.id. Valid fields are t1.id, t1.name.
```
> When a FROM clause is present, what essentially happens is that the target table is joined to the tables mentioned in the from_item list, and each output row of the join represents an update operation for the target table.
Ref: [PostgreSQL UPDATE SQL …
=> fix: generate logical plan for `UPDATE SET FROM` statement

datafusion-examples/examples/dataframe.rs
Closes #.
Every time the test class dataframe.rs is executed, a file will be generated. Similar operations should be avoided.
Create a temporary file instead and delete it after the test is completed.
No.
=> Create temporary files for reading or writing

datafusion/physical-plan/src/sorts/sort.rs
I can create an issue if needed.  However, this is a fairly minor comment-only change.
The previous description for this method was confusing, and I suspect a copy/paste error from `with_preserve_partitioning`
Comment is replaced
No change to code that can be tested.
No
=> Minor: fix comment on SortExec::with_fetch method

datafusion-examples/examples/dataframe_subquery.rs
Closes #8015.
make cargo run --example dataframe_subquery run
Use `out_ref_col` instead of `col`.
No.
=> Fix: dataframe_subquery example Optimizer rule `common_sub_expression_eliminate` failed

datafusion-cli/Cargo.lock, datafusion/core/Cargo.toml, datafusion/core/src/datasource/listing/url.rs
Closes #8009
Closes #7877
See ticket, the current behaviour is inconsistent and makes it impossible to address files with percent encoded paths. This was partially addressed in https://github.com/apache/arrow-datafusion/pull/3750 and works well for paths that don't contain percent encoded sequences, however, the behaviour is problematic for those that do.
This changes ListingTableUrl to treat the provided URLs as URL-encoded. The implications of this are:
* Users relying on percent encoding of non-URL safe characters, e.g. unicode, will need to do this themselves
* URLs containing percent encoded '%' characters, i.e. `%25` will now have a different but more consistent behaviour
* Paths containing percent encoded sequences of URL-safe characters will now work correctly
The ticket alluded …
=> Percent Decode URL Paths (#8009)

datafusion/physical-expr/src/expressions/column.rs, datafusion/physical-expr/src/expressions/no_op.rs, datafusion/physical-expr/src/sort_expr.rs
Closes #7879.
I checked all `plan_err` occurrences under `physical-expr`. Some `plan_err` are preserved as I think they are not an execution phase error, though they are generated in this phase...
The `plan_err`'s meaning is not clear to me. I believe those occurrences under `physical-expr` are used to express the plan is incorrect. While other places may use it to throw an error generated in the planning phase.
change some `plan_err` to `exec_err`
It's?
=> minor: change some plan_err to exec_err

datafusion/sql/src/expr/function.rs, datafusion/sql/tests/sql_integration.rs
Follow on to https://github.com/apache/arrow-datafusion/pull/7983 from @jackwener 
While reviewing https://github.com/apache/arrow-datafusion/pull/7983 I noticed there was a newly introduced field in SQLParser's `Function` struct that is ignored by DataFusion
1. If the unsupported syntax is included, return a not yet implemented error
Yes, with a new test
Will not silently accept (and ignore) unsupported syntax
=> Minor: error on unsupported RESPECT NULLs syntax

datafusion/physical-plan/src/aggregates/mod.rs, datafusion/physical-plan/src/aggregates/row_hash.rs
...  to decrease memory required for merging them later.
Closes #8003.
No
=> Break GroupedHashAggregateStream spill batch into smaller chunks

datafusion/physical-plan/src/lib.rs
=> Minor: Add implementation examples to ExecutionPlan::execute

datafusion/common/src/scalar.rs, datafusion/common/src/utils.rs, datafusion/physical-expr/src/aggregate/array_agg.rs, datafusion/physical-expr/src/aggregate/array_agg_distinct.rs, datafusion/physical-expr/src/array_expressions.rs
=> Minor: Extend wrap_into_list_array to accept multiple args

datafusion/physical-plan/src/aggregates/row_hash.rs
Closes #8001.
It is expected for this operator to register spillable consumer as it can spill
No
=> GroupedHashAggregateStream should register spillable consumer

datafusion/core/src/datasource/file_format/arrow.rs
Closes #6368
See issue
Adjust behaviour of infer Arrow IPC file schema from stream to infer the schema from the first Schema message in the filer, rather than from the footer of the file, thereby allowing us to only need to read as many bytes as we need to infer schema. Old behaviour was to read entire stream before inferring the schema.
Added  new unit tests.
=> Read only enough bytes to infer Arrow IPC file schema via stream

datafusion/optimizer/src/push_down_filter.rs
N/A
I was discussing Filter pushdown with @appletreeisyellow  and I wanted a reference that explained what DataFusion was doing, but I couldn't find one on the appropriate terminology,
Update the documentation that describes what Filter pushdown is and how it works
Existing tests
Docs
=> Minor: Improve documentation for Filter Pushdown

datafusion/physical-plan/src/lib.rs
N/A
While reviewing https://github.com/apache/arrow-datafusion/pull/8013 from @tustvold  and @comphead I noticed there were other parts of the documentation that could be improved to help people implement these interfaces. 
Update doc comments in `ExecutionPlan` to try and lower the barrier to implementing one (I think @tustvold 's examples are probably 90% of the value already)
Yes, by existing CI tests
Docs
=> Minor: Improve `ExecutionPlan` documentation

datafusion/common/src/error.rs, datafusion/core/tests/fuzz_cases/aggregate_fuzz.rs, datafusion/core/tests/fuzz_cases/window_fuzz.rs, datafusion/optimizer/src/simplify_expressions/utils.rs
Closes #.
Find these warnings after syncing my local toolchain
Some minor lint fixes
no
=> fix: clippy warnings from nightly rust 1.75

datafusion/physical-expr/src/array_expressions.rs
Closes #8024.
Main cleanup is to remove the duplicate compute of `compute array ndim`
=> Minor: Avoid recomputing compute_array_ndims in align_array_dimensions

datafusion/core/src/datasource/file_format/arrow.rs
Fix bug introduced in https://github.com/apache/arrow-datafusion/pull/7962
I accidentally merged  https://github.com/apache/arrow-datafusion/pull/7962 with a broken CI check (a newly added doc comment tripped up the `cargo doc` check
Fix the failures like: https://github.com/apache/arrow-datafusion/actions/runs/6737064526/job/18313740850
```
cargo fmt --all -- --check
Diff in /__w/arrow-datafusion/arrow-datafusion/datafusion/core/src/datasource/file_format/arrow.rs at line [10](https://github.com/apache/arrow-datafusion/actions/runs/6737064526/job/18313740850#step:5:11)5:
const ARROW_MAGIC: [u8; 6] = [b'A', b'R', b'R', b'O', b'W', b'1'];
const CONTINUATION_MARKER: [u8; 4] = [0xff; 4];
-/// Custom implementation of inferring schema. Should eventually be moved upstream to arrow-rs. 
+/// …
```
=> Minor: fix doc and fmt CI check

datafusion/core/src/datasource/file_format/arrow.rs, datafusion/core/tests/fuzz_cases/aggregate_fuzz.rs, datafusion/core/tests/fuzz_cases/window_fuzz.rs
Follow on to https://github.com/apache/arrow-datafusion/pull/8025
@crepererum  noticed we could remove a level of indirection in the `fuzz` integration test -- https://github.com/apache/arrow-datafusion/pull/8025#discussion_r1379810867
Remove unecessary cfg
existing coverage. you can see the tests still run:
```
cargo test --test fuzz
...
running 20 tests
test fuzz_cases::merge_fuzz::test_merge_2_no_overlap ... ok
test fuzz_cases::merge_fuzz::test_merge_2 ... ok
test fuzz_cases::merge_fuzz::test_merge_3 ... ok
test fuzz_cases::merge_fuzz::test_merge_3_gaps ... ok
test fuzz_cases::join_fuzz::test_inner_join_1k ... ok
test fuzz_cases::join_fuzz::test_right_join_1k ... ok
test fuzz_cases::join_fuzz::test_left_join_1k ... ok
test fuzz_cases::limit_fuzz::test_sort_topk_i32 ... ok
test …
```
=> Minor: remove uncessary #cfg test

datafusion/core/src/datasource/file_format/arrow.rs, datafusion/physical-plan/src/streaming.rs
Related to https://github.com/apache/arrow-datafusion/pull/8021 / https://github.com/apache/arrow-datafusion/issues/7994
I kept getting confused about the usecase of `PartitionStream`. I reviewed it as part of https://github.com/apache/arrow-datafusion/pull/8021 from @tustvold  and hope to encode some of my learning in this PR
Improve doc comments
N/A
=> Minor: Improve documentation for  `PartitionStream` and `StreamingTableExec`

datafusion/physical-plan/src/joins/nested_loop_join.rs, datafusion/physical-plan/src/lib.rs, datafusion/physical-plan/src/windows/mod.rs
N/A.
Improves comments for the `PartitionSearchMode` struct (make it clear it applies to both grouping and windowing).
Comment improvements.
Existing tests should pass.
No.
=> Improve comments for `PartitionSearchMode` struct

Cargo.toml, datafusion-cli/Cargo.lock, datafusion/physical-expr/Cargo.toml, datafusion/physical-expr/src/array_expressions.rs, datafusion/physical-expr/src/functions.rs
Part of #7988.
Find a general approach that avoid downcast Array, largely reduce the code generated size.
Main idea
* Build BooleanArray to know which inner array to replace.
* Manipulate array values with MutableArrayData
Pass existing test
`cargo bloat --filter 'array_replace'`
It significantly reduce to lower than 300B, compare to 150KB currently.
We can probably do the similar improvement for array_repeat / append / prepend
=> General approach for Array replace

datafusion/expr/src/expr.rs, datafusion/expr/src/operator.rs
N/A
The question came up on ASF Slack about what `Expr::IsNotFalse(e)` meant, and since it is subtle I had to look it up in the code, and thus I wanted to save myself (and future people) the trouble of doing that again
Update documentation about the various operator. 
doctests
Just Docs
=> Minor: improve documentation for IsNotNull, DISTINCT, etc

datafusion/expr/src/logical_plan/builder.rs, datafusion/sqllogictest/test_files/errors.slt
N/A
I hit this message when working on https://github.com/apache/arrow-datafusion/pull/8054 and I wanted more detail
Add specific data types in messages
Added a new test
=> Minor: improve error message by adding types to message

datafusion/expr/src/built_in_function.rs, datafusion/expr/src/signature.rs, datafusion/physical-expr/src/scalar_function.rs
A cleanup for https://github.com/apache/arrow-datafusion/issues/8045
Now built-in functions require a separate function to determine whether it supports 0 arg input during execution, however, this can also be determined using the function `TypeSignature`.
We can remove this redundant method, then the new function interface proposed in https://github.com/apache/arrow-datafusion/issues/8045 can be implemented more easily.
Use `TypeSignature` to determine whether a function supports 0 arg during execution
Unit test
No
=> Minor: Remove redundant BuiltinScalarFunction::supports_zero_argument()

datafusion/physical-plan/src/limit.rs, datafusion/sqllogictest/test_files/explain.slt, datafusion/sqllogictest/test_files/limit.slt, datafusion/sqllogictest/test_files/window.slt
Closes #8048.
While testing #8038, I ran into some incorrect results cases in `COUNT(*)` queries
from a `LIMIT`ed relation, related to [exact statistics](https://github.com/apache/arrow-datafusion/pull/7793).
The issue is due to use of the `fetch` value plus the `skip` value in
stats for `GlobalLimitExec` as the output stats `num_rows`, plus use of `Exact`
statistics for the output in cases where the input has `Inexact` statistics.
This commit reworks the cases in `GlobalLimitExec::statistics` to cap output
stats `num_rows` at the `fetch` value instead of the `fetch+skip` value.
Also, the following cases are modified:
- Output stats are copied from input stats when # of input rows is less than fetch rows, and `skip` is 0
- if (# of input rows - skip) <= fetch, output `num_rows` = input …
=> Fix incorrect results in COUNT(*) queries with LIMIT

datafusion/physical-plan/src/joins/hash_join.rs
Related to https://github.com/apache/arrow-datafusion/pull/8020
While reviewing https://github.com/apache/arrow-datafusion/pull/8020 I studied the join code and want to encode my learning as doc comments for both by future self and hopefully it will be useful to others as well
1. Update doc comments in `HashJoinStream`
By doc CI test
Better docstrings
=> Minor: Improve HashJoinStream docstrings

docs/source/contributor-guide/index.md
=> Fixing broken link

datafusion/expr/src/aggregate_function.rs, datafusion/expr/src/built_in_function.rs, datafusion/expr/src/window_function.rs, datafusion/sqllogictest/test_files/functions.slt
Closes #8082.
DataFusion use the `name()` method to generate suggestions for aggregate functions.
https://github.com/apache/arrow-datafusion/blob/f3c9009e50fdb5811c522bfb07ba29ac04cd1d22/datafusion/expr/src/function.rs#L91-L91
https://github.com/apache/arrow-datafusion/blob/f3c9009e50fdb5811c522bfb07ba29ac04cd1d22/datafusion/expr/src/aggregate_function.rs#L148-L152
We need to ensure that the `name()` method returns valid SQL function names.
Yes
No
=> fix: DataFusion suggests invalid functions

datafusion/optimizer/src/single_distinct_to_groupby.rs, datafusion/sqllogictest/test_files/groupby.slt, datafusion/sqllogictest/test_files/joins.slt, datafusion/sqllogictest/test_files/tpch/q16.slt.part
Closes #8086
Previously, we used `projection` to make the schema consistent before and after optimization. Now avoid the use of `proejction` by using `alias` directly in `aggregate`.
The deleted codes are all related to `proejction`.
=> Minor: remove unnecessary projection in `single_distinct_to_group_by` rule

Cargo.toml, benchmarks/Cargo.toml, datafusion-cli/Cargo.lock, datafusion-examples/Cargo.toml, datafusion/common/Cargo.toml, datafusion/core/Cargo.toml, datafusion/proto/Cargo.toml, datafusion/wasmtest/Cargo.toml
N/A
Simplify the process of upgrading to new versions of arrow-rs, object_store, and parquet crates.
Use workspace versions instead of duplicating the version numbers.
No
=> minor: Remove duplicate version numbers for arrow, object_store, and parquet dependencies

datafusion/proto/src/logical_plan/from_proto.rs
=> fix: add  encode/decode to protobuf encoding

datafusion/optimizer/src/decorrelate.rs, datafusion/optimizer/src/single_distinct_to_groupby.rs, datafusion/sql/src/select.rs
Follow on to https://github.com/apache/arrow-datafusion/pull/8061
I noticed during review of https://github.com/apache/arrow-datafusion/pull/8061 that we could use `Expr::alias` in a few places to make the code easier to work with
Use `Expr::alias` a few places
=> Minor: use `Expr::alias` in a few places to make the code more concise

datafusion/expr/src/built_in_function.rs, datafusion/expr/src/expr_schema.rs, datafusion/expr/src/type_coercion/functions.rs, datafusion/physical-expr/src/functions.rs
A small refactor for https://github.com/apache/arrow-datafusion/issues/8045
#8045 proposed a new trait-based way to define builtin functions:
``` rust
pub trait FunctionImplementation {
//...
fn return_type(&self, arg_types: &[DataType]) -> Result<DataType>;
//...
}
```
`BuiltinScalarFunction::return_type()` will do an extra step inside: validating input arg types against functions's `Signature`
This signature-checking step will also be needed if we migrate functions to `ScalarUDF`-based implementation, so separate this step out.
Separate the signature-checking step inside `BuiltinScalarFunction::return_type()` into planning
No
=> Minor: Cleanup BuiltinScalarFunction::return_type()

datafusion/sql/src/statement.rs, datafusion/sqllogictest/test_files/update.slt
N/A.
Support statements like `UPDATE foo AS f `.
> When an alias is provided, it completely hides the actual name of the table. For example, given UPDATE foo AS f, the remainder of the UPDATE statement must refer to this table as f not foo.
Ref: [PostgreSQL UPDATE SQL Commands](https://www.postgresql.org/docs/current/sql-update.html)
If there is an alias for the target table, use it to properly qualify the column names from the target table.
Yes
No
=> feat: support target table alias in update statement

datafusion/common/src/cast.rs
=> Minor: Simlify downcast functions in cast.rs.

datafusion/physical-plan/src/joins/hash_join_utils.rs
N/A
Improve the document format of JoinHashMap
N/A
doctests
Just Docs
=> Minor: Improve the document format of JoinHashMap

datafusion/expr/src/expr_fn.rs, datafusion/proto/src/logical_plan/from_proto.rs
Closes #8098.
Suggested changes were made to catch most cases of datafusion::ScalarFunction
Added the additional cases for `ScalarFunction::ArrowTypeof`, `ScalarFunction::ToTimestamp`, 'ScalarFunction::Flatten'
Test suite seemed to pass.
Not entirely sure of this. My first commit to this project so I am still getting up to speed.
None that I am aware of. Same reasoning as above answer.
=> Support remaining functions in protobuf serialization, add `expr_fn` for `StructFunction`

datafusion/physical-expr/src/datetime_expressions.rs, datafusion/physical-expr/src/functions.rs, datafusion/physical-expr/src/math_expressions.rs
Cleanup for #8045 
In current implementation, some function tries to generate input type specific physical expressions in
https://github.com/apache/arrow-datafusion/blob/308c35404939ed39e4e398054d6fc78c89817109/datafusion/physical-expr/src/functions.rs#L75-L204
However, this can be done inside function implementation like most other functions did, this PR would like to unify the implementation approach
Move input-type-specific `BuiltinScalarFunction` physical expression creation to inside function implementation
No
=> Minor: Cleanup BuiltinScalarFunction's phys-expr creation

datafusion/core/src/datasource/avro_to_arrow/arrow_array_reader.rs, datafusion/physical-expr/src/array_expressions.rs
One issue from #7988  `array_append` && `array_prepend`.
=> rewrite `array_append/array_prepend` to remove deplicate codes 

datafusion/core/src/datasource/avro_to_arrow/arrow_array_reader.rs, datafusion/expr/src/built_in_function.rs, datafusion/expr/src/expr_fn.rs, datafusion/physical-expr/src/array_expressions.rs, datafusion/physical-expr/src/functions.rs, datafusion/proto/proto/datafusion.proto, datafusion/proto/src/generated/pbjson.rs, datafusion/proto/src/generated/prost.rs, datafusion/proto/src/logical_plan/from_proto.rs, datafusion/proto/src/logical_plan/to_proto.rs, datafusion/sqllogictest/test_files/array.slt, docs/source/user-guide/expressions.md
Closes #6978 
Using RowConverter to implement `array_intersect`, no duplicate code for different data types,
=> Implementation of `array_intersect`

datafusion/core/src/execution/context/parquet.rs
NA
On the current main branch, some temporary testing files didn't get cleaned up after testing
```
> cargo test read_from_different_file_extension
> git status
Untracked files:
(use "git add <file>..." to include in what will be committed)
datafusion/core/output1.parquet
datafusion/core/output2.parquet.snappy
datafusion/core/output3.parquet.snappy.parquet
```
Create those files under temporary directory, make sure they're cleaned up automatically afterwards
No
=> Minor: Fix temporary files created but not deleted during testing

datafusion/core/src/physical_optimizer/enforce_distribution.rs, datafusion/core/src/physical_optimizer/enforce_sorting.rs, datafusion/core/src/physical_optimizer/replace_with_order_preserving_variants.rs, datafusion/core/src/physical_optimizer/test_utils.rs, datafusion/core/tests/fuzz_cases/sort_preserving_repartition_fuzz.rs, datafusion/physical-plan/src/joins/hash_join_utils.rs, datafusion/physical-plan/src/repartition/mod.rs
Closes https://github.com/apache/arrow-datafusion/issues/8043
We encountered  problem is our downstream tests that `RepartitionExec` was trying to preserve an order even when there is no order to preserve.
This was because one codepath (`RepartitionExec::new_with_children`) it set the `preserve_order` flag to true when it creates a new `RepartitionExec` even if the new child had no order to preserve. During execution, this cause the code to try and merge a stream with no sort exprs, which causes an internal error
1. Update RepartitionExec::with_preserve_order to take existing sortedness into account
2. Improve documentation
3. add test
Yes, though I am not thrilled with the test (I will comment inline)
=> Fix: Do not try and preserve order when there is no order to preserve in RepartitionExec

datafusion/common/src/stats.rs, datafusion/core/tests/sql/explain_analyze.rs, datafusion/sqllogictest/test_files/explain.slt
Closes https://github.com/apache/arrow-datafusion/issues/8110
Show column statistics in the explain
```SQL
explain select * from t1 where time <= to_timestamp(350);
+---------------+---------------------------------------------------------------------------------------------------+
| plan_type     | plan                                                                                              |
+---------------+---------------------------------------------------------------------------------------------------+
| logical_plan  | Filter: t1.time <= TimestampNanosecond(350000000000, None)                                        |
|               |   TableScan: t1 projection=[state, city, min_temp, area, time]                                    |
| physical_plan | CoalesceBatchesExec: …
```
=> feat: add column statistics into explain

datafusion/substrait/src/logical_plan/consumer.rs, datafusion/substrait/src/logical_plan/producer.rs, datafusion/substrait/tests/cases/roundtrip_logical_plan.rs
Closes #8087.
Support for IS NULL and IS NOT NULL in Substrait producer and consumer. Also includes basic tests for this functionality.
Yes
No
=> Add subtrait support for `IS NULL` and `IS NOT NULL`

datafusion/core/src/datasource/listing/helpers.rs, datafusion/core/src/physical_planner.rs, datafusion/core/tests/dataframe/mod.rs, datafusion/expr/src/expr.rs, datafusion/expr/src/expr_fn.rs, datafusion/expr/src/expr_schema.rs, datafusion/expr/src/logical_plan/builder.rs, datafusion/expr/src/tree_node/expr.rs, datafusion/expr/src/utils.rs, datafusion/optimizer/src/analyzer/count_wildcard_rule.rs, datafusion/optimizer/src/analyzer/inline_table_scan.rs, datafusion/optimizer/src/common_subexpr_eliminate.rs, datafusion/optimizer/src/push_down_filter.rs, datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs, datafusion/proto/proto/datafusion.proto, datafusion/proto/src/generated/pbjson.rs, datafusion/proto/src/generated/prost.rs, datafusion/proto/src/logical_plan/from_proto.rs, datafusion/proto/src/logical_plan/to_proto.rs, datafusion/proto/tests/cases/roundtrip_logical_plan.rs, datafusion/sql/src/expr/function.rs
Closes https://github.com/apache/arrow-datafusion/issues/8104
Per https://github.com/apache/arrow-datafusion/issues/8104
As @waynexia  points out on https://github.com/apache/arrow-datafusion/issues/8008#issuecomment-1794332809, having `Expr::Wildcard` and `Expr::QualifiedWildcard` is confusing as they are both representing the same basic pattern, `*`
Specifically, I think it could make subtle bugs more likely (e.g. using `Expr::Wildcard` instead of using `Expr::QualifiedWildcard`)
1. Change `Expr::Wildcard` to `ExprWildcard { qualifier: Option<String> }` and remove `Expr::QualifiedWildcard`
2. Update code
3. Add LogicalPlan serialization support
Yes, users can't use `Expr::Wildcard` anymore -- they either have to use `Expr::Wildcard { qualifier: None}` or `wildcard()`
=> Combine `Expr::Wildcard` and `Wxpr::QualifiedWildcard`, add `wildcard()` expr fn

datafusion/common/src/dfschema.rs
Closes #8131.
I got stuck figuring this out, and noticed there was very little documentation here.
I don't think I yet understand enough about DFSchema to fully document it. For now I'm mostly using unqualified schemas. Therefore, I'm not trying to complete #7724 with this PR.
Adds some initial examples.
Examples run with doc tests.
=> docs: show creation of DFSchema

datafusion/substrait/src/logical_plan/consumer.rs, datafusion/substrait/src/logical_plan/producer.rs, datafusion/substrait/tests/cases/roundtrip_logical_plan.rs
Closes #.
Support to serialize and deserialize UDAF in substrait. Unlike extension plan, UDAF has more information in substrait proto, it's wrapped in Aggregate Rex so we only need to implement the `name` -> `impl` part.
Add support of UDAF to substrait logical producer and consumer
Yes.
=> feat: support UDAF in substrait producer/consumer

README.md, docs/source/contributor-guide/communication.md, docs/source/index.rst
Part of https://github.com/apache/arrow-datafusion/issues/7013
I think it is not clear from the documentation site how to find Slack/Discord as it is buried under a link to the community page.
Also, while trying to update that text, I tried to explain better the differences between Discord and ASF Slack as well as remove the outdated "weekly syncs" that haven't happened in 6 months. 
1. Update documentation to make communication easier to find
2. Update communication page to better reflect current realities
N/A
Doc updates
=> Improve documentation site to make it easier to find communication on Slack/Discord

datafusion/physical-expr/src/partitioning.rs
=> Fix typo in partitioning.rs

datafusion/physical-expr/src/array_expressions.rs
Follow up on https://github.com/apache/arrow-datafusion/pull/8108#pullrequestreview-1725755288
=> Avoid concat in `array_append`

datafusion/physical-plan/src/lib.rs
Part of https://github.com/apache/arrow-datafusion/issues/8120
I did not properly set `ExecutionPlan::equivalence_properties` for one of our extension nodes, which took me a non trivial time to debug. 
Add doc comments to `ExecutionPlan::equivalence_properties`
By doc test
=> Minor: Document `ExecutionPlan::equivalence_properties` more thoroughly

datafusion/physical-plan/src/joins/hash_join.rs, datafusion/physical-plan/src/joins/hash_join_utils.rs
Related to https://github.com/apache/arrow-datafusion/issues/8130
I am going through this code to understand what is happening, and one thing I think would help would be to use names to refer to fields rather than `data.0`, `data.1`, and that could be commented
1. Make fields of `JoinData` non pub
2. Add doc comments
3. Make `LeftJoinData` a struct with named fields and accessors
Existing tests
No, this is entirely internal code refactoring
=> Minor: Encapsulate `LeftJoinData` into a struct (rather than anonymous enum) and add comments

datafusion/sql/src/statement.rs, datafusion/sql/tests/sql_integration.rs, datafusion/sqllogictest/test_files/insert.slt, datafusion/sqllogictest/test_files/insert_to_external.slt
Closes #8091.
If user does not provide a value for certain columns during insertion, NULL will be filled as their default values.
Yes
No
=> feat: fill missing values with NULLs while inserting

datafusion/physical-expr/src/aggregate/sum.rs, datafusion/physical-expr/src/aggregate/sum_distinct.rs
=> Introduce return type for aggregate sum

datafusion/core/src/datasource/listing/helpers.rs, datafusion/core/src/execution/context/mod.rs, datafusion/core/src/physical_planner.rs, datafusion/expr/src/expr.rs, datafusion/expr/src/expr_schema.rs, datafusion/expr/src/udaf.rs, datafusion/expr/src/udf.rs, datafusion/expr/src/udwf.rs, datafusion/expr/src/window_function.rs, datafusion/optimizer/src/analyzer/type_coercion.rs, datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs, datafusion/physical-expr/src/functions.rs, datafusion/physical-expr/src/scalar_function.rs, datafusion/physical-expr/src/udf.rs, datafusion/physical-plan/src/udaf.rs, datafusion/physical-plan/src/windows/mod.rs, datafusion/proto/src/logical_plan/to_proto.rs, datafusion/proto/src/physical_plan/from_proto.rs, datafusion/proto/src/physical_plan/to_proto.rs, datafusion/proto/tests/cases/roundtrip_logical_plan.rs, datafusion/proto/tests/cases/roundtrip_physical_plan.rs
Part of https://github.com/apache/arrow-datafusion/issues/8045
Closes https://github.com/apache/arrow-datafusion/pull/8039
Rationale is that we can add new features to ScalarUDF to bring it up to parity with BuiltInScalarFunction (such as adding `montonicity`) in a backwards compatible way if the fields are not pub. If the fields
In order to maintain parity with the other user defined APIs (aggregates and window functions) and to prepare them for an eventual consolidation as well, apply the same to `AggregateUDF` and `WindowUDF`
see https://github.com/apache/arrow-datafusion/issues/8045 for more details
Make all fields of ScalarUDF private and add accessors.
2. Change return_type to just call the function rather than passing back a function implementation
yes, by existing tests
yes, users …
=> Make fields of `ScalarUDF` , `AggregateUDF` and `WindowUDF` non `pub`

datafusion/physical-plan/src/joins/hash_join.rs, datafusion/physical-plan/src/joins/hash_join_utils.rs
Part of https://github.com/apache/arrow-datafusion/issues/8130
While working on https://github.com/apache/arrow-datafusion/issues/8130 I am reading the code carefully, and I want to encode my knowledge into comments
Update some example documentation  to make it clearer what is going on
Exisitng tets
No, just comments
=> Minor: Update JoinHashMap comment example to make it clearer

datafusion/physical-plan/src/aggregates/mod.rs, datafusion/physical-plan/src/windows/mod.rs
Closes #.
There are some functions that return `Result` unnecessarily. This PR changes return type from `Result<T>` to `T` for these functions.
=> [MINOR]: Remove unused Results

datafusion/core/src/physical_optimizer/join_selection.rs, datafusion/physical-plan/src/filter.rs
This is part of https://github.com/apache/arrow-datafusion/issues/8078
I am trying to clean up the existing code's use of `Precision` so that as we change it (as described on https://github.com/apache/arrow-datafusion/issues/8078) it will be easier to do so
Call `into_exact` rather than reimplementing the same logic
=> Minor: simplify filter statistics code

datafusion/expr/src/built_in_function.rs, datafusion/physical-expr/src/array_expressions.rs, datafusion/sqllogictest/test_files/array.slt
=> Replace macro with function for `array_position` and `array_positions`

datafusion-examples/examples/simple_udaf.rs, datafusion-examples/examples/simple_udwf.rs, docs/source/library-user-guide/adding-udfs.md
Closes #7307 .
Add doc for user-defined window/aggregate function
=>  Add Library Guide for User Defined Functions: Window/Aggregate

datafusion/core/src/datasource/stream.rs
Closes #.
Adds some more docs as requested by @alamb on https://github.com/apache/arrow-datafusion/pull/8021#discussion_r1394150594
=> Add more stream docs

datafusion/expr/src/built_in_function.rs, datafusion/expr/src/expr_fn.rs, datafusion/physical-expr/src/array_expressions.rs, datafusion/physical-expr/src/functions.rs, datafusion/proto/proto/datafusion.proto, datafusion/proto/src/generated/pbjson.rs, datafusion/proto/src/generated/prost.rs, datafusion/proto/src/logical_plan/from_proto.rs, datafusion/proto/src/logical_plan/to_proto.rs, datafusion/sqllogictest/test_files/array.slt, docs/source/user-guide/expressions.md, docs/source/user-guide/sql/scalar_functions.md
=> Implement func `array_pop_front`

datafusion/optimizer/src/push_down_projection.rs
Resolves https://github.com/apache/arrow-datafusion/issues/8223
We found a bug while upgrading IOx to use the latest datafusion
Some of our queries began failing like this:
> "Optimizer rule 'push_down_projection' failed"
The regression was introduced in https://github.com/apache/arrow-datafusion/pull/7981 and is related to columns with periods in their names
1. Back out an unecessary change from https://github.com/apache/arrow-datafusion/pull/7981
2. Add test coverage
yes
bug fix
=> fix regression in the use of name in ProjectionPushdown

datafusion/core/src/physical_optimizer/enforce_distribution.rs, datafusion/core/src/physical_optimizer/replace_with_order_preserving_variants.rs
Closes #.
I have recognized that in some of the tests under `enforce_distribution.rs` and `replace_with_order_preserving_variant.rs`. Column names and column indices are not consistent with the schema. Since during these test we do not execute these plans, inconsistencies didn't arise. However, if we were to run those plans, we would get error.
This PR fixes, column name and indices in those tests so that they refer to valid fields in the schema.
Existing tests should work.
=> [MINOR]: Fix column indices in the planning tests

datafusion/core/src/physical_planner.rs
No particular issue
Minor code cleanup found while looking into #7647 but which could be useful before I get a proper solution for that ticket.
Tested locally with `cargo test`
It's just a minor code cleanup, nothing user-facing.
=> Remove unnecessary reassignment

Cargo.toml, datafusion-cli/Cargo.lock, datafusion/physical-expr/Cargo.toml, datafusion/physical-plan/Cargo.toml
\-
This is the fixed version of #8184.
\-
\-
\-
=> Update itertools requirement from 0.11 to 0.12

datafusion/common/src/scalar.rs
Closes #8220
I found this was needed for using literal fixed size lists in DataFusion physical expressions.
Implements `eq_array` and `to_array_of_size` for `ScalarValue::FixedSizeList`.
A new unit test is added for each function.
I've updated the documentation to reflect that this is now supported.
=> feat: to_array_of_size for ScalarValue::FixedSizeList

datafusion/proto/proto/datafusion.proto, datafusion/proto/src/generated/pbjson.rs, datafusion/proto/src/generated/prost.rs, datafusion/proto/src/logical_plan/from_proto.rs, datafusion/proto/src/logical_plan/to_proto.rs, datafusion/proto/tests/cases/roundtrip_logical_plan.rs
Closes #8224.
This scalar type was missing from the protobuf serialization. Adding it for completeness.
Updates protobuf to add a FixedSizeList scalar variant. I've re-used the same serialization mechanism as list, to minimize the changes needed.
I've added a roundtrip test, which I think should be sufficient. I'm not deeply familiar with the proto module codebase, so if you have additional suggestions for tests, I am all ears.
This should be a backwards compatible change to the protobuf messages.
=> feat: roundtrip FixedSizeList Scalar to protobuf

datafusion/expr/src/utils.rs, datafusion/sqllogictest/test_files/joins.slt
part of https://github.com/apache/arrow-datafusion/issues/8147
The join filters all use the [ExtractEquijoinPredicate](https://docs.rs/datafusion/latest/datafusion/optimizer/extract_equijoin_predicate/struct.ExtractEquijoinPredicate.html) optimizer to make the eq expression the key for the join on, and then the presence of `join on` determines whether to use `HashJoinExec` or `NestedJoinExec`. In this process, `can _hash` function determines whether an expression type can be hashed, but currently this function does not support timestamps with timezone.
Modified the `can_hash` function to support timestamps with timezone.
No
=> fix: Timestamp with timezone not considered `join on`

datafusion/expr/src/logical_plan/plan.rs, datafusion/optimizer/src/single_distinct_to_groupby.rs, datafusion/sqllogictest/test_files/aggregate.slt
Closes #8247.
In our project using datafusion, we have a specific optimizer rule that combines an aggregation into a different node.
We noticed that when creating the results using `RecordBatch::try_new(...)` using the schmea of the aggregation, it fails as it expects the columns to be non-nullable if the input column is non-nullable in case of grouping sets, although naturally all rows that do not belong to the "current" grouping set are null for that column.
So, this PR will force the field created from a grouping set to be nullable.
Added a unit test.
No.
=> Minor: Make schema of grouping set columns nullable

datafusion/optimizer/src/simplify_expressions/guarantees.rs
Closes #8255.
Mostly, I want to be able to simplify expressions involving nested column references.
Added one new test case for this.
=> feat: support simplifying BinaryExpr with arbitrary guarantees in GuaranteeRewriter

datafusion-cli/src/exec.rs, datafusion/core/src/datasource/listing/url.rs
Closes https://github.com/apache/arrow-datafusion/issues/8277
Split out from #8007 and building on top of #8012. Instead of canonicalizing the path before conversion to a URL, it instead concatenates the working directory and relies on the URL crate's built in path resolution logic to reconcile relative paths. This allows creating ListingTableUrl to paths that don't currently exist.
Users can now create external tables referencing path that don't (yet) exist
=> Don't Canonicalize Filesystem Paths in ListingTableUrl / support new external tables for files that do not (yet) exist

datafusion/sqllogictest/test_files/insert.slt
Related to https://github.com/apache/arrow-datafusion/issues/8277
Will fail until  https://github.com/apache/arrow-datafusion/pull/8014 is merged
End to end sql tests are important
Add an end to end test for https://github.com/apache/arrow-datafusion/issues/8277
All tests
No
=> Minor: Add sql level test for inserting into non-existent directory

datafusion/physical-expr/src/array_expressions.rs
fix `array_has/array_has_all/array_has_any` in #7988 
`datafusion-cli` binary size seems to decrease by about 60~KB
=> Replace `array_has/array_has_all/array_has_any` macro to remove duplicate code

datafusion/physical-plan/src/projection.rs, datafusion/sqllogictest/src/test_context.rs, datafusion/sqllogictest/test_files/metadata.slt
Closes https://github.com/apache/arrow-datafusion/issues/8285
Bug fix
What was happening is that the input to a join has metadata on one side, but not the other. When the inputs were reordered then metadata was not properly reordered as well
Specifically:
```
OutputRequirementExec
ProjectionExec: expr=[id@0 as id]
HashJoinExec: mode=Partitioned, join_type=Inner, on=[(id@0, id@0)]
AggregateExec: mode=FinalPartitioned, gby=[id@0 as id], aggr=[]  <--******** this does not have metadata
AggregateExec: mode=Partial, gby=[id@0 as id], aggr=[]
UnionExec
MemoryExec: partitions=1, partition_sizes=[1]
MemoryExec: partitions=1, partition_sizes=[1]
MemoryExec: partitions=1, partition_sizes=[1]                    <--******** this has metadata
```
So the output schema looks like:
```
id (metadata) …
```
=> Fix bug in field level metadata matching code

datafusion/core/src/physical_optimizer/enforce_sorting.rs, datafusion/physical-plan/src/insert.rs, datafusion/sqllogictest/test_files/select.slt
Closes #.
In some of the plans, there are unnecessary `SortExec`, where ordered fields are not used (exist at the final plan.) This PR remove `SortExec`s for these cases from the plan.
=> [MINOR]: Remove unecessary orderings from the final plan

datafusion/expr/src/window_function.rs, datafusion/sqllogictest/test_files/window.slt
Closes #7639.
At this moment, while logical plan building, return type of `ntile` considered to be `UInt32`, and physical expression of `ntile` returns `UInt64` -- this leads to incompatible schemas of created memory table and record batches on insertion.
FWIW: another schema incompatibility left (non breaking in case of CTAS, though) -- nullability of output fields, should be fixed in #7638 
Return type of `ntile` logical expression is `UInt64` now
Unit test for return type & minimal reproducer from the issue in sqllogictests
Return type of `ntile` logical expression is `UInt64` now
=> consistent logical & physical `NTILE` return types

datafusion/expr/src/built_in_function.rs, datafusion/physical-expr/src/array_expressions.rs, datafusion/sql/src/expr/value.rs, datafusion/sql/tests/sql_integration.rs, datafusion/sqllogictest/test_files/aggregate.slt, datafusion/sqllogictest/test_files/array.slt
Closes #8181.
for `array_union`:
```
array_union([], []) = []
array_union([], null) = []
array_union(null, []) = []
array_union(null, null) = null
```
for `array_except`:
```
array_except([], []) = []
array_except([], null) = []
array_except(null, []) = null
array_except(null, null) = null
```
for `array_intersect`:
```
array_intersect([], []) = []
array_intersect([], null) = []
array_intersect(null, []) = []
array_intersect(null, null) = null
```
=> make `array_union`/`array_except`/`array_intersect` handle empty/null arrays rightly

datafusion/core/src/execution/context/mod.rs, datafusion/core/src/execution/context/parquet.rs
=> improve file path validation when reading parquet

benchmarks/src/sort.rs, benchmarks/src/tpch/run.rs, benchmarks/src/util/options.rs
Related to discussion in https://github.com/apache/arrow-datafusion/issues/7001
By default, the benchmarks have been running with two partitions (i.e., concurrency of two), which is unrealistic given the number of cores on modern laptops. This PR defaults to num cores instead. We can still override this and explicitly set the number of partitions.
This is the difference this makes for me (Threadripper with 24 cores).
```
┏━━━━━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Query        ┃      main ┃ bench-default-partitions ┃        Change ┃
┡━━━━━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ QQuery 1     │  655.23ms │                 283.37ms │ +2.31x faster │
│ QQuery 2     │  148.53ms │                 160.08ms │  1.08x slower │
│ QQuery 3 …
```
=> [Benchmarks] Make `partitions` default to number of cores instead of 2

datafusion/common/src/scalar.rs, datafusion/sqllogictest/test_files/explain.slt
=> Fix Display for List

datafusion/core/src/datasource/default_table_source.rs, datafusion/core/src/datasource/memory.rs, datafusion/core/src/datasource/provider.rs, datafusion/core/src/execution/context/mod.rs, datafusion/expr/src/logical_plan/ddl.rs, datafusion/expr/src/logical_plan/plan.rs, datafusion/expr/src/table_source.rs, datafusion/sql/src/planner.rs, datafusion/sql/src/query.rs, datafusion/sql/src/statement.rs, datafusion/sqllogictest/test_files/insert.slt
This is a continuation of #8146.
Currently, we only support NULL as the default value for columns. 
This pr will enable users to customize the default value while creating a table.
For example:
```sh
DataFusion CLI v33.0.0
❯ create table t(a int, b int default 100);
0 rows in set. Query took 0.004 seconds.
❯ insert into t(a) values(1);
+-------+
| count |
+-------+
| 1     |
+-------+
1 row in set. Query took 0.007 seconds.
❯ select * from t;
+---+-----+
| a | b   |
+---+-----+
| 1 | 100 |
+---+-----+
1 row in set. Query took 0.006 seconds.
```
- Parsing column default values when constructing the `CreateMemoryTable` plan.
- The default value of a column can be obtained from the `TableSource`.
- Fill default value if a column value is not specified during inserting.
- Implement it on …
=> feat: support customizing column default values for inserting

datafusion/common/src/scalar.rs, datafusion/common/src/utils.rs, datafusion/proto/proto/datafusion.proto, datafusion/proto/src/generated/pbjson.rs, datafusion/proto/src/generated/prost.rs, datafusion/proto/src/logical_plan/from_proto.rs, datafusion/proto/src/logical_plan/to_proto.rs, datafusion/proto/tests/cases/roundtrip_logical_plan.rs, datafusion/sql/src/expr/arrow_cast.rs, datafusion/sqllogictest/test_files/arrow_typeof.slt
Closes #.
It is hard to test `LargeList` in sqllogictest #8121, the convenient idea is to use `arrow_cast()` instead of `make_array`
- support `LargeList` for `arrow_cast`
- support `ScalarValue::LargeList`
- support `ScalarValue::new_large_list`
- support `LargeList` for protobuf
=> support `LargeList` for `arrow_cast`, support `ScalarValue::LargeList`

datafusion/sqllogictest/README.md, docs/source/contributor-guide/index.md
None
The crate was moved so the link needs to be updated
The new link shouldn't got to the "moved" document anymore.
=> Fix sqllogictests link in contributor-guide/index.md

datafusion/core/src/physical_optimizer/projection_pushdown.rs, datafusion/physical-plan/src/streaming.rs
Closes #.
`ProjectionExec` with its input `StreamingTableExec` can be merged into a single `StreamingTableExec`, provided there is no evaluation or aliasing in `ProjectionExec`.
`projection_pushdown` rule for physical plans is extended with `StreamingTableExec`.
Yes.
=> Projection Pushdown over StreamingTableExec

docs/source/library-user-guide/using-the-dataframe-api.md
Signed-off-by: veeupup <code@tanweime.com>
Closes #7305
=> Library Guide: Add Using the DataFrame API

datafusion/core/src/physical_planner.rs, datafusion/core/tests/dataframe/mod.rs
Part of https://github.com/apache/arrow-datafusion/issues/8194
Follow on to https://github.com/apache/arrow-datafusion/pull/8316 I noticed that one of the test was actually using the dataframe API, so it should also be put in the dataframe tests
Restore one tests into the dataframe tests
They are all tests
=> Minor: Add DataFrame test

datafusion/core/src/physical_planner.rs, datafusion/expr/src/expr.rs, datafusion/substrait/src/logical_plan/producer.rs
Related to https://github.com/apache/arrow-datafusion/pull/8258
While integrating the change from https://github.com/apache/arrow-datafusion/pull/8258 downstream in IOx, I found it would have been very helpful to have `fun.name()` available and I think it makes the code more consise
Add `expr::ScalarFunction::name()`
Existing tests
=> Minor: Make it easier to work with Expr::ScalarFunction

datafusion/expr/src/built_in_function.rs
Part of https://github.com/apache/arrow-datafusion/issues/8348
I want to have ScalarUDF support aliases, and thus I want to have aliases handled as part of Expr::ScalarFunction rather than a free function. By refactoring `BuiltInScalarFunction::alias` it will make it easier to handle uniformly.
1. Make `BuiltInScalarFunction::alias` a function 
=> Minor: Make `BuiltInScalarFunction::alias` a method

datafusion/expr/src/type_coercion/binary.rs, datafusion/sqllogictest/test_files/scalar.slt
Ref #8302 
There are two reason why I want to support this coercion.
One is that `LargeUtf8` to `Timestamp` is supported in `coerced_from`. We need the same so I can replace it with `string_temporal_coercion`
Second is that comment in `string_temporal_coercion` mentioned `LargeUtf8` but the code itself does not.
I didnt find coercion test in slt. I put it in `scalar.slt` for now.
=> Support LargeUtf8 to Temporal Coercion

datafusion/core/src/datasource/listing/helpers.rs, datafusion/core/src/physical_planner.rs, datafusion/expr/src/aggregate_function.rs, datafusion/expr/src/expr.rs, datafusion/expr/src/expr_schema.rs, datafusion/expr/src/tree_node/expr.rs, datafusion/expr/src/udaf.rs, datafusion/expr/src/utils.rs, datafusion/optimizer/src/analyzer/count_wildcard_rule.rs, datafusion/optimizer/src/analyzer/type_coercion.rs, datafusion/optimizer/src/common_subexpr_eliminate.rs, datafusion/optimizer/src/decorrelate.rs, datafusion/optimizer/src/push_down_filter.rs, datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs, datafusion/optimizer/src/single_distinct_to_groupby.rs, datafusion/proto/src/logical_plan/from_proto.rs, datafusion/proto/src/logical_plan/to_proto.rs, datafusion/proto/tests/cases/roundtrip_logical_plan.rs, datafusion/sql/src/expr/function.rs, datafusion/sql/src/expr/mod.rs, datafusion/sql/src/select.rs, datafusion/substrait/src/logical_plan/consumer.rs, datafusion/substrait/src/logical_plan/producer.rs
=> Refactor aggregate function handling

datafusion/physical-expr/src/datetime_expressions.rs, docs/source/user-guide/sql/scalar_functions.md
Closes #8336
Closes #7958
Declared limits for `to_timestamp`, `to_timestamp_nanos` functions to prevent overflows. Its been agreed in https://github.com/apache/arrow-datafusion/issues/8336#issuecomment-1830063184 to use `to_timestamp_seconds` function for values between `1677-09-21T00:12:44.0` and `2262-04-11T23:47:16.0`
No need
No
=> Document timestamp input limits

datafusion/expr/src/window_function.rs, datafusion/physical-expr/src/window/ntile.rs, datafusion/physical-plan/src/windows/mod.rs, datafusion/sqllogictest/test_files/window.slt
Closes #8284
fix #8284
Add parameter type checking using `Signature`, 
before
```
❯ select ntile('1') OVER(ORDER BY a) from t1;
Internal error: Cannot convert Utf8("1") to i64.
This was likely caused by a bug in DataFusion's code and we would welcome that you file an bug report in our issue tracker
❯ select ntile([]) OVER(ORDER BY a) from t1;
Internal error: Cannot convert List([NullArray(0)]) to i64.
This was likely caused by a bug in DataFusion's code and we would welcome that you file an bug report in our issue tracker
```
after 
```
❯ select ntile([]) OVER(ORDER BY a) from t1;
Error during planning: No function matches the given name and argument types 'NTILE(List(Field { name: "item", data_type: Null, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }))'. You might …
```
=> fix: make `ntile` work in some corner cases

datafusion/physical-expr/src/array_expressions.rs
=> Minor: Refactor array_union function to use a generic union_arrays function

datafusion/expr/src/expr_schema.rs, datafusion/physical-expr/src/planner.rs, datafusion/proto/src/logical_plan/to_proto.rs
=> Minor: Refactor function argument handling in `ScalarFunctionDefinition`

datafusion/core/tests/path_partition.rs, datafusion/physical-plan/src/aggregates/group_values/row.rs, datafusion/physical-plan/src/aggregates/mod.rs, datafusion/physical-plan/src/aggregates/row_hash.rs, datafusion/sqllogictest/test_files/aggregate.slt
Closes #7647.
From the ticket:
Given that group keys inherently have few repeated values, especially when grouping on a single column, the use of dictionary encoding is unlikely to be yielding significant returns
Now `AggregateExec` includes `original_schema` which allows us to differentiate between original schema with dictionaries in place and `schema` where we materialize them as their value types.
Tested locally with `cargo test`
The main user-facing change will be in different type returned for group keys using dictionaries.
=> Materialize dictionaries in group keys

benchmarks/compare.py
Closes #8390.
Explained in issue.
Adding a Benchmark summary at the end of compare table like this:
```
Comparing main and test
Benchmark parquet.json
┏━━━━━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Query        ┃      main ┃      test ┃        Change ┃
┡━━━━━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ QSelective-… │ 1297.07ms │ 1246.13ms │     no change │
│ filter:      │           │           │               │
│ pushdown_fi… │           │           │               │
│ reorder_fil… │           │           │               │
│ page_index=… │           │           │               │
│ QSelective-… │ 2213.53ms │ 2207.27ms │     no change │
│ filter:      │           │           │               │
│ pushdown_fi… │           │ …
```
=> add a summary table to benchmark compare output

datafusion/common/src/scalar.rs, datafusion/physical-expr/src/array_expressions.rs, datafusion/sqllogictest/test_files/array.slt
Parts #8084
Parts #8185
The current implementation of the `make_array` and `array_length` functions lack support for `LargeList`. Therefore, we need to enhance these functions by incorporating the `OffsizeTrait` to enable them to work seamlessly with `LargeList`. This will ensure that the functions can handle a large number of elements in the list, thus improving their overall efficiency.
- `make_array` can be `List` and `LargeList` depending on the array length
- support `LargeList` in `array_lenght`
-  `array_array` and `array!` can consider `OffsizeTrait`
=> feat: support  `LargeList` in `make_array` and `array_length`

datafusion-cli/src/exec.rs, datafusion/core/src/physical_planner.rs, datafusion/physical-expr/src/array_expressions.rs
Closes #.
- remove `unalias` TableScan filters
- refactor  CreateExternalTable
- fix typo
=> remove `unalias` TableScan filters when create Physical Filter

README.md, docs/source/user-guide/cli.md
=> Minor: Add installation link to README.md

datafusion/expr/src/window_frame.rs, datafusion/sqllogictest/test_files/window.slt
Closes #.
We have regularized RANGE window frame to ROWS frame if ORDER BY clause is empty under special cases (based on the comment), but the code actually ignores non-empty ORDER BY clause which implicitly allows more than one ORDER BY columns. This case is not reflected in the code comment. This updates code comment to make it more clear.
This also adds a few tests in `sqllogictest` for various `ORDER BY` cases with RANGE frame. By comparing their results with Postgres, there are a few TODOs added for the difference.
Updated code comment and added tests.
Added tests to `sqllogictest`.
=> Update code comment for the cases of regularized RANGE frame and add tests for ORDER BY cases with RANGE frame

datafusion/expr/src/logical_plan/plan.rs
Follow on to https://github.com/apache/arrow-datafusion/pull/8384
Add an example in the Doc so it is slightly easier to figure out how to use named query parameter
Extra doc example
Yes, doc test
=> Minor: Add example with parameters to LogicalPlan

datafusion/common/src/scalar.rs
=> feat: ScalarValue from String

datafusion/physical-expr/src/array_expressions.rs, datafusion/sqllogictest/test_files/array.slt
=> feat: support `LargeList` for `array_has`, `array_has_all` and `array_has_any`

.github/workflows/dev_pr/labeler.yml
Closes #.
Labeler is broken now, e.g. https://github.com/apache/arrow-datafusion/actions/runs/7107345447/job/19348599271?pr=8419.
```
Run actions/labeler@v5.0.0
The configuration file (path: .github/workflows/dev_pr/labeler.yml) was found locally, reading from the file
Error: Error: found unexpected type for label 'development-process' (should be array of config options)
Error: found unexpected type for label 'development-process' (should be array of config options)
```
Tries to restore labeler CI by following latest format.
=> fix: Changed labeler.yml to latest format

datafusion/common/src/pyarrow.rs, datafusion/common/src/scalar.rs, datafusion/core/src/datasource/listing/helpers.rs, datafusion/core/src/datasource/physical_plan/avro.rs, datafusion/core/src/datasource/physical_plan/csv.rs, datafusion/core/src/datasource/physical_plan/file_scan_config.rs, datafusion/core/src/datasource/physical_plan/parquet/mod.rs, datafusion/core/src/test/variable.rs, datafusion/execution/src/config.rs, datafusion/expr/src/expr.rs, datafusion/expr/src/literal.rs, datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs, datafusion/optimizer/src/simplify_expressions/guarantees.rs, datafusion/optimizer/src/simplify_expressions/regex.rs, datafusion/physical-expr/benches/in_list.rs, datafusion/physical-expr/src/aggregate/min_max.rs, datafusion/physical-expr/src/aggregate/string_agg.rs, datafusion/physical-expr/src/datetime_expressions.rs, datafusion/physical-expr/src/expressions/get_indexed_field.rs, datafusion/physical-expr/src/expressions/nullif.rs, datafusion/physical-expr/src/functions.rs, datafusion/physical-plan/src/joins/cross_join.rs, datafusion/physical-plan/src/projection.rs, datafusion/physical-plan/src/union.rs, datafusion/proto/tests/cases/roundtrip_logical_plan.rs, datafusion/proto/tests/cases/roundtrip_physical_plan.rs, datafusion/sql/src/expr/mod.rs, datafusion/sql/tests/sql_integration.rs
Follow on to https://github.com/apache/arrow-datafusion/pull/8411
Inspired by the commentary on https://github.com/apache/arrow-datafusion/pull/8411 from @viirya  and @Dandandan  https://github.com/apache/arrow-datafusion/pull/8411#discussion_r1414334754 I took a walk through the code and found quite a few places where we could clean up the construction of `ScalarValue::Utf8`
Use `ScalarValue::from` impl to create `ScalarValue::Utf8` -- this both takes less code and may avoid some copies. 
=> Minor: Use `ScalarValue::from` impl for strings

datafusion/substrait/src/logical_plan/consumer.rs, datafusion/substrait/src/logical_plan/producer.rs, datafusion/substrait/tests/cases/roundtrip_logical_plan.rs
ref: #8149
Closes #.
part of #8149.
Translate [cross product](https://substrait.io/relations/logical_relations/#cross-product-operation)  to LogicalPlan::CrossJoin.
=> Support crossjoin in substrait.

datafusion/physical-expr/src/array_expressions.rs
=> Minor: convert marcro `list-slice` and `slice` to function

datafusion/common/src/scalar.rs
=> Remove macro in iter_to_array for List

datafusion-cli/Cargo.lock, datafusion-cli/Cargo.toml, datafusion-cli/src/exec.rs, datafusion-cli/src/object_storage.rs
Closes #8421
See issue (PR in datafusion caused regression in datafusion-cli when using datafusion-cli specific SQL statement options)
Any arbitrary SQL statement option parsed in datafusion-cli is removed if found before executing the plan.
Yes, modified existing datafusion-cli unit test to make sure FileTypeWriterOptions::build will not throw an error when passing ObjectStore related datafusion-cli options.
No
=> Bugfix: Remove df-cli specific SQL statment options before executing with DataFusion

datafusion/common/src/scalar.rs
Bugs in #8221 
FixedsizeList should converted by `as_fixed_size_list` not `as_list_array`. However, I just found we can get the child data so we dont need to downcast array via their type.
Existing test `test_list_partial_cmp`
I removed test that array length is greater than 1 since ScalarValue::List should contains length 1 array.
=> Fix PartialOrd for ScalarValue::List/FixSizeList/LargeList

datafusion/optimizer/src/analyzer/type_coercion.rs, datafusion/sqllogictest/test_files/window.slt
Closes #.
A small follow up to #8419. In `coerce_window_frame`, if first literal is Null, it returns an error "Cannot run range queries ...".
=> fix: ORDER BY window definition should work on null literal

datafusion-examples/examples/custom_datasource.rs, datafusion-examples/examples/memtable.rs, datafusion-examples/examples/simple_udtf.rs, datafusion/common/src/dfschema.rs, datafusion/common/src/error.rs, datafusion/common/src/utils.rs, datafusion/core/benches/sort_limit_query_sql.rs, datafusion/core/benches/sql_query_with_io.rs, datafusion/core/src/datasource/file_format/parquet.rs, datafusion/core/src/datasource/file_format/write/demux.rs, datafusion/core/src/datasource/listing/table.rs, datafusion/core/src/datasource/physical_plan/json.rs, datafusion/core/src/datasource/physical_plan/mod.rs, datafusion/core/src/physical_planner.rs, datafusion/core/tests/parquet/file_statistics.rs, datafusion/core/tests/sql/mod.rs, datafusion/core/tests/sql/parquet.rs, datafusion/execution/src/cache/cache_unit.rs, datafusion/expr/src/utils.rs, datafusion/optimizer/src/eliminate_limit.rs, datafusion/optimizer/src/push_down_filter.rs, datafusion/optimizer/src/push_down_projection.rs, datafusion/optimizer/src/test/mod.rs, datafusion/physical-expr/src/aggregate/groups_accumulator/adapter.rs, datafusion/physical-expr/src/array_expressions.rs, datafusion/physical-plan/src/memory.rs, datafusion/physical-plan/src/test/exec.rs, datafusion/sql/src/relation/mod.rs
Closes #.
Fix rust lints
Two major warnings:
- unnecessary `try_from()`
- `.get(0)` to `.first()`
Yes
No
=> flx clippy warnings

datafusion/expr/src/window_frame.rs, datafusion/proto/src/logical_plan/from_proto.rs, datafusion/sql/src/expr/function.rs, datafusion/sqllogictest/test_files/window.slt
Closes #.
We currently regularize RANGE window frame with UNBOUNDED/CURRENT ROW bounds with empty ORDER BY clause to ROWS frame with the UNBOUNDED bounds. This produces inconsistent result compared to Postgres where the case is treated as ORDER BY with constant sort key and unchanged window frame.
=> fix: RANGE frame for corner cases with empty ORDER BY clause should be treated as constant sort

datafusion/proto/proto/datafusion.proto, datafusion/proto/src/generated/pbjson.rs, datafusion/proto/src/generated/prost.rs, datafusion/proto/src/logical_plan/from_proto.rs, datafusion/proto/src/logical_plan/to_proto.rs, datafusion/proto/tests/cases/roundtrip_logical_plan.rs
Closes #8461.
When round-tripping a Schema in our application, we noticed the `dict_id` on `Field`s appears to "get lost", which breaks what we are working on. This PR is an attempt to prove / fix the issue.
Serde the info.
With a unit test.
Serde should work better.
=> Preserve `dict_id` on `Field` during serde roundtrip

datafusion/proto/proto/datafusion.proto, datafusion/proto/src/generated/pbjson.rs, datafusion/proto/src/generated/prost.rs, datafusion/proto/src/physical_plan/mod.rs, datafusion/proto/tests/cases/roundtrip_physical_plan.rs
=> feat: support `InterleaveExecNode` in the proto

datafusion/common/src/utils.rs, datafusion/physical-plan/src/windows/bounded_window_agg_exec.rs, datafusion/sqllogictest/test_files/window.slt
Closes [#8403](https://github.com/apache/arrow-datafusion/issues/8403).
As described in the issue, window function RANK gives wrong results for some cases, also fails during execution for some other cases. The [PR8445](https://github.com/apache/arrow-datafusion/pull/8445) resolves the wrong result generation (This PR is merged).
This PR resolves the failure problem during execution. As far as I can tell this PR and #8445 jointly solves the issue.
Yes new test is added for window functions with empty record batches at their input.
=> [BUG FIX]: Proper Empty Batch handling in window execution

datafusion/physical-expr/src/expressions/cast.rs
Because https://github.com/apache/arrow-rs/pull/4395 and https://github.com/apache/arrow-rs/issues/2966 were completed, `CastOption` supports `PartialEq` and `hash` now
Closes #.
=> Minor: update `cast`

datafusion/core/src/physical_optimizer/projection_pushdown.rs, datafusion/sqllogictest/test_files/select.slt
Closes #8453 
don't unifies projection if the expression in non-trival. see discussion in #8296 
add physical plan check in `.slt` test
=> fix: don't unifies projection if expr is non-trival

datafusion/common/src/scalar.rs, datafusion/physical-expr/src/datetime_expressions.rs
=> Minor: refactor `data_trunc` to reduce duplicated code

datafusion/core/src/datasource/listing/table.rs
n/a
Fixes a single-character typo.
See above.
n/a
No.
=> Minor: Fix comment typo in table.rs: s/indentical/identical/

datafusion/physical-expr/src/array_expressions.rs, datafusion/physical-expr/src/expressions/get_indexed_field.rs
=> Remove `define_array_slice` and reuse `array_slice` for `array_pop_front/back`

datafusion/physical-expr/src/string_expressions.rs
=> Minor: refactor `trim` to clean up duplicated code

datafusion/expr/src/built_in_function.rs, datafusion/physical-expr/src/struct_expressions.rs, datafusion/sqllogictest/test_files/struct.slt
Closes #8118 
Datafusion can read in data with / have structs with fields of different types, but currently can't create a struct column with fields of different types: struct creation casts of all the struct fields to the same type.
This PR defines `TypeSignature::VariadicLimited` and assigns it as the return type of `BuiltinScalarFunction::Struct`. `TypeSignature::VariadicLimited` is like a `TypeSignature::VariadicAny` with a limited definition of `Any` and is distinct from `TypeSignature::Variadic` in that it does not cast any fields.
There is a test for a successful and an unsuccessful invocation of `get_valid_types` for `TypeSignature::VariadicLimited`
The type of the generated struct column will be different: users who are expecting a cast will be surprised.
=> Enable non-uniform field type for structs created in DataFusion

datafusion/core/src/physical_optimizer/enforce_distribution.rs
related to https://github.com/apache/arrow-datafusion/issues/8451
While working on a reproducer for https://github.com/apache/arrow-datafusion/issues/8451 I noticed several things that could be improved in the EnforceDistribution tests
1. Add comments
2. Update parameter names to match config names
3. Fix typos
No. It is a code cleanup only
=> Minor: Improve comments in EnforceDistribution tests

datafusion/sql/src/expr/value.rs, datafusion/sqllogictest/test_files/interval.slt
Closes #8465 .
convert the string value in `has_units` to lowercase.
yes
yes
=> fix: support uppercase when parsing `Interval`

datafusion/core/src/physical_optimizer/projection_pushdown.rs, datafusion/sqllogictest/test_files/join.slt
related to #8374
In #8374, we find `ProjectionPushdown` will incorrectly push projection down and rewrite order by column, 
before
```sql
select t1.* from t1 join t2 on t1.a = t2.a order by t1.a, t2.b;
```
after
```sql
select t1.* from t1 join t2 on t1.a = t2.a order by t1.a, t1.b;
```
the sort column change from `t1.a, t2.b` to `t1.a, t1.b`.
However, even if we find the root case, we can still not explain why setting the order by column incorrectly results in an empty output. After doing some tests, I discovered that we did not set the `preserve_partitioning` in `SortExec`. As a result, `SortExec` only run one partition(instead of all partition), leading to an empty output.
make `SortExec`'s `preserve_patitioning` consistent before and after projection_pushdown
yes, add `.slt` test
=> fix: incorrect set preserve_partitioning in SortExec

.github/workflows/rust.yml, datafusion/common/src/file_options/file_type.rs, datafusion/common/src/file_options/mod.rs, datafusion/common/src/test_util.rs
Closes #8250.
In the tests for `datafusion-common`, mark the test programs that require parquet for compilation with `#[cfg(feature = "parquet")]`. Additionally, in the CI, add a check to verify whether `datafusion-common` can compile without any features enabled (by `cargo check`).
Running `cargo test --tests --no-default-features -p datafusion-common`.
The result is a pass.
=> Explicitly mark parquet for tests in datafusion-common 

datafusion/core/src/dataframe/mod.rs
Closes #8487
Aims to clarify some confusion around DataFrame::write_table and its return type.
Updated Doc comment for DataFrame::write_table
na
Updated docs
=> Minor/Doc: Clarify DataFrame::write_table Documentation

datafusion/physical-plan/src/display.rs
Closes #8513.
Stats are pulled only if they are requested.
Added relevant regression tests.
=> fix: Pull stats in `IdentVisitor`/`GraphvizVisitor` only when requested

datafusion/core/src/dataframe/mod.rs
Closes #8476.
https://github.com/apache/arrow-datafusion/issues/8476#issue-2033547105
`test_cache_mismatch`
=> Fix `DataFrame::cache` errors with `Plan("Mismatch between schema and batches")`

datafusion/proto/Cargo.toml
Let's keep dependencies up to date
Especially since other parts of the system use `pbjson 0.6.0` already: https://github.com/apache/arrow-datafusion/blob/34b0445b778c503f4e65b384ee9ec119ec90044a/datafusion/proto/gen/Cargo.toml#L34
I am not sure why this one did not
=> Minor: update pbjson_dependency

docs/source/user-guide/dataframe.md
none
The user guide contains a table describing the methods/actions available for DataFrames but currently does not mention write_table.
Add write_table to available actions in DataFrame user guide.
Via existing tests
Doc update
=> Minor/Doc: Add DataFrame::write_table to DataFrame user guide

datafusion/core/src/datasource/listing/helpers.rs, datafusion/core/src/datasource/listing/mod.rs, datafusion/core/src/datasource/listing/url.rs, datafusion/sqllogictest/bin/sqllogictests.rs, datafusion/sqllogictest/test_files/repartition_scan.slt
This is part of https://github.com/apache/arrow-datafusion/issues/8451
There are no good end to end tests of repartitioned scans that I could find (because the default size threshold for repartitioning is 10MB, and most tests use files smaller than this)
1. Add end to end tests for repartitioning
2. Fix a bug in sqllogictest harness that meant `--complete` mode  didn't clear scratch files (I think @tustvold  hit this at some point)
3. FIx a bug in `SINGLE_FILE_OUTPUT` that caused it to fail if the parent directory didn't exist
4. Sort files by path beore splitting them in ListingTable to ensure deterministic order
Yes -- there are several new tests added
Two bug fixes as described above
=> Minor: Add repartition_file.slt end to end test for repartitioning files, and supporting tweaks

datafusion/common/src/error.rs, datafusion/substrait/src/logical_plan/consumer.rs
Related to https://github.com/apache/arrow-datafusion/issues/8149
This PR does two reactors:
- Merge all `Expr` branches in `ScalarFunctionType` into one. And move the dispatch logic into `BuiltinExprBuilder`.
- Define and use `substrait_err!`/`substrait_datafusion_err!` to generate errors.
I'm going to implement other `Expr` types in substrait. This refactoring makes it easier to extend the match of `Expr`s
As described above. This PR doesn't contains logical change
By existing cases
No
=> refactor: use ExprBuilder to consume substrait expr and use macro to generate error

datafusion/sqllogictest/test_files/distinct_on.slt, datafusion/sqllogictest/test_files/groupby.slt
Closes #.
While working on another PR, I realized that some of the test results are not deterministic. This PR makes these test results deterministic.
=> [MINOR]: Make some slt tests deterministic

datafusion/expr/src/expr.rs, datafusion/optimizer/src/common_subexpr_eliminate.rs, datafusion/sqllogictest/test_files/functions.slt
=> fix: volatile expressions should not be target of common subexpt elimination

datafusion-cli/src/functions.rs, datafusion-cli/src/main.rs
Closes #8464
Output for the `data_index_bloom_encoding_stats.parquet` file
Datafusion
DuckDB
Yes
One thing I did notice while testing this was that, for `parquet-testing/data/hadoop_lz4_compressed.parquet` file, the output was still a byte array.
I checked the converted type was `None` for that column so, not sure if just blindly converting byte array into utf-8 string would be the right approach. Open to suggestions.
=> feat: improve string statistics display in datafusion-cli `parquet_metadata` function

datafusion/sqllogictest/bin/sqllogictests.rs
Closes https://github.com/apache/arrow-datafusion/issues/8541 (I think)
@andygrove got an error when running sqllogictest, which I think was something related to his system setup (e.g. there was some filesystem error) but the error message was unhelpful 
1. Added error handling rather than `panic`
We get a somewhat unhelpful panic message about "Readable directory"
```
andrewlamb@Andrews-MacBook-Pro:~/Software/arrow-datafusion$ cargo test --test sqllogictests
Finished test [unoptimized + debuginfo] target(s) in 0.13s
Running bin/sqllogictests.rs (target/debug/deps/sqllogictests-a4acaa02cc91a4e3)
thread 'main' panicked at datafusion/sqllogictest/bin/sqllogictests.rs:264:14:
Readable directory: Os { code: 2, kind: NotFound, message: "No such file or directory" }
note: run with …
```
=> Minor: Improve error handling in sqllogictest runner

datafusion/physical-expr/src/aggregate/count.rs, datafusion/physical-expr/src/aggregate/count_distinct.rs, datafusion/sqllogictest/test_files/aggregate.slt
Use `logical_nulls` when the array data type is `Null`.
Closes #8509.
The semantics of `NullArray` in Arrow are confusing: https://github.com/apache/arrow-rs/pull/4838
So we have to handle the `Null` data type in a special way.
Patches in count and count distinct accumulators to handle the `Null` data type or use `logical_nulls` when appropriate.
Yes, added SQL tests.
Yes, count and count distinct now behave consistently wrt `null` regardless of the data type.
=> Fix count(null) and count(distinct null)

datafusion/physical-expr/src/datetime_expressions.rs
=> Minor: reduce code duplication in `date_bin_impl`

datafusion/core/tests/dataframe/mod.rs, datafusion/physical-plan/src/unnest.rs
Closes https://github.com/apache/arrow-datafusion/issues/8481.
See https://github.com/apache/arrow-datafusion/issues/8481
Adds a new `UnnestMetrics` struct to collect metrics.
Yes, added a DF test.
I'm not sure if there are better places to have this kind of test.
I saw that there are similar explain-tests for SQL. However, unnest is not yet implemented for SQL.
Yes, additional metrics now show up in `EXPLAIN ANALYZE` queries.
=> Add metrics for UnnestExec

dev/changelog/34.0.0.md
N/A
rc1 failed because a regression was identified, which is now resolved
rc2 failed due to tests failing locally for me
Update changelog.
=> Prepare 34.0.0-rc3

datafusion/physical-expr/src/expressions/case.rs, datafusion/sqllogictest/test_files/scalar.slt
Closes #8475 
In our current implementation, when `WHEN` clause is true, we will always pick the last true branch.
Because when `WHEN` is true(`WHEN true` or the expression can simplified to `WHEN true`), we don't set `when_value` to false (even though it already has the result)in the below code, so we always update the `current_value`.
https://github.com/apache/arrow-datafusion/blob/2765fee4dd7518a4dc39244d1b495329b9771be1/datafusion/physical-expr/src/expressions/case.rs#L194-L208
=> fix: make sure CASE WHEN pick first true branch when WHEN clause is true

datafusion/expr/src/logical_plan/builder.rs, datafusion/expr/src/logical_plan/plan.rs, datafusion/proto/src/logical_plan/mod.rs
N/A
Currently, all `#[non_exhaustive]` logical plan structs with a `try_new` constructor take `Arc<LogicalPlan>` as parameter, except for `SubqueryAlias`, which takes a `LogicalPlan`. This change makes `SubqueryAlias::try_new` uniform with the other plan type constructors, to improve API ergonomics.
* Change the signature of `SubqueryAlias::try_new` to take `Arc<LogicalPlan>` instead of `LogicalPlan`.
Yes.
No.
=> Minor: make SubqueryAlias::try_new take Arc<LogicalPlan>

datafusion/physical-expr/src/analysis.rs, datafusion/sqllogictest/src/test_context.rs, datafusion/sqllogictest/test_files/explain.slt
Closes #8262 
Previously in https://github.com/apache/arrow-datafusion/commit/c9330bc09e583734aed721a208a0684118b170f1 we changed the default empty value for lower and upper bound from `ScalarValue::Null` to `ScalarValue::try_from(field.data_type())`. but the drawback of this was that for the types that this wasn't implemented (as mentioned in the issue for `Map`), this cause the queries to fail. To fix this we can either implement this for other data types (for map I did a prototype in #8488), or fall back on `Null` which I did in this PR.
Explained above.
I tested it using the query provided in the issue.
No
=> Fallback on null empty value in ExprBoundaries::try_from_column

datafusion/physical-plan/src/placeholder_row.rs, datafusion/sqllogictest/test_files/window.slt
Closes #.
Currently, if there is no column at the place holder exec, it generates at least one dummy column. This causes inconsistency in the subsequent schemas for some edge cases. (Where schema of the `PlaceHolderExec` itself has 0 columns, but generated `RecordBatch` from this schema has single column.) Thanks @comphead for bringing this to my attention.
This PR fixes above mentioned problem.
Yes new test is added. Which is the test in the [discussion](https://github.com/apache/arrow-datafusion/issues/8386#issuecomment-1856695669)
=> [MINOR]: Generate empty column at placeholder exec

datafusion-examples/examples/simple_udtf.rs, docs/source/library-user-guide/adding-udfs.md
Closes https://github.com/apache/arrow-datafusion/issues/8545
Updating the docs to match the exciting UDTF addition.
Updates the UDF library doc, makes minor style update to the example
Yes, public docs update.
=> docs: update udf docs for udtf

datafusion/substrait/src/logical_plan/consumer.rs, datafusion/substrait/src/logical_plan/producer.rs, datafusion/substrait/tests/cases/roundtrip_logical_plan.rs
Part of #8149
This PR implements several unary-like `Expr`s:
- Not
- Negative
- IsTrue
- IsFalse
- IsNotTrue
- IsNotFalse
- IsUnknown
- IsNotUnknown
As above
I add roundtrip tests for every new expr
No
=> feat: implement Unary Expr in substrait

datafusion/optimizer/src/push_down_filter.rs
Closes #.
move some invariants out of the loop
=> Minor: move some invariants out of the loop

datafusion/physical-expr/src/array_expressions.rs, datafusion/sqllogictest/test_files/array.slt
=> feat: support largelist in array_slice

datafusion/sql/src/expr/function.rs, datafusion/sqllogictest/test_files/window.slt
Closes #8386 .
Support scalars for `PARTITION BY` clause to avoid `Expects PARTITION BY expression to be ordered` error.
Yes
No
=> minor: fix  to support scalars

datafusion/core/src/physical_optimizer/enforce_sorting.rs, datafusion/core/src/physical_optimizer/replace_with_order_preserving_variants.rs, datafusion/core/src/test/mod.rs
Closes #.
With the [PR8573](https://github.com/apache/arrow-datafusion/pull/8573), `is_infinite` flag is removed. Some of the changes in the [PR8573](https://github.com/apache/arrow-datafusion/pull/8573) changed tests such that the we no longer exercise the interaction between sort preservation flag with boundedness properties of sources. This PR changes these tests so that the tests exercise all possible situations.
Yes
=> [MINOR]: Parametrize sort-preservation tests to exercise all situations (unbounded/bounded sources and flag behavior)

datafusion-examples/examples/simple_udf.rs
Relate to #8045 
I found some code that could be clearer in the example, so figured I would make a small PR for it
1. Update scalar udf example docs
2. Use a less verbose schema to make RecordBatch
yes, by exisitng tests
=> Minor: Add some comments to scalar_udf example

datafusion/physical-expr/src/array_expressions.rs, datafusion/sqllogictest/test_files/array.slt
=> feat: support `LargeList` in `array_positions`

datafusion/expr/src/built_in_function.rs, datafusion/physical-expr/src/array_expressions.rs, datafusion/sqllogictest/test_files/array.slt
=> feat: support `LargeList` in `array_element`

datafusion/expr/src/expr.rs
N/A
While reviewing the excellent PR from https://github.com/apache/arrow-datafusion/pull/7942 I noticed we can avoid a (deep) copy in the `Expr::unalias` code without an API change
Avoid a copy in `Expr::unalias`
exisiting tests
No
=> Minor: avoid a copy in Expr::unalias

datafusion/core/tests/dataframe/dataframe_functions.rs, datafusion/physical-expr/src/aggregate/approx_percentile_cont.rs
=> Minor: support complex expr as the arg in the ApproxPercentileCont function

datafusion/physical-plan/src/aggregates/mod.rs
Closes #.
Removing the `GroupByOrderMode` struct that became unused after #8364.
Removal of `GroupByOrderMode`.
An old, unused public struct is removed. I can not see any potential issues as it was previously used by built-in execs only and is now unused, but we are removing a public struct nonetheless. If there is a downstream user with custom execs using this struct, they will need to migrate to `InputOrderMode`.
=> Remove GroupByOrderMode

datafusion/physical-expr/src/array_expressions.rs
In https://github.com/apache/arrow-datafusion/pull/8569#discussion_r1430679163_, the error output should be consistent for unsupported type.
=> Minor: replace` not-impl-err` in `array_expression`

datafusion/physical-expr/src/array_expressions.rs, datafusion/sqllogictest/test_files/array.slt
=> feat: support `LargeList` in `array_dims`

datafusion/proto/proto/datafusion.proto, datafusion/proto/src/generated/pbjson.rs, datafusion/proto/src/generated/prost.rs, datafusion/proto/src/logical_plan/from_proto.rs, datafusion/proto/src/logical_plan/to_proto.rs
Closes https://github.com/apache/arrow-datafusion/issues/8602
Fix regression in generating protobuf source with protobuf 3.12, which is the recommended version in the documentation.
Remove redundant `optional` keyword.
=> Fix regression in regenerating protobuf source

datafusion-cli/Cargo.lock, datafusion-cli/Cargo.toml, datafusion/common/src/error.rs, datafusion/common/src/scalar.rs, datafusion/common/src/utils.rs, datafusion/core/src/datasource/avro_to_arrow/arrow_array_reader.rs, datafusion/core/src/datasource/listing_table_factory.rs, datafusion/core/src/datasource/memory.rs, datafusion/core/src/datasource/physical_plan/parquet/row_filter.rs, datafusion/core/tests/user_defined/user_defined_plan.rs, datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs, datafusion/physical-expr/src/aggregate/first_last.rs, datafusion/physical-expr/src/aggregate/groups_accumulator/adapter.rs, datafusion/physical-expr/src/expressions/binary.rs, datafusion/physical-expr/src/regex_expressions.rs, datafusion/physical-expr/src/window/lead_lag.rs, datafusion/physical-plan/src/joins/stream_join_utils.rs, datafusion/physical-plan/src/joins/utils.rs, datafusion/physical-plan/src/repartition/mod.rs, datafusion/physical-plan/src/windows/bounded_window_agg_exec.rs, datafusion/proto/src/logical_plan/from_proto.rs, datafusion/sqllogictest/test_files/math.slt
Closes partially #7360.
Continue covering Datafusion Errors with error macros supporting optional backtrace
introduced `arrow_err!` and `arrow_datadusion_err!` macros with optional backtrace, to represent `Err(DatafusionError::ArrowError)` and `DatafusionError::ArrowError(_)`
Yes
No
=> Add `arrow_err!` macros, optional backtrace to ArrowError

datafusion-examples/README.md, datafusion-examples/examples/dataframe_output.rs
Closes #8551 
We currently do not have an example of DataFrame::write_table, nor other DataFrame::write* methods which do not depend on an external S3 bucket.
Adds examples of DataFrame::write_table and other write* methods using LocalFileSystem object store.
Via existing tests
No
=> Add examples of DataFrame::write* methods without S3 dependency

datafusion/proto/proto/datafusion.proto, datafusion/proto/src/generated/pbjson.rs, datafusion/proto/src/generated/prost.rs, datafusion/proto/src/logical_plan/mod.rs, datafusion/proto/tests/cases/roundtrip_logical_plan.rs
Closes https://github.com/apache/arrow-datafusion/issues/8596
Implement serde for `CopyTo` because it is needed by Ballista (https://github.com/apache/arrow-ballista/issues/894).
Implement serde and add unit tests.
There is a follow-on issue https://github.com/apache/arrow-datafusion/issues/8619 to add support for CopyTo with WriterOptions, which for now is unsupported and will return an `Err`.
Yes.
=> Implement logical plan serde for CopyTo

datafusion/common/src/param_value.rs
=> Rename `ParamValues::{LIST -> List,MAP -> Map}`

datafusion/expr/src/type_coercion/binary.rs, datafusion/sqllogictest/test_files/timestamps.slt
Closes #8275.
Support binary temporal coercion for Date64 and Timestamp types
sqllogictest
=> Support binary temporal coercion for Date64 and Timestamp types

datafusion/expr/src/expr_schema.rs
Closes #8507.
If parent struct is nullable; sub-fields should also be.
As suggested in #8507: 
I added a test to reproduce the bug with the schema described.
Then I introduced a simple guard clause to check if the parent col is nullable; if it is return early.
Change is tested by `test_nested_schema_nullability`.
No.
=> Fix #8507: Non-null sub-field on nullable struct-field has wrong nullity

datafusion/proto/proto/datafusion.proto, datafusion/proto/src/generated/pbjson.rs, datafusion/proto/src/generated/prost.rs, datafusion/proto/src/logical_plan/mod.rs, datafusion/proto/src/physical_plan/from_proto.rs, datafusion/proto/tests/cases/roundtrip_logical_plan.rs
Closes https://github.com/apache/arrow-datafusion/issues/8598
Closes https://github.com/apache/arrow-datafusion/issues/8619
There is a follow on issue https://github.com/apache/arrow-datafusion/issues/8632 to support advanced writer options, but this should be enough to unblock Ballista.
If this PR is accepted then I will create a similar PR to do the same for CSV.
Required by Ballista so that we can save query results to Parquet.
- Implement serde
- Add tests
=> Add partial serde support for ParquetWriterOptions

datafusion/physical-expr/src/array_expressions.rs
As suggestions by @comphead in https://github.com/apache/arrow-datafusion/pull/8592#discussion_r1432989309, I found many functions in `array_expression.rs` lack the argument check.
=> Minor: add arguments length check in `array_expressions`

datafusion/core/src/dataframe/mod.rs
Related to https://github.com/apache/arrow-datafusion/issues/8628
While working on https://github.com/apache/arrow-datafusion/pull/8629 I found it hard at first to understand what these tests  (added in https://github.com/apache/arrow-datafusion/pull/8356) were attempting to validate, largely because of some boilerplate / repetition that made them harder for me to understand
I am also trying to leave the DataFusion codebase always slightly better than when I found it.
Reduce duplication and improve comments
only tests
No, this is cleanup only
=> Minor: improve dataframe functional dependency tests

datafusion/expr/src/logical_plan/plan.rs, datafusion/optimizer/src/eliminate_cross_join.rs, datafusion/optimizer/src/push_down_filter.rs, datafusion/sqllogictest/test_files/joins.slt
Closes #.
Current filters are not pushed down to the cross join (equality predicates are pushed down). For this reason we generate following plan for the query 
```sql
SELECT *
FROM annotated_data as l, annotated_data as r
WHERE l.a > r.a
```
```sql
FilterExec: filter=a@0 > a@1
--CrossJoinExec: 
----RepartitionExec: partitioning=RoundRobinBatch(2), input_partitions=1
------CsvExec: file_groups={1 group: [[WORKSPACE_ROOT/datafusion/core/tests/data/window_2.csv]]}, projection=[a0, a, b, c, d], output_ordering=[a@1 ASC, b@2 ASC NULLS LAST, c@3 ASC NULLS LAST], has_header=true
----CsvExec: file_groups={1 group: [[WORKSPACE_ROOT/datafusion/core/tests/data/window_2.csv]]}, projection=[a0, a, b, c, d], output_ordering=[a@1 ASC, b@2 ASC NULLS LAST, c@3 ASC NULLS LAST], has_header=true
``` …
=> Filter pushdown into cross join

datafusion/physical-plan/src/joins/stream_join_utils.rs, datafusion/physical-plan/src/joins/symmetric_hash_join.rs, datafusion/physical-plan/src/joins/utils.rs
Closes #.
Make the duplication removed, and seperate the methods for utils.
Only code replacements, not new logic are added.
Yes
No
=> [MINOR] Remove duplicate test utility and move one utility function for better organization

datafusion/optimizer/src/eliminate_cross_join.rs, datafusion/optimizer/src/push_down_filter.rs, datafusion/sqllogictest/src/test_context.rs, datafusion/sqllogictest/test_files/joins.slt
Closes #.
There are couple of missing points in the [PR](Subsequent PR of [8626](https://github.com/apache/arrow-datafusion/pull/8626)). This PR add these missing points. See [discussion](https://github.com/apache/arrow-datafusion/pull/8626#discussion_r1435683995) for rationale
Yes
=> [MINOR]: Add new test for filter pushdown into cross join

datafusion/core/src/datasource/physical_plan/parquet/mod.rs, datafusion/core/src/datasource/physical_plan/parquet/row_groups.rs
Closes  https://github.com/apache/arrow-datafusion/issues/8376
Closes https://github.com/apache/arrow-datafusion/pull/8397
We introduced `contained` API in https://github.com/apache/arrow-datafusion/pull/8440, and now we can use it to simplify the bloom filter code
This also makes it possible to do things like [Support `IN` lists with more than three constants in predicates for bloom filters](https://github.com/apache/arrow-datafusion/issues/8436)
Covered by existing tests (including that added in https://github.com/apache/arrow-datafusion/pull/8433)
No
=> Rewrite bloom filters to use contains API

datafusion/core/tests/parquet/mod.rs, datafusion/core/tests/parquet/schema.rs, datafusion/core/tests/sql/mod.rs
Closes https://github.com/apache/arrow-datafusion/issues/8207
The tests in parquet_metadata.rs are not really sql tests, they are tests of the parquet reader as @matthewmturner  points out on https://github.com/apache/arrow-datafusion/issues/8207#issuecomment-1868314796
Move the tests to reflect they are really testing the parquet reader, not the SQL interface
By CI
No
=> Move parquet_schema.rs from sql to parquet tests

datafusion/core/src/dataframe/mod.rs, datafusion/expr/src/logical_plan/builder.rs
Closes https://github.com/apache/arrow-datafusion/issues/8628
Fixed regression introduced in https://github.com/apache/arrow-datafusion/pull/8356 as explained on https://github.com/apache/arrow-datafusion/issues/8628
1. Fix bug by not adding synthetic columns with duplicated namess  
2. Improve comments
3. Add test
Yes
Fix bug
=> Fix group by aliased expression in LogicalPLanBuilder::aggregate

datafusion/expr/src/built_in_function.rs, datafusion/physical-expr/src/array_expressions.rs, datafusion/sqllogictest/test_files/array.slt
Closes #.
- implement the output type for `array_intersect`
- support `LargeList`
- integrate `array_union` and `array_intersect` logic
=> Refactor `array_union` and `array_intersect` functions to one general function

datafusion/proto/src/physical_plan/mod.rs
Closes #.
As mention in: https://github.com/apache/arrow-datafusion/pull/7921#discussion_r1373232186
=> Minor: avoid extra clone in datafusion-proto::physical_plan

datafusion/core/src/datasource/file_format/arrow.rs, datafusion/core/src/datasource/file_format/avro.rs, datafusion/core/src/datasource/file_format/csv.rs, datafusion/core/src/datasource/file_format/json.rs, datafusion/core/src/datasource/file_format/parquet.rs
Follow on to https://github.com/apache/arrow-datafusion/pull/8608
The presence of numbers in the source code was not immediately obvious to me and I think it is clearer when there are comments to guide understanding. See  https://github.com/apache/arrow-datafusion/pull/8608#discussion_r1435356536
Give two constants a name and add some docstrings to explain what they do
=> Minor: name some constant values in arrow writer, parquet writer

datafusion/core/src/physical_optimizer/enforce_distribution.rs, datafusion/core/src/physical_optimizer/enforce_sorting.rs, datafusion/core/src/physical_optimizer/output_requirements.rs, datafusion/core/src/physical_optimizer/pipeline_checker.rs, datafusion/core/src/physical_optimizer/replace_with_order_preserving_variants.rs, datafusion/core/src/physical_optimizer/sort_pushdown.rs, datafusion/core/src/physical_optimizer/utils.rs, datafusion/physical-expr/src/sort_properties.rs, datafusion/physical-plan/src/union.rs
The continuation of the work initiated in https://github.com/apache/arrow-datafusion/pull/8395. It could also be beneficial for https://github.com/apache/arrow-datafusion/pull/7942.
`TreeNode` implementations of some optimizer rules are challenging to understand and are open to misuse. This refactor standardizes the implementations and eliminates unnecessary payloads.
These implementations have been refactored:
1) DistributionContext
2) PlanWithCorrespondingSort
3) PlanWithCorrespondingCoalescePartitions
4) PipelineStatePropagator
5) OrderPreservationContext
6) SortPushDown
7) ExprOrdering
8) PlanWithKeyRequirements
`map_children()` functions of these implementations are now uniform. Previously, some of the rules were in `map_children()`, others were in some utils such as …
=> TreeNode Refactor Part 2

datafusion/core/src/datasource/physical_plan/parquet/row_groups.rs, datafusion/physical-expr/src/utils/guarantee.rs
Closes #8436 
- refactor some codes
- Adding `InList` support in LiteralGurantee code 
- Add tests in LiteralGurantee
- Add a test for Bloom filters in `row_groups.rs`
=> feat: support inlist in LiteralGurantee for pruning

datafusion/proto/proto/datafusion.proto, datafusion/proto/src/generated/pbjson.rs, datafusion/proto/src/generated/prost.rs, datafusion/proto/src/logical_plan/mod.rs, datafusion/proto/src/physical_plan/from_proto.rs, datafusion/proto/tests/cases/roundtrip_logical_plan.rs
Closes https://github.com/apache/arrow-datafusion/issues/8597
Part of the effort to support DataFrame::write_xxx again in Ballista
- New serde code
- New test
Yes, new test added
=> Add serde support for CSV FileTypeWriterOptions

datafusion-cli/src/functions.rs, datafusion/common/src/error.rs, datafusion/core/src/physical_optimizer/projection_pushdown.rs, datafusion/optimizer/src/simplify_expressions/guarantees.rs, datafusion/physical-expr/src/aggregate/first_last.rs, datafusion/physical-expr/src/aggregate/mod.rs, datafusion/physical-expr/src/aggregate/utils.rs, datafusion/physical-expr/src/array_expressions.rs, datafusion/physical-plan/src/aggregates/mod.rs, datafusion/sqllogictest/src/engines/datafusion_engine/mod.rs, datafusion/sqllogictest/test_files/distinct_on.slt, datafusion/sqllogictest/test_files/groupby.slt, datafusion/sqllogictest/test_files/joins.slt
Closes #.
Improves situation on [#8662](https://github.com/apache/arrow-datafusion/pull/8662)
Related to https://github.com/apache/arrow-datafusion/issues/8582
This PR implements the observation by @alamb at the [PR](https://github.com/apache/arrow-datafusion/pull/8558) that for first and last value aggregation we do not need to sort entire data at its input.  
In other words, This PR is the `FIRST_VALUE` and `LAST_VALUE` aggregation support of the approach 3 in the design [document](https://docs.google.com/document/d/1cIIJL6RKXKge-t8z4Rs_F-XH82giWQfmciwj-h3tho4/edit?usp=sharing)
Yes
=> Handle ordering of first last aggregation inside aggregator

datafusion/physical-expr/src/array_expressions.rs, datafusion/sqllogictest/test_files/array.slt
=> feat: support 'LargeList' in `array_pop_front` and `array_pop_back`

docs/source/user-guide/introduction.md
We are pleased to announce that CeresDB has entered the apache incubator after changing its name to HoraeDB. In the future, apche horaedb community hopes to contribute more to Datafusion.
change ceresdb to apache horaedb
No
=> chore: rename ceresdb to apache horaedb

datafusion/core/src/datasource/file_format/csv.rs, datafusion/core/src/datasource/file_format/json.rs, datafusion/core/src/datasource/file_format/write/mod.rs, datafusion/core/src/datasource/file_format/write/orchestration.rs, datafusion/core/src/datasource/physical_plan/file_stream.rs
Closes #.
Currently, the serializer is re-created for each RecordBatch, which degrades the performance while dealing with small batch sizes.
The `duplicate()` method is called here
https://github.com/apache/arrow-datafusion/blob/1737d49185e9e37c15aa432342604ee559a1069d/datafusion/core/src/datasource/file_format/write/orchestration.rs#L51-L82
where it is defined as (for CSV it is used for header, for JSON it is just a deep clone.)
https://github.com/apache/arrow-datafusion/blob/1737d49185e9e37c15aa432342604ee559a1069d/datafusion/core/src/datasource/file_format/csv.rs#L432-L450
Also, this makes the internal buffer useless since it is re-created for each batch in this setup.
- Renamed the `BatchSerializer`.
- Make the trait methods take immutable references.
- Make the `type SerializerType = …
=> Make the BatchSerializer behind Arc to avoid unnecessary struct creation

datafusion/core/src/physical_optimizer/pruning.rs
=> [pruning] Add shortcut when all units have been pruned

datafusion/physical-expr/src/aggregate/first_last.rs, datafusion/physical-plan/src/aggregates/mod.rs, datafusion/sqllogictest/test_files/groupby.slt
Closes #.
This is a follow up PR for [PR8662](https://github.com/apache/arrow-datafusion/pull/8662). With the changes in this PR, first last aggregation does not make comparisons on its data when it is known that their input data already satisfies the ordering requirement.
=> Change first/last implementation to prevent redundant comparisons when data is already sorted

datafusion/core/benches/sql_planner.rs
=> Start setting up tpch planning benchmarks

datafusion/core/src/datasource/provider.rs
Closes #8683 
I was recently confused why I was not seeing LIMIT pushed down to my TableProvider when filters were also passed. @Dandandan explained on ASF slack that Inexact filters do not allow the limit to be pushed down. This PR adds to the TableProvider docs to hopefully avoid similar confusion in the future.
Expanded the TableProvider::Scan documentation
by existin tests
Just docs
=> Doc: Clarify When Limit is Pushed Down to TableProvider::Scan

datafusion/expr/src/built_in_function.rs, datafusion/expr/src/signature.rs, datafusion/expr/src/type_coercion/functions.rs, datafusion/sqllogictest/test_files/array.slt
=> Improve `array_prepend` signature for null and empty array

docs/source/user-guide/sql/scalar_functions.md
Closes #.
Update docs to reflect possible arguments here:
https://github.com/apache/arrow-datafusion/blob/bb98dfed08d8c2b94ab668a064b206d8b84b51b0/datafusion/physical-expr/src/datetime_expressions.rs#L813-L829
=> Update scalar functions doc for extract/datepart

datafusion/core/src/execution/context/mod.rs, datafusion/sql/src/parser.rs, datafusion/sql/src/statement.rs
Part of #4808
Start incrementally removing Datafusion parser extensions in favour of migrating them to sqlparser-rs. In this case, sqlparser-rs already supports explain table behaviour:
https://github.com/sqlparser-rs/sqlparser-rs/blob/a75778c8c7ef48e0ceff96637146b57912d2e10b/src/ast/mod.rs#L2091-L2101
So just remove the custom Datafusion code here.
Remove Datafusion parser extension code for `describe table_name` SQL statement as parsing of this is already supported by sqlparser-rs
Existing sqllogictest for describe ensures no breaking changes:
https://github.com/apache/arrow-datafusion/blob/bf3bd9259aa0e93ccc2c79a606207add30d004a4/datafusion/sqllogictest/test_files/describe.slt#L29-L34
=> Remove DescribeTableStmt in parser in favour of existing functionality from sqlparser-rs

datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs
Closes #8688 
Adds optimizer rule for
* `SELECT .. WHERE NULL IN (…)` --> `SELECT .. WHERE NULL`
* `SELECT .. WHERE NULL NOT IN (…)` --> `SELECT .. WHERE NULL`
```bash
DataFusion CLI v34.0.0
❯ create table t (x int) as values (1), (2);
0 rows in set. Query took 0.031 seconds.
❯ explain select x from t where null IN (x, 2, 3);
+---------------+---------------------------------------------------+
| plan_type     | plan                                              |
+---------------+---------------------------------------------------+
| logical_plan  | Filter: Boolean(NULL)                             |
|               |   TableScan: t projection=[x]                     |
| physical_plan | CoalesceBatchesExec: target_batch_size=8192       |
|               |   FilterExec: NULL …
```
=> Simplify `NULL [NOT] IN (..)` expressions

datafusion/expr/src/logical_plan/builder.rs, datafusion/expr/src/logical_plan/plan.rs, datafusion/expr/src/tree_node/plan.rs, datafusion/optimizer/src/eliminate_outer_join.rs, datafusion/optimizer/src/optimize_projections.rs, datafusion/optimizer/src/optimizer.rs, datafusion/optimizer/src/push_down_filter.rs, datafusion/optimizer/src/push_down_limit.rs, datafusion/optimizer/src/utils.rs
Closes #.
This patch deprecates `with_new_inputs` function which is duplicated with `with_new_exprs`. We should not have duplicate APIs which cause confusion and maintenance issue.
=> Deprecate duplicate function `LogicalPlan::with_new_inputs`

datafusion/core/src/datasource/file_format/write/demux.rs, datafusion/core/src/datasource/physical_plan/parquet/page_filter.rs, datafusion/core/src/execution/context/mod.rs, datafusion/core/src/physical_optimizer/sort_pushdown.rs, datafusion/core/src/physical_planner.rs, datafusion/substrait/src/logical_plan/producer.rs
=> Minor: clean up code based on `Clippy`

datafusion/physical-expr/src/array_expressions.rs, datafusion/sqllogictest/test_files/array.slt
=> feat: support `LargeList` in `array_position`

datafusion/optimizer/src/eliminate_filter.rs
Closes #8689
```bash
DataFusion CLI v34.0.0
❯ create table t(x int) as values (1), (2), (3);
0 rows in set. Query took 0.031 seconds.
❯ explain select x from t where null::bool;
+---------------+---------------+
| plan_type     | plan          |
+---------------+---------------+
| logical_plan  | EmptyRelation |
| physical_plan | EmptyExec     |
|               |               |
+---------------+---------------+
2 rows in set. Query took 0.005 seconds.
```
=> feat: remove filters with null constants

datafusion/common/src/utils.rs, datafusion/expr/src/type_coercion/functions.rs, datafusion/physical-expr/src/array_expressions.rs, datafusion/sqllogictest/test_files/array.slt
Parts #8185 
- Support `LargeList` in `array_prepend` and `array_append`
- Support cast LargeList in `ArrayAndElement`
=> support `LargeList` in `array_prepend` and `array_append`

datafusion/core/tests/sql/expr.rs, datafusion/physical-expr/src/datetime_expressions.rs
Closes #8694
Support extracting seconds since epoch for Date32 and Date64 types
=> Support for `extract(epoch from date)` for Date32 and Date64

datafusion-examples/README.md, datafusion-examples/examples/advanced_udwf.rs, datafusion/core/tests/user_defined/user_defined_window_functions.rs, datafusion/expr/src/expr_fn.rs, datafusion/expr/src/lib.rs, datafusion/expr/src/udwf.rs, datafusion/proto/tests/cases/roundtrip_logical_plan.rs, docs/source/library-user-guide/adding-udfs.md
=> Implement trait based API for defining WindowUDF

datafusion/common/src/hash_utils.rs
Closes #.
We will need this for https://github.com/apache/arrow-datafusion/pull/7893
=> Minor: Introduce utils::hash for StructArray

.github/workflows/rust.yml
Closes #8696.
CI tests for windows machines are extremely slow and running 3+ hours now, whereas other architectures are able to finish within 30 mins.
This PR adds more granular build options for each architecture.
With this change windows build time is 60 minutes, which is 2x slower than others OS but still 3x better than current windows run
=> [CI] Improve windows machine CI test time

datafusion/core/src/datasource/physical_plan/parquet/mod.rs, datafusion/core/src/physical_optimizer/pruning.rs
Closes #8685
If predicte_expr get unhandled, it will return true in always_true. 
https://github.com/apache/arrow-datafusion/blob/9a6cc889a40e4740bfc859557a9ca9c8d043891e/datafusion/core/src/physical_optimizer/pruning.rs#L914
https://github.com/apache/arrow-datafusion/blob/9a6cc889a40e4740bfc859557a9ca9c8d043891e/datafusion/core/src/physical_optimizer/pruning.rs#L299-L302
Then this PruningPredicate will be filtered here.
https://github.com/apache/arrow-datafusion/blob/9a6cc889a40e4740bfc859557a9ca9c8d043891e/datafusion/core/src/datasource/physical_plan/parquet/mod.rs#L122-L135
If an expr can't be handled as predicate_expr(like in_list with more than 20 elements) but hava some literalguarantees , the PruningPredicate may also be filtered.  
So , we need to check PruningPredicate  in …
=> fix guarantees in allways_true of PruningPredicate

datafusion/expr/src/logical_plan/builder.rs, datafusion/expr/src/utils.rs
=> Minor: Avoid memory copy in construct window exprs

datafusion-cli/Cargo.lock, datafusion-cli/Cargo.toml, datafusion-cli/src/exec.rs
Closes #.
For streams and long running queries, we will be able to abort the execution and return back to the `readline()` state without terminating the CLI session with ctrl+c signal.
=> Minor: Ctrl+C Termination in CLI

datafusion/expr/src/logical_plan/plan.rs, datafusion/sqllogictest/test_files/window.slt
Closes #.
For window queries in the form `ROW_NUMBER() OVER(PARTITION BY <empty> ORDER BY <expr>)`, we know that row numbers generated will consists of consecutive numbers across table. Hence result of this expression can be treated as `PRIMARY_KEY`. This enables us to execute queries in the form below
```sql
SELECT *
FROM (SELECT c1, c2, ROW_NUMBER() OVER() as rn
FROM aggregate_test_100
LIMIT 5)
GROUP BY rn
ORDER BY rn;
```
without this support query above should be re-written as 
```sql
SELECT *
FROM (SELECT c1, c2, ROW_NUMBER() OVER() as rn
FROM aggregate_test_100
LIMIT 5)
GROUP BY rn, c1, c2 -- this line is the difference
ORDER BY rn;
```
to be able to execute.
This PR adds ROW_NUMBER result as functional dependencies when it known that its result will be unique across rows (when …
=> Add support for functional dependency for ROW_NUMBER window function.

datafusion/core/src/physical_optimizer/enforce_distribution.rs, datafusion/sqllogictest/test_files/join.slt
=> [MINOR]: Add a test case for when target partition is 1, no hash repartition is added to the plan.

datafusion/core/src/physical_optimizer/pruning.rs
Related to https://github.com/apache/arrow-datafusion/issues/7869
As we have extended the PruningPredicate's features and scope, we should also improve its documentation to match.
Improve the PruningPredicate doc strings to reflect its ongoing changes
via doctests
Doc strings only. No code changes
=> Minor: Improve `PruningPredicate` docstrings

datafusion/physical-expr/src/array_expressions.rs, datafusion/sqllogictest/test_files/array.slt
=> feat: support `LargeList` in `cardinality`

datafusion/sqllogictest/test_files/dictionary.slt
Part of https://github.com/apache/arrow-datafusion/issues/8738
https://github.com/apache/arrow-datafusion/issues/8738 is a regression, but there was no test coverage. Thus I would like to ensure we don't introduce additional bugs while fixing it or in the future
We have also hit similar regressions in the past related to handling of dictionaries. 
Introduce a test that contains basic timeseries data with a schema like we use, along with several queries, including the one that errors due to https://github.com/apache/arrow-datafusion/issues/8738
The change is all tests
No, this is test change only
=> Add reproducer for #8738

datafusion/core/src/dataframe/mod.rs, datafusion/physical-plan/src/lib.rs
N/A
While discussing  https://github.com/apache/arrow-datafusion/pull/8739 the behavior of stream cancellation and how to abort execution were not clear (see https://github.com/apache/arrow-datafusion/pull/8739#discussion_r1440755999)
It would be good to document what has been until now an implicit assumption
Add documentation explaining the expecations on the stream returned from `ExecutionPlan::execute` as well as add explicit documentation on how to cancel the result of calling `execute_stream` and similar methods ("drop the stream").
Via doctests
=> Minor: Add documentation about stream cancellation

datafusion-examples/examples/advanced_udwf.rs, datafusion/core/tests/user_defined/user_defined_window_functions.rs, datafusion/expr/src/expr_fn.rs, datafusion/expr/src/udwf.rs, datafusion/proto/tests/cases/roundtrip_logical_plan.rs
Closes #8734 .
Clean internal implementation of WindowUDF to use WindowUDFImpl
=> Clean internal implementation of WindowUDF

datafusion/physical-expr/src/array_expressions.rs, datafusion/sqllogictest/test_files/array.slt
=> feat: support `largelist` in `array_to_string`

datafusion-cli/src/print_options.rs
Closes #.
If a streaming execution sends an error, the loop finishes as no error was received, thus this was a bug.
Handling the error if the stream sends an error.
Yes
Improved error handling.
=> [MINOR] CLI error handling on streaming use cases

datafusion/common/src/hash_utils.rs, datafusion/sqllogictest/test_files/dictionary.slt
Bug in https://github.com/apache/arrow-datafusion/pull/8552
closes https://github.com/apache/arrow-datafusion/pull/8769
Failed test is added
=> Minor: Fix incorrect indices for hashing struct

datafusion/core/src/lib.rs
N/A
While working on some other documentation improvements this morning I realized that some of the cool features of DataFusion like `TreeNode`, `ExprSimplifier`, `PruningPredicate` and `cp_solver` were not mentioned on the doc / architecture page which might make them harder to find
Add doc links to these features in the main crate library page
Existing doc tests
Just docs, no code change
=> Minor: Improve library docs to mention TreeNode, ExprSimplifier, PruningPredicate and cp_solver

docs/source/_templates/layout.html, docs/source/conf.py
Closes https://github.com/apache/arrow-datafusion/issues/8755
Comply with ASF branding guidelines
Add a footer to https://arrow.apache.org/datafusion/
I tested them locally
Website change
=> Add Apache attribution to site footer

.github/workflows/rust.yml, datafusion/common/src/column.rs, datafusion/common/src/dfschema.rs, datafusion/common/src/error.rs, datafusion/core/src/dataframe/mod.rs, datafusion/expr/src/logical_plan/builder.rs, datafusion/sql/src/planner.rs, datafusion/sql/src/statement.rs, datafusion/sql/tests/sql_integration.rs
Closes partially #7360.
Continue covering Datafusion Errors with error macros supporting optional backtrace
introduced `schema_err!` and `schema_datafusion_err!` macros with optional backtrace, to represent `Err(DatafusionError::SchemaError)` and `DatafusionError::SchemaError(_)`
Yes
No
=> Add `schema_err!` error macros with optional backtrace

datafusion/core/tests/path_partition.rs, datafusion/physical-plan/src/aggregates/group_values/row.rs, datafusion/physical-plan/src/aggregates/mod.rs, datafusion/physical-plan/src/aggregates/row_hash.rs, datafusion/sqllogictest/test_files/aggregate.slt, datafusion/sqllogictest/test_files/dictionary.slt
This closes https://github.com/apache/arrow-datafusion/issues/8738 by reverting https://github.com/apache/arrow-datafusion/pull/8291
~I am not sure if this is the right fix -- I need to write some more tests / understand the problem more fully, but I wanted to get the PR up as I had the code.~
To be clear, this change fixes a functional regression (a query that used to run no longer does), as descsribed in https://github.com/apache/arrow-datafusion/issues/8738
What I would like to do is to reopen https://github.com/apache/arrow-datafusion/issues/7647 and then we can work on reapply that change, ensuring the LogicalPlan and PhysicalPlan schemas match as well as maybe being more dilligent about performance testing
=> Fix regression by reverting Materialize dictionaries in group keys

datafusion/physical-expr/src/array_expressions.rs
=> Minor: Fix error messages in array expressions

datafusion/optimizer/src/optimize_projections.rs
Follow on to https://github.com/apache/arrow-datafusion/pull/8774 / https://github.com/apache/arrow-datafusion/issues/8735
The core issue in https://github.com/apache/arrow-datafusion/issues/8735 was that one Expr type was forgotten. @haohuaijin restored the extra `Expr` type ❤️ 
However, I think there is still some danger than a new Expr type would be added and forgotten to be added to this area. Thus I propose using the standard `TreeVisitor` to do the recursion
Use `inspect_expr_pre` instead of manual recursion
No
=> Minor: Use standard tree walk in Projection Pushdown

datafusion-examples/README.md, datafusion-examples/examples/advanced_udaf.rs, datafusion/core/tests/user_defined/user_defined_aggregates.rs, datafusion/core/tests/user_defined/user_defined_scalar_functions.rs, datafusion/expr/src/expr_fn.rs, datafusion/expr/src/lib.rs, datafusion/expr/src/udaf.rs, datafusion/expr/src/udwf.rs, datafusion/optimizer/src/analyzer/type_coercion.rs, datafusion/optimizer/src/common_subexpr_eliminate.rs, datafusion/proto/tests/cases/roundtrip_physical_plan.rs, docs/source/library-user-guide/adding-udfs.md
=> Implement trait based API for define AggregateUDF

datafusion/common/src/error.rs
Part of https://github.com/apache/arrow-datafusion/issues/7013
Inspired by https://github.com/apache/arrow-datafusion/pull/8781 I have seen several cases where people are confused about when to use `DataFusionError::Internal` vs `DataFusionError::Plan`. etc
Update doc comments for `DataFusionError`, making liberal use of @crepererum 's great description https://github.com/apache/arrow-datafusion/pull/8781#discussion_r1444685792
existing coverage
better documentation. No functional changes
=> Minor: Improve `DataFusionError` documentation

datafusion/physical-plan/src/values.rs, datafusion/sqllogictest/test_files/select.slt
Closes #8763.
In `ValuesExec::try_new`, we use the schema of `ValuesExec` and **null arrays** to construct a placeholder batch. 
https://github.com/apache/arrow-datafusion/blob/dd4263f843e093c807d63edf73a571b1ba2669b5/datafusion/physical-plan/src/values.rs#L56-L64
This batch placeholder is used to evaluate the physical expressions in Values.
But users can define a schema containing non-nullable fields for `ValuesExec` just like issue #8763, which is in conflict with null arrays.
```rust
let field = Field::new("a", DataType::Int32, false);
let schema = Schema::new(vec![field]);
let df_schema = DFSchema::try_from(schema.clone()).unwrap();
let values = vec![vec![Expr::Literal(ScalarValue::Int32(Some(1)))]];
let values_plan = LogicalPlan::Values(Values {
schema: df_schema.clone().into(), …
```
=> fix: failed to create ValuesExec with non-nullable schema

docs/source/user-guide/sql/scalar_functions.md
None
Fix typo in [scalar functions documentation](https://arrow.apache.org/datafusion/user-guide/sql/scalar_functions.html#array-pop-front).
=> Minor: array_pop_first should be array_pop_front in documentation

datafusion/core/src/datasource/physical_plan/parquet/metrics.rs, datafusion/core/src/datasource/physical_plan/parquet/mod.rs, datafusion/core/src/datasource/physical_plan/parquet/row_groups.rs, datafusion/core/src/physical_optimizer/pruning.rs, datafusion/core/tests/parquet/mod.rs, datafusion/core/tests/parquet/row_group_pruning.rs, datafusion/core/tests/sql/explain_analyze.rs, datafusion/physical-expr/src/utils/guarantee.rs, datafusion/sqllogictest/test_files/repartition_scan.slt
Closes #8767, 
Closes #8768
- I split the `row_groups_pruned` metric into two parts, including `row_groups_pruned_sbbf` and `row_groups_pruned_sbbf`.
-  add an integration test in `row_group_pruning.rs`， by checking value of `row_groups_pruned_sbbf` and `row_groups_pruned_sbbf`
- display `LiteralGuarantees` of  `ParquetExec`
=> feat: Add bloom filter metric to ParquetExec

docs/source/user-guide/sql/write_options.md
Fixes an issue with docs where a markdown table isn't being rendered correctly.
Currently https://arrow.apache.org/datafusion/user-guide/sql/write_options.html... 
After this PR...
=> fix: fix markdown table in docs

datafusion/core/src/physical_optimizer/join_selection.rs, datafusion/core/src/physical_optimizer/projection_pushdown.rs, datafusion/core/tests/sql/joins.rs, datafusion/physical-plan/src/joins/symmetric_hash_join.rs, datafusion/physical-plan/src/joins/test_utils.rs, datafusion/proto/proto/datafusion.proto, datafusion/proto/src/generated/pbjson.rs, datafusion/proto/src/generated/prost.rs, datafusion/proto/src/physical_plan/from_proto.rs, datafusion/proto/src/physical_plan/mod.rs, datafusion/proto/tests/cases/roundtrip_physical_plan.rs
Improves the condition on https://github.com/apache/arrow-datafusion/pull/8794#discussion_r1445868353 #.
Previous `SymmetricHashJoinExec` implementation did not require input ordering, thus this makes `SymmetricHashJoinExec` suboptimal when `target_partitions` is higher than one. 
If the child nodes (left or right side of the join) already have a defined order and the columns used in the filter predicate are ordered, the order of that side is kept. The identified order is then used in the `SymmetricHashJoinExec` to maintain bounded memory during join operations. However, if the child nodes do not have an inherent order, or if the filter columns are unordered, no specific order is required for the SymmetricHashJoinExec. This approach ensures that the symmetric hash join operation only …
=> Make benefits_from_input_partitioning Default in SHJ

datafusion-cli/src/exec.rs, datafusion-cli/src/main.rs
Closes #8808
For me the order of 'what does the execing, what's exec'd, then options` makes sense to me, but overally the goal of this PR is to make the order consistent.
Manual testing of built CLI, open to other options
Not sure how many are using the CLI code in their own projects, but this could break their code (albeit with an easy fix).
=> refactor: standardize exec_from funcs arg order

datafusion/core/src/physical_optimizer/pruning.rs
=> [Minor] extract const and add doc and more tests for in_list pruning

datafusion/core/src/physical_optimizer/combine_partial_final_agg.rs, datafusion/core/src/physical_optimizer/limited_distinct_aggregation.rs, datafusion/physical-plan/src/aggregates/mod.rs, datafusion/physical-plan/src/limit.rs
Closes #.
Aggregate algorithm depends on `aggr_expr.len` and `filter_expr.len()` being the same (They are iterated simultaneously with `zip`). As far as I know, their sizes cannot have different sizes from an SQL query. 
However, while writing unit tests, one can easily forget this invariant. This PR adds check for this assumption.
With this check, I recognized some of the unit tests, didn't consider this invariant. This PR fixes these tests also.
=> [MINOR]: Add size check for aggregate

pre-commit.sh
Sometimes my codes pass checks of pre-commit, but ci still fails. So I am wondering whether keeping the "clippy" consistent between  in pre-commit.sh and in CI would be beneficial.
=> Minor: chores: Update clippy in pre-commit.sh

datafusion-examples/examples/advanced_udf.rs, datafusion/expr/src/udf.rs, datafusion/physical-expr/src/udf.rs
Closes #8756 .
add monotonicity function, User can define fun monotonicity by themselves
=> Implement monotonicity for ScalarUDF

datafusion/core/src/datasource/file_format/csv.rs, datafusion/core/src/datasource/file_format/json.rs, datafusion/core/src/datasource/file_format/write/mod.rs, datafusion/core/src/datasource/file_format/write/orchestration.rs, datafusion/core/src/datasource/physical_plan/file_stream.rs
Closes #.
> In general, issuing a blocking call or performing a lot of compute in a future without yielding is problematic, as it may prevent the executor from driving other futures forward.
~~https://docs.rs/tokio/latest/tokio/task/fn.spawn_blocking.html~~
~~Previously, the serialization process was always asynchronous, even if there were no asynchronous calls involved, which was a CPU-bound operation. This is an anti-pattern.~~
This PR simplifies function signatures in `BatchSerializer`.
Make `BatchSerializer` sync ~~, and use it with `tokio::task::spawn_blocking`~~.
With existing tests.
No.
=> Serialize function signature simplifications

datafusion-examples/examples/expr_api.rs, datafusion/core/src/datasource/listing/helpers.rs, datafusion/core/src/datasource/listing/table.rs, datafusion/core/src/datasource/physical_plan/parquet/mod.rs, datafusion/core/src/datasource/physical_plan/parquet/row_filter.rs, datafusion/core/src/datasource/physical_plan/parquet/row_groups.rs, datafusion/core/src/execution/context/mod.rs, datafusion/core/src/physical_optimizer/pruning.rs, datafusion/core/src/physical_planner.rs, datafusion/core/src/test_util/parquet.rs, datafusion/core/tests/parquet/page_pruning.rs, datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs, datafusion/physical-expr/src/planner.rs, datafusion/physical-expr/src/utils/guarantee.rs
Closes #.
To create physical expression we require 2 sets of schemas:
- logical
- physical
Having 2 schemas is confusing in some sense, this PR is to create physical expression based on logical schema only.
The reason the logical schema was chosen is the schema contains more information than physical schema, for instance qualifier information.
Signature simplified for bunch of methods creating the physical expressions.
Yes, existing tests
The signature for pub `create_physical_expr` changed
=> Simplify physical expression creation API (not require schema)

datafusion/core/Cargo.toml, datafusion/core/src/datasource/listing/url.rs, datafusion/execution/src/object_store.rs, datafusion/physical-plan/Cargo.toml, datafusion/substrait/Cargo.toml, datafusion/wasmtest/Cargo.toml, datafusion/wasmtest/README.md
Related to https://github.com/apache/arrow-datafusion/pull/7633
Make more components to be `wasm-unknown-unknown` compatible.
About the background and motivation: I'm trying to continue my side project that builds a web playground based on wasm for datafuson https://github.com/waynexia/datafusion-playground
Add supports for `datafusion-physical-plan`, `datafusion-execution` and `datafusion`.
`datafusion-physical-plan` and `datafusion-execution` doesn't contain any logical changes. It works after I remove some unnecessary feature gates or dependence.
Some methods and logic in `datafusion` are commented out. The affected file is `datafusion/core/src/datasource/listing/url.rs`, all about parsing URL. This is a limitation from our dependence `url`. After some shallow investigates, I guess …
=> feat: add more components to the wasm-pack compatible list

datafusion/expr/src/aggregate_function.rs, datafusion/expr/src/type_coercion/aggregates.rs, datafusion/optimizer/src/analyzer/type_coercion.rs, datafusion/sqllogictest/test_files/aggregate.slt
The number of centroids must be an integer in `coerce_types`. Reflect that in the type signature.
Didn't create an issue for this one.
Currently when we try to pass a floating type as the number of centroids, we get a confusing error message, e.g.
> No function matches the given name and argument types `APPROX_PERCENTILE_CONT(Float64, Float64, Float64)`
And then later the exact same signature is listed among the candidates.
The reason is that the type signature is not in sync with the logic in `coerce_types`.
Changed the type signature of `ApproxPercentileCont` to be a combination of all numeric types and all integer types for the number of centroids.
I added a test but it's not really feasible to list all possible signatures in the test.
Only in terms of the type signature and error …
=> Fix ApproxPercentileCont signature

datafusion/core/src/dataframe/mod.rs
Closes #8800 .
Update `with_column_rename` method doc to describe case sensitive rename possibilities
=> Minor: Update `with_column_rename` method doc

docs/source/user-guide/cli.md
Part of #7013 
I was writing a blog post about DataFusion   https://github.com/apache/arrow-site/pull/457 and I wanted to highlight this feature that @Veeupup  added in https://github.com/apache/arrow-datafusion/issues/8367 but it wasn't documented
Document the function
N/A
More docs
=> Minor: Document `parquet_metadata` function

datafusion/common/src/dfschema.rs
BTreeMap gives stable iteration order, so we don't need to sort
Speeds up benchmarks in sql_planner.rs by 3-8%
CC @matthewmturner who seems interested in planning performance
<details>
<summary>Bench results</summary>
[~/code/arrow-datafusion/datafusion/core/benches]$ mold -run cargo bench --bench sql_planner --profile release-nonlto
logical_select_one_from_700
time:   [3.9136 ms 3.9249 ms 3.9376 ms]
change: [-8.2901% -7.9287% -7.5315%] (p = 0.00 < 0.05)
Found 6 outliers among 100 measurements (6.00%)
2 (2.00%) low mild
physical_select_one_from_700
time:   [20.597 ms 20.803 ms 21.054 ms]
change: [-8.4809% -6.9620% -5.4361%] (p = 0.00 < 0.05)
3 …
=> Speedup new_with_metadata by removing sort

datafusion/proto/src/logical_plan/from_proto.rs
Closes #.
This issue is called #8744 , but I am curious why it passed the ci 🤔
=> Minor: fix wrong function call

datafusion-examples/examples/advanced_udwf.rs, datafusion-examples/examples/simple_udwf.rs, datafusion/common/src/scalar.rs, datafusion/core/src/dataframe/mod.rs, datafusion/core/src/physical_optimizer/test_utils.rs, datafusion/core/tests/dataframe/mod.rs, datafusion/core/tests/fuzz_cases/window_fuzz.rs, datafusion/expr/src/udwf.rs, datafusion/expr/src/utils.rs, datafusion/expr/src/window_frame.rs, datafusion/expr/src/window_state.rs, datafusion/optimizer/src/analyzer/count_wildcard_rule.rs, datafusion/optimizer/src/push_down_projection.rs, datafusion/physical-expr/src/window/built_in.rs, datafusion/physical-expr/src/window/window_expr.rs, datafusion/physical-plan/src/windows/bounded_window_agg_exec.rs, datafusion/physical-plan/src/windows/mod.rs, datafusion/proto/src/logical_plan/from_proto.rs, datafusion/proto/tests/cases/roundtrip_logical_plan.rs, datafusion/proto/tests/cases/roundtrip_physical_plan.rs, datafusion/sql/src/expr/function.rs, datafusion/sqllogictest/test_files/window.slt, datafusion/substrait/src/logical_plan/consumer.rs
Closes #.
In streaming execution, window functions generate result when frame end is smaller than batch size (This guarantees that future rows may not extend up the current window frame). However, for causal window frame (e.g window frame that doesn't include future rows than the current row). We can generate results even if frame end is same with batch size. 
With this support we can decrease latency for causal queries.
This PR adds support for causality analysis for window frame to decrease latency and memory during generating window function results.
Yes
=> Determine causal window frames to produce early results.

datafusion/core/src/datasource/provider.rs
Correct the doc:
1. a wrong pushdown name
2. a typo
No, and they don't need a test since they are all docs.
No
=> docs: fix wrong pushdown name & a typo

datafusion/optimizer/src/common_subexpr_eliminate.rs, datafusion/optimizer/src/push_down_filter.rs, datafusion/optimizer/src/utils.rs, datafusion/sqllogictest/test_files/functions.slt, datafusion/sqllogictest/test_files/select.slt, datafusion/sqllogictest/test_files/tpch/q14.slt.part
Closes #8814 
as shown in #8814, in `CASE WHEN A THEN B ELSE C END` expr, the B and C only have one can run, 
so for query
```
select 
case when B.column1 > 0 then A.column1/B.column1 else 0 end as value1,
case when B.column1 > 0 and B.column2 > 0 then A.column1/B.column1 else 0 end as value3
from (select column1, column2 from users) as A ,  (select column1, column2 from users where column1 = 0) as B;
```
the `A.column1/B.column1` actually should not run, but we extract it as a common sub expr(see below plan), which results in `A.column1/B.column1` running and getting a divide zero error.
```
| initial_logical_plan                                       | Projection: CASE WHEN b.column1 > Int64(0) THEN a.column1 / b.column1 ELSE Int64(0) END AS value1, CASE WHEN b.column2 > Int64(0) THEN …
```
=> fix: don't extract common sub expr in `CASE WHEN` clause

benchmarks/bench.sh, benchmarks/queries/clickbench/README.md, benchmarks/queries/clickbench/README.txt, benchmarks/queries/clickbench/extended.sql, benchmarks/src/clickbench.rs
Closes https://github.com/apache/arrow-datafusion/issues/8860
I would like to have benchmarks that allow us to show improvements such as https://github.com/apache/arrow-datafusion/pull/8827 and https://github.com/apache/arrow-datafusion/pull/8849 are significant 
Add new "Extended" datafusion specific clickbench queries:
to run:
```shell
./benchmarks/bench.sh run clickbench_extended
```
Example:
```
***************************
DataFusion Benchmark Script
COMMAND: run
BENCHMARK: clickbench_extended
DATAFUSION_DIR: /Users/andrewlamb/Software/arrow-datafusion/benchmarks/..
BRACH_NAME: alamb_clickbench_extended
DATA_DIR: /Users/andrewlamb/Software/arrow-datafusion/benchmarks/data
RESULTS_DIR: /Users/andrewlamb/Software/arrow-datafusion/benchmarks/results/alamb_clickbench_extended …
```
=> Add "Extended" clickbench queries

datafusion/sqllogictest/test_files/arrow_typeof.slt
Closes #8305 
The issue is solved by arrow-rs 50.0
=> Minor: add tests for casts between nested `List` and `LargeList`

datafusion/proto/Cargo.toml, datafusion/proto/src/logical_plan/from_proto.rs, datafusion/proto/tests/cases/serialize.rs
Parts. #8847 
When I worked on #8847, there were wrong function calls in `parse_expr`, the ci did not notify it.
=> fix bug with `to_timestamp` and `InitCap` logical serialization, add roundtrip test between expression and proto, 

datafusion/core/src/datasource/physical_plan/file_stream.rs
Can be seen as a fix to #2990.
The `FileStream.file_reader` field is a generic type that implements the `FileOpener` trait, so it is kinda confusing to call it `file_reader` rather than `file_opener`.
#2291 tried to do some naming refactoring to this file, but it seems that @tustvold forgot to update this field name I guess?
And that doc comment was added in #1138, which is quite old and outdated.
1. rename `FileStream.file_reader` to `FileStream.file_opener`.
2. Update the doc for this field.
No
This field is private so I guess no.
=> refactor: rename FileStream.file_reader to file_opener & update doc

datafusion/sql/src/expr/value.rs, datafusion/sqllogictest/test_files/array.slt
=> Support array literal with scalar function

datafusion-cli/src/print_format.rs
Resolves https://github.com/apache/arrow-datafusion/issues/8702
This is a regression introduced in https://github.com/apache/arrow-datafusion/pull/8651 where if the first record batch happens to be empty data in non empty batches will not be printed. 
1. Fix bug
2. Add test
Yes, new tests
Fix bug
=> Fix `datafusion-cli` print output

datafusion/physical-plan/src/stream.rs
No
I was quite confused about how to this type when I first saw it, so let's add an example to make it more clear on its usage.
1. Add an example for `RecordBatchReceiverStreamBuilder`
2. Some other minor changes that may improve the doc
Yes, tested with `cargo t`
No
=> docs: add an example for RecordBatchReceiverStreamBuilder

datafusion-cli/src/print_format.rs
Draft as it build on https://github.com/apache/arrow-datafusion/pull/8895 
Related to https://github.com/apache/arrow-datafusion/issues/8702
Follow on to https://github.com/apache/arrow-datafusion/pull/8895 
While working on https://github.com/apache/arrow-datafusion/pull/8895 I found the tests somewhat hard to follow and it was hard for me to understand if there were existing tests that covered I was changing.
It was also hard top understand the coverage in general given how the tests were structured
1. Rework tests in print_format to be more explict
2. Add additional coverage for TSV and empty result printing
This PR is all tests (no code changes)
No
=> Improve `datafusion-cli` print format tests

datafusion/physical-expr/src/array_expressions.rs, datafusion/sqllogictest/test_files/array.slt
Related #8625 #8317 Thanks @jayzhan211 effort, we can remove `NULL` in `array-append` and `array-prepend`
=> Minor: remove null in `array-append` and `array-prepend`

datafusion/common/src/hash_utils.rs, datafusion/common/src/scalar.rs, datafusion/common/src/utils.rs, datafusion/expr/src/utils.rs, datafusion/sql/src/expr/arrow_cast.rs, datafusion/sqllogictest/test_files/arrow_typeof.slt
Closes #8343
- add hash function for 'FixedSizeList'
- support cast between `FixedSizeList` and `List` / `LargeList`
=> Add support for FixedSizeList type in `arrow_cast`, hashing

datafusion/core/src/physical_optimizer/aggregate_statistics.rs, datafusion/sqllogictest/test_files/aggregate.slt
=> aggregate_statistics should only optimize MIN/MAX when relation is not empty

docs/source/user-guide/sql/scalar_functions.md
N/A
@mhilton  noticed this as part of an internal discussion where we were confused about the output values of `date_bin` for timestamps with timezones (as the default argument is for the unix EPOCH in UTC)
The default is defined here: https://github.com/apache/arrow-datafusion/blob/3a9e23d138c935ffea68408899016c9323aa0f36/datafusion/physical-expr/src/datetime_expressions.rs#L534C1-L538
Document the third parameter to `date_bin` better
existing tests
Better [documentation](https://arrow.apache.org/datafusion/user-guide/sql/scalar_functions.html#date-bin)
=> Minor: Document third argument of `date_bin` as optional and default value

datafusion/core/tests/parquet/row_group_pruning.rs
Related #8880.  when i implements 8880 cause lot ut fail, because not distinguish between parquet row group pruning by statistics or bloom filter
=> Minor: distinguish parquet row group pruning type in unit test

datafusion/execution/src/object_store.rs
Closes #.
`default()` uses `new()` and `new` uses `default()`
Breaks the recursive initialize method. My stupid error...
=> fix: recursive initialize method

datafusion/core/src/physical_planner.rs, datafusion/core/tests/fuzz_cases/window_fuzz.rs, datafusion/expr/src/built_in_window_function.rs, datafusion/physical-expr/src/window/cume_dist.rs, datafusion/physical-expr/src/window/lead_lag.rs, datafusion/physical-expr/src/window/nth_value.rs, datafusion/physical-expr/src/window/ntile.rs, datafusion/physical-expr/src/window/rank.rs, datafusion/physical-expr/src/window/row_number.rs, datafusion/physical-plan/src/windows/mod.rs, datafusion/proto/tests/cases/roundtrip_physical_plan.rs, datafusion/sqllogictest/test_files/window.slt
Closes #.
Before the PR the Datafusion derives the output datatypes for builtin functions twice. 
Initially set in `BuiltInWindowFunction::return_type` the output datatype redefined in other places:
- in built in function implementations, like row_number, rank, etc
- on physical planner phase like lag, lead
This PR is to unify output types to be defined in 1 single place and be transferred through the schema. 
Another good benefit of it is other systems that embed DataFusion as an engine can now use its datatypes by constructing expected schema.
Datatype definition unified, covered with new tests, some other minor optimizations
Yes
No
=> Simplify windows builtin functions return type

datafusion/expr/src/expr.rs, datafusion/optimizer/src/common_subexpr_eliminate.rs, datafusion/sqllogictest/test_files/select.slt
Closes #8874
see #8874
before this pr
```
❯ explain select coalesce(1, y/x), coalesce(2, y/x) from t;
+---------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| plan_type     | plan                                                                                                                                                                                                  |
+---------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| logical_plan  | Projection: …
```
=> fix: common_subexpr_eliminate rule should not apply to short-circuit expression

.github/actions/setup-rust-runtime/action.yaml, .github/workflows/rust.yml
Closes #.
https://github.com/apache/arrow-datafusion/commit/428973732b14055971604204bf3dcd605120b3dd sped win ci up, running at 33min:
- https://github.com/apache/arrow-datafusion/actions/runs/7433532490
Following commit https://github.com/apache/arrow-datafusion/commit/dd4263f843e093c807d63edf73a571b1ba2669b5 had runtime of 39min:
- https://github.com/apache/arrow-datafusion/actions/runs/7433765725
Subsequent runs fall around 39-42min range
Until this commit https://github.com/apache/arrow-datafusion/commit/d9a1d4261f78dfd3ead235d6b850c64e0ae9bec6 which causes runtime of 47min:
- https://github.com/apache/arrow-datafusion/actions/runs/7494637547
Subsequent runs (up to latest main) fall around 44-48min range
Fix accidental regression by …
=> [CI] Fix RUSTFLAGS

datafusion/core/tests/parquet/row_group_pruning.rs
Closes #8922.
Since the original test in datafusion/core/tests/parquet/row_group_pruning.rs is hard to read, I use a test structure mentioned by lamb in [comment](https://github.com/apache/arrow-datafusion/pull/8921#discussion_r1460358000) to refracture the test
yes
=> fix: issue #8922 make row group test more readable

datafusion/physical-expr/src/functions.rs
Closes https://github.com/apache/arrow-datafusion/issues/8973
CI checks are failing on main: https://github.com/apache/arrow-datafusion/actions/runs/7628515989/job/20779877406
```
error: use of deprecated function `functions::make_scalar_function`: Implement your function directly in terms of ColumnarValue or use `ScalarUDF` instead
--> datafusion/physical-expr/src/functions.rs:562:17
|
562 |                 make_scalar_function(string_expressions::instr::<i32>)(args)
|                 ^^^^^^^^^^^^^^^^^^^^
|
= note: `-D deprecated` implied by `-D warnings`
= help: to override `-D warnings` add `#[allow(deprecated)]`
```
I believe this is a logical conflict between https://github.com/apache/arrow-datafusion/pull/8862 and https://github.com/apache/arrow-datafusion/pull/8878
Fix logical …
=> Fix clippy failures: error: use of deprecated function `functions::make_scalar_function

datafusion/core/src/physical_planner.rs, datafusion/core/tests/fuzz_cases/window_fuzz.rs, datafusion/physical-plan/src/windows/mod.rs
Closes #.
With the [PR8920](https://github.com/apache/arrow-datafusion/pull/8920) `create_window_expr` function refers to window_schema to get its window expr output type. However, at this stage it should calculate its output type using `input_schema`. With this PR, function only refers to its input schema.
=> [MINOR]: Update create_window_expr to refer only input schema

datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs, datafusion/optimizer/src/simplify_expressions/simplify_exprs.rs, datafusion/physical-expr/src/expressions/case.rs, datafusion/sqllogictest/test_files/arrow_typeof.slt, datafusion/sqllogictest/test_files/math.slt, datafusion/sqllogictest/test_files/scalar.slt, datafusion/sqllogictest/test_files/select.slt
Closes #8909
see #8910 and #8909 ,
before this pr, in simplify_espression we try to fold the expression, but this can result some error, for example 
```sql
select case 1 when 2 then 4/0 end;
```
`4/0` never reach in runtime.
so in this PR, if we encounter an error during fold expression, return the origin expression, and the error will occur in runtime if it is a real error(not the short-circuit problem).
Note: this pr doesn't solve #8910 , due to #8927
test by existing tests
=> Don't error in simplify_expressions rule

datafusion/common/src/param_value.rs, datafusion/core/tests/sql/select.rs, datafusion/expr/src/logical_plan/plan.rs
Closes #8976.
It should be possible for the types of parameter values and placeholders to be different, as long as the `ScalarValue` is coercible to the `Expr::Placeholder`s data type.
Removal of the eager `==` check on data types, which allows type coercion to happen later in planning.
The `data_type` argument to `ParamValues::get_placeholders_with_values` is currently unused. If we decide to remove it that would be a user-facing change to the API. 
Alternatively, instead of deleting the eager check and leaving the `data_type` parameter unused, we could improve the eager check with code borrowed from [the type coercion module](https://github.com/kallisti-dev/arrow-datafusion/blob/81f8078e49d1b9d877967de18960e993e5b3ee6a/datafusion/expr/src/type_coercion/functions.rs#L226-L234)  but I'm …
=> fix: allow placeholders to be substited when coercible

datafusion/core/src/catalog/mod.rs, datafusion/core/src/catalog/schema.rs
related to #7013 
The topic about how to implement remote catalogs has come up several times (most recently in https://github.com/apache/arrow-datafusion/discussions/8887) so it would be good to update the docs to provide more detail
1. Improve docstrings for various catalog related traits
2. Add background, examples, and notes on how to implement a remote catalog to [`CatalogProvider`]
covered by CI tests
Better docs
=> Minor: improve CatalogProvider documentation with rationale and info about remote catalogs

datafusion-examples/README.md, datafusion-examples/examples/to_timestamp.rs, docs/source/user-guide/sql/scalar_functions.md
Updated documentation concerning to_timestamp scalar function  including adding missing link in the datafusion-examples/README file.
Closes #8980.
=> Improve to_timestamp docs

datafusion/optimizer/src/analyzer/type_coercion.rs, datafusion/physical-expr/src/expressions/not.rs, datafusion/sqllogictest/test_files/scalar.slt
Closes #8965.
in `TypeCoercionRewriter` return an error if the argument to not can't be coerced to Boolean
=> NOT operator not return internal error when args are not boolean value

benchmarks/queries/clickbench/README.md, benchmarks/queries/clickbench/extended.sql
Part https://github.com/apache/arrow-datafusion/issues/5472 
We don't have great benchmark coverage for `COUNT(DISTINCT <String>)` where the lengths of the strings are small. This came up as part of https://github.com/apache/arrow-datafusion/pull/8849
1. Add two new queries in "extended" clickbench suite: (see #8861) that cover count distinct for short string columns
I tested them manually
No, this is benchmark only
=> Minor: Add new Extended ClickBench benchmark queries

datafusion/execution/src/memory_pool/mod.rs
Related to https://github.com/apache/arrow-datafusion/issues/587
@SteveLauC  asked about this on https://github.com/apache/arrow-datafusion/issues/587#issuecomment-1895387394
and I realized the rationale and high level design of the memory management system wasn't documented anywhere
Add doc comments to `MemoryPool` to add more background and rationale
Covered by existing doc comments
Better docs
=> Minor: Document memory management design on `MemoryPool`

datafusion/physical-expr/src/window/lead_lag.rs, datafusion/sqllogictest/test_files/window.slt
Closes #.
Fix the failed query LEAD/LAG window functions when default value null
```
select lead(a, 1, null) over (order by a) from (select 1 a union all select 2 a)
```
returns internal error although it is a valid query
Adding Null as list of allowed datatypes for default value
Yes
No
=> Fix LEAD/LAG window functions when default value null

datafusion/core/src/physical_optimizer/aggregate_statistics.rs, datafusion/sqllogictest/test_files/aggregate.slt
Closes #.
We can optimize MIN/MAX in the cases of input relation is empty.
=> Optimize MIN/MAX when relation is empty

Cargo.toml, datafusion-cli/Cargo.lock, datafusion/sql/src/parser.rs, datafusion/sql/src/planner.rs, datafusion/sql/src/statement.rs
N/A
Update to latest dependency, unblock merge of https://github.com/apache/arrow-datafusion/pull/8894 from @gruuya 
1. Update to sqlparser `0.42.0`
2. Update parser for changes in ast
=> Update to sqlparser `0.42.0`

datafusion/optimizer/src/optimize_projections.rs, datafusion/sqllogictest/test_files/select.slt
Closes [#8978](https://github.com/apache/arrow-datafusion/issues/8978).
Aggregate requires at least one grouping or aggregate expression. In these cases, we do not optimize away all of the aggregate expressions, we keep one aggregate expression. However, because of the place of empty check, we didnot propagate its requirement below. This PR moves this check above so that its requirements can be propagated below.
Yes
=> [MINOR]: Fix Optimize Projections Bug

datafusion/sqllogictest/test_files/aggregates_topk.slt
Closes [#8845](https://github.com/apache/arrow-datafusion/issues/8845).
=> Make Topk aggregate tests deterministic

datafusion/sql/src/planner.rs, datafusion/sql/tests/sql_integration.rs, datafusion/sqllogictest/test_files/cte.slt, datafusion/sqllogictest/test_files/select.slt
Closes #.
Table alias will process uppercase alias into lowercase. This PR will fix it.
`TableReference::parse_str` method converts uppercase to lowercase. The alias here has already undergone `normalize`, so we can directly create a TableReference as a parameter.
Yes
No
=> bug: Datafusion doesn't respect case sensitive table references

datafusion/core/src/lib.rs
Part of #7013 
The topic of thread scheduling and why not use Rayon or morsel driven parallelism has come up several times, most recently in the Discord channel: https://discord.com/channels/885562378132000778/1166447479609376850/1198721509842235402
I would like to document what is going on so that we can refer people to the documentation when these questions inevitably arise in the future
1. Add a note on pull execution and why Datafusion doesn't implement morsel driven paralleism directly
2. Add a note about using tokio as the thread pool
Existing CI checks
More docs
=> Document parallelism and thread scheduling in the architecture guide

datafusion/core/src/physical_optimizer/projection_pushdown.rs, datafusion/sqllogictest/test_files/select.slt
Closes #9004.
When source projections are none, it means it projects all columns in its file schema. This case was not properly handled.
Replace None's with all indices in file schema.
Yes, an slt test is added similar to the one in the issue.
=> Fix None Projections in Projection Pushdown

datafusion/common/src/scalar.rs, datafusion/physical-expr/src/window/lead_lag.rs, datafusion/sqllogictest/test_files/window.slt
Closes #8307.
Noticed this when reviewing #8989. Currently we only support default value with Int64 data type for Lead and Lag window functions. This patch enables other data types to be used as default value.
=> Lead and Lag window functions should support default value with datatype other than Int64

README.md
Fix the wrong license badge in README
Polish the discord badge: replace the URL with the discord server invite link.
=> chore: fix license badge in README

datafusion/optimizer/src/optimizer.rs
This is one-line fix: The assert_schema_is_the_same error will now report prev_plan / new_plan in the correct order.
Closes #9010.
When debugging logical plan optimization change errors, it's important to know the correct values of prev_plan / new_plan so further investigation is can move quickly.
No. This change will not affect the API.
No. This change will not affect the API.
=> Minor: fix: #9010 - Optimizer schema change assert error is incorrect

docs/source/user-guide/sql/scalar_functions.md
Minor doc update where it looks like the summary of `array_position` is a duplicate of `repeat`.
Small update to the markdown.
Slight doc change.
=> docs: fix array_position docs

datafusion/common/src/stats.rs, datafusion/physical-plan/src/joins/utils.rs
Closes #9006.
Sometimes an ineact row count can be smaller than the exact null count which leads to a panic.
Do a checked subtraction to get the max distinct count estimate, and if it over(under)flows return Inexact(0).
They are tested against the case presented in #9006, and there's a unit test added.
Avoid panic during execution.
=> Safeguard against potential inexact row count being smaller than exact null count

datafusion/sqllogictest/src/test_context.rs, datafusion/sqllogictest/test_files/scalar.slt
N/A
Make the implementation of this test simpler and more localized.
Move the creation of the nan_table from Rust to slt.
Yes, existing tests.
No
=> sqllogictest: move the creation of the nan_table from Rust to slt

datafusion-cli/src/exec.rs, datafusion-cli/src/helper.rs, datafusion-cli/src/highlighter.rs, datafusion-cli/src/lib.rs, datafusion-cli/src/main.rs, datafusion-cli/src/print_options.rs, docs/source/user-guide/cli.md
Closes #.
The syntax highlight has been introduced in https://github.com/apache/arrow-datafusion/pull/8918. Thanks again @trungda 
Some users is not comfortable with new syntax highlight, so the PR makes it optional. The user can enable coloring providing color flag ```datafusion-cli --color```
For now the syntax highlight put as disabled by default, my humble vision its a little bit experimental and we may want to improve the color schema to be more smooth.
introduced NoColor strategy and the color provider gets enabled by the ```--color``` flag
Yes,  manually
No
=> feat: Disable client console highlight by default

datafusion/proto/src/physical_plan/to_proto.rs, datafusion/proto/tests/cases/roundtrip_physical_plan.rs
N/A
Attempting to encode physical plans with string_agg were erroring.
Just adds in an extra downcast for encoding string_agg.
Yes, added in a test for roundtripping.
Encoding physical plans with string_agg won't error now.
=> Properly encode STRING_AGG, NTH_VALUE in physical plan protobufs

datafusion/physical-expr/src/equivalence/properties.rs
Closes #.
Currently the CI failed (https://github.com/apache/arrow-datafusion/actions/runs/7688676073/job/20950251248?pr=9031) because:
```
error: use of deprecated method `indexmap::IndexSet::<T, S>::remove`: `remove` disrupts the set order -- use `swap_remove` or `shift_remove` for explicit behavior.
--> datafusion/physical-expr/src/equivalence/properties.rs:733:32
|
733 |                 search_indices.remove(idx);
|                                ^^^^^^
|
= note: `-D deprecated` implied by `-D warnings`
= help: to override `-D warnings` add `#[allow(deprecated)]`
```
=> Fix the clippy error of use of deprecated method

datafusion/execution/src/memory_pool/mod.rs, datafusion/execution/src/memory_pool/proxy.rs
Part of #7013 
I forgot about these traits and while rediscovering them I felt I could try and make them more discoverable via some documentation. 
Add / improve documentation
Doc tests (no code changes)
=> Minor: Improve memory helper trait documentation

datafusion/physical-expr/src/string_expressions.rs, datafusion/sqllogictest/test_files/functions.slt
Closes #9053
Yes, added sql tests with unicode characters
No,
=> fix issue where upper and lower functions only work correctly on ascii character 

benchmarks/bench.sh
just small spelling etc to bench.sh. what a great helper for comparing performance between branches!
=> Minor: small updates to bench.sh

datafusion/optimizer/src/analyzer/type_coercion.rs
=> Chore: explicitly list out all Expr types in TypeCoercionRewriter::mutate

datafusion/expr/src/logical_plan/builder.rs, datafusion/expr/src/logical_plan/plan.rs, datafusion/expr/src/tree_node/plan.rs, datafusion/expr/src/utils.rs, datafusion/optimizer/src/analyzer/rewrite_expr.rs, datafusion/optimizer/src/analyzer/type_coercion.rs, datafusion/optimizer/src/eliminate_outer_join.rs, datafusion/optimizer/src/optimize_projections.rs, datafusion/optimizer/src/optimizer.rs, datafusion/optimizer/src/push_down_filter.rs, datafusion/optimizer/src/push_down_limit.rs, datafusion/optimizer/src/simplify_expressions/simplify_exprs.rs, datafusion/optimizer/src/unwrap_cast_in_comparison.rs, datafusion/optimizer/src/utils.rs
Closes #.
Investigating why the logical planner seems to run out of available stack depth, I saw that recursive cloning is unfortunately quite prevalent in this part of the codebase.
Some internal helper function signatures, their implementations, and the `with_new_exprs` API is changed to get owned `LogicalPlan` objects to avoid unnecessary recursive cloning.
Yes, by existing tests (no new features are added).
The `with_new_exprs` API is slightly changed from taking in a slice (which results in unnecessary recursive cloning) to an owned vector.
=> Remove some recursive cloning from logical planning

datafusion-examples/README.md, datafusion-examples/examples/make_date.rs, datafusion/expr/src/built_in_function.rs, datafusion/expr/src/expr_fn.rs, datafusion/physical-expr/src/datetime_expressions.rs, datafusion/physical-expr/src/functions.rs, datafusion/proto/proto/datafusion.proto, datafusion/proto/src/generated/pbjson.rs, datafusion/proto/src/generated/prost.rs, datafusion/proto/src/logical_plan/from_proto.rs, datafusion/proto/src/logical_plan/to_proto.rs, datafusion/sqllogictest/test_files/timestamps.slt, docs/source/user-guide/sql/scalar_functions.md
Closes #9024
Yes, in code and sql logic tests.
A new make_date function is available, documented in user guide with examples in the datafusion-examples module.
=>  Add a make_date function

datafusion/core/src/physical_optimizer/projection_pushdown.rs, datafusion/core/tests/user_defined/user_defined_scalar_functions.rs, datafusion/physical-expr/src/functions.rs, datafusion/physical-expr/src/planner.rs, datafusion/physical-expr/src/scalar_function.rs, datafusion/physical-expr/src/udf.rs, datafusion/proto/src/physical_plan/from_proto.rs, datafusion/proto/tests/cases/roundtrip_physical_plan.rs
=> ScalarUDF with zero arguments should be provided with one null array as parameter

datafusion-examples/README.md, datafusion-examples/examples/csv_sql_streaming.rs, datafusion/common/src/test_util.rs, docs/source/user-guide/sql/ddl.md
Improves the situation on epic:[#9016](https://github.com/apache/arrow-datafusion/issues/9016)
It closes first and second tickets
Yes
=> Add documentation for streaming usecase

datafusion/physical-expr/src/expressions/negative.rs, datafusion/sqllogictest/test_files/scalar.slt
Closes https://github.com/apache/arrow-datafusion/issues/9060
For non-numeric/non-interval/non-timestamp types, we should gracefully handle and return a meaningful error message.
Handle error instead of panicking.
added unit test + sqllogictest + manually
```
❯ select -'100';
Error during planning: Negation only supports numeric, interval and timestamp types
```
=> Handle invalid types for negation

datafusion/physical-expr/src/datetime_expressions.rs
Follow on to https://github.com/apache/arrow-datafusion/pull/9040
Implement code suggestion I had while reviewing: https://github.com/apache/arrow-datafusion/pull/9040#discussion_r1470280245
There are several other uses of `unwrap` in datetime_expressions.rs that can probably be removed for cleaner code, but I don't think it is critical. 
Minor refactor to remove some `unwrap`
Covered by existing tests 
No
=> Minor: reduce unwraps in datetime_expressions.rs

datafusion/execution/src/memory_pool/proxy.rs
Closes https://github.com/apache/arrow-datafusion/issues/9057
While writing documentation as suggested by @crepererum  on https://github.com/apache/arrow-datafusion/pull/9025#discussion_r1469361209 I found that the accounting with `push_accounted` and  `allocated_size` were different and inconsistent
1. Add examples + tests
2. Remove custom doubling strategy (use the default rust Vec implementation)
Yes, with doc tests
Allocation accounting is now different
=> Remove custom doubling strategy + add examples to `VecAllocEx`

docs/source/user-guide/introduction.md
Add another user to the known users list
cc @philippemnoel
=> Minor: Add ParadeDB to the list of users

datafusion/optimizer/src/optimize_projections.rs
Closes #.
In the [review](https://github.com/apache/arrow-datafusion/pull/8960#discussion_r1471574267) @joroKr21 pointed a place where we do not check for trivial expression. With this PR, I have moved the code to decide whether a projection is necessary or not to its own function. By this way, we can be more explicit. Inconsistent usages could be decreased.
Why are you proposing this change? If this is already explained clearly in the issue then this section is not needed.
Explaining clearly why changes are proposed helps reviewers understand your changes and offer better suggestions for fixes.  
-->
=> [MINOR]: Add check for unnecessary projection

datafusion/physical-expr/src/datetime_expressions.rs
Closes #.
releateto #8781 
change the internal_err maroc in `datetime_expression.ts` to exec_err!
no
no
=> refer to #8781, convert the internal_err! in datetime_expression.rs to exec_err!

docs/source/user-guide/introduction.md
N/A
The previous repository / project name of InfluxDB IOx have changed to InfluxDB 3.0, so let's update the documentation to reflect that
Update https://arrow.apache.org/datafusion/user-guide/introduction.html#known-users with correct link
=> Update InfluxDB links in Known Users section of documentation

datafusion/core/src/physical_optimizer/projection_pushdown.rs, datafusion/sqllogictest/test_files/join.slt
Closes #9091.
`projection_pushdown` rule uses function `update_expr` to check if a plan's expressions could be updated with projection expressions. The function only checks column name so if there are columns with same name, the check will return incorrect `RewrittenValid` state. Column index should be checked too in the function `update_expr`.
=> Fix update_expr for projection pushdown

Cargo.toml, datafusion-cli/Cargo.lock, datafusion/physical-expr/Cargo.toml, datafusion/physical-expr/src/regex_expressions.rs
Closes #9106
Code cleanup.
Code removal, minor code cleanup, toml file updates.
Yes
No.
=> Cleanup regex_expressions.rs to remove _regexp_match function 

datafusion-examples/examples/expr_api.rs, datafusion/expr/src/expr_schema.rs, docs/source/library-user-guide/working-with-exprs.md
Closes #7725
Make it easier to understand what the `get_type` returns
An extra example in  `datafusion-examples/examples/expr_api.rs`
Docscring in `datafusion/expr/src/expr_schema.rs`
A paragraph in `docs/source/library-user-guide/working-with-exprs.md`
Only documentation and an example, no breaking changes
=> docs: add docs and example showing how to get the expression data type

datafusion/core/src/datasource/listing_table_factory.rs, datafusion/sqllogictest/test_files/insert_to_external.slt
Closes #8547 .
See issue for details
Options `single_file`, `append_new_files`  and `create_local_path`  are removed already. This is to remove the Backwards Compatibility so that providing these options will not work now.
Yes
No
=> Remove External Table Backwards Compatibility Options

datafusion/expr/src/built_in_function.rs, datafusion/physical-expr/src/array_expressions.rs, datafusion/sqllogictest/test_files/array.slt
=> feat: support `LargeList` in `flatten`

datafusion/physical-expr/src/datetime_expressions.rs
#9089. It may not close it but could be a stepping stone towards more optimal version.
The change shows significant bench performance improvement
- Baseline/before
```
make_date_col_col_col_1000
time:   [12.829 µs 12.866 µs 12.907 µs]
Found 12 outliers among 100 measurements (12.00%)
4 (4.00%) low mild
5 (5.00%) high severe
make_date_scalar_col_col_1000
time:   [11.800 µs 11.830 µs 11.866 µs]
Found 13 outliers among 100 measurements (13.00%)
1 (1.00%) low severe
2 (2.00%) low mild
6 (6.00%) high mild
make_date_scalar_scalar_col_1000
time:   [10.730 µs 10.755 µs 10.781 µs]
Found 10 outliers among 100 measurements (10.00%)
9 (9.00%) high mild
make_date_scalar_scalar_scalar
time:   [1.0802 µs 1.0936 µs 1.1060 µs]
```
- After …
=> feat: improve `make_date` performance

datafusion/core/src/datasource/file_format/parquet.rs
=> Refactor min/max value update in Parquet statistics

datafusion-cli/Dockerfile
Part of https://github.com/apache/arrow-datafusion/issues/8743
I didn't completely update rust versions in https://github.com/apache/arrow-datafusion/pull/8997, as pointed out by  @Omega359  https://github.com/apache/arrow-datafusion/pull/8997#issuecomment-1927094492
Update Dockerfile to use rust 1.72
No (it might be good to add some sort of short CI check that the rust versions are consistent)
=> Fix Dockerfile min rust version to 1.72

datafusion/core/src/datasource/listing/table.rs, datafusion/core/tests/parquet/schema.rs
Closes #9081.
Fix for schema metadata retrieval when listing parquet table as explained in the issue. 
Yes.
=> fix: schema metadata retrieval when listing parquet table

datafusion/common/src/scalar.rs, datafusion/sqllogictest/test_files/array.slt
=> Fix NULL values in FixedSizeList creation

datafusion/common/src/scalar.rs, datafusion/core/src/physical_planner.rs, datafusion/core/tests/user_defined/user_defined_aggregates.rs, datafusion/physical-expr/src/aggregate/array_agg_distinct.rs, datafusion/physical-expr/src/aggregate/array_agg_ordered.rs, datafusion/physical-expr/src/aggregate/nth_value.rs, datafusion/proto/proto/datafusion.proto, datafusion/proto/src/generated/pbjson.rs, datafusion/proto/src/generated/prost.rs, datafusion/proto/src/logical_plan/from_proto.rs, datafusion/proto/src/logical_plan/to_proto.rs, datafusion/proto/tests/cases/roundtrip_logical_plan.rs, datafusion/sqllogictest/test_files/explain.slt
=> Change ScalarValue::Struct to ArrayRef

datafusion/physical-plan/src/stream.rs
The error is a DataFusionError already, so don't stringify it, just use it as-is.
`cargo test` passes; the behavior doesn't seem to be covered by tests.
Technically yes but I doubt anybody was matching on the error value. And if they were, this change is even more desirable!
=> RecordBatchReceiverStreamBuilder: don't stringify errors

datafusion-cli/src/catalog.rs, docs/source/user-guide/cli.md
Closes #9133
Query the remote http(s) location directly without creating a table
Added a dedicated unit test
Added an example to the docs showing how to query the remote parquet file via HTTP
=> feat: add ability to query the remote http(s) location directly in datafusion-cli

datafusion/core/src/dataframe/mod.rs
Follow on to https://github.com/apache/arrow-datafusion/pull/9159
I missed the comment https://github.com/apache/arrow-datafusion/pull/9159#discussion_r1483047057 from @carols10cents , so wanted to implement it. 
I took the opportunity to try and improve the documentation for `DataFrame::write_table` a bit more while I was at it
Just better docs
=> Minor: Update `DataFrame::write_table` docs

datafusion/physical-expr/src/physical_expr.rs
Part of #7013 
I was working on another example, and I wanted to create a `PhysicalExpr` but  could not figure out how to do so easily from the docs (I had to go poking around in the code)
Thus I wanted to provide improved documentation for myself (and I suspect others)
1. Improved documentation on `PhysicalExpr `
2. Examples of how to create a `PhysicalExpr` and how to execute it
Docs
=> Improve PhysicalExpr documentation

docs/source/library-user-guide/adding-udfs.md, docs/source/user-guide/cli.md, docs/source/user-guide/example-usage.md, docs/source/user-guide/expressions.md, docs/source/user-guide/sql/data_types.md, docs/source/user-guide/sql/ddl.md, docs/source/user-guide/sql/explain.md, docs/source/user-guide/sql/information_schema.md, docs/source/user-guide/sql/operators.md, docs/source/user-guide/sql/scalar_functions.md, docs/source/user-guide/sql/select.md, docs/source/user-guide/sql/subqueries.md, docs/source/user-guide/sql/window_functions.md, docs/source/user-guide/sql/write_options.md
None
The document building process produces multiple warnings. Some of these warnings are not really a big deal, but some may contains valuable information, and it's really difficult to notice that when a huge warning message is emitted.
- Remove/modify some syntax tag of code blocks, since syntax coloring not working but only produces warnings.
- Remove leading ❯ in sql code blocks.
- Fix reference links.
- Fix typos.
No code changed in this PR.
Yes.
=> Fix sphinx warnings

datafusion/common/src/scalar.rs
Use concat to simplify Nested Scalar creation
Except FixedsizeList
Closes #9145.
=> Use concat to simplify Nested Scalar creation

datafusion/common/src/scalar.rs
N/A
I noticed on https://github.com/apache/arrow-datafusion/pull/9174# there were map_err that are not needed so I figured I would propose a PR to clean them up
Make code more concise
existing tests
=> Minor: Remove unecessary map_err

datafusion-examples/README.md, datafusion-examples/examples/pruning.rs, datafusion/core/src/physical_optimizer/pruning.rs
Part of #7013 
Related to #7869 and https://github.com/apache/arrow-datafusion/issues/9171
1. We rely heavily on PruningPredicate in InfluxDB to prune data based on catalog information, so I want an easier way to point our engineers at it and understand how it works. 
2. We also had some non trivial confusion internally about how/if pruning predicates handled unknown column values, which I wanted to document
1. Add `pruning.rs` example to datafusion-examples with an annotated guide to using `PruningPredicate
2. Add link to the example in the `PruningPredicate` API docs
Yes, as part of CI
A new example, no code changes
=> Add example of using `PruningPredicate` to datafusion-examples

datafusion/physical-plan/src/joins/sort_merge_join.rs
Follow up of #9080.
Close #9179 
When applying join filter, we take filter evaluation array as selection mask to filter output batch. Next, we take the reverse mask to select (streamed) rows to join null rows.
With outer join cases, if filter evaluation has null values resulted in the selection mask, their reverse values are still nulls. Which makes some rows missed in (streamed) rows joined null rows.
We should use `prep_null_mask_filter` to handle nulls in selection mask as false before taking reverse mask from it.
=> Use prep_null_mask_filter to handle nulls in selection mask

docs/source/library-user-guide/adding-udfs.md
Closes #9136.
See #9136
Document update including adding a scalar udf by `impl ScalarUDFImpl`
=> [Document] Adding UDF by impl ScalarUDFImpl

.github/actions/setup-macos-aarch64-builder/action.yaml, .github/workflows/rust.yml
Closes #9117.
Add new CI pipeline for Mac OSX aarch64:
=> Add test pipeline for Mac aarch64

datafusion/physical-expr/src/equivalence/properties.rs, datafusion/sqllogictest/test_files/order.slt, datafusion/sqllogictest/test_files/subquery.slt, datafusion/sqllogictest/test_files/union.slt, datafusion/sqllogictest/test_files/window.slt
Closes [#9177](https://github.com/apache/arrow-datafusion/issues/9177).
Yes
=> Add constant expression support to equivalence properties

benchmarks/bench.sh, datafusion/sqllogictest/README.md
DataBloom is now Scalytics.  Fixes #9201
Closes #9201 
Updated the docker repository for tpch
Yes, ran the commands detailed in the issue
```
rm -rf benchmarks/data/tpch
./benchmarks/bench.sh data tpch
```
No
=> chore: update tpch-docker docker repository

datafusion-cli/src/catalog.rs, datafusion-cli/src/exec.rs, datafusion-cli/src/object_storage.rs, docs/source/user-guide/cli.md
Closes #9167
This is a next step from #9150 adding ability to query directly from S3 and Google Storage
Factored out the code from `exec.rs` into `object_storage.rs` to be re-usable.  
Adding a test for each storage type and a failing test for an invalid location
There are now more location types to query directly, also added docs with some examples
=> feat: implement select directly from s3 and gcs locations in datafusion-cli

datafusion/core/src/datasource/file_format/file_compression_type.rs
Closes #9156
Updates the stream gzip decoding to check for multiple members within a file.
Doesn't update the `Read` decoder because it already supports multiple members in a file.
The gzip decoding still seems to work, and I checked a manually bgzipped file, but I'm not sure if this code path is tested already.
No
=> feat: support block gzip for streams

datafusion/core/Cargo.toml, datafusion/core/src/datasource/physical_plan/parquet/row_groups.rs, datafusion/core/src/physical_optimizer/pruning.rs
Help with #9171 and #7869
`PruningPredicate` rewrites the original predicate into an expression that references min/max/null_count values of each column in the original predicate
Currently, `IS NOT NULL` is not supported, which means the rewritten predicate is ALWAYS TRUE, e.g.: 
Original Predicate | Rewritten Predicate
---------------- | -------------
`x IS NOT NULL` | `true`
See the code below, `phys_expr::IsNotNullExpr` is not listed/supported:
https://github.com/apache/arrow-datafusion/blob/292865e38cba1275a0f863230d816ee0e08c1318/datafusion/core/src/physical_optimizer/pruning.rs#L1139-L1140
Support `IS NOT NULL` predicate rewrite, e.g.:
Original Predicate | Rewritten Predicate
---------------- | -------------
`x IS NOT NULL` | `x_null_count = 0`
Yes
No API change. User will …
=> chore(pruning): Support `IS NOT NULL` predicates in `PruningPredicate`

.github/workflows/audit.yml
Closes #9116 .
Add cargo audit CI.
=> Add cargo audit CI

datafusion/core/src/datasource/listing/mod.rs, datafusion/core/src/datasource/listing/url.rs
Closes #9206.
* Aligns the code behaviour with the documentation
* Altering the `ListingTableUrl::contains` method to skip hive partitions where they appear as a segment in the url
* Makes the `list_all_files` method public to allow users to more easily see what files are being included with the `ListingTableUrl`
Yes a new test is added to ensure that the changes continue to behave as expected
* An additional public function on `ListingTableUrl`
* Extra files may be listed for a given `ListingTableUrl` which previously were not included. This could cause query results to change
=> Partitioning fixes

datafusion/sql/src/expr/function.rs, datafusion/sql/tests/sql_integration.rs
Closes #9166.
To return an error instead of panicking when columns don't exist in window function.
Code, tests
Yes
=> Return an error when a column does not exist in window function

datafusion/core/src/datasource/physical_plan/parquet/row_groups.rs, datafusion/core/src/physical_optimizer/pruning.rs
This reverts commit cc139c9790023463d2240213f2e4f335d9a880dd.
Which was PR #9208 
Closes #9230
#9208 introduced a subtle bug. See #9230 for details
=> Revert "chore(pruning): Support `IS NOT NULL` predicates in `PruningPredicate` (#9208)"

datafusion/core/src/datasource/physical_plan/mod.rs, datafusion/physical-plan/src/display.rs, datafusion/physical-plan/src/streaming.rs, datafusion/sqllogictest/test_files/window.slt
Closes #.
In other sources such as `CsvExec`, when there is more than 1 valid ordering at the source; all orderings are displayed at the plan. For instance, if `CsvExec` is ordered by `[a ASC, b ASC], [c ASC]` output ordering will be displayed as `output_orderings=[[a@1 ASC NULLS LAST, b@2 ASC NULLS LAST], [c@3 ASC NULLS LAST]`. 
However, currently output ordering of the  `StreamTableExec` is displayed as  `output_ordering=[a@1 ASC NULLS LAST, b@2 ASC NULLS LAST]` where only one of the valid orderings is displayed. This PR changes this behaviour to replicate behaviour of other sources.
=> Minor: improve Display of output ordering of `StreamTableExec`

datafusion/core/benches/sql_planner.rs, datafusion/core/src/datasource/listing/table.rs, datafusion/core/src/datasource/statistics.rs
=> Dont call multiunzip when no stats

.github/workflows/rust.yml
=> Use setup-macos-aarch64-builder for aarch64 CI pipeline

datafusion/sql/src/select.rs, datafusion/sqllogictest/test_files/aggregate.slt
Closes #9162.
When a column referenced by group-by exists both in the select list and the input, the one from the input should be given priority. In issue 9162, there are two references with the same name: one is an unqualified "t.a," and the other is a qualified t.a.
This is the practice of many databases, including PostgreSQL, Oracle, MySQL, Duckdb, etc. 
In the PostgreSQL documentation, there is an [explanation](https://www.postgresql.org/docs/current/sql-select.html#SQL-GROUPBY) about it.
> An expression used inside a grouping_element can be an input column name, or the name or ordinal number of an output column (SELECT list item), or an arbitrary expression formed from input-column values. In case of ambiguity, a GROUP BY name will be interpreted as an **input-column** name rather …
=> GROUP-BY prioritizes input columns in case of ambiguity

datafusion/core/src/catalog/mod.rs
There is no need to clone the schema in the memory_catalog_dereg_empty_schema test
=> Minor: chore: improve catalog test in mod.rs

datafusion/common/src/scalar/mod.rs, datafusion/common/src/scalar/struct_builder.rs
Follow on to https://github.com/apache/arrow-datafusion/pull/9229
related to  https://github.com/apache/arrow-datafusion/issues/9227
@NGA-TRAN  asked internally about exactly what `ScalarStructBuilder::new_null` internally so I wanted to document it in an example here.
When I did the PR the display didn't match what I thought `new_null` did, so I fixed a bug in null display as well
1. Add a doc example for `ScalarStructBuilder::new_null`
2. Fix bug in `ScalarValue::Struct` null display 
3. Add test for ScalarValue::Struct display
4. Fix a typo
Yes, new test and by CI
=> Add example for `ScalarStructBuilder::new_null`, fix display for `null` `ScalarValue::Struct`

datafusion-cli/src/exec.rs, datafusion/core/src/datasource/memory.rs, datafusion/expr/src/logical_plan/builder.rs, datafusion/expr/src/logical_plan/plan.rs, datafusion/sql/src/select.rs, datafusion/sqllogictest/test_files/same_column_name_cross_join.slt
Closes #9130 
In cross-join, Since we have to validate the uniqueness of the name, we would throw an error when failed to do it. as what sqlite did, they just substituted the name of the redundant column(supposed to be a) into a:1, and we followed the strategy.
=> fix: issue #9130 substitute redundant columns when doing cross join

datafusion/physical-plan/src/ordering.rs, datafusion/physical-plan/src/windows/mod.rs
Closes #.
When investigating an issue about Comet, I'm reading through `InputOrderMode`.  It takes some time to trace other related code to understand what it means. This patch adds a few more doc to `InputOrderMode` to make it more clear.
=> minor: Add more doc to clarify permutation satisfying input order in `InputOrderMode`

datafusion/expr/src/built_in_function.rs, datafusion/expr/src/signature.rs, datafusion/expr/src/type_coercion/functions.rs, datafusion/sqllogictest/test_files/array.slt
Closes #9093
Currently throws an error when doing `SELECT array_position(arrow_cast([1, 2, 3, 4, 5], 'List(Int32)'), 5)`, and after this PR it won't.
Change recommended in https://github.com/apache/arrow-datafusion/issues/9093#issuecomment-1920673541
Added an additional sql logic test that failed w/o the change, and doesn't fail w/ the change.
No
=> fix: add `ArrayAndElementAndOptionalIndex` for proper casting in `array_position`

datafusion/common/src/file_options/mod.rs, datafusion/core/src/dataframe/mod.rs, datafusion/core/src/dataframe/parquet.rs, datafusion/core/src/datasource/file_format/write/demux.rs, datafusion/core/src/physical_planner.rs, datafusion/expr/src/logical_plan/builder.rs, datafusion/expr/src/logical_plan/dml.rs, datafusion/expr/src/logical_plan/plan.rs, datafusion/proto/src/logical_plan/mod.rs, datafusion/proto/tests/cases/roundtrip_logical_plan.rs, datafusion/sql/src/statement.rs, datafusion/sqllogictest/test_files/copy.slt
Re #9237
Closes #8493
We currently support writing to partitioned listing tables. It would be nice to leverage the same physical plan implementation within a CopyTo statement, so users can skip registering a table if they don't need one.
- Extends CopyTo LogicalPlan to support partition_by option
- Extends CopyTo physical planning to propagate partition_by columns to the FileSinkExec plan
- Extends DataFrameWriteOptions to support the same partition_by option
- Adds partition column DataType inference to demux code so users do not have to explicitly specify data type in the COPY statement.
With these changes we can support queries like the following:
```sql
COPY source_table TO 'test_files/scratch/copy/partitioned_table1/' 
(format parquet, compression 'zstd(10)', partition_by 'col2'); …
```
=> Support Copy To Partitioned Files

datafusion/sqllogictest/test_files/scalar.slt
Fractions in the log function are an important test because the results of 2.0/3 and 2/3 are completely different
=> Minior: Add negative tests about log function

datafusion/functions/src/core/nullif.rs, datafusion/functions/src/math/nans.rs
N/A
Reported by rust-analyzer diagnostics.
Yes
No
=> Minor: fix warning of 'Unnecessary braces in use statement'

datafusion/physical-expr/Cargo.toml, datafusion/physical-expr/src/datetime_expressions.rs, datafusion/physical-expr/src/regex_expressions.rs
Closes https://github.com/apache/arrow-datafusion/issues/9277
=> Remove circular dependency

datafusion/physical-expr/src/equivalence/properties.rs, datafusion/physical-expr/src/expressions/cast.rs, datafusion/physical-plan/src/projection.rs, datafusion/sqllogictest/test_files/monotonic_projection_test.slt
fix: issue #8838 discard extra sort when sorted element is wrapped
improves the state in #8838
Closes #.
In the previous design, when we wanted to construct a dependency_map, we just used the order gotten from the previous node(In this issue, when we construct ProjectionExec, we just use the ordering gotten from CsvExec), however, previous design does not support a wrapper for the existing column, In this case, when we have orderings is [a DESC, b DESC] and the projection is CAST(a as BITINT), then we should change the ordering from a to CAST(a as BITINT) in order not to generate false dependency map(In this issue, when we construct the dependency map using the original expression, we would break prematurely and lose dependencies). In order to address this, we need to substitute original …
=> fix: issue #8838 discard extra sort when sorted element is wrapped

docs/source/user-guide/sql/dml.md, docs/source/user-guide/sql/write_options.md
NA
Support for writing partitioned files via partition_by was recently added.
Give examples of partition_by option for copy statements in the docs.
NA
Doc updates
=> Update Docs with Copy partition_by support

datafusion/core/src/datasource/file_format/write/demux.rs, datafusion/sqllogictest/test_files/copy.slt
closes #9290 
The current logic for removing partition_by columns assumes that the columns are at the end of the record batch. This is not always true when using COPY with the partition_by option.
Removes columns from record batch based on name rather than position.
Yes, modified copy.slt to cover
Yes, partitioned COPY statements will work correctly even if specifying columns that do not come at the end of the schema
=> Fix partition columns when they they are not at the end of the schema (fix Removing Partition Columns from RecordBatch)

docs/source/contributor-guide/index.md
no
1. Update the docs on integration test, `dataframe` is no longer a test target:
```sh
$ cargo t -p datafusion --test dataframe
error: no test target named `dataframe`.
Available test targets:
config_from_env
core_integration
custom_sources
fifo
fuzz
memory_limit
parquet_exec
path_partition
simplification
tpcds_planning
user_defined_integration
```
2. Add docs on how to format `.toml` files, ref: #9263 #9262
no
=> docs: update contributor guide (format toml/inte test)

datafusion/physical-plan/src/limit.rs
=> [MINOR]: Limit stream replace with slice

datafusion/core/src/dataframe/mod.rs, datafusion/core/src/datasource/file_format/parquet.rs, datafusion/core/src/physical_optimizer/test_utils.rs, datafusion/core/src/physical_planner.rs, datafusion/core/tests/dataframe/mod.rs, datafusion/core/tests/fuzz_cases/window_fuzz.rs, datafusion/expr/src/expr.rs, datafusion/expr/src/tree_node/expr.rs, datafusion/expr/src/udwf.rs, datafusion/expr/src/utils.rs, datafusion/optimizer/src/analyzer/count_wildcard_rule.rs, datafusion/optimizer/src/analyzer/type_coercion.rs, datafusion/optimizer/src/push_down_projection.rs, datafusion/physical-expr/src/window/built_in.rs, datafusion/physical-expr/src/window/lead_lag.rs, datafusion/physical-plan/src/windows/mod.rs, datafusion/proto/src/logical_plan/from_proto.rs, datafusion/proto/src/logical_plan/to_proto.rs, datafusion/proto/src/physical_plan/from_proto.rs, datafusion/proto/tests/cases/roundtrip_logical_plan.rs, datafusion/sql/src/expr/function.rs, datafusion/sqllogictest/test_files/window.slt, datafusion/substrait/src/logical_plan/consumer.rs, datafusion/substrait/src/logical_plan/producer.rs
Closes #.
Related https://github.com/apache/arrow-datafusion/issues/9055
=> Support IGNORE NULLS for LAG window function

docs/source/user-guide/sql/scalar_functions.md
As requested by @l1t1 in [this comment](https://github.com/apache/arrow-datafusion/discussions/9315#discussioncomment-8562504).
Document `generate_series()` as an alias of `range()`.
no
=> docs: document range() alias generate_series()

datafusion/core/Cargo.toml
closes https://github.com/apache/arrow-datafusion/issues/9256
before: 
```sh
> otool -L ./target/debug/datafusion-cli | grep 'liblzma'
/usr/local/lib/liblzma.5.dylib (compatibility version 10.0.0, current version 10.5.0)
```
after:
```sh
> otool -L ./target/debug/datafusion-cli | grep 'liblzma'       
```
users no longer need to dynamically link to `liblzma` or manually statically link
=> chore: statically link xz2

datafusion/sql/src/expr/function.rs, datafusion/sqllogictest/test_files/unnest.slt
Found in https://github.com/apache/arrow-datafusion/discussions/9315#discussioncomment-8562638
`unnest(make_array(1,2))` is supported, but `unnest(range(1,3))` is not supported.
```sh
DataFusion CLI v36.0.0
❯ select unnest(make_array(1,2));
+-------------------------------+
| make_array(Int64(1),Int64(2)) |
+-------------------------------+
| 1                             |
| 2                             |
+-------------------------------+
2 rows in set. Query took 0.008 seconds.
❯ select unnest(range(1,3));
Error during planning: unnest() can only be applied to array and structs and null
```
These are all supported in DuckDB.
If I understand correctly, `unnest` should support any expression with a return type of Array, not just the `make_array` function and column expressions.
The …
=> feat: expand `unnest`  to accept arbitrary single array expression

ci/scripts/rust_example.sh, datafusion-examples/Cargo.toml, datafusion-examples/examples/external_dependency/catalog.rs, datafusion-examples/examples/flight/flight_sql_server.rs
Closes https://github.com/apache/arrow-datafusion/issues/9334.
It allows the arrow flight examples to compile and makes all nested examples runnable.
This PR downgrades the `tonic` dependency to `0.10` to match `arrow-flight` and adds explicit `[[example]]` blocks so nested examples can be run with `cargo run --example`.
I verified locally that the arrow flight examples compile with this change, and I was able to run queries with JDBC against the `arrow_flight_sql` example.
No, just example fixes.
=> fix: flight examples

datafusion-examples/examples/parquet_sql_multiple_files.rs
Related to #9280, but not sure if it'd technically close it.
It's easy to get tripped up when querying the local file system if you aren't using absolute paths because by default there's a local file system registered at `file://`, so nothing needs to be done for absolute paths. But if you want to query with relative paths, you first need to register an ObjectStore, so this example shows that.
An alternative might be to also register `file://./` by default, but I'm not sure all the consequences of that. Or perhaps something easy like `ctx.register_cwd()`?
Updates the example.
Yes, running:
```console
arrow-datafusion update-p… ➜ cargo run --example parquet_sql_multiple_files                                    
Finished dev [unoptimized + debuginfo] target(s) in 0.38s
Running …
```
=> docs: update parquet_sql_multiple_files.rs with a relative path ex

datafusion/functions/src/core/mod.rs, datafusion/functions/src/core/nvl.rs, datafusion/sqllogictest/test_files/nvl.slt, docs/source/user-guide/sql/scalar_functions.md
Closes #9261.
add a new function `nvl`
yes
yes
=> feature: support nvl(ifnull) function

datafusion-cli/src/catalog.rs, datafusion-examples/examples/external_dependency/catalog.rs, datafusion/core/src/catalog/information_schema.rs, datafusion/core/src/catalog/listing_schema.rs, datafusion/core/src/catalog/schema.rs, datafusion/core/src/execution/context/mod.rs, datafusion/core/src/physical_planner.rs, datafusion/core/tests/sql/create_drop.rs
Closes #9305.
`SchemaProvider::table` is async and clearly allows IO:
https://github.com/apache/arrow-datafusion/blob/6fad5ed7a37c50b9c200f214c3e13b0e1f0cecbc/datafusion/core/src/catalog/schema.rs#L114-L116
However this method cannot fail. Casting errors to `None` is semantically wrong.
Change return type from `Option<Arc<dyn TableProvider>>` to `Result<Option<Arc<dyn TableProvider>>, DataFusionError>`.
It compiles.
**Breaking:** Interface change.
=> refactor:  Change `SchemaProvider::table` to return `Result<Option<..>` rather than `Option<..>`

datafusion-cli/Cargo.lock, datafusion/expr/src/built_in_function.rs, datafusion/expr/src/expr_fn.rs, datafusion/functions/src/math/acos.rs, datafusion/functions/src/math/mod.rs, datafusion/functions/src/math/nans.rs, datafusion/optimizer/src/analyzer/type_coercion.rs, datafusion/physical-expr/src/functions.rs, datafusion/proto/proto/datafusion.proto, datafusion/proto/src/generated/pbjson.rs, datafusion/proto/src/generated/prost.rs, datafusion/proto/src/logical_plan/from_proto.rs, datafusion/proto/src/logical_plan/to_proto.rs, datafusion/proto/tests/cases/roundtrip_physical_plan.rs
Part of #9285
Move math function `acos()` to the function crate
Let's try this in CI:<
I guess no
=> refactor: move acos() to function crate

datafusion/sqllogictest/test_files/aggregate.slt
Closes #9161.
In issue #9161, the expression `cast(a as int)` in the select list [generated](https://github.com/apache/arrow-datafusion/blob/497cb9d46c6f68de6762998c241d0860072c7909/datafusion/expr/src/expr.rs#L1687) a unqualified column named 't.a', which was then incorrectly referenced by the group by clause, leading to a schema error.
After merging PR #9228, the group by clause will now preferentially reference the column of the same name from the **input**, rather than the one in the **select list**, thereby resolving the issue.
I suspect there will still be similar issues, but we may need to find a new case to verify whether they truly exist.
Add a test.
Yes
No
=> Add test to verify issue #9161

datafusion/sql/src/planner.rs, datafusion/sqllogictest/test_files/array.slt
Closes #9380.
Support the syntax `create table t(a int[])`.
Support for defining ARRAY columns in `CREATE TABLE`.
Yes
No
=> feat: support for defining ARRAY columns in `CREATE TABLE`

datafusion/functions/src/math/nans.rs, datafusion/sqllogictest/test_files/scalar.slt
This PR fixes the panic that happens if no arguments are given to `isnan()`:
before:
```sh
❯ select isnan();
thread 'main' panicked at arrow-datafusion/datafusion/functions/src/math/nans.rs:67:39:
index out of bounds: the len is 0 but the index is 0
```
after:
```sh
❯ select isnan();
Error during planning: No function matches the given name and argument types 'isnan()'. You might need to add explicit type casts.
Candidate functions:
isnan(Float32)
isnan(Float64)
```
no
=> fix: panic in isnan() when no args are given

datafusion/expr/src/built_in_function.rs, datafusion/expr/src/expr_fn.rs, datafusion/functions/src/math/asin.rs, datafusion/functions/src/math/mod.rs, datafusion/physical-expr/src/functions.rs, datafusion/proto/proto/datafusion.proto, datafusion/proto/src/generated/pbjson.rs, datafusion/proto/src/generated/prost.rs, datafusion/proto/src/logical_plan/from_proto.rs, datafusion/proto/src/logical_plan/to_proto.rs
Closes #9378
part of #9285
See #9285
move `asin()` to function crate
I guess no
=> refactor: move asin() to function crate

ci/scripts/rust_example.sh, datafusion-examples/Cargo.toml, datafusion-examples/examples/catalog.rs
Closes #8041.
The purpose of `catalog.rs` to provide an example of `SchemaProvider` implementation, so there is no need to use submodule which may contain non-standard / non-readable .parquet files, and .csv with some sample should be enough.
Replacing `[parquet-]testing` submodules usage in catalog example with directories and .csv containing basic sample.
`catalog.rs` execution now included (back) in the CI script for examples.
No
=> fix: using test data sample for catalog example

datafusion/functions/src/encoding/inner.rs, datafusion/functions/src/encoding/mod.rs, datafusion/functions/src/lib.rs, datafusion/functions/src/macros.rs, datafusion/functions/src/math/abs.rs, datafusion/functions/src/math/nans.rs, datafusion/functions/src/regex/regexpmatch.rs
Closes https://github.com/apache/arrow-datafusion/issues/9281
The way we were defining modules in `datafusion-functions` meant that rustfmt was not running on them 
This applies the fix in https://github.com/apache/arrow-datafusion/pull/9367 to all the packages in the `datafusion-functions` crate
covered by CI
No
=> Run cargo-fmt on all of `datafusion-functions`

datafusion/core/benches/sql_planner.rs
Closes #.
While working on the [PR](https://github.com/apache/arrow-datafusion/pull/9346), I recognized that `physical_plan_tpch_all` test indeed produces `LogicalPlan`. Hence its name is misleading, this may causes unintended consequences in the benchmarks. This PR fixes this so that name and the behavior is consistent
=> [MINOR]: Generate physical plan, instead of logical plan in the bench test

datafusion-examples/examples/to_date.rs, datafusion/common/src/scalar/mod.rs, datafusion/expr/src/built_in_function.rs, datafusion/expr/src/expr_fn.rs, datafusion/physical-expr/src/datetime_expressions.rs, datafusion/physical-expr/src/functions.rs, datafusion/proto/proto/datafusion.proto, datafusion/proto/src/generated/pbjson.rs, datafusion/proto/src/generated/prost.rs, datafusion/proto/src/logical_plan/from_proto.rs, datafusion/proto/src/logical_plan/to_proto.rs, datafusion/sqllogictest/test_files/dates.slt
Closes #8987 .
Add to_date function, and change the protobuf file
Not now, but it should be added in this PR.
Add a function named `to_date`, users can use `select to_date(1243124);`  to try it.
=> Add `to_date` function

datafusion/expr/src/udaf.rs, datafusion/expr/src/udf.rs, datafusion/expr/src/udwf.rs
re https://github.com/apache/arrow-datafusion/pull/8578
@SteveLauC  asked about why the "simple" APIs were less performant https://github.com/apache/arrow-datafusion/pull/8578/files#r1505483541
In researching the answer I concluded that they are not really less performant, and thus the documentation shouldn't imply they are. 
Update the docs to explain the difference better
CI docs test
=> Minor: clarify performance in docs for `ScalarUDF`, `ScalarUDAF` and `ScalarUDWF`

datafusion/physical-plan/src/lib.rs
Draft until https://github.com/apache/arrow-datafusion/pull/9346 is merged
Related to https://github.com/apache/arrow-datafusion/pull/9346
After https://github.com/apache/arrow-datafusion/pull/9346, some of the functions that were previously on ExecutionPlan were moved to an extension trait
But the docs don't show up in rustdoc
1. Move docs to the trait so they show up in rustdoc
2. Add a reference to the new trait to rust docs
=> Improve documentation for ExecutionPlanProperties, use consistent field name

docs/source/contributor-guide/index.md
Closes #9398
Closes #5347 
New contributors (myself included!) often run `cargo test` locally when setting up DataFusion for development and are surprised to see their system lock up or fail to complete the tests. This is due to very high memory requirements to complete the tests with default parallelism.  See linked issues for more discussion on the cause of high memory usage.
Documents this phenomenon in the contributors documentation page and suggests a workaround to run
```bash
cargo test -- --test-threads 1
```
if you run into memory limitations.
No - just a doc update.
New contributor docs
=> Doc: Workaround for Running cargo test locally without signficant memory

datafusion/sql/src/select.rs, datafusion/sqllogictest/test_files/unnest.slt
Closes #9349.
The `UnnestExec` already has this [functionality](https://github.com/apache/arrow-datafusion/blob/e1ca74e7c68e4949504e902f91d2e2b152cfc910/datafusion/physical-plan/src/unnest.rs#L570).
This PR passes the necessary parameters, i.e., the expressions in the select list that do not need unnesting, to it.
Yes
No
=> feat: support `unnest` with additional columns

datafusion/expr/src/expr.rs
N/A
Make the display name of `unnest` shorter and more consistent with other functions.
Currently on main branch:
```sh
select unnest(a), array_length(a) from (values([1,2])) as t(a);
+-----------------------------------------------------------------------------+-------------------+
| UNNEST([Column(Column { relation: Some(Bare { table: "t" }), name: "a" })]) | array_length(t.a) |
+-----------------------------------------------------------------------------+-------------------+
| 1                                                                           | 2                 |
| 2                                                                           | 2                 |
+-----------------------------------------------------------------------------+-------------------+
```
After PR: …
=> Minor: improve the display name of `unnest` expressions

datafusion/expr/src/expr_schema.rs, datafusion/expr/src/logical_plan/plan.rs, datafusion/functions/src/math/abs.rs, datafusion/functions/src/math/acos.rs, datafusion/functions/src/math/nans.rs, datafusion/optimizer/src/analyzer/type_coercion.rs, datafusion/sqllogictest/test_files/errors.slt, datafusion/sqllogictest/test_files/scalar.slt
NA
I noticed a recent PR https://github.com/apache/arrow-datafusion/pull/9377 tried to check function argument number inside a specific function's implementation
It can be done at a higher level during planning (as it was in old builtin function implementation)
1. Move checking function argument number logic outside of function implementation body (for all recently ported function did such check)
2. Check argument number during planning (same as old builtin function's implementation)
Covered by existing test introduced in #9377 
No
=> Minor: Move function signature check to planning stage

docs/source/contributor-guide/index.md
Closes #.
The migration to sqllogictest is complete (see #6195), so the document should be updated.
Update the contributors' guide.
CI doc test
No
=> docs: update contributor guide (migration to sqllogictest is done)

datafusion/sqllogictest/test_files/scalar.slt
Add negative tests about sqrt function
=> Minior: Add tests with `sqrt` with negative argument

datafusion/physical-expr/src/window/lead_lag.rs, datafusion/sqllogictest/test_files/window.slt
Closes #.
Related to #9055
Expanding IGNORE NULLS support for LEAD window function
Yes
=> Support IGNORE NULLS for LEAD window function

datafusion/common/src/parsers.rs, datafusion/physical-expr/src/equivalence/ordering.rs, datafusion/physical-expr/src/equivalence/projection.rs, datafusion/physical-expr/src/execution_props.rs, datafusion/sql/tests/sql_integration.rs, datafusion/sqllogictest/src/engines/postgres_engine/types.rs
Closes #.
fix cargo clippy some warning
=> minor: fix cargo clippy some warning

datafusion/physical-plan/src/sorts/sort.rs, datafusion/sqllogictest/test_files/order.slt
Closes https://github.com/apache/arrow-datafusion/issues/9418
Support SQL:
```sql
SELECT * FROM table ORDER BY name, book_list
```
where  the`book_list` column is DataType::List .
BTW, I wanted to modify the `lexsort_to_indices` function in [arrow-rs](https://github.com/apache/arrow-rs/compare/master...JasonLi-cn:arrow-rs:fix/lexsort_to_indices_bug
), but after bench, I found that the `Rows` based implementation  was better.
Benchmark on `Apple M1 16G`: 
```shell
lexsort_to_indices([i32_opt, i32_list]): 4096
time:   [440.80 µs 442.16 µs 443.63 µs]
Found 3 outliers among 100 measurements (3.00%)
lexsort_rows([i32_opt, i32_list]): 4096
time:   [432.53 µs 434.24 µs 436.16 µs]
Found 2 outliers among 100 measurements (2.00%)
1 …
```
=> fix: sort_batch function unsupported mixed types with list

clippy.toml, datafusion/common_runtime/src/common.rs, datafusion/core/src/datasource/file_format/arrow.rs, datafusion/core/src/datasource/file_format/parquet.rs, datafusion/core/src/datasource/file_format/write/orchestration.rs, datafusion/core/src/datasource/stream.rs
Simple refactoring after #9318 
In order to avoid duplication of explicit handling it seems logical to have such method.
I thought to add this logic to `join` but there are calls with additional logic (usually returns `DatafusionError::Execution` instead of unwind)
I noticed the same pattern spread across the repo. 
It also easy to forget and hard to refactor.
So could be useful
No
=> refactor: add `join_unwind` to `SpawnedTask`

datafusion/sql/src/planner.rs, datafusion/sqllogictest/test_files/array.slt
Closes #9440.
`int[]`  has been converted to `DataType::List`. However, the inner field should be renamed to 'item' instead of 'field' to ensure better integration with the existing ARRAY implementation. For instance, the `arrow_cast` function uses 'item'.
https://github.com/apache/arrow-datafusion/blob/c43d9b347ab17f458150ffbc1339b4e63d9e8b43/datafusion/sql/src/expr/arrow_cast.rs#L166-L167
Change the name of the inner field for `List` type within the SQL planner.
Yes
No
=> fix: casting to ARRAY types failed

docs/source/contributor-guide/index.md
=> Update contributor guide with updated scalar function howto

datafusion/physical-expr/src/window/lead_lag.rs, datafusion/sqllogictest/test_files/limit.slt
Closes #.
Reduce number of unnecessary casts from `i64` to `usize` and vice versa
=> Reduce casts for LEAD/LAG

datafusion-examples/examples/to_timestamp.rs, datafusion/common/src/scalar/mod.rs, datafusion/core/tests/parquet/mod.rs, datafusion/core/tests/parquet/page_pruning.rs, datafusion/core/tests/parquet/row_group_pruning.rs, datafusion/functions/src/datetime/common.rs, datafusion/optimizer/tests/optimizer_integration.rs, datafusion/physical-expr/benches/to_char.rs, datafusion/physical-expr/src/datetime_expressions.rs
Closes #.
Chrono deprecated bunch of methods and clippy now complains, so the CI build fails
=> [CI build] fix chrono suggestions

datafusion/functions/src/datetime/common.rs, datafusion/functions/src/datetime/to_date.rs, datafusion/functions/src/datetime/to_timestamp.rs
Ref to https://github.com/apache/arrow-datafusion/pull/9077#discussion_r1515780055
`validate_data_types()` has a logically unreachable type `ColumnarValue`. And this is sometimes misleading to the caller. Considering how it's implemented and would be used, I changed the return type to `Result<()>` to make it easier to invoke.
This function is from https://github.com/apache/arrow-datafusion/pull/9388
Change the return type of `validate_data_types()` and corresponding callers.
N/A
No
=> chore: simplify the return type of `validate_data_types()`

datafusion/physical-expr/src/expressions/cast.rs
Closes #8370 .
Remove tech debt brought up by not supported cast from Float to Timestamp in arrow-rs. Now we can safely remove it
=> minor: use arrow-rs casting from Float to Timestamp

datafusion/functions/src/datetime/mod.rs, datafusion/functions/src/datetime/to_unixtime.rs, datafusion/proto/proto/datafusion.proto, datafusion/proto/src/generated/prost.rs, datafusion/sqllogictest/test_files/timestamps.slt
=> Add `to_unixtime` function

datafusion/physical-expr/src/unicode_expressions.rs, datafusion/sqllogictest/test_files/functions.slt
Closes #9472.
Example query: `select substr_index('arrow.apache.org', '.', -1)`.
Expected result is `org`, but the current result of main branch is `e.org`.
```sh
DataFusion CLI v36.0.0
❯ select substr_index('arrow.apache.org', '.', -1);
+------------------------------------------------------------+
| substr_index(Utf8("arrow.apache.org"),Utf8("."),Int64(-1)) |
+------------------------------------------------------------+
| e.org                                                      |
+------------------------------------------------------------+
1 row in set. Query took 0.006 seconds.
```
The previous test input was "www.apache.org", where "www" and "org" have the same length, which coincidentally led to the tests on negative occurrences being passed.
Background: Since this function …
=> fix: `substr_index` not handling negative occurrence correctly

datafusion/sqllogictest/test_files/join.slt
Closes #6744.
The fix for the issue itself was introduced in #7529, this PR just adds more high-level tests to ensure that further optimizer/physical plan changes won't cause this regression, as DF seems to lack this kind of tests (at least I wasn't able to found multi-table join tests, except for couple of them in `joins.slt`)
Multi-table join tests added to `join.slt`
No
=> test: sqllogictests for multiple tables join

datafusion/expr/src/expr_fn.rs, datafusion/functions/src/math/mod.rs
=> Minior: Improve log expr description

datafusion/sql/src/expr/mod.rs, datafusion/sqllogictest/test_files/expr.slt
Closes #9487
Currently `SELECT TRIM('test.com', '.com')` doesn't work as expected because `.com` isn't removed.
This PR updates the translation step between the sql expression and the trim execution so that for both ways `TRIM` can be called, the proper trim characters are passes as an argument.
Yes, but minimal to start out with.
Not really
=> fix: support two argument TRIM

datafusion/core/src/physical_planner.rs, datafusion/optimizer/src/analyzer/rewrite_expr.rs, datafusion/physical-expr/src/expressions/get_indexed_field.rs, datafusion/physical-expr/src/planner.rs, datafusion/proto/proto/datafusion.proto, datafusion/proto/src/generated/pbjson.rs, datafusion/proto/src/generated/prost.rs, datafusion/proto/src/physical_plan/from_proto.rs, datafusion/proto/src/physical_plan/to_proto.rs, datafusion/proto/tests/cases/roundtrip_physical_plan.rs
Closes #.
Preparation of #9285
=> Remove physical expr of ListIndex and ListRange, convert to `array_element` and `array_slice` functions

datafusion/core/tests/user_defined/user_defined_scalar_functions.rs, datafusion/expr/src/expr_schema.rs, datafusion/expr/src/udf.rs, datafusion/physical-expr/src/planner.rs, datafusion/physical-expr/src/udf.rs
Closes #9518 
Ends with approach 2.
Follow up change from #8985 
To avoid recomputing argument types
Extend another field for udf return type
Only existing test
Relatively new function , acceptable breaking change
```rust
pub fn return_type_from_exprs(
&self,
args: &[Expr],
schema: &dyn ExprSchema,
arg_types: &[DataType],
) -> Result<DataType> {
```
=> Extend argument types for udf `return_type_from_exprs`

docs/source/user-guide/sql/data_types.md
Closes #9525 .
As this https://github.com/apache/arrow-datafusion/issues/9525#issuecomment-1987164177 said
> interval  syntax always returns a type of IntervalMonthDayNano
And the reason is #5801 but document has not been updated yet.
=> Minor: Fix document Interval syntax

docs/source/user-guide/sql/scalar_functions.md
Closes #.
Minor doc change to remove this extra char in the array function TOC.
Deletes a character.
Checked docs post build.
Slight doc update
=> docs: fix extraneous char in array functions table of contents

datafusion/common/src/scalar/mod.rs, datafusion/physical-expr/src/window/nth_value.rs, datafusion/physical-plan/src/windows/bounded_window_agg_exec.rs, datafusion/physical-plan/src/windows/mod.rs, datafusion/proto/tests/cases/roundtrip_physical_plan.rs, datafusion/sqllogictest/test_files/window.slt
Closes #.
Related https://github.com/apache/arrow-datafusion/issues/9055
=> Support IGNORE NULLS for FIRST/LAST window function

datafusion/functions/src/macros.rs
Closes https://github.com/apache/arrow-datafusion/issues/9584
See https://github.com/apache/arrow-datafusion/issues/9584 (basically I want to find the UDF without having to search by name at runtime)
Export udf's publically 
(note I checked that datafusion-functions-array already exports these functions
no -- not sure what to test...
=> Export datafusion-functions UDFs publically

datafusion/core/src/datasource/provider.rs, datafusion/optimizer/src/push_down_filter.rs
Update the comment on TableProvider::supports_filters_pushdown() to say that the returned vector much have the same size as the filters argument. Add a check at the callsite that the vec returned from supports_filters_pushdown is the same size as the filters passed:
Closes #9405.
following the suggestions:
> Update the comment on TableProvider::supports_filters_pushdown() to say that the returned vector much have the same size as the filters argument.
> Add a check at the callsite that the vec returned from supports_filters_pushdown is the same size as the filters passed:
Add a runtime error check for TableProvider::supports_filters_pushdown().
Update the comment on TableProvider::supports_filters_pushdown() .
make sure that the returned vector much have the same size as the filters …
=> Update the comment and Add a check

datafusion/sql/src/unparser/ast.rs, datafusion/sql/src/unparser/expr.rs, datafusion/sql/src/unparser/mod.rs, datafusion/sql/src/unparser/plan.rs, datafusion/sql/tests/sql_integration.rs
Relates to #8661
This is an initial attempt at porting over the LogicalPlan Unparser as described in the tracking ticket.
I took a similar approach to #9517 but moved the tests to `sql::tests` to make use of the `MockContextProvider`. I also took a stab at turning the tests into the roundtrip style (SQL -> Expr/Plan -> SQL) as discussed in the Expr PR.
=> Initial support LogicalPlan to SQL String

.github/workflows/pr_benchmarks.yml, .github/workflows/pr_comment.yml, benchmarks/bench.sh, datafusion/physical-plan/src/sorts/sort.rs
Partially progresses #5504.
Enable automated comparative PR benchmarking, and thus make performance regression less likely to be introduced into the code.
Add two new workflows:
1. `Benchmarks`, that is triggered by a PR comment `/benchmark`, and which runs the standard repo benchmarks against the base and head commits.
2. A generic `PR Comment` workflow, that in this case should post a message along the lines of
> # Benchmark results
> 
> <details>
> <summary>Benchmarks comparing e5404a13fa3fe82a1f108430342ed7b7b0358ff1 and 3bf178a432460ac069ab9d94fc80486710d6341f</summary>
> 
> ```
> Comparing main-e5404a1 and ci-benches-3bf178a
> --------------------
> Benchmark tpch.json
> --------------------
> ┏━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
> ┃ Query        ┃ …
```
=> Add `/benchmark` github command to comparison benchmark between base and pr commit

datafusion/expr/src/expr_schema.rs, datafusion/sql/src/select.rs, datafusion/sqllogictest/test_files/unnest.slt
Closees [9591](https://github.com/apache/arrow-datafusion/issues/9591) and [9589](https://github.com/apache/arrow-datafusion/issues/9589)
Users could use unnest function with other expressions instead of writing a new wrapper query
Yes
No
=> support unnest as subexpression 

datafusion/sql/src/unparser/ast.rs, datafusion/sql/src/unparser/plan.rs, datafusion/sql/tests/sql_integration.rs
works on #8661
See issue
Adds support for aggregation and subquery plan nodes converting to a SQL AST
For example, one can now convert
```
Projection: p1.id, COUNT(*) AS cnt
Aggregate: groupBy=[[p1.id]], aggr=[[COUNT(*)]]
Projection: p1.id
Inner Join:  Filter: p1.id = p2.id
SubqueryAlias: p1
TableScan: person
SubqueryAlias: p2
TableScan: person
```
to
```sql
SELECT p1.id, COUNT(*) AS cnt 
FROM (
SELECT p1.id 
FROM person AS p1 
JOIN person AS p2 
ON (p1.id = p2.id)
) 
GROUP BY p1.id
```
Yes, new roundtrip tests are added
More plans supported
=> feat: implement aggregation and subquery plans to SQL

datafusion/optimizer/Cargo.toml, datafusion/optimizer/src/analyzer/type_coercion.rs, datafusion/sqllogictest/test_files/array.slt
Part of https://github.com/apache/arrow-datafusion/issues/9285
We are trying to decouple the functions from the rest of the system so the core functionality doesn't directly depend on the specific function packages. 
1. Remove the explicit dependency on datafusion-functions-array from datafusion-optimizer
2. Port a test to sqllogictests
Yes
No (maybe slightly faster compile speeds)
=> Minor: Remove datafusion-functions-array dependency from datafusion-optimizer

.github/workflows/pr_benchmarks.yml, benchmarks/README.md, benchmarks/bench.sh
Should close #9620.
Try a workaround for missing TTY from https://github.com/actions/runner/issues/241
Shell used to run the bench data gen step.
They are on our fork (though that worked before too): https://github.com/splitgraph/arrow-datafusion/pull/2
=> Enable TTY during bench data generation

datafusion/core/src/physical_optimizer/enforce_distribution.rs, datafusion/core/src/physical_optimizer/enforce_sorting.rs, datafusion/core/src/physical_optimizer/utils.rs, datafusion/physical-expr/src/equivalence/properties.rs, datafusion/sqllogictest/test_files/window.slt
Related to [#9612](https://github.com/apache/arrow-datafusion/issues/9612) (not solves this problem)
Datafusion can analyze `expressions` during planning. Then can mark them as constant (such as after `FilterExec`). This information can help with optimizing away some `SortExec`s from the plan. However, some `SortEXec`s stil have unnecessary constant fields in their sort expressions. This is suboptimal. This PR filters out constant fields from sort expressions at the `SortExec`. Since this behaviour is not triggerred by existing tests. I added a test for this behaviour also.
The query
```
EXPLAIN SELECT *, SUM(a) OVER(ORDER BY b ASC, d ASC)
FROM multiple_ordered_table
where b=0
```
generates following physical plan in the main
```
physical_plan
BoundedWindowAggExec: …
```
=> Remove constant expressions from SortExprs in the SortExec

.github/workflows/pr_benchmarks.yml
Addresses #9620.
Env vars seem to be missing because of a different shell.
=> Try fixing missing results name in the benchmark step

.github/workflows/pr_benchmarks.yml
Yet another attempt at #9620.
For some reason GHA doesn't propagate the env var down into the script even though it lists it at the beginning of the step.
=> Add explicit move of PR bench results if they were placed in HEAD dir

datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs, datafusion/optimizer/src/simplify_expressions/inlist_simplifier.rs
=> Move parts of `InListSimplifier` simplify rules to `Simplifier`

datafusion/sql/src/expr/mod.rs, datafusion/sqllogictest/test_files/timestamps.slt
Closes #9580 .
`AT TIME ZONE` clause wasn't supported by DataFusion. For eg:
`SELECT '2000-12-01 04:04:12' AT TIME ZONE 'America/New_York');`
would earlier lead to this error: `This feature is not implemented: Unsupported ast node in sqltorel: AtTimeZone`
Now, the query evaluates to:
```
+-----------------------------+
| Utf8("2000-12-01 04:04:12") |
+-----------------------------+
| 2000-12-01T04:04:12-05:00   |
+-----------------------------+
```
This PR adds support for converting `AtTimeZone` expression provided by `sqlparser-rs` to a logical expression in DataFusion.
Yes. New tests have been added for expected behaviour and error scenarios.
Yes. The addition of `AT TIME ZONE` clause is a user facing change.
No breaking change since this PR only adds support for a previously …
=> Support AT TIME ZONE clause

datafusion/expr/src/logical_plan/plan.rs, datafusion/expr/src/utils.rs
Parts of #9637 
This is not the core issue of 9637, but one of them. sql_planner has a slight improvement
=> Minor: remove clone in `exprlist_to_fields`

datafusion/physical-expr/src/window/nth_value.rs, datafusion/physical-plan/src/windows/mod.rs, datafusion/sqllogictest/test_files/window.slt
Closes #.
Related https://github.com/apache/arrow-datafusion/issues/9055
=> Support IGNORE NULLS for NTH_VALUE window function

datafusion/sql/src/unparser/expr.rs, datafusion/sql/src/unparser/mod.rs, datafusion/sql/src/unparser/plan.rs, datafusion/sql/src/unparser/utils.rs, datafusion/sql/tests/sql_integration.rs
Follow on to #9606
Based on review comment from @seddonm1 I wanted to see if I could make examples like the following pass in unparser:
```
Sort: COUNT(*) ASC NULLS LAST
Projection: person.id, COUNT(*), person.first_name
Filter: COUNT(*) > Int64(5) AND COUNT(*) < Int64(10)
Aggregate: groupBy=[[person.first_name, person.id]], aggr=[[COUNT(*)]]
Filter: person.id != Int64(3) AND person.first_name = Utf8("test")
TableScan: person
```
```SQL
select id, count(*), first_name 
from person 
where id!=3 and first_name=='test'
group by first_name, id 
having count(*)>5 and count(*)<10
order by count(*)
```
While working on this, I found that the implementation in #9606 was not doing what I  thought it was doing.  I was misled due to the string representation of two different AST's being the same. …
=> Improve Robustness of Unparser Testing and Implementation

datafusion/core/src/physical_optimizer/enforce_sorting.rs, datafusion/physical-plan/src/filter.rs, datafusion/sqllogictest/test_files/filter_without_sort_exec.slt
=> Adding Constant Check for FilterExec

datafusion/core/src/datasource/physical_plan/parquet/metrics.rs, datafusion/core/src/datasource/physical_plan/parquet/row_groups.rs, datafusion/core/tests/parquet/mod.rs, datafusion/core/tests/parquet/row_group_pruning.rs, datafusion/core/tests/sql/explain_analyze.rs
Closes #9639.
This helps diagnostic whether a Bloom filter mismatches (because of high false-positive probability caused by suboptimal tuning) or is not used at all.
Add the statistics and add corresponding assertions in tests.
Given the increasing number of assertions, I made them print which one failed, so we don't have to refer to line numbers when reading test failures.
It's mostly just additional tests.
The UI change affects a test, which I updated accordingly.
This adds two metrics in the `EXPLAIN ANALYZE` output.
=> parquet: Add row_groups_matched_{statistics,bloom_filter} statistics

.github/actions/setup-windows-builder/action.yaml
Close #9653
Sometimes CI fails because of rustup, we can re-reun the job and pray for the success.
```
rustup update stable
rustup toolchain install stable
rustup default stable
rustup component add rustfmt
shell: C:\Program Files\Git\bin\bash.EXE --noprofile --norc -e -o pipefail {0}
info: syncing channel updates for 'stable-x86_64-pc-windows-msvc'
stable-x86_64-pc-windows-msvc unchanged - rustc 1.76.0 (07dca489a 2024-02-04)
info: checking for self-update
info: downloading self-update
D:\a\_temp\1c8b34cc-212a-[46](https://github.com/apache/arrow-datafusion/actions/runs/8319817263/job/22763668481?pr=9651#step:3:49)4d-8031-14d0aca81a56.sh: line 2: /c/Users/runneradmin/.cargo/bin/rustup: Device or resource busy
warning: tool `rust-analyzer` is already installed, remove it from …
```
=> Suppress self update for windows CI runner

datafusion/sql/src/unparser/plan.rs, datafusion/sql/tests/sql_integration.rs
This PR is meant to upstream this PR: https://github.com/datafusion-contrib/datafusion-federation/pull/26
SQL languages will typically have schemas, so add support for schema names to the table scan AST builder.
=> add schema to SQL ast builder
