datafusion/core/tests/parquet/mod.rs, datafusion/core/tests/parquet/row_group_pruning.rs
Closes #9641.
They were only locally tested in `datafusion/core/src/datasource/physical_plan/parquet/row_groups.rs`, and not as exhaustively as they can be here.
In addition to the new tests, I added a new fixture with `String`, `Binary`, and `FixedSizeBinary` columns. The latter two are not used yet, but I have some code locally that uses them after I added support for bloom filters on these column types.
None
=> core/tests/parquet/row_group_pruning.rs: Add tests for strings

datafusion/core/src/datasource/physical_plan/parquet/row_groups.rs, datafusion/core/tests/parquet/row_group_pruning.rs
Closes #9643.
They allow faster access to binary columns with high cardinality
Also adds tests for statistics-based row group pruning.
Yes
It should be invisible other than a performance improvement.
=> parquet: Add support for Bloom filters on binary columns

datafusion/common/src/error.rs, datafusion/common/src/scalar/mod.rs, datafusion/physical-plan/src/filter.rs, datafusion/proto/proto/datafusion.proto, datafusion/proto/src/generated/pbjson.rs, datafusion/proto/src/generated/prost.rs, datafusion/proto/src/logical_plan/from_proto.rs, datafusion/proto/src/logical_plan/to_proto.rs, datafusion/sql/src/unparser/expr.rs
Closes #8499.
Closes https://github.com/apache/arrow-datafusion/issues/8500
It was decided in the linked issue that implementing the variant was the preferred solution.
Implement the `ScalarValue::Union` variant.
Via a functional test.
More queries should work.
=> Support Union types in `ScalarValue` 

datafusion/core/src/datasource/physical_plan/parquet/row_groups.rs, datafusion/core/src/datasource/physical_plan/parquet/statistics.rs, datafusion/core/tests/parquet/row_group_pruning.rs
Closes #9645.
Yes
It should be invisible other than a performance improvement.
=> parquet: Add support for row group pruning on FixedSizeBinary 

datafusion/core/src/physical_planner.rs, datafusion/core/tests/fuzz_cases/window_fuzz.rs, datafusion/physical-plan/src/windows/mod.rs
Closes #.
There are scenarios when output datatype for builtin window functions are not the same as hardcoded in DataFusion. 
For instance Apache Spark requires some functions like `ROW_NUMBER, RANK`, etc to be `Int` rather than `UInt` which is hardcoded in DF. It would be great to derive builtin window function output type from the incoming schema rather than having the type hardcoded. Having this derivation from the schema increases DF extensibility to be used in other hybrid systems.
Changed physical planner for window builtin functions to derive the output data type from schema. 
Yes
No
=> Make builtin window function output datatype to be derived from schema

README.md
Closes https://github.com/apache/arrow-datafusion/issues/9082
We discussed the policy and seemed to have reasonable consensus on 6 months as part of  https://github.com/apache/arrow-datafusion/issues/9082.
However, we never documented it and so we got at least one PR that proposed to break the MSRV: https://github.com/apache/arrow-datafusion/pull/9659
1. Document the "6 months MSRV policy"
CI
=> Add Minimum Supported Rust Version policy to docs

datafusion/common/src/cast.rs, datafusion/functions/src/datetime/date_part.rs, datafusion/sqllogictest/test_files/expr.slt, docs/source/user-guide/sql/scalar_functions.md
Closes #8692
Extend support for `extract` and `date_part` to `Time32` and `Time64` types, for relevant precisions (hours, minutes, seconds, etc.)
=> Support for `extract(x from time)` / `date_part` from time types

datafusion/optimizer/src/common_subexpr_eliminate.rs
Part of #7013 
In the context of looking at https://github.com/apache/arrow-datafusion/issues/9678 with @wiedld it was a little unclear what the `CommonSubexprEliminate` pass was doing without code exploration
Add some more description of what `CommonSubexprEliminate` does along with an example
By docs CI
No, just docs
=> Minor: improve documentation for `CommonSubexprEliminate`

datafusion/common/src/scalar/mod.rs, datafusion/core/tests/fuzz_cases/aggregate_fuzz.rs, datafusion/expr/src/expr_rewriter/mod.rs, datafusion/functions/benches/regx.rs, datafusion/functions/benches/to_char.rs, datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs, datafusion/physical-expr/src/equivalence/class.rs, datafusion/physical-expr/src/equivalence/ordering.rs, datafusion/physical-expr/src/equivalence/properties.rs, datafusion/physical-plan/src/sorts/partial_sort.rs, datafusion/physical-plan/src/union.rs, datafusion/substrait/src/serializer.rs
=> build: modify code to comply with latest clippy requirement

datafusion/common/src/scalar/mod.rs
Follow on to https://github.com/apache/arrow-datafusion/pull/9725
Closes #.
The size of `ScalarValue` appears to have changed on Linux to be the same as aarch64. Thus we can now run the ScalarValue size test again:
See details here: https://github.com/apache/arrow-datafusion/pull/9725/files#r1534400422
The point of the test was to ensure that the size of ScalarValue didn't change with PRs, but the Rust compiler may change how types are laid out. 
Update comments and run the test on all platforms again
=> Minor: Run ScalarValue size test on aarch again

datafusion/sql/src/statement.rs, datafusion/sqllogictest/test_files/copy.slt
Closes #9716 .
**Before this PR**
User has to prefix all format options they pass to the `COPY` command with `format`. For eg:
```
COPY source_table
to 'test_files/scratch/copy/table_csv_with_options'
STORED AS CSV OPTIONS (
'format.has_header' false,
'format.compression' uncompressed,
'format.datetime_format' '%FT%H:%M:%S.%9f',
'format.delimiter' ';',
'format.null_value' 'NULLVAL'
);
```
This is repetitive & different from what Datafusion 36.0.0 offered. (See issue description for more details)
**After this PR**
User can use the format options for the `COPY` command without prefixing them with `format`:
```
COPY source_table to 'test_files/scratch/copy/format_table.csv'
OPTIONS (
has_header false,
compression xz,
datetime_format '%FT%H:%M:%S.%9f',
delimiter ';',
null_value 'NULLVAL'
); …
```
=> make format prefix optional for format options in COPY

datafusion/functions-array/src/kernels.rs, datafusion/functions-array/src/lib.rs, datafusion/functions-array/src/range.rs, datafusion/functions-array/src/udf.rs
Closes #9705.
This PR aims to do following refactoring:
Extracts `range` and `gen_series` functions from `functions-array` subcrate' s `kernels` and `udf` containers,
Yes, all `array.slt` based `range` and `gen_series` functions tests are passed.
No
=> refactor: Extract `range` and `gen_series` functions from `functions-array` subcrate' s `kernels` and `udf` containers

datafusion/sql/src/unparser/expr.rs
=> adding expr to string for IsNotNull IsTrue IsFalse and IsUnkown

datafusion/core/src/dataframe/parquet.rs, datafusion/core/src/datasource/file_format/parquet.rs
Closes #9736
See issue
Parallel parquet writer can now handle the case when max_record_batch_rows < execution.batch_size by iteratively splitting the record batch rather than assuming it only needs to be split once. 
Yes, added new test that would panic prior to this PR
Just bugfix
=> fix: parallel parquet can underflow when max_record_batch_rows < execution.batch_size

datafusion/sql/src/statement.rs, datafusion/sql/tests/sql_integration.rs, datafusion/sqllogictest/test_files/copy.slt
Closes #9713 .
Please see the description of the issue.
If a `format` key is passed in the format / write options of the `COPY` command, we're using it to determine the `file_type` which is used to resolve format options for the `COPY` statement.
Yes. New tests have been added.
This PR is to improve backwards compatibility before the next release so no new changes from user's PoV.
=> support format in options of COPY command

datafusion/functions-array/src/kernels.rs, datafusion/functions-array/src/length.rs, datafusion/functions-array/src/lib.rs, datafusion/functions-array/src/range.rs, datafusion/functions-array/src/reverse.rs, datafusion/functions-array/src/sort.rs, datafusion/functions-array/src/udf.rs
Closes #9750.
This PR aims to do following refactoring:
1- Extract `array_length`, `array_reverse` and `array_sort` functions from `functions-array` subcrate' s `kernels` and `udf` containers,
2- Being added `make_scalar_function` support to `Range` and `GenSeries` `invoke` functions,
3- Being added `make_scalar_function` support to `ArrayLength`, `ArrayReverse`, `ArraySort`  `invoke` functions,
4- Being added minor refactoring such as cleaning-up redundant package definitions, fixing typo issue etc.
Yes, all `array.slt` based `array_length`, `array_reverse` and `array_sort` functions tests are passed.
No
=> refactor: Extract `array_length`, `array_reverse` and `array_sort` functions from `functions-array` subcrate' s `kernels` and `udf` containers

datafusion/functions-array/src/empty.rs, datafusion/functions-array/src/kernels.rs, datafusion/functions-array/src/lib.rs, datafusion/functions-array/src/repeat.rs, datafusion/functions-array/src/udf.rs
Closes #9761.
1- Extract `array_empty` and `array_repeat` functions from `functions-array` subcrate' s `kernels` and `udf` containers,
2- Being added `make_scalar_function` support to `ArrayEmpty` and `ArrayRepeat` invoke functions,
3- Being added minor refactoring such as cleaning-up redundant package definitions etc.
Yes, all `array.slt` based `array_empty` and `array_repeat` functions tests are passed.
No
=> refactor: Extract `array_empty` and `array_repeat` functions from `functions-array` subcrate' s `kernels` and `udf` containers

datafusion/optimizer/src/analyzer/type_coercion.rs
N/A
This TODO has already been implemented in `LogicalPlan::with_new_exprs`.
https://github.com/apache/arrow-datafusion/blob/6c6305159711fbca43ff7798faa52aaebcb2e7d3/datafusion/expr/src/logical_plan/plan.rs#L547-L558
No
=> Minor: remove an outdated TODO in `TypeCoercion`

datafusion/sql/src/unparser/expr.rs
=> Add Expr->String for ScalarFunction and InList

datafusion/functions/src/core/struct.rs, datafusion/sqllogictest/test_files/struct.slt
Fixes https://github.com/apache/arrow-datafusion/issues/9773
Bug (see https://github.com/apache/arrow-datafusion/issues/9773)
Fix bug by calling the correct api, add test
Yes, new test
Less bugs
=> Fix panic in `struct` function with mixed scalar/array arguments

datafusion/functions-array/README.md, datafusion/functions-array/src/array_has.rs, datafusion/functions-array/src/cardinality.rs, datafusion/functions-array/src/concat.rs, datafusion/functions-array/src/empty.rs, datafusion/functions-array/src/except.rs, datafusion/functions-array/src/extract.rs, datafusion/functions-array/src/flatten.rs, datafusion/functions-array/src/length.rs, datafusion/functions-array/src/lib.rs, datafusion/functions-array/src/make_array.rs, datafusion/functions-array/src/position.rs, datafusion/functions-array/src/range.rs, datafusion/functions-array/src/remove.rs, datafusion/functions-array/src/repeat.rs, datafusion/functions-array/src/replace.rs, datafusion/functions-array/src/resize.rs, datafusion/functions-array/src/reverse.rs, datafusion/functions-array/src/rewrite.rs, datafusion/functions-array/src/set_ops.rs, datafusion/functions-array/src/sort.rs, datafusion/functions-array/src/string.rs
Closes #9787.
This PR aims to do following refactoring:
1- Being added `make_scalar_function` support to missed `invoke` functions,
2- Aligning rust-doc across array functions,
3- Removing redundant imports,
4- Fixing typo problems,
5- Rename `core.rs` -> `make_array.rs`.
Yes, all `array.slt` tests pass.
No
=> refactor: Apply minor refactorings to `functions-array` crate

datafusion/sql/src/unparser/expr.rs
Related https://github.com/apache/arrow-datafusion/issues/9726.
=> Expr to Sql : Case

datafusion/sql/src/unparser/expr.rs
This PR adds support to convert Between Expr to SQL string #9726
=> feat: Between expr to sql string

datafusion/sql/src/unparser/expr.rs
=> Support Expr `Like`  to sql

datafusion/sql/src/unparser/expr.rs
This PR adds support for _Not_ expr in #9726
=> feat: Not  expr to string

datafusion/expr/src/logical_plan/builder.rs, datafusion/sqllogictest/test_files/cte.slt
Closes #9794.
Make the schema of the recursive term compatible with  the static term.
This differs from the handling of the ordinary [union](https://github.com/apache/arrow-datafusion/blob/ad89ff82421e9c4670f4440dd5a6fa6fb55c40c3/datafusion/expr/src/logical_plan/builder.rs#L1323) operator. We can't change the static term's schema, otherwise we would have to recreate the logic plan of the recursive term, as it depends on the static term through the work table.
That is to say, we use the schema of the static term as the final schema for CTE. 
DuckDB also adopted a similar approach.
```sh
D WITH RECURSIVE my_cte AS(
SELECT 1::int AS a
UNION ALL
SELECT a::bigint+2 FROM my_cte WHERE a<3
) SELECT a,typeof(a) FROM my_cte;
┌───────┬───────────┐
│   a   │ typeof(a) │
│ int32 │  varchar  │ …
```
=> fix: ensure mutual compatibility of the two input schemas from recursive CTEs

.github/workflows/pr_benchmarks.yml, benchmarks/bench.sh
Progresses #5504.
Make the variance a smaller component in benchmarks by using a larger SF
and thus reduce the noise/false-positives.
Run SF 10 in PR benchmarks too.
=> Run TPC-H SF10 during PR benchmarks

datafusion/core/tests/tpcds_planning.rs
=> [Minor] Update TCPDS tests, remove some #[ignore]d tests

datafusion-examples/examples/function_factory.rs, datafusion/core/src/execution/context/mod.rs, datafusion/core/tests/user_defined/user_defined_scalar_functions.rs
Closes #9838.
Right now `FunctionFactory::create` takes a `&SessionConfig` and not a `&SessionState`. This limits some of its utility (e.g. access to the object store) and makes it currently out of line with at least `TableProviderFactory`, which takes a `&SessionState` as well. The name of the parameter is also `state` which makes me think that was the original intention.
Update the trait signature for `FunctionFactory::create` so that gets passed `&SessionState`.
Existing tests around `FunctionFactory` are mostly unchanged.
Users of `FunctionFactory` will have to update their code.
Edit: I can't add the api-change label or I would.
=> feat: pass SessionState not SessionConfig to FunctionFactory::create

datafusion-cli/src/exec.rs, datafusion-cli/src/helper.rs
Closes #.
While we can write CLI commands sequentially such as:
```
CREATE TABLE test1 (
c1 VARCHAR(255),
c2 INT,
c3 INT
);
INSERT INTO test1 (c1, c2, c3) VALUES ('c', 2, 1);
SELECT * FROM test1;
```
CLI gives error to write more commands after "CREATE EXTERNAL TABLE":
```
CREATE EXTERNAL TABLE test1 (
c1 VARCHAR(255),
c2 INT,
c3 INT,
...
)
STORED AS CSV
WITH HEADER ROW
LOCATION '/Users/berkaysahin/Desktop/datafusion-upstream/testing/data/csv/aggregate_test_100.csv';
SELECT * FROM test1;
```
`🤔 Invalid statement: sql parser error: Expected end of statement, found: SELECT`
This PR addresses the issue that we needed to enter commands one by one for creating external tables. It resolves this by splitting the entire string at semicolons, ensuring each segment passes parser checks one by one, …
=> datafusion-cli support for multiple commands in a single line

datafusion-cli/Cargo.lock, datafusion/expr/Cargo.toml, datafusion/expr/src/logical_plan/display.rs, datafusion/expr/src/logical_plan/plan.rs
Related #3606 
[This comment](https://github.com/apache/arrow-datafusion/issues/3606#issuecomment-1259498728) reminds me to have a try on pg json plan, and the visualizer look great to me since we don't need to consider style, but just nodes.
Add a method to convert logical plan to postgresql json plan format, and tested in [dalibo](https://explain.dalibo.com/plan/9bedch8de5hghgc3). 
Tested in unittest.
No.
=> feat: Add display_pg_json for LogicalPlan

.github/workflows/pr_benchmarks.yml
Addresses issue found in https://github.com/apache/arrow-datafusion/pull/9800#issuecomment-2026073276.
Closes https://github.com/apache/arrow-datafusion/pull/9856
Part of https://github.com/apache/arrow-datafusion/issues/5504
TPC-H 10 in-mem is probably to large to handle inside shared runners.
Remove the recently added tpch_mem10 bench.
Only for devs (should see TPC-H 1, 1-mem and 10 benches now only).
=> Minor: Remove the bench most likely to cause OOM in CI

docs/source/user-guide/introduction.md
N/A
Adds [`Spice.ai`](https://github.com/spiceai/spiceai) to the list of known DataFusion users.
Update https://arrow.apache.org/datafusion/user-guide/introduction.html#known-users to add Spice.ai as a Known User.
=> doc: Add `Spice.ai` to Known Users

datafusion-cli/src/print_options.rs
Closes #.
I found it confusing as the user always looking into the code to find how to expand number of displayed rows.
The formatted query execution refactored and looks like 
```
100 row(s) fetched. (First 40 displayed. Use --maxrows to adjust)
Elapsed 0.014 seconds.
```
=> minor: add a hint how to adjust max rows displayed

.gitattributes
Closes https://github.com/apache/arrow-datafusion/issues/9843
We do not run the RAT check against the files under the hidden directory `.github` in CI, and some of these files are currently missing licenses (https://github.com/apache/arrow-datafusion/issues/9851).
However, when we create the release tarball, we include these files in the tarball and then run the RAT check against them, and this currently fails.
This PR updates `.gitattributes` so that we no longer include the `.github` files in the release tarball. There really is no need to include these files in a release.
I manually tested with the following command before and after making the change to `.gitattributes` and confirmed that the modification was effective in excluding the `.github` files from the tarball:
```
git archive …
```
=> Exclude .github directory from release tarball

docs/source/user-guide/introduction.md
N/A
Adds https://github.com/datafusion-contrib/datafusion-federation to the integrations list to help discoverability. Also fixes the InfluxDB link to match the change in https://github.com/apache/arrow-datafusion/pull/9092
Update [https://arrow.apache.org/datafusion/user-guide/introduction.html](https://arrow.apache.org/datafusion/user-guide/introduction.html) to include `datafusion-federation` to the list of integrations.
=> doc: Add `datafusion-federation` to Integrations

datafusion/physical-plan/src/joins/utils.rs
Closes #.
While #9676 found that NLJoin input reordering in benchmarks doesn't happen if one of inputs is AntiJoin -- the reason is that output statistics for all Semi/Anti join types is always set as `Absent`. This PR propagates "outer" input statistics to Anti/Semi join output.
- "outer" input statistics for Anti/Semi join cases is now propagated as output statistics (worst case  assumption -- filtering not occurs at all, an alternative might be either to use `default_filter_statistics` or use similar to regular joins algorithm based on estimated distinct values, which though could be misleading as it assumes that "all values from smaller side are present in larger side" -- not sure if it's fine for filter estimation)
- the only exception is disjoint inputs for semi-joins case -- if …
=> Implement semi/anti join output statistics estimation

.github/workflows/rust.yml, Cargo.toml, datafusion/core/Cargo.toml, dev/depcheck/Cargo.toml, dev/depcheck/README.md, dev/depcheck/src/main.rs
Related to https://github.com/apache/arrow-datafusion/issues/9278, follow on to https://github.com/apache/arrow-datafusion/pull/9292
I want DataFusion to compile quickly and be a nice development experience, so the faster the compilation / fewer dependencies the better in general. 
I have been wondering why compiling datafusion takes so long and requires compiling crates like gix (which is an implementation of git) https://github.com/apache/arrow-datafusion/pull/9844#pullrequestreview-1968625669 got me inspired to look into this:
```
...
Compiling gix-attributes v0.20.1
Compiling gix-credentials v0.22.0
Compiling gix-ignore v0.9.1
...
```
It turns out the dependencies were needed by the `depcheck` test, added in https://github.com/apache/arrow-datafusion/pull/9292.  There is no need to …
=> Minor: Move depcheck out of datafusion crate (200 less crates to compile)

datafusion/functions/benches/regx.rs
=> Minor: delete duplicate bench test

datafusion/core/src/catalog/mod.rs, docs/source/library-user-guide/catalogs.md
Closes #.
Fix the doc link since the catalog example has been moved.
I also checked other links pointing to `external_dependency`, which are still valid.
=> minor(doc): fix dead link for catalogs example

datafusion/core/tests/parquet/mod.rs, datafusion/core/tests/parquet/page_pruning.rs
Closes #9887.
New test scenario, new tests adapted from the signed integer tests
yes
no
=> parquet: Add tests for page pruning on unsigned integers

datafusion/sqllogictest/test_files/expr.slt
A workaround to fix Closes #9891 .
Replace the problematic struct literal with alias
We can support accessing table with explicit struct literal later on.
=> [CI] Use alias for table.struct

datafusion/sql/src/cte.rs, datafusion/sql/src/lib.rs, datafusion/sql/src/planner.rs, datafusion/sql/src/query.rs, datafusion/sql/src/relation/mod.rs, datafusion/sql/src/set_expr.rs, datafusion/sql/tests/sql_integration.rs, datafusion/sqllogictest/test_files/cte.slt
Closes #9804.
If the recursive term of a CTE does not reference the CTE itself, then it should be compiled to a non-recursive CTE, otherwise it may lead to incorrect query results.
This PR traverses the `LogicalPlan` of the recursive term, looking for a table scan of the work table to determine if there is a self-reference.
- Move the CTE-related code to a new mod named `cte`.
- Detect non-recursive CTEs in the recursive `WITH` clause.
Yes
No
=> fix: detect non-recursive CTEs in the recursive `WITH` clause

datafusion/physical-plan/src/metrics/builder.rs, datafusion/physical-plan/src/metrics/mod.rs, datafusion/physical-plan/src/metrics/value.rs, datafusion/physical-plan/src/sorts/sort.rs
Closes #9884.
This PR introduces following changes:
1- Currently, `ExternalSorter` exposes `BaselineMetrics`(e.g: total output rows), `spill_count` and `spilled_bytes`. `spilled_rows` can also be useful to track total spilled rows by total output rows when spilling in_memory_batches to disk by `IPCWriter`. On the other hand, currently, it is logged at `Debug` log level so seems to be invisible for `Info` level:
```
Spilled 1 batches of total 2400 rows to disk, memory released 9.5 KB
```
2- Fixing typo problems.
Yes, updated existing UT.
No
=> Add `spilled_rows` metric to `ExternalSorter` by `IPCWriter`

datafusion/common/src/config.rs, datafusion/core/src/datasource/physical_plan/parquet/mod.rs
Closes https://github.com/apache/arrow-datafusion/issues/9908
See rationale on https://github.com/apache/arrow-datafusion/issues/9908
1. Add ParquetExec::table_parquet_options accessor
2. Improve some comments
3. Improve field name
By existing CI
=> Minor: Add ParquetExec::table_parquet_options accessor

datafusion/common/src/dfschema.rs, datafusion/common/src/schema_reference.rs, datafusion/common/src/table_reference.rs, datafusion/core/src/catalog/listing_schema.rs, datafusion/core/src/datasource/listing_table_factory.rs, datafusion/core/src/execution/context/mod.rs, datafusion/core/src/test_util/mod.rs, datafusion/expr/src/logical_plan/builder.rs, datafusion/proto/src/logical_plan/from_proto.rs, datafusion/proto/src/logical_plan/to_proto.rs, datafusion/sql/src/expr/identifier.rs, datafusion/sql/src/planner.rs, datafusion/sql/src/relation/mod.rs, datafusion/sql/src/statement.rs, datafusion/substrait/src/logical_plan/consumer.rs
Closes  #9764
In the analyzer there are mostly immutable strings so we may want to use `Arc<str>` which performs better than `Cow<&'a str>` for immutable strings
Replace datatype
yes
=> perf: Use `Arc<str>` instead of `Cow<&'a>` in the analyzer

datafusion/common/src/table_reference.rs, datafusion/proto/src/logical_plan/from_proto.rs, datafusion/sql/src/planner.rs, datafusion/sql/src/statement.rs
Related to  #9764. Follow on to https://github.com/apache/arrow-datafusion/pull/9824
On https://github.com/apache/arrow-datafusion/pull/9824 @comphead  saw that using `Arc<String>` made a significant difference in planning benchmarks compared to `Arc<str>` - https://github.com/apache/arrow-datafusion/pull/9824#issuecomment-2030071719
I believe this is due to the fact that the original data often comes as a `String` so making an `Arc<str>`from a `&str` results in a second copy.
It turns out that the Rust compiler is smart enough to avoid copying when using `impl Into<Arc<str>>`  -- I thought it was, even though [the docs seem to suggest that is not the case](https://doc.rust-lang.org/std/sync/struct.Arc.html#impl-From%3CString%3E-for-Arc%3Cstr%3E). 
Change from 
```rust
pub fn bare(table: …
```
=> Improve planning speed using `impl Into<Arc<str>>` to create Arc<str> rather than `&str`

datafusion/common/src/tree_node.rs, datafusion/expr/src/tree_node/expr.rs
Closes https://github.com/apache/arrow-datafusion/issues/9457, part of https://github.com/apache/arrow-datafusion/issues/8913
The current implementation of `Expr::map_children()` is very complex, this PR tries to simplify its code.
This PR adds a `map_until_stop_and_collect()` macro, which is similar to `TransformedIterator::map_until_stop_and_collect()` to process sibling tree nodes, but it can process heterogeneous tree node containing expressions.
No.
=> Simplify Expr::map_children

datafusion/physical-expr/Cargo.toml, datafusion/physical-expr/benches/concat.rs, datafusion/physical-expr/src/functions.rs, datafusion/physical-expr/src/string_expressions.rs
Closes https://github.com/apache/arrow-datafusion/issues/9742
optimize `concat` and `concat_ws` function.
```shell
concat function/concat(old)/1024
time:   [91.562 µs 91.725 µs 91.905 µs]
Found 8 outliers among 100 measurements (8.00%)
6 (6.00%) high mild
concat function/concat(new)/1024
time:   [17.831 µs 17.877 µs 17.934 µs]
7 (7.00%) high mild
concat function/concat(old)/4096
time:   [357.95 µs 358.98 µs 360.02 µs]
concat function/concat(new)/4096
time:   [71.003 µs 71.168 µs 71.326 µs]
concat function/concat(old)/8192 …
```
=> Optimization: concat function

datafusion/expr/src/udaf.rs
part of https://github.com/apache/arrow-datafusion/issues/7013
Inspired by @jayzhan211 's changes in https://github.com/apache/arrow-datafusion/pull/9874 and also while it was fresh in my mind, I wanted to make sure it is easy to use the AggregateUDFImpl API. I found the documentation on this method somewhat confusing so I wanted to improev it
Improve `AggregateUDFImpl::state_fields` documentation
CI doc tests
Better docs
=> Improve `AggregateUDFImpl::state_fields` documentation

datafusion/sqllogictest/test_files/cte.slt
Closes #9930.
The `RepartitionExec` above `RecursiveQueryExec` may cause the result of this query to be non-deterministic.
```sh
DataFusion CLI v37.0.0
❯ explain WITH RECURSIVE my_cte AS(
SELECT 1::int AS a
UNION ALL
SELECT a::bigint+2 FROM my_cte WHERE a<3
) SELECT *, arrow_typeof(a) FROM my_cte;
+---------------+---------------------------------------------------------------------------------------------+
| plan_type     | plan                                                                                        |
+---------------+---------------------------------------------------------------------------------------------+
| physical_plan | ProjectionExec: expr=[a@0 as a, arrow_typeof(a@0) as arrow_typeof(my_cte.a)]                |
|               |   RepartitionExec: …
```
=> test: fix intermittent failure in cte.slt

datafusion/sql/src/unparser/expr.rs
Related to #9726
Yes, i wrote unit tests for the two new cases.
=> Add Expr->String for Exists, Sort

datafusion/core/src/physical_optimizer/enforce_distribution.rs, datafusion/physical-expr/src/equivalence/properties.rs, datafusion/physical-plan/src/lib.rs
Closes #.
In some units, tests I recognized that some constant expressions still exist in the output ordering of the operator (This is not wrong. However, they can be pruned out for better plans). This PR  adds this support.
=> Prune out constant expressions from output ordering.

datafusion/core/src/dataframe/mod.rs, datafusion/core/src/datasource/cte_worktable.rs, datafusion/core/src/datasource/listing/table.rs, datafusion/core/src/datasource/provider.rs, datafusion/core/src/datasource/view.rs, datafusion/core/tests/custom_sources_cases/provider_filter_pushdown.rs, datafusion/expr/src/table_source.rs
Closes https://github.com/apache/arrow-datafusion/issues/9922
part of #7013 
While debugging something with @pauldix  yesterday, we were somewhat confused with the old API (as the default impl calls the deprecated function) and the docs weren't clear
We figured it out, but it was a paper cut that caused more confusion that it should have
1. Improve docs for `TableProvider::supports_filters_pushdown` 
2. Improve docs for `TableProviderFilterPushDown`
3. Remove similarly named, but deprecated `TableProvider::supports_filter_pushdown`
Yes by CI
Docs, and the deprecated API is now removed
=> Improve docs for `TableProvider::supports_filters_pushdown` and remove deprecated function

datafusion/common/src/tree_node.rs, datafusion/expr/src/tree_node/expr.rs, datafusion/expr/src/tree_node/plan.rs, datafusion/optimizer/src/analyzer/subquery.rs
Part of https://github.com/apache/arrow-datafusion/issues/8913.
This PR simplifies `TreeNode` recursion declarations by adding 
- `TreeNodeRecursion::visit_children()`,
- `TreeNodeRecursion::visit_sibling()` and
- `TreeNodeRecursion::visit_parent()`
helpers to simplify handling of the current `TreeNodeRecursion` with continuation closures by specifying the next node position relative to the current one.
Similarly, the transforming recursions are simplified with
- `Transfomed::visit_children()`,
- `Transfomed::visit_sibling()` and
- `Transfomed::visit_parent()`
helpers.
After this PR recursion definition of `TreeNode::visit()` is as simple as that:
```
visitor.f_down(self)?
.visit_children(|| self.apply_children(|c| c.visit(visitor)))?
.visit_parent(|| visitor.f_up(self))
```
and …
=> Simplify TreeNode recursions

datafusion/optimizer/src/common_subexpr_eliminate.rs
Related to https://github.com/apache/arrow-datafusion/issues/9637  and #3058 
As part of https://github.com/apache/arrow-datafusion/issues/9637 I plan to rework `CommonSubexprEliminate` a bit to stop copying as much
I started looking at this code, and I wanted to document how it worked more clearly (mostly for my future self, but I think it will be more generally useful)
1. Add doc comments in `CommonSubexprEliminate`
Doc CI tests
Only some minor docstring changes. No functional changes intended
=> Minor: Add additional documentation to `CommonSubexprEliminate`

.github/actions/setup-rust-runtime/action.yaml, datafusion/core/src/physical_planner.rs
Closes #8837
Thanks to the previous analysis from #1047 and with some lldb debugging, was able to identify that `create_initial_plan(...)` and it's sibling `create_initial_plan_multi(...)` were the culprits for the stack overflow (also identified by this comment https://github.com/apache/arrow-datafusion/issues/8837#issuecomment-1991873404)
So went looking through it and found a place were there was a large number of local variables before the recursive call to `create_initial_plan(...)`/`create_initial_plan_multi(...)` and tested out extracting those into a separate function. This seems to resolve the issue.
Extract local variables and functionality in physical join planning in `create_initial_plan(...)` to a separate function to try reduce stack size before the recursive …
=> Fix tpcds planning stack overflows - Join planning refactoring

datafusion/expr/src/type_coercion/functions.rs, datafusion/sqllogictest/test_files/scalar.slt
Closes #9925 
The signature of the coalesce function has changed to variadic_equal and we need to add a new rule to coercion [Dictionary, Utf8] to Dictionary
=> coercion vec[Dictionary, Utf8] to Dictionary for coalesce function

datafusion/core/src/lib.rs
Part of #3058 
While reviewing https://github.com/apache/arrow-datafusion/pull/9960 I noticed some missing crates in the description of what crates make up DataFusion. I think this is because new crates have been added since this documentation was first written
Add entries for different subcrates 
Doc CI
=> Minor: Update library documentation with new crates

datafusion/physical-expr/src/planner.rs
N/A
When upgrading DataFusion internally we actually saw Panic's (due to a bug in our code): 
> level=error msg="Thread panic" panic_type=unknown panic_message="internal error: entered unreachable code: NamedStructField should be rewritten in OperatorToFunction" panic_file=/usr/local/cargo/git/checkouts/arrow-datafusion-cd9c4a788846b2bd/f16c211/datafusion/physical-expr/src/planner.rs panic_line=233 panic_column=21 target="panic_logging" location="panic_logging/src/lib.rs:54" time=1712340032101586067
Convert the errors from panic to internal error
No
=> Minor: Return InternalError rather than panic for `NamedStructField should be rewritten in OperatorToFunction`

datafusion/optimizer/src/analyzer/mod.rs
Part of #9637 
I found this while working on https://github.com/apache/arrow-datafusion/pull/9913 with @peter-toth
Calling `LogicalPlan::expressions()` does a copy of the expressions, but this function simply needs to check them
1. Use `TreeNode` API to visit expressions rather than `LogicalPlan::expressions()`
Covered by existing unit tests
(Slightly) faster planning, and fewer copies during planning
=> Minor: Avoid copying all expressions in `Analzyer` / `check_plan`

datafusion/optimizer/src/analyzer/mod.rs, datafusion/optimizer/src/decorrelate.rs, datafusion/optimizer/src/decorrelate_predicate_subquery.rs, datafusion/optimizer/src/eliminate_cross_join.rs, datafusion/optimizer/src/eliminate_duplicated_expr.rs, datafusion/optimizer/src/eliminate_filter.rs, datafusion/optimizer/src/eliminate_join.rs, datafusion/optimizer/src/eliminate_limit.rs, datafusion/optimizer/src/eliminate_nested_union.rs, datafusion/optimizer/src/eliminate_one_union.rs, datafusion/optimizer/src/eliminate_outer_join.rs, datafusion/optimizer/src/extract_equijoin_predicate.rs, datafusion/optimizer/src/filter_null_join_keys.rs, datafusion/optimizer/src/lib.rs, datafusion/optimizer/src/optimize_projections.rs, datafusion/optimizer/src/optimizer.rs, datafusion/optimizer/src/propagate_empty_relation.rs, datafusion/optimizer/src/push_down_filter.rs, datafusion/optimizer/src/push_down_limit.rs, datafusion/optimizer/src/push_down_projection.rs, datafusion/optimizer/src/replace_distinct_aggregate.rs, datafusion/optimizer/src/rewrite_disjunctive_predicate.rs, datafusion/optimizer/src/scalar_subquery_to_join.rs, datafusion/optimizer/src/simplify_expressions/mod.rs, datafusion/optimizer/src/single_distinct_to_groupby.rs, datafusion/optimizer/src/unwrap_cast_in_comparison.rs, datafusion/optimizer/src/utils.rs
Part of #7013 
@comphead  suggested we have some better documentation of the Optimizer rules https://github.com/apache/arrow-datafusion/pull/9959#pullrequestreview-1983529791 and I agree!
Update the documentation of the Optimizer so we now have a summary of the available rules
Here is what the docs look like now:
CI doc tests
No, just doc changes
=> Minor: Improve documentation about optimizer

datafusion/expr/src/utils.rs, datafusion/optimizer/src/optimize_projections.rs
Currently `inspect_expr_pre()` is a specaial wrapper around `Expr::apply()`, but all callsites of `inspect_expr_pre()` could use `Expr::apply()` directly. This PR (toghether with https://github.com/apache/arrow-datafusion/pull/9913) refactors all callsites of `inspect_expr_pre()` so technically it could be removed too. But because `inspect_expr_pre()` is a public function removing it would be a breaking change...
=> Minor: Use `Expr::apply()` instead of `inspect_expr_pre()`

docs/source/user-guide/sql/dml.md, docs/source/user-guide/sql/write_options.md
closes https://github.com/apache/arrow-datafusion/issues/9927
Looks like I missed a spot while updating the docs in https://github.com/apache/arrow-datafusion/pull/9754
1. Remove old options from COPY write options documentation
2. Update COPY
CI doc checks
Docs
=> Update documentation for COPY command

datafusion/physical-plan/src/unnest.rs
Closes #9932.
In a `GenericListArray`, the data in the `values` corresponding to a null list may not be empty; it can be any data.
```rust
pub struct GenericListArray<OffsetSize: OffsetSizeTrait> {
data_type: DataType,
nulls: Option<NullBuffer>,
values: ArrayRef,
value_offsets: OffsetBuffer<OffsetSize>,
}
```
For example, in the description of [this document](https://docs.rs/datafusion/latest/datafusion/common/arrow/array/struct.GenericListArray.html#representation), the value of the null list is `?`, it's not empty.
In this situation, merely checking the `values` is unsafe, we must obtain valid values based on the `value_offsets`.
- Fix bug in `unnest_generic_list`.
Yes
No
=> fix: improve `unnest_generic_list` handling of null list

datafusion/common/src/dfschema.rs, datafusion/expr/src/utils.rs, datafusion/sql/src/statement.rs
=> Remove unnecessary result in `DFSchema::index_of_column_by_name`

datafusion/core/src/datasource/physical_plan/parquet/row_groups.rs, datafusion/core/tests/parquet/row_group_pruning.rs
Closes #9914 .
related to https://github.com/apache/arrow-datafusion/issues/9779
I also removed the possibility to writing tests that pass and confirm that "something doesn't work, as expected". I suppose this could be confusing and was the reason why broken bloom filters for int8/int16/uint8/uint16 slipped in a previous PR, but it's a separate commit so I can rollback if necessary
=> Removes Bloom filter for Int8/Int16/Uint8/Uint16

datafusion/functions/src/unicode/substrindex.rs, datafusion/sqllogictest/test_files/functions.slt
Closes #9890 
We were using dynamic dispatch when deciding whether to do `string.split()` or `string.rsplit()` (depending on the `count` argument) because the exact type of iterator is not known at compile time, plus it allocates memory on the heap for the boxed iterator, which introduces considerable overhead. 
Instead, we can avoid doing this and handle the two cases with an if else statement, which removes that overhead and potentially enable further optimizations by the compiler.
Another major overhead is pointed to in https://github.com/apache/arrow-datafusion/pull/9973#discussion_r1554566944. Instead, we can avoid `String` creation at every iteration of `map` by using `StringBuilder` to build the output.
```bash
substr_index_array_array_1000
time:   [57.082 µs 57.407 µs 57.770 µs] …
```
=> Optimize performance of substr_index and add tests

datafusion/expr/src/logical_plan/plan.rs
Part of https://github.com/apache/arrow-datafusion/issues/9994
Document a few new methods that were added in https://github.com/apache/arrow-datafusion/pull/9913 from @peter-toth 
Yes, by CI
Just docs
=> Minor: Improve documentation on `LogicalPlan::apply*` and `LogicalPlan::map*`

datafusion/core/src/physical_optimizer/pruning.rs
N/A
As @waynexia and @Ted-Jiang noted in https://github.com/apache/arrow-datafusion/pull/9989 / https://github.com/apache/arrow-datafusion/pull/9989/files#r1555386926 the documentation for https://docs.rs/datafusion/latest/datafusion/physical_optimizer/pruning/trait.PruningStatistics.html#tymethod.row_counts says a `UInt64Array` should be returned  but the tests return a `Int64Array`
Improve documentation and update tests to do what the docs say should be done
Existing tests
No
=> Minor: Clarify documentation on `PruningStatistics::row_counts` and `PruningStatistics::null_counts` and make test match

datafusion/common/src/tree_node.rs, datafusion/expr/src/expr.rs, datafusion/expr/src/logical_plan/plan.rs, datafusion/optimizer/src/analyzer/subquery.rs, datafusion/optimizer/src/decorrelate.rs
Part of https://github.com/apache/arrow-datafusion/issues/8913.
This PR adds `TreeNode::exists()` API as a common pattern to check the presence of a matching node for a predicate in a tree.
This PR also solves the issue found by @alamb here: https://github.com/apache/arrow-datafusion/pull/9913#discussion_r1554563916. Since https://github.com/apache/arrow-datafusion/pull/9913 there is no need to call `LogicalPlan::expressions()` (that copies the plan's expressions) at certain places, but iterating over the expressions with `LogicalPlan::apply_expressions()` is enough.
- Adds the `TreeNode::exists()` API.
- Replaces `contains_outer_reference` helper with a better solution.
No.
=> Introduce `TreeNode::exists()` API, avoid copying expressions

datafusion-cli/Cargo.lock, datafusion/core/tests/simplification.rs, datafusion/expr/src/built_in_function.rs, datafusion/expr/src/expr.rs, datafusion/expr/src/expr_fn.rs, datafusion/expr/src/signature.rs, datafusion/functions/Cargo.toml, datafusion/functions/src/math/mod.rs, datafusion/functions/src/math/nanvl.rs, datafusion/functions/src/math/random.rs, datafusion/optimizer/src/push_down_filter.rs, datafusion/physical-expr/Cargo.toml, datafusion/physical-expr/src/functions.rs, datafusion/physical-expr/src/math_expressions.rs, datafusion/proto/proto/datafusion.proto, datafusion/proto/src/generated/pbjson.rs, datafusion/proto/src/generated/prost.rs, datafusion/proto/src/logical_plan/from_proto.rs, datafusion/proto/src/logical_plan/to_proto.rs
Closes #10005
Migration of builtin functions to new structure
Code, tests.
Yes.
No,
=> Move Nanvl and random functions to datafusion-functions

datafusion/physical-plan/src/repartition/mod.rs
Closes https://github.com/apache/arrow-datafusion/issues/10014
The state is initialized ONCE for all partitions. However this may take a short while (on a very busy system 1ms or more). It is quite likely that multiple threads call `execute` at the same time, because we have just fanned out to the number "target partitions" which is likely set to the number of CPU cores which now all try to start to execute the plan at the same time.
The solution is to not waste CPU circles in some futex lock but to tell the async runtime (= tokio) that we are performing work and the other threads should rather do something useful.
This mostly just moves code around, no functional change intended.
Existing tests still pass.
Faster query exec.
=> fix: reduce lock contention in `RepartitionExec::execute`

datafusion/core/src/lib.rs, datafusion/expr/src/logical_plan/mod.rs, datafusion/expr/src/logical_plan/plan.rs, datafusion/expr/src/logical_plan/tree_node.rs
Part of https://github.com/apache/arrow-datafusion/issues/9994
Part of working with optimizers / `LogicalPlans` is understanding how to rewrite them and visit them
We are improving this in https://github.com/apache/arrow-datafusion/issues/8913, so I wanted to make sure the feature is well documented.
1. Add doc comments and pointers about using the `LogicalPlan` tree node api
Yes, by CI checks
Better docs
TODO:
2. Document apply_subqueries /map_subqueries: https://github.com/apache/arrow-datafusion/pull/9998
=> Minor: Document LogicalPlan tree node transformations

datafusion-examples/examples/rewrite_expr.rs, datafusion/common/src/tree_node.rs, datafusion/core/src/execution/context/mod.rs, datafusion/core/tests/optimizer_integration.rs, datafusion/optimizer/src/decorrelate_predicate_subquery.rs, datafusion/optimizer/src/eliminate_duplicated_expr.rs, datafusion/optimizer/src/eliminate_filter.rs, datafusion/optimizer/src/eliminate_join.rs, datafusion/optimizer/src/eliminate_limit.rs, datafusion/optimizer/src/eliminate_nested_union.rs, datafusion/optimizer/src/eliminate_one_union.rs, datafusion/optimizer/src/eliminate_outer_join.rs, datafusion/optimizer/src/extract_equijoin_predicate.rs, datafusion/optimizer/src/filter_null_join_keys.rs, datafusion/optimizer/src/optimize_projections.rs, datafusion/optimizer/src/optimizer.rs, datafusion/optimizer/src/propagate_empty_relation.rs, datafusion/optimizer/src/push_down_filter.rs, datafusion/optimizer/src/push_down_limit.rs, datafusion/optimizer/src/push_down_projection.rs, datafusion/optimizer/src/replace_distinct_aggregate.rs, datafusion/optimizer/src/scalar_subquery_to_join.rs, datafusion/optimizer/src/single_distinct_to_groupby.rs, datafusion/optimizer/src/test/mod.rs, datafusion/optimizer/tests/optimizer_integration.rs, datafusion/sqllogictest/test_files/join.slt
Note: this looks like a large PR, but many of the changes are lines that removed `&` 
Part of https://github.com/apache/arrow-datafusion/issues/9637 (stop copying `LogicalPlan`s in the Optimizer) and https://github.com/apache/arrow-datafusion/issues/8913 (unified TreeNode rewrite)
The current structure of the `Optimizer` copies `LogicalPlan`s a large number of times. This is both slow as well as requires a large number of allocations
After  https://github.com/apache/arrow-datafusion/pull/9999, the `TreeNode` API  can handle rewriting `LogicalPlan` efficiently without `clone`. 
Thus it makes sense to use the [TreeNode API](https://github.com/apache/arrow-datafusion/blob/4bd7c137e0e205140e273a7c25824c94b457c660/datafusion/common/src/tree_node.rs#L1) in the optimizer, both because I think …
=> Refactor `Optimizer` to use owned plans and `TreeNode` API (10% faster planning)

datafusion/functions/Cargo.toml, datafusion/functions/benches/ltrim.rs, datafusion/functions/src/string/btrim.rs, datafusion/functions/src/string/common.rs, datafusion/functions/src/string/ltrim.rs, datafusion/functions/src/string/rtrim.rs
Closes https://github.com/apache/arrow-datafusion/issues/10007
If the `trim` function includes a second argument, I believe it is predominantly a Scalar rather than an Array. Expanding the second argument into an Array would lead to performance degradation, and more critically, the code `arg.clone().into_array(expansion_len)` would be invoked for every computation.
```shell
ltrim ": 1024           time:   [23.495 µs 23.520 µs 23.554 µs]
change: [-11.992% -11.922% -11.854%] (p = 0.00 < 0.05)
Found 2 outliers among 100 measurements (2.00%)
ltrim ": 4096           time:   [92.348 µs 92.489 µs 92.669 µs]
change: [-10.305% -10.123% -9.9762%] (p = 0.00 < 0.05)
Found 15 outliers …
```
=> Improve the performance of ltrim/rtrim/btrim

datafusion/physical-plan/src/repartition/mod.rs
Fixes #10015.
`RepartitionExec` is somewhat special. While most execs operate on "input partition = output partition", `RepartitionExec` drives all of its work using input-bound tasks. The metrics "fetch time" and "repartition time" therefore have to be accounted for the input partition, not for the output partition. The only metric that has an input & output partition label is the "send time".
Metrics fixed.
\-
Metrics make sense now.
=> fix: `RepartitionExec` metrics

datafusion/physical-plan/src/topk/mod.rs
Closes #.
Simply modify the logic of "break into record batches as needed". This modification avoid generating an empty RecordBatch where the batch.num_rows() eq batch_size.
https://github.com/apache/arrow-datafusion/blob/03d8ba1f0d94bac6bb8bb33e95f00f9f6fb5275a/datafusion/physical-plan/src/topk/mod.rs#L210-L219
=> modify emit() of TopK to emit on `batch_size` rather than `batch_size-1`

datafusion/core/tests/simplification.rs, datafusion/optimizer/src/optimizer.rs, datafusion/optimizer/src/simplify_expressions/simplify_exprs.rs
Note: A substantial number of the changes in this PR are removing `&` in tests. The actual logic change is quite small
Part of https://github.com/apache/arrow-datafusion/issues/9637
The less copying in the planner, the less time it takes to plan a query. Profiling from the`sql_planner` benchmark in https://github.com/apache/arrow-datafusion/issues/9637 shows almost 25% of the time is spent in `ExprSimplifier`, so let's make that faster.
The current API of `OptimizerRule` s requires a copy of the `LogicalPlan` to be made. Thus we need a new API that allows for in place rewrites.
1. Add new `OptimizerRule::rewrite` API for in place rewrites
2. Update `Optimizer` to use the new API
4. Update `ExprSimplifier` to implement `rewrite` rather than `try_optimize`
Open questions:
1. should we …
=> Introduce `OptimizerRule::rewrite` to rewrite in place, rewrite `ExprSimplifier` (20% faster planning)

datafusion/physical-expr/src/aggregate/count_distinct/mod.rs, datafusion/physical-expr/src/aggregate/count_distinct/native.rs, datafusion/sqllogictest/test_files/aggregate.slt, datafusion/sqllogictest/test_files/decimal.slt
Closes #10042
Fixing a regression.
Preserve the original data type in the aggregation state.
Tested in SLT.
Internal changes only.
=> Fix DistinctCount for timestamps with time zone

datafusion/expr/src/logical_plan/tree_node.rs
Part of https://github.com/apache/arrow-datafusion/issues/8913 and part of https://github.com/apache/arrow-datafusion/issues/7013
The TreeNode API has everything we need, but finding the right methods is sometimes challenging. Along with https://github.com/apache/arrow-datafusion/pull/10035 I think this will make it easier to use
1. Add more docs
2. No functional changes
CI 
No functional changes
=> Improve documentation on `LogicalPlan` TreeNode methods

datafusion/physical-expr/src/aggregate/count_distinct/mod.rs, datafusion/physical-expr/src/aggregate/count_distinct/native.rs
=> Always pass DataType to PrimitiveDistinctCountAccumulator

.github/actions/setup-rust-runtime/action.yaml
N/A
Fixes this warning that occurs in GitHub Actions, by upgrading `mozilla-actions/sccache-action` to `v0.0.4` which runs using node20.
Bump `mozilla-actions/sccache-action` to `v0.0.4`
They will be once CI runs for this PR.
No
=> Bump sccache-action to v0.0.4

.github/workflows/stale.yml, docs/source/contributor-guide/index.md
Closes https://github.com/apache/arrow-datafusion/issues/8865
We currently have many stale PRs open, some of them from around one year ago. This creates an additional maintenance burden for reviewers and also can result in older active PRs being ignored.
Add a workflow for closing stale PRs.
Not yet. I think we can only test this after merging.
No
=> chore: add GitHub workflow to close stale PRs

datafusion-cli/Cargo.lock, datafusion/core/Cargo.toml, datafusion/functions/Cargo.toml, datafusion/optimizer/Cargo.toml, datafusion/physical-expr/Cargo.toml
Closes #10058
Makes it possible to actually disable the crypto features if they aren't required for a user of DataFusion.
In addition to the main change that fixes the issue above, I realized that the `crypto_expressions` feature was added in two other crates that aren't using it anymore - so I removed them.
I tested that building with no default features does actually disable the crypto dependencies.
This could be a breaking change if people disabled the default features and were still using a crypto function. I will lean on the more experienced contributors to weigh in here.
=> Disable `crypto_expressions` feature properly for --no-default-features

datafusion/physical-plan/src/empty.rs, datafusion/physical-plan/src/placeholder_row.rs
Thus preserving the number of partitions in the plan properties.
It's not really an issue when working with real data, but I think it's useful for testing.
We are using `EmptyExec` with a specific number of partitions for testing.
It took me a while to realise the partitions were reset by plan rewriting.
=> Return self in EmptyExec and PlaceholderRowExec with_new_children

datafusion/physical-expr/src/expressions/in_list.rs, datafusion/sqllogictest/test_files/dictionary.slt
Closes #9530.
Dictionary types are already supported in the `InListExpr`, however, the `in_list` func doesn't handle types being 
mixed in with Dictionary types.
Relax type check in the `in_list` function.
Added new test
No
=> fix: Support Dict types in `in_list` physical plans

datafusion/core/src/datasource/physical_plan/parquet/page_filter.rs, datafusion/core/src/physical_optimizer/pruning.rs, datafusion/core/tests/parquet/mod.rs, datafusion/core/tests/parquet/page_pruning.rs, datafusion/core/tests/parquet/row_group_pruning.rs
and fix NOT NULL prune
Closes #9961
Closes #10049.
=> Prune pages are all null in ParquetExec by row_counts and fix NOT NULL prune

datafusion/optimizer/src/eliminate_outer_join.rs, datafusion/optimizer/src/simplify_expressions/simplify_exprs.rs
Part of https://github.com/apache/arrow-datafusion/issues/9637.
Eliminates a `LogicalPlan::with_new_exprs()` call and so `Expr` cloning.
This PR:
- Refactors `EliminateOuterJoin::try_optimize()` to `EliminateOuterJoin::rewrite()`.
- Contains minor cleanup of `eliminate_outer()`.
- Fixes typo in `SimplifyExpressions`.
No.
=> Refactor `EliminateOuterJoin` to implement `OptimizerRule::rewrite()`

datafusion/proto/src/physical_plan/from_proto.rs, datafusion/proto/src/physical_plan/mod.rs, datafusion/proto/src/physical_plan/to_proto.rs, datafusion/proto/tests/cases/roundtrip_physical_plan.rs
Follup to #9436.
We need to use the physical extension codec consistently, so that UDFs embedded in more complex expressions can also be serialized and deserialized. Most importantly in `parse_required_physical_expr` which calls recursively into `parse_physical_expr` and should be providing the original codec.
Add a `PhysicalExtensionCodec` parameter to more of the deserialization functions that were using a `DefaultPhysicalExtensionCodec` previously. I have left the the signature of public functions unchanged but they should be changed in the next major release (left a TODO comments):
* `parse_physical_window_expr`
* `parse_protobuf_hash_partitioning`
* `parse_protobuf_file_scan_config`
I extended the test in `roundtrip_physical_plan.rs` to use a more complex expression.
No, but left a …
=> Use PhysicalExtensionCodec consistently

datafusion-cli/src/exec.rs
N/A
When I want to see all the config options in datafusion CLI I use `SHOW ALL`.
However there are more than 40 rows (the default before truncation) and I almost
always forget to set `--maxrows` and thus can't see all of them:
```shell
(venv) andrewlamb@Andrews-MacBook-Pro:~/Software/arrow-datafusion2$ datafusion-cli
DataFusion CLI v37.0.0
> show all;
+-------------------------------------------------------------------------+---------------------------+
| name                                                                    | value                     |
+-------------------------------------------------------------------------+---------------------------+
| datafusion.catalog.create_default_catalog_and_schema                    | true                      |
| …
```
=> Minor: Do not truncate  `SHOW ALL` in datafusion-cli

datafusion/core/src/execution/context/mod.rs, datafusion/execution/src/config.rs
Closes #.
The `SessionConfig` has an "`extensions: AnyMap`", can be used "... to attach extra data to the session config -- e.g. tracing information or caches."(from `with_extension`'s docs). However, there's no place to add an extension from the `SessionState` site, which limits its functionality, especially when the attached extra data is wanted in optimizing physical plan stage.
This PR adds a `config_mut` in `SessionState` to get the mutable ref to `SessionConfig` to resolve the issue above.
Covered, and in doc-test.
Two new methods are added, no breaking.
=> Minor: get mutable ref to `SessionConfig` in `SessionState`

datafusion/expr/src/built_in_function.rs, datafusion/expr/src/type_coercion/binary.rs, datafusion/expr/src/type_coercion/functions.rs
=> Coerce Dictionary types for scalar functions

datafusion/optimizer/src/unwrap_cast_in_comparison.rs
Part of https://github.com/apache/arrow-datafusion/issues/9637.
Eliminates a `LogicalPlan::with_new_exprs()` call and so `Expr` cloning.
This PR refactors `UnwrapCastInComparison::try_optimize()` to `UnwrapCastInComparison::rewrite()`.
No.
=> Refactor `UnwrapCastInComparison` to implement `OptimizerRule::rewrite()`

datafusion/physical-expr/src/aggregate/approx_percentile_cont.rs, datafusion/physical-expr/src/aggregate/count_distinct/mod.rs, datafusion/physical-expr/src/aggregate/count_distinct/native.rs
=> Improve ApproxPercentileAccumulator merge api and fix bug

datafusion-cli/src/object_storage.rs
closes https://github.com/apache/arrow-datafusion/issues/10072
See https://github.com/apache/arrow-datafusion/issues/10072
Basically I want to be able to do:
```sql
-- Create external table
CREATE EXTERNAL TABLE sample
STORED AS PARQUET
OPTIONS(
'aws.access_key_id' 'A',
'aws.secret_access_key' 'B',
'aws.endpoint' 'http://localhost:8080',
'aws.allow_http' 'true',
)
LOCATION 's3://sprox/sample.parquet';
```
1. Support `aws.endpoint` as a config option
2. Support http connections
3. Add a better error message 
Can use http endpoints now
=> Support http s3 endpoints in datafusion-cli via `CREATE EXTERNAL TABLE`

datafusion/core/src/physical_optimizer/enforce_distribution.rs, datafusion/sqllogictest/test_files/joins.slt
Closes [#9928](https://github.com/apache/arrow-datafusion/issues/9928).
Yes
=> [Bug Fix]: Deem hash repartition unnecessary when input and output has 1 partition

datafusion/physical-plan/src/sorts/sort.rs
=> fix: Specify row count in sort_batch for batch with no columns

benchmarks/bench.sh, benchmarks/src/tpch/run.rs
Related to #9846.
The idea is to make Sort Merge Join as stable so this PR adds separate TPCH benchmark for SMJ
TPCH benches for SMJ
=> Adding TPCH benchmarks for Sort Merge Join

datafusion/core/tests/parquet/mod.rs, datafusion/core/tests/parquet/page_pruning.rs, datafusion/core/tests/parquet/row_group_pruning.rs
=> [minor] make parquet prune tests more readable

datafusion/optimizer/src/analyzer/function_rewrite.rs, datafusion/sqllogictest/test_files/subquery.slt
(note this targets `branch-37`, NOT `main`)
Part of 37 maintenance release https://github.com/apache/arrow-datafusion/issues/9904
Backport fixes for regressions 
Backport https://github.com/apache/arrow-datafusion/pull/10032, fix for https://github.com/apache/arrow-datafusion/issues/10029 to `branch-37`
Note this was only the first commit (as the TreeNode improvements are not on 37.0.0)
tests are included in backport
=> Backport to 37: fix `NamedStructField` should be rewritten in OperatorToFunction in subquery regression

datafusion/expr/src/type_coercion/functions.rs, datafusion/sqllogictest/test_files/scalar.slt
(note this targets `branch-37`, NOT `main`)
Part of 37 maintenance release https://github.com/apache/arrow-datafusion/issues/9904
Backport fixes for regressions
Backport https://github.com/apache/arrow-datafusion/pull/9958, fix for https://github.com/apache/arrow-datafusion/issues/9925  to `branch-37`
=> Backport to 37: fix Coercion stopped working for coalesce on a dictionary column

datafusion/physical-expr/src/aggregate/count_distinct/mod.rs, datafusion/physical-expr/src/aggregate/count_distinct/native.rs, datafusion/sqllogictest/test_files/aggregate.slt, datafusion/sqllogictest/test_files/decimal.slt
(note this targets `branch-37`, NOT `main`)
Part of 37 maintenance release https://github.com/apache/arrow-datafusion/issues/9904
Backport fixes for regressions
Backport https://github.com/apache/arrow-datafusion/issues/10042, fix for https://github.com/apache/arrow-datafusion/pull/10043  to `branch-37`
tests are included in backport
=> Backport to 37: group by count distinct doesn't work for timestamps with time zone

.github/dependabot.yml
=> Update dependabot to consider datafusion-cli

.github/workflows/dependencies.yml, .github/workflows/rust.yml, benchmarks/Cargo.toml
Follow on to https://github.com/apache/arrow-datafusion/pull/9865
Related to https://github.com/apache/arrow-datafusion/issues/9278
It would be nice not to waste runner time (and burn CO2) on unecessary jobs
Only trigger dependency check on changes to `Cargo.toml`
I tested them manually:
* commit [f106ff1](https://github.com/apache/arrow-datafusion/pull/10099/commits/f106ff1838e1aca96f18eeb9552c2f623c955aad): no depcheck ran https://github.com/apache/arrow-datafusion/pull/10099/checks
* https://github.com/apache/arrow-datafusion/pull/10099/commits/809cdcf0358d634e3bd990e25e2dd2ca4a11582a: Manually introduced a change to Cargo.toml: [depcheck ran ](https://github.com/apache/arrow-datafusion/actions/runs/8709157731/job/23888226710?pr=10099)
=> Minor: only trigger dependency check on changes to Cargo.toml

datafusion/optimizer/src/unwrap_cast_in_comparison.rs
Part of https://github.com/apache/arrow-datafusion/issues/9637, follow-up to https://github.com/apache/arrow-datafusion/pull/10087.
Eliminates remaining `Expr` clones.
This PR:
- Refactors `UnwrapCastExprRewriter` to remove `Expr` clones.
- Adds handling of a few unhandled errors in the `BinaryExpr` case as if any error occurs this optimizer rule should return the original expression.
No.
=> Refactor `UnwrapCastInComparison` to remove `Expr` clones

Cargo.toml, benchmarks/Cargo.toml, clippy.toml, datafusion-examples/Cargo.toml, datafusion/common-runtime/Cargo.toml, datafusion/common/Cargo.toml, datafusion/core/Cargo.toml, datafusion/core/src/dataframe/mod.rs, datafusion/core/src/dataframe/parquet.rs, datafusion/core/src/execution/context/mod.rs, datafusion/execution/Cargo.toml, datafusion/expr/Cargo.toml, datafusion/functions-aggregate/Cargo.toml, datafusion/functions-array/Cargo.toml, datafusion/functions/Cargo.toml, datafusion/optimizer/Cargo.toml, datafusion/physical-expr-common/Cargo.toml, datafusion/physical-expr/Cargo.toml, datafusion/physical-plan/Cargo.toml, datafusion/proto/Cargo.toml, datafusion/proto/gen/Cargo.toml, datafusion/sql/Cargo.toml, datafusion/sqllogictest/Cargo.toml, datafusion/substrait/Cargo.toml, datafusion/wasmtest/Cargo.toml, docs/Cargo.toml, test-utils/Cargo.toml
Closes #9893.
Datafusion since v37 started crashing with stack overflows. Based on issues linked to the one above - this problem existed previously but was dealt with by increasing the default stack size (which is not something our project can do).
The intent of the PR is:
- Identify places likely to cause stack overflows using clippy pedantic lint
- Fix top offenders of the stack space
1] Enables [`clippy::pedantic::large_futures`](https://rust-lang.github.io/rust-clippy/master/index.html#/large_future) lint
- This highlights a number of places in code where futures occupy 15-20 KiB on stack
- I think this lint is very useful and propose to enable it permanently
- Proposed linting configuration also makes it easy to enable more non-default lints in future on the workspace level
2] Traces …
=> Fix large futures causing stack overflows

datafusion/core/src/dataframe/mod.rs, datafusion/core/src/dataframe/parquet.rs, datafusion/core/src/execution/context/mod.rs
**Note:** this targets `branch-37`, NOT `main`.
Part of 37 maintenance release https://github.com/apache/arrow-datafusion/issues/9904
Backport fixes for stack overflowing due to large futures.
Backport https://github.com/apache/arrow-datafusion/issues/10033, fix for https://github.com/apache/arrow-datafusion/issues/9893 to `branch-37`
No API changes.
=> Backport to 37: Reduce DataFrame stack size and fix large futures warnings

dev/release/README.md
Related to #9904 
While I was working on a maintenance release in #9904  I followed this instructions  and found a few things that could be improved (like links and backporting examples)
Update docs
=> Minor: Refine dev/release/README.md

datafusion/expr/src/expr.rs, datafusion/optimizer/src/unwrap_cast_in_comparison.rs
This PR adds default for `Expr` as `Expr::Literal(ScalarValue::Null)`. This makes possible to use `mem::take()` in `UnwrapCastExprRewriter` and other rules in the future.
=> Minor: Add default for `Expr`

.asf.yaml, README.md, benchmarks/src/bin/parquet.rs, datafusion/core/src/lib.rs, datafusion/proto/README.md, datafusion/substrait/README.md, dev/release/README.md, dev/release/create-tarball.sh, dev/release/release-tarball.sh, docs/source/_templates/layout.html, docs/source/conf.py, docs/source/contributor-guide/communication.md, docs/source/index.rst, docs/source/library-user-guide/profiling.md
Part of https://github.com/apache/arrow-datafusion/issues/9691
DataFusion is now a top-level project
Documentation changes only.
There are no changes to links or release process yet.
No
=> Update documentation to replace Apache Arrow DataFusion with Apache DataFusion

datafusion/physical-expr/src/aggregate/average.rs, datafusion/sqllogictest/test_files/aggregate.slt, datafusion/sqllogictest/test_files/joins.slt
Closes #10113 .
Coerce AVG accumulator to designated return type in case of columns with nulls.
Yes, also a test is extended.
The query reported in the issue works now.
=> Fix AVG groups accummulator ignoring return type

datafusion/expr/src/lib.rs, datafusion/expr/src/type_coercion/aggregates.rs, datafusion/functions-aggregate/src/first_last.rs, datafusion/physical-expr-common/src/aggregate/mod.rs
Closes #.
Split from #10091
UDAF signature check is necessary like what built-in did.
Test is covered already 😄 
https://github.com/apache/datafusion/blob/19356b26f515149f96f9b6296975a77ac7260149/datafusion/sqllogictest/test_files/aggregate.slt#L158-L162
=> Minor: Signature check for UDAF  

datafusion/sql/src/query.rs
N/A.
When planning `Into`, we don't need to keep a copy of the whole `SetExpr`, we just need to take away the necessary `SelectInto`.
No
=> minor: avoid cloning the `SetExpr` during planning of `SelectInto`

datafusion/sqllogictest/test_files/aggregate.slt
Relates to #2411, #2410, #2408
Datafusion already supports these use cases. Just locking them into the test suite
=> Add distinct aggregate tests to sqllogictest

datafusion/sqllogictest/test_files/regexp.slt
Closes #1915
Issue seems resolved, adding a test to lock this in.
=> Add test for LIKE newline handling

datafusion/sql/src/unparser/expr.rs, datafusion/sql/tests/sql_integration.rs
related to #9726
Unimplemented paths should error not panic. Match arms should be listed explicitly to make discovery of unimplemented paths easier, especially if new enum variants are added the compiler will identify them.
- Replaces some instances of todo!() with not_impl_err!()
- Explicitly lists all match arms for expr -> SQL expr
- Adds round trip SQL test that includes some of the newly added expressions
Yes
No - other than preventing panic in some cases
=> minor: unparser cleanup and new roundtrip test

datafusion/common/src/scalar/mod.rs, datafusion/sqllogictest/test_files/aggregate.slt
Closes #10132.
`ScalarValue::iter_to_array` is a building block for many aggregation accumulators, so it should support as many data types as possible.
Add support for `Duration` and `Union` types to `ScalarValue::iter_to_array`.
Tested `Duration`. Not sure how we can test `Union`.
=> Support Duration and Union types in ScalarValue::iter_to_array

Cargo.toml, datafusion-cli/Cargo.lock, datafusion/common/src/functional_dependencies.rs, datafusion/sql/src/expr/mod.rs, datafusion/sql/src/expr/value.rs, datafusion/sql/src/statement.rs
Supersedes #10085
Handle some sqlparser API changes. Have tried to keep changes minimum.
=> chore(deps): update sqlparser requirement from 0.44.0 to 0.45.0

datafusion/core/src/physical_optimizer/join_selection.rs, datafusion/physical-plan/src/joins/hash_join.rs, datafusion/sqllogictest/test_files/joins.slt
Closes #.
While #9676, found that at this moment `HashJoinExec` works incorrect in case of LEFT / FULL types. Currently, construction of these joins is prevented by physical optimizer join_selection rule. This PR adds support for all join types in CollectLeft mode.
- `JoinLeftData` now contains bitmap with visited left indices and atomic counter of total right-side threads (streams), updating this particular `JoinLeftData` object (initial value will always be 1 for partitioned joins, and "number of right-side partitions" for CollectLeft)
- In the beginning of `process_unmatched_build_batch`, when it's guaranteed that there won't be any further updates of visited indices bitmap, each `HashJoinStream` decrements the counter of running partitions by calling `report_probe_completed`, and only …
=> fix: duplicate output for HashJoinExec in CollectLeft mode

docs/source/user-guide/example-usage.md
Closes #.
Add a backtrace example for local tests
=> [DOC] Add test example for backtraces

datafusion/expr/src/expr.rs, datafusion/expr/src/udf.rs, datafusion/functions/src/math/coalesce.rs
=> implement short_circuits function for ScalarUDFImpl trait

datafusion/optimizer/src/extract_equijoin_predicate.rs
=> implement rewrite for ExtractEquijoinPredicate and avoid clone in filter

.asf.yaml, docs/README.md, docs/source/index.rst
Closes #10151
Updates `.asf.yaml` to point to the new top-level website, and adds the required links to the ASF as required by https://www.apache.org/foundation/marks/pmcs#navigation
I mirrored what https://arrow.apache.org does and grouped these links into an `ASF Links` section
According to https://github.com/apache/infrastructure-asfyaml/blob/main/README.md#publish - removing the `subdir` config in `publish` will do what we want.
Here is a screenshot of what it looks like locally:
N/A
=> Update .asf.yaml to publish docs to datafusion.apache.org

datafusion/optimizer/src/filter_null_join_keys.rs
=> implement rewrite for FilterNullJoinKeys

datafusion/expr/src/logical_plan/tree_node.rs, datafusion/optimizer/src/eliminate_join.rs, datafusion/optimizer/src/eliminate_one_union.rs
=> Implement rewrite for EliminateOneUnion and EliminateJoin

CONTRIBUTING.md, README.md, datafusion-cli/README.md, datafusion/core/README.md, datafusion/core/src/catalog/mod.rs, datafusion/core/src/lib.rs, datafusion/expr/src/aggregate_function.rs, datafusion/proto/CONTRIBUTING.md, datafusion/proto/README.md, dev/changelog/15.0.0.md, dev/release/README.md, docs/source/contributor-guide/index.md, docs/source/user-guide/introduction.md, docs/source/user-guide/sql/select.md, docs/source/user-guide/sql/write_options.md
Part of #9691
Updates the links in the repo to point to https://datafusion.apache.org instead of https://arrow.apache.org/datafusion
I clicked through each link as I made the change.
=> Update links to point to datafusion.apache.org

datafusion/proto/proto/datafusion.proto, datafusion/proto/src/generated/pbjson.rs, datafusion/proto/src/generated/prost.rs, datafusion/proto/src/logical_plan/from_proto.rs, datafusion/proto/src/physical_plan/from_proto.rs
=> [MINOR] Remove ScalarFunction from datafusion.proto #10173

datafusion/sql/src/unparser/dialect.rs, datafusion/sql/src/unparser/expr.rs
Closes #10197
I'm using the Unparser.expr_to_sql function to translate a DataFusion Expr into an expression for Spark Connect. Unlike most SQL engines, Spark doesn't like quoting the column identifiers. I want to be able to generate an expression like `a > 4` but currently I can only get `"a" > 4`
I believe this might be useful beyond Spark for other database systems that can handle unquoted column identifiers.
Changes the DefaultDialect for the Unparser to return `Some('"')` for `identifier_quote_style`, and then changes the usage of `identifier_quote_style` to not unwrap to `"` if it is None, but pass the Option through.
Yes
No, this change is backwards-compatible.
=> Allow expr_to_sql unparsing with no quotes

datafusion/functions-array/src/rewrite.rs
Part of https://github.com/apache/datafusion/issues/9637
I was looking for why ApplyFunctionRewrite takes so much time in planning benchmarks (see https://github.com/apache/datafusion/issues/9637#issuecomment-2073325456) and noticed this. Note that this particular change is tiny and likely won't make a change but I figured I would at least make a PR for it
Avoid a few clones
=> Minor: Avoid a clone in ArrayFunctionRewriter

datafusion/functions/src/core/coalesce.rs, datafusion/functions/src/core/mod.rs, datafusion/functions/src/math/mod.rs
closes https://github.com/apache/datafusion/issues/10174
The current location of the coalesce function isn't really the best place for it.
Move coalesce function from math to core
All unit tests, sqllogictests and integration tests have passed.
No.
=> Move coalesce function from math to core

datafusion-cli/src/main.rs
Closes #.
Prevent empty datafusion-cli commands
```
datafusion-cli --command ""
datafusion-cli -c ""
datafusion-cli --command "" "command"
datafusion-cli -c "" "command"
```
Yes, manually
=> Minor: Prevent empty datafusion-cli commands

datafusion/functions/Cargo.toml, datafusion/functions/benches/date_bin.rs, datafusion/functions/src/datetime/date_bin.rs
Closes https://github.com/apache/datafusion/issues/10228
`date_bin` could be faster.
As mentioned in the docs for `PrimaryArray::unary` it is faster to apply an infallible operation across both valid and invalid values, rather than branching at every value.
1) Make stride function infallible
2) Use `unary` method
This gives this speedup on my machine:
Before: 22.345 µs
After: 10.558 µs
So around 2x faster
Yes, existing tests.
The `date_bin` function runs faster.
=> Optimize date_bin (2x faster)

datafusion/common/src/dfschema.rs, datafusion/optimizer/src/optimize_projections/mod.rs, datafusion/optimizer/src/optimize_projections/required_indices.rs
Part of https://github.com/apache/datafusion/issues/10209
This is part 1 of improving the performance of `OptimizeProjection` (by less copying) in https://github.com/apache/datafusion/issues/10209.
While trying to rework how `OptimizeProjection works`, I found that the population
of child indices pretty much required calling `LogicalPlan::expressions()` which results in an owed copy of all the plans `Expr`s
Removing these copies themselves improves the situation (and I think may make the code easier to reasona about), and sets us up to stop copying the `LogicalPlan` nodes as a follow on PR
This PR encapsulates that logic for managing required indices into a new struct `RequiredIndicies` which avoids some Expr copies (and sets up the rewrite to avoid `LogicalPlan` copies)
Covered by …
=> Avoid `Expr` copies `OptimizeProjection`, 12% faster planning, encapsulate indicies

doap.rdf
This closes https://github.com/apache/datafusion/issues/10133.
cc @alamb
=> chore: Create a doap file

datafusion/common/src/config.rs, datafusion/common/src/file_options/mod.rs, datafusion/common/src/file_options/parquet_writer.rs, datafusion/core/src/datasource/file_format/parquet.rs, datafusion/proto/src/physical_plan/from_proto.rs, datafusion/sqllogictest/test_files/copy.slt
Closes #10223 .
Related to https://github.com/apache/datafusion/issues/9493
Restore the ability to set user-inserted metadata into the writer properties of ParquetSink, and to enable this as a SQL level API configurable.
Broken up per commit:
* chore: make explicit what ParquetWriterOptions are created from a subset of TableParquetOptions
* this is code cleanup to make explicit the reported bug
* refactor: restore the ability to add kv metadata into the generated file sink
* test: demonstrate API contract for metadata TableParquetOptions
* this adds a new SQL level API for adding metadata, including tests.  
New feature added **UPDATED syntax**:
```
COPY source_table TO 'sink' STORED AS PARQUET OPTIONS ('format.metadata::key' 'value')
```
Yes. We have both integration tests for the …
=> Allow adding user defined metadata to `ParquetSink`

datafusion-cli/Cargo.lock, datafusion/optimizer/Cargo.toml, datafusion/optimizer/src/eliminate_duplicated_expr.rs
=> refactor `EliminateDuplicatedExpr` optimizer pass to avoid clone

datafusion/core/benches/aggregate_query_sql.rs, datafusion/physical-expr/src/aggregate/build_in.rs, datafusion/physical-expr/src/aggregate/median.rs, datafusion/physical-expr/src/expressions/mod.rs, datafusion/physical-plan/src/aggregates/mod.rs, datafusion/sqllogictest/test_files/aggregate.slt
Closes #2411
Support for explicit distinct median aggregation function, allowing queries such as below to execute now:
```sql
select median(a), median(distinct a) from t
```
Essentially duplicated the existing Median aggregation function but aggregate into HashSet instead of a Vec.
Chose HashSet over BTreeMap as figured the insert path is hotter than the fetch path (which is essentially once at evaluation), and (limited) benchmarking didn't show too significant a difference between the two.
Yes, tests added
=> Support for median(distinct) aggregation function

datafusion/sqllogictest/test_files/functions.slt
Closes https://github.com/apache/datafusion/issues/10247
We have a gap in test coverage
All the tests passed, but we almost broke this behavior, but caught it in review https://github.com/apache/datafusion/pull/10193#discussion_r1576674821
1. Add tests for `random` and `uuid`
Note I also verified that these tests fail at https://github.com/apache/datafusion/pull/10193/commits/864d197cdcc7ed0a37a63f197652f0dd5171cb49 (part of https://github.com/apache/datafusion/pull/10193 which almost introduced a bug)
Only tests
=> Add tests that `random()` and `uuid()` produce unique values for each row

datafusion/core/src/physical_optimizer/projection_pushdown.rs, datafusion/core/tests/user_defined/user_defined_scalar_functions.rs, datafusion/expr/src/type_coercion/functions.rs, datafusion/expr/src/udf.rs, datafusion/functions-array/src/make_array.rs, datafusion/functions/src/math/pi.rs, datafusion/functions/src/math/random.rs, datafusion/functions/src/string/uuid.rs, datafusion/physical-expr/src/functions.rs, datafusion/physical-expr/src/scalar_function.rs, datafusion/physical-expr/src/udf.rs, datafusion/proto/src/physical_plan/from_proto.rs, datafusion/proto/tests/cases/roundtrip_physical_plan.rs
Issue from https://github.com/apache/datafusion/pull/10098/files/a422b3ab10519efea3ec671fef944a1dcf8aaf96#r1573855672
Closes #10205 .
Closes #10247 
1. Remove `supports_zero_argument `
2. ~Introduce `support_randomness`~
3. Introduce `invoke_no_args`
=> ScalarUDF: Remove `supports_zero_argument` and avoid creating null array for empty args

datafusion/expr/src/built_in_window_function.rs, datafusion/expr/src/expr.rs, datafusion/sql/src/unparser/expr.rs
Related #9726 .
1. Support filter field in aggregate function
2. Support WindowFunction Expr->String
=> Add Expr->String for WindowFunction

datafusion/core/src/physical_optimizer/join_selection.rs
Closes #.
https://github.com/apache/datafusion/pull/9346 removes the `PipelineStatePropagator`, so there is no need to check `Arc<dyn ExecutionPlan>` and `TreeNode` integrity anymore. The new rule applies on `Arc<dyn ExecutionPlan>`'s directly. This PR just cleans up redundant lines.
Remove unnecessary and not-applicable test codes regarding this.
=> Minor Clean-up in JoinSelection Tests

datafusion/sql/src/expr/mod.rs, datafusion/sqllogictest/test_files/expr.slt, datafusion/sqllogictest/test_files/functions.slt
Closes #10240.
Before version 0.45.0 of sqlparser, the `special` flag for both `substring('xxxx', 1, 2)` and `substring('xxxx' from 1 for 2)` was false. 
After https://github.com/sqlparser-rs/sqlparser-rs/pull/1173, the `special` flag for `substring('xxxx', 1, 2)` becomes true.
We need to support both formats  as before, so there's no need to check the `special` flag.
The 'from' and 'for' parameters don't support string types because they should be treated as regular expressions. Currently, substring is just an alias of`substr`. This PR adds tests to verify this.
Reference document: https://www.postgresql.org/docs/current/functions-string.html
Re-enable `substring('xxxx', 1, 2)`.
Yes
No
=> fix: no longer support the `substring` function

datafusion/proto/src/generated/mod.rs
Closes https://github.com/apache/datafusion/issues/10163
Docs.rs is broken failed for https://docs.rs/crate/datafusion-proto/latest 
The build has a log https://docs.rs/crate/datafusion-proto/37.0.0/builds/1179419 shows the error that the `generated` module isn't working
Remove cfg to get working again (maybe)
No -- I don't know how to test them. In the other hands the docs are broken so this isn't going to make them any more broken 🤷
=> Fix docs.rs build for datafusion-proto (hopefully)

datafusion/expr/src/columnar_value.rs
Part of #7013 
While reviewing https://github.com/apache/datafusion/pull/10148 I realized that the documentation for `ColumnarValue` could be improved.
Improve the documentation
CI
Better docs. No code change
=> Improve documentation on `ColumnarValue`

datafusion/physical-plan/src/lib.rs, datafusion/physical-plan/src/repartition/distributor_channels.rs
Closes #10246 
Add `static_name()` method to make the name of an execution plan accessible without constructing the struct. 
A new public API in `ExecutionPlan`
Yes
Yes
=> feat: add static_name() to ExecutionPlan

datafusion/common/src/dfschema.rs
Following https://github.com/apache/datafusion/pull/9595 we can avoid needing to potentially clone the underlying arrow schema
=> Zero-copy conversion from SchemaRef to DfSchema

datafusion/physical-plan/src/common.rs, datafusion/physical-plan/src/sorts/sort.rs
Closes #9937.
Currently, `IPCWriter` metrics types are `u64` based but source values are based on `usize` so this requires redundant casting on `IPCWriter.write()` and `ExternalSorter.spill()`. On the other hand, another benefit of `usize` is that it guarantees to reference enough memory location by depending on the architecture such as `u32` or `u64`.
**Ref Discussion:** https://github.com/apache/datafusion/pull/9885#discussion_r1545794898
Yes by using existing UT case such as `SortExec.test_sort_spill`
No
=> refactor: Convert `IPCWriter` metrics from `u64` to `usize`

datafusion/sqllogictest/test_files/map.slt
Follow on to https://github.com/apache/datafusion/pull/10148
While reviewing https://github.com/apache/datafusion/pull/10148 it was not clear to me from the test file output the correct answer was, so I had to go look at the file directly
It would be nice to have the test a little more self documenting
1. Add some additional coverage to `map.slt`
They are only tests
No code changes - only tests
=> Minor: Add some more tests to map.slt

datafusion/physical-plan/src/joins/sort_merge_join.rs
Closes #.
I saw this error message `Unsupported data type in sort merge join comparator` when debugging some issues in Comet. It reads a bit confusing and doesn't provide useful info. It would be better at least we can add the data type info into the error message.
=> chore: Add datatype info to error message

datafusion/common/src/scalar/mod.rs, datafusion/core/src/datasource/listing/helpers.rs, datafusion/core/src/physical_planner.rs, datafusion/expr/src/expr.rs, datafusion/expr/src/expr_schema.rs, datafusion/expr/src/tree_node.rs, datafusion/functions/src/math/log.rs, datafusion/functions/src/math/power.rs, datafusion/optimizer/src/analyzer/type_coercion.rs, datafusion/optimizer/src/push_down_filter.rs, datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs, datafusion/physical-expr/src/planner.rs, datafusion/physical-expr/src/scalar_function.rs, datafusion/proto/src/logical_plan/to_proto.rs, datafusion/proto/src/physical_plan/to_proto.rs, datafusion/substrait/src/logical_plan/producer.rs
part of https://github.com/apache/datafusion/issues/10175 .
=> Remove `ScalarFunctionDefinition::Name`

datafusion/physical-expr/src/scalar_function.rs
It appears https://github.com/apache/datafusion/pull/10277 had a logical conflict
https://github.com/apache/datafusion/actions/runs/8899641374/job/24439454308
```
error: cannot find macro `internal_err` in this scope
--> datafusion/physical-expr/src/scalar_function.rs:156:32
|
156 |                         return internal_err!("UDF returned a different number of rows than expected. Expected: {}, Got: {}", 
|                                ^^^^^^^^^^^^
|
help: consider importing this macro
|
32  + use datafusion_common::internal_err;
```
Fix build
Add required `use`
CI
=> Fix build with missing `use` ( `" return internal_err!("UDF returned a different ..."`)

docs/source/contributor-guide/index.md
Part of #9691 
Noticed while reviewing the docs
1. Update the link to list of committers from arrow to datafusion
CI tests
=> [Minor] Update link to list of committers in contributor guide

datafusion/optimizer/src/eliminate_filter.rs, datafusion/optimizer/tests/optimizer_integration.rs
=> Optimize EliminateFilter to avoid unnecessary copies #10288

datafusion/execution/src/config.rs
This is supposed to be a part of https://github.com/apache/datafusion/pull/10259 to solve https://github.com/apache/datafusion/issues/10257 but I miss this function.
Closes #.
=> chore: add function to set prefer_existing_union

datafusion-examples/README.md, datafusion-examples/examples/parquet_exec_visitor.rs
=> `ExecutionPlan` visitor example documentation

datafusion/optimizer/src/rewrite_disjunctive_predicate.rs
Part of https://github.com/apache/datafusion/issues/9637
Closes https://github.com/apache/datafusion/issues/10213
=> Stop copying LogicalPlan and Exprs in `RewriteDisjunctivePredicate`

datafusion/optimizer/src/unwrap_cast_in_comparison.rs, datafusion/sqllogictest/test_files/dictionary.slt
Closes https://github.com/apache/datafusion/issues/10220
Improves performance of queries that filter string/dictionary columns against literals (`WHERE dict_col = 1`) by avoiding casting the column
Allows the optimizer to unwrap casts of string types in comparison operations. 
Yes 
No
=> feat: unwrap casts of string and dictionary columns

datafusion/optimizer/src/decorrelate_predicate_subquery.rs, datafusion/physical-expr/src/scalar_function.rs
Part of https://github.com/apache/datafusion/issues/9637
Closes https://github.com/apache/datafusion/issues/10289 
Reduce copying in 
1. Avoid clones in `DecorrelatePredicateSubquery` 
No
=> Stop copying LogicalPlan and Exprs in `DecorrelatePredicateSubquery`

datafusion/common/src/scalar/mod.rs
This PR resolves an issue in which we get a panic attempting to concatenate empty arrays. This prevents lead and lag functions from working on these data types.
Closes #10328.
When we call `WindowAggState::new` with a data type of a list, we will call `ScalarValue::try_from(out_type)?.to_array_of_size(0)` which in turn calls `list_to_array_of_size`. Within this function there is no check on the return size. It could be zero due to either an empty array input or a request for 0 elements. In either of these conditions, you will get a panic from `concat`.
This is a small change to check the return size. When zero it will just take an empty slice of the original array.
I have included an expansion to an existing unit test to cover this. In my bug report I have also shown minimal example to …
=> Check list size before concat in ScalarValue

datafusion-examples/examples/expr_api.rs, datafusion/core/src/test_util/parquet.rs, datafusion/optimizer/src/analyzer/type_coercion.rs, datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs
Closes https://github.com/apache/datafusion/issues/3793
1. Permit making an API for https://github.com/apache/datafusion/issues/10181 that takes a `&DFSchema` rather than an owned
2. Avoid a copy and thus make the API marginally faster in some cases. 
Change `coerce` API from 
```rust
pub fn coerce(&self, expr: Expr, schema: DFSchemaRef) -> Result<Expr> {
```
to
```rust
pub fn coerce(&self, expr: Expr, schema: &DFSchema) -> Result<Expr> {
```
By existing CI
The API to call coerce is slightly changed. Note I am in the process of adding a proper fully baked API in https://github.com/apache/datafusion/issues/10181
=> Improve coerce API so it does not need DFSchema

datafusion/expr/src/expr_rewriter/mod.rs, datafusion/optimizer/src/eliminate_nested_union.rs
Closes #10296.
Existing tests pass
=> Stop copying LogicalPlan and Exprs in EliminateNestedUnion

datafusion/sqllogictest/test_files/window.slt
re https://github.com/apache/datafusion/issues/10328
follow on to https://github.com/apache/datafusion/pull/10329
In addition to the unit test from @timsaucer  in https://github.com/apache/datafusion/pull/10329 I thought it would be good to have an end to end test showing window functions on arrays
add sqllogictest
only tests
=> Minor: Add sql level test for lead/lag on arrays

datafusion/expr/src/simplify.rs, datafusion/functions/src/math/log.rs
Closes https://github.com/apache/datafusion/issues/10359.
yes
no
=> fix: LogFunc simplify swaps arguments

datafusion/common/src/tree_node.rs
Part of #10121 
I continually get confused between when to use `Transformed::update_data`, `Transformed::map_data`, and `Transformed::transform_data` -- it would be nice for the docstrings to make it clear what the usecase is for each one
Clarify the docstrings to hopefully make it clearer what each does
CI
Better docs, no functional changes
=> Refine documentation for `Transformed::{update,map,transform})_data`

datafusion/core/src/execution/context/mod.rs, datafusion/execution/src/task.rs
Part of #7013 
As @westonpace  explained in https://github.com/apache/datafusion/pull/10330#discussion_r1586871715 the relationship and differences between these classes is not clear. 
Try to clarify the differences and when people should create one or the other
CI doc checks
Just docs, no change in functionality
=> Clarify docs explaining the relationship between `SessionState` and `SessionContext`

datafusion/optimizer/src/push_down_filter.rs
=> Optimized push down filter #10291

datafusion/sql/src/unparser/expr.rs
=> Unparser: Support `ORDER BY` in window function definition

docs/source/index.rst, docs/source/user-guide/introduction.md
N/A
Add links to DataFusion subproject to make them more easily discoverable
- Added links to menu
- Moved bdt from the list of active projects to the list of less active projects
- Reordered list of projects so that they are in alphabet order
Tested locally
No
=> docs: Add DataFusion subprojects to navigation menu, other minor updates

datafusion/sql/src/unparser/plan.rs, datafusion/sql/tests/sql_integration.rs
Part of https://github.com/apache/datafusion/issues/8661
Came across this issue when trying to federate a query selecting from multiple tables with different sources. For example, `SELECT a_1, b_1 FROM table_a, table_b` is evaluated as a cross join, but the unparser wasn't handling cross joins yet.
Allow unparsing of cross joins into the equivalent inner join.
Added a test for cross join roundtrip. It is slightly different from the other roundtrips because `sqlparser` doesn't have an implementation for Cross Join, so it gets converted into an Inner Join.
=> feat: Add CrossJoin match case to unparser

datafusion-examples/examples/rewrite_expr.rs, datafusion/core/src/execution/context/mod.rs, datafusion/core/tests/optimizer_integration.rs, datafusion/optimizer/src/analyzer/count_wildcard_rule.rs, datafusion/optimizer/src/analyzer/inline_table_scan.rs, datafusion/optimizer/src/analyzer/mod.rs, datafusion/optimizer/src/analyzer/type_coercion.rs, datafusion/optimizer/src/decorrelate_predicate_subquery.rs, datafusion/optimizer/src/scalar_subquery_to_join.rs, datafusion/optimizer/src/test/mod.rs, datafusion/optimizer/tests/optimizer_integration.rs
(this has 4 lines of code change and the rest are test updates to remove `&`)
Part of https://github.com/apache/datafusion/issues/9637
The current `Analyzer::execute_and_check` API requires cloning a `LogicalPlan`
1. Change `Analyzer::execute_and_check` to take an owned plan (and thus the caller to do the clone if they don't have one)
CI
Note I expect this to have a limited impact on performance as the higher level APIs (e.g. `SessionState::optimize` still take a `&LogicalPlan`) but at least the lower level APIs wont
=> Minor: Do not force analyzer to copy logical plans

datafusion/common/src/utils.rs, datafusion/core/src/physical_optimizer/join_selection.rs, datafusion/physical-expr-common/src/physical_expr.rs, datafusion/physical-plan/src/lib.rs
Closes #10377.
According to https://github.com/rust-lang/rust/pull/106450, Arc::ptr_eq now compares two pointer without metadata. 
So, it is safe to remove DataPtr trait and use Arc::ptr_eq directly.
This PR removed the DataPtr trait and replace all Arc::data_ptr_eq with Arc::ptr_eq.
Yes
No
=> chore: remove DataPtr trait since Arc::ptr_eq ignores pointer metadata

datafusion/core/tests/sql/sql_api.rs, datafusion/expr/src/logical_plan/builder.rs, datafusion/expr/src/logical_plan/dml.rs, datafusion/expr/src/logical_plan/plan.rs, datafusion/expr/src/logical_plan/tree_node.rs, datafusion/sql/src/statement.rs, datafusion/sqllogictest/test_files/aggregate.slt, datafusion/sqllogictest/test_files/array.slt, datafusion/sqllogictest/test_files/create_external_table.slt, datafusion/sqllogictest/test_files/insert.slt, datafusion/sqllogictest/test_files/insert_to_external.slt, datafusion/sqllogictest/test_files/math.slt
Previously, `LogicalPlan::schema` would return the input schema for DML plans, rather than the expected output schema. It is typical for the output to be the `count` of rows affected by the DML statement, so the code assumes that.
See `fn dml_output_schema` for a test.
Closes #10393.
Current behaviour is wrong.
Yes there is a test `fn dml_output_schema`.
The bug being fixed is visible to users of the DataFrame API.
=> fix dml logical plan output schema

datafusion/common/src/utils.rs, datafusion/physical-plan/src/common.rs, datafusion/physical-plan/src/repartition/mod.rs, datafusion/physical-plan/src/windows/window_agg_exec.rs
Closes #.
`fn transpose` code is under `datafusion/physical-plan/src/common.rs` currently. However, this code is pretty generic. I think, we might benefit it being in under `datafusion/common/src/utils.rs` to extend its visibility.
=> [MINOR]: Move transpose code to under common

datafusion/core/src/dataframe/mod.rs, datafusion/expr/src/utils.rs
Closes #10346.
[exprlist_to_fields_aggregate](https://github.com/apache/datafusion/blob/a0fccbf886346fde5dfbda136149ec98bbd6e952/datafusion/expr/src/utils.rs#L737) was introduced by https://github.com/apache/datafusion/pull/2486. 
It was necessary for the test `aggregate_with_rollup_with_grouping`.
https://github.com/apache/datafusion/blob/5335f8055636a0e11f8bcda8a3084edba825f79e/datafusion/core/src/sql/planner.rs#L4698-L4705
In this test, the grouped-by expression `person.state` was not included in the aggregate's output schema,  so we need to further check the aggregate's input, as mentioned in the comments.
> // when dealing with aggregate plans we cannot simply look in the aggregate output schema
// because it will contain columns representing complex expressions (such a column named …
=> Fix incorrect Schema over aggregate function, Remove unnecessary `exprlist_to_fields_aggregate`

datafusion/core/src/physical_planner.rs, datafusion/expr/src/expr.rs, datafusion/expr/src/udf.rs, datafusion/functions/src/core/getfield.rs
=> Enable user defined display_name for ScalarUDF

datafusion/core/src/catalog/information_schema.rs, datafusion/sqllogictest/test_files/information_schema.slt
Simplify making information_schame tables and avoid potential bug that someone forgets adding logic for new table here.
=> Simplify making information_schame tables

datafusion/core/src/datasource/listing/url.rs
Query string and fragment should not be considered when deciding if the path is a collection
Will open one if needed, but the PR itself is descriptive enough.
See tests in the PR. It can be common if a remote object store takes query string or fragment for other perspective, e.g. tracking.
Yes
No
=> only consider main part of the url when deciding is_collection in listing table

datafusion/physical-expr/src/equivalence/mod.rs, datafusion/physical-expr/src/equivalence/properties.rs
Closes #.
See [issue #9812](https://github.com/apache/datafusion/issues/9812) for rationale.
When an equality expression is added to the `EquivalenceProperties`. In light of this information, we can deduce new information about ordering and constantness. This PR adds this support. 
With the [PR #9813](https://github.com/apache/datafusion/pull/9813) we have this support, in terms of behaviour. However, current solution doesn't update state and cannot generalize well.
There is an additional TestCase, that showcases increased coverage with this implementation (That test case fails in main branch).
=> During expression equality, check for new ordering information

datafusion-examples/examples/flight/flight_sql_server.rs, datafusion/expr/src/table_source.rs
Implement `get_flight_info_tables` and remove unimplemented methods.
=> Improve flight sql examples

datafusion/expr/src/expr.rs, datafusion/expr/src/logical_plan/plan.rs, datafusion/optimizer/src/optimize_projections/mod.rs, datafusion/optimizer/src/utils.rs, datafusion/sqllogictest/test_files/cte.slt, datafusion/sqllogictest/test_files/joins.slt
Note this also has the changes from https://github.com/apache/datafusion/pull/10410 in it
Closes https://github.com/apache/datafusion/issues/10209
Make planning faster by not copying as much
1. Rewrite `OptimizeProjections` to use treenode APIs
Existing tests
1. More types of projections can be combined (e.g. `CASE` expressions)
1. Faster planning 
Benchmark Results show a moderate improvement (2% overall in tpch, but some queries like Q3 are like 10% faster)
<details><summary>Details</summary>
<p>
```
++ critcmp main projection_pushdown
group                                         main                                   projection_pushdown
-----                                         ----                                   -------------------
logical_aggregate_with_join …
```
=> Stop copying LogicalPlan and Exprs in `OptimizeProjections` (2% faster planning)

datafusion/optimizer/src/push_down_filter.rs
Related to https://github.com/apache/datafusion/issues/10291
While reviewing this code for https://github.com/apache/datafusion/issues/10291 I found several places the doc comments could be improved, and I thought those changes would be easy to review as their own PR
* make `//` to `///` 
* Add some additional  markdown style
No this is internal documentation -- none of these changes are user facing
=> Minor: format comments in `PushDownFilter` rule

datafusion/functions-aggregate/README.md, dev/release/README.md
N/A
I ran into a couple of minor issues during the 38.0.0 release process
- Add new crates to the release instructions
- Add a README to the new functions-aggregate crate
- Remove some content from the release instructions that isn't really needed
=> chore: Improve release process for next time

datafusion/expr/src/logical_plan/plan.rs
As part of the review https://github.com/apache/datafusion/pull/10410 @yyy1000 had a good question https://github.com/apache/datafusion/pull/10410#discussion_r1594990402
Adding some additional explanation I think will help make this clearer
Add doc comments
by CI doc checks
More docs
=> Minor: Add usecase to comments in `LogicalPlan::recompute_schema`

README.md, docs/source/index.rst
=> doc: fix old master branch references to main

datafusion/expr/src/expr_schema.rs, datafusion/expr/src/signature.rs, datafusion/expr/src/type_coercion/functions.rs, datafusion/expr/src/udaf.rs, datafusion/expr/src/udf.rs, datafusion/functions-array/src/make_array.rs, datafusion/functions/src/core/coalesce.rs, datafusion/functions/src/core/nvl2.rs, datafusion/optimizer/src/analyzer/type_coercion.rs, datafusion/physical-expr/src/scalar_function.rs, datafusion/sqllogictest/test_files/array.slt, datafusion/sqllogictest/test_files/arrow_typeof.slt, datafusion/sqllogictest/test_files/coalesce.slt, datafusion/sqllogictest/test_files/encoding.slt, datafusion/sqllogictest/test_files/errors.slt, datafusion/sqllogictest/test_files/expr.slt, datafusion/sqllogictest/test_files/math.slt, datafusion/sqllogictest/test_files/scalar.slt, datafusion/sqllogictest/test_files/struct.slt, datafusion/sqllogictest/test_files/timestamps.slt
Closes #10423 .
Add `VariadicCoercion`, `UniformCoercion`
Remove `VariadicEqual` (coercion rule does not require the result type to be the same for all)
Add the datafusion error aside from the signature error message for better debugging usage that is why many test files are updated.
UDAF code is also included but no test is covered since no UDAF requires coercion there yet (We will cover it after moving builtin to UDAF)
=> Introduce user-defined signature

datafusion/core/src/physical_planner.rs, datafusion/expr/src/expr.rs, datafusion/expr/src/expr_schema.rs, datafusion/expr/src/tree_node.rs, datafusion/optimizer/src/analyzer/type_coercion.rs, datafusion/optimizer/src/decorrelate.rs, datafusion/proto/src/logical_plan/to_proto.rs, datafusion/substrait/src/logical_plan/producer.rs
Remove `AggregateFunctionDefinition::Name` as it's useless.
=> Remove `AggregateFunctionDefinition::Name`

datafusion-examples/examples/simplify_udaf_expression.rs, datafusion/expr/src/function.rs, datafusion/expr/src/udaf.rs, datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs
Closes #9526.
yes, added new test and example 
no, changes are backward compatible
=> Add `simplify`  method to aggregate function

datafusion/sqllogictest/test_files/cast.slt
=> Add cast array test to sqllogictest

datafusion/expr/src/logical_plan/builder.rs
Closes  https://github.com/apache/datafusion/issues/10465
This PR implements `From` trait for converting `Arc<LogicalPlan>` into `LogicalPlanBuilder`
Yes
No
=> Implement `From<Arc<LogicalPlan>>` for `LogicalPlanBuilder`

datafusion/functions-array/src/array_has.rs, datafusion/functions-array/src/cardinality.rs, datafusion/functions-array/src/concat.rs, datafusion/functions-array/src/dimension.rs, datafusion/functions-array/src/empty.rs, datafusion/functions-array/src/except.rs, datafusion/functions-array/src/extract.rs, datafusion/functions-array/src/flatten.rs, datafusion/functions-array/src/length.rs, datafusion/functions-array/src/macros.rs, datafusion/functions-array/src/make_array.rs, datafusion/functions-array/src/position.rs, datafusion/functions-array/src/range.rs, datafusion/functions-array/src/remove.rs, datafusion/functions-array/src/repeat.rs, datafusion/functions-array/src/replace.rs, datafusion/functions-array/src/resize.rs, datafusion/functions-array/src/reverse.rs, datafusion/functions-array/src/rewrite.rs, datafusion/functions-array/src/set_ops.rs, datafusion/functions-array/src/sort.rs, datafusion/functions-array/src/string.rs, datafusion/proto/tests/cases/roundtrip_logical_plan.rs
Closes #10424.
Based on the draft PR #10450, and reuse the existing `make_udf_function` macro as much as possible.
- Allow array_slice to take an optional stride parameter
Not sure whether it's necessary to write a test for this.
Yes
=> feat: allow `array_slice` to take an optional stride parameter

datafusion/core/src/dataframe/mod.rs, datafusion/core/tests/dataframe/mod.rs, datafusion/core/tests/user_defined/user_defined_table_functions.rs, datafusion/expr/src/expr.rs, datafusion/expr/src/logical_plan/builder.rs, datafusion/expr/src/logical_plan/plan.rs, datafusion/expr/src/utils.rs, datafusion/optimizer/src/common_subexpr_eliminate.rs, datafusion/optimizer/src/single_distinct_to_groupby.rs, datafusion/sqllogictest/test_files/select.slt, datafusion/substrait/tests/cases/roundtrip_logical_plan.rs
Closes #10413.
[`columnize_expr`](https://github.com/apache/datafusion/blob/8cc92a921f3b0296caf035edb66a4b3c422f084d/datafusion/expr/src/logical_plan/builder.rs#L1413) is used during planning projections.  Usually, a projected expr can only reference the output data of the input plan through a column reference, but this does not work for aggregation and window functions. For example
```rust
let aggr_expr = sum(col("c2"));
let df = test_table()
.await?
.aggregate(vec![], vec![aggr_expr.clone()])?
.select(vec![aggr_expr])?;
```
The aggregate expression `sum(col("c2"))` is calculated in the aggregate logical plan, and the projection plan references its result through the aggregate expression directly. To make it work appropriately, we need to convert the aggregate expression in the …
=> fix: make `columnize_expr` resistant to display_name collisions

datafusion/core/src/datasource/physical_plan/json.rs
Closes #10435.
Turning off repartitioning for compressed JSON files allows not to fail on reading such files.
Same as above
Test for reading gzipped JSON with forced repartitioning (controlled by settings), extended with other compression types.
No
=> fix: avoid compressed json files repartitioning

datafusion/expr/src/logical_plan/builder.rs
This pull request contains missing document for PR https://github.com/apache/datafusion/pull/10466
Closes: https://github.com/apache/datafusion/issues/10465.
=> Minor: Improved document string for `LogicalPlanBuilder`

datafusion/core/tests/sql/joins.rs, datafusion/physical-plan/src/joins/sort_merge_join.rs, datafusion/sqllogictest/test_files/sort_merge_join.slt
=> Fix SortMergeJoin with join filter filtering all rows out

datafusion/functions-array/src/array_has.rs, datafusion/functions-array/src/cardinality.rs, datafusion/functions-array/src/concat.rs, datafusion/functions-array/src/dimension.rs, datafusion/functions-array/src/empty.rs, datafusion/functions-array/src/except.rs, datafusion/functions-array/src/extract.rs, datafusion/functions-array/src/flatten.rs, datafusion/functions-array/src/length.rs, datafusion/functions-array/src/macros.rs, datafusion/functions-array/src/make_array.rs, datafusion/functions-array/src/position.rs, datafusion/functions-array/src/range.rs, datafusion/functions-array/src/remove.rs, datafusion/functions-array/src/repeat.rs, datafusion/functions-array/src/replace.rs, datafusion/functions-array/src/resize.rs, datafusion/functions-array/src/reverse.rs, datafusion/functions-array/src/set_ops.rs, datafusion/functions-array/src/sort.rs, datafusion/functions-array/src/string.rs
Closes #.
cleanup code. The benefit is that we don't need to import for macro.
=> chore: use fullpath in macro to avoid declaring in other module

datafusion/functions-aggregate/src/macros.rs, datafusion/proto/tests/cases/roundtrip_logical_plan.rs
Closes #.
Part of #10484 
Improve expr_fn usage
1. add expr_fn for `count(arg, dictinct)` where has additional argument `distinct`
2. `covariance_pop(arg)` where has no any additional argument
=> Minor: Extend more style of udaf `expr_fn`, Remove order args for`covar_samp` and `covar_pop` 

datafusion/core/tests/dataframe/dataframe_functions.rs, datafusion/functions/src/regex/mod.rs
Closes #10512
The inner implementations of these UDFs depend on the number of arguments passed. This exposes that to users of the UDFs.
for each of `regexp_match` regexp_like` and `regexp_replace`
- Changes / adds optional arguments to match inner impl
- Updates argument names to match inner impl
Yes. Each function already had a test case, and were updated to include variants for the optional arguments.
Yes.
- `expr_fn::regexp_replace` signature has changed
- `expr_fn::regexp_like` signature has changed
- `expr_fn::regexp_match` signature has changed
=> feat: optional args for regexp_* UDFs

datafusion/core/src/physical_optimizer/aggregate_statistics.rs, datafusion/core/src/physical_planner.rs, datafusion/expr/src/expr.rs, datafusion/optimizer/src/analyzer/count_wildcard_rule.rs, datafusion/optimizer/src/single_distinct_to_groupby.rs, datafusion/physical-expr-common/src/aggregate/mod.rs, datafusion/physical-plan/src/windows/mod.rs, datafusion/proto/src/physical_plan/mod.rs, datafusion/proto/tests/cases/roundtrip_physical_plan.rs, datafusion/sql/src/expr/function.rs, datafusion/substrait/src/logical_plan/producer.rs
Closes #.
Most of the function expect the same args or the same behaviour as builtin aggregate function for UDAF.
This PR change most of them I need for #10484
=> Support UDAF to align Builtin aggregate function

datafusion/core/src/datasource/file_format/arrow.rs, datafusion/core/src/datasource/file_format/avro.rs, datafusion/core/src/datasource/file_format/csv.rs, datafusion/core/src/datasource/file_format/json.rs, datafusion/core/src/datasource/file_format/mod.rs, datafusion/core/src/datasource/file_format/parquet.rs
Closes #8657
Was implementing rudimentary ORC integration for DataFusion:
https://github.com/datafusion-contrib/datafusion-orc/blob/main/src/datafusion/file_format.rs
Noticed that to implement `FileFormat` it requires a `file_type()`, even though this is not really used anywhere. Removing this can make it clearer for those wanting to extend with more custom file formats.
Remove `FileFormat::file_type()` which was unused.
Yes, function removed from trait
=> Remove `file_type()` from `FileFormat`

datafusion/sqllogictest/test_files/timestamps.slt
N/A
While working with @tisonkun  on https://github.com/apache/datafusion/pull/10392 I realized there was no test coverage for the `current_time` form (with no parens). I added a test and a fix to that branch but I want to make sure we don't accidentally break it before that PR lands
1. Add sqllogictest for `current_time` syntax
All tests
=> Minor: add a test for `current_time` (no args)

datafusion/functions/src/datetime/common.rs, datafusion/functions/src/datetime/to_timestamp.rs, datafusion/sqllogictest/test_files/dates.slt
Closes #10471.
Fallback to `Parsed::to_naive_date` when `Parsed::to_naive_datetime_with_offset` failed if there is only date in format string.
Same as above.
1. Add unit test
The timestamp of "2022-01-23" is `1642896000000000000` as written in the test.
2. Test using datafusion-cli
No
=> fix: parsing timestamp with date format

datafusion/core/src/physical_optimizer/optimizer.rs, datafusion/sqllogictest/test_files/explain.slt
Closes #.
`PipelineChecker` rule either accepts the physical plan (marking it as safe to execute) or rejects it. In this sense, it doesn't change anything in the plan. It just checks the validity of the generated plan. Hence, I think with this behavior it is more apropriate for this rule to execute after other rules (where plans might be modified by rules.)
With this PR, `PipelineChecker` works at the end after other rules.
Existing tests, should work
=> [MINOR]: Move pipeline checker rule to the end

datafusion/core/tests/fuzz_cases/window_fuzz.rs, datafusion/physical-plan/src/windows/mod.rs, datafusion/proto/src/physical_plan/from_proto.rs, datafusion/proto/tests/cases/roundtrip_physical_plan.rs
Fix window expr deserialization bug which introduced in https://github.com/apache/datafusion/pull/9686.
We encountered the error like this when deserializing window plan from proto.
```
from proto: ArrowError(SchemaError("Unable to get field named \"FIRST_VALUE(a) PARTITION BY [b] ORDER BY [a ASC NULLS LAST] RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\". Valid fields: [\"a\", \"b\"]"), None)
```
The error thrown at https://github.com/apache/datafusion/blob/main/datafusion/physical-plan/src/windows/mod.rs#L188.
If I understand correctly, now `create_window_expr` function needs output schema of window plan instead of the schema of window plan input. So we should build extended schema which contains input schema and window fields.
=> Fix window expr deserialization

datafusion/sql/src/unparser/expr.rs
Closes #10519 
I found that `is_not_null` has been supported. I only implement 'is_null` here.
Yes, I also added more test cases for `is_null` and `is_not_null` (e.g. function call and case when).
No
=> Implement unparse `IS_NULL` to String and enhance the tests

datafusion/physical-expr/src/aggregate/array_agg_distinct.rs, datafusion/sqllogictest/test_files/aggregate.slt
=> Fix panic in array_agg(distinct) query

datafusion-examples/examples/advanced_udaf.rs, datafusion-examples/examples/simplify_udaf_expression.rs, datafusion/core/tests/user_defined/user_defined_aggregates.rs, datafusion/expr/src/expr_fn.rs, datafusion/expr/src/function.rs, datafusion/expr/src/udaf.rs, datafusion/functions-aggregate/src/covariance.rs, datafusion/functions-aggregate/src/first_last.rs, datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs, datafusion/physical-expr-common/src/aggregate/mod.rs
Closes #10391.
This PR is pulled from #10484 and it has a similar rationale in #10391 but the changes in this PR are for #10484
=> UDAF: Extend more args to `state_fields` and `groups_accumulator_supported` and introduce `ReversedUDAF`

datafusion/sql/src/unparser/expr.rs
=> Implement unparse `Placeholder` to String

datafusion/sql/src/unparser/expr.rs
Closes #10523 
IMO, `OuterReferenceColumn` is a column can be resolved to an outside field of the current plan. Typically, it's produced from `identifier` or `compound_identifier`.
https://github.com/apache/datafusion/blob/7535d93fa631f0fc42ca1521bc257ca20480b246/datafusion/sql/src/expr/identifier.rs#L64-L69
I think we can just convert it to a `column` sql node. Just like other identifier. Because the concept of `outer reference` is a logical plan concept, we can ignore the type of a `OuterReferenceColumn` which produced by a field resolving.
Convert `OuterReferenceColumn` to a Column SQL node.
Yes
No
=> Implement unparse `OuterReferenceColumn` to String

datafusion/optimizer/src/scalar_subquery_to_join.rs
Closes https://github.com/apache/datafusion/issues/10294
Make the optimizer faster by not copying
1. Stop copying LogicalPlan and Exprs in `ScalarSubqueryToJoin` when there are no ScalarSubqueries
2. Use the `OptimizerRule::rewrite` API
Existing CI
No (maybe minimal performance improvements)
=> Stop most copying LogicalPlan and Exprs in `ScalarSubqueryToJoin`

datafusion/functions-array/src/extract.rs, datafusion/sqllogictest/test_files/array.slt
Closes #10425.
Note:  Negative `from` or `to` implies counting from the end of the list and both are standardized to the corresponding positive index.
When `from` is greater than `to` and `stride` is a positive, the following loop becomes infinite, until the `index` becomes excessively large and panics.
https://github.com/apache/datafusion/blob/842f3933e3496a022984c2a37254475a3bcde1bf/datafusion/functions-array/src/extract.rs#L468-L478
The fix is to return an empty list directly in this situation.
Fix panic.
Yes
No
=> fix: `array_slice` panics

datafusion/sql/src/unparser/expr.rs
=> Implement unparse `ScalarVariable` to String

datafusion/core/src/datasource/file_format/parquet.rs, datafusion/core/src/datasource/physical_plan/mod.rs, datafusion/core/src/datasource/physical_plan/parquet/mod.rs, datafusion/core/src/datasource/physical_plan/parquet/schema_adapter.rs, datafusion/core/tests/parquet/mod.rs, datafusion/core/tests/parquet/schema_adapter.rs
Allow users of the Datafusion Parquet physical executor to define how to map parquet schema to the table schema.
This can be useful as there can be layers on top of parquet like Delta or Iceberg which may also define the schema and how the schema should evolve.
Closes #10398 
By exposing `SchemaAdapter` downstream consumers can reuse `ParquetExec` but allow for different interpretations of the data from the parquet.
For example, delta-rs keeps the schema separate from the parquet so that schema evolution can be well controlled.  The external schema can enrich the data inside the parquet files with missing nested columns or timezone information.
Changes `SchemaAdapter` to a public trait and adds `SchemaAdapterFactory` to be passed into the constructor of `ParquetExec`.
This change does …
=> feat: Expose Parquet Schema Adapter

datafusion/proto/proto/datafusion.proto, datafusion/proto/src/generated/pbjson.rs, datafusion/proto/src/generated/prost.rs, datafusion/proto/src/logical_plan/from_proto.rs, datafusion/proto/src/logical_plan/to_proto.rs, datafusion/proto/src/physical_plan/mod.rs, datafusion/proto/tests/cases/roundtrip_logical_plan.rs, datafusion/substrait/src/serializer.rs
Closes #10562 
1. Handle serde for `ScalarValue` which includes nested dictionary fields
2. Fix two places where we panic instead of returning an error during physical expr deserialization
Yes
Protobuf message for `ScalarNestedValue` is changed but in backward compatible way
=> Handle dictionary values in ScalarValue serde

datafusion/sql/src/unparser/expr.rs
=> Implement Unparse `GroupingSet` Expr --> String Support  sql

datafusion-examples/examples/plan_to_sql.rs
=> Add examples of how to convert logical plan to/from sql strings

datafusion/physical-plan/src/joins/sort_merge_join.rs, datafusion/sqllogictest/test_files/sort_merge_join.slt
Closes #10379  .
Fixing some existing SMJ LeftSemi bugs when join filter is set. Currently the join either crashes or giving wrong results
=> Fix: Sort Merge Join LeftSemi issues when JoinFilter is set

datafusion/functions-array/src/rewrite.rs
This confused me while debugging something else, so lets have the name that is logged match the struct name in the code
=> Minor: Fix `ArrayFunctionRewriter` name reporting

datafusion/expr/src/logical_plan/extension.rs, datafusion/expr/src/logical_plan/plan.rs, datafusion/expr/src/logical_plan/tree_node.rs, datafusion/substrait/src/logical_plan/consumer.rs, datafusion/substrait/tests/cases/roundtrip_logical_plan.rs
Closes https://github.com/apache/datafusion/issues/10571.
=> Improve `UserDefinedLogicalNode::from_template` API to return `Result`

datafusion/optimizer/src/optimizer.rs, datafusion/proto/proto/datafusion.proto
part of https://github.com/apache/datafusion/issues/9637.
=> Migrate testing optimizer rules to use `rewrite` API

datafusion/core/tests/parquet/arrow_statistics.rs, datafusion/core/tests/parquet/mod.rs
More tests for https://github.com/apache/datafusion/issues/10453
Add tests for parquet statistics reading
Tests and bug tickets linked to appropriate tests
Yes
No
=> test: add more tests for statistics reading

datafusion/optimizer/src/push_down_filter.rs
Not sure which issue to link here, but here's some changes to reduce allocations in `PushDownFilter`, and also clean the code up a bit.
=> refactor: reduce allocations in push down filter

datafusion-cli/src/main.rs
Closes #10552.
This PR fixes compilation of the datafusion-cli crate on 32bit targets. 
A constant assumed that a usize was at least 64 bits wide. I changed the constant type to be a u64, before translating it into a usize later on, throwing an error if it overflows.
These changes are not tested. I assumed adding CI for 32bit targets was too invasive for this PR.
There should be no user-facing changes or breaking changes.
=> Fix compilation of datafusion-cli on 32bit targets

docs/source/user-guide/sql/scalar_functions.md
Closes #10461 
Adding missing documentation
doc change only.
Yes,
Documentation updated.
=> Add to_date function to scalar functions doc

datafusion-examples/examples/advanced_udf.rs, datafusion-examples/examples/function_factory.rs, datafusion/expr/src/udf.rs, datafusion/functions/src/datetime/date_bin.rs, datafusion/functions/src/datetime/date_trunc.rs, datafusion/functions/src/macros.rs, datafusion/functions/src/math/abs.rs, datafusion/functions/src/math/log.rs, datafusion/functions/src/math/mod.rs, datafusion/functions/src/math/monotonicity.rs, datafusion/functions/src/math/pi.rs, datafusion/functions/src/math/round.rs, datafusion/functions/src/math/trunc.rs, datafusion/physical-expr/src/scalar_function.rs, datafusion/physical-expr/src/utils/mod.rs, datafusion/physical-plan/src/joins/stream_join_utils.rs
Closes #.
The signature and usage of the monotonicity API have significantly changed. Therefore, we believe that `output_ordering()` better reflects the new approach. https://github.com/apache/datafusion/pull/10504#discussion_r1608069310
This PR just renames the `monotonicity()` methods as `output_ordering()` in both `ScalarUDF` and `ScalarUDFImpl`.
=> Rename monotonicity as output_ordering in ScalarUDF's

datafusion/sql/src/unparser/ast.rs, datafusion/sql/src/unparser/plan.rs, datafusion/sql/tests/sql_integration.rs
It doesn't close this issue, but is part of the work for #9494
Adds support for turning LogicalPlans that have `Union` LogicalPlans (without distinct, so only `UNION ALL`, not `UNION`) into SQL strings.
It should be relatively easy now to support bare `UNION` by first inspecting the `Distinct` node - but I ran out of time on this PR.
Splits `select_to_sql` into two parts: `select_to_sql_statement` and `select_to_sql_expr`. LIMIT and ORDER BY are only valid in a statement context, whereas all other plans can appear in a SELECT expression. This allows the parsing for UNION ALL to turn each of its inputs into a SELECT expression, and still respect the LIMIT/ORDER BY at the statement level.
Yes, added two tests to the `roundtrip_sql` integration test.
This expands the valid plans that can be …
=> Implement Unparser for `UNION ALL`

datafusion/core/src/physical_planner.rs, datafusion/core/tests/user_defined/user_defined_plan.rs, datafusion/expr/src/logical_plan/extension.rs, datafusion/optimizer/src/analyzer/subquery.rs, datafusion/optimizer/src/optimize_projections/mod.rs, datafusion/optimizer/src/push_down_filter.rs, datafusion/optimizer/src/test/user_defined.rs, datafusion/proto/tests/cases/roundtrip_logical_plan.rs
follow up of https://github.com/apache/datafusion/pull/10575.
=> Improve `UserDefinedLogicalNodeCore::from_template` API to return Result

datafusion/optimizer/src/eliminate_group_by_constant.rs, datafusion/optimizer/src/lib.rs, datafusion/optimizer/src/optimizer.rs, datafusion/sqllogictest/test_files/explain.slt, datafusion/sqllogictest/test_files/optimizer_group_by_constant.slt, datafusion/sqllogictest/test_files/order.slt, datafusion/sqllogictest/test_files/subquery.slt
Closes #.
Initial intention was to improve clickbench q34 -- it contains aggregation by constant and URL which makes aggregation switch to row-based mode which is slower that single field group by.
In general, elimination of constants from `GROUP BY` seems to be reasonable optimization.
New logical optimizer rule which removes constant or originated from constant expressions from `Aggregate::group_expr`, and places additional projection on top of aggregation, to satisfy original schema for downstream operators.
Optimizer rule is placed between last `SimplifyExpressions` and `OptimizeProjections`, since it requires constant evaluation, and projections, produced by this rule, may be merged.
New unit tests and sqllogictests
No
=> feat: Add eliminate group by constant optimizer rule

datafusion/physical-expr/src/window/lead_lag.rs
Closes #.
While working on another PR, I have recognized that get_range implementation for `LEAD`, `LAG` window functions generates unnecessarily wide ranges when `ignore_nulls` flag is `false`. This PR, fixes this problem. This enables `BoundedWindowAggExec` to prune its input data better for `LEAD, LAG` window functions.
Yes, unit test is added
=> [MINOR]: Update get range implementation for lead lag window functions

datafusion-examples/examples/plan_to_sql.rs
Follow on to https://github.com/apache/datafusion/pull/10558 from @xinlifoobar (🙏 ) and @edmondop 
I noticed a few potential improvements to the sql_to_plan examples
1. Improve the documentation and function names to make the examples better in my opinion
Existing CI
=> Minor: Improve documentation in sql_to_plan example

datafusion/execution/src/object_store.rs, datafusion/execution/src/runtime_env.rs
Closes #10616. Documentation only
=> Docs: add examples for `RuntimeEnv::register_object_store`, improve error messages

datafusion/substrait/src/logical_plan/consumer.rs, datafusion/substrait/src/logical_plan/producer.rs, datafusion/substrait/tests/cases/roundtrip_logical_plan.rs
Closes #.
Extracted part of #10531 - not necessary part for it but somewhat related
Adds support for converting from DataFusion List/LargeList ScalarValues into Substrait List/EmptyList Literals and back
Adds a round-trip unit test
More things are now supported, but I don't think Substrait support status is covered by documentation currently?
=> Add support for Substrait List/EmptyList literals

Cargo.toml, datafusion-cli/Cargo.lock, datafusion-examples/examples/plan_to_sql.rs, datafusion/core/Cargo.toml, datafusion/functions/Cargo.toml, datafusion/physical-expr/Cargo.toml, datafusion/sql/Cargo.toml, datafusion/sql/src/unparser/dialect.rs, datafusion/sql/src/unparser/expr.rs, datafusion/sql/src/unparser/plan.rs, datafusion/sql/tests/sql_integration.rs
Closes #10557 
Only implement the default dialect in this PR. We need other follow-up PR for other dialects.
Yes
No
=> Implement a dialect-specific rule for unparsing an identifier with or without quotes

datafusion/sql/src/unparser/plan.rs
TableReference has the catalog information but it's not used in `plan_to_sql`
Part of https://github.com/apache/datafusion/issues/9494
It's common for DBMS to have pattern of `[catalog.][schema.]table_name` in SQL statement. E.g. snowflake.
- Add catalog information if it exists in table reference.
Yes
No
=> add catalog as part of the table path in plan_to_sql

datafusion/core/src/datasource/listing/mod.rs, datafusion/core/src/datasource/physical_plan/parquet/mod.rs, datafusion/core/src/datasource/physical_plan/parquet/page_filter.rs, datafusion/core/src/datasource/physical_plan/parquet/row_groups.rs
Part of https://github.com/apache/datafusion/issues/10453 and https://github.com/apache/datafusion/issues/9929
This PR prepares switching the parquet reader to use the new statistics extraction API added in https://github.com/apache/datafusion/pull/10537.
To avoid a massive, I broke it into its own PR for easier review. This PR refactors the code around, but doesn't change any behavior. The next PR will change the pruning API to use the new statistics extraction API.
I also think this change makes the code easier to understand and maintain as it uses a documented struct to represent the set of `RowGroup`s to scan rather than a `Vec<usize>`.
1. Add `RowGroupSet` to encapsulate the set of row groups which is being pruned
2. Move pruning code into `RowGroupSet` methods
2. Update code + tests …
=> Refactor parquet row group pruning into a struct (use new statistics API, part 1)

datafusion-cli/src/exec.rs, datafusion-examples/examples/external_dependency/dataframe-to-s3.rs, datafusion-examples/examples/external_dependency/query-aws-s3.rs, datafusion-examples/examples/parquet_sql_multiple_files.rs, datafusion-examples/examples/query-http-csv.rs, datafusion/core/src/datasource/physical_plan/avro.rs, datafusion/core/src/datasource/physical_plan/csv.rs, datafusion/core/src/datasource/physical_plan/json.rs, datafusion/core/src/datasource/physical_plan/parquet/mod.rs, datafusion/core/src/execution/context/mod.rs, datafusion/core/src/test/object_store.rs, datafusion/core/tests/dataframe/mod.rs, datafusion/core/tests/path_partition.rs
Part of https://github.com/apache/datafusion/issues/10616
Inspired by @aditanase in https://github.com/apache/datafusion/pull/10617 and my own experience in https://github.com/apache/datafusion/pull/10549 I wanted to make it easier to find / discover how to register new object stores
1. Add `SessionContext::register_object_store`
2. Add docs
=> Add SessionContext::register_object_store

datafusion/substrait/src/logical_plan/consumer.rs, datafusion/substrait/src/logical_plan/producer.rs, datafusion/substrait/tests/cases/roundtrip_logical_plan.rs
Closes #.
Extracted part of https://github.com/apache/datafusion/pull/10531 - not necessary part for it but somewhat related
Adds support for converting from un-named DataFusion Struct ScalarValues into Substrait Struct Literals and back, as well as converting from Substrait Struct type into DF Struct type (other direction already existed).
Substrait doesn't contain names in its Struct fields. For e.g. initial schema, the names are provided separately. This PR only properly supports un-named structs - which in DataFusion get default field names of form "c0", "c1", ... Other structs can also be converted but they'll be renamed automatically into the default names.
The VirtualTable PR will then provide better support for named structs.
Adds round-trip unit tests
More things are now …
=> Add support for Substrait Struct literals and type

datafusion-cli/Dockerfile
Closes #10472
The current Dockerfile is based on a pretty old ubuntu release which doesn't build when run on a newer ubuntu release. I can see no good reason why the cli should be built using old ubuntu and rust versions.
Dockerfile update.
Built and tested locally on wsl2/ubuntyu 22.04.4
No
=> Update cli Dockerfile to a newer ubuntu release, newer rust release

datafusion/substrait/src/logical_plan/consumer.rs, datafusion/substrait/src/logical_plan/producer.rs
Extracted from #10531
Builds on top of #10622 so I'll rebase this once it's merged.
More closely propagate null-ability through Substrait conversions
Handles the nullability of struct fields during Substrait conversions. This isn't perfect; some things are still assumed to just always be nullable (e.g. Literal list elements).
Tested through round-trip unit tests
Nulls are handled more accurately
=> More properly handle nullability of types/literals in Substrait

datafusion/sql/src/utils.rs, datafusion/sqllogictest/test_files/unnest.slt
=> fix wrong type validation on unnest expr

datafusion/core/src/datasource/physical_plan/parquet/statistics.rs, datafusion/core/tests/parquet/arrow_statistics.rs
=> Fix incorrect statistics read for binary columns in parquet

datafusion/core/tests/expr_api/mod.rs, datafusion/functions/src/core/getfield.rs
Closes https://github.com/apache/datafusion/issues/10654
This used to work (and we used it in IOx when we were programatically creating expressions):
```rust
lit(ScalarValue::Null).field("foo")
```
Now it returns an error:
> The expression to get an indexed field is only valid for List, Struct, or Map types, got Null
Support `NULL["field"`
Yes, new unit tests are added
Fix regression
=> Fix `NULL["field"]` for expr_API

datafusion/functions/Cargo.toml
Closes #.
When running `cargo build` locally I see
```
warning: /Users/andrewlamb/Software/datafusion/datafusion/functions/Cargo.toml: dependency (regex) specified without providing a local path, Git repository, version, or workspace dependency to use. This will be considered an error in future versions
warning: /Users/andrewlamb/Software/datafusion/datafusion/functions/Cargo.toml: unused manifest key: dependencies.regex.worksapce
```
I think this is due to a typo introduced in #10573
Fix typo
=> Fix typo in Cargo.toml (unused manifest key: dependencies.regex.worksapce)

datafusion/common/src/tree_node.rs, datafusion/physical-expr-common/src/tree_node.rs, datafusion/physical-plan/src/tree_node.rs
The idea of using slices to return a node's children came up here: https://github.com/apache/datafusion/pull/10543#discussion_r1614057653.
While it is not possible in all `TreeNode` implementations, the 2 `ConcreteTreeNode` implementations (`ExprContext` and `PlanContext`) own their children in `Vec` form, so there is a way to return a slice like `&[Self]` (instead of the current `Vec<&Self>`).
=> Minor: Use slice in `ConcreteTreeNode`

datafusion/expr/src/type_coercion/functions.rs
N/A
There was a logical conflict between https://github.com/apache/datafusion/pull/10644 and https://github.com/apache/datafusion/pull/10268
Fix conflict and compile
CI
=> Fix compilation "comparison_binary_numeric_coercion not found"

datafusion/common/src/scalar/mod.rs
N/A
`ScalarValue::try_from(dt: &DataType)`  is commonly used to create a NULL `ScalarValue` for a given DataType.
The processing of List DataTypes is a bit complex and can be simplified.
Yes
No
=> refactor: simplify converting List DataTypes to `ScalarValue`

datafusion/substrait/src/logical_plan/producer.rs
Closes #10682.
A merge conflict exists between #10640 and #10646.
Fix compilation
Yes
No
=> fix: CI compilation failed on substrait

datafusion/core/src/datasource/physical_plan/parquet/statistics.rs, datafusion/core/tests/parquet/arrow_statistics.rs, datafusion/core/tests/parquet/mod.rs
Part of https://github.com/apache/datafusion/issues/10453
As we fill out parquet statistics features, it would be good to ensure they work well with numeric limits (aka the ranges of values of different types)
Add new tests for numeric limits
Only tests
No
=> Add tests for reading numeric limits in parquet statistics

datafusion/sql/src/select.rs, datafusion/sql/src/utils.rs, datafusion/sql/tests/sql_integration.rs, datafusion/sqllogictest/test_files/group_by.slt
Closes #.
While #10591 found that planning for INT literals in GROUP BY clause is inconsistent. For example:
```sql
EXPLAIN SELECT "URL", COUNT(1) from hits GROUP BY 1, 3, 4, 5
```
produces following logical plan (this is logical plan before any optimizations):
```sql
Explain
Projection: hits.URL, COUNT(Int64(1))
Aggregate: groupBy=[[hits.URL, Int64(3), Int64(4), Int64(5)]], aggr=[[COUNT(Int64(1))]]
TableScan: hits
```
`1` resolved as column from select clause, and `3, 4, 5` remain as constants. Don't think this behavior is intended + there are couple of tests in `sql_integration.rs` (modified below), for similar cases, expect queries to fail.
The suggestion is to fail while planning phase for such cases, and return error, specifying first index which can not be resolved as select column. …
=> minor: inconsistent group by position planning

datafusion/proto/proto/datafusion.proto, datafusion/proto/src/generated/pbjson.rs, datafusion/proto/src/generated/prost.rs, datafusion/proto/src/physical_plan/mod.rs, datafusion/proto/tests/cases/roundtrip_physical_plan.rs
Closes #10630
1. add new struct  message `AggLimit` 
2. add UT in the ser/deser test for this case
=> support serialization and deserialization limit in the aggregation exec 

datafusion/physical-plan/src/unnest.rs, datafusion/sqllogictest/test_files/unnest.slt
=> Fix: array list values are leaked on nested `unnest` operators

datafusion/functions-aggregate/src/first_last.rs, datafusion/functions-aggregate/src/lib.rs, datafusion/functions-aggregate/src/median.rs, datafusion/functions-array/src/lib.rs, datafusion/functions/src/lib.rs, datafusion/optimizer/src/replace_distinct_aggregate.rs, datafusion/sqllogictest/test_files/aggregate.slt, datafusion/sqllogictest/test_files/distinct_on.slt, datafusion/sqllogictest/test_files/group_by.slt, datafusion/sqllogictest/test_files/joins.slt
Closes #10695 .
Fix `median`, `first_value` and `last_value`
Yes
No
=> Remove redundant upper case aliases for `median`, `first_value` and `last_value`

datafusion/core/src/datasource/physical_plan/parquet/statistics.rs, datafusion/core/tests/parquet/arrow_statistics.rs
=> Fix incorrect statistics read for unsigned integers columns in parquet

datafusion/substrait/Cargo.toml, datafusion/substrait/src/logical_plan/consumer.rs, datafusion/substrait/src/logical_plan/producer.rs, datafusion/substrait/tests/cases/logical_plans.rs, datafusion/substrait/tests/cases/mod.rs, datafusion/substrait/tests/testdata/select_not_bool.substrait.json
Substrait 0.32.0+ requires functions to be specified using compound names, which include the function name as well as the arguments it takes. We don't necessarily need that information while consuming the plans, but we need to support those compound names.
Closes #10412, but doesn't fix the part where DataFusion _generates_ those outdated simple names. But that's a bit bigger fix - this small thing would be enough to unblock me if it'd be okay to merge this before fixing the producer side. 
See issue.
When consuming Substrait, checks if given function names are compound names, if so strips the arguments part.
Tested manually, but will still need to add unit tests.
=> Support consuming Substrait with compound signature function names

datafusion/expr/src/expr.rs
Part of #10121 and #7013 
As @berkaysynnada says on @peter-toth 's amazing PR ' https://github.com/apache/datafusion/pull/10543
> Our TreeNode API functionality has reached a very good level. You've done a great job. Perhaps we could add documentation with code snippets to exemplify the usage of methods and their purposes, to ease the experience for less experienced users.
This PR adds examples to `Expr` and documentation to show how to use the TreeNode API
Yes, new doc examples
=> Minor: Add examples of using TreeNode with `Expr`

datafusion-examples/examples/simplify_udwf_expression.rs, datafusion/proto-common/src/to_proto/mod.rs
=> Chore: clean up udwf example && remove redundant import

datafusion/core/src/datasource/listing/helpers.rs
When applicable, table partition listing can be optimized by deriving a listing prefix based on literals provided in the filter predicates.
For a selected table with many partitions, this change reduces query time from minutes to 200ms.
* ~~stacked on top of https://github.com/apache/datafusion/pull/10691. please review that PR first.~~
* added a `evaluate_partition_prefix` function to derive a listing prefix based on filter predicates and table partitions.
* `list_partitions` extended to take an optional prefix argument.
Tested with unit tests.
No
=> Push down filter as table partition list prefix

datafusion/core/src/physical_optimizer/join_selection.rs
=> Make swap_hash_join public API

datafusion/core/src/datasource/listing/helpers.rs
=> CI: Fix complaints from newer Clippy versions

datafusion/core/tests/expr_api/mod.rs, datafusion/functions/src/string/mod.rs
Closes #10676.
- fix a minor issue about consistency
- fn signature should be the same as `fn bit_length()`
- changed `octet_length` to accept `Expr` instead of `Vec<Expr>`
Yes. Existing tests.
No.
=> Minor: fix signature `fn octect_length()`

datafusion/proto-common/src/to_proto/mod.rs, datafusion/substrait/src/logical_plan/consumer.rs, datafusion/substrait/src/logical_plan/producer.rs, datafusion/substrait/src/variation_const.rs
Closes #.
Follow-up of https://github.com/apache/datafusion/pull/10646#discussion_r1616129968. Document those type variation consts and link to the corresponding substrait website.
This patch also renames `*_TYPE_REF` to `_TYPE_VAR_REF` to distinguish "type reference" for user-defined type and "type variation reference" for type variation.
=> docs: add documents to substrait type variation consts

datafusion-cli/src/exec.rs
Closes #10737.
When setting format options for `TableOptions`,
https://github.com/apache/datafusion/blob/09dde27be39ad054f85dfb5c37b7468a3f68d652/datafusion-cli/src/exec.rs#L376
the `current_format` of `TableOptions` must already exist, which means [set_file_format](https://github.com/apache/datafusion/blob/09dde27be39ad054f85dfb5c37b7468a3f68d652/datafusion-cli/src/exec.rs#L374) must be called with a non-none file type first.
https://github.com/apache/datafusion/blob/09dde27be39ad054f85dfb5c37b7468a3f68d652/datafusion/common/src/config.rs#L1185-L1187
Yes
No
=> fix(CLI): can not create external tables with format options

datafusion/physical-expr-common/src/aggregate/mod.rs, datafusion/physical-expr/src/aggregate/count.rs, datafusion/physical-expr/src/lib.rs, datafusion/physical-expr/src/window/sliding_aggregate.rs, datafusion/physical-expr/src/window/window_expr.rs, datafusion/physical-plan/src/aggregates/mod.rs
Closes #.
While working on another PR, in which I implement a new custom rule. I hit a usecase where I want to re-write `AggregateExpr`, and `WindowExpr` according to some kind of projection. (For instance , in terms of the schema of the child). In my use case, I find it useful to define an API `fn all_expressions(&self) -> (function args, order bys, ..)` to return all expressions referred by the aggregate or window function (By the way current `fn expressions(&self)` API only returns function arguments).
With this API in place, we can update `Arc<dyn PhysicalExpr>`s, at the outside (such as inside the rule). Then we can use updated expressions to re-write `Arc<dyn AggregateExpr>` by using following API:
```rust
fn with_new_expressions(
&self,
_args: Vec<Arc<dyn PhysicalExpr>>, …
```
=> Add support for `AggregateExpr`, `WindowExpr` rewrite.

datafusion/physical-plan/src/joins/sort_merge_join.rs, datafusion/sqllogictest/test_files/sort_merge_join.slt
Closes #10380.
Fix issues when LeftAnti Join returned nothing when the join filter was set
Handled scenarios for LeftAntiJoin when join filter is set. Output the streaming row(left join side row) only if there is no corresponding filtered match from buffered data(right join side)
=> Fix SMJ Left Anti Join when the join filter is set

benchmarks/bench.sh, datafusion/physical-plan/src/joins/sort_merge_join.rs
Closes #10100 .
Basically fix for #10380 fixed the issue, I just fixing also the usage info for SMJ
=> Minor: Add SMJ to TPCH benchmark usage

datafusion/core/src/datasource/physical_plan/parquet/mod.rs, datafusion/core/src/datasource/physical_plan/parquet/opener.rs, datafusion/core/src/datasource/physical_plan/parquet/reader.rs, datafusion/core/src/datasource/physical_plan/parquet/row_groups.rs, datafusion/core/src/datasource/physical_plan/parquet/writer.rs
Part of https://github.com/apache/datafusion/issues/9929
While working on #9929 I am finding the code in the mod.rs file to be a bit hard to follow. I think it would be easier to understand if it was broken up into smaller files
1. Split `physical_plan/parquet/mod.rs` into smaller modules
Existing CI
No, all structs are re-exported as ndded
=> Minor: Split physical_plan/parquet/mod.rs into smaller modules

datafusion/functions/src/string/repeat.rs, datafusion/sqllogictest/test_files/expr.slt
Closes #10759
Repeat should not panic and should match the behavior of other common engines.
Updates the main `repeat` function's logic to only try to cast the i64 to a usize when the count is greater than or equal to 0, otherwise returns an empty string.
Added a sqllogictest.
=> fix: fix string repeat for negative numbers

datafusion/core/tests/parquet/arrow_statistics.rs, datafusion/core/tests/parquet/mod.rs
Part of #10453 
I noticed while reviewing https://github.com/apache/datafusion/pull/10711 we don't have any tests for extracting statistics from DictionaryArrays
Add tests to extract statistics from dictionary arrays
They are all tests
=> Minor: Add tests for extracting dictionary parquet statistics

datafusion/common/src/utils/memory.rs, datafusion/common/src/utils/mod.rs, datafusion/physical-expr/src/aggregate/count_distinct/native.rs, datafusion/physical-plan/src/joins/hash_join.rs
Closes #8764.
As stated in the issue [here](https://github.com/apache/datafusion/issues/8764#issuecomment-2141501909) the goal is to consolidate estimation logic into a single function. This allows for better documentation as well as better maintainability.
Also there was an [issue ](https://github.com/apache/datafusion/issues/8764#issuecomment-2143467627)with the existing implementation that could still overflow if the `checked_mul` was capped at usize::MAX. I tried to fix this by checking for overflows and returning usize::MAX as a 'max cap'.
- extract logic into single function
- fixed missing overflow checks
- moved logic into datfusion common
- used the new function in `count_distinct/native.rs` and `hash_join.rs`
Yes.
No.
=> Minor: Refactor memory size estimation for HashTable

docs/source/user-guide/example-usage.md
Closes #.
- The sample code in `docs/source/user-guide/example-usage.md` is not working with `tokio = "1.0"` dependency. The error I got is
```shell
error: The default runtime flavor is `multi_thread`, but the `rt-multi-thread` feature is disabled.
--> src/main.rs:3:1
|
3 | #[tokio::main]
| ^^^^^^^^^^^^^^
|
= note: this error originates in the attribute macro `tokio::main` (in Nightly builds, run with -Z macro-backtrace for more info)
```
- Enabled `rt-multi-thread` feature in `tokio`.
Yes. I got the expected output
```shell
+---+----------------+
| a | MIN(example.b) |
+---+----------------+
| 1 | 2              |
+---+----------------+
```
Nope
=> Minor: (Doc) Enable rt-multi-thread feature for sample code

datafusion/sql/src/unparser/expr.rs, datafusion/sql/src/unparser/plan.rs, datafusion/sql/src/unparser/utils.rs, datafusion/sql/tests/cases/plan_to_sql.rs
closes #10664 
Queries involving window functions are common and should be supported for unparsing a plan into SQL.
- Implements logic for unprojecting window function projections, similar to existing logic for aggregate functions
- No longer throw unimplemented error on LogicalPlan::Window nodes
- Fixes a subtle error in unparsing Window expressions
Yes, with a new round trip plan_to_sql test
Additional queries can be unparsed
=> feat: support unparsing LogicalPlan::Window nodes

datafusion/functions-aggregate/src/first_last.rs, datafusion/sqllogictest/test_files/window.slt
Closes #10781 
Fix coercion bug in `last_value()`
Support type signature for numeric string
Yes, tests are added
Yes, users will no longer get an error when query with `last_value()`
=> chore: fix `last_value` coercion

datafusion/sql/src/unparser/plan.rs, datafusion/sql/src/unparser/utils.rs
none
I noticed while working on #10767 some unparser methods have grown unwieldy and difficult to understand. This PR attempts to break some of the more confusing methods up with the aim of making them more easily readable. 
- Break up handling of `LogicalPlan::Projection` nodes in `select_to_sql_recursively` into multiple helpers
- Rewrite `find_agg_node_within_select` to use a `match` statement rather than several `if let`s
Yes, by existing tests (no new features or bug fixes in this PR)
No, purely reorganizing code.
=> minor: Refactor some unparser methods to improve readability

datafusion/functions-array/src/extract.rs, datafusion/functions-array/src/utils.rs, datafusion/sqllogictest/test_files/array.slt
Closes #10791.
When the `args` are empty, they panic at [display_name](https://github.com/apache/datafusion/blob/ece7ae5eca451bb2599f13f9f9197fd93b2a8bc2/datafusion/functions-array/src/extract.rs#L255),  due to "index out of bounds".
https://github.com/apache/datafusion/blob/ece7ae5eca451bb2599f13f9f9197fd93b2a8bc2/datafusion/functions-array/src/extract.rs#L253-L256
The fix is to use an empty string as the arg name if it is out of bounds,  allow `display_name` to pass through, and subsequently generating an error by checking the signature.
Yes
No
=> fix: `array_slice` and `array_element` panicked on empty args

datafusion/physical-plan/src/joins/sort_merge_join.rs, datafusion/sqllogictest/test_files/sort_merge_join.slt
A followup on https://github.com/apache/datafusion/pull/10724#discussion_r1623243082
Related to https://github.com/apache/datafusion/issues/9846
Addressing comments from PR review, improving the comments and adding more test cases
Yes
No
=> SMJ: Add more tests and improve comments

datafusion/sql/src/unparser/ast.rs, datafusion/sql/src/unparser/plan.rs, datafusion/sql/tests/cases/plan_to_sql.rs
=> Handle EmptyRelation during SQL unparsing

benchmarks/README.md, benchmarks/bench.sh, datafusion/physical-plan/src/joins/sort_merge_join.rs
Closes #.
Followup on #10747  
Related #9846 
By default benches run with hash join algorithm, this PR introduces new env variable `PREFER_HASH_JOIN` to give the user a switch for running benchmarks with SMJ as well.
Removed old SMJ benches code, added env variable and fixed the doc
Yes manually
No
=> Bench: Add `PREFER_HASH_JOIN` env variable

datafusion/expr/src/udf.rs, datafusion/physical-expr-common/src/physical_expr.rs
Closes #.
I'm reading somd udf code, and found the example in `ScalarUDFImpl::propagate_constraints` doc is confused. I checked `PhysicalExpr::propagate_constraints` doc example
```
/// If the expression is `a + b`, the current `interval` is `[4, 5]` and the
/// inputs `a` and `b` are respectively given as `[0, 2]` and `[-∞, 4]`, then
/// propagation would would return `[0, 2]` and `[2, 4]` as `b` must be at
/// least `2` to make the output at least `4`.
```
If I understand correctly, the updated bounds of child expressions should be subinterval of their original intervals.
=> Fix `ScalarUDFImpl::propagate_constraints` doc

datafusion/core/src/datasource/physical_plan/parquet/statistics.rs, datafusion/core/tests/parquet/arrow_statistics.rs, datafusion/core/tests/parquet/mod.rs
Closes #10752.
Since parquet does not support statistics for `Interval` columns, this PR only prepares test cases and some necessary setup.
Once parquet supports statistics, a follow-up PR will be needed to finish the implementation. 
- added test cases for interval columns
- added `get_statistic` match arm (stub)
- added comments to highlight the not yet supported parts
- for now the test_cases `should_panic`
No.
=> Extract Parquet statistics from `Interval` column

datafusion/sql/src/unparser/ast.rs, datafusion/sql/src/unparser/plan.rs
No specific issue but mentioned in https://github.com/apache/datafusion/pull/10803#issuecomment-2150586926
It's a follow-up PR of #10803
No, just simplify the code.
No
=> Refactor and simplify the SQL unparser

datafusion-cli/Cargo.lock, datafusion/expr/src/expr_fn.rs, datafusion/expr/src/logical_plan/builder.rs, datafusion/optimizer/Cargo.toml, datafusion/optimizer/src/analyzer/count_wildcard_rule.rs, datafusion/optimizer/src/common_subexpr_eliminate.rs, datafusion/optimizer/src/eliminate_filter.rs, datafusion/optimizer/src/eliminate_limit.rs, datafusion/optimizer/src/push_down_filter.rs, datafusion/optimizer/src/scalar_subquery_to_join.rs, datafusion/optimizer/src/single_distinct_to_groupby.rs, datafusion/optimizer/src/test/function_stub.rs, datafusion/optimizer/src/test/mod.rs, datafusion/proto/tests/cases/roundtrip_logical_plan.rs, datafusion/sqllogictest/test_files/aggregate.slt
Part of https://github.com/apache/datafusion/issues/10731
Inspired from https://github.com/apache/datafusion/pull/10807#discussion_r1630226174
Close #10807
The reason to add a stub is that as we pull the aggregate functions out of the core and into `datafusion-functions-aggregate` the existing optimizer passes don't depend on datafusion-functions-aggregate. 
Thus by using stubs we'll keep the optimizer passes decoupled from the built in aggregate functions as much as possible.
=> Remove expr_fn::sum and replace them with function stub

dev/changelog/39.0.0.md, dev/release/README.md, dev/release/generate-changelog.py
N/A
- Improve the quality of generated changelogs
- Reduce manual effort required when generating changelogs
- Improved `generate-changelog.py` script:
- Includes summary of # of commits and contributors, and credits at the end
- Add new category `other` for all PRs that are not in a specific category
- Removed the list of all PRs merged since it mostly duplicated the categorized entries
- Generates ASF header so no need to add that manually now
- I regenerated the 39.0.0 changelog as an example ([rendered version](https://github.com/andygrove/datafusion/blob/improve-changelog-generator/dev/changelog/39.0.0.md))
- Updated documentation
No
=> chore: Improve change log generator

datafusion/proto-common/Cargo.toml
Resolve https://github.com/apache/datafusion/pull/10765#issuecomment-2156823540
Some deps in `proto-common` are not inherited from the workspace, bringing inconsistency after bump dependencies.
Refactor `proto-common`'s Cargo deps to inherit common deps from workspace.
=> MINOR: use workspace deps in proto-common (upgrade object store dependency)

datafusion/functions/src/datetime/date_part.rs, datafusion/sqllogictest/test_files/expr.slt
=> fix: Support double quotes in `date_part`

datafusion/expr/src/logical_plan/plan.rs
Closes N/A
This change makes the `Window` node API more uniform with other `LogicalPlan` nodes, which all expose both `try_new` and `try_new_with_schema` constructors.
New method `Window::try_new_with_schema`
No.
=> Minor: add `Window::try_new_with_schema` constructor

datafusion-examples/examples/csv_opener.rs, datafusion/common/src/config.rs, datafusion/core/src/datasource/file_format/csv.rs, datafusion/core/src/datasource/file_format/options.rs, datafusion/core/src/datasource/physical_plan/csv.rs, datafusion/core/src/physical_optimizer/enforce_distribution.rs, datafusion/core/src/physical_optimizer/projection_pushdown.rs, datafusion/core/src/physical_optimizer/replace_with_order_preserving_variants.rs, datafusion/core/src/test/mod.rs, datafusion/proto-common/proto/datafusion_common.proto, datafusion/proto-common/src/from_proto/mod.rs, datafusion/proto-common/src/generated/pbjson.rs, datafusion/proto-common/src/generated/prost.rs, datafusion/proto-common/src/to_proto/mod.rs, datafusion/proto/proto/datafusion.proto, datafusion/proto/src/generated/datafusion_proto_common.rs, datafusion/proto/src/generated/pbjson.rs, datafusion/proto/src/generated/prost.rs, datafusion/proto/src/physical_plan/mod.rs, datafusion/sqllogictest/test_files/csv_files.slt
This PR adds support for parsing CSV files containing comment lines.
Closes #10262.
=> Add support for reading CSV files with comments

datafusion/core/src/lib.rs
related to #8373 
The official citation has been published: https://dl.acm.org/doi/10.1145/3626246.3653368 so let's link there
1. Update paper link
2. add a "how to cite" section
CI
Only doc comments
=> Minor: Update SIGMOD paper reference url

datafusion/common/src/dfschema.rs, datafusion/physical-expr/src/expressions/in_list.rs
Follow-up on #10031
As discussed in https://github.com/apache/datafusion/pull/10031#discussion_r1561945088, a followup PR to make
the function `datatype_is_logically_equal` in DFSchema public and reuses in the in_list code.
1. make `datatype_is_logically_equal` public in DFSchema
2. remove duplicate code in `in_list`
No
=> chore: Make DFSchema::datatype_is_logically_equal function public

datafusion/substrait/src/logical_plan/consumer.rs, datafusion/substrait/src/logical_plan/producer.rs, datafusion/substrait/tests/cases/consumer_integration.rs, datafusion/substrait/tests/cases/logical_plans.rs, datafusion/substrait/tests/cases/roundtrip_logical_plan.rs
Closes #10817
- fix Substrait producer to include also nested names in the root plan `names` list
- add support into Substrait consumer to use that list to enforce column and inner struct field names
Tested by a new test specifically for testing Alias (" AS "), as well as tightening existing tests.
Plans produced by DataFusion before this change are not compatible with plans produced after this change, if the plan contains inner struct fields, since the length of the "names" field does not match. The previous behavior was wrong, but still it's a breaking change.  If that's considered important, it is possible to add an extra handling for those cases, but I'd prefer not to unless necessary.
Also some output column names might change if people are depending on the old behavior that did not …
=> Support correct output column names and struct field names when consuming/producing Substrait

datafusion/core/src/datasource/listing/table.rs
Follow on to https://github.com/apache/datafusion/pull/10693
@houqp  added a great feaure in https://github.com/apache/datafusion/pull/10693 that I wanted to make sure was documented
Also, as I am working on #10481 I found I had to explain what LIstingTable was so already had a good example
Improve docstrings and example of `ListingTable`
Doc CI check
Documentation, no functional changes
=> Minor: Improve `ListingTable` documentation

datafusion/physical-expr/src/expressions/case.rs
=> replace and(*, not(*)) with and_not(*)

datafusion/core/tests/fuzz_cases/join_fuzz.rs
Temporary addresses build failed on main due to #10886
=> Disabling test for semi join with filters

datafusion/core/src/datasource/physical_plan/parquet/statistics.rs
Part of https://github.com/apache/datafusion/issues/10453
Inspired by https://github.com/apache/datafusion/pull/10852
The new `StatisticsConverter` API is ready, so we can remove the old `min_statistics` and `max_statistics` from "crate" level APIs 
1. Make  the old `min_statistics` and `max_statistics` APIs module private
1. Update module docs
=> Minor: Update `min_statistics` and `max_statistics`  to be helpers, update docs

datafusion/core/tests/parquet/arrow_statistics.rs, datafusion/core/tests/parquet/mod.rs
None.
Since `Interval` has no defined sort order and writing statistics is not planned upstream in arrow-rs. We remove the already setup test infra. See [comment](https://github.com/apache/datafusion/pull/10801#issuecomment-2163269930) for reference.
remove test and setup code (make_interval_batch)
=> Remove `Interval` column test // parquet extraction

datafusion/common/src/utils/mod.rs, datafusion/substrait/src/logical_plan/consumer.rs, datafusion/substrait/src/logical_plan/producer.rs, datafusion/substrait/tests/cases/logical_plans.rs, datafusion/substrait/tests/testdata/non_nullable_lists.substrait.json
DataFusion (or really Arrow) is quite strict about nullability, specifically, when using e.g. `LogicalPlan::Values`, the given schema must match the given literals exactly - including nullability.
This is non-trivial to do when converting schema and literals separately like we do.
The existing implementation for from_substrait_literal already creates lists that are always nullable
(see ScalarValue::new_list => array_into_list_array). This reverts part of https://github.com/apache/datafusion/pull/10640 to align from_substrait_type with that behavior.
This is the error I was hitting:
```
ArrowError(InvalidArgumentError("column types must match schema types, expected
List(Field { name: \"item\", data_type: Int32, nullable: false, dict_id: 0, dict_is_ordered: false, metadata: {} }) but found …
```
=> fix: Ignore nullability of list elements when consuming Substrait

datafusion/core/tests/fuzz_cases/join_fuzz.rs, datafusion/physical-plan/src/joins/sort_merge_join.rs
Closes #10886.
The fuzz tests for filtered SMJ introduced in https://github.com/apache/datafusion/pull/10728 has a flaw when calculating the rowcounts, it fact it caculcated batches which are not always the same and led to false negatives.
=> Minor: SMJ fuzz tests fix for rowcounts

datafusion/core/src/datasource/file_format/parquet.rs
Closes #https://github.com/apache/datafusion/issues/10877
In InfluxDB, we want to have a a function similar to [fetch_statistics](https://github.com/apache/datafusion/blob/47026a2a3dd41a5c87e44ade58d91a89feba147b/datafusion/core/src/datasource/file_format/parquet.rs#L458-L536) but the given input is not the ObjectStore and ObjectMeta but the ParquetMetaData
Refactor [fetch_statistics](https://github.com/apache/datafusion/blob/47026a2a3dd41a5c87e44ade58d91a89feba147b/datafusion/core/src/datasource/file_format/parquet.rs#L458-L536) 
Yes
No
=> refactor: fetch statistics for a given ParquetMetaData

datafusion/core/src/datasource/physical_plan/parquet/access_plan.rs, datafusion/core/src/datasource/physical_plan/parquet/mod.rs, datafusion/core/src/datasource/physical_plan/parquet/opener.rs
Follow on to https://github.com/apache/datafusion/pull/10813
@advancedxy  had some good suggestions in https://github.com/apache/datafusion/pull/10813#pullrequestreview-2109681973
Implement suggestions from https://github.com/apache/datafusion/pull/10813#pullrequestreview-2109681973
Existing CI
Not really -- there is a new debug log message
=> Refine ParquetAccessPlan comments and tests

datafusion/core/tests/fuzz_cases/join_fuzz.rs, datafusion/physical-plan/src/joins/sort_merge_join.rs
=> Minor: disable flaky fuzz test

datafusion/core/src/datasource/physical_plan/parquet/reader.rs
Part of https://github.com/apache/datafusion/issues/10580
While working on https://github.com/apache/datafusion/pull/10701  it was quite unclear to me why the parquet reader was doing a second object store request even when I had passed it pre-existing `ParquetMetadata`
It turns out the it was because the cached `ParquetMetadata` didn't have the page index strutures loaded, and so the parquet exec will load them on demand if required.
1. Add documentation
Note: I documented this in arrow-rs too: https://github.com/apache/arrow-rs/pull/5887
=> Docs: clarify when the parquet reader will read from object store when using cached metadata

benchmarks/bench.sh
Closes #.
While reviewing https://github.com/apache/datafusion/pull/10894 I noticed the tpch data generator seems broken
```
andrewlamb@Andrews-MacBook-Pro-2:~/Software/datafusion$ ./benchmarks/bench.sh data
...
warning: field `range` is never read
--> datafusion/physical-expr/src/window/window_expr.rs:562:9
|
561 | pub struct NthValueState {
|            ------------- field in this struct
562 |     pub range: Range<usize>,
|         ^^^^^
|
= note: `NthValueState` has derived impls for the traits `Clone` and `Debug`, but these are intentionally ignored during dead code analysis
= note: `#[warn(dead_code)]` on by default
warning: `datafusion-physical-expr` (lib) generated 1 warning
Finished `release-nonlto` profile [optimized] target(s) in 0.10s
Running …
```
=> Minor: Fix `bench.sh tpch data`

benchmarks/.gitignore, benchmarks/bench.sh, benchmarks/compare.py, benchmarks/requirements.txt
Closes https://github.com/apache/datafusion/issues/10022
(Note: this PR follows up on https://github.com/apache/datafusion/pull/10070 which worked on the same issue but looks like got kinda stale)
Make it more convenient to run `bench.sh compare`
Updates to bench.sh to include a new command `venv`, and edit the `compare` command to use the respective `venv`
Separates requirements.txt in case `compare.py` would ever need something else
I tested by hand `./bench.sh compare` and `./bench.sh venv`, in multiple scenarios:
- create empty venv with bench.sh, then run compare
- have existing venv, update with bench.sh venv, then run compare
- have no venv but install `rich` into system, and just run compare
In all cases compare works correctly.
No -- if the `compare` worked for the user before, …
=> Minor: use venv in benchmark compare

datafusion/expr/src/expr_schema.rs, datafusion/expr/src/type_coercion/functions.rs, datafusion/sqllogictest/test_files/array.slt
Closes https://github.com/apache/datafusion/issues/10915.
The changes in https://github.com/apache/datafusion/pull/10651/ lead to a change in the error messages given when a function is called without any arguments. I think it can be made a little clearer to the user what actually went wrong, the error message as of this PR vs `main` can be seen below.
The new error message as of this PR:
```
"Error during planning: Error during planning: SUM does not support zero arguments. No function matches the given name and argument types 'SUM()'. You might need to add explicit type casts.\n\tCandidate functions:\n\tSUM(UserDefine
d)"
```
The current error message in main:
```
"Error during planning: Error during planning: [data_types_with_aggregate_udf] Coercion from [] to the signature VariadicAny …
```
=> chore: update some error messages for clarity

datafusion/functions/src/string/contains.rs, datafusion/functions/src/string/mod.rs, datafusion/sqllogictest/test_files/functions.slt, datafusion/substrait/tests/cases/function_test.rs, datafusion/substrait/tests/cases/mod.rs, datafusion/substrait/tests/testdata/contains_plan.substrait.json, docs/source/user-guide/sql/scalar_functions.md
=> Add contains function, and support in datafusion substrait consumer

datafusion/core/tests/parquet/arrow_statistics.rs
Part of https://github.com/apache/datafusion/issues/10922
I thought of a way to make the tests easier to write -- which will be important as we start expanding out the test coverage
Add an enum to make more explicit what is being testsed
Only tests
No
cc @marvinlanhenke
=> Minor: Improve `arrow_statistics` tests

benchmarks/bench.sh
Closes #.
clickbench does not expect `--prefer_hash_join`, remove it. It is introduce in #10809 
```
***************************
DataFusion Benchmark Script
COMMAND: run
BENCHMARK: clickbench_partitioned
DATAFUSION_DIR: /Users/bytedance/arrow-datafusion/benchmarks/..
BRANCH_NAME: rm-hash-join-env-clickbench
DATA_DIR: /Users/bytedance/arrow-datafusion/benchmarks/data
RESULTS_DIR: /Users/bytedance/arrow-datafusion/benchmarks/results/rm-hash-join-env-clickbench
CARGO_COMMAND: cargo run --profile release-nonlto
PREFER_HASH_JOIN: true
***************************
RESULTS_FILE: /Users/bytedance/arrow-datafusion/benchmarks/results/rm-hash-join-env-clickbench/clickbench_partitioned.json
Running clickbench (partitioned, 100 files) benchmark...
Finished `release-nonlto` profile [optimized] target(s) …
```
=> Minor: Remove `prefer_hash_join` env variable for clickbench

datafusion-cli/src/main.rs, docs/source/user-guide/cli/usage.md
Closes #.
Currently `-h` in the datafusion CLI shows the default for max rows twice.
This PR removes the value from the argument help, so the default is only shown once.
Yes, compiled and looked at the help.
currenly main shows:
```
--maxrows <MAXROWS>
The max number of rows to display for 'Table' format
[default: 40] [possible values: numbers(0/10/...), inf(no limit)] [default: 40]
```
but after this PR, it'll show
```
--maxrows <MAXROWS>
The max number of rows to display for 'Table' format
[possible values: numbers(0/10/...), inf(no limit)] [default: 40]
```
Note the how the 2nd one only has one `[default: 40]`.
Minor, CLI help.
=> refactor: remove extra default in max rows

datafusion/core/src/datasource/physical_plan/parquet/statistics.rs
Closes #.
Refactor the code `get_statistics!` in `statistics.rs` to improve the performance of converting Parquet statistics to Arrow arrays. Instead of using conditional checks and `try_from` conversions, use the `ok()` method to handle the conversion and filtering of values. This change simplifies the code and improves readability.
=> chore: Improve performance of Parquet statistics conversion

datafusion/core/src/catalog/mod.rs, datafusion/core/src/execution/session_state.rs, datafusion/sqllogictest/test_files/cte.slt
Closes #10875.
This logic is extracted from `SessionState::resolve_table_references`, but can be used without a context making it more flexible as a helper function for catalog management.
The `resolve_table_references` function will only return the tables from the information schema if it actually implicitly requires them due to a `SHOW` statement.
A new public function `catalog::resolve_table_references` is added, containing the same logic as `SessionState::resolve_table_references` but in a more flexible interface.
Yes there is a doctest and it's well covered by sqllogictests as it's executed as part of SQL planning.
A new public function is added.
The behaviour of `SessionState::resolve_table_references` around the information schema is changed, which could theoretically break users …
=> Add catalog::resolve_table_references

datafusion/core/src/datasource/physical_plan/parquet/statistics.rs, datafusion/core/tests/parquet/arrow_statistics.rs
=> feat: Add support for Int8 and Int16 data types in data page statistics

datafusion-cli/src/main.rs, datafusion-cli/src/pool_type.rs
Closes #.
Currently for the PoolType option handling in the CLI, the argument is an Option, but Clap can handle the default explicitly for the enum, which simplifies the enum handling later in the enum. The default handling logic no longer "leaks" into the runtime configuration.
1. Move `PoolType` to its own file and implement `Display` for it so it can be used as a default w/ clap.
2. Specify `PoolType::Greedy` as the default and change the arg type from `Option<PoolType>` to `PoolType`
3. Update the main CLI function to account for the fact its no longer an option and make the match arms explicit.
CLI `-h` changes from:
```
--mem-pool-type <MEM_POOL_TYPE>
Specify the memory pool type 'greedy' or 'fair', default to 'greedy'
```
to
```
--mem-pool-type <MEM_POOL_TYPE>
Specify the memory …
```
=> refactor: improve PoolType argument handling for CLI

datafusion-cli/examples/cli-session-context.rs, datafusion-cli/src/cli_context.rs, datafusion-cli/src/command.rs, datafusion-cli/src/exec.rs, datafusion-cli/src/lib.rs, datafusion-cli/src/object_storage.rs
Closes #.
The idea is to add a `CliSessionContext` trait, which is used in the CLI in place of `SessionContext`. In doing so, I hope to make it possible for code in the `datafusion-cli` crate to be used for a custom `SessionContext` (e.g. running a REPL). See the example for something more complete.
IMO it also makes the CLI code a little cleaner (e.g. making `register_options` into a method), but that's more subjective.
* Adds a `CliSessionContext` trait.
* Updates the CLI entrypoint and related code to use a `CliSessionContext` instead of a `SessionContext` directly. 
* Adds an example: 
* Implements `CliSessionContext` for `SessionContext`
The CLI tests seem to pass w/ the trait being the main arg. Additionally, I've done some manual testing.
No
=> feat: add CliSessionContext trait for cli

datafusion/common/src/column.rs
Closes #.
While profiling code for for CSE copy removal (https://github.com/apache/datafusion/pull/10835) and noticed that 5% of the time was spent in `Column::from_qualified_name` (see screen shot)
When I looked into this a bit more, it seems to be copying the string twice on the error path which can be avoided. 
I doubt this will matter much in practice but I also think the code is cleaner this way.
Only make a string when needed
=> Minor: remove potential string copy from Column::from_qualified_name

datafusion/core/src/datasource/physical_plan/parquet/row_groups.rs, datafusion/core/src/datasource/physical_plan/parquet/statistics.rs, datafusion/core/tests/parquet/arrow_statistics.rs
Closes #10926.
- row_group_null_counts, data_page_null_counts
- data_page_row_counts
return an ArrayRef instead of UInt64Array.
- fixed methods to return correct array type
- changed data_page_row_counts to fall back on row_page_row_counts if column is missing
- added a test case in `arrow_statistics`
Yes.
=> Fix: StatisticsConverter `counts` for missing columns

datafusion/optimizer/src/decorrelate_predicate_subquery.rs, datafusion/sqllogictest/test_files/subquery.slt
=> fix: Support  `NOT <field> IN (<subquery>)` via anti join

datafusion/sql/src/cte.rs, datafusion/sql/src/expr/subquery.rs, datafusion/sql/src/planner.rs, datafusion/sql/src/query.rs, datafusion/sql/src/relation/join.rs, datafusion/sqllogictest/test_files/cte.slt
Closes #10914.
Each query should have its own scope-visible CTEs and be able to inherit the CTEs from the outer query.
CTEs defined within a subquery should be visible only inside that subquery without affecting the outer query.
These goals can be achieved by cloning `PlannerContext` for each query.
- Clone the `PlannerContext` for each query/subquery to fix the CTE scope bug.
- Use `Arc` to make cloning the `PlannerContext` cheaper.
- Eliminate the cloning of the `PlannerContext` during planning joins and SetExprs, as this has already been done in each subquery.
Yes. By existing tests and new tests.
No
=> fix: CTEs defined in a subquery can escape their scope

Cargo.toml, datafusion-cli/Cargo.lock, datafusion-cli/Cargo.toml, datafusion/common/src/scalar/mod.rs, datafusion/expr/src/type_coercion/binary.rs, datafusion/expr/src/type_coercion/functions.rs, datafusion/functions/src/datetime/date_bin.rs
Part of https://github.com/apache/datafusion/issues/10961 and https://github.com/apache/datafusion/issues/10918
Note this targets the `string-view` branch and NOT `main`
As we work through StringView development we are going to use an integration branch pointed at the arrow main branch
1. Pin the `string-view` branch to upstream arrow
2. Update to fix some clippy errors from upstream changes
3. Uncomment a test that is waiting on upstream code
=> Update `string-view` branch to arrow-rs main

datafusion-examples/examples/parquet_index.rs, datafusion/core/benches/parquet_statistic.rs, datafusion/core/src/datasource/physical_plan/parquet/row_groups.rs, datafusion/core/src/datasource/physical_plan/parquet/statistics.rs, datafusion/core/tests/parquet/arrow_statistics.rs
Closes #10965.
As stated in #10965:
> [...] even when there are no row group statistics, but it doesn't make logical sense. Furthermore, for data pages, it is different if the "page index" is not present as then it doesn't even make sense to ask how many rows are in each data page as we don't have any data pages. Thus I think row_group_row_counts should also default to returning None [...] 
- changed return type of `row_group_row_count`
- fixed downstream consumers
Yes.
=> Minor: Return option from row_group_row_count

datafusion/core/tests/fuzz_cases/join_fuzz.rs, datafusion/physical-plan/src/joins/sort_merge_join.rs
Closes #.
It is pretty complicated to find the exact root cause for issues  triggered by fuzz tests. Those tests have a random nature and sometime require stable things to reproduce the case especially when the test is flaky. Adding debug procedures and doc how to use then while debugging https://github.com/apache/datafusion/issues/10886
=> Minor: Add routine to debug join fuzz tests

datafusion/sql/src/unparser/expr.rs
Closes #10796 .
Instead of `array_value_to_string`, I just follow how to convert `datetime` type because I found the timestamp string converted by the arrow formatter would be 
```
1970-01-01T00:00:00.000010001
```
but I think the result generated by `datetime::to_string` is more suitable for SQL
```
1970-01-01 00:00:00.000010001
```
Yes
=> Support to unparse `ScalarValue::TimestampNanosecond` to String

datafusion/physical-plan/src/aggregates/group_values/row.rs
Part of #7000 
While working with @jayzhan211 on https://github.com/apache/datafusion/pull/10976 I noticed a TODO that could avoid some allocations
Use the API added in https://github.com/apache/arrow-rs/issues/4479  to reuse the temporary `Rows` allocation in the Hash grouping
Functionally tested by CI
Performance benchmarks show maybe a slight improvement in performance (but not major)
<details><summary>Details</summary>
<p>
```
Benchmark clickbench_1.json
┏━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Query        ┃  main_base ┃ alamb_less_allocation ┃        Change ┃
┡━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ QQuery 0     │     0.86ms │                0.84ms │     no change │
│ QQuery 1 …
```
=> Minor: reuse Rows buffer in GroupValuesRows

datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs, datafusion/optimizer/src/simplify_expressions/regex.rs
Closes #.
Regex simplifier requires the pattern is fully anchored, this patch extends the boundary to partial anchored pattern. And also improves document in this mod
Makes regex simplifier able to handle partially anchored regex like `^foo` or `foo$`
Yes
More regex match expr can be converted to `LIKE` expr
=> feat(optimizer): handle partial anchored regex cases and improve doc

Cargo.toml, datafusion-cli/Cargo.lock, datafusion-cli/Cargo.toml, datafusion/common/src/scalar/mod.rs, datafusion/expr/src/type_coercion/binary.rs, datafusion/sqllogictest/test_files/string_view.slt
Note: targets `string-view` branch
Closes #10919
=> feat: Implement equality = and inequality <> support for StringView

datafusion/core/src/datasource/physical_plan/parquet/statistics.rs, datafusion/core/tests/parquet/arrow_statistics.rs, datafusion/core/tests/parquet/mod.rs
Closes #10951.
Just extends the existing functionality for parquet page data stats -- `int` cases were covered previously, I just add `float` cases in the same fashion.
* Float64 was a breeze, just add a macro invocation and case branch,
* Float32 needed additionally an extension of data generation option -- I hope I didn't miss it existing already,
* Float16 got a bit messy and required something I'm not happy with. Unlike other data types, it's physically represented as `FixedByteLength` of 2 bytes, which doesn't behave like a primitive type. In particular, I needed to add a `.clone()` at a particular place, which required going from `ident` to `expr` in a macro, affecting all cases. I'm very open to suggestions here -- I haven't come up with a better idea myself yet.
Yes, I extended …
=> Add parquet page stats for float{16, 32, 64}

datafusion-examples/examples/file_stream_provider.rs
Closes #.
`file_stream_provider` example depends on `nix` crate which not support windows os. We could use cfg to avoid compilation failure on windows.
Not change any code, just move code behind cfg flag.
=> Fix `file_stream_provider` example compilation failure on windows

datafusion/sqllogictest/test_files/string_view.slt
Note this targets `string-view` branch, not `main`
Part of https://github.com/apache/datafusion/issues/10918
Follow up from https://github.com/apache/datafusion/pull/10985 with @Weijun-H 
Update the StringView comparison test coverage with additional cases (including Dictionary comparison)
It is only tests
No
=> Add more StringView comparison test coverage

datafusion/optimizer/src/push_down_filter.rs, datafusion/sqllogictest/test_files/push_down_filter.slt
=> Push down filter plan for unnest on non-unnest column only

datafusion/sqllogictest/test_files/push_down_filter.slt
Follow on to https://github.com/apache/datafusion/pull/10991
@jonahgao  suggested an additional improvement: https://github.com/apache/datafusion/pull/10991#pullrequestreview-2128604718
This PR adds a test for such a case
It is only test
=> Minor: add test for pushdown past unnest

datafusion/proto/CONTRIBUTING.md, docs/source/contributor-guide/getting_started.md
Closes #10979.
* Changes minimum version from v3.12 to v3.15
* Fixes link to `protoc` installation instructions
=> Update docs for `protoc` minimum installed version

datafusion/common/src/scalar/mod.rs, datafusion/expr/src/type_coercion/binary.rs, datafusion/sqllogictest/test_files/binary_view.slt
=> feat: Implement equality = and inequality <> support for BinaryView

datafusion/core/src/datasource/physical_plan/parquet/statistics.rs, datafusion/core/tests/parquet/arrow_statistics.rs
Closes #10952
Supports additional data types for data page stats.
Parse the uints for data page stats. It's adapted from how it works for row groups... https://github.com/apache/datafusion/blob/5bfc11ba4ac4f11eaf9793c668e4a064fb697e6e/datafusion/core/src/datasource/physical_plan/parquet/statistics.rs#L321-L336
Yes, updates the unit tests to cover row groups and data pages.
No
=> feat: support uint data page extraction

datafusion/physical-expr/src/analysis.rs
Closes #10536. 
In https://github.com/apache/datafusion/blob/cafbc9ddceb5af8c6408d0c8bbfed7568f655ddb/datafusion/physical-expr/src/analysis.rs#L95
The function panics when `col_index` is out of bounds when returning an internal error with extra context is much more convenient.
Propagate the error as en `DataFusionError::Internal.`
Users may need to handle that error case
=> propagate error instead of panicking on out of bounds in physical-expr/src/analysis.rs 

datafusion/common/src/tree_node.rs
Part of #7013 
`Transformed` is a key structure when using the TreeNode API and so it is important to make it as easy to use as possible.
1. Update documentation and add some examples
Covered by doc tests 
New docs
There are no functional changes
=> Minor: Add more docs and examples for `Transformed` and `TransformedResult`

datafusion/core/src/dataframe/mod.rs, docs/source/user-guide/dataframe.md
Closes #11007 
Add drop_columns to the dataframe api.
code, tests, documentation
Yes via tests in dataframe/mod.rs
dataframe API was amended.
=>  Add drop_columns to dataframe api

datafusion/expr/src/logical_plan/plan.rs, datafusion/optimizer/src/push_down_filter.rs, datafusion/sqllogictest/test_files/push_down_filter.slt
Follow on #10991 
Closes https://github.com/apache/datafusion/issues/11016
In https://github.com/apache/datafusion/pull/10991, if we see unnest column, we skip the push down optimization.
In this PR, we select the non-unnest columns to push down, even there is unnest columns besides.
=> Push down filter plan for non-unnest column

datafusion/expr/src/type_coercion/binary.rs, datafusion/sqllogictest/test_files/binary_view.slt, datafusion/sqllogictest/test_files/string_view.slt
Closes #11023 .
Support for LargeString and LargeBinary for StringView and BinaryView
=> Implement support for LargeString and LargeBinary for StringView and BinaryView

datafusion-examples/examples/rewrite_expr.rs, datafusion/core/tests/user_defined/user_defined_plan.rs, datafusion/optimizer/src/lib.rs, datafusion/optimizer/src/optimizer.rs, datafusion/optimizer/src/utils.rs
Closes #.
As we have already migrated built-in optimizer rules to use `rewrite` api, I think it's time to deprecate `try_optimize` api.
=> Deprecate `OptimizerRule::try_optimize`

datafusion/core/src/physical_optimizer/combine_partial_final_agg.rs, datafusion/sqllogictest/test_files/group_by.slt, datafusion/sqllogictest/test_files/joins.slt
Closes #.
Currently, `CombinePartialFinalAggregate` rule combine `AggregateExec::Partial` + `AggregateExec::Final` into `AggregateExec::Single` when following conditions are met (same conditions applies to the combining `AggregateExec::Partial` + `AggregateExec::FinalPartitioned` into `AggregateExec::SinglePartitioned`):
- These operators are consecutive
- Their group by expressions are equal
- Their aggregate expressions are equal
- Their filter expressions are equal.
See [can_combine](https://github.com/synnada-ai/datafusion-upstream/blob/d6e39a45988f5b40152773db166390a4bb56129a/datafusion/core/src/physical_optimizer/combine_partial_final_agg.rs#L141) function for implementation.
However, the query below
```sql
SELECT
DATE_BIN(INTERVAL '2' MINUTE, ts, '2000-01-01') AS ts_chunk, …
```
=> Relax combine partial final rule

datafusion/functions/src/math/gcd.rs, datafusion/sqllogictest/test_files/scalar.slt
Closes #11031.
The issue mentioned 2 problems, I'll give an explanation here why this happened:
LCM depends on GCD, and the problems are indeed in GCD, so I expect that a fix to GCD will also fix LCM.
This is because of using `i64` when computing the gcd, but the gcd is never negative. Rust doc also says that `i64::MIN.wrapping_abs() == i64::MIN`, so in the error case mentioned the gcd_compute goes like this:\
- Initial values
`a` = i64::MAX, `b` = i64::MIN
- After `wrapping_abs`:
`a` = still i64::MAX, `b` = still i64::MIN
- After the binary shifts:
`a` = still i64::MAX, b = -1 (here lies the problem)
- we swap `a` and `b` because a > b:
`a` = -1, `b` = i64::MAX
- Now we subtract a from b:
i64::MAX - (-1) = i64::MAX + 1 (here is our integer overflow)\
And because LCM depends on GCD, it …
=> Compute gcd with u64 instead of i64 because of overflows

datafusion/sqllogictest/test_files/timestamps.slt
Closes #.
Add test cases to show the current behavior of `AT TIME ZONE` for string vs. timestamp
Tests
Yes
No, only added test code
=> chore: add test to show current behavior of `AT TIME ZONE` for string vs. timestamp

datafusion/core/src/datasource/physical_plan/parquet/statistics.rs, datafusion/core/tests/parquet/arrow_statistics.rs
Closes #11027.
Implements boolean data page statistics in parquet, with tests.
Because `BooleanArray::from_iter` requires that `iter.size_hint()` returns `(_, Some(upper))` we have to collect the flattened `BooleanDataPageStatsIterator`. But i find this weird since we pass a Sized Iterator (Vec::into_iter) into `flatten()`, which would keep the upper bound. I have not gone deeper than this, but I think we don't need this extra allocation in there.
yes
no
=> Boolean parquet get datapage stat

datafusion/core/src/physical_planner.rs, datafusion/sqllogictest/test_files/expr.slt
=> Using display_name for Expr::Aggregation

datafusion-cli/Cargo.lock, datafusion/expr/src/function.rs, datafusion/functions/Cargo.toml, datafusion/functions/src/regex/regexpreplace.rs, datafusion/functions/src/string/btrim.rs, datafusion/functions/src/string/ltrim.rs, datafusion/functions/src/string/rtrim.rs, datafusion/functions/src/utils.rs, datafusion/physical-expr/src/functions.rs
=> Minor: Move `function::Hint` to `datafusion-expr` crate to avoid physical-expr dependency for `datafusion-function` crate

datafusion/sql/src/unparser/expr.rs
Closes #10797
just follow https://github.com/apache/datafusion/pull/10984 to convert `ScalarValue::TimestampMillisecond` to a  String
yes, unit test
=> Support to unparse ScalarValue::TimestampMillisecond to String

datafusion/core/tests/fuzz_cases/join_fuzz.rs, datafusion/physical-plan/src/joins/sort_merge_join.rs
Closes #10886 .
There was an issue in SMJ when streamed rows handled concurrently. Race conditions for the `self.streamed_batch.join_filter_matched_idxs` lead SMJ  producing duplicates because of unexpected event ordering caused by concurrency.
Added an extra check when calculating the filter boolean mask and test methods to make fuzz test debugging easier in future
Yes. There is no specifc test because of unstable test nature. The issue can be reproduced on main branch with high probability by running the test 1000 times
```
#[tokio::test]
async fn test_semi_join_1k_filtered() {
for _ in 0 .. 1000 { 
JoinFuzzTestCase::new(
make_staggered_batches(1000),
make_staggered_batches(1000),
JoinType::LeftSemi,
Some(Box::new(col_lt_col_filter)),
)
.run_test(&[JoinTestType::HjSmj], false)
.await
} …
```
=> SMJ: fix streaming row concurrency issue for LEFT SEMI filtered join

datafusion-examples/README.md, datafusion-examples/examples/parse_sql_expr.rs, datafusion/core/src/dataframe/mod.rs, datafusion/core/src/datasource/physical_plan/parquet/statistics.rs, datafusion/core/src/execution/context/mod.rs, datafusion/core/src/execution/session_state.rs, datafusion/core/tests/expr_api/mod.rs, datafusion/core/tests/expr_api/parse_sql_expr.rs, datafusion/sql/src/parser.rs
=> Support parsing SQL strings to Exprs

datafusion/physical-expr/src/aggregate/min_max.rs, datafusion/sqllogictest/test_files/aggregate.slt
=> Implement min/max for interval types

datafusion/core/src/test/mod.rs, datafusion/core/src/test_util/mod.rs, datafusion/core/tests/custom_sources_cases/mod.rs, datafusion/core/tests/custom_sources_cases/provider_filter_pushdown.rs, datafusion/core/tests/custom_sources_cases/statistics.rs, datafusion/core/tests/user_defined/user_defined_plan.rs, datafusion/physical-plan/src/lib.rs, datafusion/physical-plan/src/test/exec.rs
Follow-up of https://github.com/apache/datafusion/pull/10266
https://github.com/apache/datafusion/pull/10266 tries to provide a default implementation based on `static_name()`. This propagates the `Sized` requirement to `name()` and prohibits it from being called by a trait object.
Remove the default implementation of `ExecutionPlan::name()` and let every implementor implement their own based on `static_name()` to workaround object safety requirements. This is something like `as_any()`.
This solution is not elegant, but I can only find this way to suit both (1) invoke from trait object and (2) invoke from type name. Please add your suggestion if there is any better way to do so. Thanks in advance!
Yes, for those who implements `ExecutionPlan`, they need to add a new method on `impl`
=> fix: remove the Sized requirement on ExecutionPlan::name()

datafusion/substrait/src/logical_plan/consumer.rs, datafusion/substrait/tests/cases/roundtrip_logical_plan.rs
Closes #10815 , and also adds support for joining two VirtualTables with overlapping column names.
Substrait doesn't contain aliases inside the plan: neither table aliases (SubqueryAlias), nor column aliases. Columns are only named at the beginning and end of the plan, while tables are not named by substrait at all. Substrait referes to columns only by their relative indices, so that's name-independent.
When we consumer Substrait plans' ReadRels, the created DataFusion tables may or may not have qualifiers. If the tables are NamedTable reads, then DataFusion uses the name as the qualifier. If the tables are VirtualTables, then we have unqualified tables.
This causes trouble in some cases for DataFusion, as DF requires columns to be uniquely named in at least two places (there’s probably …
=> feat: Support duplicate column names in Joins in Substrait consumer

datafusion/sql/src/unparser/expr.rs
Basic support for decimal unparsing
Decimal is a common type in many sql engines, custom data provider will need this when query involves decimal
Convert decimal 128 and 256 to Ast type.
Convert both of them into string.
Yes
No
=> decimal support for unparser

datafusion/expr/src/expr.rs, datafusion/expr/src/utils.rs, datafusion/proto/proto/datafusion.proto, datafusion/proto/src/generated/pbjson.rs, datafusion/proto/src/generated/prost.rs, datafusion/proto/src/logical_plan/from_proto.rs, datafusion/proto/src/logical_plan/to_proto.rs, datafusion/sql/src/select.rs
Closes #11072.
This PR changes the wildcard qualifier type to `TableReference`. This avoids an implicit SQL parsing during logical planning, and makes the API more consistent.
The PR changes the wildcard qualifier type for `Expr::Wildcard` and updates the `.proto` file.
The changes are covered by existing tests.
Yes, this PR contains breaking changes to the public API.
=> Change wildcard qualifier type from `String` to `TableReference`

datafusion/core/src/datasource/function.rs, datafusion/core/src/execution/context/mod.rs, datafusion/core/src/execution/session_state.rs, datafusion/core/tests/user_defined/user_defined_table_functions.rs
Partially closes #9203.
The `FunctionRegistry` trait does not include methods to manage UDTF. This is because adding the methods would cause circular dependency on `TableProvider`, as explained in #9203. However, it would be useful if the user can still access/deregister the table functions they have registered. We already have the `register_udtf()` method for `SessionState` and `SessionContext`, though they are not part of the `impl FunctionRegistry` block.
This PR adds public API for `SessionContext` and `SessionState` so that the user can look up and deregister UDTF. The method is not part of the `FunctionRegistry` trait though.
Yes. A unit test is added for the changes.
Yes, this PR contains backward-compatible changes to the public API.
=> Allow access to UDTF in `SessionContext`

datafusion/expr/src/logical_plan/builder.rs, datafusion/sql/src/unparser/mod.rs, datafusion/sql/src/unparser/plan.rs, datafusion/sql/src/unparser/rewrite.rs, datafusion/sql/tests/cases/plan_to_sql.rs
Closes #10706
The schema that is the result of a UNION ALL should not have any table qualifiers, as the table information has effectively been erased and is no longer a valid reference.
Consider the following SQL:
```sql
SELECT table1.foo FROM table1
UNION ALL
SELECT table2.foo FROM table2
```
The logical schema from this UNION ALL should be just `foo`, but it is currently taking the first input's schema directly, resulting in a schema of `table1.foo`.
This came up as an issue when trying to validate the unparser works correctly for UNION ALL statements, which I added in https://github.com/apache/datafusion/pull/10603
Slightly modifying the above example, if I add an ORDER BY clause to the input SQL:
```sql
SELECT table1.foo FROM table1
UNION ALL
SELECT table2.foo FROM table2
ORDER BY foo …
```
=> Strip table qualifiers from schema in `UNION ALL` for unparser

datafusion/core/tests/sql/select.rs, datafusion/expr/src/type_coercion/binary.rs, datafusion/functions-array/src/rewrite.rs, datafusion/sql/src/expr/mod.rs
Closes #.
Part of #8506 and #10534
and nice to have for #9857
=> Rewrite array operator to function in parser

datafusion/functions/src/datetime/to_timestamp.rs
N/A
Implement suggestion from @comphead  in https://github.com/apache/datafusion/pull/11038#discussion_r1650133844
> may be we can factor this out? the same block is too repetitive
1. Factor repetition into a new function 
Existing CI tests
=> Minor: Avoid some repetition in to_timestamp

datafusion-examples/README.md, docs/source/index.rst
Part of #7013 
While reading these docs recently I found there were some places where the language was rough and I would like to improve it
Improve the wording about examples
=> Minor: refine documentation pointing to examples

datafusion/common/src/scalar/mod.rs
=> Minor: fix ScalarValue::new_ten error message (cites one not ten)

datafusion/expr/src/expr.rs, datafusion/expr/src/logical_plan/builder.rs
Closes https://github.com/apache/datafusion/issues/10505
Follow on to https://github.com/apache/datafusion/pull/11067
`Expr::column_refs` is much more efficient than `Expr::to_columns` as it avoids copying strings. Thus we should
use it more in the codebase and encourage users to do the same
Deprecate the function
By existing CI
Function is deprcated
=> Deprecate Expr::column_refs

datafusion-cli/src/catalog.rs, datafusion-cli/src/main.rs, datafusion/core/src/execution/context/mod.rs, datafusion/core/src/execution/session_state.rs, datafusion/expr/src/udaf.rs, datafusion/expr/src/udf.rs, datafusion/expr/src/udwf.rs
Closes #11100.
It's better to return `&Arc` reference to inner trait object for `&self` methods. This makes it easier to work with Rust lifetime rules when we need to cast trait object to concrete reference types. Please refer to the corresponding issue for an example. 
This PR updates the return type for few methods in `ScalarUDF`, `AggregateUDF`, `WindowUDF`, and `SessionState`.
The changes are covered by existing tests.
Yes, these are breaking changes to the public API. The changes should be small, since the user can simply call `.clone()` on `&Arc` if needed.
=> Return `&Arc` reference to inner trait object

datafusion/common/src/scalar/mod.rs
Closes #11076. Tracking: #11078
Doing checked negations on scalarValue
With unit tests yes
no
=> Overflow in negate operator

datafusion/functions/src/math/power.rs, datafusion/sqllogictest/test_files/math.slt
Closes #11075.
- check overflow for integer parameters
- check that exponent is non negative for integer parameters (this was allowed but resulted in nothing)
Added SLT test 
no
=> Fix overflow in pow

datafusion/core/src/datasource/physical_plan/parquet/statistics.rs, datafusion/core/tests/parquet/arrow_statistics.rs
=> feat: Add support for Timestamp data types in data page statistics.

datafusion/sql/src/unparser/expr.rs
=> Support to unparse Time scalar value to String

datafusion/sql/src/unparser/expr.rs
The follow-up of #11046 and #10984. Part of #9494 
yes
no
=> Support to unparse `TimestampSecond` and `TimestampMicrosecond` to String

datafusion/optimizer/src/analyzer/type_coercion.rs, datafusion/optimizer/src/unwrap_cast_in_comparison.rs, datafusion/sqllogictest/test_files/string_view.slt
=> Improve filter predicates with `Utf8View` literals

datafusion-examples/README.md, datafusion-examples/examples/optimizer_rule.rs, datafusion/core/src/execution/context/mod.rs, datafusion/core/src/execution/session_state.rs, datafusion/core/tests/user_defined/user_defined_plan.rs
Part of https://github.com/apache/datafusion/issues/10855
The current `rewrite_expr.rs` example has three distinct examples:
1. Using DataFusion LogicalPlanning without execution
2. Implementing an `AnalyzerRule`
3. Implementing an `OptimizerRule`
Each I think should be its own example to make them easier to find and more full featured
1. Add example `optimizer_rule.rs`
2. Add `SessionContext::add_optimizer_rule` as a convenience
3. Change signature of newly added SessionContext::add_analyzer_rule to take `&mut self` to be consistent
Yes, by CI test on examples
=> Add standalone example for `OptimizerRule`

datafusion/functions/src/math/factorial.rs, datafusion/sqllogictest/test_files/math.slt
Closes #11074 .
- do checked multiplication
- added SLT test for overflow
yes
no
=> Fix overflow in factorial

datafusion/core/src/physical_planner.rs, datafusion/sqllogictest/test_files/group_by.slt
Temporary fix for #11118
The query in the issue seems to require that the `physical_name` and `display_name` of the grouping expr must be the same. This is a temporary fix. 
I think this requirement might be unreasonable. Having multiple different types of names for expressions, while also ensuring they are the same, seems somewhat burdensome and error-prone.
Yes
No
=> Temporary Fix: Query error when grouping by case expressions

datafusion/common/src/scalar/mod.rs, datafusion/common/src/utils/mod.rs, datafusion/core/tests/dataframe/mod.rs, datafusion/core/tests/sql/aggregates.rs, datafusion/expr/src/aggregate_function.rs, datafusion/expr/src/expr.rs, datafusion/expr/src/expr_schema.rs, datafusion/functions-aggregate/src/bit_and_or_xor.rs, datafusion/functions-aggregate/src/count.rs, datafusion/functions-aggregate/src/median.rs, datafusion/functions-aggregate/src/sum.rs, datafusion/functions-array/src/make_array.rs, datafusion/functions-array/src/utils.rs, datafusion/physical-expr-common/src/aggregate/count_distinct/bytes.rs, datafusion/physical-expr-common/src/aggregate/count_distinct/native.rs, datafusion/physical-expr-common/src/aggregate/tdigest.rs, datafusion/physical-expr/src/aggregate/array_agg.rs, datafusion/physical-expr/src/aggregate/array_agg_distinct.rs, datafusion/physical-expr/src/aggregate/array_agg_ordered.rs, datafusion/physical-expr/src/aggregate/build_in.rs, datafusion/physical-expr/src/aggregate/nth_value.rs, datafusion/physical-plan/src/windows/mod.rs, datafusion/proto/tests/cases/roundtrip_logical_plan.rs, datafusion/substrait/src/logical_plan/consumer.rs, datafusion/substrait/src/logical_plan/producer.rs
Closes #11094. 
Currently the nullability of the value of the return type for the array_agg aggregate is wrong in two ways. Firstly the field inside the returned list is always nullable regardless of the input type and the actual list is only nullable depending on the input value. The correct behavior should be that the field in the list should depend on the input values nullabillity and the list field should not be nullable as the aggregate never returns null (it returns empty list instead).
In order to fix the nullability several changes are needed.
1. For the logical expr it is currently hard coded that all aggregates return nullable values, this is changed to be something that looked up based on the actual functions used.  For UDAF we will need to add a new customization point in the …
=> Fix nullability of return value of array_agg

datafusion/functions/src/math/gcd.rs, datafusion/functions/src/math/lcm.rs, datafusion/sqllogictest/test_files/math.slt, datafusion/sqllogictest/test_files/scalar.slt
Closes #11104.
- Use `checked_mul` to detect multiplication overflow. 
- This PR also fixed the issue of LCM potentially returning a negative result.
```sh
DataFusion CLI v39.0.0
> select lcm(1, -9223372036854775808);
+-------------------------------------------+
| lcm(Int64(1),Int64(-9223372036854775808)) |
+-------------------------------------------+
| -9223372036854775808                      |
+-------------------------------------------+
1 row(s) fetched.
```
Yes
No
=> fix: LCM panicked due to overflow

datafusion/core/tests/fifo/mod.rs, datafusion/core/tests/tpcds_planning.rs, datafusion/physical-expr/src/partitioning.rs, datafusion/physical-plan/src/aggregates/mod.rs
Closes #.
@yfy- is working on a [PR](https://github.com/synnada-ai/datafusion-upstream/pull/24) to check validity of a plan at the end of the optimization (called `SanityCheckRule`). This rule checks
- whether the distribution requirements for each operator is satisfied by its child(ren).
- whether the ordering requirements for each operator is satisfied by its child(ren).
If not, rule gives an error stating that plan is not valid. This rule rejects invalid queries without executing. See [PR](https://github.com/synnada-ai/datafusion-upstream/pull/24) for more detail. 
Indeed, rule already helped us to catch some silent errors. This PR fixes them.
=> [MINOR]: Fix some minor silent bugs

datafusion/core/src/physical_optimizer/pruning.rs, datafusion/expr/src/operator.rs, datafusion/expr/src/type_coercion/binary.rs, datafusion/expr/src/utils.rs, datafusion/optimizer/src/analyzer/type_coercion.rs, datafusion/optimizer/src/simplify_expressions/utils.rs, datafusion/optimizer/src/utils.rs, datafusion/physical-expr-common/src/datum.rs, datafusion/physical-expr/src/expressions/binary.rs, datafusion/physical-expr/src/intervals/cp_solver.rs, datafusion/physical-expr/src/intervals/utils.rs, datafusion/physical-expr/src/planner.rs, datafusion/physical-expr/src/utils/mod.rs, datafusion/proto/src/logical_plan/from_proto.rs, datafusion/substrait/src/logical_plan/producer.rs
This is the first step towards solving https://github.com/apache/datafusion/pull/10981#issuecomment-2177279989 - providing a general way to support more operators without having them all added to datafusion core.
The idea is that this would allow `Operator` to include another member of the union that in turn could including [`Custom(String)`](https://github.com/sqlparser-rs/sqlparser-rs/blob/a685e1199355b0150fd5a4f6c7b938ecc07a6818/src/ast/operator.rs#L115), but also potentially a function that defines extra operators' signatures, without having to hard code them into `datafusion/expr/src/type_coercion/binary.rs::signature`.
I'm creating this as a standalone PR, so:
1. It doesn't pollute other changes
2. ~~To see if there's willingness to accept this change before I go forward~~ The rest …
=> remove `derive(Copy)` from `Operator`

datafusion/core/src/datasource/physical_plan/parquet/mod.rs, datafusion/core/src/datasource/physical_plan/parquet/row_filter.rs, datafusion/core/src/datasource/physical_plan/parquet/row_groups.rs, datafusion/core/src/physical_optimizer/pruning.rs, datafusion/physical-expr-common/src/aggregate/mod.rs, datafusion/physical-expr/src/planner.rs, datafusion/physical-expr/src/utils/guarantee.rs
Closes #.
This is just a minor clean-up PR, locating `logical2physical()` where other physical expressions are created. I have also added a notice for the recently added API.
Removes some duplications of a function and add a notice for `with_new_expressions()` API.
=> Minor Fix for Logical and Physical Expr Conversions

datafusion/core/src/datasource/physical_plan/parquet/statistics.rs, datafusion/core/tests/parquet/arrow_statistics.rs
Closes #11113
Covered by existing test cases
```
cargo test
```
No
=> Support Date Parquet Data Page Statistics

datafusion/sqllogictest/test_files/array_query.slt
This was failing for me locally.
=> fix flaky array query slt test

datafusion/core/src/datasource/physical_plan/parquet/statistics.rs, datafusion/core/tests/parquet/arrow_statistics.rs
=> feat: Add support for `Binary`/`LargeBinary`/`Utf8`/`LargeUtf8` data types in data page statistics

datafusion/substrait/src/logical_plan/consumer.rs, datafusion/substrait/src/logical_plan/producer.rs
Closes #.
We don't currently support Map types in the Substrait consumer/producer at all. As Map type isn't yet implemented for ScalarValue (https://github.com/apache/datafusion/issues/11128), we cannot support Map literals, but we can still enable Map types.
I'm not sure how useful the Map type is w/o the literal support, but I already wrote this code so might as well add it 😅
=> feat: Support Map type in Substrait conversions

datafusion/core/src/dataframe/mod.rs, datafusion/physical-plan/src/joins/hash_join.rs
Closes #10749
This relies on newer functionality in arrow 52 and allows DataFrame.except() to properly work on schemas with structs and lists. I'm not sure if this is the appropriate way to handle this change per se, but I included the regression case from the issue as a test in order to demonstrate the correction of the issue
=> Implement comparisons on nested data types such that distinct/except would work

datafusion/physical-expr-common/src/datum.rs, datafusion/physical-plan/src/joins/hash_join.rs
Follow on to https://github.com/apache/datafusion/pull/11117
@jayzhan211  had a suggestion on how to simplify the implementation in https://github.com/apache/datafusion/pull/11117#discussion_r1655688627 from @rtyler . 
Use a pre-existing function to compare structured types
Covered by existing tests (added in https://github.com/apache/datafusion/pull/11117)
=> Minor: reduce replication for nested comparison

datafusion-cli/Cargo.lock, datafusion/physical-expr/Cargo.toml, datafusion/physical-expr/src/expressions/mod.rs, datafusion/physical-plan/src/aggregates/mod.rs
Closes #.
I recognized that we really don't need this dependency. Removing it simplifies the crate dependency graph.
I guess, the requirement for this dependency was historic, and the need became obsolete at some point. However, I appreciate the input from community.
=> [Minor]: Remove datafusion-functions-aggregate dependency from physical-expr crate

datafusion/proto/src/logical_plan/file_formats.rs, datafusion/proto/src/logical_plan/mod.rs, datafusion/proto/tests/cases/roundtrip_logical_plan.rs
The table reference is useful information for codecs that want to lookup a table provider by name when deserializing a plan.
An additional table reference parameter is exposed in `try_encode_table_provider` and `try_decode_table_provider`.
Yes the existing roundtrip test is extended to cover.
Yes this a breaking change, though a trivial one to a niche API.
=> expose table name in proto extension codec

datafusion/physical-plan/src/aggregates/row_hash.rs, datafusion/physical-plan/src/lib.rs, datafusion/physical-plan/src/sorts/sort.rs
Related to #9359 .
It looks like a bunch of useful spilling batch methods that can be used in any place whenever spilling is needed, not only for the sorting
=> Minor: move batch spilling methods to `lib.rs` to make it reusable

datafusion/core/src/datasource/listing/table.rs
It seems like this line is not needed unless the condition is met so let's save ourselves a bit of unnecessary compute.
=> Move schema projection to where it's used in ListingTable

datafusion-examples/examples/expr_api.rs, datafusion/common/src/dfschema.rs, datafusion/core/src/datasource/listing/helpers.rs, datafusion/core/src/physical_planner.rs, datafusion/expr/src/expr_schema.rs, datafusion/expr/src/logical_plan/builder.rs, datafusion/expr/src/logical_plan/plan.rs, datafusion/optimizer/src/analyzer/type_coercion.rs, datafusion/optimizer/src/common_subexpr_eliminate.rs, datafusion/optimizer/src/propagate_empty_relation.rs, datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs, datafusion/optimizer/src/unwrap_cast_in_comparison.rs
Closes #.
I find (actually this is found by my typo ci) this typo "unqualifed" in our public API.
Correct the typo
Yes, this is a breaking change.
I'm not sure how we should handle this. Maybe add a new correct spelling method that proxies to the current implementation, and deprecate the typo one?
Further more, is it necessary to setup a typo CI in this repository as well 🤔
=> fix(typo): unqualifed to unqualified

datafusion/core/src/physical_optimizer/mod.rs, datafusion/core/src/physical_optimizer/update_aggr_exprs.rs
This patch makes public some physical_optimizer mod's. This allows external code to use optimizations passes from these submodules.
To have an ability to use all of the existing physical optimizer passes in the user code that setup some optimization pipeline.
- Made projection_pushdown mod public
- Made update_aggr_exprs mod public 
No, because there are no changes in the logic.
=> Minor: make some physical_optimizer rules public

datafusion/core/src/datasource/file_format/parquet.rs, datafusion/core/src/datasource/statistics.rs
Closes #11145.
Modifies `create_max_min_accs` to instantiate accumulators for unpacked data - the value DataType of the Dictionary. 
This bug is very similar to a previous bug that impacted the Min/Max aggregate functions. https://github.com/apache/datafusion/pull/1235
In addition, the `min_max_aggregate_data_type` fn is copied from https://github.com/apache/datafusion/blob/8216e32e87b2238d8814fe16215c8770d6c327c8/datafusion/physical-expr/src/aggregate/min_max.rs#L63-L73
I'm unsure if copying the function is the right thing to do in order to prevent coupling between the crates or if it should be moved to some core crate? It also seems like the dedicated min and max functions are to be refactored into a user defined functions?
Yes - a new test has been added.
Currently implemented so the …
=> fix: Support dictionary type in parquet metadata statistics.

datafusion/substrait/src/logical_plan/consumer.rs, datafusion/substrait/src/logical_plan/producer.rs
Similar to https://github.com/apache/datafusion/pull/10874/files
Closes #.
Arrow requires schema to match exactly to literals. Substrait contains nullability separate in literals and types, and the nullability of a literal may vary
row-by-row.
The only reliable way I can think of is to either not use nullability at all (this PR), or alternatively pass the expected type into from_substrait_literal so that it can use the expected nullability.
Ignore nullability when consuming Substrait struct type and literal, always erring on the side of `nullable = true`
Tested by existing unit tests
=> fix: Ignore nullability in Substrait structs

datafusion/core/src/execution/context/mod.rs
N/A
I ran across a copy/paste error while reviewing https://github.com/apache/datafusion/pull/11035
Fix docs
=> Minor: fix SQLOptions::with_allow_ddl comments

datafusion/core/src/datasource/physical_plan/parquet/statistics.rs, datafusion/core/tests/parquet/arrow_statistics.rs
Closes #11114
Covered by existing test cases
```
cargo test
```
No
=> Support Time Parquet Data Page Statistics

datafusion/physical-plan/src/sorts/sort.rs
Closes #.
I think `sort_batch` functionality is general and very useful. Also, I use this function in tests (in other crates also) a lot. Hence, I think, we benefit from making this function public to extend its visibility.
=> [Minor]: Make sort_batch public

.github/workflows/rust.yml, ci/scripts/rust_example.sh, datafusion-examples/examples/custom_file_format.rs
Closes #11079
Adds an example of for how to `COPY table TO` a custom file format.
Created sort of a mock file format factory and file format that just wrap the CSV one but for a TSV.
yes, I've run the example
no
=> docs: add example for custom file format with `COPY TO`

datafusion/core/src/datasource/file_format/parquet.rs
It seems like this function doesn't need to be async. I exposed a sync version and deprecated the async one.
=> Make statistics_from_parquet_meta a sync function

datafusion/core/src/execution/context/mod.rs, datafusion/core/src/execution/session_state.rs, datafusion/core/tests/user_defined/mod.rs, datafusion/core/tests/user_defined/user_defined_sql_planner.rs, datafusion/expr/src/planner.rs, datafusion/expr/src/registry.rs, datafusion/functions-array/src/planner.rs
Follow up to #11180 that allows `UserDefinedSQLPlanner`s to be registered on `FunctionRegistry`s, mostly copied from #11137.
Yes, I've added a test
Adds `FunctionRegistry::register_user_defined_sql_planner`.
=> Allow user defined SQL planners to be registered

datafusion/core/src/lib.rs, docs/source/contributor-guide/testing.md, docs/source/user-guide/expressions.md
Part of https://github.com/apache/datafusion/issues/11172 and https://github.com/apache/datafusion/issues/1813
I am trying to make the examples easier to find / navigate. Right now there are many files in `datafusion-examples` but they are somewhat overwhelming. There are also some examples in the user guide, but many are not tested
I tried to consolidate the examples in https://github.com/apache/datafusion/pull/11173 but @lewiszlw (rightly) pointed out that one giant .rs example file might be even harder to find / navigate
I think the ideal outcome from a users perspective is for the examples to be inline in the user guide so they are both discoverable and the context explained. However, it is critical that the examples be testable
1. Document how to test examples in the user guide
2. …
=> Document how to test examples in user guide, add some more coverage

datafusion/core/src/catalog/information_schema.rs, datafusion/core/src/catalog/listing_schema.rs, datafusion/core/src/catalog/memory.rs, datafusion/core/src/catalog/mod.rs, datafusion/core/src/catalog/schema.rs, datafusion/core/src/lib.rs
part of https://github.com/apache/datafusion/issues/11182
There is a distinction between catalog API (the traits) and the provided simple implementations (e.g. `MemoryCatalogProvider*`) that is not well reflected in the module structure now.
If we make the code structure better mirror the distinction, it will both be clearer and set us up for future simplifications
1.  Move MemoryCatalog*Provider into a module
2. Improve doc comments
3. Leave backwards compatible `pub use`  
With existing CI
Better docs, no functional change
=> Minor: Move MemoryCatalog*Provider into a module, improve comments

datafusion/optimizer/src/push_down_filter.rs, datafusion/sqllogictest/test_files/join.slt
=> fix: Incorrect LEFT JOIN evaluation result on OR conditions

datafusion/core/src/datasource/physical_plan/parquet/statistics.rs, datafusion/core/tests/parquet/arrow_statistics.rs
Closes #11184
There are existing test cases
```
cargo test
```
=> Support FixedSizedBinaryArray Parquet Data Page Statistics

datafusion/physical-plan/src/windows/mod.rs, datafusion/sqllogictest/test_files/window.slt
The built-in window functions Lag, Lead, NthValue, Ntile accept integer arguments. However while they should allow any integers, currently as they just use ScalarValue's try_from to convert into an i64, they actually only accept i64s. Any other argument, e.g. an  i32, would be converted into a None and ignored (for lag and lead), or throw (for ntile and nth_value).
I noticed this as Spark and Substrait defines these functions as using int32 args.
Closes #.
Before - lag and lead would silently ignore the argument, ntile and nth_value would fail:
```
> SELECT id, lead(id, -1) OVER (ORDER BY id) AS correct, lead(id, arrow_cast(-1,'Int32')) OVER (ORDER BY id) as wrong from (values (1), (2)) as tbl(id);
+----+---------+-------+
| id | correct | wrong |
+----+---------+-------+
| 1  |         | …
```
=> fix: Be more lenient in interpreting input args for builtin window functions

datafusion/execution/src/cache/cache_manager.rs, datafusion/execution/src/cache/cache_unit.rs, datafusion/execution/src/disk_manager.rs, datafusion/execution/src/lib.rs, datafusion/execution/src/memory_pool/mod.rs, datafusion/execution/src/object_store.rs, datafusion/execution/src/task.rs
part of https://github.com/apache/datafusion/issues/11143.
=> Enable `clone_on_ref_ptr` clippy lint on execution crate

datafusion/optimizer/src/push_down_filter.rs
Related to  https://github.com/apache/datafusion/issues/10881
While reviewing https://github.com/apache/datafusion/pull/11203 from @viirya  I found some of the discussion about preserved input and what they meant somewhat confusing
Refine documentation to reflect better what was going on. 
N/A
No, this is internal documentation and no functional changes
=> Minor: Improve documentation about pushdown join predicates

datafusion/core/src/datasource/physical_plan/parquet/statistics.rs, datafusion/core/tests/parquet/arrow_statistics.rs
Closes #11235.
There were several tests where we missed changing `Check::RowGroup` to `Check::Both`. 
Changes most remaining tests in https://github.com/apache/datafusion/blob/3421b52605b00cd2e5a6498ea210cce196a19496/datafusion/core/tests/parquet/arrow_statistics.rs to `Check::Both`. The only two remaining tests are the one still in flight in https://github.com/apache/datafusion/pull/11200 and the one for nested Struct which hasn't been implemented yet.
However, note that there were two failing tests:
https://github.com/apache/datafusion/blob/3421b52605b00cd2e5a6498ea210cce196a19496/datafusion/core/tests/parquet/arrow_statistics.rs#L1474
and 
https://github.com/apache/datafusion/blob/3421b52605b00cd2e5a6498ea210cce196a19496/datafusion/core/tests/parquet/arrow_statistics.rs#L1485
I fixed …
=> Minor: clean up data page statistics tests and fix bugs

datafusion/physical-expr-common/src/aggregate/mod.rs, datafusion/physical-expr/src/aggregate/min_max.rs, datafusion/physical-plan/src/aggregates/mod.rs
Closes #11152 which I encountered when dealing with #10943
=> Replacing pattern matching through downcast with trait method

datafusion/optimizer/src/common_subexpr_eliminate.rs
Part of https://github.com/apache/datafusion/issues/11194.
Curently `CommonSubexprEliminate` always skips expressions that can short circuit, but that's not quite right as only the children of those expressions should be skipped.
I.e. from the plan:
```
Projection (a OR b) AS c1, (a OR b) AS c2
```
the expression `a OR b` can be extracted as common expression, but from the plan:
```
Projection (c OR (a + b)) AS c1, (d OR (a + b)) AS c2
```
the expression `a + b` can't be extracted.
Changes the rule to handle short circuiting expressions better. As `VisitRecord::JumpMark` is no longer needed this PR removes it.
Yes, added new UT.
No.
=> Enhance short circuit handling in `CommonSubexprEliminate`

datafusion/expr/src/expr_rewriter/mod.rs, datafusion/expr/src/expr_schema.rs, datafusion/expr/src/lib.rs, datafusion/expr/src/logical_plan/builder.rs, datafusion/expr/src/logical_plan/plan.rs, datafusion/expr/src/type_coercion/binary.rs, datafusion/expr/src/type_coercion/functions.rs, datafusion/expr/src/udaf.rs, datafusion/expr/src/udf.rs, datafusion/expr/src/udwf.rs, datafusion/expr/src/utils.rs
part of https://github.com/apache/datafusion/issues/11143.
=> Enable `clone_on_ref_ptr` clippy lint on expr crate

datafusion/substrait/src/logical_plan/consumer.rs, datafusion/substrait/tests/cases/consumer_integration.rs, datafusion/substrait/tests/testdata/tpch/nation.csv, datafusion/substrait/tests/testdata/tpch/part.csv, datafusion/substrait/tests/testdata/tpch/partsupp.csv, datafusion/substrait/tests/testdata/tpch/region.csv, datafusion/substrait/tests/testdata/tpch/supplier.csv, datafusion/substrait/tests/testdata/tpch_substrait_plans/query_2.json
=> Implement TPCH substrait integration teset, support tpch_2

datafusion/expr/src/expr_schema.rs
N/A
The follwoing overlong string literal prevents rustfmt from formatting the match arm in that function.
https://github.com/apache/datafusion/blob/6e637488188c6620ecd113bf47987bd98f6d7871/datafusion/expr/src/expr_schema.rs#L240
Related to https://github.com/rust-lang/rustfmt/issues/3863
Use multiple lines to replace the overly long string literal and make `cargo fmt` work.
Even though we can use the [format_strings](https://rust-lang.github.io/rustfmt/?version=v1.6.0&search=#format_strings) option to do this automatically,  it is unstable, and most IDEs do not enable it by default.
Yes
No
=> minor: format `Expr::get_type()`

datafusion/expr/src/utils.rs, datafusion/physical-plan/src/joins/hash_join.rs, datafusion/sqllogictest/test_files/joins.slt
Does some follow up to #10749 and it PR #11117 and follow up #11149.
Closes #11233
In #11117 hash join was extended to handled nested types. The fixed contained a small issues around handling of `null_equals_null` where it only used the new compare function when `null_equals_null` was true. But it also used the `Operator::Eq` which does not consider nulls equal.
This address the 2 described issues. Makes hash join also support nested types when `null_equals_null` is false and use the correct `Operator` when it is true.
New test cases.
Yes, it fixes bugs in unreleased features.
=> Fix hash join for nested types

datafusion/core/tests/dataframe/mod.rs, datafusion/expr/src/expr_schema.rs, datafusion/optimizer/src/analyzer/count_wildcard_rule.rs, datafusion/optimizer/src/single_distinct_to_groupby.rs, datafusion/optimizer/tests/optimizer_integration.rs
`count([DISTINCT [expr]])` aggregate function never returns null. Infer non-nullness of such aggregate expression. This allows elimination of the HAVING filter for a query such as
SELECT ... count(*) AS c
FROM ...
GROUP BY ...
HAVING c IS NOT NULL
=> Infer count() aggregation is not null

docs/source/user-guide/sql/aggregate_functions.md
The count aggregate was documented to count null values, but it does not do that. The implemented behavior is correct, so let's fix docs.
=> Fix count() docs around including null values

ci/scripts/rust_example.sh, datafusion-examples/README.md
Some examples are runnable from any place (e.g. `csv_sql`), but some expect a specific working directory (e.g. `regexp`). Running from `datafusion-examples/examples` is tested on CI so guaranteed to work, let's put this path in the README.
As a follow-up, we should look what it would take to make examples runnable directly from an IDE such as RustRover.
=> Fix running examples readme

datafusion/core/tests/fuzz_cases/sort_preserving_repartition_fuzz.rs, datafusion/physical-expr/src/equivalence/class.rs, datafusion/physical-expr/src/equivalence/mod.rs, datafusion/physical-expr/src/equivalence/ordering.rs, datafusion/physical-expr/src/equivalence/properties.rs, datafusion/physical-plan/src/filter.rs, datafusion/physical-plan/src/union.rs, datafusion/physical-plan/src/windows/mod.rs
Follow on to https://github.com/apache/datafusion/pull/11240
Some of the code manipulating `ConstExpr` was getting unweidly especially after `Arc::clone` is required
1. Add `ConstExpr::from(..)` to make creating `ConstExpr` more concise
2. Add some doc examples
2. Update code to use the new API
Existing CI
=> Minor: Add  `ConstExpr::from` and use in physical optimizer

datafusion/substrait/tests/cases/consumer_integration.rs, datafusion/substrait/tests/testdata/tpch/customer.csv, datafusion/substrait/tests/testdata/tpch/orders.csv, datafusion/substrait/tests/testdata/tpch_substrait_plans/query_3.json
=> Implement TPCH substrait integration teset, support tpch_3

Cargo.toml, datafusion-cli/Cargo.lock, datafusion-cli/Cargo.toml, datafusion/expr/src/type_coercion/binary.rs, datafusion/expr/src/type_coercion/functions.rs, datafusion/functions/src/datetime/date_bin.rs
closes https://github.com/apache/datafusion/pull/11202
https://crates.io/crates/arrow/52.1.0 was released an hour ago and causes clippy to start failing
Example CI failure: https://github.com/apache/datafusion/actions/runs/9818545016/job/27111235864?pr=11290
```
error: using `clone` on type `TimeUnit` which implements the `Copy` trait
--> datafusion/expr/src/type_coercion/binary.rs:1079:21
|
1079 |                     l.clone()
|                     ^^^^^^^^^ help: try dereferencing it: `*l`
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#clone_on_copy
= note: `-D clippy::clone-on-copy` implied by `-D warnings`
= help: to override `-D warnings` add `#[allow(clippy::clone_on_copy)]`
```
Update to the arrow 52.1.0 release, and fix clippy …
=> Upgrade to arrow 52.1.0 (and fix clippy issues on main)

datafusion/physical-expr-common/src/expressions/cast.rs, datafusion/sqllogictest/test_files/cast.slt
=> use safe cast in propagate_constraints

datafusion/optimizer/src/eliminate_nested_union.rs, datafusion/optimizer/src/eliminate_outer_join.rs, datafusion/optimizer/src/propagate_empty_relation.rs
Part of #4628 and #9637 
Closes #.
There are still clones left to be removed
=> Minor: Remove clone in optimizer

datafusion/physical-expr-common/src/sort_expr.rs, datafusion/physical-expr-common/src/utils.rs
N/A
I am working on some perf tests where I manually construct physical plans and noticed that in most cases we can use `new` or `try_new` for creating physical expressions, but this was not possible for `PhysicalSortExpr`.
- Add a constructor
- Update call sites in the same crate to use the new constructor
I did not think that it would be a good use of my time to update the other 291 cases where we create this struct.
=> minor: Add `PhysicalSortExpr::new`

datafusion/core/src/datasource/physical_plan/parquet/statistics.rs, datafusion/core/tests/parquet/arrow_statistics.rs
Closes #11280.
When all rows for a data page are null the min and max statistics should be present but null. Some of the data page statistics iterators were incorrectly omitting statistics rather than setting them to null. This results in an array whose length is different from the number of data pages. 
Adds test for data page statistics for all data types when all rows in a data page are null. Fixes data page statistics iterators that fail these tests. 
Yes.
No.
=> Fix data page statistics when all rows are null in a data page

datafusion/core/benches/parquet_statistic.rs, datafusion/core/src/datasource/physical_plan/parquet/statistics.rs
Closes #11281 
Improve the stats convert performance as possible.
- Use string builder directly to eliminate some tmp `Vec`s and `String`s(for example, Utf8 and LargeUtf case in both row group or page stats).
- Eliminate some unnecessary collect to avoid tmp `Vec` creation
Test by exist tests.
No
=> Improve stats convert performance for Binary/String/Boolean arrays

datafusion/core/benches/sql_planner.rs
Closes #11322.
We need to generate at least one partition to have a valid plan that conforms to distribution requirements.
For MemoryExec used in tpc-ds tests, empty partition is changed as one partition.
=> Minor: Fix Failing TPC-DS Test

datafusion/physical-plan/src/joins/hash_join.rs, datafusion/physical-plan/src/joins/nested_loop_join.rs, datafusion/physical-plan/src/joins/utils.rs, datafusion/sqllogictest/test_files/joins.slt
Closes #.
HashJoins can preserve the order of the right input when the join type is right.
`HashJoin` and `NestedLoopJoin` uses `append_right_indices()` method to combine matched and unmatched right results. This method simply appends the unmatched ones on matched ones. However, if we know that right is ordered, we can merge these indices in order to preserve order.
Yes, with an .slt test. Added test would result as:
| 1 | 1 | 3 | 1 |
| --- | --- | --- | --- |
| NULL | NULL | 1 | 0 |
before, which breaks the order.
=> HashJoin can preserve the right ordering when join type is Right

datafusion/sql/src/unparser/expr.rs
Closes #11325
Convert Arrow timestamp to `ast::DateTime::Timestamp` instead of failing. This allows the next steps to produce cast statements and successfully complete unparsing.
Added unit tests, also tested manually.
=> Support to uparse logical plans with timestamp cast to string

datafusion/common/src/scalar/mod.rs, datafusion/core/tests/dataframe/mod.rs, datafusion/physical-expr/src/expressions/is_not_null.rs, datafusion/physical-expr/src/expressions/is_null.rs
Closes #11162, replaces #11314
See #11162.
* Changes to `is_null` to support correctly support unions
* Changes to `is_not_null` to support correctly support unions
* change to `ScalarValue::is_null`
* tests
Yes
Should just be the intended fix.
=> Support `IS NULL` and `IS NOT NULL` on Unions

datafusion/substrait/src/logical_plan/consumer.rs, datafusion/substrait/tests/cases/roundtrip_logical_plan.rs
Related to https://github.com/apache/datafusion/issues/10815, and follows up from https://github.com/apache/datafusion/pull/11049#issuecomment-2185795038. There may still be some cases left uncovered, but this does handle some more.
Closes #.
As DF requires column name uniqueness while Substrait doesn't care about names at all (apart from first & last levels of the plan), that causes clashes in the intermediate nodes that prevent DF from executing plans. 
A simple example of a plan that would not work is:
```
SELECT a + 1 as sum_a, a + 1 as sum_a_2 FROM data
```
This fails as Substrait consumer first creates a project to add the columns, and only then creates the final project (or modifies the existing project) to rename them. But when the first project is created, it has two identical …
=> fix: When consuming Substrait, temporarily rename clashing duplicate columns

datafusion/core/tests/user_defined/user_defined_sql_planner.rs, datafusion/expr/src/logical_plan/plan.rs
fix #11306.
See https://github.com/datafusion-contrib/datafusion-functions-json/pull/26 and #11306
Remove the block on aliases as prediates, add test.
Yes, the only way I could get a failure without this change.
AFAIK, we just allow something that should be allowed.
**NOTE:** Aliases were already allowed in binary expressions, just not as full predicates, so this restriction seemed unusually strict. Also the SQL parser wouldn't allow me to build such an expression directly in SQL, e.g. `from x where (y = z) as the_alias` was invalid SQL.
=> Remove any aliases in `Filter::try_new` rather than erroring

datafusion/core/src/lib.rs, docs/source/user-guide/dataframe.md
Part of #3058 
While responding to comments from @efredine on https://github.com/apache/datafusion/pull/11290, I noticed some other ways the `DataFrame`  docs could be improved
Specifically this page: https://datafusion.apache.org/user-guide/dataframe.html
Among other things, the examples are incomplete (and they are not run in CO) and the documentation of methods is also incomplete
1. Run the examples as part of the doctests
2. Remove the duplicate API documentation, and instead point people at the API docs
2. Add a link to the library user guide docs on https://datafusion.apache.org/library-user-guide/using-the-dataframe-api.html  (improved in https://github.com/apache/datafusion/pull/11290)
The examples are now tested as part of CI, 
I also built the docs locally and I think they look …
=> Improve `DataFrame` Users Guide

datafusion/core/src/execution/context/mod.rs, datafusion/core/src/execution/session_state.rs, datafusion/core/tests/user_defined/expr_planner.rs, datafusion/core/tests/user_defined/mod.rs, datafusion/core/tests/user_defined/user_defined_scalar_functions.rs, datafusion/execution/src/task.rs, datafusion/expr/src/planner.rs, datafusion/expr/src/registry.rs, datafusion/functions-array/src/planner.rs, datafusion/functions/src/core/planner.rs, datafusion/functions/src/planner.rs, datafusion/proto/src/bytes/mod.rs, datafusion/proto/src/bytes/registry.rs, datafusion/sql/src/planner.rs
Closes https://github.com/apache/datafusion/issues/11304
=> chore: Rename UserDefinedSQLPlanner to ExprPlanner

datafusion/core/src/physical_optimizer/pruning.rs, datafusion/expr/src/operator.rs, datafusion/expr/src/type_coercion/binary.rs, datafusion/expr/src/utils.rs, datafusion/optimizer/src/analyzer/type_coercion.rs, datafusion/optimizer/src/simplify_expressions/utils.rs, datafusion/optimizer/src/utils.rs, datafusion/physical-expr-common/src/datum.rs, datafusion/physical-expr/src/expressions/binary.rs, datafusion/physical-expr/src/intervals/cp_solver.rs, datafusion/physical-expr/src/intervals/utils.rs, datafusion/physical-expr/src/planner.rs, datafusion/physical-expr/src/utils/mod.rs, datafusion/physical-plan/src/joins/hash_join.rs, datafusion/proto/src/logical_plan/from_proto.rs, datafusion/substrait/src/logical_plan/consumer.rs, datafusion/substrait/src/logical_plan/producer.rs
This reverts commit b468ba788310d5dcd6ea4549f0d5b0f215ea49c9.
We originally made this change in https://github.com/apache/datafusion/pull/11132 as we thought it was necessary for user defined sql extensions (https://github.com/apache/datafusion/issues/11207) but we eventually went with a different approach (specifically https://github.com/apache/datafusion/pull/11180 from @jayzhan211 )
Thus I think this change is unnecessary and since it is a breaking API change it will cause unnecessary issues on upgrade for users.
Let's revert it
This reverts commit b468ba788310d5dcd6ea4549f0d5b0f215ea49c9 / https://github.com/apache/datafusion/pull/11132 
Yes, by CI / clippy
Revert what I think is an uncessary API change
cc @samuelcolvin  and @andygrove
=> Revert "remove `derive(Copy)` from `Operator` (#11132)"

datafusion/expr/src/expr_schema.rs, datafusion/expr/src/logical_plan/plan.rs, datafusion/physical-plan/src/filter.rs, datafusion/sqllogictest/test_files/misc.slt
=> Support `NULL` literals in where clause 

docs/source/index.rst
Part of #9602 
If we are going to have a blog we should make it easier for people to find it
Add a link to the blog from the website:
I tested this manually locally
=> Minor: Add link to blog to main DataFusion website

datafusion/core/src/physical_optimizer/projection_pushdown.rs, datafusion/sqllogictest/test_files/join.slt
Closes #11269.
Closes #11275.
The bug occurs at the [`new_indices_for_join_filter`](https://github.com/apache/datafusion/blob/f5e114e4f754c81d332f5105dd0242ab13f29a51/datafusion/core/src/physical_optimizer/projection_pushdown.rs#L1219) function within the `ProjectionPushdown` rule.
It uses the column name to search for the join filter's columns from `projection_exprs`.
https://github.com/apache/datafusion/blob/f5e114e4f754c81d332f5105dd0242ab13f29a51/datafusion/core/src/physical_optimizer/projection_pushdown.rs#L1218-L1220
The problem is that different columns may have the same names, leading to incorrect column matching and generating erroneous physical plans.
Use column index for matching.
Yes
No
=> Fix bug when pushing projection under joins

datafusion/physical-plan/src/filter.rs
=> Minor: some cosmetics in `filter.rs`, fix clippy due to logical conflict

datafusion/physical-expr/src/equivalence/properties.rs, datafusion/physical-plan/src/filter.rs
Closes #11362.
This PR fixes a regression in #10434. The previous PR implements "discovery" of new orderings when equal conditions are added. However, this discovery process is not carried out when constants are added. 
As a result, adding equality conditions tends to leave the properties in a normalized state, but adding constants does _not_ leave the properties in a normalized state. Thus the order in which one constructs the properties matters. 
Since the existing test for this feature applied equal conditions _after_ adding constants, this path dependence was not caught. 
We extract out the "discovery" logic into a helper method, and we ensure it is called not only when adding equal conditions, but also when adding constants. 
Yes; we modify the test to construct the equivalence …
=> fix: Fix eq properties regression from #10434

datafusion/common/src/error.rs, datafusion/execution/src/disk_manager.rs, datafusion/execution/src/memory_pool/pool.rs
Closes #.
Related to https://github.com/apache/datafusion/issues/7360
Expand error macros series in DataFusion to include a `ResourcesExhausted` error
=> Introduce `resources_err!` error macro

datafusion/core/src/datasource/file_format/parquet.rs, datafusion/core/src/test_util/mod.rs, datafusion/core/tests/memory_limit/mod.rs
Closes #11344 
ParquetSink can use non-trivial amounts of memory to buffer rowgroups prior to flush, when executed within a task context. Therefore, this memory usage should be accounted within the task's memory pool.
Ensure memory accounting under three use cases for ParquetSink:
* when non-parallel writes
* when using multiple row-writers
* when using multiple column-writers
How parallelized-write memory tracking works, is [summarized here](https://github.com/apache/datafusion/pull/11345#discussion_r1669599846). I feel like it should be a doc comment, but I wasn't sure where. 🤔 
Yes
No
=> Track parquet writer encoding memory usage on MemoryPool

datafusion/core/src/execution/session_state.rs, datafusion/core/tests/sql/sql_api.rs
Closes #11393 .
This is a much clearer error message than previously existed in its place. 
This changes the error message and adds two tests: one to cover this exact use case (of no statements being provided) and another to cover the instance of multiple statements being provided (which returns an error right before the check to see if any statements were provided at all), since there were no tests for that error case.
Yes, running `cargo test` in the root of the repo produces no failures.
I think this qualifies as a user-facing change, but I don't think it violates any invariants or changes any use-cases (or anything like that) in a way that would require any documentation changes. I may be wrong, though - clarification on if this qualifies as a 'user-facing change' would be …
=> Minor: Change no-statement error message to be clearer

datafusion/substrait/tests/cases/consumer_integration.rs
Fixes my comment https://github.com/apache/datafusion/pull/11311#discussion_r1668128566 around reusing a function to create the context
Less lines of code
In Substrait TPCH consumer tests, reuse a single function to create context and keep table lists together with the test cases.
Existing tests
No
=> chore: reuse a single function to create the Substrait TPCH consumer test contexts

datafusion/core/src/execution/session_state.rs, datafusion/core/tests/sql/sql_api.rs
Amends #11394 (sorry, I should have reviewed that).
While reporting "not implemented" for "multiple statements" seems reasonable, I think the user should get a plan error (which roughly translates to "invalid argument") if they don't provide any statement. I don't see any reasonable way to support "no statement" ever, hence "not implemented" seems like a wrong promise.
The user now gets a plan error instead of "no implemented" if no statement was provided.
Adjusted existing test.
Improved error type. Esp. if the user converts that error type into a gRPG/HTTP error (e.g. IOx does this) then you can expect a more appropriate outcome.
=> refactor: change error type for "no statement"

datafusion-examples/examples/parse_sql_expr.rs, datafusion-examples/examples/plan_to_sql.rs, datafusion/core/tests/expr_api/parse_sql_expr.rs, datafusion/expr/src/operator.rs, datafusion/sql/src/unparser/expr.rs, datafusion/sql/src/unparser/mod.rs, datafusion/sql/tests/cases/plan_to_sql.rs
Takes a shot at #10633 .
Algorithm adapted from [this](https://stackoverflow.com/a/18403396/16516114) SO answer.
Make unparsed binary expressions easier to read.
Yes, but can use more tests/statements/plans to unparse.
New `.with_pretty()` method for the unparser to remove extra parenthesis from an expr.
=> Implement prettier SQL unparsing (more human readable)

docs/source/user-guide/sql/scalar_functions.md
Follow-up PR for https://github.com/apache/datafusion/pull/11347#issuecomment-2220519822
Relates to https://github.com/apache/datafusion/issues/10602, https://github.com/apache/datafusion/issues/11358
A scalar UDF `to_local_time()` was added in https://github.com/apache/datafusion/pull/11347. This PR documents `to_local_time()` in the scalar function reference page. 
After adding the document for `to_local_time()`, the doc page will look like this:
No. Only adding documents, so it shouldn't break anything.
No
=> Add `to_local_time()` in function reference docs

datafusion/expr/src/planner.rs, datafusion/functions/src/core/planner.rs, datafusion/functions/src/string/mod.rs, datafusion/sql/src/expr/mod.rs
Closes #11223
Part of #11207
Existing test cases
```
cargo test
```
No
=> Move `overlay` planning to`ExprPlanner`

datafusion/optimizer/src/eliminate_nested_union.rs, datafusion/sqllogictest/test_files/union.slt
Closes #11385.
Investigating the above issue led me to identify a couple of aspects that need to align in order for the bug to manifest:
- there's a (grouping) aggregation
- of a >2 way union
- with some type coercion
In particular here's a minimal repro of the above issue
```sql
> select c1, sum(c2) as sum_c2
from (select 1 as c1, 1::int as c2
union
select 2 as c1, 2::int as c2
union
select 3 as c1, coalesce(3::int, 0) as c2)
group by c1;
External error: External error: External error: Arrow error: Invalid argument error: RowConverter column schema mismatch, expected Int32 got Int64
```
What happens is that the nested union elimination unwraps the first two child plans and coerces their schema, however the remaining plan isn't being coerced. Upon physical planning Union inherits the …
=> Coerce types for all union children plans when eliminating nesting

datafusion/core/tests/user_defined/user_defined_aggregates.rs, datafusion/core/tests/user_defined/user_defined_scalar_functions.rs, datafusion/expr/src/udaf.rs, datafusion/expr/src/udf.rs, datafusion/expr/src/udwf.rs
Closes #127.
After #9436 it's possible to write and use all kinds of custom UDF functions e.g. parameterized by additional arguments, but the issue is that equality and hash code are based only on the name and signature. As such some plan rewrites that put expressions in a hash set (e.g. `FilterPushDown`) violate this assumption and we end up with semantically incorrect rewrites.
Added `equals` and `hash_value` methods to scalar, aggregate and window UDFs. By default they delegate to the name and signature as before but custom UDFs can override them to account for additional parameters. Unfortunately we can't extend the `Eq` and `Hash` traits because they prevent us from using trait objects.
Yes, added unit tests.
Yes, the UDF interfaces grow with two new functions.
=> Add customizable equality and hash functions to UDFs

datafusion/expr/src/expr.rs, datafusion/optimizer/src/common_subexpr_eliminate.rs, datafusion/optimizer/src/optimize_projections/mod.rs, datafusion/sqllogictest/test_files/cse.slt, datafusion/sqllogictest/test_files/select.slt, datafusion/sqllogictest/test_files/tpch/q14.slt.part
Part of https://github.com/apache/datafusion/issues/11194.
Currently `CommonSubexprEliminate` doesn't recurse into short-circuit expression and misses extracing common expressions from surely evaluated legs. I.e. from the plan:
```
Projection (a + 1 OR b) AS c1, (a + 1 AND b) AS c2
```
the expression `a + 1` is not extracted despite the fact that it is evaluated 2 times.
Also, it would make sense to extract such expressions that are surely evalueted only once but there is a chance that they are evaluated conditionally as well. I.e. from the plan:
```
Projection (a + 1 OR b) AS c1, (b AND a + 1) AS c2
```
it would make sense to extract `a + 1`.
This PR:
- Extends `ExprStats` with conditional evaluation counts.
- Enhances `ExprIdentifierVisitor` to recurse into children of short-circuit …
=> Improve `CommonSubexprEliminate` rule with surely and conditionally evaluated stats

datafusion/core/src/datasource/file_format/parquet.rs, datafusion/core/tests/memory_limit/mod.rs
Closes #11397 
During the parallel writes in ParquetSink, we spawn a series of parallel tasks and then message pass the outcome from one task to the next. In abstraction:
read_batches => channel => `Vec<col_write_tasks>` => channel => `Vec<serialize_rowgroup_tasks>`
When we encounter an error in one of the `Vec<x_tasks>` we are first surfacing an error on the channel.send() rather than on the task join.
Don't surface the errors on the channel send.
This results in the proper error returned, as can be seen on the updated test.
Yes.
No.
=> fix(11397): surface proper errors in ParquetSink

datafusion/common/src/file_options/csv_writer.rs
Closes https://github.com/apache/datafusion/issues/8640
Just uses the already-existing config field to pass into the respective builder method from arrow-rs
I'm not actually adding any tests here for the csv writing itself, since I've added some in https://github.com/apache/arrow-rs/pull/5890 and we're just passing the value through
No. (Well, in some sense, this fixes a sort-of bug as the config field existed but wasn't used here)
=> Trivial: use arrow csv writer's timestamp_tz_format

datafusion/sql/src/lib.rs, datafusion/sql/src/unparser/expr.rs, datafusion/sql/src/unparser/mod.rs, datafusion/sql/src/unparser/plan.rs
~Draft as it builds on https://github.com/apache/datafusion/pull/11186~
Follow on to https://github.com/apache/datafusion/pull/11186
While reviewing https://github.com/apache/datafusion/pull/11186 from @MohamedAbdeen21 I found some areas that the docs could be improved
Add module level / function level / struct level docstrings and examples
By CI doc tests
better docs
=> Improved unparser documentation

datafusion/core/src/datasource/file_format/write/orchestration.rs
in `serialize_rb_stream_to_object_store`
Avoid "`async fn` resumed after completion" panics caused by trying to shutdown an errored writer.
See e.g. `BufWriter` in `object_store` which holds on to an underlying `Future` and doesn't transition the state on error. (https://github.com/apache/arrow-rs/blob/master/object_store/src/buffered.rs#L376-L379)
I tried to figure out from the documentation of `AsyncWrite` whether we should be able to call `poll_shutdown` after `poll_write` failed but I didn't manage to figure it out so I think it's better to be defensive here.
We make the `WriterType` returned on error optional and omit it when the error originated from the writer itself.
No, not sure how to reproduce it outside of real-world conditions, let alone test it 😢 
No user-facing changes.
=> Avoid calling shutdown after failed write of AsyncWrite

datafusion/core/src/physical_optimizer/aggregate_statistics.rs
Part of  #11153 
Now only hard code like `if agg_expr.as_any().is::<expressions::Min>()` to identify the `min/max` aggregate function in `AggregateStatistics` optimizer. It can't work after `min/max` is converted to `udaf`.
This pr is for solving problem stated above. The best way to solve is adding a function like `output_from_stats` into `AggregateExpr` and moving the logic from the optimizer to `udaf`. But unfortunately it is not so easy to find good way to do that... 
For unblocking the `udaf` conversion about `min/max`, just impl a short term solution here.
Support to identify `min/max` after they are converted to `udaf` in later.
By exist tests.
No.
=> Short term way to make `AggregateStatistics` still work when min/max is converted to udaf

.github/workflows/dev_pr/labeler.yml
The automatic labeler job doesn't seem to work for documentation changes or development process
(for example, this PR modifies files in `.github` but is not automatically labeled)
Change labeler markdown syntax to be consistent
No, I didn't test them. I figure we can make another PR if this doesn't work
No, this should be a dev process only change
=> Minor: fix giuthub action labeler rules

datafusion/core/src/dataframe/mod.rs, datafusion/optimizer/src/analyzer/type_coercion.rs, datafusion/sql/src/relation/join.rs, datafusion/sqllogictest/test_files/join.slt
Closes #11414.
The query in the issue generates the following plan after some optimizations.
```sql
select * from t1 inner join t2 on null right join t3 on true;
```
```sh
Projection: t1.v1, t2.v1, t3.v1
Right Join:
Inner Join:
Filter: Boolean(true) AND NULL
TableScan: t1
TableScan: t2
TableScan: t3
```
When the `simplify_expressions` rule attempts to simplify `Boolean(true) AND NULL`,  it fails because the operand types on both sides are different (`DataType::Boolean` vs `DataType::NULL`).
The fix is to cast the NULL type to  Boolean type.
Yes
No
=> fix: make sure JOIN ON expression is boolean type

datafusion/physical-plan/Cargo.toml, datafusion/physical-plan/src/aggregates/topk/heap.rs
Closes #11389
Remove uses of termtree::tree in heap.rs. Directly generate the string instead.
=> remove termtree dependency

datafusion/substrait/tests/cases/consumer_integration.rs, datafusion/substrait/tests/testdata/tpch_substrait_plans/query_18.json, datafusion/substrait/tests/testdata/tpch_substrait_plans/query_19.json, datafusion/substrait/tests/testdata/tpch_substrait_plans/query_20.json, datafusion/substrait/tests/testdata/tpch_substrait_plans/query_21.json, datafusion/substrait/tests/testdata/tpch_substrait_plans/query_22.json
=> integrate consumer tests, implement tpch query 18 to 22

datafusion/physical-expr-common/src/aggregate/mod.rs
=> Docs: Explain the usage of logical expressions for `create_aggregate_expr`

datafusion/common/src/scalar/mod.rs, datafusion/functions/src/core/map.rs, datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs, datafusion/sqllogictest/test_files/map.slt
Closes #11460 #6485 
See #11460 
See title.
Test by new uts.
Can success to run sql like:
```sql
SELECT make_map('type', 'test') FROM test
```
=> Return scalar result when all inputs are constants in `map` and `make_map`

datafusion/functions/src/regex/regexpreplace.rs, datafusion/sqllogictest/test_files/regexp.slt
=> fix: `regexp_replace` fails when pattern or replacement is a scalar `NULL`

datafusion/physical-plan/src/repartition/mod.rs
Closes #.
Currently `repart_time` and `send_time` metrics for `RepartitionExec` may have significant overlap since timer for repart_time is binded to repartitioned batches iterator, (`partition_iter`) which is used for sending these batches.
This PR limits the time accounted by `repart_time` timer.
Repartition time now accounts only the time required to calculate input batch row indices distribution across output partitions and the time required to produce output batches.
Only manually.
No
=> minor: non-overlapping `repart_time` and `send_time` metrics

datafusion-examples/examples/plan_to_sql.rs, datafusion/sql/src/unparser/dialect.rs, datafusion/sql/src/unparser/expr.rs
This PR address more dialect variety in unparser:
- interval for standard and postgres style
- cast datetime as datetime or timestamp 
SQLStandard format interval is needed for dbms like dremio.
`datetime` is missing for certain dbms too: dremio, trino.
See "What issue does this PR close"
Yes, unit tests added
n/a. But changed one `CustomDialect::new` to be deprecated in favor of `CustomDialectBuilder`
=> Support alternate formats for unparsing `datetime` to `timestamp` and `interval`

datafusion/physical-expr/Cargo.toml, datafusion/physical-expr/benches/case_when.rs
N/A
I would like to see if it is possible to improve performance of CaseExpr in some cases and the first step is to add criterion benchmarks.
One idea for improving performance is https://github.com/apache/datafusion/issues/11484
New criterion benchmarks.
=> chore: Add criterion benchmark for CaseExpr

datafusion/sql/examples/sql.rs
Closes #.
Complete todo item in sql example.
=> Replace to_lowercase with to_string in sql example

datafusion/substrait/src/logical_plan/consumer.rs, datafusion/substrait/src/logical_plan/producer.rs
Closes #.
I'm looking at supporting date-time stuff properly through Substrait and DataFusion, part of that is introducing (🤞) a [MonthDayNano type into Substrait](https://github.com/substrait-io/substrait/issues/664). While looking into it, I noticed there already are types for YearMonth and DayTime, so we could (and should!) be using those types instead of the custom UDTs introduced in https://github.com/apache/datafusion/pull/10646 (cc @waynexia )
Add consuming support for IntervalYear and IntervalDay types as well as IntervalYearToMonth literals (IntervalDayToSecond already existed). Keep existing consuming support for the UDT for both for backwards compatibility (can probs remove this soon as well, but keeping it for now allows reading plans created by earlier version of DF, in case …
=> feat: switch to using proper Substrait types for IntervalYearMonth and IntervalDayTime

datafusion/substrait/src/logical_plan/consumer.rs, datafusion/substrait/tests/cases/roundtrip_logical_plan.rs
Closes #.
Previously Substrait consumer would, for window functions, look at:
1. UDAFs
2. built-in window functions
3. built-in aggregate functions
That makes it tough to override the built-in window function behavior, as it could only be overridden with a UDAF but some window functions don't fit nicely into aggregates.
This change adds UDWFs at the top, so the consumer will look at:
1. UDWFs
2. UDAFs
3. built-in window functions
4. built-in aggregate functions
This allows us to override any window function as well, and also paves the way for moving DF's built-in window funcs into UDWFs.
Added a unit test
=> feat: support UDWFs in Substrait

datafusion-examples/examples/composed_extension_codec.rs, datafusion/physical-expr-common/src/aggregate/mod.rs, datafusion/proto/proto/datafusion.proto, datafusion/proto/src/generated/pbjson.rs, datafusion/proto/src/generated/prost.rs, datafusion/proto/src/logical_plan/file_formats.rs, datafusion/proto/src/logical_plan/from_proto.rs, datafusion/proto/src/logical_plan/mod.rs, datafusion/proto/src/logical_plan/to_proto.rs, datafusion/proto/src/physical_plan/from_proto.rs, datafusion/proto/src/physical_plan/mod.rs, datafusion/proto/src/physical_plan/to_proto.rs, datafusion/proto/tests/cases/mod.rs, datafusion/proto/tests/cases/roundtrip_logical_plan.rs, datafusion/proto/tests/cases/roundtrip_physical_plan.rs
Closes #11422.
The rationale for this change is to be able to run parameterized aggregation UDFs in a distributed architecture.
E.g. one use case is implementing an `sample` UDF (akin to `array_agg` but with a limit on the number of elements collected).
* Extend the interface of `LogicalExtensionCodec` to handle aggregation UDFs and window UDFs.
* Extend the interface of `PhysicalExtensionCodec` to handle aggregation UDFs.
* I couldn't figure out physical window UDFs so those are omitted.
* Handle `ignore_nulls` and `distinct` flags better.
Yes, added roundtrip tests for encoding and decoding.
Yes, users can now override the new encoding and decoding functions.
=> Add extension hooks for encoding and decoding UDAFs and UDWFs

datafusion/core/tests/sql/aggregates.rs, datafusion/physical-expr/src/aggregate/array_agg.rs, datafusion/physical-expr/src/aggregate/array_agg_distinct.rs, datafusion/physical-expr/src/aggregate/array_agg_ordered.rs, datafusion/physical-expr/src/aggregate/build_in.rs, datafusion/physical-plan/src/aggregates/mod.rs
Closes #.
I think the nullability of element in array_agg_* function (in general UDAF, those elements whether null or non-null could be handled in function invoke logic itself) doesn't help much about optimization, but add complexity for the function itself. I propose to remove it until there is any use case that shows the nullability of element is really helpful.
The related change is from https://github.com/apache/datafusion/pull/8055, where introduce `nullable` but place it in a incorrect place. Then, #11093 where change the nullable from list to element. And this PR is going to cleanup nullable of element 😫
=> Remove element's nullability of array_agg function

datafusion/sql/src/unparser/dialect.rs, datafusion/sql/src/unparser/expr.rs
PR addresses Utf8 unparser issue producing invalid `CAST(col AS TEXT)` SQL for MySQL.
MySQL [cast function](https://dev.mysql.com/doc/refman/8.4/en/cast-functions.html#function_cast) does not support `TEXT` and requires `CHAR` for CAST (automatically returns VARCHAR, TEXT, LONGTEXT)
> CHAR[(N)] [charset_info]
> Produces a string with the [VARCHAR](https://dev.mysql.com/doc/refman/8.4/en/char.html) data type, unless the expression expr is empty (zero length), in which case the result type is CHAR(0). If the optional length N is given, CHAR(N) causes the cast to use no more than N characters of the argument. No padding occurs for values shorter than N characters. If the optional length N is not given, MySQL calculates the maximum length from the expression. If the supplied or calculated …
=> Support alternate format for Utf8 unparsing (CHAR)

datafusion/functions-aggregate/src/bit_and_or_xor.rs
Closes #7666.
Implements the `retract_batch()` method for the `BitwiseXorAccumulator` by calling the original `update_batch` function since XOR is its own inverse.
Added a unit test for retracting the batch.
No
=> implement retract_batch for xor accumulator

datafusion/common/src/file_options/parquet_writer.rs
Part of #11367 
This PR defines the current state.
When we switched from using the parquet's ArrowWriter (with [options](https://docs.rs/parquet/latest/parquet/arrow/arrow_writer/struct.ArrowWriterOptions.html)) to the parallelized parquet writer (with [it's own options](https://docs.rs/datafusion/latest/datafusion/datasource/file_format/parquet/struct.ParquetSink.html#method.parquet_options)), we ran into unintended behaviors due to different default settings. 
Here are the places where the current defaults differ:
| setting_name                 | applied        | default, datafusion (ParquetOptions) | default, parquet (ArrowWriterOptions) |
| ---------------------------- | -------------- | ------------------------------------ | ------------------------------------- |
| …
=> Add tests that show the different defaults for `ArrowWriter` and `TableParquetOptions` 

datafusion/common/src/error.rs
Closes #.
If the `test_enabled_backtrace` launched without `RUST_BACKTRACE=1` the test will fail with the reason which require some time to investigate.
Add proper error message if assertion doesn't satisfy prior to test run
=> Minor: Assert `test_enabled_backtrace` requirements to run

datafusion/core/tests/fuzz_cases/join_fuzz.rs
Closes https://github.com/apache/datafusion/issues/10872.
Fixed the fuzz test, previously the filter was not set up correctly
=> Enable SortMergeJoin LeftAnti filtered fuzz tests

datafusion/optimizer/src/push_down_filter.rs
=> Minor: Remove clone in `PushDownFilter`

datafusion/optimizer/src/analyzer/type_coercion.rs, datafusion/sqllogictest/test_files/misc.slt
Follow on to https://github.com/apache/datafusion/pull/11491 from  @xinlifoobar
While reviewing https://github.com/apache/datafusion/pull/11491  I found a way to remove the clone of predicate in the type coercion pass
1. Remove a clone
2. Add a test for the nice error message on non boolean predicates
yes
no
=> Minor: avoid a clone in type coercion

datafusion/common/src/cast.rs, datafusion/common/src/hash_utils.rs, datafusion/physical-expr/src/aggregate/min_max.rs
Note: targets `string-view2` branch
Let's wait until #11514 is merged
Part of https://github.com/apache/datafusion/issues/10918
Add a few helper functions to handle string views.
=> Add String view helper functions

datafusion/substrait/src/extensions.rs, datafusion/substrait/src/lib.rs, datafusion/substrait/src/logical_plan/consumer.rs, datafusion/substrait/src/logical_plan/producer.rs, datafusion/substrait/src/variation_const.rs, datafusion/substrait/tests/cases/roundtrip_logical_plan.rs
Closes #.
https://github.com/apache/datafusion/pull/10646 introduced Substrait UDTs for interval types. However as that PR didn't yet write proper Substrait extensions for those types, it's hard to produce matching UDTs from other Substrait producers. Until https://github.com/substrait-io/substrait/pull/665 gets merged and passed through to Java & DataFusion, I'd need a UDT to represent Spark's CalendarInterval / DF's IntervalMonthDayNano. 
Produce and consume SimpleExtensionDeclarations for types in addition to functions. This makes user-defined types interoperable across different consumers/producers, assuming they utilize matching names for the same UDT.
Also adds most of the support for doing it for type variations, but doesn't use that yet.
Similarly as for the existing support for …
=> feat: consume and produce Substrait type extensions

datafusion/sql/src/unparser/dialect.rs
This makes unparser trait `Dialect` easier to work within DataFusion context for federated queries (datafusion-federation).
In federated query context, that could be use cases that a dialect needs to be specified for table providers targeting protocol like flight, odbc because the underlying DBMS may have different sql dialect. Without Send + Sync, it can be tricky to pass the config of dialect down into table provider scan/execute method, etc. 
In current design, the dialect is mostly an empty struct so it's safe to change so. The alternative is to pass a `fn` which create a `Arc<dyn Dialect>` around which doesn't look great.
Thoughts?
Make Unparser Dialect to be Send + Sync
n/a. I don't think it needs one.
n/a
=> make unparser `Dialect` trait `Send` + `Sync`

datafusion/sql/src/unparser/plan.rs, datafusion/sql/tests/cases/plan_to_sql.rs
Unparser creates invalid sqls for LogicPlan that generated from sql with derived table with columns.
See "Which issue does this PR close", also check below comment.
Copy/pasted from the code comments.
```
// A roundtrip example for table alias with columns
//
// query: SELECT id FROM (SELECT j1_id from j1) AS c (id)
//
// LogicPlan:
// Projection: c.id
//   SubqueryAlias: c
//     Projection: j1.j1_id AS id
//       Projection: j1.j1_id
//         TableScan: j1
//
// Before introducing this logic, the unparsed query would be `SELECT c.id FROM (SELECT j1.j1_id AS
// id FROM (SELECT j1.j1_id FROM j1)) AS c`.
// The query is invalid as `j1.j1_id` is not a valid identifier in the derived table
// `(SELECT j1.j1_id FROM j1)`
```
Introduce a method that probe the SubqueryAlias plan to see if it …
=> fix: unparser generates wrong sql for derived table with columns

.github/workflows/large_files.yml
See https://github.com/apache/datafusion/issues/10422 for rationale.
=> Prevent bigger files from being checked in

datafusion/physical-expr/src/expressions/column.rs, datafusion/physical-plan/src/union.rs, datafusion/sqllogictest/test_files/union.slt
Closes #11409.
~~After certain optimizations such as `ProjectionPushdown`, the children of `InterleaveExec` can no longer meet the interleave [condition](https://github.com/apache/datafusion/blob/b19744968770c4ab426d065dec3cc5147534e87a/datafusion/physical-plan/src/union.rs#L363) because their output_partitioning becomes inconsistent.~~
~~Perhaps in this situation,  we could consider falling back to `UnionExec` from `InterleaveExec` instead of throwing an error.~~
We determine that union inputs can interleave when they have the same hash partition spec.
https://github.com/apache/datafusion/blob/12d82c427d6c37f7884a508707ccd3058a446908/datafusion/physical-plan/src/union.rs#L499
But this may be incorrect if the expressions in the partition spec contain …
=> fix: make `UnKnownColumn`s not equal to others physical exprs

datafusion/core/src/datasource/listing/table.rs, datafusion/core/src/datasource/schema_adapter.rs, datafusion/core/src/execution/mod.rs, datafusion/core/src/execution/session_state.rs, datafusion/core/src/execution/session_state_defaults.rs
Part of https://github.com/apache/datafusion/issues/11420
We are slowly moving towards separating the dependency of SessionState from the datafusion core crate. To do so we need to eventually remove the dependency of SessionState on the core crate. 
@Omega359  separated the defaults from `SessionState` in #11403.  `SessionStateDefaults` has many of those dependencies on the core
This PR moves the `SessionStateDefaults` struct, which depend very much on things in th core, into its own module which gets us slightly closer to being able to move the defaults out of session state.
Existing CI
No (this code is not part of any release yet)
=> Minor: move `SessionStateDefaults` into its own module

datafusion/common/src/scalar/mod.rs, datafusion/sqllogictest/test_files/scalar.slt
Closes #11552
The `assert!(datatype.is_primitive());` is getting hit in `new_negative_one`, but as far as I can tell isn't needed. There's a match statement right below that handles the datatype.
Without the assert these functions seem to work properly. That said, I'm a little confused why it's working exactly. The datatypes coming through are `Datatype::Null` which caused the assertion error but seemingly isn't causing errors in the match statement.
I'm also working on a branch https://github.com/apache/datafusion/compare/main...tshauck:arrow-datafusion:add-unary-udf-bounds?expand=1 that I think is a more complete way to solve this problem because currently unary functions don't report their bounds which I think is what ordering relies on to get its data type and means nested trig …
=> fix: fixes trig function order by

datafusion/core/src/datasource/file_format/write/orchestration.rs
Closes #11443 .
The return type was getting complex
Introduces a new type called `SerializedRecordBatchResult`, it has the same structure as the issue proposed, I tried others but this one i liked the most.
No, I don't think i can test a type signature change
No, I don't think is changes the public API
=> refactor: rewrite mega type to an enum containing both cases

datafusion/core/tests/memory_limit/mod.rs, datafusion/execution/src/memory_pool/mod.rs, datafusion/physical-plan/src/joins/sort_merge_join.rs, datafusion/physical-plan/src/sorts/sort.rs, datafusion/physical-plan/src/spill.rs
=> Support SortMergeJoin spilling

datafusion/functions/src/regex/regexpreplace.rs
(targets string-view2 branch)
part of  #11025
Implement very limited support for `regex_replace` on `StringViewArray.`
It is the minimal implementation to run ClickBench queries. I believe fully support `StringView` requires a bit discussion and much more work. This PR should help us understand the remaining work.
=> Initial support for regex_replace on `StringViewArray`

datafusion/expr/src/expr_schema.rs, datafusion/functions-aggregate/src/sum.rs, datafusion/sqllogictest/test_files/aggregate.slt, datafusion/sqllogictest/test_files/scalar.slt, datafusion/sqllogictest/test_files/select.slt
=> fix: CASE with NULL

datafusion-cli/Cargo.lock, datafusion/core/src/physical_optimizer/enforce_distribution.rs, datafusion/core/src/physical_optimizer/mod.rs, datafusion/physical-optimizer/Cargo.toml, datafusion/physical-optimizer/src/lib.rs, datafusion/physical-optimizer/src/output_requirements.rs
=> Move OutputRequirements to datafusion-physical-optimizer crate

datafusion/physical-expr/src/expressions/case.rs, datafusion/sqllogictest/test_files/case.slt
N/A
```
case_when: scalar or scalar
time:   [5.6794 µs 5.7119 µs 5.7566 µs]
change: [-70.724% -70.393% -70.042%] (p = 0.00 < 0.05)
```
Add a fast path for a specific usage of CASE expression
- Existing tests
- Added slt tests
=> feat: Optimize CASE expression for usage where then and else values are literals

datafusion/physical-plan/src/joins/sort_merge_join.rs
Closes #11555 .
Add a additional check to avoid issues in when multiple partitions gets processed concurrently
=> Fix SortMergeJoin antijoin flaky condition

datafusion/proto-common/proto/datafusion_common.proto, datafusion/proto-common/src/from_proto/mod.rs, datafusion/proto-common/src/generated/pbjson.rs, datafusion/proto-common/src/generated/prost.rs, datafusion/proto-common/src/to_proto/mod.rs, datafusion/proto/src/generated/datafusion_proto_common.rs, datafusion/proto/tests/cases/roundtrip_logical_plan.rs
Closes #11607.
Fixes a simple omission.
Added support for the Decimal256 type in datafusion-proto.
There is a unit test. Manual testing of the affected use case was also successful.
This bug was reproducible by users.
=> support Decimal256 type in datafusion-proto

datafusion/common/src/hash_utils.rs, datafusion/common/src/scalar/mod.rs, datafusion/sqllogictest/test_files/map.slt, datafusion/substrait/src/logical_plan/consumer.rs, datafusion/substrait/src/logical_plan/producer.rs, datafusion/substrait/tests/cases/roundtrip_logical_plan.rs
Related to Map epic https://github.com/apache/datafusion/issues/11434
Substrait didn't support Map literals, since we previously didn't have Map ScalarValues. https://github.com/apache/datafusion/pull/11224 implemented ScalarValues (thanks!), so now we can add them into Substrait as well. 
There were also couple gaps left by the implementation that I encountered while testing this, so I fixed those as well.
Also, there was a bug in the from_substrait_literal for lists containing structs, which I realized while implementing the map support.
- Implement Substrait roundtrip support for Map literals, incl. null and empty maps.
- Fix field name handling for Substrait lists containing structs
- Add Map support to `ScalarValue::iter_to_array` and `create_hashes`
Tested with new roundtrip tests …
=> feat: support Map literals in Substrait consumer and producer

datafusion/core/src/datasource/file_format/csv.rs
Closes #11574.
fix failure running of case test_csv_parallel_one_col on windows machine
getting `file_size` according to func `metadata` instead of `target_os`
yes
no
=> test: get file size by func metadata

datafusion/sql/src/unparser/dialect.rs, datafusion/sql/src/unparser/expr.rs
Please let me know if you prefer me to split this into separate PRs. Combined as the changes are related/follow the same logic and to avoid resolving conflicts after PRs are merged.
PR addresses unparser issues producing invalid sql for MySQL and implements support for `IntervalStyle::MySQL`
MySQL [cast function](https://dev.mysql.com/doc/refman/8.4/en/cast-functions.html#function_cast) does not support Timestamp for CAST and requires DATETIME
> DATETIME[(M)]
Produces a [DATETIME](https://dev.mysql.com/doc/refman/8.4/en/datetime.html) value. If the optional M value is given, it specifies the fractional seconds precision.
Timezone information is correctly handled by MySQL when casting with `DATETIME`.
MySQL does not support **date_part** function so PR introduces configurable option to …
=> Improve unparser MySQL compatibility

datafusion-examples/examples/custom_file_format.rs, datafusion/core/src/datasource/file_format/arrow.rs, datafusion/core/src/datasource/file_format/avro.rs, datafusion/core/src/datasource/file_format/csv.rs, datafusion/core/src/datasource/file_format/json.rs, datafusion/core/src/datasource/file_format/mod.rs, datafusion/core/src/datasource/file_format/parquet.rs, datafusion/proto/src/logical_plan/file_formats.rs, datafusion/proto/src/logical_plan/mod.rs, datafusion/proto/tests/cases/roundtrip_logical_plan.rs
=> Implement physical plan serialization for csv COPY plans , add `as_any`, `Debug` to `FileFormatFactory`

datafusion/functions/src/math/log.rs, datafusion/sqllogictest/test_files/order.slt
Closes #11549.
1. The current implementation assumes `log` has two parameters, but this does not hold for `log(100)`, which is equivalent to `log(10, 100)`. This will cause panic due to index out of bounds.
2. It mistakenly treats the second parameter as `base`, causing incorrect ordering results.
Ref: https://datafusion.apache.org/user-guide/sql/scalar_functions.html#log
Yes
No
=> fix: panic and incorrect results in `LogFunc::output_ordering()`

datafusion/physical-plan/src/coalesce_batches.rs, datafusion/physical-plan/src/joins/cross_join.rs, datafusion/physical-plan/src/joins/nested_loop_join.rs
N/A
While working on https://github.com/apache/datafusion/pull/11610 I found that there is a wrapper over `concat_batches` 
The concat batches function is now available in arrow-rs so let's use that
Use arrow concat_batches directly rather than via a wrapper
By existing CI
No
=> Minor: Use upstream `concat_batches` from arrow-rs

datafusion/functions/src/math/mod.rs, datafusion/functions/src/math/monotonicity.rs, datafusion/functions/src/math/signum.rs, datafusion/sqllogictest/test_files/scalar.slt
Closes #11557 
1. add signum function unit test
2. move `signum_order` function from monotonicity.rs to signum.rs
3. signum function implementation by new code. not `make_udf_function!` macro
1. Add some unit tests.
2. datafusion-cli test
```sql
> select signum(-1), signum(1), signum(0), signum(-0.0), signum(0.0), signum(1.0), signum(-1.0)
;
+-------------------+------------------+------------------+---------------------+--------------------+--------------------+---------------------+
| signum(Int64(-1)) | signum(Int64(1)) | signum(Int64(0)) | signum(Float64(-0)) | signum(Float64(0)) | signum(Float64(1)) | signum(Float64(-1)) |
+-------------------+------------------+------------------+---------------------+--------------------+--------------------+---------------------+
| -1.0 …
```
=> Fix : `signum` function bug when `0.0` input

datafusion/functions/src/core/named_struct.rs, datafusion/sqllogictest/test_files/struct.slt
Closes #11438
* Added a check for uniqueness of named struct fields
* add sql logic tests
Tested manually 
```
> select {'A': 1, 'a': 2};
+-----------------------------------------------------+
| named_struct(Utf8("A"),Int64(1),Utf8("a"),Int64(2)) |
+-----------------------------------------------------+
| {A: 1, a: 2}                                        |
+-----------------------------------------------------+
1 row(s) fetched. 
Elapsed 0.007 seconds.
> select {'a': 1, 'b': 2, 'c': 3, 'b': 4};
Execution error: named_struct requires unique field names. Field b is used more than once.
```
& existing test cases.
=> Enforce uniqueness of `named_struct` field names

datafusion/physical-plan/src/joins/cross_join.rs, datafusion/physical-plan/src/joins/nested_loop_join.rs
Follow on to https://github.com/apache/datafusion/pull/11615
Closes #.
@Dandandan  noticed in https://github.com/apache/datafusion/pull/11615#discussion_r1687964534 this code is now unused, so we can remove it
remove unecessary code
Existing CI
=> Minor: unecessary row_count calculation in `CrossJoinExec` and `NestedLoopsJoinExec`

datafusion/core/src/lib.rs, datafusion/core/src/physical_optimizer/aggregate_statistics.rs, datafusion/core/src/physical_optimizer/combine_partial_final_agg.rs, datafusion/core/tests/fuzz_cases/aggregate_fuzz.rs, datafusion/physical-expr-common/src/aggregate/mod.rs, datafusion/physical-plan/src/aggregates/mod.rs, datafusion/physical-plan/src/windows/mod.rs, datafusion/proto/Cargo.toml, datafusion/proto/src/physical_plan/mod.rs, datafusion/proto/tests/cases/roundtrip_physical_plan.rs
Part of #11543.
Since `create_aggregate_expr` is not stable yet, probably will change after refactor #11359 .
I only create builder API, but not mark `create_aggregate_expr` as deprecated for now.
I also update `create_aggregate_expr` to avoid breaking change on `is_reverse` field.
Ideally, we could have `count_udaf().call_physical(args)....build()` after #11359
=> ExprBuilder for Physical Aggregate Expr

datafusion/sql/src/expr/function.rs, datafusion/sql/src/expr/order_by.rs, datafusion/sql/src/query.rs, datafusion/sql/src/select.rs, datafusion/sql/src/statement.rs
N/A
While working on https://github.com/apache/datafusion/pull/11630 I noticed some cloning in SQL planning that could be avoided
Stop cloning `oby_expr`
Existing CI
No, this is internal only
=> Minor: avoid copying order by exprs in planner

datafusion/physical-expr/Cargo.toml, datafusion/physical-expr/benches/is_null.rs, datafusion/physical-expr/src/expressions/is_not_null.rs, datafusion/physical-expr/src/expressions/is_null.rs
N/A
```
is_not_null: column is all nulls
time:   [51.571 ns 51.892 ns 52.260 ns]
change: [-65.802% -65.423% -65.068%] (p = 0.00 < 0.05)
Found 3 outliers among 100 measurements (3.00%)
is_not_null: column is never null
time:   [98.535 ns 98.892 ns 99.258 ns]
change: [-34.450% -34.256% -34.098%] (p = 0.00 < 0.05)
is_not_null: column is mix of values and nulls
time:   [54.555 ns 54.634 ns 54.714 ns]
change: [-65.402% -65.352% -65.300%] (p = 0.00 < 0.05)
```
=> perf: Optimize IsNotNullExpr

pre-commit.sh
pre-commit hook runs clippy and CI scripts run clippy too. The commands are and should be the same. Let's define them once.
=> Unify CI and pre-commit hook settings for clippy

datafusion/core/tests/expr_api/parse_sql_expr.rs, datafusion/optimizer/tests/optimizer_integration.rs, datafusion/sql/src/expr/identifier.rs, datafusion/sql/tests/sql_integration.rs, datafusion/sqllogictest/test_files/group_by.slt
=> Parsing SQL strings to Exprs with the qualified schema

datafusion/functions-aggregate/src/lib.rs, datafusion/proto/tests/cases/roundtrip_logical_plan.rs
Fixes: https://github.com/apache/datafusion/issues/11643
Closes #11643 .
`expr_fn` module should aggregate and expose the fluent APIs, not the modules which are exposed separately.
Update the re-export in `expr_fn` to expose the fluent API.
No additional tests.
Anyone that currently references `functions_aggregate::expr_fn::approx_distinct::aprox_distinct` will need to change that reference.
=> fix: expose the fluent API fn for approx_distinct instead of the module

datafusion/physical-plan/src/coalesce_batches.rs
(targets `string-view2` branch)
Part of  #10918
`StringViewArray` reference to the raw parquet decoded buffer, which reduces copy but prevents those buffer from being released.
When `StringViewArray`'s cardinality significantly drops (e.g., after `FilterExec` or `HashJoinExec` or many others), we should consider consolidating it so that we can release the buffer to reduce memory usage and improve string locality for better performance.
The current heuristic is to GC `StringViewArray` in `CoalesceBatchesStream` and use larger block size to reduce buffer count (see https://github.com/apache/arrow-rs/issues/6094)
=> GC `StringViewArray` in `CoalesceBatchesStream`

datafusion/physical-plan/src/filter.rs
Closes #.
The poll loops of the `Stream`s in the execution form the core state control. It is useful for them to be as simple as possible so the state machine is easy to understand
While working on https://github.com/apache/datafusion/pull/11647 I noticed we could simplify the poll loop in FilterExec using the `ready!` macro.
Use the standard `ready!` macro to avoid code repetition
By existing CI
=> Minor: use `ready!` macro to simplify `FilterExec`

rust-toolchain.toml
Temporarily pin toolchain version until we solve problems reported by newer clippy release.
Closes for https://github.com/apache/datafusion/issues/11651
=> Temporarily pin toolchain version to avoid clippy errors

docs/source/contributor-guide/communication.md
None (documentation only change)
I wasn't sure where discussion about comet happens.
Documentation change to refer to the #comet channel in the Arrow Rust Discord server
No  - documentation change only
Yes. Documentation change.
=> Add reference to #comet channel in Arrow Rust Discord server

datafusion/sql/src/unparser/plan.rs, datafusion/sql/tests/cases/plan_to_sql.rs
Closes #10652.
Yes - I added a couple example cases to the existing tests.
Only the listed change - `LogicalPlan`s with `JoinConstraint::Using` can now successfully be translated back to SQL.
👋  Hello! This is my first contribution to apache/datafusion; all feedback welcome! I expect there will be a bit of learning on my side as to how this community works. Thanks for any help there you can provide!
Also - this passes `cargo test` locally, but if someone could trigger CI please, that would be appreciated 🙇
=> Add support for USING to SQL unparser

datafusion/expr/src/type_coercion/binary.rs, datafusion/functions/src/regex/regexpmatch.rs, datafusion/sqllogictest/test_files/regexp.slt
Closes #11622
Regex match's args will try to be coerced from Lists, but that shouldn't be possible.
List coercion was added in https://github.com/apache/datafusion/pull/10445, but it's not clear to me why.
Remove list coercion, add tests
yes
No
=> fix: dont try to coerce list for regex match

datafusion/functions-aggregate/src/nth_value.rs, datafusion/physical-expr-common/src/aggregate/mod.rs
Closes #11668.
The `AccmulatorArgs::is_reversed` was introduced in #11564 for indicating that the aggregation order has been reversed. The existing implementation of `NthValueAgg` instead uses internal state.
I believe it makes sense to use the new `is_reversed` field with the added benefit of deleting some code from `NthValueAgg`.
Refactors `NthValueAgg` to use `AccumulatorArgs::is_reversed`.
This is a simple refactor of existing code, so only existing checks against CI. 
Yes. A minor fix to doc comment for `AggregateFunctionExpr::is_reversed`.
=> Use `AccumulatorArgs::is_reversed` in `NthValueAgg`

datafusion/physical-expr-common/src/binary_view_map.rs
Targets the string-view2 branch
Closes #.
Increase the default block size from 8KB to 2MB, this significantly improves the aggregation performance with high cardinality.
More details see https://github.com/apache/arrow-rs/issues/6094
=> Increase ByteViewMap block size to 2MB

docs/source/contributor-guide/testing.md
Minor improvement of the documentation section for unit tests, probably wrong because the best practice is to use the macro as re-exported from `datafusion_common` or maybe even `datafusion`?
=> Docs: adding explicit mention of test_utils to docs

datafusion/functions/src/unicode/character_length.rs
targets string-view2 branch
Closes #11677 .
Currently we rely on auto coerce rule to support StringViewArrays, which requires a cast (copy). This pr adds native supports to StringViewArray, so that no cast is required, and we see performance improvements with this code.
I plan to make this a template PR that people can reference to when adding more native supports for StringView operations.
=> Implement native support StringView for character length

datafusion/core/src/execution/session_state.rs, datafusion/execution/src/task.rs
N/A
While working on trying to add some doc suggestions to https://github.com/apache/datafusion/pull/11516 (which is basically making a trait for `SessionState`), I reviewed the SessionState documentation and found some thing I would like to clarify
1. Update docs
2. Add an example of creating `SessionState` from `SessionContext`
yes, by doc test in CI
Only documentation, no user facing changes
=> Minor: improve documentation on `SessionState`

Cargo.toml, datafusion-cli/Cargo.lock, datafusion-cli/Cargo.toml, datafusion/core/src/datasource/file_format/parquet.rs
N/A
Now that arrow/parquet 52.2.0 is released https://github.com/apache/arrow-rs/issues/5998 let's use it
The main rationale for upgrading is that this has several additional performance improvements related to StringView that @XiangpengHao  and @a10y have been working on. It will unblock merging in the string-view2 branch: https://github.com/apache/datafusion/pull/11667
1. Update to arrow/parquet `52.2.0`
2. change to use non deprecated `flattened_fields` API
=> Update to arrow/parquet `52.2.0`

datafusion/physical-plan/src/repartition/mod.rs
~Draft until https://github.com/apache/datafusion/pull/11440 merges~
None
While reviewing https://github.com/apache/datafusion/pull/11440 from @korowa  it took me a little while to find how the metric was plumbed through. Part of that was that the field name is slightly different
Rename a field to match the metric it tracks
By existing CI
No this is entirely internal
=> Minor: Rename `RepartitionMetrics::repartition_time` to `RepartitionMetrics::repart_time` to match metric

datafusion/functions-aggregate/src/regr.rs, datafusion/sqllogictest/test_files/aggregate.slt
Closes #11726.
Consistent with `count` expectations and postgres, `regr_count` aggregate function should return an integer, not a float.
The UDAF and it's corresponding SQL tests have been updated.
Yes, via updating the `aggregate.slt` tests.
Yes - `regr_count` returns  a different `DataType`.
=> fix: regr_count now returns Uint64

datafusion/functions-aggregate/src/approx_percentile_cont.rs, datafusion/sqllogictest/test_files/aggregate.slt
Closes #11720
Fix a bug in `approx_percentile_cont` when having nulls in input
Filters input arrays on nulls if present
Yes, additional sql test
Just the fix
=> Handle nulls in approx_percentile_cont

datafusion/sql/src/select.rs, datafusion/sql/src/utils.rs
Closes https://github.com/apache/datafusion/issues/11498#event-13608606088
=> Reduce repetition in try_process_group_by_unnest and try_process_unnest

datafusion/expr/src/udf.rs
N/A
While reviewing https://github.com/apache/datafusion/pull/11694 I found that this function could be better documented, so I added an example
Add example for `ScalarUDF::call`
CI tests
Just docs
=> Minor: Add example for `ScalarUDF::call`

benchmarks/bench.sh
N/A
As we get into serious benchmarking / optimization mode, ensuring the benchmark results are as close to what is actually run as possible is important. Thus I want to propose using `cargo release` in bench.sh even if that makes the runs take longer. 
Most builds of DataFusion use `cargo <cmd> --release` rather than `cargo <cmd> --profile release-nonlto`
For example, I am not sure why https://github.com/apache/datafusion/pull/11718 shows improvements on some environments and not others. 
1. Change `bench.sh` to use `--release` instead of `--relase-non-lto`
I am going to run benchmarks on my test rig manually to see if this causes any differences
=> Use `cargo release` in `bench.sh`

datafusion/core/src/datasource/schema_adapter.rs
This seems like a nice self-contained API that would be useful for downstream consumers of DataFusion
=> Make DefaultSchemaAdapterFactory public

datafusion/physical-plan/src/aggregates/group_values/row.rs
Closes #11717 
See #11717 
See title.
By exist tests.
No.
=> Check hashes first during probing the aggr hash table

datafusion/core/src/physical_optimizer/enforce_sorting.rs, datafusion/core/src/physical_optimizer/sort_pushdown.rs, datafusion/core/src/physical_optimizer/test_utils.rs
Closes https://github.com/apache/datafusion/issues/11675
Closes https://github.com/apache/datafusion/pull/11493
See https://github.com/apache/datafusion/issues/11675 -- the PushDown sort optimizer was incorrectly pushing down sorts in certain cases
This change fixes a problem we were seeing in our tests downstream in influxdb iox
1. Don't push down sorts if doing so would violate the ordering requirements
2. Add tests
Yes, new unit tests are added
Bug fix
=> Do not push down Sorts if it violates the sort requirements

datafusion/sql/src/unparser/plan.rs, datafusion/sql/tests/cases/plan_to_sql.rs
Closes #11743.
This PR will check the `select_builder` in the `select_to_sql_expr` after calling the `select_to_sql_recursively` and if no projection is set, it will add a projection with one element set to `ast::SelectItem::Wildcard(ast::WildcardAdditionalOptions::default())`
The changes described above, and some test cases. 
Yes. 
I would say no.
=> Fix `plan_to_sql`: Add wildcard projection to SELECT statement if no projection was set

datafusion/core/tests/memory_limit/mod.rs, datafusion/execution/src/memory_pool/mod.rs, datafusion/execution/src/memory_pool/pool.rs
Part of #11523 
The OOMing error message returns information about the next incremental request of memory, and not for the biggest consumers of memory. As a result, we have spent time chasing OOMs in the wrong place.
Includes a new MemoryPool implementation, which when (optionally) used with an inner MemoryPool will return a list of the top memory consumers on OOM.
This new `TrackConsumersPool` is optional, such that individual users can determine whether or not to use this capability (along with any associated overhead).
Yes.
Yes, as a new `TrackConsumersPool`.
=> Add `TrackedMemoryPool` with better error messages on exhaustion

datafusion/expr/src/logical_plan/plan.rs
Closes #.
When I was debugging optimizer rule, I found many logical plan nodes are not derived `Debug`, so added it.
=> Derive `Debug` for logical plan nodes

benchmarks/queries/clickbench/README.md, datafusion/sqllogictest/test_files/clickbench.slt
Related to https://github.com/apache/datafusion/pull/11723
While working to enable `StringView` by default I hit an error running the [ClickBench "extended" queries](https://github.com/apache/datafusion/blob/feb9100432d453f19d40428265d2aa9a9f942d5d/benchmarks/queries/clickbench/README.md#extended-queries):
```
Finished `release` profile [optimized] target(s) in 0.77s
Running `/home/alamb/arrow-datafusion2/target/release/dfbench clickbench --iterations 5 --path /home/alamb/arrow-datafusion/benchmarks/data/hits.par\
quet --queries-path /home/alamb/arrow-datafusion/benchmarks/queries/clickbench/extended.sql -o /home/alamb/arrow-datafusion/benchmarks/results/alamb_stri\
ng_view_default/clickbench_extended.json`
Running benchmarks with the following options: RunOpt { query: None, common: …
```
=> Minor: add "clickbench extended" queries to slt tests

datafusion/physical-plan/src/aggregates/group_values/row.rs
Follow on to https://github.com/apache/datafusion/pull/11718
Closes #.
In https://github.com/apache/datafusion/pull/11718 @Rachelint  found that comparing hash values before group key values improved performance. The reason this could be faster was not obvious at first
Add doc comments explaining the rationale and linking to https://github.com/apache/datafusion/pull/11718
CI
No, just comments
=> Minor: Add comment explaining rationale for hash check

datafusion/functions-aggregate/src/count.rs, datafusion/sqllogictest/test_files/string_view.slt
=> Fix bug that `COUNT(DISTINCT)` on StringView panics 

datafusion/physical-plan/src/filter.rs
N/A
We were only timing the batch_filter operation when it resulted in non-empty batches. We should always record the time of the operation because the predicate could be expensive to evaluate.
Move the `timer.done()` call to before the early return for empty batches.
=> minor: always time batch_filter even when the result is an empty batch

datafusion/execution/src/memory_pool/pool.rs
Part of #11523 
Improve the OOM error messages [per here](https://github.com/apache/datafusion/issues/11523#issuecomment-2260759076).
We have memory reservations, memory consumers, and a memory pool. The pool has many consumers, and each consumer can have many reservations. The code docs added in [the previous PR](https://github.com/apache/datafusion/pull/11665) make this delineation clear. 
In this PR we changed the error message provided when we are comparing the pool vs reservation's request. We now explicitly define which bytes refer to the reservation vs the pool.
Changes a single error message.
Yes.
No API changes. Only less confusing error messages.
=> Improve OOM message when a single reservation request fails to get more bytes.

datafusion/optimizer/src/analyzer/function_rewrite.rs, datafusion/optimizer/src/analyzer/mod.rs, datafusion/sqllogictest/test_files/explain.slt
Relates to #9373 and #9375.
I'm dealing with a situation where we [have deeply nested plans](https://github.com/splitgraph/seafowl/blob/82a9ca4a7da9eed0d17e9fe0f6b3357af8bd97a1/src/frontend/flight/sync/writer.rs#L387-L398), which we want to execute and stream the data into storage (Parquet/Delta), and we're hitting the stack overflow problem observed in the aforementioned issues.
Since this is on a write path we don't really need the analyzer/optimizer rules (I think), which are a part of the problem due to tree node recursion that takes place there. This is not an issue, since those can easily be opted out of via `with_analyzer_rules`/`with_optimizer_rules`. 
However, the tightest bottleneck as per lldb is actually `ApplyFunctionRewrites`, which can't be opted out of, even though after …
=> [Minor] Short circuit `ApplyFunctionRewrites` if there are no function rewrites

datafusion/physical-plan/src/coalesce_batches.rs
Note most of this PR is additional documentation and tests. There is no new functionality
Related to https://github.com/apache/datafusion/issues/9370 
Related to https://github.com/apache/datafusion/issues/7957
1. I want to be able to write tests more easily for PRs like (https://github.com/apache/datafusion/pull/11587)
2. I also harbor plans to improve repartitioning and filtering (to avoid a copy -- see https://github.com/apache/datafusion/issues/7957) this is the first step
As an example of what I hope to do with this, today we have a `FilterExec` which copies all rows that pass the filter into a new `RecordBatch` followed by  `CoalesceBatches` which will likely copy the batch again into a larger set
With a struct like this, I think we have the possibility of the  filter producing the …
=> Extract `CoalesceBatchesStream` to a struct

datafusion/core/src/datasource/listing/table.rs, datafusion/core/src/datasource/listing_table_factory.rs
=> Minor: Add references to github issue in comments

datafusion/sql/src/expr/mod.rs, datafusion/sqllogictest/test_files/map.slt
Closes #11434 
yes
Provide `map` literal syntax.
=> Support planning `Map` literal

datafusion/expr/src/logical_plan/builder.rs, datafusion/sqllogictest/test_files/join.slt
=> fix: Add additional required expression for natural join

benchmarks/src/tpch/run.rs, datafusion/core/src/dataframe/mod.rs, datafusion/core/tests/custom_sources_cases/mod.rs, datafusion/core/tests/expr_api/simplification.rs, datafusion/core/tests/optimizer_integration.rs, datafusion/core/tests/sql/explain_analyze.rs, datafusion/core/tests/user_defined/user_defined_aggregates.rs, datafusion/core/tests/user_defined/user_defined_scalar_functions.rs, datafusion/expr/src/logical_plan/builder.rs, datafusion/expr/src/logical_plan/ddl.rs, datafusion/expr/src/logical_plan/dml.rs, datafusion/expr/src/logical_plan/plan.rs, datafusion/expr/src/logical_plan/statement.rs, datafusion/optimizer/src/common_subexpr_eliminate.rs, datafusion/optimizer/src/eliminate_limit.rs, datafusion/optimizer/src/optimize_projections/mod.rs, datafusion/optimizer/src/push_down_filter.rs, datafusion/optimizer/src/simplify_expressions/simplify_exprs.rs, datafusion/optimizer/src/test/mod.rs, datafusion/optimizer/tests/optimizer_integration.rs, datafusion/proto/tests/cases/roundtrip_logical_plan.rs, datafusion/sql/examples/sql.rs, datafusion/sql/tests/cases/plan_to_sql.rs, datafusion/sql/tests/sql_integration.rs, datafusion/substrait/src/logical_plan/producer.rs, datafusion/substrait/tests/cases/consumer_integration.rs, datafusion/substrait/tests/cases/function_test.rs, datafusion/substrait/tests/cases/logical_plans.rs, datafusion/substrait/tests/cases/roundtrip_logical_plan.rs, datafusion/substrait/tests/cases/serialize.rs
Closes #.
LogicalPlan implemented Debug with actual display output. It's not useful for debugging some node/expr details.
=> Support `LogicalPlan` `Debug` differently than `Display`

datafusion/core/src/physical_planner.rs, datafusion/expr/src/expr.rs, datafusion/expr/src/expr_schema.rs, datafusion/expr/src/tree_node.rs, datafusion/functions-nested/src/planner.rs, datafusion/optimizer/src/analyzer/count_wildcard_rule.rs, datafusion/optimizer/src/analyzer/type_coercion.rs, datafusion/optimizer/src/decorrelate.rs, datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs, datafusion/optimizer/src/single_distinct_to_groupby.rs, datafusion/proto/src/logical_plan/to_proto.rs, datafusion/sql/src/unparser/expr.rs, datafusion/substrait/src/logical_plan/producer.rs
Closes #.
Remove `AggregateFunctionDefinition` as all aggr functions are already implemented using UDAF.
=> Remove `AggregateFunctionDefinition`

.github/workflows/rust.yml
Closes https://github.com/apache/datafusion/issues/11788
When the MSRV CI check fails it does not say what is wrong or offer specific advice on how to fix it. For example:
CI failure: https://github.com/apache/datafusion/actions/runs/10204347289/job/28280296775?pr=11627
Output error:
```
Run # If you encounter an error with any of the commands below
Fetching index
Verifying the Minimum Supported Rust Version (MSRV) for toolchain x86_64-unknown-linux-gnu
Using check command cargo check
Failed check command cargo check didn't succeed
Crate source was found to be incompatible with its MSRV '1.76.0', as defined in '/__w/datafusion/datafusion/datafusion/core/Cargo.toml'
Error: Process completed with exit code 1.
```
1. Add `--logfile stdout` so errors are printed to the log
2. Update comments …
=> Improve MSRV CI check to print out problems to log

datafusion/optimizer/src/replace_distinct_aggregate.rs, datafusion/sqllogictest/test_files/aggregate.slt
-
Closes #.
This change is for satisfying the related conversation: https://github.com/apache/datafusion/pull/11781#discussion_r1702168887
A valid test case for distinct and group-by usage
Yes
No
=> Add valid Distinct case for aggregation

datafusion/sqllogictest/test_files/aggregate.slt
N/A
CI is failing on main, for example https://github.com/apache/datafusion/actions/runs/10251066368/job/28358425606
I think it is a logical conflict between https://github.com/apache/datafusion/pull/11795 and https://github.com/apache/datafusion/pull/11814
Update test output
No, this is just a development process change
=> Minor: Update exected output due to logical conflict

datafusion/functions/Cargo.toml, datafusion/functions/benches/nullif.rs, datafusion/functions/src/core/nullif.rs
Closes #.
`eq` used inside the `nullif` has a performance specialization for scalar, but it was not used, as we never passed a `Scalar` into it.
- Add benchmark for nullif
- Convert ScalarValue to Scalar, instead of Array of size 1
```cargo bench --bench nullif --features "core_expressions" -- --baseline=before
nullif scalar array: 1024
time:   [5.3127 µs 5.3305 µs 5.3526 µs]
change: [-1.2396% -0.9171% -0.5696%] (p = 0.00 < 0.05)
Found 13 outliers among 100 measurements (13.00%)
9 (9.00%) high mild
nullif scalar array: 4096
time:   [16.483 µs 16.577 µs 16.675 µs]
change: [-4.6029% -3.9615% -3.1831%] (p = 0.00 < 0.05)
5 (5.00%) high mild …
```
=> Pass scalar to `eq` inside `nullif` 

datafusion/physical-plan/src/aggregates/row_hash.rs
Follow on to https://github.com/apache/datafusion/pull/11627
Per https://github.com/apache/datafusion/pull/11627/files#r1694253923, I think embedding the aggregation probe logic into a function makes the code eaiser to understand
1. Pull logic into a function `should_skip_aggregation`
2. Update some comments to `///` from `//` for consistency
No, this is all internal code organization
=> Minor: refactor probe check into function `should_skip_aggregation`

datafusion/core/src/execution/session_state.rs
None.
#11403 is not shipped in 40.0.0 but marks `SessionState::new_with_config_rt` as deprecated since `40.0.0`.
Bump deprecated version of `SessionState::new_with_config_rt` to `41.0.0`.
* https://github.com/apache/datafusion/blob/40.0.0/datafusion/core/src/execution/session_state.rs#L178
* https://docs.rs/datafusion/40.0.0/datafusion/execution/session_state/struct.SessionState.html#method.new_with_config_rt
Both code and docs of 40.0.0 don't deprecate `SessionState::new_with_config_rt`.
It should be considered as a squashed fix to #11403.
=> Bump deprecated version of SessionState::new_with_config_rt to 41.0.0

datafusion/physical-expr-common/src/aggregate/groups_accumulator/prim_op.rs, datafusion/sqllogictest/test_files/aggregate_skip_partial.slt
Closes https://github.com/apache/datafusion/issues/11832
Otherwise when the dynamic grouping skip is hit you get an error
Correctly set the intermediate aggregate type
New slt test
Bug fix (but affected code has not been released)
=> Fix partial aggregation skipping with Decimal aggregators

datafusion/physical-plan/src/joins/hash_join.rs
Closes #11658.
Some tests in `hash_join.rs` check the number of output batches, and since output batch for `HashJoinExec` is created while matching join keys against hash table built on build-side data (which includes only matching by hashes, comparing actual values is a next step in join execution), these tests are failing with forced collisions (due to equal hashes, all records are considered as matching).
This PR recovers hash join tests by adjusting the numbers of expected batches in case test is running with `force_hash_collisions` feature.
Different numbers of expected output batches for `force_hash_collisions` feature in hash join tests.
Yes
No
=> fix: hash join tests with forced collisions

datafusion/physical-plan/src/coalesce_batches.rs
Part of #11752.
The new arrow-rs implementation disallow zero-sized buffer for StringViewBuilder: https://github.com/apache/arrow-rs/pull/6136
When new version of arrow-rs is released, we will trigger this bug.
- We could also change arrow so that `with_block_size` takes a [NonZeroU32](https://doc.rust-lang.org/std/num/type.NonZeroU32.html)
- I don't think zero-sized buffer should be allowed, it creates unexpected runtime problems...
=> Fix bug with zero-sized buffer for StringViewArray

datafusion/physical-expr/src/utils/mod.rs
\-
Fix accidental $O(n^2)$ in `collect_columns`.
There are the following ways to insert a clone into a hash set:
- **clone before check:** Basically `set.insert(x.clone())`. That's rather expensive if you have a lot of duplicates.
- **iter & clone:** That's what we do right now, but that's in $O(n^2)$.
- **check & insert:** Basically `if !set.contains(x) {set.insert(x.clone())}` That requires two hash probes though.
- **entry-based API:** Sadly the stdlib doesn't really offer any handle/entry-based APIs yet (see https://github.com/rust-lang/rust/issues/60896 ), but `hashbrown` does, so we can use the nice `set.get_or_insert_owned(x)` which will only clone the reference if it doesn't exists yet and only hashes once.
We now use the last approach.
Functional tests still pass, performance …
=> fix: `collect_columns` quadratic complexity

Cargo.toml
As part of mitigating https://nvd.nist.gov/vuln/detail/CVE-2024-41178, `object_store` should be upgraded to the no-longer-vulnerable version 0.10.2 instead of 0.10.1
Closes https://nvd.nist.gov/vuln/detail/CVE-2024-41178#VulnChangeHistorySection (no Github issue yet)
Upgrading to mitigate CVE-2024-41178
Only the change to the `Cargo.toml` to consume the fixed version
Changes should be covered by existing tests. I couldn't find on https://docs.rs/crate/object_store/0.10.2 if there were breaking changes between 0.10.1 and 0.10.2. 
No
=> Update `object_store` to 0.10.2

datafusion/physical-plan/src/aggregates/row_hash.rs
* Closes https://github.com/apache/datafusion/issues/11815
* Part of https://github.com/apache/datafusion/issues/6937
* Follow on to  https://github.com/apache/datafusion/pull/11627
https://github.com/apache/datafusion/pull/11627 from @korowa  adds a "partial aggregation skipping" mode to the hash aggregate exec that switches aggregate behavior dynamically at runtime, 
It would be very nice to know if the path is being executed or not, and the way to do this in DataFusion is metrics. 
Add a "skipped_aggregation_rows" counter which records the number of rows 
I tested them manually
For example, this line shows ` skipped_aggregation_rows=98293561`:
```
|                   |               AggregateExec: mode=Partial, gby=[WatchID@0 as WatchID, ClientIP@1 as ClientIP], aggr=[count(*)], …
```
=> Add `skipped_aggregation_rows` metric to aggregate operator

datafusion-examples/examples/planner_api.rs, datafusion/core/src/physical_planner.rs
Closes https://github.com/apache/datafusion/issues/11873
See https://github.com/apache/datafusion/issues/11873
- Make physical optimizer method public and rename it
- Add an example
Existing tests
=> feat: Expose public method for optimizing physical plans

datafusion/expr/src/type_coercion/binary.rs, datafusion/sqllogictest/test_files/string_view.slt
Partially make #11766 work.
* coerced `Utf8View` to `Utf8` make concat work
* Added slt tests cases
Existing test cases
```
carog test
```
=> Cast `Utf8View` to `Utf8` to support `||` from `StringViewArray`

datafusion-cli/examples/cli-session-context.rs, datafusion-cli/src/catalog.rs, datafusion-cli/src/command.rs, datafusion-cli/src/exec.rs, datafusion-cli/src/main.rs, datafusion-examples/examples/catalog.rs, datafusion/core/benches/filter_query_sql.rs, datafusion/core/src/dataframe/mod.rs, datafusion/core/src/dataframe/parquet.rs, datafusion/core/src/execution/context/mod.rs, datafusion/core/src/test_util/mod.rs, datafusion/core/tests/user_defined/user_defined_plan.rs, datafusion/proto/tests/cases/roundtrip_logical_plan.rs, docs/source/library-user-guide/custom-table-providers.md
Two years ago we require mutable reference of `SessionContext` for any operations like exec_*/register_*. But recently `SessionContext` owns a RwLock internally so mutable reference is no longer needed. 
This change remove all mutable marker I can find in tests, docs and also one API of `SessionContext`
When it compiles, it's correct.
There is an API breaking change for `register_catalog_list` in `SessionContext`. The mutable requirement is removed.
=> refactor: remove unneed mut for session context

datafusion/core/src/datasource/physical_plan/arrow_file.rs
Closes #.
Refactors an explicit `Result<Option<T>>` to `Option<Result<T>>` conversion to use the equivalent `.transpose()` method on `Result`.
> Ok(None) will be mapped to None. Ok(Some(_)) and Err(_) will be mapped to Some(Ok(_)) and Some(Err(_)).
- https://doc.rust-lang.org/std/result/enum.Result.html#method.transpose
No.
=> [Minor]: Refactor to use Result.transpose()

.github/workflows/rust.yml, ci/scripts/rust_docs.sh
Since a4ac0829ecf63b3640315835b1374211dfadd953 commit there was a discrepancy between rust.yml GitHub workflow and the `dev/rust_lint.sh` script behavior. Sync the behaviors. Reuse common script to prevent future discrepancies.
=> Sync rust docs params for CI and dev

datafusion/functions/src/string/ascii.rs, datafusion/sqllogictest/test_files/string_view.slt
=> Update ASCII scalar function to support Utf8View #11834

datafusion/expr/src/type_coercion/binary.rs, datafusion/sql/src/expr/value.rs, datafusion/sql/tests/cases/plan_to_sql.rs, datafusion/sqllogictest/test_files/timestamps.slt
Close https://github.com/apache/datafusion/issues/11891
We regularly want to allow queries of the form
```sql
SELECT * FROM records WHERE end_timestamp - start_timestamp > interval '2 seconds'
```
Until now that failed with
```
type_coercion: Cannot infer common argument type for comparison operation Duration(Microsecond) > Interval(MonthDayNano)
```
While working on that, I discovered you couldn't compare to an interval with the interval as the left hand side of the operation, so I fixed that too.
* fix `Duration` vs. `Interval` comparison - sense check - is it really as simple as it looks?
* support more operators in machinery to support intervals as the LHF of binary operations
* add tests for both
Yes
Should be only the above changes to support SQL.
=> Fix `Duration` vs `Interval` comparisons and `Interval` as LHS

benchmarks/src/bin/dfbench.rs, benchmarks/src/bin/tpch.rs
Throw explicit error message when `cargo build` is invoked with
conflicting features, e.g.  `cargo test --lib --tests --bins
--all-features`.
=> Produce clear error message when build runs with conflicting features

datafusion/sql/src/unparser/plan.rs, datafusion/sql/src/unparser/rewrite.rs, datafusion/sql/tests/cases/plan_to_sql.rs
This further addressed the unparser issues when derived table contains match operator, `cast`, `limit`, `order`, etc.
These are common SQL patterns which doesn't work now. See test cases for details
Rewrite more bits of logical plan during unparsing. The key change is to use field name to match the outer layer projection field to detect if the logical plan can be corrected for unparsing purpose, which is the reverse path of parsing for these sql during the first leg of the round trip.
Yes
No
=> fix: invalid sqls when unparsing derived table with columns contains calculations, limit/order/distinct

datafusion/core/src/datasource/listing/helpers.rs, datafusion/core/src/datasource/listing/mod.rs, datafusion/core/src/datasource/listing/table.rs, datafusion/core/src/datasource/listing/url.rs
This is part of isolating this module in order to be able to move it out
of core. This commit attempts to replace all `crate::` imports that are
possible to avoid today (i.e. which would be replaced when listing table
provider was moved to separate crate), leaving those that cannot be
replaced. This makes it easy to notice the remaining coupling between
the listing table provider module and the core.
For https://github.com/apache/datafusion/issues/10782
=> Remove many `crate::` imports in listing table provider module

datafusion/sqllogictest/test_files/array.slt
Part of https://github.com/apache/datafusion/issues/11823
Part of https://github.com/apache/datafusion/issues/11922
While reviewing https://github.com/apache/datafusion/pull/11907 from @tshauck  I didn't see any tests for running generate_series with actual input arrays, the current tests only handled constants
Add tests for `generate_series` with columns
Only tests
=> Add `generate_series` tests for arrays

datafusion/optimizer/src/decorrelate.rs, datafusion/optimizer/src/eliminate_filter.rs, datafusion/optimizer/src/eliminate_join.rs, datafusion/optimizer/src/propagate_empty_relation.rs, datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs, datafusion/physical-expr/src/planner.rs
N/A
While looking at https://github.com/apache/datafusion/pull/11897 from @Lordworms I noticed several places where the very long form of creating a literal boolean was used:
```rust
Expr::Literal(ScalarValue::Boolean(Some(false)));
```
I would like to encourage people to use the shorter form:
```rust
lit(false)
```
Which both makes the code shorter and easier to read
Replace some
* `Expr::Literal(ScalarValue::Boolean(Some(false)))` with `lit(false)`
* `Expr::Literal(ScalarValue::Boolean(Some(true)))` with `lit(true)`
By CI
No, this is all internal only
=> Minor: use `lit(true)` and `lit(false)` more

datafusion/functions-aggregate-common/src/tdigest.rs, datafusion/sqllogictest/test_files/aggregate.slt
Closes #11871.
Closes #11870.
Closes #11869.
There are several crashed bugs in `approx_median()`/`approx_percentile_cont()`/`approx_percentile_cont_with_weight()`
Those functions all rely on `ApproxPercentileAccumulator` for implementation.
This PR includes an edge case fix within `ApproxPercnetileAccumulator`, and more details can be found in the comments.
sqllogictests, note 3 added test cases are equivalent to the ones reported in issues, but they are further reduced.
=> Fix: panics in `approx_percentile_cont()` aggregate function

datafusion/functions-nested/src/range.rs, datafusion/sqllogictest/test_files/array.slt
closes #11823
Currently, when trying to generate a series of dates with increments less than a day, the query will hang due to loss of precision (the step size becomes 0 relative to the Date32).
* Raise an error if attempting increment by less than a day
* Refactor to use a `ListBuilder`
* A few minor quick-fixes
Yes, added a test.
Minor in that queries will now error when they would've hung forever.
=> fix: throw error on sub-day generate_series increments

datafusion-cli/src/exec.rs
Closes #11880 .
to support traditional `#!` ... shebangs
```
#!/usr/bin/env -S datafusion-cli -f
SELECT 1;
```
or we can use something like
```
--() { :; }; exec datafusion-cli -f "$0"
SELECT 1;
```
=> Ingore shebang at top of file in `datafusion-cli`

datafusion/functions/src/string/octet_length.rs, datafusion/sqllogictest/test_files/string_view.slt
=> Implement native support StringView for Octet Length

datafusion/core/src/physical_optimizer/test_utils.rs, datafusion/core/src/physical_planner.rs, datafusion/core/tests/fuzz_cases/window_fuzz.rs, datafusion/physical-plan/src/windows/bounded_window_agg_exec.rs, datafusion/physical-plan/src/windows/mod.rs, datafusion/proto/src/physical_plan/from_proto.rs, datafusion/proto/src/physical_plan/mod.rs, datafusion/proto/tests/cases/roundtrip_physical_plan.rs
close #11804 
see related issue #11804
add serialization/deserialization for ordering, remove logical expr need in  `create_window_expr` function(related to #11845)
add roundtrip test for approx_percentile_cont function and ordering.
no
=> fix: impl ordering for serialization/deserialization for AggregateUdf

datafusion/functions/src/string/ends_with.rs, datafusion/sqllogictest/test_files/string_view.slt
=> Implement native support StringView for Ends With

datafusion/functions/src/string/levenshtein.rs, datafusion/sqllogictest/test_files/string_view.slt
=> Implement native support StringView for Levenshtein

datafusion/functions/src/string/btrim.rs, datafusion/functions/src/string/common.rs, datafusion/functions/src/string/ltrim.rs, datafusion/functions/src/string/rtrim.rs, datafusion/sqllogictest/test_files/string_view.slt
Closes #11835
The changes mainly lie in datafusion/functions/string/common.rs, where I broke `generic_trim` up to deal with 2 conditions (whether to use `Utf8View` or not). An additional parameter is also added to indicate the datatype. I also temporarily adjusted `LTRIM` and `RTRIM` to work through the process. If my implementation is considered a good practice, I would like to open follow-on PRs to have `LTRIM` and `RTRIM` support `Utf8View` natively.
And some tests were also added to string_view.slt covering the `Utf8View` support of `BTRIM`.
yes
no
=> Implement native stringview support for BTRIM

datafusion/sql/tests/cases/plan_to_sql.rs, datafusion/sql/tests/common/mod.rs, datafusion/sql/tests/sql_integration.rs
=> chore: Add SessionState to MockContextProvider just like SessionContextProvider

datafusion/common/src/stats.rs, datafusion/core/src/datasource/physical_plan/file_scan_config.rs, datafusion/core/src/datasource/statistics.rs, datafusion/physical-expr/src/analysis.rs, datafusion/physical-plan/src/filter.rs, datafusion/physical-plan/src/joins/utils.rs
Builds on https://github.com/apache/datafusion/pull/11802
While reviewing https://github.com/apache/datafusion/pull/11802 from @Rachelint I had to double check that a call to `clone()` was not copying anything large (specifically a `ScalarValue`) and it turns it that it is not
~Move the `clone()` (of a `usize`) into a function where the type is explict~
Add `#[Derive(Copy)]` to `Precision` which results in only calls to `Precision<ScalarValue>` needing a `clone`
By existing CI
`Precision` is now `Copy` in many places, so clippy may tell you you need to remove `clone()`
=> Make `Precision<usize>` copy to make it clear clones are not expensive

datafusion-cli/Cargo.lock, datafusion/common/Cargo.toml, datafusion/common/src/error.rs, datafusion/common/src/lib.rs, datafusion/core/src/datasource/physical_plan/parquet/row_filter.rs, datafusion/functions/src/datetime/common.rs, datafusion/functions/src/datetime/to_date.rs, datafusion/physical-expr/benches/case_when.rs, datafusion/physical-expr/src/expressions/case.rs, datafusion/sql/src/parser.rs, datafusion/sql/src/unparser/plan.rs
Closes #11957 
It's nice to keep ahead of future rust changes and make sure people can comfortably use this library on any toolchain.
- Fixed all issues reported by clippy (but 1, mentioned in the attached issue)
- Refactored the `make_error` macro that's used to make all the errors + variants to prevent code duplication and get rid of unnecessary `with_dollar_sign` macro
Yes, it passes all tests that main currently passes on my machine.
This adds items to the public API, under `#[doc(hidden)]`. This is not a breaking change afaik, but would cause a breaking change if they were removed.
=> fix: Fix various complaints from the latest nightly clippy

datafusion/common/src/error.rs, datafusion/sql/src/parser.rs
Follow on to https://github.com/apache/datafusion/pull/11958
In discussion with @itsjunetime on https://github.com/apache/datafusion/pull/11958 I saw 2 improvements
1. Simplify number parsing (there is no need to `parse` a string
2. Add comment explaining the use of `allow(unused)`
By CI
No
=> Minor: simplify SQL number parsing and add a comment about unused

datafusion/functions/src/string/btrim.rs, datafusion/functions/src/string/ltrim.rs, datafusion/functions/src/string/rtrim.rs, datafusion/sqllogictest/test_files/string_view.slt
Closes #11856 and closes #11916
Follow the changes in #11920 
Added function signatures of  `ltrim` and `rtrim` to support stringview. And some relavant tests
yes
no
=> Add native stringview support for LTRIM & RTRIM

datafusion/functions/src/unicode/right.rs, datafusion/sqllogictest/test_files/string_view.slt
Closes #11917
Update signature of RIGHT to accept Utf8View and add some tests for that.
yes
no
=> Add native stringview support for RIGHT

datafusion/functions/src/core/mod.rs, datafusion/sqllogictest/test_files/struct.slt
This makes sense in principle, as all other core udfs are register by default in the context.
It also has a practical use, which is executing logical plans that have field access already de-sugared into get_field invocations.
Yes
This is technically user-facing, though there aren't a lot of use cases for actually calling `get_field`.
=> Register get_field by default

datafusion/physical-plan/src/coalesce_batches.rs
Closes #.
This PR is a small refactor of `CoalesceBatchesStream`. It adopts a stateful approach to enhance the clarity of the code and improve the usability of `BatchCoalescer`.
The `poll_next_inner` method of `CoalesceBatchesStream` has been rewritten to follow a stateful pattern. Additionally, `BatchCoalescer` has been refactored into more competent methods.
The existing unit tests have been updated to accommodate the new implementation.
=> Refactor `CoalesceBatches` to use an explicit state machine

datafusion/functions/src/unicode/find_in_set.rs, datafusion/sqllogictest/test_files/functions.slt, datafusion/sqllogictest/test_files/string_view.slt
Closes #11954 .
Ref: https://github.com/apache/datafusion/blob/main/datafusion/functions/src/unicode/character_length.rs
=> Implement native support StringView for find in set

datafusion/sqllogictest/test_files/parquet.slt
Closes #11660.
After several attempts to reproduce the failure locally and in fork CI it still was not reproducing. Also I wasn't able to find any workflow failure related to 1.80 upgrade in PRs and on main. So, trying to just uncomment the test.
Test uncommented.
=> test: re-enable window function over parquet with forced collisions

datafusion/functions/src/unicode/rpad.rs, datafusion/sqllogictest/test_files/functions.slt, datafusion/sqllogictest/test_files/string_view.slt
=> Update RPAD scalar function to support Utf8View

datafusion/functions/src/unicode/substrindex.rs, datafusion/sqllogictest/test_files/functions.slt, datafusion/sqllogictest/test_files/string_view.slt
Closes #.
Part of https://github.com/apache/datafusion/issues/11752 and https://github.com/apache/datafusion/issues/11790
YES, with sqllogictests.
NO
=> Implement native support StringView for substr_index

datafusion/functions/src/unicode/left.rs, datafusion/sqllogictest/test_files/string_view.slt
Issue similar to #11917. Instead of `RIGHT`, this PR adds string view support for `LEFT`, whose issue has not yet been filed.
Follow the model in #11955. Add string view support for `LEFT` and tests.
yes
no
=> Add native stringview support for LEFT

datafusion/functions/src/string/overlay.rs, datafusion/sqllogictest/test_files/functions.slt, datafusion/sqllogictest/test_files/string_view.slt
=> Implement native support StringView for overlay

datafusion/core/src/execution/session_state.rs
=> Keep the existing default catalog for `SessionStateBuilder::new_from_existing`

datafusion/core/tests/memory_limit/mod.rs, datafusion/execution/src/memory_pool/pool.rs, datafusion/execution/src/runtime_env.rs, datafusion/physical-plan/src/joins/cross_join.rs, datafusion/physical-plan/src/joins/hash_join.rs, datafusion/physical-plan/src/joins/nested_loop_join.rs
Closes #11523 
We would like the improved OOM error messages, which lists the top overall memory reservation consumers, to be the default.
Make `TrackConsumersPool` be the default.
Include benchmarks to assess potential performance overhead from added mutex.
Yes, for the existing tests using the default pool.
No API changes.
Change in OOM messages returned.
=> Use tracked-consumers memory pool be the default.

datafusion/functions/src/unicode/reverse.rs, datafusion/sqllogictest/test_files/functions.slt, datafusion/sqllogictest/test_files/string_view.slt
Closes #11915
Update reverse udf to support utf8view
code, tests
Yes
No
=> Update REVERSE scalar function to support Utf8View

datafusion/functions/src/unicode/translate.rs, datafusion/sqllogictest/test_files/string_view.slt
Closes #11953 
This will add StringView support for the TRANSLATE() function as part of the work to add complete StringView support in DataFusion, which permits potentially much faster processing of string data. See: https://github.com/apache/datafusion/issues/10918 for more background.
=> feat/11953: Support StringView for TRANSLATE() fn

datafusion/functions/src/string/split_part.rs, datafusion/sqllogictest/test_files/functions.slt, datafusion/sqllogictest/test_files/string_view.slt
=> Update SPLIT_PART scalar function to support Utf8View

datafusion/functions-aggregate/src/min_max.rs
Closes #12011.
Handles `min`/`max` args checking and throw error instead of crash.
Yes.
No.
=> Handle arguments checking of `min`/`max` function to avoid crashes

datafusion/expr-common/src/type_coercion/binary.rs, datafusion/physical-expr/src/expressions/binary.rs, datafusion/sqllogictest/test_files/regexp.slt
Related with #11623
Regular expression comparison operations accept NULL input, like
select 'abc' ~ null;
or
select null ~ null;
=> Fix: support NULL input for regular expression comparison operations

datafusion/core/src/dataframe/mod.rs, datafusion/physical-plan/src/windows/mod.rs
Closes #11981 
When performing a window function using a UDAF, which all of our aggregate functions are, causes an error in the physical plan. Specifically it generates a `SchemaError::FieldNotFound`. This *appears* to be because the `DFSchema` is empty in the minimal example showing in the bug report. However the ordering operation appears to already be handled by the window function call.
Removes the generation of the ordering and sorting, which are essentially duplicates of each other, and only leaves the ordering parameters on the window function definition.
All unit tests working.
The minimum demonstration of the error in the bug report now works.
Tested against my project where I initially discovered the problem.
None.
I must admit I don't fully understand the rationale behind …
=> Remove physical sort parameters on aggregate window functions

datafusion/common/src/scalar/mod.rs
Closes #.
Part of #11992
Since `ScalarValue::iter_to_array` is a widely used directly function, I think it makes sense to return execution error instead of internal error.
=> Minor: Use execution error in ScalarValue::iter_to_array for incorrect usage

datafusion/expr-common/src/type_coercion/binary.rs, datafusion/sqllogictest/test_files/regexp.slt
Closes #11872 
Support NULL input for like operations, such as
select null like null;
select null ilke null;
=> Fix: support NULL input for like operations

datafusion/sqllogictest/test_files/aggregate.slt
Related to https://github.com/apache/datafusion/issues/12011
Add test for check in https://github.com/apache/datafusion/pull/12016
Add slttest
All tests
=> Minor: Add error tests for min/max with 2 arguments

datafusion/functions-aggregate-common/src/aggregate/groups_accumulator/bool_op.rs, datafusion/functions-aggregate/src/bool_and_or.rs, datafusion/sqllogictest/test_files/aggregate.slt
Closes #11846.
The initial value of each group was set to `false`. When encountering the first non-null value of a certain group and performing the AND operation with the initial value, it resulted in an incorrect output.
We should set the initial value to the identity element.
Yes
No
=> fix: incorrect aggregation result of `bool_and`

datafusion/functions/Cargo.toml, datafusion/functions/benches/repeat.rs, datafusion/functions/src/string/common.rs, datafusion/functions/src/string/repeat.rs, datafusion/functions/src/unicode/lpad.rs, datafusion/functions/src/utils.rs
Closes #11990.
Refactor code and improve performance.
`repeat` function and benchmark.
Yes
No
______________
Benchmark stats on my local machine:
* AMD Ryzen 5 PRO 5650U (6 cores 12 threads) - 24Gb RAM
=> Improve performance of REPEAT functions

datafusion/functions/src/unicode/substr.rs, datafusion/sqllogictest/test_files/string_view.slt
=> Update SUBSTR scalar function to support Utf8View

datafusion/expr-common/src/accumulator.rs
I checked some `Accumulator` implementations, they all won't clear internal state after `evaluate` or `state` call.
=> Minor: Remove wrong comment on `Accumulator::evaluate` and `Accumulator::state`

.gitignore
Closes #.
While working on https://github.com/apache/datafusion/pull/12034 I noticed a bunch of stuff in .gitignore that was left over from when this code was pulled from the arrow monorepo: https://github.com/apache/arrow/blob/main/.gitignore
Remove the obviously irrelevant parts of .gitignore
I am sure there is more we could remove but this is an improvement already in my mind
Sort of by CI
No, this is entirely development process changes
=> Minor: cleanup `.gitignore`

datafusion/common/src/tree_node.rs, datafusion/core/src/datasource/physical_plan/parquet/mod.rs, datafusion/core/src/datasource/physical_plan/parquet/row_filter.rs
part of https://github.com/apache/datafusion/issues/4028
While reviewing this code with @itsjunetime, we discovered some interesting things that I would like to encode in comments.
1. Improve documentation in the row pushdown code
Yes, CI
Documentation change only (no functional changes)
Note most of the docs are internal (don't appear on docs.rs)
=> Improve documentation about `ParquetExec` / Parquet predicate pushdown
